// CDN configuration for static assets
// DiagramLibrary chunk is served from CDN for faster delivery and reduced main bundle size

const CDN_BASE = process.env.REACT_APP_CDN_BASE || "https://cdn.stellarlearn.com/assets";

// Asset manifest - maps chunk names to CDN paths
// Generated by deployment script during build
export const CDN_ASSETS = {
  diagramLibrary: {
    name: "DiagramLibrary",
    path: "diagramLibrary.js",
    size: "111.72 kB", // gzipped
    fallback: true, // use bundled version if CDN fails
  },
  mathText: {
    name: "MathText",
    path: "mathText.js",
    size: "78.10 kB", // gzipped
    fallback: true,
  },
  analytics: {
    name: "AnalyticsProView",
    path: "analyticsPro.js",
    size: "7.7 kB",
    fallback: true,
  },
};

// Check CDN availability via head request (non-blocking)
let cdnHealthy = true;
let cdnCheckTime = Date.now();

export async function isCdnAvailable() {
  // Cache result for 5 minutes to avoid hammering CDN health check
  if (Date.now() - cdnCheckTime < 5 * 60 * 1000) {
    return cdnHealthy;
  }

  try {
    const response = await fetch(`${CDN_BASE}/health`, {
      method: "HEAD",
      mode: "no-cors",
      cache: "no-cache",
    });
    cdnHealthy = response.ok || response.status === 0; // 0 for no-cors
    cdnCheckTime = Date.now();
  } catch (err) {
    cdnHealthy = false;
    cdnCheckTime = Date.now();
  }

  return cdnHealthy;
}

// Get CDN URL for an asset, with fallback to bundled version
export function getCdnUrl(assetKey) {
  const asset = CDN_ASSETS[assetKey];
  if (!asset) return null;

  // For now, return bundled URL until CDN is configured
  // When CDN is ready: return `${CDN_BASE}/${asset.path}`
  return null; // null = use bundled/dynamic import
}

export const CDN_CONFIG = {
  baseUrl: CDN_BASE,
  enabled: process.env.REACT_APP_CDN_ENABLED === "true",
  healthCheckInterval: 5 * 60 * 1000, // 5 minutes
  fallbackOnError: true, // Always fallback to bundled if CDN fails
};
