/**
 * enrichEnglish10.js — v3 enrichment for CBSE Class 10 English (First Flight,
 * Footprints Without Feet, Grammar & Writing units).
 *
 * The 35 `eng_*` topics already carry key_formulas + prerequisite_knowledge and
 * the core teaching_content (intuition / process_explanation / worked_example /
 * common_misconceptions / shortcuts_and_tricks / key_takeaway). They are MISSING
 * the 5 newer teaching_content fields that the Math v3 standard adds:
 *
 *   teaching_content: visual_description, svg_diagrams, when_to_use_this_method,
 *                     edge_cases, video_script_hooks
 *
 * Adapted for literature: svg_diagrams render theme/character/plot maps;
 * when_to_use_this_method is reframed as exam application; edge_cases are common
 * misreadings / exam traps. Uses dot-notation $set so existing keys are untouched.
 * Idempotent.
 *
 * Usage:  node config/enrichEnglish10.js
 * npm:    npm run enrich:english10
 */
import "dotenv/config";
import mongoose from "mongoose";
import { NcertTopicContent } from "../models/ncertTopicContentModel.js";

function svg(id, title, inner) {
  return { id, title, svg: `<svg viewBox="0 0 560 200" xmlns="http://www.w3.org/2000/svg" font-family="sans-serif" font-size="13">${inner}</svg>` };
}

const ENRICH = {
  // ── FIRST FLIGHT — Prose ───────────────────────────────────────────────────
  eng_ff_ch1_prose: {
    visual_description: "A plot-arc diagram tracing Lencho's story from the ruined cornfield through his letter to God to the postmaster's collection, ending on his bitter belief that the post office is full of crooks.",
    svg_diagrams: [svg("eng_ff_ch1_prose_diagram", "Faith vs Irony Arc", `<text x="20" y="26" font-weight="bold">A Letter to God — Faith Meets Irony</text><line x1="40" y1="150" x2="520" y2="150" stroke="#888"/><circle cx="90" cy="120" r="6" fill="#2a7"/><text x="60" y="170" font-size="11">Good harvest</text><circle cx="200" cy="100" r="6" fill="#c33"/><text x="165" y="95" font-size="11">Hailstorm ruins corn</text><circle cx="320" cy="110" r="6" fill="#36c"/><text x="285" y="180" font-size="11">Letter to God</text><circle cx="430" cy="95" r="6" fill="#e90"/><text x="380" y="90" font-size="11">Postmaster collects 70 pesos</text><text x="150" y="40" font-size="11">Faith unshaken</text><text x="350" y="50" font-size="11">Irony: thinks staff are "crooks"</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on unshakeable faith, the theme of human kindness vs divine reliance, situational irony, or characterising Lencho as simple but trusting", "Quote-based answers about 'a hundred pesos', 'God could not have made a mistake', and 'a bunch of crooks'"], use_other_when: ["Questions on overcoming fear or courage (use His First Flight, ch3)", "Questions on death and grief (use The Sermon at Benares, ch8)"] },
    edge_cases: [ { case: "Students assume the postmaster mocks or cheats Lencho", value: "The postmaster is moved by Lencho's faith and collects money from employees to help him", reasoning: "His act is one of charity to keep Lencho's faith alive, not deception", where_it_appears: "After Lencho's first letter reaches the post office" }, { case: "Students think Lencho is grateful when the money arrives", value: "Lencho is angry that only 70 of the 100 pesos came and blames the post-office employees as thieves", reasoning: "This is the central irony — the very people who helped are accused", where_it_appears: "Lencho's second letter to God" } ],
    video_script_hooks: { opening_hook: "A farmer watches a hailstorm flatten his only crop, then sits down and mails a letter — addressed to God.", concept_reveal: "The story shows that faith can be absolute and human kindness real, yet irony lies in how the helped man trusts heaven more than the people who actually saved him." },
  },
  eng_ff_ch2_prose: {
    visual_description: "A theme map radiating from Mandela's 1994 inauguration to the pillars of freedom, sacrifice, courage, and the end of apartheid.",
    svg_diagrams: [svg("eng_ff_ch2_prose_diagram", "Long Walk to Freedom Theme Map", `<text x="20" y="26" font-weight="bold">Nelson Mandela — Themes</text><rect x="220" y="80" width="130" height="34" rx="6" fill="#36c"/><text x="232" y="102" fill="#fff" font-size="12">Freedom</text><rect x="40" y="40" width="120" height="28" rx="6" fill="#eee"/><text x="50" y="59" font-size="11">Inauguration 1994</text><rect x="40" y="150" width="120" height="28" rx="6" fill="#eee"/><text x="50" y="169" font-size="11">End of apartheid</text><rect x="400" y="40" width="130" height="28" rx="6" fill="#eee"/><text x="410" y="59" font-size="11">Courage &amp; sacrifice</text><rect x="400" y="150" width="130" height="28" rx="6" fill="#eee"/><text x="410" y="169" font-size="11">Oppressor freed too</text><line x1="160" y1="54" x2="220" y2="92" stroke="#888"/><line x1="160" y1="164" x2="220" y2="108" stroke="#888"/><line x1="350" y1="92" x2="400" y2="54" stroke="#888"/><line x1="350" y1="100" x2="400" y2="164" stroke="#888"/>`)],
    when_to_use_this_method: { use_this_when: ["Questions on freedom, apartheid, courage, sacrifice of patriots, or Mandela's view that the oppressor must also be liberated", "Quote answers on 'courage was not the absence of fear but the triumph over it' and 'twin obligations'"], use_other_when: ["Questions on personal childhood adventure (use Madam Rides the Bus, ch7)", "Questions on diarised personal feelings under persecution (use Anne Frank, ch4)"] },
    edge_cases: [ { case: "Students think freedom for Mandela meant only freedom of black South Africans", value: "Mandela believed the oppressor must be liberated too, since a man who takes away another's freedom is a prisoner of hatred", reasoning: "His vision of freedom is mutual and reconciliatory, not vengeful", where_it_appears: "Mandela's reflection near the end of the extract" }, { case: "Students define courage as fearlessness", value: "Mandela defines courage as the triumph over fear, not the absence of fear", reasoning: "Brave men feel fear but conquer it", where_it_appears: "His tribute to the freedom fighters" } ],
    video_script_hooks: { opening_hook: "For decades he was a prisoner; on one morning in 1994 he stood as the first black President of a free South Africa.", concept_reveal: "Mandela teaches that true freedom liberates both the oppressed and the oppressor, and that courage means conquering fear rather than never feeling it." },
  },
  eng_ff_ch3_prose: {
    visual_description: "A split diagram contrasting the young seagull conquering his fear of flight with the pilot trusting a mysterious aeroplane through the storm.",
    svg_diagrams: [svg("eng_ff_ch3_prose_diagram", "Two Stories about Flying", `<text x="20" y="26" font-weight="bold">Two Stories about Flying</text><line x1="280" y1="40" x2="280" y2="190" stroke="#888"/><text x="40" y="56" font-weight="bold" font-size="12">I: His First Flight</text><text x="40" y="80" font-size="11">Seagull afraid of the sea</text><text x="40" y="104" font-size="11">Hunger + family coax him</text><text x="40" y="128" font-size="11">Dives, then flies!</text><text x="40" y="152" font-size="11">Theme: courage over fear</text><text x="300" y="56" font-weight="bold" font-size="12">II: The Black Aeroplane</text><text x="300" y="80" font-size="11">Pilot in storm clouds</text><text x="300" y="104" font-size="11">Mysterious plane guides him</text><text x="300" y="128" font-size="11">Lands safely, woman puzzled</text><text x="300" y="152" font-size="11">Theme: faith / the unexplained</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on overcoming fear, courage, and growth (Part I) or mystery, helplessness, and the unexplained guide (Part II)", "Character answers on the young seagull's family and the narrator-pilot"], use_other_when: ["Questions on faith in God through a letter (use A Letter to God, ch1)", "Questions on a child's first journey alone (use Madam Rides the Bus, ch7)"] },
    edge_cases: [ { case: "Students think the seagull is pushed off the cliff by force", value: "He flies only when hunger and the sight of his mother with food make him dive, then his wings catch the air", reasoning: "The first flight comes from necessity and his own instinct, not from being shoved", where_it_appears: "Climax of His First Flight" }, { case: "Students treat the black aeroplane's pilot as a known rescuer", value: "The guiding pilot is never identified; the woman in the control room says no other plane was on the radar", reasoning: "The mystery is deliberately left unexplained, suggesting a guardian or inner faith", where_it_appears: "Ending of The Black Aeroplane" } ],
    video_script_hooks: { opening_hook: "One creature is terrified to leave a cliff ledge; one pilot is desperate to leave a storm — both must trust the sky.", concept_reveal: "Together the two stories show that flight, real or symbolic, demands conquering fear and trusting forces we cannot always explain." },
  },
  eng_ff_ch4_prose: {
    visual_description: "A character web around Anne Frank linking her diary 'Kitty', her teacher Mr Keesing, and the looming threat of Nazi persecution in hiding.",
    svg_diagrams: [svg("eng_ff_ch4_prose_diagram", "Anne Frank's World", `<text x="20" y="26" font-weight="bold">From the Diary of Anne Frank</text><circle cx="280" cy="110" r="34" fill="#e90"/><text x="258" y="114" fill="#fff" font-size="12">Anne</text><rect x="60" y="50" width="110" height="28" rx="6" fill="#eee"/><text x="70" y="69" font-size="11">"Kitty" (diary)</text><rect x="60" y="160" width="120" height="28" rx="6" fill="#eee"/><text x="70" y="179" font-size="11">Mr Keesing (teacher)</text><rect x="400" y="50" width="130" height="28" rx="6" fill="#eee"/><text x="410" y="69" font-size="11">Family in hiding</text><rect x="400" y="160" width="130" height="28" rx="6" fill="#eee"/><text x="410" y="179" font-size="11">Nazi threat / WWII</text><line x1="170" y1="64" x2="250" y2="100" stroke="#888"/><line x1="180" y1="174" x2="252" y2="124" stroke="#888"/><line x1="314" y1="100" x2="400" y2="64" stroke="#888"/><line x1="314" y1="124" x2="400" y2="174" stroke="#888"/>`)],
    when_to_use_this_method: { use_this_when: ["Questions on the diary as a confidant, loneliness, Anne's wit with Mr Keesing, or the human face of the Holocaust", "Answers on why she names her diary 'Kitty' and treats it as a true friend"], use_other_when: ["Questions on public political freedom (use Mandela, ch2)", "Questions on a humorous courtship quarrel (use The Proposal, ch9)"] },
    edge_cases: [ { case: "Students think Anne hates Mr Keesing throughout", value: "She resents his punishment essays at first but wins him over with her witty essay 'A Chatterbox', and he ends up amused", reasoning: "The episode shows her humour and his fairness, not lasting enmity", where_it_appears: "The three essays Mr Keesing sets her" }, { case: "Students treat Kitty as a real person Anne writes to", value: "Kitty is the name Anne gives her diary; she addresses entries to it as an imaginary friend because she feels no real friend understands her", reasoning: "It reveals her deep loneliness, not an actual correspondent", where_it_appears: "Opening of her diary entries" } ],
    video_script_hooks: { opening_hook: "A thirteen-year-old, hiding from soldiers who want her dead, opens a notebook and writes, 'I hope I will be able to confide everything to you.'", concept_reveal: "Anne's diary turns a paper friend named Kitty into a window onto loneliness, courage, and the everyday humanity crushed by the Holocaust." },
  },
  eng_ff_ch5_prose: {
    visual_description: "A three-part theme map for the travelogue: the Goan baker's nostalgia, Coorg's brave warrior land, and Assam's tea heritage.",
    svg_diagrams: [svg("eng_ff_ch5_prose_diagram", "Glimpses of India", `<text x="20" y="26" font-weight="bold">Glimpses of India — Three Places</text><rect x="30" y="60" width="150" height="100" rx="8" fill="#fde"/><text x="42" y="84" font-weight="bold" font-size="12">I: Baker from Goa</text><text x="42" y="108" font-size="11">Portuguese legacy</text><text x="42" y="128" font-size="11">Nostalgia, "pader"</text><rect x="205" y="60" width="150" height="100" rx="8" fill="#dfe"/><text x="217" y="84" font-weight="bold" font-size="12">II: Coorg</text><text x="217" y="108" font-size="11">Warrior race, coffee</text><text x="217" y="128" font-size="11">Rivers, valour, faith</text><rect x="380" y="60" width="150" height="100" rx="8" fill="#def"/><text x="392" y="84" font-weight="bold" font-size="12">III: Tea from Assam</text><text x="392" y="108" font-size="11">Legend of tea origin</text><text x="392" y="128" font-size="11">Largest tea region</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on the diversity of India, cultural heritage, nostalgia for the Goan baker, the valour of Coorg, or the legends and importance of Assam tea", "Answers requiring details of each of the three sub-sections"], use_other_when: ["Questions on a single emotional human story (use any narrative prose like ch1 or ch7)", "Questions on a wild-animal companion (use Mijbil the Otter, ch6)"] },
    edge_cases: [ { case: "Students treat 'Glimpses of India' as one continuous story", value: "It is three separate pieces by different writers — A Baker from Goa, Coorg, and Tea from Assam", reasoning: "Each has its own setting, author, and focus, united only by the theme of India's diversity", where_it_appears: "The three titled sub-sections" }, { case: "Students say the Goan baker has disappeared", value: "The traditional baker (pader) and the profession still survive in Goa, kept alive by nostalgia and demand", reasoning: "The narrator stresses that bakers are still very much present", where_it_appears: "A Baker from Goa" } ],
    video_script_hooks: { opening_hook: "From the jingle of a Goan baker's bamboo to the warrior hills of Coorg and the tea gardens of Assam — one chapter, three Indias.", concept_reveal: "The travelogue celebrates India's astonishing diversity through small, sensory glimpses of place, tradition, and legend." },
  },
  eng_ff_ch6_prose: {
    visual_description: "A character web around Gavin Maxwell and his playful otter Mijbil, tracing the otter's habits and the journey from Iraq to a London flat.",
    svg_diagrams: [svg("eng_ff_ch6_prose_diagram", "Maxwell and Mijbil", `<text x="20" y="26" font-weight="bold">Mijbil the Otter</text><circle cx="160" cy="110" r="32" fill="#36c"/><text x="138" y="114" fill="#fff" font-size="12">Maxwell</text><circle cx="400" cy="110" r="32" fill="#2a7"/><text x="378" y="114" fill="#fff" font-size="12">Mijbil</text><line x1="192" y1="110" x2="368" y2="110" stroke="#888"/><text x="250" y="100" font-size="11">cares for / pet</text><rect x="40" y="160" width="150" height="28" rx="6" fill="#eee"/><text x="50" y="179" font-size="11">From Iraq to London</text><rect x="360" y="40" width="160" height="28" rx="6" fill="#eee"/><text x="370" y="59" font-size="11">Playful, mischievous</text><rect x="360" y="160" width="160" height="28" rx="6" fill="#eee"/><text x="370" y="179" font-size="11">Loves water, marbles</text><line x1="400" y1="78" x2="430" y2="68" stroke="#888"/><line x1="400" y1="142" x2="430" y2="160" stroke="#888"/>`)],
    when_to_use_this_method: { use_this_when: ["Questions on the bond between humans and animals, the otter's playful and mischievous nature, or the difficulties of transporting Mij to England", "Character answers describing Mijbil's antics with water, marbles, and the airline box"], use_other_when: ["Questions on human courage facing fear (use His First Flight, ch3)", "Questions on cultural travelogue of places (use Glimpses of India, ch5)"] },
    edge_cases: [ { case: "Students think Mijbil is a common, easily identified otter species", value: "Mij was a previously unknown subspecies, later named Maxwell's otter (Lutrogale perspicillata maxwelli) after the author", reasoning: "Its scientific novelty is a key detail of the text", where_it_appears: "Maxwell's description after acquiring the otter" }, { case: "Students think the flight to London was smooth", value: "The journey was troublesome — Mij escaped his box, caused chaos on the plane, and an air hostess helped Maxwell keep him on his lap", reasoning: "The travel difficulties highlight both the otter's restlessness and Maxwell's devotion", where_it_appears: "The journey from Iraq to England" } ],
    video_script_hooks: { opening_hook: "A grieving man in Iraq is handed a wriggling otter — and his quiet London flat will never be the same.", concept_reveal: "The memoir captures the deep, comic, demanding bond between a human and a wild animal whose playful nature reshapes its owner's life." },
  },
  eng_ff_ch7_prose: {
    visual_description: "A plot-arc diagram following eight-year-old Valli's secret solo bus ride into town and back, marking the cow that turns her excitement into a glimpse of life and death.",
    svg_diagrams: [svg("eng_ff_ch7_prose_diagram", "Valli's Bus Journey Arc", `<text x="20" y="26" font-weight="bold">Madam Rides the Bus — Valli's Arc</text><line x1="40" y1="150" x2="520" y2="150" stroke="#888"/><circle cx="80" cy="130" r="6" fill="#2a7"/><text x="55" y="172" font-size="11">Saves fare</text><circle cx="190" cy="110" r="6" fill="#36c"/><text x="160" y="100" font-size="11">Secret ride</text><circle cx="300" cy="100" r="6" fill="#e90"/><text x="270" y="90" font-size="11">Sees town, refuses drink</text><circle cx="410" cy="120" r="6" fill="#c33"/><text x="365" y="180" font-size="11">Dead cow on return</text><circle cx="500" cy="135" r="6" fill="#888"/><text x="460" y="178" font-size="11">Home, secret kept</text><text x="240" y="50" font-size="11">Curiosity to growing up / mortality</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on childhood curiosity, independence, the desire to grow up, and the sobering encounter with death (the cow)", "Character answers on Valli's confidence, self-respect (refusing the conductor's kindness), and secrecy"], use_other_when: ["Questions on adult political freedom (use Mandela, ch2)", "Questions on human-animal companionship (use Mijbil, ch6)"] },
    edge_cases: [ { case: "Students think Valli is poor and steals or begs the fare", value: "She carefully saves her own money by resisting fairs, toys, and treats over time to afford the thirty-paise ride", reasoning: "Her self-denial shows discipline and pride, not desperation", where_it_appears: "Early description of how Valli funds the trip" }, { case: "Students miss the significance of the dead cow", value: "The same cow Valli had cheerfully seen alive earlier lies dead on the return trip, jolting her joyful adventure into an awareness of death", reasoning: "It marks her movement from childish excitement to a more mature understanding of life", where_it_appears: "Valli's return journey" } ],
    video_script_hooks: { opening_hook: "An eight-year-old saves every coin for one forbidden thrill — riding the town bus all by herself.", concept_reveal: "Valli's small adventure becomes a story of independence and curiosity that quietly collides with the reality of death and growing up." },
  },
  eng_ff_ch8_prose: {
    visual_description: "A theme map of the Buddha's sermon: Kisa Gotami's grief, the impossible search for a mustard seed from a death-free house, and the lesson that death is universal.",
    svg_diagrams: [svg("eng_ff_ch8_prose_diagram", "The Sermon at Benares", `<text x="20" y="26" font-weight="bold">The Sermon at Benares</text><rect x="210" y="80" width="150" height="34" rx="6" fill="#a63"/><text x="220" y="102" fill="#fff" font-size="12">Death is universal</text><rect x="40" y="50" width="130" height="28" rx="6" fill="#eee"/><text x="50" y="69" font-size="11">Kisa Gotami's grief</text><rect x="40" y="150" width="150" height="28" rx="6" fill="#eee"/><text x="50" y="169" font-size="11">Seeks mustard seed</text><rect x="400" y="50" width="140" height="28" rx="6" fill="#eee"/><text x="410" y="69" font-size="11">No death-free house</text><rect x="400" y="150" width="140" height="28" rx="6" fill="#eee"/><text x="410" y="169" font-size="11">Acceptance &amp; peace</text><line x1="170" y1="64" x2="210" y2="92" stroke="#888"/><line x1="190" y1="164" x2="210" y2="108" stroke="#888"/><line x1="360" y1="92" x2="400" y2="64" stroke="#888"/><line x1="360" y1="100" x2="400" y2="164" stroke="#888"/>`)],
    when_to_use_this_method: { use_this_when: ["Questions on the inevitability of death, overcoming grief, the Buddha's teaching method (parable of the mustard seed), and Kisa Gotami's transformation", "Quote answers on 'the world is afflicted with death and decay' and selfless wisdom"], use_other_when: ["Questions on childhood adventure (use Madam Rides the Bus, ch7)", "Questions on faith answered through material help (use A Letter to God, ch1)"] },
    edge_cases: [ { case: "Students think the Buddha gives Kisa Gotami medicine to revive her son", value: "He asks her to fetch a handful of mustard seed — but only from a house where no one has ever died", reasoning: "The impossible condition is a teaching device, not a cure", where_it_appears: "The Buddha's response to her plea" }, { case: "Students think Kisa Gotami finds the seed and fails by chance", value: "She finds mustard seed in every house but learns the living are few and the dead are many, so no house qualifies", reasoning: "The search itself teaches her that death spares no family, leading to acceptance", where_it_appears: "Her journey from house to house" } ],
    video_script_hooks: { opening_hook: "A mother carries her dead child from door to door, begging for a medicine — until the Buddha sends her to find a single mustard seed.", concept_reveal: "The sermon teaches that death comes to every household, and peace lies not in escaping grief but in accepting that loss is universal." },
  },
  eng_ff_ch9_prose: {
    visual_description: "A character web of Chekhov's farce showing Lomov's proposal to Natalya undone by absurd quarrels over Oxen Meadows and the rival dogs Squeezer and Guess, with Chubukov caught between them.",
    svg_diagrams: [svg("eng_ff_ch9_prose_diagram", "The Proposal — Quarrel Web", `<text x="20" y="26" font-weight="bold">The Proposal — A One-Act Farce</text><circle cx="150" cy="110" r="30" fill="#36c"/><text x="130" y="114" fill="#fff" font-size="12">Lomov</text><circle cx="410" cy="110" r="30" fill="#c39"/><text x="385" y="114" fill="#fff" font-size="12">Natalya</text><circle cx="280" cy="50" r="26" fill="#888"/><text x="256" y="54" fill="#fff" font-size="11">Chubukov</text><line x1="180" y1="110" x2="380" y2="110" stroke="#888"/><text x="225" y="100" font-size="11">proposal to quarrels</text><line x1="170" y1="84" x2="262" y2="62" stroke="#888"/><line x1="392" y1="84" x2="300" y2="62" stroke="#888"/><rect x="60" y="160" width="170" height="28" rx="6" fill="#eee"/><text x="70" y="179" font-size="11">Fight 1: Oxen Meadows</text><rect x="330" y="160" width="200" height="28" rx="6" fill="#eee"/><text x="340" y="179" font-size="11">Fight 2: Squeezer vs Guess</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on farce and humour, the satire of marriage as a property deal, quarrelsome characters, and dramatic irony", "Answers on how trivial disputes (land and dogs) keep derailing Lomov's actual proposal"], use_other_when: ["Questions on a serious moral or spiritual lesson (use The Sermon at Benares, ch8)", "Questions on a real personal diary (use Anne Frank, ch4)"] },
    edge_cases: [ { case: "Students think Lomov and Natalya marry out of love", value: "The proposal is driven by convenience — land, money, and Lomov's age and ill health — and they keep quarrelling even as Chubukov joins their hands", reasoning: "Chekhov satirises marriage as a practical contract, not romance", where_it_appears: "Throughout the one-act play" }, { case: "Students think the quarrels are resolved before the engagement", value: "They are never truly settled; Chubukov forces the union while Lomov and Natalya are still arguing over whose dog is better", reasoning: "The unresolved bickering is the comic point — the marriage begins mid-fight", where_it_appears: "The play's final scene" } ],
    video_script_hooks: { opening_hook: "A nervous bachelor finally arrives to propose marriage — and within minutes is screaming about a meadow and whose hunting dog is faster.", concept_reveal: "Chekhov's farce mocks marriage as a property bargain, where petty pride over land and dogs matters more to the couple than love itself." },
  },

  // ── FIRST FLIGHT — Poems ───────────────────────────────────────────────────
  eng_ff_ch1_poem: {
    visual_description: "A split theme map: left side shows a crow dusting snow from a hemlock tree onto a speaker (mood shifting from gloom to relief in 'Dust of Snow'); right side contrasts fire (desire) versus ice (hatred) as two symbolic ways the world could end in 'Fire and Ice'.",
    svg_diagrams: [svg("eng_ff_ch1_poem_diagram", "Frost: Mood Change & Fire vs Ice", `<text x="20" y="26" font-weight="bold">Robert Frost — Two Short Poems</text><line x1="280" y1="40" x2="280" y2="190" stroke="#555"/><text x="20" y="60" font-weight="bold">Dust of Snow</text><circle cx="60" cy="90" r="8" fill="#222"/><text x="78" y="94">crow shakes snow</text><polygon points="55,150 75,150 65,120" fill="#2e7d32"/><text x="85" y="150">hemlock tree</text><text x="20" y="178">gloom to relief (mood heals)</text><text x="300" y="60" font-weight="bold">Fire and Ice</text><text x="300" y="92">Fire = desire</text><circle cx="520" cy="86" r="10" fill="#e53935"/><text x="300" y="124">Ice = hatred</text><circle cx="520" cy="118" r="10" fill="#42a5f5"/><text x="300" y="170">Both can end the world</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on how a small natural moment (a crow, snow) can transform a person's mood — nature as a healer in 'Dust of Snow'", "Questions on symbolism of fire and ice as human emotions (desire vs hatred) and the apocalyptic theme of how the world may end", "Questions naming poetic devices: metaphor, symbolism, alliteration ('Dust of snow'), and the rhyme scheme"], use_other_when: ["Questions about a caged animal's loss of freedom (use 'A Tiger in the Zoo')", "Questions about imagination as escape from control (use 'Amanda!')"] },
    edge_cases: [ { case: "Reading 'Dust of Snow' as merely a literal description of weather", value: "It is symbolic — the crow and hemlock (usually negative/poisonous omens) ironically bring a healing change of mood, showing nature can lift gloom", reasoning: "Frost deliberately picks gloomy images to show even these can restore a person's spirit", where_it_appears: "Whole of 'Dust of Snow'" }, { case: "Thinking fire and ice are only about literal climate or the planet's destruction", value: "Fire symbolises desire/greed and ice symbolises hatred/coldness — both human emotions powerful enough to destroy the world", reasoning: "Frost uses the natural elements as metaphors for destructive human passions", where_it_appears: "'Fire and Ice'" } ],
    video_script_hooks: { opening_hook: "A single crow shakes loose a sprinkle of snow — and somehow a bad day is saved. Then Frost asks: will the world die in fire, or in ice?", concept_reveal: "Both poems show emotion through nature: a tiny moment can heal a mood, while desire (fire) and hatred (ice) are powerful enough to end everything." },
  },
  eng_ff_ch2_poem: {
    visual_description: "A contrast chart with two panels: a tiger pacing behind cage bars (helpless rage) beside a free tiger sliding through long grass and lurking near the village — highlighting the loss of freedom.",
    svg_diagrams: [svg("eng_ff_ch2_poem_diagram", "A Tiger in the Zoo — Caged vs Free", `<text x="20" y="26" font-weight="bold">Leslie Norris — Caged vs Free Tiger</text><rect x="30" y="50" width="200" height="120" fill="none" stroke="#555"/><line x1="70" y1="50" x2="70" y2="170" stroke="#555"/><line x1="110" y1="50" x2="110" y2="170" stroke="#555"/><line x1="150" y1="50" x2="150" y2="170" stroke="#555"/><line x1="190" y1="50" x2="190" y2="170" stroke="#555"/><polygon points="90,140 150,140 120,110" fill="#ef6c00"/><text x="60" y="190">Caged: rage, pacing, helpless</text><text x="330" y="44" font-weight="bold">Free</text><polygon points="360,150 470,150 415,100" fill="#ef6c00"/><line x1="320" y1="160" x2="540" y2="160" stroke="#2e7d32"/><text x="320" y="184">long grass, lurking, sliding</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on the loss of freedom and the cruelty of confining wild animals in zoos", "Questions built on the contrast between the caged tiger and what the tiger would do in the wild", "Questions on poetic devices: imagery, metaphor, personification, and the tiger's 'quiet rage' and 'brilliant eyes'"], use_other_when: ["Questions on humour in describing animals (use 'How to Tell Wild Animals')", "Questions on the theme of how the world will end (use 'Fire and Ice')"] },
    edge_cases: [ { case: "Reading the tiger's quietness as calmness or contentment", value: "The 'quiet rage' shows suppressed fury and helplessness, not peace — the tiger is frustrated by captivity", reasoning: "Norris contrasts the tiger's stillness with the violent freedom it is denied", where_it_appears: "'He stalks... in quiet rage' / 'few steps of his cage'" } ],
    video_script_hooks: { opening_hook: "A tiger paces a tiny cage in 'quiet rage' while, somewhere, it could be sliding through long grass toward a watering hole.", concept_reveal: "Through sharp contrast, Norris shows that a wild animal locked in a zoo has lost its freedom, dignity, and very nature." },
  },
  eng_ff_ch3_poem: {
    visual_description: "A two-part chart: top half a humorous identification key for wild animals from 'How to Tell Wild Animals'; bottom half a boy watching his ball bounce into the harbour water, learning loss in 'The Ball Poem'.",
    svg_diagrams: [svg("eng_ff_ch3_poem_diagram", "Wild Animals (humour) & The Ball Poem (loss)", `<text x="20" y="24" font-weight="bold">Two Poems: Humour &amp; Loss</text><text x="20" y="52" font-weight="bold">How to Tell Wild Animals</text><polygon points="40,90 100,90 70,64" fill="#fbc02d"/><text x="110" y="86">Lion: large &amp; tawny (humour)</text><text x="20" y="116">comic, mock-instructional tone</text><line x1="20" y1="128" x2="540" y2="128" stroke="#999"/><text x="20" y="150" font-weight="bold">The Ball Poem</text><circle cx="60" cy="176" r="8" fill="#e53935"/><line x1="120" y1="190" x2="540" y2="190" stroke="#1565c0"/><text x="80" y="180">ball lost in water = grief &amp; growing up</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on humour, comic verse, and the mock how-to tone in 'How to Tell Wild Animals' (puns, exaggeration, rhyme)", "Questions on loss, the responsibility of possession, and growing up / coming to terms with grief in 'The Ball Poem'", "Questions on poetic devices: alliteration, internal rhyme, and metaphor (the ball as childhood/innocence)"], use_other_when: ["Questions on a single caged animal's loss of freedom (use 'A Tiger in the Zoo')", "Questions on imagination as escape (use 'Amanda!')"] },
    edge_cases: [ { case: "Reading 'The Ball Poem' as being literally about a lost toy worth replacing", value: "The ball symbolises childhood/innocence and first experiences of loss; the point is the boy must learn 'the epistemology of loss', not buy a new ball", reasoning: "Berryman refuses to offer money for another ball because the lesson is about coping with grief, not the object", where_it_appears: "'No use to say \"O there are other balls\"' / 'He is learning... how to stand up'" }, { case: "Taking the advice in 'How to Tell Wild Animals' as serious zoology", value: "It is deliberately absurd and humorous — the 'advice' is comically dangerous, used for comic effect", reasoning: "Carolyn Wells writes light, comic verse, not a real guide", where_it_appears: "'A novice might nonplus' / the playful animal descriptions" } ],
    video_script_hooks: { opening_hook: "First, a hilarious 'guide' to identifying a lion by letting it eat you — then a small boy watches his ball bounce, once, into the harbour, gone forever.", concept_reveal: "One poem laughs through clever comic verse; the other quietly teaches that loss is part of growing up and learning responsibility." },
  },
  eng_ff_ch4_poem: {
    visual_description: "A theme map of a nagged child: the parent's constant instructions in the centre, with Amanda's three imaginative escapes branching out — a mermaid in a silent sea, an orphan roaming free, and Rapunzel in a tower.",
    svg_diagrams: [svg("eng_ff_ch4_poem_diagram", "Amanda! — Control vs Imagination", `<text x="20" y="26" font-weight="bold">Robin Klein — Amanda!</text><rect x="200" y="44" width="170" height="40" fill="none" stroke="#c62828"/><text x="212" y="69">Parent's nagging (control)</text><text x="20" y="120" font-weight="bold">Amanda escapes into:</text><line x1="285" y1="124" x2="540" y2="86" stroke="#1565c0"/><line x1="285" y1="124" x2="60" y2="160" stroke="#1565c0"/><line x1="285" y1="124" x2="540" y2="160" stroke="#1565c0"/><text x="30" y="180">mermaid (silent sea)</text><text x="220" y="180">orphan (roaming free)</text><text x="420" y="180">Rapunzel (tower)</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on the conflict between parental control/nagging and a child's longing for freedom", "Questions on how a child uses imagination and fantasy (mermaid, orphan, Rapunzel) to escape constant instruction", "Questions on poetic devices: imagery, allusion (Rapunzel), and the use of italics to show Amanda's daydreams"], use_other_when: ["Questions on a wild animal's loss of freedom (use 'A Tiger in the Zoo')", "Questions on nature gaining freedom by moving out (use 'The Trees')"] },
    edge_cases: [ { case: "Blaming Amanda as a sulky, disobedient child", value: "The poem criticises the relentless, suffocating nagging; Amanda's silence and fantasies are her coping response to over-control", reasoning: "Klein contrasts the parent's harsh demands with the freedom of Amanda's imagined worlds to evoke sympathy for the child", where_it_appears: "Italicised stanzas (mermaid/orphan/Rapunzel) vs the parent's commands" } ],
    video_script_hooks: { opening_hook: "Stop biting your nails. Sit up straight. Don't slouch. As the orders pile up, Amanda quietly slips away — into a silent green sea.", concept_reveal: "Klein shows a child smothered by constant nagging, escaping through imagination into freedom — a gentle cry against over-controlling adults." },
  },
  eng_ff_ch5_poem: {
    visual_description: "A symbolism map showing trees uprooting from inside a house and moving out toward a forest under the moon at night — arrows from indoor confinement to outdoor freedom, glossed as nature reclaiming itself and women's liberation.",
    svg_diagrams: [svg("eng_ff_ch5_poem_diagram", "The Trees — From House to Forest", `<text x="20" y="26" font-weight="bold">Adrienne Rich — The Trees</text><rect x="40" y="60" width="150" height="110" fill="none" stroke="#555"/><text x="60" y="50">House (confinement)</text><polygon points="80,150 130,150 105,110" fill="#2e7d32"/><line x1="200" y1="120" x2="360" y2="120" stroke="#1565c0" stroke-width="2"/><polygon points="350,118 360,120 350,122" fill="#1565c0"/><text x="210" y="112">trees move out</text><polygon points="420,150 470,150 445,100" fill="#2e7d32"/><polygon points="480,150 530,150 505,110" fill="#2e7d32"/><text x="410" y="50">Forest (freedom)</text><circle cx="500" cy="60" r="10" fill="#fdd835"/><text x="410" y="184">night, moon</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on symbolism: trees standing for nature breaking free, and (in many readings) women's liberation from domestic confinement", "Questions on the contrast between the artificial indoors and the natural outdoors, and humans being out of touch with nature", "Questions on poetic devices: extended metaphor, imagery, personification of the trees, and enjambment"], use_other_when: ["Questions on a literal extended metaphor of one object only (use 'Fog' — fog as a cat)", "Questions on a child's imaginative escape (use 'Amanda!')"] },
    edge_cases: [ { case: "Reading the poem literally as houseplants being moved outside", value: "The trees are symbolic — of nature reasserting freedom and, in feminist readings, of women breaking out of confined domestic roles", reasoning: "Rich uses the trees' movement as an extended metaphor for liberation, not a literal gardening event", where_it_appears: "'The trees inside are moving out into the forest'" } ],
    video_script_hooks: { opening_hook: "All night, inside a quiet house, the trees are pulling free of the walls and walking out into the forest under the moon.", concept_reveal: "Rich's trees are a metaphor for liberation — nature reclaiming its place, and, read another way, women breaking free of confinement." },
  },
  eng_ff_ch6_poem: {
    visual_description: "An extended-metaphor diagram: fog drawn as a cat — arriving on 'little cat feet', sitting silent on 'haunches' overlooking the harbour and city, then moving on — illustrating the single sustained comparison and vivid imagery.",
    svg_diagrams: [svg("eng_ff_ch6_poem_diagram", "Fog — Extended Metaphor (fog = cat)", `<text x="20" y="26" font-weight="bold">Carl Sandburg — Fog as a Cat</text><ellipse cx="150" cy="120" rx="70" ry="40" fill="#b0bec5"/><circle cx="120" cy="95" r="6" fill="#37474f"/><circle cx="150" cy="95" r="6" fill="#37474f"/><polygon points="110,70 120,90 100,90" fill="#90a4ae"/><polygon points="180,70 190,90 170,90" fill="#90a4ae"/><text x="60" y="180">on little cat feet, silent haunches</text><line x1="300" y1="150" x2="540" y2="150" stroke="#1565c0"/><rect x="320" y="100" width="30" height="50" fill="#90a4ae"/><rect x="370" y="80" width="30" height="70" fill="#90a4ae"/><text x="320" y="80">harbour &amp; city below</text><text x="300" y="184">sits, looks, then moves on</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on the extended metaphor where fog is compared to a cat throughout the whole poem", "Questions on imagery, personification, and the quiet, fleeting nature of fog over a harbour and city", "Questions naming devices: metaphor, personification, and the brevity/free verse of the poem"], use_other_when: ["Questions on contrasting caged vs free states (use 'A Tiger in the Zoo')", "Questions on symbolism of trees and liberation (use 'The Trees')"] },
    edge_cases: [ { case: "Calling the fog-cat comparison a simile", value: "It is a metaphor (an extended/sustained metaphor) — fog is the cat, never said to be 'like' a cat", reasoning: "Sandburg never uses 'like' or 'as'; the entire poem identifies fog with a cat", where_it_appears: "'The fog comes on little cat feet' through 'and then moves on'" } ],
    video_script_hooks: { opening_hook: "The fog doesn't roll in — it pads in on little cat feet, sits silently over the harbour, and then, without a sound, moves on.", concept_reveal: "In just six lines, Sandburg builds one extended metaphor — fog as a silent cat — to capture how mist quietly arrives and slips away." },
  },
  eng_ff_ch7_poem: {
    visual_description: "A ballad scene chart: Belinda's house with her brave-seeming pets versus Custard the dragon who cries for a 'nice safe cage' — yet when the pirate appears, the 'coward' dragon is the one who fights, an ironic reversal.",
    svg_diagrams: [svg("eng_ff_ch7_poem_diagram", "Custard the Dragon — Irony of the 'Coward'", `<text x="20" y="24" font-weight="bold">Ogden Nash — Custard the Dragon (ballad)</text><text x="20" y="52">Belinda &amp; pets: 'brave' but flee</text><circle cx="50" cy="80" r="8" fill="#212121"/><text x="68" y="84">kitten</text><circle cx="150" cy="80" r="8" fill="#9e9e9e"/><text x="168" y="84">mouse</text><polygon points="250,88 280,88 265,70" fill="#fbc02d"/><text x="290" y="84">dog</text><text x="20" y="120">Custard: cries for a safe cage (mocked)</text><polygon points="60,150 120,150 90,128" fill="#2e7d32"/><text x="130" y="148">dragon</text><text x="20" y="184" font-weight="bold">Pirate comes: Custard fights &amp; wins (irony)</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on irony — the supposed 'coward' Custard turns out to be the bravest, while the boastful pets run and hide", "Questions on the ballad form, humour, and rhyme/refrain in the poem", "Questions on poetic devices: irony, humour, imagery, alliteration, and the mock-heroic tone"], use_other_when: ["Questions on a serious loss of freedom (use 'A Tiger in the Zoo')", "Questions on a single quiet extended metaphor (use 'Fog')"] },
    edge_cases: [ { case: "Believing Custard really is the coward the poem keeps calling him", value: "It is ironic — Custard, mocked as cowardly, is the only one brave enough to fight and kill the pirate; the boastful pets hide", reasoning: "Nash uses situational irony for humour: the 'bravest' are cowards and the 'coward' is the hero", where_it_appears: "When the pirate appears: pets flee, 'Custard gobbled up the pirate'" } ],
    video_script_hooks: { opening_hook: "Belinda's kitten, mouse and dog all brag they're fierce — and Custard the dragon just begs for a nice safe cage. Then a pirate climbs through the window.", concept_reveal: "In this funny ballad, Nash flips expectations: the mocked 'coward' dragon is the true hero, while the loud boasters run — a lesson in irony and real courage." },
  },
  eng_ff_ch8_poem: {
    visual_description: "A theme map contrasting outward beauty (a woman's 'great honey-coloured ramparts' of yellow hair) with inner self/true love — arrows showing that love based on hair colour is false, and only one 'old religious man' could love for the self alone.",
    svg_diagrams: [svg("eng_ff_ch8_poem_diagram", "For Anne Gregory — Outer vs Inner Self", `<text x="20" y="26" font-weight="bold">W. B. Yeats — For Anne Gregory</text><text x="40" y="60" font-weight="bold">Outer (appearance)</text><polygon points="60,90 60,150 120,150 120,90 90,72" fill="#fbc02d"/><text x="40" y="180">yellow 'honey-coloured' hair</text><line x1="280" y1="50" x2="280" y2="190" stroke="#555"/><text x="320" y="60" font-weight="bold">Inner (true self)</text><circle cx="360" cy="110" r="22" fill="none" stroke="#1565c0"/><text x="320" y="150">loved for 'yourself alone'</text><text x="320" y="180">only God can — true love</text>`)],
    when_to_use_this_method: { use_this_when: ["Questions on the theme that true love is for the inner self/soul, not outward physical beauty", "Questions on the symbolism of 'yellow hair' standing for superficial, external appearance", "Questions on poetic devices: dialogue/argument form, metaphor ('honey-coloured ramparts'), allusion, and the message that only God could love for the self alone"], use_other_when: ["Questions on a child escaping control through imagination (use 'Amanda!')", "Questions on nature/liberation symbolism (use 'The Trees')"] },
    edge_cases: [ { case: "Reading the poem as encouraging the girl to dye her hair to test love", value: "The point is the opposite — Yeats argues that loving someone only for their hair colour is shallow; genuine love values the self, something only God can do perfectly", reasoning: "The 'old religious man' line shows that loving the inner self alone is almost divine, beyond ordinary men charmed by appearance", where_it_appears: "'only God, my dear, / Could love you for yourself alone / And not your yellow hair'" } ],
    video_script_hooks: { opening_hook: "A young woman is told men can only love her 'honey-coloured' hair — so could she change it to be loved for herself instead?", concept_reveal: "Yeats argues that true love must be for the inner self, not outward beauty; loving the soul alone, he says, is something only God can truly do." },
  },

  // ── FOOTPRINTS WITHOUT FEET ────────────────────────────────────────────────
  eng_fw_ch1: {
    visual_description: "A plot arc showing Tricki the overfed dog declining at Mrs Pumphrey's home, then recovering at Mr Herriot's surgery through diet and exercise.",
    svg_diagrams: [svg("eng_fw_ch1_diagram", "Tricki's Recovery Arc", `<text x="20" y="26" font-weight="bold">A Triumph of Surgery — Recovery Arc</text><text x="20" y="60">Over-pampered &amp; ill</text><line x1="40" y1="150" x2="180" y2="120" stroke="#c00" stroke-width="2"/><text x="60" y="170">Pumphrey's: cream, cakes</text><line x1="180" y1="120" x2="320" y2="90" stroke="#0a0" stroke-width="2"/><text x="230" y="110">Surgery: diet + exercise</text><line x1="320" y1="90" x2="480" y2="50" stroke="#0a0" stroke-width="2"/><text x="380" y="40">Full recovery</text><circle cx="480" cy="50" r="6" fill="#0a0"/>`)],
    when_to_use_this_method: { use_this_when: ["questions on the theme of over-pampering / harmful indulgence", "character sketch of Mr Herriot or Mrs Pumphrey", "humour and irony in the 'triumph of surgery' title"], use_other_when: ["questions about science misuse — use ch5/ch6", "questions about crime or trust — use ch2/ch3/ch4"] },
    edge_cases: [ { case: "Students think Tricki needed actual surgery", value: "No operation occurred; 'surgery' is the British word for the vet's clinic, and the cure was diet and exercise", reasoning: "The ironic title plays on 'surgery' meaning the vet's premises, not an operation", where_it_appears: "Throughout; the title and the no-medicine treatment at the hospital" } ],
    video_script_hooks: { opening_hook: "A dog so spoiled with cream and cakes that he can barely waddle — and the cure is not medicine, but tough love.", concept_reveal: "Love that over-indulges is harmful; Tricki recovers only through proper diet, exercise, and discipline." },
  },
  eng_fw_ch2: {
    visual_description: "A character web linking the young thief Hari Singh to Anil, who teaches him to read and write, with arrows showing trust given and theft reversed.",
    svg_diagrams: [svg("eng_fw_ch2_diagram", "Trust & Reform", `<text x="20" y="26" font-weight="bold">The Thief's Story — Trust Reverses Theft</text><circle cx="120" cy="110" r="34" fill="#eef"/><text x="92" y="115">Hari Singh</text><circle cx="420" cy="110" r="34" fill="#efe"/><text x="402" y="115">Anil</text><line x1="154" y1="100" x2="386" y2="100" stroke="#0a0" stroke-width="2"/><text x="210" y="92">teaches to read &amp; write</text><line x1="386" y1="125" x2="154" y2="125" stroke="#c00" stroke-width="2"/><text x="210" y="148">money stolen then returned</text>`)],
    when_to_use_this_method: { use_this_when: ["theme of trust, reform and the power of education", "character sketch of Hari Singh or Anil", "why Hari Singh returns the stolen money"], use_other_when: ["theme of clever deception by a spy — use ch3", "theme of a burglar tricked — use ch4"] },
    edge_cases: [ { case: "Students say Anil never realised the money was stolen", value: "Anil knew Hari had taken and returned the money; the slightly damp note revealed it, yet he chose to say nothing", reasoning: "Anil's silent forgiveness and the wet note show he understood, deepening the trust theme", where_it_appears: "The morning after the theft, when Anil hands Hari a fifty-rupee note that is still damp" } ],
    video_script_hooks: { opening_hook: "A fifteen-year-old thief picks his easiest victim yet — a careless young man who offers him food, a bed, and lessons in reading.", concept_reveal: "Being trusted and taught can reform a person more powerfully than punishment; Hari returns the money to keep what he values most." },
  },
  eng_fw_ch3: {
    visual_description: "A plot map of the hotel room showing Ausable's invented 'balcony' trick that fools the gun-wielding Max into jumping to his death.",
    svg_diagrams: [svg("eng_fw_ch3_diagram", "The Balcony Bluff", `<text x="20" y="26" font-weight="bold">The Midnight Visitor — Ausable's Bluff</text><rect x="40" y="60" width="200" height="110" fill="none" stroke="#333"/><text x="70" y="50">Ausable's room</text><text x="60" y="100">Ausable &amp; Fowler</text><text x="60" y="130">Max with gun</text><line x1="240" y1="60" x2="240" y2="170" stroke="#c00" stroke-width="3"/><text x="250" y="100">"balcony"</text><text x="250" y="120">(does not exist)</text><text x="360" y="100">Police knock</text><text x="360" y="125">Max jumps, falls</text>`)],
    when_to_use_this_method: { use_this_when: ["theme of presence of mind / intelligence over force", "character sketch of Ausable as an unglamorous, clever spy", "how the balcony trick works and why Max believes it"], use_other_when: ["theme of trust and reform — use ch2", "theme of vanity and irony — use ch7"] },
    edge_cases: [ { case: "Students assume there really was a balcony Max fell from", value: "There was no balcony at all; Ausable invented it, and Max jumped onto nothing, falling two floors to escape the 'police'", reasoning: "Ausable's whole victory rests on the lie that a balcony exists below the window", where_it_appears: "The climax, after the knock at the door; the waiter's later confirmation there is no balcony" } ],
    video_script_hooks: { opening_hook: "A fat, unimpressive secret agent faces an armed enemy in his own room — and his only weapon is a story about a balcony.", concept_reveal: "Quick thinking and calm nerves defeat brute force; the real spy is nothing like the glamorous figure of films." },
  },
  eng_fw_ch4: {
    visual_description: "An irony diagram showing Horace Danby the gentleman burglar tricked by a woman posing as the house's mistress, ending with him jailed for a crime that locks him in.",
    svg_diagrams: [svg("eng_fw_ch4_diagram", "The Irony of Trust", `<text x="20" y="26" font-weight="bold">A Question of Trust — Tables Turned</text><circle cx="120" cy="110" r="34" fill="#eef"/><text x="88" y="115">Horace D.</text><circle cx="420" cy="110" r="34" fill="#fee"/><text x="388" y="115">"Mistress"</text><line x1="154" y1="105" x2="386" y2="105" stroke="#c00" stroke-width="2"/><text x="200" y="96">opens safe FOR her</text><line x1="386" y1="125" x2="154" y2="125" stroke="#333" stroke-width="2"/><text x="180" y="150">she keeps jewels, he's jailed</text>`)],
    when_to_use_this_method: { use_this_when: ["theme of irony — a thief robbed by a cleverer thief", "character sketch of Horace Danby the law-abiding burglar", "the meaning of the title 'A Question of Trust'"], use_other_when: ["a spy outwitting an enemy — use ch3", "a scientist turning to crime — use ch5"] },
    edge_cases: [ { case: "Students think the woman was the real owner of the house", value: "She was another thief who tricked Horace into opening the safe and walked off with the jewels herself", reasoning: "Her ease and the later proof that the real owners did not recognise her reveal she was an impostor", where_it_appears: "Her arrival at the house; Horace's arrest when his fingerprints (he removed gloves at her request) are found" } ],
    video_script_hooks: { opening_hook: "A polite burglar who steals only once a year to fund his book-buying habit meets a charming woman in the house he's robbing.", concept_reveal: "Trust placed in the wrong person is fatal; the trickster gets tricked, and irony delivers his punishment." },
  },
  eng_fw_ch5: {
    visual_description: "A theme map of Griffin the invisible scientist's descent from discovery to theft and violence, tracing his trail through Iping and Mrs Hall's inn.",
    svg_diagrams: [svg("eng_fw_ch5_diagram", "Science Misused", `<text x="20" y="26" font-weight="bold">Footprints Without Feet — Griffin's Trail</text><text x="40" y="70">Becomes invisible</text><line x1="50" y1="80" x2="180" y2="110" stroke="#c00" stroke-width="2"/><text x="150" y="130">Burns house, robs shop</text><line x1="200" y1="120" x2="330" y2="120" stroke="#c00" stroke-width="2"/><text x="300" y="145">Mrs Hall's inn, Iping</text><line x1="350" y1="115" x2="480" y2="90" stroke="#c00" stroke-width="2"/><text x="380" y="70">Exposed &amp; hunted</text><circle cx="100" cy="160" r="4" fill="#333"/><circle cx="130" cy="165" r="4" fill="#333"/><circle cx="160" cy="160" r="4" fill="#333"/><text x="180" y="175">muddy footprints with no feet</text>`)],
    when_to_use_this_method: { use_this_when: ["theme of misuse of science / science without conscience", "character sketch of Griffin as a lawless, brilliant scientist", "how the invisible man is detected (footprints, smashed windows)"], use_other_when: ["theme of curiosity used well — use ch6 (Ebright)", "a polite, harmless burglar — use ch4"] },
    edge_cases: [ { case: "Students think Griffin was a hero or sympathetic figure", value: "Griffin is a brilliant but lawless and dangerous man who turns to arson, theft and assault", reasoning: "He sets fire to his landlord's house and robs a shop, showing science used for selfish, criminal ends", where_it_appears: "His backstory in London and his behaviour at Iping toward Mrs Hall and the villagers" } ],
    video_script_hooks: { opening_hook: "Muddy footprints appear on a doorstep in the snow — but there is no one there to make them.", concept_reveal: "A great scientific gift turns destructive without morality; Griffin's invisibility becomes a tool for crime, not progress." },
  },
  eng_fw_ch6: {
    visual_description: "A 'making of a scientist' staircase from Richard Ebright's childhood butterfly collecting up through science fairs to a discovery about cell DNA.",
    svg_diagrams: [svg("eng_fw_ch6_diagram", "Steps of a Scientist", `<text x="20" y="26" font-weight="bold">The Making of a Scientist — Ebright's Rise</text><rect x="40" y="150" width="110" height="20" fill="#cce"/><text x="50" y="145">Collects butterflies</text><rect x="150" y="125" width="110" height="20" fill="#cce"/><text x="160" y="120">Science fairs</text><rect x="260" y="100" width="110" height="20" fill="#cce"/><text x="270" y="95">Monarch &amp; cell theory</text><rect x="370" y="75" width="130" height="20" fill="#bdb"/><text x="380" y="70">DNA &amp; cell discovery</text>`)],
    when_to_use_this_method: { use_this_when: ["theme of curiosity, hard work and the right guidance making a scientist", "character sketch of Richard Ebright or his mother / Mr Weiherer", "the three qualities behind Ebright's success"], use_other_when: ["theme of science misused — use ch5 (Griffin)", "stories of crime or trust — use ch2/ch3/ch4"] },
    edge_cases: [ { case: "Students say Ebright won every science fair from the start", value: "He lost his first county science fair with a slide display, learning that real science means experiments, not just collections", reasoning: "The failure taught him the difference between displaying and doing science — a turning point", where_it_appears: "His first county science fair entry in seventh grade, which did not win" } ],
    video_script_hooks: { opening_hook: "A boy who collected all twenty-five species of butterflies in his town grew up to discover how a cell reads its own DNA.", concept_reveal: "Curiosity, a first-rate mind, the will to win, and good mentors together make a scientist." },
  },
  eng_fw_ch7: {
    visual_description: "An irony arc tracing Matilda Loisel from one glamorous evening to ten years of debt repaying a necklace that turns out to be fake.",
    svg_diagrams: [svg("eng_fw_ch7_diagram", "The Cost of Vanity", `<text x="20" y="26" font-weight="bold">The Necklace — Irony of Ten Years</text><text x="40" y="65">Borrows necklace</text><line x1="50" y1="75" x2="170" y2="60" stroke="#0a0" stroke-width="2"/><text x="150" y="50">One grand ball</text><line x1="180" y1="65" x2="300" y2="130" stroke="#c00" stroke-width="2"/><text x="220" y="120">Necklace LOST</text><line x1="300" y1="135" x2="430" y2="150" stroke="#c00" stroke-width="2"/><text x="340" y="170">10 yrs of debt &amp; toil</text><text x="380" y="60" fill="#c00">Truth: it was fake!</text>`)],
    when_to_use_this_method: { use_this_when: ["theme of pride, vanity and discontent", "the role of irony and the surprise ending", "character sketch of Matilda or her husband Loisel"], use_other_when: ["a thief reformed by trust — use ch2", "a burglar tricked — use ch4"] },
    edge_cases: [ { case: "Students think Matilda lost a genuine diamond necklace", value: "The borrowed necklace was an imitation worth only about five hundred francs, though the Loisels spent thirty-six thousand replacing it", reasoning: "Madame Forestier reveals at the end that her necklace was paste, making the ten years of sacrifice tragically pointless", where_it_appears: "The final scene where Madame Forestier tells Matilda the necklace was false" } ],
    video_script_hooks: { opening_hook: "A woman borrows a glittering diamond necklace for one perfect night — and loses it, along with the next ten years of her life.", concept_reveal: "Vanity and dishonesty about one's means lead to ruin; the cruellest irony is that the lost treasure was worthless all along." },
  },
  eng_fw_ch8: {
    visual_description: "A transformation arc showing Sulekha, nicknamed 'Bholi' (the simpleton), changing through education into a confident girl who rejects a greedy groom.",
    svg_diagrams: [svg("eng_fw_ch8_diagram", "Bholi's Transformation", `<text x="20" y="26" font-weight="bold">Bholi — Education Transforms a Girl</text><text x="40" y="70">Neglected, mocked,</text><text x="40" y="90">stammering 'Bholi'</text><line x1="60" y1="110" x2="220" y2="110" stroke="#08a" stroke-width="2"/><text x="100" y="135">School &amp; teacher's care</text><line x1="240" y1="110" x2="420" y2="110" stroke="#0a0" stroke-width="2"/><text x="300" y="90">Confident, speaks out</text><text x="300" y="135">Refuses dowry-greedy Bishamber</text>`)],
    when_to_use_this_method: { use_this_when: ["theme of girl-child education and empowerment", "evil of dowry and child marriage", "character sketch of Bholi (Sulekha) or her teacher"], use_other_when: ["theme of vanity and class — use ch7", "science themes — use ch5/ch6"] },
    edge_cases: [ { case: "Students think Bholi was born unintelligent", value: "Bholi was not dim by nature; a childhood fall and an attack of smallpox left her slow to speak and pockmarked, and neglect did the rest — education revealed her real intelligence", reasoning: "Her stammer and 'backwardness' came from accident, illness and neglect, not innate inability", where_it_appears: "The opening describing her fall as a baby and her bout of smallpox" } ],
    video_script_hooks: { opening_hook: "A pockmarked, stammering girl whom even her family calls a simpleton walks into a classroom — and walks out able to decide her own future.", concept_reveal: "Education gives a neglected girl the voice to reject injustice; Bholi refuses a groom who demands dowry, transforming from victim to decision-maker." },
  },
  eng_fw_ch9: {
    visual_description: "A comic plot map of the 2040 Martian invasion in which Think-Tank misreads a Mother Goose nursery rhyme book and orders a panicked retreat from Earth.",
    svg_diagrams: [svg("eng_fw_ch9_diagram", "How a Book Saved Earth", `<text x="20" y="26" font-weight="bold">The Book That Saved the Earth — Plot</text><text x="40" y="65">Mars, 2040: Think-Tank plans invasion</text><line x1="60" y1="80" x2="200" y2="110" stroke="#a06" stroke-width="2"/><text x="140" y="130">Probe finds a book of nursery rhymes</text><line x1="220" y1="115" x2="360" y2="115" stroke="#a06" stroke-width="2"/><text x="300" y="140">Misreads 'Humpty Dumpty' as a threat</text><line x1="380" y1="110" x2="500" y2="80" stroke="#0a0" stroke-width="2"/><text x="380" y="65">Martians flee Earth!</text>`)],
    when_to_use_this_method: { use_this_when: ["theme of humour and satire / power of books", "it is a science-fiction PLAY, not a prose story (stage directions, characters)", "character sketch of Think-Tank, Noodle, Captain Omega or Lieutenant Iota"], use_other_when: ["serious science misuse — use ch5", "real-life scientist's growth — use ch6"] },
    edge_cases: [ { case: "Students treat this as a regular story and miss the humour/format", value: "It is a one-act comic science-fiction play set in 2040, and a harmless Mother Goose nursery-rhyme book — not weapons — drives the Martians away", reasoning: "Think-Tank misinterprets the rhymes (e.g. Humpty Dumpty as a portrait of himself, 'Hey diddle diddle' as a chemical attack) and orders retreat", where_it_appears: "The Mars Space Control scenes where Think-Tank reads the captured nursery-rhyme book" } ],
    video_script_hooks: { opening_hook: "In the year 2040, Martians prepare to conquer Earth — until their great leader opens a children's book of nursery rhymes.", concept_reveal: "Humour and misunderstanding turn a harmless book into Earth's saviour, gently mocking arrogance and the fear of the unknown." },
  },

  // ── GRAMMAR & WRITING UNITS ────────────────────────────────────────────────
  eng_wb_grammar1: {
    visual_description: "A timeline chart showing the three time frames (past, present, future) split into simple, continuous, and perfect aspects with a sequence-of-tenses arrow.",
    svg_diagrams: [svg("eng_wb_grammar1_diagram", "Tense Aspect Grid", `<text x="20" y="26" font-weight="bold">Tenses: Time &amp; Aspect</text><line x1="20" y1="40" x2="540" y2="40" stroke="#333"/><text x="30" y="70">PAST</text><text x="230" y="70">PRESENT</text><text x="430" y="70">FUTURE</text><text x="30" y="110">wrote</text><text x="230" y="110">writes</text><text x="430" y="110">will write</text><text x="30" y="140">was writing</text><text x="230" y="140">is writing</text><text x="430" y="140">will be writing</text><text x="30" y="170">had written</text><text x="230" y="170">has written</text><text x="430" y="170">will have written</text>`)],
    when_to_use_this_method: { use_this_when: ["gap-filling and editing tasks in Section B that test correct verb forms", "sentence-completion items where a reporting/main verb fixes the tense of a following clause"], use_other_when: ["the test is about reporting a speaker's exact words, use reported speech instead", "the focus is matching the verb to the subject's number, use subject-verb agreement instead"] },
    edge_cases: [ { case: "Lencho 'has wrote' a letter to God.", value: "Lencho has written a letter to God.", reasoning: "The present perfect needs the past participle 'written', not the simple past 'wrote'.", where_it_appears: "Gap-fill / editing on A Letter to God" }, { case: "When he opened the box, he sees no money.", value: "When he opened the box, he saw no money.", reasoning: "Sequence of tenses: a past main clause requires a past tense in the linked clause.", where_it_appears: "Sentence-transformation in Section B" } ],
    video_script_hooks: { opening_hook: "Lencho mailed a letter to God and waited - but did he 'wait', is he 'waiting', or had he 'waited'? Same action, three different stories.", concept_reveal: "Time tells you WHEN (past, present, future); aspect tells you whether the action is complete, ongoing, or simply a fact - and once your main verb picks a time, the rest of the sentence must follow it." },
  },
  eng_wb_grammar2: {
    visual_description: "A modal verbs chart mapping each modal to its function (ability, permission, obligation, advice, possibility) along a weak-to-strong certainty scale.",
    svg_diagrams: [svg("eng_wb_grammar2_diagram", "Modals by Function", `<text x="20" y="26" font-weight="bold">Modals: Function &amp; Strength</text><line x1="20" y1="180" x2="540" y2="180" stroke="#333"/><text x="20" y="195">weak</text><text x="490" y="195">strong</text><text x="40" y="70">can - ability</text><text x="40" y="95">could - past ability/polite</text><text x="40" y="120">may - permission/possibility</text><text x="300" y="70">should - advice</text><text x="300" y="95">ought to - duty</text><text x="300" y="120">must - obligation</text><circle cx="60" cy="160" r="5" fill="#4a90d9"/><circle cx="300" cy="160" r="5" fill="#4a90d9"/><circle cx="500" cy="160" r="5" fill="#d94a4a"/>`)],
    when_to_use_this_method: { use_this_when: ["gap-fill items asking for the right modal to express permission, obligation, ability, or advice", "editing tasks where a wrong modal changes the meaning of a sentence"], use_other_when: ["the sentence needs an ordinary tense form rather than a function word, use tenses instead", "you must turn an active sentence into passive, use voice instead"] },
    edge_cases: [ { case: "Mandela said the oppressed 'must to' be liberated.", value: "Mandela said the oppressed must be liberated.", reasoning: "Modals are followed by the bare infinitive; 'must' never takes 'to'.", where_it_appears: "Gap-fill / editing on Nelson Mandela" }, { case: "Using 'can' to ask polite permission of an official.", value: "Use 'may' or 'could' for polite permission ('May I leave?').", reasoning: "'Can' marks ability/informal permission; 'may' and 'could' are the polite/formal choices.", where_it_appears: "Sentence completion in Section B" } ],
    video_script_hooks: { opening_hook: "Mandela could not vote, may not enter certain doors, must obey unjust laws - one tiny word in each sentence decided what was allowed and what was forced.", concept_reveal: "Modals are helper verbs that add attitude: can/could (ability), may/could (permission), must/should/ought to (obligation and advice) - and every one of them is followed by the plain form of the verb." },
  },
  eng_wb_grammar3: {
    visual_description: "A flow rule showing a subject feeding into a verb, with branches for singular vs plural and special cases like collective nouns and 'either/neither'.",
    svg_diagrams: [svg("eng_wb_grammar3_diagram", "Subject-Verb Concord", `<text x="20" y="26" font-weight="bold">Subject-Verb Agreement</text><rect x="30" y="50" width="120" height="36" fill="none" stroke="#333"/><text x="45" y="73">Subject</text><line x1="150" y1="68" x2="220" y2="68" stroke="#333"/><rect x="220" y="40" width="150" height="30" fill="none" stroke="#333"/><text x="232" y="60">Singular: verb + s</text><rect x="220" y="80" width="150" height="30" fill="none" stroke="#333"/><text x="232" y="100">Plural: base verb</text><text x="30" y="150">Each / Everyone: singular</text><text x="30" y="175">Neither pilot nor crew: verb agrees with nearer noun</text>`)],
    when_to_use_this_method: { use_this_when: ["editing/omission tasks where a verb does not match its subject in number", "gap-fill choosing 'is/are' or 'has/have' after tricky subjects like 'each', 'everyone', collective nouns"], use_other_when: ["the error is the verb's time frame rather than its number, use tenses instead", "the sentence asks for a determiner before the noun, use determiners instead" ] },
    edge_cases: [ { case: "Neither the pilot nor the passengers 'was' calm.", value: "Neither the pilot nor the passengers were calm.", reasoning: "With 'neither...nor', the verb agrees with the nearer subject, here the plural 'passengers'.", where_it_appears: "Editing on Two Stories about Flying" }, { case: "Everyone in the planes 'were' frightened.", value: "Everyone in the planes was frightened.", reasoning: "'Everyone' is singular; the intervening plural 'planes' does not change the verb.", where_it_appears: "Gap-fill in Section B" } ],
    video_script_hooks: { opening_hook: "Two pilots, one storm: 'the young pilot flies' but 'the pilots fly' - lose that single 's' and your sentence crash-lands.", concept_reveal: "Subject-verb agreement means a singular subject takes a singular verb and a plural subject takes a plural verb - and tricky words like 'each', 'everyone' and 'neither...nor' have their own rules." },
  },
  eng_wb_grammar4: {
    visual_description: "A two-column transformation chart converting direct speech to indirect speech, showing changes to pronouns, tense, time words, and the reporting verb for statements, questions, and commands.",
    svg_diagrams: [svg("eng_wb_grammar4_diagram", "Direct to Indirect", `<text x="20" y="26" font-weight="bold">Reported Speech</text><text x="30" y="55" font-weight="bold">Direct</text><text x="300" y="55" font-weight="bold">Indirect</text><line x1="280" y1="40" x2="280" y2="190" stroke="#333"/><text x="30" y="85">"I am tired," she said.</text><text x="300" y="85">She said she was tired.</text><text x="30" y="120">"Open it," he said.</text><text x="300" y="120">He told her to open it.</text><text x="30" y="155">"Are you here?" he asked.</text><text x="300" y="155">He asked if I was there.</text>`)],
    when_to_use_this_method: { use_this_when: ["Section B transformation items that ask you to change direct speech into indirect (or vice versa)", "questions reporting statements, commands, requests, and questions with correct backshift"], use_other_when: ["the task only tests an isolated verb form with no speaker, use tenses instead", "you must swap subject and object for emphasis, use active and passive voice instead"] },
    edge_cases: [ { case: "She said that she 'is' writing in her diary (backshift forgotten).", value: "She said that she was writing in her diary.", reasoning: "After a past reporting verb the present tense backshifts to past.", where_it_appears: "Transformation on Anne Frank" }, { case: "He asked me 'where do I live?' (keeping question word order and '?').", value: "He asked me where I lived.", reasoning: "Reported questions use statement word order, no question mark, and use 'if/whether' for yes/no questions.", where_it_appears: "Direct-to-indirect items in Section B" } ],
    video_script_hooks: { opening_hook: "Anne Frank wrote 'I want to confide in you' - but the moment you report her words, the 'I' shifts, the tense steps back in time, and the diary speaks differently.", concept_reveal: "In reported speech you drop the quotation marks and adjust pronouns, the tense (backshift), and time words; commands use 'to + verb', and questions take 'if/whether' or the question word with normal word order." },
  },
  eng_wb_grammar5: {
    visual_description: "A decision chart for determiners grouping articles (a/an/the), quantifiers (some/any, much/many, little/few) and demonstratives (this/that) by the type of noun they precede.",
    svg_diagrams: [svg("eng_wb_grammar5_diagram", "Choosing Determiners", `<text x="20" y="26" font-weight="bold">Determiners</text><text x="30" y="60" font-weight="bold">Articles</text><text x="30" y="85">a/an - first mention; the - known</text><text x="30" y="120" font-weight="bold">Quantifiers</text><text x="30" y="145">many/few: countable; much/little: uncountable</text><text x="30" y="180">some (positive) / any (neg. &amp; questions)</text><line x1="20" y1="95" x2="540" y2="95" stroke="#333"/>`)],
    when_to_use_this_method: { use_this_when: ["gap-fill items asking for the correct article or quantifier before a noun", "editing tasks with a missing or wrong a/an/the, much/many, or some/any"], use_other_when: ["the word links two ideas rather than introducing a noun, use connectors instead", "the word shows the relationship of place or time, use prepositions instead"] },
    edge_cases: [ { case: "We did not have 'some' tea at the Coorg plantation.", value: "We did not have any tea at the Coorg plantation.", reasoning: "Use 'any' in negatives and questions; 'some' is for affirmative statements.", where_it_appears: "Gap-fill on Glimpses of India" }, { case: "There were too 'much' tourists in Coorg.", value: "There were too many tourists in Coorg.", reasoning: "'Many' goes with countable plural nouns; 'much' goes with uncountable nouns.", where_it_appears: "Editing in Section B" } ],
    video_script_hooks: { opening_hook: "In the hills of Coorg you sip 'a' cup of coffee, watch 'the' mist rise, and meet 'many' travellers - swap one of those little words and the sentence wobbles.", concept_reveal: "Determiners are the small words before nouns: a/an for first mention, 'the' for something known, and quantifiers like much/many or some/any chosen by whether the noun is countable and the sentence is positive or negative." },
  },
  eng_wb_grammar6: {
    visual_description: "A map-style diagram sorting prepositions into three boxes - time (at/on/in), place (in/on/at/under), and direction (to/into/across) - with a small example under each.",
    svg_diagrams: [svg("eng_wb_grammar6_diagram", "Prepositions Sorted", `<text x="20" y="26" font-weight="bold">Prepositions: Time, Place, Direction</text><rect x="20" y="45" width="160" height="120" fill="none" stroke="#333"/><text x="40" y="70" font-weight="bold">TIME</text><text x="32" y="95">at 5 o'clock</text><text x="32" y="120">on Monday</text><text x="32" y="145">in June</text><rect x="200" y="45" width="160" height="120" fill="none" stroke="#333"/><text x="220" y="70" font-weight="bold">PLACE</text><text x="212" y="95">in the river</text><text x="212" y="120">on the bank</text><text x="212" y="145">under water</text><rect x="380" y="45" width="160" height="120" fill="none" stroke="#333"/><text x="400" y="70" font-weight="bold">DIRECTION</text><text x="392" y="95">into the tank</text><text x="392" y="120">across the room</text><text x="392" y="145">towards Maxwell</text>`)],
    when_to_use_this_method: { use_this_when: ["gap-fill items needing the right preposition of time, place, or direction", "editing tasks with a missing or wrong preposition before a noun phrase"], use_other_when: ["the word joins two clauses, use connectors/conjunctions instead", "you need the article or quantifier before the noun, use determiners instead"] },
    edge_cases: [ { case: "Mijbil the otter dived 'in' the water tank (motion intended).", value: "Mijbil dived into the water tank.", reasoning: "'Into' shows movement to the inside; 'in' shows position only.", where_it_appears: "Gap-fill on Mijbil the Otter" }, { case: "Maxwell arrived 'in' Monday morning.", value: "Maxwell arrived on Monday morning.", reasoning: "Use 'on' with days and dates; 'in' is for months, years, and longer periods.", where_it_appears: "Editing in Section B" } ],
    video_script_hooks: { opening_hook: "Mijbil the otter slid INTO the tank, splashed water ACROSS the floor, and curled up IN the basket AT night - tiny prepositions tracking every move.", concept_reveal: "Prepositions show relationships of time (at/on/in), place (in/on/at/under) and direction (to/into/across); the rule of thumb is at for points, on for surfaces and days, and in for enclosed spaces and longer periods." },
  },
  eng_wb_grammar7: {
    visual_description: "A two-line transformation diagram showing an active sentence (subject-verb-object) with arrows swapping the object to the front, the verb becoming 'be + past participle', and the subject moving into a 'by' phrase.",
    svg_diagrams: [svg("eng_wb_grammar7_diagram", "Active to Passive", `<text x="20" y="26" font-weight="bold">Active and Passive Voice</text><text x="30" y="60">Active:</text><text x="100" y="60">The conductor drove the bus.</text><text x="30" y="110">Passive:</text><text x="100" y="110">The bus was driven by the conductor.</text><polygon points="120,70 270,70 195,95" fill="none" stroke="#4a90d9"/><text x="150" y="150">object: subject; verb: be + V3; subject: by-phrase</text>`)],
    when_to_use_this_method: { use_this_when: ["Section B transformation items asking you to change a sentence from active to passive or back", "editing tasks where the passive form ('be + past participle') is wrongly built"], use_other_when: ["you must report someone's words, use reported speech instead", "the change is only the tense of one verb, use tenses instead"] },
    edge_cases: [ { case: "Active 'The driver was driving the bus' wrongly made passive as 'The bus was drive by the driver'.", value: "The bus was being driven by the driver.", reasoning: "Past continuous passive is 'was/were being + past participle', and the participle must be 'driven', not 'drive'.", where_it_appears: "Transformation on Madam Rides the Bus" }, { case: "Forgetting to change the verb form: 'The ticket bought by Valli.'", value: "The ticket was bought by Valli.", reasoning: "Passive always needs the correct form of 'be' plus the past participle; you cannot drop the auxiliary.", where_it_appears: "Active-to-passive items in Section B" } ],
    video_script_hooks: { opening_hook: "Valli bought a ticket - or was a ticket bought by Valli? Same journey, but the spotlight swings from the doer to the deed.", concept_reveal: "To make a sentence passive, move the object to the front, change the verb to the right form of 'be' plus the past participle, and push the original subject into a 'by' phrase - which you can even drop when the doer is unimportant." },
  },
  eng_wb_grammar8: {
    visual_description: "A connector chart linking two simple sentences with labelled bridges showing the meaning each conjunction adds (addition, contrast, cause, condition, purpose).",
    svg_diagrams: [svg("eng_wb_grammar8_diagram", "Connectors at Work", `<text x="20" y="26" font-weight="bold">Connectors / Conjunctions</text><rect x="20" y="60" width="120" height="36" fill="none" stroke="#333"/><text x="35" y="83">Clause A</text><rect x="420" y="60" width="120" height="36" fill="none" stroke="#333"/><text x="435" y="83">Clause B</text><line x1="140" y1="78" x2="420" y2="78" stroke="#333"/><text x="180" y="70">and (add) / but (contrast)</text><text x="180" y="120">because (cause) / although (concede)</text><text x="180" y="150">unless (condition) / so that (purpose)</text>`)],
    when_to_use_this_method: { use_this_when: ["gap-fill items choosing the right joining word between clauses (because, although, unless, so that)", "editing tasks where a wrong connector breaks the logical link between ideas"], use_other_when: ["the word sits before a noun, use prepositions or determiners instead", "you are reordering one clause into passive, use voice instead"] },
    edge_cases: [ { case: "'Although' Buddha taught peace, 'but' the woman grieved.", value: "Although Buddha taught peace, the woman grieved.", reasoning: "'Although' and 'but' both show contrast; using both together is redundant - keep only one.", where_it_appears: "Editing on The Sermon at Benares" }, { case: "Kisa Gotami will not find peace 'if' she stops mourning (wrong logic).", value: "Kisa Gotami will not find peace unless she accepts death.", reasoning: "'Unless' means 'if not' and fits a negative condition more accurately than a plain 'if' here.", where_it_appears: "Gap-fill in Section B" } ],
    video_script_hooks: { opening_hook: "Kisa Gotami begged for a cure BECAUSE her son had died, searched ALTHOUGH no house was spared, and found peace ONLY WHEN she understood - connectors carry the whole story.", concept_reveal: "Connectors are the bridges between ideas: 'and' adds, 'but/although' contrast, 'because' gives a cause, 'unless' sets a negative condition, and 'so that' shows purpose - pick the one whose meaning matches the link." },
  },
  eng_wb_grammar9: {
    visual_description: "A sentence-tree diagram showing one main clause with branches into subordinate clauses labelled noun, adjective, and adverb, plus a small editing/omission strip beneath.",
    svg_diagrams: [svg("eng_wb_grammar9_diagram", "Clauses & Editing", `<text x="20" y="26" font-weight="bold">Clauses</text><rect x="200" y="45" width="160" height="34" fill="none" stroke="#333"/><text x="215" y="67">Main Clause</text><line x1="240" y1="79" x2="120" y2="120" stroke="#333"/><line x1="280" y1="79" x2="280" y2="120" stroke="#333"/><line x1="320" y1="79" x2="440" y2="120" stroke="#333"/><text x="60" y="140">Noun: what he said</text><text x="230" y="140">Adjective: who proposed</text><text x="400" y="140">Adverb: because he argued</text><text x="20" y="180">Editing: omit / correct one word per line</text>`)],
    when_to_use_this_method: { use_this_when: ["identifying or combining main and subordinate clauses in Section B", "editing and omission tasks that ask you to correct or delete one extra word per line"], use_other_when: ["the item only tests choosing a single connecting word, use connectors instead", "you must report dialogue between characters, use reported speech instead"] },
    edge_cases: [ { case: "Combining wrongly: 'Lomov came to propose. He quarrelled instead. (left as two stubs).'", value: "Lomov, who came to propose, quarrelled instead.", reasoning: "An adjective clause beginning with 'who' embeds the second idea into the main clause smoothly.", where_it_appears: "Clause combining on The Proposal" }, { case: "Omission: 'Natalya argued with him about of the meadows.'", value: "Natalya argued with him about the meadows.", reasoning: "The extra word 'of' must be omitted; 'about' already takes the noun directly.", where_it_appears: "Editing/omission in Section B" } ],
    video_script_hooks: { opening_hook: "Lomov came to propose, but the sentence about WHO owns the Oxen Meadows splits into clause after clause - just like their endless quarrel.", concept_reveal: "A clause has its own subject and verb; the main clause stands alone, while subordinate clauses act as a noun, an adjective, or an adverb - and editing tasks hide one extra or wrong word in each line for you to fix." },
  },
};

// ─────────────────────────────────────────────────────────────────────────────
async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  const entries = Object.entries(ENRICH);
  if (!entries.length) { console.log("Nothing to enrich."); await mongoose.disconnect(); return; }

  let patched = 0, missing = 0;
  for (const [topicId, f] of entries) {
    const set = {
      "teaching_content.visual_description":      f.visual_description,
      "teaching_content.svg_diagrams":            f.svg_diagrams,
      "teaching_content.when_to_use_this_method": f.when_to_use_this_method,
      "teaching_content.edge_cases":              f.edge_cases,
      "teaching_content.video_script_hooks":      f.video_script_hooks,
    };
    const r = await NcertTopicContent.updateOne({ topicId }, { $set: set });
    if (r.matchedCount === 0) { console.log(`  ✗ MISSING in DB: ${topicId}`); missing++; }
    else { console.log(`  ✓ enriched ${topicId}`); patched++; }
  }
  console.log(`\nDone — ${patched} enriched, ${missing} missing (of ${entries.length}).`);
  await mongoose.disconnect();
  process.exit(missing ? 1 : 0);
}
run().catch((e) => { console.error("enrichEnglish10 failed:", e.message); process.exit(1); });
