import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math4_ch11_times_tables — 8 Qs
  { questionId:"math4_ch11_tt_q1", topicId:"math4_ch11_times_tables", text:"7 × 6 = ?", options:[{text:"36",type:"calculation_error"},{text:"42",type:"correct"},{text:"48",type:"calculation_error"},{text:"49",type:"calculation_error"}], explanation:"7 × 6 = 42.", solutionSteps:["7 × 6 = 42."], shortcut:"Table of 7.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_tt_q2", topicId:"math4_ch11_times_tables", text:"Table of 9: 9, 18, 27, 36, ?", options:[{text:"40",type:"calculation_error"},{text:"45",type:"correct"},{text:"42",type:"calculation_error"},{text:"50",type:"calculation_error"}], explanation:"+9 each: 36 + 9 = 45.", solutionSteps:["Table of 9.","36 + 9 = 45."], shortcut:"Add 9.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_tt_q3", topicId:"math4_ch11_times_tables", text:"8 × 7 = ?", options:[{text:"54",type:"calculation_error"},{text:"56",type:"correct"},{text:"64",type:"calculation_error"},{text:"49",type:"calculation_error"}], explanation:"8 × 7 = 56.", solutionSteps:["8 × 7 = 56."], shortcut:"7 × 8.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_tt_q4", topicId:"math4_ch11_times_tables", text:"6 × 9 = ?", options:[{text:"54",type:"correct"},{text:"56",type:"calculation_error"},{text:"45",type:"calculation_error"},{text:"63",type:"calculation_error"}], explanation:"6 × 9 = 54.", solutionSteps:["6 × 9 = 54."], shortcut:"Digits sum to 9 (5+4=9).", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_tt_q5", topicId:"math4_ch11_times_tables", text:"Table of 5 always ends in…", options:[{text:"0 or 5",type:"correct"},{text:"1 or 6",type:"calculation_error"},{text:"Any digit",type:"misinterpretation"},{text:"0 only",type:"partial_logic"}], explanation:"Multiples of 5 always end in 0 or 5.", solutionSteps:["5, 10, 15, 20, ..","Ends in 5 or 0."], shortcut:"× 5 ends 0 or 5.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_tt_q6", topicId:"math4_ch11_times_tables", text:"What is 11 × 11?", options:[{text:"22",type:"misinterpretation"},{text:"121",type:"correct"},{text:"110",type:"calculation_error"},{text:"111",type:"calculation_error"}], explanation:"11 × 11 = 121.", solutionSteps:["11 × 11 = 121."], shortcut:"Square of 11.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_tt_q7", topicId:"math4_ch11_times_tables", text:"12 × 12 = ?", options:[{text:"24",type:"misinterpretation"},{text:"144",type:"correct"},{text:"122",type:"calculation_error"},{text:"132",type:"calculation_error"}], explanation:"12 × 12 = 144.", solutionSteps:["12 × 12 = 144."], shortcut:"Square of 12.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_tt_q8", topicId:"math4_ch11_times_tables", text:"Table of 2 contains only…", options:[{text:"Odd numbers",type:"concept_error"},{text:"Even numbers",type:"correct"},{text:"Random",type:"misinterpretation"},{text:"Zero only",type:"calculation_error"}], explanation:"Multiples of 2 = even numbers.", solutionSteps:["Table of 2: 2, 4, 6, 8...","All even."], shortcut:"× 2 = even.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },

  // math4_ch11_division_tables — 8 Qs
  { questionId:"math4_ch11_dt_q1", topicId:"math4_ch11_division_tables", text:"30 ÷ 5 = ?", options:[{text:"5",type:"calculation_error"},{text:"6",type:"correct"},{text:"3",type:"calculation_error"},{text:"15",type:"misinterpretation"}], explanation:"5 × 6 = 30.", solutionSteps:["5 × ? = 30 → ? = 6."], shortcut:"Use times table backwards.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_dt_q2", topicId:"math4_ch11_division_tables", text:"56 ÷ 7 = ?", options:[{text:"6",type:"calculation_error"},{text:"7",type:"calculation_error"},{text:"8",type:"correct"},{text:"49",type:"misinterpretation"}], explanation:"7 × 8 = 56.", solutionSteps:["7 × 8 = 56.","56 ÷ 7 = 8."], shortcut:"Table of 7.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_dt_q3", topicId:"math4_ch11_division_tables", text:"Division is the OPPOSITE of…", options:[{text:"Addition",type:"concept_error"},{text:"Multiplication",type:"correct"},{text:"Subtraction",type:"misinterpretation"},{text:"Counting",type:"calculation_error"}], explanation:"Multiplication and division are inverses.", solutionSteps:["× and ÷ are opposites.","If a×b=c, then c÷b=a."], shortcut:"÷ undoes ×.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_dt_q4", topicId:"math4_ch11_division_tables", text:"81 ÷ 9 = ?", options:[{text:"7",type:"calculation_error"},{text:"8",type:"calculation_error"},{text:"9",type:"correct"},{text:"10",type:"calculation_error"}], explanation:"9 × 9 = 81.", solutionSteps:["9 × 9 = 81.","81 ÷ 9 = 9."], shortcut:"Square root of 81 is 9.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_dt_q5", topicId:"math4_ch11_division_tables", text:"100 ÷ 10 = ?", options:[{text:"1",type:"calculation_error"},{text:"10",type:"correct"},{text:"100",type:"misinterpretation"},{text:"1000",type:"calculation_error"}], explanation:"10 × 10 = 100.", solutionSteps:["100 ÷ 10 = 10."], shortcut:"÷ 10 drops a zero.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_dt_q6", topicId:"math4_ch11_division_tables", text:"42 ÷ 6 = ?", options:[{text:"6",type:"calculation_error"},{text:"7",type:"correct"},{text:"8",type:"calculation_error"},{text:"36",type:"misinterpretation"}], explanation:"6 × 7 = 42.", solutionSteps:["6 × 7 = 42.","42 ÷ 6 = 7."], shortcut:"Table of 6.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_dt_q7", topicId:"math4_ch11_division_tables", text:"0 ÷ 5 = ?", options:[{text:"5",type:"concept_error"},{text:"0",type:"correct"},{text:"1",type:"calculation_error"},{text:"Undefined",type:"misinterpretation"}], explanation:"0 divided by any nonzero number = 0.", solutionSteps:["0 ÷ anything (≠0) = 0."], shortcut:"0 ÷ N = 0.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_dt_q8", topicId:"math4_ch11_division_tables", text:"24 ÷ 8 = ?", options:[{text:"3",type:"correct"},{text:"4",type:"calculation_error"},{text:"6",type:"calculation_error"},{text:"32",type:"misinterpretation"}], explanation:"8 × 3 = 24.", solutionSteps:["8 × 3 = 24.","24 ÷ 8 = 3."], shortcut:"Table of 8.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },

  // math4_ch11_sharing — 8 Qs
  { questionId:"math4_ch11_sh_q1", topicId:"math4_ch11_sharing", text:"24 chocolates shared among 4 kids equally. Each gets…", options:[{text:"4",type:"calculation_error"},{text:"6",type:"correct"},{text:"8",type:"calculation_error"},{text:"24",type:"misinterpretation"}], explanation:"24 ÷ 4 = 6.", solutionSteps:["24 ÷ 4 = 6."], shortcut:"Total ÷ people.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_sh_q2", topicId:"math4_ch11_sharing", text:"36 sweets among 6 children. Each gets…", options:[{text:"4",type:"calculation_error"},{text:"5",type:"calculation_error"},{text:"6",type:"correct"},{text:"30",type:"misinterpretation"}], explanation:"36 ÷ 6 = 6.", solutionSteps:["36 ÷ 6 = 6."], shortcut:"6 × 6 = 36.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_sh_q3", topicId:"math4_ch11_sharing", text:"50 marbles shared equally between 5 friends. Each gets…", options:[{text:"5",type:"calculation_error"},{text:"10",type:"correct"},{text:"25",type:"calculation_error"},{text:"50",type:"misinterpretation"}], explanation:"50 ÷ 5 = 10.", solutionSteps:["50 ÷ 5 = 10."], shortcut:"÷ 5.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_sh_q4", topicId:"math4_ch11_sharing", text:"Equal sharing uses…", options:[{text:"Addition",type:"concept_error"},{text:"Division",type:"correct"},{text:"Subtraction",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"Equal sharing = dividing equally.", solutionSteps:["Total ÷ shares = each share.","Operation: division."], shortcut:"Share = ÷.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_sh_q5", topicId:"math4_ch11_sharing", text:"100 sweets among 10 children. Each gets…", options:[{text:"5",type:"calculation_error"},{text:"10",type:"correct"},{text:"100",type:"misinterpretation"},{text:"1",type:"concept_error"}], explanation:"100 ÷ 10 = 10.", solutionSteps:["100 ÷ 10 = 10."], shortcut:"÷ 10.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_sh_q6", topicId:"math4_ch11_sharing", text:"₹120 shared equally among 4. Each gets…", options:[{text:"₹30",type:"correct"},{text:"₹40",type:"calculation_error"},{text:"₹120",type:"misinterpretation"},{text:"₹60",type:"calculation_error"}], explanation:"120 ÷ 4 = ₹30.", solutionSteps:["120 ÷ 4 = 30."], shortcut:"Total ÷ people.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_sh_q7", topicId:"math4_ch11_sharing", text:"If total = 35 and each person gets 5, how many people?", options:[{text:"5",type:"calculation_error"},{text:"7",type:"correct"},{text:"30",type:"calculation_error"},{text:"40",type:"misinterpretation"}], explanation:"35 ÷ 5 = 7 people.", solutionSteps:["Total ÷ per share = number of shares.","35 ÷ 5 = 7."], shortcut:"Inverse of sharing.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_sh_q8", topicId:"math4_ch11_sharing", text:"To check 24 ÷ 4 = 6, verify with…", options:[{text:"6 + 4 = 10",type:"concept_error"},{text:"6 × 4 = 24",type:"correct"},{text:"6 − 4 = 2",type:"misinterpretation"},{text:"24 × 4",type:"calculation_error"}], explanation:"Answer × divisor = dividend.", solutionSteps:["Verify ÷ with ×.","6 × 4 = 24 ✓."], shortcut:"× to check ÷.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },

  // math4_ch11_grouping — 8 Qs
  { questionId:"math4_ch11_gr_q1", topicId:"math4_ch11_grouping", text:"20 items in groups of 5. Number of groups?", options:[{text:"4",type:"correct"},{text:"5",type:"calculation_error"},{text:"20",type:"misinterpretation"},{text:"100",type:"calculation_error"}], explanation:"20 ÷ 5 = 4.", solutionSteps:["Total ÷ group size.","20 ÷ 5 = 4."], shortcut:"Total ÷ group size.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_gr_q2", topicId:"math4_ch11_grouping", text:"36 students in groups of 6. Number of groups?", options:[{text:"5",type:"calculation_error"},{text:"6",type:"correct"},{text:"36",type:"misinterpretation"},{text:"30",type:"calculation_error"}], explanation:"36 ÷ 6 = 6.", solutionSteps:["36 ÷ 6 = 6."], shortcut:"6 × 6 = 36.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_gr_q3", topicId:"math4_ch11_grouping", text:"Grouping uses…", options:[{text:"Addition",type:"concept_error"},{text:"Division",type:"correct"},{text:"Multiplication",type:"misinterpretation"},{text:"Subtraction",type:"calculation_error"}], explanation:"Grouping uses division.", solutionSteps:["Total ÷ group size = group count.","Operation: division."], shortcut:"Group = ÷.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_gr_q4", topicId:"math4_ch11_grouping", text:"How many groups of 10 in 90?", options:[{text:"8",type:"calculation_error"},{text:"9",type:"correct"},{text:"10",type:"calculation_error"},{text:"100",type:"misinterpretation"}], explanation:"90 ÷ 10 = 9.", solutionSteps:["90 ÷ 10 = 9."], shortcut:"÷ 10.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_gr_q5", topicId:"math4_ch11_grouping", text:"60 chocolates in boxes of 12. Number of boxes?", options:[{text:"5",type:"correct"},{text:"6",type:"calculation_error"},{text:"12",type:"misinterpretation"},{text:"60",type:"calculation_error"}], explanation:"60 ÷ 12 = 5.", solutionSteps:["60 ÷ 12 = 5."], shortcut:"5 × 12 = 60.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_gr_q6", topicId:"math4_ch11_grouping", text:"Sharing differs from grouping in…", options:[{text:"They're identical",type:"concept_error"},{text:"Sharing knows # of groups; grouping knows group size",type:"correct"},{text:"They're opposite operations",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"Both use division but differ in what's given.", solutionSteps:["Sharing: # groups given.","Grouping: group size given.","Both ÷."], shortcut:"Sharing vs grouping = ÷ direction.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_gr_q7", topicId:"math4_ch11_grouping", text:"42 candies in packets of 7. Packets?", options:[{text:"5",type:"calculation_error"},{text:"6",type:"correct"},{text:"7",type:"misinterpretation"},{text:"49",type:"calculation_error"}], explanation:"42 ÷ 7 = 6.", solutionSteps:["42 ÷ 7 = 6."], shortcut:"6 × 7 = 42.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },
  { questionId:"math4_ch11_gr_q8", topicId:"math4_ch11_grouping", text:"Grouping 100 into 4-sized groups gives ___ groups.", options:[{text:"4",type:"calculation_error"},{text:"25",type:"correct"},{text:"100",type:"misinterpretation"},{text:"400",type:"calculation_error"}], explanation:"100 ÷ 4 = 25.", solutionSteps:["100 ÷ 4 = 25."], shortcut:"Quarter of 100 = 25.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Tables and Shares" },

  // math4_ch12_weight_units — 8 Qs
  { questionId:"math4_ch12_wu_q1", topicId:"math4_ch12_weight_units", text:"Best unit for a paperclip?", options:[{text:"kg",type:"concept_error"},{text:"g",type:"correct"},{text:"km",type:"misinterpretation"},{text:"L",type:"calculation_error"}], explanation:"Paperclip ≈ 1 g; use g.", solutionSteps:["Paperclip is light.","Use g."], shortcut:"Light = g.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wu_q2", topicId:"math4_ch12_weight_units", text:"Best unit for a sack of rice?", options:[{text:"g",type:"concept_error"},{text:"kg",type:"correct"},{text:"km",type:"misinterpretation"},{text:"ml",type:"calculation_error"}], explanation:"Sack ≈ 5-25 kg; use kg.", solutionSteps:["Sack is heavy.","Use kg."], shortcut:"Heavy = kg.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wu_q3", topicId:"math4_ch12_weight_units", text:"Pencil weighs about…", options:[{text:"1 mg",type:"calculation_error"},{text:"5 g",type:"correct"},{text:"50 g",type:"calculation_error"},{text:"1 kg",type:"misinterpretation"}], explanation:"Pencil ≈ 5 g.", solutionSteps:["Pencil is light.","≈ 5 g."], shortcut:"Pencil ≈ 5 g.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wu_q4", topicId:"math4_ch12_weight_units", text:"Adult person weighs about…", options:[{text:"5 g",type:"concept_error"},{text:"50 g",type:"calculation_error"},{text:"50 kg",type:"correct"},{text:"500 kg",type:"misinterpretation"}], explanation:"Adult ≈ 50-70 kg.", solutionSteps:["Person ≈ 50 kg."], shortcut:"Person ≈ 50 kg.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wu_q5", topicId:"math4_ch12_weight_units", text:"Choose the heaviest:", options:[{text:"1 g",type:"concept_error"},{text:"100 g",type:"calculation_error"},{text:"1 kg",type:"correct"},{text:"500 g",type:"calculation_error"}], explanation:"1 kg = 1000 g > 500 g > 100 g > 1 g.", solutionSteps:["1 kg = 1000 g.","Compare: 1000 > 500 > 100 > 1.","1 kg heaviest."], shortcut:"Convert to same unit.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wu_q6", topicId:"math4_ch12_weight_units", text:"Apple is about ___ g.", options:[{text:"20",type:"calculation_error"},{text:"200",type:"correct"},{text:"2000",type:"calculation_error"},{text:"5",type:"misinterpretation"}], explanation:"Apple ≈ 200 g.", solutionSteps:["Apple ≈ 200 g."], shortcut:"Apple ≈ 200 g.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wu_q7", topicId:"math4_ch12_weight_units", text:"Tonne is used for very heavy weights. 1 tonne = ___ kg.", options:[{text:"100",type:"calculation_error"},{text:"1000",type:"correct"},{text:"10",type:"misinterpretation"},{text:"10000",type:"calculation_error"}], explanation:"1 tonne = 1000 kg.", solutionSteps:["1 tonne = 1000 kg."], shortcut:"Tonne = 1000 kg.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wu_q8", topicId:"math4_ch12_weight_units", text:"Best unit for one tablet?", options:[{text:"kg",type:"concept_error"},{text:"g",type:"partial_logic"},{text:"mg",type:"correct"},{text:"L",type:"misinterpretation"}], explanation:"Tablets are usually measured in milligrams (mg).", solutionSteps:["Tablet is tiny.","mg = 1/1000 g.","Use mg."], shortcut:"Tiny = mg.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },

  // math4_ch12_grams_kilograms — 8 Qs
  { questionId:"math4_ch12_gk_q1", topicId:"math4_ch12_grams_kilograms", text:"1 kg = ? g", options:[{text:"10",type:"concept_error"},{text:"100",type:"calculation_error"},{text:"1000",type:"correct"},{text:"10000",type:"misinterpretation"}], explanation:"1 kg = 1000 g.", solutionSteps:["By definition: 1 kg = 1000 g."], shortcut:"1 kg = 1000 g.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_gk_q2", topicId:"math4_ch12_grams_kilograms", text:"5 kg = ? g", options:[{text:"50",type:"calculation_error"},{text:"500",type:"calculation_error"},{text:"5000",type:"correct"},{text:"50000",type:"misinterpretation"}], explanation:"5 × 1000 = 5000 g.", solutionSteps:["5 × 1000 = 5000."], shortcut:"× 1000.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_gk_q3", topicId:"math4_ch12_grams_kilograms", text:"3000 g = ? kg", options:[{text:"3",type:"correct"},{text:"30",type:"calculation_error"},{text:"0.3",type:"calculation_error"},{text:"300",type:"misinterpretation"}], explanation:"3000 ÷ 1000 = 3 kg.", solutionSteps:["3000 ÷ 1000 = 3."], shortcut:"÷ 1000.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_gk_q4", topicId:"math4_ch12_grams_kilograms", text:"½ kg = ?", options:[{text:"5 g",type:"calculation_error"},{text:"50 g",type:"calculation_error"},{text:"500 g",type:"correct"},{text:"5000 g",type:"misinterpretation"}], explanation:"½ × 1000 = 500 g.", solutionSteps:["½ × 1000 = 500."], shortcut:"½ kg = 500 g.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_gk_q5", topicId:"math4_ch12_grams_kilograms", text:"1 kg 250 g = ? g", options:[{text:"1025 g",type:"calculation_error"},{text:"1250 g",type:"correct"},{text:"125 g",type:"calculation_error"},{text:"12500 g",type:"misinterpretation"}], explanation:"1 kg = 1000 g + 250 g = 1250 g.", solutionSteps:["1 kg = 1000 g.","+250 = 1250 g."], shortcut:"Combine.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_gk_q6", topicId:"math4_ch12_grams_kilograms", text:"2500 g = ? kg ? g", options:[{text:"2 kg 500 g",type:"correct"},{text:"25 kg",type:"calculation_error"},{text:"2 kg 50 g",type:"calculation_error"},{text:"0.25 kg",type:"misinterpretation"}], explanation:"2500 = 2000 + 500 = 2 kg 500 g.", solutionSteps:["2500 ÷ 1000 = 2 kg with 500 g remainder.","→ 2 kg 500 g."], shortcut:"Divide for kg, remainder for g.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_gk_q7", topicId:"math4_ch12_grams_kilograms", text:"3 kg 500 g = ? g", options:[{text:"3500 g",type:"correct"},{text:"3050 g",type:"calculation_error"},{text:"350 g",type:"calculation_error"},{text:"35000 g",type:"misinterpretation"}], explanation:"3 × 1000 + 500 = 3500 g.", solutionSteps:["3 kg = 3000 g.","+500 = 3500 g."], shortcut:"Combine.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_gk_q8", topicId:"math4_ch12_grams_kilograms", text:"To convert g to kg, you ___ 1000.", options:[{text:"Multiply by",type:"concept_error"},{text:"Divide by",type:"correct"},{text:"Add",type:"misinterpretation"},{text:"Subtract",type:"calculation_error"}], explanation:"Smaller to bigger unit: divide.", solutionSteps:["g → kg: divide.","Larger unit needs fewer."], shortcut:"÷ 1000 for g to kg.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },

  // math4_ch12_comparing_weights — 8 Qs
  { questionId:"math4_ch12_cw_q1", topicId:"math4_ch12_comparing_weights", text:"Which is heavier: 1 kg or 800 g?", options:[{text:"800 g",type:"concept_error"},{text:"1 kg",type:"correct"},{text:"Equal",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"1 kg = 1000 g > 800 g.", solutionSteps:["1 kg = 1000 g.","1000 > 800."], shortcut:"Convert + compare.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_cw_q2", topicId:"math4_ch12_comparing_weights", text:"Order from lightest: 2 kg, 1500 g, 1 kg 200 g.", options:[{text:"1 kg 200 g, 1500 g, 2 kg",type:"correct"},{text:"2 kg, 1500 g, 1 kg 200 g",type:"misinterpretation"},{text:"1500 g, 2 kg, 1 kg 200 g",type:"calculation_error"},{text:"1 kg 200 g, 2 kg, 1500 g",type:"calculation_error"}], explanation:"In g: 1200, 1500, 2000.", solutionSteps:["Convert: 2 kg = 2000, 1500 g, 1 kg 200 g = 1200.","Order: 1200 < 1500 < 2000."], shortcut:"Convert + sort.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_cw_q3", topicId:"math4_ch12_comparing_weights", text:"To compare 1 kg and 950 g, convert to…", options:[{text:"Different units",type:"concept_error"},{text:"Same unit",type:"correct"},{text:"Pounds",type:"misinterpretation"},{text:"L",type:"calculation_error"}], explanation:"Same unit (g or kg) before comparing.", solutionSteps:["Convert to g: 1 kg = 1000 g.","1000 > 950."], shortcut:"Same unit first.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_cw_q4", topicId:"math4_ch12_comparing_weights", text:"5 kg vs 5000 g.", options:[{text:">",type:"concept_error"},{text:"<",type:"concept_error"},{text:"=",type:"correct"},{text:"Cannot compare",type:"guessing"}], explanation:"5 kg = 5000 g. Equal.", solutionSteps:["5 × 1000 = 5000.","= 5000 g."], shortcut:"Convert + compare.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_cw_q5", topicId:"math4_ch12_comparing_weights", text:"Heavier: 2 kg or 2200 g?", options:[{text:"2 kg",type:"concept_error"},{text:"2200 g",type:"correct"},{text:"Equal",type:"calculation_error"},{text:"Cannot say",type:"guessing"}], explanation:"2 kg = 2000 g; 2200 > 2000.", solutionSteps:["2 kg = 2000 g.","2200 > 2000."], shortcut:"Convert then compare.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_cw_q6", topicId:"math4_ch12_comparing_weights", text:"By how much is 2 kg heavier than 1500 g?", options:[{text:"500 g",type:"correct"},{text:"3500 g",type:"calculation_error"},{text:"1500 g",type:"calculation_error"},{text:"2 kg",type:"misinterpretation"}], explanation:"2 kg = 2000 g. 2000 − 1500 = 500 g.", solutionSteps:["2 kg = 2000 g.","2000 − 1500 = 500 g."], shortcut:"Convert + subtract.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_cw_q7", topicId:"math4_ch12_comparing_weights", text:"Sack 50 kg vs 50000 g. Relation?", options:[{text:">",type:"concept_error"},{text:"=",type:"correct"},{text:"<",type:"calculation_error"},{text:"Cannot say",type:"guessing"}], explanation:"50 kg = 50000 g. Equal.", solutionSteps:["50 × 1000 = 50000.","Equal."], shortcut:"× 1000.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_cw_q8", topicId:"math4_ch12_comparing_weights", text:"Smallest: 1 kg, 500 g, 1500 g.", options:[{text:"500 g",type:"correct"},{text:"1 kg",type:"calculation_error"},{text:"1500 g",type:"calculation_error"},{text:"All equal",type:"misinterpretation"}], explanation:"In g: 500, 1000, 1500. Smallest = 500 g.", solutionSteps:["Convert: 1 kg = 1000.","Compare: 500 < 1000 < 1500."], shortcut:"Smallest converted value.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },

  // math4_ch12_weight_problems — 8 Qs
  { questionId:"math4_ch12_wp_q1", topicId:"math4_ch12_weight_problems", text:"Rice 5 kg + flour 2 kg = ?", options:[{text:"3 kg",type:"misinterpretation"},{text:"7 kg",type:"correct"},{text:"10 kg",type:"calculation_error"},{text:"52 kg",type:"calculation_error"}], explanation:"5 + 2 = 7 kg.", solutionSteps:["5 + 2 = 7 kg."], shortcut:"Add weights.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wp_q2", topicId:"math4_ch12_weight_problems", text:"500 g sugar + 1 kg flour = ?", options:[{text:"1 kg 500 g",type:"correct"},{text:"501 g",type:"calculation_error"},{text:"1500 kg",type:"misinterpretation"},{text:"6 kg",type:"calculation_error"}], explanation:"500 g + 1000 g = 1500 g = 1 kg 500 g.", solutionSteps:["1 kg = 1000 g.","1000 + 500 = 1500 g = 1 kg 500 g."], shortcut:"Convert + add.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wp_q3", topicId:"math4_ch12_weight_problems", text:"3 kg − 1 kg 500 g = ?", options:[{text:"1 kg 500 g",type:"correct"},{text:"4 kg 500 g",type:"misinterpretation"},{text:"2 kg",type:"calculation_error"},{text:"500 g",type:"calculation_error"}], explanation:"3 kg = 3000 g. 3000 − 1500 = 1500 g = 1 kg 500 g.", solutionSteps:["3 kg = 3000 g.","3000 − 1500 = 1500 g."], shortcut:"Convert + subtract.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wp_q4", topicId:"math4_ch12_weight_problems", text:"4 books × 250 g each = ?", options:[{text:"1 kg",type:"correct"},{text:"500 g",type:"calculation_error"},{text:"1.5 kg",type:"calculation_error"},{text:"2 kg",type:"misinterpretation"}], explanation:"4 × 250 = 1000 g = 1 kg.", solutionSteps:["4 × 250 = 1000 g.","= 1 kg."], shortcut:"4 × 250 = 1000.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wp_q5", topicId:"math4_ch12_weight_problems", text:"Truck carries 500 kg. After delivering 200 kg, weight left = ?", options:[{text:"700 kg",type:"misinterpretation"},{text:"300 kg",type:"correct"},{text:"100 kg",type:"calculation_error"},{text:"250 kg",type:"calculation_error"}], explanation:"500 − 200 = 300 kg.", solutionSteps:["500 − 200 = 300."], shortcut:"Delivered = subtract.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wp_q6", topicId:"math4_ch12_weight_problems", text:"A bag of rice = 5 kg. 4 bags = ?", options:[{text:"9 kg",type:"misinterpretation"},{text:"20 kg",type:"correct"},{text:"25 kg",type:"calculation_error"},{text:"100 kg",type:"calculation_error"}], explanation:"4 × 5 = 20 kg.", solutionSteps:["4 × 5 = 20 kg."], shortcut:"Bags × per bag.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wp_q7", topicId:"math4_ch12_weight_problems", text:"100 g + 100 g + 200 g = ?", options:[{text:"300 g",type:"calculation_error"},{text:"400 g",type:"correct"},{text:"500 g",type:"calculation_error"},{text:"600 g",type:"calculation_error"}], explanation:"100 + 100 + 200 = 400 g.", solutionSteps:["100 + 100 = 200.","200 + 200 = 400."], shortcut:"Add g.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
  { questionId:"math4_ch12_wp_q8", topicId:"math4_ch12_weight_problems", text:"A box weighs 3 kg empty. Adding 1.5 kg books, total = ?", options:[{text:"1.5 kg",type:"misinterpretation"},{text:"4.5 kg",type:"correct"},{text:"4 kg",type:"calculation_error"},{text:"3 kg",type:"calculation_error"}], explanation:"3 + 1.5 = 4.5 kg.", solutionSteps:["3 + 1.5 = 4.5 kg."], shortcut:"Add weights.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"How Heavy? How Light?" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 4 Math v2 questions (Ch11-12).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
