import mongoose from "mongoose";
import dotenv from "dotenv";
import { NcertTopicContent } from "../models/ncertTopicContentModel.js";
dotenv.config();

const topics = [
  // ── Chapter 1: Building with Bricks ────────────────────────────────────
  {
    topicId: "math4_ch1_brick_patterns", chapterNumber: 1, sectionNumber: "1.1",
    title: "Brick Patterns", subject: "Mathematics",
    intuition: "Bricks fit together in patterns that lock them firmly so walls don't fall.",
    process_explanation: "Each new row is shifted by half a brick so vertical joints don't line up. This is called 'running bond'.",
    worked_example: "Look at a wall: rows alternate so each brick sits on the joint between two below. This makes the wall stronger.",
    common_misconceptions: "Students think any arrangement works. Random placement creates weak walls.",
    shortcuts_and_tricks: "Look at real walls. Notice the shifted pattern of bricks row by row.",
    key_takeaway: "Bricks are laid in offset patterns so walls become strong and stable.",
  },
  {
    topicId: "math4_ch1_brick_walls", chapterNumber: 1, sectionNumber: "1.2",
    title: "Building Walls with Bricks", subject: "Mathematics",
    intuition: "Walls are built brick by brick. We can count bricks needed for a wall using length × height.",
    process_explanation: "Count bricks per row × number of rows = total bricks for a wall.",
    worked_example: "A wall is 10 bricks long and 5 rows tall → 10 × 5 = 50 bricks.",
    common_misconceptions: "Students forget to count rows. Both dimensions matter.",
    shortcuts_and_tricks: "Multiply bricks per row × number of rows for the total.",
    key_takeaway: "Bricks per row × rows = total bricks in a wall.",
  },
  {
    topicId: "math4_ch1_top_views", chapterNumber: 1, sectionNumber: "1.3",
    title: "Top View of Brick Arrangements", subject: "Mathematics",
    intuition: "Looking down at brick arrangements shows how rows offset — like an aerial view.",
    process_explanation: "Top view shows the staggered pattern from above. Each brick is a small rectangle.",
    worked_example: "A 4-row wall from above shows 4 lines of rectangles, each shifted by half-brick.",
    common_misconceptions: "Students draw top view as a simple grid. The offset shift is essential.",
    shortcuts_and_tricks: "Draw small rectangles, shift each row by half a rectangle to the right or left.",
    key_takeaway: "Top view of bricks shows the staggered offset pattern clearly.",
  },
  {
    topicId: "math4_ch1_brick_designs", chapterNumber: 1, sectionNumber: "1.4",
    title: "Brick Designs and Patterns", subject: "Mathematics",
    intuition: "Builders create artistic patterns: herringbone, basket-weave, English bond. Each uses bricks differently.",
    process_explanation: "Patterns repeat a small unit of bricks. Identify the unit, then continue.",
    worked_example: "Herringbone: two bricks at right angles, repeated to form a zigzag.",
    common_misconceptions: "Patterns aren't just decoration — they affect strength too.",
    shortcuts_and_tricks: "Find the smallest repeating block of bricks. That's the pattern unit.",
    key_takeaway: "Brick designs use repeating units. Pattern + strength go together.",
  },

  // ── Chapter 2: Long and Short ──────────────────────────────────────────
  {
    topicId: "math4_ch2_units_length", chapterNumber: 2, sectionNumber: "2.1",
    title: "Units of Length", subject: "Mathematics",
    intuition: "Different lengths need different units: mm for tiny, cm for small, m for medium, km for large.",
    process_explanation: "Choose unit by size: pencil = cm, room = m, distance between cities = km.",
    worked_example: "Finger nail = 1 cm. Door = 2 m. School to home = 2 km.",
    common_misconceptions: "Using cm for huge distances or m for tiny things makes numbers awkward.",
    shortcuts_and_tricks: "Always pick the unit that gives the smallest sensible number.",
    key_takeaway: "Right unit makes measurements easier to read and use.",
  },
  {
    topicId: "math4_ch2_cm_m_km", chapterNumber: 2, sectionNumber: "2.2",
    title: "Converting cm, m, km", subject: "Mathematics",
    intuition: "10 mm = 1 cm. 100 cm = 1 m. 1000 m = 1 km. Each step is × 10 or × 1000.",
    process_explanation: "mm → cm: ÷ 10. cm → m: ÷ 100. m → km: ÷ 1000. Reverse for the other direction.",
    worked_example: "300 cm = 3 m. 5000 m = 5 km. 2 km = 2000 m = 200000 cm.",
    common_misconceptions: "Students mix conversion factors. Remember: 100 cm in 1 m; 1000 m in 1 km.",
    shortcuts_and_tricks: "× to go to smaller unit, ÷ to go to bigger unit.",
    key_takeaway: "Length units: mm, cm, m, km — convert using powers of 10.",
  },
  {
    topicId: "math4_ch2_measuring_distance", chapterNumber: 2, sectionNumber: "2.3",
    title: "Measuring Long Distances", subject: "Mathematics",
    intuition: "For long distances (city to city), kilometres are used. We can also walk and count steps.",
    process_explanation: "Use a measuring tape for medium distances. Use km for very long ones. Maps show distances in km.",
    worked_example: "A measuring tape can measure up to 30 m. For 100 km between cities, use a map.",
    common_misconceptions: "You can't measure km with a ruler — they're too long.",
    shortcuts_and_tricks: "1 km ≈ 12 minute walk for an adult.",
    key_takeaway: "Long distances use km and measuring tapes or maps.",
  },
  {
    topicId: "math4_ch2_comparing_long", chapterNumber: 2, sectionNumber: "2.4",
    title: "Comparing Long Things", subject: "Mathematics",
    intuition: "To compare two lengths, convert to the same unit and subtract.",
    process_explanation: "Convert both to mm/cm/m as needed. Then subtract smaller from bigger.",
    worked_example: "Bus = 12 m, car = 4 m → bus is 8 m longer. 2 km vs 1500 m: 2 km = 2000 m, so 2 km is 500 m longer.",
    common_misconceptions: "Forgetting to convert before comparing.",
    shortcuts_and_tricks: "Use the smallest unit if mixed (everything in cm or m).",
    key_takeaway: "Compare lengths in the same unit. Difference = bigger − smaller.",
  },

  // ── Chapter 3: A Trip to Bhopal ────────────────────────────────────────
  {
    topicId: "math4_ch3_four_digit_numbers", chapterNumber: 3, sectionNumber: "3.1",
    title: "Four-Digit Numbers", subject: "Mathematics",
    intuition: "After 999 comes 1000 — the smallest 4-digit number. 4-digit numbers go from 1000 to 9999.",
    process_explanation: "4-digit numbers have thousands, hundreds, tens, ones. 1000 = 1 thousand; 9999 = nine thousand nine hundred ninety-nine.",
    worked_example: "Number 4567 = 4 thousands + 5 hundreds + 6 tens + 7 ones.",
    common_misconceptions: "Students don't add the thousands place when reading 4-digit numbers.",
    shortcuts_and_tricks: "Read in 'thousand' groups: 4 5 6 7 → 'four thousand five hundred sixty-seven'.",
    key_takeaway: "4-digit numbers go from 1000 to 9999, with thousands as the new place.",
  },
  {
    topicId: "math4_ch3_distances", chapterNumber: 3, sectionNumber: "3.2",
    title: "Distance Between Places", subject: "Mathematics",
    intuition: "Distances between cities are measured in km, often hundreds or thousands.",
    process_explanation: "Use a map or distance chart. Add distances along the route to find total travel.",
    worked_example: "Delhi to Bhopal = 750 km. If you've travelled 250 km, you have 500 km left.",
    common_misconceptions: "Students confuse distance (km) with time (hours).",
    shortcuts_and_tricks: "Subtract distance covered to find distance remaining.",
    key_takeaway: "Distances between cities are big numbers in km — use addition/subtraction to plan.",
  },
  {
    topicId: "math4_ch3_travel_problems", chapterNumber: 3, sectionNumber: "3.3",
    title: "Travel Word Problems", subject: "Mathematics",
    intuition: "Travel problems involve distance, time, and speed. Distance = speed × time.",
    process_explanation: "Identify what's given (distance, time, or speed) and what's asked. Use the right formula or steps.",
    worked_example: "A train covers 60 km in 1 hour → speed = 60 km/h. In 4 hours, it covers 60 × 4 = 240 km.",
    common_misconceptions: "Students mix up speed and distance. Speed = how fast; distance = how far.",
    shortcuts_and_tricks: "Distance = speed × time. Speed = distance ÷ time. Time = distance ÷ speed.",
    key_takeaway: "Travel: distance, time, speed are linked. Use the right relationship.",
  },
  {
    topicId: "math4_ch3_place_value_thousands", chapterNumber: 3, sectionNumber: "3.4",
    title: "Place Value in Thousands", subject: "Mathematics",
    intuition: "The thousands place is 4 positions from the right. Its digit is worth 1000 times its face value.",
    process_explanation: "In 4567: 4 (thousands), 5 (hundreds), 6 (tens), 7 (ones). Place values: 4000, 500, 60, 7.",
    worked_example: "5862: 5 thousands + 8 hundreds + 6 tens + 2 ones = 5000 + 800 + 60 + 2.",
    common_misconceptions: "Students forget the thousands place adds value × 1000.",
    shortcuts_and_tricks: "Add the place values: thousands + hundreds + tens + ones = the number.",
    key_takeaway: "Thousands place gives 1000× its digit's value.",
  },

  // ── Chapter 4: Tick-Tick-Tick ──────────────────────────────────────────
  {
    topicId: "math4_ch4_reading_time", chapterNumber: 4, sectionNumber: "4.1",
    title: "Reading Time Precisely", subject: "Mathematics",
    intuition: "Time can be read to the minute. Short hand = hours; long hand = minutes (each number × 5).",
    process_explanation: "Hour hand position shows hours. Minute hand position × 5 gives minutes past.",
    worked_example: "Short on 4, long on 8 → 8 × 5 = 40 minutes → 4:40.",
    common_misconceptions: "Students count the long hand as raw position, forgetting × 5.",
    shortcuts_and_tricks: "Memorise minute marks: 1→5, 2→10, 3→15, 4→20, 5→25, 6→30, etc.",
    key_takeaway: "Read time as 'hours : minutes'. Long hand × 5 = minutes.",
  },
  {
    topicId: "math4_ch4_24_hour_clock", chapterNumber: 4, sectionNumber: "4.2",
    title: "24-Hour Clock", subject: "Mathematics",
    intuition: "24-hour clock counts continuously from 00:00 (midnight) to 23:59 (one minute before midnight).",
    process_explanation: "After 12 noon, add 12 to the hour: 1 PM = 13:00, 2 PM = 14:00, ..., 11 PM = 23:00.",
    worked_example: "5 PM = 17:00 (5 + 12). 8 AM = 08:00. Midnight = 00:00.",
    common_misconceptions: "Students confuse 12 AM and 12 PM. Midnight = 00:00; noon = 12:00.",
    shortcuts_and_tricks: "12-hour PM → 24-hour: add 12. 12-hour AM stays the same (except 12 AM = 00).",
    key_takeaway: "24-hour clock removes AM/PM confusion. Hours go 00 to 23.",
  },
  {
    topicId: "math4_ch4_time_intervals", chapterNumber: 4, sectionNumber: "4.3",
    title: "Time Intervals and Duration", subject: "Mathematics",
    intuition: "Duration = end time − start time. Subtract carefully across hours.",
    process_explanation: "Subtract minutes first; if not enough, borrow 60 minutes from hours. Then subtract hours.",
    worked_example: "From 9:50 to 11:20: 20 − 50 → borrow, 80 − 50 = 30 min; hours: 10 − 9 = 1. Duration = 1 hr 30 min.",
    common_misconceptions: "Students treat minutes like regular subtraction (no borrow concept).",
    shortcuts_and_tricks: "60 min = 1 hour. Borrow 60 minutes when needed.",
    key_takeaway: "Duration = end − start. Borrow 60 min from hours when subtracting minutes.",
  },
  {
    topicId: "math4_ch4_calendar_year", chapterNumber: 4, sectionNumber: "4.4",
    title: "Calendar — Full Year", subject: "Mathematics",
    intuition: "A year has 365 days (366 in leap year), 12 months, 52 weeks.",
    process_explanation: "Knuckle trick for days: knuckle = 31-day month; gap = 30-day (except Feb).",
    worked_example: "Jan 31, Feb 28/29, Mar 31, Apr 30, May 31, Jun 30, Jul 31, Aug 31, Sep 30, Oct 31, Nov 30, Dec 31. Total: 365 (or 366).",
    common_misconceptions: "Forgetting which months have 30 vs 31 days.",
    shortcuts_and_tricks: "Knuckles count Jan to Jul: J(31)F(28)M(31)A(30)M(31)J(30)J(31). Then back: A(31)S(30)O(31)N(30)D(31).",
    key_takeaway: "Year: 12 months, 365/366 days. Use knuckle trick for days per month.",
  },

  // ── Chapter 5: The Way The World Looks ─────────────────────────────────
  {
    topicId: "math4_ch5_top_view", chapterNumber: 5, sectionNumber: "5.1",
    title: "Top View of Objects", subject: "Mathematics",
    intuition: "Looking down on something is the top view. Useful for maps, blueprints, and bird's-eye drawings.",
    process_explanation: "Imagine standing above the object. Draw the outline of what you see directly below.",
    worked_example: "A table from above is a rectangle. A house from above shows a roof.",
    common_misconceptions: "Students draw what they think the object looks like, not the top view.",
    shortcuts_and_tricks: "Hold object below your eye and look down. That's the top view.",
    key_takeaway: "Top view = view from straight above.",
  },
  {
    topicId: "math4_ch5_side_view", chapterNumber: 5, sectionNumber: "5.2",
    title: "Side View and Profile", subject: "Mathematics",
    intuition: "The side view shows an object's profile — what you see from the left or right.",
    process_explanation: "Stand to the side. Draw the outline from that angle.",
    worked_example: "A car from the side shows wheels, doors, and a body outline. A pyramid from the side is a triangle.",
    common_misconceptions: "Side view ≠ front view. Different orientations give different shapes.",
    shortcuts_and_tricks: "Take a photo from the side — that's the side view.",
    key_takeaway: "Side view = profile from the left or right.",
  },
  {
    topicId: "math4_ch5_maps", chapterNumber: 5, sectionNumber: "5.3",
    title: "Reading Maps", subject: "Mathematics",
    intuition: "Maps show places from a top view. They have keys for streets, parks, buildings.",
    process_explanation: "Look at the map's key (legend) to understand symbols. Use the scale to estimate distances.",
    worked_example: "On a city map, blue = water, green = parks, red lines = main roads. Scale: 1 cm = 100 m.",
    common_misconceptions: "Students ignore the map scale, leading to wrong distance estimates.",
    shortcuts_and_tricks: "Always check the scale and key before using a map.",
    key_takeaway: "Maps are top views with keys and scales for navigation.",
  },
  {
    topicId: "math4_ch5_directions", chapterNumber: 5, sectionNumber: "5.4",
    title: "Directions — North, East, South, West", subject: "Mathematics",
    intuition: "Maps have four main directions: N (up), E (right), S (down), W (left).",
    process_explanation: "Find north on the map (usually arrow pointing up). Other directions follow.",
    worked_example: "If north is up: east is right, south is down, west is left.",
    common_misconceptions: "Students think north is always toward the sun. North depends on location.",
    shortcuts_and_tricks: "NEWS clockwise: N → E → S → W.",
    key_takeaway: "Directions: N up, E right, S down, W left. Always check map's north arrow.",
  },

  // ── Chapter 6: The Junk Seller ─────────────────────────────────────────
  {
    topicId: "math4_ch6_money_calculations", chapterNumber: 6, sectionNumber: "6.1",
    title: "Money Calculations", subject: "Mathematics",
    intuition: "Money math uses addition, subtraction, multiplication, division. Same as numbers but with ₹.",
    process_explanation: "Line up decimals (rupees and paise). Use same operations as integers.",
    worked_example: "Buying 3 toys at ₹15 each: 3 × 15 = ₹45.",
    common_misconceptions: "Mixing up rupees and paise without converting.",
    shortcuts_and_tricks: "Convert everything to paise (no decimals) for tricky problems, then convert back.",
    key_takeaway: "Money math is regular math with ₹. Mind decimals and units.",
  },
  {
    topicId: "math4_ch6_buying_selling", chapterNumber: 6, sectionNumber: "6.2",
    title: "Buying and Selling", subject: "Mathematics",
    intuition: "When you buy, you spend money. When you sell, you receive money. Profit = selling price − cost price.",
    process_explanation: "Identify cost (buying) and selling prices. Subtract to find profit or loss.",
    worked_example: "Junk seller buys 10 kg paper at ₹5/kg = ₹50. Sells at ₹8/kg = ₹80. Profit = 80 − 50 = ₹30.",
    common_misconceptions: "Confusing profit with total selling price.",
    shortcuts_and_tricks: "Profit = SP − CP. Loss = CP − SP.",
    key_takeaway: "Buying and selling: profit/loss = price difference between buying and selling.",
  },
  {
    topicId: "math4_ch6_change_money", chapterNumber: 6, sectionNumber: "6.3",
    title: "Calculating Change", subject: "Mathematics",
    intuition: "Change = money given − cost. Always check if you got the right change back.",
    process_explanation: "Subtract cost from money paid to find change.",
    worked_example: "Cost = ₹78. Paid ₹100. Change = 100 − 78 = ₹22.",
    common_misconceptions: "Adding instead of subtracting. Change is always subtract.",
    shortcuts_and_tricks: "Round up cost to nearest 10/100 mentally, then adjust.",
    key_takeaway: "Change = paid − cost. Always subtract.",
  },
  {
    topicId: "math4_ch6_money_word_problems", chapterNumber: 6, sectionNumber: "6.4",
    title: "Money Word Problems", subject: "Mathematics",
    intuition: "Word problems describe real situations: buying, selling, change, profit, loss.",
    process_explanation: "Read carefully. Find numbers. Choose operation (×, +, −). Solve. Label with ₹.",
    worked_example: "Mom has ₹500. Buys 3 books at ₹120 each. Money left = 500 − (3 × 120) = 500 − 360 = ₹140.",
    common_misconceptions: "Doing one operation when the problem needs two (e.g., multiply then subtract).",
    shortcuts_and_tricks: "Solve in steps. Multi-step problems need each step in order.",
    key_takeaway: "Money word problems often need multiple operations in sequence.",
  },

  // ── Chapter 7: Jugs and Mugs ───────────────────────────────────────────
  {
    topicId: "math4_ch7_ml_l_conversion", chapterNumber: 7, sectionNumber: "7.1",
    title: "Millilitres and Litres Conversion", subject: "Mathematics",
    intuition: "1 litre (L) = 1000 millilitres (ml). Use L for big amounts, ml for small.",
    process_explanation: "L → ml: × 1000. ml → L: ÷ 1000.",
    worked_example: "2 L = 2000 ml. 750 ml = 0.75 L (or 750 ÷ 1000).",
    common_misconceptions: "Mistaking 1 L for 100 ml.",
    shortcuts_and_tricks: "Move decimal 3 places: L → ml right; ml → L left.",
    key_takeaway: "1 L = 1000 ml. Convert by × or ÷ 1000.",
  },
  {
    topicId: "math4_ch7_measuring_capacity", chapterNumber: 7, sectionNumber: "7.2",
    title: "Measuring Capacity", subject: "Mathematics",
    intuition: "Capacity = how much liquid a container holds. We measure with marked containers (jugs, cups).",
    process_explanation: "Pour liquid into a marked container. Read the level at eye height.",
    worked_example: "Jug shows 750 ml when filled to that line. Add 250 ml more → 1000 ml = 1 L.",
    common_misconceptions: "Reading level from above gives wrong answer. Always read at eye level.",
    shortcuts_and_tricks: "Use the smallest container that fits the volume for accuracy.",
    key_takeaway: "Capacity is measured with marked containers, read at eye level.",
  },
  {
    topicId: "math4_ch7_comparing_capacity", chapterNumber: 7, sectionNumber: "7.3",
    title: "Comparing Capacities", subject: "Mathematics",
    intuition: "Convert to same unit, then compare. Use ml or L throughout.",
    process_explanation: "Convert L to ml (or vice versa). Compare numbers directly.",
    worked_example: "Compare 1 L vs 750 ml: 1 L = 1000 ml → 1000 > 750 → 1 L bigger.",
    common_misconceptions: "Comparing 1 vs 750 without converting (gives wrong answer).",
    shortcuts_and_tricks: "Always convert to smaller unit first for clarity.",
    key_takeaway: "Compare capacities in the same unit.",
  },
  {
    topicId: "math4_ch7_capacity_problems", chapterNumber: 7, sectionNumber: "7.4",
    title: "Capacity Word Problems", subject: "Mathematics",
    intuition: "Real problems: filling, emptying, sharing liquid. Use addition, subtraction, multiplication, division.",
    process_explanation: "Identify total, used, remaining. Convert units if mixed. Choose operation.",
    worked_example: "Tank has 50 L. After 18 L used, 32 L remain. To fill back to 50, add 18 L.",
    common_misconceptions: "Forgetting unit conversion mid-problem.",
    shortcuts_and_tricks: "Solve step by step. Keep units consistent throughout.",
    key_takeaway: "Capacity problems = real-life arithmetic with liquid measures.",
  },

  // ── Chapter 8: Carts and Wheels ────────────────────────────────────────
  {
    topicId: "math4_ch8_circles", chapterNumber: 8, sectionNumber: "8.1",
    title: "Circles — Basics", subject: "Mathematics",
    intuition: "A circle is a closed curve where every point is the same distance from the centre.",
    process_explanation: "Draw a circle with a compass: fix centre, swing pencil at constant distance.",
    worked_example: "Pizza, plate, coin, wheel — all are circles. Distance from centre is the radius.",
    common_misconceptions: "Confusing circle (boundary) with disc (filled area).",
    shortcuts_and_tricks: "Compass = circle drawer. Radius = pencil distance from centre.",
    key_takeaway: "A circle is a curve where every point is equidistant from the centre.",
  },
  {
    topicId: "math4_ch8_circle_parts", chapterNumber: 8, sectionNumber: "8.2",
    title: "Parts of a Circle", subject: "Mathematics",
    intuition: "Centre, radius (centre to edge), diameter (across, through centre = 2 × radius), circumference (around).",
    process_explanation: "Radius = half diameter. Diameter = 2 × radius. Circumference = perimeter of circle.",
    worked_example: "Radius 5 cm → diameter 10 cm. A wheel of diameter 50 cm has radius 25 cm.",
    common_misconceptions: "Diameter and radius are different! Diameter = 2 × radius.",
    shortcuts_and_tricks: "Diameter always goes through the centre, edge to edge.",
    key_takeaway: "Circle parts: centre, radius (r), diameter (d = 2r), circumference.",
  },
  {
    topicId: "math4_ch8_circular_objects", chapterNumber: 8, sectionNumber: "8.3",
    title: "Circular Objects in Daily Life", subject: "Mathematics",
    intuition: "Many everyday things are circular: wheels, plates, clocks, rings, coins.",
    process_explanation: "Identify objects with circular faces/cross-sections. Notice their use.",
    worked_example: "Wheels: easy to roll. Plates: easy to wash. Coins: fit any orientation.",
    common_misconceptions: "Students think only flat circles count — cylinders also have circular faces.",
    shortcuts_and_tricks: "Circular things often roll or rotate.",
    key_takeaway: "Circles appear everywhere — anywhere we want smooth rotation or no corners.",
  },
  {
    topicId: "math4_ch8_rotation", chapterNumber: 8, sectionNumber: "8.4",
    title: "Rotation and Wheels", subject: "Mathematics",
    intuition: "A wheel rolls smoothly because it's circular. Each rotation moves it forward by its circumference.",
    process_explanation: "1 full rotation of a wheel = wheel moves forward by its circumference (≈ 3.14 × diameter).",
    worked_example: "A wheel diameter 100 cm rolls forward ≈ 314 cm per rotation.",
    common_misconceptions: "Bigger wheel doesn't mean faster — depends on revolutions per minute too.",
    shortcuts_and_tricks: "Circumference ≈ 3.14 × diameter.",
    key_takeaway: "A wheel's rotation moves the cart forward by the wheel's circumference each turn.",
  },

  // ── Chapter 9: Halves and Quarters ─────────────────────────────────────
  {
    topicId: "math4_ch9_fractions_intro", chapterNumber: 9, sectionNumber: "9.1",
    title: "Introduction to Fractions", subject: "Mathematics",
    intuition: "A fraction is a part of a whole. ½ means 1 part out of 2 equal parts.",
    process_explanation: "Fraction = numerator / denominator. Top = how many parts. Bottom = total equal parts.",
    worked_example: "Pizza cut in 4. You eat 1 slice → you ate ¼. 3 slices left → ¾ remaining.",
    common_misconceptions: "Bigger denominator means smaller pieces, not bigger.",
    shortcuts_and_tricks: "Bigger denominator → smaller fraction (for same numerator).",
    key_takeaway: "Fraction = part / whole. Top is parts taken; bottom is total parts.",
  },
  {
    topicId: "math4_ch9_halves", chapterNumber: 9, sectionNumber: "9.2",
    title: "Halves", subject: "Mathematics",
    intuition: "A half (½) splits something into 2 equal parts.",
    process_explanation: "Cut along the middle. Each part is half the whole.",
    worked_example: "Half of 10 = 5. Half of an apple is 1 piece out of 2 equal pieces.",
    common_misconceptions: "Halves must be equal — not just any two pieces.",
    shortcuts_and_tricks: "Half of N = N ÷ 2.",
    key_takeaway: "Half = one of 2 equal parts. ½ = 1/2.",
  },
  {
    topicId: "math4_ch9_quarters", chapterNumber: 9, sectionNumber: "9.3",
    title: "Quarters", subject: "Mathematics",
    intuition: "A quarter (¼) splits something into 4 equal parts.",
    process_explanation: "Cut into 4 equal pieces. Each is one-quarter.",
    worked_example: "Quarter of 20 = 5. ¼ of an hour = 15 minutes.",
    common_misconceptions: "Confusing ¼ with ½. Quarter is smaller (1/4 < 1/2).",
    shortcuts_and_tricks: "Quarter of N = N ÷ 4. ¾ = three quarters = 3 × ¼.",
    key_takeaway: "Quarter = one of 4 equal parts. ¼ = 1/4.",
  },
  {
    topicId: "math4_ch9_fraction_word", chapterNumber: 9, sectionNumber: "9.4",
    title: "Fraction Word Problems", subject: "Mathematics",
    intuition: "Real problems use halves and quarters: cutting cakes, sharing pizzas, telling time.",
    process_explanation: "Identify whole, then take the fraction. Divide and (if needed) multiply.",
    worked_example: "If a cake is cut in 8 pieces, 4 pieces = ½ the cake. Quarter past 3 = 3:15.",
    common_misconceptions: "Splitting unequal parts and calling them fractions. Parts must be equal.",
    shortcuts_and_tricks: "Visualise with pies or rectangles to check answers.",
    key_takeaway: "Fraction word problems = real-life sharing and parts of wholes.",
  },

  // ── Chapter 10: Play with Patterns ─────────────────────────────────────
  {
    topicId: "math4_ch10_number_patterns", chapterNumber: 10, sectionNumber: "10.1",
    title: "Number Patterns", subject: "Mathematics",
    intuition: "Numbers in a sequence often follow a rule (add, subtract, multiply).",
    process_explanation: "Find difference between terms. If constant, rule is 'add n each step'. If grows, more complex.",
    worked_example: "5, 10, 15, 20, ... → +5 each step. Next = 25.",
    common_misconceptions: "Stopping at first 2 terms and guessing. Check at least 3 differences.",
    shortcuts_and_tricks: "Look at differences. Constant diff = arithmetic pattern.",
    key_takeaway: "Number patterns follow rules. Find the rule from differences.",
  },
  {
    topicId: "math4_ch10_shape_patterns", chapterNumber: 10, sectionNumber: "10.2",
    title: "Shape Patterns", subject: "Mathematics",
    intuition: "Shapes can repeat in patterns: △◯△◯△◯... Find the repeating unit.",
    process_explanation: "Identify smallest repeating block. Continue by repeating.",
    worked_example: "□△□△ → unit is □△. Next would be □, then △.",
    common_misconceptions: "Not identifying the FULL unit, missing complex patterns.",
    shortcuts_and_tricks: "Find smallest repeating block, then repeat.",
    key_takeaway: "Shape patterns repeat a unit. Identify the unit, then continue.",
  },
  {
    topicId: "math4_ch10_skipping_patterns", chapterNumber: 10, sectionNumber: "10.3",
    title: "Skipping (Skip-Count) Patterns", subject: "Mathematics",
    intuition: "Skip counting jumps by a fixed amount: 2, 4, 6, ... (skip by 2) or 5, 10, 15, ... (skip by 5).",
    process_explanation: "Choose a step size. Start at a number. Add the step repeatedly.",
    worked_example: "Skip by 3 from 0: 0, 3, 6, 9, 12, 15, 18, ...",
    common_misconceptions: "Confusing skip-counting with multiplication tables (they're related).",
    shortcuts_and_tricks: "Skip by N = table of N.",
    key_takeaway: "Skip counting = repeated addition by a step size. Same as times tables.",
  },
  {
    topicId: "math4_ch10_pattern_rules", chapterNumber: 10, sectionNumber: "10.4",
    title: "Finding Pattern Rules", subject: "Mathematics",
    intuition: "Every pattern has a rule. Try add, subtract, multiply, divide until something fits.",
    process_explanation: "Compute differences or ratios between consecutive terms. Test the candidate rule.",
    worked_example: "2, 6, 18, 54 → ×3 each step (rule: multiply by 3).",
    common_misconceptions: "Assuming rule is always 'add'. Sometimes it's 'multiply' or 'subtract'.",
    shortcuts_and_tricks: "Try addition first; if differences vary, try multiplication.",
    key_takeaway: "Every pattern has a rule. Try +, −, ×, ÷ until one fits.",
  },

  // ── Chapter 11: Tables and Shares ──────────────────────────────────────
  {
    topicId: "math4_ch11_times_tables", chapterNumber: 11, sectionNumber: "11.1",
    title: "Times Tables (2 to 10)", subject: "Mathematics",
    intuition: "Times tables show multiples of each number from 1 to 10. Knowing them speeds up multiplication.",
    process_explanation: "Memorise patterns. Table of 5 ends in 0 or 5. Table of 2 = even. Table of 9: digits sum to 9.",
    worked_example: "Table of 7: 7, 14, 21, 28, 35, 42, 49, 56, 63, 70.",
    common_misconceptions: "Tables aren't random — they have patterns.",
    shortcuts_and_tricks: "9's table: count down, then complement (9×3=27, 2+7=9).",
    key_takeaway: "Times tables (2-10) are foundation of fast multiplication.",
  },
  {
    topicId: "math4_ch11_division_tables", chapterNumber: 11, sectionNumber: "11.2",
    title: "Division Tables", subject: "Mathematics",
    intuition: "Division tables are times tables read backwards. If 6 × 4 = 24, then 24 ÷ 4 = 6.",
    process_explanation: "For 30 ÷ 6, find what × 6 = 30. Answer: 5.",
    worked_example: "30 ÷ 5 = 6 (because 5 × 6 = 30). 56 ÷ 7 = 8 (because 7 × 8 = 56).",
    common_misconceptions: "Trying to divide without knowing the matching multiplication.",
    shortcuts_and_tricks: "Division = times table backwards.",
    key_takeaway: "Division tables use multiplication knowledge in reverse.",
  },
  {
    topicId: "math4_ch11_sharing", chapterNumber: 11, sectionNumber: "11.3",
    title: "Sharing Equally", subject: "Mathematics",
    intuition: "Division is equal sharing. 24 ÷ 4 means 24 items split among 4 people equally.",
    process_explanation: "Total ÷ number of groups = items per group. Items per group × groups = total.",
    worked_example: "24 chocolates shared among 4 kids → each gets 6 (24 ÷ 4).",
    common_misconceptions: "Forgetting remainder when sharing doesn't divide evenly.",
    shortcuts_and_tricks: "Total ÷ groups = per group. Check: per × groups = total.",
    key_takeaway: "Equal sharing = division. Total ÷ groups = per group.",
  },
  {
    topicId: "math4_ch11_grouping", chapterNumber: 11, sectionNumber: "11.4",
    title: "Grouping Numbers", subject: "Mathematics",
    intuition: "Grouping is making equal-sized groups. 20 items into groups of 5 → 4 groups.",
    process_explanation: "Total ÷ group size = number of groups.",
    worked_example: "20 ÷ 5 = 4 groups. 36 students in groups of 6 → 6 groups.",
    common_misconceptions: "Mixing 'sharing' (groups given) with 'grouping' (size given).",
    shortcuts_and_tricks: "Both are division — direction differs.",
    key_takeaway: "Grouping: total ÷ group size = number of groups.",
  },

  // ── Chapter 12: How Heavy? How Light? ──────────────────────────────────
  {
    topicId: "math4_ch12_weight_units", chapterNumber: 12, sectionNumber: "12.1",
    title: "Weight Units", subject: "Mathematics",
    intuition: "Weight measures how heavy something is. Units: gram (g) for light; kilogram (kg) for heavy.",
    process_explanation: "g for paperclips, food packets, fruits. kg for textbooks, rice bags, people.",
    worked_example: "Pencil ≈ 5 g. Apple ≈ 200 g. Person ≈ 50 kg.",
    common_misconceptions: "Weight vs mass — for school level, treat as the same.",
    shortcuts_and_tricks: "Light = g. Heavy = kg.",
    key_takeaway: "g for light things, kg for heavy things.",
  },
  {
    topicId: "math4_ch12_grams_kilograms", chapterNumber: 12, sectionNumber: "12.2",
    title: "Grams and Kilograms Conversion", subject: "Mathematics",
    intuition: "1 kg = 1000 g. Convert by × 1000 or ÷ 1000.",
    process_explanation: "kg → g: multiply by 1000. g → kg: divide by 1000.",
    worked_example: "3 kg = 3000 g. 500 g = 0.5 kg.",
    common_misconceptions: "Thinking 1 kg = 100 g.",
    shortcuts_and_tricks: "Move decimal 3 places left/right.",
    key_takeaway: "1 kg = 1000 g.",
  },
  {
    topicId: "math4_ch12_comparing_weights", chapterNumber: 12, sectionNumber: "12.3",
    title: "Comparing Weights", subject: "Mathematics",
    intuition: "Convert to same unit, then compare numbers.",
    process_explanation: "If mixed units, convert all to g (or all to kg). Compare numbers.",
    worked_example: "1 kg vs 800 g → 1000 vs 800 → 1 kg heavier.",
    common_misconceptions: "Skipping conversion before comparing.",
    shortcuts_and_tricks: "Smaller unit first for clarity.",
    key_takeaway: "Compare weights in same unit.",
  },
  {
    topicId: "math4_ch12_weight_problems", chapterNumber: 12, sectionNumber: "12.4",
    title: "Weight Word Problems", subject: "Mathematics",
    intuition: "Weight problems involve adding, subtracting, multiplying weights of objects.",
    process_explanation: "Read carefully. Convert if needed. Choose operation. Label answer with unit.",
    worked_example: "A bag of rice = 5 kg. A bag of flour = 2 kg. Total = 5 + 2 = 7 kg.",
    common_misconceptions: "Mixing units in calculations.",
    shortcuts_and_tricks: "Convert all to g, calculate, then convert final to kg if huge.",
    key_takeaway: "Weight problems = arithmetic with units. Stay consistent.",
  },

  // ── Chapter 13: Fields and Fences ──────────────────────────────────────
  {
    topicId: "math4_ch13_perimeter_intro", chapterNumber: 13, sectionNumber: "13.1",
    title: "Perimeter — Introduction", subject: "Mathematics",
    intuition: "Perimeter = total distance around a closed shape. Like fencing a field.",
    process_explanation: "Add up all the sides of the shape.",
    worked_example: "Rectangle with sides 5 and 3: perimeter = 5 + 3 + 5 + 3 = 16. Triangle 3, 4, 5: perimeter = 12.",
    common_misconceptions: "Confusing perimeter (boundary) with area (inside).",
    shortcuts_and_tricks: "For rectangles: P = 2(l + w).",
    key_takeaway: "Perimeter = sum of all sides = distance around.",
  },
  {
    topicId: "math4_ch13_perimeter_shapes", chapterNumber: 13, sectionNumber: "13.2",
    title: "Perimeter of Common Shapes", subject: "Mathematics",
    intuition: "Square: 4 × side. Rectangle: 2 × (length + width). Triangle: a + b + c.",
    process_explanation: "Use the formula for known shapes. For irregular, add all sides.",
    worked_example: "Square side 6 → P = 4 × 6 = 24. Rectangle 8 × 5 → P = 2 × (8 + 5) = 26.",
    common_misconceptions: "Adding instead of multiplying when sides are equal.",
    shortcuts_and_tricks: "Square = 4s. Rectangle = 2(l+w).",
    key_takeaway: "Common shapes have perimeter formulas: square = 4s, rectangle = 2(l+w).",
  },
  {
    topicId: "math4_ch13_area_intro", chapterNumber: 13, sectionNumber: "13.3",
    title: "Area — Introduction", subject: "Mathematics",
    intuition: "Area = space inside a flat shape. Measured in square units (cm², m²).",
    process_explanation: "Cover the shape with square units. Count them.",
    worked_example: "A rectangle of 3 × 4 squares has area 12 sq units.",
    common_misconceptions: "Confusing area (inside) with perimeter (boundary).",
    shortcuts_and_tricks: "For rectangles, area = length × width.",
    key_takeaway: "Area = space inside, measured in square units.",
  },
  {
    topicId: "math4_ch13_area_squares", chapterNumber: 13, sectionNumber: "13.4",
    title: "Counting Squares for Area", subject: "Mathematics",
    intuition: "On grid paper, count the squares inside the shape to find its area.",
    process_explanation: "Count whole squares. Add half-squares (= 0.5 each).",
    worked_example: "A triangle covering 3 whole squares and 2 half squares: area = 3 + 1 = 4 sq units.",
    common_misconceptions: "Counting partial squares as whole.",
    shortcuts_and_tricks: "Half square = 0.5. Two halves = 1.",
    key_takeaway: "Count whole + half squares to find area on grid paper.",
  },

  // ── Chapter 14: Smart Charts ───────────────────────────────────────────
  {
    topicId: "math4_ch14_pictographs", chapterNumber: 14, sectionNumber: "14.1",
    title: "Pictographs", subject: "Mathematics",
    intuition: "Pictograph uses pictures to show counts. Each picture = a fixed value (the key).",
    process_explanation: "Count pictures in each row × key = total.",
    worked_example: "If each ★ = 5: a row with 4 stars = 20.",
    common_misconceptions: "Forgetting to multiply by the key.",
    shortcuts_and_tricks: "Always read the key first.",
    key_takeaway: "Pictograph: count symbols × key value.",
  },
  {
    topicId: "math4_ch14_bar_graphs", chapterNumber: 14, sectionNumber: "14.2",
    title: "Bar Graphs", subject: "Mathematics",
    intuition: "Bar graph uses rectangles of different heights to show data.",
    process_explanation: "x-axis: categories. y-axis: values. Bar height = value.",
    worked_example: "Bar graph of pets: dogs=10, cats=8. Dog bar is taller.",
    common_misconceptions: "Misreading the y-axis scale.",
    shortcuts_and_tricks: "Read scale carefully before reading bars.",
    key_takeaway: "Bar graph: height = value. Compare by looking at heights.",
  },
  {
    topicId: "math4_ch14_reading_charts", chapterNumber: 14, sectionNumber: "14.3",
    title: "Reading Charts and Tables", subject: "Mathematics",
    intuition: "Charts and tables organise data. Find the right row/column to answer.",
    process_explanation: "Identify what's asked. Find the row/column. Read the value.",
    worked_example: "Table: Day | Books read. Find Monday's value to answer 'How many on Monday?'",
    common_misconceptions: "Reading wrong row/column.",
    shortcuts_and_tricks: "Use finger to trace row and column.",
    key_takeaway: "Read charts/tables by finding the right cell or bar.",
  },
  {
    topicId: "math4_ch14_data_collection", chapterNumber: 14, sectionNumber: "14.4",
    title: "Collecting and Organising Data", subject: "Mathematics",
    intuition: "Before charting, you need data. Collect by asking, observing, or measuring.",
    process_explanation: "Decide question. Collect data using tally marks. Organise in a table. Chart it.",
    worked_example: "Survey: favourite fruit. Tally: apple=10, banana=8, mango=5. Make a bar graph.",
    common_misconceptions: "Skipping the tally step and trying to remember everything.",
    shortcuts_and_tricks: "Tally as you go. Don't trust memory.",
    key_takeaway: "Data flow: collect → tally → table → chart.",
  },
];

const toSchema = (t) => ({
  topicId: t.topicId, chapterNumber: t.chapterNumber, subject: t.subject || "Mathematics",
  name: t.title || t.name || t.topicId,
  teaching_content: { intuition: t.intuition || "", derivation: t.process_explanation || "", process_explanation: t.process_explanation || "", worked_example: t.worked_example || "", common_misconceptions: t.common_misconceptions || "", shortcuts_and_tricks: t.shortcuts_and_tricks || "", key_takeaway: t.key_takeaway || "" },
});

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log(`Seeding ${topics.length} Class 4 Math v2 sub-topics...`);
  for (const t of topics) {
    await NcertTopicContent.findOneAndUpdate({ topicId: t.topicId }, { $set: toSchema(t) }, { upsert: true, new: true });
  }
  console.log(`Seeded ${topics.length} Class 4 Math v2 sub-topics.`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
