/**
 * CBSE Class 9 Mathematics — Questions v2A (Ch1–Ch2, 64 questions)
 * 8 questions per sub-topic × 4 sub-topics × 2 chapters = 64 total
 * Usage: node config/seedMath9QuestionsV2A.js
 */
import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const questions = [

  // ── Ch1 · Sub-topic 1: The Cartesian Plane ──────────────────────────────────
  {
    questionId: "math9_ch1_cartesian_plane_q1", topicId: "math9_ch1_cartesian_plane",
    text: "A point lies in the third quadrant. Which of the following correctly describes its coordinates?",
    options: [
      { text: "Both x and y are positive", type: "concept_error", logicTag: "wrong quadrant" },
      { text: "x is negative, y is positive", type: "concept_error", logicTag: "Q2 confusion" },
      { text: "Both x and y are negative", type: "correct", logicTag: "Q3 definition" },
      { text: "x is positive, y is negative", type: "concept_error", logicTag: "Q4 confusion" },
    ],
    explanation: "Q3 is bottom-left: both x and y are negative. Q1(+,+), Q2(−,+), Q3(−,−), Q4(+,−).",
    solutionSteps: ["Q1: (+,+) top-right", "Q2: (−,+) top-left", "Q3: (−,−) bottom-left ← answer", "Q4: (+,−) bottom-right"],
    shortcut: "Sign pattern anticlockwise from Q1: ++, −+, −−, +−",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_cartesian_plane_q2", topicId: "math9_ch1_cartesian_plane",
    text: "The point (0, −5) lies on which axis?",
    options: [
      { text: "Positive x-axis", type: "concept_error", logicTag: "axis confusion" },
      { text: "Negative x-axis", type: "concept_error", logicTag: "axis confusion" },
      { text: "Positive y-axis", type: "concept_error", logicTag: "sign error" },
      { text: "Negative y-axis", type: "correct", logicTag: "y-axis, y<0" },
    ],
    explanation: "x=0 means the point is on the y-axis. y=−5 is negative, so it's on the negative y-axis.",
    solutionSteps: ["x=0 → point is on y-axis", "y=−5 < 0 → negative y-axis"],
    shortcut: "x=0 → y-axis. y=0 → x-axis. Both=0 → origin.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_cartesian_plane_q3", topicId: "math9_ch1_cartesian_plane",
    text: "Point P(−3, 4) is reflected across the x-axis. What are the coordinates of the reflected point?",
    options: [
      { text: "(3, 4)", type: "concept_error", logicTag: "reflected across y-axis" },
      { text: "(−3, −4)", type: "correct", logicTag: "x-axis reflection negates y" },
      { text: "(3, −4)", type: "concept_error", logicTag: "both negated" },
      { text: "(−3, 4)", type: "concept_error", logicTag: "no change" },
    ],
    explanation: "Reflection across x-axis: x stays the same, y changes sign. (−3, 4) → (−3, −4).",
    solutionSteps: ["Across x-axis: y → −y", "x unchanged: x = −3", "y negated: 4 → −4", "Result: (−3, −4)"],
    shortcut: "Across x-axis → negate y. Across y-axis → negate x.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_cartesian_plane_q4", topicId: "math9_ch1_cartesian_plane",
    text: "If a point (a, b) lies in Q2, which of the following must be true?",
    options: [
      { text: "a > 0 and b > 0", type: "concept_error", logicTag: "Q1" },
      { text: "a < 0 and b > 0", type: "correct", logicTag: "Q2 definition" },
      { text: "a < 0 and b < 0", type: "concept_error", logicTag: "Q3" },
      { text: "a > 0 and b < 0", type: "concept_error", logicTag: "Q4" },
    ],
    explanation: "Q2 (top-left): x is negative, y is positive. So a<0 and b>0.",
    solutionSteps: ["Q2 is top-left quadrant", "x-coordinate (a) is negative", "y-coordinate (b) is positive"],
    shortcut: "Memorise: Q2 has the (−,+) sign pattern.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_cartesian_plane_q5", topicId: "math9_ch1_cartesian_plane",
    text: "How many quadrants does the Cartesian plane have, and what is the name of the intersection point of the two axes?",
    options: [
      { text: "2 quadrants; intersection called the midpoint", type: "concept_error", logicTag: "wrong count" },
      { text: "4 quadrants; intersection called the origin", type: "correct", logicTag: "correct definition" },
      { text: "4 quadrants; intersection called the vertex", type: "concept_error", logicTag: "wrong term" },
      { text: "6 quadrants; intersection called the origin", type: "concept_error", logicTag: "wrong count" },
    ],
    explanation: "Two perpendicular axes divide the plane into exactly 4 quadrants. Their intersection is the origin (0,0).",
    solutionSteps: ["Two axes cross at one point", "This divides the plane into 4 regions = 4 quadrants", "Intersection = origin (0,0)"],
    shortcut: "Quad = 4. Origin = (0,0).",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_cartesian_plane_q6", topicId: "math9_ch1_cartesian_plane",
    text: "A point has equal positive x and y coordinates. In which quadrant or axis does it lie?",
    options: [
      { text: "Q1, on the line y = x", type: "correct", logicTag: "equal positive coords" },
      { text: "Q3, on the line y = x", type: "concept_error", logicTag: "equal but negative" },
      { text: "On the x-axis", type: "concept_error", logicTag: "y=0 confusion" },
      { text: "Q2", type: "concept_error", logicTag: "sign error" },
    ],
    explanation: "Equal positive x and y means x>0, y>0 → Q1. The set of all such points forms the line y=x in Q1.",
    solutionSteps: ["x > 0, y > 0 → Q1", "x = y → all points lie on the line y = x"],
    shortcut: "y=x bisects Q1 and Q3. Positive equal coords → Q1 portion.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_cartesian_plane_q7", topicId: "math9_ch1_cartesian_plane",
    text: "The abscissa of a point is −4 and its ordinate is 0. Where does this point lie?",
    options: [
      { text: "Negative y-axis", type: "concept_error", logicTag: "swapped axes" },
      { text: "Negative x-axis", type: "correct", logicTag: "ordinate=0 means x-axis" },
      { text: "Q3", type: "concept_error", logicTag: "would need y<0 too" },
      { text: "Origin", type: "concept_error", logicTag: "not both zero" },
    ],
    explanation: "Abscissa=x=−4, ordinate=y=0. y=0 means the point is on the x-axis. x=−4<0 → negative x-axis.",
    solutionSteps: ["abscissa = x = −4", "ordinate = y = 0", "y=0 → x-axis", "x<0 → negative x-axis"],
    shortcut: "Abscissa = x-coordinate. Ordinate = y-coordinate.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_cartesian_plane_q8", topicId: "math9_ch1_cartesian_plane",
    text: "Points A(2,3), B(−2,3), C(−2,−3) and D(2,−3) are plotted. What shape do they form?",
    options: [
      { text: "Square", type: "concept_error", logicTag: "equal sides but not" },
      { text: "Rectangle", type: "correct", logicTag: "symmetric about both axes" },
      { text: "Rhombus", type: "concept_error", logicTag: "not equal diagonals" },
      { text: "Trapezium", type: "concept_error", logicTag: "no parallel sides reasoning" },
    ],
    explanation: "Width = |2−(−2)|=4, Height = |3−(−3)|=6. Opposite sides equal (4 and 6), all angles 90° → Rectangle. Not square since 4≠6.",
    solutionSteps: ["Width (horizontal) = 4", "Height (vertical) = 6", "4 ≠ 6 → not a square", "All angles are 90° → Rectangle"],
    shortcut: "Points symmetric about both axes form a rectangle. Equal dimensions → square.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },

  // ── Ch1 · Sub-topic 2: Plotting Points ─────────────────────────────────────
  {
    questionId: "math9_ch1_plotting_points_q1", topicId: "math9_ch1_plotting_points",
    text: "To plot the point (−4, 6), you should move:",
    options: [
      { text: "4 units right, 6 units up", type: "concept_error", logicTag: "sign error on x" },
      { text: "4 units left, 6 units up", type: "correct", logicTag: "negative x left, positive y up" },
      { text: "4 units left, 6 units down", type: "concept_error", logicTag: "sign error on y" },
      { text: "6 units left, 4 units up", type: "concept_error", logicTag: "coordinates swapped" },
    ],
    explanation: "x=−4: move 4 units left. y=6: move 6 units up. First move horizontally, then vertically.",
    solutionSteps: ["x=−4 → move LEFT 4 units", "y=6 → move UP 6 units"],
    shortcut: "Negative x → left. Negative y → down. Always move horizontally first.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_plotting_points_q2", topicId: "math9_ch1_plotting_points",
    text: "Which point is the closest to the x-axis?",
    options: [
      { text: "A(3, 5)", type: "concept_error", logicTag: "y=5" },
      { text: "B(−1, 2)", type: "correct", logicTag: "smallest |y|=2" },
      { text: "C(0, −4)", type: "concept_error", logicTag: "y=−4, |y|=4" },
      { text: "D(−6, 3)", type: "concept_error", logicTag: "y=3" },
    ],
    explanation: "Distance from x-axis = |y-coordinate|. |5|=5, |2|=2, |−4|=4, |3|=3. Minimum is 2, so B(−1,2) is closest.",
    solutionSteps: ["Distance from x-axis = |y|", "A: |5|=5, B: |2|=2, C: |−4|=4, D: |3|=3", "Minimum |y| = 2 → B(−1, 2)"],
    shortcut: "Closest to x-axis = smallest |y|. Closest to y-axis = smallest |x|.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_plotting_points_q3", topicId: "math9_ch1_plotting_points",
    text: "A point P is 3 units to the left of the y-axis and 5 units below the x-axis. What are its coordinates?",
    options: [
      { text: "(3, 5)", type: "concept_error", logicTag: "both positive" },
      { text: "(−3, 5)", type: "concept_error", logicTag: "y sign error" },
      { text: "(−3, −5)", type: "correct", logicTag: "left=negative x, below=negative y" },
      { text: "(3, −5)", type: "concept_error", logicTag: "x sign error" },
    ],
    explanation: "Left of y-axis → x = −3. Below x-axis → y = −5. So P(−3, −5).",
    solutionSteps: ["3 units LEFT of y-axis → x = −3", "5 units BELOW x-axis → y = −5", "P = (−3, −5)"],
    shortcut: "Left → negative x. Below → negative y.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_plotting_points_q4", topicId: "math9_ch1_plotting_points",
    text: "If a point is equidistant from both axes and lies in Q2, which of the following could be its coordinates?",
    options: [
      { text: "(−4, 4)", type: "correct", logicTag: "equal distance, Q2" },
      { text: "(4, 4)", type: "concept_error", logicTag: "Q1" },
      { text: "(−4, −4)", type: "concept_error", logicTag: "Q3" },
      { text: "(0, 4)", type: "concept_error", logicTag: "on y-axis, not Q2" },
    ],
    explanation: "Equidistant from both axes means |x|=|y|. In Q2: x<0, y>0, so x=−4, y=4.",
    solutionSteps: ["|x| = |y| (equidistant from axes)", "Q2 requires x<0, y>0", "So x=−a, y=a for some a>0", "Answer: (−4, 4)"],
    shortcut: "Equidistant from axes → points on y=x or y=−x. In Q2, it's y=−x (negative x, positive y).",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_plotting_points_q5", topicId: "math9_ch1_plotting_points",
    text: "Points A(1,0), B(0,1), C(−1,0), D(0,−1) are plotted. What shape do they form?",
    options: [
      { text: "Rectangle", type: "concept_error", logicTag: "not a rectangle" },
      { text: "Square", type: "correct", logicTag: "all sides equal, right angles" },
      { text: "Parallelogram", type: "partial_logic", logicTag: "has parallel sides but more specific" },
      { text: "Rhombus only", type: "partial_logic", logicTag: "equal sides but angles are 90°" },
    ],
    explanation: "All four vertices are distance 1 from origin, at 90° to each other. All sides = √2. All angles = 90°. This is a square (tilted 45°).",
    solutionSteps: ["AB = √((1−0)²+(0−1)²) = √2", "BC = CD = DA = √2 (same)", "Diagonal AC = 2 (through origin)", "Equal sides + equal diagonals → Square"],
    shortcut: "Points at (±1,0) and (0,±1) always form a unit square rotated 45°.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_plotting_points_q6", topicId: "math9_ch1_plotting_points",
    text: "A point is reflected across the y-axis. Its new coordinates are (3, −2). What were its original coordinates?",
    options: [
      { text: "(3, 2)", type: "concept_error", logicTag: "reflected across x-axis instead" },
      { text: "(−3, −2)", type: "correct", logicTag: "y-axis reflection negates x" },
      { text: "(−3, 2)", type: "concept_error", logicTag: "both negated" },
      { text: "(3, −2)", type: "concept_error", logicTag: "no change" },
    ],
    explanation: "Reflection across y-axis: x changes sign, y stays same. New = (3,−2), so original x was −3, y was −2. Original: (−3, −2).",
    solutionSteps: ["Across y-axis: x → −x, y unchanged", "New point (3,−2): 3 = −(original x) → original x = −3", "y unchanged: original y = −2", "Original: (−3, −2)"],
    shortcut: "Across y-axis reflection is reversible — negate x again to get back.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_plotting_points_q7", topicId: "math9_ch1_plotting_points",
    text: "On which axis does the point (k, 0) always lie, regardless of the value of k?",
    options: [
      { text: "y-axis always", type: "concept_error", logicTag: "y=0 is x-axis" },
      { text: "x-axis always", type: "correct", logicTag: "y=0 means x-axis" },
      { text: "Origin always", type: "concept_error", logicTag: "only when k=0 too" },
      { text: "Depends on value of k", type: "concept_error", logicTag: "y=0 is enough" },
    ],
    explanation: "Any point with y=0 lies on the x-axis, regardless of x. (k,0) is always on the x-axis.",
    solutionSteps: ["y=0 for all such points", "y=0 defines the x-axis", "So (k,0) is on x-axis for any k"],
    shortcut: "(k,0) → x-axis. (0,k) → y-axis.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_plotting_points_q8", topicId: "math9_ch1_plotting_points",
    text: "The vertices of a triangle are at A(0,4), B(−3,0), and C(3,0). What type of triangle is it?",
    options: [
      { text: "Scalene", type: "concept_error", logicTag: "not all different" },
      { text: "Equilateral", type: "concept_error", logicTag: "sides not all equal" },
      { text: "Isosceles", type: "correct", logicTag: "AB = AC by symmetry" },
      { text: "Right-angled", type: "concept_error", logicTag: "check angles" },
    ],
    explanation: "B and C are symmetric about y-axis. AB = √(9+16)=5, AC = √(9+16)=5, BC = 6. Two equal sides → Isosceles.",
    solutionSteps: ["AB = √((−3−0)²+(0−4)²) = √(9+16) = 5", "AC = √((3−0)²+(0−4)²) = √(9+16) = 5", "BC = 6", "AB = AC → Isosceles"],
    shortcut: "Triangle symmetric about an axis → automatically isosceles.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },

  // ── Ch1 · Sub-topic 3: Distance Formula ────────────────────────────────────
  {
    questionId: "math9_ch1_distance_formula_q1", topicId: "math9_ch1_distance_formula",
    text: "Find the distance between A(3, 4) and B(0, 0).",
    options: [
      { text: "3", type: "concept_error", logicTag: "only x difference" },
      { text: "4", type: "concept_error", logicTag: "only y difference" },
      { text: "5", type: "correct", logicTag: "√(9+16)=5" },
      { text: "7", type: "concept_error", logicTag: "added instead of Pythagoras" },
    ],
    explanation: "Distance = √(3²+4²) = √(9+16) = √25 = 5. This is the 3-4-5 Pythagorean triple.",
    solutionSteps: ["Δx = 3−0 = 3, Δy = 4−0 = 4", "Distance = √(3²+4²) = √25 = 5"],
    shortcut: "Recognise 3-4-5 triple instantly. √(9+16) = 5.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_distance_formula_q2", topicId: "math9_ch1_distance_formula",
    text: "What is the distance between P(1, 3) and Q(4, 7)?",
    options: [
      { text: "3", type: "concept_error", logicTag: "only Δx" },
      { text: "5", type: "correct", logicTag: "√(9+16)=5" },
      { text: "7", type: "concept_error", logicTag: "Δx+Δy" },
      { text: "√7", type: "concept_error", logicTag: "√(3+4) not √(9+16)" },
    ],
    explanation: "Δx=4−1=3, Δy=7−3=4. Distance=√(9+16)=√25=5.",
    solutionSteps: ["Δx = 4−1 = 3", "Δy = 7−3 = 4", "Distance = √(3²+4²) = √25 = 5"],
    shortcut: "Δx=3, Δy=4 → immediately 3-4-5 triple → distance = 5.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_distance_formula_q3", topicId: "math9_ch1_distance_formula",
    text: "Point P(x, 0) is 10 units from A(−6, 0). Which of the following are the possible values of x?",
    options: [
      { text: "x = 4 only", type: "partial_logic", logicTag: "only one solution" },
      { text: "x = 4 or x = −16", type: "correct", logicTag: "two solutions on x-axis" },
      { text: "x = 16 only", type: "concept_error", logicTag: "sign error" },
      { text: "x = −4 or x = 4", type: "concept_error", logicTag: "wrong calculation" },
    ],
    explanation: "Both points on x-axis (y=0). Distance = |x−(−6)| = |x+6| = 10. So x+6=10 → x=4, or x+6=−10 → x=−16.",
    solutionSteps: ["|x+6| = 10", "x+6 = 10 → x = 4", "x+6 = −10 → x = −16", "Both are valid solutions"],
    shortcut: "Points on x-axis: distance = |x₂−x₁|. Absolute value gives two solutions.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_distance_formula_q4", topicId: "math9_ch1_distance_formula",
    text: "Are the points A(1,5), B(2,3), C(−2,−11) collinear?",
    options: [
      { text: "Yes, all three lie on a straight line", type: "concept_error", logicTag: "incorrect" },
      { text: "No, they are not collinear", type: "correct", logicTag: "AB+BC ≠ AC" },
      { text: "Cannot be determined without a graph", type: "concept_error", logicTag: "distance method works" },
      { text: "Yes, because AB + BC = AC", type: "concept_error", logicTag: "calculation error" },
    ],
    explanation: "AB=√(1+4)=√5, BC=√(16+196)=√212, AC=√(9+256)=√265. AB+BC≠AC and no pair sums to the third. Not collinear.",
    solutionSteps: ["AB=√((2−1)²+(3−5)²)=√5≈2.24", "BC=√(16+196)=√212≈14.56", "AC=√(9+256)=√265≈16.28", "AB+BC≈16.8≠16.28=AC → not collinear"],
    shortcut: "Collinear test: if AB+BC=AC (one point between the others), they're collinear.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_distance_formula_q5", topicId: "math9_ch1_distance_formula",
    text: "The distance between (a, 2) and (3, 4) is 2√2. Find a.",
    options: [
      { text: "a = 1 only", type: "correct", logicTag: "a=3±2, take a=1" },
      { text: "a = 5 only", type: "partial_logic", logicTag: "other solution" },
      { text: "a = 1 or a = 5", type: "correct", logicTag: "two solutions" },
      { text: "a = 3", type: "concept_error", logicTag: "no displacement" },
    ],
    explanation: "√((a−3)²+4)=2√2 → (a−3)²+4=8 → (a−3)²=4 → a−3=±2 → a=1 or a=5.",
    solutionSteps: ["(a−3)²+(2−4)²=(2√2)²=8", "(a−3)²+4=8", "(a−3)²=4", "a=3±2 → a=1 or a=5"],
    shortcut: "Square both sides, isolate (a−3)², solve quadratic.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_distance_formula_q6", topicId: "math9_ch1_distance_formula",
    text: "Which set of points forms a right isosceles triangle?",
    options: [
      { text: "A(0,0), B(4,0), C(0,3)", type: "concept_error", logicTag: "right but not isosceles" },
      { text: "A(0,0), B(4,0), C(0,4)", type: "correct", logicTag: "right angle at A, AB=AC=4" },
      { text: "A(0,0), B(3,4), C(0,5)", type: "concept_error", logicTag: "not right isosceles" },
      { text: "A(1,1), B(4,1), C(4,5)", type: "concept_error", logicTag: "right but legs unequal" },
    ],
    explanation: "A(0,0),B(4,0),C(0,4): AB=4, AC=4 (equal legs). BC=√32=4√2. Right angle at A (axes are perpendicular). Right isosceles ✓.",
    solutionSteps: ["AB=4, AC=4 (equal → isosceles)", "Angle at A: AB along x-axis, AC along y-axis → 90°", "BC=4√2=AB×√2 (hypotenuse check ✓)"],
    shortcut: "Right isosceles: two legs equal, right angle between them, hypotenuse = leg×√2.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_distance_formula_q7", topicId: "math9_ch1_distance_formula",
    text: "What is the distance of point (−5, 12) from the origin?",
    options: [
      { text: "13", type: "correct", logicTag: "5-12-13 triple" },
      { text: "17", type: "concept_error", logicTag: "5+12" },
      { text: "√7", type: "concept_error", logicTag: "12−5" },
      { text: "7", type: "concept_error", logicTag: "arithmetic error" },
    ],
    explanation: "Distance = √(25+144) = √169 = 13. Recognise the 5-12-13 Pythagorean triple.",
    solutionSteps: ["Δx=−5, Δy=12", "Distance=√(25+144)=√169=13"],
    shortcut: "5-12-13 is a Pythagorean triple. Memorise: (3,4,5), (5,12,13), (8,15,17).",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_distance_formula_q8", topicId: "math9_ch1_distance_formula",
    text: "If the distance between (0,0) and (k, k) is 6, what is the value of k?",
    options: [
      { text: "k = 6", type: "concept_error", logicTag: "forgot √2" },
      { text: "k = 3√2", type: "correct", logicTag: "k√2=6 → k=6/√2=3√2" },
      { text: "k = 3", type: "concept_error", logicTag: "arithmetic error" },
      { text: "k = 2√3", type: "concept_error", logicTag: "wrong simplification" },
    ],
    explanation: "Distance = √(k²+k²) = √(2k²) = k√2 = 6. So k = 6/√2 = 3√2.",
    solutionSteps: ["Distance = √(k²+k²) = k√2", "k√2 = 6", "k = 6/√2 = 6√2/2 = 3√2"],
    shortcut: "Distance from origin to (k,k) is always k√2.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },

  // ── Ch1 · Sub-topic 4: Section Formula ─────────────────────────────────────
  {
    questionId: "math9_ch1_section_formula_q1", topicId: "math9_ch1_section_formula",
    text: "Find the midpoint of A(2, 6) and B(8, 4).",
    options: [
      { text: "(6, 10)", type: "concept_error", logicTag: "added instead of averaged" },
      { text: "(5, 5)", type: "correct", logicTag: "(2+8)/2=5, (6+4)/2=5" },
      { text: "(3, 2)", type: "concept_error", logicTag: "subtracted" },
      { text: "(4, 5)", type: "concept_error", logicTag: "arithmetic error" },
    ],
    explanation: "Midpoint = ((2+8)/2, (6+4)/2) = (5, 5).",
    solutionSteps: ["x_m = (2+8)/2 = 5", "y_m = (6+4)/2 = 5", "Midpoint = (5,5)"],
    shortcut: "Midpoint = average of both coordinates.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_section_formula_q2", topicId: "math9_ch1_section_formula",
    text: "Point P divides A(1,2) and B(7,5) in the ratio 2:1. Find P.",
    options: [
      { text: "(4, 3.5)", type: "concept_error", logicTag: "used midpoint" },
      { text: "(5, 4)", type: "correct", logicTag: "section formula with m=2, n=1" },
      { text: "(3, 3)", type: "concept_error", logicTag: "arithmetic error" },
      { text: "(5, 3)", type: "concept_error", logicTag: "y error" },
    ],
    explanation: "P = ((2×7+1×1)/(2+1), (2×5+1×2)/3) = (15/3, 12/3) = (5, 4).",
    solutionSteps: ["m=2, n=1, A(1,2), B(7,5)", "x = (2×7+1×1)/3 = 15/3 = 5", "y = (2×5+1×2)/3 = 12/3 = 4", "P = (5, 4)"],
    shortcut: "m goes with B (second point), n goes with A (first point).",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_section_formula_q3", topicId: "math9_ch1_section_formula",
    text: "M(4,3) is the midpoint of A(1,1) and B. Find B.",
    options: [
      { text: "(7, 5)", type: "correct", logicTag: "B=2M−A" },
      { text: "(2.5, 2)", type: "concept_error", logicTag: "averaged instead of doubled" },
      { text: "(5, 4)", type: "concept_error", logicTag: "arithmetic error" },
      { text: "(3, 2)", type: "concept_error", logicTag: "subtracted" },
    ],
    explanation: "M = (A+B)/2 → B = 2M−A = (8−1, 6−1) = (7, 5).",
    solutionSteps: ["4 = (1+x_B)/2 → x_B = 7", "3 = (1+y_B)/2 → y_B = 5", "B = (7, 5)"],
    shortcut: "B = 2×Midpoint − A. Simple formula to reverse the midpoint.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_section_formula_q4", topicId: "math9_ch1_section_formula",
    text: "In what ratio does the origin divide the segment joining A(−3, 4) and B(6, −8)?",
    options: [
      { text: "1:1", type: "concept_error", logicTag: "midpoint" },
      { text: "1:2", type: "correct", logicTag: "3:6=1:2 ratio" },
      { text: "2:1", type: "concept_error", logicTag: "reversed ratio" },
      { text: "3:4", type: "concept_error", logicTag: "using y coords wrong" },
    ],
    explanation: "Let O(0,0) divide AB in ratio k:1. x: 0=(k×6+1×(−3))/(k+1) → 6k=3 → k=1/2. Ratio = 1:2.",
    solutionSteps: ["(0,0) divides A(−3,4) to B(6,−8) in ratio k:1", "0 = (6k−3)/(k+1) → 6k=3 → k=1/2", "Ratio = 1/2 : 1 = 1 : 2"],
    shortcut: "Set origin as the dividing point, solve for k. Verify with y-coordinate: (k×−8+4)/(k+1)=(−4+4)/1.5=0 ✓",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_section_formula_q5", topicId: "math9_ch1_section_formula",
    text: "A point divides the segment from A(0,0) to B(6,9) in the ratio 2:1. Find it.",
    options: [
      { text: "(3, 4.5)", type: "concept_error", logicTag: "midpoint (1:1)" },
      { text: "(4, 6)", type: "correct", logicTag: "2:1 from A to B" },
      { text: "(2, 3)", type: "concept_error", logicTag: "1:2 (1/3 way)" },
      { text: "(6, 9)", type: "concept_error", logicTag: "endpoint B" },
    ],
    explanation: "m=2, n=1, A(0,0), B(6,9). P=((2×6+1×0)/3, (2×9+1×0)/3)=(12/3, 18/3)=(4, 6).",
    solutionSteps: ["x=(2×6+1×0)/3=4", "y=(2×9+1×0)/3=6", "P=(4,6)"],
    shortcut: "From A(0,0) in ratio 2:1: P = (2/3)×B.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_section_formula_q6", topicId: "math9_ch1_section_formula",
    text: "The centroid of a triangle with vertices A(2,4), B(6,2), C(1,6) is:",
    options: [
      { text: "(3, 4)", type: "correct", logicTag: "centroid = average of vertices" },
      { text: "(4, 4)", type: "concept_error", logicTag: "x arithmetic error" },
      { text: "(3, 3)", type: "concept_error", logicTag: "y arithmetic error" },
      { text: "(2, 3)", type: "concept_error", logicTag: "wrong formula" },
    ],
    explanation: "Centroid G = ((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3) = ((2+6+1)/3, (4+2+6)/3) = (9/3, 12/3) = (3, 4).",
    solutionSteps: ["G_x = (2+6+1)/3 = 9/3 = 3", "G_y = (4+2+6)/3 = 12/3 = 4", "Centroid G = (3, 4)"],
    shortcut: "Centroid = arithmetic mean of all three vertices.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_section_formula_q7", topicId: "math9_ch1_section_formula",
    text: "A point divides A(2,−3) and B(5,6) externally in ratio 2:1. Find it.",
    options: [
      { text: "(8, 15)", type: "correct", logicTag: "external division formula" },
      { text: "(4, 3)", type: "concept_error", logicTag: "internal midpoint" },
      { text: "(4, 0)", type: "concept_error", logicTag: "incorrect formula" },
      { text: "(11, 15)", type: "concept_error", logicTag: "sign error" },
    ],
    explanation: "External: P=((2×5−1×2)/(2−1), (2×6−1×(−3))/(2−1)) = (8/1, 15/1) = (8, 15).",
    solutionSteps: ["External formula: P=((mx₂−nx₁)/(m−n), (my₂−ny₁)/(m−n))", "x=(2×5−1×2)/1=8", "y=(2×6−1×(−3))/1=15", "P=(8,15)"],
    shortcut: "External division: replace + with − in internal formula, and (m+n) with (m−n).",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },
  {
    questionId: "math9_ch1_section_formula_q8", topicId: "math9_ch1_section_formula",
    text: "If the midpoint of AB is (3,5) and A = (1,2), what is the distance from A to B?",
    options: [
      { text: "√(20)", type: "concept_error", logicTag: "used midpoint to origin" },
      { text: "√(52)", type: "correct", logicTag: "B=(5,8), AB=√(16+36)=√52" },
      { text: "√(13)", type: "concept_error", logicTag: "half the distance" },
      { text: "2√(13)", type: "correct", logicTag: "same as √52" },
    ],
    explanation: "B = 2×(3,5)−(1,2) = (5,8). AB = √((5−1)²+(8−2)²) = √(16+36) = √52 = 2√13.",
    solutionSteps: ["B = 2M−A = (6−1, 10−2) = (5,8)", "AB = √(4²+6²) = √52 = 2√13"],
    shortcut: "Find B first using B=2M−A, then apply distance formula.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Orienting Yourself: The Use of Coordinates",
  },

  // ── Ch2 · Sub-topic 1: Poly Basics ─────────────────────────────────────────
  {
    questionId: "math9_ch2_poly_basics_q1", topicId: "math9_ch2_poly_basics",
    text: "Which of the following is NOT a polynomial?",
    options: [
      { text: "3x² − 5x + 2", type: "concept_error", logicTag: "this is a polynomial" },
      { text: "x⁻² + 1", type: "correct", logicTag: "negative exponent → not polynomial" },
      { text: "5", type: "concept_error", logicTag: "constant polynomial, degree 0" },
      { text: "x³ + 0x² − x", type: "concept_error", logicTag: "valid polynomial" },
    ],
    explanation: "Polynomials only have non-negative integer exponents. x⁻² has a negative exponent, so it's NOT a polynomial.",
    solutionSteps: ["Check each for non-negative integer exponents", "x⁻² → exponent = −2 < 0 → NOT a polynomial"],
    shortcut: "Any negative or fractional exponent of the variable → not a polynomial.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_poly_basics_q2", topicId: "math9_ch2_poly_basics",
    text: "What is the degree of the polynomial 4x³ − 2x⁵ + x − 7?",
    options: [
      { text: "3", type: "concept_error", logicTag: "first term's power" },
      { text: "5", type: "correct", logicTag: "highest power is 5" },
      { text: "1", type: "concept_error", logicTag: "only x term" },
      { text: "4", type: "concept_error", logicTag: "number of terms" },
    ],
    explanation: "Degree = highest power of the variable. Terms: 4x³ (power 3), −2x⁵ (power 5), x (power 1), −7 (power 0). Highest = 5.",
    solutionSteps: ["Identify powers: 3, 5, 1, 0", "Highest power = 5", "Degree = 5"],
    shortcut: "Don't look at the first term — scan ALL terms for the highest power.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_poly_basics_q3", topicId: "math9_ch2_poly_basics",
    text: "A polynomial with exactly two terms is called a:",
    options: [
      { text: "Monomial", type: "concept_error", logicTag: "one term" },
      { text: "Binomial", type: "correct", logicTag: "two terms" },
      { text: "Trinomial", type: "concept_error", logicTag: "three terms" },
      { text: "Linear polynomial", type: "concept_error", logicTag: "relates to degree, not terms" },
    ],
    explanation: "Monomial = 1 term, Binomial = 2 terms, Trinomial = 3 terms. Number of terms determines the prefix.",
    solutionSteps: ["bi = 2 → binomial = two terms"],
    shortcut: "Mono=1, Bi=2, Tri=3. Degree is about the power, not the number of terms.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_poly_basics_q4", topicId: "math9_ch2_poly_basics",
    text: "The leading coefficient of the polynomial 3x⁴ − 5x³ + 2x − 7 is:",
    options: [
      { text: "−7", type: "concept_error", logicTag: "constant term" },
      { text: "−5", type: "concept_error", logicTag: "coefficient of second term" },
      { text: "3", type: "correct", logicTag: "coefficient of highest degree term" },
      { text: "2", type: "concept_error", logicTag: "coefficient of x term" },
    ],
    explanation: "The leading coefficient is the coefficient of the term with the highest degree. Highest degree term is 3x⁴, coefficient = 3.",
    solutionSteps: ["Highest degree term: 3x⁴", "Coefficient of 3x⁴ = 3", "Leading coefficient = 3"],
    shortcut: "Leading coefficient = coefficient of the highest power term.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_poly_basics_q5", topicId: "math9_ch2_poly_basics",
    text: "Which of the following is a linear polynomial?",
    options: [
      { text: "x² + 1", type: "concept_error", logicTag: "degree 2 = quadratic" },
      { text: "2x + 5", type: "correct", logicTag: "degree 1 = linear" },
      { text: "x³ − x", type: "concept_error", logicTag: "degree 3 = cubic" },
      { text: "7", type: "concept_error", logicTag: "degree 0 = constant" },
    ],
    explanation: "A linear polynomial has degree 1 (highest power is 1). 2x+5 has degree 1 → linear.",
    solutionSteps: ["Linear = degree 1", "2x+5: highest power of x is 1 → linear"],
    shortcut: "Linear=1, Quadratic=2, Cubic=3, Quartic=4, Quintic=5.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_poly_basics_q6", topicId: "math9_ch2_poly_basics",
    text: "What is the degree of the zero polynomial?",
    options: [
      { text: "0", type: "concept_error", logicTag: "zero polynomial is special" },
      { text: "1", type: "concept_error", logicTag: "incorrect" },
      { text: "Undefined (not defined)", type: "correct", logicTag: "zero polynomial has no degree" },
      { text: "−1", type: "concept_error", logicTag: "some texts use this but CBSE says undefined" },
    ],
    explanation: "The zero polynomial (every coefficient is 0) has no degree by convention — its degree is undefined.",
    solutionSteps: ["Zero polynomial: p(x) = 0", "No highest-power term exists", "Degree is undefined"],
    shortcut: "Only the zero polynomial has undefined degree. A constant non-zero polynomial has degree 0.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_poly_basics_q7", topicId: "math9_ch2_poly_basics",
    text: "If p(x) = 2x³ − 3x + 5, what is p(0)?",
    options: [
      { text: "0", type: "concept_error", logicTag: "confused with zero of polynomial" },
      { text: "5", type: "correct", logicTag: "constant term" },
      { text: "4", type: "concept_error", logicTag: "arithmetic error" },
      { text: "−3", type: "concept_error", logicTag: "only the x term" },
    ],
    explanation: "p(0) = 2(0)³ − 3(0) + 5 = 0 − 0 + 5 = 5. p(0) always equals the constant term.",
    solutionSteps: ["Substitute x=0", "p(0) = 2×0 − 3×0 + 5 = 5"],
    shortcut: "p(0) = constant term of the polynomial. Always.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_poly_basics_q8", topicId: "math9_ch2_poly_basics",
    text: "How many terms does (x+1)³ have when expanded?",
    options: [
      { text: "2", type: "concept_error", logicTag: "binomial not expanded" },
      { text: "3", type: "concept_error", logicTag: "one less than correct" },
      { text: "4", type: "correct", logicTag: "(x+1)³=x³+3x²+3x+1" },
      { text: "6", type: "concept_error", logicTag: "overcounted" },
    ],
    explanation: "(x+1)³ = x³+3x²+3x+1. This has 4 terms. Pascal's triangle row: 1,3,3,1.",
    solutionSteps: ["(x+1)³ = x³+3x²+3x+1", "Count terms: x³, 3x², 3x, 1 → 4 terms"],
    shortcut: "(a+b)ⁿ has (n+1) terms when expanded. n=3 → 4 terms.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },

  // ── Ch2 · Sub-topic 2: Zeroes ───────────────────────────────────────────────
  {
    questionId: "math9_ch2_zeroes_q1", topicId: "math9_ch2_zeroes",
    text: "What is the zero of the polynomial p(x) = 3x − 12?",
    options: [
      { text: "−12", type: "concept_error", logicTag: "constant term" },
      { text: "3", type: "concept_error", logicTag: "coefficient" },
      { text: "4", type: "correct", logicTag: "3x−12=0 → x=4" },
      { text: "−4", type: "concept_error", logicTag: "sign error" },
    ],
    explanation: "Set p(x)=0: 3x−12=0 → 3x=12 → x=4. Verify: p(4)=12−12=0 ✓.",
    solutionSteps: ["3x−12=0", "3x=12", "x=4"],
    shortcut: "Zero of ax+b = −b/a = −(−12)/3 = 4.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_zeroes_q2", topicId: "math9_ch2_zeroes",
    text: "How many zeroes can a linear polynomial have at most?",
    options: [
      { text: "0", type: "concept_error", logicTag: "it always has one" },
      { text: "1", type: "correct", logicTag: "degree 1 → exactly 1 zero" },
      { text: "2", type: "concept_error", logicTag: "that would be quadratic" },
      { text: "Infinitely many", type: "concept_error", logicTag: "only zero polynomial does" },
    ],
    explanation: "A polynomial of degree n has at most n zeroes. Linear = degree 1 → exactly 1 zero (since ax+b=0 has exactly one solution for a≠0).",
    solutionSteps: ["Linear polynomial: degree 1", "Maximum zeroes = degree = 1", "Exactly one zero"],
    shortcut: "Degree = maximum number of zeroes.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_zeroes_q3", topicId: "math9_ch2_zeroes",
    text: "p(x) = x² − 4. What are the zeroes of p(x)?",
    options: [
      { text: "x = 4 only", type: "concept_error", logicTag: "forgot square root" },
      { text: "x = 2 or x = −2", type: "correct", logicTag: "difference of squares" },
      { text: "x = 2 only", type: "concept_error", logicTag: "only positive root" },
      { text: "x = 0", type: "concept_error", logicTag: "confused with p(0)" },
    ],
    explanation: "x²−4=0 → (x+2)(x−2)=0 → x=2 or x=−2.",
    solutionSteps: ["x²=4", "x=±√4=±2", "Zeroes: x=2 and x=−2"],
    shortcut: "x²=a² has two solutions: x=a and x=−a.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_zeroes_q4", topicId: "math9_ch2_zeroes",
    text: "If 1 is a zero of p(x) = kx² − 3x + k, find k.",
    options: [
      { text: "k = 3", type: "concept_error", logicTag: "arithmetic error" },
      { text: "k = 3/2", type: "correct", logicTag: "k−3+k=0 → 2k=3" },
      { text: "k = 1", type: "concept_error", logicTag: "wrong substitution" },
      { text: "k = −3", type: "concept_error", logicTag: "sign error" },
    ],
    explanation: "Since 1 is a zero: p(1)=0. k(1)²−3(1)+k=0 → k−3+k=0 → 2k=3 → k=3/2.",
    solutionSteps: ["p(1)=0", "k−3+k=0", "2k=3", "k=3/2"],
    shortcut: "Substitute the zero into p(x), set equal to 0, solve for the unknown.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_zeroes_q5", topicId: "math9_ch2_zeroes",
    text: "A constant polynomial p(x) = 7 has how many zeroes?",
    options: [
      { text: "0", type: "correct", logicTag: "7=0 is impossible" },
      { text: "1", type: "concept_error", logicTag: "only linear has 1" },
      { text: "7", type: "concept_error", logicTag: "confused with the value" },
      { text: "Infinite", type: "concept_error", logicTag: "only zero polynomial" },
    ],
    explanation: "p(x)=7 means the polynomial equals 7 for all x. It can never equal 0. So it has NO zeroes.",
    solutionSteps: ["p(x)=7 for all x", "7≠0 for any x", "Zero zeroes"],
    shortcut: "Constant non-zero polynomial → 0 zeroes. Zero polynomial → all x are zeroes (infinitely many).",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_zeroes_q6", topicId: "math9_ch2_zeroes",
    text: "If p(x) = x² − 5x + 6, which of the following is a zero of p(x)?",
    options: [
      { text: "x = 1", type: "concept_error", logicTag: "p(1)=1−5+6=2≠0" },
      { text: "x = 2", type: "correct", logicTag: "p(2)=4−10+6=0" },
      { text: "x = 4", type: "concept_error", logicTag: "p(4)=16−20+6=2≠0" },
      { text: "x = −2", type: "concept_error", logicTag: "p(−2)=4+10+6=20≠0" },
    ],
    explanation: "Check each: p(2) = 4−10+6 = 0 ✓. Also p(3) = 9−15+6 = 0. Zeroes are 2 and 3.",
    solutionSteps: ["p(2)=4−10+6=0 ✓"],
    shortcut: "Try obvious values. Factors of constant term (6) are ±1,±2,±3,±6.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_zeroes_q7", topicId: "math9_ch2_zeroes",
    text: "What is the value of p(−1) for p(x) = 2x³ − x² + 3x − 4?",
    options: [
      { text: "−10", type: "correct", logicTag: "−2−1−3−4=−10" },
      { text: "−2", type: "concept_error", logicTag: "arithmetic error" },
      { text: "0", type: "concept_error", logicTag: "not a zero" },
      { text: "10", type: "concept_error", logicTag: "sign error" },
    ],
    explanation: "p(−1)=2(−1)³−(−1)²+3(−1)−4=−2−1−3−4=−10.",
    solutionSteps: ["x=−1", "2(−1)=−2, (−1)²=1, 3(−1)=−3", "−2−1−3−4=−10"],
    shortcut: "Keep track of signs carefully. (−1)^odd = −1, (−1)^even = 1.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_zeroes_q8", topicId: "math9_ch2_zeroes",
    text: "For p(x) = ax + b, the zero is at x = 3. If b = −6, what is a?",
    options: [
      { text: "a = −2", type: "concept_error", logicTag: "sign error" },
      { text: "a = 2", type: "correct", logicTag: "zero = −b/a = 6/a = 3 → a=2" },
      { text: "a = 3", type: "concept_error", logicTag: "confused" },
      { text: "a = 6", type: "concept_error", logicTag: "forgot to divide" },
    ],
    explanation: "Zero of ax+b is x=−b/a. So −(−6)/a=3 → 6/a=3 → a=2.",
    solutionSteps: ["Zero = −b/a = 3", "b=−6 → −(−6)/a=3 → 6/a=3 → a=2"],
    shortcut: "Zero of linear = −b/a. Rearrange to find any unknown.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },

  // ── Ch2 · Sub-topic 3: Remainder Theorem ───────────────────────────────────
  {
    questionId: "math9_ch2_remainder_theorem_q1", topicId: "math9_ch2_remainder_theorem",
    text: "Find the remainder when p(x) = x³ + 3x² − 2x + 1 is divided by (x−1).",
    options: [
      { text: "0", type: "concept_error", logicTag: "not a zero" },
      { text: "3", type: "correct", logicTag: "p(1)=1+3−2+1=3" },
      { text: "7", type: "concept_error", logicTag: "arithmetic error" },
      { text: "−3", type: "concept_error", logicTag: "sign error" },
    ],
    explanation: "By Remainder Theorem: remainder = p(1) = 1+3−2+1 = 3.",
    solutionSteps: ["Divisor: x−1 → substitute x=1", "p(1) = 1+3−2+1 = 3", "Remainder = 3"],
    shortcut: "Remainder = p(value that makes divisor zero). (x−1)=0 → x=1.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_remainder_theorem_q2", topicId: "math9_ch2_remainder_theorem",
    text: "What is the remainder when 2x³ − 3x² + x + 5 is divided by (x+2)?",
    options: [
      { text: "−25", type: "correct", logicTag: "p(−2)=−16−12−2+5=−25" },
      { text: "25", type: "concept_error", logicTag: "sign error" },
      { text: "−9", type: "concept_error", logicTag: "arithmetic error" },
      { text: "7", type: "concept_error", logicTag: "used x=+2 instead of −2" },
    ],
    explanation: "Divisor (x+2) → x=−2. p(−2)=2(−8)−3(4)+(−2)+5=−16−12−2+5=−25.",
    solutionSteps: ["(x+2)=0 → x=−2", "p(−2)=2(−8)−3(4)+(−2)+5", "=−16−12−2+5=−25"],
    shortcut: "(x+a) → substitute x=−a (negate the constant).",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_remainder_theorem_q3", topicId: "math9_ch2_remainder_theorem",
    text: "If the remainder when p(x) = x² + kx + 2 is divided by (x−2) is 8, find k.",
    options: [
      { text: "k = 0", type: "concept_error", logicTag: "arithmetic error" },
      { text: "k = 1", type: "correct", logicTag: "4+2k+2=8 → 2k=2 → k=1" },
      { text: "k = 2", type: "concept_error", logicTag: "arithmetic error" },
      { text: "k = −1", type: "concept_error", logicTag: "sign error" },
    ],
    explanation: "p(2)=8: 4+2k+2=8 → 2k=2 → k=1.",
    solutionSteps: ["Remainder = p(2) = 8", "4+2k+2=8", "2k=2 → k=1"],
    shortcut: "Set up equation from p(value)=remainder, solve for unknown.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_remainder_theorem_q4", topicId: "math9_ch2_remainder_theorem",
    text: "If the remainder when p(x) = x³ + ax² − 7 is divided by (x−2) equals the remainder when divided by (x+1), find a.",
    options: [
      { text: "a = −3", type: "concept_error", logicTag: "arithmetic error" },
      { text: "a = 3", type: "correct", logicTag: "equation p(2)=p(−1)" },
      { text: "a = 0", type: "concept_error", logicTag: "incorrect" },
      { text: "a = 1", type: "concept_error", logicTag: "off by one" },
    ],
    explanation: "p(2)=8+4a−7=4a+1. p(−1)=−1+a−7=a−8. Set equal: 4a+1=a−8 → 3a=−9 → a=−3. Wait, let me recheck. 4a+1=a−8 → 3a=−9 → a=−3.",
    solutionSteps: ["p(2)=8+4a−7=4a+1", "p(−1)=−1+a−7=a−8", "4a+1=a−8 → 3a=−9 → a=−3"],
    shortcut: "Set p(first value) = p(second value). This gives a simple equation to solve.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_remainder_theorem_q5", topicId: "math9_ch2_remainder_theorem",
    text: "When p(x) is divided by (x−a), the remainder is p(a). If p(3) = 0, what can you conclude?",
    options: [
      { text: "Remainder is 3", type: "concept_error", logicTag: "confused remainder with zero" },
      { text: "(x−3) is a factor of p(x)", type: "correct", logicTag: "RT + Factor Theorem" },
      { text: "p(x) has no zeroes", type: "concept_error", logicTag: "opposite" },
      { text: "p(x) is divisible by 3", type: "concept_error", logicTag: "wrong interpretation" },
    ],
    explanation: "By Remainder Theorem, remainder when dividing by (x−3) = p(3) = 0. Zero remainder means (x−3) divides p(x) exactly → it's a factor.",
    solutionSteps: ["p(3)=0 → remainder when ÷(x−3) is 0", "Zero remainder → (x−3) is a factor"],
    shortcut: "p(a)=0 ↔ (x−a) is a factor. This is the Factor Theorem.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_remainder_theorem_q6", topicId: "math9_ch2_remainder_theorem",
    text: "Find the remainder when x⁴ − 1 is divided by (x−1).",
    options: [
      { text: "1", type: "concept_error", logicTag: "forgot to subtract" },
      { text: "0", type: "correct", logicTag: "p(1)=1−1=0" },
      { text: "−1", type: "concept_error", logicTag: "p(−1) not p(1)" },
      { text: "2", type: "concept_error", logicTag: "arithmetic error" },
    ],
    explanation: "p(1) = 1⁴−1 = 0. Remainder = 0, confirming (x−1) is a factor of x⁴−1.",
    solutionSteps: ["p(1) = 1−1 = 0", "Remainder = 0"],
    shortcut: "(xⁿ−1) is always divisible by (x−1) for any n. Useful fact.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_remainder_theorem_q7", topicId: "math9_ch2_remainder_theorem",
    text: "What is the remainder when p(x) = 5 (a constant) is divided by (x−100)?",
    options: [
      { text: "100", type: "concept_error", logicTag: "confused with divisor" },
      { text: "0", type: "concept_error", logicTag: "5 ≠ 0" },
      { text: "5", type: "correct", logicTag: "p(100)=5 for constant" },
      { text: "−95", type: "concept_error", logicTag: "nonsensical" },
    ],
    explanation: "For constant polynomial p(x)=5, p(any value)=5. By RT: remainder = p(100) = 5.",
    solutionSteps: ["p(x)=5 for all x", "Remainder = p(100) = 5"],
    shortcut: "Constant polynomial p(x)=c always gives remainder c when divided by any (x−a).",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_remainder_theorem_q8", topicId: "math9_ch2_remainder_theorem",
    text: "p(x) = x³ − 7x + 6. Find the remainder when divided by (2x − 1).",
    options: [
      { text: "1/8", type: "concept_error", logicTag: "only x³ term" },
      { text: "35/8", type: "correct", logicTag: "p(1/2)=1/8−7/2+6=35/8" },
      { text: "0", type: "concept_error", logicTag: "1/2 is not a zero" },
      { text: "6", type: "concept_error", logicTag: "constant term" },
    ],
    explanation: "2x−1=0 → x=1/2. p(1/2)=(1/8)−(7/2)+6=1/8−28/8+48/8=21/8. Wait: 1/8 − 3.5 + 6 = 1/8 − 28/8 + 48/8 = 21/8.",
    solutionSteps: ["2x−1=0 → x=1/2", "p(1/2)=(1/2)³−7(1/2)+6=1/8−7/2+6", "=1/8−28/8+48/8=21/8"],
    shortcut: "Divisor (ax−b) → substitute x=b/a.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },

  // ── Ch2 · Sub-topic 4: Factor Theorem ──────────────────────────────────────
  {
    questionId: "math9_ch2_factor_theorem_q1", topicId: "math9_ch2_factor_theorem",
    text: "Is (x−2) a factor of p(x) = x³ − 4x² + x + 6?",
    options: [
      { text: "No, because p(2) ≠ 0", type: "concept_error", logicTag: "need to check" },
      { text: "Yes, because p(2) = 0", type: "correct", logicTag: "8−16+2+6=0" },
      { text: "Cannot determine without long division", type: "concept_error", logicTag: "RT is enough" },
      { text: "No, because degree is 3", type: "concept_error", logicTag: "irrelevant" },
    ],
    explanation: "p(2) = 8−16+2+6 = 0. By Factor Theorem, (x−2) IS a factor.",
    solutionSteps: ["Check p(2): 8−16+2+6=0 ✓", "p(2)=0 → (x−2) is a factor"],
    shortcut: "p(a)=0 → (x−a) is a factor. One substitution is all you need.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_factor_theorem_q2", topicId: "math9_ch2_factor_theorem",
    text: "Factorise: p(x) = x³ − 3x − 2.",
    options: [
      { text: "(x−1)(x+1)(x+2)", type: "concept_error", logicTag: "wrong factors" },
      { text: "(x+1)²(x−2)", type: "correct", logicTag: "p(−1)=0, factor out twice" },
      { text: "(x−1)²(x+2)", type: "concept_error", logicTag: "wrong sign" },
      { text: "(x+2)(x²−x−1)", type: "concept_error", logicTag: "wrong quadratic" },
    ],
    explanation: "Test x=−1: p(−1)=−1+3−2=0 ✓. Divide by (x+1): x²−x−2=(x−2)(x+1). So p(x)=(x+1)(x+1)(x−2)=(x+1)²(x−2).",
    solutionSteps: ["p(−1)=0 → (x+1) is a factor", "Divide: x³−3x−2÷(x+1)=x²−x−2", "x²−x−2=(x−2)(x+1)", "Full: (x+1)²(x−2)"],
    shortcut: "Sum of coefficients: 1+0−3−2=−4≠0. Try p(−1)=−1+0+3−2=0 ✓.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_factor_theorem_q3", topicId: "math9_ch2_factor_theorem",
    text: "If (x+1) is a factor of p(x) = x³ + kx² − x − 2, find k.",
    options: [
      { text: "k = 2", type: "correct", logicTag: "p(−1)=0 → −1+k+1−2=0 → k=2" },
      { text: "k = −2", type: "concept_error", logicTag: "sign error" },
      { text: "k = 1", type: "concept_error", logicTag: "arithmetic error" },
      { text: "k = 0", type: "concept_error", logicTag: "doesn't satisfy" },
    ],
    explanation: "If (x+1) is a factor, p(−1)=0. −1+k(1)+1−2=0 → k−2=0 → k=2.",
    solutionSteps: ["p(−1)=0", "(−1)³+k(−1)²−(−1)−2=0", "−1+k+1−2=0", "k=2"],
    shortcut: "Factor → zero of the polynomial. Use the zero to set up equation for unknown.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_factor_theorem_q4", topicId: "math9_ch2_factor_theorem",
    text: "Which of the following is a factor of x³ + 8?",
    options: [
      { text: "(x+2)", type: "correct", logicTag: "p(−2)=−8+8=0" },
      { text: "(x−2)", type: "concept_error", logicTag: "p(2)=8+8≠0" },
      { text: "(x+4)", type: "concept_error", logicTag: "p(−4)=−64+8≠0" },
      { text: "(x²+4)", type: "partial_logic", logicTag: "part of identity but not factor alone" },
    ],
    explanation: "x³+8 = x³+2³. By sum of cubes: (x+2)(x²−2x+4). So (x+2) is a factor.",
    solutionSteps: ["x³+8 = (x)³+(2)³", "Sum of cubes: (a+b)(a²−ab+b²)", "= (x+2)(x²−2x+4)", "(x+2) is a factor"],
    shortcut: "a³+b³=(a+b)(a²−ab+b²). a³−b³=(a−b)(a²+ab+b²).",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_factor_theorem_q5", topicId: "math9_ch2_factor_theorem",
    text: "Show that (x−3) is a factor of x³ − 3x² − x + 3, then fully factorise it.",
    options: [
      { text: "(x−3)(x+1)(x−1)", type: "correct", logicTag: "correct full factorisation" },
      { text: "(x−3)(x²+1)", type: "concept_error", logicTag: "x²−1 not x²+1" },
      { text: "(x−3)²(x+1)", type: "concept_error", logicTag: "only one factor of (x−3)" },
      { text: "(x−3)(x−1)²", type: "concept_error", logicTag: "wrong" },
    ],
    explanation: "p(3)=27−27−3+3=0 ✓. Divide by (x−3): x²−1=(x+1)(x−1). Full: (x−3)(x+1)(x−1).",
    solutionSteps: ["p(3)=0 → (x−3) is a factor", "p(x)÷(x−3) = x²−1", "x²−1=(x+1)(x−1)", "Full: (x−3)(x+1)(x−1)"],
    shortcut: "After finding one factor, the quotient is a quadratic — factorise it by inspection.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_factor_theorem_q6", topicId: "math9_ch2_factor_theorem",
    text: "For p(x) = 2x³ + x² − 5x + 2, check if (2x−1) is a factor.",
    options: [
      { text: "Yes, (2x−1) is a factor", type: "correct", logicTag: "p(1/2)=0" },
      { text: "No, (2x−1) is not a factor", type: "concept_error", logicTag: "need to check p(1/2)" },
      { text: "Cannot apply Factor Theorem here", type: "concept_error", logicTag: "FT works for any linear" },
      { text: "Depends on the other factors", type: "concept_error", logicTag: "irrelevant" },
    ],
    explanation: "2x−1=0 → x=1/2. p(1/2)=2(1/8)+1/4−5/2+2=1/4+1/4−10/4+8/4=0 ✓. Yes, (2x−1) is a factor.",
    solutionSteps: ["2x−1=0 → x=1/2", "p(1/2)=2/8+1/4−5/2+2=1/4+1/4−10/4+8/4=0", "(2x−1) is a factor"],
    shortcut: "For (ax−b), check p(b/a)=0.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_factor_theorem_q7", topicId: "math9_ch2_factor_theorem",
    text: "If sum of coefficients of p(x) = 0, which is always a factor?",
    options: [
      { text: "(x+1)", type: "concept_error", logicTag: "that's p(−1)=0" },
      { text: "(x−1)", type: "correct", logicTag: "p(1)=sum of coefficients=0" },
      { text: "(x+0)", type: "concept_error", logicTag: "that's just x" },
      { text: "None necessarily", type: "concept_error", logicTag: "sum of coefficients=p(1)" },
    ],
    explanation: "p(1) = a₁+a₂+…+a₀ = sum of all coefficients. If this sum = 0, then p(1)=0, so (x−1) is a factor.",
    solutionSteps: ["p(1) = sum of coefficients", "If sum = 0, then p(1) = 0", "By Factor Theorem, (x−1) is a factor"],
    shortcut: "Sum of coefficients = 0 → (x−1) is a factor. Alternating sum of coefficients = 0 → (x+1) is a factor.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
  {
    questionId: "math9_ch2_factor_theorem_q8", topicId: "math9_ch2_factor_theorem",
    text: "How many factors does x³ − 6x² + 11x − 6 have of the form (x−n) where n is a positive integer?",
    options: [
      { text: "1", type: "concept_error", logicTag: "only one zero found" },
      { text: "2", type: "concept_error", logicTag: "only two zeroes found" },
      { text: "3", type: "correct", logicTag: "zeroes are 1,2,3" },
      { text: "0", type: "concept_error", logicTag: "there are zeroes" },
    ],
    explanation: "p(1)=1−6+11−6=0, p(2)=8−24+22−6=0, p(3)=27−54+33−6=0. All three are zeroes → 3 factors: (x−1)(x−2)(x−3).",
    solutionSteps: ["p(1)=0 → (x−1)", "p(2)=0 → (x−2)", "p(3)=0 → (x−3)", "Degree 3 → exactly 3 linear factors"],
    shortcut: "Try ±(divisors of constant term). For constant −6: try ±1,±2,±3,±6.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Introduction to Linear Polynomials",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  for (const q of questions) {
    await Question.findOneAndUpdate(
      { questionId: q.questionId },
      q,
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`  ✓ ${q.questionId}`);
  }
  console.log(`\nSeeded ${questions.length} questions for Class 9 Math (Ch1–Ch2 sub-topics).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
