import "dotenv/config";
import mongoose from "mongoose";
import { Topic } from "../models/index.js";

const BOARD = "AP_SSC";
const GRADE = "9";
const SUBJECT = "Mathematics";

/**
 * AP SSC Math 9 — Topic DAG
 * 35 topics across 12 chapters.
 * Prerequisites form a linear chain within chapters + cross-chapter edges.
 * topicId format: ap_ssc_math9_ch{N}_{slug}
 */
const topics = [
  // ─── Chapter 1 — Number Systems ───────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    name: "Irrational Numbers",
    chapterName: "Number Systems",
    chapterNumber: 1,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: [],
    description: "Understanding irrational numbers, proving irrationality by contradiction, representing surds on number line.",
    estimatedMinutes: 45,
    difficulty: "medium",
    bloomLevels: ["remember", "understand", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    name: "Decimal Expansions",
    chapterName: "Number Systems",
    chapterNumber: 1,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch1_irrational_numbers"],
    description: "Terminating and non-terminating recurring decimals, converting recurring decimals to p/q form.",
    estimatedMinutes: 40,
    difficulty: "medium",
    bloomLevels: ["understand", "apply"],
  },
  {
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    name: "Operations on Reals",
    chapterName: "Number Systems",
    chapterNumber: 1,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch1_decimal_expansions"],
    description: "Rationalisation of surds, operations with irrational numbers, simplification of expressions involving surds.",
    estimatedMinutes: 50,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    name: "Laws of Exponents for Real Numbers",
    chapterName: "Number Systems",
    chapterNumber: 1,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch1_operations_on_reals"],
    description: "Fractional and negative exponents, laws of indices, simplifying exponential expressions.",
    estimatedMinutes: 45,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },

  // ─── Chapter 2 — Polynomials ───────────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    name: "Polynomials — Basics",
    chapterName: "Polynomials",
    chapterNumber: 2,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch1_laws_of_exponents"],
    description: "Definition, degree, types, coefficients, evaluating polynomials.",
    estimatedMinutes: 35,
    difficulty: "easy",
    bloomLevels: ["remember", "understand", "apply"],
  },
  {
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    name: "Zeroes of a Polynomial",
    chapterName: "Polynomials",
    chapterNumber: 2,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch2_polynomials_basics"],
    description: "Finding zeroes, relationship between zeroes and coefficients (Vieta's formulas).",
    estimatedMinutes: 40,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    name: "Remainder Theorem",
    chapterName: "Polynomials",
    chapterNumber: 2,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch2_zeroes_of_polynomial"],
    description: "Remainder Theorem statement and applications, finding unknown coefficients.",
    estimatedMinutes: 40,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    name: "Factor Theorem",
    chapterName: "Polynomials",
    chapterNumber: 2,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch2_remainder_theorem"],
    description: "Factor Theorem and its applications, complete factorisation of polynomials.",
    estimatedMinutes: 45,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    name: "Algebraic Identities",
    chapterName: "Polynomials",
    chapterNumber: 2,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch2_factor_theorem"],
    description: "Standard identities, cubic expansions, sum of cubes identity, applications.",
    estimatedMinutes: 50,
    difficulty: "medium",
    bloomLevels: ["apply", "evaluate"],
  },

  // ─── Chapter 3 — Coordinate Geometry ──────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch3_cartesian_system",
    name: "Cartesian System",
    chapterName: "Coordinate Geometry",
    chapterNumber: 3,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: [],
    description: "Cartesian plane, quadrants, axes, plotting points, abscissa and ordinate.",
    estimatedMinutes: 35,
    difficulty: "easy",
    bloomLevels: ["remember", "understand"],
  },
  {
    topicId: "ap_ssc_math9_ch3_plotting_points",
    name: "Plotting Points in the Plane",
    chapterName: "Coordinate Geometry",
    chapterNumber: 3,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch3_cartesian_system"],
    description: "Plotting coordinates, identifying shapes, distance and area using coordinates.",
    estimatedMinutes: 40,
    difficulty: "easy",
    bloomLevels: ["apply", "analyse"],
  },

  // ─── Chapter 4 — Linear Equations in Two Variables ────────────────────────
  {
    topicId: "ap_ssc_math9_ch4_linear_equation_solutions",
    name: "Solutions of a Linear Equation",
    chapterName: "Linear Equations in Two Variables",
    chapterNumber: 4,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch3_plotting_points"],
    description: "Solutions as ordered pairs, infinite solutions, forming equations from word problems.",
    estimatedMinutes: 35,
    difficulty: "easy",
    bloomLevels: ["understand", "apply"],
  },
  {
    topicId: "ap_ssc_math9_ch4_graph_of_linear_equation",
    name: "Graph of a Linear Equation",
    chapterName: "Linear Equations in Two Variables",
    chapterNumber: 4,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch4_linear_equation_solutions"],
    description: "Drawing graphs of linear equations, x/y intercepts, graphical solution of simultaneous equations.",
    estimatedMinutes: 45,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch4_equations_of_special_lines",
    name: "Equations of Lines Parallel to Axes",
    chapterName: "Linear Equations in Two Variables",
    chapterNumber: 4,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch4_graph_of_linear_equation"],
    description: "Horizontal and vertical lines, y = constant, x = constant, real-life applications.",
    estimatedMinutes: 30,
    difficulty: "easy",
    bloomLevels: ["understand", "apply"],
  },

  // ─── Chapter 5 — Euclid's Geometry ────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch5_euclid_definitions_axioms",
    name: "Euclid's Definitions, Axioms and Postulates",
    chapterName: "Introduction to Euclid's Geometry",
    chapterNumber: 5,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: [],
    description: "Euclid's elements, 5 postulates, 7 axioms, undefined terms, geometric constructions.",
    estimatedMinutes: 40,
    difficulty: "medium",
    bloomLevels: ["remember", "understand", "apply"],
  },
  {
    topicId: "ap_ssc_math9_ch5_fifth_postulate",
    name: "Equivalent Versions of the Fifth Postulate",
    chapterName: "Introduction to Euclid's Geometry",
    chapterNumber: 5,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch5_euclid_definitions_axioms"],
    description: "Playfair's axiom, non-Euclidean geometries, historical significance.",
    estimatedMinutes: 35,
    difficulty: "medium",
    bloomLevels: ["understand", "evaluate"],
  },

  // ─── Chapter 6 — Lines and Angles ─────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch6_basic_terms_angles",
    name: "Basic Terms and Angles",
    chapterName: "Lines and Angles",
    chapterNumber: 6,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch5_fifth_postulate"],
    description: "Linear pair, supplementary, complementary, vertically opposite angles.",
    estimatedMinutes: 40,
    difficulty: "easy",
    bloomLevels: ["remember", "understand", "apply"],
  },
  {
    topicId: "ap_ssc_math9_ch6_parallel_lines_transversal",
    name: "Parallel Lines and a Transversal",
    chapterName: "Lines and Angles",
    chapterNumber: 6,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch6_basic_terms_angles"],
    description: "Corresponding, alternate interior, co-interior angles; proofs.",
    estimatedMinutes: 50,
    difficulty: "medium",
    bloomLevels: ["understand", "apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch6_lines_parallel_to_same_line",
    name: "Lines Parallel to the Same Line",
    chapterName: "Lines and Angles",
    chapterNumber: 6,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch6_parallel_lines_transversal"],
    description: "Transitivity of parallelism, angle sum property of triangle proved using parallel lines.",
    estimatedMinutes: 40,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },

  // ─── Chapter 7 — Triangles ─────────────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch7_congruence_of_triangles",
    name: "Congruence of Triangles",
    chapterName: "Triangles",
    chapterNumber: 7,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch6_lines_parallel_to_same_line"],
    description: "Definition of congruence, CPCT, writing congruence statements.",
    estimatedMinutes: 35,
    difficulty: "easy",
    bloomLevels: ["remember", "understand"],
  },
  {
    topicId: "ap_ssc_math9_ch7_congruence_criteria",
    name: "Congruence Criteria",
    chapterName: "Triangles",
    chapterNumber: 7,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch7_congruence_of_triangles"],
    description: "SSS, SAS, ASA, AAS, RHS — proofs and applications.",
    estimatedMinutes: 55,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch7_triangle_properties_inequalities",
    name: "Properties of Triangles and Inequalities",
    chapterName: "Triangles",
    chapterNumber: 7,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch7_congruence_criteria"],
    description: "Angle-side inequalities, triangle inequality, exterior angle theorem — proofs.",
    estimatedMinutes: 50,
    difficulty: "hard",
    bloomLevels: ["analyse", "evaluate"],
  },

  // ─── Chapter 8 — Quadrilaterals ────────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch8_angle_sum_property",
    name: "Angle Sum Property of a Quadrilateral",
    chapterName: "Quadrilaterals",
    chapterNumber: 8,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch7_triangle_properties_inequalities"],
    description: "360° angle sum, ratio problems, special quadrilaterals.",
    estimatedMinutes: 35,
    difficulty: "easy",
    bloomLevels: ["understand", "apply"],
  },
  {
    topicId: "ap_ssc_math9_ch8_parallelogram_properties",
    name: "Properties of a Parallelogram",
    chapterName: "Quadrilaterals",
    chapterNumber: 8,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch8_angle_sum_property"],
    description: "Opposite sides/angles equal, diagonals bisect; rectangle, rhombus, square properties.",
    estimatedMinutes: 55,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch8_midpoint_theorem",
    name: "Midpoint Theorem",
    chapterName: "Quadrilaterals",
    chapterNumber: 8,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch8_parallelogram_properties"],
    description: "Midpoint theorem statement, proof, converse, trapezium mid-segment.",
    estimatedMinutes: 50,
    difficulty: "hard",
    bloomLevels: ["apply", "analyse"],
  },

  // ─── Chapter 9 — Circles ──────────────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch9_chords_of_circle",
    name: "Chords of a Circle",
    chapterName: "Circles",
    chapterNumber: 9,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch7_congruence_criteria"],
    description: "Perpendicular from centre bisects chord, equal chords equidistant from centre.",
    estimatedMinutes: 45,
    difficulty: "medium",
    bloomLevels: ["understand", "apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch9_angle_subtended_by_arc",
    name: "Angle Subtended by an Arc",
    chapterName: "Circles",
    chapterNumber: 9,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch9_chords_of_circle"],
    description: "Inscribed angle theorem, angle in semicircle, angles in same segment.",
    estimatedMinutes: 50,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch9_cyclic_quadrilaterals",
    name: "Cyclic Quadrilaterals",
    chapterName: "Circles",
    chapterNumber: 9,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch9_angle_subtended_by_arc"],
    description: "Opposite angles supplementary, exterior angle = interior opposite, applications.",
    estimatedMinutes: 45,
    difficulty: "hard",
    bloomLevels: ["apply", "analyse"],
  },

  // ─── Chapter 10 — Heron's Formula ─────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch10_herons_formula",
    name: "Heron's Formula",
    chapterName: "Heron's Formula",
    chapterNumber: 10,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch1_operations_on_reals"],
    description: "Heron's formula, semi-perimeter, area of various triangles, real-life applications.",
    estimatedMinutes: 45,
    difficulty: "medium",
    bloomLevels: ["apply"],
  },
  {
    topicId: "ap_ssc_math9_ch10_herons_application_quadrilaterals",
    name: "Heron's Formula — Quadrilaterals",
    chapterName: "Heron's Formula",
    chapterNumber: 10,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch10_herons_formula", "ap_ssc_math9_ch8_angle_sum_property"],
    description: "Applying Heron's formula to quadrilaterals by splitting along diagonal; trapezium area.",
    estimatedMinutes: 45,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },

  // ─── Chapter 11 — Surface Areas and Volumes ───────────────────────────────
  {
    topicId: "ap_ssc_math9_ch11_surface_area_solids",
    name: "Surface Areas of Solids",
    chapterName: "Surface Areas and Volumes",
    chapterNumber: 11,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch10_herons_formula"],
    description: "TSA/CSA of cuboid, cylinder, cone, sphere, hemisphere; real-life applications.",
    estimatedMinutes: 55,
    difficulty: "medium",
    bloomLevels: ["apply"],
  },
  {
    topicId: "ap_ssc_math9_ch11_volume_of_solids",
    name: "Volumes of Solids",
    chapterName: "Surface Areas and Volumes",
    chapterNumber: 11,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch11_surface_area_solids"],
    description: "Volumes of cuboid, cylinder, cone, sphere; recasting problems; real-life applications.",
    estimatedMinutes: 55,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },

  // ─── Chapter 12 — Statistics ──────────────────────────────────────────────
  {
    topicId: "ap_ssc_math9_ch12_data_collection_presentation",
    name: "Data Collection and Presentation",
    chapterName: "Statistics",
    chapterNumber: 12,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: [],
    description: "Primary/secondary data, raw vs grouped data, bar graph, histogram, frequency polygon.",
    estimatedMinutes: 40,
    difficulty: "easy",
    bloomLevels: ["remember", "understand", "apply"],
  },
  {
    topicId: "ap_ssc_math9_ch12_frequency_distributions",
    name: "Frequency Distributions",
    chapterName: "Statistics",
    chapterNumber: 12,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch12_data_collection_presentation"],
    description: "Frequency tables, cumulative frequency, ogive, class marks, relative frequency.",
    estimatedMinutes: 45,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse"],
  },
  {
    topicId: "ap_ssc_math9_ch12_central_tendency",
    name: "Measures of Central Tendency",
    chapterName: "Statistics",
    chapterNumber: 12,
    examBoard: BOARD,
    grade: GRADE,
    subject: SUBJECT,
    prerequisites: ["ap_ssc_math9_ch12_frequency_distributions"],
    description: "Mean (raw and grouped), median, mode, choosing appropriate measure.",
    estimatedMinutes: 50,
    difficulty: "medium",
    bloomLevels: ["apply", "analyse", "evaluate"],
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log(`Seeding AP SSC Math 9 — Topic DAG (${topics.length} topics)…`);

  let upserted = 0;
  let skipped = 0;

  for (const t of topics) {
    try {
      await Topic.findOneAndUpdate(
        { topicId: t.topicId },
        { $set: t },
        { upsert: true, new: true }
      );
      console.log(`  ✓ ${t.topicId}`);
      upserted++;
    } catch (err) {
      if (err.code === 11000) {
        console.log(`  — skip ${t.topicId}`);
        skipped++;
      } else {
        throw err;
      }
    }
  }

  console.log(`\nDone. Upserted: ${upserted}  Skipped: ${skipped}`);
  await mongoose.disconnect();
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
