import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math1_ch13_counting_large_groups — 8 questions
  {
    questionId: "math1_ch13_clg_q1",
    topicId: "math1_ch13_counting_large_groups",
    text: "There are 25 apples in a basket. How many apples are there?",
    options: [
      { text: "25", type: "correct" },
      { text: "52", type: "concept_error" },
      { text: "20", type: "calculation_error" },
      { text: "15", type: "guessing" },
    ],
    explanation: "Count the digits: 2 tens and 5 ones = 25.",
    solutionSteps: ["Read the number on the basket", "25 means 2 tens and 5 ones", "Answer: 25"],
    shortcut: "Read two-digit numbers as tens first, then ones.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_clg_q2",
    topicId: "math1_ch13_counting_large_groups",
    text: "A box has 30 crayons. Riya adds 5 more. How many crayons are there now?",
    options: [
      { text: "35", type: "correct" },
      { text: "25", type: "calculation_error" },
      { text: "53", type: "concept_error" },
      { text: "30", type: "partial_logic" },
    ],
    explanation: "30 + 5 = 35.",
    solutionSteps: ["Start at 30", "Count on 5 more: 31, 32, 33, 34, 35", "Answer: 35"],
    shortcut: "Add ones to a round number by counting on.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_clg_q3",
    topicId: "math1_ch13_counting_large_groups",
    text: "Which number is greater — 47 or 74?",
    options: [
      { text: "74", type: "correct" },
      { text: "47", type: "concept_error" },
      { text: "They are equal", type: "misinterpretation" },
      { text: "Cannot say", type: "guessing" },
    ],
    explanation: "74 has 7 tens; 47 has only 4 tens. More tens means a bigger number.",
    solutionSteps: ["Compare tens digit: 7 > 4", "So 74 > 47"],
    shortcut: "Always compare the tens digit first.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_clg_q4",
    topicId: "math1_ch13_counting_large_groups",
    text: "Count the stars: ★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★ (50 stars). How many are there?",
    options: [
      { text: "50", type: "correct" },
      { text: "45", type: "calculation_error" },
      { text: "55", type: "calculation_error" },
      { text: "40", type: "guessing" },
    ],
    explanation: "Counting all 50 stars gives 50.",
    solutionSteps: ["Group into tens", "5 groups of 10 = 50"],
    shortcut: "Group objects into tens to count faster.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_clg_q5",
    topicId: "math1_ch13_counting_large_groups",
    text: "There are 4 bunches of bananas with 10 bananas each and 3 extra. How many bananas total?",
    options: [
      { text: "43", type: "correct" },
      { text: "34", type: "concept_error" },
      { text: "40", type: "partial_logic" },
      { text: "13", type: "misinterpretation" },
    ],
    explanation: "4 × 10 = 40, plus 3 extra = 43.",
    solutionSteps: ["4 bunches × 10 = 40", "40 + 3 = 43"],
    shortcut: "Write tens digit = number of full groups, ones digit = extras.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_clg_q6",
    topicId: "math1_ch13_counting_large_groups",
    text: "What comes just before 60?",
    options: [
      { text: "59", type: "correct" },
      { text: "61", type: "concept_error" },
      { text: "50", type: "misinterpretation" },
      { text: "69", type: "guessing" },
    ],
    explanation: "The number just before 60 is 59 (one less).",
    solutionSteps: ["60 − 1 = 59"],
    shortcut: "Just before = subtract 1.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_clg_q7",
    topicId: "math1_ch13_counting_large_groups",
    text: "Arrange from smallest to largest: 28, 82, 48.",
    options: [
      { text: "28, 48, 82", type: "correct" },
      { text: "82, 48, 28", type: "concept_error" },
      { text: "28, 82, 48", type: "misinterpretation" },
      { text: "48, 28, 82", type: "guessing" },
    ],
    explanation: "Compare tens: 2 < 4 < 8, so 28 < 48 < 82.",
    solutionSteps: ["Tens digits: 28→2, 48→4, 82→8", "Order: 28, 48, 82"],
    shortcut: "Smallest tens digit = smallest number.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_clg_q8",
    topicId: "math1_ch13_counting_large_groups",
    text: "A farmer has 99 mangoes. How many tens and ones?",
    options: [
      { text: "9 tens and 9 ones", type: "correct" },
      { text: "9 tens and 0 ones", type: "calculation_error" },
      { text: "99 tens and 0 ones", type: "concept_error" },
      { text: "0 tens and 99 ones", type: "misinterpretation" },
    ],
    explanation: "99 = 90 + 9 = 9 tens and 9 ones.",
    solutionSteps: ["Tens digit = 9 → 9 tens", "Ones digit = 9 → 9 ones"],
    shortcut: "Tens digit tells tens; ones digit tells ones.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },

  // math1_ch13_counting_in_groups — 8 questions
  {
    questionId: "math1_ch13_cig_q1",
    topicId: "math1_ch13_counting_in_groups",
    text: "Count by 2s: 2, 4, 6, __, 10. What is the missing number?",
    options: [
      { text: "8", type: "correct" },
      { text: "7", type: "concept_error" },
      { text: "9", type: "misinterpretation" },
      { text: "6", type: "partial_logic" },
    ],
    explanation: "Counting by 2s: 2, 4, 6, 8, 10. The missing number is 8.",
    solutionSteps: ["Each step adds 2", "6 + 2 = 8"],
    shortcut: "Skip-count by 2 to find even numbers in order.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cig_q2",
    topicId: "math1_ch13_counting_in_groups",
    text: "Count by 5s: 5, 10, 15, __, 25. What is missing?",
    options: [
      { text: "20", type: "correct" },
      { text: "18", type: "calculation_error" },
      { text: "22", type: "misinterpretation" },
      { text: "15", type: "partial_logic" },
    ],
    explanation: "Counting by 5s: 5, 10, 15, 20, 25. Missing = 20.",
    solutionSteps: ["Each step adds 5", "15 + 5 = 20"],
    shortcut: "Multiples of 5 always end in 0 or 5.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cig_q3",
    topicId: "math1_ch13_counting_in_groups",
    text: "Count by 10s: 10, 20, 30, __, 50. What comes in the blank?",
    options: [
      { text: "40", type: "correct" },
      { text: "35", type: "calculation_error" },
      { text: "45", type: "misinterpretation" },
      { text: "50", type: "partial_logic" },
    ],
    explanation: "Counting by 10s: 10, 20, 30, 40, 50. Missing = 40.",
    solutionSteps: ["Each step adds 10", "30 + 10 = 40"],
    shortcut: "Ones digit stays 0 when counting by 10.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cig_q4",
    topicId: "math1_ch13_counting_in_groups",
    text: "There are 3 groups of 5 cookies. How many cookies in all?",
    options: [
      { text: "15", type: "correct" },
      { text: "8", type: "calculation_error" },
      { text: "10", type: "partial_logic" },
      { text: "53", type: "concept_error" },
    ],
    explanation: "3 groups of 5 = 5 + 5 + 5 = 15.",
    solutionSteps: ["Count by 5 three times: 5, 10, 15"],
    shortcut: "Groups of 5 = skip-count by 5.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cig_q5",
    topicId: "math1_ch13_counting_in_groups",
    text: "There are 4 groups of 10 flowers. How many flowers altogether?",
    options: [
      { text: "40", type: "correct" },
      { text: "14", type: "concept_error" },
      { text: "30", type: "calculation_error" },
      { text: "44", type: "misinterpretation" },
    ],
    explanation: "4 groups of 10 = 10 + 10 + 10 + 10 = 40.",
    solutionSteps: ["Count by 10 four times: 10, 20, 30, 40"],
    shortcut: "Groups of 10 = number of groups × 10.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cig_q6",
    topicId: "math1_ch13_counting_in_groups",
    text: "How many legs do 5 cats have? (Each cat has 4 legs.)",
    options: [
      { text: "20", type: "correct" },
      { text: "9", type: "calculation_error" },
      { text: "15", type: "concept_error" },
      { text: "4", type: "partial_logic" },
    ],
    explanation: "5 cats × 4 legs = 4 + 4 + 4 + 4 + 4 = 20.",
    solutionSteps: ["Count by 4 five times: 4, 8, 12, 16, 20"],
    shortcut: "Repeated addition = skip-counting.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cig_q7",
    topicId: "math1_ch13_counting_in_groups",
    text: "Count by 2s starting from 1: 1, 3, 5, __, 9. What is missing?",
    options: [
      { text: "7", type: "correct" },
      { text: "6", type: "concept_error" },
      { text: "8", type: "misinterpretation" },
      { text: "4", type: "guessing" },
    ],
    explanation: "Odd numbers by 2s from 1: 1, 3, 5, 7, 9.",
    solutionSteps: ["5 + 2 = 7"],
    shortcut: "Odd skip-count by 2 gives: 1, 3, 5, 7, 9...",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cig_q8",
    topicId: "math1_ch13_counting_in_groups",
    text: "Which number does NOT belong in the count-by-5s list: 5, 10, 13, 20, 25?",
    options: [
      { text: "13", type: "correct" },
      { text: "5", type: "misinterpretation" },
      { text: "20", type: "misinterpretation" },
      { text: "25", type: "misinterpretation" },
    ],
    explanation: "Multiples of 5 end in 0 or 5. 13 ends in 3, so it does not belong.",
    solutionSteps: ["Check: 5✓ 10✓ 13✗ 20✓ 25✓"],
    shortcut: "Multiples of 5 always end in 0 or 5.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },

  // math1_ch13_estimation — 8 questions
  {
    questionId: "math1_ch13_est_q1",
    topicId: "math1_ch13_estimation",
    text: "There are about 20 marbles in a jar. Is this an exact count or an estimate?",
    options: [
      { text: "Estimate", type: "correct" },
      { text: "Exact count", type: "concept_error" },
      { text: "Both", type: "misinterpretation" },
      { text: "Neither", type: "guessing" },
    ],
    explanation: "The word 'about' tells us it is an estimate, not an exact count.",
    solutionSteps: ["'About' signals estimation", "An estimate is a close guess"],
    shortcut: "Words like 'about', 'around', 'nearly' = estimation.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_est_q2",
    topicId: "math1_ch13_estimation",
    text: "A bag has between 30 and 40 beads. Which is the best estimate?",
    options: [
      { text: "35", type: "correct" },
      { text: "5", type: "concept_error" },
      { text: "100", type: "misinterpretation" },
      { text: "50", type: "calculation_error" },
    ],
    explanation: "35 is between 30 and 40 and is a reasonable estimate.",
    solutionSteps: ["We need a number between 30 and 40", "35 is in the middle of that range"],
    shortcut: "Pick the middle value of the given range.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_est_q3",
    topicId: "math1_ch13_estimation",
    text: "You see a pile of about 50 seeds. Without counting each one, which is closest to your estimate?",
    options: [
      { text: "50", type: "correct" },
      { text: "5", type: "concept_error" },
      { text: "500", type: "misinterpretation" },
      { text: "150", type: "calculation_error" },
    ],
    explanation: "An estimate is the closest reasonable guess. 50 matches the description.",
    solutionSteps: ["'About 50' means our estimate should be near 50"],
    shortcut: "Use given clues to make your estimate close.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_est_q4",
    topicId: "math1_ch13_estimation",
    text: "Priya has a box of crayons. She thinks there are about 20. She counts and finds 19. Is her estimate good?",
    options: [
      { text: "Yes, it is close", type: "correct" },
      { text: "No, it is wrong", type: "concept_error" },
      { text: "Only exact answers are accepted", type: "misinterpretation" },
      { text: "She should try again", type: "guessing" },
    ],
    explanation: "An estimate of 20 when the answer is 19 is very close — a good estimate.",
    solutionSteps: ["Difference = 20 − 19 = 1", "1 is very small, so the estimate is good"],
    shortcut: "An estimate is good if it is close to the real number.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_est_q5",
    topicId: "math1_ch13_estimation",
    text: "Which is the best estimate for the number of fingers on both hands?",
    options: [
      { text: "10", type: "correct" },
      { text: "20", type: "concept_error" },
      { text: "5", type: "partial_logic" },
      { text: "100", type: "guessing" },
    ],
    explanation: "Both hands have exactly 10 fingers — a precise and correct estimate.",
    solutionSteps: ["5 fingers per hand × 2 hands = 10"],
    shortcut: "Use known facts as anchors for estimation.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_est_q6",
    topicId: "math1_ch13_estimation",
    text: "A jar holds about 10 toffees. You fill 3 such jars. Roughly how many toffees are there?",
    options: [
      { text: "About 30", type: "correct" },
      { text: "About 13", type: "concept_error" },
      { text: "About 100", type: "misinterpretation" },
      { text: "About 7", type: "calculation_error" },
    ],
    explanation: "3 jars × about 10 each ≈ 30.",
    solutionSteps: ["Estimate each jar at 10", "3 × 10 = 30"],
    shortcut: "Round each group, then multiply for a quick estimate.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_est_q7",
    topicId: "math1_ch13_estimation",
    text: "Which word shows estimation? 'There are __ children in the park.'",
    options: [
      { text: "about 15", type: "correct" },
      { text: "exactly 15", type: "concept_error" },
      { text: "0 children", type: "misinterpretation" },
      { text: "definitely 15", type: "misinterpretation" },
    ],
    explanation: "'About 15' uses estimation language. 'Exactly 15' is a precise count.",
    solutionSteps: ["'About' = estimation", "'Exactly' = precise count"],
    shortcut: "Look for hedge words: about, around, nearly, roughly.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_est_q8",
    topicId: "math1_ch13_estimation",
    text: "You look at a bowl and guess it has about 40 grapes. A friend guesses 38. Whose estimate is better after counting exactly 39?",
    options: [
      { text: "Friend's (38 is closer to 39)", type: "correct" },
      { text: "Yours (40 is closer)", type: "concept_error" },
      { text: "Both are equally good", type: "partial_logic" },
      { text: "Neither, only exact counts count", type: "misinterpretation" },
    ],
    explanation: "|40−39|=1 and |38−39|=1 are equal — both estimates are equally close. (If answers differ, pick the one with the smaller gap.)",
    solutionSteps: ["Your error: |40−39|=1", "Friend's error: |38−39|=1", "Both errors are equal"],
    shortcut: "Smaller difference = better estimate.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },

  // math1_ch13_comparing_quantities — 8 questions
  {
    questionId: "math1_ch13_cq_q1",
    topicId: "math1_ch13_comparing_quantities",
    text: "Raju has 15 marbles and Sana has 9 marbles. Who has more?",
    options: [
      { text: "Raju", type: "correct" },
      { text: "Sana", type: "concept_error" },
      { text: "They have the same", type: "misinterpretation" },
      { text: "Cannot say", type: "guessing" },
    ],
    explanation: "15 > 9, so Raju has more marbles.",
    solutionSteps: ["Compare 15 and 9", "15 > 9 → Raju has more"],
    shortcut: "The bigger number = more objects.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cq_q2",
    topicId: "math1_ch13_comparing_quantities",
    text: "A tree has 30 leaves and another has 50 leaves. How many more leaves does the second tree have?",
    options: [
      { text: "20", type: "correct" },
      { text: "80", type: "calculation_error" },
      { text: "20 fewer", type: "misinterpretation" },
      { text: "10", type: "guessing" },
    ],
    explanation: "50 − 30 = 20 more leaves.",
    solutionSteps: ["Subtract: 50 − 30 = 20"],
    shortcut: "Difference = bigger − smaller.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cq_q3",
    topicId: "math1_ch13_comparing_quantities",
    text: "Which is less — 62 or 26?",
    options: [
      { text: "26", type: "correct" },
      { text: "62", type: "concept_error" },
      { text: "Both are equal", type: "misinterpretation" },
      { text: "Cannot compare", type: "guessing" },
    ],
    explanation: "26 has 2 tens; 62 has 6 tens. 2 < 6, so 26 < 62.",
    solutionSteps: ["Tens of 26 = 2, Tens of 62 = 6", "2 < 6 → 26 is less"],
    shortcut: "Compare tens first — fewer tens = smaller number.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cq_q4",
    topicId: "math1_ch13_comparing_quantities",
    text: "A basket has 45 oranges and a box has 45 apples. Which has more fruit?",
    options: [
      { text: "Both have the same", type: "correct" },
      { text: "Basket has more", type: "concept_error" },
      { text: "Box has more", type: "concept_error" },
      { text: "Cannot say", type: "guessing" },
    ],
    explanation: "Both have 45. Equal quantities mean neither is more.",
    solutionSteps: ["45 = 45 → same quantity"],
    shortcut: "Same number = same quantity regardless of type.",
    difficulty: "easy",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cq_q5",
    topicId: "math1_ch13_comparing_quantities",
    text: "Meena has 28 stickers. Ritu has 10 fewer. How many stickers does Ritu have?",
    options: [
      { text: "18", type: "correct" },
      { text: "38", type: "concept_error" },
      { text: "20", type: "calculation_error" },
      { text: "8", type: "misinterpretation" },
    ],
    explanation: "28 − 10 = 18.",
    solutionSteps: ["'10 fewer' means subtract 10", "28 − 10 = 18"],
    shortcut: "Fewer = subtract; more = add.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cq_q6",
    topicId: "math1_ch13_comparing_quantities",
    text: "Class A has 32 students and Class B has 29. Together, how many students are there?",
    options: [
      { text: "61", type: "correct" },
      { text: "3", type: "calculation_error" },
      { text: "62", type: "calculation_error" },
      { text: "59", type: "misinterpretation" },
    ],
    explanation: "32 + 29 = 61.",
    solutionSteps: ["Add ones: 2 + 9 = 11 (write 1, carry 1)", "Add tens: 3 + 2 + 1 = 6", "Answer: 61"],
    shortcut: "Add ones first, then tens (with carry if needed).",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cq_q7",
    topicId: "math1_ch13_comparing_quantities",
    text: "A shop has 50 pens. It sells 17. How many pens are left?",
    options: [
      { text: "33", type: "correct" },
      { text: "67", type: "concept_error" },
      { text: "43", type: "calculation_error" },
      { text: "37", type: "calculation_error" },
    ],
    explanation: "50 − 17 = 33.",
    solutionSteps: ["50 − 17", "Borrow from tens: 10 − 7 = 3 ones", "4 − 1 = 3 tens", "Answer: 33"],
    shortcut: "Subtract ones first, borrow if needed, then subtract tens.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
  {
    questionId: "math1_ch13_cq_q8",
    topicId: "math1_ch13_comparing_quantities",
    text: "Put in order from most to least: 72 books, 27 books, 52 books.",
    options: [
      { text: "72, 52, 27", type: "correct" },
      { text: "27, 52, 72", type: "concept_error" },
      { text: "72, 27, 52", type: "misinterpretation" },
      { text: "52, 72, 27", type: "guessing" },
    ],
    explanation: "72 > 52 > 27, so ordered from most to least: 72, 52, 27.",
    solutionSteps: ["Compare tens: 7 > 5 > 2", "Order: 72, 52, 27"],
    shortcut: "Most to least = largest to smallest.",
    difficulty: "medium",
    subject: "Math",
    grade: 1,
    chapter: 13,
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  let inserted = 0;
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
    inserted++;
  }
  console.log(`Seeded ${inserted} Class 1 Math v2 questions (Chapter 13).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
