/**
 * Seed: CBSE Class 10 Hindi — 30 practice questions
 * Topics: Sparsh (Kabir, Meera), Kshitij (Ram-Lakshman-Parashuram), Vyakaran (Sangya, Sarvnam, Sandhi)
 * Questions in English (transliteration + meaning where needed)
 * Safe to re-run — skips duplicates on { questionText, subject }
 *
 * Usage:
 *   cd ai-learning-backend/backend
 *   node config/seedHindiQuestions.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const QUESTIONS = [
  // ── 1. Sparsh — Kabir Ke Dohe (5 questions) ─────────────────────────────────
  {
    topic: "Sparsh — Kabir Ke Dohe",
    subtopic: "Central Message",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In Kabir's doha 'Mati kahe kumhar se, tu kya roonde mohe...' what is the central message?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.4,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Clay teaches the potter about the cycle of creation and the transience of existence", type: "correct", logicTag: "" },
      { text: "The potter is superior to clay because he shapes it into useful objects", type: "concept_error", logicTag: "misread_hierarchy" },
      { text: "Clay represents wealth and material possessions in Kabir's philosophy", type: "concept_error", logicTag: "symbolic_meaning_missed" },
      { text: "The doha is a practical guide to the art of pottery-making", type: "guessing", logicTag: "surface_literal_reading" },
    ],
    solutionSteps: [
      "In this doha, clay (mati) questions the potter's pride — 'Why do you trample me? One day you too will become clay.'",
      "Both clay and potter will eventually return to the same earth after death.",
      "The central theme is humility (vinay) and the transience (naashtvaadita) of human existence.",
    ],
    shortcut: "Mati = clay questioning arrogance. Theme = humility + impermanence. Both become clay eventually.",
  },
  {
    topic: "Sparsh — Kabir Ke Dohe",
    subtopic: "Philosophy",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In Kabir's doha about the swan (Hans) and the lake, what does 'Hans' symbolise?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "A bird that migrates in winter", type: "concept_error", logicTag: "literal_bird_only" },
      { text: "The pure soul or Atman that must leave the body (lake)", type: "correct", logicTag: "" },
      { text: "The Hindu god Brahma whose vehicle is a swan", type: "concept_error", logicTag: "mythological_reference_misapplied" },
      { text: "A symbol of royal power and authority", type: "concept_error", logicTag: "wrong_symbolic_reading" },
    ],
    solutionSteps: [
      "In Kabir's poetry, Hans (swan) is a recurring symbol for the jivatma (individual soul).",
      "The lake (sarovar) represents the body or the world.",
      "The swan eventually departs — symbolising the soul leaving the body at death.",
    ],
    shortcut: "Hans = pure soul (jivatma). Sarovar/lake = body or worldly life. Swan departs = soul leaves body.",
  },
  {
    topic: "Sparsh — Kabir Ke Dohe",
    subtopic: "Bhakti Philosophy",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Kabir belongs to which strand of the Bhakti movement?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Saguna Bhakti (worship of God with form)", type: "concept_error", logicTag: "opposite_tradition" },
      { text: "Nirguna Bhakti (worship of formless God)", type: "correct", logicTag: "" },
      { text: "Shaiva tradition (worship of Shiva)", type: "concept_error", logicTag: "sectarian_tradition_confused" },
      { text: "Vaishnava tradition (worship of Vishnu)", type: "concept_error", logicTag: "different_tradition_misapplied" },
    ],
    solutionSteps: [
      "Kabir was a Nirguna bhakta — he believed in a formless God beyond all religious boundaries.",
      "He rejected idol worship, caste distinctions, and both Hindu and Muslim rituals.",
      "Other Saguna poets include Tulsidas (Rama) and Surdas (Krishna).",
    ],
    shortcut: "Kabir = Nirguna (formless God). Tulsidas = Saguna/Rama. Surdas = Saguna/Krishna. Mirabai = Saguna/Krishna.",
  },
  {
    topic: "Sparsh — Kabir Ke Dohe",
    subtopic: "Literary Devices",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The literary device most prominently used in Kabir's dohas is:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Shringar ras (the emotion of love/beauty)", type: "concept_error", logicTag: "romantic_rasa_wrong" },
      { text: "Upma (simile) and Rupak (metaphor) with everyday imagery", type: "correct", logicTag: "" },
      { text: "Veer ras (the emotion of heroism)", type: "concept_error", logicTag: "heroic_rasa_wrong" },
      { text: "Yamak (pun using the same word with different meanings)", type: "concept_error", logicTag: "different_device_primary" },
    ],
    solutionSteps: [
      "Kabir uses Upma (simile) and Rupak (metaphor) extensively.",
      "He draws from everyday life: potter, clay, swan, lamp, ocean — simple yet profound.",
      "His language is Sadhukkadi — a mix of Hindi, Braj, Awadhi, Punjabi, and Rajasthani.",
    ],
    shortcut: "Kabir = Upma (simile) + Rupak (metaphor) from everyday imagery. Language = Sadhukkadi (mixed).",
  },
  {
    topic: "Sparsh — Kabir Ke Dohe",
    subtopic: "Comprehension",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In Kabir's doha 'Aisi vani boliye, man ka aapa khoye...', what advice does Kabir give about speech?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Speak loudly and clearly so everyone can hear you", type: "concept_error", logicTag: "physical_voice_misread" },
      { text: "Speak in such a way that gives peace to the self and others — lose the ego in speech", type: "correct", logicTag: "" },
      { text: "Avoid speaking to strangers as it causes trouble", type: "concept_error", logicTag: "opposite_interpretation" },
      { text: "Speak only when spoken to, as silence is golden", type: "concept_error", logicTag: "different_virtue_misapplied" },
    ],
    solutionSteps: [
      "Kabir advises: speak words that give comfort (seetal kare) to the listener and peace to yourself.",
      "'Aapa khoye' means losing the ego — humility is essential in speech.",
      "Cool/sweet speech benefits both speaker and listener.",
    ],
    shortcut: "Vani doha = speak with humility and kindness. Lose ego (aapa). Sweet words benefit all.",
  },

  // ── 2. Sparsh — Meera Ke Pad (5 questions) ──────────────────────────────────
  {
    topic: "Sparsh — Meera Ke Pad",
    subtopic: "Central Theme",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The central theme of Meera's pads (poems) in the CBSE syllabus is:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "The glory of the Mughal emperors", type: "concept_error", logicTag: "historical_topic_wrong" },
      { text: "Intense devotion (viraha bhakti) to Lord Krishna and longing for union with him", type: "correct", logicTag: "" },
      { text: "The philosophy of non-violence in daily life", type: "concept_error", logicTag: "gandhi_connection_wrong" },
      { text: "Nature poetry celebrating the monsoon season", type: "concept_error", logicTag: "nature_theme_wrong" },
    ],
    solutionSteps: [
      "Meera's pads express viraha bhakti — the pain of separation from her beloved Krishna.",
      "She refers to Krishna as her husband (piya) and herself as his devotee-bride.",
      "Her poetry reflects surrender (samarpan) and unconditional love (ananya bhakti).",
    ],
    shortcut: "Meera = viraha bhakti (longing for Krishna). She is the devotee-bride. Extreme surrender.",
  },
  {
    topic: "Sparsh — Meera Ke Pad",
    subtopic: "Biography",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Meera Bai was associated with which royal family and which state of Rajasthan?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Mughal royal family of Delhi", type: "concept_error", logicTag: "wrong_dynasty" },
      { text: "Rathore clan of Merta (Jodhpur region), Rajasthan", type: "correct", logicTag: "" },
      { text: "Sisodiya clan of Udaipur (Mewar), Maharashtra", type: "concept_error", logicTag: "married_into_mewar_confused_with_origin" },
      { text: "Kachwaha clan of Jaipur (Amber)", type: "concept_error", logicTag: "different_Rajput_clan" },
    ],
    solutionSteps: [
      "Meera Bai was born into the Rathore clan at Merta (near Jodhpur).",
      "She was married into the Sisodia clan of Mewar (Udaipur) — Bhoj Raj of Chittorgarh.",
      "After her husband's death, she devoted herself entirely to Krishna and faced persecution from Mewar royals.",
    ],
    shortcut: "Born = Rathore (Merta). Married = Sisodia (Mewar). Husband died → full devotion to Krishna.",
  },
  {
    topic: "Sparsh — Meera Ke Pad",
    subtopic: "Literary Analysis",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In Meera's pad 'Main to Giridhar ke ghar jaun...', what does 'Giridhar' refer to?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Meera's father's home (maika)", type: "concept_error", logicTag: "literal_house_reading" },
      { text: "Lord Krishna who lifted the Govardhan mountain (Giridhara)", type: "correct", logicTag: "" },
      { text: "A mountain temple dedicated to Lord Shiva", type: "concept_error", logicTag: "wrong_deity" },
      { text: "Meera's in-law's palace (sasural)", type: "concept_error", logicTag: "household_confused" },
    ],
    solutionSteps: [
      "Giridhar (giri = mountain, dhar = holder) is a name of Krishna, who lifted Govardhan mountain.",
      "'Main to Giridhar ke ghar jaun' means 'I will go to the house of Krishna (my true home/beloved).'",
      "Meera declares that her true home is with Krishna, rejecting worldly ties.",
    ],
    shortcut: "Giridhar = Krishna (lifted Govardhan mountain). Meera's spiritual home = with Krishna, not her in-laws.",
  },
  {
    topic: "Sparsh — Meera Ke Pad",
    subtopic: "Symbolism",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In Meera's poetry, the poison given to her by her in-laws is described as turning sweet. This symbolises:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Meera's medical knowledge of antidotes", type: "concept_error", logicTag: "literal_misreading" },
      { text: "That divine devotion (bhakti) transforms all suffering and obstacles into blessings", type: "correct", logicTag: "" },
      { text: "Meera was immune to poison because of her caste background", type: "concept_error", logicTag: "factual_error" },
      { text: "The poison was actually a sweet drink disguised", type: "concept_error", logicTag: "literal_drink_reading" },
    ],
    solutionSteps: [
      "According to legend, Meera's in-laws sent poison in a cup of nectar to kill her.",
      "Because of her intense devotion to Krishna, the poison became nectar (amrit).",
      "This symbolises that true bhakti (devotion) removes all worldly pain and transforms suffering into joy.",
    ],
    shortcut: "Poison → nectar = bhakti transforms all suffering. Devotion is a shield against worldly harm.",
  },
  {
    topic: "Sparsh — Meera Ke Pad",
    subtopic: "Language",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The language (boli) primarily used by Meera Bai in her pads is:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Khariboli Hindi", type: "concept_error", logicTag: "standard_hindi_not_used" },
      { text: "Braj Bhasha mixed with Rajasthani", type: "correct", logicTag: "" },
      { text: "Sanskrit (tatsam words throughout)", type: "concept_error", logicTag: "high_literary_language_confused" },
      { text: "Avadhi (used by Tulsidas)", type: "concept_error", logicTag: "different_poet_language" },
    ],
    solutionSteps: [
      "Meera composed primarily in Braj Bhasha, the literary language of the Krishna bhakti tradition.",
      "Her poetry also shows influence of Rajasthani — her native language.",
      "Braj Bhasha was the dominant language for Vaishnava bhakti poetry in that era.",
    ],
    shortcut: "Meera = Braj Bhasha + Rajasthani. Kabir = Sadhukkadi. Tulsidas = Awadhi. Surdas = Braj Bhasha.",
  },

  // ── 3. Kshitij — Ram-Lakshman-Parashuram Samvad (5 questions) ───────────────
  {
    topic: "Kshitij — Ram-Lakshman-Parashuram Samvad",
    subtopic: "Characters",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In 'Ram-Lakshman-Parashuram Samvad', who broke the Shiva Dhanush (bow of Shiva)?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Lakshman", type: "concept_error", logicTag: "wrong_character" },
      { text: "Shri Ram", type: "correct", logicTag: "" },
      { text: "Parashuram himself", type: "concept_error", logicTag: "inverted_scenario" },
      { text: "King Janaka", type: "concept_error", logicTag: "host_not_breaker" },
    ],
    solutionSteps: [
      "Shri Ram broke the Shiva Dhanush during the Swayamvara of Sita.",
      "Parashuram arrived enraged at the sound of the bow breaking.",
      "He challenged Ram but was ultimately placated by Ram's humility and Lakshman's wit.",
    ],
    shortcut: "Ram broke the bow. Parashuram arrived angry. Samvad = argument between Lakshman & Parashuram.",
  },
  {
    topic: "Kshitij — Ram-Lakshman-Parashuram Samvad",
    subtopic: "Character Analysis",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the Samvad, Lakshman's attitude towards Parashuram is best described as:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Fearful and submissive", type: "concept_error", logicTag: "opposite_of_actual" },
      { text: "Bold, witty, and fearless — even provocative with sarcasm", type: "correct", logicTag: "" },
      { text: "Respectful and silent as a disciple", type: "concept_error", logicTag: "ram_attitude_confused_with_lakshman" },
      { text: "Apologetic and trying to make peace", type: "concept_error", logicTag: "ram_role_applied_to_lakshman" },
    ],
    solutionSteps: [
      "Lakshman speaks boldly and with sarcasm (vyang) to Parashuram.",
      "He mocks Parashuram's boasting: 'We have also seen many bows — this one just broke.'",
      "His fearless speech contrasts with Ram's calm humility.",
    ],
    shortcut: "Lakshman = bold, sarcastic, provocative. Ram = calm, humble, deferential.",
  },
  {
    topic: "Kshitij — Ram-Lakshman-Parashuram Samvad",
    subtopic: "Source Text",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The 'Ram-Lakshman-Parashuram Samvad' is an excerpt from which text?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Valmiki Ramayana (Sanskrit)", type: "concept_error", logicTag: "original_sanskrit_not_cbse_text" },
      { text: "Ramcharitmanas by Tulsidas (Balkand)", type: "correct", logicTag: "" },
      { text: "Padmaavat by Malik Muhammad Jayasi", type: "concept_error", logicTag: "different_text" },
      { text: "Vinay Patrika by Tulsidas", type: "concept_error", logicTag: "same_author_different_text" },
    ],
    solutionSteps: [
      "The Samvad is taken from the Balkand (Book of Childhood) of Ramcharitmanas, composed by Tulsidas.",
      "Ramcharitmanas is written in Awadhi language.",
      "Tulsidas was a 16th-century poet and a devotee of Lord Ram (Saguna bhakti tradition).",
    ],
    shortcut: "Source = Ramcharitmanas (Balkand) by Tulsidas. Language = Awadhi. Tradition = Saguna (Ram bhakti).",
  },
  {
    topic: "Kshitij — Ram-Lakshman-Parashuram Samvad",
    subtopic: "Literary Device",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The dominant literary device in Lakshman's dialogue with Parashuram is:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Karunaras (the emotion of compassion)", type: "concept_error", logicTag: "wrong_rasa" },
      { text: "Veer ras (heroism) combined with Vyang (sarcasm/irony)", type: "correct", logicTag: "" },
      { text: "Shringar ras (love and beauty)", type: "concept_error", logicTag: "romantic_rasa_wrong" },
      { text: "Shant ras (tranquility)", type: "concept_error", logicTag: "opposite_mood" },
    ],
    solutionSteps: [
      "Lakshman's speech is full of Veer ras (bravery) as he fearlessly challenges the mighty Parashuram.",
      "He also uses Vyang (sarcasm/satire): mocking Parashuram's boasting about killing Kshatriyas.",
      "This combination makes his dialogue dramatically powerful.",
    ],
    shortcut: "Lakshman = Veer ras (heroism) + Vyang (sarcasm). Parashuram = Raudra ras (anger).",
  },
  {
    topic: "Kshitij — Ram-Lakshman-Parashuram Samvad",
    subtopic: "Parashuram's Role",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is Parashuram famous for that makes him a fearsome warrior in the Samvad?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "He is an avatar of Brahma and creator of the universe", type: "concept_error", logicTag: "wrong_deity_attribute" },
      { text: "He is an avatar of Vishnu who annihilated Kshatriyas 21 times to avenge his father's death", type: "correct", logicTag: "" },
      { text: "He is an avatar of Shiva who created the Dhanush", type: "concept_error", logicTag: "wrong_deity_and_act" },
      { text: "He is a sage who gave the Dhanush to King Janaka", type: "concept_error", logicTag: "giver_role_confused" },
    ],
    solutionSteps: [
      "Parashuram is the sixth avatar of Vishnu, born to Brahmin sage Jamadagni.",
      "He annihilated Kshatriyas 21 times to avenge his father's murder by King Sahastrarjun.",
      "His association with the Shiva Dhanush explains his fury at its destruction.",
    ],
    shortcut: "Parashuram = 6th Vishnu avatar. Killed Kshatriyas 21 times. His father = Jamadagni (killed by Kshatriyas).",
  },

  // ── 4. Vyakaran — Sangya (Noun) (5 questions) ────────────────────────────────
  {
    topic: "Vyakaran — Sangya (Noun)",
    subtopic: "Types of Nouns",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is an example of 'Jatiwachak Sangya' (Common Noun) in Hindi?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Delhi (the city)", type: "concept_error", logicTag: "vyaktiwachak_proper_noun" },
      { text: "Ladka (boy — a common noun for all boys)", type: "correct", logicTag: "" },
      { text: "Pyaar (love — an abstract idea)", type: "concept_error", logicTag: "bhavwachak_abstract_noun" },
      { text: "Sena (army — a collective group)", type: "concept_error", logicTag: "samuhwachak_collective_noun" },
    ],
    solutionSteps: [
      "Jatiwachak Sangya (Common Noun) refers to a class of similar beings/things: ladka (boy), ladki (girl), ghar (house).",
      "Vyaktiwachak = proper noun (specific name): Delhi, Ram.",
      "Bhavwachak = abstract noun (feeling/quality): pyaar, khushi.",
    ],
    shortcut: "Jatiwachak = class/category. Vyaktiwachak = specific name. Bhavwachak = emotion/quality. Samuhwachak = group.",
  },
  {
    topic: "Vyakaran — Sangya (Noun)",
    subtopic: "Abstract Noun",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is a 'Bhavwachak Sangya' (Abstract Noun)?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Ganga (name of a river)", type: "concept_error", logicTag: "vyaktiwachak_proper_noun" },
      { text: "Imandaari (honesty)", type: "correct", logicTag: "" },
      { text: "Dal (army/unit)", type: "concept_error", logicTag: "samuhwachak_collective" },
      { text: "Kitab (book)", type: "concept_error", logicTag: "jatiwachak_common_noun" },
    ],
    solutionSteps: [
      "Bhavwachak Sangya (Abstract Noun) refers to ideas, qualities, or states that cannot be touched.",
      "Examples: imandaari (honesty), khushi (happiness), budhimaan (wisdom), aazaadi (freedom).",
      "Kitab (book) is concrete/jatiwachak; Ganga is proper/vyaktiwachak.",
    ],
    shortcut: "Bhavwachak = feelings, qualities, ideas. Cannot touch or see directly. Often ends in -aari, -ta, -pan.",
  },
  {
    topic: "Vyakaran — Sangya (Noun)",
    subtopic: "Collective Noun",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Identify the 'Samuhwachak Sangya' (Collective Noun) in the following options:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Larka (boy)", type: "concept_error", logicTag: "jatiwachak_common" },
      { text: "Sabhaa (assembly/gathering)", type: "correct", logicTag: "" },
      { text: "Sundar (beautiful — adjective not noun)", type: "concept_error", logicTag: "adjective_not_noun" },
      { text: "Pyaas (thirst — abstract)", type: "concept_error", logicTag: "bhavwachak_abstract" },
    ],
    solutionSteps: [
      "Samuhwachak Sangya (Collective Noun) names a group of people, animals, or things.",
      "Examples: sabhaa (assembly), sena (army), jhoond (herd/flock), kaksha (class).",
      "Sabhaa refers to a group gathered together — it is a collective noun.",
    ],
    shortcut: "Samuhwachak = group/collection. Sena, sabhaa, kaksha, jhoond = collective nouns in Hindi.",
  },
  {
    topic: "Vyakaran — Sangya (Noun)",
    subtopic: "Gender of Nouns",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "'Pustak' (book) in Hindi is of which gender (ling)?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Pulling (masculine)", type: "concept_error", logicTag: "wrong_gender" },
      { text: "Striling (feminine)", type: "correct", logicTag: "" },
      { text: "Napunsak ling (neuter)", type: "concept_error", logicTag: "hindi_has_no_neuter" },
      { text: "Both masculine and feminine", type: "concept_error", logicTag: "dual_gender_not_applicable" },
    ],
    solutionSteps: [
      "'Pustak' (book) is Striling (feminine) in Hindi.",
      "Hindi has two genders: Pulling (masculine) and Striling (feminine).",
      "Common feminine nouns: pustak, nadi, raat, baat, aankh, diwaar.",
      "Common masculine nouns: ghar, pani, din, aadmi, desh.",
    ],
    shortcut: "Pustak (book) = Striling (feminine). Hindi only has 2 genders — masculine and feminine. No neuter.",
  },
  {
    topic: "Vyakaran — Sangya (Noun)",
    subtopic: "Number of Nouns",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the plural (bahuvachan) of 'Ladki' (girl) in Hindi?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Ladkiya", type: "concept_error", logicTag: "incomplete_plural" },
      { text: "Ladkiyaan", type: "correct", logicTag: "" },
      { text: "Ladkiyon", type: "concept_error", logicTag: "oblique_case_plural" },
      { text: "Ladkis", type: "concept_error", logicTag: "english_plural_applied" },
    ],
    solutionSteps: [
      "Feminine nouns ending in 'i' form plural by adding 'yaan': ladki → ladkiyaan.",
      "In oblique case (vibhakti), the plural becomes 'ladkiyon' (used before ne, ko, se, etc.).",
      "Direct plural (prathamaa vibhakti) = ladkiyaan.",
    ],
    shortcut: "Ladki → ladkiyaan (direct plural). Ladkiyon = oblique plural (before ne/ko/se). -i endings add -yaan.",
  },

  // ── 5. Vyakaran — Sarvnam (Pronoun) (5 questions) ───────────────────────────
  {
    topic: "Vyakaran — Sarvnam (Pronoun)",
    subtopic: "Types of Pronouns",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the sentence 'Woh bahut sundar hai' (She is very beautiful), the word 'woh' is which type of sarvnam?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Nishchay Vachak Sarvnam (Demonstrative Pronoun)", type: "concept_error", logicTag: "yeh_woh_demonstrative_confusion" },
      { text: "Purush Vachak Sarvnam (Personal Pronoun)", type: "correct", logicTag: "" },
      { text: "Prashna Vachak Sarvnam (Interrogative Pronoun)", type: "concept_error", logicTag: "question_pronoun_confused" },
      { text: "Sambandh Vachak Sarvnam (Relative Pronoun)", type: "concept_error", logicTag: "relative_pronoun_confused" },
    ],
    solutionSteps: [
      "'Woh' is a third-person personal pronoun (Purush Vachak Sarvnam).",
      "Personal pronouns: Main (I), Hum (We), Tu/Tum/Aap (You), Woh/Ve (He/She/They).",
      "Demonstrative pronouns (Nishchay Vachak) also use Yeh/Woh but point to specific objects.",
    ],
    shortcut: "Purush Vachak = I/We/You/He/She/They (personal). Three categories: uttam (I), madhyam (you), antam (he/she).",
  },
  {
    topic: "Vyakaran — Sarvnam (Pronoun)",
    subtopic: "Reflexive Pronoun",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is a 'Nij Vachak Sarvnam' (Reflexive Pronoun) in Hindi?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Koi (someone)", type: "concept_error", logicTag: "anishchay_indefinite" },
      { text: "Apne aap / Khud (oneself/myself)", type: "correct", logicTag: "" },
      { text: "Jo-So (who-that — relative)", type: "concept_error", logicTag: "sambandh_relative" },
      { text: "Kaun (who — question)", type: "concept_error", logicTag: "prashna_interrogative" },
    ],
    solutionSteps: [
      "Nij Vachak Sarvnam (Reflexive Pronoun) refers back to the subject of the sentence.",
      "'Woh apne aap karta hai' = He does it himself. 'Apne aap' / 'Khud' are reflexive.",
      "Other pronouns: Koi (indefinite), Jo-So (relative), Kaun/Kya (interrogative).",
    ],
    shortcut: "Nij Vachak = apne aap, khud, svayam. Reflects back to the doer. 'I did it myself.'",
  },
  {
    topic: "Vyakaran — Sarvnam (Pronoun)",
    subtopic: "Interrogative Pronoun",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Identify the 'Prashna Vachak Sarvnam' (Interrogative Pronoun) in the sentence: 'Kaun aa raha hai?'",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "aa (come)", type: "concept_error", logicTag: "verb_not_pronoun" },
      { text: "Kaun (who)", type: "correct", logicTag: "" },
      { text: "raha (progressive marker)", type: "concept_error", logicTag: "auxiliary_not_pronoun" },
      { text: "hai (is)", type: "concept_error", logicTag: "copula_not_pronoun" },
    ],
    solutionSteps: [
      "'Kaun' (who) is a Prashna Vachak Sarvnam (Interrogative Pronoun).",
      "Other interrogative pronouns: Kya (what), Kis (whom — oblique of kaun), Kiska (whose).",
      "They are used to ask questions about people or things.",
    ],
    shortcut: "Prashna Vachak = Kaun (who), Kya (what), Kab (when used as pronoun). Ask questions.",
  },
  {
    topic: "Vyakaran — Sarvnam (Pronoun)",
    subtopic: "Pronoun in Context",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In 'Jo mehnat karta hai, woh safal hota hai' (Who works hard, he succeeds), the pronoun pair 'Jo...Woh' is:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Purush Vachak Sarvnam (Personal Pronoun)", type: "concept_error", logicTag: "personal_pronoun_confused" },
      { text: "Sambandh Vachak Sarvnam (Relative Pronoun)", type: "correct", logicTag: "" },
      { text: "Nishchay Vachak Sarvnam (Demonstrative Pronoun)", type: "concept_error", logicTag: "demonstrative_confused" },
      { text: "Anishchay Vachak Sarvnam (Indefinite Pronoun)", type: "concept_error", logicTag: "indefinite_confused" },
    ],
    solutionSteps: [
      "Sambandh Vachak Sarvnam (Relative Pronoun) connects two clauses using 'Jo...So/Woh'.",
      "'Jo...Woh' pattern = whoever...he/that. It creates a conditional-relational sentence.",
      "Other relative pairs: Jo...wahi, Jaise...waise, Jab...tab.",
    ],
    shortcut: "Sambandh Vachak = Jo...Woh/So (whoever...that). Connects two related clauses.",
  },
  {
    topic: "Vyakaran — Sarvnam (Pronoun)",
    subtopic: "Pronoun Usage",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the correct polite form (aadarniya roop) of the second person pronoun in Hindi?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Tu (thou/you — very informal)", type: "concept_error", logicTag: "least_formal" },
      { text: "Aap (you — most respectful form)", type: "correct", logicTag: "" },
      { text: "Tum (you — neutral/informal form)", type: "concept_error", logicTag: "informal_not_formal" },
      { text: "Woh (he/she — third person)", type: "concept_error", logicTag: "third_person_not_second" },
    ],
    solutionSteps: [
      "Hindi has three levels of second person pronoun: Tu (intimate/disrespectful), Tum (informal/equal), Aap (formal/respectful).",
      "Aap is the most polite form, used for elders, strangers, or respected individuals.",
      "Aap also has plural usage (you all), making it the most versatile polite form.",
    ],
    shortcut: "Tu = intimate/rude. Tum = casual/peer. Aap = formal/respectful. Always use Aap for elders/strangers.",
  },

  // ── 6. Vyakaran — Sandhi (5 questions) ──────────────────────────────────────
  {
    topic: "Vyakaran — Sandhi",
    subtopic: "Types of Sandhi",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "When two vowels combine at the junction of two words, what type of Sandhi occurs?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Vyanjan Sandhi (Consonant Junction)", type: "concept_error", logicTag: "wrong_sandhi_type" },
      { text: "Swar Sandhi (Vowel Junction)", type: "correct", logicTag: "" },
      { text: "Visarg Sandhi (Visarga Junction)", type: "concept_error", logicTag: "different_sandhi" },
      { text: "Anunaasik Sandhi (Nasal Junction)", type: "concept_error", logicTag: "subtype_confused" },
    ],
    solutionSteps: [
      "Sandhi is the joining of two sounds (varnas) to form a smoother pronunciation.",
      "Swar Sandhi occurs when two vowels (swar) meet at the junction.",
      "Vyanjan Sandhi occurs when a vowel meets a consonant or two consonants meet.",
    ],
    shortcut: "Swar + Swar = Swar Sandhi. Vyanjan involved = Vyanjan Sandhi. Visarg (:) involved = Visarg Sandhi.",
  },
  {
    topic: "Vyakaran — Sandhi",
    subtopic: "Sandhi Vichchhed",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the Sandhi Vichchhed (splitting) of the word 'Himalaya' (हिमालय)?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Him + Aalay", type: "concept_error", logicTag: "wrong_split_double_a" },
      { text: "Hima + Aalay", type: "correct", logicTag: "" },
      { text: "Himu + Aalay", type: "concept_error", logicTag: "wrong_first_part" },
      { text: "Himalay + a", type: "concept_error", logicTag: "arbitrary_split" },
    ],
    solutionSteps: [
      "'Himalaya' = 'Hima' (snow) + 'Aalay' (home/abode) = 'Home of snow'.",
      "Here 'a' (hima) + 'aa' (aalay) → 'aa' (dirgha sandhi): a + aa = aa.",
      "This is an example of Dirgha Swar Sandhi (long vowel junction).",
    ],
    shortcut: "Himalaya = Hima + Aalay. a + aa = aa (Dirgha Sandhi). Mountain = abode of snow.",
  },
  {
    topic: "Vyakaran — Sandhi",
    subtopic: "Sandhi Formation",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Sandhi of 'Vidya + Aalay' is:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Vidyalay", type: "concept_error", logicTag: "missing_aa_in_result" },
      { text: "Vidyaalaya", type: "correct", logicTag: "" },
      { text: "Vidyaalay", type: "concept_error", logicTag: "incomplete_final_vowel" },
      { text: "Vidya-Alaya (no sandhi)", type: "concept_error", logicTag: "sandhi_not_applied" },
    ],
    solutionSteps: [
      "'Vidya' ends in 'aa'. 'Aalay' starts with 'aa'.",
      "aa + aa = aa (Dirgha Sandhi): the two identical long vowels merge into one.",
      "Result: Vidyaalaya (school / place of learning).",
    ],
    shortcut: "aa + aa = aa (not aaaa!). Vidya + Aalay = Vidyaalaya. Dirgha Sandhi = identical vowels merge.",
  },
  {
    topic: "Vyakaran — Sandhi",
    subtopic: "Visarg Sandhi",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In Visarg Sandhi, when Visarga (ः) is followed by a voiced consonant (ghosh varna), it becomes:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "It remains as Visarga (ः)", type: "concept_error", logicTag: "no_change_assumed" },
      { text: "It becomes 'o' (o-kaar): aah + aas → aho/o-sound", type: "concept_error", logicTag: "specific_rule_confused" },
      { text: "It becomes 'r' (ra): Nih + dhana → Nirdhana (nih+dh → nir)", type: "correct", logicTag: "" },
      { text: "It is dropped silently with no change", type: "concept_error", logicTag: "disappear_rule_wrong" },
    ],
    solutionSteps: [
      "In Visarg Sandhi, when Visarga follows 'a/aa' and is followed by a voiced consonant, it becomes 'r'.",
      "Example: Nih + dhana = Nirdhana (poor). Nih + bala = Nirbala (weak).",
      "This is the Ra-kaar Visarg Sandhi rule (र-कार विसर्ग संधि).",
    ],
    shortcut: "Visarg + voiced consonant → 'r' (rakaar). Nih + dhana = Nir + dhana = Nirdhana.",
  },
  {
    topic: "Vyakaran — Sandhi",
    subtopic: "Sandhi Identification",
    subject: "Hindi",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is an example of 'Ayaadi Sandhi' (where 'e/o/ai/au' changes before vowel)?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.78,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Ram + Aayan = Ramaayan (a+aa=aa)", type: "concept_error", logicTag: "dirgha_sandhi_not_ayaadi" },
      { text: "Nau + Ik = Navik (au + i → av + i)", type: "correct", logicTag: "" },
      { text: "Swar + Sandhi = Swarsandhi (no vowel change)", type: "concept_error", logicTag: "compound_word_not_sandhi" },
      { text: "Hari + Om = Hariom (no special change)", type: "concept_error", logicTag: "simple_concatenation" },
    ],
    solutionSteps: [
      "Ayaadi Sandhi: when 'e/o/ai/au' comes before a vowel, it changes — 'au' becomes 'av'.",
      "Nau (nine) + Ik (one) = Nav + ik = Navik (sailor). 'au' + 'i' → 'av' + 'i'.",
      "Similarly: Nau + Aadhya = Navadhya; Pau + Ana = Pavan.",
    ],
    shortcut: "Ayaadi: e→ay, o→av, ai→aay, au→aav before another vowel. Nau+ik=Navik (au→av).",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  let added = 0, skipped = 0;
  for (const q of QUESTIONS) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    added++;
  }
  console.log(`Hindi questions: ${added} added, ${skipped} skipped`);
  await mongoose.disconnect();
}

seed().catch(console.error);
