/**
 * seedMath1QuestionsV2F.js
 * Class 1 Mathematics v2 — Chapters 11–12 (64 questions)
 * Numbers to 99 and Money
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";

dotenv.config();

const questions = [

  // ── Ch11 S1: Tens and Ones (math1_ch11_tens_and_ones) ────────────────────────
  { questionId:"math1_ch11_tens_and_ones_q1", topicId:"math1_ch11_tens_and_ones", text:"In the number 34, what is the TENS digit?", options:[{text:"4",type:"concept_error",logicTag:"4 is the ones digit"},{text:"34",type:"concept_error",logicTag:"whole number not one digit"},{text:"3",type:"correct",logicTag:"3 is in tens place"},{text:"7",type:"concept_error",logicTag:"not in the number"}], explanation:"In 34, the digit '3' is in the tens place. 3 tens = 30.", solutionSteps:["34: left digit = tens","Tens digit = 3"], shortcut:"Left digit = tens.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_tens_and_ones_q2", topicId:"math1_ch11_tens_and_ones", text:"In 67, the digit 7 is in the ___ place.", options:[{text:"Tens",type:"concept_error",logicTag:"7 is on the right"},{text:"Hundreds",type:"concept_error",logicTag:"no hundreds in two-digit"},{text:"Ones",type:"correct",logicTag:"right digit = ones"},{text:"Thousands",type:"concept_error",logicTag:"wrong"}], explanation:"In 67, the right digit (7) is in the ones place.", solutionSteps:["67: right digit = ones","7 is ones digit"], shortcut:"Right digit = ones.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_tens_and_ones_q3", topicId:"math1_ch11_tens_and_ones", text:"What is the VALUE of the digit '5' in 53?", options:[{text:"5",type:"concept_error",logicTag:"5 in ones = 5; in tens = 50"},{text:"3",type:"concept_error",logicTag:"that's the ones digit"},{text:"50",type:"correct",logicTag:"5 in tens place = 50"},{text:"35",type:"concept_error",logicTag:"that's reversed"}], explanation:"In 53, the '5' is in the tens place. Its value = 5 × 10 = 50.", solutionSteps:["5 is in the tens place","Value = 5 × 10 = 50"], shortcut:"Tens place value = digit × 10.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_tens_and_ones_q4", topicId:"math1_ch11_tens_and_ones", text:"85 = ___ tens + ___ ones.", options:[{text:"5 tens + 8 ones",type:"concept_error",logicTag:"digits reversed"},{text:"8 tens + 5 ones",type:"correct",logicTag:"85 = 80 + 5"},{text:"8 tens + 0 ones",type:"concept_error",logicTag:"forgot ones"},{text:"0 tens + 85 ones",type:"concept_error",logicTag:"no tens recognised"}], explanation:"85 = 8 tens + 5 ones = 80 + 5.", solutionSteps:["85: tens digit = 8, ones digit = 5","8 tens + 5 ones"], shortcut:"Tens digit + ones digit.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_tens_and_ones_q5", topicId:"math1_ch11_tens_and_ones", text:"3 tens + 9 ones = ___.", options:[{text:"93",type:"concept_error",logicTag:"digits reversed"},{text:"39",type:"correct",logicTag:"30+9=39"},{text:"30",type:"concept_error",logicTag:"forgot ones"},{text:"9",type:"concept_error",logicTag:"only ones"}], explanation:"3 tens = 30, 9 ones = 9. 30 + 9 = 39.", solutionSteps:["3 tens = 30","9 ones = 9","30 + 9 = 39"], shortcut:"tens digit + ones digit → write side by side.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_tens_and_ones_q6", topicId:"math1_ch11_tens_and_ones", text:"Which number has the SAME tens and ones digit?", options:[{text:"73",type:"concept_error",logicTag:"7 ≠ 3"},{text:"55",type:"correct",logicTag:"5 tens and 5 ones"},{text:"62",type:"concept_error",logicTag:"6 ≠ 2"},{text:"84",type:"concept_error",logicTag:"8 ≠ 4"}], explanation:"55 has tens digit 5 and ones digit 5 — both the same.", solutionSteps:["55: tens=5, ones=5","Same digit"], shortcut:"Look for repeated digit numbers: 11,22,33,44,55…", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_tens_and_ones_q7", topicId:"math1_ch11_tens_and_ones", text:"What is the ONES digit of 92?", options:[{text:"9",type:"concept_error",logicTag:"9 is tens digit"},{text:"92",type:"concept_error",logicTag:"whole number"},{text:"2",type:"correct",logicTag:"ones digit = 2"},{text:"0",type:"concept_error",logicTag:"not in the number"}], explanation:"In 92, the ones digit (right digit) is 2.", solutionSteps:["92: ones digit = 2 (on the right)"], shortcut:"Right digit = ones.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_tens_and_ones_q8", topicId:"math1_ch11_tens_and_ones", text:"A number has 7 tens and 0 ones. What is the number?", options:[{text:"7",type:"concept_error",logicTag:"just the tens digit"},{text:"17",type:"concept_error",logicTag:"not right"},{text:"70",type:"correct",logicTag:"7 tens + 0 ones = 70"},{text:"07",type:"concept_error",logicTag:"leading zero"}], explanation:"7 tens + 0 ones = 70.", solutionSteps:["7 tens = 70","0 ones = 0","70 + 0 = 70"], shortcut:"N tens + 0 ones = N0.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },

  // ── Ch11 S2: Numbers 51 to 75 (math1_ch11_numbers_51_to_75) ──────────────────
  { questionId:"math1_ch11_numbers_51_to_75_q1", topicId:"math1_ch11_numbers_51_to_75", text:"63 = ___ tens + ___ ones.", options:[{text:"3 tens + 6 ones",type:"concept_error",logicTag:"reversed"},{text:"6 tens + 3 ones",type:"correct",logicTag:"63=60+3"},{text:"6 tens + 0 ones",type:"concept_error",logicTag:"that's 60"},{text:"7 tens + 3 ones",type:"concept_error",logicTag:"wrong tens"}], explanation:"63 = 6 tens + 3 ones.", solutionSteps:["63: tens=6, ones=3","6 tens + 3 ones"], shortcut:"Left digit = tens.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_51_to_75_q2", topicId:"math1_ch11_numbers_51_to_75", text:"What number comes AFTER 69?", options:[{text:"68",type:"concept_error",logicTag:"before 69"},{text:"71",type:"concept_error",logicTag:"skipped 70"},{text:"70",type:"correct",logicTag:"after 69 = 70"},{text:"79",type:"concept_error",logicTag:"too far"}], explanation:"After 69 comes 70 (new tens group).", solutionSteps:["…68,69,70…","After 69 = 70"], shortcut:"69 → 70.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_51_to_75_q3", topicId:"math1_ch11_numbers_51_to_75", text:"Seventy = ?", options:[{text:"17",type:"concept_error",logicTag:"seventeen"},{text:"7",type:"concept_error",logicTag:"just 7"},{text:"170",type:"concept_error",logicTag:"too big"},{text:"70",type:"correct",logicTag:"seventy = 70"}], explanation:"Seventy = 70 (7 tens).", solutionSteps:["Seven-ty = 7 tens = 70"], shortcut:"Seven-ty = 70.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_51_to_75_q4", topicId:"math1_ch11_numbers_51_to_75", text:"Which is GREATER: 58 or 75?", options:[{text:"58",type:"concept_error",logicTag:"5 tens < 7 tens"},{text:"Both equal",type:"concept_error",logicTag:"not equal"},{text:"75",type:"correct",logicTag:"7 tens > 5 tens"},{text:"Cannot tell",type:"guessing",logicTag:"can compare"}], explanation:"75 has 7 tens; 58 has 5 tens. 7 > 5 → 75 > 58.", solutionSteps:["58: 5 tens","75: 7 tens","7 > 5 → 75 > 58"], shortcut:"Compare tens first.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_51_to_75_q5", topicId:"math1_ch11_numbers_51_to_75", text:"Order: 52, 74, 61, 65, 57 — largest first.", options:[{text:"52,57,61,65,74",type:"concept_error",logicTag:"smallest first"},{text:"74,65,61,57,52",type:"correct",logicTag:"descending"},{text:"74,61,65,57,52",type:"concept_error",logicTag:"not fully ordered"},{text:"52,61,57,65,74",type:"concept_error",logicTag:"not ordered"}], explanation:"Descending: 74, 65, 61, 57, 52.", solutionSteps:["Tens: 7>6>6>5>5","Then compare ones for ties: 65>61, 57>52","Order: 74,65,61,57,52"], shortcut:"Largest tens first, then compare ones for ties.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_51_to_75_q6", topicId:"math1_ch11_numbers_51_to_75", text:"What is the word name for 64?", options:[{text:"Sixty-four",type:"correct",logicTag:"60+4=64"},{text:"Forty-six",type:"concept_error",logicTag:"reversed"},{text:"Sixty",type:"concept_error",logicTag:"forgot ones"},{text:"Six-four",type:"concept_error",logicTag:"wrong format"}], explanation:"64 = sixty-four.", solutionSteps:["Tens = sixty","Ones = four","Together = sixty-four"], shortcut:"Sixty + ones digit name.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_51_to_75_q7", topicId:"math1_ch11_numbers_51_to_75", text:"How many tens are in 73?", options:[{text:"3",type:"concept_error",logicTag:"3 is ones"},{text:"10",type:"concept_error",logicTag:"too many"},{text:"7",type:"correct",logicTag:"73 = 7 tens + 3 ones"},{text:"73",type:"concept_error",logicTag:"whole number"}], explanation:"73 has 7 tens (tens digit = 7).", solutionSteps:["73: tens digit = 7","7 tens = 70"], shortcut:"Tens digit of 73 = 7.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_51_to_75_q8", topicId:"math1_ch11_numbers_51_to_75", text:"Fill in the missing number: 67, 68, ___, 70, 71.", options:[{text:"66",type:"concept_error",logicTag:"before 67"},{text:"72",type:"concept_error",logicTag:"after 71"},{text:"69",type:"correct",logicTag:"between 68 and 70"},{text:"65",type:"concept_error",logicTag:"too small"}], explanation:"67, 68, 69, 70, 71 — missing = 69.", solutionSteps:["Count up: 67,68,69,70,71","Missing = 69"], shortcut:"Count up from 68.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },

  // ── Ch11 S3: Numbers 76 to 99 (math1_ch11_numbers_76_to_99) ──────────────────
  { questionId:"math1_ch11_numbers_76_to_99_q1", topicId:"math1_ch11_numbers_76_to_99", text:"88 = ___ tens + ___ ones.", options:[{text:"8 tens + 8 ones",type:"correct",logicTag:"eighty-eight"},{text:"8 tens + 0 ones",type:"concept_error",logicTag:"that's 80"},{text:"0 tens + 88 ones",type:"concept_error",logicTag:"no tens"},{text:"9 tens + 8 ones",type:"concept_error",logicTag:"wrong tens"}], explanation:"88 = 8 tens + 8 ones = eighty-eight.", solutionSteps:["88: tens=8, ones=8","8 tens + 8 ones"], shortcut:"Same digits: 8 tens + 8 ones = 88.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_76_to_99_q2", topicId:"math1_ch11_numbers_76_to_99", text:"What comes AFTER 99?", options:[{text:"98",type:"concept_error",logicTag:"before 99"},{text:"100",type:"correct",logicTag:"after 99 = 100"},{text:"90",type:"concept_error",logicTag:"too far back"},{text:"109",type:"concept_error",logicTag:"skipped 100"}], explanation:"After 99 comes 100 — the first three-digit number.", solutionSteps:["99 is the last two-digit number","99 + 1 = 100"], shortcut:"99 → 100.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_76_to_99_q3", topicId:"math1_ch11_numbers_76_to_99", text:"Ninety = ?", options:[{text:"19",type:"concept_error",logicTag:"nineteen"},{text:"9",type:"concept_error",logicTag:"single digit"},{text:"900",type:"concept_error",logicTag:"nine hundred"},{text:"90",type:"correct",logicTag:"ninety = 90"}], explanation:"Ninety = 90 (9 tens). Note: spelled NINETY not 'ninty'.", solutionSteps:["Nine-ty = 9 tens = 90"], shortcut:"Nine-ty = 90. Spell it NINETY.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_76_to_99_q4", topicId:"math1_ch11_numbers_76_to_99", text:"Which is the LARGEST: 79, 97, 89, 77?", options:[{text:"79",type:"concept_error",logicTag:"7 tens"},{text:"89",type:"concept_error",logicTag:"8 tens"},{text:"77",type:"concept_error",logicTag:"7 tens"},{text:"97",type:"correct",logicTag:"9 tens = largest"}], explanation:"97 has 9 tens — the most of any number in the list.", solutionSteps:["79,77: 7 tens","89: 8 tens","97: 9 tens → largest"], shortcut:"Most tens = biggest number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_76_to_99_q5", topicId:"math1_ch11_numbers_76_to_99", text:"99 is how many less than 100?", options:[{text:"0",type:"concept_error",logicTag:"not equal"},{text:"9",type:"calculation_error",logicTag:"wrong"},{text:"1",type:"correct",logicTag:"100-99=1"},{text:"10",type:"calculation_error",logicTag:"wrong"}], explanation:"100 − 99 = 1. 99 is one less than 100.", solutionSteps:["100 − 99 = 1","99 is 1 less than 100"], shortcut:"99 = 100 − 1.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_76_to_99_q6", topicId:"math1_ch11_numbers_76_to_99", text:"What is the word name for 86?", options:[{text:"Sixty-eight",type:"concept_error",logicTag:"reversed"},{text:"Eighty-six",type:"correct",logicTag:"80+6=86"},{text:"Eighty",type:"concept_error",logicTag:"forgot ones"},{text:"Ninety-six",type:"concept_error",logicTag:"wrong tens"}], explanation:"86 = eighty-six.", solutionSteps:["Tens = eighty","Ones = six","Together = eighty-six"], shortcut:"Eighty + ones name = eighty-six.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_76_to_99_q7", topicId:"math1_ch11_numbers_76_to_99", text:"Order from SMALLEST to LARGEST: 91, 79, 87, 95, 83.", options:[{text:"95,91,87,83,79",type:"concept_error",logicTag:"descending"},{text:"79,83,87,91,95",type:"correct",logicTag:"ascending"},{text:"79,87,83,91,95",type:"concept_error",logicTag:"not fully sorted"},{text:"83,79,87,91,95",type:"concept_error",logicTag:"not sorted"}], explanation:"Ascending: 79, 83, 87, 91, 95.", solutionSteps:["Tens: 7<8<8<9<9","Ones to break ties: 83<87, 91<95","Order: 79,83,87,91,95"], shortcut:"Sort tens first, then ones.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_numbers_76_to_99_q8", topicId:"math1_ch11_numbers_76_to_99", text:"The number 99 is the LAST ___ number.", options:[{text:"Single-digit",type:"concept_error",logicTag:"single-digit ends at 9"},{text:"Three-digit",type:"concept_error",logicTag:"three digits starts at 100"},{text:"Two-digit",type:"correct",logicTag:"last two-digit number before 100"},{text:"Even",type:"concept_error",logicTag:"99 is odd"}], explanation:"99 is the last two-digit number. The next number (100) has three digits.", solutionSteps:["Two-digit: 10 to 99","99 = last two-digit","100 = first three-digit"], shortcut:"99 = last two-digit. 100 = first three-digit.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },

  // ── Ch11 S4: Comparing Two-Digit Numbers (math1_ch11_comparing_two_digit) ─────
  { questionId:"math1_ch11_comparing_two_digit_q1", topicId:"math1_ch11_comparing_two_digit", text:"Compare: 74 ___ 47. Which symbol fits?", options:[{text:"<",type:"concept_error",logicTag:"74 > 47"},{text:"=",type:"concept_error",logicTag:"not equal"},{text:">",type:"correct",logicTag:"7 tens > 4 tens"},{text:"None",type:"guessing",logicTag:"a symbol fits"}], explanation:"74 has 7 tens; 47 has 4 tens. 7 > 4 → 74 > 47.", solutionSteps:["Tens: 7 vs 4","7 > 4 → 74 > 47"], shortcut:"Compare tens: 7 > 4.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_comparing_two_digit_q2", topicId:"math1_ch11_comparing_two_digit", text:"85 ___ 89: which symbol?", options:[{text:">",type:"concept_error",logicTag:"5 < 9"},{text:"=",type:"concept_error",logicTag:"not equal"},{text:"<",type:"correct",logicTag:"same tens; 5 < 9"},{text:"None",type:"guessing",logicTag:"a symbol fits"}], explanation:"Same tens (8). Compare ones: 5 < 9 → 85 < 89.", solutionSteps:["Tens equal (8=8)","Ones: 5 < 9 → 85 < 89"], shortcut:"Same tens → compare ones.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_comparing_two_digit_q3", topicId:"math1_ch11_comparing_two_digit", text:"Which of these means 'GREATER THAN'?", options:[{text:"<",type:"concept_error",logicTag:"less than"},{text:"=",type:"concept_error",logicTag:"equal to"},{text:">",type:"correct",logicTag:"greater than"},{text:"−",type:"concept_error",logicTag:"minus sign"}], explanation:"'>' means greater than. The open mouth faces the bigger number.", solutionSteps:["< = less than","= = equal to","> = greater than"], shortcut:"> = greater than.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_comparing_two_digit_q4", topicId:"math1_ch11_comparing_two_digit", text:"The 'crocodile' in the > and < symbols always opens its mouth toward the ___ number.", options:[{text:"Smaller",type:"concept_error",logicTag:"mouth faces bigger"},{text:"First number",type:"concept_error",logicTag:"not based on position"},{text:"Larger",type:"correct",logicTag:"crocodile eats the bigger number"},{text:"Random",type:"concept_error",logicTag:"has a rule"}], explanation:"The open side of > and < always faces the larger number — 'the crocodile eats the bigger number'.", solutionSteps:["5 < 9: open side faces 9 (bigger)","9 > 5: open side faces 9"], shortcut:"Open side = bigger number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_comparing_two_digit_q5", topicId:"math1_ch11_comparing_two_digit", text:"Which comparison is CORRECT?", options:[{text:"56 > 65",type:"concept_error",logicTag:"5 tens < 6 tens"},{text:"72 < 27",type:"concept_error",logicTag:"7 tens > 2 tens"},{text:"43 = 43",type:"correct",logicTag:"same number = equal"},{text:"91 < 19",type:"concept_error",logicTag:"9 tens > 1 ten"}], explanation:"43 = 43. A number always equals itself.", solutionSteps:["43 and 43 are identical","Equal → ="], shortcut:"Same number = equal.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_comparing_two_digit_q6", topicId:"math1_ch11_comparing_two_digit", text:"Put in order (smallest to largest): 53, 35, 73, 37.", options:[{text:"73,53,37,35",type:"concept_error",logicTag:"descending"},{text:"35,37,53,73",type:"correct",logicTag:"ascending"},{text:"35,53,37,73",type:"concept_error",logicTag:"not sorted"},{text:"37,35,53,73",type:"concept_error",logicTag:"35 should come before 37"}], explanation:"Ascending: 35, 37, 53, 73.", solutionSteps:["Tens: 3,3,5,7","Within same tens: 35<37","Order: 35,37,53,73"], shortcut:"Tens first, then ones.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_comparing_two_digit_q7", topicId:"math1_ch11_comparing_two_digit", text:"If 6 tens > 4 tens, then 68 ___ 49.", options:[{text:"<",type:"concept_error",logicTag:"68 > 49"},{text:"=",type:"concept_error",logicTag:"not equal"},{text:">",type:"correct",logicTag:"6 tens > 4 tens"},{text:"Cannot tell",type:"guessing",logicTag:"can tell from tens"}], explanation:"6 tens > 4 tens → 68 > 49.", solutionSteps:["Tens: 6 > 4","→ 68 > 49"], shortcut:"More tens = bigger.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },
  { questionId:"math1_ch11_comparing_two_digit_q8", topicId:"math1_ch11_comparing_two_digit", text:"The LARGEST two-digit number possible is ___.", options:[{text:"90",type:"concept_error",logicTag:"ones can go higher"},{text:"99",type:"correct",logicTag:"9 tens + 9 ones = 99"},{text:"100",type:"concept_error",logicTag:"three digits"},{text:"89",type:"concept_error",logicTag:"9 tens > 8 tens"}], explanation:"The largest two-digit number is 99 (9 tens + 9 ones).", solutionSteps:["Max tens = 9","Max ones = 9","9 tens + 9 ones = 99"], shortcut:"Largest two-digit = 99.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"11" },

  // ── Ch12 S1: Identifying Coins and Notes (math1_ch12_coins_and_notes) ─────────
  { questionId:"math1_ch12_coins_and_notes_q1", topicId:"math1_ch12_coins_and_notes", text:"Which is a COIN (not a note)?", options:[{text:"₹50 paper",type:"concept_error",logicTag:"notes are paper"},{text:"₹100 paper",type:"concept_error",logicTag:"note"},{text:"₹5 metal",type:"correct",logicTag:"coins are metal"},{text:"₹10 paper",type:"concept_error",logicTag:"note"}], explanation:"Coins are made of metal (₹1, ₹2, ₹5, ₹10 coins). Notes are paper.", solutionSteps:["Coins = metal","₹5 metal = coin"], shortcut:"Metal = coin. Paper = note.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_coins_and_notes_q2", topicId:"math1_ch12_coins_and_notes", text:"You see a paper currency with '50' on it. It is a ₹___ note.", options:[{text:"₹5",type:"concept_error",logicTag:"5 not 50"},{text:"₹500",type:"concept_error",logicTag:"500 not 50"},{text:"₹50",type:"correct",logicTag:"read the number"},{text:"₹5000",type:"concept_error",logicTag:"wrong"}], explanation:"The number on a note tells its value. '50' = ₹50 note.", solutionSteps:["Read the number: 50","₹50 note"], shortcut:"Read the number on the note.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_coins_and_notes_q3", topicId:"math1_ch12_coins_and_notes", text:"A ₹2 coin is ___ in value than a ₹5 coin.", options:[{text:"More",type:"concept_error",logicTag:"₹2 < ₹5"},{text:"Equal",type:"concept_error",logicTag:"not equal"},{text:"Less",type:"correct",logicTag:"2 < 5"},{text:"Cannot compare",type:"guessing",logicTag:"can compare"}], explanation:"₹2 < ₹5. The ₹5 coin is worth more.", solutionSteps:["₹2 and ₹5","2 < 5 → ₹2 is less"], shortcut:"Higher number = more value.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_coins_and_notes_q4", topicId:"math1_ch12_coins_and_notes", text:"A BIG coin is always worth MORE. True or False?", options:[{text:"True",type:"concept_error",logicTag:"size ≠ value in coins"},{text:"False",type:"correct",logicTag:"value = number on coin, not size"},{text:"Sometimes",type:"partial_logic",logicTag:"not reliable rule"},{text:"Only for silver coins",type:"concept_error",logicTag:"irrelevant"}], explanation:"FALSE. A ₹1 coin can be larger than a ₹2 coin. Always read the number for the value.", solutionSteps:["Coin value = number stamped on it","Size doesn't determine value"], shortcut:"Read the number, not the size.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_coins_and_notes_q5", topicId:"math1_ch12_coins_and_notes", text:"Which coins are available in India? (Select the correct set)", options:[{text:"₹1, ₹2, ₹5, ₹10",type:"correct",logicTag:"common Indian coins"},{text:"₹1, ₹3, ₹7, ₹11",type:"concept_error",logicTag:"₹3,₹7,₹11 don't exist"},{text:"₹5, ₹10, ₹15, ₹20",type:"concept_error",logicTag:"₹15 doesn't exist as coin"},{text:"₹2, ₹4, ₹6, ₹8",type:"concept_error",logicTag:"₹4,₹6,₹8 don't exist"}], explanation:"Common Indian coins: ₹1, ₹2, ₹5, ₹10.", solutionSteps:["Indian coins: ₹1, ₹2, ₹5, ₹10"], shortcut:"Coins: ₹1, ₹2, ₹5, ₹10.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_coins_and_notes_q6", topicId:"math1_ch12_coins_and_notes", text:"How many ₹2 coins equal one ₹10 coin?", options:[{text:"2",type:"calculation_error",logicTag:"2×2=4, not 10"},{text:"4",type:"calculation_error",logicTag:"4×2=8, not 10"},{text:"5",type:"correct",logicTag:"5×2=10"},{text:"10",type:"calculation_error",logicTag:"10×2=20"}], explanation:"5 × ₹2 = ₹10.", solutionSteps:["₹2 × ? = ₹10","₹10 ÷ ₹2 = 5","5 coins of ₹2 = ₹10"], shortcut:"10 ÷ 2 = 5 coins.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_coins_and_notes_q7", topicId:"math1_ch12_coins_and_notes", text:"Which is LARGER in value: a ₹10 note or a ₹10 coin?", options:[{text:"₹10 note (more)",type:"concept_error",logicTag:"same value"},{text:"₹10 coin (more)",type:"concept_error",logicTag:"same value"},{text:"They are equal in value",type:"correct",logicTag:"both = ₹10"},{text:"Cannot compare",type:"guessing",logicTag:"can compare"}], explanation:"₹10 note and ₹10 coin both have the same value: ten rupees.", solutionSteps:["Note ₹10 = 10 rupees","Coin ₹10 = 10 rupees","Equal value"], shortcut:"Same number = same value, regardless of form.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_coins_and_notes_q8", topicId:"math1_ch12_coins_and_notes", text:"Notes (paper money) generally have ___ values than coins.", options:[{text:"Smaller",type:"concept_error",logicTag:"notes have bigger values"},{text:"Equal",type:"concept_error",logicTag:"notes can be much bigger"},{text:"Larger",type:"correct",logicTag:"₹50,₹100,₹200 etc. are notes"},{text:"No",type:"concept_error",logicTag:"notes have values"}], explanation:"Notes come in larger denominations: ₹10, ₹20, ₹50, ₹100, ₹200, ₹500, ₹2000.", solutionSteps:["Coins: ₹1 to ₹10","Notes: ₹10 upward to ₹2000","Notes have generally larger values"], shortcut:"Large amounts = notes.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },

  // ── Ch12 S2: Value of Coins (math1_ch12_value_of_coins) ──────────────────────
  { questionId:"math1_ch12_value_of_coins_q1", topicId:"math1_ch12_value_of_coins", text:"How many ₹1 coins equal one ₹5 coin?", options:[{text:"1",type:"concept_error",logicTag:"one ₹1 ≠ ₹5"},{text:"10",type:"concept_error",logicTag:"too many"},{text:"5",type:"correct",logicTag:"5×₹1=₹5"},{text:"2",type:"concept_error",logicTag:"not enough"}], explanation:"₹1 × 5 = ₹5. Five one-rupee coins equal one five-rupee coin.", solutionSteps:["₹1+₹1+₹1+₹1+₹1 = ₹5","5 coins of ₹1 = ₹5"], shortcut:"₹5 = 5 × ₹1.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_value_of_coins_q2", topicId:"math1_ch12_value_of_coins", text:"Which is worth MORE: 1 coin of ₹5 or 3 coins of ₹1?", options:[{text:"3 coins of ₹1",type:"concept_error",logicTag:"₹3 < ₹5"},{text:"They are equal",type:"concept_error",logicTag:"₹5 ≠ ₹3"},{text:"1 coin of ₹5",type:"correct",logicTag:"₹5 > ₹3"},{text:"Cannot compare",type:"guessing",logicTag:"can compare"}], explanation:"₹5 > ₹3 (three ₹1 coins = ₹3). One ₹5 coin is worth more.", solutionSteps:["3 × ₹1 = ₹3","₹5 > ₹3 → ₹5 coin worth more"], shortcut:"More rupees = more value.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_value_of_coins_q3", topicId:"math1_ch12_value_of_coins", text:"What is the total value of two ₹5 coins?", options:[{text:"₹5",type:"concept_error",logicTag:"one coin only"},{text:"₹15",type:"calculation_error",logicTag:"too much"},{text:"₹10",type:"correct",logicTag:"₹5+₹5=₹10"},{text:"₹2",type:"concept_error",logicTag:"wrong"}], explanation:"₹5 + ₹5 = ₹10.", solutionSteps:["₹5 + ₹5 = ₹10","Two ₹5 coins = ₹10"], shortcut:"₹5 + ₹5 = ₹10.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_value_of_coins_q4", topicId:"math1_ch12_value_of_coins", text:"You have 4 coins of ₹2 each. Total = ?", options:[{text:"₹2",type:"concept_error",logicTag:"one coin"},{text:"₹6",type:"calculation_error",logicTag:"3 coins not 4"},{text:"₹10",type:"calculation_error",logicTag:"too many"},{text:"₹8",type:"correct",logicTag:"4×₹2=₹8"}], explanation:"4 × ₹2 = ₹8.", solutionSteps:["₹2+₹2+₹2+₹2","= ₹4+₹4 = ₹8"], shortcut:"4 × ₹2 = ₹8.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_value_of_coins_q5", topicId:"math1_ch12_value_of_coins", text:"Is ₹2 enough to buy a pencil that costs ₹3?", options:[{text:"Yes",type:"concept_error",logicTag:"₹2 < ₹3"},{text:"Yes, if you find a discount",type:"concept_error",logicTag:"not the point"},{text:"No",type:"correct",logicTag:"₹2 < ₹3"},{text:"It depends",type:"guessing",logicTag:"straightforward comparison"}], explanation:"₹2 < ₹3. You need ₹1 more. ₹2 is not enough.", solutionSteps:["Cost = ₹3, Have = ₹2","₹2 < ₹3 → not enough"], shortcut:"Compare: Have ≥ Cost? If no, not enough.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_value_of_coins_q6", topicId:"math1_ch12_value_of_coins", text:"To find the total value of a group of coins, we ___.", options:[{text:"Count the coins (number)",type:"concept_error",logicTag:"number ≠ value"},{text:"Weigh the coins",type:"concept_error",logicTag:"irrelevant"},{text:"Add their values together",type:"correct",logicTag:"total value = sum"},{text:"Subtract their values",type:"concept_error",logicTag:"addition not subtraction"}], explanation:"Add the value of each coin: ₹2 + ₹5 + ₹1 = ₹8.", solutionSteps:["Each coin has a value","Add all values → total"], shortcut:"Add values, not count coins.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_value_of_coins_q7", topicId:"math1_ch12_value_of_coins", text:"3 coins of ₹1 and 1 coin of ₹5. Total?", options:[{text:"₹4",type:"calculation_error",logicTag:"wrong"},{text:"₹3",type:"concept_error",logicTag:"only ones"},{text:"₹8",type:"correct",logicTag:"₹3+₹5=₹8"},{text:"₹15",type:"calculation_error",logicTag:"wrong"}], explanation:"3 × ₹1 + 1 × ₹5 = ₹3 + ₹5 = ₹8.", solutionSteps:["3 × ₹1 = ₹3","1 × ₹5 = ₹5","₹3 + ₹5 = ₹8"], shortcut:"Calculate each group, then add.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_value_of_coins_q8", topicId:"math1_ch12_value_of_coins", text:"Which collection is worth MORE: five ₹1 coins or one ₹10 coin?", options:[{text:"Five ₹1 coins (₹5)",type:"concept_error",logicTag:"₹5 < ₹10"},{text:"They are equal",type:"concept_error",logicTag:"₹5 ≠ ₹10"},{text:"One ₹10 coin",type:"correct",logicTag:"₹10 > ₹5"},{text:"Cannot tell from coins",type:"guessing",logicTag:"can compare values"}], explanation:"Five ₹1 = ₹5. One ₹10 = ₹10. ₹10 > ₹5.", solutionSteps:["5 × ₹1 = ₹5","₹10 > ₹5 → ₹10 coin worth more"], shortcut:"More rupees = more value.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },

  // ── Ch12 S3: Making Amounts (math1_ch12_making_amounts) ───────────────────────
  { questionId:"math1_ch12_making_amounts_q1", topicId:"math1_ch12_making_amounts", text:"Make ₹7 using a ₹5 coin and ₹1 coins. How many ₹1 coins do you need?", options:[{text:"5",type:"concept_error",logicTag:"5+5=10 not 7"},{text:"7",type:"concept_error",logicTag:"plus the ₹5 that's ₹12"},{text:"3",type:"concept_error",logicTag:"5+3=8 not 7"},{text:"2",type:"correct",logicTag:"₹5+₹2=₹7"}], explanation:"₹5 + 2×₹1 = ₹5 + ₹2 = ₹7. Need 2 one-rupee coins.", solutionSteps:["₹7 − ₹5 = ₹2 remaining","₹2 = 2 × ₹1 coins"], shortcut:"Target − big coin = remaining → fill with ₹1 coins.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_making_amounts_q2", topicId:"math1_ch12_making_amounts", text:"How many DIFFERENT ways can you make ₹5?", options:[{text:"Only 1 way",type:"concept_error",logicTag:"multiple ways exist"},{text:"Many ways",type:"correct",logicTag:"₹5=₹5, ₹2+₹2+₹1, ₹1×5 etc."},{text:"Zero ways",type:"concept_error",logicTag:"at least one way"},{text:"Exactly 3 ways",type:"concept_error",logicTag:"depends on coins available"}], explanation:"Many ways: one ₹5 coin, ₹2+₹2+₹1, five ₹1 coins, ₹2+₹1+₹1+₹1, etc.", solutionSteps:["₹5 coin = 1 way","₹2+₹2+₹1 = another","₹1×5 = another","More ways exist"], shortcut:"Same total, different combinations = many ways.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_making_amounts_q3", topicId:"math1_ch12_making_amounts", text:"Which combination makes EXACTLY ₹6?", options:[{text:"₹5 + ₹2",type:"calculation_error",logicTag:"₹7 not ₹6"},{text:"₹2 + ₹2 + ₹2",type:"correct",logicTag:"₹6=₹2+₹2+₹2"},{text:"₹5 + ₹5",type:"calculation_error",logicTag:"₹10"},{text:"₹1 + ₹1 + ₹1",type:"calculation_error",logicTag:"₹3"}], explanation:"₹2 + ₹2 + ₹2 = ₹6.", solutionSteps:["₹2+₹2=₹4","₹4+₹2=₹6 ✓"], shortcut:"Three ₹2 coins = ₹6.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_making_amounts_q4", topicId:"math1_ch12_making_amounts", text:"Start with the LARGEST coin that fits when making ₹9. Which coin should you use first?", options:[{text:"₹1",type:"concept_error",logicTag:"start with largest"},{text:"₹2",type:"concept_error",logicTag:"larger coin available"},{text:"₹5",type:"correct",logicTag:"₹5 is largest that fits in ₹9"},{text:"₹10",type:"concept_error",logicTag:"₹10 > ₹9, won't fit"}], explanation:"₹5 is the largest coin that doesn't exceed ₹9. Start with ₹5, then make up the ₹4 remainder.", solutionSteps:["Target: ₹9","Largest fitting coin: ₹5","₹9 − ₹5 = ₹4 remaining","Then use ₹2+₹2 for ₹4"], shortcut:"Start largest: ₹5, then fill rest.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_making_amounts_q5", topicId:"math1_ch12_making_amounts", text:"Make ₹8 using only ₹2 coins. How many coins needed?", options:[{text:"2",type:"calculation_error",logicTag:"2×₹2=₹4"},{text:"8",type:"concept_error",logicTag:"8 × ₹2 = ₹16"},{text:"4",type:"correct",logicTag:"4×₹2=₹8"},{text:"3",type:"calculation_error",logicTag:"3×₹2=₹6"}], explanation:"₹8 ÷ ₹2 = 4 coins needed.", solutionSteps:["₹2+₹2+₹2+₹2=₹8","4 coins"], shortcut:"₹8 ÷ ₹2 = 4 coins.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_making_amounts_q6", topicId:"math1_ch12_making_amounts", text:"₹5 + ₹2 + ₹1 = ?", options:[{text:"₹6",type:"calculation_error",logicTag:"wrong sum"},{text:"₹9",type:"calculation_error",logicTag:"one too many"},{text:"₹8",type:"correct",logicTag:"₹5+₹2+₹1=₹8"},{text:"₹7",type:"calculation_error",logicTag:"one short"}], explanation:"₹5 + ₹2 + ₹1 = ₹8.", solutionSteps:["₹5+₹2=₹7","₹7+₹1=₹8"], shortcut:"Add each coin value.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_making_amounts_q7", topicId:"math1_ch12_making_amounts", text:"Using FEWER coins is ___ than using many small coins.", options:[{text:"Wrong",type:"concept_error",logicTag:"not wrong"},{text:"The same",type:"concept_error",logicTag:"fewer = more convenient"},{text:"More practical / convenient",type:"correct",logicTag:"fewer = easier to handle"},{text:"Impossible",type:"concept_error",logicTag:"possible"}], explanation:"Using fewer coins (larger denominations) is more practical — lighter, easier to count, and carry.", solutionSteps:["₹5 coin vs five ₹1 coins","Same value, but one coin is easier to carry"], shortcut:"Start big: fewer coins = more convenient.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_making_amounts_q8", topicId:"math1_ch12_making_amounts", text:"Make ₹10 using coins. Which combination uses the FEWEST coins?", options:[{text:"10 × ₹1",type:"concept_error",logicTag:"10 coins"},{text:"5 × ₹2",type:"concept_error",logicTag:"5 coins"},{text:"2 × ₹5",type:"concept_error",logicTag:"2 coins, good but..."},{text:"1 × ₹10",type:"correct",logicTag:"1 coin — fewest possible"}], explanation:"One ₹10 coin = ₹10 using just 1 coin. That's the fewest possible.", solutionSteps:["₹10 coin = 1 coin","₹5+₹5 = 2 coins","2×₹2+6×₹1 = many coins","1 coin is fewest"], shortcut:"One large coin = fewest coins.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"12" },

  // ── Ch12 S4: Simple Money Problems (math1_ch12_simple_money_problems) ─────────
  { questionId:"math1_ch12_simple_money_problems_q1", topicId:"math1_ch12_simple_money_problems", text:"Buy a ball for ₹4 and a pencil for ₹3. Total cost?", options:[{text:"₹6",type:"calculation_error",logicTag:"one short"},{text:"₹8",type:"calculation_error",logicTag:"one too many"},{text:"₹7",type:"correct",logicTag:"₹4+₹3=₹7"},{text:"₹1",type:"concept_error",logicTag:"subtracted"}], explanation:"₹4 + ₹3 = ₹7.", solutionSteps:["Ball ₹4 + Pencil ₹3","₹4+₹3=₹7 total"], shortcut:"Total cost = add prices.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_simple_money_problems_q2", topicId:"math1_ch12_simple_money_problems", text:"Pay ₹10 for an item costing ₹7. What is the CHANGE?", options:[{text:"₹7",type:"concept_error",logicTag:"that's the cost"},{text:"₹17",type:"concept_error",logicTag:"added instead"},{text:"₹3",type:"correct",logicTag:"₹10-₹7=₹3"},{text:"₹2",type:"calculation_error",logicTag:"one short"}], explanation:"Change = payment − cost = ₹10 − ₹7 = ₹3.", solutionSteps:["Payment: ₹10","Cost: ₹7","Change = ₹10 − ₹7 = ₹3"], shortcut:"Change = pay − cost.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_simple_money_problems_q3", topicId:"math1_ch12_simple_money_problems", text:"Do you have enough? You have ₹6; the eraser costs ₹4.", options:[{text:"No",type:"concept_error",logicTag:"₹6 > ₹4"},{text:"Yes",type:"correct",logicTag:"₹6 ≥ ₹4"},{text:"Exactly enough",type:"partial_logic",logicTag:"not exact (₹6 > ₹4)"},{text:"Cannot tell",type:"guessing",logicTag:"can compare"}], explanation:"₹6 > ₹4. You have more than enough.", solutionSteps:["Have: ₹6","Cost: ₹4","₹6 ≥ ₹4 → Yes, enough"], shortcut:"Have ≥ cost → yes, enough.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_simple_money_problems_q4", topicId:"math1_ch12_simple_money_problems", text:"Buy a chocolate for ₹5 and a juice for ₹3. Pay ₹10. Change?", options:[{text:"₹1",type:"calculation_error",logicTag:"wrong"},{text:"₹3",type:"calculation_error",logicTag:"didn't add both costs"},{text:"₹2",type:"correct",logicTag:"₹5+₹3=₹8; ₹10-₹8=₹2"},{text:"₹8",type:"concept_error",logicTag:"that's the cost"}], explanation:"Total cost = ₹5 + ₹3 = ₹8. Change = ₹10 − ₹8 = ₹2.", solutionSteps:["Total: ₹5+₹3=₹8","Change: ₹10−₹8=₹2"], shortcut:"Step 1: total cost. Step 2: change.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_simple_money_problems_q5", topicId:"math1_ch12_simple_money_problems", text:"A toy costs ₹9. You have ₹5. How much MORE money do you need?", options:[{text:"₹14",type:"concept_error",logicTag:"added"},{text:"₹5",type:"concept_error",logicTag:"that's what you have"},{text:"₹4",type:"correct",logicTag:"₹9-₹5=₹4"},{text:"₹3",type:"calculation_error",logicTag:"off by one"}], explanation:"₹9 − ₹5 = ₹4 more needed.", solutionSteps:["Need: ₹9","Have: ₹5","More needed: ₹9−₹5=₹4"], shortcut:"More needed = cost − have.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_simple_money_problems_q6", topicId:"math1_ch12_simple_money_problems", text:"Anu pays ₹5 for an item. She gets ₹2 change. What did the item cost?", options:[{text:"₹7",type:"concept_error",logicTag:"added instead"},{text:"₹2",type:"concept_error",logicTag:"that's the change"},{text:"₹3",type:"correct",logicTag:"₹5-₹2=₹3"},{text:"₹5",type:"concept_error",logicTag:"paid not cost"}], explanation:"Cost = paid − change = ₹5 − ₹2 = ₹3.", solutionSteps:["Paid ₹5, got ₹2 back","Cost = ₹5 − ₹2 = ₹3"], shortcut:"Cost = paid − change.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_simple_money_problems_q7", topicId:"math1_ch12_simple_money_problems", text:"What is CHANGE in a money problem?", options:[{text:"The price of the item",type:"concept_error",logicTag:"that's cost"},{text:"Money left over after paying more than needed",type:"correct",logicTag:"change = excess payment returned"},{text:"The total cost",type:"concept_error",logicTag:"total ≠ change"},{text:"The number of coins",type:"concept_error",logicTag:"number not value"}], explanation:"Change = the money returned when you pay more than the exact cost.", solutionSteps:["Pay ₹10 for ₹7 item","₹10 − ₹7 = ₹3 change (returned)"], shortcut:"Change = excess payment given back.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
  { questionId:"math1_ch12_simple_money_problems_q8", topicId:"math1_ch12_simple_money_problems", text:"Rohan has ₹8. He buys a pen for ₹3. How much does he have left?", options:[{text:"₹3",type:"concept_error",logicTag:"only cost"},{text:"₹11",type:"concept_error",logicTag:"added"},{text:"₹5",type:"correct",logicTag:"₹8-₹3=₹5"},{text:"₹4",type:"calculation_error",logicTag:"off by one"}], explanation:"₹8 − ₹3 = ₹5 left.", solutionSteps:["Had ₹8, spent ₹3","₹8 − ₹3 = ₹5 remaining"], shortcut:"Left = had − spent.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"12" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
    console.log(`  ✓ ${q.questionId}`);
  }
  console.log(`\nSeeded ${questions.length} questions for Class 1 Math v2 (Ch11–Ch12).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
