import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math3_ch11_ml_litres — 8 Qs
  { questionId:"math3_ch11_ml_q1", topicId:"math3_ch11_ml_litres", text:"1 litre = ? millilitres", options:[{text:"10",type:"concept_error"},{text:"100",type:"calculation_error"},{text:"1000",type:"correct"},{text:"10000",type:"misinterpretation"}], explanation:"By definition: 1 l = 1000 ml.", solutionSteps:["1 l = 1000 ml."], shortcut:"1 l = 1000 ml.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_ml_q2", topicId:"math3_ch11_ml_litres", text:"500 ml + 500 ml = ?", options:[{text:"1000 ml (= 1 l)",type:"correct"},{text:"5000 ml",type:"misinterpretation"},{text:"100 ml",type:"calculation_error"},{text:"10 ml",type:"concept_error"}], explanation:"500 + 500 = 1000 ml = 1 l.", solutionSteps:["500 + 500 = 1000 ml.","1000 ml = 1 l."], shortcut:"500 ml + 500 ml = 1 l.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_ml_q3", topicId:"math3_ch11_ml_litres", text:"2 l = ? ml", options:[{text:"200",type:"calculation_error"},{text:"2000",type:"correct"},{text:"20000",type:"misinterpretation"},{text:"20",type:"concept_error"}], explanation:"2 × 1000 = 2000 ml.", solutionSteps:["l → ml: × 1000.","2 × 1000 = 2000 ml."], shortcut:"× 1000.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_ml_q4", topicId:"math3_ch11_ml_litres", text:"3000 ml = ? l", options:[{text:"3",type:"correct"},{text:"30",type:"calculation_error"},{text:"0.3",type:"calculation_error"},{text:"300",type:"misinterpretation"}], explanation:"3000 ÷ 1000 = 3 l.", solutionSteps:["ml → l: ÷ 1000.","3000 ÷ 1000 = 3 l."], shortcut:"ml ÷ 1000 = l.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_ml_q5", topicId:"math3_ch11_ml_litres", text:"Which unit measures the water in a glass?", options:[{text:"l",type:"partial_logic"},{text:"ml",type:"correct"},{text:"kg",type:"misinterpretation"},{text:"cm",type:"concept_error"}], explanation:"A glass holds about 250 ml — small enough for ml.", solutionSteps:["Small amount = ml.","Glass ≈ 250 ml."], shortcut:"Small = ml.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_ml_q6", topicId:"math3_ch11_ml_litres", text:"½ l = ? ml", options:[{text:"50",type:"calculation_error"},{text:"100",type:"calculation_error"},{text:"500",type:"correct"},{text:"5000",type:"misinterpretation"}], explanation:"½ × 1000 = 500 ml.", solutionSteps:["½ × 1000 = 500.","½ l = 500 ml."], shortcut:"½ l = 500 ml.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_ml_q7", topicId:"math3_ch11_ml_litres", text:"1 l 250 ml = ? ml", options:[{text:"1025 ml",type:"calculation_error"},{text:"1250 ml",type:"correct"},{text:"125 ml",type:"calculation_error"},{text:"12500 ml",type:"misinterpretation"}], explanation:"1 l = 1000 ml + 250 ml = 1250 ml.", solutionSteps:["1 l = 1000 ml.","1000 + 250 = 1250 ml."], shortcut:"Combine: l × 1000 + ml.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_ml_q8", topicId:"math3_ch11_ml_litres", text:"Which is bigger: 800 ml or 1 l?", options:[{text:"800 ml",type:"concept_error"},{text:"1 l",type:"correct"},{text:"Equal",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"1 l = 1000 ml. 1000 > 800.", solutionSteps:["1 l = 1000 ml.","1000 > 800.","1 l is bigger."], shortcut:"Convert and compare.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },

  // math3_ch11_measuring_capacity — 8 Qs
  { questionId:"math3_ch11_mc_q1", topicId:"math3_ch11_measuring_capacity", text:"To measure water in a jug, you use a…", options:[{text:"Ruler",type:"concept_error"},{text:"Measuring jar / cup",type:"correct"},{text:"Weighing scale",type:"misinterpretation"},{text:"Clock",type:"concept_error"}], explanation:"Measuring cups/jars have ml markings.", solutionSteps:["Marked jars/cups for capacity.","Pour and read level."], shortcut:"Marked container = capacity tool.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_mc_q2", topicId:"math3_ch11_measuring_capacity", text:"Capacity is…", options:[{text:"Weight of an object",type:"concept_error"},{text:"How much liquid a container can hold",type:"correct"},{text:"Length of a container",type:"misinterpretation"},{text:"Colour of liquid",type:"guessing"}], explanation:"Capacity = how much it can hold.", solutionSteps:["Capacity ≠ weight.","Capacity = volume that fits inside."], shortcut:"Capacity = volume held.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_mc_q3", topicId:"math3_ch11_measuring_capacity", text:"To get accurate reading, hold the cup at…", options:[{text:"Above eye level",type:"concept_error"},{text:"Eye level (look horizontally)",type:"correct"},{text:"Below eye level",type:"misinterpretation"},{text:"Any level",type:"guessing"}], explanation:"Looking at the liquid level horizontally avoids parallax errors.", solutionSteps:["Hold container at eye level.","Read marking horizontally."], shortcut:"Eye level = accurate.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_mc_q4", topicId:"math3_ch11_measuring_capacity", text:"A bucket can hold 10 L of water. To fill it half, you need…", options:[{text:"1 L",type:"calculation_error"},{text:"5 L",type:"correct"},{text:"10 L",type:"misinterpretation"},{text:"100 L",type:"calculation_error"}], explanation:"Half of 10 = 5 L.", solutionSteps:["Half = ÷ 2.","10 ÷ 2 = 5 L."], shortcut:"Half = ÷ 2.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_mc_q5", topicId:"math3_ch11_measuring_capacity", text:"To measure exactly 750 ml, use…", options:[{text:"A measuring cup with 750 ml line",type:"correct"},{text:"A weighing scale",type:"misinterpretation"},{text:"A clock",type:"concept_error"},{text:"A ruler",type:"misinterpretation"}], explanation:"Measuring cups have specific ml markings.", solutionSteps:["Pour up to 750 ml line.","Stop when level reaches the line."], shortcut:"Use marked container.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_mc_q6", topicId:"math3_ch11_measuring_capacity", text:"A teaspoon holds about…", options:[{text:"1 ml",type:"concept_error"},{text:"5 ml",type:"correct"},{text:"50 ml",type:"calculation_error"},{text:"500 ml",type:"misinterpretation"}], explanation:"Standard teaspoon ≈ 5 ml.", solutionSteps:["Teaspoon = 5 ml.","Useful reference."], shortcut:"Tsp = 5 ml.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_mc_q7", topicId:"math3_ch11_measuring_capacity", text:"How many 250 ml cups fill a 1 L jug?", options:[{text:"2",type:"calculation_error"},{text:"4",type:"correct"},{text:"5",type:"calculation_error"},{text:"10",type:"misinterpretation"}], explanation:"1 L = 1000 ml ÷ 250 ml = 4 cups.", solutionSteps:["1 L = 1000 ml.","1000 ÷ 250 = 4 cups."], shortcut:"Total ÷ cup size.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_mc_q8", topicId:"math3_ch11_measuring_capacity", text:"If a jug shows 600 ml when filled, the capacity at that level is…", options:[{text:"60 ml",type:"calculation_error"},{text:"600 ml",type:"correct"},{text:"6000 ml",type:"misinterpretation"},{text:"6 ml",type:"concept_error"}], explanation:"Reading on the scale tells you the volume directly.", solutionSteps:["Read the marking.","600 ml = volume at that level."], shortcut:"Read the marking.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },

  // math3_ch11_comparing_capacity — 8 Qs
  { questionId:"math3_ch11_cc_q1", topicId:"math3_ch11_comparing_capacity", text:"Which is bigger: 1 L or 600 ml?", options:[{text:"600 ml",type:"concept_error"},{text:"1 L",type:"correct"},{text:"Equal",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"1 L = 1000 ml > 600 ml.", solutionSteps:["1 L = 1000 ml.","1000 > 600.","1 L is bigger."], shortcut:"Convert before comparing.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cc_q2", topicId:"math3_ch11_comparing_capacity", text:"Order from smallest to biggest: 250 ml, 1 L, 700 ml.", options:[{text:"250, 1 L, 700",type:"concept_error"},{text:"250 ml, 700 ml, 1 L",type:"correct"},{text:"1 L, 700 ml, 250 ml",type:"misinterpretation"},{text:"700, 250, 1 L",type:"calculation_error"}], explanation:"In ml: 250, 700, 1000. Smallest first → 250 ml, 700 ml, 1 L.", solutionSteps:["1 L = 1000 ml.","Sort: 250 < 700 < 1000.","→ 250 ml, 700 ml, 1 L."], shortcut:"Convert all to same unit, sort.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cc_q3", topicId:"math3_ch11_comparing_capacity", text:"To compare 2 L and 1500 ml, both should be in…", options:[{text:"Different units",type:"concept_error"},{text:"The same unit",type:"correct"},{text:"Gallons",type:"misinterpretation"},{text:"kg",type:"concept_error"}], explanation:"Always convert to the same unit (e.g., ml) before comparing.", solutionSteps:["Convert: 2 L = 2000 ml.","Compare: 2000 vs 1500.","2 L is bigger."], shortcut:"Same unit first.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cc_q4", topicId:"math3_ch11_comparing_capacity", text:"Compare: 999 ml ___ 1 L", options:[{text:">",type:"concept_error"},{text:"<",type:"correct"},{text:"=",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"1 L = 1000 ml. 999 < 1000.", solutionSteps:["1 L = 1000 ml.","999 < 1000.","999 ml < 1 L."], shortcut:"Convert and compare.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cc_q5", topicId:"math3_ch11_comparing_capacity", text:"Compare: 2 L 200 ml ___ 2200 ml", options:[{text:">",type:"concept_error"},{text:"<",type:"concept_error"},{text:"=",type:"correct"},{text:"Cannot compare",type:"guessing"}], explanation:"2 L = 2000 ml. 2000 + 200 = 2200 = 2200. Equal.", solutionSteps:["2 L = 2000 ml.","2000 + 200 = 2200 ml.","Same as 2200 ml. = Equal."], shortcut:"Convert mixed → ml.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cc_q6", topicId:"math3_ch11_comparing_capacity", text:"Which holds more water: a glass (250 ml) or a bottle (1 L)?", options:[{text:"Glass",type:"concept_error"},{text:"Bottle",type:"correct"},{text:"Equal",type:"misinterpretation"},{text:"Depends",type:"guessing"}], explanation:"Bottle (1000 ml) > Glass (250 ml).", solutionSteps:["1 L = 1000 ml.","1000 > 250.","Bottle holds more."], shortcut:"Bigger container = more capacity.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cc_q7", topicId:"math3_ch11_comparing_capacity", text:"By how much is 2 L bigger than 700 ml?", options:[{text:"1300 ml",type:"correct"},{text:"2700 ml",type:"calculation_error"},{text:"1700 ml",type:"calculation_error"},{text:"300 ml",type:"calculation_error"}], explanation:"2 L = 2000 ml. 2000 − 700 = 1300 ml.", solutionSteps:["2 L = 2000 ml.","2000 − 700 = 1300 ml."], shortcut:"Convert + subtract.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cc_q8", topicId:"math3_ch11_comparing_capacity", text:"A water tank holds 1500 L. A bucket holds 15 L. Tank is ___ times bigger.", options:[{text:"10",type:"calculation_error"},{text:"100",type:"correct"},{text:"1000",type:"misinterpretation"},{text:"1500",type:"calculation_error"}], explanation:"1500 ÷ 15 = 100.", solutionSteps:["1500 ÷ 15 = 100.","Tank = 100 × bucket."], shortcut:"Divide for ratio.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },

  // math3_ch11_capacity_word — 8 Qs
  { questionId:"math3_ch11_cw_q1", topicId:"math3_ch11_capacity_word", text:"A jug has 750 ml of milk. Adding 250 ml more, the total is…", options:[{text:"500 ml",type:"calculation_error"},{text:"1000 ml = 1 L",type:"correct"},{text:"1250 ml",type:"calculation_error"},{text:"750 ml",type:"misinterpretation"}], explanation:"750 + 250 = 1000 ml = 1 L.", solutionSteps:["750 + 250 = 1000 ml.","= 1 L."], shortcut:"Add ml.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cw_q2", topicId:"math3_ch11_capacity_word", text:"A bottle has 2 L water. After pouring 800 ml, water left is…", options:[{text:"1200 ml = 1 L 200 ml",type:"correct"},{text:"1000 ml",type:"calculation_error"},{text:"2800 ml",type:"misinterpretation"},{text:"200 ml",type:"calculation_error"}], explanation:"2 L = 2000 ml. 2000 − 800 = 1200 ml = 1 L 200 ml.", solutionSteps:["2 L = 2000 ml.","2000 − 800 = 1200 ml = 1 L 200 ml."], shortcut:"Convert → subtract.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cw_q3", topicId:"math3_ch11_capacity_word", text:"A glass holds 200 ml. 5 glasses are filled. Total liquid?", options:[{text:"1000 ml = 1 L",type:"correct"},{text:"500 ml",type:"calculation_error"},{text:"2000 ml",type:"calculation_error"},{text:"200 ml",type:"misinterpretation"}], explanation:"5 × 200 = 1000 ml = 1 L.", solutionSteps:["5 × 200 = 1000 ml.","= 1 L."], shortcut:"Glasses × per glass.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cw_q4", topicId:"math3_ch11_capacity_word", text:"A tank holds 100 L. After using 35 L, how much is left?", options:[{text:"135 L",type:"misinterpretation"},{text:"65 L",type:"correct"},{text:"75 L",type:"calculation_error"},{text:"45 L",type:"calculation_error"}], explanation:"100 − 35 = 65 L.", solutionSteps:["Left = total − used.","100 − 35 = 65 L."], shortcut:"Used = subtract.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cw_q5", topicId:"math3_ch11_capacity_word", text:"You need 3 L of juice. A pack contains 750 ml. How many packs do you need?", options:[{text:"3",type:"calculation_error"},{text:"4",type:"correct"},{text:"5",type:"misinterpretation"},{text:"2",type:"calculation_error"}], explanation:"3 L = 3000 ml. 3000 ÷ 750 = 4 packs.", solutionSteps:["3 L = 3000 ml.","3000 ÷ 750 = 4 packs."], shortcut:"Total ÷ pack size.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cw_q6", topicId:"math3_ch11_capacity_word", text:"Two jugs: A has 1.5 L, B has 750 ml. Together, they have…", options:[{text:"2 L 250 ml",type:"correct"},{text:"2 L 500 ml",type:"calculation_error"},{text:"1 L 750 ml",type:"calculation_error"},{text:"3 L",type:"misinterpretation"}], explanation:"1.5 L = 1500 ml. 1500 + 750 = 2250 ml = 2 L 250 ml.", solutionSteps:["1.5 L = 1500 ml.","1500 + 750 = 2250 ml.","= 2 L 250 ml."], shortcut:"Convert all to ml, then add.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cw_q7", topicId:"math3_ch11_capacity_word", text:"A bottle of medicine has 100 ml. The doctor says take 5 ml twice a day. The bottle will last…", options:[{text:"5 days",type:"calculation_error"},{text:"10 days",type:"correct"},{text:"20 days",type:"calculation_error"},{text:"100 days",type:"misinterpretation"}], explanation:"5 ml × 2 = 10 ml/day. 100 ÷ 10 = 10 days.", solutionSteps:["Per day: 5 × 2 = 10 ml.","Days: 100 ÷ 10 = 10."], shortcut:"Daily use, then divide total.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },
  { questionId:"math3_ch11_cw_q8", topicId:"math3_ch11_capacity_word", text:"A tap fills 5 L in 1 minute. In 4 minutes, water poured?", options:[{text:"9 L",type:"misinterpretation"},{text:"20 L",type:"correct"},{text:"54 L",type:"misinterpretation"},{text:"15 L",type:"calculation_error"}], explanation:"5 × 4 = 20 L.", solutionSteps:["Rate × time = total.","5 × 4 = 20 L."], shortcut:"Rate problem: multiply.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Jugs and Mugs" },

  // math3_ch12_sharing_equally — 8 Qs
  { questionId:"math3_ch12_se_q1", topicId:"math3_ch12_sharing_equally", text:"12 sweets shared among 3 children. Each gets…", options:[{text:"2",type:"calculation_error"},{text:"3",type:"calculation_error"},{text:"4",type:"correct"},{text:"6",type:"misinterpretation"}], explanation:"12 ÷ 3 = 4 sweets each.", solutionSteps:["12 ÷ 3 = 4."], shortcut:"Total ÷ children.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_se_q2", topicId:"math3_ch12_sharing_equally", text:"Division is best described as…", options:[{text:"Adding",type:"concept_error"},{text:"Sharing equally",type:"correct"},{text:"Multiplying",type:"misinterpretation"},{text:"Counting up",type:"guessing"}], explanation:"Division splits a total into equal groups.", solutionSteps:["÷ = split equally.","Opposite of ×."], shortcut:"÷ = share equally.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_se_q3", topicId:"math3_ch12_sharing_equally", text:"20 marbles in 4 equal groups. Marbles per group?", options:[{text:"4",type:"calculation_error"},{text:"5",type:"correct"},{text:"6",type:"calculation_error"},{text:"10",type:"misinterpretation"}], explanation:"20 ÷ 4 = 5.", solutionSteps:["20 ÷ 4 = 5."], shortcut:"Total ÷ groups.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_se_q4", topicId:"math3_ch12_sharing_equally", text:"In 24 ÷ 6, which number is being SHARED?", options:[{text:"6 (small)",type:"concept_error"},{text:"24 (big)",type:"correct"},{text:"Both",type:"misinterpretation"},{text:"Neither",type:"guessing"}], explanation:"The BIG number (24) is the total being shared.", solutionSteps:["Dividend (24) is the total.","Divisor (6) is the number of groups."], shortcut:"Big number = total = dividend.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_se_q5", topicId:"math3_ch12_sharing_equally", text:"How many groups of 5 can be formed from 25?", options:[{text:"3",type:"calculation_error"},{text:"5",type:"correct"},{text:"10",type:"misinterpretation"},{text:"25",type:"concept_error"}], explanation:"25 ÷ 5 = 5 groups.", solutionSteps:["25 ÷ 5 = 5.","5 groups of 5."], shortcut:"Total ÷ group size.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_se_q6", topicId:"math3_ch12_sharing_equally", text:"18 chairs equally placed in 6 rows. Chairs per row?", options:[{text:"2",type:"calculation_error"},{text:"3",type:"correct"},{text:"4",type:"calculation_error"},{text:"24",type:"misinterpretation"}], explanation:"18 ÷ 6 = 3.", solutionSteps:["18 ÷ 6 = 3."], shortcut:"Chairs ÷ rows.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_se_q7", topicId:"math3_ch12_sharing_equally", text:"To check 12 ÷ 3 = 4, multiply…", options:[{text:"4 × 3 = 12",type:"correct"},{text:"12 × 4 = 48",type:"misinterpretation"},{text:"4 + 3 = 7",type:"concept_error"},{text:"12 + 3 = 15",type:"misinterpretation"}], explanation:"Answer × divisor = dividend. 4 × 3 = 12 ✓.", solutionSteps:["Check: answer × divisor.","4 × 3 = 12.","Matches dividend ✓."], shortcut:"× to verify ÷.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_se_q8", topicId:"math3_ch12_sharing_equally", text:"What is 100 ÷ 10?", options:[{text:"1",type:"calculation_error"},{text:"10",type:"correct"},{text:"100",type:"concept_error"},{text:"1000",type:"misinterpretation"}], explanation:"100 ÷ 10 = 10.", solutionSteps:["100 ÷ 10 = 10."], shortcut:"÷ 10 drops a zero.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },

  // math3_ch12_division_facts — 8 Qs
  { questionId:"math3_ch12_df_q1", topicId:"math3_ch12_division_facts", text:"What is 20 ÷ 5?", options:[{text:"3",type:"calculation_error"},{text:"4",type:"correct"},{text:"5",type:"calculation_error"},{text:"25",type:"misinterpretation"}], explanation:"5 × 4 = 20 → 20 ÷ 5 = 4.", solutionSteps:["Find what × 5 = 20.","4 × 5 = 20.","So 20 ÷ 5 = 4."], shortcut:"Use table of 5.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_df_q2", topicId:"math3_ch12_division_facts", text:"What is 50 ÷ 10?", options:[{text:"5",type:"correct"},{text:"10",type:"calculation_error"},{text:"50",type:"concept_error"},{text:"500",type:"misinterpretation"}], explanation:"10 × 5 = 50 → 50 ÷ 10 = 5.", solutionSteps:["10 × 5 = 50.","50 ÷ 10 = 5."], shortcut:"÷ 10: easy.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_df_q3", topicId:"math3_ch12_division_facts", text:"14 ÷ 2 = ?", options:[{text:"6",type:"calculation_error"},{text:"7",type:"correct"},{text:"12",type:"misinterpretation"},{text:"16",type:"misinterpretation"}], explanation:"2 × 7 = 14 → 14 ÷ 2 = 7.", solutionSteps:["2 × 7 = 14.","14 ÷ 2 = 7."], shortcut:"÷ 2 = half.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_df_q4", topicId:"math3_ch12_division_facts", text:"40 ÷ 5 = ?", options:[{text:"4",type:"calculation_error"},{text:"8",type:"correct"},{text:"5",type:"calculation_error"},{text:"35",type:"misinterpretation"}], explanation:"5 × 8 = 40 → 40 ÷ 5 = 8.", solutionSteps:["5 × 8 = 40.","40 ÷ 5 = 8."], shortcut:"Use table of 5.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_df_q5", topicId:"math3_ch12_division_facts", text:"To compute 24 ÷ 6, you can use:", options:[{text:"Addition table",type:"concept_error"},{text:"Times table of 6 (4 × 6 = 24)",type:"correct"},{text:"Subtraction only",type:"partial_logic"},{text:"Random guess",type:"misinterpretation"}], explanation:"Division uses the multiplication table backwards.", solutionSteps:["× table backwards = ÷.","4 × 6 = 24.","So 24 ÷ 6 = 4."], shortcut:"÷ = × backwards.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_df_q6", topicId:"math3_ch12_division_facts", text:"30 ÷ 5 = ?", options:[{text:"5",type:"calculation_error"},{text:"6",type:"correct"},{text:"3",type:"calculation_error"},{text:"15",type:"misinterpretation"}], explanation:"5 × 6 = 30 → 30 ÷ 5 = 6.", solutionSteps:["5 × 6 = 30.","30 ÷ 5 = 6."], shortcut:"Table of 5.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_df_q7", topicId:"math3_ch12_division_facts", text:"What is 0 ÷ 5?", options:[{text:"5",type:"concept_error"},{text:"0",type:"correct"},{text:"1",type:"calculation_error"},{text:"Undefined",type:"misinterpretation"}], explanation:"0 divided by any nonzero number = 0.", solutionSteps:["0 split into 5 groups = 0 each.","0 ÷ 5 = 0."], shortcut:"0 ÷ anything = 0.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_df_q8", topicId:"math3_ch12_division_facts", text:"Any number ÷ 1 = ?", options:[{text:"1",type:"concept_error"},{text:"The number itself",type:"correct"},{text:"0",type:"calculation_error"},{text:"Undefined",type:"misinterpretation"}], explanation:"n ÷ 1 = n.", solutionSteps:["Divide into 1 group → the whole.","n ÷ 1 = n."], shortcut:"÷ 1 = self.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },

  // math3_ch12_remainders — 8 Qs
  { questionId:"math3_ch12_re_q1", topicId:"math3_ch12_remainders", text:"14 ÷ 3 = ? with remainder ?", options:[{text:"3 remainder 5",type:"calculation_error"},{text:"4 remainder 2",type:"correct"},{text:"5 remainder 1",type:"calculation_error"},{text:"4 remainder 0",type:"calculation_error"}], explanation:"3 × 4 = 12, leaves 14 − 12 = 2. So 14 ÷ 3 = 4 rem 2.", solutionSteps:["Largest multiple of 3 ≤ 14: 3 × 4 = 12.","Remainder = 14 − 12 = 2."], shortcut:"Find largest multiple, subtract.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_re_q2", topicId:"math3_ch12_remainders", text:"7 ÷ 2 = ? with remainder ?", options:[{text:"2 rem 3",type:"calculation_error"},{text:"3 rem 1",type:"correct"},{text:"4 rem 0",type:"calculation_error"},{text:"5 rem 0",type:"misinterpretation"}], explanation:"2 × 3 = 6, 7 − 6 = 1. So 7 ÷ 2 = 3 rem 1.", solutionSteps:["Largest multiple of 2 ≤ 7: 6.","Remainder: 7 − 6 = 1.","→ 3 rem 1."], shortcut:"Odd ÷ 2 has rem 1.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_re_q3", topicId:"math3_ch12_remainders", text:"In 25 ÷ 4, the remainder is…", options:[{text:"0",type:"calculation_error"},{text:"1",type:"correct"},{text:"2",type:"calculation_error"},{text:"3",type:"misinterpretation"}], explanation:"4 × 6 = 24, 25 − 24 = 1. Rem = 1.", solutionSteps:["Largest multiple of 4 ≤ 25: 24.","Remainder: 25 − 24 = 1."], shortcut:"Subtract closest multiple.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_re_q4", topicId:"math3_ch12_remainders", text:"Verify: 14 = 3 × 4 + ?", options:[{text:"0",type:"calculation_error"},{text:"1",type:"calculation_error"},{text:"2",type:"correct"},{text:"3",type:"misinterpretation"}], explanation:"3 × 4 = 12. 14 − 12 = 2.", solutionSteps:["3 × 4 = 12.","14 − 12 = 2.","Remainder = 2."], shortcut:"Quotient × divisor + remainder = dividend.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_re_q5", topicId:"math3_ch12_remainders", text:"23 ÷ 5 = ? rem ?", options:[{text:"4 rem 3",type:"correct"},{text:"5 rem 3",type:"calculation_error"},{text:"3 rem 8",type:"concept_error"},{text:"4 rem 0",type:"calculation_error"}], explanation:"5 × 4 = 20, 23 − 20 = 3. So 23 ÷ 5 = 4 rem 3.", solutionSteps:["5 × 4 = 20.","23 − 20 = 3.","→ 4 rem 3."], shortcut:"Find biggest multiple, subtract.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_re_q6", topicId:"math3_ch12_remainders", text:"If a division has remainder 0, then…", options:[{text:"Division is impossible",type:"concept_error"},{text:"Division is exact",type:"correct"},{text:"There's an error",type:"misinterpretation"},{text:"Try smaller numbers",type:"guessing"}], explanation:"Remainder 0 means it divides evenly.", solutionSteps:["Rem = 0 → exact.","Multiplication table contains the number."], shortcut:"Rem 0 = exact.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_re_q7", topicId:"math3_ch12_remainders", text:"30 ÷ 7 = ? rem ?", options:[{text:"4 rem 2",type:"correct"},{text:"5 rem 0",type:"calculation_error"},{text:"3 rem 9",type:"concept_error"},{text:"4 rem 5",type:"calculation_error"}], explanation:"7 × 4 = 28, 30 − 28 = 2. So 30 ÷ 7 = 4 rem 2.", solutionSteps:["7 × 4 = 28.","30 − 28 = 2.","→ 4 rem 2."], shortcut:"Closest multiple below.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_re_q8", topicId:"math3_ch12_remainders", text:"Remainder must always be ___ the divisor.", options:[{text:"Greater than",type:"concept_error"},{text:"Smaller than",type:"correct"},{text:"Equal to",type:"misinterpretation"},{text:"Negative",type:"guessing"}], explanation:"Remainder must be less than the divisor (otherwise, we could divide one more time).", solutionSteps:["If rem ≥ divisor, we could ÷ once more.","So remainder < divisor."], shortcut:"Remainder < divisor.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },

  // math3_ch12_division_word — 8 Qs
  { questionId:"math3_ch12_dw_q1", topicId:"math3_ch12_division_word", text:"24 students sit in 4 equal rows. Students per row?", options:[{text:"4",type:"calculation_error"},{text:"6",type:"correct"},{text:"20",type:"misinterpretation"},{text:"96",type:"misinterpretation"}], explanation:"24 ÷ 4 = 6.", solutionSteps:["24 ÷ 4 = 6 students per row."], shortcut:"Total ÷ rows.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_dw_q2", topicId:"math3_ch12_division_word", text:"Which keyword means DIVIDE?", options:[{text:"Together",type:"concept_error"},{text:"Share equally / split / per group",type:"correct"},{text:"Sum",type:"misinterpretation"},{text:"Difference",type:"concept_error"}], explanation:"Share, split, distribute, equally → division.", solutionSteps:["Share = ÷.","Split = ÷.","Equally = ÷."], shortcut:"Share/split/equal = ÷.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_dw_q3", topicId:"math3_ch12_division_word", text:"36 sweets shared among 4 children. Each gets…", options:[{text:"6",type:"calculation_error"},{text:"9",type:"correct"},{text:"12",type:"calculation_error"},{text:"40",type:"misinterpretation"}], explanation:"36 ÷ 4 = 9.", solutionSteps:["36 ÷ 4 = 9 sweets each."], shortcut:"Sweets ÷ children.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_dw_q4", topicId:"math3_ch12_division_word", text:"42 pencils packed in boxes of 6 pencils each. How many boxes?", options:[{text:"6",type:"calculation_error"},{text:"7",type:"correct"},{text:"36",type:"misinterpretation"},{text:"48",type:"calculation_error"}], explanation:"42 ÷ 6 = 7.", solutionSteps:["42 ÷ 6 = 7 boxes."], shortcut:"Total ÷ per box.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_dw_q5", topicId:"math3_ch12_division_word", text:"A baker bakes 60 cookies. She packs 12 in each box. How many boxes filled?", options:[{text:"4",type:"calculation_error"},{text:"5",type:"correct"},{text:"6",type:"calculation_error"},{text:"72",type:"misinterpretation"}], explanation:"60 ÷ 12 = 5.", solutionSteps:["60 ÷ 12 = 5 boxes."], shortcut:"Total ÷ per box.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_dw_q6", topicId:"math3_ch12_division_word", text:"100 sweets distributed equally to 10 children. Each gets…", options:[{text:"5",type:"calculation_error"},{text:"10",type:"correct"},{text:"100",type:"concept_error"},{text:"1000",type:"misinterpretation"}], explanation:"100 ÷ 10 = 10.", solutionSteps:["100 ÷ 10 = 10 sweets each."], shortcut:"÷ 10 drops a zero.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_dw_q7", topicId:"math3_ch12_division_word", text:"A pizza has 8 equal slices. 4 friends share equally. Slices per person?", options:[{text:"1",type:"calculation_error"},{text:"2",type:"correct"},{text:"3",type:"calculation_error"},{text:"4",type:"misinterpretation"}], explanation:"8 ÷ 4 = 2 slices each.", solutionSteps:["8 ÷ 4 = 2."], shortcut:"Slices ÷ people.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
  { questionId:"math3_ch12_dw_q8", topicId:"math3_ch12_division_word", text:"15 students form groups of 3. How many groups?", options:[{text:"3",type:"calculation_error"},{text:"5",type:"correct"},{text:"15",type:"concept_error"},{text:"45",type:"misinterpretation"}], explanation:"15 ÷ 3 = 5 groups.", solutionSteps:["15 ÷ 3 = 5."], shortcut:"Total ÷ per group.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Can We Share?" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 3 Math v2 questions (Ch11-12).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
