import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math2_ch5_color_patterns — 8 questions
  { questionId:"math2_ch5_cp_q1", topicId:"math2_ch5_color_patterns", text:"Pattern: 🔴🔵🔴🔵🔴__. What comes next?", options:[{text:"🔴",type:"concept_error"},{text:"🔵",type:"correct"},{text:"🟡",type:"misinterpretation"},{text:"🟢",type:"guessing"}], explanation:"Core = 🔴🔵. After 🔴 comes 🔵.", solutionSteps:["Core = red, blue (repeats)","After red → blue"], shortcut:"Find the core, then predict the next.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_cp_q2", topicId:"math2_ch5_color_patterns", text:"Pattern core: △○□. The 7th shape is:", options:[{text:"△",type:"correct"},{text:"○",type:"calculation_error"},{text:"□",type:"calculation_error"},{text:"Cannot say",type:"guessing"}], explanation:"Core has 3 shapes: △○□. 7 ÷ 3 = 2 remainder 1. 1st in core = △.", solutionSteps:["Core length = 3","7 ÷ 3 = 2 remainder 1","Remainder 1 → 1st in core = △"], shortcut:"Divide position by core length; remainder tells which shape.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_cp_q3", topicId:"math2_ch5_color_patterns", text:"What is the core of this pattern: ABABAB?", options:[{text:"A",type:"concept_error"},{text:"AB",type:"correct"},{text:"ABA",type:"misinterpretation"},{text:"ABAB",type:"misinterpretation"}], explanation:"The core (repeating unit) is AB.", solutionSteps:["AB repeats: AB|AB|AB → core = AB"], shortcut:"Shortest repeating unit = core.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_cp_q4", topicId:"math2_ch5_color_patterns", text:"Pattern: 🔴🔴🔵🔴🔴🔵__. What comes next?", options:[{text:"🔵",type:"concept_error"},{text:"🟡",type:"misinterpretation"},{text:"🔴",type:"correct"},{text:"🟢",type:"guessing"}], explanation:"Core = 🔴🔴🔵. After 🔴🔴🔵 comes 🔴 again.", solutionSteps:["Core = red, red, blue (3 items)","Position 7 = start of new cycle = red"], shortcut:"Identify core (2 reds + 1 blue here).", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_cp_q5", topicId:"math2_ch5_color_patterns", text:"Which is NOT a repeating pattern?", options:[{text:"ABABAB",type:"misinterpretation"},{text:"ABCABCABC",type:"misinterpretation"},{text:"ABCDE",type:"correct"},{text:"AABAABAAB",type:"misinterpretation"}], explanation:"ABCDE has no repeating core — each letter appears just once.", solutionSteps:["ABABAB → core AB, repeating ✓","ABCDE → no repetition ✗"], shortcut:"A pattern MUST repeat. If it doesn't repeat, it's not a pattern.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_cp_q6", topicId:"math2_ch5_color_patterns", text:"Pattern: ★☆★☆★☆. The next two shapes are:", options:[{text:"★★",type:"concept_error"},{text:"☆☆",type:"concept_error"},{text:"★☆",type:"correct"},{text:"☆★",type:"misinterpretation"}], explanation:"Core = ★☆. After ★☆★☆★☆ comes ★☆ again.", solutionSteps:["Core = ★☆","Next two = ★☆"], shortcut:"The pattern restarts after the core — just repeat the core.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_cp_q7", topicId:"math2_ch5_color_patterns", text:"How many items are in one core of ABCABC?", options:[{text:"2",type:"concept_error"},{text:"3",type:"correct"},{text:"6",type:"misinterpretation"},{text:"1",type:"guessing"}], explanation:"The core is ABC (A, B, C) — 3 items.", solutionSteps:["Core = ABC → 3 items"], shortcut:"Count items until the first repeat.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_cp_q8", topicId:"math2_ch5_color_patterns", text:"Create the next 3 items: 🟡🟢🔵🟡🟢🔵___ ___ ___", options:[{text:"🔵🟢🟡",type:"concept_error"},{text:"🟡🟢🔵",type:"correct"},{text:"🟡🔵🟢",type:"misinterpretation"},{text:"🟢🔵🟡",type:"calculation_error"}], explanation:"Core = 🟡🟢🔵. Next three restart the core: 🟡🟢🔵.", solutionSteps:["Core = yellow, green, blue","Next 3 = yellow, green, blue"], shortcut:"Extend by repeating the core.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },

  // math2_ch5_number_patterns — 8 questions
  { questionId:"math2_ch5_np_q1", topicId:"math2_ch5_number_patterns", text:"Pattern: 3, 6, 9, 12, __. What is the rule?", options:[{text:"Add 2",type:"concept_error"},{text:"Add 3",type:"correct"},{text:"Add 5",type:"misinterpretation"},{text:"Add 6",type:"guessing"}], explanation:"6−3=3, 9−6=3, 12−9=3. The rule is +3.", solutionSteps:["Differences: 3, 3, 3 → rule: +3"], shortcut:"Subtract consecutive terms to find the rule.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_np_q2", topicId:"math2_ch5_number_patterns", text:"Next number: 10, 20, 30, 40, __", options:[{text:"45",type:"concept_error"},{text:"60",type:"calculation_error"},{text:"50",type:"correct"},{text:"41",type:"misinterpretation"}], explanation:"Rule: +10. 40+10=50.", solutionSteps:["Rule = +10","40+10=50"], shortcut:"Same as counting by 10s.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_np_q3", topicId:"math2_ch5_number_patterns", text:"Find the missing number: 25, __, 15, 10, 5.", options:[{text:"22",type:"concept_error"},{text:"20",type:"correct"},{text:"18",type:"misinterpretation"},{text:"30",type:"calculation_error"}], explanation:"Rule: −5. 25−5=20.", solutionSteps:["Differences: 5, 5, 5 → rule: −5","25−5=20"], shortcut:"Subtract 5 each step (counting back by 5).", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_np_q4", topicId:"math2_ch5_number_patterns", text:"Pattern: 2, 4, 8, 16, __. What is the rule?", options:[{text:"Add 2",type:"concept_error"},{text:"Add 4",type:"concept_error"},{text:"Multiply by 2",type:"correct"},{text:"Add 10",type:"misinterpretation"}], explanation:"4÷2=2, 8÷4=2, 16÷8=2. Rule: ×2 (multiply by 2).", solutionSteps:["Ratios: 2,2,2 → multiply by 2"], shortcut:"If ratios are equal, the rule is multiplication.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_np_q5", topicId:"math2_ch5_number_patterns", text:"Next number: 5, 10, 15, 20, __", options:[{text:"22",type:"concept_error"},{text:"24",type:"misinterpretation"},{text:"25",type:"correct"},{text:"30",type:"calculation_error"}], explanation:"Rule: +5. 20+5=25.", solutionSteps:["Rule = +5","20+5=25"], shortcut:"Counting by 5s.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_np_q6", topicId:"math2_ch5_number_patterns", text:"Which number fits: 1, 3, 5, 7, __, 11?", options:[{text:"8",type:"concept_error"},{text:"9",type:"correct"},{text:"10",type:"misinterpretation"},{text:"6",type:"calculation_error"}], explanation:"Rule: +2 (odd numbers). 7+2=9.", solutionSteps:["Odd numbers: +2 each step","7+2=9"], shortcut:"Odd number sequence: +2 each step.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_np_q7", topicId:"math2_ch5_number_patterns", text:"What is the rule in: 50, 45, 40, 35, 30?", options:[{text:"Add 5",type:"concept_error"},{text:"Subtract 5",type:"correct"},{text:"Subtract 10",type:"calculation_error"},{text:"Multiply by 5",type:"misinterpretation"}], explanation:"45−50=−5, 40−45=−5. Rule: subtract 5 each step.", solutionSteps:["Differences: −5 each time → subtract 5"], shortcut:"Decreasing by the same amount = subtract that amount.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_np_q8", topicId:"math2_ch5_number_patterns", text:"Next two terms: 11, 14, 17, 20, __, __", options:[{text:"22, 24",type:"concept_error"},{text:"23, 26",type:"correct"},{text:"21, 22",type:"misinterpretation"},{text:"24, 27",type:"calculation_error"}], explanation:"Rule: +3. 20+3=23, 23+3=26.", solutionSteps:["Rule = +3","20+3=23, 23+3=26"], shortcut:"Apply rule twice to find both terms.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },

  // math2_ch5_growing_patterns — 8 questions
  { questionId:"math2_ch5_gp_q1", topicId:"math2_ch5_growing_patterns", text:"Is 2, 4, 6, 8, 10 a growing or shrinking pattern?", options:[{text:"Shrinking",type:"concept_error"},{text:"Growing",type:"correct"},{text:"Neither",type:"misinterpretation"},{text:"Both",type:"guessing"}], explanation:"Numbers increase each step → it is a growing pattern.", solutionSteps:["2 < 4 < 6 < 8 < 10 → increasing → growing"], shortcut:"Numbers getting larger = growing.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_gp_q2", topicId:"math2_ch5_growing_patterns", text:"Pattern: 30, 25, 20, 15, 10. This is:", options:[{text:"Growing",type:"concept_error"},{text:"Shrinking",type:"correct"},{text:"Constant",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"Numbers decrease each step → shrinking pattern.", solutionSteps:["30 > 25 > 20 > 15 > 10 → decreasing → shrinking"], shortcut:"Numbers getting smaller = shrinking.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_gp_q3", topicId:"math2_ch5_growing_patterns", text:"Next term: 1, 2, 4, 8, __", options:[{text:"10",type:"concept_error"},{text:"12",type:"calculation_error"},{text:"16",type:"correct"},{text:"9",type:"misinterpretation"}], explanation:"Rule: ×2. 8×2=16.", solutionSteps:["2÷1=2, 4÷2=2, 8÷4=2 → rule: ×2","8×2=16"], shortcut:"Doubling pattern: multiply by 2 each step.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_gp_q4", topicId:"math2_ch5_growing_patterns", text:"A growing pattern starts at 5 and adds 4 each time. The 4th term is:", options:[{text:"17",type:"correct"},{text:"20",type:"calculation_error"},{text:"13",type:"calculation_error"},{text:"9",type:"calculation_error"}], explanation:"5, 9, 13, 17. 4th term = 17.", solutionSteps:["5 → 9 → 13 → 17","Each step: +4"], shortcut:"Formula: 5 + (n−1)×4. For n=4: 5+12=17.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_gp_q5", topicId:"math2_ch5_growing_patterns", text:"A shrinking pattern: 100, 90, 80, 70, __. Next term:", options:[{text:"75",type:"concept_error"},{text:"65",type:"calculation_error"},{text:"60",type:"correct"},{text:"50",type:"calculation_error"}], explanation:"Rule: −10. 70−10=60.", solutionSteps:["70−10=60"], shortcut:"Subtract 10 each step.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_gp_q6", topicId:"math2_ch5_growing_patterns", text:"Pattern: 3, 6, 9, 12, 15. Does this grow or shrink?", options:[{text:"Shrink",type:"concept_error"},{text:"Grow",type:"correct"},{text:"Stay same",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"3 < 6 < 9 < 12 < 15 → increasing → growing.", solutionSteps:["Each term larger than previous → growing"], shortcut:"Increasing sequence = growing pattern.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_gp_q7", topicId:"math2_ch5_growing_patterns", text:"Growing pattern: starts at 10, rule is +7. What is the 3rd term?", options:[{text:"17",type:"calculation_error"},{text:"21",type:"calculation_error"},{text:"24",type:"correct"},{text:"27",type:"calculation_error"}], explanation:"10, 17, 24. 3rd term = 24.", solutionSteps:["10 → 17 → 24","Each +7"], shortcut:"Start + (position−1) × step.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_gp_q8", topicId:"math2_ch5_growing_patterns", text:"Is 5, 5, 5, 5 a growing, shrinking, or constant pattern?", options:[{text:"Growing",type:"concept_error"},{text:"Shrinking",type:"concept_error"},{text:"Constant",type:"correct"},{text:"Random",type:"guessing"}], explanation:"All terms are equal — no growth or shrinkage → constant pattern.", solutionSteps:["5=5=5=5 → stays the same → constant"], shortcut:"All equal terms → constant pattern.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },

  // math2_ch5_pattern_rules — 8 questions
  { questionId:"math2_ch5_pr_q1", topicId:"math2_ch5_pattern_rules", text:"What is the rule for: 7, 14, 21, 28?", options:[{text:"Add 6",type:"concept_error"},{text:"Add 7",type:"correct"},{text:"Multiply by 2",type:"misinterpretation"},{text:"Add 14",type:"guessing"}], explanation:"14−7=7, 21−14=7. Rule: add 7.", solutionSteps:["Differences: 7, 7, 7 → add 7"], shortcut:"Constant difference → addition rule.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_pr_q2", topicId:"math2_ch5_pattern_rules", text:"Verify the rule 'add 4' for: 3, 7, 11, 15, 20. Is 20 correct?", options:[{text:"Yes, 20 is correct",type:"concept_error"},{text:"No, it should be 19",type:"correct"},{text:"No, it should be 17",type:"calculation_error"},{text:"Cannot say",type:"guessing"}], explanation:"15+4=19, not 20. So 20 is incorrect; should be 19.", solutionSteps:["Rule: +4","15+4=19 ≠ 20 → error at 20"], shortcut:"Always verify by applying the rule to the previous term.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_pr_q3", topicId:"math2_ch5_pattern_rules", text:"Rule is 'subtract 3'. Start at 18. What is the 5th term?", options:[{text:"6",type:"correct"},{text:"3",type:"calculation_error"},{text:"9",type:"calculation_error"},{text:"12",type:"calculation_error"}], explanation:"18, 15, 12, 9, 6. 5th term = 6.", solutionSteps:["18 → 15 → 12 → 9 → 6","Each −3"], shortcut:"Apply rule (n−1) times to get nth term.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_pr_q4", topicId:"math2_ch5_pattern_rules", text:"What rule connects 4, 8, 12, 16, 20?", options:[{text:"Add 3",type:"concept_error"},{text:"Add 4",type:"correct"},{text:"Multiply by 2",type:"misinterpretation"},{text:"Add 5",type:"misinterpretation"}], explanation:"8−4=4, 12−8=4. Rule: add 4.", solutionSteps:["Differences: 4, 4, 4 → add 4"], shortcut:"Check 2–3 differences; if same → that's the rule.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_pr_q5", topicId:"math2_ch5_pattern_rules", text:"Pattern: 1, 3, 9, 27. What is the rule?", options:[{text:"Add 2",type:"concept_error"},{text:"Add 8",type:"calculation_error"},{text:"Multiply by 3",type:"correct"},{text:"Add 6",type:"misinterpretation"}], explanation:"3÷1=3, 9÷3=3, 27÷9=3. Rule: multiply by 3.", solutionSteps:["Ratios: 3, 3, 3 → multiply by 3"], shortcut:"Equal ratios = multiplication rule.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_pr_q6", topicId:"math2_ch5_pattern_rules", text:"Apply rule 'add 6' to fill: __, __, 18, 24, 30.", options:[{text:"12, 15",type:"concept_error"},{text:"6, 12",type:"correct"},{text:"8, 14",type:"misinterpretation"},{text:"10, 16",type:"calculation_error"}], explanation:"18−6=12, 12−6=6. Blanks = 6, 12.", solutionSteps:["Work backwards: 18−6=12, 12−6=6"], shortcut:"Apply rule in reverse (subtract) to fill earlier terms.", difficulty:"medium", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_pr_q7", topicId:"math2_ch5_pattern_rules", text:"Which sequence follows the rule 'add 5'?", options:[{text:"2, 5, 10, 20",type:"concept_error"},{text:"5, 10, 15, 20",type:"correct"},{text:"5, 8, 11, 14",type:"calculation_error"},{text:"5, 6, 7, 8",type:"misinterpretation"}], explanation:"5, 10, 15, 20: each term increases by 5.", solutionSteps:["10−5=5, 15−10=5, 20−15=5 → rule +5 ✓"], shortcut:"Check all differences equal 5.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },
  { questionId:"math2_ch5_pr_q8", topicId:"math2_ch5_pattern_rules", text:"The rule for the pattern 100, 80, 60, 40 is:", options:[{text:"Subtract 10",type:"concept_error"},{text:"Subtract 20",type:"correct"},{text:"Add 20",type:"concept_error"},{text:"Divide by 2",type:"misinterpretation"}], explanation:"80−100=−20, 60−80=−20. Rule: subtract 20.", solutionSteps:["Differences: −20, −20 → subtract 20"], shortcut:"Negative constant difference = subtract that amount.", difficulty:"easy", subject:"Math", grade:2, chapter:5 },

  // math2_ch6_footprint_shapes — 8 questions
  { questionId:"math2_ch6_fs_q1", topicId:"math2_ch6_footprint_shapes", text:"What shape is the footprint of a cube pressed into clay?", options:[{text:"Circle",type:"concept_error"},{text:"Triangle",type:"misinterpretation"},{text:"Square",type:"correct"},{text:"Rectangle",type:"partial_logic"}], explanation:"A cube's face is a square → footprint in clay is a square.", solutionSteps:["Cube face = square","Footprint = shape of face = square"], shortcut:"Footprint = flat face of the shape.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_fs_q2", topicId:"math2_ch6_footprint_shapes", text:"A ball pressed into clay leaves what shape footprint?", options:[{text:"Square",type:"concept_error"},{text:"Circle",type:"correct"},{text:"Triangle",type:"misinterpretation"},{text:"Oval",type:"partial_logic"}], explanation:"A ball (sphere) is circular at any cross-section → circle footprint.", solutionSteps:["Sphere cross-section = circle","Footprint = circle"], shortcut:"Sphere → circle footprint.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_fs_q3", topicId:"math2_ch6_footprint_shapes", text:"A cylinder standing upright leaves what footprint?", options:[{text:"Square",type:"misinterpretation"},{text:"Circle",type:"correct"},{text:"Rectangle",type:"concept_error"},{text:"Triangle",type:"guessing"}], explanation:"Cylinder standing upright: the bottom face is a circle → circle footprint.", solutionSteps:["Cylinder: flat bottom = circle → circular footprint"], shortcut:"Standing cylinder → circle footprint (bottom face).", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_fs_q4", topicId:"math2_ch6_footprint_shapes", text:"A cylinder lying on its side leaves what footprint?", options:[{text:"Circle",type:"partial_logic"},{text:"Triangle",type:"misinterpretation"},{text:"Rectangle",type:"correct"},{text:"Square",type:"concept_error"}], explanation:"Cylinder on its side: the curved surface makes a rectangular footprint (in 2D).", solutionSteps:["Cylinder on side → long rectangular contact area → rectangle footprint"], shortcut:"Cylinder on its side → rectangle footprint.", difficulty:"medium", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_fs_q5", topicId:"math2_ch6_footprint_shapes", text:"What is the footprint of a cone standing on its base?", options:[{text:"Triangle",type:"concept_error"},{text:"Square",type:"misinterpretation"},{text:"Circle",type:"correct"},{text:"Oval",type:"partial_logic"}], explanation:"The base of a cone is a circle → circular footprint.", solutionSteps:["Cone base = circle → footprint = circle"], shortcut:"Cone standing on base → circle footprint.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_fs_q6", topicId:"math2_ch6_footprint_shapes", text:"Which 3D shape leaves a rectangular footprint when placed on any face?", options:[{text:"Sphere",type:"concept_error"},{text:"Cone",type:"misinterpretation"},{text:"Cuboid",type:"correct"},{text:"Cylinder",type:"partial_logic"}], explanation:"A cuboid has 6 rectangular faces → rectangular footprint on any face.", solutionSteps:["Cuboid: all faces = rectangles → rectangle footprint"], shortcut:"Cuboid → rectangle footprint (all 6 faces are rectangles).", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_fs_q7", topicId:"math2_ch6_footprint_shapes", text:"Why do different shapes leave different footprints?", options:[{text:"Because of their colour",type:"concept_error"},{text:"Because of the shape of their faces",type:"correct"},{text:"Because of their weight",type:"misinterpretation"},{text:"Because of their size",type:"partial_logic"}], explanation:"The footprint is determined by the shape of the face that contacts the surface.", solutionSteps:["Footprint = 2D cross-section of the 3D shape's contact face"], shortcut:"Shape of face → shape of footprint.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_fs_q8", topicId:"math2_ch6_footprint_shapes", text:"Which 2D shape cannot be a footprint of any common 3D solid?", options:[{text:"Circle",type:"misinterpretation"},{text:"Square",type:"misinterpretation"},{text:"Triangle",type:"concept_error"},{text:"Star shape",type:"correct"}], explanation:"Common 3D solids produce circle, square, or rectangle footprints. A star is not a footprint of standard solids.", solutionSteps:["Standard solids → circle, square, rectangle, triangle footprints","Star is not a standard cross-section"], shortcut:"Common solids have circular, square, or rectangular cross-sections.", difficulty:"medium", subject:"Math", grade:2, chapter:6 },

  // math2_ch6_symmetry — 8 questions
  { questionId:"math2_ch6_sym_q1", topicId:"math2_ch6_symmetry", text:"How many lines of symmetry does a square have?", options:[{text:"1",type:"concept_error"},{text:"2",type:"calculation_error"},{text:"4",type:"correct"},{text:"8",type:"misinterpretation"}], explanation:"A square has 4 lines of symmetry: 2 through midpoints of sides, 2 through opposite corners.", solutionSteps:["Square: 2 diagonal + 2 horizontal/vertical = 4 lines"], shortcut:"Square = 4 lines of symmetry.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_sym_q2", topicId:"math2_ch6_symmetry", text:"The letter 'A' has how many lines of symmetry?", options:[{text:"0",type:"concept_error"},{text:"1",type:"correct"},{text:"2",type:"calculation_error"},{text:"3",type:"misinterpretation"}], explanation:"The letter A has 1 vertical line of symmetry down the middle.", solutionSteps:["Fold A vertically: left half matches right half → 1 line of symmetry"], shortcut:"A = 1 vertical line of symmetry.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_sym_q3", topicId:"math2_ch6_symmetry", text:"Which of these shapes has NO lines of symmetry?", options:[{text:"Circle",type:"misinterpretation"},{text:"Square",type:"misinterpretation"},{text:"Scalene triangle",type:"correct"},{text:"Rectangle",type:"misinterpretation"}], explanation:"A scalene triangle has no equal sides and no lines of symmetry.", solutionSteps:["Scalene triangle: all sides different → no matching halves"], shortcut:"Scalene = no symmetry (all sides different).", difficulty:"medium", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_sym_q4", topicId:"math2_ch6_symmetry", text:"A rectangle has how many lines of symmetry?", options:[{text:"1",type:"concept_error"},{text:"2",type:"correct"},{text:"4",type:"misinterpretation"},{text:"0",type:"concept_error"}], explanation:"A rectangle has 2 lines of symmetry: one horizontal and one vertical through the midpoints.", solutionSteps:["Rectangle: horizontal midline and vertical midline = 2 lines"], shortcut:"Rectangle = 2 lines (not through corners).", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_sym_q5", topicId:"math2_ch6_symmetry", text:"What does a line of symmetry do to a shape?", options:[{text:"Makes it larger",type:"concept_error"},{text:"Divides it into two identical halves",type:"correct"},{text:"Measures its length",type:"misinterpretation"},{text:"Changes its colour",type:"guessing"}], explanation:"A line of symmetry divides a shape into two perfectly matching (mirror) halves.", solutionSteps:["Fold along the line → both halves match exactly"], shortcut:"Line of symmetry = fold line where both halves match.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_sym_q6", topicId:"math2_ch6_symmetry", text:"A circle has how many lines of symmetry?", options:[{text:"0",type:"concept_error"},{text:"4",type:"calculation_error"},{text:"8",type:"calculation_error"},{text:"Infinite",type:"correct"}], explanation:"A circle has infinitely many lines of symmetry — any diameter is a line of symmetry.", solutionSteps:["Any diameter of a circle divides it into two equal halves","There are infinitely many diameters"], shortcut:"Circle = infinite lines of symmetry.", difficulty:"medium", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_sym_q7", topicId:"math2_ch6_symmetry", text:"If you fold a butterfly image along its body, both wings match. This is:", options:[{text:"Estimation",type:"misinterpretation"},{text:"Symmetry",type:"correct"},{text:"A pattern",type:"partial_logic"},{text:"Measurement",type:"guessing"}], explanation:"The body is the line of symmetry; both wings are mirror images → symmetry.", solutionSteps:["Both sides match when folded → symmetry"], shortcut:"Nature often has symmetry — butterfly wings, leaves, faces.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_sym_q8", topicId:"math2_ch6_symmetry", text:"Which letter has a horizontal line of symmetry?", options:[{text:"A",type:"concept_error"},{text:"B",type:"correct"},{text:"L",type:"misinterpretation"},{text:"T",type:"partial_logic"}], explanation:"B has a horizontal line of symmetry — the top half mirrors the bottom half.", solutionSteps:["Fold B horizontally → top half matches bottom half"], shortcut:"B, C, D, E, K have horizontal lines of symmetry.", difficulty:"medium", subject:"Math", grade:2, chapter:6 },

  // math2_ch6_measuring_length — 8 questions
  { questionId:"math2_ch6_ml_q1", topicId:"math2_ch6_measuring_length", text:"Riya measures her desk using her handspan. She gets 5 spans. Her friend gets 6 spans. Why?", options:[{text:"They measured different desks",type:"misinterpretation"},{text:"Their hands are different sizes",type:"correct"},{text:"They both made an error",type:"concept_error"},{text:"Desks change size",type:"guessing"}], explanation:"Hand spans differ from person to person. This is why non-standard units give different results.", solutionSteps:["Non-standard unit (hand) varies by person → different results for same object"], shortcut:"Non-standard units vary → results are not consistent.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_ml_q2", topicId:"math2_ch6_measuring_length", text:"Which is a non-standard unit of length?", options:[{text:"Centimetre",type:"misinterpretation"},{text:"Metre",type:"misinterpretation"},{text:"Foot (body part)",type:"correct"},{text:"Kilometre",type:"misinterpretation"}], explanation:"Using your foot (body part) as a unit is a non-standard unit.", solutionSteps:["Standard: cm, m, km","Non-standard: hand, foot (body), pencil length"], shortcut:"Non-standard = body parts or everyday objects.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_ml_q3", topicId:"math2_ch6_measuring_length", text:"A table is 8 pencils long. What does this tell us?", options:[{text:"The table is 8 cm",type:"concept_error"},{text:"It takes 8 pencils placed end-to-end to span the table",type:"correct"},{text:"The table has 8 sides",type:"misinterpretation"},{text:"8 people can sit at the table",type:"guessing"}], explanation:"8 pencils = 8 pencil-lengths placed end-to-end equals the length of the table.", solutionSteps:["Pencil used as a unit","8 pencils placed end-to-end = table length"], shortcut:"Number of units × unit length = total length.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_ml_q4", topicId:"math2_ch6_measuring_length", text:"If a pencil is about 15 cm, a table is 8 pencils long. About how many cm is the table?", options:[{text:"23 cm",type:"concept_error"},{text:"100 cm",type:"calculation_error"},{text:"120 cm",type:"correct"},{text:"80 cm",type:"calculation_error"}], explanation:"8 pencils × 15 cm each = 120 cm.", solutionSteps:["8 × 15 = 120 cm"], shortcut:"Total = count × length per unit.", difficulty:"medium", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_ml_q5", topicId:"math2_ch6_measuring_length", text:"Which is more reliable — measuring with a hand or a ruler?", options:[{text:"Hand",type:"concept_error"},{text:"Ruler",type:"correct"},{text:"Both are equally reliable",type:"misinterpretation"},{text:"Neither",type:"guessing"}], explanation:"A ruler uses standard units (cm) that are the same everywhere. Hands vary.", solutionSteps:["Ruler: standard units → consistent results","Hand: non-standard → varies by person"], shortcut:"Standard unit (ruler) = reliable. Non-standard (hand) = variable.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_ml_q6", topicId:"math2_ch6_measuring_length", text:"A book is 3 erasers long. An eraser is 5 cm. How long is the book?", options:[{text:"8 cm",type:"concept_error"},{text:"10 cm",type:"calculation_error"},{text:"15 cm",type:"correct"},{text:"20 cm",type:"calculation_error"}], explanation:"3 × 5 cm = 15 cm.", solutionSteps:["3 erasers × 5 cm per eraser = 15 cm"], shortcut:"Units × cm per unit = total cm.", difficulty:"medium", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_ml_q7", topicId:"math2_ch6_measuring_length", text:"Which of these is a standard unit of length?", options:[{text:"Palm",type:"concept_error"},{text:"Thumb width",type:"concept_error"},{text:"Centimetre",type:"correct"},{text:"Arm span",type:"misinterpretation"}], explanation:"Centimetre (cm) is a standard unit used everywhere consistently.", solutionSteps:["Standard units: cm, m, km — same everywhere"], shortcut:"If it's a body part → non-standard. If it has a fixed value → standard.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_ml_q8", topicId:"math2_ch6_measuring_length", text:"Why did ancient people use non-standard units?", options:[{text:"Standard units didn't exist yet",type:"correct"},{text:"Standard units were too expensive",type:"misinterpretation"},{text:"Non-standard units are more accurate",type:"concept_error"},{text:"There was no need to measure",type:"guessing"}], explanation:"Standard units like cm and m were invented much later. Early people used body parts as convenient units.", solutionSteps:["Non-standard units were the only option before standard units were invented"], shortcut:"Non-standard came first; standard units were invented for consistency.", difficulty:"medium", subject:"Math", grade:2, chapter:6 },

  // math2_ch6_comparing_sizes — 8 questions
  { questionId:"math2_ch6_cs_q1", topicId:"math2_ch6_comparing_sizes", text:"A pencil is 12 cm and a pen is 14 cm. Which is longer?", options:[{text:"Pencil",type:"concept_error"},{text:"Pen",type:"correct"},{text:"Both same",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"14 > 12, so the pen is longer.", solutionSteps:["14 cm (pen) > 12 cm (pencil) → pen is longer"], shortcut:"Compare the numbers; larger = longer.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_cs_q2", topicId:"math2_ch6_comparing_sizes", text:"Order from shortest to longest: rope A=25 cm, rope B=40 cm, rope C=15 cm.", options:[{text:"A, B, C",type:"concept_error"},{text:"C, A, B",type:"correct"},{text:"B, A, C",type:"misinterpretation"},{text:"A, C, B",type:"calculation_error"}], explanation:"15 < 25 < 40. Shortest to longest: C, A, B.", solutionSteps:["15 < 25 < 40","C(15), A(25), B(40)"], shortcut:"Sort lengths from smallest to largest number.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_cs_q3", topicId:"math2_ch6_comparing_sizes", text:"To compare the lengths of two sticks fairly, we should:", options:[{text:"Hold them in the air",type:"misinterpretation"},{text:"Align one end and see which extends further",type:"correct"},{text:"Guess by looking",type:"concept_error"},{text:"Weigh them",type:"guessing"}], explanation:"Aligning one end ensures a fair comparison — the stick that extends further is longer.", solutionSteps:["Align at one end","Read which end sticks out more"], shortcut:"Align one end → look at other end.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_cs_q4", topicId:"math2_ch6_comparing_sizes", text:"Pencil = 15 cm, Eraser = 5 cm. How much longer is the pencil?", options:[{text:"20 cm",type:"concept_error"},{text:"10 cm",type:"correct"},{text:"5 cm",type:"calculation_error"},{text:"15 cm",type:"partial_logic"}], explanation:"15 − 5 = 10 cm. The pencil is 10 cm longer.", solutionSteps:["Difference = 15 − 5 = 10 cm"], shortcut:"How much longer = subtract shorter from longer.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_cs_q5", topicId:"math2_ch6_comparing_sizes", text:"A snake is 30 cm and a worm is 8 cm. Which is shorter?", options:[{text:"Snake",type:"concept_error"},{text:"Worm",type:"correct"},{text:"Both same",type:"misinterpretation"},{text:"Cannot compare",type:"guessing"}], explanation:"8 < 30, so the worm is shorter.", solutionSteps:["8 cm < 30 cm → worm is shorter"], shortcut:"Smaller number = shorter object.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_cs_q6", topicId:"math2_ch6_comparing_sizes", text:"Three strings: red=18 cm, blue=12 cm, green=24 cm. Which is longest?", options:[{text:"Red",type:"concept_error"},{text:"Blue",type:"concept_error"},{text:"Green",type:"correct"},{text:"All same",type:"misinterpretation"}], explanation:"24 > 18 > 12. Green (24 cm) is the longest.", solutionSteps:["24 > 18 > 12 → green is longest"], shortcut:"Largest number = longest.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_cs_q7", topicId:"math2_ch6_comparing_sizes", text:"A is shorter than B. B is shorter than C. What is the order from shortest to longest?", options:[{text:"C, B, A",type:"concept_error"},{text:"A, B, C",type:"correct"},{text:"B, A, C",type:"misinterpretation"},{text:"C, A, B",type:"guessing"}], explanation:"A < B < C. Shortest to longest: A, B, C.", solutionSteps:["A < B < C → A, B, C"], shortcut:"Shorter than = smaller. Follow the chain.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
  { questionId:"math2_ch6_cs_q8", topicId:"math2_ch6_comparing_sizes", text:"If the difference in length between two objects is 0, what does that mean?", options:[{text:"One is twice the other",type:"concept_error"},{text:"They are equal in length",type:"correct"},{text:"One is longer",type:"concept_error"},{text:"Cannot compare",type:"guessing"}], explanation:"Difference = 0 means the lengths are equal — both objects are the same length.", solutionSteps:["Difference = longer − shorter","If difference = 0 → equal lengths"], shortcut:"Difference = 0 → same length.", difficulty:"easy", subject:"Math", grade:2, chapter:6 },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  let inserted = 0;
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
    console.log(`  ✓ ${q.questionId}`);
    inserted++;
  }
  console.log(`\nSeeded ${inserted} Class 2 Math v2 questions (Ch5–Ch6).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
