import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // ── Chapter 15: How Many Ponytails? ── math2_ch15_survey_data (8 Qs)
  {
    questionId: "math2_ch15_survey_data_q1",
    topicId: "math2_ch15_survey_data",
    text: "What does a survey help you do?",
    options: [
      { text: "Draw pictures", type: "concept_error" },
      { text: "Collect answers from many people", type: "correct" },
      { text: "Build a house", type: "guessing" },
      { text: "Solve a multiplication", type: "concept_error" },
    ],
    explanation: "A survey is a way to collect answers (data) by asking a question to many people.",
    solutionSteps: ["Pick a question.", "Ask many people.", "Record each answer.", "That collection is your survey data."],
    shortcut: "Survey = ask + record.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_survey_data_q2",
    topicId: "math2_ch15_survey_data",
    text: "Ravi wants to know which fruit his class likes most. What should he do first?",
    options: [
      { text: "Buy fruits for everyone", type: "concept_error" },
      { text: "Decide the question to ask", type: "correct" },
      { text: "Make a graph", type: "partial_logic" },
      { text: "Eat a fruit himself", type: "guessing" },
    ],
    explanation: "Before asking, you must decide the question. A clear question gives clean data.",
    solutionSteps: ["Step 1: decide the question.", "Step 2: ask each classmate.", "Step 3: record answers."],
    shortcut: "First decide the question, then start asking.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_survey_data_q3",
    topicId: "math2_ch15_survey_data",
    text: "Which is the BEST way to record answers as you ask people?",
    options: [
      { text: "Remember them all in your head", type: "concept_error" },
      { text: "Use a tally table", type: "correct" },
      { text: "Write a long story", type: "partial_logic" },
      { text: "Take a photo", type: "guessing" },
    ],
    explanation: "Tally tables make it quick to record and easy to count totals at the end.",
    solutionSteps: ["Tally marks are fast: |, ||, |||, ||||, then cross the 5th for ||||̸.", "One mark per answer."],
    shortcut: "Tally as you go — count at the end.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_survey_data_q4",
    topicId: "math2_ch15_survey_data",
    text: "Survey: 'Favourite colour?' Answers: Red=10, Blue=7, Green=5, Yellow=3. How many people were asked in total?",
    options: [
      { text: "20", type: "calculation_error" },
      { text: "22", type: "calculation_error" },
      { text: "25", type: "correct" },
      { text: "30", type: "guessing" },
    ],
    explanation: "Total = 10 + 7 + 5 + 3 = 25.",
    solutionSteps: ["Add all counts: 10 + 7 = 17.", "17 + 5 = 22.", "22 + 3 = 25."],
    shortcut: "Total people = sum of all category counts.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_survey_data_q5",
    topicId: "math2_ch15_survey_data",
    text: "Which question is a GOOD survey question?",
    options: [
      { text: "Why is the sky?", type: "concept_error" },
      { text: "What is your favourite sport?", type: "correct" },
      { text: "Maybe ice cream?", type: "guessing" },
      { text: "How big is small?", type: "misinterpretation" },
    ],
    explanation: "A good survey question is clear and asks for a single answer that can be counted.",
    solutionSteps: ["Clear question → people understand.", "Single answer per person → easy to tally."],
    shortcut: "Survey questions should be clear, short, and answerable.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_survey_data_q6",
    topicId: "math2_ch15_survey_data",
    text: "If only Riya's friends are asked, what is the problem with the survey?",
    options: [
      { text: "Nothing — friends are best", type: "concept_error" },
      { text: "Answers may not represent the whole class", type: "correct" },
      { text: "Tally marks won't work", type: "misinterpretation" },
      { text: "It will take too long", type: "guessing" },
    ],
    explanation: "Asking only friends is biased — their answers won't reflect the whole group.",
    solutionSteps: ["Survey should include different kinds of people.", "Otherwise the result is unfair (biased)."],
    shortcut: "Ask a mix of people for fair results.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_survey_data_q7",
    topicId: "math2_ch15_survey_data",
    text: "Survey of pets: Dog=8, Cat=5, Fish=2. Which pet is most common?",
    options: [
      { text: "Cat", type: "concept_error" },
      { text: "Fish", type: "concept_error" },
      { text: "Dog", type: "correct" },
      { text: "All equal", type: "misinterpretation" },
    ],
    explanation: "Most common = the category with the highest count. Dog = 8, which is the highest.",
    solutionSteps: ["Compare: 8 > 5 > 2.", "Highest count → most common pet."],
    shortcut: "Largest tally = most common answer.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_survey_data_q8",
    topicId: "math2_ch15_survey_data",
    text: "After collecting survey answers, what is the LAST step?",
    options: [
      { text: "Ask more people", type: "partial_logic" },
      { text: "Add up the tallies to get totals", type: "correct" },
      { text: "Throw the data away", type: "guessing" },
      { text: "Decide a new question", type: "concept_error" },
    ],
    explanation: "The final step is counting the tally marks for each category to get totals.",
    solutionSteps: ["1: decide question.", "2: ask.", "3: tally.", "4: count totals."],
    shortcut: "Last step = count and total each category.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },

  // ── Chapter 15: How Many Ponytails? ── math2_ch15_sorting_data (8 Qs)
  {
    questionId: "math2_ch15_sorting_data_q1",
    topicId: "math2_ch15_sorting_data",
    text: "Sorting means…",
    options: [
      { text: "Throwing data away", type: "concept_error" },
      { text: "Grouping items by a feature", type: "correct" },
      { text: "Drawing a picture", type: "misinterpretation" },
      { text: "Counting only odd numbers", type: "guessing" },
    ],
    explanation: "Sorting groups items by a shared feature like colour, size, or type.",
    solutionSteps: ["Pick a feature (e.g., colour).", "Place each item into a group based on that feature."],
    shortcut: "Sort = group by a shared feature.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_sorting_data_q2",
    topicId: "math2_ch15_sorting_data",
    text: "Hair types in class: curly=8, straight=12, wavy=5. How many groups are the children sorted into?",
    options: [
      { text: "2", type: "concept_error" },
      { text: "3", type: "correct" },
      { text: "8", type: "misinterpretation" },
      { text: "25", type: "misinterpretation" },
    ],
    explanation: "Three categories: curly, straight, wavy → 3 groups.",
    solutionSteps: ["Count the categories: curly, straight, wavy → 3."],
    shortcut: "Number of categories = number of groups.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_sorting_data_q3",
    topicId: "math2_ch15_sorting_data",
    text: "Hair types: curly=8, straight=12, wavy=5. How many children in total?",
    options: [
      { text: "20", type: "calculation_error" },
      { text: "25", type: "correct" },
      { text: "13", type: "calculation_error" },
      { text: "27", type: "guessing" },
    ],
    explanation: "Total = 8 + 12 + 5 = 25.",
    solutionSteps: ["8 + 12 = 20.", "20 + 5 = 25."],
    shortcut: "Sum each group's count for the total.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_sorting_data_q4",
    topicId: "math2_ch15_sorting_data",
    text: "Why must sorting categories NOT overlap?",
    options: [
      { text: "So a single item belongs to exactly one group", type: "correct" },
      { text: "Because overlap is illegal", type: "guessing" },
      { text: "Because graphs look ugly", type: "misinterpretation" },
      { text: "It does not matter", type: "concept_error" },
    ],
    explanation: "If categories overlap, an item could be counted twice — that breaks the totals.",
    solutionSteps: ["Each data point → exactly one category.", "No overlap → totals add up correctly."],
    shortcut: "One item, one category — no overlap.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_sorting_data_q5",
    topicId: "math2_ch15_sorting_data",
    text: "Sort these shapes by sides: triangle=4, square=6, circle=2 (sides=0). Which group has the most?",
    options: [
      { text: "Triangle", type: "concept_error" },
      { text: "Circle", type: "concept_error" },
      { text: "Square", type: "correct" },
      { text: "All equal", type: "misinterpretation" },
    ],
    explanation: "Compare counts: 4, 6, 2. The square group has 6, which is the most.",
    solutionSteps: ["Triangle: 4.", "Square: 6.", "Circle: 2.", "Most = 6 = square."],
    shortcut: "Biggest count wins.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_sorting_data_q6",
    topicId: "math2_ch15_sorting_data",
    text: "Which sorting rule could split shoes into 2 groups?",
    options: [
      { text: "Colours of the rainbow", type: "concept_error" },
      { text: "Left foot vs right foot", type: "correct" },
      { text: "Brand and model and size and colour", type: "partial_logic" },
      { text: "Names of the owners", type: "misinterpretation" },
    ],
    explanation: "Left vs right gives exactly 2 categories. The other choices give more or fewer than 2.",
    solutionSteps: ["Need 2 groups → 2 categories.", "Left/right = 2 categories."],
    shortcut: "Want N groups? Choose a feature with N possible values.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_sorting_data_q7",
    topicId: "math2_ch15_sorting_data",
    text: "Sorted toys: cars=10, dolls=6, balls=4. Which two groups together equal the cars group?",
    options: [
      { text: "Cars + dolls", type: "misinterpretation" },
      { text: "Dolls + balls", type: "correct" },
      { text: "Cars + balls", type: "calculation_error" },
      { text: "None of them", type: "guessing" },
    ],
    explanation: "Dolls + balls = 6 + 4 = 10 = cars count.",
    solutionSteps: ["Cars = 10.", "Dolls + balls = 6 + 4 = 10.", "Match found."],
    shortcut: "Add pairs of other categories to find matching totals.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_sorting_data_q8",
    topicId: "math2_ch15_sorting_data",
    text: "Which is NOT a good sorting rule for a class survey?",
    options: [
      { text: "By favourite colour", type: "concept_error" },
      { text: "By age (in years)", type: "concept_error" },
      { text: "By a feeling that changes every minute", type: "correct" },
      { text: "By tallest to shortest", type: "partial_logic" },
    ],
    explanation: "Sorting rules must be stable (not change while you sort). A feeling that changes every minute is unreliable.",
    solutionSteps: ["Need a stable, measurable feature.", "Feelings change → unreliable."],
    shortcut: "Sort on stable, observable features.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },

  // ── Chapter 15: How Many Ponytails? ── math2_ch15_interpreting_data (8 Qs)
  {
    questionId: "math2_ch15_interpreting_data_q1",
    topicId: "math2_ch15_interpreting_data",
    text: "Table: Fruit | Count. Apple=12, Mango=7, Banana=15. Which fruit has the highest count?",
    options: [
      { text: "Apple", type: "concept_error" },
      { text: "Mango", type: "concept_error" },
      { text: "Banana", type: "correct" },
      { text: "All equal", type: "misinterpretation" },
    ],
    explanation: "Highest count: Banana (15) > Apple (12) > Mango (7).",
    solutionSteps: ["Compare: 15 > 12 > 7.", "Banana wins."],
    shortcut: "Largest count = highest row.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_interpreting_data_q2",
    topicId: "math2_ch15_interpreting_data",
    text: "Table: Apple=12, Mango=7, Banana=15. What is the total count of all fruits?",
    options: [
      { text: "27", type: "calculation_error" },
      { text: "32", type: "calculation_error" },
      { text: "34", type: "correct" },
      { text: "37", type: "guessing" },
    ],
    explanation: "12 + 7 + 15 = 34.",
    solutionSteps: ["12 + 7 = 19.", "19 + 15 = 34."],
    shortcut: "Sum the counts column.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_interpreting_data_q3",
    topicId: "math2_ch15_interpreting_data",
    text: "Table: Apple=12, Mango=7, Banana=15. How many MORE bananas than mangoes?",
    options: [
      { text: "5", type: "calculation_error" },
      { text: "8", type: "correct" },
      { text: "22", type: "concept_error" },
      { text: "3", type: "calculation_error" },
    ],
    explanation: "Difference = 15 − 7 = 8.",
    solutionSteps: ["Banana = 15.", "Mango = 7.", "15 − 7 = 8."],
    shortcut: "'How many more' = subtract smaller from larger.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_interpreting_data_q4",
    topicId: "math2_ch15_interpreting_data",
    text: "When reading a table, what should you check FIRST?",
    options: [
      { text: "The colour of the paper", type: "concept_error" },
      { text: "The row and column labels", type: "correct" },
      { text: "Only the biggest number", type: "partial_logic" },
      { text: "The title, then ignore the rest", type: "misinterpretation" },
    ],
    explanation: "Row and column labels tell you what the numbers mean. Without them, the data has no meaning.",
    solutionSteps: ["Read the title.", "Read row labels.", "Read column labels.", "Then read values."],
    shortcut: "Labels first — values second.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_interpreting_data_q5",
    topicId: "math2_ch15_interpreting_data",
    text: "Table: Day | Books read. Mon=3, Tue=5, Wed=2, Thu=4. On which day were the FEWEST books read?",
    options: [
      { text: "Monday", type: "concept_error" },
      { text: "Tuesday", type: "concept_error" },
      { text: "Wednesday", type: "correct" },
      { text: "Thursday", type: "concept_error" },
    ],
    explanation: "Fewest = smallest count. 2 < 3 < 4 < 5 → Wednesday with 2 books.",
    solutionSteps: ["Compare: 2 (Wed) < 3 (Mon) < 4 (Thu) < 5 (Tue).", "Wed is smallest."],
    shortcut: "Smallest count = fewest.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_interpreting_data_q6",
    topicId: "math2_ch15_interpreting_data",
    text: "Table: Mon=3, Tue=5, Wed=2, Thu=4. How many books were read in the first two days together?",
    options: [
      { text: "5", type: "calculation_error" },
      { text: "8", type: "correct" },
      { text: "10", type: "misinterpretation" },
      { text: "14", type: "guessing" },
    ],
    explanation: "First two days = Mon + Tue = 3 + 5 = 8.",
    solutionSteps: ["Mon = 3.", "Tue = 5.", "3 + 5 = 8."],
    shortcut: "'First two days' = add Mon + Tue.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_interpreting_data_q7",
    topicId: "math2_ch15_interpreting_data",
    text: "If a table value is missing but the total = 20 and the other rows are 5, 6, and 4, what is the missing value?",
    options: [
      { text: "3", type: "calculation_error" },
      { text: "5", type: "correct" },
      { text: "6", type: "calculation_error" },
      { text: "15", type: "concept_error" },
    ],
    explanation: "Sum of known = 5 + 6 + 4 = 15. Missing = 20 − 15 = 5.",
    solutionSteps: ["Add known: 5 + 6 + 4 = 15.", "Missing = 20 − 15 = 5."],
    shortcut: "Missing value = Total − sum of known values.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_interpreting_data_q8",
    topicId: "math2_ch15_interpreting_data",
    text: "Two tables show pet counts for two classes. Class A: dogs=4, cats=6. Class B: dogs=3, cats=8. Which class has MORE cats?",
    options: [
      { text: "Class A", type: "concept_error" },
      { text: "Class B", type: "correct" },
      { text: "Equal", type: "calculation_error" },
      { text: "Cannot tell", type: "guessing" },
    ],
    explanation: "Cats: Class A = 6, Class B = 8. 8 > 6 → Class B has more cats.",
    solutionSteps: ["Find 'cats' row in each table.", "A: 6, B: 8.", "8 > 6 → B."],
    shortcut: "Compare the same row across tables.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },

  // ── Chapter 15: How Many Ponytails? ── math2_ch15_making_graphs (8 Qs)
  {
    questionId: "math2_ch15_making_graphs_q1",
    topicId: "math2_ch15_making_graphs",
    text: "What does a bar graph use to show counts?",
    options: [
      { text: "Bars of different heights", type: "correct" },
      { text: "Dots only", type: "concept_error" },
      { text: "Pictures of food", type: "misinterpretation" },
      { text: "Words only", type: "concept_error" },
    ],
    explanation: "Bar graphs use rectangular bars whose heights match the counts.",
    solutionSteps: ["Each category gets one bar.", "Bar height matches count."],
    shortcut: "Tallest bar = largest count.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_making_graphs_q2",
    topicId: "math2_ch15_making_graphs",
    text: "Data: Apples=12, Mangoes=7, Bananas=15. In a bar graph, which bar is TALLEST?",
    options: [
      { text: "Apples", type: "concept_error" },
      { text: "Mangoes", type: "concept_error" },
      { text: "Bananas", type: "correct" },
      { text: "All equal", type: "misinterpretation" },
    ],
    explanation: "Tallest bar = largest count = Bananas (15).",
    solutionSteps: ["Compare: 12, 7, 15.", "15 is the largest.", "Bananas bar is tallest."],
    shortcut: "Highest count → tallest bar.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_making_graphs_q3",
    topicId: "math2_ch15_making_graphs",
    text: "Before drawing bars, what should you decide first?",
    options: [
      { text: "The colour of the bars", type: "partial_logic" },
      { text: "The scale on the y-axis", type: "correct" },
      { text: "Where to eat lunch", type: "guessing" },
      { text: "Whether to use a pen", type: "misinterpretation" },
    ],
    explanation: "Scale (the step size on the y-axis) decides how tall each bar should be drawn. Pick scale first.",
    solutionSteps: ["Find max value in data.", "Choose a scale step that fits (e.g., 1, 2, 5, 10).", "Then draw bars."],
    shortcut: "Scale first, bars next.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_making_graphs_q4",
    topicId: "math2_ch15_making_graphs",
    text: "A graph has bars but no title. What is the problem?",
    options: [
      { text: "Nothing — bars are enough", type: "concept_error" },
      { text: "We don't know what the graph is about", type: "correct" },
      { text: "The bars are too tall", type: "misinterpretation" },
      { text: "There's not enough colour", type: "guessing" },
    ],
    explanation: "Without a title, the graph has no context — we don't know what is being measured.",
    solutionSteps: ["Title tells the reader the subject of the graph.", "Missing title → confused reader."],
    shortcut: "Always give your graph a title.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_making_graphs_q5",
    topicId: "math2_ch15_making_graphs",
    text: "Pictograph key: each ☺ = 2 people. To show 8 people in a row, how many ☺ do you draw?",
    options: [
      { text: "2", type: "calculation_error" },
      { text: "4", type: "correct" },
      { text: "6", type: "calculation_error" },
      { text: "8", type: "misinterpretation" },
    ],
    explanation: "8 people ÷ 2 per symbol = 4 symbols.",
    solutionSteps: ["Each symbol stands for 2 people.", "8 ÷ 2 = 4 symbols."],
    shortcut: "Symbols needed = total ÷ key value.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_making_graphs_q6",
    topicId: "math2_ch15_making_graphs",
    text: "Pictograph key: each ★ = 5 books. A row has 3 stars. How many books does that row show?",
    options: [
      { text: "3", type: "concept_error" },
      { text: "8", type: "calculation_error" },
      { text: "15", type: "correct" },
      { text: "5", type: "calculation_error" },
    ],
    explanation: "3 stars × 5 books each = 15 books.",
    solutionSteps: ["3 × 5 = 15."],
    shortcut: "Books = stars × key value.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_making_graphs_q7",
    topicId: "math2_ch15_making_graphs",
    text: "Data has values 0, 4, 8, 12, 16, 20. What is the BEST scale step on the y-axis?",
    options: [
      { text: "1", type: "partial_logic" },
      { text: "4", type: "correct" },
      { text: "10", type: "calculation_error" },
      { text: "100", type: "guessing" },
    ],
    explanation: "All values are multiples of 4. A scale of 4 fits perfectly and uses fewer gridlines.",
    solutionSteps: ["Look for a common step that divides all values.", "All values are multiples of 4.", "Step = 4."],
    shortcut: "Pick the largest step that still hits all your data points.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
  {
    questionId: "math2_ch15_making_graphs_q8",
    topicId: "math2_ch15_making_graphs",
    text: "Why is a graph often better than a table for comparing data?",
    options: [
      { text: "Graphs hide numbers", type: "concept_error" },
      { text: "You can SEE which is biggest at a glance", type: "correct" },
      { text: "Tables are not allowed", type: "guessing" },
      { text: "Graphs are smaller", type: "misinterpretation" },
    ],
    explanation: "A graph makes the comparison visual — you instantly see the tallest bar or longest row.",
    solutionSteps: ["Graphs turn numbers into pictures.", "Pictures are quicker to compare than numbers."],
    shortcut: "Graphs = quick visual comparison.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "How Many Ponytails?",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 2 Math v2 questions (Chapter 15).`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
