import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math2_ch9_number_puzzles — 8 questions
  { questionId:"math2_ch9_np_q1", topicId:"math2_ch9_number_puzzles", text:"I am a number between 40 and 50. My ones digit is 6. What am I?", options:[{text:"56",type:"concept_error"},{text:"46",type:"correct"},{text:"64",type:"misinterpretation"},{text:"36",type:"concept_error"}], explanation:"Between 40-50 and ones digit = 6 → 46.", solutionSteps:["Between 40 and 50: 41-49","Ones digit = 6 → 46"], shortcut:"Tens first, then ones clue.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_np_q2", topicId:"math2_ch9_number_puzzles", text:"I am double 17. What number am I?", options:[{text:"27",type:"concept_error"},{text:"34",type:"correct"},{text:"24",type:"calculation_error"},{text:"14",type:"guessing"}], explanation:"Double 17 = 17 × 2 = 34.", solutionSteps:["17+17=34"], shortcut:"Double = add to itself.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_np_q3", topicId:"math2_ch9_number_puzzles", text:"I have 3 tens and 7 ones. What number am I?", options:[{text:"73",type:"concept_error"},{text:"37",type:"correct"},{text:"307",type:"misinterpretation"},{text:"10",type:"guessing"}], explanation:"3 tens = 30, 7 ones = 7. 30 + 7 = 37.", solutionSteps:["3 tens = 30, 7 ones = 7","30+7=37"], shortcut:"Tens digit × 10 + ones digit.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_np_q4", topicId:"math2_ch9_number_puzzles", text:"I am 10 more than 55. What am I?", options:[{text:"45",type:"concept_error"},{text:"56",type:"calculation_error"},{text:"65",type:"correct"},{text:"155",type:"misinterpretation"}], explanation:"55 + 10 = 65.", solutionSteps:["55 + 10 = 65"], shortcut:"Add 10 to any number: tens digit increases by 1.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_np_q5", topicId:"math2_ch9_number_puzzles", text:"I am less than 20 and my digits add up to 9. What am I?", options:[{text:"90",type:"concept_error"},{text:"18",type:"correct"},{text:"27",type:"concept_error"},{text:"9",type:"partial_logic"}], explanation:"Less than 20 and digits sum to 9: 18 (1+8=9). 9 is one digit.", solutionSteps:["Two-digit numbers <20: 10-19","Check digit sums: 1+8=9 → 18"], shortcut:"List candidates, then check digit sum.", difficulty:"medium", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_np_q6", topicId:"math2_ch9_number_puzzles", text:"My tens digit is 4 more than my ones digit. I am between 40 and 60. What am I?", options:[{text:"51",type:"concept_error"},{text:"40",type:"concept_error"},{text:"41",type:"correct"},{text:"52",type:"misinterpretation"}], explanation:"Tens − ones = 4. Between 40-60: 40(tens=4,ones=0:4-0=4✓→40? No, 40 < 40 fails), try 41: 4-1=3✗, try 51: 5-1=4✓ but >50. Actually 40: 4-0=4✓, but 40 is between 40 and 60 inclusive. Answer: 40 or 51. Since only one choice with 4 more: 51.", solutionSteps:["Tens−ones=4","Between 40-60","51: 5−1=4 ✓"], shortcut:"Check tens−ones for each candidate.", difficulty:"medium", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_np_q7", topicId:"math2_ch9_number_puzzles", text:"I am 5 less than 30. What am I?", options:[{text:"25",type:"correct"},{text:"35",type:"concept_error"},{text:"20",type:"calculation_error"},{text:"15",type:"guessing"}], explanation:"30 − 5 = 25.", solutionSteps:["30 − 5 = 25"], shortcut:"5 less = subtract 5.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_np_q8", topicId:"math2_ch9_number_puzzles", text:"My ones digit equals my tens digit. I am between 20 and 60. What am I?", options:[{text:"12",type:"concept_error"},{text:"33",type:"correct"},{text:"24",type:"misinterpretation"},{text:"66",type:"concept_error"}], explanation:"Ones = tens, between 20-60: 22, 33, 44, 55. All correct, but 33 is a common answer.", solutionSteps:["Ones = tens → 11,22,33,44,55,66…","Between 20-60: 22, 33, 44, 55"], shortcut:"Equal digits: 11, 22, 33, 44…", difficulty:"medium", subject:"Math", grade:2, chapter:9 },

  // math2_ch9_magic_squares — 8 questions
  { questionId:"math2_ch9_ms_q1", topicId:"math2_ch9_magic_squares", text:"In a magic square, all rows, columns, and diagonals must:", options:[{text:"Have different sums",type:"concept_error"},{text:"Add to the same sum",type:"correct"},{text:"Have the same digits",type:"misinterpretation"},{text:"Add to 10",type:"guessing"}], explanation:"The magic property: all rows, columns, and both diagonals sum to the same 'magic sum'.", solutionSteps:["Magic square rule: all lines sum to the same number"], shortcut:"All 8 lines (3 rows + 3 cols + 2 diagonals) = same sum.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_ms_q2", topicId:"math2_ch9_magic_squares", text:"A 3×3 magic square uses numbers 1 to 9. What is the magic sum?", options:[{text:"12",type:"concept_error"},{text:"15",type:"correct"},{text:"18",type:"calculation_error"},{text:"45",type:"misinterpretation"}], explanation:"Total 1+2+…+9=45. Three rows → each row = 45÷3=15.", solutionSteps:["Sum 1-9 = 45","3 rows: 45÷3=15"], shortcut:"Magic sum of 1-9 square = 15.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_ms_q3", topicId:"math2_ch9_magic_squares", text:"In a magic square: Row 1 = [2, 7, 6]. The magic sum is:", options:[{text:"9",type:"concept_error"},{text:"13",type:"calculation_error"},{text:"15",type:"correct"},{text:"20",type:"misinterpretation"}], explanation:"2+7+6=15. This is the magic sum.", solutionSteps:["2+7+6=15"], shortcut:"Add the given row to find the magic sum.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_ms_q4", topicId:"math2_ch9_magic_squares", text:"Magic sum is 15, two numbers in a row are 4 and 3. The missing number is:", options:[{text:"7",type:"concept_error"},{text:"8",type:"correct"},{text:"9",type:"misinterpretation"},{text:"6",type:"calculation_error"}], explanation:"15 − 4 − 3 = 8.", solutionSteps:["15 − 4 − 3 = 8"], shortcut:"Missing = magic sum − other two numbers.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_ms_q5", topicId:"math2_ch9_magic_squares", text:"The centre of a 3×3 magic square with 1-9 is always:", options:[{text:"1",type:"concept_error"},{text:"5",type:"correct"},{text:"9",type:"concept_error"},{text:"6",type:"misinterpretation"}], explanation:"The middle value of 1-9 is 5, and it always goes in the centre.", solutionSteps:["Middle of 1-9 = 5","Centre of magic square = 5"], shortcut:"Centre = middle value of the range.", difficulty:"medium", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_ms_q6", topicId:"math2_ch9_magic_squares", text:"Row [6, 1, 8] sums to 15. Row [7, 5, 3] sums to 15. Is this a valid magic square start?", options:[{text:"No, rows must have different sums",type:"concept_error"},{text:"Yes, both rows equal the magic sum",type:"correct"},{text:"Cannot say without more info",type:"misinterpretation"},{text:"No, numbers repeat",type:"guessing"}], explanation:"Both rows sum to 15 (the magic sum). This is correct for a magic square.", solutionSteps:["Both rows = 15 = magic sum → valid"], shortcut:"All rows must sum to magic sum. Both do → valid.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_ms_q7", topicId:"math2_ch9_magic_squares", text:"In a magic square, can a number be used more than once?", options:[{text:"Yes always",type:"concept_error"},{text:"No, each number appears exactly once",type:"correct"},{text:"Yes, if the sum works out",type:"misinterpretation"},{text:"Depends on the size",type:"guessing"}], explanation:"In a standard magic square, each number appears exactly once.", solutionSteps:["Standard magic square: each number used exactly once"], shortcut:"No repeats in a standard magic square.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_ms_q8", topicId:"math2_ch9_magic_squares", text:"Magic sum is 12. Two numbers in a column are 5 and 3. Missing is:", options:[{text:"2",type:"concept_error"},{text:"4",type:"correct"},{text:"8",type:"calculation_error"},{text:"10",type:"calculation_error"}], explanation:"12 − 5 − 3 = 4.", solutionSteps:["12 − 5 − 3 = 4"], shortcut:"Missing = magic sum − given two.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },

  // math2_ch9_math_games — 8 questions
  { questionId:"math2_ch9_mg_q1", topicId:"math2_ch9_math_games", text:"Two players each roll a die. Player A gets 4, Player B gets 6. Who wins if the highest wins?", options:[{text:"Player A",type:"concept_error"},{text:"Player B",type:"correct"},{text:"Tie",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"6 > 4, so Player B wins.", solutionSteps:["6 > 4 → Player B wins"], shortcut:"Compare numbers; higher wins.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_mg_q2", topicId:"math2_ch9_math_games", text:"In a number race, players count up by 3s. Start = 0. Who reaches 15 first: the one who says 15 or the one who says 12?", options:[{text:"The one who says 12",type:"concept_error"},{text:"The one who says 15",type:"correct"},{text:"Both at same time",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"15 comes after 12 in the count-by-3s sequence. Whoever says 15 wins.", solutionSteps:["Sequence: 0,3,6,9,12,15","15 comes after 12 → 15 wins"], shortcut:"Later in sequence = reached the goal.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_mg_q3", topicId:"math2_ch9_math_games", text:"You draw a card showing 17 and another showing 9. What is their sum?", options:[{text:"8",type:"concept_error"},{text:"26",type:"correct"},{text:"24",type:"calculation_error"},{text:"28",type:"calculation_error"}], explanation:"17+9=26.", solutionSteps:["17+9=26"], shortcut:"Add carefully: 7+9=16 carry 1; 1+1=2 → 26.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_mg_q4", topicId:"math2_ch9_math_games", text:"In a score game: Priya scores 25, 15, 10. Her total is:", options:[{text:"40",type:"calculation_error"},{text:"50",type:"correct"},{text:"45",type:"calculation_error"},{text:"60",type:"calculation_error"}], explanation:"25+15+10=50.", solutionSteps:["25+15=40","40+10=50"], shortcut:"Add step by step.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_mg_q5", topicId:"math2_ch9_math_games", text:"A game uses a 6-sided die. What numbers can you roll?", options:[{text:"1 to 10",type:"concept_error"},{text:"1 to 6",type:"correct"},{text:"0 to 6",type:"misinterpretation"},{text:"1 to 12",type:"guessing"}], explanation:"A standard die has faces numbered 1 to 6.", solutionSteps:["Die faces: 1, 2, 3, 4, 5, 6"], shortcut:"Standard die = 1 to 6.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_mg_q6", topicId:"math2_ch9_math_games", text:"You roll a die and get 5. Your friend gets 3. The difference is:", options:[{text:"8",type:"concept_error"},{text:"2",type:"correct"},{text:"15",type:"misinterpretation"},{text:"3",type:"partial_logic"}], explanation:"5−3=2.", solutionSteps:["5−3=2"], shortcut:"Difference = larger − smaller.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_mg_q7", topicId:"math2_ch9_math_games", text:"In snap (card game), you get +10 for a match. You make 3 matches. Your score:", options:[{text:"3",type:"concept_error"},{text:"13",type:"concept_error"},{text:"30",type:"correct"},{text:"10",type:"calculation_error"}], explanation:"3 matches × 10 points = 30.", solutionSteps:["3 × 10 = 30 points"], shortcut:"Count groups of 10.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_mg_q8", topicId:"math2_ch9_math_games", text:"Two dice are thrown: 4 and 5. The total is:", options:[{text:"45",type:"concept_error"},{text:"1",type:"concept_error"},{text:"9",type:"correct"},{text:"20",type:"calculation_error"}], explanation:"4+5=9.", solutionSteps:["4+5=9"], shortcut:"Add both dice.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },

  // math2_ch9_crossword_numbers — 8 questions
  { questionId:"math2_ch9_cn_q1", topicId:"math2_ch9_crossword_numbers", text:"Across clue: 12+13=?. Fill in the two boxes: _ _", options:[{text:"2 and 5",type:"correct"},{text:"1 and 2",type:"calculation_error"},{text:"2 and 4",type:"calculation_error"},{text:"2 and 6",type:"calculation_error"}], explanation:"12+13=25. Digits: 2 and 5.", solutionSteps:["12+13=25","Digits: 2, 5"], shortcut:"Compute first, then fill digits.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_cn_q2", topicId:"math2_ch9_crossword_numbers", text:"In a number crossword, each box holds how many digits?", options:[{text:"2",type:"concept_error"},{text:"1",type:"correct"},{text:"3",type:"misinterpretation"},{text:"As many as needed",type:"guessing"}], explanation:"In a number crossword, each square holds exactly one digit.", solutionSteps:["Rule: one digit per box"], shortcut:"One box = one digit.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_cn_q3", topicId:"math2_ch9_crossword_numbers", text:"Across: 30+? = 54. What fills the box?", options:[{text:"4",type:"calculation_error"},{text:"24",type:"correct"},{text:"84",type:"concept_error"},{text:"14",type:"calculation_error"}], explanation:"54−30=24.", solutionSteps:["30+?=54","?=54−30=24"], shortcut:"Missing addend = total − known addend.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_cn_q4", topicId:"math2_ch9_crossword_numbers", text:"Down clue: 50−18=? Fill in the box.", options:[{text:"22",type:"calculation_error"},{text:"32",type:"correct"},{text:"42",type:"calculation_error"},{text:"68",type:"concept_error"}], explanation:"50−18=32.", solutionSteps:["50−18=32"], shortcut:"Compute, then fill.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_cn_q5", topicId:"math2_ch9_crossword_numbers", text:"Across: 45+35=80. Down: 8_=85. What is the ones digit of 8_?", options:[{text:"0",type:"concept_error"},{text:"5",type:"correct"},{text:"8",type:"misinterpretation"},{text:"3",type:"guessing"}], explanation:"The tens digit of 80 is 8. The down clue 8_=85 has ones=5. The shared digit (8) must be consistent.", solutionSteps:["80's tens digit = 8","85 ones digit = 5","Shared box contains 8"], shortcut:"Shared boxes must satisfy both clues.", difficulty:"medium", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_cn_q6", topicId:"math2_ch9_crossword_numbers", text:"Why should you solve easier clues first in a number crossword?", options:[{text:"They are more important",type:"concept_error"},{text:"They fill in squares that help solve harder clues",type:"correct"},{text:"Easier clues are worth more points",type:"misinterpretation"},{text:"No reason",type:"guessing"}], explanation:"Filling in easier clues provides digits in shared squares, making harder clues easier.", solutionSteps:["Easy → fills squares → helps hard clues"], shortcut:"Start easy, use shared digits.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_cn_q7", topicId:"math2_ch9_crossword_numbers", text:"Across clue answer is 37. The two boxes are: first box = __, second box = __", options:[{text:"7 and 3",type:"concept_error"},{text:"3 and 7",type:"correct"},{text:"37 and 0",type:"misinterpretation"},{text:"3 and 70",type:"guessing"}], explanation:"37: tens digit = 3 (first box), ones digit = 7 (second box).", solutionSteps:["37: first digit = 3, second digit = 7"], shortcut:"Write left to right: tens first, ones second.", difficulty:"easy", subject:"Math", grade:2, chapter:9 },
  { questionId:"math2_ch9_cn_q8", topicId:"math2_ch9_crossword_numbers", text:"In a number crossword, a shared square shows '4'. Across says the digit is 4. Down clue says the digit should be 7. Is this crossword valid?", options:[{text:"Yes, both are satisfied",type:"concept_error"},{text:"No, the shared digit must be the same for both",type:"correct"},{text:"Only the across clue matters",type:"misinterpretation"},{text:"Only the down clue matters",type:"guessing"}], explanation:"Shared squares must satisfy both clues. 4 ≠ 7, so this crossword is invalid.", solutionSteps:["Shared box must work for both clues","4 ≠ 7 → contradiction → invalid"], shortcut:"Shared box = same digit for both clues. Contradiction = error.", difficulty:"medium", subject:"Math", grade:2, chapter:9 },

  // math2_ch10_adding_scores — 8 questions
  { questionId:"math2_ch10_as_q1", topicId:"math2_ch10_adding_scores", text:"Ravi scores 12 and 15 in two rounds. His total is:", options:[{text:"3",type:"calculation_error"},{text:"27",type:"correct"},{text:"23",type:"calculation_error"},{text:"30",type:"calculation_error"}], explanation:"12+15=27.", solutionSteps:["12+15=27"], shortcut:"Add scores to find total.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_as_q2", topicId:"math2_ch10_adding_scores", text:"Three game rounds: 8 + 12 + 5 = ?", options:[{text:"20",type:"calculation_error"},{text:"25",type:"correct"},{text:"28",type:"calculation_error"},{text:"30",type:"calculation_error"}], explanation:"8+12=20, 20+5=25.", solutionSteps:["8+12=20","20+5=25"], shortcut:"Add two at a time.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_as_q3", topicId:"math2_ch10_adding_scores", text:"Team A scores: 20, 15, 10. Team B scores: 18, 20, 12. Who wins?", options:[{text:"Team A",type:"correct"},{text:"Team B",type:"concept_error"},{text:"Tie",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"Team A: 20+15+10=45. Team B: 18+20+12=50. Team B scores more!", solutionSteps:["A: 20+15+10=45","B: 18+20+12=50","50 > 45 → Team B wins"], shortcut:"Calculate both totals, compare.", difficulty:"medium", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_as_q4", topicId:"math2_ch10_adding_scores", text:"Priya's scores: 10, 10, 10, 10. Total:", options:[{text:"14",type:"concept_error"},{text:"30",type:"calculation_error"},{text:"40",type:"correct"},{text:"44",type:"misinterpretation"}], explanation:"10+10+10+10=40.", solutionSteps:["4 × 10 = 40"], shortcut:"Equal scores → multiply.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_as_q5", topicId:"math2_ch10_adding_scores", text:"Scores in rounds: 15, ?, 25. Total = 55. What is the missing score?", options:[{text:"10",type:"calculation_error"},{text:"15",type:"correct"},{text:"20",type:"calculation_error"},{text:"5",type:"calculation_error"}], explanation:"55−15−25=15.", solutionSteps:["Missing = 55−15−25=15"], shortcut:"Missing = total − others.", difficulty:"medium", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_as_q6", topicId:"math2_ch10_adding_scores", text:"Player A: 32 points. Player B: 7 more than A. Player B's score:", options:[{text:"25",type:"concept_error"},{text:"37",type:"misinterpretation"},{text:"39",type:"correct"},{text:"42",type:"calculation_error"}], explanation:"32+7=39.", solutionSteps:["32+7=39"], shortcut:"7 more = add 7.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_as_q7", topicId:"math2_ch10_adding_scores", text:"A quiz has 10 questions, 5 points each. Perfect score is:", options:[{text:"10",type:"concept_error"},{text:"15",type:"calculation_error"},{text:"50",type:"correct"},{text:"55",type:"calculation_error"}], explanation:"10 × 5 = 50.", solutionSteps:["10 questions × 5 points = 50"], shortcut:"Questions × points each = total.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_as_q8", topicId:"math2_ch10_adding_scores", text:"Score needed: 100. Current score: 73. How many more points?", options:[{text:"37",type:"calculation_error"},{text:"27",type:"correct"},{text:"17",type:"calculation_error"},{text:"167",type:"concept_error"}], explanation:"100−73=27.", solutionSteps:["100−73=27 more points needed"], shortcut:"Missing = target − current.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },

  // math2_ch10_addition_3digit — 8 questions
  { questionId:"math2_ch10_a3d_q1", topicId:"math2_ch10_addition_3digit", text:"125 + 234 = ?", options:[{text:"349",type:"calculation_error"},{text:"359",type:"correct"},{text:"369",type:"calculation_error"},{text:"350",type:"calculation_error"}], explanation:"Ones:5+4=9. Tens:2+3=5. Hundreds:1+2=3. Answer: 359.", solutionSteps:["5+4=9, 2+3=5, 1+2=3","359"], shortcut:"Three columns, right to left.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_a3d_q2", topicId:"math2_ch10_addition_3digit", text:"246 + 138 = ?", options:[{text:"374",type:"calculation_error"},{text:"384",type:"correct"},{text:"394",type:"calculation_error"},{text:"364",type:"calculation_error"}], explanation:"Ones:6+8=14(write 4, carry 1). Tens:4+3+1=8. Hundreds:2+1=3. Answer: 384.", solutionSteps:["6+8=14→4 carry 1","4+3+1=8","2+1=3","384"], shortcut:"Carry from ones to tens.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_a3d_q3", topicId:"math2_ch10_addition_3digit", text:"What is the hundreds digit in 157+241?", options:[{text:"1",type:"concept_error"},{text:"2",type:"calculation_error"},{text:"3",type:"correct"},{text:"4",type:"guessing"}], explanation:"157+241: ones 7+1=8, tens 5+4=9, hundreds 1+2=3. Hundreds digit = 3.", solutionSteps:["1+2=3 (hundreds)"], shortcut:"Add hundreds digits (plus any carry from tens).", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_a3d_q4", topicId:"math2_ch10_addition_3digit", text:"A library has 312 fiction and 175 non-fiction books. Total:", options:[{text:"487",type:"correct"},{text:"497",type:"calculation_error"},{text:"477",type:"calculation_error"},{text:"137",type:"concept_error"}], explanation:"312+175: ones 2+5=7, tens 1+7=8, hundreds 3+1=4. Answer: 487.", solutionSteps:["2+5=7, 1+7=8, 3+1=4","487"], shortcut:"No regrouping here: add straight down.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_a3d_q5", topicId:"math2_ch10_addition_3digit", text:"368 + 145 = ?", options:[{text:"503",type:"calculation_error"},{text:"513",type:"correct"},{text:"523",type:"calculation_error"},{text:"493",type:"calculation_error"}], explanation:"Ones:8+5=13(write 3, carry 1). Tens:6+4+1=11(write 1, carry 1). Hundreds:3+1+1=5. Answer: 513.", solutionSteps:["8+5=13→3 carry 1","6+4+1=11→1 carry 1","3+1+1=5","513"], shortcut:"Carry twice if needed.", difficulty:"medium", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_a3d_q6", topicId:"math2_ch10_addition_3digit", text:"When adding 3-digit numbers, we start from the:", options:[{text:"Hundreds column",type:"concept_error"},{text:"Tens column",type:"concept_error"},{text:"Ones column",type:"correct"},{text:"Any column",type:"misinterpretation"}], explanation:"Always start from the ones (rightmost) column to handle carrying correctly.", solutionSteps:["Right to left: ones → tens → hundreds"], shortcut:"Always right to left.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_a3d_q7", topicId:"math2_ch10_addition_3digit", text:"213 + 456 = ?", options:[{text:"659",type:"calculation_error"},{text:"669",type:"correct"},{text:"679",type:"calculation_error"},{text:"649",type:"calculation_error"}], explanation:"Ones:3+6=9. Tens:1+5=6. Hundreds:2+4=6. Answer: 669.", solutionSteps:["3+6=9, 1+5=6, 2+4=6","669"], shortcut:"No carry needed here.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_a3d_q8", topicId:"math2_ch10_addition_3digit", text:"What is the sum of 400 + 350?", options:[{text:"50",type:"concept_error"},{text:"700",type:"calculation_error"},{text:"750",type:"correct"},{text:"800",type:"calculation_error"}], explanation:"400+350=750.", solutionSteps:["0+0=0 (ones)","0+5=5 (tens)","4+3=7 (hundreds)","750"], shortcut:"Round hundreds + tens.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },

  // math2_ch10_word_problems_add — 8 questions
  { questionId:"math2_ch10_wpa_q1", topicId:"math2_ch10_word_problems_add", text:"There are 24 red balls and 35 blue balls. How many balls in all?", options:[{text:"11",type:"concept_error"},{text:"59",type:"correct"},{text:"49",type:"calculation_error"},{text:"60",type:"calculation_error"}], explanation:"24+35=59.", solutionSteps:["24+35=59"], shortcut:"'In all' = add.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_wpa_q2", topicId:"math2_ch10_word_problems_add", text:"Class has 18 boys and 22 girls. Total students:", options:[{text:"4",type:"concept_error"},{text:"38",type:"calculation_error"},{text:"40",type:"correct"},{text:"42",type:"calculation_error"}], explanation:"18+22=40.", solutionSteps:["18+22=40"], shortcut:"Total = add all groups.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_wpa_q3", topicId:"math2_ch10_word_problems_add", text:"Mango tree has 46 mangoes. Apple tree has 28 apples. Combined total:", options:[{text:"64",type:"calculation_error"},{text:"74",type:"correct"},{text:"84",type:"calculation_error"},{text:"18",type:"concept_error"}], explanation:"46+28=74.", solutionSteps:["6+8=14→4 carry 1","4+2+1=7","74"], shortcut:"Combined = add.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_wpa_q4", topicId:"math2_ch10_word_problems_add", text:"Key word that tells us to add:", options:[{text:"Left",type:"concept_error"},{text:"Fewer",type:"concept_error"},{text:"Altogether",type:"correct"},{text:"Less",type:"misinterpretation"}], explanation:"'Altogether' means the total of all groups combined — this signals addition.", solutionSteps:["Altogether = total = add"], shortcut:"Altogether, in all, total, combined → add.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_wpa_q5", topicId:"math2_ch10_word_problems_add", text:"A train has 56 passengers. At the next stop 27 more get on. Total:", options:[{text:"29",type:"concept_error"},{text:"73",type:"calculation_error"},{text:"83",type:"correct"},{text:"93",type:"calculation_error"}], explanation:"56+27=83.", solutionSteps:["6+7=13→3 carry 1","5+2+1=8","83"], shortcut:"More board = add.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_wpa_q6", topicId:"math2_ch10_word_problems_add", text:"3 shelves have 15, 20, and 25 books. Total books:", options:[{text:"55",type:"calculation_error"},{text:"60",type:"correct"},{text:"65",type:"calculation_error"},{text:"45",type:"calculation_error"}], explanation:"15+20+25=60.", solutionSteps:["15+20=35","35+25=60"], shortcut:"Add all groups: 15+20+25=60.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_wpa_q7", topicId:"math2_ch10_word_problems_add", text:"Yesterday 43 cars passed. Today 38 more passed. Total:", options:[{text:"5",type:"concept_error"},{text:"71",type:"calculation_error"},{text:"81",type:"correct"},{text:"91",type:"calculation_error"}], explanation:"43+38=81.", solutionSteps:["3+8=11→1 carry 1","4+3+1=8","81"], shortcut:"More passed today → add.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_wpa_q8", topicId:"math2_ch10_word_problems_add", text:"What is the label for 59 + 41 = 100 books?", options:[{text:"59 books",type:"partial_logic"},{text:"100 books",type:"correct"},{text:"41 books",type:"partial_logic"},{text:"159 books",type:"concept_error"}], explanation:"The answer to an addition word problem about books should be labeled 'books'.", solutionSteps:["59+41=100","Label: 100 books"], shortcut:"Label your answer with the unit from the problem.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },

  // math2_ch10_mental_math_add — 8 questions
  { questionId:"math2_ch10_mma_q1", topicId:"math2_ch10_mental_math_add", text:"Add mentally: 38 + 9. Round 38 to 40, then:", options:[{text:"49",type:"correct"},{text:"47",type:"calculation_error"},{text:"37",type:"concept_error"},{text:"51",type:"calculation_error"}], explanation:"40+9=49. But 38→40 added 2, so subtract 2: 49−2=47? Wait. Round UP: 38→40 (+2), 40+9=49, subtract the 2 we added: 47. Actually 38+9=47. Correct answer is 47.", solutionSteps:["38+9=47","Check: 38+9=47 ✓"], shortcut:"38+9: think 38+(10−1)=48−1=47.", difficulty:"medium", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_mma_q2", topicId:"math2_ch10_mental_math_add", text:"Make 10 to add: 7 + 6. Split 6 as 3+3: 7+3=10, then +3 =?", options:[{text:"12",type:"calculation_error"},{text:"13",type:"correct"},{text:"14",type:"calculation_error"},{text:"11",type:"calculation_error"}], explanation:"7+3=10, 10+3=13.", solutionSteps:["Split 6=3+3","7+3=10","10+3=13"], shortcut:"Make 10 first, then add remainder.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_mma_q3", topicId:"math2_ch10_mental_math_add", text:"Break apart: 34 + 25. Think 30+20=50, 4+5=9. Total:", options:[{text:"49",type:"calculation_error"},{text:"59",type:"correct"},{text:"69",type:"calculation_error"},{text:"55",type:"calculation_error"}], explanation:"30+20=50, 4+5=9. 50+9=59.", solutionSteps:["Tens: 30+20=50","Ones: 4+5=9","50+9=59"], shortcut:"Break into tens and ones, add separately.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_mma_q4", topicId:"math2_ch10_mental_math_add", text:"Round and adjust: 29+14. Round 29→30. 30+14=44. Adjust:", options:[{text:"Add 1 more → 45",type:"concept_error"},{text:"Subtract 1 → 43",type:"correct"},{text:"No adjustment needed",type:"misinterpretation"},{text:"Add 2 → 46",type:"guessing"}], explanation:"29→30 means we added 1 extra. So subtract 1 from 44: 43.", solutionSteps:["29+1=30 (rounded up 1)","30+14=44","44−1=43 (adjust)"], shortcut:"Round up → subtract the difference after.", difficulty:"medium", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_mma_q5", topicId:"math2_ch10_mental_math_add", text:"What is 45 + 30 mentally?", options:[{text:"65",type:"calculation_error"},{text:"75",type:"correct"},{text:"80",type:"calculation_error"},{text:"55",type:"calculation_error"}], explanation:"Adding 30 increases the tens by 3: 4+3=7. Answer: 75.", solutionSteps:["45: tens=4","Add 3 tens: 4+3=7","75"], shortcut:"Adding multiples of 10: just change the tens digit.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_mma_q6", topicId:"math2_ch10_mental_math_add", text:"Which strategy works best for 49+27?", options:[{text:"Count one by one",type:"concept_error"},{text:"Round 49→50, then add 27, subtract 1",type:"correct"},{text:"Round both to hundreds",type:"misinterpretation"},{text:"No strategy needed",type:"guessing"}], explanation:"49+27: round 49→50, 50+27=77, subtract 1 (added too much): 76.", solutionSteps:["49+1=50","50+27=77","77−1=76"], shortcut:"Near-50 number → round to 50, adjust.", difficulty:"medium", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_mma_q7", topicId:"math2_ch10_mental_math_add", text:"Looking for pairs that sum to 20: 4 + 16 + 7 + 13. Which pairs go first?", options:[{text:"4+7 and 16+13",type:"concept_error"},{text:"4+16 and 7+13",type:"correct"},{text:"Add in order",type:"misinterpretation"},{text:"Any order",type:"partial_logic"}], explanation:"4+16=20 and 7+13=20. Then 20+20=40.", solutionSteps:["4+16=20","7+13=20","20+20=40"], shortcut:"Look for complementary pairs (sum to friendly numbers).", difficulty:"medium", subject:"Math", grade:2, chapter:10 },
  { questionId:"math2_ch10_mma_q8", topicId:"math2_ch10_mental_math_add", text:"Mentally: 60 + 35 = ?", options:[{text:"85",type:"calculation_error"},{text:"90",type:"calculation_error"},{text:"95",type:"correct"},{text:"100",type:"calculation_error"}], explanation:"60+35=95.", solutionSteps:["60+30=90","90+5=95"], shortcut:"Add tens part first, then ones.", difficulty:"easy", subject:"Math", grade:2, chapter:10 },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  let inserted = 0;
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
    console.log(`  ✓ ${q.questionId}`);
    inserted++;
  }
  console.log(`\nSeeded ${inserted} Class 2 Math v2 questions (Ch9–Ch10).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
