/**
 * Seed: CBSE Class 10 English — Workbook Grammar Questions (72 MCQs)
 * Topics: eng_wb_grammar1 … eng_wb_grammar9  (8 questions each)
 * Safe to re-run — skips duplicates on { questionText, subject }
 * Usage: node config/seedEnglishQuestionsD.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const Q = [
  // ── eng_wb_grammar1 — Sequencing & Narrative Writing ──────────────────────
  {
    topic: "eng_wb_grammar1", topicId: "eng_wb_grammar1",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct sequence marker to begin the second step in a process: 'First, wash the vegetables. _____, chop them into small pieces.'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Next", type: "correct", logicTag: "" },
      { text: "However", type: "concept_error", logicTag: "contrast_not_sequence" },
      { text: "Therefore", type: "concept_error", logicTag: "conclusion_not_sequence" },
      { text: "Although", type: "concept_error", logicTag: "concession_not_sequence" },
    ],
    solutionSteps: ["Sequence markers show order: first, next, then, after that, finally.", "'However' = contrast. 'Therefore' = conclusion. 'Although' = concession.", "'Next' correctly signals the second step in a sequence."],
    shortcut: "Sequence markers (process writing): First → Next/Then → After that → Finally. 'However/Therefore/Although' are not sequence markers.",
  },
  {
    topic: "eng_wb_grammar1", topicId: "eng_wb_grammar1",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In narrative writing, which tense is most commonly used to describe past events in sequence?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Simple Past", type: "correct", logicTag: "" },
      { text: "Present Perfect", type: "concept_error", logicTag: "wrong_tense_for_narrative" },
      { text: "Future Perfect", type: "concept_error", logicTag: "wrong_tense" },
      { text: "Past Perfect Continuous", type: "concept_error", logicTag: "too_complex_for_narrative" },
    ],
    solutionSteps: ["Narratives about past events use Simple Past for the main sequence.", "Past Perfect is used for events BEFORE the main past events.", "Present Perfect is for actions with present relevance.", "Simple Past = 'He walked, she spoke, they decided' — standard narrative."],
    shortcut: "Narrative tense = Simple Past for the main events. Past Perfect for 'before that.' Not Present Perfect.",
  },
  {
    topic: "eng_wb_grammar1", topicId: "eng_wb_grammar1",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Select the sentence where sequence markers are used correctly:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "First, she made the dough. Then, she kneaded it for ten minutes. Finally, she baked it.", type: "correct", logicTag: "" },
      { text: "Finally, she made the dough. First, she baked it. Then, she kneaded it.", type: "concept_error", logicTag: "wrong_order" },
      { text: "However, she made the dough. Although she kneaded it. Therefore, she baked it.", type: "concept_error", logicTag: "wrong_connectors" },
      { text: "She made the dough first then she kneaded it finally she baked it.", type: "concept_error", logicTag: "punctuation_error" },
    ],
    solutionSteps: ["Option A uses First → Then → Finally in logical order.", "Option B reverses the order (Finally before First).", "Option C uses the wrong type of connectors (contrast/conclusion).", "Option D lacks proper punctuation and comma placement."],
    shortcut: "Sequence = logical order + correct markers + proper punctuation. First + commas + Then + Finally.",
  },
  {
    topic: "eng_wb_grammar1", topicId: "eng_wb_grammar1",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which feature is essential in a good paragraph in narrative writing?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A clear topic sentence, supporting details, and a concluding sentence", type: "correct", logicTag: "" },
      { text: "Exactly five sentences, neither more nor less", type: "concept_error", logicTag: "wrong_rule" },
      { text: "Beginning every sentence with a capital letter and ending with a full stop", type: "concept_error", logicTag: "basic_punctuation_not_structure" },
      { text: "Using as many descriptive adjectives as possible", type: "concept_error", logicTag: "wrong_priority" },
    ],
    solutionSteps: ["A good paragraph has: topic sentence (main idea), supporting sentences (evidence/details), concluding sentence.", "The number of sentences varies; five is not a fixed rule.", "Descriptive language helps but is not the defining feature.", "Structure is primary."],
    shortcut: "Paragraph = topic sentence + supporting details + conclusion. Not a fixed number of sentences. Structure over quantity.",
  },
  {
    topic: "eng_wb_grammar1", topicId: "eng_wb_grammar1",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Fill in the blank with the correct sequence marker: 'After mixing the ingredients, _____ pour the batter into the tin.'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "then", type: "correct", logicTag: "" },
      { text: "despite", type: "concept_error", logicTag: "contrast_not_sequence" },
      { text: "unless", type: "concept_error", logicTag: "condition_not_sequence" },
      { text: "besides", type: "concept_error", logicTag: "addition_not_sequence" },
    ],
    solutionSteps: ["'After mixing… then pour' = correct temporal sequence.", "'Despite' = contrast/concession.", "'Unless' = condition.", "'Besides' = addition.", "'Then' correctly follows 'after' in a sequence."],
    shortcut: "'After… then' = sequence. 'Despite/unless/besides' are not sequence markers for process writing.",
  },
  {
    topic: "eng_wb_grammar1", topicId: "eng_wb_grammar1",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence shows the use of 'as soon as' to express immediate sequence?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "As soon as he arrived, she left.", type: "correct", logicTag: "" },
      { text: "He arrived as soon as after she left.", type: "concept_error", logicTag: "grammatically_wrong" },
      { text: "She left, as soon he arrived.", type: "concept_error", logicTag: "missing_as" },
      { text: "As soon as she will leave, he arrives.", type: "concept_error", logicTag: "wrong_tense_combination" },
    ],
    solutionSteps: ["'As soon as + subject + verb' introduces an immediate sequence.", "'As soon as he arrived, she left' = correct structure: both clauses in Simple Past.", "Option B has 'as soon as after' — incorrect.", "Option D mixes future and present incorrectly."],
    shortcut: "'As soon as + Simple Past, Simple Past' = correct. Don't use 'will/would' in the 'as soon as' clause.",
  },
  {
    topic: "eng_wb_grammar1", topicId: "eng_wb_grammar1",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does a 'concluding sentence' do in a paragraph?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "It restates the main idea in different words or summarises the paragraph's key point", type: "correct", logicTag: "" },
      { text: "It introduces a completely new idea to end on a surprise", type: "concept_error", logicTag: "new_idea_in_conclusion_wrong" },
      { text: "It always ends with a question to engage the reader", type: "concept_error", logicTag: "not_a_rule" },
      { text: "It gives the most important piece of evidence in the paragraph", type: "concept_error", logicTag: "wrong_position_evidence_goes_in_body" },
    ],
    solutionSteps: ["Concluding sentence = wraps up the paragraph's idea.", "It restates or summarises — does NOT introduce new information.", "It may reflect on significance but stays on topic.", "Evidence/details belong in supporting sentences."],
    shortcut: "Concluding sentence = summarise/restate. No new ideas in conclusion. Evidence goes in supporting sentences.",
  },
  {
    topic: "eng_wb_grammar1", topicId: "eng_wb_grammar1",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Identify the correct use of 'meanwhile' as a sequence marker:",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "She was cooking dinner; meanwhile, he was setting the table.", type: "correct", logicTag: "" },
      { text: "She cooked dinner meanwhile before he arrived.", type: "concept_error", logicTag: "wrong_usage" },
      { text: "Meanwhile she cooked dinner after he set the table.", type: "concept_error", logicTag: "wrong_meaning" },
      { text: "She cooked, therefore, meanwhile he set the table.", type: "concept_error", logicTag: "redundant_markers" },
    ],
    solutionSteps: ["'Meanwhile' = at the same time (two simultaneous actions).", "Option A: two simultaneous actions — cooking + setting table. Correct.", "Option B: 'before' + 'meanwhile' contradict each other.", "Option D: 'therefore' + 'meanwhile' is redundant and contradictory."],
    shortcut: "'Meanwhile' = at the same time (simultaneous actions). Not before/after. Use semicolon or new sentence.",
  },

  // ── eng_wb_grammar2 — Verb Forms & Tenses ────────────────────────────────
  {
    topic: "eng_wb_grammar2", topicId: "eng_wb_grammar2",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct verb form: 'She _____ (study) for three hours before the test started.'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "had been studying", type: "correct", logicTag: "" },
      { text: "was studying", type: "concept_error", logicTag: "past_continuous_no_completion" },
      { text: "has studied", type: "concept_error", logicTag: "wrong_tense" },
      { text: "studies", type: "concept_error", logicTag: "present_tense_wrong" },
    ],
    solutionSteps: ["An action that was in progress before another past action uses Past Perfect Continuous.", "'Had been studying' = she was studying continuously before the test started.", "'Was studying' lacks the 'before' relationship clearly.", "'Has studied' = Present Perfect, wrong here."],
    shortcut: "Ongoing action BEFORE a past event = Past Perfect Continuous (had been + V-ing). Duration + completion before past event.",
  },
  {
    topic: "eng_wb_grammar2", topicId: "eng_wb_grammar2",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence uses the Present Perfect correctly?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "I have visited Paris twice.", type: "correct", logicTag: "" },
      { text: "I have visited Paris last year.", type: "concept_error", logicTag: "specific_past_time_needs_simple_past" },
      { text: "I visited Paris since 2019.", type: "concept_error", logicTag: "since_needs_present_perfect" },
      { text: "I am visiting Paris many times.", type: "concept_error", logicTag: "present_continuous_wrong" },
    ],
    solutionSteps: ["Present Perfect cannot be used with specific past time (yesterday, last year).", "'I have visited' = experience up to now, no specific time. Correct.", "'Last year' = specific past time → use Simple Past.", "'Since' must be used with Present Perfect, not Simple Past."],
    shortcut: "Present Perfect: no specific past time (never with last year/yesterday/in 2010). 'Since' + Pres. Perfect. Experience = have visited.",
  },
  {
    topic: "eng_wb_grammar2", topicId: "eng_wb_grammar2",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Fill in: 'By the time she arrived, he _____ (finish) the work.'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "had finished", type: "correct", logicTag: "" },
      { text: "finished", type: "concept_error", logicTag: "simple_past_not_before_another_past" },
      { text: "has finished", type: "concept_error", logicTag: "present_perfect_wrong" },
      { text: "was finishing", type: "concept_error", logicTag: "past_continuous_wrong" },
    ],
    solutionSteps: ["'By the time + past simple' → main clause uses Past Perfect.", "The work was finished BEFORE she arrived → earlier past action = Past Perfect.", "'Had finished' = the earlier of the two past actions."],
    shortcut: "'By the time + past' → use Past Perfect (had + V3). Earlier past action. Not Simple Past or Present Perfect.",
  },
  {
    topic: "eng_wb_grammar2", topicId: "eng_wb_grammar2",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct form: 'Water _____ at 100°C.'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "boils", type: "correct", logicTag: "" },
      { text: "is boiling", type: "concept_error", logicTag: "present_continuous_not_for_facts" },
      { text: "boiled", type: "concept_error", logicTag: "past_tense_wrong" },
      { text: "will boil", type: "concept_error", logicTag: "future_wrong_for_facts" },
    ],
    solutionSteps: ["Universal truths and scientific facts use Simple Present.", "'Water boils at 100°C' = scientific fact, always true.", "Present Continuous is for actions happening NOW.", "Past and Future are wrong for permanent truths."],
    shortcut: "Scientific fact/universal truth = Simple Present (boils, rises, melts). Not 'is boiling' or 'boiled.'",
  },
  {
    topic: "eng_wb_grammar2", topicId: "eng_wb_grammar2",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Identify the correct use of the Past Continuous tense:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "When the phone rang, she was reading a book.", type: "correct", logicTag: "" },
      { text: "When the phone rang, she read a book.", type: "concept_error", logicTag: "simple_past_but_background_needs_continuous" },
      { text: "While the phone was ringing, she has read a book.", type: "concept_error", logicTag: "wrong_tense_combination" },
      { text: "She was reading a book yesterday at 5 PM was interrupted.", type: "concept_error", logicTag: "grammatically_wrong" },
    ],
    solutionSteps: ["Past Continuous = background/ongoing action interrupted by a Simple Past action.", "'Was reading' (ongoing) + 'rang' (interruption) = correct.", "Option B: 'she read' makes both actions equal — loses the background sense.", "Option C: 'has read' (Present Perfect) is wrong in a past context."],
    shortcut: "Past Continuous (was + V-ing) = ongoing background action. Simple Past = sudden interruption. Pattern: 'was V-ing when X happened.'",
  },
  {
    topic: "eng_wb_grammar2", topicId: "eng_wb_grammar2",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence correctly uses 'used to'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He used to play cricket every evening when he was young.", type: "correct", logicTag: "" },
      { text: "He used to plays cricket every evening.", type: "concept_error", logicTag: "wrong_verb_form_after_used_to" },
      { text: "He is used to play cricket every evening.", type: "concept_error", logicTag: "is_used_to_needs_gerund" },
      { text: "He was used to play cricket every evening.", type: "concept_error", logicTag: "was_used_to_needs_gerund" },
    ],
    solutionSteps: ["'Used to + bare infinitive' = past habit or state no longer true.", "'Used to play' is correct.", "'Used to plays' = wrong (plays is 3rd person singular, but after 'used to' use bare infinitive).", "'Is/was used to' = 'be accustomed to' — takes gerund (-ing), not infinitive."],
    shortcut: "'Used to + bare infinitive' = past habit. 'Be used to + gerund' = accustomed to. Never 'used to plays' or 'used to playing' for past habit.",
  },
  {
    topic: "eng_wb_grammar2", topicId: "eng_wb_grammar2",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct sentence using Future Perfect:",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "By next Monday, she will have completed the project.", type: "correct", logicTag: "" },
      { text: "By next Monday, she will complete the project.", type: "concept_error", logicTag: "simple_future_no_completion_by" },
      { text: "By next Monday, she has completed the project.", type: "concept_error", logicTag: "present_perfect_wrong_time" },
      { text: "By next Monday, she will be completing the project.", type: "concept_error", logicTag: "future_continuous_not_completion" },
    ],
    solutionSteps: ["Future Perfect = will have + V3 = action completed BEFORE a future point.", "'By next Monday' signals a future deadline → use Future Perfect.", "'Will complete' = simple future (doesn't emphasise completion).", "'Will be completing' = future continuous (in progress, not completed)."],
    shortcut: "'By + future time' → Future Perfect (will have + V3). Shows completion before a future deadline.",
  },
  {
    topic: "eng_wb_grammar2", topicId: "eng_wb_grammar2",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which option correctly uses the simple present for a scheduled future event?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "The train leaves at 9 PM tomorrow.", type: "correct", logicTag: "" },
      { text: "The train will leave at 9 PM tomorrow.", type: "concept_error", logicTag: "correct_but_not_schedule_usage" },
      { text: "The train is leaving at 9 PM tomorrow.", type: "concept_error", logicTag: "personal_plan_not_timetable" },
      { text: "The train has left at 9 PM tomorrow.", type: "concept_error", logicTag: "present_perfect_wrong" },
    ],
    solutionSteps: ["Simple Present can express fixed schedules/timetables.", "'The train leaves at 9 PM' = fixed timetable (scheduled departure).", "'Will leave' is acceptable but less precise for timetables.", "'Is leaving' = personal arrangement, not official schedule.", "'Has left' = wrong tense for future."],
    shortcut: "Timetables/schedules = Simple Present (the train leaves, the match starts). 'Is leaving' = personal plan. Both OK but distinction matters.",
  },

  // ── eng_wb_grammar3 — Relative Clauses ───────────────────────────────────
  {
    topic: "eng_wb_grammar3", topicId: "eng_wb_grammar3",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct relative pronoun: 'The book _____ I borrowed was very interesting.'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "that / which", type: "correct", logicTag: "" },
      { text: "who", type: "concept_error", logicTag: "who_is_for_people" },
      { text: "whom", type: "concept_error", logicTag: "whom_is_for_people_object" },
      { text: "whose", type: "concept_error", logicTag: "whose_shows_possession" },
    ],
    solutionSteps: ["'That' and 'which' are used for things.", "'Who/whom' = for people.", "The book = thing → use 'that' or 'which'.", "'That' is more common in restrictive clauses."],
    shortcut: "'That/which' = things. 'Who/whom' = people. 'Whose' = possession (of people or things). Book → that/which.",
  },
  {
    topic: "eng_wb_grammar3", topicId: "eng_wb_grammar3",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Identify the defining (restrictive) relative clause: which sentence's relative clause is essential to the meaning?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The man who stole the wallet was arrested.", type: "correct", logicTag: "" },
      { text: "My father, who is a doctor, is very kind.", type: "concept_error", logicTag: "non_defining_clause" },
      { text: "The Taj Mahal, which is in Agra, is beautiful.", type: "concept_error", logicTag: "non_defining_clause" },
      { text: "My sister, who lives in London, called yesterday.", type: "concept_error", logicTag: "non_defining_clause" },
    ],
    solutionSteps: ["A defining clause identifies which person/thing. Removing it changes the meaning.", "'The man who stole the wallet' — 'who stole the wallet' tells us WHICH man. Essential.", "Options B, C, D have non-defining clauses (in commas) — add extra info, not essential to identification."],
    shortcut: "Defining (no commas) = essential, identifies the noun. Non-defining (with commas) = extra info, can be removed.",
  },
  {
    topic: "eng_wb_grammar3", topicId: "eng_wb_grammar3",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct relative pronoun: 'This is the girl _____ parents I met yesterday.'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "whose", type: "correct", logicTag: "" },
      { text: "who", type: "concept_error", logicTag: "who_is_subject_not_possessive" },
      { text: "which", type: "concept_error", logicTag: "which_for_things_not_people" },
      { text: "whom", type: "concept_error", logicTag: "whom_object_not_possessive" },
    ],
    solutionSteps: ["'Whose' = possessive relative pronoun (belonging to).", "'The girl whose parents' = the girl's parents.", "'Who' would need 'who's parents' — wrong.", "'Whom' is an object pronoun, not possessive."],
    shortcut: "'Whose' = possessive (belonging to). 'The girl whose X' = the girl's X. Not 'who' (subject) or 'whom' (object).",
  },
  {
    topic: "eng_wb_grammar3", topicId: "eng_wb_grammar3",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence correctly uses 'whom'?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "The teacher whom we respect has retired.", type: "correct", logicTag: "" },
      { text: "The teacher who we respect has retired.", type: "concept_error", logicTag: "who_used_as_object_informal" },
      { text: "The teacher whom respects us has retired.", type: "concept_error", logicTag: "whom_used_as_subject_wrong" },
      { text: "The teacher which we respect has retired.", type: "concept_error", logicTag: "which_for_people_wrong" },
    ],
    solutionSteps: ["'Whom' = object form. 'We respect WHOM (him)' — 'we' is subject, teacher is object.", "'Whom we respect' = object of 'respect'. Correct.", "'Who we respect' is common informally but 'whom' is formally correct.", "'Whom respects us' = wrong: subject would need 'who.'"],
    shortcut: "Test: replace relative pronoun with him/her/them. 'We respect him' → object → use 'whom'. 'He respects us' → subject → use 'who'.",
  },
  {
    topic: "eng_wb_grammar3", topicId: "eng_wb_grammar3",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Combine these sentences using a relative clause: 'The house was on fire. The house was built in 1920.'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The house, which was built in 1920, was on fire.", type: "correct", logicTag: "" },
      { text: "The house who was built in 1920 was on fire.", type: "concept_error", logicTag: "who_for_things_wrong" },
      { text: "The house was built in 1920 was on fire.", type: "concept_error", logicTag: "missing_relative_pronoun" },
      { text: "The house which was on fire built in 1920.", type: "concept_error", logicTag: "wrong_structure" },
    ],
    solutionSteps: ["'Which' is used for things in non-defining clauses.", "Commas are needed as both facts are known (non-defining).", "'Who' is for people, not houses.", "The relative pronoun must come right after the noun it modifies."],
    shortcut: "House = thing → use 'which'. Both facts known → non-defining → use commas. 'The house, which was built in 1920, was on fire.'",
  },
  {
    topic: "eng_wb_grammar3", topicId: "eng_wb_grammar3",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence is grammatically correct?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The students who pass the exam will receive certificates.", type: "correct", logicTag: "" },
      { text: "The students which pass the exam will receive certificates.", type: "concept_error", logicTag: "which_for_people_wrong" },
      { text: "The students whom pass the exam will receive certificates.", type: "concept_error", logicTag: "whom_as_subject_wrong" },
      { text: "The students whose pass the exam will receive certificates.", type: "concept_error", logicTag: "whose_shows_possession_not_subject" },
    ],
    solutionSteps: ["Students = people → use 'who/whom'.", "'Who pass' = 'who' is subject of 'pass'. Correct.", "'Which' = for things.", "'Whom' = object pronoun (cannot be subject of 'pass').", "'Whose' = possessive (not needed here)."],
    shortcut: "People + subject role → 'who'. People + object role → 'whom'. Things → 'which/that'. Possession → 'whose'.",
  },
  {
    topic: "eng_wb_grammar3", topicId: "eng_wb_grammar3",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Identify where the relative clause goes wrong: 'She met the man. He helped her last year. She met the man who helped her last year.'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "The combined sentence is correct.", type: "correct", logicTag: "" },
      { text: "It should be 'whom helped her last year'", type: "concept_error", logicTag: "whom_wrong_as_subject" },
      { text: "It should be 'which helped her last year'", type: "concept_error", logicTag: "which_for_people_wrong" },
      { text: "It should be 'whose helped her last year'", type: "concept_error", logicTag: "whose_shows_possession" },
    ],
    solutionSteps: ["'Who helped her' = 'who' as subject of 'helped'. Correct.", "'Whom helped' = wrong — 'whom' is an object pronoun; 'helped' needs a subject.", "'Which' = for things, not people.", "The original combined sentence is entirely correct."],
    shortcut: "Combined sentence is CORRECT. 'Who' = subject (he helped → who helped). 'Whom' would be wrong as subject pronoun here.",
  },
  {
    topic: "eng_wb_grammar3", topicId: "eng_wb_grammar3",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence uses 'where' as a relative pronoun correctly?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "This is the city where I was born.", type: "correct", logicTag: "" },
      { text: "This is the city which I was born.", type: "concept_error", logicTag: "which_needs_preposition_in" },
      { text: "This is the city who I was born.", type: "concept_error", logicTag: "who_for_people_not_places" },
      { text: "This is the city that I was born where.", type: "concept_error", logicTag: "double_relative_wrong" },
    ],
    solutionSteps: ["'Where' as relative pronoun = for places.", "'The city where I was born' = 'in which I was born.' Equivalent.", "'Which' needs a preposition: 'the city in which I was born.'", "'Who' is for people, not places."],
    shortcut: "'Where' = place relative pronoun. 'The city where' = 'the city in which'. 'Who' for people, 'where' for places.",
  },

  // ── eng_wb_grammar4 — Active and Passive Voice ────────────────────────────
  {
    topic: "eng_wb_grammar4", topicId: "eng_wb_grammar4",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Convert to passive voice: 'She wrote the letter.'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "The letter was written by her.", type: "correct", logicTag: "" },
      { text: "The letter is written by her.", type: "concept_error", logicTag: "present_tense_wrong" },
      { text: "The letter was wrote by her.", type: "concept_error", logicTag: "wrong_past_participle" },
      { text: "The letter has been written by her.", type: "concept_error", logicTag: "present_perfect_passive_wrong" },
    ],
    solutionSteps: ["Active: She (subject) wrote (verb) the letter (object).", "Passive: The letter (new subject) + was written (passive = was + V3) + by her.", "'Wrote' is past tense, V3 = written (not wrote).", "'Was written' = Simple Past Passive."],
    shortcut: "Simple Past Active → Simple Past Passive: was/were + V3. 'Wrote' → 'was written'. Object becomes subject.",
  },
  {
    topic: "eng_wb_grammar4", topicId: "eng_wb_grammar4",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Convert to active voice: 'The cake was eaten by the children.'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "The children ate the cake.", type: "correct", logicTag: "" },
      { text: "The children have eaten the cake.", type: "concept_error", logicTag: "present_perfect_wrong" },
      { text: "The children eat the cake.", type: "concept_error", logicTag: "present_tense_wrong" },
      { text: "The cake ate the children.", type: "concept_error", logicTag: "wrong_subject_object_reversal" },
    ],
    solutionSteps: ["Passive: 'was eaten' = Simple Past Passive.", "Active: 'by the children' → children = subject.", "Past Passive 'was eaten' → Active Simple Past 'ate'.", "'The children ate the cake.' is correct."],
    shortcut: "Passive to Active: 'by X' → X becomes subject. 'was eaten by children' → 'children ate'. Match the tense.",
  },
  {
    topic: "eng_wb_grammar4", topicId: "eng_wb_grammar4",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct passive form: 'They are building a new bridge.'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A new bridge is being built (by them).", type: "correct", logicTag: "" },
      { text: "A new bridge is built by them.", type: "concept_error", logicTag: "simple_present_passive_wrong" },
      { text: "A new bridge was being built by them.", type: "concept_error", logicTag: "past_continuous_passive_wrong" },
      { text: "A new bridge has been built by them.", type: "concept_error", logicTag: "present_perfect_passive_wrong" },
    ],
    solutionSteps: ["Active: 'They are building' = Present Continuous.", "Passive of Present Continuous = is/am/are + being + V3.", "'A new bridge is being built' = correct Present Continuous Passive.", "'Is built' = Simple Present Passive (wrong tense)."],
    shortcut: "Present Continuous Passive = is/are/am + being + V3. 'Are building' → 'is being built'. Not 'is built' (that's Simple Present).",
  },
  {
    topic: "eng_wb_grammar4", topicId: "eng_wb_grammar4",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence is in the correct passive form for: 'Someone must repair this computer.'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "This computer must be repaired.", type: "correct", logicTag: "" },
      { text: "This computer must be repairing.", type: "concept_error", logicTag: "gerund_not_past_participle" },
      { text: "This computer must have been repaired.", type: "concept_error", logicTag: "modal_perfect_passive_wrong" },
      { text: "This computer is must be repaired.", type: "concept_error", logicTag: "double_verb_wrong" },
    ],
    solutionSteps: ["Modal passive: modal + be + V3.", "'Must be repaired' = modal (must) + be + V3 (repaired). Correct.", "'Must be repairing' = wrong (gerund after modal passive).", "'Must have been repaired' = modal perfect passive (past speculation, not instruction)."],
    shortcut: "Modal passive: modal + be + V3. 'Must repair' → 'must be repaired'. Not 'must be repairing' (gerund wrong).",
  },
  {
    topic: "eng_wb_grammar4", topicId: "eng_wb_grammar4",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "When is passive voice preferred over active voice in writing?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "When the doer is unknown, unimportant, or when the focus is on the action/receiver", type: "correct", logicTag: "" },
      { text: "Always in formal writing — active voice should never be used in formal contexts", type: "concept_error", logicTag: "wrong_rule" },
      { text: "When you want to make the sentence longer and more impressive", type: "concept_error", logicTag: "wrong_reason" },
      { text: "Only in science writing and never in literature", type: "concept_error", logicTag: "wrong_restriction" },
    ],
    solutionSteps: ["Passive is preferred: doer unknown ('The wallet was stolen'), focus on receiver/action ('The medicine was administered'), formal impersonal style.", "Active voice is generally preferred in modern writing for clarity.", "Neither is 'always' required — context determines the choice."],
    shortcut: "Use passive: doer unknown/unimportant; focus on action/object; formal/scientific writing. Active = clearer, preferred otherwise.",
  },
  {
    topic: "eng_wb_grammar4", topicId: "eng_wb_grammar4",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Convert to passive: 'Has anyone told you the news?'",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Have you been told the news?", type: "correct", logicTag: "" },
      { text: "Has the news been told to you?", type: "concept_error", logicTag: "acceptable_alternative_but_changes_focus" },
      { text: "Were you told the news?", type: "concept_error", logicTag: "wrong_tense_simple_past" },
      { text: "You have been told the news.", type: "concept_error", logicTag: "loses_interrogative" },
    ],
    solutionSteps: ["Active: 'Has anyone told you the news?' = Present Perfect question.", "Two objects: you (indirect object), the news (direct object).", "Indirect object 'you' becomes subject of passive: 'Have you been told the news?'", "The question structure must be preserved."],
    shortcut: "Present Perfect Question Passive: Have/Has + subject + been + V3? 'Has anyone told you' → 'Have you been told.' Keep question form.",
  },
  {
    topic: "eng_wb_grammar4", topicId: "eng_wb_grammar4",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the sentence where passive voice is used appropriately:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The results will be announced tomorrow.", type: "correct", logicTag: "" },
      { text: "The ball was kicked by John into the goal.", type: "concept_error", logicTag: "active_more_natural_here" },
      { text: "She was written the letter.", type: "concept_error", logicTag: "grammatically_wrong" },
      { text: "By the students, the book was read.", type: "concept_error", logicTag: "awkward_agent_placement" },
    ],
    solutionSteps: ["'Results will be announced' — doer unknown/unimportant. Passive appropriate.", "'The ball was kicked by John' — active ('John kicked the ball') is clearer.", "'She was written the letter' — grammatically wrong.", "'By the students, the book was read' — awkward; place 'by' at end."],
    shortcut: "Good passive: 'The results will be announced' (doer irrelevant). Bad passive: when doer is known and important.",
  },
  {
    topic: "eng_wb_grammar4", topicId: "eng_wb_grammar4",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Identify the passive construction in the sentence: 'The letter had been sent before she arrived.'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Past Perfect Passive — had been + V3", type: "correct", logicTag: "" },
      { text: "Present Perfect Passive — has been + V3", type: "concept_error", logicTag: "wrong_tense" },
      { text: "Past Continuous Passive — was being + V3", type: "concept_error", logicTag: "wrong_form" },
      { text: "Future Passive — will be + V3", type: "concept_error", logicTag: "wrong_tense" },
    ],
    solutionSteps: ["'Had been sent' = had + been + V3 = Past Perfect Passive.", "It indicates the letter was sent BEFORE she arrived (earlier past).", "Past Perfect Passive = had been + V3."],
    shortcut: "Past Perfect Passive = had been + V3. 'Had been sent' = action completed before another past event. Passive of Past Perfect.",
  },

  // ── eng_wb_grammar5 — Conditionals ────────────────────────────────────────
  {
    topic: "eng_wb_grammar5", topicId: "eng_wb_grammar5",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct zero conditional sentence:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "If you heat ice, it melts.", type: "correct", logicTag: "" },
      { text: "If you heated ice, it would melt.", type: "concept_error", logicTag: "second_conditional" },
      { text: "If you had heated ice, it would have melted.", type: "concept_error", logicTag: "third_conditional" },
      { text: "If you heat ice, it will melt.", type: "concept_error", logicTag: "first_conditional_but_not_zero" },
    ],
    solutionSteps: ["Zero conditional: If + Simple Present, Simple Present. For universal/scientific truths.", "'If you heat ice, it melts' = always true. Zero conditional.", "First conditional uses 'will': 'If you heat… it will melt' (possible future).", "Zero = facts/truths; First = real future possibility."],
    shortcut: "Zero: If + present, present (facts/truths). First: If + present, will. Second: If + past, would. Third: If + past perfect, would have.",
  },
  {
    topic: "eng_wb_grammar5", topicId: "eng_wb_grammar5",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence is a correct First Conditional?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "If she studies hard, she will pass the exam.", type: "correct", logicTag: "" },
      { text: "If she studied hard, she would pass the exam.", type: "concept_error", logicTag: "second_conditional" },
      { text: "If she studies hard, she would pass the exam.", type: "concept_error", logicTag: "mixed_conditional" },
      { text: "If she will study hard, she passes the exam.", type: "concept_error", logicTag: "will_in_if_clause_wrong" },
    ],
    solutionSteps: ["First Conditional: If + Simple Present, will + infinitive.", "'If she studies hard, she will pass' = real/possible future condition. Correct.", "Second: If + Simple Past, would (hypothetical present).", "Never use 'will' in the if-clause (unless it's a polite request)."],
    shortcut: "First: If + present, will + base. Real future possibility. Never 'will' in the 'if' clause for conditions.",
  },
  {
    topic: "eng_wb_grammar5", topicId: "eng_wb_grammar5",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Identify the Second Conditional: which sentence talks about an unlikely or imaginary present situation?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "If I had wings, I would fly to the moon.", type: "correct", logicTag: "" },
      { text: "If I have time, I will call you.", type: "concept_error", logicTag: "first_conditional" },
      { text: "If I had studied, I would have passed.", type: "concept_error", logicTag: "third_conditional" },
      { text: "If water freezes, it becomes ice.", type: "concept_error", logicTag: "zero_conditional" },
    ],
    solutionSteps: ["Second Conditional: If + Simple Past, would + infinitive.", "'If I had wings' = impossible/imaginary (I don't have wings).", "Used for imaginary or very unlikely present/future situations.", "'Would have passed' = Third Conditional (past regret)."],
    shortcut: "Second: If + past, would (imaginary/hypothetical present). Not real. 'If I were rich, I would travel' = classic example.",
  },
  {
    topic: "eng_wb_grammar5", topicId: "eng_wb_grammar5",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correct Third Conditional: a past situation that didn't happen:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "If she had arrived earlier, she would have met him.", type: "correct", logicTag: "" },
      { text: "If she arrived earlier, she would meet him.", type: "concept_error", logicTag: "second_conditional" },
      { text: "If she arrives earlier, she will meet him.", type: "concept_error", logicTag: "first_conditional" },
      { text: "If she had arrived earlier, she will meet him.", type: "concept_error", logicTag: "mixed_wrong" },
    ],
    solutionSteps: ["Third Conditional: If + Past Perfect, would have + V3.", "Refers to imaginary past situations (she didn't arrive earlier — real past).", "'Would have met' = consequence that didn't happen.", "Used for regret, criticism of past actions."],
    shortcut: "Third: If + past perfect, would have + V3. PAST regret/impossibility. 'If I had studied, I would have passed.'",
  },
  {
    topic: "eng_wb_grammar5", topicId: "eng_wb_grammar5",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the sentence that correctly uses 'unless' as a conditional:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Unless you hurry, you will miss the bus.", type: "correct", logicTag: "" },
      { text: "Unless you don't hurry, you will miss the bus.", type: "concept_error", logicTag: "double_negative" },
      { text: "Unless you hurried, you would miss the bus.", type: "concept_error", logicTag: "second_conditional_wrong_with_unless" },
      { text: "Unless you will hurry, you miss the bus.", type: "concept_error", logicTag: "will_in_unless_clause_wrong" },
    ],
    solutionSteps: ["'Unless' = 'if not'. 'Unless you hurry' = 'If you don't hurry.'", "Option A: Unless + present → will + base. Correct (First Conditional equivalent).", "Option B: 'Unless you don't hurry' = double negative (if you don't not hurry = if you hurry). Wrong.", "No 'will' in the unless-clause."],
    shortcut: "'Unless' = 'if not.' Don't add 'not' with 'unless' (double negative). 'Unless + present, will' = correct.",
  },
  {
    topic: "eng_wb_grammar5", topicId: "eng_wb_grammar5",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Complete the sentence: 'If I were the Prime Minister, I _____ (improve) public transport.'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "would improve", type: "correct", logicTag: "" },
      { text: "will improve", type: "concept_error", logicTag: "first_conditional_wrong" },
      { text: "would have improved", type: "concept_error", logicTag: "third_conditional_wrong" },
      { text: "improved", type: "concept_error", logicTag: "no_modal_wrong" },
    ],
    solutionSteps: ["'If I were' = Second Conditional (hypothetical present).", "Result clause = would + base verb.", "'Would improve' is correct.", "'Were' (not 'was') is used in hypothetical second conditionals for all subjects."],
    shortcut: "Second Conditional: 'If I were' (hypothetical) → 'would + base'. Note: 'were' (not 'was') in formal second conditional.",
  },
  {
    topic: "eng_wb_grammar5", topicId: "eng_wb_grammar5",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence correctly expresses a condition with 'provided that'?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "You can borrow the car provided that you return it by evening.", type: "correct", logicTag: "" },
      { text: "You can borrow the car provided that you will return it by evening.", type: "concept_error", logicTag: "will_in_conditional_clause_wrong" },
      { text: "You can borrow the car providing you returned it by evening.", type: "concept_error", logicTag: "past_tense_inconsistent" },
      { text: "You can borrow the car provided that would you return it by evening.", type: "concept_error", logicTag: "would_wrong_placement" },
    ],
    solutionSteps: ["'Provided that' = conditional = 'on the condition that.' Used with Simple Present (not will).", "'Provided that you return it' = conditional clause, present tense.", "Like 'if', 'provided that' does not take 'will' in the clause.", "Other conditionals: 'as long as', 'on condition that' — same rule."],
    shortcut: "'Provided that/as long as' = formal 'if'. Use Simple Present in the condition. No 'will/would' in the clause.",
  },
  {
    topic: "eng_wb_grammar5", topicId: "eng_wb_grammar5",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the mixed conditional: past condition affecting the present:",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "If he had studied medicine, he would be a doctor now.", type: "correct", logicTag: "" },
      { text: "If he studied medicine, he would be a doctor now.", type: "concept_error", logicTag: "second_conditional_not_mixed" },
      { text: "If he had studied medicine, he would have been a doctor.", type: "concept_error", logicTag: "third_conditional_past_result" },
      { text: "If he studies medicine, he will be a doctor.", type: "concept_error", logicTag: "first_conditional" },
    ],
    solutionSteps: ["Mixed conditional: If + Past Perfect (past condition), would + base (present result).", "'If he had studied medicine' = past condition (he didn't study in the past).", "'He would be a doctor now' = present consequence.", "Third conditional would say 'would have been' — past result."],
    shortcut: "Mixed: If + past perfect (past condition), would + base (present result). 'If he had studied… he would be X now.'",
  },

  // ── eng_wb_grammar6 — Reported Speech ────────────────────────────────────
  {
    topic: "eng_wb_grammar6", topicId: "eng_wb_grammar6",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Change to reported speech: 'She said, \"I am tired.\"'",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She said that she was tired.", type: "correct", logicTag: "" },
      { text: "She said that she is tired.", type: "concept_error", logicTag: "tense_not_backshifted" },
      { text: "She said that I am tired.", type: "concept_error", logicTag: "pronoun_not_changed" },
      { text: "She told that she was tired.", type: "concept_error", logicTag: "told_needs_object" },
    ],
    solutionSteps: ["Tense backshift: 'am' (present) → 'was' (past) in reported speech.", "Pronoun change: 'I' → 'she'.", "'Said' does not need an object; 'told' needs one ('told me/him...').", "Correct: 'She said that she was tired.'"],
    shortcut: "Reported speech: 'said' (no object). Backshift: am→was, is→was, will→would, can→could. Change pronouns: I→she/he.",
  },
  {
    topic: "eng_wb_grammar6", topicId: "eng_wb_grammar6",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Change to reported speech: 'He said, \"Can you help me?\"'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He asked if I could help him.", type: "correct", logicTag: "" },
      { text: "He asked that could I help him.", type: "concept_error", logicTag: "wrong_word_order_in_reported" },
      { text: "He said that can you help him.", type: "concept_error", logicTag: "no_tense_backshift_wrong_conjunction" },
      { text: "He asked whether I can help him.", type: "concept_error", logicTag: "can_not_backshifted" },
    ],
    solutionSteps: ["Questions in reported speech use 'asked if/whether' + subject + verb (no question order).", "'Can' → 'could' (backshift).", "'You' → 'I' (perspective change).", "No 'that' with indirect questions — use 'if/whether'."],
    shortcut: "Reported question: asked if/whether + subject + verb (statement order). 'Can' → 'could'. No question marks.",
  },
  {
    topic: "eng_wb_grammar6", topicId: "eng_wb_grammar6",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Change the command to reported speech: 'The teacher said to the students, \"Open your books.\"'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The teacher told the students to open their books.", type: "correct", logicTag: "" },
      { text: "The teacher said the students to open their books.", type: "concept_error", logicTag: "said_not_for_commands" },
      { text: "The teacher told the students that open their books.", type: "concept_error", logicTag: "that_wrong_for_commands" },
      { text: "The teacher asked the students open their books.", type: "concept_error", logicTag: "asked_needs_if_for_questions" },
    ],
    solutionSteps: ["Commands/instructions use: told/asked + object + to + infinitive.", "'Open your books' → 'to open their books'.", "'Said to' → 'told'. 'Told' requires an object.", "No 'that' with commands in reported speech."],
    shortcut: "Reported command: told + object + to + infinitive. 'Open' → 'to open'. 'Their' replaces 'your'. No 'that'.",
  },
  {
    topic: "eng_wb_grammar6", topicId: "eng_wb_grammar6",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the correctly reported sentence for: 'He said, \"I will come tomorrow.\"'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He said that he would come the next day.", type: "correct", logicTag: "" },
      { text: "He said that he will come tomorrow.", type: "concept_error", logicTag: "no_tense_backshift_and_no_time_change" },
      { text: "He said that he would come tomorrow.", type: "concept_error", logicTag: "tomorrow_not_changed" },
      { text: "He told that he would come the next day.", type: "concept_error", logicTag: "told_needs_object" },
    ],
    solutionSteps: ["'Will' → 'would' (tense backshift).", "'Tomorrow' → 'the next day' (time expression change).", "'I' → 'he' (pronoun change).", "'Said' not 'told' — 'told' needs an object like 'told me.'"],
    shortcut: "Time changes: tomorrow→next day, today→that day, yesterday→the day before, here→there. Will→would.",
  },
  {
    topic: "eng_wb_grammar6", topicId: "eng_wb_grammar6",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which sentence correctly reports: 'She asked, \"Where do you live?\"'",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "She asked where I lived.", type: "correct", logicTag: "" },
      { text: "She asked where do I live.", type: "concept_error", logicTag: "question_word_order_in_reported" },
      { text: "She asked that where I lived.", type: "concept_error", logicTag: "that_not_used_with_wh_questions" },
      { text: "She asked where I will live.", type: "concept_error", logicTag: "no_tense_backshift" },
    ],
    solutionSteps: ["Wh-question reported: asked + wh-word + subject + verb (statement order).", "'Where do you live?' → 'where I lived' (do removed, you→I, live→lived).", "No 'that' with wh-questions in reported speech.", "'Will' is not present here, so no will→would change needed."],
    shortcut: "Wh-question reported: asked + wh-word + subject + past verb. No 'do/does/did'. No 'that'. No question mark.",
  },
  {
    topic: "eng_wb_grammar6", topicId: "eng_wb_grammar6",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Identify the correct backshift rule: which tense does Simple Present change to in reported speech?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Simple Past", type: "correct", logicTag: "" },
      { text: "Present Perfect", type: "concept_error", logicTag: "wrong_backshift" },
      { text: "Past Perfect", type: "concept_error", logicTag: "that_is_for_past_simple" },
      { text: "Past Continuous", type: "concept_error", logicTag: "wrong_backshift" },
    ],
    solutionSteps: ["Backshift rule: Simple Present → Simple Past.", "Present Continuous → Past Continuous.", "Simple Past → Past Perfect.", "Present Perfect → Past Perfect."],
    shortcut: "Backshift table: am/is/are→was/were; will→would; can→could; may→might; must→had to; Simple Past→Past Perfect.",
  },
  {
    topic: "eng_wb_grammar6", topicId: "eng_wb_grammar6",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "No tense backshift is needed when reporting speech in which situation?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "When the reporting verb is in the Present tense OR the statement is a universal truth", type: "correct", logicTag: "" },
      { text: "When the original speaker used the Simple Past", type: "concept_error", logicTag: "past_always_backshifts" },
      { text: "When the reporter and the speaker are the same person", type: "concept_error", logicTag: "not_a_rule" },
      { text: "When the reported speech is very long", type: "concept_error", logicTag: "not_a_rule" },
    ],
    solutionSteps: ["No backshift: present reporting verb ('He says that he is tired') or universal truths ('She said that the sun rises in the east').", "Universal truths stay in Simple Present even in reported speech.", "Past reporting verb usually requires backshift."],
    shortcut: "No backshift: (1) reporting verb is present tense; (2) universal/scientific truth. 'Sun rises in east' stays present.",
  },
  {
    topic: "eng_wb_grammar6", topicId: "eng_wb_grammar6",
    subtopic: "Grammar", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Change to direct speech: 'He told me that he had finished his homework.'",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He said to me, \"I have finished my homework.\"", type: "correct", logicTag: "" },
      { text: "He said to me, \"I had finished my homework.\"", type: "concept_error", logicTag: "no_tense_forward_shift" },
      { text: "He said to me, \"He has finished his homework.\"", type: "concept_error", logicTag: "wrong_pronoun" },
      { text: "He told me, \"I had finished my homework.\"", type: "concept_error", logicTag: "no_forward_shift" },
    ],
    solutionSteps: ["Reported→Direct: reverse the backshift. 'Had finished' → 'have finished'.", "Pronouns: 'he' → 'I'; 'his' → 'my'.", "'Told me' → 'said to me' + direct speech in quotes.", "Past Perfect in reported → Present Perfect in direct speech."],
    shortcut: "Reported to Direct: reverse backshift (had finished→have finished). he→I, his→my. Add quotation marks and 'said to me.'",
  },

  // ── eng_wb_grammar7 — Article Writing ────────────────────────────────────
  {
    topic: "eng_wb_grammar7", topicId: "eng_wb_grammar7",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which element is NOT part of the standard CBSE format for a newspaper article?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A postscript (P.S.) summarising the key points", type: "correct", logicTag: "" },
      { text: "A headline", type: "concept_error", logicTag: "headline_is_required" },
      { text: "By-line (writer's name)", type: "concept_error", logicTag: "byline_is_required" },
      { text: "An introduction paragraph that states the main issue", type: "concept_error", logicTag: "intro_is_required" },
    ],
    solutionSteps: ["CBSE article format: Headline, By-line (by + Name), Introduction, Body (2-3 paragraphs), Conclusion.", "A postscript (P.S.) is used in letters, not articles.", "Headline, by-line, intro, body, conclusion = required elements."],
    shortcut: "Article format: Headline → By-line → Intro → Body → Conclusion. No P.S. (that's for letters).",
  },
  {
    topic: "eng_wb_grammar7", topicId: "eng_wb_grammar7",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which type of language is appropriate for a formal newspaper article?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Formal, objective, impersonal — third-person perspective", type: "correct", logicTag: "" },
      { text: "Casual, conversational, with slang and colloquial expressions", type: "concept_error", logicTag: "wrong_register" },
      { text: "Poetic language with rhyme and metre", type: "concept_error", logicTag: "wrong_genre" },
      { text: "First-person emotional narrative about personal feelings", type: "concept_error", logicTag: "diary_style_wrong" },
    ],
    solutionSteps: ["Newspaper articles = formal, objective, third-person ('it was reported', 'officials stated').", "First person (I, my) is avoided in formal articles.", "Slang/colloquial language is inappropriate for formal writing.", "Poetic language = poetry, not articles."],
    shortcut: "Article language = formal, third-person, objective. Not casual, poetic, or first-person (except opinion pieces).",
  },
  {
    topic: "eng_wb_grammar7", topicId: "eng_wb_grammar7",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the purpose of the 'headline' in a newspaper article?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "To capture attention and summarise the main point of the article in a few words", type: "correct", logicTag: "" },
      { text: "To provide a detailed summary of all the facts in the article", type: "concept_error", logicTag: "too_detailed_for_headline" },
      { text: "To identify the author and publication date", type: "concept_error", logicTag: "byline_function" },
      { text: "To give the background and history of the topic covered", type: "concept_error", logicTag: "intro_function" },
    ],
    solutionSteps: ["Headline = eye-catching title. Short (usually 5-10 words), summarises the main idea.", "By-line = author's name. Introduction = background context.", "Headline should be specific and engaging, not vague."],
    shortcut: "Headline = attention-grabbing summary. Short, punchy, specific. Not the by-line (name) or intro (background).",
  },
  {
    topic: "eng_wb_grammar7", topicId: "eng_wb_grammar7",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In article writing, what should the concluding paragraph do?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Summarise the key points and/or offer a recommendation or call to action", type: "correct", logicTag: "" },
      { text: "Introduce new statistics that weren't mentioned before", type: "concept_error", logicTag: "new_info_in_conclusion_wrong" },
      { text: "Repeat the headline word for word", type: "concept_error", logicTag: "wrong_repetition" },
      { text: "Provide a personal letter to the reader", type: "concept_error", logicTag: "wrong_format" },
    ],
    solutionSteps: ["Conclusion = wrap up, summarise, recommend/suggest, or call to action.", "No new facts in conclusion.", "It should feel like a satisfying close to the argument.", "A recommendation ('The government must…') or reflection is appropriate."],
    shortcut: "Conclusion: summarise key points + recommend/call to action. No new info. Satisfying close to the article.",
  },
  {
    topic: "eng_wb_grammar7", topicId: "eng_wb_grammar7",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the difference between a 'report' and an 'article' in CBSE writing tasks?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A report presents factual information about an event; an article can include opinion, analysis, and recommendations", type: "correct", logicTag: "" },
      { text: "A report is always longer than an article", type: "concept_error", logicTag: "length_not_defining" },
      { text: "An article must be published in a newspaper; a report can be unpublished", type: "concept_error", logicTag: "publishing_not_the_difference" },
      { text: "Both are identical in structure and purpose", type: "concept_error", logicTag: "wrong_equivalence" },
    ],
    solutionSteps: ["Report = factual, objective account of an event/incident. No personal opinion.", "Article = can include facts + analysis + opinion + recommendations.", "Both have a heading but differ in tone and purpose.", "CBSE tests both formats separately."],
    shortcut: "Report = factual only (no opinion). Article = fact + opinion + recommendations. Both have headings but differ in tone.",
  },
  {
    topic: "eng_wb_grammar7", topicId: "eng_wb_grammar7",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is a 'by-line' in a newspaper article?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A line giving the writer's name, usually written as 'By [Name]'", type: "correct", logicTag: "" },
      { text: "The main headline of the article", type: "concept_error", logicTag: "wrong_element" },
      { text: "A sub-heading within the body of the article", type: "concept_error", logicTag: "wrong_element" },
      { text: "The publication date and newspaper name", type: "concept_error", logicTag: "dateline_not_byline" },
    ],
    solutionSteps: ["By-line = 'By [Author's Name]' placed below the headline.", "It credits the author of the article.", "Sub-headings divide sections within the body.", "Dateline = date and place of publication."],
    shortcut: "By-line = 'By [Name]' under the headline. Gives author credit. Not the headline, not the date.",
  },
  {
    topic: "eng_wb_grammar7", topicId: "eng_wb_grammar7",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which of the following would make the best headline for an article about rising pollution in Delhi?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Delhi Chokes: AQI Hits Critical Levels as Winter Sets In", type: "correct", logicTag: "" },
      { text: "This article is about the increasing pollution levels in the city of Delhi during the winter season", type: "concept_error", logicTag: "too_long_for_headline" },
      { text: "Pollution", type: "concept_error", logicTag: "too_vague_one_word" },
      { text: "I Think Delhi's Air is Very Bad These Days", type: "concept_error", logicTag: "informal_and_first_person" },
    ],
    solutionSteps: ["Good headline: specific, engaging, short, uses strong verbs/nouns.", "'Delhi Chokes' = metaphor + specific. 'AQI' = relevant detail. Punchy.", "Option B = too long (a sentence, not a headline).", "Option C = too vague. Option D = informal, first-person."],
    shortcut: "Best headline: specific + punchy + active verb + no unnecessary words. Use strong metaphors/verbs to hook the reader.",
  },
  {
    topic: "eng_wb_grammar7", topicId: "eng_wb_grammar7",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "An article for a school magazine differs from a newspaper article in what way?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "A school magazine article can be slightly informal and may use first-person; the audience is school peers", type: "correct", logicTag: "" },
      { text: "A school magazine article must use more difficult vocabulary than a newspaper article", type: "concept_error", logicTag: "wrong_requirement" },
      { text: "A school magazine article needs no headline or by-line", type: "concept_error", logicTag: "format_still_needed" },
      { text: "School magazine articles are always about school events only", type: "concept_error", logicTag: "too_restrictive" },
    ],
    solutionSteps: ["Audience affects tone: school magazine = peer audience → slightly informal, first-person possible.", "Both still need headline, by-line, intro, body, conclusion.", "School magazines can cover any topic relevant to students.", "The key difference is register and audience, not format elements."],
    shortcut: "School magazine: peer audience → slightly informal register, first-person OK. Newspaper: formal, third-person, wider audience.",
  },

  // ── eng_wb_grammar8 — Report Writing ──────────────────────────────────────
  {
    topic: "eng_wb_grammar8", topicId: "eng_wb_grammar8",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which tense is predominantly used when writing a report about an event that has already occurred?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Simple Past", type: "correct", logicTag: "" },
      { text: "Simple Present", type: "concept_error", logicTag: "wrong_tense_for_past_events" },
      { text: "Future Perfect", type: "concept_error", logicTag: "wrong_tense" },
      { text: "Present Continuous", type: "concept_error", logicTag: "wrong_tense" },
    ],
    solutionSteps: ["Reports about completed events use Simple Past.", "'The event was held', 'students participated', 'the chief guest spoke' — all Simple Past.", "Passive voice is also common: 'The award was presented.'"],
    shortcut: "Event report = Simple Past (active) + Passive. 'The event was held…', 'The chief guest spoke…'",
  },
  {
    topic: "eng_wb_grammar8", topicId: "eng_wb_grammar8",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the correct CBSE format for a report heading?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Title in capitals, then 'Reported by:' (name) and date", type: "correct", logicTag: "" },
      { text: "Only the name of the reporter, no title needed", type: "concept_error", logicTag: "incomplete_format" },
      { text: "Dear Sir/Madam, followed by the report content", type: "concept_error", logicTag: "letter_format_wrong" },
      { text: "To: [recipient], From: [sender], Subject: [topic]", type: "concept_error", logicTag: "memo_format_not_report" },
    ],
    solutionSteps: ["CBSE Report format: Title (in capitals), By/Reported by: Name, Date.", "It does not start with 'Dear Sir/Madam' (that's a letter).", "'To/From/Subject' = memo format.", "Reports have a title, not a salutation."],
    shortcut: "Report format: TITLE (caps) → Reported by: Name → Date → Opening → Body → Closing. No 'Dear Sir.'",
  },
  {
    topic: "eng_wb_grammar8", topicId: "eng_wb_grammar8",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which information is usually included in the opening paragraph of a school event report?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Name of the event, date, venue, and purpose/occasion", type: "correct", logicTag: "" },
      { text: "Names of all students who attended the event", type: "concept_error", logicTag: "too_detailed_for_opening" },
      { text: "The personal opinion of the reporter about the event", type: "concept_error", logicTag: "opinion_in_report_wrong" },
      { text: "Instructions for attending future events", type: "concept_error", logicTag: "wrong_content" },
    ],
    solutionSteps: ["Opening paragraph = 5 Ws: Who, What, When, Where, Why.", "Name + date + venue + purpose. Then body describes what happened.", "No opinion in the opening paragraph (reports are factual).", "Attendee lists are excessive for standard school reports."],
    shortcut: "Opening = 5Ws (who/what/when/where/why). Name, date, venue, purpose. No opinion. Body = what happened.",
  },
  {
    topic: "eng_wb_grammar8", topicId: "eng_wb_grammar8",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the sentence written in the appropriate report writing style:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The Annual Day was celebrated on 15th December at the school auditorium.", type: "correct", logicTag: "" },
      { text: "I think the Annual Day was amazing and everyone had so much fun!", type: "concept_error", logicTag: "informal_opinion_wrong" },
      { text: "The Annual Day will be celebrated on 15th December.", type: "concept_error", logicTag: "future_tense_wrong_for_past_event" },
      { text: "We must celebrate Annual Day every year as it is very important.", type: "concept_error", logicTag: "recommendation_in_description_wrong" },
    ],
    solutionSteps: ["Report style: formal, third-person, Simple Past for completed event.", "Option A = factual, impersonal, past tense. Correct.", "Option B = informal, first-person opinion.", "Option C = future tense (event has already happened).", "Option D = recommendation/opinion, not description."],
    shortcut: "Report style: formal + third-person + Simple Past + factual. No 'I', no opinions, no future tense for past events.",
  },
  {
    topic: "eng_wb_grammar8", topicId: "eng_wb_grammar8",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What should the concluding line of a school event report typically state?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The event concluded with a vote of thanks and/or the national anthem", type: "correct", logicTag: "" },
      { text: "A personal recommendation for future events", type: "concept_error", logicTag: "opinion_not_for_factual_report" },
      { text: "A list of all prizes distributed", type: "concept_error", logicTag: "too_detailed_for_conclusion" },
      { text: "The reporter's signature and designation", type: "concept_error", logicTag: "signature_at_end_not_last_sentence" },
    ],
    solutionSteps: ["Standard school event reports end with: 'The event ended with a vote of thanks' or 'The function concluded with the national anthem.'", "This signals the formal close of the event.", "Opinions and recommendations are for articles, not factual reports.", "The reporter's name goes in the by-line, not in the concluding sentence."],
    shortcut: "Report ending = 'The event concluded with a vote of thanks.' Standard formal close. Not opinion or signature.",
  },
  {
    topic: "eng_wb_grammar8", topicId: "eng_wb_grammar8",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which of the following should NOT appear in a factual report?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Personal opinions and emotional reactions of the reporter", type: "correct", logicTag: "" },
      { text: "The date and venue of the event", type: "concept_error", logicTag: "required_in_report" },
      { text: "Names of participants and chief guests", type: "concept_error", logicTag: "relevant_facts" },
      { text: "A brief description of the activities conducted", type: "concept_error", logicTag: "required_in_report" },
    ],
    solutionSteps: ["Reports are factual and objective.", "Date, venue, participants, activities = factual content. Included.", "Personal opinions ('I felt overwhelmed') = subjective. NOT in factual reports.", "Opinion belongs in articles or reviews, not event reports."],
    shortcut: "Reports = no personal opinions. Date + venue + participants + activities = yes. 'I felt/I think' = no.",
  },
  {
    topic: "eng_wb_grammar8", topicId: "eng_wb_grammar8",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "A report about a debate competition should mention all EXCEPT:",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "The personal childhood memories of the judge", type: "correct", logicTag: "" },
      { text: "The topic of the debate", type: "concept_error", logicTag: "relevant_fact" },
      { text: "The names of winning participants", type: "concept_error", logicTag: "relevant_fact" },
      { text: "The date and venue of the competition", type: "concept_error", logicTag: "relevant_fact" },
    ],
    solutionSteps: ["A competition report should cover: topic, date, venue, participants, results, judges.", "Personal childhood memories of a judge = irrelevant, subjective, anecdotal.", "Even if a judge shared such memories in a speech, they don't belong in a factual report.", "Reports include: what, when, where, who, outcome."],
    shortcut: "Report includes: relevant facts (topic, venue, date, results). Excludes: irrelevant personal anecdotes, opinions, emotions.",
  },
  {
    topic: "eng_wb_grammar8", topicId: "eng_wb_grammar8",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Choose the best opening sentence for a report on a 'Science Exhibition':",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A Science Exhibition was held at Greenfield Public School on 20th January 2025 to showcase the scientific innovations of students.", type: "correct", logicTag: "" },
      { text: "Science is very important and we all must appreciate it more in our daily lives.", type: "concept_error", logicTag: "general_statement_not_event_reporting" },
      { text: "I went to the science exhibition last week and it was great!", type: "concept_error", logicTag: "informal_first_person" },
      { text: "The science exhibition will be held next month at our school.", type: "concept_error", logicTag: "future_tense_wrong" },
    ],
    solutionSteps: ["Best opening: states event name, date, venue, purpose.", "Third-person, formal, Simple Past.", "Option B = general statement (not event-specific).", "Option C = informal, first-person.", "Option D = future tense (wrong for past event)."],
    shortcut: "Report opening: 'A [event] was held at [venue] on [date] to [purpose].' Formal, factual, past tense, third-person.",
  },

  // ── eng_wb_grammar9 — Speech Writing ────────────────────────────────────
  {
    topic: "eng_wb_grammar9", topicId: "eng_wb_grammar9",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which is the correct way to begin a formal speech in CBSE format?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Respected Principal, teachers, and dear friends/fellow students — Good morning!", type: "correct", logicTag: "" },
      { text: "Hi everyone! Let me just jump right in.", type: "concept_error", logicTag: "too_casual" },
      { text: "Dear Sir/Madam, I am writing to you about...", type: "concept_error", logicTag: "letter_format_not_speech" },
      { text: "Topic: Environmental Pollution. By: Ravi.", type: "concept_error", logicTag: "report_format_not_speech" },
    ],
    solutionSteps: ["Formal speech opening: salutation + greeting + self-introduction (optional) + topic statement.", "'Respected Principal, teachers, and dear students, Good morning!' = standard CBSE format.", "Informal greetings ('Hi everyone') = wrong register.", "Letter/report formats are different from speech format."],
    shortcut: "Speech opening: Respected Principal + teachers + dear students + Good morning. Then introduce yourself and your topic.",
  },
  {
    topic: "eng_wb_grammar9", topicId: "eng_wb_grammar9",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is an appropriate way to conclude a formal speech?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Thank the audience and end with 'Thank you' or 'Jai Hind' as appropriate", type: "correct", logicTag: "" },
      { text: "Sign your name and add the date", type: "concept_error", logicTag: "letter_format_wrong" },
      { text: "Simply stop speaking without any formal closing", type: "concept_error", logicTag: "abrupt_unprofessional" },
      { text: "Start a new topic to keep the audience engaged", type: "concept_error", logicTag: "wrong_approach" },
    ],
    solutionSteps: ["Speech conclusion: summarise main points + call to action (if appropriate) + thank you.", "'Thank you' or 'Jai Hind' for patriotic speeches are standard closings.", "A speech does not have a signature (unlike a letter).", "The conclusion should feel complete, not trailing off."],
    shortcut: "Speech ending: summarise → call to action → 'Thank you.' For patriotic = 'Jai Hind.' Not a signature or abrupt stop.",
  },
  {
    topic: "eng_wb_grammar9", topicId: "eng_wb_grammar9",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "A speech on 'Save Water' should primarily use which type of language?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Persuasive, emotive, and action-oriented language to motivate the audience", type: "correct", logicTag: "" },
      { text: "Technical scientific language with precise measurements and chemical terms", type: "concept_error", logicTag: "wrong_register_for_persuasion" },
      { text: "Narrative language telling a long story about a character who saved water", type: "concept_error", logicTag: "wrong_mode" },
      { text: "Purely factual language with no emotional appeal", type: "concept_error", logicTag: "ineffective_for_speech" },
    ],
    solutionSteps: ["Speeches aim to persuade, inform, or inspire.", "For 'Save Water': use facts + emotional appeal + call to action.", "Repetition, rhetorical questions, and direct address ('You and I must act now') are effective.", "Technical jargon alienates a general audience."],
    shortcut: "Speech language = persuasive + emotive + action-oriented. Use rhetorical questions, repetition, direct address.",
  },
  {
    topic: "eng_wb_grammar9", topicId: "eng_wb_grammar9",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is a 'rhetorical question' and why is it used in speeches?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A question asked for effect — not expecting a literal answer — to engage the audience and make them think", type: "correct", logicTag: "" },
      { text: "A question that requires a very detailed answer from each audience member", type: "concept_error", logicTag: "wrong_definition" },
      { text: "A question about grammar or rhetoric that only scholars can answer", type: "concept_error", logicTag: "literal_misread" },
      { text: "A question the speaker asks himself and then answers aloud", type: "concept_error", logicTag: "that_is_hypophora_not_rhetorical" },
    ],
    solutionSteps: ["Rhetorical question = asked for impact, not a literal answer.", "Example: 'How long will we ignore climate change?' — no one is expected to answer.", "Creates engagement, makes audience reflect, adds drama to speech.", "Distinguishable from hypophora (question then answered by speaker)."],
    shortcut: "Rhetorical question = no answer expected. Purpose: engage audience, create emphasis. 'How long will we wait?' = rhetorical.",
  },
  {
    topic: "eng_wb_grammar9", topicId: "eng_wb_grammar9",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which of the following is an example of effective use of repetition in a speech?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "'We can change, we must change, we will change.'", type: "correct", logicTag: "" },
      { text: "Using the same sentence three times without changing any words", type: "concept_error", logicTag: "monotonous_repetition" },
      { text: "Repeating every point twice to help slow learners follow along", type: "concept_error", logicTag: "patronising_not_rhetorical" },
      { text: "Starting every paragraph with 'In conclusion' to signal summaries", type: "concept_error", logicTag: "wrong_usage" },
    ],
    solutionSteps: ["Rhetorical repetition (anaphora) = repeating a word/phrase at the start of consecutive clauses.", "'We can… we must… we will' = escalating emphasis.", "Effective repetition creates rhythm and emotional impact.", "Mere duplication without variation = boring."],
    shortcut: "Anaphora = repetition at start of clauses for emphasis. 'We can, we must, we will' = escalating, rhythmic, powerful.",
  },
  {
    topic: "eng_wb_grammar9", topicId: "eng_wb_grammar9",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In CBSE speech writing, what is the function of the 'body' of a speech?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "To present the main arguments, evidence, examples, and analysis related to the topic", type: "correct", logicTag: "" },
      { text: "To greet the audience and introduce the speaker's name", type: "concept_error", logicTag: "introduction_function" },
      { text: "To thank the audience and summarise the speech", type: "concept_error", logicTag: "conclusion_function" },
      { text: "To list all the books and sources the speaker consulted", type: "concept_error", logicTag: "bibliography_wrong" },
    ],
    solutionSteps: ["Body = main content. Arguments, facts, examples, analysis, call to action (if argument).", "Introduction = greet + introduce self + state topic.", "Conclusion = summarise + thank you.", "Bibliographies are for essays/research, not speeches."],
    shortcut: "Speech = Introduction (greet, introduce) + Body (arguments, facts, examples) + Conclusion (summarise, thank). No bibliography.",
  },
  {
    topic: "eng_wb_grammar9", topicId: "eng_wb_grammar9",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Which feature distinguishes speech writing from essay writing?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "A speech directly addresses the audience ('you', rhetorical questions, direct appeals), while an essay is impersonal and formal", type: "correct", logicTag: "" },
      { text: "An essay must always be longer than a speech", type: "concept_error", logicTag: "length_not_defining" },
      { text: "A speech never uses facts or statistics; it is purely emotional", type: "concept_error", logicTag: "wrong_characterisation" },
      { text: "Essays can have opinions, but speeches must always be objective", type: "concept_error", logicTag: "reversed" },
    ],
    solutionSteps: ["Key difference: speech = addresses audience directly ('you', salutation, rhetorical questions).", "Essay = impersonal, third-person, academic.", "Both can have facts and opinions, but tone differs.", "Speech = persuasive + personal address. Essay = analytical + impersonal."],
    shortcut: "Speech vs Essay: Speech = direct address ('you', 'we'), rhetorical questions, emotional. Essay = impersonal, analytical.",
  },
  {
    topic: "eng_wb_grammar9", topicId: "eng_wb_grammar9",
    subtopic: "Writing", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How should a speaker use 'direct address' effectively in a speech?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "By saying 'you' to include and involve the audience, making them feel personally responsible or connected to the issue", type: "correct", logicTag: "" },
      { text: "By calling individual audience members by name throughout the speech", type: "concept_error", logicTag: "impractical_and_awkward" },
      { text: "By using 'we' to distance the speaker from the audience", type: "concept_error", logicTag: "we_includes_speaker_not_distance" },
      { text: "By avoiding 'you' as it is considered rude in formal speeches", type: "concept_error", logicTag: "wrong_convention" },
    ],
    solutionSteps: ["'You' in speeches = powerful inclusive device.", "'You, the youth of this nation, must act now!' = direct, personal, motivating.", "It creates a sense of individual responsibility in each listener.", "'We' = inclusive (speaker + audience together); 'you' = addresses audience specifically."],
    shortcut: "'You' in speech = direct appeal to audience. Creates personal responsibility. 'We' = collective. Both effective, different effect.",
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI, { serverSelectionTimeoutMS: 10_000 });
  console.log("MongoDB connected");

  let created = 0, skipped = 0;
  for (const q of Q) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    created++;
  }
  console.log(`\n✅ English QuestionsD (Workbook Grammar): ${created} created, ${skipped} skipped (${Q.length} total)`);
  await mongoose.disconnect();
}

run().catch((err) => { console.error(err); process.exit(1); });
