/**
 * seedMath1QuestionsV2D.js
 * Class 1 Mathematics v2 — Chapters 7–8 (64 questions)
 * Measurement and Numbers 21-50
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";

dotenv.config();

const questions = [

  // ── Ch7 S1: Comparing Lengths (math1_ch7_comparing_lengths) ──────────────────
  { questionId:"math1_ch7_comparing_lengths_q1", topicId:"math1_ch7_comparing_lengths", text:"A pencil is longer than a crayon. Which is SHORTER?", options:[{text:"Pencil",type:"concept_error",logicTag:"longer"},{text:"They are the same",type:"concept_error",logicTag:"stated differently"},{text:"Crayon",type:"correct",logicTag:"shorter than pencil"},{text:"Cannot tell",type:"guessing",logicTag:"can tell"}], explanation:"The pencil is longer, so the crayon must be shorter.", solutionSteps:["Pencil > crayon","So crayon < pencil = shorter"], shortcut:"Longer ↔ shorter: the other one.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_lengths_q2", topicId:"math1_ch7_comparing_lengths", text:"To compare lengths correctly, we must ___ one end before looking.", options:[{text:"Paint",type:"concept_error",logicTag:"irrelevant"},{text:"Align / line up",type:"correct",logicTag:"align starting ends"},{text:"Weigh",type:"concept_error",logicTag:"weight not length"},{text:"Cut",type:"concept_error",logicTag:"wrong method"}], explanation:"We align one end of both objects before comparing — otherwise the comparison is unfair.", solutionSteps:["Put both objects on a flat surface","Line up the starting end","Then look at the other end"], shortcut:"Align one end first — always!", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_lengths_q3", topicId:"math1_ch7_comparing_lengths", text:"A table is TALLER than a chair. Which is closer to the floor?", options:[{text:"Table",type:"concept_error",logicTag:"taller, further from floor"},{text:"Chair",type:"correct",logicTag:"shorter = closer to floor"},{text:"Both the same",type:"concept_error",logicTag:"stated as different"},{text:"Cannot compare",type:"guessing",logicTag:"can compare"}], explanation:"The chair is shorter, so it is closer to the floor.", solutionSteps:["Table taller, chair shorter","Shorter = lower down = closer to floor"], shortcut:"Shorter = closer to ground.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_lengths_q4", topicId:"math1_ch7_comparing_lengths", text:"Which word describes something longer from left to right?", options:[{text:"Taller",type:"concept_error",logicTag:"up-down"},{text:"Heavier",type:"concept_error",logicTag:"weight"},{text:"Wider",type:"correct",logicTag:"wide = left-right"},{text:"Shorter",type:"concept_error",logicTag:"less length"}], explanation:"'Wider' or 'longer' describes the left-to-right measurement.", solutionSteps:["Length = left to right distance","Wider = more left-to-right extent"], shortcut:"Wide = side to side.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_lengths_q5", topicId:"math1_ch7_comparing_lengths", text:"A giraffe is TALLER than a dog. Which word describes the dog's height?", options:[{text:"Taller",type:"concept_error",logicTag:"dog is shorter"},{text:"Shorter",type:"correct",logicTag:"dog < giraffe"},{text:"Same",type:"concept_error",logicTag:"stated as different"},{text:"Wider",type:"concept_error",logicTag:"wrong dimension"}], explanation:"If the giraffe is taller, the dog is shorter.", solutionSteps:["Giraffe tall, dog = shorter","Shorter = less height"], shortcut:"Not as tall = shorter.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_lengths_q6", topicId:"math1_ch7_comparing_lengths", text:"You line up a pen and a ruler. The ruler sticks out further. Which is LONGER?", options:[{text:"Pen",type:"concept_error",logicTag:"pen shorter"},{text:"Ruler",type:"correct",logicTag:"sticks out further = longer"},{text:"Both equal",type:"concept_error",logicTag:"stated as different"},{text:"Cannot tell",type:"guessing",logicTag:"can tell"}], explanation:"The one that sticks out further (when one end is aligned) is longer.", solutionSteps:["Aligned one end","Ruler extends further → ruler is longer"], shortcut:"Extends further = longer.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_lengths_q7", topicId:"math1_ch7_comparing_lengths", text:"Three ropes: red (longest), blue, green (shortest). Which is in the MIDDLE?", options:[{text:"Red",type:"concept_error",logicTag:"longest"},{text:"Green",type:"concept_error",logicTag:"shortest"},{text:"Blue",type:"correct",logicTag:"between longest and shortest"},{text:"Cannot tell",type:"guessing",logicTag:"can tell from order"}], explanation:"Red is longest, green is shortest, blue is in the middle.", solutionSteps:["Red > blue > green","Middle = blue"], shortcut:"Middle = neither longest nor shortest.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_lengths_q8", topicId:"math1_ch7_comparing_lengths", text:"We compare lengths using words like ___.", options:[{text:"Hot and cold",type:"concept_error",logicTag:"temperature words"},{text:"Heavy and light",type:"concept_error",logicTag:"weight words"},{text:"Longer and shorter",type:"correct",logicTag:"length comparison words"},{text:"Full and empty",type:"concept_error",logicTag:"capacity words"}], explanation:"Length is compared using: longer, shorter, taller, shorter, wider, narrower.", solutionSteps:["Length words: longer/shorter, taller/shorter","Not weight, temperature or capacity"], shortcut:"Longer/Shorter = length words.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },

  // ── Ch7 S2: Non-Standard Units (math1_ch7_non_standard_units) ────────────────
  { questionId:"math1_ch7_non_standard_units_q1", topicId:"math1_ch7_non_standard_units", text:"You measure a book using paperclips. You need 6 paperclips. The book is ___ paperclips long.", options:[{text:"5",type:"calculation_error",logicTag:"one short"},{text:"7",type:"calculation_error",logicTag:"one too many"},{text:"6",type:"correct",logicTag:"correct reading"},{text:"12",type:"concept_error",logicTag:"doubled"}], explanation:"If 6 paperclips fit end-to-end, the book is 6 paperclips long.", solutionSteps:["Lay paperclips end to end","Count: 6 fit","Book = 6 paperclips"], shortcut:"Count how many units fit = measurement.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_non_standard_units_q2", topicId:"math1_ch7_non_standard_units", text:"When measuring with non-standard units, what must we NOT leave between units?", options:[{text:"Colour",type:"concept_error",logicTag:"irrelevant"},{text:"Gaps",type:"correct",logicTag:"gaps cause undercounting"},{text:"Numbers",type:"concept_error",logicTag:"numbers are needed"},{text:"Objects",type:"concept_error",logicTag:"objects are the units"}], explanation:"Gaps between units give a smaller (wrong) count. Units must be end-to-end with no gaps.", solutionSteps:["Gap = empty space = missed length","No gaps → accurate count"], shortcut:"No gaps, no overlaps.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_non_standard_units_q3", topicId:"math1_ch7_non_standard_units", text:"Riya measures a shelf using her hand span. She gets 5 spans. Dev measures the same shelf and gets 7 spans. Why might they get different results?", options:[{text:"The shelf changed size",type:"concept_error",logicTag:"shelf stays same"},{text:"Their hand spans are different sizes",type:"correct",logicTag:"non-standard units vary"},{text:"One of them made an arithmetic error",type:"partial_logic",logicTag:"possible but not the main reason"},{text:"Hand spans cannot measure shelves",type:"concept_error",logicTag:"they can, just non-standard"}], explanation:"Different people have different hand span sizes, so they get different counts for the same object.", solutionSteps:["Non-standard units vary person to person","Same shelf, different spans = different counts"], shortcut:"Non-standard = different for each person.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_non_standard_units_q4", topicId:"math1_ch7_non_standard_units", text:"Which is a NON-STANDARD unit of length?", options:[{text:"Centimetre",type:"concept_error",logicTag:"standard unit"},{text:"Metre",type:"concept_error",logicTag:"standard unit"},{text:"Kilometre",type:"concept_error",logicTag:"standard unit"},{text:"Foot step",type:"correct",logicTag:"non-standard: varies per person"}], explanation:"Centimetre, metre, and kilometre are standard (same everywhere). A footstep varies per person.", solutionSteps:["Standard: cm, m, km (fixed size)","Non-standard: footstep, hand span (varies)"], shortcut:"Standard = ruler. Non-standard = body parts/everyday objects.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_non_standard_units_q5", topicId:"math1_ch7_non_standard_units", text:"A table is 8 blocks long. A chair is 5 blocks long. Which is LONGER?", options:[{text:"Chair",type:"concept_error",logicTag:"5 < 8"},{text:"Both same",type:"concept_error",logicTag:"not equal"},{text:"Table",type:"correct",logicTag:"8 > 5"},{text:"Cannot tell",type:"guessing",logicTag:"can compare 8 vs 5"}], explanation:"8 blocks > 5 blocks → table is longer.", solutionSteps:["Table = 8 blocks","Chair = 5 blocks","8 > 5 → table longer"], shortcut:"More blocks = longer.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_non_standard_units_q6", topicId:"math1_ch7_non_standard_units", text:"To get an accurate measurement, all units used must be ___.", options:[{text:"Different sizes",type:"concept_error",logicTag:"mixed units give wrong results"},{text:"The same size",type:"correct",logicTag:"identical units required"},{text:"Very large",type:"concept_error",logicTag:"size doesn't matter as long as consistent"},{text:"Round",type:"concept_error",logicTag:"shape irrelevant"}], explanation:"All units must be the same size so the measurement is consistent.", solutionSteps:["Use identical units","Mixed sizes → wrong answer"], shortcut:"Same-size units = fair measurement.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_non_standard_units_q7", topicId:"math1_ch7_non_standard_units", text:"You measure a pen: it is 3 cubes long. Your friend measures a straw: 5 cubes long. Which is longer?", options:[{text:"Pen",type:"concept_error",logicTag:"3 < 5"},{text:"Both equal",type:"concept_error",logicTag:"different counts"},{text:"Cannot tell because units are different",type:"concept_error",logicTag:"both used cubes"},{text:"Straw",type:"correct",logicTag:"5 > 3, same units used"}], explanation:"Both used cubes (same units), so 5 > 3 means the straw is longer.", solutionSteps:["Both measured with cubes (same unit)","5 cubes > 3 cubes → straw longer"], shortcut:"Same units → just compare numbers.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_non_standard_units_q8", topicId:"math1_ch7_non_standard_units", text:"How do we say the result of a measurement?", options:[{text:"'It is long'",type:"concept_error",logicTag:"vague, no unit"},{text:"'7 paperclips long'",type:"correct",logicTag:"number + unit"},{text:"'Big'",type:"concept_error",logicTag:"no number or unit"},{text:"'Nice'",type:"concept_error",logicTag:"not a measurement"}], explanation:"A measurement always has a number AND a unit: '7 paperclips long'.", solutionSteps:["Number: 7","Unit: paperclips","Together: 7 paperclips long"], shortcut:"Measurement = number + unit.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },

  // ── Ch7 S3: Comparing Weights (math1_ch7_comparing_weights) ──────────────────
  { questionId:"math1_ch7_comparing_weights_q1", topicId:"math1_ch7_comparing_weights", text:"On a balance scale, the stone side goes DOWN. The feather side goes UP. Which is HEAVIER?", options:[{text:"Feather",type:"concept_error",logicTag:"feather goes up = lighter"},{text:"Both equal",type:"concept_error",logicTag:"not equal"},{text:"Stone",type:"correct",logicTag:"down = heavier"},{text:"Cannot tell",type:"guessing",logicTag:"balance tells us"}], explanation:"The side that goes DOWN is HEAVIER. Stone side down → stone is heavier.", solutionSteps:["Balance: down = heavy, up = light","Stone side goes down → stone is heavier"], shortcut:"Down on balance = heavier.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_weights_q2", topicId:"math1_ch7_comparing_weights", text:"A cotton ball and a stone: which is LIGHTER?", options:[{text:"Stone",type:"concept_error",logicTag:"stone is heavy"},{text:"Both equal",type:"concept_error",logicTag:"not equal"},{text:"Cotton ball",type:"correct",logicTag:"cotton is much lighter"},{text:"Cannot tell",type:"guessing",logicTag:"can tell from common knowledge"}], explanation:"A cotton ball is much lighter than a stone.", solutionSteps:["Cotton = light","Stone = heavy","Cotton ball is lighter"], shortcut:"Cotton = feather-light. Stone = heavy.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_weights_q3", topicId:"math1_ch7_comparing_weights", text:"A big balloon and a small stone — which is HEAVIER?", options:[{text:"Big balloon",type:"concept_error",logicTag:"big doesn't mean heavy"},{text:"They are equal",type:"concept_error",logicTag:"very different weights"},{text:"Small stone",type:"correct",logicTag:"stone heavier than balloon"},{text:"Cannot compare",type:"guessing",logicTag:"can compare by holding"}], explanation:"A small stone is much heavier than a big balloon. Size does not determine weight.", solutionSteps:["Balloon = mostly air = very light","Stone = dense = heavy","Stone heavier despite being smaller"], shortcut:"Big ≠ heavy. Weight depends on material.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_weights_q4", topicId:"math1_ch7_comparing_weights", text:"What tool do we use to compare the weight of two objects?", options:[{text:"Ruler",type:"concept_error",logicTag:"ruler measures length"},{text:"Clock",type:"concept_error",logicTag:"clock measures time"},{text:"Balance scale",type:"correct",logicTag:"balance compares weight"},{text:"Cup",type:"concept_error",logicTag:"cup measures capacity"}], explanation:"A balance scale compares the weight of objects placed on each side.", solutionSteps:["Balance scale: one object per side","Heavy side goes down"], shortcut:"Balance scale = weight tool.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_weights_q5", topicId:"math1_ch7_comparing_weights", text:"Heavier objects feel ___ when you hold them.", options:[{text:"Soft",type:"concept_error",logicTag:"texture not weight"},{text:"Light",type:"concept_error",logicTag:"opposite"},{text:"Pulled down more",type:"correct",logicTag:"gravity pulls heavy objects more"},{text:"Cold",type:"concept_error",logicTag:"temperature not weight"}], explanation:"Heavy objects are pulled down more by gravity, so your arm is pulled down harder.", solutionSteps:["Hold object","More pull-down = heavier"], shortcut:"More pull = heavier.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_weights_q6", topicId:"math1_ch7_comparing_weights", text:"Two apples balance a bunch of grapes. The apples are ___ than the grapes.", options:[{text:"Lighter",type:"concept_error",logicTag:"they're balanced = equal"},{text:"Heavier",type:"concept_error",logicTag:"they're balanced = equal"},{text:"Equal in weight",type:"correct",logicTag:"balance = same weight"},{text:"Larger",type:"concept_error",logicTag:"size not weight"}], explanation:"When a balance is level (balanced), both sides have the same weight.", solutionSteps:["Balanced = level scales","Equal weight on both sides"], shortcut:"Balanced scale = equal weight.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_weights_q7", topicId:"math1_ch7_comparing_weights", text:"Which word is OPPOSITE to 'heavier'?", options:[{text:"Taller",type:"concept_error",logicTag:"height not weight"},{text:"Lighter",type:"correct",logicTag:"lighter is opposite of heavier"},{text:"Longer",type:"concept_error",logicTag:"length"},{text:"More",type:"concept_error",logicTag:"vague"}], explanation:"The opposite of heavier is lighter.", solutionSteps:["Heavier ↔ Lighter","Weight opposites"], shortcut:"Heavy ↔ Light.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_weights_q8", topicId:"math1_ch7_comparing_weights", text:"On a see-saw (like a balance), where does the heavier child sit?", options:[{text:"On the high side",type:"concept_error",logicTag:"heavy goes down"},{text:"In the middle",type:"concept_error",logicTag:"pivot not a seat"},{text:"On the low / down side",type:"correct",logicTag:"heavy = goes down"},{text:"Either side, it doesn't matter",type:"concept_error",logicTag:"weight matters"}], explanation:"The heavier child brings their side down — the heavy side is lower.", solutionSteps:["Heavier = more downward pull","Heavier child's side goes down"], shortcut:"Heavy = down. Like a balance.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },

  // ── Ch7 S4: Comparing Capacities (math1_ch7_comparing_capacities) ─────────────
  { questionId:"math1_ch7_comparing_capacities_q1", topicId:"math1_ch7_comparing_capacities", text:"A cup holds less water than a bucket. Which has MORE capacity?", options:[{text:"Cup",type:"concept_error",logicTag:"cup holds less"},{text:"Both the same",type:"concept_error",logicTag:"stated as different"},{text:"Bucket",type:"correct",logicTag:"holds more = more capacity"},{text:"Cannot tell",type:"guessing",logicTag:"stated in question"}], explanation:"The bucket holds more water → bucket has more capacity.", solutionSteps:["Capacity = how much it holds","Bucket holds more → more capacity"], shortcut:"Holds more = more capacity.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_capacities_q2", topicId:"math1_ch7_comparing_capacities", text:"A FULL glass has ___ water than an EMPTY glass.", options:[{text:"Less",type:"concept_error",logicTag:"full has more"},{text:"The same",type:"concept_error",logicTag:"full ≠ empty"},{text:"More",type:"correct",logicTag:"full > empty"},{text:"No",type:"concept_error",logicTag:"not a comparison"}], explanation:"A full glass has more water than an empty glass.", solutionSteps:["Full = maximum water","Empty = zero water","Full has MORE"], shortcut:"Full > empty.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_capacities_q3", topicId:"math1_ch7_comparing_capacities", text:"You pour water from a jug into two containers: one big, one small. The small container overflows first. Which has LESS capacity?", options:[{text:"Big container",type:"concept_error",logicTag:"big holds more"},{text:"Both the same",type:"concept_error",logicTag:"one overflowed first"},{text:"Small container",type:"correct",logicTag:"overflows first = less capacity"},{text:"The jug",type:"concept_error",logicTag:"question is about containers"}], explanation:"The small container overflowed first, meaning it can hold less water → less capacity.", solutionSteps:["Overflow = full = cannot hold more","Overflows first = less capacity"], shortcut:"Overflows first = less capacity.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_capacities_q4", topicId:"math1_ch7_comparing_capacities", text:"What does 'capacity' mean?", options:[{text:"How heavy a container is",type:"concept_error",logicTag:"that's weight"},{text:"How tall a container is",type:"concept_error",logicTag:"that's height"},{text:"How much a container can hold",type:"correct",logicTag:"capacity = maximum amount held"},{text:"What colour a container is",type:"concept_error",logicTag:"irrelevant"}], explanation:"Capacity = the maximum amount (liquid, sand, etc.) a container can hold.", solutionSteps:["Capacity = how much fits inside"], shortcut:"Capacity = holds how much.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_capacities_q5", topicId:"math1_ch7_comparing_capacities", text:"A tall thin glass holds 150 ml. A short wide bowl holds 300 ml. Which has MORE capacity?", options:[{text:"Tall thin glass",type:"concept_error",logicTag:"150 < 300"},{text:"Both equal",type:"concept_error",logicTag:"150 ≠ 300"},{text:"Short wide bowl",type:"correct",logicTag:"300 > 150"},{text:"Cannot compare",type:"guessing",logicTag:"numbers given"}], explanation:"300 ml > 150 ml → the bowl has more capacity. Taller doesn't mean more capacity.", solutionSteps:["Glass = 150 ml","Bowl = 300 ml","300 > 150 → bowl has more"], shortcut:"Compare the numbers: more ml = more capacity.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_capacities_q6", topicId:"math1_ch7_comparing_capacities", text:"Which word is OPPOSITE to 'full'?", options:[{text:"Heavy",type:"concept_error",logicTag:"weight not capacity"},{text:"Big",type:"concept_error",logicTag:"size not level"},{text:"Empty",type:"correct",logicTag:"opposite of full"},{text:"Long",type:"concept_error",logicTag:"length"}], explanation:"Full and empty are opposites for capacity.", solutionSteps:["Full = maximum content","Empty = no content","Opposites"], shortcut:"Full ↔ Empty.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_capacities_q7", topicId:"math1_ch7_comparing_capacities", text:"If a container is HALF full, it means it holds ___ of its maximum.", options:[{text:"All of it",type:"concept_error",logicTag:"that's full"},{text:"None of it",type:"concept_error",logicTag:"that's empty"},{text:"About half",type:"correct",logicTag:"half full = halfway"},{text:"More than full",type:"concept_error",logicTag:"overfull"}], explanation:"Half full = the container is filled to about halfway.", solutionSteps:["Half = 50%","Half full = halfway filled"], shortcut:"Half full = halfway.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },
  { questionId:"math1_ch7_comparing_capacities_q8", topicId:"math1_ch7_comparing_capacities", text:"To compare capacity of two containers, we should ___ the same liquid into each.", options:[{text:"Weigh",type:"concept_error",logicTag:"weight not capacity"},{text:"Pour",type:"correct",logicTag:"pour same liquid, see which holds more"},{text:"Heat",type:"concept_error",logicTag:"irrelevant"},{text:"Paint",type:"concept_error",logicTag:"irrelevant"}], explanation:"Pour the same liquid and see which holds more without overflowing.", solutionSteps:["Pour same amount","One that holds more = more capacity"], shortcut:"Pour and observe — the one that holds more wins.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"7" },

  // ── Ch8 S1: Numbers 21 to 30 (math1_ch8_numbers_21_to_30) ────────────────────
  { questionId:"math1_ch8_numbers_21_to_30_q1", topicId:"math1_ch8_numbers_21_to_30", text:"23 = ___ tens and ___ ones.", options:[{text:"3 tens and 2 ones",type:"concept_error",logicTag:"digits swapped"},{text:"2 tens and 0 ones",type:"concept_error",logicTag:"forgot ones"},{text:"2 tens and 3 ones",type:"correct",logicTag:"2 tens + 3 ones = 23"},{text:"0 tens and 23 ones",type:"concept_error",logicTag:"no tens recognised"}], explanation:"23 = 2 tens + 3 ones.", solutionSteps:["23 − 20 = 3 ones","20 = 2 tens","So 2 tens + 3 ones"], shortcut:"Tens digit = tens. Ones digit = ones.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_21_to_30_q2", topicId:"math1_ch8_numbers_21_to_30", text:"What is the word name for 28?", options:[{text:"Twenty-eight",type:"correct",logicTag:"correct"},{text:"Eighty-two",type:"concept_error",logicTag:"digits reversed in name"},{text:"Eighteenty",type:"concept_error",logicTag:"not a real word"},{text:"Twenty",type:"concept_error",logicTag:"only the tens part"}], explanation:"28 = twenty-eight.", solutionSteps:["Tens = twenty","Ones = eight","Together = twenty-eight"], shortcut:"twenty + ones digit name = number name.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_21_to_30_q3", topicId:"math1_ch8_numbers_21_to_30", text:"Which number comes AFTER 25?", options:[{text:"24",type:"concept_error",logicTag:"before 25"},{text:"27",type:"concept_error",logicTag:"skipped"},{text:"26",type:"correct",logicTag:"one after 25"},{text:"30",type:"concept_error",logicTag:"too far"}], explanation:"After 25 is 26.", solutionSteps:["…24,25,26…","After 25 = 26"], shortcut:"After = next number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_21_to_30_q4", topicId:"math1_ch8_numbers_21_to_30", text:"30 = ___ tens.", options:[{text:"2",type:"concept_error",logicTag:"that's 20"},{text:"0",type:"concept_error",logicTag:"no tens"},{text:"3",type:"correct",logicTag:"30 = 3 tens"},{text:"30",type:"concept_error",logicTag:"that's all ones"}], explanation:"30 = 3 tens + 0 ones.", solutionSteps:["30 ÷ 10 = 3 tens"], shortcut:"30 = 3 tens.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_21_to_30_q5", topicId:"math1_ch8_numbers_21_to_30", text:"Order: 22, 27, 21, 25, 29 — smallest first.", options:[{text:"29,27,25,22,21",type:"concept_error",logicTag:"descending"},{text:"21,22,25,27,29",type:"correct",logicTag:"ascending"},{text:"22,21,25,27,29",type:"concept_error",logicTag:"21 should come before 22"},{text:"21,25,22,27,29",type:"concept_error",logicTag:"not ordered"}], explanation:"Ascending: 21, 22, 25, 27, 29.", solutionSteps:["Smallest = 21","Then 22,25,27,29"], shortcut:"Ones digits in order when tens are equal.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_21_to_30_q6", topicId:"math1_ch8_numbers_21_to_30", text:"What is BETWEEN 24 and 26?", options:[{text:"23",type:"concept_error",logicTag:"before 24"},{text:"27",type:"concept_error",logicTag:"after 26"},{text:"25",type:"correct",logicTag:"24,25,26"},{text:"20",type:"concept_error",logicTag:"too small"}], explanation:"24, 25, 26 — the number between 24 and 26 is 25.", solutionSteps:["24, 25, 26","Between = 25"], shortcut:"Count up from 24.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_21_to_30_q7", topicId:"math1_ch8_numbers_21_to_30", text:"Which is larger: 29 or 23?", options:[{text:"23",type:"concept_error",logicTag:"smaller"},{text:"They are equal",type:"concept_error",logicTag:"not equal"},{text:"29",type:"correct",logicTag:"29 > 23"},{text:"Cannot tell",type:"guessing",logicTag:"can compare"}], explanation:"Both have 2 tens; compare ones: 9 > 3 → 29 > 23.", solutionSteps:["Same tens (2)","Ones: 9 > 3","So 29 > 23"], shortcut:"Same tens → compare ones.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_21_to_30_q8", topicId:"math1_ch8_numbers_21_to_30", text:"Twenty-four = ?", options:[{text:"42",type:"concept_error",logicTag:"reversed"},{text:"24",type:"correct",logicTag:"twenty-four = 24"},{text:"14",type:"concept_error",logicTag:"wrong tens"},{text:"40",type:"concept_error",logicTag:"forty not twenty-four"}], explanation:"Twenty-four = 24 (2 tens + 4 ones).", solutionSteps:["Twenty = 20","Four = 4","20 + 4 = 24"], shortcut:"Twenty-X = 2X.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },

  // ── Ch8 S2: Numbers 31 to 40 (math1_ch8_numbers_31_to_40) ────────────────────
  { questionId:"math1_ch8_numbers_31_to_40_q1", topicId:"math1_ch8_numbers_31_to_40", text:"36 = ___ tens and ___ ones.", options:[{text:"6 tens and 3 ones",type:"concept_error",logicTag:"reversed"},{text:"3 tens and 6 ones",type:"correct",logicTag:"36 = 30 + 6"},{text:"3 tens and 0 ones",type:"concept_error",logicTag:"that's 30"},{text:"0 tens and 36 ones",type:"concept_error",logicTag:"no tens"}], explanation:"36 = 3 tens + 6 ones.", solutionSteps:["3 tens = 30","6 ones = 6","30 + 6 = 36"], shortcut:"Tens digit = 3 → 3 tens. Ones digit = 6.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_31_to_40_q2", topicId:"math1_ch8_numbers_31_to_40", text:"Which spelling is CORRECT for 40?", options:[{text:"Fourty",type:"concept_error",logicTag:"common misspelling"},{text:"Forty",type:"correct",logicTag:"correct spelling"},{text:"Fortey",type:"concept_error",logicTag:"misspelling"},{text:"Fourtey",type:"concept_error",logicTag:"misspelling"}], explanation:"40 = forty. There is no 'u' in forty (unlike 'four').", solutionSteps:["four → has 'u'","forty → no 'u'"], shortcut:"Forty = no 'u'. Forty.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_31_to_40_q3", topicId:"math1_ch8_numbers_31_to_40", text:"What number comes BEFORE 35?", options:[{text:"36",type:"concept_error",logicTag:"after 35"},{text:"33",type:"concept_error",logicTag:"two before"},{text:"34",type:"correct",logicTag:"one before 35"},{text:"30",type:"concept_error",logicTag:"too far before"}], explanation:"Before 35 is 34.", solutionSteps:["…33,34,35,36…","Before 35 = 34"], shortcut:"Before = step back one.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_31_to_40_q4", topicId:"math1_ch8_numbers_31_to_40", text:"Which is the LARGEST: 31, 39, 35, 38?", options:[{text:"31",type:"concept_error",logicTag:"smallest"},{text:"35",type:"concept_error",logicTag:"not largest"},{text:"38",type:"concept_error",logicTag:"not largest"},{text:"39",type:"correct",logicTag:"largest"}], explanation:"All have 3 tens. Compare ones: 9 > 8 > 5 > 1. So 39 is largest.", solutionSteps:["Same tens (3)","Ones: 9 > 8 > 5 > 1","Largest = 39"], shortcut:"Same tens: biggest ones digit = biggest number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_31_to_40_q5", topicId:"math1_ch8_numbers_31_to_40", text:"Fill in: 32, 33, ___, 35.", options:[{text:"36",type:"concept_error",logicTag:"too far"},{text:"31",type:"concept_error",logicTag:"before 32"},{text:"34",type:"correct",logicTag:"between 33 and 35"},{text:"30",type:"concept_error",logicTag:"too small"}], explanation:"32, 33, 34, 35 — missing is 34.", solutionSteps:["After 33 = 34","Before 35 = 34","Missing = 34"], shortcut:"Count up from 33.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_31_to_40_q6", topicId:"math1_ch8_numbers_31_to_40", text:"Thirty-seven = ?", options:[{text:"73",type:"concept_error",logicTag:"reversed"},{text:"37",type:"correct",logicTag:"thirty-seven = 37"},{text:"3",type:"concept_error",logicTag:"only tens"},{text:"17",type:"concept_error",logicTag:"wrong tens"}], explanation:"Thirty-seven = 37 (3 tens + 7 ones).", solutionSteps:["Thirty = 30","Seven = 7","30 + 7 = 37"], shortcut:"Thirty-X = 3X.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_31_to_40_q7", topicId:"math1_ch8_numbers_31_to_40", text:"How many tens are in 38?", options:[{text:"8",type:"concept_error",logicTag:"that's the ones"},{text:"38",type:"concept_error",logicTag:"that's the whole number"},{text:"3",type:"correct",logicTag:"38 = 3 tens + 8 ones"},{text:"0",type:"concept_error",logicTag:"no tens"}], explanation:"38 has 3 tens (the tens digit is 3).", solutionSteps:["38 = 30 + 8","30 = 3 tens"], shortcut:"Tens digit of 38 = 3.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_31_to_40_q8", topicId:"math1_ch8_numbers_31_to_40", text:"Which of these is a number in the THIRTIES?", options:[{text:"29",type:"concept_error",logicTag:"twenties"},{text:"40",type:"concept_error",logicTag:"forty, not thirties"},{text:"30",type:"concept_error",logicTag:"30 is the start, but 31-39 are 'thirties'"},{text:"33",type:"correct",logicTag:"33 is in the thirties"}], explanation:"The thirties are 31–39. 33 is in the thirties.", solutionSteps:["Thirties = 31-39","33 is in that range"], shortcut:"Tens digit = 3 → thirties.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },

  // ── Ch8 S3: Numbers 41 to 50 (math1_ch8_numbers_41_to_50) ────────────────────
  { questionId:"math1_ch8_numbers_41_to_50_q1", topicId:"math1_ch8_numbers_41_to_50", text:"47 = ___ tens and ___ ones.", options:[{text:"7 tens and 4 ones",type:"concept_error",logicTag:"reversed"},{text:"4 tens and 7 ones",type:"correct",logicTag:"47 = 40 + 7"},{text:"4 tens and 0 ones",type:"concept_error",logicTag:"that's 40"},{text:"5 tens and 7 ones",type:"concept_error",logicTag:"that's 57"}], explanation:"47 = 4 tens + 7 ones.", solutionSteps:["4 tens = 40","7 ones = 7","40 + 7 = 47"], shortcut:"Tens digit = 4 → 4 tens. Ones digit = 7.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_41_to_50_q2", topicId:"math1_ch8_numbers_41_to_50", text:"50 = ___ tens.", options:[{text:"0",type:"concept_error",logicTag:"no tens"},{text:"5",type:"correct",logicTag:"50 = 5 tens"},{text:"50",type:"concept_error",logicTag:"that's all ones"},{text:"10",type:"concept_error",logicTag:"too many"}], explanation:"50 = 5 tens + 0 ones.", solutionSteps:["50 ÷ 10 = 5 tens"], shortcut:"50 = 5 tens.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_41_to_50_q3", topicId:"math1_ch8_numbers_41_to_50", text:"What is 50 in words?", options:[{text:"Fifteen",type:"concept_error",logicTag:"fifteen = 15"},{text:"Five",type:"concept_error",logicTag:"just the digit"},{text:"Fifty",type:"correct",logicTag:"50 = fifty"},{text:"Fiveteen",type:"concept_error",logicTag:"not a real word"}], explanation:"50 = fifty. The '-ty' ending means tens.", solutionSteps:["five + ty = fifty","50 = fifty"], shortcut:"Five-ty = fifty = 50.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_41_to_50_q4", topicId:"math1_ch8_numbers_41_to_50", text:"Which comes AFTER 49?", options:[{text:"48",type:"concept_error",logicTag:"before 49"},{text:"51",type:"concept_error",logicTag:"skips 50"},{text:"50",type:"correct",logicTag:"after 49 = 50"},{text:"40",type:"concept_error",logicTag:"too far back"}], explanation:"After 49 is 50 (the next number).", solutionSteps:["…48,49,50…","After 49 = 50"], shortcut:"49 → 50.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_41_to_50_q5", topicId:"math1_ch8_numbers_41_to_50", text:"Order: 44, 41, 50, 47, 43 — largest first.", options:[{text:"41,43,44,47,50",type:"concept_error",logicTag:"smallest first"},{text:"50,47,44,43,41",type:"correct",logicTag:"descending"},{text:"50,44,47,41,43",type:"concept_error",logicTag:"not ordered"},{text:"44,43,41,47,50",type:"concept_error",logicTag:"not ordered"}], explanation:"Largest first: 50, 47, 44, 43, 41.", solutionSteps:["Largest = 50","Then 47,44,43,41"], shortcut:"Descending = largest first.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_41_to_50_q6", topicId:"math1_ch8_numbers_41_to_50", text:"Forty-five = ?", options:[{text:"54",type:"concept_error",logicTag:"reversed"},{text:"45",type:"correct",logicTag:"forty-five = 45"},{text:"40",type:"concept_error",logicTag:"only tens"},{text:"15",type:"concept_error",logicTag:"fifteen"}], explanation:"Forty-five = 45 (4 tens + 5 ones).", solutionSteps:["Forty = 40","Five = 5","40 + 5 = 45"], shortcut:"Forty-X = 4X.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_41_to_50_q7", topicId:"math1_ch8_numbers_41_to_50", text:"What number is between 46 and 48?", options:[{text:"45",type:"concept_error",logicTag:"before 46"},{text:"49",type:"concept_error",logicTag:"after 48"},{text:"47",type:"correct",logicTag:"between 46 and 48"},{text:"50",type:"concept_error",logicTag:"too far"}], explanation:"46, 47, 48 — 47 is between.", solutionSteps:["46, 47, 48","Between = 47"], shortcut:"Count up from 46.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_numbers_41_to_50_q8", topicId:"math1_ch8_numbers_41_to_50", text:"50 is the LAST number before we reach ___.", options:[{text:"40",type:"concept_error",logicTag:"we came from 40s"},{text:"49",type:"concept_error",logicTag:"comes before 50"},{text:"100",type:"concept_error",logicTag:"too far ahead"},{text:"51",type:"correct",logicTag:"next number after 50"}], explanation:"50 is the last in the forties range; after 50 comes 51.", solutionSteps:["After 50 = 51","51 is the next number"], shortcut:"50 → 51.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },

  // ── Ch8 S4: Ordering Numbers to 50 (math1_ch8_ordering_to_50) ────────────────
  { questionId:"math1_ch8_ordering_to_50_q1", topicId:"math1_ch8_ordering_to_50", text:"Which is GREATER: 42 or 24?", options:[{text:"24",type:"concept_error",logicTag:"smaller"},{text:"Both equal",type:"concept_error",logicTag:"not equal"},{text:"42",type:"correct",logicTag:"4 tens > 2 tens"},{text:"Cannot tell",type:"guessing",logicTag:"can compare"}], explanation:"42 has 4 tens; 24 has 2 tens. 4 > 2 → 42 > 24.", solutionSteps:["42: 4 tens","24: 2 tens","4 > 2 → 42 > 24"], shortcut:"Compare tens first. 4 tens > 2 tens.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_ordering_to_50_q2", topicId:"math1_ch8_ordering_to_50", text:"Order: 50, 21, 38, 44, 17 — smallest first.", options:[{text:"50,44,38,21,17",type:"concept_error",logicTag:"descending"},{text:"17,21,38,44,50",type:"correct",logicTag:"ascending"},{text:"21,17,38,44,50",type:"concept_error",logicTag:"not in order"},{text:"50,38,44,21,17",type:"concept_error",logicTag:"not in order"}], explanation:"Ascending: 17, 21, 38, 44, 50.", solutionSteps:["Compare tens first: 1<2<3<4<5","Order: 17,21,38,44,50"], shortcut:"Sort by tens digit first.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_ordering_to_50_q3", topicId:"math1_ch8_ordering_to_50", text:"Which symbol fits: 35 ___ 35?", options:[{text:">",type:"concept_error",logicTag:"not greater"},{text:"<",type:"concept_error",logicTag:"not less"},{text:"=",type:"correct",logicTag:"same number"},{text:"≠",type:"concept_error",logicTag:"they are equal"}], explanation:"35 = 35. A number equals itself.", solutionSteps:["35 and 35 are the same","Same number = equal = '='"], shortcut:"Same number = '='.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_ordering_to_50_q4", topicId:"math1_ch8_ordering_to_50", text:"To compare 47 and 43, we first look at the ___ digit.", options:[{text:"Ones",type:"concept_error",logicTag:"check tens first when different"},{text:"Tens",type:"correct",logicTag:"compare tens first"},{text:"Both at once",type:"concept_error",logicTag:"check in order"},{text:"Neither",type:"concept_error",logicTag:"must look at digits"}], explanation:"Always compare tens digits first. If equal, then compare ones.", solutionSteps:["47: 4 tens","43: 4 tens","Equal tens → compare ones: 7 > 3 → 47 > 43"], shortcut:"Tens first. Then ones if tied.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_ordering_to_50_q5", topicId:"math1_ch8_ordering_to_50", text:"Which number is NOT in order in this list: 22, 27, 25, 31?", options:[{text:"22",type:"concept_error",logicTag:"it's in place"},{text:"27",type:"concept_error",logicTag:"this is the issue: 27 > 25 but 25 comes after"},{text:"25",type:"correct",logicTag:"25 should come before 27"},{text:"31",type:"concept_error",logicTag:"31 correctly at the end"}], explanation:"22, 27, 25 is not in ascending order — 25 should come before 27. So 25 (or 27) is out of place.", solutionSteps:["Ascending: 22,25,27,31","In given list: 22,27,25,31 — 25 is after 27 (wrong)"], shortcut:"Check each step: must always go up.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_ordering_to_50_q6", topicId:"math1_ch8_ordering_to_50", text:"What is the SMALLEST two-digit number?", options:[{text:"20",type:"concept_error",logicTag:"larger than 10"},{text:"11",type:"concept_error",logicTag:"not smallest 2-digit"},{text:"10",type:"correct",logicTag:"10 is the first two-digit number"},{text:"1",type:"concept_error",logicTag:"single digit"}], explanation:"10 is the first (smallest) two-digit number.", solutionSteps:["1-9: single digit","10 = first two-digit number"], shortcut:"10 = first two-digit number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_ordering_to_50_q7", topicId:"math1_ch8_ordering_to_50", text:"29 ___ 31 (which symbol?)", options:[{text:"=",type:"concept_error",logicTag:"not equal"},{text:">",type:"concept_error",logicTag:"29 < 31"},{text:"<",type:"correct",logicTag:"29 < 31"},{text:"None",type:"guessing",logicTag:"a symbol fits"}], explanation:"29 < 31 (2 tens < 3 tens).", solutionSteps:["29: 2 tens","31: 3 tens","2 < 3 → 29 < 31"], shortcut:"Compare tens: 2 < 3.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"8" },
  { questionId:"math1_ch8_ordering_to_50_q8", topicId:"math1_ch8_ordering_to_50", text:"The number 50 is ___ all other numbers from 1 to 50.", options:[{text:"Smaller than",type:"concept_error",logicTag:"50 is the largest"},{text:"Equal to",type:"concept_error",logicTag:"not all equal"},{text:"Greater than or equal to",type:"correct",logicTag:"50 ≥ all from 1-50"},{text:"Unrelated to",type:"concept_error",logicTag:"wrong"}], explanation:"50 is the largest number from 1 to 50, so it is greater than or equal to all numbers in that range.", solutionSteps:["50 is the maximum in 1-50","50 ≥ every other number here"], shortcut:"Largest in range ≥ all others.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"8" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
    console.log(`  ✓ ${q.questionId}`);
  }
  console.log(`\nSeeded ${questions.length} questions for Class 1 Math v2 (Ch7–Ch8).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
