/**
 * seedMath1QuestionsV2A.js
 * Class 1 Mathematics v2 — Chapters 1–2 (64 questions)
 * 8 chapters × 4 sub-topics × 8 questions
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";

dotenv.config();

const questions = [

  // ── Ch1 S1: Identifying 2D Shapes (math1_ch1_2d_shapes) ──────────────────────
  { questionId:"math1_ch1_2d_shapes_q1", topicId:"math1_ch1_2d_shapes", text:"Which shape has 3 sides and 3 corners?", options:[{text:"Circle",type:"concept_error",logicTag:"0 sides confused"},{text:"Triangle",type:"correct",logicTag:"3 sides"},{text:"Square",type:"concept_error",logicTag:"4 sides"},{text:"Rectangle",type:"concept_error",logicTag:"4 sides"}], explanation:"A triangle has exactly 3 sides and 3 corners.", solutionSteps:["Count sides of each shape","Triangle = 3 sides, 3 corners"], shortcut:"Tri = 3 (like tricycle has 3 wheels).", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_2d_shapes_q2", topicId:"math1_ch1_2d_shapes", text:"How many sides does a square have?", options:[{text:"3",type:"concept_error",logicTag:"triangle confused"},{text:"5",type:"guessing",logicTag:"too many"},{text:"4",type:"correct",logicTag:"correct"},{text:"0",type:"concept_error",logicTag:"circle confused"}], explanation:"A square has 4 equal sides and 4 corners.", solutionSteps:["Draw a square","Count each side: 1,2,3,4"], shortcut:"Square = 4 equal sides.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_2d_shapes_q3", topicId:"math1_ch1_2d_shapes", text:"Which shape has NO sides and NO corners?", options:[{text:"Triangle",type:"concept_error",logicTag:"3 sides"},{text:"Rectangle",type:"concept_error",logicTag:"4 sides"},{text:"Square",type:"concept_error",logicTag:"4 sides"},{text:"Circle",type:"correct",logicTag:"0 sides"}], explanation:"A circle is perfectly round with no sides and no corners.", solutionSteps:["Circles are round","No straight sides, no corners"], shortcut:"Circle = 0 sides, 0 corners.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_2d_shapes_q4", topicId:"math1_ch1_2d_shapes", text:"A book cover is the shape of a ___.", options:[{text:"Circle",type:"concept_error",logicTag:"round not rectangular"},{text:"Triangle",type:"concept_error",logicTag:"3 sides not 4"},{text:"Rectangle",type:"correct",logicTag:"2 long 2 short sides"},{text:"Square",type:"concept_error",logicTag:"all sides equal"}], explanation:"A book has 4 sides — 2 long and 2 short — making it a rectangle.", solutionSteps:["Look at the book","4 sides: 2 long, 2 short = rectangle"], shortcut:"Rectangle has 2 pairs of equal sides (not all 4 equal).", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_2d_shapes_q5", topicId:"math1_ch1_2d_shapes", text:"Which shape has 4 EQUAL sides?", options:[{text:"Rectangle",type:"concept_error",logicTag:"not all equal"},{text:"Circle",type:"concept_error",logicTag:"no sides"},{text:"Triangle",type:"concept_error",logicTag:"3 sides"},{text:"Square",type:"correct",logicTag:"all 4 sides equal"}], explanation:"A square has all four sides of the same length.", solutionSteps:["Rectangle has 4 sides but 2 are longer","Square has 4 sides all equal"], shortcut:"Square = all 4 sides the same.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_2d_shapes_q6", topicId:"math1_ch1_2d_shapes", text:"A pizza slice looks like which shape?", options:[{text:"Circle",type:"concept_error",logicTag:"full pizza is circle"},{text:"Triangle",type:"correct",logicTag:"wedge = 3 sides"},{text:"Square",type:"concept_error",logicTag:"4 equal sides"},{text:"Rectangle",type:"concept_error",logicTag:"2 long 2 short"}], explanation:"A pizza slice has a pointed top and a curved base — it looks like a triangle.", solutionSteps:["Count the straight edges of a slice","3 sides → triangle"], shortcut:"Pizza slice = triangle shape.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_2d_shapes_q7", topicId:"math1_ch1_2d_shapes", text:"How many corners does a triangle have?", options:[{text:"4",type:"concept_error",logicTag:"square corners"},{text:"0",type:"concept_error",logicTag:"circle"},{text:"2",type:"concept_error",logicTag:"too few"},{text:"3",type:"correct",logicTag:"3 corners"}], explanation:"A triangle has 3 sides and 3 corners.", solutionSteps:["Corners = where sides meet","Triangle has 3 where sides meet"], shortcut:"Corners = same count as sides in a triangle.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_2d_shapes_q8", topicId:"math1_ch1_2d_shapes", text:"Which of these is round (no sides)?", options:[{text:"Square",type:"concept_error",logicTag:"4 sides"},{text:"Triangle",type:"concept_error",logicTag:"3 sides"},{text:"Circle",type:"correct",logicTag:"round, no sides"},{text:"Rectangle",type:"concept_error",logicTag:"4 sides"}], explanation:"Only a circle is round with no sides.", solutionSteps:["Round = circle","Circle has no sides or corners"], shortcut:"If it's round, it's a circle.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },

  // ── Ch1 S2: Comparing Shapes by Size (math1_ch1_comparing_shapes) ─────────────
  { questionId:"math1_ch1_comparing_shapes_q1", topicId:"math1_ch1_comparing_shapes", text:"A football and a coin are both round. Which is BIGGER?", options:[{text:"Coin",type:"concept_error",logicTag:"smaller"},{text:"They are the same",type:"concept_error",logicTag:"different sizes"},{text:"Football",type:"correct",logicTag:"larger circle"},{text:"Cannot tell",type:"guessing",logicTag:"irrelevant"}], explanation:"Both are circles, but the football is much bigger than the coin.", solutionSteps:["Both are circular","Football is larger → football is bigger"], shortcut:"Same shape, different sizes — compare sizes directly.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_comparing_shapes_q2", topicId:"math1_ch1_comparing_shapes", text:"If a shape is BIGGER, it has more ___.", options:[{text:"Sides",type:"concept_error",logicTag:"sides don't change with size"},{text:"Corners",type:"concept_error",logicTag:"corners don't change"},{text:"Space inside it",type:"correct",logicTag:"area increases"},{text:"Colour",type:"guessing",logicTag:"irrelevant"}], explanation:"A bigger shape takes up more space (has more area).", solutionSteps:["Bigger = more space","Same shape name, more area"], shortcut:"Bigger = more room inside.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_comparing_shapes_q3", topicId:"math1_ch1_comparing_shapes", text:"Can two triangles be different sizes?", options:[{text:"No, all triangles are the same size",type:"concept_error",logicTag:"shape doesn't fix size"},{text:"Yes",type:"correct",logicTag:"size varies independently"},{text:"Only if they have different colours",type:"guessing",logicTag:"irrelevant"},{text:"No, triangles cannot be big",type:"concept_error",logicTag:"incorrect"}], explanation:"Yes! A triangle can be tiny or enormous — the shape name doesn't fix the size.", solutionSteps:["Shape name = number of sides","Size is separate from shape name"], shortcut:"Same shape, any size.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_comparing_shapes_q4", topicId:"math1_ch1_comparing_shapes", text:"A tall candle and a short candle are both cylinder shapes. Which is TALLER?", options:[{text:"Short candle",type:"concept_error",logicTag:"shorter"},{text:"They are the same",type:"concept_error",logicTag:"question says different"},{text:"Tall candle",type:"correct",logicTag:"taller"},{text:"Cannot compare",type:"guessing",logicTag:"irrelevant"}], explanation:"Both are cylinders, but the tall candle extends higher.", solutionSteps:["Both cylinder-shaped","Tall candle reaches up higher → taller"], shortcut:"Tall = extends higher.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_comparing_shapes_q5", topicId:"math1_ch1_comparing_shapes", text:"Which word means NOT as big?", options:[{text:"Taller",type:"concept_error",logicTag:"size in one direction"},{text:"Wider",type:"concept_error",logicTag:"breadth"},{text:"Smaller",type:"correct",logicTag:"less in size"},{text:"Longer",type:"concept_error",logicTag:"length"}], explanation:"'Smaller' means less big or not as large.", solutionSteps:["Smaller = less in size","Opposite of bigger"], shortcut:"Big ↔ Small.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_comparing_shapes_q6", topicId:"math1_ch1_comparing_shapes", text:"A large square and a small square — which has MORE sides?", options:[{text:"Large square — it has 8 sides",type:"concept_error",logicTag:"sides don't increase with size"},{text:"Small square — it has 2 sides",type:"concept_error",logicTag:"incorrect"},{text:"Both have the same — 4 sides",type:"correct",logicTag:"sides don't change with size"},{text:"Large square — it has 6 sides",type:"concept_error",logicTag:"wrong count"}], explanation:"Both squares have 4 sides regardless of size. Size does not change the number of sides.", solutionSteps:["Square always has 4 sides","Size does not change the number of sides"], shortcut:"Shape name = fixed sides. Size changes area, not sides.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_comparing_shapes_q7", topicId:"math1_ch1_comparing_shapes", text:"Which word best describes a shape that is NOT as tall?", options:[{text:"Bigger",type:"concept_error",logicTag:"overall size"},{text:"Shorter",type:"correct",logicTag:"less tall"},{text:"Wider",type:"concept_error",logicTag:"breadth"},{text:"Rounder",type:"concept_error",logicTag:"shape not height"}], explanation:"Shorter describes something with less height.", solutionSteps:["Height comparison","Less tall = shorter"], shortcut:"Tall ↔ Short.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_comparing_shapes_q8", topicId:"math1_ch1_comparing_shapes", text:"A big triangle and a small triangle — which is a triangle?", options:[{text:"Only the big one",type:"concept_error",logicTag:"both are triangles"},{text:"Only the small one",type:"concept_error",logicTag:"both are triangles"},{text:"Both are triangles",type:"correct",logicTag:"shape name independent of size"},{text:"Neither",type:"concept_error",logicTag:"incorrect"}], explanation:"Both shapes are triangles because both have 3 sides — size doesn't change the shape name.", solutionSteps:["Triangle = 3 sides","Both have 3 sides → both are triangles"], shortcut:"Shape name is about sides, not size.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },

  // ── Ch1 S3: Position Words (math1_ch1_position_words) ────────────────────────
  { questionId:"math1_ch1_position_words_q1", topicId:"math1_ch1_position_words", text:"The bird is sitting on TOP of the tree. Which word describes the bird's position?", options:[{text:"Below",type:"concept_error",logicTag:"opposite"},{text:"Inside",type:"concept_error",logicTag:"within boundary"},{text:"Above/on top",type:"correct",logicTag:"higher than tree"},{text:"Far",type:"concept_error",logicTag:"distance not position"}], explanation:"'On top' or 'above' describes something that is higher than the reference object.", solutionSteps:["Bird is higher than the tree","Higher = above / on top"], shortcut:"Up high = above / on top.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_position_words_q2", topicId:"math1_ch1_position_words", text:"The ball is INSIDE the box. The cat is OUTSIDE the box. Where is the ball?", options:[{text:"Outside",type:"concept_error",logicTag:"confuses inside/outside"},{text:"Below",type:"concept_error",logicTag:"different position"},{text:"Inside",type:"correct",logicTag:"within the box"},{text:"Above",type:"concept_error",logicTag:"different position"}], explanation:"The question states the ball is inside the box — 'inside' means within the boundary.", solutionSteps:["Question says ball is inside","Inside = within the boundary"], shortcut:"Inside = in. Outside = out.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_position_words_q3", topicId:"math1_ch1_position_words", text:"Your school is NEAR your house. The market is FAR. Which is closer to your house?", options:[{text:"Market",type:"concept_error",logicTag:"far = not close"},{text:"School",type:"correct",logicTag:"near = close"},{text:"Both are the same distance",type:"concept_error",logicTag:"near ≠ far"},{text:"Cannot tell",type:"guessing",logicTag:"irrelevant"}], explanation:"Near means close. School is near → school is closer.", solutionSteps:["Near = close by","School is near → school is closer"], shortcut:"Near = close, Far = not close.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_position_words_q4", topicId:"math1_ch1_position_words", text:"Hold up your RIGHT hand. The right hand is on which side?", options:[{text:"Left",type:"concept_error",logicTag:"opposite hand"},{text:"Right",type:"correct",logicTag:"correct side"},{text:"Above",type:"concept_error",logicTag:"different direction"},{text:"Below",type:"concept_error",logicTag:"different direction"}], explanation:"Right is the direction of the right hand.", solutionSteps:["Right hand = right side","Holding up right hand shows right direction"], shortcut:"Right hand = right side.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_position_words_q5", topicId:"math1_ch1_position_words", text:"The book is BELOW the table. Where is the book?", options:[{text:"On top of the table",type:"concept_error",logicTag:"above not below"},{text:"Under the table",type:"correct",logicTag:"below = under"},{text:"Inside the table",type:"concept_error",logicTag:"different position"},{text:"Far from the table",type:"concept_error",logicTag:"distance not position"}], explanation:"Below means under — the book is under the table.", solutionSteps:["Below = under","Book is below = book is under"], shortcut:"Below = under / lower than.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_position_words_q6", topicId:"math1_ch1_position_words", text:"Which word is OPPOSITE to 'above'?", options:[{text:"Near",type:"concept_error",logicTag:"distance not up/down"},{text:"Right",type:"concept_error",logicTag:"horizontal not vertical"},{text:"Below",type:"correct",logicTag:"opposite of above"},{text:"Inside",type:"concept_error",logicTag:"different dimension"}], explanation:"Above and below are opposites — above is higher, below is lower.", solutionSteps:["Opposite of above = below","Up ↔ Down"], shortcut:"Above ↔ Below (up and down pair).", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_position_words_q7", topicId:"math1_ch1_position_words", text:"A fish is INSIDE the water. A bird is OUTSIDE the water. Which is IN the water?", options:[{text:"Bird",type:"concept_error",logicTag:"outside = not in water"},{text:"Both",type:"concept_error",logicTag:"bird is outside"},{text:"Fish",type:"correct",logicTag:"inside = in"},{text:"Neither",type:"concept_error",logicTag:"fish is inside"}], explanation:"Inside means within — the fish is inside (within) the water.", solutionSteps:["Inside = within","Fish is inside water"], shortcut:"Inside = in, Outside = out.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_position_words_q8", topicId:"math1_ch1_position_words", text:"Which word describes something that is very close by?", options:[{text:"Far",type:"concept_error",logicTag:"opposite"},{text:"Below",type:"concept_error",logicTag:"different dimension"},{text:"Near",type:"correct",logicTag:"close by"},{text:"Above",type:"concept_error",logicTag:"different dimension"}], explanation:"Near means close by or not far away.", solutionSteps:["Near = close by","Close = near, not far"], shortcut:"Near = close. Far = not close.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },

  // ── Ch1 S4: Sorting Objects by Shape (math1_ch1_sorting_shapes) ──────────────
  { questionId:"math1_ch1_sorting_shapes_q1", topicId:"math1_ch1_sorting_shapes", text:"You are sorting by SHAPE. A coin, a clock, and a button are all round. Which group do they belong to?", options:[{text:"Square group",type:"concept_error",logicTag:"not square"},{text:"Triangle group",type:"concept_error",logicTag:"not triangle"},{text:"Circle group",type:"correct",logicTag:"all round"},{text:"Rectangle group",type:"concept_error",logicTag:"not rectangle"}], explanation:"Coins, clocks, and buttons are all round — they belong to the circle group.", solutionSteps:["All three are round","Round = circle group"], shortcut:"Round = circle.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_sorting_shapes_q2", topicId:"math1_ch1_sorting_shapes", text:"When sorting by shape, a red square and a blue square go in the SAME group because they have the same ___.", options:[{text:"Colour",type:"concept_error",logicTag:"colour is not the rule"},{text:"Shape",type:"correct",logicTag:"sorting by shape"},{text:"Size",type:"concept_error",logicTag:"size is not the rule"},{text:"Weight",type:"guessing",logicTag:"irrelevant"}], explanation:"We are sorting by shape, so colour doesn't matter. Both are squares → same group.", solutionSteps:["Rule = sort by shape","Both are squares → same group"], shortcut:"The rule decides the group — ignore other attributes.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_sorting_shapes_q3", topicId:"math1_ch1_sorting_shapes", text:"A triangle road sign and a triangular sandwich — which group do they go into when sorting by shape?", options:[{text:"Square group",type:"concept_error",logicTag:"not square"},{text:"Circle group",type:"concept_error",logicTag:"not circle"},{text:"Triangle group",type:"correct",logicTag:"both have 3 sides"},{text:"Rectangle group",type:"concept_error",logicTag:"not rectangle"}], explanation:"Both have 3 sides → they go in the triangle group.", solutionSteps:["Count sides of each shape","3 sides = triangle group"], shortcut:"Count corners to decide: 3 corners = triangle group.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_sorting_shapes_q4", topicId:"math1_ch1_sorting_shapes", text:"After sorting, the circle group has 5 objects and the square group has 3. Which group has MORE objects?", options:[{text:"Square group",type:"concept_error",logicTag:"3 < 5"},{text:"They are equal",type:"concept_error",logicTag:"5 ≠ 3"},{text:"Circle group",type:"correct",logicTag:"5 > 3"},{text:"Cannot tell",type:"guessing",logicTag:"data given"}], explanation:"5 > 3, so the circle group has more objects.", solutionSteps:["Circle group = 5","Square group = 3","5 > 3 → circle group has more"], shortcut:"Compare the numbers: 5 > 3.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_sorting_shapes_q5", topicId:"math1_ch1_sorting_shapes", text:"You want to sort blocks by shape. You see cube, ball, cube, cone, ball. How many cubes are there?", options:[{text:"1",type:"concept_error",logicTag:"too few"},{text:"3",type:"concept_error",logicTag:"too many"},{text:"2",type:"correct",logicTag:"two cubes"},{text:"4",type:"concept_error",logicTag:"too many"}], explanation:"Cube, cube = 2 cubes in the list.", solutionSteps:["List: cube, ball, cube, cone, ball","Count cubes: 1, 2 → 2 cubes"], shortcut:"Cross each item off as you count.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_sorting_shapes_q6", topicId:"math1_ch1_sorting_shapes", text:"Which object does NOT belong in the circle group?", options:[{text:"Coin",type:"concept_error",logicTag:"coin is round"},{text:"Clock face",type:"concept_error",logicTag:"clock is round"},{text:"Ruler",type:"correct",logicTag:"ruler is long rectangle"},{text:"Button",type:"concept_error",logicTag:"button is round"}], explanation:"A ruler is long and straight (rectangle-like), not round.", solutionSteps:["Coin, clock, button = round","Ruler = long rectangle → does not belong in circle group"], shortcut:"Odd one out: which is NOT round?", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_sorting_shapes_q7", topicId:"math1_ch1_sorting_shapes", text:"To sort correctly by shape, you should look at the object's ___.", options:[{text:"Colour",type:"concept_error",logicTag:"colour is not shape"},{text:"Weight",type:"guessing",logicTag:"irrelevant"},{text:"Outline / boundary",type:"correct",logicTag:"shape = outline"},{text:"Size",type:"concept_error",logicTag:"size ≠ shape"}], explanation:"Shape is defined by the outline (boundary) — how many sides and corners it has.", solutionSteps:["Shape = outline","Count sides/corners of the outline"], shortcut:"Trace the outline with your finger to feel the shape.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },
  { questionId:"math1_ch1_sorting_shapes_q8", topicId:"math1_ch1_sorting_shapes", text:"How many groups would you make when sorting these: squares, circles, and triangles?", options:[{text:"1",type:"concept_error",logicTag:"all different shapes"},{text:"5",type:"guessing",logicTag:"too many"},{text:"2",type:"concept_error",logicTag:"3 different shapes"},{text:"3",type:"correct",logicTag:"one per shape"}], explanation:"Three different shapes → three groups: square group, circle group, triangle group.", solutionSteps:["Three different shapes","One group per shape type = 3 groups"], shortcut:"Number of groups = number of different shapes.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"1" },

  // ── Ch2 S1: Counting 1 to 5 (math1_ch2_counting_1_to_5) ──────────────────────
  { questionId:"math1_ch2_counting_1_to_5_q1", topicId:"math1_ch2_counting_1_to_5", text:"How many apples: 🍎🍎🍎?", options:[{text:"2",type:"concept_error",logicTag:"one short"},{text:"4",type:"concept_error",logicTag:"one too many"},{text:"3",type:"correct",logicTag:"correct count"},{text:"1",type:"concept_error",logicTag:"much too few"}], explanation:"Count: 1, 2, 3. There are 3 apples.", solutionSteps:["Point to each apple as you count","1…2…3 → 3 apples"], shortcut:"Touch each one: 1, 2, 3.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_1_to_5_q2", topicId:"math1_ch2_counting_1_to_5", text:"How many fingers on ONE hand?", options:[{text:"4",type:"concept_error",logicTag:"one short"},{text:"6",type:"concept_error",logicTag:"too many"},{text:"3",type:"concept_error",logicTag:"too few"},{text:"5",type:"correct",logicTag:"5 fingers"}], explanation:"One hand has 5 fingers: thumb, index, middle, ring, little.", solutionSteps:["Count fingers on one hand","1,2,3,4,5 → 5 fingers"], shortcut:"5 fingers = 5.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_1_to_5_q3", topicId:"math1_ch2_counting_1_to_5", text:"What number comes AFTER 3?", options:[{text:"2",type:"concept_error",logicTag:"before 3"},{text:"5",type:"concept_error",logicTag:"two after 3"},{text:"4",type:"correct",logicTag:"one after 3"},{text:"1",type:"concept_error",logicTag:"much earlier"}], explanation:"The number after 3 is 4 (one step forward on the number line).", solutionSteps:["Count: 1,2,3,4","After 3 = 4"], shortcut:"After = next number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_1_to_5_q4", topicId:"math1_ch2_counting_1_to_5", text:"Count the stars: ★★★★. How many?", options:[{text:"3",type:"concept_error",logicTag:"one short"},{text:"5",type:"concept_error",logicTag:"one too many"},{text:"2",type:"concept_error",logicTag:"too few"},{text:"4",type:"correct",logicTag:"correct"}], explanation:"Count: 1, 2, 3, 4. There are 4 stars.", solutionSteps:["Touch each star","1,2,3,4 → 4 stars"], shortcut:"Touch as you count.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_1_to_5_q5", topicId:"math1_ch2_counting_1_to_5", text:"Show me 2 on your fingers. How many fingers are up?", options:[{text:"1",type:"concept_error",logicTag:"too few"},{text:"5",type:"concept_error",logicTag:"all fingers"},{text:"2",type:"correct",logicTag:"correct"},{text:"3",type:"concept_error",logicTag:"too many"}], explanation:"Showing 2 on fingers means 2 fingers up.", solutionSteps:["Hold up 2 fingers","Count them: 1, 2 → 2 fingers"], shortcut:"Fingers = number tool.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_1_to_5_q6", topicId:"math1_ch2_counting_1_to_5", text:"What number comes BEFORE 4?", options:[{text:"5",type:"concept_error",logicTag:"after 4"},{text:"2",type:"concept_error",logicTag:"two before"},{text:"3",type:"correct",logicTag:"one before 4"},{text:"1",type:"concept_error",logicTag:"three before"}], explanation:"Before 4 on the number line is 3.", solutionSteps:["Count: 1,2,3,4","Before 4 = 3"], shortcut:"Before = previous number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_1_to_5_q7", topicId:"math1_ch2_counting_1_to_5", text:"How many wheels does a tricycle have?", options:[{text:"2",type:"concept_error",logicTag:"bicycle wheels"},{text:"4",type:"concept_error",logicTag:"car wheels"},{text:"1",type:"concept_error",logicTag:"unicycle"},{text:"3",type:"correct",logicTag:"tri = 3"}], explanation:"A tricycle has 3 wheels. 'Tri' means three.", solutionSteps:["Tri = 3","Tricycle = 3 wheels"], shortcut:"Tri = 3.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_1_to_5_q8", topicId:"math1_ch2_counting_1_to_5", text:"Count backward from 5: 5, 4, ___, 2, 1. What is missing?", options:[{text:"6",type:"concept_error",logicTag:"going wrong direction"},{text:"0",type:"concept_error",logicTag:"too far"},{text:"3",type:"correct",logicTag:"between 4 and 2"},{text:"5",type:"concept_error",logicTag:"already said"}], explanation:"Counting backward: 5, 4, 3, 2, 1. The missing number is 3.", solutionSteps:["5, 4, ?, 2, 1","Between 4 and 2 = 3"], shortcut:"Count back: one less each time.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },

  // ── Ch2 S2: Counting 6 to 9 (math1_ch2_counting_6_to_9) ──────────────────────
  { questionId:"math1_ch2_counting_6_to_9_q1", topicId:"math1_ch2_counting_6_to_9", text:"Count: ★★★★★★★. How many stars?", options:[{text:"6",type:"concept_error",logicTag:"one short"},{text:"8",type:"concept_error",logicTag:"one too many"},{text:"5",type:"concept_error",logicTag:"two short"},{text:"7",type:"correct",logicTag:"correct"}], explanation:"Count 7 stars: 1,2,3,4,5,6,7.", solutionSteps:["Touch each star","Count: 1…7 → 7 stars"], shortcut:"Group in 5 + extras: 5 + 2 = 7.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_6_to_9_q2", topicId:"math1_ch2_counting_6_to_9", text:"What number comes after 7?", options:[{text:"6",type:"concept_error",logicTag:"before 7"},{text:"9",type:"concept_error",logicTag:"two after"},{text:"10",type:"concept_error",logicTag:"three after"},{text:"8",type:"correct",logicTag:"one after 7"}], explanation:"After 7 is 8.", solutionSteps:["Number sequence: 7, 8","After 7 = 8"], shortcut:"After = next number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_6_to_9_q3", topicId:"math1_ch2_counting_6_to_9", text:"How many legs does a spider have?", options:[{text:"6",type:"concept_error",logicTag:"insect legs"},{text:"4",type:"concept_error",logicTag:"dog legs"},{text:"9",type:"concept_error",logicTag:"too many"},{text:"8",type:"correct",logicTag:"spider has 8 legs"}], explanation:"A spider has 8 legs.", solutionSteps:["Spiders = 8 legs","Count: 1–8"], shortcut:"Spider = 8 legs (remember by the 'ight' in 'eight').", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_6_to_9_q4", topicId:"math1_ch2_counting_6_to_9", text:"Which number is BETWEEN 7 and 9?", options:[{text:"6",type:"concept_error",logicTag:"before 7"},{text:"10",type:"concept_error",logicTag:"after 9"},{text:"8",type:"correct",logicTag:"between 7 and 9"},{text:"5",type:"concept_error",logicTag:"too small"}], explanation:"7, 8, 9 — the number between 7 and 9 is 8.", solutionSteps:["Write sequence: 7, 8, 9","Middle = 8"], shortcut:"Between: look at the number that fits in the gap.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_6_to_9_q5", topicId:"math1_ch2_counting_6_to_9", text:"Show 6 on your fingers. Which fingers are left down (not showing)?", options:[{text:"6 fingers are down",type:"concept_error",logicTag:"6 are up"},{text:"1 finger is down",type:"concept_error",logicTag:"too few"},{text:"4 fingers are down",type:"correct",logicTag:"10 − 6 = 4"},{text:"3 fingers are down",type:"concept_error",logicTag:"wrong"}], explanation:"You have 10 fingers total. Showing 6 means 4 are still folded down: 10 − 6 = 4.", solutionSteps:["Total fingers = 10","Showing 6 → 10 − 6 = 4 down"], shortcut:"Up fingers + down fingers = 10 always.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_6_to_9_q6", topicId:"math1_ch2_counting_6_to_9", text:"Count objects: ○○○○○○○○○. How many?", options:[{text:"8",type:"concept_error",logicTag:"one short"},{text:"10",type:"concept_error",logicTag:"one too many"},{text:"7",type:"concept_error",logicTag:"two short"},{text:"9",type:"correct",logicTag:"correct"}], explanation:"Count: 1–9. There are 9 circles.", solutionSteps:["Touch each circle","1…2…3…4…5…6…7…8…9 → 9"], shortcut:"Group 5 + 4 = 9.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_6_to_9_q7", topicId:"math1_ch2_counting_6_to_9", text:"What number comes BEFORE 9?", options:[{text:"10",type:"concept_error",logicTag:"after 9"},{text:"7",type:"concept_error",logicTag:"two before"},{text:"8",type:"correct",logicTag:"one before 9"},{text:"6",type:"concept_error",logicTag:"three before"}], explanation:"Before 9 on the number line is 8.", solutionSteps:["…7, 8, 9…","One before 9 = 8"], shortcut:"Before = step back one.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_counting_6_to_9_q8", topicId:"math1_ch2_counting_6_to_9", text:"Which is the LARGEST number: 6, 9, 7, 8?", options:[{text:"6",type:"concept_error",logicTag:"smallest"},{text:"7",type:"concept_error",logicTag:"not largest"},{text:"8",type:"concept_error",logicTag:"not largest"},{text:"9",type:"correct",logicTag:"largest single digit after 8"}], explanation:"9 is the last single-digit number and the largest of these four.", solutionSteps:["Compare: 6, 7, 8, 9","9 is furthest right → largest"], shortcut:"Rightmost on number line = largest.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },

  // ── Ch2 S3: Number Names 1–9 (math1_ch2_number_names) ────────────────────────
  { questionId:"math1_ch2_number_names_q1", topicId:"math1_ch2_number_names", text:"What is the word name for the numeral 5?", options:[{text:"Four",type:"concept_error",logicTag:"one off"},{text:"Six",type:"concept_error",logicTag:"one off the other way"},{text:"Three",type:"concept_error",logicTag:"wrong"},{text:"Five",type:"correct",logicTag:"correct"}], explanation:"5 → five.", solutionSteps:["Numeral 5 = word 'five'"], shortcut:"5 = five.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_number_names_q2", topicId:"math1_ch2_number_names", text:"Which numeral matches the word 'eight'?", options:[{text:"6",type:"concept_error",logicTag:"six"},{text:"9",type:"concept_error",logicTag:"nine"},{text:"8",type:"correct",logicTag:"eight = 8"},{text:"3",type:"concept_error",logicTag:"three"}], explanation:"Eight = 8.", solutionSteps:["Word 'eight' = numeral 8"], shortcut:"Eight has 8 — remember they both have 8.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_number_names_q3", topicId:"math1_ch2_number_names", text:"Write the number name for 3.", options:[{text:"Two",type:"concept_error",logicTag:"wrong number"},{text:"Four",type:"concept_error",logicTag:"one too many"},{text:"Three",type:"correct",logicTag:"correct"},{text:"One",type:"concept_error",logicTag:"too small"}], explanation:"3 → three.", solutionSteps:["3 = three"], shortcut:"Three = 3.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_number_names_q4", topicId:"math1_ch2_number_names", text:"Which word name comes AFTER 'six' in order?", options:[{text:"Five",type:"concept_error",logicTag:"before six"},{text:"Eight",type:"concept_error",logicTag:"two after"},{text:"Four",type:"concept_error",logicTag:"before six"},{text:"Seven",type:"correct",logicTag:"one after six"}], explanation:"After six is seven (6, 7).", solutionSteps:["…five, six, seven…","After six = seven"], shortcut:"Six → seven: one step forward.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_number_names_q5", topicId:"math1_ch2_number_names", text:"How is the number 1 written in words?", options:[{text:"Zero",type:"concept_error",logicTag:"different number"},{text:"Two",type:"concept_error",logicTag:"different number"},{text:"One",type:"correct",logicTag:"correct"},{text:"Nine",type:"concept_error",logicTag:"different number"}], explanation:"1 = one.", solutionSteps:["Numeral 1 = word 'one'"], shortcut:"1 = one.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_number_names_q6", topicId:"math1_ch2_number_names", text:"Match: 'nine' = ?", options:[{text:"6",type:"concept_error",logicTag:"six"},{text:"7",type:"concept_error",logicTag:"seven"},{text:"9",type:"correct",logicTag:"nine = 9"},{text:"4",type:"concept_error",logicTag:"four"}], explanation:"Nine = 9.", solutionSteps:["Word 'nine' = numeral 9"], shortcut:"Nine = 9.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_number_names_q7", topicId:"math1_ch2_number_names", text:"Spell the number that comes after 'six': s _ v _ n", options:[{text:"siven",type:"concept_error",logicTag:"misspelling"},{text:"seven",type:"correct",logicTag:"correct spelling"},{text:"sevin",type:"concept_error",logicTag:"misspelling"},{text:"sevon",type:"concept_error",logicTag:"misspelling"}], explanation:"After six is seven, spelled s-e-v-e-n.", solutionSteps:["After six = seven","Spelling: s-e-v-e-n"], shortcut:"Seven = 7 letters, the same number it represents... and an easy word to remember.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_number_names_q8", topicId:"math1_ch2_number_names", text:"How many letters are in the word 'four'?", options:[{text:"3",type:"concept_error",logicTag:"too few"},{text:"5",type:"concept_error",logicTag:"too many"},{text:"4",type:"correct",logicTag:"f-o-u-r = 4 letters"},{text:"6",type:"concept_error",logicTag:"too many"}], explanation:"F-O-U-R = 4 letters.", solutionSteps:["Count letters: F,O,U,R","4 letters"], shortcut:"'Four' has 4 letters — same as the number!", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },

  // ── Ch2 S4: Ordering Numbers 1–9 (math1_ch2_ordering_numbers) ────────────────
  { questionId:"math1_ch2_ordering_numbers_q1", topicId:"math1_ch2_ordering_numbers", text:"Which number comes BETWEEN 5 and 7?", options:[{text:"4",type:"concept_error",logicTag:"before 5"},{text:"8",type:"concept_error",logicTag:"after 7"},{text:"6",type:"correct",logicTag:"between 5 and 7"},{text:"3",type:"concept_error",logicTag:"too small"}], explanation:"5, 6, 7 — the number between 5 and 7 is 6.", solutionSteps:["Sequence: 5, 6, 7","Between = 6"], shortcut:"Write the three in order: 5, __, 7 → 6.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_ordering_numbers_q2", topicId:"math1_ch2_ordering_numbers", text:"Order from SMALLEST to LARGEST: 7, 2, 5, 9, 1.", options:[{text:"9,7,5,2,1",type:"concept_error",logicTag:"largest to smallest"},{text:"1,2,5,7,9",type:"correct",logicTag:"correct ascending order"},{text:"1,5,2,9,7",type:"concept_error",logicTag:"not in order"},{text:"2,1,5,9,7",type:"concept_error",logicTag:"not in order"}], explanation:"Smallest to largest: 1, 2, 5, 7, 9.", solutionSteps:["Find smallest first: 1","Then next: 2, 5, 7, 9","Order: 1,2,5,7,9"], shortcut:"Ascending = smallest first.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_ordering_numbers_q3", topicId:"math1_ch2_ordering_numbers", text:"Which number comes BEFORE 6?", options:[{text:"7",type:"concept_error",logicTag:"after 6"},{text:"8",type:"concept_error",logicTag:"after 6"},{text:"5",type:"correct",logicTag:"one before 6"},{text:"4",type:"concept_error",logicTag:"two before"}], explanation:"Before 6 is 5.", solutionSteps:["…4,5,6,7…","One before 6 = 5"], shortcut:"Before = step back one.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_ordering_numbers_q4", topicId:"math1_ch2_ordering_numbers", text:"Which is the SMALLEST: 3, 8, 1, 6?", options:[{text:"3",type:"concept_error",logicTag:"not smallest"},{text:"8",type:"concept_error",logicTag:"largest"},{text:"6",type:"concept_error",logicTag:"not smallest"},{text:"1",type:"correct",logicTag:"smallest in list"}], explanation:"1 is the smallest number (furthest left on the number line).", solutionSteps:["Number line: 1 < 3 < 6 < 8","1 is leftmost → smallest"], shortcut:"Leftmost on number line = smallest.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_ordering_numbers_q5", topicId:"math1_ch2_ordering_numbers", text:"Fill in the blank: 4, 5, ___, 7, 8.", options:[{text:"5",type:"concept_error",logicTag:"already listed"},{text:"9",type:"concept_error",logicTag:"too far"},{text:"6",type:"correct",logicTag:"between 5 and 7"},{text:"3",type:"concept_error",logicTag:"too small"}], explanation:"The number between 5 and 7 in the sequence is 6.", solutionSteps:["4,5,__,7,8","Missing = 6 (one after 5, one before 7)"], shortcut:"Count on from 5: next is 6.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_ordering_numbers_q6", topicId:"math1_ch2_ordering_numbers", text:"9 is ___ than 4.", options:[{text:"smaller",type:"concept_error",logicTag:"9 > 4"},{text:"equal to",type:"concept_error",logicTag:"not equal"},{text:"greater",type:"correct",logicTag:"9 > 4"},{text:"the same as",type:"concept_error",logicTag:"not equal"}], explanation:"9 is to the right of 4 on the number line → 9 is greater than 4.", solutionSteps:["Number line: 4 is left of 9","Right = bigger → 9 is greater"], shortcut:"Right = bigger.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_ordering_numbers_q7", topicId:"math1_ch2_ordering_numbers", text:"What number is AFTER the number that comes after 6?", options:[{text:"6",type:"concept_error",logicTag:"that's the start"},{text:"7",type:"concept_error",logicTag:"that's 'after 6'"},{text:"8",type:"correct",logicTag:"after 7 (which is after 6)"},{text:"9",type:"concept_error",logicTag:"one too many"}], explanation:"After 6 is 7. After 7 is 8. So the answer is 8.", solutionSteps:["After 6 = 7","After 7 = 8","Answer = 8"], shortcut:"Two steps forward from 6: 7, 8.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"2" },
  { questionId:"math1_ch2_ordering_numbers_q8", topicId:"math1_ch2_ordering_numbers", text:"On the number line, which direction do numbers get BIGGER?", options:[{text:"To the left",type:"concept_error",logicTag:"opposite"},{text:"Numbers don't have direction",type:"concept_error",logicTag:"incorrect"},{text:"To the right",type:"correct",logicTag:"standard number line"},{text:"Upward",type:"concept_error",logicTag:"vertical not standard"}], explanation:"On a standard number line, numbers increase from left to right.", solutionSteps:["Number line: 1,2,3…","Goes left to right","Right = bigger"], shortcut:"Bigger = rightward on number line.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"2" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
    console.log(`  ✓ ${q.questionId}`);
  }
  console.log(`\nSeeded ${questions.length} questions for Class 1 Math v2 (Ch1–Ch2).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
