import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // ── Chapter 11: Lines and Lines ── math2_ch11_straight_curved (8 Qs)
  {
    questionId: "math2_ch11_straight_curved_q1",
    topicId: "math2_ch11_straight_curved",
    text: "Which of the following is a straight line?",
    options: [
      { text: "A curved road on a hill", type: "concept_error" },
      { text: "The edge of a ruler", type: "correct" },
      { text: "A river path", type: "concept_error" },
      { text: "A coiled rope", type: "guessing" },
    ],
    explanation: "The edge of a ruler is perfectly straight. Roads, rivers, and coiled ropes are curved or wavy.",
    solutionSteps: ["Think of lines that do not bend at all.", "A ruler's edge never bends — it is straight."],
    shortcut: "If it bends or turns, it is curved.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_straight_curved_q2",
    topicId: "math2_ch11_straight_curved",
    text: "How many straight lines make the letter 'T'?",
    options: [
      { text: "1", type: "concept_error" },
      { text: "2", type: "correct" },
      { text: "3", type: "partial_logic" },
      { text: "4", type: "guessing" },
    ],
    explanation: "The letter T is made of two straight lines — one horizontal line on top and one vertical line going down.",
    solutionSteps: ["Look at T.", "One line goes across (horizontal).", "One line goes down (vertical).", "Total = 2 straight lines."],
    shortcut: "T = 1 across + 1 down = 2 lines.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_straight_curved_q3",
    topicId: "math2_ch11_straight_curved",
    text: "Which shape has only curved lines?",
    options: [
      { text: "Triangle", type: "concept_error" },
      { text: "Square", type: "concept_error" },
      { text: "Circle", type: "correct" },
      { text: "Rectangle", type: "concept_error" },
    ],
    explanation: "A circle is made of one continuous curved line. Triangles, squares, and rectangles are made of straight lines.",
    solutionSteps: ["Triangle → 3 straight sides.", "Square → 4 straight sides.", "Circle → only a curved boundary.", "Answer: Circle."],
    shortcut: "No corners = curved.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_straight_curved_q4",
    topicId: "math2_ch11_straight_curved",
    text: "A road that bends around a mountain is an example of a ____.",
    options: [
      { text: "Straight line", type: "concept_error" },
      { text: "Curved line", type: "correct" },
      { text: "Vertical line", type: "concept_error" },
      { text: "Horizontal line", type: "concept_error" },
    ],
    explanation: "Roads that bend around hills or mountains follow a curved path — they are curved lines.",
    solutionSteps: ["Does the road go straight? No, it bends.", "Bending means curved.", "Answer: Curved line."],
    shortcut: "Bends = curved.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_straight_curved_q5",
    topicId: "math2_ch11_straight_curved",
    text: "How many curved lines does the letter 'S' have?",
    options: [
      { text: "0", type: "concept_error" },
      { text: "1", type: "concept_error" },
      { text: "2", type: "correct" },
      { text: "3", type: "partial_logic" },
    ],
    explanation: "The letter S has two curved portions — one curving to the right on top and one curving to the left at the bottom.",
    solutionSteps: ["Trace S from top.", "First curve goes right.", "Second curve goes left.", "Total = 2 curves."],
    shortcut: "S = 2 mirror curves.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_straight_curved_q6",
    topicId: "math2_ch11_straight_curved",
    text: "Which of the following has both straight AND curved lines?",
    options: [
      { text: "Circle", type: "concept_error" },
      { text: "Square", type: "concept_error" },
      { text: "Half-circle (D shape)", type: "correct" },
      { text: "Triangle", type: "concept_error" },
    ],
    explanation: "A half-circle (like the letter D) has one straight side and one curved side — making it a mix of both types.",
    solutionSteps: ["Circle → only curved.", "Square → only straight.", "D shape → 1 straight + 1 curved side.", "Answer: D shape (half-circle)."],
    shortcut: "D = straight + curved.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_straight_curved_q7",
    topicId: "math2_ch11_straight_curved",
    text: "Riya draws 3 straight lines and 2 curved lines. How many lines did she draw in total?",
    options: [
      { text: "4", type: "calculation_error" },
      { text: "5", type: "correct" },
      { text: "6", type: "calculation_error" },
      { text: "3", type: "partial_logic" },
    ],
    explanation: "3 straight + 2 curved = 5 lines total.",
    solutionSteps: ["Straight lines: 3.", "Curved lines: 2.", "Total = 3 + 2 = 5."],
    shortcut: "Just add both types.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_straight_curved_q8",
    topicId: "math2_ch11_straight_curved",
    text: "Which of these objects has a straight line edge?",
    options: [
      { text: "Ball", type: "concept_error" },
      { text: "Banana", type: "concept_error" },
      { text: "Book edge", type: "correct" },
      { text: "Egg", type: "concept_error" },
    ],
    explanation: "The edge of a book (side of a rectangle) is perfectly straight. Balls, bananas, and eggs have curved surfaces.",
    solutionSteps: ["Ball → round surface.", "Banana → curved fruit.", "Book edge → straight rectangular edge.", "Egg → oval/curved."],
    shortcut: "Flat-edged objects → straight lines.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },

  // ── math2_ch11_horizontal_vertical (8 Qs)
  {
    questionId: "math2_ch11_horizontal_vertical_q1",
    topicId: "math2_ch11_horizontal_vertical",
    text: "A line that goes from left to right (like the horizon) is called a ____.",
    options: [
      { text: "Vertical line", type: "concept_error" },
      { text: "Horizontal line", type: "correct" },
      { text: "Curved line", type: "concept_error" },
      { text: "Diagonal line", type: "concept_error" },
    ],
    explanation: "A horizontal line lies flat and goes from left to right, just like the horizon you see at sunrise.",
    solutionSteps: ["Horizon → flat, left to right.", "Horizontal comes from 'horizon'.", "Left to right = horizontal."],
    shortcut: "Horizontal = like the horizon — flat.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_horizontal_vertical_q2",
    topicId: "math2_ch11_horizontal_vertical",
    text: "A flag pole standing straight up is an example of a ____.",
    options: [
      { text: "Horizontal line", type: "concept_error" },
      { text: "Vertical line", type: "correct" },
      { text: "Curved line", type: "concept_error" },
      { text: "Slanted line", type: "concept_error" },
    ],
    explanation: "A flagpole stands straight up and down — that is a vertical line.",
    solutionSteps: ["Flagpole goes up and down.", "Up and down = vertical.", "Answer: vertical line."],
    shortcut: "Vertical = stands up like a person.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_horizontal_vertical_q3",
    topicId: "math2_ch11_horizontal_vertical",
    text: "How many horizontal lines are there in the letter 'E'?",
    options: [
      { text: "1", type: "concept_error" },
      { text: "2", type: "concept_error" },
      { text: "3", type: "correct" },
      { text: "4", type: "partial_logic" },
    ],
    explanation: "The letter E has 3 horizontal lines — one at the top, one in the middle, and one at the bottom.",
    solutionSteps: ["Look at E.", "Line at top → horizontal.", "Line in middle → horizontal.", "Line at bottom → horizontal.", "Total = 3 horizontal lines."],
    shortcut: "E has 3 horizontal arms.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_horizontal_vertical_q4",
    topicId: "math2_ch11_horizontal_vertical",
    text: "Which part of a plus sign (+) is horizontal?",
    options: [
      { text: "The up-down part", type: "concept_error" },
      { text: "The left-right part", type: "correct" },
      { text: "Both parts", type: "partial_logic" },
      { text: "Neither part", type: "concept_error" },
    ],
    explanation: "In a plus sign, the line going left to right is horizontal. The line going up and down is vertical.",
    solutionSteps: ["+ has two lines.", "Left-right line = horizontal.", "Up-down line = vertical."],
    shortcut: "Left-right = horizontal.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_horizontal_vertical_q5",
    topicId: "math2_ch11_horizontal_vertical",
    text: "A bookshelf lying flat on the floor is ____.",
    options: [
      { text: "Vertical", type: "concept_error" },
      { text: "Horizontal", type: "correct" },
      { text: "Diagonal", type: "concept_error" },
      { text: "Curved", type: "concept_error" },
    ],
    explanation: "When a bookshelf lies flat on the floor, it is horizontal — parallel to the ground.",
    solutionSteps: ["Flat on the floor = lying down.", "Left to right direction = horizontal."],
    shortcut: "Flat = horizontal.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_horizontal_vertical_q6",
    topicId: "math2_ch11_horizontal_vertical",
    text: "A telephone pole stands straight. It is a ____ line.",
    options: [
      { text: "Horizontal", type: "concept_error" },
      { text: "Vertical", type: "correct" },
      { text: "Slanted", type: "concept_error" },
      { text: "Curved", type: "concept_error" },
    ],
    explanation: "A telephone pole stands straight up — it is a vertical line.",
    solutionSteps: ["Telephone pole goes straight up.", "Up-down direction = vertical."],
    shortcut: "Standing up = vertical.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_horizontal_vertical_q7",
    topicId: "math2_ch11_horizontal_vertical",
    text: "A table top goes from left to right. It represents a ____ surface.",
    options: [
      { text: "Vertical", type: "concept_error" },
      { text: "Horizontal", type: "correct" },
      { text: "Diagonal", type: "concept_error" },
      { text: "Slanted", type: "concept_error" },
    ],
    explanation: "A table top is flat and goes from left to right — that is a horizontal surface.",
    solutionSteps: ["Table top → flat.", "Flat and level → horizontal."],
    shortcut: "Flat top = horizontal.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_horizontal_vertical_q8",
    topicId: "math2_ch11_horizontal_vertical",
    text: "In a plus sign (+), how many lines are vertical?",
    options: [
      { text: "0", type: "concept_error" },
      { text: "1", type: "correct" },
      { text: "2", type: "partial_logic" },
      { text: "3", type: "guessing" },
    ],
    explanation: "A plus sign has 2 lines total: 1 horizontal (left-right) and 1 vertical (up-down).",
    solutionSteps: ["Plus sign = 2 lines.", "1 goes left-right → horizontal.", "1 goes up-down → vertical.", "Vertical count = 1."],
    shortcut: "Plus = 1 vertical + 1 horizontal.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },

  // ── math2_ch11_parallel_lines (8 Qs)
  {
    questionId: "math2_ch11_parallel_lines_q1",
    topicId: "math2_ch11_parallel_lines",
    text: "Parallel lines are lines that ____.",
    options: [
      { text: "Always cross each other", type: "concept_error" },
      { text: "Never meet, no matter how long they get", type: "correct" },
      { text: "Are always curved", type: "concept_error" },
      { text: "Meet at a right angle", type: "misinterpretation" },
    ],
    explanation: "Parallel lines run side by side and never cross each other, no matter how far they extend.",
    solutionSteps: ["Parallel = running side by side.", "They keep the same distance apart.", "They never meet."],
    shortcut: "Parallel = same direction, never meeting.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_parallel_lines_q2",
    topicId: "math2_ch11_parallel_lines",
    text: "Which is the best example of parallel lines in real life?",
    options: [
      { text: "Railway tracks", type: "correct" },
      { text: "Two roads crossing", type: "concept_error" },
      { text: "A spider web", type: "concept_error" },
      { text: "A circle", type: "concept_error" },
    ],
    explanation: "Railway tracks run side by side and never meet — they are the classic example of parallel lines.",
    solutionSteps: ["Railway tracks always stay the same distance apart.", "They never cross.", "Perfect parallel lines."],
    shortcut: "Train tracks = parallel.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_parallel_lines_q3",
    topicId: "math2_ch11_parallel_lines",
    text: "The two long sides of a ruler are ____.",
    options: [
      { text: "Curved lines", type: "concept_error" },
      { text: "Parallel lines", type: "correct" },
      { text: "Diagonal lines", type: "concept_error" },
      { text: "Intersecting lines", type: "concept_error" },
    ],
    explanation: "The two long edges of a ruler are straight lines that run side by side and never meet — they are parallel.",
    solutionSteps: ["Look at a ruler.", "Two long edges run side by side.", "They never meet → parallel."],
    shortcut: "Ruler edges = parallel.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_parallel_lines_q4",
    topicId: "math2_ch11_parallel_lines",
    text: "Lines that cross each other are called ____.",
    options: [
      { text: "Parallel lines", type: "concept_error" },
      { text: "Intersecting lines", type: "correct" },
      { text: "Curved lines", type: "concept_error" },
      { text: "Horizontal lines", type: "concept_error" },
    ],
    explanation: "When two lines cross or meet at a point, they are called intersecting lines — opposite of parallel.",
    solutionSteps: ["Cross = meet at a point.", "Meeting at a point = intersecting.", "Parallel lines NEVER meet."],
    shortcut: "Cross = intersect; never cross = parallel.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_parallel_lines_q5",
    topicId: "math2_ch11_parallel_lines",
    text: "The lines on a ruled notebook page are examples of ____.",
    options: [
      { text: "Vertical parallel lines", type: "concept_error" },
      { text: "Horizontal parallel lines", type: "correct" },
      { text: "Curved parallel lines", type: "concept_error" },
      { text: "Diagonal parallel lines", type: "concept_error" },
    ],
    explanation: "Ruled notebook lines go from left to right (horizontal) and never meet — horizontal parallel lines.",
    solutionSteps: ["Notebook lines go left to right → horizontal.", "They never meet → parallel.", "Answer: horizontal parallel lines."],
    shortcut: "Ruled lines = horizontal + parallel.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_parallel_lines_q6",
    topicId: "math2_ch11_parallel_lines",
    text: "Mohan draws two lines. They meet at the centre. Are they parallel?",
    options: [
      { text: "Yes, because they are straight", type: "concept_error" },
      { text: "No, because they meet (intersect)", type: "correct" },
      { text: "Yes, because they are long", type: "guessing" },
      { text: "Cannot say", type: "partial_logic" },
    ],
    explanation: "Parallel lines NEVER meet. If Mohan's lines meet at the centre, they are intersecting lines, not parallel.",
    solutionSteps: ["Parallel = never meet.", "Mohan's lines meet → not parallel.", "They are intersecting lines."],
    shortcut: "Any meeting point = NOT parallel.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_parallel_lines_q7",
    topicId: "math2_ch11_parallel_lines",
    text: "Which letter has two vertical parallel lines?",
    options: [
      { text: "O", type: "concept_error" },
      { text: "H", type: "correct" },
      { text: "T", type: "concept_error" },
      { text: "C", type: "concept_error" },
    ],
    explanation: "The letter H has two vertical lines running parallel to each other, connected by a horizontal bar in the middle.",
    solutionSteps: ["H → two vertical lines on left and right.", "They run side by side and don't meet.", "Two vertical parallel lines."],
    shortcut: "H = two parallel vertical sticks.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_parallel_lines_q8",
    topicId: "math2_ch11_parallel_lines",
    text: "In a square, which sides are parallel to each other?",
    options: [
      { text: "No sides are parallel", type: "concept_error" },
      { text: "Only the top and bottom sides", type: "partial_logic" },
      { text: "Both pairs of opposite sides", type: "correct" },
      { text: "Only the left and right sides", type: "partial_logic" },
    ],
    explanation: "In a square, both pairs of opposite sides are parallel: top-bottom are parallel AND left-right are parallel.",
    solutionSteps: ["Square has 4 equal sides.", "Top and bottom run in same direction → parallel.", "Left and right run in same direction → parallel.", "Both pairs are parallel."],
    shortcut: "Square = 2 pairs of parallel sides.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },

  // ── math2_ch11_shapes_from_lines (8 Qs)
  {
    questionId: "math2_ch11_shapes_from_lines_q1",
    topicId: "math2_ch11_shapes_from_lines",
    text: "How many straight lines are needed to draw a triangle?",
    options: [
      { text: "2", type: "concept_error" },
      { text: "3", type: "correct" },
      { text: "4", type: "concept_error" },
      { text: "5", type: "guessing" },
    ],
    explanation: "A triangle has 3 sides, each made of one straight line. So 3 straight lines form a triangle.",
    solutionSteps: ["Triangle = 3 sides.", "Each side = 1 straight line.", "Total = 3 straight lines."],
    shortcut: "Tri = 3 = 3 lines.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_shapes_from_lines_q2",
    topicId: "math2_ch11_shapes_from_lines",
    text: "A square is made of ____ straight lines.",
    options: [
      { text: "3", type: "concept_error" },
      { text: "4", type: "correct" },
      { text: "5", type: "concept_error" },
      { text: "6", type: "guessing" },
    ],
    explanation: "A square has 4 equal sides, each a straight line. So 4 straight lines make a square.",
    solutionSteps: ["Square = 4 sides.", "4 sides = 4 straight lines."],
    shortcut: "4 sides = 4 lines.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_shapes_from_lines_q3",
    topicId: "math2_ch11_shapes_from_lines",
    text: "Which shape can be made with exactly 0 straight lines?",
    options: [
      { text: "Triangle", type: "concept_error" },
      { text: "Rectangle", type: "concept_error" },
      { text: "Circle", type: "correct" },
      { text: "Pentagon", type: "concept_error" },
    ],
    explanation: "A circle has no straight lines — it is one continuous curved line.",
    solutionSteps: ["Circle → round, no corners.", "No corners = no straight lines.", "0 straight lines."],
    shortcut: "Circle = 0 straight lines.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_shapes_from_lines_q4",
    topicId: "math2_ch11_shapes_from_lines",
    text: "Priya uses 6 straight lines to draw a shape. Which shape could she have drawn?",
    options: [
      { text: "Triangle (3 lines)", type: "concept_error" },
      { text: "Square (4 lines)", type: "concept_error" },
      { text: "Hexagon (6 lines)", type: "correct" },
      { text: "Circle (0 lines)", type: "concept_error" },
    ],
    explanation: "A hexagon has 6 sides, so it needs 6 straight lines. A triangle needs 3, a square needs 4.",
    solutionSteps: ["6 lines = 6 sides.", "Shape with 6 sides = hexagon."],
    shortcut: "Count sides = count lines needed.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_shapes_from_lines_q5",
    topicId: "math2_ch11_shapes_from_lines",
    text: "A rectangle has ____ pairs of parallel sides.",
    options: [
      { text: "0", type: "concept_error" },
      { text: "1", type: "concept_error" },
      { text: "2", type: "correct" },
      { text: "4", type: "partial_logic" },
    ],
    explanation: "A rectangle has 2 pairs of parallel sides: the two longer sides are parallel, and the two shorter sides are parallel.",
    solutionSteps: ["Rectangle has 4 sides.", "Top and bottom are parallel.", "Left and right are parallel.", "2 pairs of parallel sides."],
    shortcut: "Rectangle = 2 pairs parallel.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_shapes_from_lines_q6",
    topicId: "math2_ch11_shapes_from_lines",
    text: "Amit draws a shape with 5 straight lines and 5 corners. What shape is it?",
    options: [
      { text: "Square", type: "concept_error" },
      { text: "Triangle", type: "concept_error" },
      { text: "Pentagon", type: "correct" },
      { text: "Hexagon", type: "concept_error" },
    ],
    explanation: "A shape with 5 sides and 5 corners is a pentagon.",
    solutionSteps: ["5 lines = 5 sides.", "5 sides + 5 corners = pentagon."],
    shortcut: "Penta = 5.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_shapes_from_lines_q7",
    topicId: "math2_ch11_shapes_from_lines",
    text: "How many more lines does a square need than a triangle?",
    options: [
      { text: "0", type: "concept_error" },
      { text: "1", type: "correct" },
      { text: "2", type: "concept_error" },
      { text: "3", type: "guessing" },
    ],
    explanation: "Square needs 4 lines; triangle needs 3 lines. 4 − 3 = 1 more line.",
    solutionSteps: ["Square = 4 lines.", "Triangle = 3 lines.", "4 − 3 = 1."],
    shortcut: "4 − 3 = 1.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },
  {
    questionId: "math2_ch11_shapes_from_lines_q8",
    topicId: "math2_ch11_shapes_from_lines",
    text: "Which of these shapes uses ONLY curved lines?",
    options: [
      { text: "Triangle", type: "concept_error" },
      { text: "Rectangle", type: "concept_error" },
      { text: "Oval (ellipse)", type: "correct" },
      { text: "Pentagon", type: "concept_error" },
    ],
    explanation: "An oval (ellipse) is made entirely of curved lines. Triangles, rectangles, and pentagons use only straight lines.",
    solutionSteps: ["Triangle/Rectangle/Pentagon → straight sides.", "Oval → round, no corners → only curved."],
    shortcut: "Round shape = curved lines only.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Lines and Lines",
  },

  // ── Chapter 12: Give and Take ── math2_ch12_subtraction_meaning (8 Qs)
  {
    questionId: "math2_ch12_subtraction_meaning_q1",
    topicId: "math2_ch12_subtraction_meaning",
    text: "Subtraction means ____.",
    options: [
      { text: "Adding more", type: "concept_error" },
      { text: "Taking away from a group", type: "correct" },
      { text: "Multiplying two numbers", type: "concept_error" },
      { text: "Putting groups together", type: "concept_error" },
    ],
    explanation: "Subtraction means taking away a part from a whole. It tells how many are left after removing some.",
    solutionSteps: ["Start with a group.", "Remove some from the group.", "Count what is left → subtraction."],
    shortcut: "Take away = subtract.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_meaning_q2",
    topicId: "math2_ch12_subtraction_meaning",
    text: "There are 8 apples. Raju eats 3. How many are left?",
    options: [
      { text: "11", type: "concept_error" },
      { text: "4", type: "calculation_error" },
      { text: "5", type: "correct" },
      { text: "6", type: "calculation_error" },
    ],
    explanation: "8 − 3 = 5. Start with 8 apples, remove 3, 5 are left.",
    solutionSteps: ["Start: 8 apples.", "Raju eats 3.", "8 − 3 = 5.", "5 apples left."],
    shortcut: "8 − 3 = 5.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_meaning_q3",
    topicId: "math2_ch12_subtraction_meaning",
    text: "Which symbol is used for subtraction?",
    options: [
      { text: "+", type: "concept_error" },
      { text: "−", type: "correct" },
      { text: "×", type: "concept_error" },
      { text: "=", type: "concept_error" },
    ],
    explanation: "The minus sign (−) is used for subtraction.",
    solutionSteps: ["+ means addition.", "− means subtraction.", "× means multiplication."],
    shortcut: "− = subtract.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_meaning_q4",
    topicId: "math2_ch12_subtraction_meaning",
    text: "12 − 12 = ____.",
    options: [
      { text: "12", type: "concept_error" },
      { text: "1", type: "calculation_error" },
      { text: "0", type: "correct" },
      { text: "24", type: "concept_error" },
    ],
    explanation: "When you subtract a number from itself, the answer is always 0. 12 − 12 = 0.",
    solutionSteps: ["12 − 12.", "Same number taken away from itself.", "Nothing left = 0."],
    shortcut: "n − n = 0 always.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_meaning_q5",
    topicId: "math2_ch12_subtraction_meaning",
    text: "15 − 0 = ____.",
    options: [
      { text: "0", type: "concept_error" },
      { text: "1", type: "calculation_error" },
      { text: "14", type: "calculation_error" },
      { text: "15", type: "correct" },
    ],
    explanation: "Subtracting 0 from any number gives the same number. 15 − 0 = 15.",
    solutionSteps: ["Nothing is taken away.", "15 stays as 15.", "15 − 0 = 15."],
    shortcut: "n − 0 = n.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_meaning_q6",
    topicId: "math2_ch12_subtraction_meaning",
    text: "Sneha has 20 stickers. She gives 7 to her friend. How many does she have now?",
    options: [
      { text: "27", type: "concept_error" },
      { text: "12", type: "calculation_error" },
      { text: "13", type: "correct" },
      { text: "14", type: "calculation_error" },
    ],
    explanation: "20 − 7 = 13. Sneha gives away 7 stickers from her 20.",
    solutionSteps: ["Start: 20 stickers.", "Gives 7 away.", "20 − 7 = 13."],
    shortcut: "20 − 7 = 13.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_meaning_q7",
    topicId: "math2_ch12_subtraction_meaning",
    text: "In 18 − 5 = 13, the number 13 is called the ____.",
    options: [
      { text: "Minuend", type: "concept_error" },
      { text: "Subtrahend", type: "concept_error" },
      { text: "Difference", type: "correct" },
      { text: "Sum", type: "misinterpretation" },
    ],
    explanation: "The result of a subtraction is called the difference. In 18 − 5 = 13, the difference is 13.",
    solutionSteps: ["18 is the minuend (starting number).", "5 is the subtrahend (taken away).", "13 is the difference (result)."],
    shortcut: "Answer of subtraction = difference.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_meaning_q8",
    topicId: "math2_ch12_subtraction_meaning",
    text: "Which story matches 9 − 4 = 5?",
    options: [
      { text: "Rohan has 4 balls and gets 9 more.", type: "concept_error" },
      { text: "Rohan has 9 balls and gives 4 away.", type: "correct" },
      { text: "Rohan has 5 balls and gets 4 more.", type: "concept_error" },
      { text: "Rohan has 9 balls and gets 4 more.", type: "concept_error" },
    ],
    explanation: "9 − 4 = 5 means starting with 9 and giving away 4, leaving 5. 'Rohan has 9 balls and gives 4 away.'",
    solutionSteps: ["9 is what Rohan starts with.", "4 is given away.", "5 is what is left.", "Match: 9 balls, gives 4."],
    shortcut: "Bigger number − smaller number = what's left.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },

  // ── math2_ch12_subtraction_word_problems (8 Qs)
  {
    questionId: "math2_ch12_subtraction_word_problems_q1",
    topicId: "math2_ch12_subtraction_word_problems",
    text: "A tree has 25 mangoes. 10 fall down. How many are still on the tree?",
    options: [
      { text: "35", type: "concept_error" },
      { text: "14", type: "calculation_error" },
      { text: "15", type: "correct" },
      { text: "16", type: "calculation_error" },
    ],
    explanation: "25 − 10 = 15. After 10 mangoes fall, 15 remain on the tree.",
    solutionSteps: ["Total mangoes: 25.", "Fall down: 10.", "25 − 10 = 15."],
    shortcut: "25 − 10 = 15.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_word_problems_q2",
    topicId: "math2_ch12_subtraction_word_problems",
    text: "A class has 30 students. 8 are absent. How many are present?",
    options: [
      { text: "38", type: "concept_error" },
      { text: "22", type: "correct" },
      { text: "21", type: "calculation_error" },
      { text: "23", type: "calculation_error" },
    ],
    explanation: "30 − 8 = 22. With 8 students absent, 22 are present.",
    solutionSteps: ["Total students: 30.", "Absent: 8.", "30 − 8 = 22."],
    shortcut: "30 − 8 = 22.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_word_problems_q3",
    topicId: "math2_ch12_subtraction_word_problems",
    text: "Meena saved ₹50. She spent ₹28. How much does she have left?",
    options: [
      { text: "₹78", type: "concept_error" },
      { text: "₹21", type: "calculation_error" },
      { text: "₹22", type: "correct" },
      { text: "₹32", type: "calculation_error" },
    ],
    explanation: "50 − 28 = 22. Meena has ₹22 left after spending ₹28.",
    solutionSteps: ["Saved: ₹50.", "Spent: ₹28.", "50 − 28 = 22.", "₹22 left."],
    shortcut: "50 − 28: borrow → 10 + 0 − 8 = 2, 4 − 2 = 2 → 22.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_word_problems_q4",
    topicId: "math2_ch12_subtraction_word_problems",
    text: "A shop had 45 pencils. 17 were sold. How many are left?",
    options: [
      { text: "62", type: "concept_error" },
      { text: "28", type: "correct" },
      { text: "27", type: "calculation_error" },
      { text: "38", type: "calculation_error" },
    ],
    explanation: "45 − 17 = 28. After selling 17, 28 pencils remain.",
    solutionSteps: ["Total: 45.", "Sold: 17.", "45 − 17 = 28.", "28 pencils left."],
    shortcut: "45 − 17: ones: 5 − 7 needs borrowing → 15 − 7 = 8; tens: 3 − 1 = 2 → 28.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_word_problems_q5",
    topicId: "math2_ch12_subtraction_word_problems",
    text: "Rani had 60 stamps. She gave 35 to her cousin. How many does she have now?",
    options: [
      { text: "95", type: "concept_error" },
      { text: "24", type: "calculation_error" },
      { text: "25", type: "correct" },
      { text: "26", type: "calculation_error" },
    ],
    explanation: "60 − 35 = 25. After giving away 35 stamps, Rani has 25 left.",
    solutionSteps: ["Start: 60.", "Gave away: 35.", "60 − 35 = 25."],
    shortcut: "60 − 35 = 25.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_word_problems_q6",
    topicId: "math2_ch12_subtraction_word_problems",
    text: "A bus had 72 passengers. 19 got off. How many are still on the bus?",
    options: [
      { text: "91", type: "concept_error" },
      { text: "52", type: "calculation_error" },
      { text: "53", type: "correct" },
      { text: "54", type: "calculation_error" },
    ],
    explanation: "72 − 19 = 53. After 19 passengers get off, 53 remain.",
    solutionSteps: ["Start: 72.", "Got off: 19.", "72 − 19 = 53."],
    shortcut: "72 − 19: ones 2 − 9 → borrow → 12 − 9 = 3; tens 6 − 1 = 5 → 53.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_word_problems_q7",
    topicId: "math2_ch12_subtraction_word_problems",
    text: "There are 99 balloons. 40 burst. How many are left?",
    options: [
      { text: "139", type: "concept_error" },
      { text: "58", type: "calculation_error" },
      { text: "59", type: "correct" },
      { text: "60", type: "calculation_error" },
    ],
    explanation: "99 − 40 = 59. After 40 balloons burst, 59 remain.",
    solutionSteps: ["Start: 99.", "Burst: 40.", "99 − 40 = 59."],
    shortcut: "99 − 40 = 59.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_subtraction_word_problems_q8",
    topicId: "math2_ch12_subtraction_word_problems",
    text: "Kiran read 36 pages of a 50-page book. How many pages are left to read?",
    options: [
      { text: "86", type: "concept_error" },
      { text: "13", type: "calculation_error" },
      { text: "14", type: "correct" },
      { text: "15", type: "calculation_error" },
    ],
    explanation: "50 − 36 = 14. Kiran has 14 pages left to read.",
    solutionSteps: ["Total pages: 50.", "Pages read: 36.", "50 − 36 = 14."],
    shortcut: "50 − 36: ones 0 − 6 → borrow → 10 − 6 = 4; tens 4 − 3 = 1 → 14.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },

  // ── math2_ch12_mental_math_subtract (8 Qs)
  {
    questionId: "math2_ch12_mental_math_subtract_q1",
    topicId: "math2_ch12_mental_math_subtract",
    text: "What is 50 − 20 in your head?",
    options: [
      { text: "20", type: "calculation_error" },
      { text: "25", type: "calculation_error" },
      { text: "30", type: "correct" },
      { text: "70", type: "concept_error" },
    ],
    explanation: "50 − 20 = 30. Think: 5 tens − 2 tens = 3 tens = 30.",
    solutionSteps: ["50 = 5 tens.", "20 = 2 tens.", "5 − 2 = 3 tens = 30."],
    shortcut: "Subtract tens: 5 − 2 = 3, add zero → 30.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_mental_math_subtract_q2",
    topicId: "math2_ch12_mental_math_subtract",
    text: "What is 85 − 5 mentally?",
    options: [
      { text: "70", type: "calculation_error" },
      { text: "79", type: "calculation_error" },
      { text: "80", type: "correct" },
      { text: "90", type: "concept_error" },
    ],
    explanation: "85 − 5 = 80. The ones cancel: 5 − 5 = 0. Tens stay: 8 tens → 80.",
    solutionSteps: ["85 = 8 tens + 5 ones.", "Subtract 5 ones.", "8 tens + 0 ones = 80."],
    shortcut: "Subtract ones only when tens untouched.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_mental_math_subtract_q3",
    topicId: "math2_ch12_mental_math_subtract",
    text: "98 − 8 = ____.",
    options: [
      { text: "80", type: "calculation_error" },
      { text: "89", type: "calculation_error" },
      { text: "90", type: "correct" },
      { text: "88", type: "calculation_error" },
    ],
    explanation: "98 − 8 = 90. Subtract ones: 8 − 8 = 0. Tens unchanged: 9 tens → 90.",
    solutionSteps: ["98 = 9 tens 8 ones.", "8 ones − 8 ones = 0.", "9 tens = 90."],
    shortcut: "98 − 8 = 90.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_mental_math_subtract_q4",
    topicId: "math2_ch12_mental_math_subtract",
    text: "67 − 7 = ____.",
    options: [
      { text: "57", type: "calculation_error" },
      { text: "59", type: "calculation_error" },
      { text: "60", type: "correct" },
      { text: "74", type: "concept_error" },
    ],
    explanation: "67 − 7 = 60. Ones: 7 − 7 = 0. Tens: 6 tens = 60.",
    solutionSteps: ["67 = 6 tens 7 ones.", "7 ones − 7 ones = 0.", "Answer: 60."],
    shortcut: "n7 − 7 = n0.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_mental_math_subtract_q5",
    topicId: "math2_ch12_mental_math_subtract",
    text: "What is 100 − 50 mentally?",
    options: [
      { text: "40", type: "calculation_error" },
      { text: "50", type: "correct" },
      { text: "60", type: "calculation_error" },
      { text: "150", type: "concept_error" },
    ],
    explanation: "100 − 50 = 50. 10 tens − 5 tens = 5 tens = 50.",
    solutionSteps: ["100 = 10 tens.", "50 = 5 tens.", "10 − 5 = 5 tens = 50."],
    shortcut: "Half of 100 = 50.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_mental_math_subtract_q6",
    topicId: "math2_ch12_mental_math_subtract",
    text: "Solve in your head: 74 − 4 = ____.",
    options: [
      { text: "60", type: "calculation_error" },
      { text: "68", type: "calculation_error" },
      { text: "70", type: "correct" },
      { text: "78", type: "concept_error" },
    ],
    explanation: "74 − 4 = 70. The ones digits cancel (4 − 4 = 0). Tens remain: 7 tens = 70.",
    solutionSteps: ["74 = 7 tens 4 ones.", "4 ones − 4 ones = 0.", "Answer: 70."],
    shortcut: "74 − 4 = 70.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_mental_math_subtract_q7",
    topicId: "math2_ch12_mental_math_subtract",
    text: "45 − 15 = ____. (Think in your head using tens.)",
    options: [
      { text: "20", type: "calculation_error" },
      { text: "25", type: "calculation_error" },
      { text: "30", type: "correct" },
      { text: "35", type: "calculation_error" },
    ],
    explanation: "45 − 15 = 30. Ones: 5 − 5 = 0. Tens: 4 − 1 = 3 → 30.",
    solutionSteps: ["Ones: 5 − 5 = 0.", "Tens: 4 − 1 = 3.", "Answer: 30."],
    shortcut: "Subtract tens and ones separately: 45 − 15 = 30.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_mental_math_subtract_q8",
    topicId: "math2_ch12_mental_math_subtract",
    text: "55 − 25 = ____.",
    options: [
      { text: "20", type: "calculation_error" },
      { text: "28", type: "calculation_error" },
      { text: "30", type: "correct" },
      { text: "80", type: "concept_error" },
    ],
    explanation: "55 − 25 = 30. Ones: 5 − 5 = 0. Tens: 5 − 2 = 3 → 30.",
    solutionSteps: ["Ones: 5 − 5 = 0.", "Tens: 5 − 2 = 3.", "Answer: 30."],
    shortcut: "55 − 25 = 30.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },

  // ── math2_ch12_addition_subtraction_link (8 Qs)
  {
    questionId: "math2_ch12_addition_subtraction_link_q1",
    topicId: "math2_ch12_addition_subtraction_link",
    text: "If 6 + 4 = 10, then 10 − 4 = ____.",
    options: [
      { text: "4", type: "concept_error" },
      { text: "14", type: "concept_error" },
      { text: "6", type: "correct" },
      { text: "5", type: "calculation_error" },
    ],
    explanation: "Addition and subtraction are linked. If 6 + 4 = 10, then 10 − 4 = 6.",
    solutionSteps: ["6 + 4 = 10.", "Reverse: 10 − 4 = 6."],
    shortcut: "Addition fact → subtraction fact by reversing.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_addition_subtraction_link_q2",
    topicId: "math2_ch12_addition_subtraction_link",
    text: "If 13 + 7 = 20, then 20 − 7 = ____.",
    options: [
      { text: "7", type: "concept_error" },
      { text: "27", type: "concept_error" },
      { text: "13", type: "correct" },
      { text: "12", type: "calculation_error" },
    ],
    explanation: "If 13 + 7 = 20, then 20 − 7 = 13. Subtraction undoes addition.",
    solutionSteps: ["13 + 7 = 20.", "Remove 7 from 20 → back to 13.", "20 − 7 = 13."],
    shortcut: "Subtraction undoes addition.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_addition_subtraction_link_q3",
    topicId: "math2_ch12_addition_subtraction_link",
    text: "Use addition to check: 35 − 12 = 23. Which addition confirms this?",
    options: [
      { text: "23 + 35 = 58", type: "concept_error" },
      { text: "12 + 23 = 35", type: "correct" },
      { text: "35 + 12 = 47", type: "concept_error" },
      { text: "23 + 12 = 24", type: "calculation_error" },
    ],
    explanation: "To check 35 − 12 = 23, add back: 12 + 23 = 35. The answer plus what was subtracted equals the original.",
    solutionSteps: ["Subtraction: 35 − 12 = 23.", "Check: add subtracted number back.", "12 + 23 = 35 ✓"],
    shortcut: "To check subtraction: add answer + subtracted number = original.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_addition_subtraction_link_q4",
    topicId: "math2_ch12_addition_subtraction_link",
    text: "If 8 + □ = 15, what is □?",
    options: [
      { text: "6", type: "calculation_error" },
      { text: "7", type: "correct" },
      { text: "8", type: "concept_error" },
      { text: "23", type: "concept_error" },
    ],
    explanation: "Think: 15 − 8 = 7. So □ = 7. Use subtraction to find the missing addend.",
    solutionSteps: ["8 + □ = 15.", "□ = 15 − 8.", "□ = 7."],
    shortcut: "Missing addend = total − known addend.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_addition_subtraction_link_q5",
    topicId: "math2_ch12_addition_subtraction_link",
    text: "Rohan scored 42 in a game. He lost 18 points. Use addition to find what he had before losing.",
    options: [
      { text: "24", type: "calculation_error" },
      { text: "50", type: "calculation_error" },
      { text: "60", type: "correct" },
      { text: "62", type: "calculation_error" },
    ],
    explanation: "After losing: 42. Lost: 18. Before = 42 + 18 = 60. Addition reverses the subtraction.",
    solutionSteps: ["End score: 42.", "Lost: 18.", "Original = 42 + 18 = 60."],
    shortcut: "If you lose and end with X, you had X + loss.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_addition_subtraction_link_q6",
    topicId: "math2_ch12_addition_subtraction_link",
    text: "□ − 9 = 14. What is □?",
    options: [
      { text: "5", type: "concept_error" },
      { text: "13", type: "calculation_error" },
      { text: "23", type: "correct" },
      { text: "22", type: "calculation_error" },
    ],
    explanation: "□ − 9 = 14 means □ = 14 + 9 = 23. Add to find the original number.",
    solutionSteps: ["□ − 9 = 14.", "□ = 14 + 9.", "□ = 23."],
    shortcut: "Missing start = answer + what was subtracted.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_addition_subtraction_link_q7",
    topicId: "math2_ch12_addition_subtraction_link",
    text: "Which of these is a subtraction fact linked to 30 + 50 = 80?",
    options: [
      { text: "80 + 30 = 110", type: "concept_error" },
      { text: "80 − 50 = 30", type: "correct" },
      { text: "50 − 30 = 20", type: "concept_error" },
      { text: "80 − 80 = 0", type: "concept_error" },
    ],
    explanation: "From 30 + 50 = 80, we can write: 80 − 50 = 30 or 80 − 30 = 50.",
    solutionSteps: ["30 + 50 = 80.", "Subtraction fact: 80 − 50 = 30."],
    shortcut: "a + b = c → c − b = a and c − a = b.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
  {
    questionId: "math2_ch12_addition_subtraction_link_q8",
    topicId: "math2_ch12_addition_subtraction_link",
    text: "Priya scored 55 marks. She lost 15 marks for wrong answers. Her final score was ____. Check using addition.",
    options: [
      { text: "30", type: "calculation_error" },
      { text: "38", type: "calculation_error" },
      { text: "40", type: "correct" },
      { text: "70", type: "concept_error" },
    ],
    explanation: "55 − 15 = 40. Check: 40 + 15 = 55 ✓. Priya's final score is 40.",
    solutionSteps: ["55 − 15 = 40.", "Check: 40 + 15 = 55 ✓.", "Final score = 40."],
    shortcut: "55 − 15 = 40; verify with 40 + 15 = 55.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Give and Take",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded 64 Class 2 Math v2 questions (Chapters 11-12).`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
