import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math3_ch5_2d_shapes — 8 Qs
  { questionId:"math3_ch5_2d_q1", topicId:"math3_ch5_2d_shapes", text:"How many sides does a triangle have?", options:[{text:"2",type:"concept_error"},{text:"3",type:"correct"},{text:"4",type:"calculation_error"},{text:"5",type:"misinterpretation"}], explanation:"A triangle has 3 sides and 3 corners.", solutionSteps:["Triangle = 3 sides + 3 corners."], shortcut:"Triangle = 3 sides.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_2d_q2", topicId:"math3_ch5_2d_shapes", text:"A square has how many EQUAL sides?", options:[{text:"2",type:"concept_error"},{text:"3",type:"misinterpretation"},{text:"4",type:"correct"},{text:"6",type:"calculation_error"}], explanation:"A square has 4 equal sides.", solutionSteps:["Square: all 4 sides same length."], shortcut:"Square = 4 equal sides.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_2d_q3", topicId:"math3_ch5_2d_shapes", text:"Which shape has NO sides or corners?", options:[{text:"Triangle",type:"concept_error"},{text:"Square",type:"concept_error"},{text:"Circle",type:"correct"},{text:"Pentagon",type:"misinterpretation"}], explanation:"A circle is a smooth curve — no straight sides, no corners.", solutionSteps:["Circle = 1 curved boundary.","No sides or corners."], shortcut:"Circle = 0 sides, 0 corners.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_2d_q4", topicId:"math3_ch5_2d_shapes", text:"Difference between square and rectangle?", options:[{text:"No difference",type:"concept_error"},{text:"Square has all sides equal; rectangle has only opposite sides equal",type:"correct"},{text:"Rectangle has 4 corners; square has 3",type:"misinterpretation"},{text:"Square is round",type:"guessing"}], explanation:"Square = all 4 sides equal. Rectangle = opposite sides equal, adjacent unequal.", solutionSteps:["Square: 4 equal sides.","Rectangle: 2 pairs of equal sides."], shortcut:"Square ⊂ rectangle (all squares are rectangles).", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_2d_q5", topicId:"math3_ch5_2d_shapes", text:"How many corners does a hexagon have?", options:[{text:"4",type:"concept_error"},{text:"5",type:"calculation_error"},{text:"6",type:"correct"},{text:"8",type:"calculation_error"}], explanation:"Hexagon: 6 sides and 6 corners.", solutionSteps:["Hexagon = 6 sides.","Same number of corners = 6."], shortcut:"Hex = 6.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_2d_q6", topicId:"math3_ch5_2d_shapes", text:"A 5-sided shape is called a…", options:[{text:"Hexagon",type:"calculation_error"},{text:"Pentagon",type:"correct"},{text:"Quadrilateral",type:"misinterpretation"},{text:"Triangle",type:"concept_error"}], explanation:"Penta = 5. A pentagon has 5 sides.", solutionSteps:["Pent = 5.","5-sided = pentagon."], shortcut:"Penta = 5.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_2d_q7", topicId:"math3_ch5_2d_shapes", text:"Number of sides + corners in a quadrilateral?", options:[{text:"4",type:"concept_error"},{text:"6",type:"calculation_error"},{text:"8",type:"correct"},{text:"12",type:"calculation_error"}], explanation:"Quadrilateral: 4 sides + 4 corners = 8.", solutionSteps:["Quadrilateral: 4 sides.","4 corners.","Total = 8."], shortcut:"Polygon: sides + corners = 2 × sides.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_2d_q8", topicId:"math3_ch5_2d_shapes", text:"Which is NOT a polygon?", options:[{text:"Triangle",type:"concept_error"},{text:"Pentagon",type:"concept_error"},{text:"Circle",type:"correct"},{text:"Hexagon",type:"concept_error"}], explanation:"Polygons have straight sides. Circles are curved — not polygons.", solutionSteps:["Polygon = closed shape with straight sides.","Circle has no straight sides → not a polygon."], shortcut:"Polygon = straight sides only.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },

  // math3_ch5_3d_shapes — 8 Qs
  { questionId:"math3_ch5_3d_q1", topicId:"math3_ch5_3d_shapes", text:"A cube has how many faces?", options:[{text:"4",type:"concept_error"},{text:"6",type:"correct"},{text:"8",type:"calculation_error"},{text:"12",type:"misinterpretation"}], explanation:"A cube has 6 square faces.", solutionSteps:["Top, bottom, front, back, left, right = 6 faces."], shortcut:"Cube = 6 faces.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_3d_q2", topicId:"math3_ch5_3d_shapes", text:"Number of edges in a cube?", options:[{text:"6",type:"concept_error"},{text:"8",type:"calculation_error"},{text:"12",type:"correct"},{text:"24",type:"misinterpretation"}], explanation:"A cube has 12 edges (where two faces meet).", solutionSteps:["Edges of cube = 12."], shortcut:"Cube: 6 faces, 12 edges, 8 vertices.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_3d_q3", topicId:"math3_ch5_3d_shapes", text:"Number of vertices in a cube?", options:[{text:"4",type:"concept_error"},{text:"6",type:"calculation_error"},{text:"8",type:"correct"},{text:"12",type:"misinterpretation"}], explanation:"A cube has 8 corners (vertices).", solutionSteps:["Cube vertices = 8."], shortcut:"Cube: 8 vertices.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_3d_q4", topicId:"math3_ch5_3d_shapes", text:"Which shape has only 1 curved surface and no flat face?", options:[{text:"Cube",type:"concept_error"},{text:"Cylinder",type:"misinterpretation"},{text:"Sphere",type:"correct"},{text:"Cone",type:"calculation_error"}], explanation:"Sphere = 1 curved surface, no flat face.", solutionSteps:["Sphere is entirely curved.","No flat surface."], shortcut:"Sphere = round all over.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_3d_q5", topicId:"math3_ch5_3d_shapes", text:"A cylinder has how many flat faces?", options:[{text:"0",type:"concept_error"},{text:"1",type:"calculation_error"},{text:"2",type:"correct"},{text:"3",type:"misinterpretation"}], explanation:"Cylinder = 2 flat circular faces (top + bottom) + 1 curved surface.", solutionSteps:["Cylinder: top + bottom circles = 2 flat faces.","Side = curved."], shortcut:"Cylinder: 2 flat, 1 curved.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_3d_q6", topicId:"math3_ch5_3d_shapes", text:"A cone has how many vertices (corners)?", options:[{text:"0",type:"concept_error"},{text:"1",type:"correct"},{text:"2",type:"calculation_error"},{text:"4",type:"misinterpretation"}], explanation:"Cone has 1 pointed tip = 1 vertex.", solutionSteps:["Cone has 1 pointed top.","That tip is its only vertex."], shortcut:"Cone = 1 vertex.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_3d_q7", topicId:"math3_ch5_3d_shapes", text:"Which is a 3D shape?", options:[{text:"Square",type:"concept_error"},{text:"Triangle",type:"concept_error"},{text:"Cube",type:"correct"},{text:"Circle",type:"misinterpretation"}], explanation:"Cube is solid (3D). The others are flat (2D).", solutionSteps:["3D = solid.","Cube = solid."], shortcut:"3D = can hold it.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_3d_q8", topicId:"math3_ch5_3d_shapes", text:"A dice is shaped like a…", options:[{text:"Sphere",type:"concept_error"},{text:"Cube",type:"correct"},{text:"Cone",type:"misinterpretation"},{text:"Cylinder",type:"calculation_error"}], explanation:"A standard dice has 6 equal square faces — a cube.", solutionSteps:["Dice = 6 equal sides.","6 equal square faces = cube."], shortcut:"Dice = cube.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },

  // math3_ch5_tiling — 8 Qs
  { questionId:"math3_ch5_ti_q1", topicId:"math3_ch5_tiling", text:"Tiling means…", options:[{text:"Drawing pictures",type:"concept_error"},{text:"Covering a surface with shapes that fit without gaps or overlaps",type:"correct"},{text:"Cutting shapes",type:"misinterpretation"},{text:"Painting walls",type:"guessing"}], explanation:"Tiling = covering completely with shapes; no gaps, no overlaps.", solutionSteps:["Tiling: no gaps, no overlaps.","Like floor tiles."], shortcut:"Tile = perfect cover.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_ti_q2", topicId:"math3_ch5_tiling", text:"Which shape CANNOT tile a flat surface alone?", options:[{text:"Square",type:"concept_error"},{text:"Triangle",type:"concept_error"},{text:"Regular pentagon",type:"correct"},{text:"Hexagon",type:"concept_error"}], explanation:"Regular pentagons leave gaps and cannot tile alone.", solutionSteps:["Squares, triangles, hexagons tile.","Regular pentagons do not."], shortcut:"Pentagons don't tile.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_ti_q3", topicId:"math3_ch5_tiling", text:"Honeycomb cells are shaped like…", options:[{text:"Squares",type:"concept_error"},{text:"Circles",type:"misinterpretation"},{text:"Hexagons",type:"correct"},{text:"Triangles",type:"partial_logic"}], explanation:"Bees build hexagonal cells — strong AND space-efficient tiling.", solutionSteps:["Honeycomb = hexagons.","Hexagons tile perfectly."], shortcut:"Honeycomb = hexagon.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_ti_q4", topicId:"math3_ch5_tiling", text:"Do circles tile a surface?", options:[{text:"Yes, perfectly",type:"concept_error"},{text:"No, they leave gaps",type:"correct"},{text:"Yes, with overlap",type:"partial_logic"},{text:"Only on Tuesdays",type:"guessing"}], explanation:"Circles leave curved gaps between them. They don't tile.", solutionSteps:["Curved sides → gaps remain.","Cannot tile."], shortcut:"Circles don't tile.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_ti_q5", topicId:"math3_ch5_tiling", text:"Floor tiles in homes are usually…", options:[{text:"Triangles",type:"partial_logic"},{text:"Squares or rectangles",type:"correct"},{text:"Pentagons",type:"misinterpretation"},{text:"Circles",type:"concept_error"}], explanation:"Squares and rectangles are easiest to manufacture and tile.", solutionSteps:["Squares/rectangles tile easily.","Most floor tiles are these."], shortcut:"Floor tiles = square/rectangle.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_ti_q6", topicId:"math3_ch5_tiling", text:"To tile without gaps, the corner angles must add up to…", options:[{text:"180°",type:"concept_error"},{text:"360°",type:"correct"},{text:"90°",type:"misinterpretation"},{text:"45°",type:"calculation_error"}], explanation:"Angles around a point sum to 360°. For tiling, that's the rule.", solutionSteps:["Full turn = 360°.","Tiles must fit around a vertex with 360° total."], shortcut:"Tiling: 360° at each corner.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_ti_q7", topicId:"math3_ch5_tiling", text:"Equilateral triangles tile by joining how many at each vertex?", options:[{text:"3",type:"concept_error"},{text:"4",type:"calculation_error"},{text:"6",type:"correct"},{text:"8",type:"misinterpretation"}], explanation:"Each angle is 60°. 6 × 60° = 360°.", solutionSteps:["Equilateral triangle angle = 60°.","6 × 60° = 360°.","So 6 triangles meet at a vertex."], shortcut:"Triangle tile: 6 at a corner.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_ti_q8", topicId:"math3_ch5_tiling", text:"How can you check if a pattern is a true tiling?", options:[{text:"It has many colours",type:"concept_error"},{text:"No gaps and no overlaps anywhere",type:"correct"},{text:"It uses only triangles",type:"misinterpretation"},{text:"It looks colourful",type:"guessing"}], explanation:"True tiling: every point on the surface is covered exactly once.", solutionSteps:["No empty space.","No double covering."], shortcut:"Tile = no gap, no overlap.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },

  // math3_ch5_symmetry — 8 Qs
  { questionId:"math3_ch5_sy_q1", topicId:"math3_ch5_symmetry", text:"A shape has a line of symmetry if…", options:[{text:"It is colourful",type:"concept_error"},{text:"Folding along the line makes both halves match exactly",type:"correct"},{text:"It has 4 sides",type:"misinterpretation"},{text:"It is round",type:"guessing"}], explanation:"Symmetry: fold along a line and both halves overlap perfectly.", solutionSteps:["Fold → both halves match.","That fold line = line of symmetry."], shortcut:"Fold → match = symmetric.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_sy_q2", topicId:"math3_ch5_symmetry", text:"How many lines of symmetry does a square have?", options:[{text:"1",type:"concept_error"},{text:"2",type:"calculation_error"},{text:"4",type:"correct"},{text:"8",type:"misinterpretation"}], explanation:"Square: 2 diagonals + 2 mid-lines (vertical and horizontal) = 4 lines.", solutionSteps:["Vertical, horizontal mid-lines: 2.","Both diagonals: 2.","Total: 4 lines."], shortcut:"Square = 4 lines of symmetry.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_sy_q3", topicId:"math3_ch5_symmetry", text:"How many lines of symmetry does a rectangle have?", options:[{text:"1",type:"concept_error"},{text:"2",type:"correct"},{text:"4",type:"calculation_error"},{text:"0",type:"misinterpretation"}], explanation:"Rectangle: 1 vertical + 1 horizontal mid-line (NOT diagonals).", solutionSteps:["Vertical mid-line: 1.","Horizontal mid-line: 1.","Diagonals don't work (sides unequal).","Total: 2 lines."], shortcut:"Rectangle = 2 lines.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_sy_q4", topicId:"math3_ch5_symmetry", text:"A circle has how many lines of symmetry?", options:[{text:"4",type:"concept_error"},{text:"8",type:"calculation_error"},{text:"Infinitely many",type:"correct"},{text:"None",type:"misinterpretation"}], explanation:"Any line through the centre is a line of symmetry — infinitely many.", solutionSteps:["Every diameter = line of symmetry.","Infinitely many diameters → infinite symmetry lines."], shortcut:"Circle = infinite symmetry lines.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_sy_q5", topicId:"math3_ch5_symmetry", text:"Which letter has no line of symmetry?", options:[{text:"A",type:"concept_error"},{text:"H",type:"concept_error"},{text:"F",type:"correct"},{text:"O",type:"misinterpretation"}], explanation:"F has no line of symmetry. A (vertical), H (both), O (any) all have symmetry.", solutionSteps:["F: no fold matches.","Other letters here have symmetry."], shortcut:"F, G, J, L, N, P, Q, R, S, Z have no symmetry.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_sy_q6", topicId:"math3_ch5_symmetry", text:"An equilateral triangle has how many lines of symmetry?", options:[{text:"1",type:"concept_error"},{text:"2",type:"calculation_error"},{text:"3",type:"correct"},{text:"6",type:"misinterpretation"}], explanation:"Equilateral triangle: 3 lines, each from a vertex to the midpoint of the opposite side.", solutionSteps:["3 vertices, each gives 1 line.","Total: 3 lines."], shortcut:"Equilateral = 3 lines.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_sy_q7", topicId:"math3_ch5_symmetry", text:"A heart shape has how many lines of symmetry?", options:[{text:"0",type:"concept_error"},{text:"1",type:"correct"},{text:"2",type:"calculation_error"},{text:"Many",type:"misinterpretation"}], explanation:"A heart has only one vertical line of symmetry.", solutionSteps:["Vertical fold → both halves match.","Horizontal fold doesn't.","→ 1 line."], shortcut:"Heart = 1 line.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },
  { questionId:"math3_ch5_sy_q8", topicId:"math3_ch5_symmetry", text:"Which is NOT symmetric?", options:[{text:"Square",type:"concept_error"},{text:"Letter F",type:"correct"},{text:"Circle",type:"misinterpretation"},{text:"Equilateral triangle",type:"concept_error"}], explanation:"F has no line of symmetry.", solutionSteps:["Test each shape.","F: no fold matches."], shortcut:"F = no symmetry.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Shapes and Designs" },

  // math3_ch6_word_problems_add — 8 Qs
  { questionId:"math3_ch6_wa_q1", topicId:"math3_ch6_word_problems_add", text:"Rita has 234 stamps. Her brother gives her 156 more. How many stamps in total?", options:[{text:"78",type:"misinterpretation"},{text:"390",type:"correct"},{text:"380",type:"calculation_error"},{text:"400",type:"calculation_error"}], explanation:"234 + 156: ones 4+6=10 → 0 c1. Tens 3+5+1=9. Hundreds 2+1=3. → 390.", solutionSteps:["Total = 234 + 156.","Ones: 4+6=10, c1.","Tens: 3+5+1=9.","Hundreds: 2+1=3.","Total = 390."], shortcut:"'Total' = add.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_wa_q2", topicId:"math3_ch6_word_problems_add", text:"Which keyword means ADD in a word problem?", options:[{text:"Difference",type:"concept_error"},{text:"Altogether",type:"correct"},{text:"Left",type:"misinterpretation"},{text:"Less",type:"concept_error"}], explanation:"'Altogether' means total, which means addition.", solutionSteps:["Altogether = total = add."], shortcut:"Altogether = +.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_wa_q3", topicId:"math3_ch6_word_problems_add", text:"There are 125 boys and 98 girls in a fair. Total people?", options:[{text:"223",type:"correct"},{text:"123",type:"calculation_error"},{text:"233",type:"calculation_error"},{text:"213",type:"calculation_error"}], explanation:"125 + 98 = 223.", solutionSteps:["Ones: 5+8=13. Write 3, carry 1.","Tens: 2+9+1=12. Write 2, carry 1.","Hundreds: 1+0+1=2.","Total = 223."], shortcut:"Add carefully with carrying.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_wa_q4", topicId:"math3_ch6_word_problems_add", text:"A library has 567 books. The librarian adds 245 new books. New total?", options:[{text:"322",type:"misinterpretation"},{text:"812",type:"correct"},{text:"712",type:"calculation_error"},{text:"802",type:"calculation_error"}], explanation:"567 + 245 = 812.", solutionSteps:["Ones: 7+5=12. Write 2, carry 1.","Tens: 6+4+1=11. Write 1, carry 1.","Hundreds: 5+2+1=8.","Total = 812."], shortcut:"Read carefully — 'adds' = +.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_wa_q5", topicId:"math3_ch6_word_problems_add", text:"A box has 75 chocolates. Another has 95. Sum?", options:[{text:"170",type:"correct"},{text:"160",type:"calculation_error"},{text:"180",type:"calculation_error"},{text:"165",type:"calculation_error"}], explanation:"75 + 95 = 170.", solutionSteps:["Ones: 5+5=10. Write 0, carry 1.","Tens: 7+9+1=17.","Total = 170."], shortcut:"Add ones, then tens with carry.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_wa_q6", topicId:"math3_ch6_word_problems_add", text:"Pinki collected 158 shells on Monday and 142 on Tuesday. Total shells?", options:[{text:"290",type:"calculation_error"},{text:"300",type:"correct"},{text:"308",type:"calculation_error"},{text:"310",type:"calculation_error"}], explanation:"158 + 142 = 300.", solutionSteps:["Ones: 8+2=10. Write 0, carry 1.","Tens: 5+4+1=10. Write 0, carry 1.","Hundreds: 1+1+1=3.","Total = 300."], shortcut:"Double-carry possible.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_wa_q7", topicId:"math3_ch6_word_problems_add", text:"Three classes have 32, 28, and 35 students. Total students in all 3?", options:[{text:"95",type:"correct"},{text:"85",type:"calculation_error"},{text:"100",type:"calculation_error"},{text:"105",type:"misinterpretation"}], explanation:"32 + 28 + 35: 32+28=60. 60+35=95.", solutionSteps:["First two: 32 + 28 = 60.","Add third: 60 + 35 = 95."], shortcut:"Add pairs.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_wa_q8", topicId:"math3_ch6_word_problems_add", text:"A bookshop sold 119 books in week 1 and 161 in week 2. Total?", options:[{text:"280",type:"correct"},{text:"270",type:"calculation_error"},{text:"290",type:"calculation_error"},{text:"281",type:"calculation_error"}], explanation:"119 + 161 = 280.", solutionSteps:["Ones: 9+1=10. Write 0, carry 1.","Tens: 1+6+1=8.","Hundreds: 1+1=2.","Total = 280."], shortcut:"Always check carries.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },

  // math3_ch6_word_problems_sub — 8 Qs
  { questionId:"math3_ch6_ws_q1", topicId:"math3_ch6_word_problems_sub", text:"Ramu had 458 marbles. He gave 173 to his sister. Marbles left?", options:[{text:"631",type:"misinterpretation"},{text:"285",type:"correct"},{text:"385",type:"calculation_error"},{text:"275",type:"calculation_error"}], explanation:"458 − 173 = 285.", solutionSteps:["Ones: 8−3=5.","Tens: 5−7 → borrow → 15−7=8. (4→3)","Hundreds: 3−1=2 (after the borrow on tens, the original 4 became 3).","Diff = 285."], shortcut:"'Left' = subtract.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_ws_q2", topicId:"math3_ch6_word_problems_sub", text:"Which keyword usually means subtraction?", options:[{text:"Total",type:"concept_error"},{text:"Sum",type:"concept_error"},{text:"Difference",type:"correct"},{text:"Altogether",type:"misinterpretation"}], explanation:"'Difference' explicitly means subtraction.", solutionSteps:["Difference = subtraction."], shortcut:"Difference = −.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_ws_q3", topicId:"math3_ch6_word_problems_sub", text:"A bag has 250 sweets. 75 are eaten. Sweets remaining?", options:[{text:"325",type:"misinterpretation"},{text:"175",type:"correct"},{text:"185",type:"calculation_error"},{text:"165",type:"calculation_error"}], explanation:"250 − 75 = 175.", solutionSteps:["250 − 75 = 175."], shortcut:"Sweets eaten = subtract.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_ws_q4", topicId:"math3_ch6_word_problems_sub", text:"Class A has 47 students; Class B has 39. How many MORE in A?", options:[{text:"6",type:"calculation_error"},{text:"8",type:"correct"},{text:"86",type:"misinterpretation"},{text:"4",type:"calculation_error"}], explanation:"47 − 39 = 8.", solutionSteps:["A − B = 47 − 39 = 8."], shortcut:"'More than' = subtract.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_ws_q5", topicId:"math3_ch6_word_problems_sub", text:"A tank holds 500 L. After use, 180 L is left. How much was used?", options:[{text:"320",type:"correct"},{text:"680",type:"misinterpretation"},{text:"300",type:"calculation_error"},{text:"380",type:"calculation_error"}], explanation:"Used = Total − Left = 500 − 180 = 320 L.", solutionSteps:["Used = total − left.","500 − 180 = 320."], shortcut:"Used = total − remaining.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_ws_q6", topicId:"math3_ch6_word_problems_sub", text:"A book has 200 pages. Riya read 75. Pages left?", options:[{text:"275",type:"misinterpretation"},{text:"125",type:"correct"},{text:"135",type:"calculation_error"},{text:"100",type:"calculation_error"}], explanation:"200 − 75 = 125.", solutionSteps:["200 − 75 = 125."], shortcut:"'Left' = subtract.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_ws_q7", topicId:"math3_ch6_word_problems_sub", text:"A shopkeeper has 999 oranges. He sells 678. Oranges remaining?", options:[{text:"1677",type:"misinterpretation"},{text:"321",type:"correct"},{text:"311",type:"calculation_error"},{text:"332",type:"calculation_error"}], explanation:"999 − 678 = 321.", solutionSteps:["Ones: 9−8=1.","Tens: 9−7=2.","Hundreds: 9−6=3.","Diff = 321."], shortcut:"Simple subtract, no borrowing.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_ws_q8", topicId:"math3_ch6_word_problems_sub", text:"Rinku had ₹500. He spent ₹275. Money left?", options:[{text:"₹225",type:"correct"},{text:"₹775",type:"misinterpretation"},{text:"₹325",type:"calculation_error"},{text:"₹250",type:"calculation_error"}], explanation:"500 − 275 = 225.", solutionSteps:["Money left = had − spent.","500 − 275 = 225."], shortcut:"Spent = subtract.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },

  // math3_ch6_mental_math — 8 Qs
  { questionId:"math3_ch6_mm_q1", topicId:"math3_ch6_mental_math", text:"Quick: 298 + 156 (mental math)?", options:[{text:"454",type:"correct"},{text:"444",type:"calculation_error"},{text:"464",type:"calculation_error"},{text:"500",type:"misinterpretation"}], explanation:"Round 298 → 300. 300 + 156 = 456. Subtract the +2 → 454.", solutionSteps:["Round: 298 → 300.","300 + 156 = 456.","Adjust: 456 − 2 = 454."], shortcut:"Round up, then adjust back.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_mm_q2", topicId:"math3_ch6_mental_math", text:"Mentally: 100 − 47?", options:[{text:"53",type:"correct"},{text:"57",type:"calculation_error"},{text:"43",type:"calculation_error"},{text:"63",type:"calculation_error"}], explanation:"100 − 50 = 50. Adjust: +3 (since 50 > 47 by 3) → 53.", solutionSteps:["Round 47 → 50.","100 − 50 = 50.","Adjust: + 3 → 53."], shortcut:"Round and adjust.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_mm_q3", topicId:"math3_ch6_mental_math", text:"What is a 'friendly number' for 99?", options:[{text:"100",type:"correct"},{text:"90",type:"partial_logic"},{text:"50",type:"concept_error"},{text:"9",type:"calculation_error"}], explanation:"100 is the nearest multiple of 100 — easy to use.", solutionSteps:["99 is close to 100.","100 is a friendly number."], shortcut:"Nearest 10 or 100 = friendly.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_mm_q4", topicId:"math3_ch6_mental_math", text:"Mental math is faster when…", options:[{text:"Numbers are big",type:"partial_logic"},{text:"Numbers are friendly or small",type:"correct"},{text:"You use a calculator",type:"misinterpretation"},{text:"You forget the question",type:"guessing"}], explanation:"Friendly or small numbers are easy to compute mentally.", solutionSteps:["Small numbers: instant.","Friendly numbers: round, compute, adjust."], shortcut:"Friendly = fast mental math.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_mm_q5", topicId:"math3_ch6_mental_math", text:"50 + 50 + 50 (mental)?", options:[{text:"100",type:"calculation_error"},{text:"150",type:"correct"},{text:"200",type:"calculation_error"},{text:"500",type:"misinterpretation"}], explanation:"3 × 50 = 150.", solutionSteps:["50 + 50 = 100.","+50 = 150."], shortcut:"50s add quickly: 50 → 100 → 150 → 200.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_mm_q6", topicId:"math3_ch6_mental_math", text:"Quick mental: 250 + 250?", options:[{text:"450",type:"calculation_error"},{text:"500",type:"correct"},{text:"525",type:"calculation_error"},{text:"550",type:"calculation_error"}], explanation:"250 + 250 = 500 (double of 250).", solutionSteps:["Double 250 = 500."], shortcut:"Doubling = 2 × value.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_mm_q7", topicId:"math3_ch6_mental_math", text:"Mentally: 199 + 199?", options:[{text:"398",type:"correct"},{text:"388",type:"calculation_error"},{text:"400",type:"calculation_error"},{text:"398",type:"concept_error"}], explanation:"200 + 200 = 400. Adjust: −1 −1 = 398.", solutionSteps:["Round: 199 → 200.","200 + 200 = 400.","Adjust: −2 → 398."], shortcut:"Round both, adjust at end.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_mm_q8", topicId:"math3_ch6_mental_math", text:"Mental: 500 − 99?", options:[{text:"401",type:"correct"},{text:"411",type:"calculation_error"},{text:"399",type:"calculation_error"},{text:"301",type:"calculation_error"}], explanation:"500 − 100 = 400. Adjust: +1 (since 100 > 99 by 1) → 401.", solutionSteps:["Round: 99 → 100.","500 − 100 = 400.","Adjust: +1 → 401."], shortcut:"Round and adjust.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },

  // math3_ch6_estimation — 8 Qs
  { questionId:"math3_ch6_es_q1", topicId:"math3_ch6_estimation", text:"Estimate 298 + 411 by rounding to the nearest 100.", options:[{text:"500",type:"calculation_error"},{text:"700",type:"correct"},{text:"800",type:"calculation_error"},{text:"600",type:"calculation_error"}], explanation:"298 → 300. 411 → 400. 300 + 400 = 700.", solutionSteps:["Round to nearest 100: 298 → 300, 411 → 400.","Sum: 300 + 400 = 700."], shortcut:"Round both, then add.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_es_q2", topicId:"math3_ch6_estimation", text:"Why is estimation useful in math?", options:[{text:"It's always exact",type:"concept_error"},{text:"To quickly check if an answer is reasonable",type:"correct"},{text:"To make math harder",type:"guessing"},{text:"To skip practice",type:"misinterpretation"}], explanation:"Estimation gives a quick check on whether your exact answer is in the right ballpark.", solutionSteps:["Estimate first.","Compare with exact answer.","If far off → recheck."], shortcut:"Estimate to verify.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_es_q3", topicId:"math3_ch6_estimation", text:"Round 67 to the nearest 10.", options:[{text:"60",type:"calculation_error"},{text:"70",type:"correct"},{text:"100",type:"misinterpretation"},{text:"7",type:"concept_error"}], explanation:"7 ≥ 5 in ones → round up. 67 → 70.", solutionSteps:["Ones digit: 7.","7 ≥ 5 → round up.","67 → 70."], shortcut:"Ones ≥ 5: round up.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_es_q4", topicId:"math3_ch6_estimation", text:"Round 234 to the nearest 100.", options:[{text:"200",type:"correct"},{text:"300",type:"calculation_error"},{text:"230",type:"misinterpretation"},{text:"100",type:"calculation_error"}], explanation:"Tens digit = 3 < 5 → round down. 234 → 200.", solutionSteps:["Look at tens digit: 3.","3 < 5 → round down.","234 → 200."], shortcut:"Tens < 5: round down hundreds.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_es_q5", topicId:"math3_ch6_estimation", text:"Estimate 67 + 28 (to nearest 10).", options:[{text:"70",type:"calculation_error"},{text:"100",type:"correct"},{text:"95",type:"misinterpretation"},{text:"105",type:"calculation_error"}], explanation:"67 → 70. 28 → 30. 70 + 30 = 100.", solutionSteps:["67 → 70.","28 → 30.","Sum: 70 + 30 = 100."], shortcut:"Round each then add.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_es_q6", topicId:"math3_ch6_estimation", text:"Estimate 487 − 213 (to nearest 100).", options:[{text:"200",type:"correct"},{text:"100",type:"calculation_error"},{text:"300",type:"calculation_error"},{text:"500",type:"misinterpretation"}], explanation:"487 → 500. 213 → 200. 500 − 200 = 300… wait: 487 rounds to 500, 213 rounds to 200. Actual estimate: 500 − 200 = 300.", solutionSteps:["487 → 500.","213 → 200.","500 − 200 = 300.","(Note: actual answer = 274.)"], shortcut:"Round each before subtracting.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_es_q7", topicId:"math3_ch6_estimation", text:"Closer estimate of 145 + 165 (to nearest 100)?", options:[{text:"200",type:"calculation_error"},{text:"300",type:"correct"},{text:"400",type:"calculation_error"},{text:"500",type:"misinterpretation"}], explanation:"145 → 100. 165 → 200. 100 + 200 = 300.", solutionSteps:["145 → 100 (tens 4 < 5).","165 → 200 (tens 6 ≥ 5).","Sum: 300."], shortcut:"Round each then add.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
  { questionId:"math3_ch6_es_q8", topicId:"math3_ch6_estimation", text:"Estimation usually gives a/an ___ answer.", options:[{text:"Exact",type:"concept_error"},{text:"Approximate",type:"correct"},{text:"Wrong",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"Estimation is approximate, not exact.", solutionSteps:["Estimation rounds numbers.","Result is close, not exact."], shortcut:"Estimate = approximate.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Fun with Give and Take" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 3 Math v2 questions (Ch5-6).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
