/**
 * Seed — System Design DEPTH batch 6 (SD_DEPTH_STANDARD.md).
 *
 *   sysd_m15_t4  API Gateway                       (module sysd_m15)
 *   sysd_m16_t1  Single Sign-On (SSO / IdP)        (module sysd_m16)
 *   sysd_m16_t2  Change Data Capture (CDC) Pipeline(module sysd_m16)
 *   sysd_m16_t3  Service Mesh                       (module sysd_m16)
 *   sysd_m11_t7  Distributed Tracing               (module sysd_m11)
 *   sysd_m10_t6  Webhook Delivery System           (module sysd_m10)
 *
 * Idempotent upsert by id; recomputes totals. Verify:
 *   node config/auditSysdDepth.mjs --require sysd_m15_t4,sysd_m16_t1,sysd_m16_t2,sysd_m16_t3,sysd_m11_t7,sysd_m10_t6
 * Usage: node config/seedSysdDepthBatch6.js  ·  npm run seed:sysd-depth-6
 */
import "dotenv/config";
import mongoose from "mongoose";
import { ProModule, ProTopic, ProExercise } from "../models/proModels.js";
import { recomputeTrackTotals } from "./proTrackTotals.mjs";

const TRACK_KEY = "pro_sysd";

const FONT = "system-ui,-apple-system,Segoe UI,Roboto,sans-serif";
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
function box(x, y, w, h, label, sub, fill = "#eff6ff") {
  const cy = sub ? y + h / 2 - 3 : y + h / 2 + 5;
  let s = `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="${fill}" stroke="#94a3b8" stroke-width="1.5"/>`;
  s += `<text x="${x + w / 2}" y="${cy}" text-anchor="middle" font-family="${FONT}" font-size="14" font-weight="600" fill="#0f172a">${esc(label)}</text>`;
  if (sub) s += `<text x="${x + w / 2}" y="${y + h / 2 + 14}" text-anchor="middle" font-family="${FONT}" font-size="11" fill="#475569">${esc(sub)}</text>`;
  return s;
}
function arrow(x1, y1, x2, y2, label, dashed) {
  const dash = dashed ? ` stroke-dasharray="5 4"` : "";
  let s = `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#94a3b8" stroke-width="2"${dash} marker-end="url(#ah)"/>`;
  if (label) s += `<text x="${(x1 + x2) / 2}" y="${(y1 + y2) / 2 - 6}" text-anchor="middle" font-family="${FONT}" font-size="10.5" fill="#64748b">${esc(label)}</text>`;
  return s;
}
function note(x, y, text, anchor = "middle") {
  return `<text x="${x}" y="${y}" text-anchor="${anchor}" font-family="${FONT}" font-size="11" fill="#64748b">${esc(text)}</text>`;
}
function svg(w, h, inner) {
  return `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" width="100%" style="max-width:${w}px;height:auto">` +
    `<defs><marker id="ah" markerWidth="9" markerHeight="9" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#94a3b8"/></marker></defs>` +
    `<rect x="0" y="0" width="${w}" height="${h}" fill="#ffffff"/>${inner}</svg>`;
}

const DIAG = {
  apigw: svg(820, 250,
    box(20, 95, 100, 56, "Clients", "") +
    box(170, 95, 160, 56, "API Gateway", "auth/rate-limit/route", "#f0fdf4") +
    box(400, 25, 120, 44, "Service A", "", "#fce7f3") +
    box(400, 92, 120, 44, "Service B", "", "#fce7f3") +
    box(400, 159, 120, 44, "Service C", "", "#fce7f3") +
    box(580, 92, 140, 56, "Service discovery", "+ LB", "#ede9fe") +
    arrow(120, 123, 170, 123) +
    arrow(330, 110, 400, 47) + arrow(330, 123, 400, 114) + arrow(330, 136, 400, 181) +
    arrow(330, 140, 580, 120, "route", true) +
    note(420, 240, "Single entry point: cross-cutting concerns at the edge, then route to services")),
  sso: svg(820, 250,
    box(20, 100, 100, 56, "User", "") +
    box(160, 100, 110, 56, "App", "(client)", "#f0fdf4") +
    box(320, 30, 160, 60, "Identity Provider", "authN + MFA", "#fce7f3") +
    box(320, 150, 160, 52, "Session + keys", "JWKS", "#fef9c3") +
    box(540, 100, 150, 56, "Token validate", "verify signature", "#ede9fe") +
    arrow(120, 128, 160, 128) +
    arrow(270, 115, 320, 60, "redirect / authN") +
    arrow(480, 60, 540, 110, "token (OIDC/JWT)") +
    arrow(480, 176, 540, 140, "public keys") +
    note(420, 240, "Login once at IdP -> token; apps verify signature (stateless) for SSO")),
  cdc: svg(820, 250,
    box(20, 95, 110, 56, "Database", "WAL/binlog") +
    box(180, 95, 130, 56, "CDC connector", "tail the log", "#f0fdf4") +
    box(360, 95, 120, 56, "Kafka", "keyed stream", "#fef9c3") +
    box(540, 25, 120, 44, "Cache", "", "#fce7f3") +
    box(540, 92, 120, 44, "Search index", "", "#fce7f3") +
    box(540, 159, 120, 44, "Analytics", "", "#fce7f3") +
    arrow(130, 123, 180, 123, "changes") + arrow(310, 123, 360, 123) +
    arrow(480, 110, 540, 47) + arrow(480, 123, 540, 114) + arrow(480, 136, 540, 181) +
    note(420, 240, "Tail the commit log -> stream changes (no dual-write); consumers stay in sync")),
  mesh: svg(820, 260,
    box(300, 25, 220, 50, "Control plane", "policies + certs", "#ede9fe") +
    box(60, 130, 110, 50, "Service A", "", "#f0fdf4") +
    box(180, 130, 90, 50, "sidecar", "proxy", "#fce7f3") +
    box(540, 130, 90, 50, "sidecar", "proxy", "#fce7f3") +
    box(640, 130, 110, 50, "Service B", "", "#f0fdf4") +
    arrow(170, 155, 180, 155) + arrow(630, 155, 640, 155) +
    arrow(270, 155, 540, 155, "mTLS, retries, LB") +
    arrow(360, 75, 225, 130, "config", true) + arrow(460, 75, 585, 130, "config", true) +
    note(410, 240, "Sidecar proxies handle service-to-service concerns; control plane configures them")),
  trace: svg(820, 250,
    box(20, 100, 90, 50, "Request", "trace id") +
    box(150, 100, 90, 50, "Svc A", "span", "#fce7f3") +
    box(270, 100, 90, 50, "Svc B", "span", "#fce7f3") +
    box(390, 100, 90, 50, "Svc C", "span", "#fce7f3") +
    box(520, 30, 130, 50, "Collector", "async export", "#f0fdf4") +
    box(520, 150, 130, 50, "Trace store", "spans", "#fef9c3") +
    box(680, 90, 110, 50, "UI tree", "waterfall", "#ede9fe") +
    arrow(110, 125, 150, 125, "propagate") + arrow(240, 125, 270, 125) + arrow(360, 125, 390, 125) +
    arrow(480, 115, 520, 60, "spans") + arrow(520, 70, 520, 150, "") + arrow(650, 120, 680, 115) +
    note(410, 240, "Trace id propagated across calls; spans form a tree; sampled + exported async")),
  webhook: svg(820, 250,
    box(20, 100, 100, 56, "Event", "") +
    box(160, 100, 110, 56, "Queue", "per-subscriber", "#fef9c3") +
    box(310, 100, 130, 56, "Delivery wkrs", "sign + POST", "#f0fdf4") +
    box(480, 30, 150, 46, "Subscriber URL 1", "", "#fce7f3") +
    box(480, 100, 150, 46, "Subscriber URL 2", "", "#fce7f3") +
    box(480, 170, 150, 46, "DLQ", "exhausted", "#ede9fe") +
    arrow(120, 128, 160, 128) + arrow(270, 128, 310, 128) +
    arrow(440, 115, 480, 53, "HMAC-signed") + arrow(440, 128, 480, 123) +
    arrow(440, 140, 480, 190, "retries exhausted", true) +
    note(420, 240, "Queue + retry/backoff to customer URLs; sign payloads; dead-letter failures")),
};

const TT = (moduleId, id, num, name, slug, tags, hookQ, hookI, blocks, rel, gaps, diff, svgStr, vaType) => ({
  trackKey: TRACK_KEY, moduleId, topicId: id, topicNumber: num, name, slug,
  metadata: { estimated_minutes: 50, difficulty: 4, prerequisites: [], tags },
  hook: { question: hookQ, insight: hookI },
  teaching: { blocks, visual_aid: { type: vaType, svg: svgStr, alt_text: `${name} architecture diagram.` } },
  interviewRelevance: rel, commonGaps: { gaps },
  prerequisites: [], estimatedMinutes: 50, difficulty: diff, xpReward: 80, visualizer: null,
});
const C = (section, heading, body) => ({ kind: "concept", section, heading, body });
const K = (section, heading, body) => ({ kind: "code", section, heading, body });
const G = (id, w, r, d) => ({ gap_id: id, what_students_get_wrong: w, remediation: r, detection_pattern: d });

const TOPICS = [
  // ─────────────────────────────── API GATEWAY ─────────────────────────────
  TT("sysd_m15", "sysd_m15_t4", 4, "Design an API Gateway", "design-api-gateway",
    ["case-study", "api-gateway", "routing", "cross-cutting"],
    "Dozens of microservices sit behind your platform, and every one needs auth, rate limiting, TLS, and logging. Making each client talk to each service directly — and each service re-implement those concerns — is a mess. What sits in front, and what must it NOT absorb?",
    "An API GATEWAY: a single entry point that ROUTES each request to the right backend service and centralizes CROSS-CUTTING concerns (authentication, rate limiting, TLS termination, request/response transformation, caching, observability) so services don't each re-implement them. It must stay STATELESS and thin — no business logic, or it becomes a distributed monolith and bottleneck — and highly available (it's on every request's path).",
    [
      C("requirements", "Requirements",
        "Functional: expose ONE entry point for many backend services; ROUTE each request to the correct service (by path/host/version); enforce AUTHENTICATION/authorization; apply RATE LIMITING; terminate TLS; optionally transform requests/responses, cache, and aggregate multiple service calls (a BFF — backend-for-frontend); emit consistent logging/metrics/tracing. Non-functional: low added LATENCY (it's on the hot path of every request), high availability (if it's down, everything is down — so NOT a single point of failure), horizontal scalability, and statelessness. Clarify scope: a generic edge gateway vs a per-client BFF. The defining purpose is DECOUPLING clients from the internal service topology and DRY-ing up cross-cutting concerns into one layer — while the defining danger is scope creep: the gateway must remain a thin, generic policy/routing layer and must NOT accumulate business logic, or it becomes a development bottleneck and a distributed monolith."),
      K("estimation", "Capacity estimation (with numbers)",
        "Every external request passes through the gateway:\n  if the platform does 100k req/sec, the gateway handles ALL 100k/sec\n  -> it must be horizontally scaled (stateless instances behind an L4 LB)\nAdded latency budget: a few ms (auth check, route lookup, rate-limit check)\n  -> keep per-request work minimal; cache auth/keys and route tables in memory\nHA: N+ instances across zones; losing the gateway = total outage, so over-provision.\nTakeaway: it's a high-throughput, latency-sensitive, must-not-fail proxy ->\nstateless + replicated + minimal hot-path work."),
      C("hld", "High-level design",
        "Clients hit ONE endpoint (the gateway) behind a load balancer. For each request the gateway: terminates TLS; AUTHENTICATES (validates a token/API key, often via an identity provider) and authorizes; applies RATE LIMITING (shared store, the rate-limiter design); looks up the ROUTE (path/host/version -> target service), often via SERVICE DISCOVERY + load balancing; optionally TRANSFORMS the request, then forwards it to the backend service; on the response it can transform, cache, and record metrics/traces. The gateway is STATELESS (no per-request state stored locally) so any instance handles any request and it scales horizontally; configuration (routes, policies) comes from a CONTROL PLANE that the gateway reads (cached), separate from the request-serving DATA PLANE. Trace a request: client -> LB -> gateway (TLS, authN, rate-limit, route) -> Service B -> response -> gateway (transform, log) -> client. Backends are freed to focus on business logic; the gateway owns the edge policy."),
      K("api", "API / config",
        "Route config (control plane, not business code):\n  GET  /v1/orders/**   -> order-service     (auth: required, rate: 100/min)\n  POST /v1/payments/** -> payment-service    (auth: required, rate: 20/min)\n  GET  /v1/public/**   -> content-service    (auth: none, cache: 60s)\nPer-request pipeline: TLS -> authN/Z -> rate-limit -> route(discovery+LB)\n  -> transform -> forward -> response transform -> log/trace\nAdmin API: register/update routes + policies (hot-reloaded by data plane)"),
      K("data_model", "Data model",
        "routes:    pattern (path/host/version) -> target service + policy refs\npolicies:  auth (required? scopes), rate limits, cache TTL, transforms\nupstreams: service -> healthy instances (from service discovery) + LB strategy\ncontrol plane: stores config; data-plane gateways pull + cache it (hot reload)\n-- the gateway stores NO business/session state (stateless)"),
      C("deep_dive", "Deep dive: cross-cutting concerns at the edge",
        "The gateway's value is doing ONCE, at the edge, what every service would otherwise duplicate. AUTHENTICATION/authorization: validate the caller's token/API key at the gateway (e.g. verify a JWT signature or call the IdP), so backends can trust an authenticated identity passed inward and not each re-implement auth. RATE LIMITING / throttling: enforce per-client/endpoint limits centrally (shared atomic store) to protect backends from abuse and overload. TLS TERMINATION: handle certificates and HTTPS at the edge, simplifying backends. TRANSFORMATION: protocol/version translation, header injection, request/response shaping. CACHING: serve cacheable responses without hitting backends. OBSERVABILITY: assign/propagate a trace id and emit consistent logs/metrics for every request (the natural place to start a distributed trace). Aggregation/BFF: a gateway tailored to a client can fan out to several services and combine responses, reducing client round-trips. Centralizing these keeps backends focused purely on business logic and gives one place to enforce and change policy."),
      C("deep_dive", "Deep dive: what it must NOT become + stateless scaling",
        "The critical anti-pattern: do NOT put BUSINESS LOGIC in the gateway. Its job is generic routing + policy; the moment domain rules leak in, it becomes a DISTRIBUTED MONOLITH — every team must change and redeploy the shared gateway for their feature, creating a development bottleneck and a fragile single component coupling all services. Keep it THIN and generic. STATELESSNESS is the other rule: the gateway holds no per-request or session state locally (session/auth state lives in tokens or a shared store), so any instance can serve any request, enabling trivial horizontal scaling and failover — losing an instance loses nothing. Separate the CONTROL PLANE (where routes/policies are configured and stored) from the DATA PLANE (the running proxies that serve traffic): the data plane caches config and serves requests with minimal latency, hot-reloading when the control plane changes — so config updates don't require redeploys and the hot path stays fast. Thin + stateless + control/data-plane split is what keeps the gateway scalable and not a bottleneck."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "The gateway is a SINGLE POINT OF FAILURE by position — mitigate with multiple stateless instances across zones behind an L4 load balancer, generous capacity, and health checks; if it's down, everything is. It adds LATENCY to every request — minimize hot-path work (cache auth keys, route tables, rate-limit checks in/near memory). Becoming a MONOLITH (business logic creep) is the organizational bottleneck — enforce a thin generic boundary. Config management at scale needs the control/data-plane split with hot reload. Trade-offs: centralized gateway (DRY cross-cutting, one enforcement point, but a shared dependency/SPOF) vs direct-to-service (no SPOF, but duplicated concerns); generic gateway vs per-client BFF (tailored, less generic, more to maintain); fat gateway (convenient, becomes a monolith) vs thin (scalable, services own logic). Closing signal: a stateless, horizontally-scaled, thin gateway doing routing + edge cross-cutting concerns, with a control/data-plane split and HA — and explicitly no business logic."),
      C("deep_dive", "Deep dive: availability, BFF & operations",
        "Operationally the gateway must be the most reliable thing you run. HIGH AVAILABILITY: run many stateless replicas across availability zones behind a load balancer with health checks; because it's stateless, scaling and failover are trivial — but capacity planning matters since it carries all traffic. BFF pattern: for distinct clients (web, mobile, partner), a dedicated backend-for-frontend gateway can aggregate several backend calls and shape responses to that client's needs, cutting round-trips — at the cost of more gateways to maintain. Resilience: apply timeouts, retries (idempotent only), and circuit breaking toward backends so a slow service doesn't cascade through the gateway. Canary/traffic shifting: the gateway is a natural place to route a percentage of traffic to a new version. Security: it's the front door — WAF rules, DDoS absorption, and TLS live here. Config safety: validate and hot-reload routes/policies; a bad config push must not take down the edge (staged rollout). Observability: per-route latency/error rates, auth failures, rate-limit hits, and gateway saturation are the SLOs. The spine holds: a thin, stateless, highly-available edge that routes and applies cross-cutting policy, never business logic."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'What does the gateway handle?' routing + cross-cutting concerns (authN/Z, rate limiting, TLS, transformation, caching, observability) — once, at the edge. 'What must it NOT do?' business logic — that makes it a distributed monolith/bottleneck. 'Isn't it a SPOF?' run many stateless replicas across zones behind an LB; it's stateless so failover is easy. 'How does it find services?' integrates service discovery + load balancing. 'Different clients need different shapes?' a BFF (per-client gateway) aggregates/tailors responses. 'Config without redeploys?' control plane stores config; data plane hot-reloads it. 'Protect backends from a slow service?' timeouts, retries, circuit breaking at the gateway. 'Auth?' validate tokens (often from the IdP/SSO) at the edge. Each returns to the spine: a thin, stateless, HA edge that routes and enforces policy, keeping business logic in the services."),
    ],
    "An API gateway tests centralizing cross-cutting concerns (authN/Z, rate limiting, TLS, observability) and routing at a single, thin, STATELESS edge — while keeping business logic OUT (or it becomes a distributed monolith), with a control/data-plane split and HA so it's not a SPOF. The signal is 'thin generic edge + no business logic + stateless replicas', not a smart god-service.",
    [
      G("business_logic", "Putting business logic into the gateway.", "Keep it thin/generic (routing + policy); business logic stays in services.", "Domain rules/workflows implemented in the gateway."),
      G("spof", "Treating the gateway as one box / ignoring it's a SPOF.", "Run stateless replicas across zones behind an LB with health checks.", "Single gateway instance; no HA story."),
      G("stateful", "Storing session/request state in the gateway.", "Keep it stateless (state in tokens/shared store) so any instance serves any request.", "Gateway holds per-user session state locally."),
    ],
    0.6, DIAG.apigw, "API gateway architecture"),

  // ──────────────────────── SSO / IDENTITY PROVIDER ────────────────────────
  TT("sysd_m16", "sysd_m16_t1", 1, "Design Single Sign-On (SSO / Identity Provider)", "design-sso-idp",
    ["case-study", "sso", "oauth", "identity"],
    "A user logs in once and is then authenticated across many separate applications — without re-entering credentials at each. And every app must verify 'who is this user?' on every request without calling a central server each time. How do you centralize login yet validate identity in a decentralized, scalable way?",
    "A central IDENTITY PROVIDER (IdP) authenticates the user once and issues a signed TOKEN (OIDC/OAuth2, typically a JWT). Apps redirect users to the IdP to log in, receive the token, and then VALIDATE it locally by checking the signature (using the IdP's public keys) — so identity is verified statelessly at each service without a call per request. SSO works because all apps share the IdP session. Token lifecycle, validation, and revocation are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: a user authenticates ONCE and gains access to multiple applications (SSO); centralized credential management; issue and validate identity TOKENS; support logout (ideally single logout across apps); and MFA. Non-functional: strong SECURITY (it guards everything — credentials, token integrity, key management), high AVAILABILITY (if the IdP is down, no one can log in anywhere — it's a critical dependency), low-latency token validation (on every request), and scalability. Clarify scope: workforce SSO / consumer login, and standards (OAuth2/OIDC for modern apps, SAML for enterprise). The defining tension: login is CENTRALIZED (one IdP, one session, one place for MFA and policy) but VALIDATION must be DECENTRALIZED and cheap (each service verifies the token itself, not by calling the IdP per request) — achieved with cryptographically SIGNED tokens that any service can verify with the IdP's public key. The hard parts are the token lifecycle and revocation given that stateless tokens can't be 'un-issued'."),
      K("estimation", "Capacity estimation (with numbers)",
        "Auth (login) events are modest: e.g. 10M users, a few logins/day -> hundreds/sec.\nBUT token VALIDATION happens on (nearly) every API request across all services:\n  100k req/sec -> 100k validations/sec\n  -> validation MUST be local (verify signature, no IdP call) or the IdP melts\nTokens are short-lived (e.g. 15 min access) + refresh tokens for continuity.\nThe IdP is a critical dependency -> replicate for HA; cache its public keys (JWKS).\nTakeaway: centralize login (low rate), decentralize validation (high rate, local\nsignature check); short token TTL balances revocation vs re-issue load."),
      C("hld", "High-level design",
        "A central IDENTITY PROVIDER owns user credentials and authentication. When a user hits an app unauthenticated, the app REDIRECTS them to the IdP (OAuth2/OIDC authorization-code flow); the IdP authenticates them (password + MFA), establishes an IdP SESSION, and redirects back with an authorization code the app exchanges for TOKENS — an ID/access token (a signed JWT) and a refresh token. The app (and downstream services) then AUTHORIZE requests by VALIDATING the access token's signature using the IdP's published public keys (JWKS endpoint) — entirely locally, no per-request IdP call. SSO falls out: when the user visits a SECOND app and is redirected to the IdP, the existing IdP session means no re-login — the IdP just issues a new token. Trace it: user -> App A -> redirect to IdP -> authenticate (+MFA) -> token -> App A validates signature -> access; later user -> App B -> redirect to IdP -> already-logged-in -> token -> access (SSO). The IdP centralizes authN; services do stateless authZ via signatures."),
      K("api", "API / protocol (OAuth2/OIDC)",
        "GET  /authorize?client_id&redirect_uri&scope&response_type=code  -> login + consent -> code\nPOST /token { code, client_id, client_secret } -> { access_token(JWT), id_token, refresh_token }\nGET  /.well-known/jwks.json   -> IdP public keys (services cache these to verify signatures)\nPOST /token { grant_type=refresh_token, refresh_token } -> new access_token\nService-side: verify JWT signature + exp + audience locally (no IdP round-trip)"),
      K("data_model", "Data model",
        "users:      user_id PK, credential hash, MFA settings, attributes\nsessions:   IdP session per user (cookie at the IdP domain) -> enables SSO\nclients:    registered apps (client_id/secret, allowed redirect URIs, scopes)\nsigning keys: private key (sign tokens) + public keys exposed via JWKS (rotated)\ntokens:     access (short-lived JWT, stateless) + refresh (longer, revocable, stored)"),
      C("deep_dive", "Deep dive: token-based auth & the SSO flow",
        "The mechanism is delegated, token-based authentication (OIDC on top of OAuth2). Instead of each app handling passwords, the app TRUSTS the IdP: it redirects the user there, the IdP authenticates and returns a signed token asserting 'this is user X with these claims'. The standard AUTHORIZATION-CODE flow returns a short-lived code the app swaps server-side for tokens (so tokens aren't exposed in the browser URL). The key to scale is the SIGNED JWT: it's self-contained (carries the user id, claims, expiry) and cryptographically signed by the IdP's private key, so any service can VERIFY it with the IdP's PUBLIC key (fetched once from the JWKS endpoint and cached) — meaning authorization is a local signature+expiry check, NOT a network call to the IdP per request. SSO emerges from the shared IdP SESSION: once the user has a session at the IdP, every other app's redirect-to-IdP is satisfied without re-entering credentials, so one login serves all apps. Centralized authentication + decentralized, signature-based validation is the whole idea."),
      C("deep_dive", "Deep dive: tokens, sessions & the revocation problem",
        "Token lifecycle is where the subtlety lives. Use SHORT-LIVED ACCESS tokens (minutes) plus longer-lived REFRESH tokens: the access token is presented on every request and verified statelessly; when it expires, the app silently exchanges the refresh token for a new access token (so the user isn't logged out), and the refresh token (stored, revocable) is the control point. The REVOCATION PROBLEM: a stateless JWT is valid until it expires by definition — you can't 'un-issue' one already in the wild — so if you need immediate revocation (user logged out, account compromised) you either keep access-token TTLs SHORT (so a revoked user loses access within minutes) and revoke the refresh token (no new access tokens issued), or maintain a revocation/blocklist that services check (which reintroduces a lookup, trading some statelessness for immediacy). KEY ROTATION: the IdP rotates signing keys and publishes them via JWKS with key ids, so services pick the right public key and rotation doesn't break validation. SINGLE LOGOUT is hard precisely because tokens are distributed — typically driven by ending the IdP session + short TTLs. Balancing stateless validation against timely revocation via short TTLs + refresh tokens is the core trade-off."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "The IdP is a critical dependency / SPOF — if it's down, nobody can log in anywhere — so replicate it across zones, make it highly available, and ensure token VALIDATION stays local (so existing sessions keep working even during an IdP blip). Revocation vs statelessness is the core trade: stateless JWTs scale (no per-request IdP call) but can't be instantly revoked — short TTLs + refresh-token revocation, or a blocklist if you need immediacy. Token theft is a security risk — short TTLs, HTTPS, secure storage, and refresh-token rotation/binding mitigate it. Key management/rotation must be handled via JWKS or validation breaks. Trade-offs: stateless JWT (scalable local validation, weak revocation) vs opaque/reference tokens (introspection call to IdP, instant revocation, more load); short TTL (timely revocation, more refreshes) vs long TTL (fewer refreshes, slower revocation); centralized IdP (one login/policy, but a dependency) vs per-app auth (no SSO, no central control). Closing signal: a central IdP issuing short-lived signed tokens validated locally via JWKS, refresh tokens for continuity, short TTLs + revocation list for the revocation gap, replicated for HA."),
      C("deep_dive", "Deep dive: security, key rotation & operations",
        "Operationally, security and availability dominate. Availability: the IdP is replicated across zones with a highly-available user store; since validation is local (signature check), backend services keep authorizing requests even if the IdP is briefly unreachable — only new logins are affected, which is the right failure mode. Key management: signing keys are protected (HSM/secret store), rotated regularly, and exposed as a JWKS set with key ids so services fetch and cache the current public keys and rotation is seamless; never embed a single static secret in every service. MFA & risk: the IdP centralizes multi-factor and risk-based step-up (new device/location), which is far better than each app doing its own. Token hygiene: short access TTLs, refresh-token rotation (one-time-use, detect reuse = theft), audience/scopes to limit blast radius, and HTTPS everywhere. Auditing: centralized login/consent/auth events feed an audit log (compliance). Standards: use OAuth2/OIDC (and SAML for enterprise) rather than rolling your own. Observability: login success/failure, token issuance/validation rates, refresh failures, and IdP availability are the SLOs. The spine holds: centralized authN + MFA at a replicated IdP, decentralized signature-based validation via rotated JWKS keys, short-lived tokens + revocable refresh, audited."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'How is one login good for many apps?' a shared IdP session + redirect-to-IdP means no re-login (SSO). 'How do services validate without calling the IdP each request?' verify the JWT signature locally using cached JWKS public keys. 'How do you revoke a stateless token?' you can't instantly — use short access TTLs + revoke the refresh token, or a blocklist for immediacy. 'IdP down?' validation is local so existing sessions work; only new logins fail — replicate the IdP for HA. 'Key rotation?' publish keys via JWKS with key ids; services pick the right one. 'Access vs refresh tokens?' short-lived access (every request) + longer refresh (re-issue access). 'Standards?' OAuth2/OIDC (SAML for enterprise) — don't roll your own. 'MFA?' centralized at the IdP. Each returns to the spine: centralized login at a replicated IdP issuing short-lived signed tokens, validated locally via JWKS, with refresh tokens + short TTLs handling the revocation trade-off."),
    ],
    "SSO tests centralized authentication with decentralized validation: a central IdP issues short-lived signed tokens (OIDC/JWT) that services verify locally via cached JWKS keys (no per-request IdP call), with SSO from a shared IdP session, and short-TTL-plus-refresh handling the stateless-token revocation problem. The signal is signature-based local validation + the revocation trade-off + IdP HA.",
    [
      G("validate_per_request", "Calling the IdP to validate identity on every request.", "Verify the signed token locally with cached JWKS public keys; no per-request IdP call.", "Each service calls the IdP/DB to check the user per request."),
      G("ignore_revocation", "Treating long-lived JWTs as instantly revocable.", "Use short access TTLs + revocable refresh tokens (or a blocklist) for revocation.", "Long-lived JWT with an expectation of instant logout/revoke."),
      G("idp_spof", "Ignoring that the IdP is a critical dependency.", "Replicate the IdP for HA; keep validation local so sessions survive an IdP blip.", "Single IdP; an outage blocks all auth including existing sessions."),
    ],
    0.7, DIAG.sso, "SSO / identity provider architecture"),

  // ─────────────────────── CHANGE DATA CAPTURE (CDC) ───────────────────────
  TT("sysd_m16", "sysd_m16_t2", 2, "Design a Change Data Capture (CDC) Pipeline", "design-cdc-pipeline",
    ["case-study", "cdc", "outbox", "streaming"],
    "When a row changes in your primary database, a cache, a search index, and an analytics warehouse all need to reflect that change. Writing to all of them from the app (dual writes) silently drifts out of sync on any partial failure. How do you reliably propagate every database change to downstream systems?",
    "CHANGE DATA CAPTURE: instead of dual-writing, READ the database's own commit log (the WAL/binlog) — which already records every committed change in order — and STREAM those changes (via Kafka) to consumers (cache, search, analytics, other services). Log-based CDC captures changes reliably with no app changes and no dual-write inconsistency. Consumers apply changes idempotently, in per-key order. Avoiding dual writes and preserving order are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: capture every row-level change (insert/update/delete) committed to a source database and deliver it to one or more downstream consumers (caches, search indexes, data warehouses, dependent services) so they stay in sync; support an initial SNAPSHOT of existing data plus ongoing changes. Non-functional: reliability (NO lost changes), ORDERING (apply changes in the right order, at least per key/row), low propagation latency, decoupling (the source DB and app shouldn't know or care who consumes changes), and handle schema changes. Clarify scope: keeping derived stores in sync, the transactional-outbox/event-driven need. The defining problem is the DUAL-WRITE inconsistency: if the app writes to the DB and then separately publishes an event (or writes to the cache), a crash between the two leaves them inconsistent, and there's no atomic transaction spanning a DB and a message broker. CDC solves this by deriving events from the DB's OWN durable, ordered commit log — the single source of truth — so events exactly match what was committed."),
      K("estimation", "Capacity estimation (with numbers)",
        "Change rate tracks DB writes -- e.g. 50k row-changes/sec at peak.\n  each change event ~= a few hundred bytes (table, op, before/after, ts)\n  -> ~tens of MB/sec into the stream (Kafka) -> sized like any high-throughput topic\nLog retention: the source DB's WAL/binlog must be retained long enough for the\n  connector to read it (don't let it rotate away before capture) -> monitor lag.\nInitial snapshot of a large table can be huge (one-time) then switch to streaming.\nTakeaway: throughput tracks DB write rate; the operational risks are connector\nLAG vs log retention and the snapshot-to-stream handoff, not raw scale."),
      C("hld", "High-level design",
        "A CDC CONNECTOR taps the source database's replication/commit LOG (PostgreSQL WAL, MySQL binlog) — the durable, ordered record of every committed change the DB already maintains for replication — parses each change into a structured event ({table, op, before, after, ts, position}), and PUBLISHES it to a streaming platform (Kafka), partitioned by primary key so all changes to a given row land in one partition (preserving per-key order). Downstream CONSUMERS subscribe and apply the changes to their own stores: the cache invalidates/updates, the search index re-indexes, the warehouse appends, a service reacts. An INITIAL SNAPSHOT captures existing rows once, then the connector switches to streaming ongoing changes from the log position after the snapshot. Trace a change: app commits UPDATE -> the DB writes it to the WAL -> the connector reads the WAL entry -> emits a change event to Kafka (partition = pk) -> the search consumer re-indexes that row, the cache evicts it. No dual write — events are derived from the committed log, so they can't disagree with the DB."),
      K("api", "Change event format",
        "change event:\n  { source: 'orders_db.orders', op: 'u',         // c=create, u=update, d=delete\n    ts_ms, position: '<log offset>',\n    before: { id:7, status:'pending', ... },\n    after:  { id:7, status:'shipped', ... },\n    key: 7 }                                       // -> Kafka partition by key\nconsumer: poll(topic) -> apply(change) idempotently -> commit offset\nsnapshot: read existing rows -> emit as 'r' (read) events, then stream from log"),
      K("data_model", "Data model",
        "source:      DB commit log (WAL/binlog) = ordered record of committed changes\nconnector:    tracks its read POSITION in the log (resume after restart)\nstream:       Kafka topic per table, partitioned by primary key (per-key order)\nchange event: { table, op, before, after, ts, log_position, key }\nconsumers:    each tracks its own offset; apply idempotently to its own store"),
      C("deep_dive", "Deep dive: log-based CDC vs the alternatives",
        "There are a few ways to capture changes, and log-based is the strong one. QUERY-BASED (polling): periodically SELECT rows changed since a timestamp/version — simple but adds DB load, misses deletes, can miss intermediate changes, and lags. TRIGGER-BASED: DB triggers write changes to a side table — captures everything but adds write overhead and couples to the schema. LOG-BASED (the preferred approach): read the database's REPLICATION LOG (WAL/binlog) that it already produces for its own replicas. This is powerful because the log records EVERY committed change, IN ORDER, including deletes and before/after values, with NO application changes and NEAR-ZERO overhead on the source (it's just another log reader, like a replica). Tools like Debezium implement this. The connector tracks its POSITION in the log so it can resume exactly where it left off after a restart (no loss, no dupes beyond at-least-once). Reading the DB's own source-of-truth log is what makes CDC both complete and non-intrusive — the alternatives are fallbacks when log access isn't available."),
      C("deep_dive", "Deep dive: the dual-write problem, ordering & delivery",
        "CDC's reason for existing is to KILL the DUAL-WRITE inconsistency. If an app does write-to-DB then publish-event (or write-to-cache) as two separate operations, any crash or failure between them desynchronizes the systems, and you CAN'T wrap a DB and a message broker in one atomic transaction. CDC sidesteps this entirely: the event is DERIVED from the DB's committed log, so it exists if and only if the change committed — perfectly consistent by construction. (The TRANSACTIONAL OUTBOX is a sibling pattern: the app writes the event to an 'outbox' table in the SAME DB transaction as the data change, and CDC then streams the outbox — same guarantee.) ORDERING: partition the stream by primary key so all changes to one row are ordered (global ordering across all rows isn't needed and doesn't scale); consumers process a key's changes in sequence. DELIVERY is at-least-once (the connector may re-emit after a restart), so consumers must be IDEMPOTENT — applying the same change twice equals once (e.g. upsert by key, or check the log position). Derived-from-the-log events + per-key ordering + idempotent consumers give reliable, consistent propagation."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "Connector LAG vs log RETENTION is the main operational risk: the source's WAL/binlog is finite, so if the connector falls behind and the log rotates away before it's read, changes are LOST — monitor lag and retain enough log. SCHEMA CHANGES (a column added/dropped) must be handled so events and consumers don't break — a schema registry helps. The initial SNAPSHOT of a huge table is heavy (one-time) and the snapshot-to-stream handoff must not miss or duplicate changes. Ordering is only per-partition/key, not global. Trade-offs: log-based CDC (complete, low-overhead, needs log access/tooling) vs query-based (simple, misses deletes/intermediate, adds load) vs trigger-based (complete, write overhead); CDC (derive events from the log) vs transactional outbox (app writes events explicitly, same atomicity); at-least-once + idempotent consumers (reliable, possible dup) vs exactly-once (complex). Closing signal: log-based CDC tailing the WAL/binlog -> keyed stream (per-key order) -> idempotent consumers, eliminating dual writes; watch connector lag vs log retention."),
      C("deep_dive", "Deep dive: snapshots, schema evolution & operations",
        "Operationally CDC must start cleanly, survive change, and not lose data. Initial snapshot: when first connecting (or adding a consumer), read all existing rows and emit them as change events, then SWITCH to streaming from the exact log position captured at snapshot start — done carefully so no change is missed or double-applied across the handoff (incremental/watermark-based snapshots avoid locking large tables). Resume: the connector persists its log position, so a restart continues exactly where it stopped (no loss; at-least-once). Schema evolution: as the source schema changes, change events change shape — register schemas (a schema registry) and version them so consumers handle old and new formats; some changes (drop column) need consumer awareness. Retention/lag: alert when connector lag approaches log retention (the data-loss cliff) and size retention generously. Backpressure: a slow consumer just lags its own offset (the stream buffers), not blocking the source DB or other consumers. Multi-consumer: many independent consumers read the same change stream at their own offsets (one capture, many derived stores). Observability: connector lag, log position, events/sec, and per-consumer lag are the SLOs. The spine holds: snapshot + resumable log-based capture -> keyed durable stream -> idempotent, independently-paced consumers, with schema versioning."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'Why not have the app dual-write to the DB and Kafka/cache?' partial failures desync them and there's no atomic DB+broker transaction — derive events from the DB log (CDC) or use a transactional outbox. 'How do you capture changes?' read the WAL/binlog (log-based CDC, e.g. Debezium) — complete, ordered, low overhead, no app change. 'Ordering?' partition the stream by primary key (per-key order; global order isn't needed). 'Duplicates?' at-least-once delivery -> idempotent consumers (upsert by key / dedupe by log position). 'Existing data?' initial snapshot then switch to streaming. 'Schema changes?' a schema registry + versioned events. 'Connector falls behind?' monitor lag vs log retention or you lose changes. 'Many consumers?' each reads the same stream at its own offset. Each returns to the spine: tail the DB's committed log, stream keyed change events, and apply them idempotently downstream — no dual writes."),
    ],
    "CDC tests propagating database changes without dual writes: read the DB's own commit log (log-based CDC) and stream keyed change events to idempotent consumers, eliminating the dual-write inconsistency (or use a transactional outbox). The signal is deriving events from the committed log for consistency, per-key ordering, idempotent consumers, and watching connector lag vs log retention.",
    [
      G("dual_write", "Having the app write to the DB and separately publish events/update other stores.", "Derive events from the DB commit log (CDC) or a transactional outbox — no dual writes.", "App does DB write then a separate publish/cache write."),
      G("polling_misses", "Polling the table for changes (query-based) as the primary method.", "Use log-based CDC (WAL/binlog) — captures deletes and every change in order, low overhead.", "SELECT where updated_at > X; misses deletes/intermediate changes."),
      G("ignore_lag", "Ignoring connector lag vs finite log retention (silent loss).", "Monitor lag and retain enough log; idempotent consumers for at-least-once.", "No mention of WAL retention / connector falling behind."),
    ],
    0.6, DIAG.cdc, "Change data capture (CDC) pipeline"),

  // ─────────────────────────────── SERVICE MESH ────────────────────────────
  TT("sysd_m16", "sysd_m16_t3", 3, "Design a Service Mesh", "design-service-mesh",
    ["case-study", "service-mesh", "sidecar", "mtls"],
    "Every microservice needs mutual TLS, retries, timeouts, load balancing, and consistent metrics for its calls to other services. Re-implementing all that in every service (and every language) is duplicated, inconsistent, and entangled with business code. How do you provide service-to-service networking concerns WITHOUT touching the services?",
    "A SERVICE MESH moves networking concerns out of the application into a SIDECAR proxy deployed beside each service instance that transparently intercepts all its inbound/outbound traffic and applies mTLS, retries, timeouts, load balancing, and observability. A CONTROL PLANE configures all the sidecars (policies, routing rules, certificates) centrally. The split is a DATA PLANE (sidecars carrying traffic) + a CONTROL PLANE (configuring them) — concerns handled uniformly, transparently, outside app code.",
    [
      C("requirements", "Requirements",
        "Functional: provide service-to-service communication concerns uniformly — mutual TLS (encrypt + authenticate calls between services), retries, timeouts, circuit breaking, load balancing, traffic shifting (canary/blue-green), and observability (metrics, traces, logs for every call) — WITHOUT requiring each service to implement them. Non-functional: TRANSPARENCY (services shouldn't change their code or even be aware), language-agnostic (works for any service in any language), consistent policy enforcement across all services, and centralized configurability. Clarify scope: east-west (service-to-service) traffic in a microservices/Kubernetes environment, distinct from the API gateway's north-south (client-to-system) edge. The defining idea is moving cross-cutting NETWORKING concerns OUT of application code (where they'd be duplicated, inconsistent, per-language, and tangled with business logic) into a shared infrastructure layer that handles them identically for every service — so teams write business logic and get secure, reliable, observable networking for free."),
      K("estimation", "Capacity estimation (with numbers)",
        "One sidecar per service INSTANCE: 1000 instances -> 1000 sidecars (proxies).\n  each adds CPU/memory overhead (e.g. tens of MB RAM, some CPU) and a small\n  per-hop LATENCY (the proxy hop in + out, often sub-ms to low-ms)\nControl plane scales with the number of services/instances it configures + cert\n  issuance/rotation -> must handle thousands of proxies and frequent updates.\nTraffic: every inter-service call now traverses two proxies (caller + callee).\nTakeaway: the cost is per-instance sidecar overhead + per-hop latency + control-\nplane scale; the benefit is uniform, transparent mTLS/resilience/observability."),
      C("hld", "High-level design",
        "Deploy a SIDECAR proxy (e.g. Envoy) alongside EACH service instance (in the same pod). All of the service's network traffic is transparently routed THROUGH its sidecar: outbound calls go service -> its sidecar -> the callee's sidecar -> callee, and the sidecars apply the policies (mTLS handshake, retry/timeout, load balance across callee instances, emit metrics/traces). The service itself just makes a normal local call — it's unaware of the mesh. A CONTROL PLANE (e.g. Istio's istiod) holds the configuration — traffic rules, security policies, service registry — and PUSHES it to all sidecars, and issues/rotates the certificates that enable mTLS. So the DATA PLANE is the fleet of sidecars actually carrying and securing traffic; the CONTROL PLANE is the brain configuring them. Trace a call: Service A calls B -> A's sidecar intercepts, opens an mTLS connection to B's sidecar, load-balances/retries/times-out, records metrics -> B's sidecar terminates mTLS, forwards to B; the control plane supplied both sidecars their config and certs. Networking concerns live in the mesh, not the apps."),
      K("api", "Configuration (control plane)",
        "Services don't call a mesh API — it's transparent. Operators configure policy:\n  traffic: route 90% -> reviews:v1, 10% -> reviews:v2   (canary)\n  resilience: timeout=2s, retries=3, circuitBreaker(maxErrors)\n  security: mTLS=STRICT for namespace; authz: serviceA may call serviceB\nControl plane distributes this + rotating certs to every sidecar (data plane).\nObservability: sidecars emit uniform metrics/traces for every call automatically."),
      K("data_model", "Data model / planes",
        "data plane:    sidecar proxy per service instance (intercepts all traffic)\ncontrol plane: service registry, traffic/security policies, certificate authority\nconfig:        routing rules, retry/timeout/circuit-breaker, mTLS + authz policies\ncerts:         per-service identity certs (issued + rotated by control plane CA)\n-- the application contains NO mesh code; the sidecar + control plane do the work"),
      C("deep_dive", "Deep dive: the sidecar pattern & data/control plane split",
        "The enabling idea is the SIDECAR: a proxy process deployed in the same unit (pod) as each service instance, sharing its network namespace so it can transparently intercept ALL traffic in and out of that service. Because every call is intercepted by a proxy, the proxy can implement networking features for the service WITHOUT the service knowing — language-agnostic (it works for a Go, Java, or Python service identically) and code-free (no library to import). The DATA PLANE is this fleet of sidecars: they carry the actual traffic and enforce policy at the point of communication. The CONTROL PLANE is separate: it doesn't touch request traffic; it holds the desired configuration (routing, security, resilience policies) and the service registry, and it PUSHES config and certificates down to every sidecar, reacting as services scale up/down. This separation is crucial: the control plane can be updated/scaled independently and can be briefly unavailable without dropping traffic (sidecars keep running with their last config). Sidecars (do the work, per instance) + control plane (decide policy, centrally) is the architecture."),
      C("deep_dive", "Deep dive: what the mesh provides (and the cost)",
        "With every call flowing through sidecars, the mesh delivers a bundle of capabilities uniformly. SECURITY: automatic mutual TLS between services — sidecars handshake with control-plane-issued certs, so all service-to-service traffic is encrypted and mutually AUTHENTICATED (zero-trust networking) without app changes; plus service-to-service authorization policy. RESILIENCE: retries, timeouts, and circuit breaking applied consistently so a slow/failing dependency doesn't cascade. TRAFFIC MANAGEMENT: fine-grained load balancing and traffic SHIFTING — route 10% to a canary, do blue-green, fault-inject for testing — all by config, not code. OBSERVABILITY: because every call passes through a proxy, the mesh emits uniform metrics (latency, error rate, throughput per service pair), distributed-trace spans, and access logs automatically — instant golden-signal visibility across the whole system. The COST is real: per-instance sidecar resource overhead (CPU/memory ×N instances), added per-hop LATENCY (two extra proxy hops per call), and significant OPERATIONAL COMPLEXITY (running and upgrading the mesh itself). The trade is uniform, transparent networking superpowers vs that overhead — worth it at many services, overkill at few."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "Per-hop LATENCY: every call now traverses two sidecars, adding (usually small but non-zero) latency — a concern for very chatty/latency-critical paths. RESOURCE overhead: a sidecar per instance multiplies CPU/memory across the fleet. CONTROL-PLANE scale and availability: it must configure thousands of proxies and rotate certs; though traffic survives a control-plane blip (sidecars cache config), a prolonged outage stalls config/cert updates. COMPLEXITY: the mesh is powerful but is itself a complex distributed system to operate, debug, and upgrade — a real adoption cost. Trade-offs: mesh/sidecar (uniform transparent mTLS/resilience/observability, language-agnostic) vs in-app libraries (no extra hop/overhead, but duplicated, per-language, tangled with code); sidecar (per-instance, transparent) vs a node-level/ambient proxy (less overhead, newer); mesh complexity vs just doing it in a few services (don't adopt a mesh for 3 services). Closing signal: sidecar data plane + central control plane delivering mTLS/resilience/traffic-control/observability transparently, accepting per-hop latency, resource overhead, and operational complexity."),
      C("deep_dive", "Deep dive: security, rollout & operations",
        "Operationally a mesh is infrastructure that must be secure and safely adoptable. Zero-trust security: the control plane runs a certificate authority that issues each service a short-lived identity cert and rotates them automatically, so mTLS is always on and identities are verifiable — a big security win over plaintext internal traffic; authorization policies (which service may call which) are enforced at the sidecars. Rollout: adopt incrementally (inject sidecars namespace by namespace), start mTLS in PERMISSIVE mode (accept both plaintext and mTLS) before STRICT, so you don't break existing traffic during migration. Upgrades: the mesh (sidecars + control plane) needs careful version management; sidecar upgrades roll with the services. Resilience of the mesh: run the control plane HA; ensure the data plane fails open/last-known-good if the control plane is unavailable (don't drop traffic). Debugging: the extra hop and abstraction can complicate troubleshooting — the mesh's own observability helps. When NOT to use it: for a handful of services the overhead/complexity outweighs the benefit — libraries or a gateway suffice. Observability: per-service-pair latency/error/throughput, mTLS coverage, cert rotation health, and control-plane status are the SLOs. The spine holds: transparent sidecars + a central control plane providing mTLS, resilience, traffic control, and observability, adopted incrementally."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'How does it work without changing services?' a sidecar proxy per instance transparently intercepts all traffic and applies the concerns. 'What does it provide?' mTLS, retries/timeouts/circuit-breaking, load balancing, traffic shifting (canary), and uniform observability. 'Data plane vs control plane?' sidecars carry/secure traffic (data plane); the control plane configures them + issues certs. 'Cost?' per-instance resource overhead, per-hop latency, and operational complexity. 'Mesh vs API gateway?' mesh = east-west (service-to-service); gateway = north-south (client-to-system) — complementary. 'mTLS rollout without breakage?' permissive mode then strict. 'Control plane down?' sidecars keep running on cached config (fail static). 'When not to use it?' few services — libraries/gateway suffice. Each returns to the spine: a sidecar data plane + central control plane delivering networking concerns transparently and uniformly, at the cost of overhead and complexity."),
    ],
    "A service mesh tests moving service-to-service networking concerns (mTLS, retries/timeouts, load balancing, traffic shifting, observability) out of application code into transparent SIDECAR proxies, configured by a central CONTROL PLANE — the data-plane/control-plane split. The signal is the sidecar pattern for transparency + the plane split, and naming the cost (per-hop latency, overhead, complexity) and east-west vs the gateway's north-south.",
    [
      G("in_app", "Re-implementing mTLS/retries/observability in each service.", "Move them into a sidecar proxy per instance, configured centrally — transparent + uniform.", "Networking concerns coded per-service/per-language."),
      G("no_plane_split", "Conflating the proxies with the configuration / no control plane.", "Separate data plane (sidecars carry traffic) from control plane (configures them + certs).", "No notion of a control plane distributing config/certs."),
      G("ignore_cost", "Treating a mesh as free / using it for a few services.", "Account for per-hop latency, per-instance overhead, and operational complexity; skip it when few services.", "Adopts a mesh with no mention of overhead/complexity."),
    ],
    0.7, DIAG.mesh, "Service mesh architecture"),

  // ────────────────────────── DISTRIBUTED TRACING ──────────────────────────
  TT("sysd_m11", "sysd_m11_t7", 7, "Design Distributed Tracing", "design-distributed-tracing",
    ["case-study", "tracing", "spans", "observability"],
    "A user request is slow, but it touched a dozen microservices on its way through. Logs and metrics tell you SOMETHING is slow — not WHERE. How do you follow one request across all those services and see exactly which hop cost the time?",
    "Give each request a TRACE ID and PROPAGATE it across every service call (in headers). Each service records a SPAN — a timed unit of work with its trace id, span id, and parent span id — and ships spans asynchronously to a collector; the backend assembles all spans sharing a trace id into a TREE (a timeline/waterfall) showing the path and timing across services. Because volume is huge, you SAMPLE. Context propagation, spans, and sampling are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: follow a single request END TO END as it traverses many services; for each step capture timing, the service/operation, and parent-child relationships; assemble these into a per-request view showing where latency and errors occur; make traces searchable (by trace id, service, latency, error). Non-functional: LOW OVERHEAD (tracing must not meaningfully slow the requests it measures), scalability to huge span volumes, and acceptable completeness via SAMPLING (you can't store a trace for every request at scale). Clarify scope: tracing is one leg of the observability trio (logs = discrete events, metrics = numeric aggregates, TRACES = per-request causal timelines) — tracing's unique job is causality and latency attribution ACROSS service boundaries, which logs/metrics alone can't give. The two core challenges are PROPAGATING a request's identity across process/network boundaries (so spans from different services can be stitched together) and doing it CHEAPLY at scale (low overhead + sampling), then storing/querying the spans."),
      K("estimation", "Capacity estimation (with numbers)",
        "Assume 100k requests/sec, each touching ~10 services -> ~1M spans/sec if 100% traced.\n  storing every span = log-scale volume -> SAMPLE: keep e.g. 1% -> ~10k spans/sec\n  (sample whole TRACES, not individual spans, so a kept trace is complete)\nSpan ~= a few hundred bytes (ids, service, timing, tags).\nExport is ASYNC + batched so the request path isn't blocked.\nStorage: spans stored + indexed by trace id (and service/time) like logs, tiered.\nTakeaway: span volume is enormous -> sample whole traces, export async, store\nlike logs (indexed by trace id, time-tiered) -- overhead and volume drive sampling."),
      C("hld", "High-level design",
        "When a request enters the system (often at the API gateway), it's assigned a unique TRACE ID. As it flows from service to service, that trace id (plus the current span id) is PROPAGATED in the request headers (a standard like W3C Trace Context / OpenTelemetry). Each service, for each unit of work, creates a SPAN — recording the trace id, a new span id, the PARENT span id (the caller's span), the service/operation name, start time, duration, and tags (status, errors) — and emits it. Spans are exported ASYNCHRONOUSLY (buffered, batched, often via an agent) to a COLLECTOR, which writes them to a span STORE indexed by trace id. A UI queries by trace id and assembles all spans of a trace into a TREE / waterfall timeline showing each service's contribution and where time/errors went. SAMPLING decides which traces to keep. Trace it: request gets trace=abc at the gateway -> Service A span(parent=root) calls B with header trace=abc,parent=spanA -> B span(parent=spanA) -> ... -> all spans for abc shipped async -> UI shows the abc waterfall. Propagated ids + emitted spans + async collection + assembly is the pipeline."),
      K("api", "Instrumentation / propagation",
        "On request entry:   traceId = new (or from incoming header)\nPer operation:      span = startSpan(name, parentSpanId); ... ; span.end()\n  span = { traceId, spanId, parentSpanId, service, op, startTs, durationMs, tags }\nPropagation (HTTP header, W3C Trace Context):\n  traceparent: 00-<traceId>-<spanId>-<flags>     // passed on every outbound call\nExport: async batch spans -> collector -> store (indexed by traceId)\nQuery: getTrace(traceId) -> spans -> assemble tree/waterfall"),
      K("data_model", "Data model",
        "span:   { trace_id, span_id, parent_span_id, service, operation,\n            start_ts, duration_ms, status, tags{...} }\ntrace:  all spans sharing a trace_id -> reconstructed into a tree via parent ids\nindex:  by trace_id (assemble a trace) + by service/time/latency (search)\nstorage: spans stored like logs; time-partitioned + tiered; sampled subset\npropagation: trace_id + span_id carried in request headers across services"),
      C("deep_dive", "Deep dive: context propagation & spans",
        "The thing that makes tracing 'distributed' is CONTEXT PROPAGATION: a request's trace context (trace id + current span id) must travel with it across every process and network hop, or you'd have disconnected per-service spans you can't stitch together. So on every outbound call a service injects the trace id and its current span id into the request (HTTP headers, message metadata) following a standard (W3C Trace Context / OpenTelemetry), and the receiving service extracts them and continues the trace. Each SPAN is a timed unit of work carrying: the shared TRACE ID (ties all spans of one request together), its own SPAN ID, and its PARENT SPAN ID (the span that caused it) — these parent links let the backend reconstruct the causal TREE (who called whom, nested timings). A span also records duration, service/operation, and tags (status code, error, db query). Instrumentation creates these spans — via auto-instrumentation (libraries/frameworks, or the service mesh's sidecars) so developers get tracing with little manual code. Propagated context + parent-linked spans are exactly what turns a dozen independent service timings into one coherent request timeline."),
      C("deep_dive", "Deep dive: sampling, overhead & assembly",
        "At scale you can't trace and store EVERY request, so SAMPLING is essential and is the key design decision. HEAD-BASED sampling decides at the start of a request (e.g. keep 1%) — simple and low overhead, but it might miss the rare slow/errored requests you most want. TAIL-BASED sampling buffers spans and decides AFTER the request completes — so you can keep all traces that were slow or errored and sample the boring fast ones — far more useful but needs buffering/coordination (more infrastructure). Crucially, sample whole TRACES (all spans of a request) together, not individual spans, or you get fragmentary traces. OVERHEAD: instrumentation must be cheap and export ASYNCHRONOUS (buffer spans in-process, batch-send via an agent) so the traced request is never blocked on I/O to the collector. ASSEMBLY: spans arrive independently and possibly out of order; the backend groups them by trace id and uses parent_span_id links to build the tree, rendering a WATERFALL where each bar is a span's duration — instantly showing which service/hop dominated latency or threw the error. Sampling (what to keep) + async export (low overhead) + trace-id assembly (the picture) make tracing practical."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "Span VOLUME is the scaling pressure — 100% tracing is infeasible, so sampling is mandatory; the trade is completeness vs cost. OVERHEAD on the traced path must stay low — async/batched export and lightweight instrumentation, or tracing harms what it measures. STORAGE of spans is large (like logs) — index by trace id, time-partition, and tier/retain. Propagation GAPS break traces — any service (or async hop: queues, batch jobs) that doesn't propagate context creates broken/disconnected traces, so propagation must be universal (standardized, auto-instrumented). Clock skew across services can distort relative timings. Trade-offs: head sampling (cheap, simple, may miss anomalies) vs tail sampling (keeps slow/errored traces, needs buffering); always-on low rate vs adaptive/anomaly-biased; auto-instrumentation (broad coverage, less control) vs manual (precise, effortful); store-everything (complete, costly) vs aggressive sampling (cheap, gaps). Closing signal: propagate a trace id across all hops, emit parent-linked spans, export async, SAMPLE (ideally tail-based for anomalies), and assemble by trace id into a waterfall."),
      C("deep_dive", "Deep dive: correlation, standards & operations",
        "Operationally tracing is most valuable when integrated and standardized. The OBSERVABILITY trio: correlate traces with LOGS and METRICS — stamp the trace id into log lines (so from a slow trace you jump to the exact logs of each span) and link metrics anomalies to exemplar traces; together they answer what/where/why. Standards: use OpenTelemetry (vendor-neutral instrumentation + W3C Trace Context propagation) so any language/service interoperates and you avoid lock-in; auto-instrumentation and the service-mesh sidecars can emit spans with minimal app code. Storage/retention: spans are stored and indexed (by trace id, service, latency, error) like logs, time-partitioned and tiered, with retention bounded by cost — sampled data keeps this affordable. Async pipeline: in-process buffer -> local agent -> collector -> store, with backpressure so trace export never blocks or crashes the app. Coverage gaps: ensure propagation through async boundaries (message queues carry trace context in metadata; batch jobs continue the trace) or you get broken traces. Observability of the tracer: sampling rate, span throughput, dropped spans, and trace completeness are the SLOs. The spine holds: standardized propagation + parent-linked spans + async export + sampling + trace-id assembly, correlated with logs/metrics."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'How do spans from different services get connected?' a trace id (+ span id) is propagated in headers across every call; spans link via parent_span_id. 'Can you trace every request?' no — sample; whole traces, ideally tail-based to keep slow/errored ones. 'How do you keep overhead low?' lightweight instrumentation + async/batched export off the request path. 'How is a trace shown?' assemble all spans by trace id into a tree/waterfall timeline. 'Async hops (queues, batch)?' carry trace context in message metadata so the trace continues. 'Correlate with logs?' stamp the trace id into logs (the observability trio). 'Standards?' OpenTelemetry + W3C Trace Context (avoid lock-in, auto-instrument). 'Storage?' index spans by trace id, time-tier like logs. Each returns to the spine: propagate trace context everywhere, emit parent-linked spans, export async, sample, and assemble by trace id."),
    ],
    "Distributed tracing tests context propagation (a trace id carried across every hop) + parent-linked spans assembled by trace id into a waterfall, with async low-overhead export and SAMPLING (ideally tail-based to keep slow/errored traces) given enormous span volume. The signal is propagation across services, the span tree, and sampling — plus correlating with logs/metrics as the observability trio.",
    [
      G("no_propagation", "Logging per-service timings without a propagated trace id to connect them.", "Propagate a trace id (+ span id) across every call; link spans via parent ids.", "Each service logs durations independently; no cross-service id."),
      G("trace_everything", "Trying to store a trace for every request at scale.", "Sample (whole traces), ideally tail-based to keep slow/errored ones; export async.", "100% tracing with no sampling/overhead consideration."),
      G("sync_export", "Exporting spans synchronously on the request path.", "Buffer + batch + async export so tracing doesn't slow the traced request.", "Span sent to collector inline before responding."),
    ],
    0.6, DIAG.trace, "Distributed tracing architecture"),

  // ──────────────────────── WEBHOOK DELIVERY SYSTEM ────────────────────────
  TT("sysd_m10", "sysd_m10_t6", 6, "Design a Webhook Delivery System", "design-webhook-delivery",
    ["case-study", "webhooks", "delivery", "retries"],
    "Customers register URLs to receive your events ('payment.succeeded') as HTTP callbacks. But those endpoints are outside your control — they go down, get slow, and return errors. How do you deliver events reliably to thousands of flaky external URLs without losing events or letting one slow customer stall everyone?",
    "Decouple event production from delivery with a QUEUE: events are enqueued, and DELIVERY WORKERS POST them to subscriber URLs with RETRIES + exponential backoff, sending exhausted attempts to a DEAD-LETTER queue. Payloads are SIGNED (HMAC) so receivers can verify authenticity, and delivery is at-least-once so receivers DEDUPE by event id. Per-subscriber isolation (and circuit breaking on dead endpoints) stops one bad consumer from starving others. Reliable delivery to unreliable endpoints is the substance.",
    [
      C("requirements", "Requirements",
        "Functional: let customers SUBSCRIBE a URL to event types; when an event occurs, DELIVER it to the subscribed URL(s) via HTTP POST; RETRY failed deliveries; let customers see delivery status/history and replay. Non-functional: RELIABILITY (don't lose events even when endpoints are down — at-least-once delivery), resilience to SLOW/FAILING external endpoints (you don't control them), scale (thousands of subscribers, high event volume, large fan-out), SECURITY (the receiver must verify the call really came from you), and ISOLATION (one customer's broken endpoint must not delay everyone else's deliveries). Clarify scope: outbound webhooks (you calling customers). The defining challenge is delivering to ENDPOINTS YOU DON'T CONTROL — they're flaky, slow, return errors, and have wildly varying reliability — so the system must retry persistently, isolate failures, secure payloads, and tolerate duplicates, all while not letting a few dead endpoints consume all resources."),
      K("estimation", "Capacity estimation (with numbers)",
        "Assume 10M events/day, avg fan-out 2 subscribers -> 20M deliveries/day\n  = ~230 deliveries/sec avg; bursty around event spikes\nEach delivery = an HTTP POST (tens of ms to several seconds if the endpoint is slow)\n  -> slow endpoints tie up workers -> need many workers + per-endpoint isolation\nRetries multiply attempts: a dead endpoint retried 5x over hours adds load.\nState: store every delivery attempt + status (for visibility/replay) -> sizable log.\nTakeaway: it's I/O-bound on external endpoints (concurrency + isolation matter\nmore than CPU); retries + history drive the storage; bursts need the queue."),
      C("hld", "High-level design",
        "When an event is produced, it's written to a durable QUEUE (decoupling production from delivery and absorbing bursts). DELIVERY WORKERS consume events, look up the matching SUBSCRIPTIONS, render the payload, SIGN it (HMAC with the subscriber's secret), and POST it to each subscriber URL. On success (2xx) the delivery is marked delivered; on failure (non-2xx, timeout, connection error) it's RETRIED with exponential backoff up to a max, after which it goes to a DEAD-LETTER queue and the subscription may be flagged/disabled. Every attempt is logged (status, response) for customer visibility and replay. Per-subscriber QUEUES/rate limits and circuit breaking isolate a slow/dead endpoint so it doesn't consume all workers or delay other customers. Trace a delivery: event -> queue -> worker -> sign -> POST to customer URL -> 200 (done) | timeout (retry with backoff -> ... -> DLQ). The receiver verifies the signature and dedupes by event id (since we deliver at-least-once). Queue + workers + retries + signing + isolation is the shape."),
      K("api", "API design",
        "POST /api/v1/webhooks { url, events:['payment.succeeded'], secret } -> { subscriptionId }\nDelivery (us -> customer):\n  POST <customer-url>\n  Headers: X-Webhook-Id: <event_id>      (receiver dedupes on this)\n           X-Webhook-Signature: hmac_sha256(secret, body)   (receiver verifies)\n  Body: { id, type:'payment.succeeded', created, data:{...} }\n  expect 2xx; else retry with backoff -> DLQ after N attempts\nGET /api/v1/webhooks/{id}/deliveries -> attempt history (status, response, replay)"),
      K("data_model", "Data model",
        "subscriptions:  id, customer_id, url, event_types[], secret, status(active|disabled)\ndelivery:        id, event_id, subscription_id, status(pending|delivered|failed),\n                 attempts, next_retry_at, last_response   (history + retry state)\nevents:          id, type, payload, created_at\nqueue:           events/deliveries to dispatch (durable) + per-subscriber isolation\nDLQ:             deliveries that exhausted retries (inspect/replay)"),
      C("deep_dive", "Deep dive: reliable delivery (queue, retries, signing, dedupe)",
        "Reliability rests on four mechanisms. QUEUE: events go to a durable queue first, so production never blocks on delivery, bursts are absorbed, and an event isn't lost if a worker crashes (it's redelivered) — this gives AT-LEAST-ONCE delivery. RETRIES with EXPONENTIAL BACKOFF: external endpoints fail transiently (a deploy, a blip), so a failed POST is retried on a growing schedule (e.g. seconds, then minutes, then hours) up to a max, after which it's DEAD-LETTERED for inspection/manual replay and the subscription may be disabled — this rides out temporary outages without hammering a struggling endpoint. SIGNING: because the receiver gets an HTTP call from the internet, you sign the payload with a shared secret (HMAC) and include the signature in a header, so the receiver can VERIFY the request genuinely came from you (and wasn't tampered with) — without signing, anyone could forge webhook calls. DEDUPLICATION: since delivery is at-least-once (retries, redelivery after crashes), the SAME event may arrive more than once, so each delivery carries a unique event id and receivers must DEDUPE on it (process once) — the same idempotency discipline as payments. Queue + backoff retries + signature + at-least-once-with-dedupe is the reliable-delivery core."),
      C("deep_dive", "Deep dive: handling unreliable endpoints at scale",
        "The hard operational reality is that subscriber endpoints vary wildly and misbehave, so you must ISOLATE failures. Without isolation, a few slow endpoints (taking seconds per request or timing out) would tie up all the shared delivery workers, starving every other customer's deliveries — head-of-line blocking. So isolate per subscriber/endpoint: per-subscriber queues or fair scheduling, concurrency limits per endpoint, and CIRCUIT BREAKING — if an endpoint has been failing/timing out persistently, trip a breaker that pauses delivery to it (and backs off or disables the subscription) rather than continuing to spend workers and retries on a dead URL, while other customers flow normally. RATE LIMITING per subscriber prevents overwhelming a customer's endpoint (and respects their capacity). Timeouts cap how long a slow endpoint can hold a worker. ORDERING is a caveat: with retries and parallelism, events may arrive OUT OF ORDER, so either don't promise ordering (receivers handle via timestamps/version) or use per-subscriber sequential delivery (lower throughput) if ordering is required. These isolation + flow-control mechanisms keep one bad actor from degrading the whole system."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "Slow/dead endpoints are the core bottleneck — without per-subscriber isolation, concurrency limits, timeouts, and circuit breaking, they cause head-of-line blocking and waste workers/retries; isolate and breaker them. RETRY STORMS: many endpoints failing at once (or aggressive retries) multiply load — exponential backoff + jitter + caps tame this. ORDERING isn't guaranteed with retries/parallelism — make receivers order-tolerant or pay for sequential per-subscriber delivery. SECURITY: unsigned webhooks are forgeable and replayable — sign (HMAC) and include a timestamp to limit replay. DUPLICATES are inherent to at-least-once — push dedupe to the receiver via event id. Trade-offs: at-least-once + dedupe (no loss, possible dup) vs at-most-once (no dup, risk loss); shared workers (simple, head-of-line risk) vs per-subscriber isolation (fair, more complex); aggressive retries (faster recovery, more load) vs gentle backoff; ordered delivery (sequential, slower) vs unordered (parallel, fast). Closing signal: durable queue + retry-with-backoff to DLQ + HMAC signing + at-least-once with receiver dedupe + per-subscriber isolation/circuit-breaking for unreliable endpoints."),
      C("deep_dive", "Deep dive: visibility, replay & operations",
        "Operationally customers need transparency and you need control over flaky consumers. Delivery LOG: record every attempt (timestamp, response code, body, latency) per delivery so customers can SEE what was sent and why it failed, and so you can debug — this history is a core feature, not an afterthought. REPLAY: let customers (or ops) re-trigger delivery of past/failed events (from the log or DLQ) after they fix their endpoint — essential because endpoints are often down during the original attempts. Endpoint health: track per-subscriber success/failure rates; auto-DISABLE or alert on chronically failing endpoints (and notify the customer), reclaiming resources from dead URLs. Security hardening: sign with HMAC, include a timestamp/nonce so old payloads can't be replayed by an attacker, and document signature verification for customers; allowlist/validate URLs to avoid SSRF. Fan-out: one event to many subscribers expands in the queue; large fan-outs are processed by the worker pool within rate limits. Observability: delivery success rate, retry/DLQ rates, per-endpoint latency, and queue depth (backlog) are the SLOs. The spine holds: durable queued delivery with retries/DLQ, signed at-least-once payloads, per-subscriber isolation/health management, and full attempt history with replay."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'How do you not lose events when an endpoint is down?' durable queue + retries with exponential backoff -> DLQ; at-least-once delivery. 'One slow customer slows everyone?' per-subscriber isolation (queues/concurrency limits) + circuit breaking + timeouts. 'How does the receiver know it's really you?' HMAC-sign the payload; they verify the signature (+ timestamp to stop replay). 'Duplicates?' at-least-once -> include an event id; receivers dedupe. 'Ordering?' not guaranteed with retries/parallelism — be order-tolerant or do sequential per-subscriber. 'Customer fixed their endpoint — resend?' replay from the delivery log/DLQ. 'Dead endpoints?' track health, auto-disable + notify. 'Big fan-out?' expand in the queue, drain via workers within rate limits. Each returns to the spine: queue + backoff retries to DLQ + signed at-least-once delivery with receiver dedupe + per-subscriber isolation, plus attempt history and replay."),
    ],
    "A webhook delivery system tests reliable delivery to endpoints you don't control: a durable queue + retry-with-backoff to a DLQ (at-least-once), HMAC-signed payloads receivers verify, receiver-side dedupe by event id, and per-subscriber isolation/circuit-breaking so one flaky endpoint can't starve others. The signal is queue+retries+signing+dedupe and isolating unreliable consumers.",
    [
      G("sync_no_retry", "POSTing to subscriber URLs synchronously with no queue/retries.", "Enqueue events; deliver via workers with retry+backoff -> DLQ (at-least-once).", "Delivers inline on the event with no retry/queue; loses events on failure."),
      G("no_isolation", "Shared workers with no per-subscriber isolation.", "Isolate per subscriber (queues/concurrency limits) + circuit-break dead endpoints + timeouts.", "One slow endpoint blocks all deliveries (head-of-line)."),
      G("no_signing_dedupe", "Unsigned payloads and/or assuming exactly-once.", "HMAC-sign payloads (receiver verifies) and send an event id so receivers dedupe.", "No signature; receiver can't verify or dedupe duplicates."),
    ],
    0.5, DIAG.webhook, "Webhook delivery system architecture"),
];

// ── 3 exercises per topic ────────────────────────────────────────────────────
const xpFor = (l) => (l === "warmup" ? 5 : l === "easy" ? 10 : l === "medium" ? 15 : 20);
const diffFor = (l) => (l === "warmup" ? 0.1 : l === "easy" ? 0.2 : l === "medium" ? 0.4 : 0.6);
function pm(moduleId, o) {
  return { trackKey: TRACK_KEY, moduleId, topicId: o.topicId, exerciseId: o.exerciseId,
    position: o.position, level: o.level, type: "pattern_match", title: o.title, scenario: o.scenario,
    instructions: "Pick the best answer.", starterCode: "", expectedSolution: o.correct,
    blanks: [{ options: o.options }], testCases: [{ type: "pattern_match", correct: o.correct, explanation: o.explanation }],
    hints: [], xpReward: xpFor(o.level), difficulty: diffFor(o.level) };
}

const EXERCISES = [
  // API gateway
  pm("sysd_m15", { topicId: "sysd_m15_t4", exerciseId: "sysd_m15_t4_pm_d1", position: 11, level: "medium",
    title: "What belongs at the gateway?", scenario: "Which concerns should an API gateway centralize for all services?",
    options: ["Auth, rate limiting, TLS, routing, observability", "Order business logic", "The product database", "Per-service domain rules"],
    correct: "Auth, rate limiting, TLS, routing, observability",
    explanation: "The gateway centralizes cross-cutting concerns + routing at the edge; business logic stays in the services." }),
  pm("sysd_m15", { topicId: "sysd_m15_t4", exerciseId: "sysd_m15_t4_pm_d2", position: 12, level: "hard",
    title: "The anti-pattern", scenario: "What happens if you put business logic into the API gateway?",
    options: ["It becomes a distributed monolith / bottleneck", "It gets faster", "It improves security", "Nothing — that's recommended"],
    correct: "It becomes a distributed monolith / bottleneck",
    explanation: "Business logic in the gateway couples all teams to it and makes it a development bottleneck and fragile shared component — keep it thin/generic." }),
  pm("sysd_m15", { topicId: "sysd_m15_t4", exerciseId: "sysd_m15_t4_pm_d3", position: 13, level: "medium",
    title: "Not a SPOF", scenario: "The gateway is on every request's path. How do you keep it from being a single point of failure?",
    options: ["Run stateless replicas across zones behind a load balancer", "Run one powerful instance", "Cache requests on the client", "Skip the gateway for some clients"],
    correct: "Run stateless replicas across zones behind a load balancer",
    explanation: "Statelessness lets you run many replicas with easy failover; an LB + health checks across zones removes the SPOF." }),
  // SSO
  pm("sysd_m16", { topicId: "sysd_m16_t1", exerciseId: "sysd_m16_t1_pm_d1", position: 11, level: "hard",
    title: "Validating without calling the IdP", scenario: "Services must check identity on every request without a per-request call to the IdP. How?",
    options: ["Verify the token's signature locally using the IdP's public keys (JWKS)", "Call the IdP to introspect every token", "Query the user database each request", "Trust any token"],
    correct: "Verify the token's signature locally using the IdP's public keys (JWKS)",
    explanation: "A signed JWT is self-contained; services verify the signature + expiry locally with cached JWKS public keys — no per-request IdP call." }),
  pm("sysd_m16", { topicId: "sysd_m16_t1", exerciseId: "sysd_m16_t1_pm_d2", position: 12, level: "hard",
    title: "The revocation problem", scenario: "You need to revoke access fast, but JWTs are valid until they expire. Common approach?",
    options: ["Short access-token TTLs + revoke the refresh token (or a blocklist)", "Make tokens last a year", "Nothing — JWTs auto-revoke", "Delete the user's password"],
    correct: "Short access-token TTLs + revoke the refresh token (or a blocklist)",
    explanation: "Stateless tokens can't be un-issued; keep access TTLs short and revoke the refresh token so no new access tokens are issued (add a blocklist for immediacy)." }),
  pm("sysd_m16", { topicId: "sysd_m16_t1", exerciseId: "sysd_m16_t1_pm_d3", position: 13, level: "medium",
    title: "How SSO works", scenario: "Why does logging in once give access to many apps?",
    options: ["A shared IdP session: each app redirects to the IdP, which issues a token without re-login", "Each app stores the password", "The browser remembers the password", "Apps share a database of sessions"],
    correct: "A shared IdP session: each app redirects to the IdP, which issues a token without re-login",
    explanation: "With an existing IdP session, every app's redirect-to-IdP is satisfied without re-entering credentials — the IdP just issues a fresh token (SSO)." }),
  // CDC
  pm("sysd_m16", { topicId: "sysd_m16_t2", exerciseId: "sysd_m16_t2_pm_d1", position: 11, level: "hard",
    title: "The dual-write problem", scenario: "The app writes to the DB then publishes an event separately. Why is CDC better?",
    options: ["A crash between the two desyncs them; CDC derives events from the committed log (always consistent)", "CDC is just faster", "Dual writes are atomic", "CDC avoids using a database"],
    correct: "A crash between the two desyncs them; CDC derives events from the committed log (always consistent)",
    explanation: "You can't atomically write a DB and a broker; CDC reads the DB's commit log so events exist iff the change committed — no dual-write drift." }),
  pm("sysd_m16", { topicId: "sysd_m16_t2", exerciseId: "sysd_m16_t2_pm_d2", position: 12, level: "medium",
    title: "How changes are captured", scenario: "What's the preferred way to capture every change (including deletes) with low overhead?",
    options: ["Log-based CDC: read the WAL/binlog", "Poll the table with SELECT where updated_at > X", "Add triggers that write to a side table", "Diff full table dumps nightly"],
    correct: "Log-based CDC: read the WAL/binlog",
    explanation: "The commit log records every committed change in order (incl. deletes) with near-zero source overhead and no app changes — unlike polling (misses deletes) or triggers (write overhead)." }),
  pm("sysd_m16", { topicId: "sysd_m16_t2", exerciseId: "sysd_m16_t2_pm_d3", position: 13, level: "medium",
    title: "Ordering + duplicates", scenario: "How do you preserve order and handle at-least-once delivery in a CDC stream?",
    options: ["Partition by primary key (per-key order) + idempotent consumers", "Global total ordering of all changes", "Ignore ordering and duplicates", "One consumer reads everything serially"],
    correct: "Partition by primary key (per-key order) + idempotent consumers",
    explanation: "Per-key partitioning keeps a row's changes ordered (global order doesn't scale); idempotent consumers make at-least-once redelivery safe." }),
  // Service mesh
  pm("sysd_m16", { topicId: "sysd_m16_t3", exerciseId: "sysd_m16_t3_pm_d1", position: 11, level: "medium",
    title: "Networking without app changes", scenario: "How does a service mesh add mTLS/retries/observability without changing service code?",
    options: ["A sidecar proxy per instance transparently intercepts all traffic", "A library imported into every service", "Rewriting each service in one language", "A gateway at the edge only"],
    correct: "A sidecar proxy per instance transparently intercepts all traffic",
    explanation: "The sidecar shares the pod's network and intercepts traffic, applying concerns transparently and language-agnostically — no app code." }),
  pm("sysd_m16", { topicId: "sysd_m16_t3", exerciseId: "sysd_m16_t3_pm_d2", position: 12, level: "medium",
    title: "Data plane vs control plane", scenario: "In a service mesh, what configures the sidecars and issues certs?",
    options: ["The control plane (sidecars are the data plane)", "Each sidecar configures itself", "The API gateway", "The application"],
    correct: "The control plane (sidecars are the data plane)",
    explanation: "Sidecars (data plane) carry/secure traffic; the control plane holds policy/registry and pushes config + rotating certs to all sidecars." }),
  pm("sysd_m16", { topicId: "sysd_m16_t3", exerciseId: "sysd_m16_t3_pm_d3", position: 13, level: "hard",
    title: "The cost of a mesh", scenario: "What's the main trade-off of adopting a service mesh?",
    options: ["Per-hop latency + per-instance overhead + operational complexity", "It removes all latency", "It eliminates the need for services", "There's no downside"],
    correct: "Per-hop latency + per-instance overhead + operational complexity",
    explanation: "Every call traverses two sidecars (latency), each instance runs a proxy (overhead), and the mesh is a complex system to operate — overkill for few services." }),
  // Distributed tracing
  pm("sysd_m11", { topicId: "sysd_m11_t7", exerciseId: "sysd_m11_t7_pm_d1", position: 11, level: "medium",
    title: "Connecting spans across services", scenario: "How do per-service timings get stitched into one request's trace?",
    options: ["A trace id is propagated across every call; spans link via parent ids", "Each service logs its own time only", "By matching timestamps", "By the user id"],
    correct: "A trace id is propagated across every call; spans link via parent ids",
    explanation: "Propagating a trace id (+ span id) in headers and recording parent_span_id lets the backend assemble all spans into the request tree." }),
  pm("sysd_m11", { topicId: "sysd_m11_t7", exerciseId: "sysd_m11_t7_pm_d2", position: 12, level: "hard",
    title: "Tracing at scale", scenario: "You can't store a trace for every request. How do you keep the useful ones?",
    options: ["Tail-based sampling: decide after completion, keep slow/errored traces", "Trace 100% and store everything", "Random per-span sampling", "Never trace"],
    correct: "Tail-based sampling: decide after completion, keep slow/errored traces",
    explanation: "Tail sampling buffers spans and keeps whole traces that were slow or errored (the valuable ones), sampling the rest — head sampling is cheaper but may miss anomalies." }),
  pm("sysd_m11", { topicId: "sysd_m11_t7", exerciseId: "sysd_m11_t7_pm_d3", position: 13, level: "medium",
    title: "Keeping overhead low", scenario: "How do you ensure tracing doesn't slow the requests it measures?",
    options: ["Buffer + batch + export spans asynchronously, off the request path", "Send each span synchronously before responding", "Trace only in production peak", "Store spans in the request thread"],
    correct: "Buffer + batch + export spans asynchronously, off the request path",
    explanation: "Async, batched export (via an in-process buffer/agent) keeps the traced request from blocking on span I/O — low overhead." }),
  // Webhook delivery
  pm("sysd_m10", { topicId: "sysd_m10_t6", exerciseId: "sysd_m10_t6_pm_d1", position: 11, level: "medium",
    title: "Delivering to flaky endpoints", scenario: "Subscriber URLs go down and time out. How do you deliver reliably without losing events?",
    options: ["Queue events; workers POST with retry+backoff -> DLQ (at-least-once)", "POST once inline and drop on failure", "Email the customer instead", "Block until the endpoint is up"],
    correct: "Queue events; workers POST with retry+backoff -> DLQ (at-least-once)",
    explanation: "A durable queue + retries with exponential backoff (then dead-letter) rides out endpoint outages without losing events; delivery is at-least-once." }),
  pm("sysd_m10", { topicId: "sysd_m10_t6", exerciseId: "sysd_m10_t6_pm_d2", position: 12, level: "hard",
    title: "One slow customer", scenario: "A few subscribers' endpoints are very slow. How do you stop them delaying everyone?",
    options: ["Per-subscriber isolation + concurrency limits + circuit breaking + timeouts", "Use one shared worker pool with no limits", "Retry the slow ones faster", "Disable retries globally"],
    correct: "Per-subscriber isolation + concurrency limits + circuit breaking + timeouts",
    explanation: "Isolating per subscriber (and breaking dead endpoints) prevents head-of-line blocking so a few flaky URLs don't starve other customers' deliveries." }),
  pm("sysd_m10", { topicId: "sysd_m10_t6", exerciseId: "sysd_m10_t6_pm_d3", position: 13, level: "medium",
    title: "Authenticity + duplicates", scenario: "How does a receiver know the webhook is really from you, and handle duplicates?",
    options: ["HMAC-sign the payload (they verify) + send an event id they dedupe on", "Send it over plain HTTP", "Include your password", "Promise exactly-once and ignore dupes"],
    correct: "HMAC-sign the payload (they verify) + send an event id they dedupe on",
    explanation: "An HMAC signature lets the receiver verify authenticity; an event id lets them dedupe, since at-least-once delivery can resend the same event." }),
];

// ── upsert + recompute ──────────────────────────────────────────────────────
async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  const moduleIds = [...new Set(TOPICS.map((t) => t.moduleId))];
  for (const mid of moduleIds) {
    const m = await ProModule.findOne({ trackKey: TRACK_KEY, moduleId: mid }).lean();
    if (!m) throw new Error(`Module ${mid} not found — run the base SD seeds first.`);
  }
  let tUp = 0, eUp = 0;
  for (const t of TOPICS) { await ProTopic.updateOne({ trackKey: TRACK_KEY, topicId: t.topicId }, { $set: t }, { upsert: true }); tUp++; }
  for (const e of EXERCISES) { await ProExercise.updateOne({ trackKey: TRACK_KEY, exerciseId: e.exerciseId }, { $set: e }, { upsert: true }); eUp++; }
  const totals = await recomputeTrackTotals(TRACK_KEY);
  console.log(`✓ Depth batch 6 seeded: ${tUp} topics deepened, ${eUp} exercises upserted.`);
  console.log(`  track totals now: ${JSON.stringify(totals)}`);
  await mongoose.disconnect();
}
run().catch((err) => { console.error(err); process.exit(1); });
