import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math3_ch13_pictographs — 8 Qs
  { questionId:"math3_ch13_pi_q1", topicId:"math3_ch13_pictographs", text:"A pictograph uses ___ to show data.", options:[{text:"Numbers only",type:"concept_error"},{text:"Pictures / symbols",type:"correct"},{text:"Letters",type:"misinterpretation"},{text:"Lines only",type:"calculation_error"}], explanation:"Pictograph: each picture (symbol) represents a count.", solutionSteps:["Pictograph = picture + graph.","Each symbol = N items."], shortcut:"Pictograph = pictures.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_pi_q2", topicId:"math3_ch13_pictographs", text:"Key: each ★ = 5 apples. A row has 4 stars. How many apples?", options:[{text:"4",type:"concept_error"},{text:"20",type:"correct"},{text:"9",type:"calculation_error"},{text:"40",type:"misinterpretation"}], explanation:"4 stars × 5 apples each = 20.", solutionSteps:["Stars × key = total.","4 × 5 = 20."], shortcut:"Symbols × key.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_pi_q3", topicId:"math3_ch13_pictographs", text:"Why is the KEY in a pictograph important?", options:[{text:"It's decoration",type:"concept_error"},{text:"It tells you what each symbol stands for",type:"correct"},{text:"It's irrelevant",type:"misinterpretation"},{text:"It's a name",type:"guessing"}], explanation:"Without the key, you don't know how much each symbol represents.", solutionSteps:["Key tells the scale.","Each symbol = key value."], shortcut:"Key = scale.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_pi_q4", topicId:"math3_ch13_pictographs", text:"Key: each 😊 = 10. Row has 3 faces. Count?", options:[{text:"13",type:"misinterpretation"},{text:"30",type:"correct"},{text:"3",type:"concept_error"},{text:"100",type:"calculation_error"}], explanation:"3 × 10 = 30.", solutionSteps:["3 × 10 = 30."], shortcut:"Symbols × key.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_pi_q5", topicId:"math3_ch13_pictographs", text:"Pictograph with key=2: dog row has 5 symbols, cat row has 4. How many MORE dogs?", options:[{text:"1",type:"concept_error"},{text:"2",type:"correct"},{text:"4",type:"calculation_error"},{text:"9",type:"misinterpretation"}], explanation:"Dogs: 5×2=10. Cats: 4×2=8. Diff = 10−8 = 2.", solutionSteps:["Dogs: 5×2=10.","Cats: 4×2=8.","Diff: 10−8=2."], shortcut:"Difference in symbols × key.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_pi_q6", topicId:"math3_ch13_pictographs", text:"If key = 4 and total count = 28, how many symbols?", options:[{text:"4",type:"calculation_error"},{text:"7",type:"correct"},{text:"24",type:"misinterpretation"},{text:"112",type:"misinterpretation"}], explanation:"Symbols = total ÷ key = 28 ÷ 4 = 7.", solutionSteps:["Symbols = 28 ÷ 4 = 7."], shortcut:"Total ÷ key = symbols.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_pi_q7", topicId:"math3_ch13_pictographs", text:"What does ½ symbol typically mean in pictographs?", options:[{text:"Half the key value",type:"correct"},{text:"Same as full symbol",type:"concept_error"},{text:"Zero",type:"misinterpretation"},{text:"Two symbols",type:"guessing"}], explanation:"Half a symbol = half the key value (e.g., if key=10, half symbol = 5).", solutionSteps:["½ symbol = ½ × key value.","If key = 10, ½ = 5."], shortcut:"Half symbol = half key.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_pi_q8", topicId:"math3_ch13_pictographs", text:"Which category has the FEWEST? (sticker=2 per ⭐)\nApples: ⭐⭐⭐⭐\nBananas: ⭐⭐\nMangoes: ⭐⭐⭐", options:[{text:"Apples",type:"concept_error"},{text:"Bananas",type:"correct"},{text:"Mangoes",type:"concept_error"},{text:"All equal",type:"misinterpretation"}], explanation:"Bananas have fewest symbols (2) → fewest count.", solutionSteps:["Compare symbols: 4, 2, 3.","Smallest = 2 (Bananas).","Bananas have fewest."], shortcut:"Fewest symbols = lowest count.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },

  // math3_ch13_bar_graphs — 8 Qs
  { questionId:"math3_ch13_bg_q1", topicId:"math3_ch13_bar_graphs", text:"In a bar graph, taller bar means…", options:[{text:"Smaller count",type:"concept_error"},{text:"Bigger count",type:"correct"},{text:"Same count",type:"misinterpretation"},{text:"Average",type:"guessing"}], explanation:"Bar height represents value — taller = more.", solutionSteps:["Bar height ↑ = count ↑."], shortcut:"Tall bar = big count.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_bg_q2", topicId:"math3_ch13_bar_graphs", text:"The y-axis of a bar graph usually shows…", options:[{text:"Names of items",type:"concept_error"},{text:"The scale / count",type:"correct"},{text:"Pictures",type:"misinterpretation"},{text:"Title only",type:"guessing"}], explanation:"y-axis = counts / numbers; x-axis = categories.", solutionSteps:["y-axis: values.","x-axis: categories."], shortcut:"y-axis = numbers.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_bg_q3", topicId:"math3_ch13_bar_graphs", text:"Bar graph data: Dog=10, Cat=8, Fish=5. Most popular pet?", options:[{text:"Cat",type:"concept_error"},{text:"Dog",type:"correct"},{text:"Fish",type:"concept_error"},{text:"Equal",type:"misinterpretation"}], explanation:"Highest bar = most popular. Dog (10) > Cat (8) > Fish (5).", solutionSteps:["Compare: 10, 8, 5.","Dog = 10 (highest)."], shortcut:"Tallest bar = winner.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_bg_q4", topicId:"math3_ch13_bar_graphs", text:"Dog=10, Cat=8. How many MORE dogs than cats?", options:[{text:"2",type:"correct"},{text:"18",type:"misinterpretation"},{text:"5",type:"calculation_error"},{text:"10",type:"misinterpretation"}], explanation:"10 − 8 = 2.", solutionSteps:["10 − 8 = 2."], shortcut:"Difference of bars.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_bg_q5", topicId:"math3_ch13_bar_graphs", text:"Bar graph scale: each gridline = 2. A bar reaches gridline 5. Value?", options:[{text:"5",type:"concept_error"},{text:"10",type:"correct"},{text:"7",type:"calculation_error"},{text:"2",type:"misinterpretation"}], explanation:"5 gridlines × 2 = 10.", solutionSteps:["Each gridline = 2.","5 gridlines × 2 = 10."], shortcut:"Gridlines × scale = value.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_bg_q6", topicId:"math3_ch13_bar_graphs", text:"In a bar graph, bars usually have…", options:[{text:"The same width",type:"correct"},{text:"Random widths",type:"concept_error"},{text:"No width",type:"misinterpretation"},{text:"Triangular shape",type:"guessing"}], explanation:"Bars are drawn with equal widths — only heights vary.", solutionSteps:["Equal widths = fair comparison.","Heights vary by data."], shortcut:"Equal widths in bar graphs.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_bg_q7", topicId:"math3_ch13_bar_graphs", text:"What is shown on the x-axis?", options:[{text:"Numbers",type:"concept_error"},{text:"Categories (names)",type:"correct"},{text:"Title",type:"misinterpretation"},{text:"Bar height",type:"guessing"}], explanation:"x-axis lists categories (names of items).", solutionSteps:["x-axis: category names.","y-axis: values."], shortcut:"x = category, y = value.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_bg_q8", topicId:"math3_ch13_bar_graphs", text:"Bars: cricket=15, football=12, hockey=5. Total students?", options:[{text:"22",type:"calculation_error"},{text:"32",type:"correct"},{text:"30",type:"calculation_error"},{text:"40",type:"misinterpretation"}], explanation:"15 + 12 + 5 = 32.", solutionSteps:["15 + 12 = 27.","27 + 5 = 32."], shortcut:"Sum all bars.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },

  // math3_ch13_reading_charts — 8 Qs
  { questionId:"math3_ch13_rc_q1", topicId:"math3_ch13_reading_charts", text:"To read a bar's value, trace its top to which axis?", options:[{text:"x-axis (bottom)",type:"concept_error"},{text:"y-axis (left)",type:"correct"},{text:"Diagonally",type:"misinterpretation"},{text:"Doesn't matter",type:"guessing"}], explanation:"Trace the bar's top horizontally to the y-axis.", solutionSteps:["Bar top → trace left.","Read y-axis number."], shortcut:"Top of bar → y-axis.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_rc_q2", topicId:"math3_ch13_reading_charts", text:"Cricket=15, hockey=5. The difference is…", options:[{text:"20",type:"misinterpretation"},{text:"10",type:"correct"},{text:"5",type:"calculation_error"},{text:"3",type:"calculation_error"}], explanation:"15 − 5 = 10.", solutionSteps:["15 − 5 = 10."], shortcut:"Subtract bars.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_rc_q3", topicId:"math3_ch13_reading_charts", text:"What should you check FIRST when reading a chart?", options:[{text:"The label / title",type:"correct"},{text:"The colours",type:"concept_error"},{text:"The smallest bar",type:"misinterpretation"},{text:"The biggest bar",type:"partial_logic"}], explanation:"Label / title tells you what the chart is about.", solutionSteps:["Read title.","Read axis labels.","Then read bars."], shortcut:"Title first, then values.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_rc_q4", topicId:"math3_ch13_reading_charts", text:"In a chart of book counts (A=20, B=15, C=25, D=10), how many in total?", options:[{text:"50",type:"calculation_error"},{text:"70",type:"correct"},{text:"60",type:"calculation_error"},{text:"100",type:"misinterpretation"}], explanation:"20 + 15 + 25 + 10 = 70.", solutionSteps:["20 + 15 = 35.","35 + 25 = 60.","60 + 10 = 70."], shortcut:"Sum all categories.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_rc_q5", topicId:"math3_ch13_reading_charts", text:"Which is the BEST chart to compare counts of 4 categories?", options:[{text:"Just a number",type:"concept_error"},{text:"Bar graph",type:"correct"},{text:"Long text",type:"misinterpretation"},{text:"Calculator",type:"guessing"}], explanation:"Bar graphs visualise category counts clearly.", solutionSteps:["Bar graphs: easy to compare.","Categories on x, counts on y."], shortcut:"Compare categories = bar graph.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_rc_q6", topicId:"math3_ch13_reading_charts", text:"Chart shows: rainfall over 5 days (mm). Highest rainfall on:", options:[{text:"The day with shortest bar",type:"concept_error"},{text:"The day with tallest bar",type:"correct"},{text:"The first day",type:"misinterpretation"},{text:"The last day",type:"guessing"}], explanation:"Tallest bar = highest value.", solutionSteps:["Find tallest bar.","Read x-label for that day."], shortcut:"Tallest = highest.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_rc_q7", topicId:"math3_ch13_reading_charts", text:"If two bars are equal height, the two categories…", options:[{text:"Are different",type:"concept_error"},{text:"Have the same count",type:"correct"},{text:"Cannot be compared",type:"misinterpretation"},{text:"Are zero",type:"guessing"}], explanation:"Same height = same value (regardless of category).", solutionSteps:["Equal height = equal value.","Different categories can tie."], shortcut:"Equal bars = tie.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_rc_q8", topicId:"math3_ch13_reading_charts", text:"Why is a chart easier than reading a table of numbers?", options:[{text:"Shows answers without thinking",type:"concept_error"},{text:"Patterns are easier to SEE visually",type:"correct"},{text:"Numbers are easier",type:"misinterpretation"},{text:"It hides data",type:"guessing"}], explanation:"Charts make differences and patterns visually obvious.", solutionSteps:["Visual = quicker to interpret.","Trends pop out."], shortcut:"Charts: visual > numeric.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },

  // math3_ch13_data_collection — 8 Qs
  { questionId:"math3_ch13_dc_q1", topicId:"math3_ch13_data_collection", text:"Before making a chart, you must first…", options:[{text:"Pick colours",type:"concept_error"},{text:"Collect data",type:"correct"},{text:"Buy paper",type:"misinterpretation"},{text:"Draw axes",type:"partial_logic"}], explanation:"Without data, there's nothing to chart.", solutionSteps:["1. Collect data.","2. Tally.","3. Organise.","4. Chart."], shortcut:"Data first, chart second.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_dc_q2", topicId:"math3_ch13_data_collection", text:"Tally marks |||| represent…", options:[{text:"2",type:"concept_error"},{text:"3",type:"calculation_error"},{text:"4",type:"correct"},{text:"5",type:"misinterpretation"}], explanation:"|||| = 4 (four vertical lines).", solutionSteps:["Count vertical lines: 4."], shortcut:"4 lines = 4.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_dc_q3", topicId:"math3_ch13_data_collection", text:"Tally mark for 5 is…", options:[{text:"|||||",type:"calculation_error"},{text:"|||| with diagonal cross",type:"correct"},{text:"55",type:"misinterpretation"},{text:"V",type:"guessing"}], explanation:"For 5, draw 4 vertical lines + 1 diagonal cross.", solutionSteps:["||||̸ = 5.","4 verticals + 1 diagonal.","Makes counting groups of 5 easier."], shortcut:"Cross every 5th.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_dc_q4", topicId:"math3_ch13_data_collection", text:"To collect 'favourite sport', you should…", options:[{text:"Guess",type:"concept_error"},{text:"Ask many students individually",type:"correct"},{text:"Use one student's answer for all",type:"misinterpretation"},{text:"Make it up",type:"guessing"}], explanation:"Survey means asking many people one by one.", solutionSteps:["Decide question.","Ask each person.","Record each answer."], shortcut:"Survey = ask many.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_dc_q5", topicId:"math3_ch13_data_collection", text:"Tally |||| ||||̸ ||| represents…", options:[{text:"12",type:"correct"},{text:"10",type:"calculation_error"},{text:"13",type:"calculation_error"},{text:"11",type:"calculation_error"}], explanation:"||||̸ = 5, |||| = 4, ||| = 3. Total = 5+4+3 = 12.", solutionSteps:["First group: ||||̸ = 5.","|||| = 4.","||| = 3.","Wait — re-reading: |||| ||||̸ ||| = 4 + 5 + 3 = 12."], shortcut:"Sum each tally group.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_dc_q6", topicId:"math3_ch13_data_collection", text:"Organised data is presented in a…", options:[{text:"Sentence",type:"concept_error"},{text:"Table",type:"correct"},{text:"Drawing",type:"misinterpretation"},{text:"Letter",type:"guessing"}], explanation:"Tables show data in rows and columns.", solutionSteps:["Categories on left.","Counts on right.","Easy to read."], shortcut:"Table = organised data.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_dc_q7", topicId:"math3_ch13_data_collection", text:"Why use tally marks instead of just numbers?", options:[{text:"They look prettier",type:"partial_logic"},{text:"They are fast to make while counting",type:"correct"},{text:"They are required by law",type:"misinterpretation"},{text:"Numbers are wrong",type:"guessing"}], explanation:"Tally marks are quick to draw one at a time as you count.", solutionSteps:["No need to write digits.","One stroke per item."], shortcut:"Tally = fast counting.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },
  { questionId:"math3_ch13_dc_q8", topicId:"math3_ch13_data_collection", text:"In a survey of 30 students, if 12 chose football and 8 chose cricket, how many chose other sports?", options:[{text:"10",type:"correct"},{text:"20",type:"calculation_error"},{text:"22",type:"calculation_error"},{text:"30",type:"misinterpretation"}], explanation:"Other = 30 − (12 + 8) = 30 − 20 = 10.", solutionSteps:["Football + cricket = 12 + 8 = 20.","Other = 30 − 20 = 10."], shortcut:"Total − known = unknown.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Smart Charts!" },

  // math3_ch14_rupees_paise — 8 Qs
  { questionId:"math3_ch14_rp_q1", topicId:"math3_ch14_rupees_paise", text:"1 rupee = ? paise", options:[{text:"10",type:"concept_error"},{text:"100",type:"correct"},{text:"1000",type:"misinterpretation"},{text:"1",type:"calculation_error"}], explanation:"By definition: 1 ₹ = 100 paise.", solutionSteps:["1 ₹ = 100 paise."], shortcut:"1 ₹ = 100 p.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_rp_q2", topicId:"math3_ch14_rupees_paise", text:"Which is the largest Indian coin (in value)?", options:[{text:"50 paise",type:"concept_error"},{text:"₹10",type:"correct"},{text:"₹1",type:"calculation_error"},{text:"₹5",type:"calculation_error"}], explanation:"₹10 coin is the largest commonly used Indian coin.", solutionSteps:["Coin denominations: 1, 2, 5, 10 ₹.","Largest = ₹10."], shortcut:"₹10 is biggest coin.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_rp_q3", topicId:"math3_ch14_rupees_paise", text:"50 paise + 50 paise = ?", options:[{text:"₹1",type:"correct"},{text:"₹0.50",type:"calculation_error"},{text:"₹5",type:"misinterpretation"},{text:"₹2",type:"calculation_error"}], explanation:"50 + 50 = 100 paise = ₹1.", solutionSteps:["50 + 50 = 100 paise.","100 paise = 1 ₹."], shortcut:"100 paise = 1 ₹.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_rp_q4", topicId:"math3_ch14_rupees_paise", text:"The symbol ₹ stands for…", options:[{text:"Pound",type:"concept_error"},{text:"Rupee",type:"correct"},{text:"Dollar",type:"misinterpretation"},{text:"Euro",type:"misinterpretation"}], explanation:"₹ = Rupee (Indian currency).", solutionSteps:["₹ = Indian Rupee symbol."], shortcut:"₹ = rupee.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_rp_q5", topicId:"math3_ch14_rupees_paise", text:"25 paise + 75 paise = ?", options:[{text:"₹0.50",type:"calculation_error"},{text:"₹1",type:"correct"},{text:"₹0.75",type:"calculation_error"},{text:"100 paise = ₹1",type:"correct"}], explanation:"25 + 75 = 100 paise = ₹1.", solutionSteps:["25 + 75 = 100 paise.","= ₹1."], shortcut:"Add paise; convert to ₹.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_rp_q6", topicId:"math3_ch14_rupees_paise", text:"₹25.50 means…", options:[{text:"25 rupees and 5 paise",type:"calculation_error"},{text:"25 rupees and 50 paise",type:"correct"},{text:"25 rupees 500 paise",type:"misinterpretation"},{text:"2550 rupees",type:"misinterpretation"}], explanation:"After the decimal, digits show paise (50 means 50 paise).", solutionSteps:["₹ part before decimal.","Paise after decimal.","₹25.50 = 25 ₹ + 50 paise."], shortcut:"After dot = paise.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_rp_q7", topicId:"math3_ch14_rupees_paise", text:"Which note is NOT in current use?", options:[{text:"₹100",type:"concept_error"},{text:"₹500",type:"concept_error"},{text:"₹1000",type:"correct"},{text:"₹200",type:"concept_error"}], explanation:"₹1000 note was demonetised in 2016. Notes now: 10, 20, 50, 100, 200, 500, 2000.", solutionSteps:["₹1000 = no longer legal tender.","Current notes: 10–500, 2000."], shortcut:"₹1000 = retired.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_rp_q8", topicId:"math3_ch14_rupees_paise", text:"Which is more: ₹1 or 100 paise?", options:[{text:"₹1 is more",type:"concept_error"},{text:"100 paise is more",type:"concept_error"},{text:"They are equal",type:"correct"},{text:"Cannot say",type:"guessing"}], explanation:"₹1 = 100 paise, by definition.", solutionSteps:["1 ₹ = 100 p.","Equal."], shortcut:"₹1 = 100 p.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },

  // math3_ch14_money_conversion — 8 Qs
  { questionId:"math3_ch14_mc_q1", topicId:"math3_ch14_money_conversion", text:"350 paise = ? ₹", options:[{text:"₹35",type:"calculation_error"},{text:"₹3.50",type:"correct"},{text:"₹0.35",type:"calculation_error"},{text:"₹350",type:"misinterpretation"}], explanation:"350 ÷ 100 = ₹3.50.", solutionSteps:["paise → ₹: ÷ 100.","350 ÷ 100 = ₹3.50."], shortcut:"paise ÷ 100 = ₹.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mc_q2", topicId:"math3_ch14_money_conversion", text:"₹4 = ? paise", options:[{text:"4 paise",type:"concept_error"},{text:"40 paise",type:"calculation_error"},{text:"400 paise",type:"correct"},{text:"4000 paise",type:"misinterpretation"}], explanation:"4 × 100 = 400 paise.", solutionSteps:["₹ → paise: × 100.","4 × 100 = 400."], shortcut:"₹ × 100 = paise.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mc_q3", topicId:"math3_ch14_money_conversion", text:"₹2.75 = ? paise", options:[{text:"275 paise",type:"correct"},{text:"27.5 paise",type:"calculation_error"},{text:"2750 paise",type:"misinterpretation"},{text:"2.75 paise",type:"concept_error"}], explanation:"2 × 100 + 75 = 275 paise.", solutionSteps:["₹2 = 200 paise.","+ 75 paise = 275 paise."], shortcut:"₹ × 100 + remainder paise.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mc_q4", topicId:"math3_ch14_money_conversion", text:"₹0.50 = ? paise", options:[{text:"5",type:"concept_error"},{text:"50",type:"correct"},{text:"500",type:"misinterpretation"},{text:"0.5",type:"calculation_error"}], explanation:"0.50 × 100 = 50 paise.", solutionSteps:["After decimal = paise.","₹0.50 = 50 paise."], shortcut:"After decimal = paise.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mc_q5", topicId:"math3_ch14_money_conversion", text:"To convert paise to rupees, you ___ by 100.", options:[{text:"Multiply",type:"concept_error"},{text:"Divide",type:"correct"},{text:"Add",type:"misinterpretation"},{text:"Subtract",type:"misinterpretation"}], explanation:"paise ÷ 100 = ₹.", solutionSteps:["paise → ₹: ÷ 100.","Smaller unit → bigger unit: divide."], shortcut:"÷ 100 to go paise → ₹.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mc_q6", topicId:"math3_ch14_money_conversion", text:"1000 paise = ? ₹", options:[{text:"₹10",type:"correct"},{text:"₹1",type:"calculation_error"},{text:"₹100",type:"misinterpretation"},{text:"₹1000",type:"concept_error"}], explanation:"1000 ÷ 100 = ₹10.", solutionSteps:["1000 ÷ 100 = ₹10."], shortcut:"Divide by 100.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mc_q7", topicId:"math3_ch14_money_conversion", text:"₹5.20 = ? paise", options:[{text:"52 paise",type:"calculation_error"},{text:"520 paise",type:"correct"},{text:"5200 paise",type:"misinterpretation"},{text:"5.2 paise",type:"concept_error"}], explanation:"5 × 100 = 500 paise + 20 = 520 paise.", solutionSteps:["₹5 = 500 paise.","+20 = 520 paise."], shortcut:"₹ × 100 + paise = total paise.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mc_q8", topicId:"math3_ch14_money_conversion", text:"125 paise = ? ₹ + ? paise", options:[{text:"₹1 + 25 paise",type:"correct"},{text:"₹0 + 125 paise",type:"partial_logic"},{text:"₹12 + 5 paise",type:"calculation_error"},{text:"₹2 + 5 paise",type:"calculation_error"}], explanation:"125 ÷ 100 = 1 rupee, 25 paise remainder.", solutionSteps:["100 paise = 1 ₹.","Remainder: 125 − 100 = 25 paise.","→ ₹1 + 25 paise."], shortcut:"Divide; quotient = ₹, remainder = paise.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },

  // math3_ch14_money_addition — 8 Qs
  { questionId:"math3_ch14_ma_q1", topicId:"math3_ch14_money_addition", text:"₹25.50 + ₹14.25 = ?", options:[{text:"₹39.75",type:"correct"},{text:"₹40.75",type:"calculation_error"},{text:"₹39.25",type:"calculation_error"},{text:"₹11.25",type:"misinterpretation"}], explanation:"₹25.50 + ₹14.25 = ₹39.75.", solutionSteps:["Add paise: 50 + 25 = 75 paise.","Add ₹: 25 + 14 = ₹39.","Total: ₹39.75."], shortcut:"Add columns (paise and ₹).", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_ma_q2", topicId:"math3_ch14_money_addition", text:"₹100 − ₹37.50 = ?", options:[{text:"₹137.50",type:"misinterpretation"},{text:"₹62.50",type:"correct"},{text:"₹72.50",type:"calculation_error"},{text:"₹52.50",type:"calculation_error"}], explanation:"100 − 37.50 = 62.50.", solutionSteps:["100.00 − 37.50.","Borrow if needed.","= 62.50."], shortcut:"Decimal subtraction.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_ma_q3", topicId:"math3_ch14_money_addition", text:"To add ₹2.50 and ₹3.75, line up the…", options:[{text:"Beginning",type:"concept_error"},{text:"Decimal points",type:"correct"},{text:"Letters",type:"misinterpretation"},{text:"Top",type:"guessing"}], explanation:"Aligning decimal points keeps ₹ and paise in correct columns.", solutionSteps:["Line up decimals.","Add column by column."], shortcut:"Line up decimals.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_ma_q4", topicId:"math3_ch14_money_addition", text:"₹5 + ₹3.25 = ?", options:[{text:"₹8.25",type:"correct"},{text:"₹8.05",type:"calculation_error"},{text:"₹8.50",type:"calculation_error"},{text:"₹2.25",type:"misinterpretation"}], explanation:"₹5 = ₹5.00. 5.00 + 3.25 = ₹8.25.", solutionSteps:["₹5 = ₹5.00.","5.00 + 3.25 = ₹8.25."], shortcut:"Write missing zeros after decimal.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_ma_q5", topicId:"math3_ch14_money_addition", text:"₹10.50 − ₹3.75 = ?", options:[{text:"₹6.75",type:"correct"},{text:"₹7.25",type:"calculation_error"},{text:"₹14.25",type:"misinterpretation"},{text:"₹7.75",type:"calculation_error"}], explanation:"10.50 − 3.75 = 6.75.", solutionSteps:["10.50 − 3.75.","Borrow if needed.","= 6.75."], shortcut:"Align decimals then subtract.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_ma_q6", topicId:"math3_ch14_money_addition", text:"Add ₹15 + ₹7.50 + ₹2.50.", options:[{text:"₹24",type:"calculation_error"},{text:"₹25",type:"correct"},{text:"₹26",type:"calculation_error"},{text:"₹30",type:"misinterpretation"}], explanation:"15 + 7.50 + 2.50 = 25.", solutionSteps:["7.50 + 2.50 = 10.","15 + 10 = 25."], shortcut:"Add in friendly order.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_ma_q7", topicId:"math3_ch14_money_addition", text:"What's the easiest way to add ₹4.99 + ₹2.99?", options:[{text:"Use a calculator only",type:"partial_logic"},{text:"Round to ₹5 + ₹3 = ₹8, then subtract 0.02",type:"correct"},{text:"Add the paise first",type:"misinterpretation"},{text:"Skip decimals",type:"concept_error"}], explanation:"Round 4.99 → 5, 2.99 → 3. 5 + 3 = 8. Adjust by −0.02 → ₹7.98.", solutionSteps:["Round: 5 + 3 = 8.","Adjust: −0.02.","= ₹7.98."], shortcut:"Round, add, adjust.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_ma_q8", topicId:"math3_ch14_money_addition", text:"Sum: 50 paise + ₹1 = ?", options:[{text:"51 paise",type:"calculation_error"},{text:"₹1.50",type:"correct"},{text:"₹50",type:"misinterpretation"},{text:"₹0.50",type:"misinterpretation"}], explanation:"50 paise = ₹0.50. 0.50 + 1.00 = ₹1.50.", solutionSteps:["50 paise = ₹0.50.","₹0.50 + ₹1.00 = ₹1.50."], shortcut:"Convert paise to ₹, then add.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },

  // math3_ch14_money_problems — 8 Qs
  { questionId:"math3_ch14_mp_q1", topicId:"math3_ch14_money_problems", text:"A pen costs ₹15. Riya buys 3 pens. Total cost?", options:[{text:"₹18",type:"misinterpretation"},{text:"₹45",type:"correct"},{text:"₹30",type:"calculation_error"},{text:"₹50",type:"calculation_error"}], explanation:"3 × 15 = ₹45.", solutionSteps:["3 × 15 = ₹45."], shortcut:"Items × per-item cost.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mp_q2", topicId:"math3_ch14_money_problems", text:"Riya gives ₹50 for goods worth ₹45. Change received?", options:[{text:"₹95",type:"misinterpretation"},{text:"₹5",type:"correct"},{text:"₹4",type:"calculation_error"},{text:"₹15",type:"calculation_error"}], explanation:"50 − 45 = ₹5.", solutionSteps:["Change = paid − cost.","50 − 45 = ₹5."], shortcut:"Change = paid − cost.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mp_q3", topicId:"math3_ch14_money_problems", text:"5 apples cost ₹50. Cost of 1 apple?", options:[{text:"₹5",type:"calculation_error"},{text:"₹10",type:"correct"},{text:"₹25",type:"calculation_error"},{text:"₹55",type:"misinterpretation"}], explanation:"50 ÷ 5 = ₹10.", solutionSteps:["50 ÷ 5 = ₹10."], shortcut:"Cost ÷ items = per item cost.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mp_q4", topicId:"math3_ch14_money_problems", text:"Cost of 1 notebook = ₹12. Cost of 7 notebooks?", options:[{text:"₹19",type:"misinterpretation"},{text:"₹84",type:"correct"},{text:"₹84",type:"calculation_error"},{text:"₹56",type:"calculation_error"}], explanation:"7 × 12 = ₹84.", solutionSteps:["7 × 12 = ₹84."], shortcut:"Items × per-item.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mp_q5", topicId:"math3_ch14_money_problems", text:"Ramu has ₹150. He buys items worth ₹125. Money left?", options:[{text:"₹275",type:"misinterpretation"},{text:"₹25",type:"correct"},{text:"₹15",type:"calculation_error"},{text:"₹50",type:"calculation_error"}], explanation:"150 − 125 = ₹25.", solutionSteps:["Money left = had − spent.","150 − 125 = ₹25."], shortcut:"Spent = subtract.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mp_q6", topicId:"math3_ch14_money_problems", text:"A book is ₹85. A pen is ₹15. Total cost of 1 book + 1 pen?", options:[{text:"₹70",type:"calculation_error"},{text:"₹100",type:"correct"},{text:"₹95",type:"calculation_error"},{text:"₹105",type:"calculation_error"}], explanation:"85 + 15 = ₹100.", solutionSteps:["85 + 15 = ₹100."], shortcut:"Add costs.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mp_q7", topicId:"math3_ch14_money_problems", text:"₹500 ÷ 5 friends equally = ?", options:[{text:"₹50",type:"calculation_error"},{text:"₹100",type:"correct"},{text:"₹250",type:"calculation_error"},{text:"₹2500",type:"misinterpretation"}], explanation:"500 ÷ 5 = ₹100 per friend.", solutionSteps:["500 ÷ 5 = ₹100."], shortcut:"Equal share = total ÷ people.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
  { questionId:"math3_ch14_mp_q8", topicId:"math3_ch14_money_problems", text:"3 toffees cost ₹15. How many toffees can you buy with ₹50?", options:[{text:"5 toffees",type:"calculation_error"},{text:"10 toffees",type:"correct"},{text:"15 toffees",type:"calculation_error"},{text:"3 toffees",type:"misinterpretation"}], explanation:"3 toffees = ₹15 → 1 toffee = ₹5. ₹50 ÷ ₹5 = 10 toffees.", solutionSteps:["Cost per toffee = 15 ÷ 3 = ₹5.","Toffees for ₹50 = 50 ÷ 5 = 10."], shortcut:"Find unit cost, then total.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Rupees and Paise" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 3 Math v2 questions (Ch13-14).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
