/**
 * Seed: CBSE Class 10 Science — 30 practice questions
 * Topics: Chemical Reactions, Life Processes, Light, Electricity, Heredity, Control & Coordination
 * Safe to re-run — skips duplicates on { questionText, subject }
 *
 * Usage:
 *   cd ai-learning-backend/backend
 *   node config/seedScienceQuestions.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const QUESTIONS = [
  // ── 1. Chemical Reactions and Equations (5 questions) ───────────────────────
  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Types of Chemical Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is an example of a decomposition reaction?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "2H₂ + O₂ → 2H₂O", type: "concept_error", logicTag: "combination_confused_with_decomposition" },
      { text: "2FeSO₄ → Fe₂O₃ + SO₂ + SO₃", type: "correct", logicTag: "" },
      { text: "Fe + CuSO₄ → FeSO₄ + Cu", type: "concept_error", logicTag: "displacement_confused" },
      { text: "NaOH + HCl → NaCl + H₂O", type: "concept_error", logicTag: "neutralisation_confused" },
    ],
    solutionSteps: [
      "Decomposition reactions involve one compound breaking down into simpler substances.",
      "2FeSO₄ heated gives Fe₂O₃ + SO₂ + SO₃ — one compound splits into three products.",
      "The other options are combination, displacement, and neutralisation reactions respectively.",
    ],
    shortcut: "Decomposition = 1 reactant → 2+ products. Combination = 2+ reactants → 1 product.",
  },
  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Oxidation and Reduction",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the reaction: CuO + H₂ → Cu + H₂O, which substance is oxidised?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "CuO", type: "concept_error", logicTag: "oxidising_agent_confused_with_oxidised_substance" },
      { text: "H₂", type: "correct", logicTag: "" },
      { text: "Cu", type: "concept_error", logicTag: "product_confused_with_reactant" },
      { text: "H₂O", type: "concept_error", logicTag: "product_mistaken" },
    ],
    solutionSteps: [
      "Oxidation = gain of oxygen OR loss of hydrogen.",
      "H₂ gains oxygen to become H₂O → H₂ is oxidised.",
      "CuO loses oxygen to become Cu → CuO is reduced (it is the oxidising agent).",
    ],
    shortcut: "OIL RIG: Oxidation Is Loss (of electrons/hydrogen), Reduction Is Gain.",
  },
  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Corrosion and Rancidity",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Rancidity in food is primarily caused by:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Oxidation of fats and oils", type: "correct", logicTag: "" },
      { text: "Reduction of carbohydrates", type: "concept_error", logicTag: "wrong_process_type" },
      { text: "Hydrolysis of proteins", type: "concept_error", logicTag: "different_spoilage_mechanism" },
      { text: "Neutralisation of acids in food", type: "guessing", logicTag: "surface_level_guess" },
    ],
    solutionSteps: [
      "Rancidity occurs when fats and oils in food are oxidised by atmospheric oxygen.",
      "This changes the smell and taste of food, making it unfit to eat.",
      "Antioxidants (like BHA) and nitrogen flushing are used to prevent rancidity.",
    ],
    shortcut: "Rancidity = oxidation of fats. Prevent with antioxidants or inert gas packaging.",
  },
  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Balancing Chemical Equations",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which law forms the basis for balancing chemical equations?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Law of Conservation of Mass", type: "correct", logicTag: "" },
      { text: "Law of Multiple Proportions", type: "concept_error", logicTag: "different_law_confused" },
      { text: "Law of Definite Proportions", type: "concept_error", logicTag: "related_but_wrong" },
      { text: "Avogadro's Law", type: "concept_error", logicTag: "different_context" },
    ],
    solutionSteps: [
      "The Law of Conservation of Mass states that mass is neither created nor destroyed in a chemical reaction.",
      "Therefore, the total mass of reactants = total mass of products.",
      "This requires equal numbers of each type of atom on both sides of the equation.",
    ],
    shortcut: "Lavoisier's Law: atoms are rearranged, never created or destroyed.",
  },
  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Types of Chemical Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Iron displaces copper from copper sulphate solution because:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Iron is more reactive than copper", type: "correct", logicTag: "" },
      { text: "Copper is more reactive than iron", type: "concept_error", logicTag: "reactivity_series_reversed" },
      { text: "Iron has a higher atomic mass than copper", type: "concept_error", logicTag: "atomic_mass_irrelevant" },
      { text: "CuSO₄ is a weak electrolyte", type: "misinterpretation", logicTag: "irrelevant_property" },
    ],
    solutionSteps: [
      "In displacement reactions, a more reactive metal displaces a less reactive metal from its salt solution.",
      "Iron (Fe) is higher in the reactivity series than copper (Cu).",
      "Reaction: Fe + CuSO₄ → FeSO₄ + Cu",
    ],
    shortcut: "Reactivity series: K > Na > Ca > Mg > Al > Zn > Fe > Ni > Sn > Pb > H > Cu > Hg > Ag > Au.",
  },

  // ── 2. Life Processes (5 questions) ────────────────────────────────────────
  {
    topic: "Life Processes",
    subtopic: "Nutrition",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which enzyme in saliva begins the digestion of starch?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Salivary amylase", type: "correct", logicTag: "" },
      { text: "Pepsin", type: "concept_error", logicTag: "gastric_enzyme_not_salivary" },
      { text: "Lipase", type: "concept_error", logicTag: "fat_digesting_enzyme_confused" },
      { text: "Trypsin", type: "concept_error", logicTag: "pancreatic_enzyme_confused" },
    ],
    solutionSteps: [
      "Saliva contains salivary amylase (also called ptyalin).",
      "It breaks down starch into maltose — beginning carbohydrate digestion in the mouth.",
      "Pepsin works in the stomach (proteins), lipase digests fats, trypsin is pancreatic.",
    ],
    shortcut: "Mouth → amylase (starch). Stomach → pepsin (protein). Small intestine → lipase, trypsin.",
  },
  {
    topic: "Life Processes",
    subtopic: "Respiration",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "During anaerobic respiration in yeast, glucose is converted to:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Ethanol and CO₂", type: "correct", logicTag: "" },
      { text: "Lactic acid and CO₂", type: "concept_error", logicTag: "animal_anaerobic_confused" },
      { text: "CO₂ and H₂O", type: "concept_error", logicTag: "aerobic_confused" },
      { text: "Pyruvate only", type: "partial_logic", logicTag: "intermediate_only" },
    ],
    solutionSteps: [
      "Anaerobic respiration in yeast: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ + energy.",
      "Yeast produces ethanol (alcohol) and carbon dioxide — used in brewing and baking.",
      "In human muscles, anaerobic respiration produces lactic acid (no CO₂).",
    ],
    shortcut: "Yeast → ethanol + CO₂. Muscles → lactic acid. Both start from pyruvate.",
  },
  {
    topic: "Life Processes",
    subtopic: "Transportation",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which blood vessel carries oxygenated blood from the lungs to the heart?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Pulmonary artery", type: "concept_error", logicTag: "direction_reversed" },
      { text: "Pulmonary vein", type: "correct", logicTag: "" },
      { text: "Aorta", type: "concept_error", logicTag: "systemic_artery_confused" },
      { text: "Vena cava", type: "concept_error", logicTag: "deoxygenated_vein_confused" },
    ],
    solutionSteps: [
      "Pulmonary vein carries oxygenated blood from lungs → left atrium of heart.",
      "Pulmonary artery carries deoxygenated blood from right ventricle → lungs.",
      "Exception to rule: veins carry deoxygenated blood — pulmonary vein is the exception.",
    ],
    shortcut: "Pulmonary vein = O₂ rich (lung → heart). Pulmonary artery = O₂ poor (heart → lung). Exceptions!",
  },
  {
    topic: "Life Processes",
    subtopic: "Excretion",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The functional unit of the kidney is called the:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Nephron", type: "correct", logicTag: "" },
      { text: "Neuron", type: "concept_error", logicTag: "nervous_system_confused" },
      { text: "Alveolus", type: "concept_error", logicTag: "lung_unit_confused" },
      { text: "Villus", type: "concept_error", logicTag: "intestine_unit_confused" },
    ],
    solutionSteps: [
      "Each kidney contains approximately 1 million nephrons.",
      "A nephron consists of a glomerulus (filtration) and renal tubule (reabsorption).",
      "Urine is formed through filtration, selective reabsorption, and secretion.",
    ],
    shortcut: "Nephron = kidney unit. Neuron = nerve unit. Alveolus = lung unit. Villus = intestine unit.",
  },
  {
    topic: "Life Processes",
    subtopic: "Photosynthesis",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In photosynthesis, oxygen is released as a by-product from the splitting of:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.78,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Carbon dioxide", type: "concept_error", logicTag: "CO2_split_misconception" },
      { text: "Water molecules", type: "correct", logicTag: "" },
      { text: "Glucose", type: "concept_error", logicTag: "product_confused_with_source" },
      { text: "Chlorophyll", type: "concept_error", logicTag: "catalyst_confused_with_source" },
    ],
    solutionSteps: [
      "During the light-dependent reactions, water is split by photolysis: 2H₂O → 4H⁺ + 4e⁻ + O₂.",
      "The oxygen released comes entirely from water, not from CO₂.",
      "CO₂ is fixed into glucose during the Calvin cycle (light-independent reactions).",
    ],
    shortcut: "Photolysis of water → O₂ is released. O in CO₂ goes into glucose, not atmosphere.",
  },

  // ── 3. Light — Reflection and Refraction (5 questions) ─────────────────────
  {
    topic: "Light — Reflection and Refraction",
    subtopic: "Mirrors",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A concave mirror of focal length 15 cm forms a virtual, erect, and magnified image. The object must be placed:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Beyond the centre of curvature", type: "concept_error", logicTag: "real_inverted_image_region" },
      { text: "Between the focus and the pole", type: "correct", logicTag: "" },
      { text: "At the focus", type: "concept_error", logicTag: "image_at_infinity" },
      { text: "At the centre of curvature", type: "concept_error", logicTag: "same_size_real_image" },
    ],
    solutionSteps: [
      "For a concave mirror, virtual + erect + magnified → object is between pole (P) and focus (F).",
      "This is the principle used in shaving mirrors and makeup mirrors.",
      "When object is between P and F: image is behind the mirror, virtual, erect, and enlarged.",
    ],
    shortcut: "Concave mirror image table: beyond C → small real; at C → same size real; between C&F → large real; at F → infinity; between F&P → virtual enlarged.",
  },
  {
    topic: "Light — Reflection and Refraction",
    subtopic: "Refraction",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A ray of light passes from air into glass. The speed of light in glass is 2×10⁸ m/s and in air is 3×10⁸ m/s. What is the refractive index of glass?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "0.67", type: "concept_error", logicTag: "formula_inverted" },
      { text: "1.5", type: "correct", logicTag: "" },
      { text: "1.0", type: "concept_error", logicTag: "no_change_assumed" },
      { text: "2.0", type: "calculation_error", logicTag: "subtracted_instead_of_divided" },
    ],
    solutionSteps: [
      "Refractive index (n) = speed of light in vacuum (or air) / speed of light in medium.",
      "n = c/v = (3×10⁸) / (2×10⁸) = 1.5",
      "n > 1 means light slows down when entering glass from air.",
    ],
    shortcut: "n = c/v. Higher n → denser medium → slower light → more bending toward normal.",
  },
  {
    topic: "Light — Reflection and Refraction",
    subtopic: "Lenses",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The power of a lens is -2.5 D. The lens is:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Convex lens with focal length 40 cm", type: "concept_error", logicTag: "sign_ignored" },
      { text: "Concave lens with focal length 40 cm", type: "correct", logicTag: "" },
      { text: "Concave lens with focal length 25 cm", type: "calculation_error", logicTag: "wrong_conversion" },
      { text: "Convex lens with focal length 25 cm", type: "concept_error", logicTag: "sign_and_value_both_wrong" },
    ],
    solutionSteps: [
      "Power P = 1/f (in metres). So f = 1/P = 1/(-2.5) = -0.4 m = -40 cm.",
      "Negative power → negative focal length → concave (diverging) lens.",
      "Concave lenses are used to correct myopia (short-sightedness).",
    ],
    shortcut: "P = 1/f(m). Positive P = convex. Negative P = concave. f(cm) = 100/P.",
  },
  {
    topic: "Light — Reflection and Refraction",
    subtopic: "Human Eye",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The defect of vision in which a person cannot see distant objects clearly is called:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Hypermetropia", type: "concept_error", logicTag: "far_sight_confused" },
      { text: "Myopia", type: "correct", logicTag: "" },
      { text: "Presbyopia", type: "concept_error", logicTag: "age_related_defect_confused" },
      { text: "Astigmatism", type: "concept_error", logicTag: "different_defect" },
    ],
    solutionSteps: [
      "Myopia (short-sightedness): image forms in front of retina → distant objects blurry.",
      "Caused by elongated eyeball or overly curved cornea/lens.",
      "Corrected using a concave (diverging) lens.",
    ],
    shortcut: "Myopia = near OK, far blurry → concave lens. Hypermetropia = far OK, near blurry → convex lens.",
  },
  {
    topic: "Light — Reflection and Refraction",
    subtopic: "Refraction",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which phenomenon is responsible for the twinkling of stars?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.72,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Reflection of starlight", type: "concept_error", logicTag: "wrong_phenomenon" },
      { text: "Atmospheric refraction", type: "correct", logicTag: "" },
      { text: "Dispersion of light", type: "concept_error", logicTag: "rainbow_phenomenon_confused" },
      { text: "Total internal reflection", type: "concept_error", logicTag: "different_refraction_type" },
    ],
    solutionSteps: [
      "Stars are point sources of light far away. Their light passes through the atmosphere.",
      "The atmosphere has varying density layers, causing continuous refraction.",
      "This bending fluctuates rapidly, making the star's apparent position change → twinkling.",
      "Planets don't twinkle because they subtend a small disc (not a point) — fluctuations average out.",
    ],
    shortcut: "Twinkling = atmospheric refraction (stars). Planets don't twinkle — they appear as discs.",
  },

  // ── 4. Electricity (5 questions) ────────────────────────────────────────────
  {
    topic: "Electricity",
    subtopic: "Ohm's Law",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A resistor of 10 Ω is connected to a 5 V battery. What current flows through it?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "2 A", type: "concept_error", logicTag: "multiplied_instead_of_divided" },
      { text: "0.5 A", type: "correct", logicTag: "" },
      { text: "50 A", type: "calculation_error", logicTag: "decimal_error" },
      { text: "0.2 A", type: "calculation_error", logicTag: "inverted_formula" },
    ],
    solutionSteps: [
      "Ohm's Law: V = IR → I = V/R",
      "I = 5/10 = 0.5 A",
    ],
    shortcut: "V = IR triangle: cover what you want → V/R = I, V/I = R, I×R = V.",
  },
  {
    topic: "Electricity",
    subtopic: "Resistance",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Three resistors of 3 Ω each are connected in parallel. What is the equivalent resistance?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "9 Ω", type: "concept_error", logicTag: "used_series_formula" },
      { text: "1 Ω", type: "correct", logicTag: "" },
      { text: "3 Ω", type: "concept_error", logicTag: "gave_single_value" },
      { text: "1/3 Ω", type: "calculation_error", logicTag: "forgot_to_invert" },
    ],
    solutionSteps: [
      "For parallel: 1/R = 1/R₁ + 1/R₂ + 1/R₃ = 1/3 + 1/3 + 1/3 = 3/3 = 1",
      "R = 1 Ω",
      "Parallel resistance is always less than the smallest individual resistance.",
    ],
    shortcut: "n equal resistors in parallel: R_eq = R/n. Here: 3/3 = 1 Ω.",
  },
  {
    topic: "Electricity",
    subtopic: "Power and Energy",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "An electric bulb of 60 W is used for 5 hours. How many units (kWh) of electricity are consumed?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "300 units", type: "concept_error", logicTag: "watts_times_hours_not_converted" },
      { text: "0.3 units", type: "correct", logicTag: "" },
      { text: "3 units", type: "calculation_error", logicTag: "division_error" },
      { text: "12 units", type: "calculation_error", logicTag: "added_instead" },
    ],
    solutionSteps: [
      "Energy (kWh) = Power (kW) × Time (h)",
      "= (60/1000) kW × 5 h = 0.06 × 5 = 0.3 kWh",
      "1 unit of electricity = 1 kWh",
    ],
    shortcut: "kWh = (Watts/1000) × hours. Convert W to kW first!",
  },
  {
    topic: "Electricity",
    subtopic: "Heating Effect",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The heating effect of electric current is used in:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Electric motor", type: "concept_error", logicTag: "magnetic_effect_confused" },
      { text: "Electric iron and electric bulb", type: "correct", logicTag: "" },
      { text: "Transformer", type: "concept_error", logicTag: "electromagnetic_induction_confused" },
      { text: "Galvanometer", type: "concept_error", logicTag: "detection_device_confused" },
    ],
    solutionSteps: [
      "Joule's heating effect: H = I²Rt — heat produced is proportional to square of current.",
      "Electric iron and filament bulbs use this heating effect intentionally.",
      "Electric motors use the magnetic effect of current (not heating).",
    ],
    shortcut: "Joule heating: H = I²Rt. Used in bulbs, heaters, irons, fuses.",
  },
  {
    topic: "Electricity",
    subtopic: "Resistance",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "If the length of a wire is doubled and its cross-sectional area is halved, the resistance becomes:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.76,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Same", type: "concept_error", logicTag: "changes_not_considered" },
      { text: "4 times the original", type: "correct", logicTag: "" },
      { text: "2 times the original", type: "partial_logic", logicTag: "only_length_considered" },
      { text: "Half the original", type: "concept_error", logicTag: "inverse_applied_wrongly" },
    ],
    solutionSteps: [
      "R = ρL/A",
      "New length = 2L, new area = A/2",
      "New R = ρ(2L)/(A/2) = ρ × 2L × 2/A = 4ρL/A = 4R",
      "Resistance becomes 4 times the original.",
    ],
    shortcut: "R ∝ L/A. If L×2 and A÷2 → R multiplied by 2×2 = 4.",
  },

  // ── 5. Heredity and Evolution (5 questions) ─────────────────────────────────
  {
    topic: "Heredity and Evolution",
    subtopic: "Mendel's Laws",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In a monohybrid cross between tall (TT) and dwarf (tt) pea plants, the F1 generation will be:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "All dwarf", type: "concept_error", logicTag: "dominant_effect_ignored" },
      { text: "All tall", type: "correct", logicTag: "" },
      { text: "3 tall : 1 dwarf", type: "concept_error", logicTag: "F2_ratio_applied_to_F1" },
      { text: "1 tall : 1 dwarf", type: "concept_error", logicTag: "test_cross_ratio_confused" },
    ],
    solutionSteps: [
      "TT × tt → all offspring are Tt (heterozygous).",
      "T (tall) is dominant over t (dwarf), so all F1 plants appear tall.",
      "The 3:1 ratio appears in F2 when F1 plants are self-crossed.",
    ],
    shortcut: "F1 of TT × tt = all Tt = all tall (dominant shows). F2 of Tt × Tt = 3 tall : 1 dwarf.",
  },
  {
    topic: "Heredity and Evolution",
    subtopic: "Sex Determination",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The sex of a human child is determined by:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "The X chromosome from the mother", type: "concept_error", logicTag: "mother_always_gives_X" },
      { text: "The chromosome contributed by the father", type: "correct", logicTag: "" },
      { text: "Both parents equally", type: "concept_error", logicTag: "both_contribute_misconception" },
      { text: "Environmental temperature", type: "concept_error", logicTag: "reptile_mechanism_confused" },
    ],
    solutionSteps: [
      "Mother is XX — all eggs carry X chromosome.",
      "Father is XY — sperm carry either X or Y chromosome.",
      "If Y-sperm fertilises egg → XY (male). If X-sperm → XX (female).",
      "Therefore the father's contribution determines the sex of the child.",
    ],
    shortcut: "Mother → always X. Father → X gives girl, Y gives boy. Father decides sex.",
  },
  {
    topic: "Heredity and Evolution",
    subtopic: "Evolution",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Homologous organs are those that have:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Same function but different structure and origin", type: "concept_error", logicTag: "analogous_definition" },
      { text: "Same basic structure and origin but different functions", type: "correct", logicTag: "" },
      { text: "Both same structure and same function", type: "concept_error", logicTag: "identical_organs" },
      { text: "Different structure and different origin", type: "concept_error", logicTag: "vestigial_confused" },
    ],
    solutionSteps: [
      "Homologous organs: same basic design/embryological origin, but different functions.",
      "Example: forelimbs of humans (holding), bats (flying), whales (swimming), frogs (jumping).",
      "Analogous organs: same function, different structure — wings of birds and insects.",
    ],
    shortcut: "Homologous = same origin, different use (evolution proof). Analogous = same use, different origin.",
  },
  {
    topic: "Heredity and Evolution",
    subtopic: "Mendel's Laws",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In a dihybrid cross (RrYy × RrYy), what is the expected phenotypic ratio in F2?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.78,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "1:1:1:1", type: "concept_error", logicTag: "test_cross_ratio" },
      { text: "9:3:3:1", type: "correct", logicTag: "" },
      { text: "3:1", type: "concept_error", logicTag: "monohybrid_ratio" },
      { text: "1:2:1", type: "concept_error", logicTag: "genotypic_ratio_confused" },
    ],
    solutionSteps: [
      "Dihybrid cross RrYy × RrYy gives 16 combinations in the Punnett square.",
      "Phenotypic ratio: 9 (R_Y_) : 3 (R_yy) : 3 (rrY_) : 1 (rryy).",
      "This supports Mendel's Law of Independent Assortment.",
    ],
    shortcut: "Dihybrid F2 phenotypic = 9:3:3:1. Monohybrid F2 = 3:1. Test cross = 1:1 or 1:1:1:1.",
  },
  {
    topic: "Heredity and Evolution",
    subtopic: "Evolution",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is the correct order of geological time from oldest to youngest?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.74,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Reptiles → Fishes → Amphibians → Mammals", type: "concept_error", logicTag: "order_scrambled" },
      { text: "Fishes → Amphibians → Reptiles → Mammals", type: "correct", logicTag: "" },
      { text: "Amphibians → Fishes → Reptiles → Mammals", type: "concept_error", logicTag: "first_two_swapped" },
      { text: "Fishes → Reptiles → Amphibians → Mammals", type: "concept_error", logicTag: "middle_two_swapped" },
    ],
    solutionSteps: [
      "Life evolved from water to land: Marine invertebrates → Fishes → Amphibians → Reptiles → Mammals/Birds.",
      "Fishes are the oldest vertebrates (Devonian period).",
      "Amphibians evolved from fish-like ancestors, reptiles from amphibians, mammals from reptile-like ancestors.",
    ],
    shortcut: "Fish → Amphibian → Reptile → Mammal (FARM). Water → amphibious → land.",
  },

  // ── 6. Control and Coordination (5 questions) ───────────────────────────────
  {
    topic: "Control and Coordination",
    subtopic: "Nervous System",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The basic unit of the nervous system is the:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Nephron", type: "concept_error", logicTag: "kidney_unit_confused" },
      { text: "Neuron", type: "correct", logicTag: "" },
      { text: "Axon", type: "partial_logic", logicTag: "part_of_neuron_not_unit" },
      { text: "Synapse", type: "concept_error", logicTag: "junction_not_unit" },
    ],
    solutionSteps: [
      "A neuron (nerve cell) is the structural and functional unit of the nervous system.",
      "It consists of: cell body (cyton), dendrites (receive signals), axon (transmit signals).",
      "Axon and synapse are parts of a neuron, not the unit itself.",
    ],
    shortcut: "Neuron = nervous system. Nephron = kidney. Alveolus = lungs. Villus = small intestine.",
  },
  {
    topic: "Control and Coordination",
    subtopic: "Reflex Action",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A reflex arc consists of (in correct order):",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Effector → Motor neuron → Spinal cord → Sensory neuron → Receptor", type: "concept_error", logicTag: "order_completely_reversed" },
      { text: "Receptor → Sensory neuron → Spinal cord → Motor neuron → Effector", type: "correct", logicTag: "" },
      { text: "Receptor → Motor neuron → Brain → Sensory neuron → Effector", type: "concept_error", logicTag: "brain_substituted_for_spinal_cord" },
      { text: "Receptor → Sensory neuron → Brain → Motor neuron → Effector", type: "concept_error", logicTag: "brain_involved_in_reflex" },
    ],
    solutionSteps: [
      "Reflex arc pathway: Stimulus → Receptor → Afferent (sensory) neuron → Spinal cord → Efferent (motor) neuron → Effector → Response.",
      "Reflex actions do NOT involve the brain — they are processed in the spinal cord.",
      "This makes reflex actions faster than voluntary actions.",
    ],
    shortcut: "RSRME: Receptor → Sensory → (Spinal cord) → Motor → Effector. No brain = faster.",
  },
  {
    topic: "Control and Coordination",
    subtopic: "Plant Hormones",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which plant hormone is responsible for the bending of a plant stem towards light?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Gibberellin", type: "concept_error", logicTag: "stem_elongation_hormone_confused" },
      { text: "Auxin", type: "correct", logicTag: "" },
      { text: "Abscisic acid", type: "concept_error", logicTag: "inhibitory_hormone_confused" },
      { text: "Cytokinin", type: "concept_error", logicTag: "cell_division_hormone_confused" },
    ],
    solutionSteps: [
      "Auxin causes phototropism — bending of stem towards light.",
      "Light causes unequal distribution of auxin: more auxin on shaded side → more elongation.",
      "The stem bends towards light because the shaded side grows faster.",
    ],
    shortcut: "Auxin → phototropism (light bending) + geotropism (gravity). More auxin = more growth.",
  },
  {
    topic: "Control and Coordination",
    subtopic: "Human Endocrine System",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Insulin is secreted by which gland and what is its function?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Pituitary gland — controls growth", type: "concept_error", logicTag: "wrong_gland_and_function" },
      { text: "Pancreas — lowers blood glucose levels", type: "correct", logicTag: "" },
      { text: "Thyroid gland — regulates metabolism", type: "concept_error", logicTag: "different_gland_confused" },
      { text: "Adrenal gland — fight-or-flight response", type: "concept_error", logicTag: "adrenaline_confused" },
    ],
    solutionSteps: [
      "Insulin is secreted by beta cells of the islets of Langerhans in the pancreas.",
      "It lowers blood glucose by promoting uptake of glucose by cells.",
      "Deficiency of insulin causes diabetes mellitus.",
    ],
    shortcut: "Pancreas: insulin (lowers glucose), glucagon (raises glucose). Insulin IN = brings glucose IN to cells.",
  },
  {
    topic: "Control and Coordination",
    subtopic: "Human Endocrine System",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Adrenaline is often called the 'emergency hormone' because it:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.72,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Slows heart rate to conserve energy during stress", type: "concept_error", logicTag: "opposite_effect" },
      { text: "Increases heart rate, dilates airways, redirects blood to muscles for fight-or-flight", type: "correct", logicTag: "" },
      { text: "Controls long-term growth in emergencies", type: "concept_error", logicTag: "growth_hormone_confused" },
      { text: "Lowers blood glucose during emergencies", type: "concept_error", logicTag: "insulin_effect_confused" },
    ],
    solutionSteps: [
      "Adrenaline (epinephrine) is released by the adrenal glands during stress or danger.",
      "It prepares the body for 'fight-or-flight': increases heart rate, dilates bronchi, increases blood pressure.",
      "Blood is redirected from skin/digestive organs to muscles and brain.",
    ],
    shortcut: "Adrenaline = emergency → FAST (Fight-or-flight, Adrenaline, Stress, Tachycardia).",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  let added = 0, skipped = 0;
  for (const q of QUESTIONS) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    added++;
  }
  console.log(`Science questions: ${added} added, ${skipped} skipped`);
  await mongoose.disconnect();
}

seed().catch(console.error);
