/**
 * CBSE Class 6 Mathematics — MCQ seed (Part B: chapters 6–10)
 * 5 questions per chapter × 5 chapters = 25 questions
 * Usage: node config/seedMath6QuestionsB.js
 */
import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";

dotenv.config();

const questions = [
  // ─── Chapter 6: Perimeter and Area ───────────────────────────────────────
  {
    questionId: "math6_ch6_q1",
    topicId: "math6_ch6",
    text: "A rectangle has length 8 cm and breadth 5 cm. What is its perimeter?",
    options: [
      { text: "26 cm",  type: "correct",           logicTag: "P = 2(l+b) = 2(8+5) = 26" },
      { text: "40 cm",  type: "concept_error",      logicTag: "Confused perimeter with area" },
      { text: "13 cm",  type: "partial_logic",      logicTag: "Added l+b without multiplying by 2" },
      { text: "20 cm",  type: "calculation_error",  logicTag: "Used 2×(5+5) instead of 2×(8+5)" },
    ],
    explanation: "Perimeter of a rectangle = 2(length + breadth) = 2(8 + 5) = 2 × 13 = 26 cm.",
    solutionSteps: [
      "Identify length = 8 cm, breadth = 5 cm.",
      "Apply formula: P = 2(l + b).",
      "P = 2(8 + 5) = 2 × 13 = 26 cm.",
    ],
    shortcut: "Think of walking all four sides: two lengths and two breadths.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Perimeter and Area",
  },
  {
    questionId: "math6_ch6_q2",
    topicId: "math6_ch6",
    text: "What is the area of a rectangle with length 12 cm and breadth 4 cm?",
    options: [
      { text: "48 cm²", type: "correct",           logicTag: "A = l × b = 12 × 4 = 48" },
      { text: "32 cm",  type: "concept_error",      logicTag: "Calculated perimeter instead of area" },
      { text: "16 cm²", type: "calculation_error",  logicTag: "Added l+b instead of multiplying" },
      { text: "48 cm",  type: "concept_error",      logicTag: "Correct value but wrong unit" },
    ],
    explanation: "Area of a rectangle = length × breadth = 12 × 4 = 48 cm².",
    solutionSteps: [
      "Identify length = 12 cm, breadth = 4 cm.",
      "Apply formula: A = l × b.",
      "A = 12 × 4 = 48 cm².",
    ],
    shortcut: "Area fills the inside; perimeter goes around the outside.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Perimeter and Area",
  },
  {
    questionId: "math6_ch6_q3",
    topicId: "math6_ch6",
    text: "A square has perimeter 36 cm. What is its side length?",
    options: [
      { text: "9 cm",  type: "correct",           logicTag: "side = 36 ÷ 4 = 9" },
      { text: "18 cm", type: "concept_error",      logicTag: "Divided by 2 (treating as rectangle)" },
      { text: "12 cm", type: "calculation_error",  logicTag: "Divided 36 by 3" },
      { text: "36 cm", type: "guessing",           logicTag: "Did not divide at all" },
    ],
    explanation: "All four sides of a square are equal. Side = Perimeter ÷ 4 = 36 ÷ 4 = 9 cm.",
    solutionSteps: [
      "A square has 4 equal sides.",
      "Side = Perimeter ÷ 4 = 36 ÷ 4 = 9 cm.",
    ],
    shortcut: "Square perimeter ÷ 4 = side length.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Perimeter and Area",
  },
  {
    questionId: "math6_ch6_q4",
    topicId: "math6_ch6",
    text: "What is the area of a triangle with base 10 cm and height 6 cm?",
    options: [
      { text: "30 cm²", type: "correct",           logicTag: "A = ½ × base × height = ½ × 10 × 6 = 30" },
      { text: "60 cm²", type: "concept_error",      logicTag: "Forgot to halve — used A = b × h" },
      { text: "16 cm²", type: "calculation_error",  logicTag: "Added base + height instead of multiplying" },
      { text: "15 cm²", type: "partial_logic",      logicTag: "Halved only one dimension" },
    ],
    explanation: "Area of a triangle = ½ × base × height = ½ × 10 × 6 = 30 cm².",
    solutionSteps: [
      "Identify base = 10 cm, height = 6 cm.",
      "Apply formula: A = ½ × b × h.",
      "A = ½ × 10 × 6 = 30 cm².",
    ],
    shortcut: "A triangle is half of a rectangle — always divide by 2.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Perimeter and Area",
  },
  {
    questionId: "math6_ch6_q5",
    topicId: "math6_ch6",
    text: "A room measures 6 m × 4 m. How many square tiles of side 1 m are needed to cover its floor?",
    options: [
      { text: "24",  type: "correct",           logicTag: "Area = 6 × 4 = 24 tiles" },
      { text: "20",  type: "calculation_error",  logicTag: "Calculated perimeter instead" },
      { text: "10",  type: "concept_error",      logicTag: "Added 6+4 only" },
      { text: "48",  type: "calculation_error",  logicTag: "Doubled the area" },
    ],
    explanation: "Number of tiles = Floor area ÷ Tile area = (6 × 4) ÷ 1 = 24 tiles.",
    solutionSteps: [
      "Floor area = 6 m × 4 m = 24 m².",
      "Each tile covers 1 m² = 1 × 1.",
      "Tiles needed = 24 ÷ 1 = 24.",
    ],
    shortcut: "Tiles needed = floor area when tile area = 1 unit².",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Perimeter and Area",
  },

  // ─── Chapter 7: Fractions ─────────────────────────────────────────────────
  {
    questionId: "math6_ch7_q1",
    topicId: "math6_ch7",
    text: "Which fraction is equivalent to 2/3?",
    options: [
      { text: "4/6",  type: "correct",           logicTag: "2×2 / 3×2 = 4/6" },
      { text: "3/4",  type: "concept_error",      logicTag: "Incremented numerator and denominator by 1" },
      { text: "2/6",  type: "partial_logic",      logicTag: "Doubled denominator only" },
      { text: "6/4",  type: "concept_error",      logicTag: "Swapped and doubled" },
    ],
    explanation: "Equivalent fractions are made by multiplying numerator and denominator by the same number. 2/3 × (2/2) = 4/6.",
    solutionSteps: [
      "Multiply numerator and denominator of 2/3 by 2.",
      "2×2 = 4 and 3×2 = 6.",
      "So 4/6 is equivalent to 2/3.",
    ],
    shortcut: "Same multiplier top and bottom → equivalent fraction.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Fractions",
  },
  {
    questionId: "math6_ch7_q2",
    topicId: "math6_ch7",
    text: "Which is the larger fraction: 3/4 or 5/8?",
    options: [
      { text: "3/4",  type: "correct",           logicTag: "3/4 = 6/8 > 5/8" },
      { text: "5/8",  type: "concept_error",      logicTag: "Larger numerator assumed larger fraction" },
      { text: "Equal", type: "concept_error",     logicTag: "Did not convert to common denominator" },
      { text: "Cannot tell", type: "guessing",    logicTag: "Avoided comparison" },
    ],
    explanation: "Convert to common denominator: 3/4 = 6/8. Since 6/8 > 5/8, the fraction 3/4 is larger.",
    solutionSteps: [
      "LCM of 4 and 8 is 8.",
      "3/4 = 6/8.",
      "Compare: 6/8 > 5/8, so 3/4 > 5/8.",
    ],
    shortcut: "Convert to same denominator, then compare numerators.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Fractions",
  },
  {
    questionId: "math6_ch7_q3",
    topicId: "math6_ch7",
    text: "What is 1/4 + 1/4?",
    options: [
      { text: "1/2",  type: "correct",           logicTag: "1/4 + 1/4 = 2/4 = 1/2" },
      { text: "2/8",  type: "concept_error",      logicTag: "Added numerators and denominators separately" },
      { text: "1/8",  type: "concept_error",      logicTag: "Multiplied instead of added" },
      { text: "2/4",  type: "partial_logic",      logicTag: "Correct value but not simplified" },
    ],
    explanation: "When denominators are the same, add the numerators: 1/4 + 1/4 = 2/4 = 1/2 (simplified).",
    solutionSteps: [
      "Denominators are same (4).",
      "Add numerators: 1 + 1 = 2.",
      "Result: 2/4 = 1/2.",
    ],
    shortcut: "Same denominator → just add the tops.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Fractions",
  },
  {
    questionId: "math6_ch7_q4",
    topicId: "math6_ch7",
    text: "What is 3/5 − 1/5?",
    options: [
      { text: "2/5",  type: "correct",           logicTag: "3/5 − 1/5 = 2/5" },
      { text: "2/10", type: "concept_error",      logicTag: "Subtracted denominators too" },
      { text: "4/5",  type: "calculation_error",  logicTag: "Added instead of subtracted" },
      { text: "1/5",  type: "calculation_error",  logicTag: "Subtracted wrong numerator" },
    ],
    explanation: "Same denominator: subtract the numerators. 3/5 − 1/5 = (3−1)/5 = 2/5.",
    solutionSteps: [
      "Denominators are same (5).",
      "Subtract numerators: 3 − 1 = 2.",
      "Result: 2/5.",
    ],
    shortcut: "Same denominator → just subtract the tops.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Fractions",
  },
  {
    questionId: "math6_ch7_q5",
    topicId: "math6_ch7",
    text: "Simplify the fraction 12/16 to its lowest terms.",
    options: [
      { text: "3/4",  type: "correct",           logicTag: "GCD(12,16)=4; 12÷4=3, 16÷4=4" },
      { text: "6/8",  type: "partial_logic",      logicTag: "Divided by 2 but not fully simplified" },
      { text: "4/3",  type: "concept_error",      logicTag: "Inverted the fraction" },
      { text: "12/16", type: "guessing",          logicTag: "Did not simplify" },
    ],
    explanation: "GCD of 12 and 16 is 4. Divide both: 12÷4 = 3, 16÷4 = 4. Simplified form: 3/4.",
    solutionSteps: [
      "Find GCD(12, 16) = 4.",
      "Divide numerator: 12 ÷ 4 = 3.",
      "Divide denominator: 16 ÷ 4 = 4.",
      "Simplified fraction: 3/4.",
    ],
    shortcut: "Divide top and bottom by their GCD to reach lowest terms.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Fractions",
  },

  // ─── Chapter 8: Playing with Constructions ────────────────────────────────
  {
    questionId: "math6_ch8_q1",
    topicId: "math6_ch8",
    text: "Which instrument is used to draw a circle of a given radius?",
    options: [
      { text: "Compass",  type: "correct",          logicTag: "Compass draws circles" },
      { text: "Ruler",    type: "concept_error",     logicTag: "Ruler measures length, not circles" },
      { text: "Protractor", type: "concept_error",   logicTag: "Protractor measures angles" },
      { text: "Set square", type: "concept_error",   logicTag: "Set square draws right angles" },
    ],
    explanation: "A compass is used to draw circles. You set the distance (radius) between the pencil tip and needle, then rotate.",
    solutionSteps: [
      "Set compass opening to the required radius.",
      "Place needle at the centre point.",
      "Rotate pencil end to draw the circle.",
    ],
    shortcut: "Compass = circle drawer; ruler = length measurer.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Playing with Constructions",
  },
  {
    questionId: "math6_ch8_q2",
    topicId: "math6_ch8",
    text: "What is the relationship between the diameter and radius of a circle?",
    options: [
      { text: "Diameter = 2 × Radius",   type: "correct",           logicTag: "d = 2r" },
      { text: "Radius = 2 × Diameter",   type: "concept_error",     logicTag: "Inverted the relationship" },
      { text: "Diameter = Radius + 1",   type: "concept_error",     logicTag: "Added constant instead of doubling" },
      { text: "Diameter = Radius / 2",   type: "concept_error",     logicTag: "Halved instead of doubled" },
    ],
    explanation: "The diameter passes through the centre of the circle, so it equals twice the radius: d = 2r.",
    solutionSteps: [
      "Radius = distance from centre to edge.",
      "Diameter = distance from one edge to the other through the centre.",
      "Diameter = Radius + Radius = 2 × Radius.",
    ],
    shortcut: "d = 2r; r = d/2.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Playing with Constructions",
  },
  {
    questionId: "math6_ch8_q3",
    topicId: "math6_ch8",
    text: "A chord of a circle is a line segment joining two points on the circle. What is the longest possible chord?",
    options: [
      { text: "Diameter",  type: "correct",          logicTag: "Diameter is the longest chord" },
      { text: "Radius",    type: "concept_error",     logicTag: "Radius connects centre to edge, not two edge points" },
      { text: "Arc",       type: "concept_error",     logicTag: "An arc is curved, not a chord" },
      { text: "Secant",    type: "concept_error",     logicTag: "Secant extends beyond the circle" },
    ],
    explanation: "The longest chord passes through the centre of the circle, which is the diameter.",
    solutionSteps: [
      "A chord connects two points on the circle.",
      "The chord is longest when it passes through the centre.",
      "A chord through the centre is the diameter.",
    ],
    shortcut: "Longest chord = diameter.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Playing with Constructions",
  },
  {
    questionId: "math6_ch8_q4",
    topicId: "math6_ch8",
    text: "To construct a perpendicular bisector using a compass and ruler, what is the first step?",
    options: [
      { text: "Draw arcs from both ends of the line segment with the same radius", type: "correct", logicTag: "Standard perpendicular bisector construction first step" },
      { text: "Draw a circle centred at one endpoint",                             type: "concept_error", logicTag: "This gives a circle, not a perpendicular bisector" },
      { text: "Measure the length and mark the midpoint directly",                 type: "concept_error", logicTag: "Marking midpoint directly is not a compass construction" },
      { text: "Draw any two lines and find their intersection",                    type: "guessing",      logicTag: "Random intersection is not the bisector" },
    ],
    explanation: "Draw arcs of the same radius from both endpoints — the two intersection points of the arcs define the perpendicular bisector.",
    solutionSteps: [
      "Open compass to more than half the segment length.",
      "Draw arcs from each endpoint above and below the segment.",
      "Connect the two arc intersection points to get the perpendicular bisector.",
    ],
    shortcut: "Same radius arcs from both ends → their intersections give the bisector.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Playing with Constructions",
  },
  {
    questionId: "math6_ch8_q5",
    topicId: "math6_ch8",
    text: "If you set a compass to 5 cm and draw a circle, what is the circumference of that circle? (Use π ≈ 3.14)",
    options: [
      { text: "31.4 cm",  type: "correct",           logicTag: "C = 2πr = 2 × 3.14 × 5 = 31.4" },
      { text: "78.5 cm²", type: "concept_error",      logicTag: "Calculated area πr² instead" },
      { text: "15.7 cm",  type: "calculation_error",  logicTag: "Forgot to multiply by 2 (used πr)" },
      { text: "10 cm",    type: "concept_error",      logicTag: "Gave diameter, not circumference" },
    ],
    explanation: "The compass is set to the radius = 5 cm. Circumference C = 2πr = 2 × 3.14 × 5 = 31.4 cm.",
    solutionSteps: [
      "Radius r = 5 cm (compass setting).",
      "C = 2 × π × r = 2 × 3.14 × 5.",
      "C = 31.4 cm.",
    ],
    shortcut: "C = 2πr; Area = πr². Don't mix them up.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Playing with Constructions",
  },

  // ─── Chapter 9: Symmetry ──────────────────────────────────────────────────
  {
    questionId: "math6_ch9_q1",
    topicId: "math6_ch9",
    text: "How many lines of symmetry does a square have?",
    options: [
      { text: "4",  type: "correct",           logicTag: "Two diagonals + two midpoint lines = 4" },
      { text: "2",  type: "partial_logic",      logicTag: "Counted only the midpoint lines" },
      { text: "1",  type: "concept_error",      logicTag: "Only counted one axis" },
      { text: "0",  type: "concept_error",      logicTag: "Denied symmetry" },
    ],
    explanation: "A square has 4 lines of symmetry: 2 through opposite midpoints, and 2 along diagonals.",
    solutionSteps: [
      "Fold vertically through midpoints → matches. ✓",
      "Fold horizontally through midpoints → matches. ✓",
      "Fold along one diagonal → matches. ✓",
      "Fold along the other diagonal → matches. ✓",
      "Total = 4 lines of symmetry.",
    ],
    shortcut: "Regular polygon with n sides has n lines of symmetry.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Symmetry",
  },
  {
    questionId: "math6_ch9_q2",
    topicId: "math6_ch9",
    text: "How many lines of symmetry does an equilateral triangle have?",
    options: [
      { text: "3",  type: "correct",           logicTag: "Each vertex to opposite midpoint = 3" },
      { text: "1",  type: "partial_logic",      logicTag: "Counted only one axis" },
      { text: "6",  type: "concept_error",      logicTag: "Confused with hexagon" },
      { text: "0",  type: "concept_error",      logicTag: "Denied symmetry" },
    ],
    explanation: "An equilateral triangle has 3 lines of symmetry — each passes through a vertex and the midpoint of the opposite side.",
    solutionSteps: [
      "Draw from vertex 1 to midpoint of opposite side → line of symmetry.",
      "Repeat for vertex 2 → another line.",
      "Repeat for vertex 3 → third line.",
      "Total = 3.",
    ],
    shortcut: "Equilateral triangle: 3 sides → 3 lines of symmetry.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "Symmetry",
  },
  {
    questionId: "math6_ch9_q3",
    topicId: "math6_ch9",
    text: "What is the order of rotational symmetry of a regular hexagon?",
    options: [
      { text: "6",  type: "correct",           logicTag: "Rotates onto itself 6 times in 360°" },
      { text: "3",  type: "partial_logic",      logicTag: "Only counted alternating positions" },
      { text: "2",  type: "concept_error",      logicTag: "Confused with 180° symmetry" },
      { text: "1",  type: "concept_error",      logicTag: "Every shape has at least order 1" },
    ],
    explanation: "A regular hexagon maps onto itself every 60° rotation. 360° ÷ 60° = 6. Order of rotational symmetry = 6.",
    solutionSteps: [
      "Angle of rotational symmetry = 360° ÷ number of sides.",
      "For hexagon: 360° ÷ 6 = 60°.",
      "Rotations before returning to start: 360° ÷ 60° = 6.",
      "Order = 6.",
    ],
    shortcut: "Order of rotational symmetry = number of sides for a regular polygon.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Symmetry",
  },
  {
    questionId: "math6_ch9_q4",
    topicId: "math6_ch9",
    text: "Which of the following letters has exactly one line of symmetry?",
    options: [
      { text: "A",  type: "correct",           logicTag: "A has one vertical line of symmetry" },
      { text: "X",  type: "concept_error",      logicTag: "X has two lines of symmetry" },
      { text: "O",  type: "concept_error",      logicTag: "O has infinite lines of symmetry" },
      { text: "Z",  type: "concept_error",      logicTag: "Z has no line symmetry (rotational only)" },
    ],
    explanation: "The letter A has exactly one vertical line of symmetry splitting it into two mirror halves. X has two, O has infinite, Z has none.",
    solutionSteps: [
      "A: fold vertically — left and right match. No horizontal fold works. One line.",
      "X: both vertical and horizontal folds work. Two lines.",
      "O: any fold through centre works. Infinite lines.",
      "Z: no fold produces a mirror image. Zero lines.",
    ],
    shortcut: "Visualise folding the letter — count how many folds give exact overlap.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Symmetry",
  },
  {
    questionId: "math6_ch9_q5",
    topicId: "math6_ch9",
    text: "A shape has rotational symmetry of order 4. By how many degrees does it rotate to map onto itself?",
    options: [
      { text: "90°",  type: "correct",           logicTag: "360° ÷ 4 = 90°" },
      { text: "45°",  type: "calculation_error",  logicTag: "360° ÷ 8 = 45°, wrong divisor" },
      { text: "180°", type: "concept_error",      logicTag: "180° gives order 2, not 4" },
      { text: "120°", type: "concept_error",      logicTag: "120° gives order 3, not 4" },
    ],
    explanation: "Order of rotational symmetry = 4 means it maps onto itself 4 times in one full rotation. Angle = 360° ÷ 4 = 90°.",
    solutionSteps: [
      "Full rotation = 360°.",
      "Order 4 means 4 identical positions.",
      "Angle per rotation = 360° ÷ 4 = 90°.",
    ],
    shortcut: "Rotation angle = 360° ÷ order.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "Symmetry",
  },

  // ─── Chapter 10: The Other Side of Zero ──────────────────────────────────
  {
    questionId: "math6_ch10_q1",
    topicId: "math6_ch10",
    text: "Which of the following is a negative integer?",
    options: [
      { text: "−5",  type: "correct",           logicTag: "Negative integers are left of zero on number line" },
      { text: "0",   type: "concept_error",      logicTag: "0 is neither positive nor negative" },
      { text: "5",   type: "concept_error",      logicTag: "5 is a positive integer" },
      { text: "1/2", type: "concept_error",      logicTag: "1/2 is a fraction, not an integer" },
    ],
    explanation: "Integers to the left of 0 on the number line are negative integers. −5 is a negative integer.",
    solutionSteps: [
      "Integers: ..., −3, −2, −1, 0, 1, 2, 3, ...",
      "Negative integers are those less than 0.",
      "−5 < 0, so −5 is a negative integer.",
    ],
    shortcut: "Negative sign in front = left of zero.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "The Other Side of Zero",
  },
  {
    questionId: "math6_ch10_q2",
    topicId: "math6_ch10",
    text: "What is the result of (−3) + 5?",
    options: [
      { text: "2",   type: "correct",           logicTag: "Move 5 right from −3: −3+5=2" },
      { text: "−8",  type: "concept_error",      logicTag: "Added magnitudes with negative sign" },
      { text: "8",   type: "concept_error",      logicTag: "Added magnitudes ignoring signs" },
      { text: "−2",  type: "calculation_error",  logicTag: "Got sign wrong: 5−3=2 not −2" },
    ],
    explanation: "Start at −3 on the number line, move 5 steps to the right: −3 + 5 = 2.",
    solutionSteps: [
      "On the number line, start at −3.",
      "Move 5 places to the right (positive direction).",
      "Land at −3 + 5 = 2.",
    ],
    shortcut: "Opposite signs: subtract smaller magnitude from larger, keep sign of larger.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "The Other Side of Zero",
  },
  {
    questionId: "math6_ch10_q3",
    topicId: "math6_ch10",
    text: "Which statement is true about integers on a number line?",
    options: [
      { text: "Numbers increase as you move to the right",      type: "correct",       logicTag: "Standard number line direction" },
      { text: "Numbers increase as you move to the left",       type: "concept_error", logicTag: "Reversed direction" },
      { text: "Negative numbers are greater than positive ones", type: "concept_error", logicTag: "Reversed inequality" },
      { text: "Zero is a positive number",                      type: "concept_error", logicTag: "Zero is neither positive nor negative" },
    ],
    explanation: "On a standard number line, numbers increase from left to right. Positive numbers are to the right of 0; negative numbers are to the left.",
    solutionSteps: [
      "Standard number line: ← negative | 0 | positive →.",
      "Moving right = increasing value.",
      "−5 < −1 < 0 < 3 < 7.",
    ],
    shortcut: "Right = bigger; Left = smaller on a number line.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "6",
    chapter: "The Other Side of Zero",
  },
  {
    questionId: "math6_ch10_q4",
    topicId: "math6_ch10",
    text: "What is (−7) − (−3)?",
    options: [
      { text: "−4",  type: "correct",           logicTag: "(−7) − (−3) = −7 + 3 = −4" },
      { text: "−10", type: "concept_error",      logicTag: "Added instead: −7 + (−3) = −10" },
      { text: "4",   type: "calculation_error",  logicTag: "Ignored the leading negative: 7−3=4" },
      { text: "10",  type: "concept_error",      logicTag: "Added magnitudes without checking signs" },
    ],
    explanation: "Subtracting a negative is the same as adding a positive: (−7) − (−3) = −7 + 3 = −4.",
    solutionSteps: [
      "Rewrite: (−7) − (−3) = (−7) + 3.",
      "On number line: start at −7, move 3 right.",
      "−7 + 3 = −4.",
    ],
    shortcut: "Minus a minus = plus: a − (−b) = a + b.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "The Other Side of Zero",
  },
  {
    questionId: "math6_ch10_q5",
    topicId: "math6_ch10",
    text: "A submarine is at −40 m (below sea level). It rises 15 m. What is its new position?",
    options: [
      { text: "−25 m",  type: "correct",           logicTag: "−40 + 15 = −25" },
      { text: "−55 m",  type: "concept_error",      logicTag: "Subtracted instead of adding" },
      { text: "25 m",   type: "calculation_error",  logicTag: "Ignored negative sign" },
      { text: "55 m",   type: "concept_error",      logicTag: "Added magnitudes with wrong sign" },
    ],
    explanation: "Starting at −40 m and rising 15 m: new position = −40 + 15 = −25 m (still below sea level).",
    solutionSteps: [
      "Initial position = −40 m.",
      "Rise = +15 m.",
      "New position = −40 + 15 = −25 m.",
    ],
    shortcut: "Rising = positive change; falling = negative change.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "6",
    chapter: "The Other Side of Zero",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");

  for (const q of questions) {
    await Question.findOneAndUpdate(
      { questionId: q.questionId },
      q,
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`  ✓ ${q.questionId}`);
  }

  console.log(`\nSeeded ${questions.length} questions for Class 6 Math (Part B, Ch 6–10).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
