import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math3_ch7_reading_clock — 8 Qs
  { questionId:"math3_ch7_rc_q1", topicId:"math3_ch7_reading_clock", text:"The SHORT hand on a clock shows…", options:[{text:"Minutes",type:"concept_error"},{text:"Hours",type:"correct"},{text:"Seconds",type:"misinterpretation"},{text:"Date",type:"guessing"}], explanation:"Short hand = hour hand.", solutionSteps:["Short = hour.","Long = minute."], shortcut:"Short = hour.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_rc_q2", topicId:"math3_ch7_reading_clock", text:"Short hand on 3, long hand on 12. What time is it?", options:[{text:"3:30",type:"concept_error"},{text:"3:00",type:"correct"},{text:"12:30",type:"misinterpretation"},{text:"12:00",type:"calculation_error"}], explanation:"Long hand on 12 = 0 minutes. Short on 3 = 3 hours. Time = 3:00.", solutionSteps:["Long on 12 → 0 minutes.","Short on 3 → 3 hours.","→ 3:00."], shortcut:"Long on 12 = sharp hour.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_rc_q3", topicId:"math3_ch7_reading_clock", text:"Short on 5, long on 6. What time is it?", options:[{text:"5:30",type:"correct"},{text:"6:30",type:"misinterpretation"},{text:"5:06",type:"calculation_error"},{text:"6:05",type:"calculation_error"}], explanation:"Long on 6 = 6 × 5 = 30 minutes. Short on 5 = 5 hours. Time = 5:30.", solutionSteps:["Long on 6 → 30 minutes.","Short on 5 → 5 hours.","→ 5:30."], shortcut:"Minute hand: number × 5.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_rc_q4", topicId:"math3_ch7_reading_clock", text:"How many minutes does the LONG hand take to go all the way around the clock?", options:[{text:"15 min",type:"calculation_error"},{text:"30 min",type:"calculation_error"},{text:"60 min",type:"correct"},{text:"12 hours",type:"misinterpretation"}], explanation:"Minute hand completes 1 full circle in 60 minutes (1 hour).", solutionSteps:["Minute hand goes 360° in 60 min.","One full revolution = 60 minutes."], shortcut:"Minute hand: 1 round per hour.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_rc_q5", topicId:"math3_ch7_reading_clock", text:"If the long hand is on 3, how many minutes past the hour?", options:[{text:"3 minutes",type:"concept_error"},{text:"15 minutes",type:"correct"},{text:"30 minutes",type:"calculation_error"},{text:"45 minutes",type:"calculation_error"}], explanation:"Each number = 5 minutes. 3 × 5 = 15 minutes.", solutionSteps:["Number × 5 = minutes.","3 × 5 = 15."], shortcut:"Minute = clock number × 5.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_rc_q6", topicId:"math3_ch7_reading_clock", text:"What time when long hand is on 9 and short hand is between 7 and 8?", options:[{text:"7:09",type:"calculation_error"},{text:"7:45",type:"correct"},{text:"9:35",type:"misinterpretation"},{text:"8:45",type:"calculation_error"}], explanation:"Long on 9 = 45 min. Short between 7 & 8 → still 7 hours. Time = 7:45.", solutionSteps:["Long on 9 → 45 min.","Short between 7 and 8 → hour = 7.","→ 7:45."], shortcut:"Use the lower hour when short is between two numbers.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_rc_q7", topicId:"math3_ch7_reading_clock", text:"How many minutes are there in half an hour?", options:[{text:"30",type:"correct"},{text:"60",type:"misinterpretation"},{text:"15",type:"calculation_error"},{text:"45",type:"calculation_error"}], explanation:"Half of 60 = 30 minutes.", solutionSteps:["1 hour = 60 min.","Half = 30 min."], shortcut:"Half hour = 30 min.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_rc_q8", topicId:"math3_ch7_reading_clock", text:"Quarter past 4 means…", options:[{text:"4:15",type:"correct"},{text:"4:30",type:"calculation_error"},{text:"4:45",type:"calculation_error"},{text:"3:45",type:"misinterpretation"}], explanation:"Quarter = 15 min. Quarter past 4 = 4:15.", solutionSteps:["Quarter hour = 15 min.","Past 4 → 4 + 15 = 4:15."], shortcut:"Quarter past = :15.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },

  // math3_ch7_am_pm — 8 Qs
  { questionId:"math3_ch7_ap_q1", topicId:"math3_ch7_am_pm", text:"AM means…", options:[{text:"After Midnight",type:"partial_logic"},{text:"Before Noon (midnight to 12 noon)",type:"correct"},{text:"After Noon",type:"misinterpretation"},{text:"All Morning",type:"guessing"}], explanation:"AM = Ante Meridiem = before noon (12 midnight to 12 noon).", solutionSteps:["AM = before noon.","From 12 midnight to 12 noon."], shortcut:"AM = morning side.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ap_q2", topicId:"math3_ch7_am_pm", text:"PM means…", options:[{text:"Past Midnight",type:"misinterpretation"},{text:"After Noon (12 noon to 12 midnight)",type:"correct"},{text:"Before Morning",type:"concept_error"},{text:"Past Morning",type:"guessing"}], explanation:"PM = Post Meridiem = after noon (12 noon to 12 midnight).", solutionSteps:["PM = after noon.","From 12 noon to 12 midnight."], shortcut:"PM = afternoon/evening.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ap_q3", topicId:"math3_ch7_am_pm", text:"School usually starts at 8…", options:[{text:"PM",type:"concept_error"},{text:"AM",type:"correct"},{text:"Either",type:"misinterpretation"},{text:"Noon",type:"guessing"}], explanation:"8 in the morning is AM.", solutionSteps:["School morning = AM."], shortcut:"Morning = AM.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ap_q4", topicId:"math3_ch7_am_pm", text:"Dinner time at 8 is in…", options:[{text:"AM",type:"concept_error"},{text:"PM",type:"correct"},{text:"Noon",type:"misinterpretation"},{text:"Midnight",type:"misinterpretation"}], explanation:"8 in the evening = 8 PM.", solutionSteps:["Evening time = PM.","8 PM = dinner time."], shortcut:"Evening = PM.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ap_q5", topicId:"math3_ch7_am_pm", text:"12 noon is…", options:[{text:"12 AM",type:"concept_error"},{text:"12 PM",type:"correct"},{text:"Either",type:"partial_logic"},{text:"Doesn't matter",type:"misinterpretation"}], explanation:"12 noon = 12 PM (transition from AM to PM happens at noon).", solutionSteps:["AM ends at 12 noon.","PM begins at 12 noon.","12 noon labelled 12 PM."], shortcut:"Noon = 12 PM.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ap_q6", topicId:"math3_ch7_am_pm", text:"12 midnight is…", options:[{text:"12 PM",type:"concept_error"},{text:"12 AM",type:"correct"},{text:"Noon",type:"misinterpretation"},{text:"00:00",type:"partial_logic"}], explanation:"12 midnight = 12 AM (start of a new day).", solutionSteps:["Midnight starts the new day.","Labelled 12 AM (or 00:00)."], shortcut:"Midnight = 12 AM.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ap_q7", topicId:"math3_ch7_am_pm", text:"How many hours are in AM (from 12 midnight to 12 noon)?", options:[{text:"6",type:"calculation_error"},{text:"12",type:"correct"},{text:"24",type:"misinterpretation"},{text:"1",type:"concept_error"}], explanation:"AM spans 12 midnight to 12 noon = 12 hours.", solutionSteps:["AM: 12 midnight to 12 noon.","Span = 12 hours."], shortcut:"AM = 12 hours.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ap_q8", topicId:"math3_ch7_am_pm", text:"At 3:30 PM, what time of day is it?", options:[{text:"Morning",type:"concept_error"},{text:"Afternoon",type:"correct"},{text:"Late night",type:"misinterpretation"},{text:"Sunrise",type:"calculation_error"}], explanation:"3:30 PM = 3:30 in the afternoon.", solutionSteps:["PM = afternoon/evening.","3:30 PM is afternoon."], shortcut:"3:30 PM = afternoon.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },

  // math3_ch7_calendar — 8 Qs
  { questionId:"math3_ch7_ca_q1", topicId:"math3_ch7_calendar", text:"How many months are there in a year?", options:[{text:"10",type:"concept_error"},{text:"12",type:"correct"},{text:"24",type:"misinterpretation"},{text:"7",type:"calculation_error"}], explanation:"A year has 12 months.", solutionSteps:["Jan to Dec = 12 months."], shortcut:"Year = 12 months.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ca_q2", topicId:"math3_ch7_calendar", text:"Which month has 28 (or 29) days?", options:[{text:"January",type:"concept_error"},{text:"February",type:"correct"},{text:"April",type:"calculation_error"},{text:"September",type:"calculation_error"}], explanation:"February has 28 days, or 29 in a leap year.", solutionSteps:["February: 28 days normally.","Leap year: 29."], shortcut:"Feb = 28 or 29.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ca_q3", topicId:"math3_ch7_calendar", text:"How many days are in a (non-leap) year?", options:[{text:"360",type:"calculation_error"},{text:"365",type:"correct"},{text:"366",type:"calculation_error"},{text:"400",type:"misinterpretation"}], explanation:"A regular year has 365 days; a leap year has 366.", solutionSteps:["12 months ≈ 365 days.","Leap year = 366."], shortcut:"Normal year = 365 days.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ca_q4", topicId:"math3_ch7_calendar", text:"How many days are in a week?", options:[{text:"5",type:"concept_error"},{text:"7",type:"correct"},{text:"10",type:"calculation_error"},{text:"30",type:"misinterpretation"}], explanation:"Mon, Tue, Wed, Thu, Fri, Sat, Sun = 7 days.", solutionSteps:["7 named days = 1 week."], shortcut:"Week = 7 days.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ca_q5", topicId:"math3_ch7_calendar", text:"How many days does June have?", options:[{text:"28",type:"concept_error"},{text:"30",type:"correct"},{text:"31",type:"calculation_error"},{text:"29",type:"calculation_error"}], explanation:"June = 30 days. (April, June, September, November all have 30.)", solutionSteps:["April, June, September, November = 30 days.","Feb = 28 or 29.","Rest = 31."], shortcut:"30 days: Apr, Jun, Sep, Nov.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ca_q6", topicId:"math3_ch7_calendar", text:"How many hours in a day?", options:[{text:"12",type:"concept_error"},{text:"24",type:"correct"},{text:"60",type:"misinterpretation"},{text:"7",type:"calculation_error"}], explanation:"24 hours = 1 day.", solutionSteps:["AM = 12 hours.","PM = 12 hours.","Total = 24."], shortcut:"Day = 24 hours.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ca_q7", topicId:"math3_ch7_calendar", text:"Which month comes RIGHT AFTER August?", options:[{text:"July",type:"misinterpretation"},{text:"September",type:"correct"},{text:"October",type:"calculation_error"},{text:"June",type:"misinterpretation"}], explanation:"Aug → Sep (in calendar order).", solutionSteps:["Months order: Aug → Sep."], shortcut:"After Aug = Sep.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_ca_q8", topicId:"math3_ch7_calendar", text:"In a leap year, February has…", options:[{text:"28 days",type:"concept_error"},{text:"29 days",type:"correct"},{text:"30 days",type:"calculation_error"},{text:"31 days",type:"misinterpretation"}], explanation:"Leap year February = 29 days.", solutionSteps:["Leap year = every 4 years.","Feb = 29 days that year."], shortcut:"Leap year Feb = 29 days.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },

  // math3_ch7_duration — 8 Qs
  { questionId:"math3_ch7_du_q1", topicId:"math3_ch7_duration", text:"A movie starts at 4 PM and ends at 6 PM. Duration?", options:[{text:"4 hours",type:"calculation_error"},{text:"2 hours",type:"correct"},{text:"10 hours",type:"calculation_error"},{text:"6 hours",type:"misinterpretation"}], explanation:"Duration = end − start = 6 − 4 = 2 hours.", solutionSteps:["End = 6 PM.","Start = 4 PM.","Duration = 6 − 4 = 2 hours."], shortcut:"Duration = end − start.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_du_q2", topicId:"math3_ch7_duration", text:"School: 8 AM to 2 PM. Duration?", options:[{text:"4 hours",type:"calculation_error"},{text:"6 hours",type:"correct"},{text:"8 hours",type:"calculation_error"},{text:"10 hours",type:"misinterpretation"}], explanation:"From 8 AM to 12 noon = 4 hours. 12 noon to 2 PM = 2 hours. Total = 6.", solutionSteps:["8 AM → 12 noon = 4 hours.","12 noon → 2 PM = 2 hours.","Total = 6 hours."], shortcut:"Cross noon: split, then add.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_du_q3", topicId:"math3_ch7_duration", text:"Class starts 9:00 and ends 9:45. Duration?", options:[{text:"45 minutes",type:"correct"},{text:"1 hour",type:"calculation_error"},{text:"30 min",type:"calculation_error"},{text:"15 min",type:"calculation_error"}], explanation:"9:45 − 9:00 = 45 minutes.", solutionSteps:["End − start in minutes: 45 − 0 = 45.","Duration = 45 min."], shortcut:"Same hour → subtract minutes.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_du_q4", topicId:"math3_ch7_duration", text:"Bus departs 11:30 AM, arrives 1:30 PM. Duration?", options:[{text:"1 hour",type:"calculation_error"},{text:"2 hours",type:"correct"},{text:"3 hours",type:"calculation_error"},{text:"30 min",type:"misinterpretation"}], explanation:"11:30 → 12:30 = 1 hour. 12:30 → 1:30 = 1 hour. Total = 2 hours.", solutionSteps:["11:30 AM → 12:30 PM = 1 hour.","12:30 PM → 1:30 PM = 1 hour.","Total = 2 hours."], shortcut:"Cross noon: split.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_du_q5", topicId:"math3_ch7_duration", text:"A nap from 1:15 PM to 2:00 PM. Duration?", options:[{text:"45 min",type:"correct"},{text:"30 min",type:"calculation_error"},{text:"1 hour",type:"calculation_error"},{text:"15 min",type:"calculation_error"}], explanation:"From 1:15 to 2:00 = 60 − 15 = 45 min.", solutionSteps:["Up to next hour: 60 − 15 = 45 min."], shortcut:"To full hour: 60 − start minutes.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_du_q6", topicId:"math3_ch7_duration", text:"A game starts 5 PM and lasts 90 min. End time?", options:[{text:"6:30 PM",type:"correct"},{text:"6 PM",type:"calculation_error"},{text:"7 PM",type:"calculation_error"},{text:"6:45 PM",type:"calculation_error"}], explanation:"90 min = 1 hour 30 min. 5 PM + 1:30 = 6:30 PM.", solutionSteps:["90 min = 1 h 30 min.","5 PM + 1:30 = 6:30 PM."], shortcut:"Add hours and minutes separately.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_du_q7", topicId:"math3_ch7_duration", text:"School ends at 2 PM and homework time starts at 4 PM. Gap?", options:[{text:"1 hour",type:"calculation_error"},{text:"2 hours",type:"correct"},{text:"3 hours",type:"calculation_error"},{text:"30 min",type:"misinterpretation"}], explanation:"4 PM − 2 PM = 2 hours.", solutionSteps:["Gap = 4 − 2 = 2 hours."], shortcut:"Subtract.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },
  { questionId:"math3_ch7_du_q8", topicId:"math3_ch7_duration", text:"Train leaves Mumbai at 6 AM and arrives Delhi at 10 PM same day. Travel time?", options:[{text:"12 hours",type:"calculation_error"},{text:"16 hours",type:"correct"},{text:"14 hours",type:"calculation_error"},{text:"20 hours",type:"misinterpretation"}], explanation:"6 AM to 12 noon = 6 hours. 12 noon to 10 PM = 10 hours. Total = 16.", solutionSteps:["6 AM → 12 noon = 6 hours.","12 noon → 10 PM = 10 hours.","Total = 16 hours."], shortcut:"Split at noon, add.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Time Goes On" },

  // math3_ch8_heavier_lighter — 8 Qs
  { questionId:"math3_ch8_hl_q1", topicId:"math3_ch8_heavier_lighter", text:"Heavier objects pull DOWN MORE on a…", options:[{text:"Watch",type:"concept_error"},{text:"Balance scale",type:"correct"},{text:"Calendar",type:"misinterpretation"},{text:"Ruler",type:"concept_error"}], explanation:"Heavier objects pull a balance scale DOWN more on their side.", solutionSteps:["Heavier = pulls down.","Balance scale shows difference."], shortcut:"Heavier side goes down.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_hl_q2", topicId:"math3_ch8_heavier_lighter", text:"Which is usually heavier: a brick or a paper?", options:[{text:"Paper",type:"concept_error"},{text:"Brick",type:"correct"},{text:"Both equal",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"A brick is much denser than paper.", solutionSteps:["Bricks are dense.","Heavier than paper of similar size."], shortcut:"Denser = heavier.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_hl_q3", topicId:"math3_ch8_heavier_lighter", text:"True or false: bigger size always means heavier.", options:[{text:"True",type:"concept_error"},{text:"False",type:"correct"},{text:"Sometimes true",type:"partial_logic"},{text:"Always equal",type:"misinterpretation"}], explanation:"A pillow is bigger but lighter than a brick. Size doesn't equal weight.", solutionSteps:["Big + light: pillow.","Small + heavy: brick.","Size ≠ weight always."], shortcut:"Size ≠ weight.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_hl_q4", topicId:"math3_ch8_heavier_lighter", text:"Lifting which is harder: a 1 kg bag or a 100 g bag?", options:[{text:"1 kg bag",type:"correct"},{text:"100 g bag",type:"concept_error"},{text:"Both equal",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"1 kg = 1000 g, ten times heavier than 100 g.", solutionSteps:["1 kg = 1000 g.","1000 > 100 → heavier."], shortcut:"More mass = harder lift.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_hl_q5", topicId:"math3_ch8_heavier_lighter", text:"On a balance, the LIGHTER side…", options:[{text:"Stays level",type:"concept_error"},{text:"Goes UP",type:"correct"},{text:"Goes DOWN",type:"misinterpretation"},{text:"Breaks",type:"guessing"}], explanation:"Lighter side goes up; heavier side goes down.", solutionSteps:["Heavier = down.","Lighter = up."], shortcut:"Lighter up, heavier down.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_hl_q6", topicId:"math3_ch8_heavier_lighter", text:"Compare: 1 kg of feathers and 1 kg of stones — which weighs more?", options:[{text:"Feathers",type:"concept_error"},{text:"Stones",type:"concept_error"},{text:"Both equal",type:"correct"},{text:"Cannot tell",type:"guessing"}], explanation:"1 kg = 1 kg, no matter the material. Equal weight.", solutionSteps:["Same number = same weight.","Material doesn't matter for weight."], shortcut:"1 kg = 1 kg, always.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_hl_q7", topicId:"math3_ch8_heavier_lighter", text:"Which is the lightest unit listed?", options:[{text:"1 g",type:"correct"},{text:"100 g",type:"concept_error"},{text:"1 kg",type:"misinterpretation"},{text:"1000 g",type:"misinterpretation"}], explanation:"1 g is the smallest weight here.", solutionSteps:["1 g < 100 g < 1 kg = 1000 g."], shortcut:"Compare numbers in same unit.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_hl_q8", topicId:"math3_ch8_heavier_lighter", text:"To compare weights of two items, you can…", options:[{text:"Look at colour",type:"concept_error"},{text:"Use a balance scale",type:"correct"},{text:"Use a ruler",type:"misinterpretation"},{text:"Smell them",type:"guessing"}], explanation:"A balance scale compares weights directly.", solutionSteps:["Balance compares weights.","Heavier side goes down."], shortcut:"Balance = weight comparison tool.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },

  // math3_ch8_grams_kilograms — 8 Qs
  { questionId:"math3_ch8_gk_q1", topicId:"math3_ch8_grams_kilograms", text:"1 kg = ? g", options:[{text:"10",type:"concept_error"},{text:"100",type:"calculation_error"},{text:"1000",type:"correct"},{text:"10000",type:"misinterpretation"}], explanation:"By definition: 1 kg = 1000 grams.", solutionSteps:["1 kg = 1000 g."], shortcut:"1 kg = 1000 g.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_gk_q2", topicId:"math3_ch8_grams_kilograms", text:"500 g + 500 g = ?", options:[{text:"1000 g (= 1 kg)",type:"correct"},{text:"100 g",type:"calculation_error"},{text:"5000 g",type:"misinterpretation"},{text:"10 g",type:"concept_error"}], explanation:"500 + 500 = 1000 g = 1 kg.", solutionSteps:["500 + 500 = 1000.","1000 g = 1 kg."], shortcut:"500 g + 500 g = 1 kg.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_gk_q3", topicId:"math3_ch8_grams_kilograms", text:"2 kg = ? g", options:[{text:"200",type:"calculation_error"},{text:"2000",type:"correct"},{text:"20000",type:"misinterpretation"},{text:"20",type:"concept_error"}], explanation:"2 × 1000 = 2000 g.", solutionSteps:["kg → g: × 1000.","2 × 1000 = 2000 g."], shortcut:"kg × 1000 = g.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_gk_q4", topicId:"math3_ch8_grams_kilograms", text:"3000 g = ? kg", options:[{text:"3 kg",type:"correct"},{text:"30 kg",type:"calculation_error"},{text:"0.3 kg",type:"calculation_error"},{text:"300 kg",type:"misinterpretation"}], explanation:"3000 ÷ 1000 = 3 kg.", solutionSteps:["g → kg: ÷ 1000.","3000 ÷ 1000 = 3 kg."], shortcut:"g ÷ 1000 = kg.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_gk_q5", topicId:"math3_ch8_grams_kilograms", text:"Best unit for weighing a sack of rice?", options:[{text:"g",type:"concept_error"},{text:"kg",type:"correct"},{text:"mm",type:"misinterpretation"},{text:"ml",type:"misinterpretation"}], explanation:"Heavy items like a sack are measured in kg.", solutionSteps:["Heavy = kg.","Sack of rice ≈ 5–25 kg."], shortcut:"Heavy items = kg.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_gk_q6", topicId:"math3_ch8_grams_kilograms", text:"Best unit for weighing one paperclip?", options:[{text:"g",type:"correct"},{text:"kg",type:"concept_error"},{text:"m",type:"misinterpretation"},{text:"ml",type:"misinterpretation"}], explanation:"Tiny items are weighed in grams.", solutionSteps:["Light = g.","Paperclip ≈ 1 g."], shortcut:"Tiny things = g.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_gk_q7", topicId:"math3_ch8_grams_kilograms", text:"Half a kilogram (½ kg) = ? g", options:[{text:"50 g",type:"calculation_error"},{text:"100 g",type:"calculation_error"},{text:"500 g",type:"correct"},{text:"5000 g",type:"misinterpretation"}], explanation:"½ × 1000 = 500 g.", solutionSteps:["½ × 1000 = 500.","½ kg = 500 g."], shortcut:"½ kg = 500 g.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_gk_q8", topicId:"math3_ch8_grams_kilograms", text:"1 kg 200 g = ? g", options:[{text:"1020 g",type:"calculation_error"},{text:"1200 g",type:"correct"},{text:"120 g",type:"calculation_error"},{text:"12000 g",type:"misinterpretation"}], explanation:"1 kg = 1000 g + 200 g = 1200 g.", solutionSteps:["1 kg = 1000 g.","1000 + 200 = 1200 g."], shortcut:"Combine: kg part × 1000 + g part.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },

  // math3_ch8_balance_scale — 8 Qs
  { questionId:"math3_ch8_bs_q1", topicId:"math3_ch8_balance_scale", text:"A fruit balances with three 100 g weights. Its weight is…", options:[{text:"100 g",type:"concept_error"},{text:"200 g",type:"calculation_error"},{text:"300 g",type:"correct"},{text:"400 g",type:"calculation_error"}], explanation:"3 × 100 = 300 g.", solutionSteps:["3 weights × 100 g = 300 g."], shortcut:"Add up weights.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_bs_q2", topicId:"math3_ch8_balance_scale", text:"On a balance, two oranges balance with one apple. So:", options:[{text:"Apple is lighter than 2 oranges",type:"concept_error"},{text:"Apple equals 2 oranges in weight",type:"correct"},{text:"Oranges are heavier than apple",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"Balanced = equal weights. 1 apple = 2 oranges.", solutionSteps:["Balanced = equal weights.","1 apple = 2 oranges."], shortcut:"Balanced = equal.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_bs_q3", topicId:"math3_ch8_balance_scale", text:"To weigh 250 g on a balance, you need standard weights of:", options:[{text:"100 g + 100 g + 50 g",type:"correct"},{text:"100 g + 100 g + 100 g",type:"calculation_error"},{text:"50 g + 50 g",type:"calculation_error"},{text:"500 g",type:"misinterpretation"}], explanation:"Sum to 250 g: 100 + 100 + 50.", solutionSteps:["100 + 100 = 200.","+50 = 250."], shortcut:"Add standard weights to match.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_bs_q4", topicId:"math3_ch8_balance_scale", text:"What does a level (horizontal) balance scale mean?", options:[{text:"Right side heavier",type:"concept_error"},{text:"Equal weights on both sides",type:"correct"},{text:"Empty scale",type:"misinterpretation"},{text:"Broken",type:"guessing"}], explanation:"Level = equal weights on both sides.", solutionSteps:["Both sides equal → level.","Unequal → tilts."], shortcut:"Level = balanced = equal.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_bs_q5", topicId:"math3_ch8_balance_scale", text:"A book balances with two 250 g weights. Book weight?", options:[{text:"250 g",type:"concept_error"},{text:"500 g",type:"correct"},{text:"125 g",type:"calculation_error"},{text:"1 kg",type:"calculation_error"}], explanation:"2 × 250 g = 500 g.", solutionSteps:["2 × 250 = 500 g."], shortcut:"Add the weights.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_bs_q6", topicId:"math3_ch8_balance_scale", text:"On a balance: left has 500 g; right has 200 g + 200 g + 50 g. Which way does it tilt?", options:[{text:"Left",type:"correct"},{text:"Right",type:"concept_error"},{text:"Level",type:"calculation_error"},{text:"Cannot tell",type:"guessing"}], explanation:"Right total = 200 + 200 + 50 = 450 g. Left (500) > Right (450), so it tilts LEFT.", solutionSteps:["Right = 200 + 200 + 50 = 450 g.","Left = 500 g.","500 > 450 → tilts left."], shortcut:"Sum each side, then compare.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_bs_q7", topicId:"math3_ch8_balance_scale", text:"If a banana = 100 g and an apple = 200 g, how many bananas balance with 3 apples?", options:[{text:"3",type:"calculation_error"},{text:"6",type:"correct"},{text:"2",type:"calculation_error"},{text:"5",type:"misinterpretation"}], explanation:"3 apples = 600 g. 600 ÷ 100 = 6 bananas.", solutionSteps:["3 apples = 3 × 200 = 600 g.","600 ÷ 100 = 6 bananas."], shortcut:"Total weight ÷ banana weight.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_bs_q8", topicId:"math3_ch8_balance_scale", text:"On a balance, if I add a weight to the heavier side, will it become more balanced?", options:[{text:"Yes",type:"concept_error"},{text:"No, it becomes even more unbalanced",type:"correct"},{text:"Equally balanced",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"Adding to the heavier side makes the imbalance bigger.", solutionSteps:["More weight on heavier side → more tilt.","To balance: add to LIGHTER side."], shortcut:"Add to lighter side to balance.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },

  // math3_ch8_weight_word — 8 Qs
  { questionId:"math3_ch8_ww_q1", topicId:"math3_ch8_weight_word", text:"A bag of rice weighs 5 kg. A bag of dal weighs 2 kg. Total weight?", options:[{text:"3 kg",type:"misinterpretation"},{text:"7 kg",type:"correct"},{text:"10 kg",type:"calculation_error"},{text:"6 kg",type:"calculation_error"}], explanation:"5 + 2 = 7 kg.", solutionSteps:["Total = rice + dal.","= 5 + 2 = 7 kg."], shortcut:"'Total' = add.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_ww_q2", topicId:"math3_ch8_weight_word", text:"500 g of sugar + 750 g of flour = ?", options:[{text:"1250 g",type:"correct"},{text:"1150 g",type:"calculation_error"},{text:"1300 g",type:"calculation_error"},{text:"250 g",type:"misinterpretation"}], explanation:"500 + 750 = 1250 g (= 1 kg 250 g).", solutionSteps:["500 + 750 = 1250 g.","= 1 kg 250 g."], shortcut:"Add grams directly.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_ww_q3", topicId:"math3_ch8_weight_word", text:"A box weighs 3 kg. After removing 1 kg of items, weight is…", options:[{text:"2 kg",type:"correct"},{text:"3 kg",type:"misinterpretation"},{text:"4 kg",type:"misinterpretation"},{text:"1 kg",type:"calculation_error"}], explanation:"3 − 1 = 2 kg.", solutionSteps:["Original − removed = 3 − 1 = 2 kg."], shortcut:"Remove = subtract.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_ww_q4", topicId:"math3_ch8_weight_word", text:"Convert 1500 g to kg and g.", options:[{text:"1 kg 5 g",type:"calculation_error"},{text:"1 kg 500 g",type:"correct"},{text:"15 kg",type:"misinterpretation"},{text:"0.15 kg",type:"calculation_error"}], explanation:"1500 g = 1000 g + 500 g = 1 kg 500 g.", solutionSteps:["1500 ÷ 1000 = 1 kg with 500 g remainder.","→ 1 kg 500 g."], shortcut:"Quotient = kg; remainder = g.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_ww_q5", topicId:"math3_ch8_weight_word", text:"Each book weighs 250 g. Weight of 4 books?", options:[{text:"500 g",type:"calculation_error"},{text:"1 kg",type:"correct"},{text:"1.5 kg",type:"calculation_error"},{text:"2 kg",type:"misinterpretation"}], explanation:"4 × 250 = 1000 g = 1 kg.", solutionSteps:["4 × 250 = 1000 g.","= 1 kg."], shortcut:"4 × 250 = 1000 → 1 kg.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_ww_q6", topicId:"math3_ch8_weight_word", text:"A baby weighs 4 kg at birth. After 6 months it weighs 7 kg. Weight gain?", options:[{text:"3 kg",type:"correct"},{text:"11 kg",type:"misinterpretation"},{text:"4 kg",type:"calculation_error"},{text:"7 kg",type:"misinterpretation"}], explanation:"7 − 4 = 3 kg.", solutionSteps:["Gain = now − before = 7 − 4 = 3 kg."], shortcut:"Gain = now − before.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_ww_q7", topicId:"math3_ch8_weight_word", text:"What if you add 500 g + 1 kg without converting? You'd get…", options:[{text:"1.5 g (wrong)",type:"correct"},{text:"1.5 kg (correct)",type:"misinterpretation"},{text:"500 g",type:"calculation_error"},{text:"1500 g",type:"misinterpretation"}], explanation:"Adding 500 + 1 without converting gives 501 — wrong! Always convert first: 500 g + 1000 g = 1500 g.", solutionSteps:["Wrong: 500 + 1 = 501.","Right: 500 g + 1000 g = 1500 g.","Convert before adding."], shortcut:"Same unit before adding.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
  { questionId:"math3_ch8_ww_q8", topicId:"math3_ch8_weight_word", text:"A truck carries 500 kg of rice. After delivering 200 kg, weight left?", options:[{text:"700 kg",type:"misinterpretation"},{text:"300 kg",type:"correct"},{text:"100 kg",type:"calculation_error"},{text:"250 kg",type:"calculation_error"}], explanation:"500 − 200 = 300 kg.", solutionSteps:["Left = total − delivered.","500 − 200 = 300 kg."], shortcut:"Delivered = subtract.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Who is Heavier?" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 3 Math v2 questions (Ch7-8).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
