import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math3_ch9_repeated_addition — 8 Qs
  { questionId:"math3_ch9_ra_q1", topicId:"math3_ch9_repeated_addition", text:"5 × 3 is the same as…", options:[{text:"5 + 3",type:"concept_error"},{text:"3 + 3 + 3 + 3 + 3 (= 15)",type:"correct"},{text:"5 + 5 + 5 + 5",type:"calculation_error"},{text:"15 × 1",type:"partial_logic"}], explanation:"5 × 3 means 5 groups of 3 = 3 + 3 + 3 + 3 + 3 = 15.", solutionSteps:["5 × 3 = 5 groups of 3.","= 3 + 3 + 3 + 3 + 3 = 15."], shortcut:"a × b = a groups of b.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ra_q2", topicId:"math3_ch9_repeated_addition", text:"4 + 4 + 4 = ? × ?", options:[{text:"3 × 4 = 12",type:"correct"},{text:"4 × 4 = 16",type:"calculation_error"},{text:"3 × 3 = 9",type:"calculation_error"},{text:"4 + 3 = 7",type:"misinterpretation"}], explanation:"3 fours = 3 × 4 = 12.", solutionSteps:["Count 4s: three times.","3 × 4 = 12."], shortcut:"Count groups, then multiply.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ra_q3", topicId:"math3_ch9_repeated_addition", text:"What is 6 × 2?", options:[{text:"8",type:"concept_error"},{text:"10",type:"calculation_error"},{text:"12",type:"correct"},{text:"4",type:"misinterpretation"}], explanation:"2 + 2 + 2 + 2 + 2 + 2 = 12.", solutionSteps:["6 twos.","6 × 2 = 12."], shortcut:"6 × 2 = 12.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ra_q4", topicId:"math3_ch9_repeated_addition", text:"Multiplication is a shortcut for…", options:[{text:"Subtraction",type:"concept_error"},{text:"Repeated addition",type:"correct"},{text:"Division",type:"misinterpretation"},{text:"Counting backwards",type:"guessing"}], explanation:"Multiplication = repeated addition of the same number.", solutionSteps:["× = add same number repeatedly.","Faster than writing every addition."], shortcut:"× = repeated +.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ra_q5", topicId:"math3_ch9_repeated_addition", text:"Each box has 5 candies. 4 boxes = ? candies.", options:[{text:"9",type:"misinterpretation"},{text:"20",type:"correct"},{text:"25",type:"calculation_error"},{text:"15",type:"calculation_error"}], explanation:"4 × 5 = 20.", solutionSteps:["4 boxes × 5 = 20 candies."], shortcut:"Groups × items = total.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ra_q6", topicId:"math3_ch9_repeated_addition", text:"3 + 3 + 3 + 3 + 3 = ?", options:[{text:"12",type:"calculation_error"},{text:"15",type:"correct"},{text:"18",type:"calculation_error"},{text:"5 × 3",type:"partial_logic"}], explanation:"5 threes = 5 × 3 = 15.", solutionSteps:["Count 3s: 5.","5 × 3 = 15."], shortcut:"Count groups × value.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ra_q7", topicId:"math3_ch9_repeated_addition", text:"What is 7 × 0?", options:[{text:"7",type:"concept_error"},{text:"0",type:"correct"},{text:"1",type:"calculation_error"},{text:"70",type:"misinterpretation"}], explanation:"Any number × 0 = 0.", solutionSteps:["× 0 = 0, always.","7 × 0 = 0."], shortcut:"Zero rule: × 0 = 0.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ra_q8", topicId:"math3_ch9_repeated_addition", text:"What is 8 × 1?", options:[{text:"8",type:"correct"},{text:"1",type:"concept_error"},{text:"0",type:"calculation_error"},{text:"9",type:"misinterpretation"}], explanation:"Any number × 1 = the same number.", solutionSteps:["× 1 = self.","8 × 1 = 8."], shortcut:"Identity: × 1 = same.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },

  // math3_ch9_times_tables — 8 Qs
  { questionId:"math3_ch9_tt_q1", topicId:"math3_ch9_times_tables", text:"What is 5 × 7?", options:[{text:"30",type:"calculation_error"},{text:"35",type:"correct"},{text:"40",type:"calculation_error"},{text:"12",type:"misinterpretation"}], explanation:"5 × 7 = 35 (table of 5).", solutionSteps:["Table of 5: 5, 10, 15, 20, 25, 30, 35.","Seventh = 35."], shortcut:"Table of 5 ends in 0 or 5.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_tt_q2", topicId:"math3_ch9_times_tables", text:"In the table of 2, all numbers are…", options:[{text:"Odd",type:"concept_error"},{text:"Even",type:"correct"},{text:"Prime",type:"misinterpretation"},{text:"Negative",type:"guessing"}], explanation:"2, 4, 6, 8, 10, 12... all even.", solutionSteps:["Table of 2: all multiples of 2.","Multiples of 2 are even."], shortcut:"Table of 2 = even numbers.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_tt_q3", topicId:"math3_ch9_times_tables", text:"Table of 10 always ends in…", options:[{text:"5",type:"concept_error"},{text:"0",type:"correct"},{text:"1",type:"misinterpretation"},{text:"Any digit",type:"guessing"}], explanation:"Multiples of 10 always end in 0: 10, 20, 30, 40, ...", solutionSteps:["10, 20, 30, 40, ...","All end in 0."], shortcut:"× 10: append 0.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_tt_q4", topicId:"math3_ch9_times_tables", text:"What is 9 × 4?", options:[{text:"32",type:"calculation_error"},{text:"36",type:"correct"},{text:"40",type:"calculation_error"},{text:"45",type:"calculation_error"}], explanation:"Table of 9: 9, 18, 27, 36. 4th = 36.", solutionSteps:["Table of 9: 9, 18, 27, 36.","Fourth = 36."], shortcut:"9's table digits add to 9 (3+6=9).", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_tt_q5", topicId:"math3_ch9_times_tables", text:"What is 6 × 8?", options:[{text:"48",type:"correct"},{text:"42",type:"calculation_error"},{text:"56",type:"calculation_error"},{text:"54",type:"calculation_error"}], explanation:"6 × 8 = 48.", solutionSteps:["6 × 8 = 48.","(Or 8 × 6 = 48.)"], shortcut:"Order doesn't matter: 6 × 8 = 8 × 6.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_tt_q6", topicId:"math3_ch9_times_tables", text:"What is 3 × 9?", options:[{text:"21",type:"calculation_error"},{text:"27",type:"correct"},{text:"30",type:"calculation_error"},{text:"24",type:"calculation_error"}], explanation:"3 × 9 = 27.", solutionSteps:["3 × 9 = 27.","Or 9 × 3 = 27."], shortcut:"Digits add to 9: 2+7=9 ✓", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_tt_q7", topicId:"math3_ch9_times_tables", text:"What is 7 × 7?", options:[{text:"49",type:"correct"},{text:"42",type:"calculation_error"},{text:"56",type:"calculation_error"},{text:"14",type:"misinterpretation"}], explanation:"7 × 7 = 49 (square of 7).", solutionSteps:["7 × 7 = 49."], shortcut:"Square of 7 = 49.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_tt_q8", topicId:"math3_ch9_times_tables", text:"What is 10 × 10?", options:[{text:"20",type:"concept_error"},{text:"100",type:"correct"},{text:"1000",type:"misinterpretation"},{text:"10",type:"calculation_error"}], explanation:"10 × 10 = 100.", solutionSteps:["10 × 10 = 100."], shortcut:"× 10 then × 10 again = × 100.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },

  // math3_ch9_multiplication_word — 8 Qs
  { questionId:"math3_ch9_mw_q1", topicId:"math3_ch9_multiplication_word", text:"Each box has 6 chocolates. There are 4 boxes. How many chocolates in all?", options:[{text:"10",type:"misinterpretation"},{text:"24",type:"correct"},{text:"30",type:"calculation_error"},{text:"20",type:"calculation_error"}], explanation:"4 × 6 = 24.", solutionSteps:["Boxes × chocolates per box = 4 × 6 = 24."], shortcut:"'Each ... each' = multiply.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_mw_q2", topicId:"math3_ch9_multiplication_word", text:"Which keyword usually means MULTIPLY?", options:[{text:"Difference",type:"concept_error"},{text:"Each, every, per",type:"correct"},{text:"Sum",type:"misinterpretation"},{text:"Left",type:"guessing"}], explanation:"Each, every, and per are typical multiplication keywords.", solutionSteps:["Each / every / per = ×.","Look for 'per group' phrasing."], shortcut:"Each = ×.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_mw_q3", topicId:"math3_ch9_multiplication_word", text:"7 students each have 5 pencils. Total pencils?", options:[{text:"12",type:"misinterpretation"},{text:"35",type:"correct"},{text:"30",type:"calculation_error"},{text:"40",type:"calculation_error"}], explanation:"7 × 5 = 35.", solutionSteps:["7 × 5 = 35."], shortcut:"Students × per student.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_mw_q4", topicId:"math3_ch9_multiplication_word", text:"A bicycle has 2 wheels. How many wheels do 9 bicycles have?", options:[{text:"11",type:"misinterpretation"},{text:"18",type:"correct"},{text:"20",type:"calculation_error"},{text:"16",type:"calculation_error"}], explanation:"9 × 2 = 18.", solutionSteps:["9 bicycles × 2 wheels = 18."], shortcut:"Multiply per-item count by number of items.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_mw_q5", topicId:"math3_ch9_multiplication_word", text:"A spider has 8 legs. How many legs do 6 spiders have?", options:[{text:"40",type:"calculation_error"},{text:"48",type:"correct"},{text:"56",type:"calculation_error"},{text:"14",type:"misinterpretation"}], explanation:"6 × 8 = 48.", solutionSteps:["6 spiders × 8 legs = 48."], shortcut:"× = repeated addition.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_mw_q6", topicId:"math3_ch9_multiplication_word", text:"Each row has 4 chairs. There are 5 rows. Total chairs?", options:[{text:"9",type:"misinterpretation"},{text:"20",type:"correct"},{text:"15",type:"calculation_error"},{text:"25",type:"calculation_error"}], explanation:"5 × 4 = 20.", solutionSteps:["5 rows × 4 chairs each = 20."], shortcut:"Rows × per row.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_mw_q7", topicId:"math3_ch9_multiplication_word", text:"Cost of one pencil is ₹5. Cost of 7 pencils?", options:[{text:"₹12",type:"misinterpretation"},{text:"₹35",type:"correct"},{text:"₹40",type:"calculation_error"},{text:"₹30",type:"calculation_error"}], explanation:"7 × ₹5 = ₹35.", solutionSteps:["Per pencil cost × number = 5 × 7 = 35."], shortcut:"Per-unit × total units.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_mw_q8", topicId:"math3_ch9_multiplication_word", text:"A week has 7 days. How many days in 4 weeks?", options:[{text:"11",type:"misinterpretation"},{text:"28",type:"correct"},{text:"30",type:"calculation_error"},{text:"24",type:"calculation_error"}], explanation:"4 × 7 = 28 days.", solutionSteps:["4 weeks × 7 days = 28 days."], shortcut:"4 × 7 = 28.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },

  // math3_ch9_arrays — 8 Qs
  { questionId:"math3_ch9_ar_q1", topicId:"math3_ch9_arrays", text:"In an array with 3 rows and 4 columns, how many objects in total?", options:[{text:"7",type:"misinterpretation"},{text:"12",type:"correct"},{text:"34",type:"misinterpretation"},{text:"14",type:"calculation_error"}], explanation:"3 × 4 = 12.", solutionSteps:["Rows × Columns = 3 × 4 = 12."], shortcut:"Array total = rows × columns.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ar_q2", topicId:"math3_ch9_arrays", text:"4 × 5 in array means…", options:[{text:"4 rows + 5 columns",type:"concept_error"},{text:"4 rows × 5 columns = 20",type:"correct"},{text:"4 × 5 = 9",type:"misinterpretation"},{text:"Just 4 or 5",type:"guessing"}], explanation:"4 rows × 5 columns gives a 4×5 array of 20 objects.", solutionSteps:["4 rows × 5 columns = 20 objects."], shortcut:"Array dimensions = multiply.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ar_q3", topicId:"math3_ch9_arrays", text:"Does 3 × 4 = 4 × 3?", options:[{text:"No",type:"concept_error"},{text:"Yes, both = 12",type:"correct"},{text:"Only sometimes",type:"misinterpretation"},{text:"Depends",type:"guessing"}], explanation:"Multiplication is commutative — order doesn't matter.", solutionSteps:["3 × 4 = 12.","4 × 3 = 12.","Same answer."], shortcut:"a × b = b × a.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ar_q4", topicId:"math3_ch9_arrays", text:"A garden has 6 rows of plants with 5 plants in each row. Total plants?", options:[{text:"11",type:"misinterpretation"},{text:"30",type:"correct"},{text:"35",type:"calculation_error"},{text:"25",type:"calculation_error"}], explanation:"6 × 5 = 30.", solutionSteps:["6 rows × 5 plants = 30."], shortcut:"Array problem = multiply.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ar_q5", topicId:"math3_ch9_arrays", text:"A school stage has 8 chairs in 1 row. There are 5 such rows. Total chairs?", options:[{text:"40",type:"correct"},{text:"45",type:"calculation_error"},{text:"35",type:"calculation_error"},{text:"30",type:"calculation_error"}], explanation:"5 rows × 8 chairs = 40.", solutionSteps:["5 × 8 = 40 chairs."], shortcut:"5 × 8 = 40.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ar_q6", topicId:"math3_ch9_arrays", text:"An array has 36 items in 6 rows. Items per row?", options:[{text:"4",type:"calculation_error"},{text:"6",type:"correct"},{text:"30",type:"misinterpretation"},{text:"42",type:"misinterpretation"}], explanation:"36 ÷ 6 = 6 items per row.", solutionSteps:["Total ÷ rows = per row.","36 ÷ 6 = 6."], shortcut:"Inverse: ÷ to find missing dimension.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ar_q7", topicId:"math3_ch9_arrays", text:"Arrange 24 marbles in equal rows. Which is NOT possible?", options:[{text:"4 rows of 6",type:"concept_error"},{text:"5 rows of 5",type:"correct"},{text:"6 rows of 4",type:"concept_error"},{text:"8 rows of 3",type:"concept_error"}], explanation:"5 × 5 = 25, not 24. 24 doesn't divide evenly into 5.", solutionSteps:["Check each: 4×6=24 ✓","5×5=25 ✗","6×4=24 ✓","8×3=24 ✓","→ 5 rows of 5 doesn't work."], shortcut:"Check rows × columns = total.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },
  { questionId:"math3_ch9_ar_q8", topicId:"math3_ch9_arrays", text:"Why is array shape useful for multiplication?", options:[{text:"It hides numbers",type:"concept_error"},{text:"It shows multiplication visually",type:"correct"},{text:"It makes math harder",type:"misinterpretation"},{text:"Only for triangles",type:"guessing"}], explanation:"Arrays make the rows × columns structure visible.", solutionSteps:["Array shows multiplication clearly.","Rows and columns visible."], shortcut:"Array = visual multiplication.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"How Many Times?" },

  // math3_ch10_number_patterns — 8 Qs
  { questionId:"math3_ch10_np_q1", topicId:"math3_ch10_number_patterns", text:"What is the next number: 2, 4, 6, 8, ?", options:[{text:"9",type:"concept_error"},{text:"10",type:"correct"},{text:"11",type:"calculation_error"},{text:"12",type:"calculation_error"}], explanation:"Pattern: +2 each time. 8 + 2 = 10.", solutionSteps:["Differences: +2 each step.","Next: 8 + 2 = 10."], shortcut:"Find the +rule, then apply.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_np_q2", topicId:"math3_ch10_number_patterns", text:"Next number: 5, 10, 15, 20, ?", options:[{text:"21",type:"concept_error"},{text:"25",type:"correct"},{text:"30",type:"calculation_error"},{text:"35",type:"calculation_error"}], explanation:"Pattern: +5 each time. 20 + 5 = 25.", solutionSteps:["Rule: +5 each step.","Next: 20 + 5 = 25."], shortcut:"Multiples of 5 increase by 5.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_np_q3", topicId:"math3_ch10_number_patterns", text:"Next: 100, 90, 80, 70, ?", options:[{text:"75",type:"calculation_error"},{text:"60",type:"correct"},{text:"80",type:"misinterpretation"},{text:"50",type:"calculation_error"}], explanation:"Pattern: −10 each step. 70 − 10 = 60.", solutionSteps:["Rule: −10 each step.","Next: 70 − 10 = 60."], shortcut:"Decreasing patterns use subtraction.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_np_q4", topicId:"math3_ch10_number_patterns", text:"To find a number pattern, look at the ___ between numbers.", options:[{text:"Length",type:"concept_error"},{text:"Difference",type:"correct"},{text:"Colour",type:"misinterpretation"},{text:"Sum",type:"partial_logic"}], explanation:"The difference between consecutive terms reveals the rule.", solutionSteps:["Differences tell the rule.","Constant difference = arithmetic pattern."], shortcut:"Difference = rule.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_np_q5", topicId:"math3_ch10_number_patterns", text:"Next: 3, 6, 9, 12, ?", options:[{text:"14",type:"calculation_error"},{text:"15",type:"correct"},{text:"18",type:"calculation_error"},{text:"21",type:"calculation_error"}], explanation:"Pattern: +3 each step. 12 + 3 = 15.", solutionSteps:["Rule: +3 each step.","Next: 12 + 3 = 15."], shortcut:"Multiples of 3.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_np_q6", topicId:"math3_ch10_number_patterns", text:"Missing number: 1, 4, 7, ?, 13", options:[{text:"9",type:"calculation_error"},{text:"10",type:"correct"},{text:"11",type:"calculation_error"},{text:"12",type:"misinterpretation"}], explanation:"Pattern: +3 each step. 7 + 3 = 10. Check: 10 + 3 = 13 ✓.", solutionSteps:["Differences: 4−1=3, 7−4=3.","Rule: +3.","Missing: 7+3=10.","Verify: 10+3=13 ✓."], shortcut:"Find rule, fill missing.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_np_q7", topicId:"math3_ch10_number_patterns", text:"Pattern: 2, 4, 8, 16. Rule?", options:[{text:"Add 2",type:"concept_error"},{text:"Multiply by 2",type:"correct"},{text:"Subtract 2",type:"misinterpretation"},{text:"Divide by 2",type:"calculation_error"}], explanation:"Each number is double the previous. ×2 rule.", solutionSteps:["4 = 2 × 2.","8 = 4 × 2.","16 = 8 × 2.","Rule: × 2."], shortcut:"Doubling pattern.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_np_q8", topicId:"math3_ch10_number_patterns", text:"Next: 100, 200, 300, 400, ?", options:[{text:"450",type:"calculation_error"},{text:"500",type:"correct"},{text:"600",type:"misinterpretation"},{text:"401",type:"calculation_error"}], explanation:"Pattern: +100 each time. 400 + 100 = 500.", solutionSteps:["Rule: +100.","Next: 500."], shortcut:"+100 increments.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },

  // math3_ch10_shape_patterns — 8 Qs
  { questionId:"math3_ch10_sp_q1", topicId:"math3_ch10_shape_patterns", text:"What comes next: □ △ □ △ □ ?", options:[{text:"□",type:"concept_error"},{text:"△",type:"correct"},{text:"○",type:"guessing"},{text:"☆",type:"misinterpretation"}], explanation:"Repeating unit is □ △. So after □ comes △.", solutionSteps:["Repeating unit: □ △.","After □ → △."], shortcut:"Find repeating block, continue.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_sp_q2", topicId:"math3_ch10_shape_patterns", text:"What's the next shape: ⭐ ⭐ ◯ ⭐ ⭐ ◯ ?", options:[{text:"◯",type:"concept_error"},{text:"⭐",type:"correct"},{text:"△",type:"guessing"},{text:"□",type:"misinterpretation"}], explanation:"Repeating unit: ⭐ ⭐ ◯. Next is ⭐.", solutionSteps:["Block: ⭐⭐◯.","After ◯, restart with ⭐."], shortcut:"Identify the full repeating block.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_sp_q3", topicId:"math3_ch10_shape_patterns", text:"A pattern has shapes that repeat. The repeating part is called the…", options:[{text:"Tail",type:"concept_error"},{text:"Unit / block",type:"correct"},{text:"Total",type:"misinterpretation"},{text:"Sum",type:"guessing"}], explanation:"The repeating part is called the unit (or block).", solutionSteps:["Pattern repeats a fixed block.","That block = the unit."], shortcut:"Repeating block = unit.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_sp_q4", topicId:"math3_ch10_shape_patterns", text:"Pattern: A B A B A B. The unit is…", options:[{text:"A",type:"concept_error"},{text:"AB",type:"correct"},{text:"ABA",type:"misinterpretation"},{text:"AABB",type:"calculation_error"}], explanation:"Repeating unit = AB.", solutionSteps:["AB AB AB → repeating unit AB."], shortcut:"Find smallest repeat.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_sp_q5", topicId:"math3_ch10_shape_patterns", text:"What's the 7th shape in ⬛ ⬜ ⬛ ⬜ ⬛ ⬜ ___?", options:[{text:"⬛",type:"correct"},{text:"⬜",type:"concept_error"},{text:"△",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"Pattern: ⬛⬜ repeated. Position 7 (odd) = ⬛.", solutionSteps:["Unit: ⬛⬜.","Odd positions = ⬛.","Position 7 odd → ⬛."], shortcut:"Odd position → first of unit.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_sp_q6", topicId:"math3_ch10_shape_patterns", text:"How long is the repeating unit in: ☀️ 🌙 ⭐ ☀️ 🌙 ⭐?", options:[{text:"2",type:"calculation_error"},{text:"3",type:"correct"},{text:"6",type:"misinterpretation"},{text:"1",type:"concept_error"}], explanation:"Unit ☀️ 🌙 ⭐ has length 3.", solutionSteps:["☀️ 🌙 ⭐ = 3 shapes.","Whole pattern = 2 units of 3."], shortcut:"Smallest block = unit length.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_sp_q7", topicId:"math3_ch10_shape_patterns", text:"Continue the pattern: ◯ □ △ ◯ □ △ ___", options:[{text:"□",type:"concept_error"},{text:"◯",type:"correct"},{text:"△",type:"misinterpretation"},{text:"⭐",type:"guessing"}], explanation:"Unit: ◯□△. After △ → ◯.", solutionSteps:["Unit length: 3 (◯□△).","Position 7 = position 1 of next unit = ◯."], shortcut:"Restart unit after each complete block.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_sp_q8", topicId:"math3_ch10_shape_patterns", text:"In pattern ⬛⬛⬜⬛⬛⬜, how many ⬛ per unit?", options:[{text:"1",type:"concept_error"},{text:"2",type:"correct"},{text:"3",type:"misinterpretation"},{text:"6",type:"calculation_error"}], explanation:"Unit ⬛⬛⬜ has 2 black squares.", solutionSteps:["Unit: ⬛⬛⬜.","Count ⬛: 2."], shortcut:"Count per unit, not total.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },

  // math3_ch10_growing_patterns — 8 Qs
  { questionId:"math3_ch10_gp_q1", topicId:"math3_ch10_growing_patterns", text:"In a growing pattern, the change…", options:[{text:"Stays the same",type:"concept_error"},{text:"Increases or decreases steadily",type:"correct"},{text:"Is random",type:"misinterpretation"},{text:"Doesn't exist",type:"guessing"}], explanation:"Growing patterns add (or subtract) a changing amount each step.", solutionSteps:["Growing = changing increments.","Constant rule = arithmetic, not growing."], shortcut:"Changing differences = growing.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_gp_q2", topicId:"math3_ch10_growing_patterns", text:"Next: 1, 3, 6, 10, ?", options:[{text:"13",type:"calculation_error"},{text:"15",type:"correct"},{text:"14",type:"calculation_error"},{text:"20",type:"misinterpretation"}], explanation:"Differences: +2, +3, +4, +5 → 10 + 5 = 15.", solutionSteps:["Differences: 2, 3, 4 (increasing by 1).","Next difference: 5.","10 + 5 = 15."], shortcut:"Triangular numbers!", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_gp_q3", topicId:"math3_ch10_growing_patterns", text:"Next: 1, 2, 4, 7, 11, ?", options:[{text:"14",type:"calculation_error"},{text:"16",type:"correct"},{text:"15",type:"calculation_error"},{text:"22",type:"misinterpretation"}], explanation:"Differences: +1, +2, +3, +4, → next +5 → 11 + 5 = 16.", solutionSteps:["Differences: 1, 2, 3, 4 (each +1).","Next: 5.","11 + 5 = 16."], shortcut:"Sum of differences grows.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_gp_q4", topicId:"math3_ch10_growing_patterns", text:"Is 5, 10, 15, 20 a growing pattern?", options:[{text:"Yes, growing",type:"concept_error"},{text:"No — it's a constant +5 pattern (arithmetic)",type:"correct"},{text:"Yes, but slow",type:"misinterpretation"},{text:"It's random",type:"guessing"}], explanation:"5, 10, 15, 20 has constant +5 → arithmetic, NOT growing.", solutionSteps:["Differences: 5, 5, 5.","Constant difference = arithmetic.","Not growing."], shortcut:"Constant difference ≠ growing.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_gp_q5", topicId:"math3_ch10_growing_patterns", text:"Next: 2, 5, 9, 14, 20, ?", options:[{text:"24",type:"calculation_error"},{text:"27",type:"correct"},{text:"25",type:"calculation_error"},{text:"30",type:"misinterpretation"}], explanation:"Differences: +3, +4, +5, +6, next +7 → 20 + 7 = 27.", solutionSteps:["Differences: 3, 4, 5, 6.","Next +1: 7.","20 + 7 = 27."], shortcut:"Differences increase by 1.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_gp_q6", topicId:"math3_ch10_growing_patterns", text:"Pattern: 0, 1, 3, 6, 10, 15. What's adding each step?", options:[{text:"Same number each time",type:"concept_error"},{text:"1, 2, 3, 4, 5 (one more each time)",type:"correct"},{text:"All zeros",type:"misinterpretation"},{text:"Random numbers",type:"guessing"}], explanation:"Differences: 1, 2, 3, 4, 5 → each is one more than before.", solutionSteps:["1−0=1.","3−1=2.","6−3=3.","10−6=4.","15−10=5.","→ Adding 1, 2, 3, 4, 5..."], shortcut:"Triangular numbers grow by +1 each step.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_gp_q7", topicId:"math3_ch10_growing_patterns", text:"To check if it's growing, look at…", options:[{text:"Colour of numbers",type:"concept_error"},{text:"How the difference between terms changes",type:"correct"},{text:"Total",type:"misinterpretation"},{text:"Just the first number",type:"guessing"}], explanation:"Compute differences. If they grow, it's a growing pattern.", solutionSteps:["Differences constant → arithmetic.","Differences increase → growing."], shortcut:"Check differences of differences.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_gp_q8", topicId:"math3_ch10_growing_patterns", text:"Is 100, 98, 95, 91 a growing pattern?", options:[{text:"Yes, growing down",type:"correct"},{text:"No, just shrinking same",type:"concept_error"},{text:"Same all the way",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"Differences: −2, −3, −4. Difference changes → it IS a growing (or decaying) pattern.", solutionSteps:["100−98=−2.","98−95=−3.","95−91=−4.","Differences increase in magnitude → growing pattern (declining)."], shortcut:"Growing can decrease too.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },

  // math3_ch10_pattern_rules — 8 Qs
  { questionId:"math3_ch10_pr_q1", topicId:"math3_ch10_pattern_rules", text:"Rule for 2, 4, 8, 16, 32?", options:[{text:"Add 2 each time",type:"concept_error"},{text:"Multiply by 2 each time",type:"correct"},{text:"Subtract 2",type:"misinterpretation"},{text:"Add a different number each time",type:"partial_logic"}], explanation:"Each = previous × 2.", solutionSteps:["2 × 2 = 4.","4 × 2 = 8.","8 × 2 = 16.","Rule: × 2."], shortcut:"Doubling pattern = × 2.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_pr_q2", topicId:"math3_ch10_pattern_rules", text:"Rule for 100, 90, 80, 70, 60?", options:[{text:"Add 10",type:"concept_error"},{text:"Subtract 10",type:"correct"},{text:"Multiply by 10",type:"misinterpretation"},{text:"Divide by 10",type:"calculation_error"}], explanation:"Each step is 10 less than the previous.", solutionSteps:["100−90=10.","90−80=10.","Rule: −10."], shortcut:"Constant subtraction = arithmetic rule.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_pr_q3", topicId:"math3_ch10_pattern_rules", text:"Find rule: 1, 5, 25, 125, 625", options:[{text:"Add 4",type:"calculation_error"},{text:"Multiply by 5",type:"correct"},{text:"Add 50",type:"misinterpretation"},{text:"Subtract",type:"concept_error"}], explanation:"Each = previous × 5.", solutionSteps:["1 × 5 = 5.","5 × 5 = 25.","Rule: × 5."], shortcut:"Multiply each by the same number.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_pr_q4", topicId:"math3_ch10_pattern_rules", text:"Rule for 1, 4, 9, 16, 25?", options:[{text:"Add 3 each time",type:"concept_error"},{text:"Square numbers (1², 2², 3², 4², 5²)",type:"correct"},{text:"Random",type:"misinterpretation"},{text:"Subtract 3",type:"guessing"}], explanation:"These are squares: 1×1, 2×2, 3×3, 4×4, 5×5.", solutionSteps:["1 = 1².","4 = 2².","9 = 3².","16 = 4².","25 = 5²."], shortcut:"Square numbers.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_pr_q5", topicId:"math3_ch10_pattern_rules", text:"Apply the rule '×2' starting at 3 for 4 steps: 3, ?, ?, ?, ?", options:[{text:"6, 12, 24, 48",type:"correct"},{text:"6, 9, 12, 15",type:"calculation_error"},{text:"5, 7, 9, 11",type:"concept_error"},{text:"4, 5, 6, 7",type:"misinterpretation"}], explanation:"Start 3 → 3×2=6 → 6×2=12 → 12×2=24 → 24×2=48.", solutionSteps:["3 × 2 = 6.","6 × 2 = 12.","12 × 2 = 24.","24 × 2 = 48."], shortcut:"Apply rule iteratively.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_pr_q6", topicId:"math3_ch10_pattern_rules", text:"Apply rule '+7' starting at 1: 1, ?, ?, ?, ?", options:[{text:"8, 15, 22, 29",type:"correct"},{text:"7, 14, 21, 28",type:"calculation_error"},{text:"8, 16, 24, 32",type:"calculation_error"},{text:"2, 3, 4, 5",type:"concept_error"}], explanation:"1+7=8, 8+7=15, 15+7=22, 22+7=29.", solutionSteps:["1+7=8.","8+7=15.","15+7=22.","22+7=29."], shortcut:"Add 7 each step.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_pr_q7", topicId:"math3_ch10_pattern_rules", text:"What rule turns 3 into 9, 4 into 16, 5 into 25?", options:[{text:"Add 6",type:"concept_error"},{text:"Multiply by itself (square)",type:"correct"},{text:"Add 12",type:"misinterpretation"},{text:"Subtract 3",type:"guessing"}], explanation:"3²=9, 4²=16, 5²=25.", solutionSteps:["3 × 3 = 9.","4 × 4 = 16.","5 × 5 = 25.","→ Square."], shortcut:"Squares: n × n.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
  { questionId:"math3_ch10_pr_q8", topicId:"math3_ch10_pattern_rules", text:"For 12, 9, 6, 3 — what's the rule?", options:[{text:"+3",type:"concept_error"},{text:"−3",type:"correct"},{text:"×3",type:"misinterpretation"},{text:"÷3",type:"calculation_error"}], explanation:"Each next number is 3 less than the previous.", solutionSteps:["12−9=3.","9−6=3.","Rule: subtract 3."], shortcut:"Constant decrease = subtract rule.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Play with Patterns" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 3 Math v2 questions (Ch9-10).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
