/**
 * Seed: CBSE Class 10 English — First Flight Prose Questions (72 MCQs)
 * Topics: eng_ff_ch1_prose … eng_ff_ch9_prose  (8 questions each)
 * Safe to re-run — skips duplicates on { questionText, subject }
 * Usage: node config/seedEnglishQuestionsA.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const Q = [
  // ── eng_ff_ch1_prose — A Letter to God ──────────────────────────────────
  {
    topic: "eng_ff_ch1_prose", topicId: "eng_ff_ch1_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'A Letter to God', what crops did Lencho cultivate on his field?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Corn and wheat", type: "correct", logicTag: "" },
      { text: "Rice and sugarcane", type: "concept_error", logicTag: "wrong_crop" },
      { text: "Cotton and barley", type: "concept_error", logicTag: "wrong_crop" },
      { text: "Millet and jowar", type: "guessing", logicTag: "surface_guess" },
    ],
    solutionSteps: ["Lencho grew corn and wheat on his field.", "He was waiting for rain to ensure a good harvest."],
    shortcut: "Lencho grew corn + wheat. Hailstorm destroyed crop. He wrote letter to God for 100 pesos.",
  },
  {
    topic: "eng_ff_ch1_prose", topicId: "eng_ff_ch1_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Lencho compare the raindrops to 'new coins'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Because rain meant a good harvest and therefore money", type: "correct", logicTag: "" },
      { text: "Because raindrops were silver-coloured like coins", type: "partial_logic", logicTag: "literal_appearance" },
      { text: "Because rain was rare and valuable like gold coins", type: "concept_error", logicTag: "region_error" },
      { text: "Because he needed coins to buy seeds", type: "concept_error", logicTag: "invented_detail" },
    ],
    solutionSteps: ["To Lencho, rain = good harvest = income/money.", "The simile 'new coins' reflects his farmer's perspective where rain is wealth."],
    shortcut: "Rain = harvest = money. Lencho sees rain as coins (figurative, not literal colour).",
  },
  {
    topic: "eng_ff_ch1_prose", topicId: "eng_ff_ch1_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Lencho's act of writing a letter to God reveal about his character?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Unshakeable faith and deep religious belief", type: "correct", logicTag: "" },
      { text: "Foolishness and lack of education", type: "concept_error", logicTag: "negative_judgement" },
      { text: "Laziness and dependence on others", type: "concept_error", logicTag: "misreading_theme" },
      { text: "Greed for money", type: "concept_error", logicTag: "misreading_motive" },
    ],
    solutionSteps: ["Lencho's faith is so strong he believes God will respond.", "The letter shows innocence and unquestioning belief rather than folly."],
    shortcut: "Central theme = faith. Lencho's letter = symbol of innocent, unshakeable faith in God.",
  },
  {
    topic: "eng_ff_ch1_prose", topicId: "eng_ff_ch1_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How much money did Lencho ask God for, and how much did he actually receive?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He asked for 100 pesos; received 70 pesos", type: "correct", logicTag: "" },
      { text: "He asked for 70 pesos; received 50 pesos", type: "concept_error", logicTag: "wrong_amount" },
      { text: "He asked for 100 pesos; received 100 pesos", type: "concept_error", logicTag: "wrong_amount" },
      { text: "He asked for 200 pesos; received 100 pesos", type: "concept_error", logicTag: "wrong_amount" },
    ],
    solutionSteps: ["Lencho asked for 100 pesos in his letter.", "Post office employees collected 70 pesos and sent it.", "Lencho received 70 pesos."],
    shortcut: "Asked: 100 pesos. Got: 70 pesos. Missing 30 = called post employees 'crooks'.",
  },
  {
    topic: "eng_ff_ch1_prose", topicId: "eng_ff_ch1_prose",
    subtopic: "Irony", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the irony in Lencho calling the post office workers 'a bunch of crooks'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The very people who helped him out of sympathy were called thieves by him", type: "correct", logicTag: "" },
      { text: "He did not know that God had sent the money", type: "concept_error", logicTag: "misses_irony" },
      { text: "The post office never helped him at all", type: "concept_error", logicTag: "factual_error" },
      { text: "He wrote a second letter asking for more money", type: "partial_logic", logicTag: "consequence_not_irony" },
    ],
    solutionSteps: ["Post office employees felt sympathy and donated money from their own pockets.", "Lencho, thinking God sent 100 pesos, blamed them for 'stealing' 30 pesos.", "The helpers were accused of theft — this is the central irony."],
    shortcut: "Irony = helpers called thieves. They gave money out of kindness, he accused them of stealing the shortfall.",
  },
  {
    topic: "eng_ff_ch1_prose", topicId: "eng_ff_ch1_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did the postmaster decide to answer Lencho's letter?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "To protect Lencho's faith in God from being shaken", type: "correct", logicTag: "" },
      { text: "It was part of his official duty", type: "concept_error", logicTag: "misreads_motivation" },
      { text: "He wanted to test Lencho's intelligence", type: "concept_error", logicTag: "invented_motive" },
      { text: "He was ordered by the government to help farmers", type: "concept_error", logicTag: "invented_detail" },
    ],
    solutionSteps: ["The postmaster was struck by Lencho's firm faith in God.", "He did not want that faith to be broken.", "He decided to collect money from colleagues to answer the letter as 'God'."],
    shortcut: "Postmaster = good soul. Didn't want Lencho's faith shaken. Collected money from staff.",
  },
  {
    topic: "eng_ff_ch1_prose", topicId: "eng_ff_ch1_prose",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What literary device is used when Lencho says the raindrops were like 'silver coins' and 'golden coins'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Simile", type: "correct", logicTag: "" },
      { text: "Metaphor", type: "concept_error", logicTag: "no_like_as" },
      { text: "Personification", type: "concept_error", logicTag: "wrong_device" },
      { text: "Alliteration", type: "concept_error", logicTag: "wrong_device" },
    ],
    solutionSteps: ["Lencho compares raindrops to coins using 'like' (implied comparison).", "A simile is a comparison using like/as.", "Silver drops = small raindrops; golden drops = larger drops near the corn ears."],
    shortcut: "Raindrops 'like coins' → simile. Metaphor would be 'are coins' (no like/as).",
  },
  {
    topic: "eng_ff_ch1_prose", topicId: "eng_ff_ch1_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the story 'A Letter to God' suggest about the nature of faith?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "True faith is innocent, unwavering, and sees miracles where others see coincidence", type: "correct", logicTag: "" },
      { text: "Faith is blind and leads to foolish actions", type: "concept_error", logicTag: "negative_reading" },
      { text: "Faith is only useful when supported by practical action", type: "concept_error", logicTag: "misreads_theme" },
      { text: "Faith in God is a cultural superstition limited to rural people", type: "concept_error", logicTag: "reductive_reading" },
    ],
    solutionSteps: ["Lencho's faith never wavers even after the disaster.", "He writes to God with complete conviction.", "The story presents faith positively — even if practically naive, it sustains the human spirit."],
    shortcut: "Theme: pure/innocent faith. Story doesn't mock Lencho — it celebrates his conviction.",
  },

  // ── eng_ff_ch2_prose — Nelson Mandela: Long Walk to Freedom ─────────────
  {
    topic: "eng_ff_ch2_prose", topicId: "eng_ff_ch2_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Where was Nelson Mandela inaugurated as President of South Africa?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "The Union Buildings in Pretoria", type: "correct", logicTag: "" },
      { text: "The Parliament in Cape Town", type: "concept_error", logicTag: "wrong_venue" },
      { text: "Robben Island prison", type: "concept_error", logicTag: "wrong_venue" },
      { text: "Johannesburg Stadium", type: "concept_error", logicTag: "wrong_venue" },
    ],
    solutionSteps: ["The inauguration ceremony took place at the Union Buildings amphitheatre in Pretoria.", "It was attended by dignitaries from 140 countries."],
    shortcut: "Inaugurated at Union Buildings, Pretoria. Not Cape Town parliament.",
  },
  {
    topic: "eng_ff_ch2_prose", topicId: "eng_ff_ch2_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "According to Mandela, what twin obligations does every man have?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Obligations to his family and obligations to his people and country", type: "correct", logicTag: "" },
      { text: "Obligations to his employer and to the government", type: "concept_error", logicTag: "wrong_obligations" },
      { text: "Obligations to God and to his nation", type: "concept_error", logicTag: "partial_error" },
      { text: "Obligations to himself and to the law", type: "concept_error", logicTag: "wrong_obligations" },
    ],
    solutionSteps: ["Mandela says every man has twin obligations: to his family (parents, wife, children) and to his people, community, and country."],
    shortcut: "Twin obligations = family + people/country. Under apartheid, fulfilling the second was impossible for Black South Africans.",
  },
  {
    topic: "eng_ff_ch2_prose", topicId: "eng_ff_ch2_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How many years did Mandela spend in prison?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "27 years", type: "correct", logicTag: "" },
      { text: "18 years", type: "concept_error", logicTag: "wrong_years" },
      { text: "35 years", type: "concept_error", logicTag: "wrong_years" },
      { text: "10 years", type: "concept_error", logicTag: "wrong_years" },
    ],
    solutionSteps: ["Nelson Mandela was imprisoned for 27 years, mostly on Robben Island.", "He was released in 1990."],
    shortcut: "Mandela: 27 years in prison. Released 1990. Became President 1994.",
  },
  {
    topic: "eng_ff_ch2_prose", topicId: "eng_ff_ch2_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Mandela say courage is?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Not the absence of fear, but the triumph over it", type: "correct", logicTag: "" },
      { text: "The complete absence of any fear", type: "concept_error", logicTag: "wrong_definition" },
      { text: "The ability to defeat one's enemies", type: "concept_error", logicTag: "misreads_concept" },
      { text: "The willingness to die for one's country", type: "concept_error", logicTag: "incomplete" },
    ],
    solutionSteps: ["Mandela redefines courage: brave men feel fear but conquer it.", "His own bravery came from conquering fear, not lacking it."],
    shortcut: "Courage ≠ no fear. Courage = triumph over fear. Mandela felt fear but overcame it.",
  },
  {
    topic: "eng_ff_ch2_prose", topicId: "eng_ff_ch2_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What, according to Mandela, is the greatest wealth and the greatest poverty?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Greatest wealth = freedom; greatest poverty = loss of hope", type: "concept_error", logicTag: "close_but_wrong" },
      { text: "Greatest wealth = love for freedom; greatest poverty = fear and prejudice", type: "correct", logicTag: "" },
      { text: "Greatest wealth = money; greatest poverty = unemployment", type: "concept_error", logicTag: "literal_misread" },
      { text: "Greatest wealth = education; greatest poverty = illiteracy", type: "concept_error", logicTag: "wrong_values" },
    ],
    solutionSteps: ["Mandela: love for freedom is the most precious wealth.", "Fear and prejudice (products of apartheid) are the greatest poverty.", "This reflects his moral/philosophical view beyond material wealth."],
    shortcut: "Wealth = love of freedom. Poverty = fear + prejudice. Both are spiritual/moral, not material.",
  },
  {
    topic: "eng_ff_ch2_prose", topicId: "eng_ff_ch2_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Who were some of the dignitaries present at Mandela's inauguration?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Dignitaries and heads of state from more than 140 countries", type: "correct", logicTag: "" },
      { text: "Only African leaders", type: "concept_error", logicTag: "wrong_scope" },
      { text: "United Nations representatives only", type: "concept_error", logicTag: "wrong_scope" },
      { text: "Leaders from Commonwealth countries only", type: "concept_error", logicTag: "wrong_scope" },
    ],
    solutionSteps: ["The inauguration was attended by dignitaries from 140 countries.", "It was a moment of global significance."],
    shortcut: "140+ countries' heads of state attended. South Africa's first democratic inauguration was a world event.",
  },
  {
    topic: "eng_ff_ch2_prose", topicId: "eng_ff_ch2_prose",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Mandela mean by 'hunger for freedom' in the context of his autobiography?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "An intense, deep longing for freedom that could not be suppressed", type: "correct", logicTag: "" },
      { text: "Starvation caused by the apartheid government's food restrictions", type: "concept_error", logicTag: "literal_misread" },
      { text: "His desire to become the head of state", type: "concept_error", logicTag: "misreads_intent" },
      { text: "The legal fight for voting rights", type: "concept_error", logicTag: "too_narrow" },
    ],
    solutionSteps: ["'Hunger' here is a metaphor for intense desire.", "Freedom was denied to Black South Africans — the longing for it was as strong as hunger for food."],
    shortcut: "'Hunger for freedom' = metaphor for intense, irresistible longing. Not literal hunger.",
  },
  {
    topic: "eng_ff_ch2_prose", topicId: "eng_ff_ch2_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What transformation does Mandela describe in the oppressor due to the apartheid system?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "The oppressor loses his sense of humanity and becomes a prisoner of hatred", type: "correct", logicTag: "" },
      { text: "The oppressor becomes richer and more powerful", type: "concept_error", logicTag: "misreads_mandela" },
      { text: "The oppressor eventually becomes the oppressed", type: "concept_error", logicTag: "partial_logic" },
      { text: "The oppressor develops guilt and reforms voluntarily", type: "concept_error", logicTag: "wishful_reading" },
    ],
    solutionSteps: ["Mandela says oppressing someone dehumanises the oppressor too.", "The oppressor is locked in hatred and becomes a 'prisoner' of his own prejudice.", "Both the oppressed and oppressor need liberation."],
    shortcut: "Deep idea: oppressor also loses humanity. Both need to be liberated — oppressed from chains, oppressor from hatred.",
  },

  // ── eng_ff_ch3_prose — Two Stories about Flying ─────────────────────────
  {
    topic: "eng_ff_ch3_prose", topicId: "eng_ff_ch3_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'His First Flight', why did the young seagull refuse to fly?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He was afraid of the vast empty stretch of sea below him", type: "correct", logicTag: "" },
      { text: "His wings were injured and he could not fly", type: "concept_error", logicTag: "wrong_reason" },
      { text: "He was waiting for his parents' permission", type: "concept_error", logicTag: "wrong_reason" },
      { text: "He had not yet learned the technique of flying", type: "partial_logic", logicTag: "incomplete" },
    ],
    solutionSteps: ["The young seagull's wings and body were ready for flight.", "He was gripped by fear of the great expanse of sea and sky.", "His fear was purely psychological, not physical."],
    shortcut: "Seagull's problem = fear, not inability. He could fly — he was terrified of the open sea below.",
  },
  {
    topic: "eng_ff_ch3_prose", topicId: "eng_ff_ch3_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'His First Flight', how did the young seagull's mother make him fly?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She held a piece of fish near him but kept it just out of reach until he leaped forward", type: "correct", logicTag: "" },
      { text: "She pushed him off the ledge forcefully", type: "concept_error", logicTag: "wrong_method" },
      { text: "She ignored him until he flew on his own", type: "concept_error", logicTag: "wrong_method" },
      { text: "She called him with loud cries from across the sea", type: "concept_error", logicTag: "wrong_method" },
    ],
    solutionSteps: ["The mother used food as bait.", "She held a piece of fish near the young seagull, teasing him.", "When hunger overcame fear, he lunged at the fish and found himself flying."],
    shortcut: "Mother = hunger as motivation. Fish dangled near; hunger > fear; seagull leapt and flew instinctively.",
  },
  {
    topic: "eng_ff_ch3_prose", topicId: "eng_ff_ch3_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'His First Flight'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Overcoming fear and self-doubt to discover one's true potential", type: "correct", logicTag: "" },
      { text: "The importance of parental guidance at every step", type: "partial_logic", logicTag: "secondary_theme" },
      { text: "The instinct of survival in animals", type: "concept_error", logicTag: "too_literal" },
      { text: "The beauty of nature and the sea", type: "concept_error", logicTag: "setting_not_theme" },
    ],
    solutionSteps: ["The seagull's journey mirrors human experience of fear and self-doubt.", "He had all the ability but was paralysed by fear.", "Once he overcame fear, he soared naturally."],
    shortcut: "Theme = conquering fear. The seagull HAD the ability all along — fear was the only obstacle.",
  },
  {
    topic: "eng_ff_ch3_prose", topicId: "eng_ff_ch3_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Black Aeroplane', where was the pilot flying when he encountered the storm?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Over France, on his way from Paris to England", type: "correct", logicTag: "" },
      { text: "Over the English Channel, on his way to America", type: "concept_error", logicTag: "wrong_route" },
      { text: "Over Germany, on a night flight", type: "concept_error", logicTag: "wrong_route" },
      { text: "Over the Atlantic Ocean, mid-journey", type: "concept_error", logicTag: "wrong_route" },
    ],
    solutionSteps: ["The pilot was flying from Paris to England.", "He was over France when he saw the massive storm clouds."],
    shortcut: "Paris → England. Storm appeared over France. Pilot: 550 km from Paris, fuel for 40 mins.",
  },
  {
    topic: "eng_ff_ch3_prose", topicId: "eng_ff_ch3_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the mystery at the end of 'The Black Aeroplane'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The control room had no record of any other aircraft in the area, making the black aeroplane's existence inexplicable", type: "correct", logicTag: "" },
      { text: "The pilot's plane disappeared from radar", type: "concept_error", logicTag: "wrong_mystery" },
      { text: "The pilot discovered the black plane was his own reflection", type: "concept_error", logicTag: "invented_detail" },
      { text: "The storm turned out to be a test by the flight controllers", type: "concept_error", logicTag: "invented_detail" },
    ],
    solutionSteps: ["After landing safely, the pilot asked the woman in the control room about the other plane.", "She said no other planes were on the radar that night.", "The mysterious black aeroplane — with no lights — has no explanation."],
    shortcut: "Mystery: black plane doesn't exist in records. No other aircraft. Was it real, imagination, or supernatural?",
  },
  {
    topic: "eng_ff_ch3_prose", topicId: "eng_ff_ch3_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What did the pilot of the black aeroplane do when the narrator's instruments stopped working?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He guided the narrator's plane through the storm to safety by flying ahead", type: "correct", logicTag: "" },
      { text: "He radioed the control tower for help", type: "concept_error", logicTag: "no_radio_used" },
      { text: "He forced the narrator to turn back", type: "concept_error", logicTag: "wrong_action" },
      { text: "He disappeared, leaving the narrator alone", type: "concept_error", logicTag: "wrong_sequence" },
    ],
    solutionSteps: ["The mysterious black plane flew in front and led the narrator through the storm.", "All the narrator had to do was follow the black plane's lights.", "Once through the clouds, he saw the landing lights of an airport."],
    shortcut: "Black plane: no markings, no lights, yet guided narrator to safety. Then vanished.",
  },
  {
    topic: "eng_ff_ch3_prose", topicId: "eng_ff_ch3_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What connects the themes of 'His First Flight' and 'The Black Aeroplane'?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Both deal with fear, risk-taking, and unexpected help in achieving something new", type: "correct", logicTag: "" },
      { text: "Both are about the science and mechanics of flying", type: "concept_error", logicTag: "surface_reading" },
      { text: "Both end in failure and the protagonists return home", type: "concept_error", logicTag: "factual_error" },
      { text: "Both criticise the recklessness of humans in facing danger", type: "concept_error", logicTag: "misreads_theme" },
    ],
    solutionSteps: ["Story 1: seagull overcomes fear of flying, aided by mother's strategy.", "Story 2: pilot overcomes crisis, aided by the mysterious black aeroplane.", "Both = fear overcome with help; both = first successful 'flight' of sorts."],
    shortcut: "Link: both involve overcoming fear + mysterious/unexpected help. Both celebrate courage.",
  },
  {
    topic: "eng_ff_ch3_prose", topicId: "eng_ff_ch3_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "The narrator in 'The Black Aeroplane' disobeyed the rules and flew into the storm. What does this tell us about his character?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "He was reckless but driven by a strong longing to reach home", type: "correct", logicTag: "" },
      { text: "He was an experienced pilot who knew the risk was manageable", type: "concept_error", logicTag: "wrong_inference" },
      { text: "He was irresponsible and didn't care about safety", type: "concept_error", logicTag: "oversimplified" },
      { text: "He was ordered by the control tower to fly through the storm", type: "concept_error", logicTag: "factual_error" },
    ],
    solutionSteps: ["The narrator was thinking about a good English breakfast with his family.", "His desire to be home made him take an impulsive risk.", "This shows he is emotional and nostalgic, not purely reckless."],
    shortcut: "Narrator's motivation = longing for family/home (breakfast, wife). Emotion > caution. Human but impulsive.",
  },

  // ── eng_ff_ch4_prose — From the Diary of Anne Frank ────────────────────
  {
    topic: "eng_ff_ch4_prose", topicId: "eng_ff_ch4_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Anne Frank begin to keep a diary?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She had no true friends to confide in and wanted a deep friendship with paper", type: "correct", logicTag: "" },
      { text: "Her teacher assigned a diary-writing exercise", type: "concept_error", logicTag: "wrong_reason" },
      { text: "She wanted to document the horrors of World War II", type: "partial_logic", logicTag: "later_purpose_not_start" },
      { text: "She was bored and confined to the house", type: "concept_error", logicTag: "wrong_reason" },
    ],
    solutionSteps: ["Anne felt she had acquaintances but not a true friend.", "She wanted to write down her deepest feelings to 'paper as a friend'.", "She named the diary 'Kitty'."],
    shortcut: "Anne's reason: no true friend to confide in. Diary = friend named 'Kitty'. Not a school exercise.",
  },
  {
    topic: "eng_ff_ch4_prose", topicId: "eng_ff_ch4_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What was Mr Keesing's complaint about Anne Frank in class?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He said she talked too much in class", type: "correct", logicTag: "" },
      { text: "He said she was rude and disrespectful", type: "concept_error", logicTag: "wrong_complaint" },
      { text: "He said she never submitted her homework", type: "concept_error", logicTag: "wrong_complaint" },
      { text: "He said she was inattentive during lessons", type: "concept_error", logicTag: "wrong_complaint" },
    ],
    solutionSteps: ["Mr Keesing was Anne's Maths teacher.", "He complained that Anne talked too much and gave her extra writing assignments as punishment."],
    shortcut: "Mr Keesing (Maths teacher) = Anne talked too much. Punishment: write essays. Anne turned it around cleverly.",
  },
  {
    topic: "eng_ff_ch4_prose", topicId: "eng_ff_ch4_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What was the essay Anne wrote as punishment for talking in class that made Mr Keesing laugh?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A poem defending her habit of talking, arguing it was inherited and could not be cured", type: "correct", logicTag: "" },
      { text: "An essay about why silence is golden in a classroom", type: "concept_error", logicTag: "wrong_content" },
      { text: "A funny story about a chatty parrot", type: "concept_error", logicTag: "close_but_wrong" },
      { text: "A letter to her parents about school rules", type: "concept_error", logicTag: "wrong_content" },
    ],
    solutionSteps: ["After two essay punishments, Anne wrote a poem in rhyme.", "It argued that talking was in her genes (inherited from her mother), so it was incurable.", "Keesing read the poem to the class and laughed — he stopped punishing her."],
    shortcut: "Third essay = poem. Argued: talking = inherited trait from mother = incurable. Keesing laughed, stopped assignments.",
  },
  {
    topic: "eng_ff_ch4_prose", topicId: "eng_ff_ch4_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Anne Frank's diary reveal about the psychology of a child during difficult times?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Children need an outlet for their emotions and a sense of being understood", type: "correct", logicTag: "" },
      { text: "Children are unaware of the dangers around them and live in fantasy", type: "concept_error", logicTag: "misreads_anne" },
      { text: "Children are resilient and do not need emotional support", type: "concept_error", logicTag: "wrong_conclusion" },
      { text: "Children cope best by staying silent and obedient", type: "concept_error", logicTag: "contradicts_theme" },
    ],
    solutionSteps: ["Anne felt no one truly understood her.", "The diary was her emotional outlet.", "Even in hiding from Nazis, her need for friendship and understanding was profound.", "This shows children's emotional needs are as serious as physical safety."],
    shortcut: "Anne's diary = emotional outlet. Key insight: emotional need for friendship/understanding even during war.",
  },
  {
    topic: "eng_ff_ch4_prose", topicId: "eng_ff_ch4_prose",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Anne Frank addresses her diary as 'Kitty'. What does this tell us?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "She personified the diary as a close friend to fulfil her deep need for intimacy", type: "correct", logicTag: "" },
      { text: "'Kitty' was a nickname for her pet cat", type: "concept_error", logicTag: "wrong_reference" },
      { text: "Kitty was the name of her best friend who had moved away", type: "concept_error", logicTag: "wrong_reference" },
      { text: "It was a code name to hide her diary from the Nazis", type: "concept_error", logicTag: "invented_reason" },
    ],
    solutionSteps: ["Naming the diary 'Kitty' is personification.", "Anne treated the diary as a living friend to confide in.", "It reflects her loneliness and need for a genuine confidant."],
    shortcut: "Kitty = personified diary-as-friend. Named to fill the void of real friendship. A sign of loneliness.",
  },
  {
    topic: "eng_ff_ch4_prose", topicId: "eng_ff_ch4_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What did Anne mean when she wrote that 'paper has more patience than people'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Paper will accept all her thoughts without judgement, unlike people who might dismiss or misunderstand her", type: "correct", logicTag: "" },
      { text: "She preferred writing to talking because she was shy", type: "concept_error", logicTag: "wrong_inference" },
      { text: "People around her were too busy to listen to her", type: "partial_logic", logicTag: "secondary_point" },
      { text: "She was afraid of people and trusted only inanimate objects", type: "concept_error", logicTag: "oversimplified" },
    ],
    solutionSteps: ["Anne felt no real person would truly listen without judging or trivialising her feelings.", "Paper (diary) would hold all her thoughts quietly, patiently.", "It's a reflection of her feeling of not being truly heard."],
    shortcut: "'Paper more patient than people' = no judgment from paper. People don't listen truly; diary does.",
  },
  {
    topic: "eng_ff_ch4_prose", topicId: "eng_ff_ch4_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Anne Frank say she did not want anyone to read the diary?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Because the diary contained her most intimate feelings and she valued privacy", type: "correct", logicTag: "" },
      { text: "Because the diary contained information about the resistance movement", type: "concept_error", logicTag: "later_diary_context" },
      { text: "Because she was ashamed of her grammar and spelling", type: "concept_error", logicTag: "invented_reason" },
      { text: "Because her family had forbidden her from discussing the war", type: "concept_error", logicTag: "invented_reason" },
    ],
    solutionSteps: ["Anne intended the diary to be personal — a true friend for herself.", "She wanted to be completely honest without fear of judgement.", "She said paper is patient and no one else would read it."],
    shortcut: "Diary = private emotional space. Anne wanted complete freedom to express without others judging.",
  },
  {
    topic: "eng_ff_ch4_prose", topicId: "eng_ff_ch4_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What do Anne Frank's diary entries reveal about her personality?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "She was intelligent, witty, emotionally sensitive, and had great self-awareness", type: "correct", logicTag: "" },
      { text: "She was obedient and did whatever her teachers said without question", type: "concept_error", logicTag: "contradicts_text" },
      { text: "She was rebellious and had no respect for authority", type: "concept_error", logicTag: "oversimplified" },
      { text: "She was cheerful and unaffected by the difficult circumstances around her", type: "concept_error", logicTag: "incorrect_reading" },
    ],
    solutionSteps: ["Anne challenged Mr Keesing with a clever poem — shows wit.", "She analysed her own need for friendship — shows self-awareness.", "She was deeply emotional but also resilient and creative."],
    shortcut: "Anne's personality: witty (poem to Keesing), self-aware (analysed loneliness), sensitive (felt deeply), intelligent.",
  },

  // ── eng_ff_ch5_prose — Glimpses of India ────────────────────────────────
  {
    topic: "eng_ff_ch5_prose", topicId: "eng_ff_ch5_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'A Baker from Goa', what is the traditional Goan name for a baker?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Pader", type: "correct", logicTag: "" },
      { text: "Padre", type: "concept_error", logicTag: "confused_with_padre" },
      { text: "Boulanger", type: "concept_error", logicTag: "french_word" },
      { text: "Naan maker", type: "concept_error", logicTag: "wrong_term" },
    ],
    solutionSteps: ["In Goa, the baker is traditionally called 'pader'.", "This Portuguese-influenced term reflects Goa's colonial heritage."],
    shortcut: "Baker in Goa = Pader. (Not padre, which means priest). Portuguese influence on Goan culture.",
  },
  {
    topic: "eng_ff_ch5_prose", topicId: "eng_ff_ch5_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Coorg', what is the legendary origin of the Kodavas (Coorgis)?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "They are believed to be descendants of Alexander's soldiers who settled and married locals", type: "correct", logicTag: "" },
      { text: "They are descendants of the ancient Dravidian tribes", type: "concept_error", logicTag: "wrong_legend" },
      { text: "They migrated from Persia in the 10th century", type: "concept_error", logicTag: "wrong_legend" },
      { text: "They are mentioned in the Ramayana as forest warriors", type: "concept_error", logicTag: "invented_legend" },
    ],
    solutionSteps: ["One legend says Coorgis are descendants of Greek/Arab soldiers who accompanied Alexander's army.", "They married local women and adopted local customs.", "This explains their distinct customs and dress."],
    shortcut: "Coorgi origin legend: possibly descendants of Alexander's soldiers. Their customs differ from mainstream India.",
  },
  {
    topic: "eng_ff_ch5_prose", topicId: "eng_ff_ch5_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Tea from Assam', what does Pranjol tell Rajvir about the origin of tea?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Tea was first drunk in China 2700 years ago when leaves fell into the emperor's boiling water", type: "correct", logicTag: "" },
      { text: "Tea was discovered in Assam by British planters in the 19th century", type: "concept_error", logicTag: "wrong_origin" },
      { text: "Tea originated in India and was spread to China by traders", type: "concept_error", logicTag: "reversed" },
      { text: "Tea was invented in Japan as a ceremonial drink", type: "concept_error", logicTag: "wrong_origin" },
    ],
    solutionSteps: ["Rajvir shares that the first tea was drunk in China 2700 BCE.", "Legend: Chinese emperor's servant accidentally dropped leaves into boiling water.", "The drink became popular and spread worldwide."],
    shortcut: "Tea origin: China ~2700 BCE. Leaves fell into emperor's water. Not India or Britain.",
  },
  {
    topic: "eng_ff_ch5_prose", topicId: "eng_ff_ch5_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'Glimpses of India'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "India's rich cultural diversity as seen through regional customs, food, and traditions", type: "correct", logicTag: "" },
      { text: "The economic development of rural India", type: "concept_error", logicTag: "misreads_theme" },
      { text: "The contrast between modern India and its colonial past", type: "partial_logic", logicTag: "secondary_element" },
      { text: "The importance of tourism in preserving culture", type: "concept_error", logicTag: "misreads_theme" },
    ],
    solutionSteps: ["Three writers showcase Goa (baker), Coorg (warriors/nature), and Assam (tea plantation).", "Together, they highlight India's incredible regional diversity in culture, cuisine, and traditions."],
    shortcut: "Glimpses theme = India's diversity. Goa (Portuguese blend), Coorg (warrior culture), Assam (tea/nature).",
  },
  {
    topic: "eng_ff_ch5_prose", topicId: "eng_ff_ch5_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'A Baker from Goa', what do the bread bangles (bol) symbolise in Goan culture?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "They are a symbol of celebration and auspiciousness during weddings and festivals", type: "correct", logicTag: "" },
      { text: "They are a daily staple eaten for breakfast every morning", type: "concept_error", logicTag: "oversimplified" },
      { text: "They represent Goa's Portuguese colonial heritage and are only made for tourists", type: "concept_error", logicTag: "wrong_context" },
      { text: "They are used as a currency substitute in rural Goa", type: "concept_error", logicTag: "invented_detail" },
    ],
    solutionSteps: ["The bol (bread bangle/sweet bread) is essential for festive occasions.", "No marriage, festival, or ceremony in Goa is complete without the baker and his bread."],
    shortcut: "Bol (bread bangles) = auspicious, used in weddings/festivals. Baker's role = culturally essential in Goa.",
  },
  {
    topic: "eng_ff_ch5_prose", topicId: "eng_ff_ch5_prose",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Tea from Assam', Rajvir is fascinated by the tea garden. What does his excitement suggest?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He is a curious, well-read person who connects what he has read with what he now sees", type: "correct", logicTag: "" },
      { text: "He had never seen a tree before and found the scenery unusual", type: "concept_error", logicTag: "exaggerated" },
      { text: "He wanted to become a tea planter like Pranjol's father", type: "concept_error", logicTag: "no_evidence" },
      { text: "He was trying to impress Pranjol with his general knowledge", type: "partial_logic", logicTag: "secondary_motive" },
    ],
    solutionSteps: ["Rajvir knows the legends of tea's origin and is excited to actually see a tea garden.", "He quotes lines of poetry about tea.", "This contrast with Pranjol (who grew up there and takes it for granted) highlights the freshness of a curious outsider."],
    shortcut: "Rajvir = outsider, curious and well-read. Pranjol = insider, bored. Fresh perspective vs. familiarity.",
  },
  {
    topic: "eng_ff_ch5_prose", topicId: "eng_ff_ch5_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What quality of the Kodavas (Coorgis) is highlighted by the author in 'Coorg'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Their fierce martial spirit and the pride in their military traditions", type: "correct", logicTag: "" },
      { text: "Their expertise in coffee and spice cultivation", type: "partial_logic", logicTag: "mentioned_not_highlighted" },
      { text: "Their adoption of modern democratic values", type: "concept_error", logicTag: "not_in_text" },
      { text: "Their skill in classical music and dance", type: "concept_error", logicTag: "not_in_text" },
    ],
    solutionSteps: ["Coorgis are known for their bravery and martial spirit.", "They keep personal weapons at home and have a tradition of military service.", "The Indian Army's Coorg Regiment is famous."],
    shortcut: "Coorg highlight = martial spirit/bravery. They carry arms as custom. Army regiment bears their name.",
  },
  {
    topic: "eng_ff_ch5_prose", topicId: "eng_ff_ch5_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How do the three stories in 'Glimpses of India' collectively celebrate Indian identity?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "They show that Indian identity is not monolithic but a rich mosaic of distinct regional cultures and traditions", type: "correct", logicTag: "" },
      { text: "They prove that all Indians share the same food and customs", type: "concept_error", logicTag: "contradicts_theme" },
      { text: "They criticise India's colonial heritage as something to be forgotten", type: "concept_error", logicTag: "misreads_tone" },
      { text: "They argue that rural India is better than urban India", type: "concept_error", logicTag: "misreads_theme" },
    ],
    solutionSteps: ["Goa = Portuguese-influenced, baking tradition, festive culture.", "Coorg = warrior heritage, dense nature, distinct customs.", "Assam = tea gardens, natural beauty, local legends.", "Together: India = diverse but unified."],
    shortcut: "Glimpses' power = showing India as mosaic. No single Indian identity — rich regional diversity = national strength.",
  },

  // ── eng_ff_ch6_prose — Mijbil the Otter ─────────────────────────────────
  {
    topic: "eng_ff_ch6_prose", topicId: "eng_ff_ch6_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Where did Gavin Maxwell get his pet otter Mijbil from?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "From the Tigris marshes in Southern Iraq while visiting a friend", type: "correct", logicTag: "" },
      { text: "From a pet shop in London", type: "concept_error", logicTag: "wrong_place" },
      { text: "From a wildlife sanctuary in Scotland", type: "concept_error", logicTag: "wrong_place" },
      { text: "From a river in India during his travels", type: "concept_error", logicTag: "wrong_place" },
    ],
    solutionSteps: ["Maxwell was visiting a friend in the Tigris marshes of Southern Iraq.", "Two Arabs brought him a small otter — Mijbil.", "The otter was a new species, later named Lutrogale perspicillata maxwelli."],
    shortcut: "Mijbil = from Tigris marshes, Iraq. New sub-species named after Maxwell. Not from London or India.",
  },
  {
    topic: "eng_ff_ch6_prose", topicId: "eng_ff_ch6_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What did Mijbil discover in the hotel bathroom and how did he spend his time there?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He discovered the water tap and learned to turn it on himself to play in the water", type: "correct", logicTag: "" },
      { text: "He found fish in the bathroom and spent time hunting them", type: "concept_error", logicTag: "invented_detail" },
      { text: "He chewed through the pipes and flooded the bathroom", type: "concept_error", logicTag: "wrong_detail" },
      { text: "He hid under the bath and refused to come out", type: "concept_error", logicTag: "wrong_detail" },
    ],
    solutionSteps: ["Mijbil loved water intensely.", "He discovered the tap and learned to turn it on himself.", "He spent hours playing in the water — rolling, splashing, diving."],
    shortcut: "Mijbil's bathroom discovery: learned to turn on the tap himself. Genius otter who loved water.",
  },
  {
    topic: "eng_ff_ch6_prose", topicId: "eng_ff_ch6_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What problem did Maxwell face while trying to fly Mijbil to England?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The airline rules required animals to travel in the hold, but he was allowed to carry Mijbil in the cabin after an hour delay", type: "correct", logicTag: "" },
      { text: "Mijbil was too heavy to be taken as hand luggage", type: "concept_error", logicTag: "wrong_problem" },
      { text: "The British government banned otters as pets", type: "concept_error", logicTag: "invented_obstacle" },
      { text: "Mijbil escaped at the airport and was never found", type: "concept_error", logicTag: "wrong_plot" },
    ],
    solutionSteps: ["The airline required animals in the hold unless the entire aircraft was chartered.", "Maxwell had to spend an agonising hour contacting airline offices.", "Eventually he was allowed to carry Mijbil in a box in the cabin."],
    shortcut: "Flight problem: airline rules = animals in hold. After 1 hour of calls, Maxwell got special cabin permission.",
  },
  {
    topic: "eng_ff_ch6_prose", topicId: "eng_ff_ch6_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Maxwell's relationship with Mijbil reveal about him?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He was deeply empathetic and formed a close emotional bond with animals", type: "correct", logicTag: "" },
      { text: "He was a scientist studying otter behaviour in a detached, academic manner", type: "concept_error", logicTag: "misreads_tone" },
      { text: "He was irresponsible and kept exotic pets illegally", type: "concept_error", logicTag: "wrong_characterisation" },
      { text: "He viewed animals as symbols of adventure and status", type: "concept_error", logicTag: "wrong_reading" },
    ],
    solutionSteps: ["Maxwell describes Mijbil's personality with warmth and detail.", "He suffers when Mijbil is put in a box; he is distressed by Mijbil's distress.", "His account is personal and emotional — not scientific or detached."],
    shortcut: "Maxwell = emotionally bonded with Mijbil. He writes with warmth, distress, love. Not scientific — personal.",
  },
  {
    topic: "eng_ff_ch6_prose", topicId: "eng_ff_ch6_prose",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Mijbil the Otter', how did Londoners typically respond to seeing Mijbil on the street?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "With curiosity — they tried to guess what animal he was, often guessing wrong (seal, mongoose, squirrel)", type: "correct", logicTag: "" },
      { text: "With fear — they ran away from the unusual creature", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "With indifference — Londoners were used to exotic animals", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "With hostility — they complained to the police about the animal", type: "concept_error", logicTag: "wrong_reaction" },
    ],
    solutionSteps: ["Londoners were fascinated and puzzled by Mijbil.", "They tried to identify the animal: 'Is it a seal? A squirrel? A mongoose?'", "Maxwell found this amusing and catalogued the reactions."],
    shortcut: "Londoners = curious, puzzled. Guessed: seal, squirrel, mongoose, beaver. Never got it right (= otter).",
  },
  {
    topic: "eng_ff_ch6_prose", topicId: "eng_ff_ch6_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What theme does 'Mijbil the Otter' primarily explore?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The deep, mutually affectionate bond that can develop between humans and wild animals", type: "correct", logicTag: "" },
      { text: "The dangers of keeping exotic animals as pets in urban environments", type: "concept_error", logicTag: "misreads_tone" },
      { text: "The importance of wildlife conservation and anti-poaching laws", type: "concept_error", logicTag: "not_in_text" },
      { text: "The cultural differences between the Middle East and England", type: "concept_error", logicTag: "background_not_theme" },
    ],
    solutionSteps: ["The entire narrative is about Maxwell's growing love for Mijbil.", "Mijbil develops trust and a unique personality with Maxwell.", "Central theme = human-animal bond, mutual affection, and the joy of animal companionship."],
    shortcut: "Theme = human-animal bond. Maxwell ↔ Mijbil: deep mutual affection despite being different species.",
  },
  {
    topic: "eng_ff_ch6_prose", topicId: "eng_ff_ch6_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What do Mijbil's intelligent behaviours (turning on taps, inventing games) suggest about animals?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Animals have complex minds, can learn, problem-solve, and have individual personalities", type: "correct", logicTag: "" },
      { text: "Wild animals can be fully domesticated and become identical to human companions", type: "concept_error", logicTag: "overstatement" },
      { text: "Otters are uniquely intelligent among all animals", type: "concept_error", logicTag: "too_specific" },
      { text: "Animals only behave intelligently when trained with rewards", type: "concept_error", logicTag: "wrong_model" },
    ],
    solutionSteps: ["Mijbil turned on taps without being taught.", "He invented a game with a marble, playing for hours alone.", "These unsolicited behaviours suggest genuine intelligence and personality."],
    shortcut: "Mijbil = intelligent individual. Tap trick = self-taught. Marble game = self-invented. Animals have rich inner lives.",
  },

  // ── eng_ff_ch7_prose — Madam Rides the Bus ──────────────────────────────
  {
    topic: "eng_ff_ch7_prose", topicId: "eng_ff_ch7_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Madam Rides the Bus', what was Valli's most desired dream?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "To ride the bus to the nearest town and back on her own", type: "correct", logicTag: "" },
      { text: "To become a bus driver when she grew up", type: "concept_error", logicTag: "wrong_dream" },
      { text: "To go to school in the town", type: "concept_error", logicTag: "wrong_dream" },
      { text: "To buy a treat from the town market", type: "concept_error", logicTag: "wrong_dream" },
    ],
    solutionSteps: ["Valli watched the bus pass her village every day.", "Her deepest wish was to ride the bus to the town and come back.", "She meticulously saved money for the fare."],
    shortcut: "Valli's dream = ride bus to town and back alone. She saved money secretly by denying herself treats.",
  },
  {
    topic: "eng_ff_ch7_prose", topicId: "eng_ff_ch7_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How much did Valli save for her bus ride and over what period?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "60 paise (30 paise each way) saved over many months by denying herself small pleasures", type: "correct", logicTag: "" },
      { text: "1 rupee saved over a week from her pocket money", type: "concept_error", logicTag: "wrong_amount" },
      { text: "2 rupees taken from her mother's purse", type: "concept_error", logicTag: "wrong_source" },
      { text: "50 paise borrowed from a friend", type: "concept_error", logicTag: "wrong_amount_and_source" },
    ],
    solutionSteps: ["Bus fare = 30 paise one way, 60 paise return.", "Valli saved by refusing to buy sweets, toys, and other treats over several months.", "She planned the trip carefully and secretly."],
    shortcut: "Fare: 30p one way = 60p return. Saved by resisting treats. Months of careful planning.",
  },
  {
    topic: "eng_ff_ch7_prose", topicId: "eng_ff_ch7_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Valli refuse to look at the dead cow on the return journey?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The sight reminded her that the same young cow she had admired earlier was now dead, making her aware of the reality of death", type: "correct", logicTag: "" },
      { text: "She was afraid of dead animals and always avoided them", type: "concept_error", logicTag: "misses_significance" },
      { text: "The cow was blocking the road and the sight was disgusting", type: "concept_error", logicTag: "misses_theme" },
      { text: "She was superstitious and believed seeing a dead cow was bad luck", type: "concept_error", logicTag: "invented_reason" },
    ],
    solutionSteps: ["On the way to town, Valli saw a young cow running playfully beside the bus — she found it funny.", "On the return, the same cow lay dead on the road.", "This sudden confrontation with death sobered her — her joy was replaced by sadness and a new awareness of mortality."],
    shortcut: "Same playful cow = now dead. Valli's innocent joy → awareness of death. Coming-of-age moment.",
  },
  {
    topic: "eng_ff_ch7_prose", topicId: "eng_ff_ch7_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'Madam Rides the Bus'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A child's transition from innocent joy to an awareness of life's transience and complexity", type: "correct", logicTag: "" },
      { text: "The importance of saving money for one's goals", type: "concept_error", logicTag: "secondary_element" },
      { text: "The contrast between village life and city life in India", type: "concept_error", logicTag: "misreads_theme" },
      { text: "A young girl's rebellion against her overprotective parents", type: "concept_error", logicTag: "oversimplified" },
    ],
    solutionSteps: ["Valli starts the journey with childlike excitement and joy.", "The dead cow ends her journey with sadness and a new awareness.", "This is a coming-of-age moment: awareness of mortality and the complexity of life."],
    shortcut: "Theme = innocence → awareness. Valli begins with joy, ends with sadness about death. Coming of age.",
  },
  {
    topic: "eng_ff_ch7_prose", topicId: "eng_ff_ch7_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How did the conductor and passengers treat Valli during her bus ride?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "They were amused and affectionate, calling her 'madam', though she bristled at any condescension", type: "correct", logicTag: "" },
      { text: "They ignored her completely as she was just a child", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "They were hostile and asked her to get off the bus", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "They were worried and called her parents immediately", type: "concept_error", logicTag: "wrong_reaction" },
    ],
    solutionSteps: ["The conductor called her 'madam' affectionately, which she initially objected to.", "An older woman offered her a seat; Valli refused as she wanted to stand.", "Passengers were amused but kind; Valli was confident and self-possessed."],
    shortcut: "Conductor called her 'madam' (amused). She refused free seat/cold drink — independent and proud. Not bullied.",
  },
  {
    topic: "eng_ff_ch7_prose", topicId: "eng_ff_ch7_prose",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Valli's refusal to accept a cold drink from the conductor suggest about her character?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "She has strong self-respect and independence — she will not accept charity", type: "correct", logicTag: "" },
      { text: "She was afraid the drink would make her sick", type: "concept_error", logicTag: "wrong_inference" },
      { text: "She disliked cold drinks", type: "concept_error", logicTag: "wrong_inference" },
      { text: "Her mother had told her not to accept things from strangers", type: "concept_error", logicTag: "possible_but_not_stated" },
    ],
    solutionSteps: ["Valli also refused an offered seat and standing space at the front.", "Her refusals reflect a proud, independent spirit.", "She wants to do things on her own terms, not as a recipient of adult charity."],
    shortcut: "Refusals (seat + drink) = Valli's independence and self-respect. She wants equality, not charity.",
  },
  {
    topic: "eng_ff_ch7_prose", topicId: "eng_ff_ch7_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why does Valli not tell her mother about her adventure at the end of the story?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "She wants to keep the experience — including its sad ending — as her own private memory; some experiences are too personal to share", type: "correct", logicTag: "" },
      { text: "She is afraid her mother will punish her for going without permission", type: "partial_logic", logicTag: "secondary_fear" },
      { text: "She has forgotten the adventure by the time she gets home", type: "concept_error", logicTag: "factually_wrong" },
      { text: "She wants to plan another secret trip and doesn't want to be caught", type: "concept_error", logicTag: "speculative" },
    ],
    solutionSteps: ["Valli smiles a mysterious smile but says nothing.", "Her experience — joy followed by sadness — has become deeply personal.", "The silence also marks a new maturity: she understands some things are hers alone.", "Fear of punishment is secondary; the deeper reason is the personal nature of growth."],
    shortcut: "Valli's silence = maturity. The experience (especially dead cow) was too personal/deep to explain. She has grown.",
  },

  // ── eng_ff_ch8_prose — The Sermon at Benares ─────────────────────────────
  {
    topic: "eng_ff_ch8_prose", topicId: "eng_ff_ch8_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What tragic event led Kisa Gotami to seek the Buddha?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "The death of her only son, which drove her to desperate grief", type: "correct", logicTag: "" },
      { text: "Her husband abandoned her and she sought solace", type: "concept_error", logicTag: "wrong_event" },
      { text: "She had a severe illness and wanted the Buddha to heal her", type: "concept_error", logicTag: "wrong_event" },
      { text: "Her village was destroyed by a flood and she lost everything", type: "concept_error", logicTag: "wrong_event" },
    ],
    solutionSteps: ["Kisa Gotami's only son died.", "In her grief, she carried the dead child and went to every house asking for medicine.", "Eventually she was directed to the Buddha for help."],
    shortcut: "Kisa Gotami: only son died. Carried dead body. Asked everyone for medicine. Directed to Buddha.",
  },
  {
    topic: "eng_ff_ch8_prose", topicId: "eng_ff_ch8_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What did the Buddha ask Kisa Gotami to bring him so that he could make medicine for her son?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A handful of mustard seeds from a house where no one had died", type: "correct", logicTag: "" },
      { text: "Water from the holy Ganges River collected at midnight", type: "concept_error", logicTag: "wrong_task" },
      { text: "Flowers from a garden that had never known sorrow", type: "concept_error", logicTag: "wrong_item" },
      { text: "A handful of rice from 100 different households", type: "concept_error", logicTag: "wrong_item" },
    ],
    solutionSteps: ["The Buddha asked for a handful of mustard seeds.", "The condition: the seeds must come from a house where no one — parent, child, servant — had died.", "Kisa Gotami visited house after house; every family had known death."],
    shortcut: "Task: mustard seeds from a house where NO ONE has died. Impossible to fulfil → teaches universal lesson.",
  },
  {
    topic: "eng_ff_ch8_prose", topicId: "eng_ff_ch8_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What did Kisa Gotami realise after visiting all the homes in the village?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Death is universal — she was not alone in her suffering; every household had experienced loss", type: "correct", logicTag: "" },
      { text: "Mustard seeds were very rare and hard to find", type: "concept_error", logicTag: "misses_lesson" },
      { text: "The Buddha's task was impossible and meant to punish her", type: "concept_error", logicTag: "wrong_reading" },
      { text: "Her son could not be revived because medicine didn't exist in ancient times", type: "concept_error", logicTag: "misses_theme" },
    ],
    solutionSteps: ["Every house she visited had known death — parents, children, relatives.", "She realised death is the universal human condition.", "This realisation helped her accept her son's death and move on."],
    shortcut: "Lesson: death is universal. Every house mourns. She is not alone → her grief, though real, is not unique.",
  },
  {
    topic: "eng_ff_ch8_prose", topicId: "eng_ff_ch8_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What was the Buddha's teaching about grief according to 'The Sermon at Benares'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Selfish desire and ignorance of death's universality cause suffering; accepting impermanence brings peace", type: "correct", logicTag: "" },
      { text: "Only prayer can remove grief; the remedy is ritual worship", type: "concept_error", logicTag: "wrong_teaching" },
      { text: "Grief is healthy and should be expressed through mourning for as long as needed", type: "concept_error", logicTag: "wrong_teaching" },
      { text: "Death is a punishment from God for past sins", type: "concept_error", logicTag: "wrong_doctrine" },
    ],
    solutionSteps: ["The Buddha's lesson: 'Of all the worldly passions, lust is the most intense; ignorance is the most baffling.'", "Grief comes from desire and attachment.", "Death is inevitable; weeping does not revive the dead. Peace comes from acceptance."],
    shortcut: "Buddha's teaching: grief = attachment + ignorance of impermanence. Accept death → peace. Not prayer, not ritual.",
  },
  {
    topic: "eng_ff_ch8_prose", topicId: "eng_ff_ch8_prose",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What literary device does the Buddha use in sending Kisa Gotami for mustard seeds?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Socratic method — he lets her discover the truth herself through experience", type: "correct", logicTag: "" },
      { text: "Flashback — he recalls a past event to explain death", type: "concept_error", logicTag: "wrong_device" },
      { text: "Allegory — the mustard seed represents the soul", type: "concept_error", logicTag: "wrong_device" },
      { text: "Simile — he compares death to falling leaves", type: "concept_error", logicTag: "wrong_device" },
    ],
    solutionSteps: ["The Buddha doesn't lecture Kisa Gotami directly.", "He gives her a task that she must accomplish herself.", "Through the impossible search, she arrives at the truth on her own — classic Socratic method."],
    shortcut: "Buddha = Socratic method. He doesn't tell her — he lets her discover. Task = path to self-realisation.",
  },
  {
    topic: "eng_ff_ch8_prose", topicId: "eng_ff_ch8_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the title 'The Sermon at Benares' suggest about the setting and tone?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Benares (Varanasi) is a holy city; the title signals a solemn, philosophical, spiritual teaching", type: "correct", logicTag: "" },
      { text: "The sermon was delivered by a politician in Benares", type: "concept_error", logicTag: "wrong_context" },
      { text: "The title is ironic, as no actual sermon is given in the story", type: "concept_error", logicTag: "factually_wrong" },
      { text: "Benares was the Buddha's birthplace, which is why the sermon is set there", type: "concept_error", logicTag: "wrong_fact" },
    ],
    solutionSteps: ["Benares (Varanasi) is one of the holiest cities in Hinduism and Buddhism.", "The Deer Park at Sarnath near Benares is where Buddha gave his first sermon.", "The title sets a spiritual, meditative, philosophical tone."],
    shortcut: "Benares = holy city. Buddha's first sermon was near Benares (Sarnath). Title = spiritual, solemn tone expected.",
  },
  {
    topic: "eng_ff_ch8_prose", topicId: "eng_ff_ch8_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How does the story of Kisa Gotami serve as a parable for modern readers?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "It teaches that clinging to loss intensifies suffering; shared mortality is the basis for compassion and acceptance", type: "correct", logicTag: "" },
      { text: "It teaches that traditional medicine was inadequate and the Buddha was a doctor", type: "concept_error", logicTag: "literal_misread" },
      { text: "It shows that only wise teachers can cure grief, so one should always seek guidance", type: "concept_error", logicTag: "oversimplified" },
      { text: "It warns against excessive love for children as it causes suffering", type: "concept_error", logicTag: "misreads_lesson" },
    ],
    solutionSteps: ["Kisa Gotami's grief = denial + bargaining (classic grief stages).", "The Buddha's method = lead her to acceptance through shared experience.", "Modern relevance: grief counselling also emphasises sharing loss, accepting impermanence, finding community."],
    shortcut: "Parable for today: accept impermanence. Clinging = suffering. Shared grief = compassion. Universal across cultures.",
  },

  // ── eng_ff_ch9_prose — The Proposal ──────────────────────────────────────
  {
    topic: "eng_ff_ch9_prose", topicId: "eng_ff_ch9_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In Chekhov's 'The Proposal', what is Ivan Vassilevitch Lomov's purpose in visiting the Chubukov household?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "To propose marriage to Natalya, the daughter of Chubukov", type: "correct", logicTag: "" },
      { text: "To settle a business dispute about land ownership", type: "concept_error", logicTag: "wrong_purpose" },
      { text: "To apologise for a previous quarrel with Chubukov", type: "concept_error", logicTag: "wrong_purpose" },
      { text: "To invite the family to his birthday party", type: "concept_error", logicTag: "wrong_purpose" },
    ],
    solutionSteps: ["Lomov comes dressed formally to propose to Natalya.", "Chubukov quickly infers the purpose and is delighted.", "However, the proposal leads to immediate quarrels."],
    shortcut: "Lomov = proposal to Natalya. Chubukov = delighted. But quarrels start before he can even propose.",
  },
  {
    topic: "eng_ff_ch9_prose", topicId: "eng_ff_ch9_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the first subject of quarrel between Lomov and Natalya in 'The Proposal'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "The ownership of the Oxen Meadows (a small piece of land between their properties)", type: "correct", logicTag: "" },
      { text: "The ownership of a prize-winning hunting dog", type: "concept_error", logicTag: "second_quarrel" },
      { text: "Who should host the wedding banquet", type: "concept_error", logicTag: "invented_quarrel" },
      { text: "The quality of Lomov's horse", type: "concept_error", logicTag: "invented_quarrel" },
    ],
    solutionSteps: ["Lomov mentions the Oxen Meadows as part of his estate.", "Natalya insists they belong to the Chubukovs.", "This triggers the first major quarrel; both shout and cite family history."],
    shortcut: "Quarrel 1 = Oxen Meadows (whose land?). Quarrel 2 = whose dog is better. Both are petty but escalate fast.",
  },
  {
    topic: "eng_ff_ch9_prose", topicId: "eng_ff_ch9_prose",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Natalya's reaction when she discovers Lomov had come to propose reveal about her character?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "She is pragmatic and eager for marriage despite their quarrel — she drops her anger immediately when she realises the purpose of the visit", type: "correct", logicTag: "" },
      { text: "She is deeply in love with Lomov and is glad he finally proposed", type: "concept_error", logicTag: "overreads_emotion" },
      { text: "She is hurt by the quarrel and refuses to marry him", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "She pretends not to care but secretly approves", type: "concept_error", logicTag: "overcomplicated" },
    ],
    solutionSteps: ["When Natalya hears from her father that Lomov came to propose, she immediately demands he be brought back.", "She sheds tears — not from love but from realisation she nearly missed a marriage opportunity.", "This shows practical mindset over romantic feelings."],
    shortcut: "Natalya's reaction: practical, not romantic. Realises she almost missed a proposal → demands Lomov back immediately.",
  },
  {
    topic: "eng_ff_ch9_prose", topicId: "eng_ff_ch9_prose",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'The Proposal' by Chekhov?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Satire on petty quarrels and the calculating nature of marriage among the landed gentry", type: "correct", logicTag: "" },
      { text: "A romantic celebration of true love that overcomes all obstacles", type: "concept_error", logicTag: "wrong_tone" },
      { text: "A tragedy about people who cannot communicate", type: "concept_error", logicTag: "wrong_genre" },
      { text: "A commentary on the importance of property rights in rural Russia", type: "concept_error", logicTag: "too_narrow" },
    ],
    solutionSteps: ["The play is a farce/comedy.", "Both characters are quarrelsome, petty, and self-righteous.", "The marriage is motivated by practicality, not love.", "Chekhov mocks the feudal aristocracy's fixation on trivial disputes and social calculations."],
    shortcut: "Theme = satire + farce. No real love — just quarrels and practicality. Chekhov mocks petty landed gentry.",
  },
  {
    topic: "eng_ff_ch9_prose", topicId: "eng_ff_ch9_prose",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the second quarrel between Lomov and Natalya in 'The Proposal'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "About whose hunting dog — Guess (Natalya's) or Squeezer (Lomov's) — is superior", type: "correct", logicTag: "" },
      { text: "About who owns the wedding furniture", type: "concept_error", logicTag: "invented" },
      { text: "About the Oxen Meadows again", type: "concept_error", logicTag: "first_quarrel_repeated" },
      { text: "About which family will pay for the wedding", type: "concept_error", logicTag: "invented" },
    ],
    solutionSteps: ["After reconciliation over Oxen Meadows, Lomov tries to propose again.", "Natalya mentions dogs; Lomov says his Squeezer is better than her Guess.", "A new fierce quarrel breaks out over whose dog is superior."],
    shortcut: "Quarrel 2 = Squeezer (Lomov's dog) vs Guess (Natalya's dog). Both claim their dog is better. Lomov collapses again.",
  },
  {
    topic: "eng_ff_ch9_prose", topicId: "eng_ff_ch9_prose",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "The play 'The Proposal' is described as a farce. What makes it farcical?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Exaggerated quarrels over trivial matters, comic physical reactions (Lomov's fainting), and situations that are absurd yet recognisable", type: "correct", logicTag: "" },
      { text: "It involves mistaken identities and disguises", type: "concept_error", logicTag: "different_comedy_type" },
      { text: "The humour comes from wordplay and puns in every line", type: "concept_error", logicTag: "different_comedy_type" },
      { text: "It uses magical realism to create humour", type: "concept_error", logicTag: "wrong_genre" },
    ],
    solutionSteps: ["A farce uses exaggerated, absurd situations for comedy.", "Lomov faints dramatically; both characters shout and lose composure over trivial things.", "The entire proposal gets derailed multiple times by petty fights — inherently absurd and funny."],
    shortcut: "Farce = exaggeration + absurdity. Lomov faints. Quarrels about meadows and dogs instead of proposing. Very comic.",
  },
  {
    topic: "eng_ff_ch9_prose", topicId: "eng_ff_ch9_prose",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Chubukov's behaviour throughout the play reveal about his character?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "He is hypocritical — sweet when he thinks Lomov will marry Natalya, abusive when they quarrel, sweet again immediately after", type: "correct", logicTag: "" },
      { text: "He is a wise patriarch who mediates all quarrels fairly", type: "concept_error", logicTag: "wrong_reading" },
      { text: "He genuinely dislikes Lomov and only allows the marriage under pressure", type: "concept_error", logicTag: "wrong_reading" },
      { text: "He is absent-minded and does not pay attention to what is happening", type: "concept_error", logicTag: "wrong_characterisation" },
    ],
    solutionSteps: ["Chubukov calls Lomov 'darling' when he guesses the proposal.", "When quarrels break out, he joins in abusing Lomov passionately.", "The moment Lomov agrees to marry, Chubukov blesses them immediately.", "This hypocrisy and opportunism characterise him as a comic villain."],
    shortcut: "Chubukov = opportunist hypocrite. Warm when marriage is possible, abusive when quarrels start, warm again instantly.",
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI, { serverSelectionTimeoutMS: 10_000 });
  console.log("MongoDB connected");

  let created = 0;
  let skipped = 0;

  for (const q of Q) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    created++;
  }

  console.log(`\n✅ English QuestionsA: ${created} created, ${skipped} skipped (${Q.length} total)`);
  await mongoose.disconnect();
}

run().catch((err) => { console.error(err); process.exit(1); });
