/**
 * CBSE Class 5 Mathematics — MCQ seed (Part B: chapters 8–14)
 * 5 questions per chapter × 7 chapters = 35 questions
 * Usage: node config/seedMath5QuestionsB.js
 */
import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";

dotenv.config();

const questions = [
  // ─── Chapter 8: Mapping Your Way ──────────────────────────────────────────
  {
    questionId: "math5_ch8_q1",
    topicId: "math5_ch8",
    text: "A map has a scale of 1 cm = 5 km. Two cities are 8 cm apart on the map. What is the actual distance?",
    options: [
      { text: "40 km",   type: "correct",           logicTag: "8 × 5 = 40 km" },
      { text: "1.6 km",  type: "concept_error",      logicTag: "Divided instead of multiplied" },
      { text: "13 km",   type: "calculation_error",  logicTag: "Added 8+5=13" },
      { text: "80 km",   type: "calculation_error",  logicTag: "Multiplied by 10 instead of 5" },
    ],
    explanation: "Real distance = Map distance × Scale = 8 cm × 5 km/cm = 40 km.",
    solutionSteps: ["Scale: 1 cm = 5 km.", "Map distance = 8 cm.", "Real distance = 8 × 5 = 40 km."],
    shortcut: "Map → Real: multiply by scale. Real → Map: divide by scale.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Mapping Your Way",
  },
  {
    questionId: "math5_ch8_q2",
    topicId: "math5_ch8",
    text: "On a map with scale 1 cm = 10 km, how many cm apart are two towns that are 75 km apart in reality?",
    options: [
      { text: "7.5 cm",  type: "correct",           logicTag: "75 ÷ 10 = 7.5 cm" },
      { text: "750 cm",  type: "concept_error",      logicTag: "Multiplied instead of dividing" },
      { text: "65 cm",   type: "calculation_error",  logicTag: "Subtracted 10 from 75" },
      { text: "85 cm",   type: "calculation_error",  logicTag: "Added 10 to 75" },
    ],
    explanation: "Map distance = Real distance ÷ Scale = 75 ÷ 10 = 7.5 cm.",
    solutionSteps: ["Scale: 1 cm = 10 km.", "Real distance = 75 km.", "Map distance = 75 ÷ 10 = 7.5 cm."],
    shortcut: "Real → Map: ÷ scale. Map → Real: × scale.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Mapping Your Way",
  },
  {
    questionId: "math5_ch8_q3",
    topicId: "math5_ch8",
    text: "You are facing North and turn 90° clockwise. Which direction are you now facing?",
    options: [
      { text: "East",   type: "correct",          logicTag: "N → 90° clockwise = E" },
      { text: "West",   type: "concept_error",    logicTag: "90° anti-clockwise from N = W" },
      { text: "South",  type: "concept_error",    logicTag: "180° from N = S" },
      { text: "North-East", type: "concept_error", logicTag: "45° clockwise from N = NE" },
    ],
    explanation: "Clockwise from North: N → E → S → W → N. A 90° clockwise turn from North gives East.",
    solutionSteps: ["Start: North.", "Clockwise 90° → East.", "Answer: East."],
    shortcut: "Clockwise quarter-turn: N→E→S→W→N.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Mapping Your Way",
  },
  {
    questionId: "math5_ch8_q4",
    topicId: "math5_ch8",
    text: "On a map, a road is 6.5 cm long. The scale is 1 cm = 4 km. What is the road's actual length?",
    options: [
      { text: "26 km",    type: "correct",           logicTag: "6.5 × 4 = 26 km" },
      { text: "1.625 km", type: "concept_error",      logicTag: "Divided instead of multiplied" },
      { text: "10.5 km",  type: "calculation_error",  logicTag: "Added 6.5+4=10.5" },
      { text: "24 km",    type: "calculation_error",  logicTag: "Used 6 instead of 6.5" },
    ],
    explanation: "Real length = 6.5 cm × 4 km/cm = 26 km.",
    solutionSteps: ["Map length = 6.5 cm. Scale = 4 km per cm.", "Real length = 6.5 × 4 = 26 km."],
    shortcut: "Decimal × whole: 6.5 × 4 = 6 × 4 + 0.5 × 4 = 24 + 2 = 26.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Mapping Your Way",
  },
  {
    questionId: "math5_ch8_q5",
    topicId: "math5_ch8",
    text: "Which direction is opposite to South-West?",
    options: [
      { text: "North-East",  type: "correct",          logicTag: "Opposite of SW is NE (180° apart)" },
      { text: "North-West",  type: "concept_error",    logicTag: "NW is 90° from SW, not opposite" },
      { text: "South-East",  type: "concept_error",    logicTag: "SE is adjacent to SW, not opposite" },
      { text: "North",       type: "concept_error",    logicTag: "North is opposite to South, not SW" },
    ],
    explanation: "Opposite directions are 180° apart. Opposite of South-West is North-East.",
    solutionSteps: ["SW is between S and W.", "Opposite of S is N; opposite of W is E.", "Opposite of SW = NE."],
    shortcut: "Opposite pairs: N↔S, E↔W, NE↔SW, NW↔SE.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Mapping Your Way",
  },

  // ─── Chapter 9: Boxes and Sketches ────────────────────────────────────────
  {
    questionId: "math5_ch9_q1",
    topicId: "math5_ch9",
    text: "A cube has ___ faces, ___ edges, and ___ vertices.",
    options: [
      { text: "6 faces, 12 edges, 8 vertices",  type: "correct",          logicTag: "Standard cube: F=6, E=12, V=8" },
      { text: "4 faces, 6 edges, 4 vertices",   type: "concept_error",    logicTag: "Properties of a tetrahedron" },
      { text: "6 faces, 8 edges, 12 vertices",  type: "concept_error",    logicTag: "Swapped edges and vertices" },
      { text: "8 faces, 12 edges, 6 vertices",  type: "concept_error",    logicTag: "Swapped faces and vertices" },
    ],
    explanation: "A cube has 6 square faces, 12 edges (where faces meet), and 8 vertices (corners). Verify: F+V−E = 6+8−12 = 2 ✓.",
    solutionSteps: ["Faces: top, bottom, front, back, left, right = 6.", "Vertices: 8 corners.", "Edges: 12 (4 top + 4 bottom + 4 vertical)."],
    shortcut: "Cube: F=6, E=12, V=8. Remember with Euler: 6+8−12=2.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Boxes and Sketches",
  },
  {
    questionId: "math5_ch9_q2",
    topicId: "math5_ch9",
    text: "Which of the following correctly states Euler's formula for 3D shapes?",
    options: [
      { text: "F + V − E = 2",  type: "correct",          logicTag: "Faces + Vertices − Edges = 2" },
      { text: "F + E − V = 2",  type: "concept_error",    logicTag: "Wrong arrangement" },
      { text: "F × V = E",      type: "concept_error",    logicTag: "Not Euler's formula" },
      { text: "F + V + E = 2",  type: "concept_error",    logicTag: "All added, not minus E" },
    ],
    explanation: "Euler's formula: Faces + Vertices − Edges = 2 (F + V − E = 2) for any convex polyhedron.",
    solutionSteps: ["F = faces, V = vertices, E = edges.", "Formula: F + V − E = 2.", "Check with cube: 6+8−12 = 2 ✓."],
    shortcut: "FaVouritE formula: F + V − E = 2.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Boxes and Sketches",
  },
  {
    questionId: "math5_ch9_q3",
    topicId: "math5_ch9",
    text: "A triangular prism has 5 faces and 6 vertices. How many edges does it have?",
    options: [
      { text: "9",   type: "correct",           logicTag: "F+V−E=2 → 5+6−E=2 → E=9" },
      { text: "11",  type: "calculation_error",  logicTag: "Arithmetic error" },
      { text: "7",   type: "calculation_error",  logicTag: "F+V−2=9, not 7" },
      { text: "12",  type: "concept_error",      logicTag: "Used cube's edge count" },
    ],
    explanation: "Using Euler's formula: F + V − E = 2 → 5 + 6 − E = 2 → E = 11 − 2 = 9.",
    solutionSteps: ["F=5, V=6. Apply F+V−E=2.", "5+6−E=2 → 11−E=2 → E=9.", "9 edges."],
    shortcut: "E = F + V − 2.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Boxes and Sketches",
  },
  {
    questionId: "math5_ch9_q4",
    topicId: "math5_ch9",
    text: "Which of the following is a valid net for a cube?",
    options: [
      { text: "A cross-shaped arrangement of 6 squares",         type: "correct",          logicTag: "Classic T-cross net folds into a cube" },
      { text: "6 squares arranged in a straight line",           type: "concept_error",    logicTag: "Some squares would overlap when folded" },
      { text: "4 squares arranged in a 2×2 grid",               type: "concept_error",    logicTag: "Only 4 faces, not enough for a cube" },
      { text: "6 triangles arranged around a central triangle",  type: "concept_error",    logicTag: "Triangles form a tetrahedron net, not cube" },
    ],
    explanation: "A cube has 6 square faces. A valid net must contain exactly 6 squares arranged so they fold into a closed box without overlapping.",
    solutionSteps: ["Cube needs 6 square faces.", "A cross-shape (4 in a column, 1 on each side of the second) folds correctly.", "The straight line of 6 squares causes overlap."],
    shortcut: "There are 11 valid nets of a cube — all have 6 connected squares.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Boxes and Sketches",
  },
  {
    questionId: "math5_ch9_q5",
    topicId: "math5_ch9",
    text: "How many faces does a square pyramid have?",
    options: [
      { text: "5",  type: "correct",          logicTag: "1 square base + 4 triangular faces = 5" },
      { text: "4",  type: "concept_error",    logicTag: "Counted only triangular faces" },
      { text: "6",  type: "concept_error",    logicTag: "Confused with cube" },
      { text: "8",  type: "concept_error",    logicTag: "Confused with octahedron" },
    ],
    explanation: "A square pyramid has 1 square base + 4 triangular faces = 5 faces total.",
    solutionSteps: ["Base: 1 square face.", "Sides: 4 triangular faces.", "Total: 1 + 4 = 5 faces."],
    shortcut: "Pyramid on n-gon base: n+1 faces, 2n edges, n+1 vertices.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Boxes and Sketches",
  },

  // ─── Chapter 10: Tenths and Hundredths ────────────────────────────────────
  {
    questionId: "math5_ch10_q1",
    topicId: "math5_ch10",
    text: "Write 7/10 as a decimal.",
    options: [
      { text: "0.7",   type: "correct",          logicTag: "7/10 = 0.7 (tenths place)" },
      { text: "7.0",   type: "concept_error",    logicTag: "Placed 7 in ones, not tenths" },
      { text: "0.07",  type: "concept_error",    logicTag: "Wrote in hundredths place instead of tenths" },
      { text: "7/10",  type: "guessing",         logicTag: "Did not convert" },
    ],
    explanation: "The tenths place is the first decimal place. 7/10 = 0.7.",
    solutionSteps: ["Denominator 10 → tenths place (1 decimal place).", "7/10 = 0.7."],
    shortcut: "Denominator 10 → 1 decimal place. Denominator 100 → 2 decimal places.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Tenths and Hundredths",
  },
  {
    questionId: "math5_ch10_q2",
    topicId: "math5_ch10",
    text: "Which decimal is greater: 0.6 or 0.58?",
    options: [
      { text: "0.6",   type: "correct",           logicTag: "0.60 > 0.58; tenths digit 6>5" },
      { text: "0.58",  type: "concept_error",      logicTag: "Thinks 58 > 6 so 0.58 > 0.6" },
      { text: "Equal", type: "concept_error",      logicTag: "They are not equal" },
      { text: "Cannot tell", type: "guessing",     logicTag: "Can be determined" },
    ],
    explanation: "Compare after equalising decimal places: 0.60 vs 0.58. Tenths digit: 6 > 5. So 0.60 > 0.58, i.e., 0.6 > 0.58.",
    solutionSteps: ["Write 0.6 as 0.60.", "Compare digit by digit: tenths: 6 vs 5. 6 > 5.", "0.6 > 0.58."],
    shortcut: "Add trailing zeros to make the same number of decimal places, then compare as whole numbers.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Tenths and Hundredths",
  },
  {
    questionId: "math5_ch10_q3",
    topicId: "math5_ch10",
    text: "What is 0.35 written as a fraction in its simplest form?",
    options: [
      { text: "7/20",   type: "correct",           logicTag: "35/100 = 7/20" },
      { text: "35/10",  type: "concept_error",      logicTag: "Used denominator 10 instead of 100" },
      { text: "7/10",   type: "calculation_error",  logicTag: "Simplified 35/100 incorrectly" },
      { text: "35/100", type: "partial_logic",      logicTag: "Correct fraction but not simplified" },
    ],
    explanation: "0.35 = 35/100. Simplify: GCD(35,100)=5. 35÷5=7, 100÷5=20. Simplest form: 7/20.",
    solutionSteps: ["0.35 = 35/100 (two decimal places → denominator 100).", "GCD(35,100) = 5.", "35÷5 = 7, 100÷5 = 20. Answer: 7/20."],
    shortcut: "Two decimal places → /100. Then simplify by GCD.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Tenths and Hundredths",
  },
  {
    questionId: "math5_ch10_q4",
    topicId: "math5_ch10",
    text: "What is the value of the digit 4 in 3.47?",
    options: [
      { text: "4 tenths (0.4)",      type: "correct",          logicTag: "4 is in the tenths place" },
      { text: "4 hundredths (0.04)", type: "concept_error",    logicTag: "Confused tenths and hundredths places" },
      { text: "4 ones (4)",          type: "concept_error",    logicTag: "4 is after the decimal point" },
      { text: "4 tens (40)",         type: "concept_error",    logicTag: "Digit is fractional, not whole" },
    ],
    explanation: "In 3.47: 3 is in the ones place, 4 is in the tenths place (value = 0.4), 7 is in the hundredths place (value = 0.07).",
    solutionSteps: ["3.47 → ones.tenths hundredths.", "The digit 4 is immediately after the decimal point = tenths place.", "Value = 4/10 = 0.4."],
    shortcut: "First decimal digit = tenths; second = hundredths.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Tenths and Hundredths",
  },
  {
    questionId: "math5_ch10_q5",
    topicId: "math5_ch10",
    text: "Order from smallest to largest: 0.9, 0.09, 0.99, 0.19.",
    options: [
      { text: "0.09, 0.19, 0.9, 0.99",  type: "correct",          logicTag: "Correct ascending order" },
      { text: "0.09, 0.9, 0.19, 0.99",  type: "concept_error",    logicTag: "Incorrect placement of 0.19" },
      { text: "0.99, 0.9, 0.19, 0.09",  type: "concept_error",    logicTag: "Descending, not ascending" },
      { text: "0.9, 0.09, 0.99, 0.19",  type: "guessing",         logicTag: "Not ordered" },
    ],
    explanation: "Compare tenths digits: 0 < 1 < 9 < 9. For equal tenths, compare hundredths: 0.9(0) vs 0.99 → 0.90 < 0.99. Order: 0.09 < 0.19 < 0.90 < 0.99.",
    solutionSteps: ["Write as: 0.90, 0.09, 0.99, 0.19.", "Compare tenths: 0, 1, 9, 9.", "For equal tenths (both 9): hundredths: 0 vs 9 → 0.90 < 0.99.", "Order: 0.09, 0.19, 0.90, 0.99."],
    shortcut: "Add trailing zeros, then compare as whole numbers: 09 < 19 < 90 < 99.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Tenths and Hundredths",
  },

  // ─── Chapter 11: Area and Its Boundary ────────────────────────────────────
  {
    questionId: "math5_ch11_q1",
    topicId: "math5_ch11",
    text: "A rectangular garden is 12 m long and 8 m wide. What is its perimeter?",
    options: [
      { text: "40 m",  type: "correct",           logicTag: "P = 2(12+8) = 2×20 = 40 m" },
      { text: "96 m",  type: "concept_error",      logicTag: "Calculated area (12×8=96) instead" },
      { text: "20 m",  type: "partial_logic",      logicTag: "Found l+b but forgot to multiply by 2" },
      { text: "48 m",  type: "calculation_error",  logicTag: "Used 2×(l+b)=2×24=48" },
    ],
    explanation: "Perimeter = 2(l + b) = 2(12 + 8) = 2 × 20 = 40 m.",
    solutionSteps: ["l = 12 m, b = 8 m.", "P = 2(l + b) = 2(12 + 8) = 2 × 20 = 40 m."],
    shortcut: "Double the sum of length and breadth.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Area and Its Boundary",
  },
  {
    questionId: "math5_ch11_q2",
    topicId: "math5_ch11",
    text: "A square field has a perimeter of 48 m. What is its area?",
    options: [
      { text: "144 m²",  type: "correct",           logicTag: "Side=48÷4=12; Area=12²=144" },
      { text: "576 m²",  type: "concept_error",      logicTag: "Used perimeter as side: 48²=2304; or 48/4=12, 12×48=576" },
      { text: "12 m²",   type: "partial_logic",      logicTag: "Found side but not area" },
      { text: "192 m²",  type: "calculation_error",  logicTag: "Multiplied 48×4=192 instead of squaring side" },
    ],
    explanation: "Side of square = 48 ÷ 4 = 12 m. Area = side² = 12² = 144 m².",
    solutionSteps: ["Side = Perimeter ÷ 4 = 48 ÷ 4 = 12 m.", "Area = 12 × 12 = 144 m²."],
    shortcut: "Square: side = perimeter/4. Area = side².",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Area and Its Boundary",
  },
  {
    questionId: "math5_ch11_q3",
    topicId: "math5_ch11",
    text: "Two rectangles: A is 4 m × 9 m and B is 6 m × 6 m. Which has the larger area?",
    options: [
      { text: "They are equal (both 36 m²)",  type: "correct",          logicTag: "4×9=36, 6×6=36" },
      { text: "A is larger",                   type: "concept_error",    logicTag: "Not calculated correctly" },
      { text: "B is larger",                   type: "concept_error",    logicTag: "Not calculated correctly" },
      { text: "Cannot compare",               type: "guessing",         logicTag: "Areas can be calculated" },
    ],
    explanation: "Area of A = 4 × 9 = 36 m². Area of B = 6 × 6 = 36 m². Both equal 36 m².",
    solutionSteps: ["Area A = 4 × 9 = 36 m².", "Area B = 6 × 6 = 36 m².", "They are equal."],
    shortcut: "Different shapes can have equal areas — always calculate before comparing.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Area and Its Boundary",
  },
  {
    questionId: "math5_ch11_q4",
    topicId: "math5_ch11",
    text: "A floor is 10 m × 6 m. Square tiles of side 1 m are used to tile it. How many tiles are needed?",
    options: [
      { text: "60",  type: "correct",           logicTag: "Area = 10×6 = 60 tiles" },
      { text: "32",  type: "concept_error",      logicTag: "Calculated perimeter 2(10+6)=32" },
      { text: "16",  type: "concept_error",      logicTag: "Used 10+6=16" },
      { text: "100", type: "calculation_error",  logicTag: "Used 10²=100" },
    ],
    explanation: "Each 1 m × 1 m tile covers 1 m². Floor area = 10 × 6 = 60 m². Tiles needed = 60.",
    solutionSteps: ["Floor area = 10 × 6 = 60 m².", "Each tile area = 1 m².", "Tiles = 60 ÷ 1 = 60."],
    shortcut: "Tiles needed = floor area ÷ tile area.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Area and Its Boundary",
  },
  {
    questionId: "math5_ch11_q5",
    topicId: "math5_ch11",
    text: "If a rectangle's length is doubled and breadth is halved, what happens to its area?",
    options: [
      { text: "Area stays the same",    type: "correct",          logicTag: "(2l) × (b/2) = l×b = same area" },
      { text: "Area doubles",           type: "concept_error",    logicTag: "Forgot that breadth halves" },
      { text: "Area halves",            type: "concept_error",    logicTag: "Forgot that length doubles" },
      { text: "Area becomes 4 times",   type: "concept_error",    logicTag: "Both doubled error" },
    ],
    explanation: "New area = (2l) × (b/2) = 2 × (1/2) × l × b = l × b. The area is unchanged.",
    solutionSteps: ["Original area = l × b.", "New length = 2l, new breadth = b/2.", "New area = 2l × b/2 = l × b. Same!"],
    shortcut: "Doubling one dimension and halving the other keeps the area constant.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Area and Its Boundary",
  },

  // ─── Chapter 12: Smart Charts ──────────────────────────────────────────────
  {
    questionId: "math5_ch12_q1",
    topicId: "math5_ch12",
    text: "A bar graph shows: Apples=30, Bananas=45, Oranges=25, Grapes=40. Which fruit is the most popular?",
    options: [
      { text: "Bananas (45)",  type: "correct",          logicTag: "45 is the highest value" },
      { text: "Grapes (40)",   type: "concept_error",    logicTag: "Second highest but not the most" },
      { text: "Apples (30)",   type: "concept_error",    logicTag: "Lower value" },
      { text: "Oranges (25)",  type: "concept_error",    logicTag: "Lowest value" },
    ],
    explanation: "The most popular fruit has the tallest bar. Bananas = 45, which is the highest value.",
    solutionSteps: ["List values: Apples=30, Bananas=45, Oranges=25, Grapes=40.", "Highest = 45 = Bananas."],
    shortcut: "Most popular = tallest bar = largest value.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Smart Charts",
  },
  {
    questionId: "math5_ch12_q2",
    topicId: "math5_ch12",
    text: "Using the same data (Apples=30, Bananas=45, Oranges=25, Grapes=40), what is the total number of fruits?",
    options: [
      { text: "140",  type: "correct",           logicTag: "30+45+25+40=140" },
      { text: "120",  type: "calculation_error",  logicTag: "Arithmetic error" },
      { text: "45",   type: "concept_error",      logicTag: "Gave only the maximum" },
      { text: "135",  type: "calculation_error",  logicTag: "Missed one value" },
    ],
    explanation: "Total = 30 + 45 + 25 + 40 = 140.",
    solutionSteps: ["30 + 45 = 75.", "75 + 25 = 100.", "100 + 40 = 140."],
    shortcut: "Total = sum of all bar values.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Smart Charts",
  },
  {
    questionId: "math5_ch12_q3",
    topicId: "math5_ch12",
    text: "In a pictograph, each ☺ symbol represents 5 students. If Class A has 4☺ symbols, how many students are in Class A?",
    options: [
      { text: "20",  type: "correct",           logicTag: "4 × 5 = 20 students" },
      { text: "4",   type: "partial_logic",      logicTag: "Counted symbols without applying scale" },
      { text: "9",   type: "calculation_error",  logicTag: "Added 4+5=9" },
      { text: "25",  type: "calculation_error",  logicTag: "Counted 5 symbols instead of 4" },
    ],
    explanation: "Each symbol = 5 students. Class A has 4 symbols. Total = 4 × 5 = 20 students.",
    solutionSteps: ["Key: 1 symbol = 5 students.", "Class A symbols = 4.", "Students = 4 × 5 = 20."],
    shortcut: "Pictograph: count symbols × scale value.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Smart Charts",
  },
  {
    questionId: "math5_ch12_q4",
    topicId: "math5_ch12",
    text: "From the fruit data (Apples=30, Bananas=45, Oranges=25, Grapes=40), how many more bananas than oranges are there?",
    options: [
      { text: "20",  type: "correct",           logicTag: "45 − 25 = 20" },
      { text: "70",  type: "concept_error",      logicTag: "Added 45+25=70" },
      { text: "15",  type: "calculation_error",  logicTag: "Arithmetic error" },
      { text: "5",   type: "calculation_error",  logicTag: "Used 30−25=5 (wrong pair)" },
    ],
    explanation: "Difference = Bananas − Oranges = 45 − 25 = 20.",
    solutionSteps: ["Bananas = 45, Oranges = 25.", "Difference = 45 − 25 = 20."],
    shortcut: "Difference = larger value − smaller value.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Smart Charts",
  },
  {
    questionId: "math5_ch12_q5",
    topicId: "math5_ch12",
    text: "In a bar graph where the y-axis scale is: each unit = 10, a bar reaches height 7. What value does it represent?",
    options: [
      { text: "70",   type: "correct",           logicTag: "7 units × 10 = 70" },
      { text: "7",    type: "concept_error",      logicTag: "Read bar height without applying scale" },
      { text: "17",   type: "calculation_error",  logicTag: "Added 7+10=17" },
      { text: "700",  type: "calculation_error",  logicTag: "Multiplied by 100 instead of 10" },
    ],
    explanation: "Bar height = 7 units on the y-axis. Scale: 1 unit = 10. Value = 7 × 10 = 70.",
    solutionSteps: ["Bar height = 7 units.", "Scale: 1 unit = 10.", "Value = 7 × 10 = 70."],
    shortcut: "Always multiply bar height by the scale factor.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Smart Charts",
  },

  // ─── Chapter 13: Ways to Multiply and Divide ──────────────────────────────
  {
    questionId: "math5_ch13_q1",
    topicId: "math5_ch13",
    text: "What is 325 × 4?",
    options: [
      { text: "1300",  type: "correct",           logicTag: "300×4+25×4=1200+100=1300" },
      { text: "1280",  type: "calculation_error",  logicTag: "320×4=1280 (missed the 5)" },
      { text: "329",   type: "concept_error",      logicTag: "Added 325+4=329" },
      { text: "1600",  type: "calculation_error",  logicTag: "Used 400×4=1600" },
    ],
    explanation: "325 × 4: split into 300×4 + 25×4 = 1200 + 100 = 1300.",
    solutionSteps: ["300 × 4 = 1200.", "25 × 4 = 100.", "Total = 1200 + 100 = 1300."],
    shortcut: "Break the number: (300 + 25) × 4.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Ways to Multiply and Divide",
  },
  {
    questionId: "math5_ch13_q2",
    topicId: "math5_ch13",
    text: "What is 756 ÷ 6?",
    options: [
      { text: "126",  type: "correct",           logicTag: "756÷6=126" },
      { text: "120",  type: "calculation_error",  logicTag: "720÷6=120 (missed 36)" },
      { text: "150",  type: "calculation_error",  logicTag: "900÷6=150" },
      { text: "1260", type: "concept_error",      logicTag: "Missed decimal position" },
    ],
    explanation: "756 ÷ 6: 7÷6=1 rem 1; bring down 5 → 15÷6=2 rem 3; bring down 6 → 36÷6=6. Quotient = 126.",
    solutionSteps: ["7 ÷ 6 = 1 rem 1.", "15 ÷ 6 = 2 rem 3.", "36 ÷ 6 = 6.", "Quotient = 126."],
    shortcut: "Check: 126 × 6 = 756 ✓.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Ways to Multiply and Divide",
  },
  {
    questionId: "math5_ch13_q3",
    topicId: "math5_ch13",
    text: "When 489 is divided by 7, what is the remainder?",
    options: [
      { text: "6",   type: "correct",           logicTag: "489÷7=69 rem 6; 7×69=483; 489−483=6" },
      { text: "0",   type: "concept_error",      logicTag: "Assumed exact division" },
      { text: "1",   type: "calculation_error",  logicTag: "Arithmetic error" },
      { text: "69",  type: "concept_error",      logicTag: "Gave quotient, not remainder" },
    ],
    explanation: "489 ÷ 7 = 69 remainder 6. Check: 7 × 69 = 483; 489 − 483 = 6.",
    solutionSteps: ["7 × 60 = 420; 7 × 9 = 63; 7 × 69 = 483.", "489 − 483 = 6.", "Remainder = 6."],
    shortcut: "Remainder = Dividend − (Divisor × Quotient).",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Ways to Multiply and Divide",
  },
  {
    questionId: "math5_ch13_q4",
    topicId: "math5_ch13",
    text: "A school has 348 students. They are divided equally into 4 classes. How many students in each class?",
    options: [
      { text: "87",   type: "correct",           logicTag: "348 ÷ 4 = 87" },
      { text: "84",   type: "calculation_error",  logicTag: "Arithmetic error" },
      { text: "352",  type: "concept_error",      logicTag: "Added instead of dividing" },
      { text: "1392", type: "concept_error",      logicTag: "Multiplied instead of dividing" },
    ],
    explanation: "348 ÷ 4: 32÷4=8 (for 320) wait — 3÷4=0 rem 3; 34÷4=8 rem 2; 28÷4=7. Quotient=87.",
    solutionSteps: ["34 ÷ 4 = 8 rem 2.", "28 ÷ 4 = 7.", "Quotient = 87. Check: 87 × 4 = 348 ✓."],
    shortcut: "Check by multiplying back: quotient × divisor = dividend.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "Ways to Multiply and Divide",
  },
  {
    questionId: "math5_ch13_q5",
    topicId: "math5_ch13",
    text: "What is 45 × 99?",
    options: [
      { text: "4455",  type: "correct",           logicTag: "45×(100−1)=4500−45=4455" },
      { text: "4500",  type: "partial_logic",      logicTag: "Used 45×100 without subtracting" },
      { text: "4445",  type: "calculation_error",  logicTag: "Subtracted 55 instead of 45" },
      { text: "4400",  type: "calculation_error",  logicTag: "Subtracted 100 instead of 45" },
    ],
    explanation: "45 × 99 = 45 × (100 − 1) = 4500 − 45 = 4455.",
    solutionSteps: ["99 = 100 − 1.", "45 × 100 = 4500.", "45 × 1 = 45.", "4500 − 45 = 4455."],
    shortcut: "Multiply by 99 → multiply by 100 then subtract the number.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "Ways to Multiply and Divide",
  },

  // ─── Chapter 14: How Big? How Heavy? ──────────────────────────────────────
  {
    questionId: "math5_ch14_q1",
    topicId: "math5_ch14",
    text: "A bag weighs 2 kg 350 g. What is its weight in grams?",
    options: [
      { text: "2350 g",  type: "correct",           logicTag: "2×1000+350=2350 g" },
      { text: "235 g",   type: "concept_error",      logicTag: "Multiplied by 100 instead of 1000" },
      { text: "2035 g",  type: "calculation_error",  logicTag: "Used 2×1000+35=2035" },
      { text: "2300 g",  type: "partial_logic",      logicTag: "Ignored the 50 g" },
    ],
    explanation: "2 kg = 2 × 1000 g = 2000 g. Total = 2000 + 350 = 2350 g.",
    solutionSteps: ["Convert: 2 kg = 2000 g.", "Add: 2000 + 350 = 2350 g."],
    shortcut: "kg to g: multiply by 1000.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "How Big? How Heavy?",
  },
  {
    questionId: "math5_ch14_q2",
    topicId: "math5_ch14",
    text: "A bottle holds 1 L 750 mL. Convert this to millilitres.",
    options: [
      { text: "1750 mL",  type: "correct",           logicTag: "1×1000+750=1750 mL" },
      { text: "175 mL",   type: "concept_error",      logicTag: "Multiplied by 100 instead of 1000" },
      { text: "1075 mL",  type: "calculation_error",  logicTag: "Used 1×1000+075 forgetting proper place" },
      { text: "2750 mL",  type: "calculation_error",  logicTag: "Added 1000+750+1000" },
    ],
    explanation: "1 L = 1000 mL. Total = 1000 + 750 = 1750 mL.",
    solutionSteps: ["1 L = 1000 mL.", "1750 mL = 1000 + 750."],
    shortcut: "L to mL: multiply by 1000.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "How Big? How Heavy?",
  },
  {
    questionId: "math5_ch14_q3",
    topicId: "math5_ch14",
    text: "Which is heavier: 3500 g or 3 kg 400 g?",
    options: [
      { text: "3500 g",  type: "correct",           logicTag: "3500 g vs 3400 g; 3500 > 3400" },
      { text: "3 kg 400 g", type: "concept_error",  logicTag: "3400 g < 3500 g" },
      { text: "Equal",   type: "concept_error",     logicTag: "3500 ≠ 3400" },
      { text: "Cannot tell", type: "guessing",      logicTag: "Can be converted and compared" },
    ],
    explanation: "3 kg 400 g = 3000 + 400 = 3400 g. Comparing: 3500 g > 3400 g. So 3500 g is heavier.",
    solutionSteps: ["Convert: 3 kg 400 g = 3400 g.", "Compare: 3500 vs 3400.", "3500 > 3400, so 3500 g is heavier."],
    shortcut: "Convert all to the same unit before comparing.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "How Big? How Heavy?",
  },
  {
    questionId: "math5_ch14_q4",
    topicId: "math5_ch14",
    text: "A jug has 2 L 200 mL of juice. After drinking 850 mL, how much is left?",
    options: [
      { text: "1 L 350 mL",  type: "correct",           logicTag: "2200−850=1350 mL=1 L 350 mL" },
      { text: "1 L 150 mL",  type: "calculation_error",  logicTag: "2200−1050=1150" },
      { text: "3 L 50 mL",   type: "concept_error",      logicTag: "Added instead of subtracted" },
      { text: "1 L 450 mL",  type: "calculation_error",  logicTag: "Arithmetic error" },
    ],
    explanation: "Total = 2200 mL. After drinking 850 mL: 2200 − 850 = 1350 mL = 1 L 350 mL.",
    solutionSteps: ["Convert: 2 L 200 mL = 2200 mL.", "2200 − 850 = 1350 mL.", "Convert back: 1350 mL = 1 L 350 mL."],
    shortcut: "Convert to smallest unit, calculate, then convert back.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "5",
    chapter: "How Big? How Heavy?",
  },
  {
    questionId: "math5_ch14_q5",
    topicId: "math5_ch14",
    text: "How many 250 mL glasses can be filled from a 2 L bottle?",
    options: [
      { text: "8",   type: "correct",           logicTag: "2000 ÷ 250 = 8" },
      { text: "4",   type: "concept_error",      logicTag: "Used 1000÷250=4 (1 L instead of 2 L)" },
      { text: "10",  type: "calculation_error",  logicTag: "Used 2500÷250=10" },
      { text: "2",   type: "concept_error",      logicTag: "Divided 2÷250 without converting" },
    ],
    explanation: "2 L = 2000 mL. Number of glasses = 2000 ÷ 250 = 8.",
    solutionSteps: ["Convert: 2 L = 2000 mL.", "Glasses = 2000 ÷ 250 = 8."],
    shortcut: "Convert to mL first, then divide.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "5",
    chapter: "How Big? How Heavy?",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");

  for (const q of questions) {
    await Question.findOneAndUpdate(
      { questionId: q.questionId },
      q,
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`  ✓ ${q.questionId}`);
  }

  console.log(`\nSeeded ${questions.length} questions for Class 5 Math (Part B, Ch 8–14).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
