import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // sst_ch1_unification
  { topic: "sst_ch1_unification", questionText: "Who was the 'Iron Chancellor' responsible for German unification?", options: [{ text: "Otto von Bismarck", type: "correct", logicTag: "" }, { text: "Napoleon Bonaparte", type: "concept_error", logicTag: "" }, { text: "Giuseppe Garibaldi", type: "concept_error", logicTag: "" }, { text: "Cavour", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch1_unification", questionText: "Germany was unified as a nation in:", options: [{ text: "1871", type: "correct", logicTag: "" }, { text: "1848", type: "concept_error", logicTag: "" }, { text: "1815", type: "concept_error", logicTag: "" }, { text: "1789", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch1_unification", questionText: "Which battle was decisive in Prussian victory over France, leading to German unification?", options: [{ text: "Battle of Sedan", type: "correct", logicTag: "" }, { text: "Battle of Waterloo", type: "concept_error", logicTag: "" }, { text: "Battle of Leipzig", type: "concept_error", logicTag: "" }, { text: "Battle of Austerlitz", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch1_unification", questionText: "Who led the Red Shirts movement to unify Italy?", options: [{ text: "Giuseppe Garibaldi", type: "correct", logicTag: "" }, { text: "Mazzini", type: "concept_error", logicTag: "" }, { text: "Bismarck", type: "concept_error", logicTag: "" }, { text: "King Victor Emmanuel", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch1_unification", questionText: "The 'Young Italy' movement was founded by:", options: [{ text: "Giuseppe Mazzini", type: "correct", logicTag: "" }, { text: "Cavour", type: "concept_error", logicTag: "" }, { text: "Garibaldi", type: "concept_error", logicTag: "" }, { text: "Napoleon III", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch1_unification", questionText: "Which region did Garibaldi's forces capture in 1860 to advance Italian unification?", options: [{ text: "Kingdom of Two Sicilies", type: "correct", logicTag: "" }, { text: "Lombardy", type: "concept_error", logicTag: "" }, { text: "Venice", type: "concept_error", logicTag: "" }, { text: "Papal States", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch1_unification", questionText: "Bismarck used 'blood and iron' policy meaning:", options: [{ text: "Military force and war rather than diplomacy", type: "correct", logicTag: "" }, { text: "Economic trade agreements", type: "concept_error", logicTag: "" }, { text: "Democratic elections", type: "concept_error", logicTag: "" }, { text: "Cultural nationalism", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch1_unification", questionText: "Italy was unified as a nation-state in:", options: [{ text: "1861", type: "correct", logicTag: "" }, { text: "1871", type: "concept_error", logicTag: "" }, { text: "1848", type: "concept_error", logicTag: "" }, { text: "1815", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.2 },

  // sst_ch1_visualising_nation
  { topic: "sst_ch1_visualising_nation", questionText: "The figure of 'Marianne' was used to represent:", options: [{ text: "France", type: "correct", logicTag: "" }, { text: "Germany", type: "concept_error", logicTag: "" }, { text: "Britain", type: "concept_error", logicTag: "" }, { text: "Italy", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch1_visualising_nation", questionText: "Germania was the allegory of which nation?", options: [{ text: "Germany", type: "correct", logicTag: "" }, { text: "France", type: "concept_error", logicTag: "" }, { text: "Austria", type: "concept_error", logicTag: "" }, { text: "Prussia", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch1_visualising_nation", questionText: "Allegories of nations were portrayed as:", options: [{ text: "Female figures representing abstract ideals", type: "correct", logicTag: "" }, { text: "Kings and rulers", type: "concept_error", logicTag: "" }, { text: "Military generals", type: "concept_error", logicTag: "" }, { text: "Religious leaders", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch1_visualising_nation", questionText: "Britannia was the female allegory for:", options: [{ text: "Britain", type: "correct", logicTag: "" }, { text: "France", type: "concept_error", logicTag: "" }, { text: "Greece", type: "concept_error", logicTag: "" }, { text: "Rome", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch1_visualising_nation", questionText: "Marianne's key symbol in French paintings was:", options: [{ text: "Red cap (Liberty cap)", type: "correct", logicTag: "" }, { text: "Crown", type: "concept_error", logicTag: "" }, { text: "Sword", type: "concept_error", logicTag: "" }, { text: "Oak leaves", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch1_visualising_nation", questionText: "German oak tree symbolised:", options: [{ text: "Heroism and strength", type: "correct", logicTag: "" }, { text: "Peace", type: "concept_error", logicTag: "" }, { text: "Liberty", type: "concept_error", logicTag: "" }, { text: "Equality", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch1_visualising_nation", questionText: "Romanticism as a cultural movement sought to:", options: [{ text: "Create national pride through art, poetry and music", type: "correct", logicTag: "" }, { text: "Promote industrialisation", type: "concept_error", logicTag: "" }, { text: "Encourage democracy only", type: "concept_error", logicTag: "" }, { text: "Spread colonial ideas", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch1_visualising_nation", questionText: "The painter Philipp Veit's Germania wore:", options: [{ text: "A crown of oak leaves", type: "correct", logicTag: "" }, { text: "A red cap", type: "concept_error", logicTag: "" }, { text: "A helmet with eagle", type: "concept_error", logicTag: "" }, { text: "A blue robe", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "1", isAIGenerated: true, difficultyScore: 0.8 },

  // sst_ch2_collective_belonging
  { topic: "sst_ch2_collective_belonging", questionText: "Which symbol became a unifying element of Indian nationalism?", options: [{ text: "Vande Mataram", type: "correct", logicTag: "" }, { text: "Union Jack", type: "concept_error", logicTag: "" }, { text: "Crescent Moon", type: "concept_error", logicTag: "" }, { text: "Trident", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "2", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch2_collective_belonging", questionText: "Bankim Chandra Chattopadhyay wrote 'Vande Mataram' in:", options: [{ text: "Anandamath", type: "correct", logicTag: "" }, { text: "Gitanjali", type: "concept_error", logicTag: "" }, { text: "Gora", type: "concept_error", logicTag: "" }, { text: "Devdas", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "2", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch2_collective_belonging", questionText: "The Swaraj flag designed by Gandhiji had which symbol?", options: [{ text: "Spinning wheel (charkha)", type: "correct", logicTag: "" }, { text: "Ashoka Chakra", type: "concept_error", logicTag: "" }, { text: "Tiger", type: "concept_error", logicTag: "" }, { text: "Lotus", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "2", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch2_collective_belonging", questionText: "Bharat Mata image was first created by:", options: [{ text: "Abanindranath Tagore", type: "correct", logicTag: "" }, { text: "Raja Ravi Varma", type: "concept_error", logicTag: "" }, { text: "Rabindranath Tagore", type: "concept_error", logicTag: "" }, { text: "Nandalal Bose", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "2", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch2_collective_belonging", questionText: "The idea of collective belonging arose from:", options: [{ text: "Shared history, culture, and symbols", type: "correct", logicTag: "" }, { text: "British colonial laws", type: "concept_error", logicTag: "" }, { text: "Religious conversions", type: "concept_error", logicTag: "" }, { text: "Military victories", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "2", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch2_collective_belonging", questionText: "Folklore and folk songs were revived during the nationalist movement to:", options: [{ text: "Recover a shared cultural heritage", type: "correct", logicTag: "" }, { text: "Promote western culture", type: "concept_error", logicTag: "" }, { text: "Spread literacy", type: "concept_error", logicTag: "" }, { text: "Encourage industrialisation", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "2", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch2_collective_belonging", questionText: "Which animal became a symbol of the Indian nation on the Congress flag?", options: [{ text: "No animal; the charkha was the symbol", type: "correct", logicTag: "" }, { text: "Lion", type: "concept_error", logicTag: "" }, { text: "Elephant", type: "concept_error", logicTag: "" }, { text: "Bull", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "2", isAIGenerated: true, difficultyScore: 0.8 },
  { topic: "sst_ch2_collective_belonging", questionText: "The map of India as a symbol of nationalism was popularised through:", options: [{ text: "Printed images and calendar art", type: "correct", logicTag: "" }, { text: "Official government notices", type: "concept_error", logicTag: "" }, { text: "British surveys only", type: "concept_error", logicTag: "" }, { text: "School textbooks only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "2", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch3_premodern_world
  { topic: "sst_ch3_premodern_world", questionText: "Silk routes connected which two major regions?", options: [{ text: "China and the Mediterranean (Europe)", type: "correct", logicTag: "" }, { text: "India and Africa", type: "concept_error", logicTag: "" }, { text: "Arabia and the Americas", type: "concept_error", logicTag: "" }, { text: "Russia and East Asia", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_premodern_world", questionText: "The cowrie shells used as currency in the pre-modern world originated from:", options: [{ text: "Maldives/Indian Ocean", type: "correct", logicTag: "" }, { text: "Mediterranean Sea", type: "concept_error", logicTag: "" }, { text: "Pacific Islands", type: "concept_error", logicTag: "" }, { text: "Red Sea", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_premodern_world", questionText: "Potato, soya, groundnut arrived in Europe and Asia from:", options: [{ text: "Americas", type: "correct", logicTag: "" }, { text: "Africa", type: "concept_error", logicTag: "" }, { text: "India", type: "concept_error", logicTag: "" }, { text: "China", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_premodern_world", questionText: "Which disease killed 75 million people in 14th-century Europe?", options: [{ text: "Bubonic Plague (Black Death)", type: "correct", logicTag: "" }, { text: "Smallpox", type: "concept_error", logicTag: "" }, { text: "Cholera", type: "concept_error", logicTag: "" }, { text: "Influenza", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_premodern_world", questionText: "Christopher Columbus reached the Americas in:", options: [{ text: "1492", type: "correct", logicTag: "" }, { text: "1498", type: "concept_error", logicTag: "" }, { text: "1510", type: "concept_error", logicTag: "" }, { text: "1480", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_premodern_world", questionText: "The pre-modern world trade was characterised by:", options: [{ text: "Movement of goods, people and diseases across vast distances", type: "correct", logicTag: "" }, { text: "Only local barter trade", type: "concept_error", logicTag: "" }, { text: "Sea routes only", type: "concept_error", logicTag: "" }, { text: "State-controlled monopoly only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_premodern_world", questionText: "Vasco da Gama discovered the sea route to India in:", options: [{ text: "1498", type: "correct", logicTag: "" }, { text: "1492", type: "concept_error", logicTag: "" }, { text: "1510", type: "concept_error", logicTag: "" }, { text: "1520", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_premodern_world", questionText: "The term 'globalisation' as an economic phenomenon is rooted in:", options: [{ text: "Pre-modern silk and trade routes", type: "correct", logicTag: "" }, { text: "World War I", type: "concept_error", logicTag: "" }, { text: "Internet revolution", type: "concept_error", logicTag: "" }, { text: "Industrial Revolution only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch3_interwar_economy
  { topic: "sst_ch3_interwar_economy", questionText: "The Great Depression began in:", options: [{ text: "1929", type: "correct", logicTag: "" }, { text: "1919", type: "concept_error", logicTag: "" }, { text: "1935", type: "concept_error", logicTag: "" }, { text: "1925", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_interwar_economy", questionText: "The stock market crash of 1929 occurred at:", options: [{ text: "Wall Street, New York", type: "correct", logicTag: "" }, { text: "London Stock Exchange", type: "concept_error", logicTag: "" }, { text: "Paris Bourse", type: "concept_error", logicTag: "" }, { text: "Tokyo Stock Exchange", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_interwar_economy", questionText: "The Great Depression was caused primarily by:", options: [{ text: "Overproduction, falling prices and bank failures", type: "correct", logicTag: "" }, { text: "World War I military spending", type: "concept_error", logicTag: "" }, { text: "Oil shortage", type: "concept_error", logicTag: "" }, { text: "Drought and famine", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_interwar_economy", questionText: "The New Deal was introduced by US President:", options: [{ text: "Franklin D. Roosevelt", type: "correct", logicTag: "" }, { text: "Herbert Hoover", type: "concept_error", logicTag: "" }, { text: "Woodrow Wilson", type: "concept_error", logicTag: "" }, { text: "Harry Truman", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_interwar_economy", questionText: "Which country was worst hit by the Great Depression leading to rise of fascism?", options: [{ text: "Germany", type: "correct", logicTag: "" }, { text: "France", type: "concept_error", logicTag: "" }, { text: "Britain", type: "concept_error", logicTag: "" }, { text: "Italy", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_interwar_economy", questionText: "During the interwar period, countries adopted which economic policy?", options: [{ text: "Protectionism and import tariffs", type: "correct", logicTag: "" }, { text: "Free trade", type: "concept_error", logicTag: "" }, { text: "Gold standard expansion", type: "concept_error", logicTag: "" }, { text: "Open borders", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_interwar_economy", questionText: "India's export economy during the Depression was hurt by:", options: [{ text: "Falling prices of agricultural goods in global markets", type: "correct", logicTag: "" }, { text: "Industrial strikes", type: "concept_error", logicTag: "" }, { text: "Monsoon failure", type: "concept_error", logicTag: "" }, { text: "British military campaigns", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_interwar_economy", questionText: "The Bretton Woods system (1944) was established to:", options: [{ text: "Stabilise international currencies and fund reconstruction", type: "correct", logicTag: "" }, { text: "Create a military alliance", type: "concept_error", logicTag: "" }, { text: "Abolish gold standard", type: "concept_error", logicTag: "" }, { text: "Promote colonialism", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.8 },

  // sst_ch3_post_war
  { topic: "sst_ch3_post_war", questionText: "The post-WWII economic order was based on which institution?", options: [{ text: "IMF and World Bank", type: "correct", logicTag: "" }, { text: "League of Nations", type: "concept_error", logicTag: "" }, { text: "NATO", type: "concept_error", logicTag: "" }, { text: "OPEC", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_post_war", questionText: "The Bretton Woods conference was held in:", options: [{ text: "1944", type: "correct", logicTag: "" }, { text: "1945", type: "concept_error", logicTag: "" }, { text: "1947", type: "concept_error", logicTag: "" }, { text: "1950", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_post_war", questionText: "The post-war era saw rapid growth due to:", options: [{ text: "Technology, cheap oil and Bretton Woods stability", type: "correct", logicTag: "" }, { text: "World War II military production only", type: "concept_error", logicTag: "" }, { text: "Colonialism expansion", type: "concept_error", logicTag: "" }, { text: "Soviet aid", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_post_war", questionText: "The US dollar under Bretton Woods was pegged to:", options: [{ text: "Gold at $35 per ounce", type: "correct", logicTag: "" }, { text: "British Pound", type: "concept_error", logicTag: "" }, { text: "French Franc", type: "concept_error", logicTag: "" }, { text: "No fixed commodity", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_post_war", questionText: "The 1970s oil crisis was triggered by:", options: [{ text: "OPEC oil embargo against Western countries", type: "correct", logicTag: "" }, { text: "USâ€“Soviet Cold War", type: "concept_error", logicTag: "" }, { text: "World War III", type: "concept_error", logicTag: "" }, { text: "UK leaving gold standard", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_post_war", questionText: "MNCs began relocating production to developing countries in the 1970s because of:", options: [{ text: "Cheaper labour and lower costs", type: "correct", logicTag: "" }, { text: "Better technology access", type: "concept_error", logicTag: "" }, { text: "Political pressure", type: "concept_error", logicTag: "" }, { text: "Environmental regulations", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch3_post_war", questionText: "Which institution was created to oversee international monetary system post-WWII?", options: [{ text: "International Monetary Fund (IMF)", type: "correct", logicTag: "" }, { text: "World Trade Organisation", type: "concept_error", logicTag: "" }, { text: "United Nations", type: "concept_error", logicTag: "" }, { text: "NATO", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch3_post_war", questionText: "The end of the Bretton Woods fixed exchange rate system occurred in:", options: [{ text: "1971", type: "correct", logicTag: "" }, { text: "1945", type: "concept_error", logicTag: "" }, { text: "1980", type: "concept_error", logicTag: "" }, { text: "1960", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "3", isAIGenerated: true, difficultyScore: 0.8 },

  // sst_ch4_proto_industrialisation
  { topic: "sst_ch4_proto_industrialisation", questionText: "Proto-industrialisation refers to:", options: [{ text: "Large-scale production in rural areas before factories", type: "correct", logicTag: "" }, { text: "Early factory system in cities", type: "concept_error", logicTag: "" }, { text: "Cottage industries in Asia only", type: "concept_error", logicTag: "" }, { text: "Steam-powered machines", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_proto_industrialisation", questionText: "In proto-industrialisation, who organised production?", options: [{ text: "Merchants who supplied raw materials and collected finished goods", type: "correct", logicTag: "" }, { text: "Government factories", type: "concept_error", logicTag: "" }, { text: "Artisan guilds only", type: "concept_error", logicTag: "" }, { text: "Colonial authorities", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_proto_industrialisation", questionText: "The staple exchange and market networks in proto-industrialisation were controlled by:", options: [{ text: "Merchants", type: "correct", logicTag: "" }, { text: "Workers themselves", type: "concept_error", logicTag: "" }, { text: "Government", type: "concept_error", logicTag: "" }, { text: "Landlords", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch4_proto_industrialisation", questionText: "Proto-industrialisation helped merchants because:", options: [{ text: "Production cost was low due to rural wage labour", type: "correct", logicTag: "" }, { text: "Technology was advanced", type: "concept_error", logicTag: "" }, { text: "Workers were slaves", type: "concept_error", logicTag: "" }, { text: "Guilds controlled quality", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_proto_industrialisation", questionText: "A major advantage of the putting-out system was:", options: [{ text: "Merchants bypassed town guild regulations", type: "correct", logicTag: "" }, { text: "Workers earned more money", type: "concept_error", logicTag: "" }, { text: "Quality improved significantly", type: "concept_error", logicTag: "" }, { text: "Factory costs reduced", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_proto_industrialisation", questionText: "The 'Staple' towns in England were:", options: [{ text: "Towns where wool merchants operated through the putting-out system", type: "correct", logicTag: "" }, { text: "Industrial factory towns", type: "concept_error", logicTag: "" }, { text: "Port cities", type: "concept_error", logicTag: "" }, { text: "Mining towns", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.8 },
  { topic: "sst_ch4_proto_industrialisation", questionText: "Proto-industrialisation was replaced by the factory system because:", options: [{ text: "Steam-powered machines made centralised production efficient", type: "correct", logicTag: "" }, { text: "Workers demanded factories", type: "concept_error", logicTag: "" }, { text: "Government mandated factories", type: "concept_error", logicTag: "" }, { text: "Rural areas ran out of workers", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_proto_industrialisation", questionText: "Proto-industrialisation was widespread in:", options: [{ text: "17thâ€“18th century England and Europe", type: "correct", logicTag: "" }, { text: "19th century United States only", type: "concept_error", logicTag: "" }, { text: "Ancient Greece", type: "concept_error", logicTag: "" }, { text: "20th century Asia", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.2 },

  // sst_ch4_factory_system
  { topic: "sst_ch4_factory_system", questionText: "The first cotton mill in England was established in:", options: [{ text: "1815", type: "concept_error", logicTag: "" }, { text: "1772", type: "concept_error", logicTag: "" }, { text: "1730", type: "correct", logicTag: "" }, { text: "1800", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.8 },
  { topic: "sst_ch4_factory_system", questionText: "James Watt's steam engine (1781 improved version) revolutionised:", options: [{ text: "Factory production and transport", type: "correct", logicTag: "" }, { text: "Agriculture only", type: "concept_error", logicTag: "" }, { text: "Shipbuilding only", type: "concept_error", logicTag: "" }, { text: "Mining only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch4_factory_system", questionText: "Early factory workers were mainly:", options: [{ text: "Rural migrants and women and children", type: "correct", logicTag: "" }, { text: "Skilled guild craftsmen", type: "concept_error", logicTag: "" }, { text: "Government employees", type: "concept_error", logicTag: "" }, { text: "Merchant families", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_factory_system", questionText: "The Luddite movement (early 19th century) was a protest against:", options: [{ text: "Machines replacing skilled workers", type: "correct", logicTag: "" }, { text: "Low food prices", type: "concept_error", logicTag: "" }, { text: "Colonial trade", type: "concept_error", logicTag: "" }, { text: "Voting rights", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_factory_system", questionText: "Factory owners preferred child labour because:", options: [{ text: "Children were paid lower wages and could work in small spaces", type: "correct", logicTag: "" }, { text: "Children were more skilled", type: "concept_error", logicTag: "" }, { text: "Adults refused to work", type: "concept_error", logicTag: "" }, { text: "Children needed education", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_factory_system", questionText: "The factory system brought advantages of:", options: [{ text: "Standardised production, efficiency and reduced costs", type: "correct", logicTag: "" }, { text: "Better worker welfare", type: "concept_error", logicTag: "" }, { text: "Handmade quality products", type: "concept_error", logicTag: "" }, { text: "Decentralised production", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_factory_system", questionText: "Manchester became famous in 19th century for:", options: [{ text: "Cotton textile factories", type: "correct", logicTag: "" }, { text: "Steel production", type: "concept_error", logicTag: "" }, { text: "Shipbuilding", type: "concept_error", logicTag: "" }, { text: "Coal mining", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch4_factory_system", questionText: "The spinning jenny was invented by:", options: [{ text: "James Hargreaves", type: "correct", logicTag: "" }, { text: "James Watt", type: "concept_error", logicTag: "" }, { text: "Richard Arkwright", type: "concept_error", logicTag: "" }, { text: "Thomas Edison", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch4_india_industrialisation
  { topic: "sst_ch4_india_industrialisation", questionText: "The first cotton mill in India was set up in Bombay in:", options: [{ text: "1854", type: "correct", logicTag: "" }, { text: "1875", type: "concept_error", logicTag: "" }, { text: "1900", type: "concept_error", logicTag: "" }, { text: "1840", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch4_india_industrialisation", questionText: "The first jute mill in India was set up in:", options: [{ text: "Rishra near Calcutta", type: "correct", logicTag: "" }, { text: "Bombay", type: "concept_error", logicTag: "" }, { text: "Madras", type: "concept_error", logicTag: "" }, { text: "Surat", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_india_industrialisation", questionText: "Indian industrialisation was hindered primarily by:", options: [{ text: "British colonial policies favouring imports over Indian industry", type: "correct", logicTag: "" }, { text: "Lack of raw materials", type: "concept_error", logicTag: "" }, { text: "Worker strikes", type: "concept_error", logicTag: "" }, { text: "Monsoon failures", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_india_industrialisation", questionText: "The Swadeshi movement encouraged Indians to:", options: [{ text: "Buy Indian-made goods and boycott British imports", type: "correct", logicTag: "" }, { text: "Set up factories in Britain", type: "concept_error", logicTag: "" }, { text: "Export cotton to Britain", type: "concept_error", logicTag: "" }, { text: "Adopt British technology only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch4_india_industrialisation", questionText: "Tata Iron and Steel Company (TISCO) was established in:", options: [{ text: "1907", type: "correct", logicTag: "" }, { text: "1900", type: "concept_error", logicTag: "" }, { text: "1920", type: "concept_error", logicTag: "" }, { text: "1885", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_india_industrialisation", questionText: "The colonial government promoted railways in India primarily to:", options: [{ text: "Move raw materials to ports and troops across India", type: "correct", logicTag: "" }, { text: "Develop Indian industry", type: "concept_error", logicTag: "" }, { text: "Connect Indian cities for trade", type: "concept_error", logicTag: "" }, { text: "Serve Indian farmers", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch4_india_industrialisation", questionText: "Indian weavers lost markets in the 19th century because:", options: [{ text: "Cheap machine-made cloth from Britain flooded Indian markets", type: "correct", logicTag: "" }, { text: "Indians stopped wearing cotton", type: "concept_error", logicTag: "" }, { text: "Weavers went on strike", type: "concept_error", logicTag: "" }, { text: "Silk became more popular", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch4_india_industrialisation", questionText: "The Manchester Capitalists opposed import duties on British cloth in India because:", options: [{ text: "They wanted free access to Indian markets", type: "correct", logicTag: "" }, { text: "Indian cloth was cheaper", type: "concept_error", logicTag: "" }, { text: "They wanted to develop Indian industry", type: "concept_error", logicTag: "" }, { text: "Indian workers were skilled", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "4", isAIGenerated: true, difficultyScore: 0.8 },

  // sst_ch5_print_revolution
  { topic: "sst_ch5_print_revolution", questionText: "Johannes Gutenberg invented the printing press around:", options: [{ text: "1448", type: "correct", logicTag: "" }, { text: "1500", type: "concept_error", logicTag: "" }, { text: "1600", type: "concept_error", logicTag: "" }, { text: "1300", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch5_print_revolution", questionText: "Martin Luther's 95 Theses spread rapidly because of:", options: [{ text: "The printing press", type: "correct", logicTag: "" }, { text: "Oral preaching alone", type: "concept_error", logicTag: "" }, { text: "Royal decree", type: "concept_error", logicTag: "" }, { text: "Handwritten copies", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch5_print_revolution", questionText: "The 'print capitalism' concept was introduced by:", options: [{ text: "Benedict Anderson", type: "correct", logicTag: "" }, { text: "Karl Marx", type: "concept_error", logicTag: "" }, { text: "Max Weber", type: "concept_error", logicTag: "" }, { text: "John Stuart Mill", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.8 },
  { topic: "sst_ch5_print_revolution", questionText: "The print revolution created a new reading public by making books:", options: [{ text: "Cheaper and more widely available", type: "correct", logicTag: "" }, { text: "Exclusive to clergy only", type: "concept_error", logicTag: "" }, { text: "Only in Latin", type: "concept_error", logicTag: "" }, { text: "Handwritten and scarce", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch5_print_revolution", questionText: "Vernacular languages in print helped:", options: [{ text: "Wider literacy and nationalism", type: "correct", logicTag: "" }, { text: "Decline of local cultures", type: "concept_error", logicTag: "" }, { text: "Church dominance", type: "concept_error", logicTag: "" }, { text: "Colonial expansion", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch5_print_revolution", questionText: "The earliest printed books in Europe were called:", options: [{ text: "Incunabula", type: "correct", logicTag: "" }, { text: "Manuscripts", type: "concept_error", logicTag: "" }, { text: "Scrolls", type: "concept_error", logicTag: "" }, { text: "Codex", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.8 },
  { topic: "sst_ch5_print_revolution", questionText: "Penny magazines became popular in 19th century Britain because:", options: [{ text: "They were cheap and accessible to working class", type: "correct", logicTag: "" }, { text: "They were published by the government", type: "concept_error", logicTag: "" }, { text: "They used colour printing", type: "concept_error", logicTag: "" }, { text: "They were only for women", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch5_print_revolution", questionText: "The Church feared the printing press because:", options: [{ text: "It spread ideas challenging Church authority", type: "correct", logicTag: "" }, { text: "It was expensive", type: "concept_error", logicTag: "" }, { text: "It promoted paganism", type: "concept_error", logicTag: "" }, { text: "It printed only secular books", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch5_india_print
  { topic: "sst_ch5_india_print", questionText: "The first printing press in India was introduced by:", options: [{ text: "Portuguese missionaries in Goa (16th century)", type: "correct", logicTag: "" }, { text: "British East India Company", type: "concept_error", logicTag: "" }, { text: "Mughal emperors", type: "concept_error", logicTag: "" }, { text: "Dutch traders", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch5_india_print", questionText: "Raja Ram Mohan Roy's Sambad Kaumudi was a:", options: [{ text: "Bengali newspaper promoting social reform", type: "correct", logicTag: "" }, { text: "Hindi religious text", type: "concept_error", logicTag: "" }, { text: "English journal", type: "concept_error", logicTag: "" }, { text: "Urdu magazine", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch5_india_print", questionText: "The Vernacular Press Act (1878) was passed to:", options: [{ text: "Suppress nationalist Indian newspapers", type: "correct", logicTag: "" }, { text: "Promote Indian language printing", type: "concept_error", logicTag: "" }, { text: "Regulate English press", type: "concept_error", logicTag: "" }, { text: "Spread literacy", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch5_india_print", questionText: "Bal Gangadhar Tilak used the newspaper Kesari to:", options: [{ text: "Spread nationalist ideas against British rule", type: "correct", logicTag: "" }, { text: "Promote British culture", type: "concept_error", logicTag: "" }, { text: "Publish scientific articles", type: "concept_error", logicTag: "" }, { text: "Advertise products", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch5_india_print", questionText: "Women's issues in print were addressed by reformers to:", options: [{ text: "Promote women's education and end social evils like sati", type: "correct", logicTag: "" }, { text: "Promote British law", type: "concept_error", logicTag: "" }, { text: "Increase women's factory work", type: "concept_error", logicTag: "" }, { text: "Spread religious texts", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch5_india_print", questionText: "Ulgulan (Rebellion) by Birsa Munda was spread through:", options: [{ text: "Oral traditions and local leaders", type: "correct", logicTag: "" }, { text: "National newspapers", type: "concept_error", logicTag: "" }, { text: "British radio", type: "concept_error", logicTag: "" }, { text: "Telegram messages", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.8 },
  { topic: "sst_ch5_india_print", questionText: "The Deoband seminary in India used print to:", options: [{ text: "Spread Islamic teachings and discuss colonial rule", type: "correct", logicTag: "" }, { text: "Promote British laws", type: "concept_error", logicTag: "" }, { text: "Publish English newspapers", type: "concept_error", logicTag: "" }, { text: "Advance science education", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch5_india_print", questionText: "Literacy rates in colonial India were low because:", options: [{ text: "Education was limited to upper castes and men", type: "correct", logicTag: "" }, { text: "Books were too expensive for government", type: "concept_error", logicTag: "" }, { text: "Indians preferred oral culture", type: "concept_error", logicTag: "" }, { text: "There was no written Indian language", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "5", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch6_types_resources
  { topic: "sst_ch6_types_resources", questionText: "Resources that can be renewed or reproduced are called:", options: [{ text: "Renewable resources", type: "correct", logicTag: "" }, { text: "Non-renewable resources", type: "concept_error", logicTag: "" }, { text: "Biotic resources", type: "concept_error", logicTag: "" }, { text: "Abiotic resources", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_types_resources", questionText: "Coal and petroleum are examples of:", options: [{ text: "Non-renewable resources", type: "correct", logicTag: "" }, { text: "Renewable resources", type: "concept_error", logicTag: "" }, { text: "Biotic resources", type: "concept_error", logicTag: "" }, { text: "Human-made resources", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_types_resources", questionText: "Resources owned by the government are called:", options: [{ text: "National resources", type: "correct", logicTag: "" }, { text: "Individual resources", type: "concept_error", logicTag: "" }, { text: "Community resources", type: "concept_error", logicTag: "" }, { text: "International resources", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_types_resources", questionText: "Resources that are derived from biosphere are:", options: [{ text: "Biotic resources", type: "correct", logicTag: "" }, { text: "Abiotic resources", type: "concept_error", logicTag: "" }, { text: "Renewable resources", type: "concept_error", logicTag: "" }, { text: "Non-renewable resources", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_types_resources", questionText: "Rocks, minerals and metals are examples of:", options: [{ text: "Abiotic resources", type: "correct", logicTag: "" }, { text: "Biotic resources", type: "concept_error", logicTag: "" }, { text: "Renewable resources", type: "concept_error", logicTag: "" }, { text: "Community resources", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_types_resources", questionText: "Agenda 21 was adopted at:", options: [{ text: "Rio Earth Summit, 1992", type: "correct", logicTag: "" }, { text: "Kyoto Protocol, 1997", type: "concept_error", logicTag: "" }, { text: "Paris Agreement, 2015", type: "concept_error", logicTag: "" }, { text: "Stockholm Conference, 1972", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch6_types_resources", questionText: "Resources accessible to all community members are:", options: [{ text: "Community resources", type: "correct", logicTag: "" }, { text: "National resources", type: "concept_error", logicTag: "" }, { text: "Individual resources", type: "concept_error", logicTag: "" }, { text: "International resources", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_types_resources", questionText: "Sustainable development means:", options: [{ text: "Meeting present needs without compromising future generations' ability", type: "correct", logicTag: "" }, { text: "Unlimited industrial growth", type: "concept_error", logicTag: "" }, { text: "Using only non-renewable resources", type: "concept_error", logicTag: "" }, { text: "Stopping all development", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch6_soil_types
  { topic: "sst_ch6_soil_types", questionText: "Which soil is most suitable for cotton cultivation?", options: [{ text: "Black soil (Regur)", type: "correct", logicTag: "" }, { text: "Red soil", type: "concept_error", logicTag: "" }, { text: "Laterite soil", type: "concept_error", logicTag: "" }, { text: "Alluvial soil", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_soil_types", questionText: "Alluvial soil is found mainly in:", options: [{ text: "Northern Plains (Gangetic plains)", type: "correct", logicTag: "" }, { text: "Deccan Plateau", type: "concept_error", logicTag: "" }, { text: "Western Ghats", type: "concept_error", logicTag: "" }, { text: "Thar Desert", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_soil_types", questionText: "Laterite soil is characterised by:", options: [{ text: "Low fertility due to leaching in heavy rainfall areas", type: "correct", logicTag: "" }, { text: "High moisture retention", type: "concept_error", logicTag: "" }, { text: "Rich humus content", type: "concept_error", logicTag: "" }, { text: "Found in river plains", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch6_soil_types", questionText: "The dark colour of black soil is due to:", options: [{ text: "High titaniferous magnetite content", type: "correct", logicTag: "" }, { text: "Iron oxide", type: "concept_error", logicTag: "" }, { text: "Humus", type: "concept_error", logicTag: "" }, { text: "Calcium carbonate", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.8 },
  { topic: "sst_ch6_soil_types", questionText: "Red soil gets its colour from:", options: [{ text: "Diffusion of iron in crystalline and metamorphic rocks", type: "correct", logicTag: "" }, { text: "Organic matter", type: "concept_error", logicTag: "" }, { text: "Moisture content", type: "concept_error", logicTag: "" }, { text: "Clay minerals", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch6_soil_types", questionText: "Soil erosion is caused mainly by:", options: [{ text: "Wind, water and human activities", type: "correct", logicTag: "" }, { text: "Rainfall alone", type: "concept_error", logicTag: "" }, { text: "Earthquakes only", type: "concept_error", logicTag: "" }, { text: "Temperature changes only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_soil_types", questionText: "Contour ploughing helps in:", options: [{ text: "Preventing soil erosion on slopes", type: "correct", logicTag: "" }, { text: "Increasing soil fertility", type: "concept_error", logicTag: "" }, { text: "Increasing water table", type: "concept_error", logicTag: "" }, { text: "Adding minerals to soil", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch6_soil_types", questionText: "Bangar alluvial soil is:", options: [{ text: "Older alluvium, less fertile with kankar nodules", type: "correct", logicTag: "" }, { text: "Newer, highly fertile flood plain soil", type: "concept_error", logicTag: "" }, { text: "Black volcanic soil", type: "concept_error", logicTag: "" }, { text: "Laterite-type soil", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "6", isAIGenerated: true, difficultyScore: 0.8 },

  // sst_ch7_biodiversity
  { topic: "sst_ch7_biodiversity", questionText: "India has how many species of flowering plants approximately?", options: [{ text: "About 47,000", type: "correct", logicTag: "" }, { text: "About 10,000", type: "concept_error", logicTag: "" }, { text: "About 100,000", type: "concept_error", logicTag: "" }, { text: "About 5,000", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_biodiversity", questionText: "The biodiversity of India is due to:", options: [{ text: "Varied climate, relief and soil types", type: "correct", logicTag: "" }, { text: "Large area only", type: "concept_error", logicTag: "" }, { text: "Tropical location only", type: "concept_error", logicTag: "" }, { text: "Heavy rainfall only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_biodiversity", questionText: "Which region of India has the highest biodiversity?", options: [{ text: "Western Ghats and Northeast India", type: "correct", logicTag: "" }, { text: "Thar Desert", type: "concept_error", logicTag: "" }, { text: "Northern Plains", type: "concept_error", logicTag: "" }, { text: "Deccan Plateau", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_biodiversity", questionText: "The main threat to biodiversity in India is:", options: [{ text: "Habitat destruction and deforestation", type: "correct", logicTag: "" }, { text: "Rainfall increase", type: "concept_error", logicTag: "" }, { text: "Temperature decrease", type: "concept_error", logicTag: "" }, { text: "Sea level fall", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch7_biodiversity", questionText: "India has approximately what percentage of world's biodiversity?", options: [{ text: "8%", type: "correct", logicTag: "" }, { text: "2%", type: "concept_error", logicTag: "" }, { text: "20%", type: "concept_error", logicTag: "" }, { text: "15%", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_biodiversity", questionText: "Endemic species are those that:", options: [{ text: "Exist only in a specific geographic region", type: "correct", logicTag: "" }, { text: "Are found globally", type: "concept_error", logicTag: "" }, { text: "Are invasive foreign species", type: "concept_error", logicTag: "" }, { text: "Are domesticated animals", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_biodiversity", questionText: "Which ecosystem has the highest biodiversity on Earth?", options: [{ text: "Tropical rainforests", type: "correct", logicTag: "" }, { text: "Deserts", type: "concept_error", logicTag: "" }, { text: "Polar regions", type: "concept_error", logicTag: "" }, { text: "Temperate grasslands", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch7_biodiversity", questionText: "Keystone species are important because:", options: [{ text: "Their removal drastically alters the ecosystem", type: "correct", logicTag: "" }, { text: "They are the most numerous species", type: "concept_error", logicTag: "" }, { text: "They are the largest animals", type: "concept_error", logicTag: "" }, { text: "They are only found in forests", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch7_conservation
  { topic: "sst_ch7_conservation", questionText: "Project Tiger was launched in India in:", options: [{ text: "1973", type: "correct", logicTag: "" }, { text: "1960", type: "concept_error", logicTag: "" }, { text: "1980", type: "concept_error", logicTag: "" }, { text: "1952", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch7_conservation", questionText: "Biosphere reserves protect:", options: [{ text: "Both biodiversity and cultural traditions of local communities", type: "correct", logicTag: "" }, { text: "Only wild animals", type: "concept_error", logicTag: "" }, { text: "Only forests", type: "concept_error", logicTag: "" }, { text: "Only marine species", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_conservation", questionText: "Wildlife Protection Act in India was passed in:", options: [{ text: "1972", type: "correct", logicTag: "" }, { text: "1960", type: "concept_error", logicTag: "" }, { text: "1985", type: "concept_error", logicTag: "" }, { text: "1950", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_conservation", questionText: "In situ conservation means:", options: [{ text: "Protecting species in their natural habitat", type: "correct", logicTag: "" }, { text: "Protecting species in zoos", type: "concept_error", logicTag: "" }, { text: "Captive breeding programmes", type: "concept_error", logicTag: "" }, { text: "Seed banks", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_conservation", questionText: "Chipko movement was about:", options: [{ text: "Protecting forests by hugging trees to prevent cutting", type: "correct", logicTag: "" }, { text: "Protecting tigers", type: "concept_error", logicTag: "" }, { text: "Water conservation", type: "concept_error", logicTag: "" }, { text: "Soil conservation", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch7_conservation", questionText: "India's national parks are areas where:", options: [{ text: "No human activity is permitted; wildlife is fully protected", type: "correct", logicTag: "" }, { text: "Limited hunting is allowed", type: "concept_error", logicTag: "" }, { text: "Agriculture is permitted", type: "concept_error", logicTag: "" }, { text: "Forests can be logged", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch7_conservation", questionText: "Ex situ conservation includes:", options: [{ text: "Zoos, botanical gardens and seed banks", type: "correct", logicTag: "" }, { text: "National parks", type: "concept_error", logicTag: "" }, { text: "Wildlife sanctuaries", type: "concept_error", logicTag: "" }, { text: "Biosphere reserves", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch7_conservation", questionText: "The Forest Rights Act (2006) aimed to:", options: [{ text: "Recognise rights of tribal communities over forest land", type: "correct", logicTag: "" }, { text: "Open forests for industry", type: "concept_error", logicTag: "" }, { text: "Create new national parks", type: "concept_error", logicTag: "" }, { text: "Ban all forest activities", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "7", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch8_water_scarcity
  { topic: "sst_ch8_water_scarcity", questionText: "Water scarcity means:", options: [{ text: "Insufficient water to meet demand", type: "correct", logicTag: "" }, { text: "Too much rainfall", type: "concept_error", logicTag: "" }, { text: "Water pollution only", type: "concept_error", logicTag: "" }, { text: "Floods", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch8_water_scarcity", questionText: "The main cause of water scarcity in India is:", options: [{ text: "Overuse and unequal distribution of water", type: "correct", logicTag: "" }, { text: "Too little rainfall", type: "concept_error", logicTag: "" }, { text: "Sea water intrusion only", type: "concept_error", logicTag: "" }, { text: "No rivers", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch8_water_scarcity", questionText: "Water availability per person is reduced by:", options: [{ text: "Population growth and economic development", type: "correct", logicTag: "" }, { text: "Better irrigation", type: "concept_error", logicTag: "" }, { text: "Forest growth", type: "concept_error", logicTag: "" }, { text: "River management", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch8_water_scarcity", questionText: "The multi-purpose river valley projects were built to:", options: [{ text: "Irrigation, flood control, electricity and water supply", type: "correct", logicTag: "" }, { text: "Only generate electricity", type: "concept_error", logicTag: "" }, { text: "Only control floods", type: "concept_error", logicTag: "" }, { text: "Only supply drinking water", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch8_water_scarcity", questionText: "Bhakra Nangal dam is built on which river?", options: [{ text: "Sutlej", type: "correct", logicTag: "" }, { text: "Ganga", type: "concept_error", logicTag: "" }, { text: "Yamuna", type: "concept_error", logicTag: "" }, { text: "Brahmaputra", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch8_water_scarcity", questionText: "Which state in India adopted rainwater harvesting in building bylaws?", options: [{ text: "Tamil Nadu", type: "correct", logicTag: "" }, { text: "Kerala", type: "concept_error", logicTag: "" }, { text: "Rajasthan", type: "concept_error", logicTag: "" }, { text: "Maharashtra", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch8_water_scarcity", questionText: "Sardar Sarovar dam is located on which river?", options: [{ text: "Narmada", type: "correct", logicTag: "" }, { text: "Godavari", type: "concept_error", logicTag: "" }, { text: "Krishna", type: "concept_error", logicTag: "" }, { text: "Kaveri", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch8_water_scarcity", questionText: "Over-extraction of groundwater leads to:", options: [{ text: "Falling water table and land subsidence", type: "correct", logicTag: "" }, { text: "Flood risk increase", type: "concept_error", logicTag: "" }, { text: "Increase in river flow", type: "concept_error", logicTag: "" }, { text: "Better soil quality", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch8_rainwater_harvesting
  { topic: "sst_ch8_rainwater_harvesting", questionText: "Khadins and Johads are traditional water harvesting systems found in:", options: [{ text: "Rajasthan", type: "correct", logicTag: "" }, { text: "Kerala", type: "concept_error", logicTag: "" }, { text: "Assam", type: "concept_error", logicTag: "" }, { text: "Tamil Nadu", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch8_rainwater_harvesting", questionText: "Bamboo drip irrigation is used in:", options: [{ text: "Meghalaya", type: "correct", logicTag: "" }, { text: "Gujarat", type: "concept_error", logicTag: "" }, { text: "Punjab", type: "concept_error", logicTag: "" }, { text: "Bihar", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch8_rainwater_harvesting", questionText: "Guls and Kuls are traditional water channels found in:", options: [{ text: "Western Himalayas", type: "correct", logicTag: "" }, { text: "Eastern India", type: "concept_error", logicTag: "" }, { text: "Deccan Plateau", type: "concept_error", logicTag: "" }, { text: "Southern India", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch8_rainwater_harvesting", questionText: "Rainwater harvesting helps in:", options: [{ text: "Recharging groundwater and reducing runoff", type: "correct", logicTag: "" }, { text: "Increasing rainfall", type: "concept_error", logicTag: "" }, { text: "Creating new rivers", type: "concept_error", logicTag: "" }, { text: "Reducing air pollution", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch8_rainwater_harvesting", questionText: "Tanks and stepwells for water storage were traditional systems mainly in:", options: [{ text: "Peninsular India", type: "correct", logicTag: "" }, { text: "North-East India", type: "concept_error", logicTag: "" }, { text: "Himalayan region", type: "concept_error", logicTag: "" }, { text: "Western coast", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch8_rainwater_harvesting", questionText: "The rooftop rainwater harvesting system collects water from:", options: [{ text: "Building rooftops to store in underground tanks", type: "correct", logicTag: "" }, { text: "Rivers", type: "concept_error", logicTag: "" }, { text: "Ponds", type: "concept_error", logicTag: "" }, { text: "Underground springs", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch8_rainwater_harvesting", questionText: "Zabo system of water harvesting is practised in:", options: [{ text: "Nagaland", type: "correct", logicTag: "" }, { text: "Rajasthan", type: "concept_error", logicTag: "" }, { text: "Gujarat", type: "concept_error", logicTag: "" }, { text: "Tamil Nadu", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "hard", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.8 },
  { topic: "sst_ch8_rainwater_harvesting", questionText: "The primary benefit of traditional water harvesting structures is:", options: [{ text: "Local water availability during dry seasons", type: "correct", logicTag: "" }, { text: "Electricity generation", type: "concept_error", logicTag: "" }, { text: "Flood prevention in cities", type: "concept_error", logicTag: "" }, { text: "Navigation", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "8", isAIGenerated: true, difficultyScore: 0.2 },

  // sst_ch9_types_farming
  { topic: "sst_ch9_types_farming", questionText: "Subsistence farming means:", options: [{ text: "Farming for self-consumption with little or no surplus", type: "correct", logicTag: "" }, { text: "Farming for export only", type: "concept_error", logicTag: "" }, { text: "Large-scale commercial farming", type: "concept_error", logicTag: "" }, { text: "Government-controlled farming", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch9_types_farming", questionText: "Plantation agriculture is characterised by:", options: [{ text: "Single crop grown on large estates for export", type: "correct", logicTag: "" }, { text: "Multiple food crops for local use", type: "concept_error", logicTag: "" }, { text: "Small family farms", type: "concept_error", logicTag: "" }, { text: "Organic farming", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch9_types_farming", questionText: "Primitive subsistence farming includes:", options: [{ text: "Shifting cultivation and nomadic herding", type: "correct", logicTag: "" }, { text: "Canal irrigation and HYV seeds", type: "concept_error", logicTag: "" }, { text: "Greenhouse farming", type: "concept_error", logicTag: "" }, { text: "Hydroponic farming", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch9_types_farming", questionText: "Commercial farming uses:", options: [{ text: "Higher doses of inputs like fertilisers, HYV seeds and machines", type: "correct", logicTag: "" }, { text: "Only traditional tools", type: "concept_error", logicTag: "" }, { text: "No irrigation", type: "concept_error", logicTag: "" }, { text: "Organic methods only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch9_types_farming", questionText: "Intensive subsistence farming is practised in:", options: [{ text: "Densely populated areas with small landholdings", type: "correct", logicTag: "" }, { text: "Sparsely populated desert regions", type: "concept_error", logicTag: "" }, { text: "Large commercial farms in USA", type: "concept_error", logicTag: "" }, { text: "Arctic regions", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch9_types_farming", questionText: "Mixed farming involves:", options: [{ text: "Cultivation of crops and rearing of animals together", type: "correct", logicTag: "" }, { text: "Only crop production", type: "concept_error", logicTag: "" }, { text: "Two crops grown in rotation only", type: "concept_error", logicTag: "" }, { text: "Sea and land farming", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch9_types_farming", questionText: "Tea and coffee are grown under which type of farming?", options: [{ text: "Plantation farming", type: "correct", logicTag: "" }, { text: "Subsistence farming", type: "concept_error", logicTag: "" }, { text: "Shifting cultivation", type: "concept_error", logicTag: "" }, { text: "Dry farming", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch9_types_farming", questionText: "Jhumming is the local name for shifting cultivation in:", options: [{ text: "Northeast India", type: "correct", logicTag: "" }, { text: "Rajasthan", type: "concept_error", logicTag: "" }, { text: "Punjab", type: "concept_error", logicTag: "" }, { text: "Kerala", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch9_tech_reforms
  { topic: "sst_ch9_tech_reforms", questionText: "The Green Revolution in India introduced:", options: [{ text: "High Yielding Variety (HYV) seeds for wheat and rice", type: "correct", logicTag: "" }, { text: "Organic farming methods", type: "concept_error", logicTag: "" }, { text: "Shifting cultivation", type: "concept_error", logicTag: "" }, { text: "Dryland farming only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch9_tech_reforms", questionText: "The Green Revolution was most successful in:", options: [{ text: "Punjab, Haryana and western UP", type: "correct", logicTag: "" }, { text: "Northeast India", type: "concept_error", logicTag: "" }, { text: "Rajasthan and Gujarat", type: "concept_error", logicTag: "" }, { text: "Kerala and Tamil Nadu", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch9_tech_reforms", questionText: "A negative impact of the Green Revolution was:", options: [{ text: "Overuse of chemical fertilisers causing soil degradation", type: "correct", logicTag: "" }, { text: "Decrease in crop yields", type: "concept_error", logicTag: "" }, { text: "Reduction in irrigation", type: "concept_error", logicTag: "" }, { text: "Decline in wheat production", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch9_tech_reforms", questionText: "Land reforms in India after independence included:", options: [{ text: "Abolition of zamindari and ceiling on land holdings", type: "correct", logicTag: "" }, { text: "Land given to foreign companies", type: "concept_error", logicTag: "" }, { text: "Privatisation of all farmland", type: "concept_error", logicTag: "" }, { text: "Forced collectivisation", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch9_tech_reforms", questionText: "Operation Flood in India was related to:", options: [{ text: "Increasing milk production (White Revolution)", type: "correct", logicTag: "" }, { text: "Flood control", type: "concept_error", logicTag: "" }, { text: "Irrigation expansion", type: "concept_error", logicTag: "" }, { text: "Fish production", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch9_tech_reforms", questionText: "Consolidation of landholdings means:", options: [{ text: "Merging small scattered plots into larger, contiguous farms", type: "correct", logicTag: "" }, { text: "Distributing land to landless farmers", type: "concept_error", logicTag: "" }, { text: "Building irrigation canals", type: "concept_error", logicTag: "" }, { text: "Planting forests on farmland", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch9_tech_reforms", questionText: "NABARD (National Bank for Agriculture and Rural Development) was set up to:", options: [{ text: "Provide credit and support for rural development", type: "correct", logicTag: "" }, { text: "Export agricultural goods", type: "concept_error", logicTag: "" }, { text: "Build dams", type: "concept_error", logicTag: "" }, { text: "Regulate food prices", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch9_tech_reforms", questionText: "The Minimum Support Price (MSP) system was introduced to:", options: [{ text: "Protect farmers from price crashes by guaranteeing minimum prices", type: "correct", logicTag: "" }, { text: "Fix maximum price for consumers", type: "concept_error", logicTag: "" }, { text: "Reduce food imports", type: "concept_error", logicTag: "" }, { text: "Increase land productivity", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "9", isAIGenerated: true, difficultyScore: 0.5 },

  // sst_ch10_minerals
  { topic: "sst_ch10_minerals", questionText: "Which mineral is found in the Gondwana coal fields of India?", options: [{ text: "Coal", type: "correct", logicTag: "" }, { text: "Bauxite", type: "concept_error", logicTag: "" }, { text: "Copper", type: "concept_error", logicTag: "" }, { text: "Gold", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "10", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch10_minerals", questionText: "Iron ore is mainly found in India in:", options: [{ text: "Jharkhand, Odisha, Chhattisgarh and Karnataka", type: "correct", logicTag: "" }, { text: "Punjab and Haryana", type: "concept_error", logicTag: "" }, { text: "Kerala and Tamil Nadu", type: "concept_error", logicTag: "" }, { text: "Rajasthan only", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "10", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch10_minerals", questionText: "Minerals are classified as metallic and non-metallic. Mica is:", options: [{ text: "Non-metallic mineral", type: "correct", logicTag: "" }, { text: "Metallic mineral", type: "concept_error", logicTag: "" }, { text: "Fossil fuel", type: "concept_error", logicTag: "" }, { text: "Radioactive mineral", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "10", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch10_minerals", questionText: "Bauxite is used to manufacture:", options: [{ text: "Aluminium", type: "correct", logicTag: "" }, { text: "Steel", type: "concept_error", logicTag: "" }, { text: "Copper wire", type: "concept_error", logicTag: "" }, { text: "Glass", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "10", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch10_minerals", questionText: "Which state has the largest reserves of iron ore in India?", options: [{ text: "Odisha", type: "correct", logicTag: "" }, { text: "Rajasthan", type: "concept_error", logicTag: "" }, { text: "Kerala", type: "concept_error", logicTag: "" }, { text: "Punjab", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "10", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch10_minerals", questionText: "Minerals are non-renewable because:", options: [{ text: "They take millions of years to form and cannot be renewed quickly", type: "correct", logicTag: "" }, { text: "They are found only in oceans", type: "concept_error", logicTag: "" }, { text: "They dissolve in water", type: "concept_error", logicTag: "" }, { text: "They are found only underground", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "10", isAIGenerated: true, difficultyScore: 0.2 },
  { topic: "sst_ch10_minerals", questionText: "Copper ore in India is mainly found in:", options: [{ text: "Singhbhum (Jharkhand) and Rajasthan", type: "correct", logicTag: "" }, { text: "Bihar and UP", type: "concept_error", logicTag: "" }, { text: "Kerala and Karnataka", type: "concept_error", logicTag: "" }, { text: "Punjab and Haryana", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "medium", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "10", isAIGenerated: true, difficultyScore: 0.5 },
  { topic: "sst_ch10_minerals", questionText: "Conservation of minerals is needed because:", options: [{ text: "Mineral reserves are finite and overuse leads to depletion", type: "correct", logicTag: "" }, { text: "Minerals are renewable resources", type: "concept_error", logicTag: "" }, { text: "Mining is banned in India", type: "concept_error", logicTag: "" }, { text: "Minerals cause pollution", type: "concept_error", logicTag: "" }], questionType: "mcq", difficulty: "easy", grade: "10", examBoard: "CBSE", subject: "Social Science", chapter: "10", isAIGenerated: true, difficultyScore: 0.2 },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  let created = 0;
  for (const q of questions) {
    await Question.create(q);
    created++;
  }
  console.log(`âœ… SST Missing Questions: ${created} created`);
  await mongoose.disconnect();
}

run().catch((e) => { console.error(e); process.exit(1); });

