import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math4_ch13_perimeter_intro — 8 Qs
  { questionId:"math4_ch13_pi_q1", topicId:"math4_ch13_perimeter_intro", text:"Perimeter is the total distance…", options:[{text:"Inside a shape",type:"concept_error"},{text:"Around a closed shape",type:"correct"},{text:"Across diagonally",type:"misinterpretation"},{text:"Of the centre",type:"calculation_error"}], explanation:"Perimeter = sum of side lengths (around shape).", solutionSteps:["Add all sides.","Perimeter = boundary length."], shortcut:"Perimeter = around.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_pi_q2", topicId:"math4_ch13_perimeter_intro", text:"Rectangle 5 × 3. Perimeter?", options:[{text:"8",type:"calculation_error"},{text:"15",type:"misinterpretation"},{text:"16",type:"correct"},{text:"30",type:"calculation_error"}], explanation:"5 + 3 + 5 + 3 = 16.", solutionSteps:["P = 2(l + w) = 2(5+3) = 16."], shortcut:"P = 2(l+w).", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_pi_q3", topicId:"math4_ch13_perimeter_intro", text:"Triangle sides 3, 4, 5. Perimeter?", options:[{text:"12",type:"correct"},{text:"15",type:"calculation_error"},{text:"7",type:"calculation_error"},{text:"60",type:"misinterpretation"}], explanation:"3 + 4 + 5 = 12.", solutionSteps:["Add all sides: 3+4+5 = 12."], shortcut:"Add all sides.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_pi_q4", topicId:"math4_ch13_perimeter_intro", text:"Square side 7. Perimeter?", options:[{text:"14",type:"calculation_error"},{text:"21",type:"calculation_error"},{text:"28",type:"correct"},{text:"49",type:"misinterpretation"}], explanation:"4 × 7 = 28.", solutionSteps:["P = 4s = 4 × 7 = 28."], shortcut:"4 × side.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_pi_q5", topicId:"math4_ch13_perimeter_intro", text:"To fence a garden, you need to know the…", options:[{text:"Area",type:"concept_error"},{text:"Perimeter",type:"correct"},{text:"Volume",type:"misinterpretation"},{text:"Diagonal",type:"calculation_error"}], explanation:"Fence goes around = perimeter.", solutionSteps:["Fence = around.","Perimeter measures around."], shortcut:"Fence = perimeter.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_pi_q6", topicId:"math4_ch13_perimeter_intro", text:"Perimeter is measured in…", options:[{text:"Sq units",type:"concept_error"},{text:"Length units (cm, m)",type:"correct"},{text:"Volume units",type:"misinterpretation"},{text:"Weight units",type:"calculation_error"}], explanation:"Perimeter = length, in cm, m, etc.", solutionSteps:["Perimeter = distance.","Use length units."], shortcut:"Length units.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_pi_q7", topicId:"math4_ch13_perimeter_intro", text:"For an irregular shape, perimeter = ?", options:[{text:"Just one side",type:"concept_error"},{text:"Sum of all sides",type:"correct"},{text:"Largest side",type:"misinterpretation"},{text:"Half perimeter",type:"calculation_error"}], explanation:"Add all sides for any closed shape.", solutionSteps:["Add every side.","Sum = perimeter."], shortcut:"Sum sides for any shape.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_pi_q8", topicId:"math4_ch13_perimeter_intro", text:"Rectangle 10 × 4. Perimeter?", options:[{text:"14",type:"calculation_error"},{text:"28",type:"correct"},{text:"40",type:"misinterpretation"},{text:"24",type:"calculation_error"}], explanation:"2(10 + 4) = 28.", solutionSteps:["P = 2(l + w).","= 2(10+4) = 28."], shortcut:"P = 2(l+w).", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },

  // math4_ch13_perimeter_shapes — 8 Qs
  { questionId:"math4_ch13_ps_q1", topicId:"math4_ch13_perimeter_shapes", text:"Square side 6 cm. Perimeter?", options:[{text:"12 cm",type:"calculation_error"},{text:"24 cm",type:"correct"},{text:"36 cm",type:"misinterpretation"},{text:"18 cm",type:"calculation_error"}], explanation:"4 × 6 = 24.", solutionSteps:["P = 4s = 4 × 6 = 24 cm."], shortcut:"Square P = 4s.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ps_q2", topicId:"math4_ch13_perimeter_shapes", text:"Rectangle l = 8, w = 5. Perimeter?", options:[{text:"13",type:"calculation_error"},{text:"26",type:"correct"},{text:"40",type:"misinterpretation"},{text:"30",type:"calculation_error"}], explanation:"2(8+5) = 26.", solutionSteps:["P = 2(8+5) = 26."], shortcut:"2(l+w).", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ps_q3", topicId:"math4_ch13_perimeter_shapes", text:"Equilateral triangle side 10. Perimeter?", options:[{text:"20",type:"calculation_error"},{text:"30",type:"correct"},{text:"40",type:"misinterpretation"},{text:"100",type:"calculation_error"}], explanation:"3 × 10 = 30.", solutionSteps:["P = 3s = 3 × 10 = 30."], shortcut:"P = 3s.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ps_q4", topicId:"math4_ch13_perimeter_shapes", text:"Square formula: P = ?", options:[{text:"side²",type:"concept_error"},{text:"4 × side",type:"correct"},{text:"l × w",type:"misinterpretation"},{text:"side + side",type:"calculation_error"}], explanation:"Square: P = 4 × side.", solutionSteps:["4 equal sides.","P = 4s."], shortcut:"P = 4s.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ps_q5", topicId:"math4_ch13_perimeter_shapes", text:"Rectangle formula: P = ?", options:[{text:"l × w",type:"concept_error"},{text:"2(l + w)",type:"correct"},{text:"4 × l",type:"misinterpretation"},{text:"l + w",type:"calculation_error"}], explanation:"Rectangle: P = 2(l + w).", solutionSteps:["2 pairs of equal sides.","P = 2l + 2w = 2(l+w)."], shortcut:"P = 2(l+w).", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ps_q6", topicId:"math4_ch13_perimeter_shapes", text:"Pentagon (regular) side 4 cm. Perimeter?", options:[{text:"16",type:"calculation_error"},{text:"20",type:"correct"},{text:"25",type:"calculation_error"},{text:"15",type:"calculation_error"}], explanation:"5 × 4 = 20.", solutionSteps:["P = 5 × 4 = 20 cm."], shortcut:"5 × side for pentagon.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ps_q7", topicId:"math4_ch13_perimeter_shapes", text:"Hexagon (regular) side 3. Perimeter?", options:[{text:"6",type:"calculation_error"},{text:"18",type:"correct"},{text:"36",type:"calculation_error"},{text:"9",type:"calculation_error"}], explanation:"6 × 3 = 18.", solutionSteps:["P = 6 × 3 = 18."], shortcut:"6 × side for hexagon.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ps_q8", topicId:"math4_ch13_perimeter_shapes", text:"Sq garden side 10 m. Fence costs ₹50/m. Total fence cost?", options:[{text:"₹500",type:"calculation_error"},{text:"₹2000",type:"correct"},{text:"₹4000",type:"calculation_error"},{text:"₹1000",type:"calculation_error"}], explanation:"P = 4 × 10 = 40 m. 40 × 50 = ₹2000.", solutionSteps:["P = 40 m.","Cost = 40 × 50 = 2000."], shortcut:"Compute P, then × cost.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },

  // math4_ch13_area_intro — 8 Qs
  { questionId:"math4_ch13_ai_q1", topicId:"math4_ch13_area_intro", text:"Area is the space…", options:[{text:"Around a shape",type:"concept_error"},{text:"Inside a flat shape",type:"correct"},{text:"Diagonal",type:"misinterpretation"},{text:"Outside",type:"calculation_error"}], explanation:"Area = inside space.", solutionSteps:["Area = inside.","Measured in square units."], shortcut:"Area = inside.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ai_q2", topicId:"math4_ch13_area_intro", text:"Area is measured in…", options:[{text:"cm",type:"concept_error"},{text:"sq cm (cm²)",type:"correct"},{text:"cm³",type:"calculation_error"},{text:"L",type:"misinterpretation"}], explanation:"Area = sq units (cm², m²).", solutionSteps:["Area = 2D space.","Unit: square units."], shortcut:"Square units.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ai_q3", topicId:"math4_ch13_area_intro", text:"Rectangle area = ?", options:[{text:"l + w",type:"concept_error"},{text:"l × w",type:"correct"},{text:"2(l+w)",type:"misinterpretation"},{text:"l − w",type:"calculation_error"}], explanation:"Area of rectangle = length × width.", solutionSteps:["Area = l × w."], shortcut:"l × w.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ai_q4", topicId:"math4_ch13_area_intro", text:"Rectangle 5 × 3. Area?", options:[{text:"8",type:"calculation_error"},{text:"15",type:"correct"},{text:"16",type:"calculation_error"},{text:"30",type:"misinterpretation"}], explanation:"5 × 3 = 15 sq units.", solutionSteps:["Area = l × w = 5 × 3 = 15."], shortcut:"l × w.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ai_q5", topicId:"math4_ch13_area_intro", text:"Square side 5. Area?", options:[{text:"10",type:"calculation_error"},{text:"15",type:"calculation_error"},{text:"20",type:"calculation_error"},{text:"25",type:"correct"}], explanation:"5 × 5 = 25 sq units.", solutionSteps:["Square area = s × s = 5 × 5 = 25."], shortcut:"s².", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ai_q6", topicId:"math4_ch13_area_intro", text:"Area vs perimeter:", options:[{text:"Same thing",type:"concept_error"},{text:"Area = inside; perimeter = around",type:"correct"},{text:"Both around",type:"misinterpretation"},{text:"Both inside",type:"calculation_error"}], explanation:"Area = inside; perimeter = boundary.", solutionSteps:["Area = inside.","Perimeter = around."], shortcut:"Area inside, P around.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ai_q7", topicId:"math4_ch13_area_intro", text:"For painting a wall, the relevant quantity is…", options:[{text:"Perimeter",type:"concept_error"},{text:"Area",type:"correct"},{text:"Diagonal",type:"misinterpretation"},{text:"Volume",type:"calculation_error"}], explanation:"Paint covers area, not perimeter.", solutionSteps:["Paint covers surface = area.","Need area for paint."], shortcut:"Cover = area.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_ai_q8", topicId:"math4_ch13_area_intro", text:"Square area unit:", options:[{text:"cm",type:"concept_error"},{text:"cm²",type:"correct"},{text:"cm³",type:"calculation_error"},{text:"m",type:"misinterpretation"}], explanation:"Area = square units (cm², m², etc.).", solutionSteps:["Area = sq units.","cm × cm = cm²."], shortcut:"sq units.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },

  // math4_ch13_area_squares — 8 Qs
  { questionId:"math4_ch13_as_q1", topicId:"math4_ch13_area_squares", text:"A 4×3 grid shape has area ___ sq units.", options:[{text:"7",type:"calculation_error"},{text:"12",type:"correct"},{text:"14",type:"calculation_error"},{text:"24",type:"misinterpretation"}], explanation:"4 × 3 = 12 squares.", solutionSteps:["4 rows × 3 columns = 12 squares.","Area = 12."], shortcut:"Rows × cols.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_as_q2", topicId:"math4_ch13_area_squares", text:"Count whole + half squares: 3 whole + 4 halves = ?", options:[{text:"5",type:"correct"},{text:"7",type:"calculation_error"},{text:"3",type:"calculation_error"},{text:"4",type:"calculation_error"}], explanation:"3 whole + 4 halves = 3 + 2 = 5.", solutionSteps:["Whole: 3.","Halves: 4 × 0.5 = 2.","Total: 3 + 2 = 5."], shortcut:"Halves add to wholes.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_as_q3", topicId:"math4_ch13_area_squares", text:"A square grid 5×5 has area ___ sq units.", options:[{text:"10",type:"calculation_error"},{text:"15",type:"calculation_error"},{text:"20",type:"calculation_error"},{text:"25",type:"correct"}], explanation:"5 × 5 = 25.", solutionSteps:["25 squares total.","Area = 25 sq units."], shortcut:"5² = 25.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_as_q4", topicId:"math4_ch13_area_squares", text:"To compare areas, count…", options:[{text:"Sides only",type:"concept_error"},{text:"Squares inside",type:"correct"},{text:"Lines",type:"misinterpretation"},{text:"Corners",type:"calculation_error"}], explanation:"More squares = bigger area.", solutionSteps:["Count squares inside.","Compare counts."], shortcut:"Count squares.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_as_q5", topicId:"math4_ch13_area_squares", text:"L-shape: 3+2 squares high, 2 wide. Total squares?", options:[{text:"5",type:"correct"},{text:"6",type:"calculation_error"},{text:"7",type:"calculation_error"},{text:"10",type:"misinterpretation"}], explanation:"Count: 3 stacked + 2 = 5.", solutionSteps:["Count all squares in L-shape.","Total 5."], shortcut:"Count carefully.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_as_q6", topicId:"math4_ch13_area_squares", text:"A triangle covers 2 whole and 2 half squares. Area?", options:[{text:"2",type:"calculation_error"},{text:"3",type:"correct"},{text:"4",type:"calculation_error"},{text:"6",type:"misinterpretation"}], explanation:"2 whole + 2 halves = 2 + 1 = 3.", solutionSteps:["Whole: 2.","Halves: 2 × 0.5 = 1.","Total: 3."], shortcut:"Whole + halves.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_as_q7", topicId:"math4_ch13_area_squares", text:"A 6×6 grid has area ___?", options:[{text:"12",type:"calculation_error"},{text:"36",type:"correct"},{text:"24",type:"calculation_error"},{text:"72",type:"calculation_error"}], explanation:"6 × 6 = 36.", solutionSteps:["36 squares total.","Area = 36 sq units."], shortcut:"6² = 36.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },
  { questionId:"math4_ch13_as_q8", topicId:"math4_ch13_area_squares", text:"Why count squares to find area?", options:[{text:"It's the only way",type:"partial_logic"},{text:"It shows area visually",type:"correct"},{text:"It's harder",type:"misinterpretation"},{text:"For decoration",type:"guessing"}], explanation:"Counting squares makes area concrete and visual.", solutionSteps:["Visual = concrete.","Counts = direct area."], shortcut:"Visual area.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Fields and Fences" },

  // math4_ch14_pictographs — 8 Qs
  { questionId:"math4_ch14_pi_q1", topicId:"math4_ch14_pictographs", text:"Pictograph uses ___ to show data.", options:[{text:"Numbers",type:"concept_error"},{text:"Pictures/symbols",type:"correct"},{text:"Letters",type:"misinterpretation"},{text:"Random shapes",type:"guessing"}], explanation:"Pictographs use symbols, each representing a count.", solutionSteps:["Each symbol = N items (key)."], shortcut:"Pictograph = pictures.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_pi_q2", topicId:"math4_ch14_pictographs", text:"Each ★ = 5. Row has 4 stars = ?", options:[{text:"4",type:"concept_error"},{text:"9",type:"calculation_error"},{text:"20",type:"correct"},{text:"45",type:"calculation_error"}], explanation:"4 × 5 = 20.", solutionSteps:["4 symbols × 5 = 20."], shortcut:"Symbols × key.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_pi_q3", topicId:"math4_ch14_pictographs", text:"Key tells you…", options:[{text:"Name of chart",type:"concept_error"},{text:"What each symbol stands for",type:"correct"},{text:"Total count",type:"misinterpretation"},{text:"Date",type:"calculation_error"}], explanation:"Key = symbol value.", solutionSteps:["Key = symbol → value mapping."], shortcut:"Key = symbol value.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_pi_q4", topicId:"math4_ch14_pictographs", text:"Each ☺ = 10. 3 symbols in dogs row. Dogs count?", options:[{text:"3",type:"concept_error"},{text:"13",type:"calculation_error"},{text:"30",type:"correct"},{text:"100",type:"misinterpretation"}], explanation:"3 × 10 = 30.", solutionSteps:["3 × 10 = 30."], shortcut:"× key.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_pi_q5", topicId:"math4_ch14_pictographs", text:"Each ✿ = 4. To show 20, draw ___ flowers.", options:[{text:"4",type:"calculation_error"},{text:"5",type:"correct"},{text:"16",type:"misinterpretation"},{text:"20",type:"calculation_error"}], explanation:"20 ÷ 4 = 5.", solutionSteps:["20 ÷ 4 = 5 symbols."], shortcut:"Total ÷ key.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_pi_q6", topicId:"math4_ch14_pictographs", text:"Half symbol means…", options:[{text:"Zero",type:"concept_error"},{text:"Half of the key value",type:"correct"},{text:"One",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"½ symbol = ½ × key.", solutionSteps:["Half symbol = half key.","If key=10, half=5."], shortcut:"½ = ½ × key.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_pi_q7", topicId:"math4_ch14_pictographs", text:"Pictograph: apples=5 symbols, mangoes=3, key=2. Total fruits?", options:[{text:"8",type:"calculation_error"},{text:"16",type:"correct"},{text:"15",type:"calculation_error"},{text:"32",type:"calculation_error"}], explanation:"Apples: 5×2=10. Mangoes: 3×2=6. Total: 16.", solutionSteps:["Apples: 5×2=10.","Mangoes: 3×2=6.","Total: 10+6=16."], shortcut:"Sum across rows.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_pi_q8", topicId:"math4_ch14_pictographs", text:"Which category has most? (key=3)\nA: 2 symbols\nB: 4 symbols\nC: 3 symbols", options:[{text:"A",type:"concept_error"},{text:"B",type:"correct"},{text:"C",type:"concept_error"},{text:"All equal",type:"misinterpretation"}], explanation:"B has most symbols → most count.", solutionSteps:["A: 6. B: 12. C: 9.","B is most."], shortcut:"Most symbols = most.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },

  // math4_ch14_bar_graphs — 8 Qs
  { questionId:"math4_ch14_bg_q1", topicId:"math4_ch14_bar_graphs", text:"Taller bar means…", options:[{text:"Smaller count",type:"concept_error"},{text:"Bigger count",type:"correct"},{text:"Same",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"Bar height = count. Taller = bigger.", solutionSteps:["Bar height ∝ count.","Taller bar = more."], shortcut:"Taller = bigger.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_bg_q2", topicId:"math4_ch14_bar_graphs", text:"Bar graph y-axis usually shows…", options:[{text:"Names",type:"concept_error"},{text:"Counts / values",type:"correct"},{text:"Title",type:"misinterpretation"},{text:"Colors",type:"calculation_error"}], explanation:"y-axis = values; x-axis = categories.", solutionSteps:["y-axis: numbers.","x-axis: categories."], shortcut:"y = values.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_bg_q3", topicId:"math4_ch14_bar_graphs", text:"Bars in a bar graph are usually…", options:[{text:"Equal width",type:"correct"},{text:"Different widths",type:"concept_error"},{text:"No width",type:"misinterpretation"},{text:"Triangular",type:"guessing"}], explanation:"Equal widths for fair visual comparison.", solutionSteps:["Equal width = fair comparison.","Only height varies."], shortcut:"Same width.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_bg_q4", topicId:"math4_ch14_bar_graphs", text:"Pets: Dog=10, Cat=8, Fish=5. Tallest bar?", options:[{text:"Cat",type:"concept_error"},{text:"Dog",type:"correct"},{text:"Fish",type:"concept_error"},{text:"Equal",type:"misinterpretation"}], explanation:"Dog (10) > Cat (8) > Fish (5).", solutionSteps:["Compare 10, 8, 5.","Dog is biggest."], shortcut:"Biggest count.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_bg_q5", topicId:"math4_ch14_bar_graphs", text:"y-axis scale: each gridline = 2. Bar at 4 gridlines = ?", options:[{text:"4",type:"concept_error"},{text:"8",type:"correct"},{text:"6",type:"calculation_error"},{text:"2",type:"misinterpretation"}], explanation:"4 × 2 = 8.", solutionSteps:["Gridlines × scale.","4 × 2 = 8."], shortcut:"Gridlines × scale.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_bg_q6", topicId:"math4_ch14_bar_graphs", text:"Two equal-height bars mean…", options:[{text:"Categories are different",type:"concept_error"},{text:"Same count",type:"correct"},{text:"Cannot be compared",type:"misinterpretation"},{text:"Zero count",type:"calculation_error"}], explanation:"Same height = same value.", solutionSteps:["Equal height = same value.","Tie in counts."], shortcut:"Equal = tie.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_bg_q7", topicId:"math4_ch14_bar_graphs", text:"From a bar graph, what's easiest to spot?", options:[{text:"Exact numbers",type:"concept_error"},{text:"Largest and smallest categories",type:"correct"},{text:"Random",type:"misinterpretation"},{text:"Nothing visible",type:"guessing"}], explanation:"Largest/smallest visible by bar heights.", solutionSteps:["Tallest = biggest.","Shortest = smallest."], shortcut:"Visual extremes.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_bg_q8", topicId:"math4_ch14_bar_graphs", text:"Bar graph: A=15, B=10, C=20. Sum?", options:[{text:"35",type:"calculation_error"},{text:"45",type:"correct"},{text:"40",type:"calculation_error"},{text:"50",type:"calculation_error"}], explanation:"15 + 10 + 20 = 45.", solutionSteps:["15+10 = 25.","25+20 = 45."], shortcut:"Sum bar heights.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },

  // math4_ch14_reading_charts — 8 Qs
  { questionId:"math4_ch14_rc_q1", topicId:"math4_ch14_reading_charts", text:"To read a chart, first check the…", options:[{text:"Title and labels",type:"correct"},{text:"Smallest bar",type:"concept_error"},{text:"Only data",type:"misinterpretation"},{text:"Author",type:"guessing"}], explanation:"Title and labels give context first.", solutionSteps:["Title: what data is about.","Labels: axes meaning.","Then read values."], shortcut:"Labels first.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_rc_q2", topicId:"math4_ch14_reading_charts", text:"Table: Day | Books. Mon=3, Tue=5, Wed=2. Wed value?", options:[{text:"5",type:"misinterpretation"},{text:"2",type:"correct"},{text:"10",type:"calculation_error"},{text:"3",type:"misinterpretation"}], explanation:"Read Wed row: 2.", solutionSteps:["Find Wed row.","Read value: 2."], shortcut:"Find row, read value.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_rc_q3", topicId:"math4_ch14_reading_charts", text:"From chart: Mon=3, Tue=5. How many MORE on Tue?", options:[{text:"2",type:"correct"},{text:"8",type:"misinterpretation"},{text:"3",type:"calculation_error"},{text:"15",type:"calculation_error"}], explanation:"5 − 3 = 2.", solutionSteps:["Tue − Mon = 5 − 3 = 2."], shortcut:"Subtract values.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_rc_q4", topicId:"math4_ch14_reading_charts", text:"To compare 2 categories on a chart, look at…", options:[{text:"Just titles",type:"concept_error"},{text:"Bar heights or values",type:"correct"},{text:"Colours",type:"misinterpretation"},{text:"Side text",type:"calculation_error"}], explanation:"Bar heights/values directly compare quantities.", solutionSteps:["Compare bar heights.","Or compare numerical values."], shortcut:"Heights/values compare.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_rc_q5", topicId:"math4_ch14_reading_charts", text:"Chart of birds spotted: Sparrow=12, Crow=8, Pigeon=10. Total?", options:[{text:"20",type:"calculation_error"},{text:"30",type:"correct"},{text:"32",type:"calculation_error"},{text:"40",type:"calculation_error"}], explanation:"12 + 8 + 10 = 30.", solutionSteps:["12 + 8 = 20.","20 + 10 = 30."], shortcut:"Add all categories.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_rc_q6", topicId:"math4_ch14_reading_charts", text:"Which is best for comparing data?", options:[{text:"Just numbers",type:"partial_logic"},{text:"Bar graph (visual)",type:"correct"},{text:"Long paragraph",type:"misinterpretation"},{text:"Random colors",type:"guessing"}], explanation:"Bar graphs make comparison visual.", solutionSteps:["Visual > tabular for comparison.","Heights pop out."], shortcut:"Visual = clearer compare.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_rc_q7", topicId:"math4_ch14_reading_charts", text:"Highest value in chart = tallest bar means…", options:[{text:"Always 100",type:"concept_error"},{text:"Most frequent category",type:"correct"},{text:"Least common",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"Most frequent = highest count = tallest bar.", solutionSteps:["Tallest bar = highest count = most frequent."], shortcut:"Tallest = winner.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_rc_q8", topicId:"math4_ch14_reading_charts", text:"In a table, the column 'Total' usually shows…", options:[{text:"Smallest value",type:"concept_error"},{text:"Sum of all values in row",type:"correct"},{text:"Average",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"Total column = sum of that row.", solutionSteps:["Total = sum across row."], shortcut:"Total = sum.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },

  // math4_ch14_data_collection — 8 Qs
  { questionId:"math4_ch14_dc_q1", topicId:"math4_ch14_data_collection", text:"To collect data, you first…", options:[{text:"Make a chart",type:"concept_error"},{text:"Decide a question",type:"correct"},{text:"Buy paper",type:"misinterpretation"},{text:"Open a book",type:"guessing"}], explanation:"Question first, then data.", solutionSteps:["Decide question.","Collect answers.","Tally and organise."], shortcut:"Question first.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_dc_q2", topicId:"math4_ch14_data_collection", text:"Tally marks |||| represent…", options:[{text:"3",type:"calculation_error"},{text:"4",type:"correct"},{text:"5",type:"calculation_error"},{text:"40",type:"misinterpretation"}], explanation:"4 vertical lines = 4.", solutionSteps:["Count: 4 vertical lines = 4."], shortcut:"4 lines = 4.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_dc_q3", topicId:"math4_ch14_data_collection", text:"Tally for 5 = ?", options:[{text:"|||||",type:"partial_logic"},{text:"|||| with diagonal cross",type:"correct"},{text:"5",type:"misinterpretation"},{text:"V",type:"guessing"}], explanation:"For 5, draw 4 verticals + 1 cross.", solutionSteps:["||||̸ = 5.","Helps count by 5s."], shortcut:"Cross every 5th.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_dc_q4", topicId:"math4_ch14_data_collection", text:"After tallying, organise data in a…", options:[{text:"Paragraph",type:"concept_error"},{text:"Table",type:"correct"},{text:"Pile",type:"misinterpretation"},{text:"Letter",type:"guessing"}], explanation:"Tables organise data clearly.", solutionSteps:["Tally → table.","Then can chart."], shortcut:"Tally → table.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_dc_q5", topicId:"math4_ch14_data_collection", text:"Tally ||||̸ |||| ||| (5 + 4 + 3) = ?", options:[{text:"11",type:"calculation_error"},{text:"12",type:"correct"},{text:"13",type:"calculation_error"},{text:"10",type:"calculation_error"}], explanation:"5 + 4 + 3 = 12.", solutionSteps:["5 + 4 = 9.","9 + 3 = 12."], shortcut:"Sum tally groups.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_dc_q6", topicId:"math4_ch14_data_collection", text:"Why tally instead of just counting up?", options:[{text:"Looks pretty",type:"partial_logic"},{text:"Fast and accurate while counting",type:"correct"},{text:"Required",type:"misinterpretation"},{text:"Random",type:"guessing"}], explanation:"Tally is quick to draw and easy to count after.", solutionSteps:["1 stroke per item.","Group by 5s for fast count."], shortcut:"Tally = quick.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_dc_q7", topicId:"math4_ch14_data_collection", text:"In a survey of 30 students, 12 chose football, 8 cricket. How many chose neither?", options:[{text:"10",type:"correct"},{text:"20",type:"calculation_error"},{text:"22",type:"calculation_error"},{text:"30",type:"misinterpretation"}], explanation:"Neither = 30 − (12 + 8) = 30 − 20 = 10.", solutionSteps:["Total: 30.","Known: 12 + 8 = 20.","Other: 30 − 20 = 10."], shortcut:"Total − known = neither.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
  { questionId:"math4_ch14_dc_q8", topicId:"math4_ch14_data_collection", text:"Steps for data collection:", options:[{text:"Chart first, then collect",type:"concept_error"},{text:"Decide question → ask → tally → organise → chart",type:"correct"},{text:"Random",type:"misinterpretation"},{text:"Only chart",type:"calculation_error"}], explanation:"Logical flow: question → collect → tally → table → chart.", solutionSteps:["1: question.","2: ask.","3: tally.","4: table.","5: chart."], shortcut:"Q → ask → tally → table → chart.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Smart Charts" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 4 Math v2 questions (Ch13-14).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
