import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math4_ch1_brick_patterns — 8 Qs
  { questionId:"math4_ch1_bp_q1", topicId:"math4_ch1_brick_patterns", text:"Why are bricks laid in offset patterns?", options:[{text:"Looks pretty",type:"partial_logic"},{text:"Walls become stronger",type:"correct"},{text:"Uses less brick",type:"misinterpretation"},{text:"Custom requirement",type:"guessing"}], explanation:"Offset bricks lock together, preventing the wall from splitting along vertical joints.", solutionSteps:["Offset = no aligned joints.","Aligned joints crack easily.","Offset adds strength."], shortcut:"Offset = strength.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bp_q2", topicId:"math4_ch1_brick_patterns", text:"In a running bond pattern, each row is shifted by…", options:[{text:"A full brick",type:"concept_error"},{text:"Half a brick",type:"correct"},{text:"A quarter brick",type:"calculation_error"},{text:"Nothing",type:"misinterpretation"}], explanation:"Running bond shifts each row by half a brick.", solutionSteps:["Running bond = half-brick offset.","Standard pattern."], shortcut:"Half-brick offset.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bp_q3", topicId:"math4_ch1_brick_patterns", text:"What happens if all bricks are stacked directly above one another?", options:[{text:"Wall is stronger",type:"concept_error"},{text:"Vertical joints align — wall weakens",type:"correct"},{text:"No difference",type:"misinterpretation"},{text:"Uses fewer bricks",type:"calculation_error"}], explanation:"Stacking with no offset creates aligned vertical joints — easy crack lines.", solutionSteps:["No offset = aligned joints.","Cracks travel straight through.","Wall weaker."], shortcut:"Stacked = weak.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bp_q4", topicId:"math4_ch1_brick_patterns", text:"Which is NOT a brick pattern?", options:[{text:"Running bond",type:"concept_error"},{text:"Herringbone",type:"concept_error"},{text:"Stretcher bond",type:"concept_error"},{text:"Circular bond",type:"correct"}], explanation:"Circular bond is not a real brick pattern.", solutionSteps:["Common patterns: running, stretcher, herringbone, basket-weave.","Circular bond does not exist."], shortcut:"Circular bond is invented.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bp_q5", topicId:"math4_ch1_brick_patterns", text:"Where can you see brick patterns?", options:[{text:"Only in books",type:"concept_error"},{text:"Walls of houses and buildings",type:"correct"},{text:"Only museums",type:"misinterpretation"},{text:"Nowhere",type:"guessing"}], explanation:"Brick patterns are visible on most brick walls.", solutionSteps:["Look at any brick wall.","Notice offset pattern."], shortcut:"Brick walls everywhere.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bp_q6", topicId:"math4_ch1_brick_patterns", text:"Bricks are typically shaped like…", options:[{text:"Spheres",type:"concept_error"},{text:"Cuboids (rectangular blocks)",type:"correct"},{text:"Cones",type:"misinterpretation"},{text:"Cylinders",type:"calculation_error"}], explanation:"Bricks are rectangular cuboids — flat, long, with 6 rectangular faces.", solutionSteps:["Standard brick = cuboid.","6 rectangular faces."], shortcut:"Brick = cuboid.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bp_q7", topicId:"math4_ch1_brick_patterns", text:"In offset pattern, the seam between two bricks below is covered by…", options:[{text:"Nothing",type:"concept_error"},{text:"The middle of a brick above",type:"correct"},{text:"Air",type:"misinterpretation"},{text:"Mortar only",type:"partial_logic"}], explanation:"The brick above is centred over the joint between two bricks below.", solutionSteps:["Brick above sits centred over the joint below.","Locks the wall."], shortcut:"Centre over joint.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bp_q8", topicId:"math4_ch1_brick_patterns", text:"Mortar between bricks is for…", options:[{text:"Decoration",type:"concept_error"},{text:"Binding bricks together",type:"correct"},{text:"Painting",type:"misinterpretation"},{text:"Coolness",type:"guessing"}], explanation:"Mortar glues bricks together so the wall acts as one solid piece.", solutionSteps:["Mortar = the 'glue'.","Holds bricks in place.","Adds strength."], shortcut:"Mortar = brick glue.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },

  // math4_ch1_brick_walls — 8 Qs
  { questionId:"math4_ch1_bw_q1", topicId:"math4_ch1_brick_walls", text:"A wall has 10 bricks per row and 5 rows. Total bricks?", options:[{text:"15",type:"misinterpretation"},{text:"50",type:"correct"},{text:"500",type:"misinterpretation"},{text:"25",type:"calculation_error"}], explanation:"10 × 5 = 50.", solutionSteps:["Per row × rows = total.","10 × 5 = 50."], shortcut:"Per row × rows.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bw_q2", topicId:"math4_ch1_brick_walls", text:"A wall has 8 bricks per row and 12 rows. Total bricks?", options:[{text:"20",type:"misinterpretation"},{text:"96",type:"correct"},{text:"86",type:"calculation_error"},{text:"100",type:"calculation_error"}], explanation:"8 × 12 = 96.", solutionSteps:["8 × 12 = 96."], shortcut:"× rows by per-row.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bw_q3", topicId:"math4_ch1_brick_walls", text:"To find bricks needed, we use…", options:[{text:"Addition",type:"concept_error"},{text:"Multiplication (per row × rows)",type:"correct"},{text:"Subtraction",type:"misinterpretation"},{text:"Division",type:"calculation_error"}], explanation:"Bricks per row × number of rows = total.", solutionSteps:["Rows × per row = total."], shortcut:"× for rectangular arrays.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bw_q4", topicId:"math4_ch1_brick_walls", text:"A wall needs 200 bricks per row and is 10 rows tall. Total?", options:[{text:"210",type:"misinterpretation"},{text:"2000",type:"correct"},{text:"1900",type:"calculation_error"},{text:"500",type:"calculation_error"}], explanation:"200 × 10 = 2000.", solutionSteps:["200 × 10 = 2000."], shortcut:"× 10 adds a zero.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bw_q5", topicId:"math4_ch1_brick_walls", text:"If 1 brick is missing per row in a 50-brick row wall (10 rows), how many bricks total?", options:[{text:"500",type:"concept_error"},{text:"490",type:"correct"},{text:"450",type:"calculation_error"},{text:"49",type:"misinterpretation"}], explanation:"49 × 10 = 490.", solutionSteps:["49 bricks per row × 10 rows = 490."], shortcut:"Adjust per-row count, then × rows.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bw_q6", topicId:"math4_ch1_brick_walls", text:"A wall has 25 bricks per row, 8 rows. How many bricks?", options:[{text:"33",type:"misinterpretation"},{text:"200",type:"correct"},{text:"100",type:"calculation_error"},{text:"180",type:"calculation_error"}], explanation:"25 × 8 = 200.", solutionSteps:["25 × 8 = 200."], shortcut:"× small numbers fast.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bw_q7", topicId:"math4_ch1_brick_walls", text:"To build a wall of 100 bricks (10 per row), how many rows?", options:[{text:"10",type:"correct"},{text:"100",type:"misinterpretation"},{text:"1000",type:"calculation_error"},{text:"5",type:"calculation_error"}], explanation:"100 ÷ 10 = 10 rows.", solutionSteps:["Total ÷ per row = rows.","100 ÷ 10 = 10."], shortcut:"Total ÷ per row.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bw_q8", topicId:"math4_ch1_brick_walls", text:"Building 4 walls, each 50 bricks: total bricks?", options:[{text:"54",type:"misinterpretation"},{text:"200",type:"correct"},{text:"100",type:"calculation_error"},{text:"54",type:"calculation_error"}], explanation:"4 × 50 = 200.", solutionSteps:["4 walls × 50 = 200 bricks."], shortcut:"Walls × per wall.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },

  // math4_ch1_top_views — 8 Qs
  { questionId:"math4_ch1_tv_q1", topicId:"math4_ch1_top_views", text:"Top view of a brick wall shows…", options:[{text:"A line",type:"concept_error"},{text:"Staggered rectangles in rows",type:"correct"},{text:"Triangles",type:"misinterpretation"},{text:"Circles",type:"guessing"}], explanation:"Top view shows the offset pattern as staggered rectangles.", solutionSteps:["Top view = bird's eye.","Sees the offset pattern."], shortcut:"Top view = offset rectangles.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_tv_q2", topicId:"math4_ch1_top_views", text:"In a top view, each brick appears as a…", options:[{text:"Square",type:"partial_logic"},{text:"Rectangle",type:"correct"},{text:"Triangle",type:"misinterpretation"},{text:"Circle",type:"concept_error"}], explanation:"Bricks viewed from above look like rectangles.", solutionSteps:["Brick top face = rectangle.","Top view = rectangle."], shortcut:"Brick top view = rectangle.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_tv_q3", topicId:"math4_ch1_top_views", text:"Bird's eye view = ___ view.", options:[{text:"Front",type:"concept_error"},{text:"Top",type:"correct"},{text:"Side",type:"misinterpretation"},{text:"Inside",type:"guessing"}], explanation:"Bird's eye = looking from above = top view.", solutionSteps:["Bird above ground = top view."], shortcut:"Bird's eye = top.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_tv_q4", topicId:"math4_ch1_top_views", text:"On a top view of bricks, the joints look like…", options:[{text:"Curves",type:"concept_error"},{text:"Straight lines forming an offset grid",type:"correct"},{text:"Triangles",type:"misinterpretation"},{text:"Random shapes",type:"guessing"}], explanation:"Joints between bricks form an offset (staggered) grid of straight lines.", solutionSteps:["Lines between bricks.","Offset rows = staggered grid."], shortcut:"Joints = straight offset lines.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_tv_q5", topicId:"math4_ch1_top_views", text:"To draw a top view of a 4-row brick wall, you draw…", options:[{text:"4 horizontal rows of offset rectangles",type:"correct"},{text:"4 squares",type:"concept_error"},{text:"1 big rectangle",type:"misinterpretation"},{text:"4 triangles",type:"guessing"}], explanation:"4 horizontal rows show the wall's depth in top view.", solutionSteps:["Each row of bricks = 1 line of rectangles.","4 rows = 4 lines, offset."], shortcut:"4 rows = 4 stacked lines.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_tv_q6", topicId:"math4_ch1_top_views", text:"A top view is useful for…", options:[{text:"Counting how tall the wall is",type:"concept_error"},{text:"Seeing the brick layout pattern clearly",type:"correct"},{text:"Identifying colours",type:"misinterpretation"},{text:"Measuring weight",type:"guessing"}], explanation:"Top view shows the layout pattern best.", solutionSteps:["Top view shows arrangement.","Best for layout questions."], shortcut:"Top view → layout.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_tv_q7", topicId:"math4_ch1_top_views", text:"Which view shows the WIDTH and LENGTH of a wall?", options:[{text:"Front view",type:"partial_logic"},{text:"Top view",type:"correct"},{text:"Inside view",type:"misinterpretation"},{text:"Bottom view",type:"concept_error"}], explanation:"Top view shows the wall's footprint = length × width.", solutionSteps:["Top view = horizontal extent.","Shows length and width."], shortcut:"Footprint = top view.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_tv_q8", topicId:"math4_ch1_top_views", text:"A wall's height is NOT visible from the…", options:[{text:"Front view",type:"concept_error"},{text:"Top view",type:"correct"},{text:"Side view",type:"misinterpretation"},{text:"Any view",type:"guessing"}], explanation:"Top view shows length and width only — not height.", solutionSteps:["Top view = horizontal only.","Height needs front or side view."], shortcut:"Top view ignores height.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },

  // math4_ch1_brick_designs — 8 Qs
  { questionId:"math4_ch1_bd_q1", topicId:"math4_ch1_brick_designs", text:"Herringbone pattern has bricks arranged at…", options:[{text:"All horizontal",type:"concept_error"},{text:"Right angles in a zigzag",type:"correct"},{text:"Random angles",type:"misinterpretation"},{text:"All vertical",type:"guessing"}], explanation:"Herringbone uses bricks at right angles to form a V-shape that repeats.", solutionSteps:["Herringbone = V-shapes.","Right angles between bricks."], shortcut:"Herringbone = zigzag.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bd_q2", topicId:"math4_ch1_brick_designs", text:"Brick designs are made by…", options:[{text:"Random placement",type:"concept_error"},{text:"Repeating a small unit of bricks",type:"correct"},{text:"Just colouring",type:"misinterpretation"},{text:"Cutting bricks",type:"calculation_error"}], explanation:"Designs repeat a small unit of bricks across the surface.", solutionSteps:["Identify the unit.","Repeat the unit."], shortcut:"Design = repeating unit.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bd_q3", topicId:"math4_ch1_brick_designs", text:"Basket-weave pattern looks like…", options:[{text:"A spiral",type:"concept_error"},{text:"Pairs of bricks at right angles",type:"correct"},{text:"Stars",type:"misinterpretation"},{text:"Circles",type:"guessing"}], explanation:"Basket-weave uses pairs of bricks placed at 90° to each other.", solutionSteps:["Pairs of bricks.","Each pair rotated 90° from next."], shortcut:"Basket-weave = pair rotation.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bd_q4", topicId:"math4_ch1_brick_designs", text:"Brick designs are both…", options:[{text:"Decorative only",type:"partial_logic"},{text:"Decorative AND structural",type:"correct"},{text:"Random",type:"misinterpretation"},{text:"Only modern",type:"guessing"}], explanation:"Designs look nice AND affect wall strength.", solutionSteps:["Visual appeal = decorative.","Locking = structural."], shortcut:"Designs serve both purposes.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bd_q5", topicId:"math4_ch1_brick_designs", text:"To find the repeating unit, look for the…", options:[{text:"Biggest piece",type:"concept_error"},{text:"Smallest block that repeats",type:"correct"},{text:"Random brick",type:"misinterpretation"},{text:"Corner only",type:"guessing"}], explanation:"The unit is the smallest piece that repeats over the whole pattern.", solutionSteps:["Identify the smallest repeating block.","That's the unit."], shortcut:"Smallest repeat.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bd_q6", topicId:"math4_ch1_brick_designs", text:"Which is a real brick pattern?", options:[{text:"Stretcher bond",type:"correct"},{text:"Star bond",type:"misinterpretation"},{text:"Triangle bond",type:"concept_error"},{text:"Curve bond",type:"guessing"}], explanation:"Stretcher bond is a common real brick pattern.", solutionSteps:["Real patterns: stretcher, header, English, Flemish.","Star/triangle/curve bonds aren't standard."], shortcut:"Stretcher bond = standard.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bd_q7", topicId:"math4_ch1_brick_designs", text:"English bond alternates between…", options:[{text:"Long and short bricks",type:"correct"},{text:"Red and white bricks",type:"partial_logic"},{text:"Different rooms",type:"misinterpretation"},{text:"Tall and flat",type:"calculation_error"}], explanation:"English bond alternates rows of long bricks (stretchers) and short ends (headers).", solutionSteps:["Row of stretchers (long).","Row of headers (ends).","Alternate."], shortcut:"English = alternating rows.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },
  { questionId:"math4_ch1_bd_q8", topicId:"math4_ch1_brick_designs", text:"To copy a brick design, you should…", options:[{text:"Guess randomly",type:"concept_error"},{text:"Find the unit, then repeat",type:"correct"},{text:"Use random colours",type:"misinterpretation"},{text:"Skip rows",type:"guessing"}], explanation:"Identifying the unit lets you reproduce the pattern reliably.", solutionSteps:["Find smallest repeating block.","Repeat across the surface."], shortcut:"Unit then repeat.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Building with Bricks" },

  // math4_ch2_units_length — 8 Qs
  { questionId:"math4_ch2_ul_q1", topicId:"math4_ch2_units_length", text:"Which unit is BEST for measuring a tiny screw?", options:[{text:"km",type:"concept_error"},{text:"m",type:"misinterpretation"},{text:"cm",type:"partial_logic"},{text:"mm",type:"correct"}], explanation:"A screw is tiny — millimetres are the best unit.", solutionSteps:["Very small = mm.","Screw < 1 cm typically."], shortcut:"Tiny = mm.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ul_q2", topicId:"math4_ch2_units_length", text:"Which unit is BEST for measuring distance between two cities?", options:[{text:"mm",type:"concept_error"},{text:"cm",type:"concept_error"},{text:"m",type:"partial_logic"},{text:"km",type:"correct"}], explanation:"Cities are far — kilometres.", solutionSteps:["Long distances = km.","Hundreds of km between cities."], shortcut:"Far = km.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ul_q3", topicId:"math4_ch2_units_length", text:"Best unit for measuring a tall door?", options:[{text:"mm",type:"concept_error"},{text:"cm",type:"partial_logic"},{text:"m",type:"correct"},{text:"km",type:"misinterpretation"}], explanation:"A door is about 2 m — metres are best.", solutionSteps:["Door ≈ 2 m.","Use m."], shortcut:"Body-sized = m.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ul_q4", topicId:"math4_ch2_units_length", text:"From smallest to largest length unit:", options:[{text:"km, m, cm, mm",type:"concept_error"},{text:"mm, cm, m, km",type:"correct"},{text:"cm, mm, m, km",type:"misinterpretation"},{text:"m, mm, cm, km",type:"guessing"}], explanation:"Order: mm < cm < m < km.", solutionSteps:["mm = smallest.","Then cm, m, km."], shortcut:"mm-cm-m-km.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ul_q5", topicId:"math4_ch2_units_length", text:"1 cm = ? mm", options:[{text:"1",type:"concept_error"},{text:"10",type:"correct"},{text:"100",type:"misinterpretation"},{text:"1000",type:"calculation_error"}], explanation:"By definition: 1 cm = 10 mm.", solutionSteps:["1 cm = 10 mm."], shortcut:"× 10: cm to mm.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ul_q6", topicId:"math4_ch2_units_length", text:"Best unit for finger length?", options:[{text:"mm",type:"partial_logic"},{text:"cm",type:"correct"},{text:"m",type:"misinterpretation"},{text:"km",type:"concept_error"}], explanation:"A finger is about 7-8 cm — cm is best.", solutionSteps:["Finger ≈ 7 cm.","cm = right size."], shortcut:"Small objects = cm.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ul_q7", topicId:"math4_ch2_units_length", text:"100 cm = ? m", options:[{text:"0.1",type:"calculation_error"},{text:"1",type:"correct"},{text:"10",type:"calculation_error"},{text:"100",type:"misinterpretation"}], explanation:"100 cm = 1 m.", solutionSteps:["1 m = 100 cm."], shortcut:"÷ 100: cm to m.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ul_q8", topicId:"math4_ch2_units_length", text:"1 km = ? m", options:[{text:"100",type:"calculation_error"},{text:"1000",type:"correct"},{text:"10",type:"misinterpretation"},{text:"10000",type:"calculation_error"}], explanation:"1 km = 1000 m.", solutionSteps:["1 km = 1000 m."], shortcut:"× 1000: km to m.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },

  // math4_ch2_cm_m_km — 8 Qs
  { questionId:"math4_ch2_ck_q1", topicId:"math4_ch2_cm_m_km", text:"5 m = ? cm", options:[{text:"50",type:"calculation_error"},{text:"500",type:"correct"},{text:"5000",type:"misinterpretation"},{text:"0.05",type:"calculation_error"}], explanation:"5 × 100 = 500 cm.", solutionSteps:["m → cm: × 100.","5 × 100 = 500."], shortcut:"× 100.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ck_q2", topicId:"math4_ch2_cm_m_km", text:"3 km = ? m", options:[{text:"30",type:"calculation_error"},{text:"300",type:"calculation_error"},{text:"3000",type:"correct"},{text:"30000",type:"misinterpretation"}], explanation:"3 × 1000 = 3000 m.", solutionSteps:["km → m: × 1000.","3 × 1000 = 3000."], shortcut:"× 1000.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ck_q3", topicId:"math4_ch2_cm_m_km", text:"500 cm = ? m", options:[{text:"5",type:"correct"},{text:"50",type:"calculation_error"},{text:"0.5",type:"calculation_error"},{text:"5000",type:"misinterpretation"}], explanation:"500 ÷ 100 = 5 m.", solutionSteps:["cm → m: ÷ 100.","500 ÷ 100 = 5."], shortcut:"÷ 100.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ck_q4", topicId:"math4_ch2_cm_m_km", text:"5000 m = ? km", options:[{text:"5",type:"correct"},{text:"50",type:"calculation_error"},{text:"0.5",type:"calculation_error"},{text:"500",type:"misinterpretation"}], explanation:"5000 ÷ 1000 = 5 km.", solutionSteps:["m → km: ÷ 1000.","5000 ÷ 1000 = 5."], shortcut:"÷ 1000.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ck_q5", topicId:"math4_ch2_cm_m_km", text:"2 m 50 cm = ? cm", options:[{text:"205",type:"calculation_error"},{text:"250",type:"correct"},{text:"2050",type:"misinterpretation"},{text:"25",type:"calculation_error"}], explanation:"2 m = 200 cm. + 50 = 250 cm.", solutionSteps:["2 m = 200 cm.","+50 = 250 cm."], shortcut:"Combine.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ck_q6", topicId:"math4_ch2_cm_m_km", text:"1 km 200 m = ? m", options:[{text:"1020",type:"calculation_error"},{text:"1200",type:"correct"},{text:"120",type:"calculation_error"},{text:"12000",type:"misinterpretation"}], explanation:"1 km = 1000 m + 200 m = 1200 m.", solutionSteps:["1 km = 1000 m.","+200 = 1200 m."], shortcut:"Combine.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ck_q7", topicId:"math4_ch2_cm_m_km", text:"To go from cm to mm, you ___ 10.", options:[{text:"Divide by",type:"concept_error"},{text:"Multiply by",type:"correct"},{text:"Subtract",type:"misinterpretation"},{text:"Add",type:"guessing"}], explanation:"1 cm = 10 mm. cm × 10 = mm.", solutionSteps:["1 cm = 10 mm.","Multiply to convert."], shortcut:"× 10 = cm to mm.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_ck_q8", topicId:"math4_ch2_cm_m_km", text:"15 m + 80 cm = ? cm", options:[{text:"1580",type:"correct"},{text:"95",type:"calculation_error"},{text:"230",type:"calculation_error"},{text:"15080",type:"misinterpretation"}], explanation:"15 m = 1500 cm. + 80 cm = 1580 cm.", solutionSteps:["15 m = 1500 cm.","1500 + 80 = 1580."], shortcut:"Convert all to cm, then add.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Long and Short" },

  // math4_ch2_measuring_distance — 8 Qs
  { questionId:"math4_ch2_md_q1", topicId:"math4_ch2_measuring_distance", text:"To measure 100 km, the best tool is…", options:[{text:"Ruler",type:"concept_error"},{text:"Measuring tape",type:"calculation_error"},{text:"Map with scale",type:"correct"},{text:"Hand-span",type:"misinterpretation"}], explanation:"Long distances need a map — too far for a ruler or tape.", solutionSteps:["100 km is huge.","Map scale gives the distance."], shortcut:"Long distances → map.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_md_q2", topicId:"math4_ch2_measuring_distance", text:"A measuring tape typically measures up to…", options:[{text:"1 m",type:"calculation_error"},{text:"30 m",type:"correct"},{text:"1 km",type:"misinterpretation"},{text:"100 km",type:"calculation_error"}], explanation:"Standard measuring tapes go up to ~30 m.", solutionSteps:["Tape: usually 1-30 m.","Beyond that, use a map."], shortcut:"Tape ≈ 30 m max.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_md_q3", topicId:"math4_ch2_measuring_distance", text:"Distance from home to school is 2 km. In metres, this is…", options:[{text:"20 m",type:"calculation_error"},{text:"200 m",type:"calculation_error"},{text:"2000 m",type:"correct"},{text:"20000 m",type:"misinterpretation"}], explanation:"2 × 1000 = 2000 m.", solutionSteps:["2 km × 1000 = 2000 m."], shortcut:"× 1000.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_md_q4", topicId:"math4_ch2_measuring_distance", text:"On a map, the distance between two cities is 250 km. To go and come back, you travel…", options:[{text:"250 km",type:"concept_error"},{text:"500 km",type:"correct"},{text:"1000 km",type:"calculation_error"},{text:"125 km",type:"calculation_error"}], explanation:"To go AND come back = 250 + 250 = 500 km.", solutionSteps:["Each way: 250 km.","2 × 250 = 500 km."], shortcut:"Round trip = × 2.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_md_q5", topicId:"math4_ch2_measuring_distance", text:"1 km is roughly how many steps for an adult?", options:[{text:"100 steps",type:"calculation_error"},{text:"1000 steps",type:"calculation_error"},{text:"1300-1500 steps",type:"correct"},{text:"10000 steps",type:"misinterpretation"}], explanation:"Average adult takes about 1400 steps to cover 1 km.", solutionSteps:["1 step ≈ 70 cm.","1 km = 1000 m = 100000 cm.","100000 ÷ 70 ≈ 1430 steps."], shortcut:"1 km ≈ 1400 steps.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_md_q6", topicId:"math4_ch2_measuring_distance", text:"From A to B is 5 km. From B to C is 3 km. A to B to C total?", options:[{text:"2 km",type:"calculation_error"},{text:"8 km",type:"correct"},{text:"15 km",type:"calculation_error"},{text:"53 km",type:"misinterpretation"}], explanation:"Add: 5 + 3 = 8 km.", solutionSteps:["A→B: 5 km.","B→C: 3 km.","Total: 5+3 = 8 km."], shortcut:"Sum of segments.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_md_q7", topicId:"math4_ch2_measuring_distance", text:"Bhopal to Delhi = 700 km. After 250 km, distance left?", options:[{text:"450 km",type:"correct"},{text:"950 km",type:"misinterpretation"},{text:"500 km",type:"calculation_error"},{text:"350 km",type:"calculation_error"}], explanation:"700 − 250 = 450 km.", solutionSteps:["Left = total − covered.","700 − 250 = 450."], shortcut:"Subtract covered.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_md_q8", topicId:"math4_ch2_measuring_distance", text:"A foot-step ≈ 70 cm. In 1 km, you take about…", options:[{text:"100 steps",type:"calculation_error"},{text:"1400 steps",type:"correct"},{text:"10000 steps",type:"calculation_error"},{text:"70 steps",type:"concept_error"}], explanation:"1 km = 100000 cm. ÷ 70 ≈ 1400 steps.", solutionSteps:["1 km = 100000 cm.","100000 ÷ 70 ≈ 1430 ≈ 1400 steps."], shortcut:"≈ 1400 steps per km.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Long and Short" },

  // math4_ch2_comparing_long — 8 Qs
  { questionId:"math4_ch2_cl_q1", topicId:"math4_ch2_comparing_long", text:"Which is longer: 1 m or 90 cm?", options:[{text:"90 cm",type:"concept_error"},{text:"1 m",type:"correct"},{text:"Equal",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"1 m = 100 cm > 90 cm.", solutionSteps:["1 m = 100 cm.","100 > 90.","1 m is longer."], shortcut:"Convert + compare.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_cl_q2", topicId:"math4_ch2_comparing_long", text:"Which is shortest: 50 cm, 1 m, 80 cm?", options:[{text:"1 m",type:"concept_error"},{text:"80 cm",type:"concept_error"},{text:"50 cm",type:"correct"},{text:"All equal",type:"misinterpretation"}], explanation:"In cm: 1 m = 100, 80, 50. Smallest = 50 cm.", solutionSteps:["Convert: 50, 100, 80.","Smallest = 50 cm."], shortcut:"Smallest converted value wins.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_cl_q3", topicId:"math4_ch2_comparing_long", text:"Bus = 12 m, car = 4 m. Bus is ___ m longer.", options:[{text:"6",type:"calculation_error"},{text:"8",type:"correct"},{text:"16",type:"misinterpretation"},{text:"4",type:"calculation_error"}], explanation:"12 − 4 = 8 m.", solutionSteps:["12 − 4 = 8 m."], shortcut:"Subtract.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_cl_q4", topicId:"math4_ch2_comparing_long", text:"Compare 2 km and 1500 m:", options:[{text:"2 km is shorter",type:"concept_error"},{text:"2 km is longer by 500 m",type:"correct"},{text:"Equal",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"2 km = 2000 m. 2000 − 1500 = 500 m longer.", solutionSteps:["2 km = 2000 m.","2000 − 1500 = 500.","2 km > 1500 m by 500 m."], shortcut:"Convert to same unit.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_cl_q5", topicId:"math4_ch2_comparing_long", text:"Order from shortest to longest: 1 km, 800 m, 1500 cm, 200 m.", options:[{text:"1500 cm, 200 m, 800 m, 1 km",type:"correct"},{text:"1 km, 800 m, 200 m, 1500 cm",type:"concept_error"},{text:"200 m, 800 m, 1500 cm, 1 km",type:"calculation_error"},{text:"1500 cm, 200 m, 1 km, 800 m",type:"calculation_error"}], explanation:"In m: 1500 cm = 15, 200, 800, 1 km = 1000.", solutionSteps:["1500 cm = 15 m.","200 m, 800 m, 1 km = 1000 m.","Order: 15 < 200 < 800 < 1000."], shortcut:"Same unit then sort.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_cl_q6", topicId:"math4_ch2_comparing_long", text:"Train length 200 m, bus length 20 m. Train is ___ times longer.", options:[{text:"2 times",type:"calculation_error"},{text:"10 times",type:"correct"},{text:"100 times",type:"misinterpretation"},{text:"20 times",type:"calculation_error"}], explanation:"200 ÷ 20 = 10.", solutionSteps:["200 ÷ 20 = 10.","Train = 10 × bus."], shortcut:"Divide to find times.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_cl_q7", topicId:"math4_ch2_comparing_long", text:"To compare 50 cm and 0.5 m:", options:[{text:"50 cm bigger",type:"concept_error"},{text:"0.5 m bigger",type:"concept_error"},{text:"Equal",type:"correct"},{text:"Cannot say",type:"guessing"}], explanation:"0.5 m = 50 cm. Equal.", solutionSteps:["0.5 m = 50 cm.","Same value."], shortcut:"½ m = 50 cm.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
  { questionId:"math4_ch2_cl_q8", topicId:"math4_ch2_comparing_long", text:"A pencil 12 cm, a book 24 cm. Book is ___ longer.", options:[{text:"2 times",type:"correct"},{text:"36 cm",type:"misinterpretation"},{text:"12 cm",type:"calculation_error"},{text:"half",type:"concept_error"}], explanation:"24 ÷ 12 = 2. Book is 2 times longer.", solutionSteps:["24 ÷ 12 = 2.","Book = 2 × pencil."], shortcut:"Find ratio: bigger ÷ smaller.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"Long and Short" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 4 Math v2 questions (Ch1-2).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
