/**
 * Seed: CBSE Class 10 Social Science — 30 practice questions
 * Topics: Resources & Development, Forest & Wildlife, Rise of Nationalism in Europe,
 *         Nationalism in India, Development, Money and Credit
 * Safe to re-run — skips duplicates on { questionText, subject }
 *
 * Usage:
 *   cd ai-learning-backend/backend
 *   node config/seedSocialScienceQuestions.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const QUESTIONS = [
  // ── 1. Resources and Development (5 questions) ──────────────────────────────
  {
    topic: "Resources and Development",
    subtopic: "Types of Resources",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Resources that are found in a region but have not been utilised are known as:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Actual Resources", type: "concept_error", logicTag: "used_resources_confused" },
      { text: "Potential Resources", type: "correct", logicTag: "" },
      { text: "Stock", type: "concept_error", logicTag: "tech_not_available_confused" },
      { text: "Reserves", type: "concept_error", logicTag: "can_use_but_not_yet_confused" },
    ],
    solutionSteps: [
      "Potential Resources: known to exist but not yet in use due to lack of technology or economic viability.",
      "Actual Resources: known and currently being used (e.g., coal in Ruhr, Germany).",
      "Stock: resources where technology is unavailable (e.g., hydrogen as energy).",
      "Reserves: subset of stock that can be used with existing technology but are conserved.",
    ],
    shortcut: "Potential = exists but not used yet. Actual = being used. Stock = tech unavailable. Reserve = conserved for future.",
  },
  {
    topic: "Resources and Development",
    subtopic: "Land Use",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The land use data for India is recorded and published by the:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Ministry of Environment, Forest and Climate Change", type: "concept_error", logicTag: "environment_ministry_confused" },
      { text: "Survey of India under the Union Ministry of Science and Technology", type: "correct", logicTag: "" },
      { text: "National Sample Survey Office (NSSO)", type: "concept_error", logicTag: "statistics_body_confused" },
      { text: "National Remote Sensing Centre (NRSC)", type: "concept_error", logicTag: "remote_sensing_agency_confused" },
    ],
    solutionSteps: [
      "Land use data is recorded and maintained by the Survey of India.",
      "Some states also use satellite imagery from NRSC for mapping, but official land-use data = Survey of India.",
      "Land use categories: forests, land under non-agricultural uses, barren land, cultivable waste, pastures, tree crops, fallow, net sown area.",
    ],
    shortcut: "Land use data = Survey of India. Remember the 9 land-use categories for CBSE exams.",
  },
  {
    topic: "Resources and Development",
    subtopic: "Soil Types",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which type of soil is found in the Deccan Plateau and is ideal for growing cotton?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Alluvial soil", type: "concept_error", logicTag: "river_plains_soil_confused" },
      { text: "Black soil (Regur)", type: "correct", logicTag: "" },
      { text: "Red and yellow soil", type: "concept_error", logicTag: "crystalline_rock_soil_confused" },
      { text: "Laterite soil", type: "concept_error", logicTag: "leached_tropical_soil_confused" },
    ],
    solutionSteps: [
      "Black soil (Regur) is found in the Deccan Plateau — Maharashtra, Gujarat, Madhya Pradesh.",
      "It has high moisture retention and is rich in calcium, potassium, and magnesium carbonate.",
      "Ideal for cotton (kala mitti = black gold because of cotton).",
    ],
    shortcut: "Black soil = Deccan Plateau = cotton. Alluvial = Indo-Gangetic plains = wheat/rice. Laterite = Kerala/Assam = tea/coffee.",
  },
  {
    topic: "Resources and Development",
    subtopic: "Resource Conservation",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The concept of 'sustainable development' as described in the Brundtland Commission Report (1987) means:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Stopping all development to preserve nature for future generations", type: "concept_error", logicTag: "no_development_extreme" },
      { text: "Development that meets present needs without compromising future generations' ability to meet their needs", type: "correct", logicTag: "" },
      { text: "Using all available resources now to maximise present growth", type: "concept_error", logicTag: "opposite_definition" },
      { text: "Limiting population growth to reduce resource consumption", type: "concept_error", logicTag: "one_aspect_not_definition" },
    ],
    solutionSteps: [
      "The Brundtland Commission (Our Common Future, 1987) defined sustainable development.",
      "It balances economic growth with environmental protection across generations.",
      "Resources should be used wisely so future generations can also benefit.",
    ],
    shortcut: "Sustainable development = meet present needs without harming future generations. Balance economy + environment.",
  },
  {
    topic: "Resources and Development",
    subtopic: "Resource Classification",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Iron ore and coal are examples of which type of resource?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Renewable resources", type: "concept_error", logicTag: "renewable_confused" },
      { text: "Non-renewable resources", type: "correct", logicTag: "" },
      { text: "Biotic resources", type: "concept_error", logicTag: "living_resource_confused" },
      { text: "International resources", type: "concept_error", logicTag: "ownership_category_confused" },
    ],
    solutionSteps: [
      "Non-renewable resources take millions of years to form and cannot be replenished once used.",
      "Iron ore and coal are fossil/mineral resources — classified as non-renewable.",
      "Renewable resources: solar energy, wind, water, forests (if managed sustainably).",
    ],
    shortcut: "Non-renewable = minerals, fossil fuels (coal, oil, gas). Renewable = sun, wind, water, forests.",
  },

  // ── 2. Forest and Wildlife Resources (5 questions) ──────────────────────────
  {
    topic: "Forest and Wildlife Resources",
    subtopic: "Conservation",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Chipko Movement, associated with protecting forests, began in which state of India?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Kerala", type: "concept_error", logicTag: "wrong_state" },
      { text: "Uttarakhand (then Uttar Pradesh hills)", type: "correct", logicTag: "" },
      { text: "Rajasthan", type: "concept_error", logicTag: "Bishnoi_movement_confused" },
      { text: "Karnataka", type: "concept_error", logicTag: "appiko_movement_confused" },
    ],
    solutionSteps: [
      "The Chipko Movement began in 1973 in the Gopeshwar village of Chamoli district (now Uttarakhand).",
      "Villagers, especially women, hugged trees to prevent contractors from felling them.",
      "A similar movement in Karnataka is called the Appiko Movement; Bishnoi is in Rajasthan.",
    ],
    shortcut: "Chipko = Uttarakhand (1973). Appiko = Karnataka. Bishnoi = Rajasthan. All = tree/nature protection.",
  },
  {
    topic: "Forest and Wildlife Resources",
    subtopic: "Protected Areas",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A 'Biosphere Reserve' differs from a National Park primarily because:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Biosphere Reserves are smaller in area than National Parks", type: "concept_error", logicTag: "size_comparison_wrong" },
      { text: "Biosphere Reserves allow some human habitation and sustainable use in buffer zones, integrating biodiversity with people", type: "correct", logicTag: "" },
      { text: "National Parks have no protection and allow hunting", type: "concept_error", logicTag: "national_park_wrongly_defined" },
      { text: "Biosphere Reserves are managed by state governments; National Parks by the centre", type: "concept_error", logicTag: "governance_wrong" },
    ],
    solutionSteps: [
      "National Parks: strict protection, no human activity allowed.",
      "Wildlife Sanctuaries: some human activity permitted (like grazing) but wildlife protected.",
      "Biosphere Reserves: have a core zone (strict), buffer zone (research), and transition zone (human use).",
    ],
    shortcut: "Biosphere Reserve has 3 zones: core (strict), buffer (research), transition (human activity). Most flexible.",
  },
  {
    topic: "Forest and Wildlife Resources",
    subtopic: "Flora and Fauna",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "According to the IUCN Red List, which category describes a species with an extremely high risk of extinction in the wild?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Vulnerable", type: "concept_error", logicTag: "lower_risk_category" },
      { text: "Critically Endangered", type: "correct", logicTag: "" },
      { text: "Near Threatened", type: "concept_error", logicTag: "least_risk" },
      { text: "Extinct in the Wild", type: "concept_error", logicTag: "next_category_confused" },
    ],
    solutionSteps: [
      "IUCN categories (increasing risk): Least Concern → Near Threatened → Vulnerable → Endangered → Critically Endangered → Extinct in Wild → Extinct.",
      "Critically Endangered = extremely high risk of extinction in the wild.",
      "Examples: Snow Leopard, Indian Wild Ass are Endangered; Great Indian Bustard is Critically Endangered.",
    ],
    shortcut: "IUCN: LC → NT → V → E → CE → EW → EX. CE = Critically Endangered = highest extinction risk.",
  },
  {
    topic: "Forest and Wildlife Resources",
    subtopic: "Forest Types",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which category of forests in India are under the least protection and allow local communities to use them?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Reserved Forests", type: "concept_error", logicTag: "most_protected_not_least" },
      { text: "Village Forests or Unclassed Forests", type: "correct", logicTag: "" },
      { text: "Protected Forests", type: "concept_error", logicTag: "middle_category_confused" },
      { text: "National Parks", type: "concept_error", logicTag: "strictest_protection_confused" },
    ],
    solutionSteps: [
      "Three main categories: Reserved Forests (most protected), Protected Forests (some restrictions), Unclassed/Village Forests (least regulated).",
      "Village forests or unclassed forests can be used by local communities.",
      "About 54% of forests are Reserved, 29% Protected, 17% Unclassed.",
    ],
    shortcut: "Reserved (most strict) → Protected (some) → Village/Unclassed (least). Community use = Unclassed forests.",
  },
  {
    topic: "Forest and Wildlife Resources",
    subtopic: "Community Conservation",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Bishnoi community of Rajasthan is famous for:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Building check dams for rainwater harvesting", type: "concept_error", logicTag: "water_conservation_confused" },
      { text: "Protecting the blackbuck and khejri trees by sacrificing their lives", type: "correct", logicTag: "" },
      { text: "Planting eucalyptus trees across the Thar desert", type: "concept_error", logicTag: "afforestation_confused" },
      { text: "Starting the Joint Forest Management scheme", type: "concept_error", logicTag: "government_scheme_confused" },
    ],
    solutionSteps: [
      "In 1731, Amrita Devi Bishnoi and 363 others sacrificed their lives to protect khejri trees in Khejrali village.",
      "The Bishnoi community holds nature worship as a religious duty.",
      "They protect the blackbuck (regarded as their kin) and the khejri tree (sacred to them).",
    ],
    shortcut: "Bishnoi = protect blackbuck + khejri trees. Amrita Devi sacrificed life in 1731. Rajasthan community.",
  },

  // ── 3. The Rise of Nationalism in Europe (5 questions) ──────────────────────
  {
    topic: "The Rise of Nationalism in Europe",
    subtopic: "Frankfurt Parliament",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Frankfurt Parliament of 1848 was convened primarily to:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Declare war on Austria", type: "concept_error", logicTag: "confused_with_austro-prussian_war" },
      { text: "Draft a constitution for a unified Germany", type: "correct", logicTag: "" },
      { text: "Abolish the monarchy in Prussia", type: "concept_error", logicTag: "misread_scope" },
      { text: "Establish the German Confederation", type: "concept_error", logicTag: "confused_with_earlier_body" },
    ],
    solutionSteps: [
      "The Frankfurt Parliament met in May 1848 at the Church of St Paul.",
      "Its main purpose was to draft a constitution for a united German nation.",
      "It offered the crown to the Prussian king Frederick William IV who refused it.",
    ],
    shortcut: "Frankfurt Parliament (1848) = draft German constitution. Frederick William IV refused crown. Failed attempt at liberal unification.",
  },
  {
    topic: "The Rise of Nationalism in Europe",
    subtopic: "Treaty of Vienna",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The conservative powers who convened at Vienna in 1815 were led by:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Napoleon Bonaparte of France", type: "concept_error", logicTag: "napoleon_defeated_at_congress" },
      { text: "Duke Metternich of Austria", type: "correct", logicTag: "" },
      { text: "Otto von Bismarck of Prussia", type: "concept_error", logicTag: "later_figure_confused" },
      { text: "Giuseppe Mazzini of Italy", type: "concept_error", logicTag: "revolutionary_not_conservative" },
    ],
    solutionSteps: [
      "The Congress of Vienna (1815) was convened after Napoleon's defeat.",
      "It was led by Duke Metternich of Austria — a conservative statesman.",
      "The goal was to restore the old monarchies and suppress nationalist/liberal movements.",
    ],
    shortcut: "Congress of Vienna 1815 = Metternich (Austria) led conservatives. Restore monarchy, suppress nationalism.",
  },
  {
    topic: "The Rise of Nationalism in Europe",
    subtopic: "Unification of Germany",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "German unification was achieved through 'blood and iron' policy by:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Giuseppe Garibaldi", type: "concept_error", logicTag: "italian_unifier_confused" },
      { text: "Otto von Bismarck", type: "correct", logicTag: "" },
      { text: "Duke Metternich", type: "concept_error", logicTag: "conservative_not_unifier" },
      { text: "Napoleon III", type: "concept_error", logicTag: "french_ruler_confused" },
    ],
    solutionSteps: [
      "Otto von Bismarck, Chancellor of Prussia, unified Germany through wars (blood) and military strength (iron).",
      "He fought three wars: against Denmark (1864), Austria (1866), and France (1870-71).",
      "Germany was proclaimed a nation at Versailles Palace in 1871.",
    ],
    shortcut: "Germany unified by Bismarck (Prussia) — blood and iron, 3 wars, proclaimed 1871 at Versailles.",
  },
  {
    topic: "The Rise of Nationalism in Europe",
    subtopic: "Nationalism and Romanticism",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Romanticism as a cultural movement contributed to nationalism by:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Promoting rational scientific thought over tradition", type: "concept_error", logicTag: "opposite_of_romanticism" },
      { text: "Evoking collective national identity through folk songs, stories, poetry, and vernacular languages", type: "correct", logicTag: "" },
      { text: "Encouraging individual economic freedom through trade", type: "concept_error", logicTag: "liberalism_confused_with_romanticism" },
      { text: "Supporting monarchies and the Church against revolutionaries", type: "concept_error", logicTag: "conservatism_confused" },
    ],
    solutionSteps: [
      "Romanticism was a cultural and artistic movement that emphasised emotion, tradition, and folk heritage.",
      "Poets and artists collected folk stories, myths, and vernacular songs to build national identity.",
      "Examples: Brothers Grimm collected German folk tales; Karol Kurpinski composed Polish nationalist music.",
    ],
    shortcut: "Romanticism = emotion + folk culture + vernacular language = build national identity. Anti-Enlightenment/rational.",
  },
  {
    topic: "The Rise of Nationalism in Europe",
    subtopic: "French Revolution",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following ideas did the French Revolution NOT promote?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Liberty, equality, and fraternity", type: "concept_error", logicTag: "core_ideals_wrongly_chosen" },
      { text: "Restoration of monarchy and aristocratic privileges", type: "correct", logicTag: "" },
      { text: "The idea of la patrie (the fatherland) and le citoyen (the citizen)", type: "concept_error", logicTag: "revolutionary_concepts_wrongly_chosen" },
      { text: "A new French flag, anthem, and centralised administrative system", type: "concept_error", logicTag: "national_symbols_wrongly_chosen" },
    ],
    solutionSteps: [
      "The French Revolution promoted liberty, equality, fraternity, la patrie, national symbols, and citizenship.",
      "It abolished monarchy, aristocratic privileges, and the old feudal order.",
      "Restoration of monarchy was the goal of conservatives AFTER the revolution (Congress of Vienna).",
    ],
    shortcut: "French Revolution promoted = liberty, equality, fraternity, citizenship. Did NOT promote = monarchy/aristocracy.",
  },

  // ── 4. Nationalism in India (5 questions) ────────────────────────────────────
  {
    topic: "Nationalism in India",
    subtopic: "Non-Cooperation Movement",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Non-Cooperation Movement was called off by Gandhi in 1922 because of:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "The Jallianwala Bagh Massacre", type: "concept_error", logicTag: "event_that_started_movement" },
      { text: "The Chauri Chaura incident, where a mob burned a police station killing policemen", type: "correct", logicTag: "" },
      { text: "The signing of the Treaty of Lucknow", type: "concept_error", logicTag: "invented_event" },
      { text: "Gandhi's arrest by British authorities", type: "concept_error", logicTag: "later_event_confused" },
    ],
    solutionSteps: [
      "In February 1922, a crowd at Chauri Chaura (Uttar Pradesh) turned violent and burned a police station.",
      "22 policemen were killed. Gandhi was horrified by the violence.",
      "He called off the movement, saying India was not ready for non-violent struggle.",
    ],
    shortcut: "Non-Cooperation Movement called off = Chauri Chaura (Feb 1922, police station burned, 22 killed).",
  },
  {
    topic: "Nationalism in India",
    subtopic: "Civil Disobedience",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Dandi March (Salt Satyagraha) of 1930 was significant because:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "It was the first movement in which only upper-caste Hindus participated", type: "concept_error", logicTag: "narrow_participation_wrong" },
      { text: "It challenged a symbol of British economic exploitation and involved all sections of society", type: "correct", logicTag: "" },
      { text: "It led to immediate Indian independence", type: "concept_error", logicTag: "result_exaggerated" },
      { text: "Gandhi broke into a government storehouse to protest", type: "concept_error", logicTag: "wrong_action" },
    ],
    solutionSteps: [
      "Gandhi marched 240 miles from Sabarmati Ashram to Dandi (Gujarat) to make salt.",
      "Salt was chosen because it was taxed by the British — every Indian needed it regardless of class/caste.",
      "The movement spread nationally; women, merchants, tribals all participated.",
    ],
    shortcut: "Dandi March = salt protest. 240 miles, Sabarmati to Dandi (Gujarat). April 6, 1930 — salt made.",
  },
  {
    topic: "Nationalism in India",
    subtopic: "Jallianwala Bagh",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Rowlatt Act of 1919 allowed the British government to:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Grant self-government to Indian provinces", type: "concept_error", logicTag: "opposite_intent" },
      { text: "Detain any person without trial for up to two years on suspicion of sedition", type: "correct", logicTag: "" },
      { text: "Create separate electorates for Muslims", type: "concept_error", logicTag: "morley_minto_reforms_confused" },
      { text: "Transfer Indian soldiers to fight in World War I", type: "concept_error", logicTag: "ww1_recruitment_confused" },
    ],
    solutionSteps: [
      "The Rowlatt Act (1919) allowed detention without trial for up to 2 years on suspicion of sedition.",
      "It was called the 'Black Act' and sparked massive protests.",
      "The Jallianwala Bagh Massacre (April 13, 1919) occurred during protests against this act.",
    ],
    shortcut: "Rowlatt Act = Black Act. Detention without trial. Caused protests → Jallianwala Bagh massacre.",
  },
  {
    topic: "Nationalism in India",
    subtopic: "Participation in National Movement",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Why were plantation workers in Assam particularly enthusiastic about the Non-Cooperation Movement?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "They wanted higher wages from British tea companies", type: "partial_logic", logicTag: "only_one_reason" },
      { text: "They linked swaraj (self-rule) with the freedom to return to their home villages — the Inland Emigration Act prevented them from leaving plantations", type: "correct", logicTag: "" },
      { text: "They were mostly educated and politically aware nationalists", type: "concept_error", logicTag: "class_assumption_wrong" },
      { text: "Gandhi personally visited Assam and mobilised plantation workers", type: "concept_error", logicTag: "invented_event" },
    ],
    solutionSteps: [
      "Under the Inland Emigration Act of 1859, plantation workers could not leave without permission.",
      "They interpreted swaraj as freedom to move freely and return to their native villages.",
      "During the movement, thousands walked out of plantations — crossing rivers, facing police violence.",
    ],
    shortcut: "Assam workers = trapped by Inland Emigration Act. Swaraj = freedom to leave. They walked out of plantations.",
  },
  {
    topic: "Nationalism in India",
    subtopic: "Gandhi's Movements",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Quit India Movement was launched by Gandhi in:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "1920", type: "concept_error", logicTag: "non_cooperation_year" },
      { text: "1942", type: "correct", logicTag: "" },
      { text: "1930", type: "concept_error", logicTag: "civil_disobedience_year" },
      { text: "1935", type: "concept_error", logicTag: "government_of_india_act_year" },
    ],
    solutionSteps: [
      "The Quit India Movement was launched on August 8, 1942, at the Bombay session of the Congress.",
      "Gandhi gave the call: 'Do or Die' (Karo Ya Maro).",
      "The movement demanded immediate independence from British rule.",
    ],
    shortcut: "Quit India = August 8, 1942. 'Do or Die' (Karo Ya Maro). Bombay session. Immediate independence demanded.",
  },

  // ── 5. Development (5 questions) ────────────────────────────────────────────
  {
    topic: "Development",
    subtopic: "Development Goals",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Why is per capita income alone considered an inadequate measure of development?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "It is difficult to calculate accurately", type: "concept_error", logicTag: "computational_issue_not_conceptual" },
      { text: "It does not reflect the distribution of income, or access to education, health, and equality", type: "correct", logicTag: "" },
      { text: "It ignores industrial production entirely", type: "concept_error", logicTag: "partial_misunderstanding" },
      { text: "Countries with high per capita income never face poverty", type: "concept_error", logicTag: "false_assumption" },
    ],
    solutionSteps: [
      "Per capita income = total national income ÷ population. It is an average.",
      "An average hides inequality — a country may have high per capita income but extreme inequality.",
      "HDI (Human Development Index) adds life expectancy, education, and standard of living.",
    ],
    shortcut: "Per capita income = average (hides inequality). HDI = income + education + health. More complete measure.",
  },
  {
    topic: "Development",
    subtopic: "Human Development Index",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The Human Development Index (HDI) is published by:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "World Bank", type: "concept_error", logicTag: "economic_institution_confused" },
      { text: "United Nations Development Programme (UNDP)", type: "correct", logicTag: "" },
      { text: "International Monetary Fund (IMF)", type: "concept_error", logicTag: "financial_institution_confused" },
      { text: "World Health Organisation (WHO)", type: "concept_error", logicTag: "health_body_confused" },
    ],
    solutionSteps: [
      "UNDP publishes the annual Human Development Report, which includes the HDI.",
      "HDI measures three dimensions: long and healthy life, access to knowledge, and decent standard of living.",
      "India's HDI rank helps compare its development with other nations.",
    ],
    shortcut: "HDI = UNDP. Three dimensions: health (life expectancy) + education (schooling) + income (GNI per capita).",
  },
  {
    topic: "Development",
    subtopic: "National Development Goals",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following best explains why different persons have different development goals?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "People in developing countries only care about income", type: "concept_error", logicTag: "oversimplification" },
      { text: "People have different aspirations, needs, and situations — development goals depend on their life context", type: "correct", logicTag: "" },
      { text: "The government decides development goals for every individual", type: "concept_error", logicTag: "top_down_confusion" },
      { text: "Development goals are the same for all but are achieved at different speeds", type: "concept_error", logicTag: "uniformity_assumed" },
    ],
    solutionSteps: [
      "A landless labourer wants more work and better wages; a rich farmer wants higher crop prices.",
      "An industrialist wants easier access to capital; a student in a remote area wants a school.",
      "Development is multidimensional — different contexts create different priorities.",
    ],
    shortcut: "Different people → different needs → different goals. Development = not one-size-fits-all.",
  },
  {
    topic: "Development",
    subtopic: "Sustainability",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which aspect makes 'sustainable development' different from 'development at any cost'?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Sustainable development only occurs in rich countries", type: "concept_error", logicTag: "wealth_condition_wrong" },
      { text: "Sustainable development considers the consequences for future generations and does not deplete resources", type: "correct", logicTag: "" },
      { text: "Sustainable development avoids all industrialisation to preserve nature", type: "concept_error", logicTag: "no_industry_extreme" },
      { text: "Sustainable development means growing the economy first and cleaning the environment later", type: "concept_error", logicTag: "kuznets_curve_misconception" },
    ],
    solutionSteps: [
      "'Development at any cost' ignores environmental damage and social inequity.",
      "Sustainable development ensures today's growth does not destroy future possibilities.",
      "Example: groundwater use — if extracted faster than it is replenished, it is unsustainable.",
    ],
    shortcut: "Sustainable = long-term thinking. Use resources within limits of regeneration. Future generations matter.",
  },
  {
    topic: "Development",
    subtopic: "Kerala Model",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Kerala has a lower per capita income than Punjab but better human development indicators. This illustrates that:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.74,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Income is the only factor that matters for quality of life", type: "concept_error", logicTag: "income_only_view" },
      { text: "High income does not automatically translate to better health, education, or social equality", type: "correct", logicTag: "" },
      { text: "Punjab is less developed than Kerala in every way", type: "concept_error", logicTag: "oversimplification" },
      { text: "Kerala's population is smaller, making its indicators appear better", type: "concept_error", logicTag: "population_excuse" },
    ],
    solutionSteps: [
      "Kerala has high literacy, low infant mortality, and high life expectancy despite lower per capita income than Punjab.",
      "This shows that public spending on education and health matters as much as income.",
      "It proves that income alone is an insufficient measure of development — HDI is more complete.",
    ],
    shortcut: "Kerala model = lower income, higher HDI. Shows public investment in health+education > mere income growth.",
  },

  // ── 6. Money and Credit (5 questions) ────────────────────────────────────────
  {
    topic: "Money and Credit",
    subtopic: "Functions of Money",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is a primary function of money?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Acting as a standard for deferred payments", type: "concept_error", logicTag: "secondary_function" },
      { text: "Medium of exchange that eliminates the need for double coincidence of wants", type: "correct", logicTag: "" },
      { text: "Store of value for future use", type: "concept_error", logicTag: "secondary_function_2" },
      { text: "Transfer of value through cheques", type: "concept_error", logicTag: "credit_instrument_confused" },
    ],
    solutionSteps: [
      "Primary functions of money: (1) Medium of exchange, (2) Measure of value.",
      "Money eliminates the problem of 'double coincidence of wants' that existed in the barter system.",
      "Store of value and standard of deferred payments are secondary functions.",
    ],
    shortcut: "Primary = medium of exchange + measure of value. Secondary = store of value + standard of deferred payment.",
  },
  {
    topic: "Money and Credit",
    subtopic: "Formal and Informal Credit",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is an example of formal sector credit in India?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "A moneylender charging 5% per month", type: "concept_error", logicTag: "informal_sector" },
      { text: "A bank loan from the State Bank of India", type: "correct", logicTag: "" },
      { text: "Borrowing from a chit fund", type: "concept_error", logicTag: "informal_unregulated" },
      { text: "Credit from a landlord at harvest time", type: "concept_error", logicTag: "informal_rural_credit" },
    ],
    solutionSteps: [
      "Formal sector credit = banks and cooperatives (regulated by Reserve Bank of India).",
      "Informal sector = moneylenders, traders, landlords, relatives, chit funds (unregulated).",
      "Formal sector charges lower interest and is monitored by RBI.",
    ],
    shortcut: "Formal = banks + cooperatives (RBI regulated). Informal = moneylenders, landlords, relatives (unregulated).",
  },
  {
    topic: "Money and Credit",
    subtopic: "Role of Credit",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Credit (loan) can be harmful when:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "It is used to buy agricultural inputs and the harvest is good", type: "concept_error", logicTag: "beneficial_credit_confused" },
      { text: "The borrower cannot repay, leading to debt trap — loss of assets and greater poverty", type: "correct", logicTag: "" },
      { text: "It is given at low interest by a bank for business expansion", type: "concept_error", logicTag: "productive_loan_confused" },
      { text: "The loan is used to purchase machinery for a small enterprise", type: "concept_error", logicTag: "investment_loan_confused" },
    ],
    solutionSteps: [
      "Credit is harmful when borrowers cannot repay: mounting interest, loss of collateral, debt traps.",
      "Example: a farmer takes a loan for seeds; drought ruins the crop — he cannot repay → sells land.",
      "Informal sector loans are especially risky due to high interest rates and harsh terms.",
    ],
    shortcut: "Credit harmful = debt trap → cannot repay → collateral seized → poorer than before.",
  },
  {
    topic: "Money and Credit",
    subtopic: "Self-Help Groups",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Self-Help Groups (SHGs) primarily help the rural poor by:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Providing direct government grants to members", type: "concept_error", logicTag: "government_subsidy_confused" },
      { text: "Organising members to save collectively and access credit without collateral at reasonable interest", type: "correct", logicTag: "" },
      { text: "Training members to migrate to cities for employment", type: "concept_error", logicTag: "migration_solution_confused" },
      { text: "Replacing formal banks in rural areas entirely", type: "concept_error", logicTag: "replacement_role_wrong" },
    ],
    solutionSteps: [
      "SHGs are small groups (15-20 members) that pool savings and lend to each other.",
      "After regular saving for 6 months, an SHG can access bank credit without individual collateral.",
      "They empower women, reduce dependence on moneylenders, and build financial discipline.",
    ],
    shortcut: "SHG = 15-20 members save → get bank credit collectively. No individual collateral needed. Empowers women.",
  },
  {
    topic: "Money and Credit",
    subtopic: "Banking",
    subject: "Social Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Banks charge higher interest on loans than they pay on deposits because:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Banks are trying to exploit depositors", type: "concept_error", logicTag: "exploitation_narrative_wrong" },
      { text: "The difference (spread) covers operating costs and generates profit for the bank", type: "correct", logicTag: "" },
      { text: "The government requires banks to charge more than they pay", type: "concept_error", logicTag: "government_directive_wrong" },
      { text: "Banks lose money on every deposit so they compensate through loans", type: "concept_error", logicTag: "backwards_reasoning" },
    ],
    solutionSteps: [
      "Banks pay interest to depositors (e.g., 4%) and charge interest from borrowers (e.g., 12%).",
      "The difference (spread) covers bank operating expenses, bad debt provisions, and profit.",
      "This spread is the main source of bank income.",
    ],
    shortcut: "Bank spread = loan interest − deposit interest = bank's income. E.g., 12% charged − 4% paid = 8% spread.",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  let added = 0, skipped = 0;
  for (const q of QUESTIONS) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    added++;
  }
  console.log(`Social Science questions: ${added} added, ${skipped} skipped`);
  await mongoose.disconnect();
}

seed().catch(console.error);
