import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math4_ch5_top_view — 8 Qs
  { questionId:"math4_ch5_tv_q1", topicId:"math4_ch5_top_view", text:"Top view of a glass shows…", options:[{text:"Rectangle",type:"concept_error"},{text:"Circle",type:"correct"},{text:"Triangle",type:"misinterpretation"},{text:"Square",type:"guessing"}], explanation:"Glass rim is circular, top view = circle.", solutionSteps:["Glass top = round.","Top view = circle."], shortcut:"Glass top = circle.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_tv_q2", topicId:"math4_ch5_top_view", text:"Looking down on a book lying flat shows…", options:[{text:"Triangle",type:"concept_error"},{text:"Rectangle",type:"correct"},{text:"Circle",type:"misinterpretation"},{text:"Cube",type:"calculation_error"}], explanation:"Book from above looks rectangular.", solutionSteps:["Book cover = rectangle.","Top view = rectangle."], shortcut:"Book = rectangle.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_tv_q3", topicId:"math4_ch5_top_view", text:"Top view shows…", options:[{text:"Height of an object",type:"concept_error"},{text:"Length and width (footprint)",type:"correct"},{text:"Side details",type:"misinterpretation"},{text:"Inside",type:"guessing"}], explanation:"Top view = horizontal footprint, not height.", solutionSteps:["Top view = bird's eye.","Shows length × width."], shortcut:"Top view = footprint.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_tv_q4", topicId:"math4_ch5_top_view", text:"Top view of a pyramid (square base)?", options:[{text:"Triangle",type:"concept_error"},{text:"Square",type:"correct"},{text:"Pentagon",type:"misinterpretation"},{text:"Circle",type:"guessing"}], explanation:"From above, you see the pyramid's square base.", solutionSteps:["Looking down → see base.","Pyramid base = square."], shortcut:"Top view = base shape.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_tv_q5", topicId:"math4_ch5_top_view", text:"Top view of a cylinder standing on its end?", options:[{text:"Rectangle",type:"concept_error"},{text:"Circle",type:"correct"},{text:"Triangle",type:"misinterpretation"},{text:"Oval",type:"calculation_error"}], explanation:"Cylinder's end face is a circle.", solutionSteps:["Cylinder end = circle.","Top view = circle."], shortcut:"Cylinder top = circle.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_tv_q6", topicId:"math4_ch5_top_view", text:"A map of a city is essentially a…", options:[{text:"Side view",type:"concept_error"},{text:"Top view",type:"correct"},{text:"Front view",type:"misinterpretation"},{text:"Random view",type:"guessing"}], explanation:"Maps show land from above = top view.", solutionSteps:["Maps = bird's eye = top view."], shortcut:"Map = top view.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_tv_q7", topicId:"math4_ch5_top_view", text:"Top view of a coffee cup with handle?", options:[{text:"Just a circle",type:"partial_logic"},{text:"Circle with a small bump (handle)",type:"correct"},{text:"Rectangle",type:"misinterpretation"},{text:"Triangle",type:"guessing"}], explanation:"Top view: round cup + handle protruding to one side.", solutionSteps:["Cup body = circle from top.","Handle adds a bump."], shortcut:"Round + handle bump.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_tv_q8", topicId:"math4_ch5_top_view", text:"What does a top view NOT show?", options:[{text:"Length",type:"concept_error"},{text:"Width",type:"concept_error"},{text:"Height",type:"correct"},{text:"Shape",type:"misinterpretation"}], explanation:"Top view shows L × W but not H.", solutionSteps:["Top view: L and W.","Height is hidden."], shortcut:"Top hides height.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },

  // math4_ch5_side_view — 8 Qs
  { questionId:"math4_ch5_sv_q1", topicId:"math4_ch5_side_view", text:"Side view of a cylinder lying horizontally?", options:[{text:"Circle",type:"concept_error"},{text:"Rectangle",type:"correct"},{text:"Triangle",type:"misinterpretation"},{text:"Square",type:"calculation_error"}], explanation:"Cylinder from side = rectangle.", solutionSteps:["Cylinder side profile = rectangle."], shortcut:"Cylinder side = rectangle.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_sv_q2", topicId:"math4_ch5_side_view", text:"Side view of a cone (pointed up)?", options:[{text:"Circle",type:"concept_error"},{text:"Triangle",type:"correct"},{text:"Square",type:"misinterpretation"},{text:"Rectangle",type:"calculation_error"}], explanation:"Cone profile = triangle (point at top, wide at base).", solutionSteps:["Cone side = triangle."], shortcut:"Cone side = triangle.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_sv_q3", topicId:"math4_ch5_side_view", text:"Side view of a car shows…", options:[{text:"Bonnet only",type:"concept_error"},{text:"Full length: wheels, doors, windows",type:"correct"},{text:"Roof only",type:"misinterpretation"},{text:"Just headlights",type:"guessing"}], explanation:"Side view shows car's full profile.", solutionSteps:["Side view = full car profile.","Wheels, doors, windows visible."], shortcut:"Side view = profile.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_sv_q4", topicId:"math4_ch5_side_view", text:"Side view of a cube?", options:[{text:"Triangle",type:"concept_error"},{text:"Square",type:"correct"},{text:"Circle",type:"misinterpretation"},{text:"Cuboid",type:"calculation_error"}], explanation:"All cube faces are squares.", solutionSteps:["Cube face = square.","Side view = square."], shortcut:"Cube every view = square.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_sv_q5", topicId:"math4_ch5_side_view", text:"Which view shows BOTH length AND height of a building?", options:[{text:"Top view",type:"concept_error"},{text:"Side view",type:"correct"},{text:"Front view",type:"partial_logic"},{text:"Inside view",type:"misinterpretation"}], explanation:"Side view = length (front-to-back) and height.", solutionSteps:["Side view shows L × H."], shortcut:"Side = L and H.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_sv_q6", topicId:"math4_ch5_side_view", text:"To fully describe a 3D object, you need:", options:[{text:"Only top view",type:"concept_error"},{text:"Top + front + side views",type:"correct"},{text:"Only front",type:"misinterpretation"},{text:"None of these",type:"guessing"}], explanation:"3 views = complete description.", solutionSteps:["Top: footprint.","Front: face.","Side: profile.","Together: full description."], shortcut:"3 views suffice.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_sv_q7", topicId:"math4_ch5_side_view", text:"Side view of a sphere (ball)?", options:[{text:"Circle",type:"correct"},{text:"Square",type:"concept_error"},{text:"Triangle",type:"misinterpretation"},{text:"Oval",type:"calculation_error"}], explanation:"Sphere from any side = circle.", solutionSteps:["Sphere = round from every angle.","All views = circle."], shortcut:"Sphere = circle always.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_sv_q8", topicId:"math4_ch5_side_view", text:"A chair from the side shows…", options:[{text:"Round object",type:"concept_error"},{text:"L-shape (seat + backrest)",type:"correct"},{text:"Just legs",type:"misinterpretation"},{text:"Triangle",type:"guessing"}], explanation:"Chair side profile = L-shape.", solutionSteps:["Seat = horizontal.","Backrest = vertical.","Together: L-shape."], shortcut:"Chair side = L.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },

  // math4_ch5_maps — 8 Qs
  { questionId:"math4_ch5_ma_q1", topicId:"math4_ch5_maps", text:"A map is essentially a…", options:[{text:"Photo from inside a house",type:"concept_error"},{text:"Top view of a place",type:"correct"},{text:"Side view of a city",type:"misinterpretation"},{text:"Random drawing",type:"guessing"}], explanation:"Maps show places from above = top view.", solutionSteps:["Map = bird's eye = top view."], shortcut:"Map = top view.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_ma_q2", topicId:"math4_ch5_maps", text:"What's a map's KEY for?", options:[{text:"To open doors",type:"concept_error"},{text:"To show what symbols mean",type:"correct"},{text:"To find names",type:"partial_logic"},{text:"To colour the map",type:"misinterpretation"}], explanation:"The key (legend) explains symbols (blue = water, green = park, etc.).", solutionSteps:["Key/legend = symbol guide.","Tells you what each symbol means."], shortcut:"Key = legend.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_ma_q3", topicId:"math4_ch5_maps", text:"On a map, scale 1 cm = 100 m. If two places are 5 cm apart on the map, real distance?", options:[{text:"5 m",type:"concept_error"},{text:"500 m",type:"correct"},{text:"100 m",type:"calculation_error"},{text:"5 km",type:"calculation_error"}], explanation:"5 × 100 m = 500 m.", solutionSteps:["1 cm = 100 m.","5 cm × 100 = 500 m."], shortcut:"Multiply map distance by scale.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_ma_q4", topicId:"math4_ch5_maps", text:"Map scale 1 cm = 1 km. Two cities 8 cm apart. Real distance?", options:[{text:"8 m",type:"concept_error"},{text:"8 km",type:"correct"},{text:"1 km",type:"calculation_error"},{text:"80 km",type:"calculation_error"}], explanation:"8 × 1 km = 8 km.", solutionSteps:["1 cm = 1 km.","8 cm × 1 km = 8 km."], shortcut:"Multiply by scale.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_ma_q5", topicId:"math4_ch5_maps", text:"On a city map, what color usually shows water?", options:[{text:"Green",type:"concept_error"},{text:"Blue",type:"correct"},{text:"Red",type:"misinterpretation"},{text:"Brown",type:"calculation_error"}], explanation:"Water = blue. Parks = green. Roads = lines.", solutionSteps:["Water = blue.","Parks = green.","Buildings = grey/red."], shortcut:"Blue = water.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_ma_q6", topicId:"math4_ch5_maps", text:"Why is map scale important?", options:[{text:"Pretty",type:"concept_error"},{text:"To know real distances",type:"correct"},{text:"To colour",type:"misinterpretation"},{text:"Not important",type:"guessing"}], explanation:"Scale tells you how map distance relates to real distance.", solutionSteps:["Scale = ratio of map to real.","Lets you compute real distance."], shortcut:"Scale = distance converter.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_ma_q7", topicId:"math4_ch5_maps", text:"If 2 cm on a map = 1 km in reality, then 6 cm on map = ___?", options:[{text:"3 km",type:"correct"},{text:"6 km",type:"calculation_error"},{text:"12 km",type:"calculation_error"},{text:"0.5 km",type:"misinterpretation"}], explanation:"2 cm = 1 km → 6 cm = 6/2 = 3 km.", solutionSteps:["2 cm : 1 km.","6 cm : ? → 6/2 = 3 km."], shortcut:"Divide by scale factor.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_ma_q8", topicId:"math4_ch5_maps", text:"A globe is a map of…", options:[{text:"One city",type:"concept_error"},{text:"The whole Earth",type:"correct"},{text:"A country",type:"partial_logic"},{text:"The moon",type:"misinterpretation"}], explanation:"Globe = round model of Earth.", solutionSteps:["Globe = Earth, 3D.","Maps Earth in spherical form."], shortcut:"Globe = Earth.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },

  // math4_ch5_directions — 8 Qs
  { questionId:"math4_ch5_di_q1", topicId:"math4_ch5_directions", text:"On most maps, north is shown…", options:[{text:"Down",type:"concept_error"},{text:"Up",type:"correct"},{text:"Left",type:"misinterpretation"},{text:"Right",type:"calculation_error"}], explanation:"By convention, north is at the top of a map.", solutionSteps:["Standard: north = up.","Other directions follow."], shortcut:"North up.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_di_q2", topicId:"math4_ch5_directions", text:"If north is up, then east is…", options:[{text:"Up",type:"concept_error"},{text:"Down",type:"misinterpretation"},{text:"Left",type:"calculation_error"},{text:"Right",type:"correct"}], explanation:"N up → E right → S down → W left.", solutionSteps:["NEWS clockwise: N, E, S, W.","E = right."], shortcut:"NEWS clockwise.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_di_q3", topicId:"math4_ch5_directions", text:"Opposite of east?", options:[{text:"North",type:"concept_error"},{text:"South",type:"calculation_error"},{text:"West",type:"correct"},{text:"Up",type:"misinterpretation"}], explanation:"East ↔ west.", solutionSteps:["East and west = opposite directions."], shortcut:"E ↔ W.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_di_q4", topicId:"math4_ch5_directions", text:"The four cardinal directions are…", options:[{text:"Up, down, left, right",type:"misinterpretation"},{text:"North, south, east, west",type:"correct"},{text:"Top, bottom, side, inside",type:"concept_error"},{text:"Forward, back, right, left",type:"guessing"}], explanation:"NSEW are the 4 main directions.", solutionSteps:["Cardinal = 4 main.","N, S, E, W."], shortcut:"NSEW.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_di_q5", topicId:"math4_ch5_directions", text:"Sun rises in the…", options:[{text:"North",type:"concept_error"},{text:"South",type:"misinterpretation"},{text:"East",type:"correct"},{text:"West",type:"calculation_error"}], explanation:"Sun rises in the east, sets in the west.", solutionSteps:["Sun rises: east.","Sun sets: west."], shortcut:"East = rise, West = set.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_di_q6", topicId:"math4_ch5_directions", text:"From south, turn 90° clockwise → you face…", options:[{text:"North",type:"calculation_error"},{text:"East",type:"calculation_error"},{text:"West",type:"correct"},{text:"South",type:"concept_error"}], explanation:"South → 90° clockwise → West.", solutionSteps:["South facing S.","Clockwise 90° → W.","→ west."], shortcut:"NSEW clockwise = N, E, S, W.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_di_q7", topicId:"math4_ch5_directions", text:"NEWS clockwise reads:", options:[{text:"N, S, E, W",type:"concept_error"},{text:"N, E, S, W",type:"correct"},{text:"N, W, E, S",type:"calculation_error"},{text:"N, E, W, S",type:"calculation_error"}], explanation:"Clockwise from N: N → E → S → W.", solutionSteps:["Starting north.","Clockwise: N, E, S, W."], shortcut:"NESW clockwise.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },
  { questionId:"math4_ch5_di_q8", topicId:"math4_ch5_directions", text:"If you walk 3 km north, then 3 km east, you are…", options:[{text:"6 km away in NE",type:"correct"},{text:"6 km away in N",type:"calculation_error"},{text:"At start",type:"concept_error"},{text:"3 km away",type:"calculation_error"}], explanation:"3 km N + 3 km E = NE direction; total path 6 km.", solutionSteps:["N: 3 km.","E: 3 km.","Path: 6 km, NE direction."], shortcut:"Two perpendicular paths = diagonal direction.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"The Way The World Looks" },

  // math4_ch6_money_calculations — 8 Qs
  { questionId:"math4_ch6_mc_q1", topicId:"math4_ch6_money_calculations", text:"3 toys at ₹15 each. Total?", options:[{text:"₹18",type:"misinterpretation"},{text:"₹45",type:"correct"},{text:"₹315",type:"calculation_error"},{text:"₹30",type:"calculation_error"}], explanation:"3 × 15 = ₹45.", solutionSteps:["Items × price = total.","3 × 15 = 45."], shortcut:"Quantity × per-unit.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mc_q2", topicId:"math4_ch6_money_calculations", text:"₹100 + ₹250 + ₹75 = ?", options:[{text:"₹425",type:"correct"},{text:"₹325",type:"calculation_error"},{text:"₹450",type:"calculation_error"},{text:"₹400",type:"calculation_error"}], explanation:"100 + 250 = 350. + 75 = 425.", solutionSteps:["100 + 250 = 350.","350 + 75 = 425."], shortcut:"Add in order.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mc_q3", topicId:"math4_ch6_money_calculations", text:"₹500 − ₹235 = ?", options:[{text:"₹735",type:"misinterpretation"},{text:"₹265",type:"correct"},{text:"₹235",type:"misinterpretation"},{text:"₹255",type:"calculation_error"}], explanation:"500 − 235 = 265.", solutionSteps:["500 − 235 = 265."], shortcut:"Subtract.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mc_q4", topicId:"math4_ch6_money_calculations", text:"₹2.50 × 4 = ?", options:[{text:"₹6.50",type:"calculation_error"},{text:"₹10",type:"correct"},{text:"₹8",type:"calculation_error"},{text:"₹12",type:"calculation_error"}], explanation:"2.50 × 4 = 10.", solutionSteps:["2.50 × 4 = 10."], shortcut:"Decimal × integer.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mc_q5", topicId:"math4_ch6_money_calculations", text:"Share ₹60 equally among 4. Each gets…", options:[{text:"₹10",type:"calculation_error"},{text:"₹15",type:"correct"},{text:"₹20",type:"calculation_error"},{text:"₹240",type:"misinterpretation"}], explanation:"60 ÷ 4 = ₹15.", solutionSteps:["60 ÷ 4 = 15."], shortcut:"Total ÷ people.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mc_q6", topicId:"math4_ch6_money_calculations", text:"Money math uses same operations as numbers, but you must mind…", options:[{text:"Colour",type:"concept_error"},{text:"Decimal points and units",type:"correct"},{text:"Time of day",type:"misinterpretation"},{text:"Order of zeros",type:"partial_logic"}], explanation:"Decimals and units (₹/paise) need care.", solutionSteps:["Same ops as numbers.","Mind decimals and units."], shortcut:"Watch decimals.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mc_q7", topicId:"math4_ch6_money_calculations", text:"₹12.75 + ₹8.25 = ?", options:[{text:"₹20",type:"calculation_error"},{text:"₹21",type:"correct"},{text:"₹20.75",type:"calculation_error"},{text:"₹4.50",type:"misinterpretation"}], explanation:"12.75 + 8.25 = 21.", solutionSteps:["Add paise: 75+25 = 100 (= ₹1 carry).","₹: 12+8+1 = ₹21."], shortcut:"Watch the carry from paise.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mc_q8", topicId:"math4_ch6_money_calculations", text:"₹50 ÷ 10 = ?", options:[{text:"₹5",type:"correct"},{text:"₹10",type:"calculation_error"},{text:"₹40",type:"calculation_error"},{text:"₹500",type:"misinterpretation"}], explanation:"50 ÷ 10 = 5.", solutionSteps:["50 ÷ 10 = ₹5."], shortcut:"÷ 10 drops a zero.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },

  // math4_ch6_buying_selling — 8 Qs
  { questionId:"math4_ch6_bs_q1", topicId:"math4_ch6_buying_selling", text:"Cost ₹50, Selling ₹80. Profit?", options:[{text:"₹130",type:"misinterpretation"},{text:"₹30",type:"correct"},{text:"₹50",type:"calculation_error"},{text:"₹40",type:"calculation_error"}], explanation:"Profit = SP − CP = 80 − 50 = ₹30.", solutionSteps:["Profit = SP − CP.","80 − 50 = 30."], shortcut:"SP > CP = profit.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_bs_q2", topicId:"math4_ch6_buying_selling", text:"Profit = ?", options:[{text:"SP + CP",type:"concept_error"},{text:"SP − CP",type:"correct"},{text:"CP − SP",type:"misinterpretation"},{text:"SP × CP",type:"calculation_error"}], explanation:"Profit = Selling Price − Cost Price.", solutionSteps:["Profit when SP > CP.","Profit = SP − CP."], shortcut:"P = SP − CP.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_bs_q3", topicId:"math4_ch6_buying_selling", text:"Cost ₹100, sold for ₹80. Result?", options:[{text:"Profit ₹20",type:"concept_error"},{text:"Loss ₹20",type:"correct"},{text:"Profit ₹180",type:"misinterpretation"},{text:"No change",type:"calculation_error"}], explanation:"SP < CP = loss. Loss = 100 − 80 = ₹20.", solutionSteps:["SP < CP → loss.","Loss = CP − SP = 100 − 80 = 20."], shortcut:"SP < CP = loss.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_bs_q4", topicId:"math4_ch6_buying_selling", text:"10 kg paper bought at ₹5/kg. Total CP?", options:[{text:"₹15",type:"misinterpretation"},{text:"₹50",type:"correct"},{text:"₹150",type:"calculation_error"},{text:"₹2",type:"calculation_error"}], explanation:"10 × 5 = ₹50.", solutionSteps:["Quantity × per-unit = total.","10 × 5 = 50."], shortcut:"Total cost = quantity × per-unit.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_bs_q5", topicId:"math4_ch6_buying_selling", text:"Bought 10 kg at ₹5/kg, sold at ₹8/kg. Profit?", options:[{text:"₹3",type:"calculation_error"},{text:"₹30",type:"correct"},{text:"₹130",type:"calculation_error"},{text:"₹80",type:"misinterpretation"}], explanation:"CP = 10×5 = ₹50. SP = 10×8 = ₹80. Profit = 80−50 = ₹30.", solutionSteps:["CP: 10 × 5 = 50.","SP: 10 × 8 = 80.","Profit: 80 − 50 = 30."], shortcut:"Compute CP and SP, then subtract.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_bs_q6", topicId:"math4_ch6_buying_selling", text:"Junk seller wants to make ₹100 profit on a ₹200 buy. Selling price?", options:[{text:"₹100",type:"concept_error"},{text:"₹300",type:"correct"},{text:"₹500",type:"calculation_error"},{text:"₹200",type:"calculation_error"}], explanation:"SP = CP + profit = 200 + 100 = ₹300.", solutionSteps:["SP = CP + profit.","200 + 100 = 300."], shortcut:"SP = CP + P.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_bs_q7", topicId:"math4_ch6_buying_selling", text:"Loss happens when…", options:[{text:"SP > CP",type:"concept_error"},{text:"SP < CP",type:"correct"},{text:"SP = CP",type:"misinterpretation"},{text:"There's no money",type:"guessing"}], explanation:"Loss = sell for less than cost.", solutionSteps:["SP < CP → loss.","Loss = CP − SP."], shortcut:"SP < CP = loss.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_bs_q8", topicId:"math4_ch6_buying_selling", text:"Loss of ₹30 when CP is ₹500. SP?", options:[{text:"₹530",type:"concept_error"},{text:"₹470",type:"correct"},{text:"₹530",type:"calculation_error"},{text:"₹500",type:"misinterpretation"}], explanation:"SP = CP − Loss = 500 − 30 = ₹470.", solutionSteps:["SP = CP − Loss.","500 − 30 = 470."], shortcut:"Loss means SP < CP.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },

  // math4_ch6_change_money — 8 Qs
  { questionId:"math4_ch6_cm_q1", topicId:"math4_ch6_change_money", text:"Cost ₹78, paid ₹100. Change?", options:[{text:"₹178",type:"misinterpretation"},{text:"₹22",type:"correct"},{text:"₹78",type:"misinterpretation"},{text:"₹32",type:"calculation_error"}], explanation:"Change = paid − cost = 100 − 78 = ₹22.", solutionSteps:["100 − 78 = 22."], shortcut:"Change = paid − cost.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_cm_q2", topicId:"math4_ch6_change_money", text:"Change = ?", options:[{text:"Cost + Paid",type:"concept_error"},{text:"Paid − Cost",type:"correct"},{text:"Cost − Paid",type:"misinterpretation"},{text:"Cost × Paid",type:"calculation_error"}], explanation:"Change = money paid − money owed.", solutionSteps:["Change = paid − cost."], shortcut:"Change = paid − cost.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_cm_q3", topicId:"math4_ch6_change_money", text:"Cost ₹45, paid ₹50. Change?", options:[{text:"₹5",type:"correct"},{text:"₹95",type:"misinterpretation"},{text:"₹15",type:"calculation_error"},{text:"₹4",type:"calculation_error"}], explanation:"50 − 45 = ₹5.", solutionSteps:["50 − 45 = 5."], shortcut:"Paid − cost.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_cm_q4", topicId:"math4_ch6_change_money", text:"Cost ₹250, paid ₹500. Change?", options:[{text:"₹750",type:"misinterpretation"},{text:"₹250",type:"correct"},{text:"₹125",type:"calculation_error"},{text:"₹150",type:"calculation_error"}], explanation:"500 − 250 = ₹250.", solutionSteps:["500 − 250 = 250."], shortcut:"Half of 500 = 250.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_cm_q5", topicId:"math4_ch6_change_money", text:"If paid exactly the cost, change = ?", options:[{text:"₹1",type:"concept_error"},{text:"₹0",type:"correct"},{text:"Full cost",type:"misinterpretation"},{text:"Cannot be determined",type:"guessing"}], explanation:"Paid = cost → change = 0.", solutionSteps:["Paid = cost.","Change = 0."], shortcut:"Exact payment = no change.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_cm_q6", topicId:"math4_ch6_change_money", text:"Cost ₹120, paid ₹200. Change?", options:[{text:"₹320",type:"misinterpretation"},{text:"₹80",type:"correct"},{text:"₹120",type:"calculation_error"},{text:"₹100",type:"calculation_error"}], explanation:"200 − 120 = ₹80.", solutionSteps:["200 − 120 = 80."], shortcut:"Subtract cost.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_cm_q7", topicId:"math4_ch6_change_money", text:"Cost ₹3 + ₹5 + ₹2, paid ₹20. Change?", options:[{text:"₹10",type:"correct"},{text:"₹15",type:"calculation_error"},{text:"₹5",type:"calculation_error"},{text:"₹30",type:"misinterpretation"}], explanation:"Total cost = 10. Change = 20 − 10 = ₹10.", solutionSteps:["Total cost: 3+5+2 = 10.","Change: 20 − 10 = 10."], shortcut:"First total, then subtract.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_cm_q8", topicId:"math4_ch6_change_money", text:"Cost ₹98, paid ₹100. Change?", options:[{text:"₹98",type:"misinterpretation"},{text:"₹2",type:"correct"},{text:"₹198",type:"misinterpretation"},{text:"₹10",type:"calculation_error"}], explanation:"100 − 98 = ₹2.", solutionSteps:["100 − 98 = 2."], shortcut:"Quick mental: 100 − 98 = 2.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },

  // math4_ch6_money_word_problems — 8 Qs
  { questionId:"math4_ch6_mw_q1", topicId:"math4_ch6_money_word_problems", text:"Mom has ₹500. Buys 3 books at ₹120 each. Money left?", options:[{text:"₹260",type:"calculation_error"},{text:"₹140",type:"correct"},{text:"₹380",type:"calculation_error"},{text:"₹360",type:"calculation_error"}], explanation:"Total spent: 3×120 = 360. Left: 500 − 360 = ₹140.", solutionSteps:["3 × 120 = 360.","500 − 360 = 140."], shortcut:"Multi-step: × then −.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mw_q2", topicId:"math4_ch6_money_word_problems", text:"Apples ₹40/kg. Cost of 5 kg?", options:[{text:"₹45",type:"misinterpretation"},{text:"₹200",type:"correct"},{text:"₹8",type:"calculation_error"},{text:"₹220",type:"calculation_error"}], explanation:"5 × 40 = ₹200.", solutionSteps:["5 × 40 = 200."], shortcut:"Quantity × per-unit.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mw_q3", topicId:"math4_ch6_money_word_problems", text:"Riya has ₹350. Spends ₹125 on a book and ₹85 on a pen. Money left?", options:[{text:"₹560",type:"misinterpretation"},{text:"₹140",type:"correct"},{text:"₹125",type:"calculation_error"},{text:"₹100",type:"calculation_error"}], explanation:"Spent: 125 + 85 = 210. Left: 350 − 210 = ₹140.", solutionSteps:["Total spent: 125 + 85 = 210.","Left: 350 − 210 = 140."], shortcut:"Add expenses, subtract from start.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mw_q4", topicId:"math4_ch6_money_word_problems", text:"4 friends share ₹200 equally. Each gets…", options:[{text:"₹40",type:"calculation_error"},{text:"₹50",type:"correct"},{text:"₹80",type:"calculation_error"},{text:"₹800",type:"misinterpretation"}], explanation:"200 ÷ 4 = ₹50.", solutionSteps:["200 ÷ 4 = 50."], shortcut:"Total ÷ people.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mw_q5", topicId:"math4_ch6_money_word_problems", text:"A toy costs ₹65 each. With ₹300, how many toys can be bought?", options:[{text:"3",type:"calculation_error"},{text:"4",type:"correct"},{text:"5",type:"calculation_error"},{text:"7",type:"misinterpretation"}], explanation:"300 ÷ 65 ≈ 4 (with ₹40 left over).", solutionSteps:["300 ÷ 65: 4 × 65 = 260.","4 toys, ₹40 left."], shortcut:"Total ÷ price, take whole part.", difficulty:"hard", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mw_q6", topicId:"math4_ch6_money_word_problems", text:"Bus ticket ₹15 each way. Round trip cost?", options:[{text:"₹15",type:"concept_error"},{text:"₹30",type:"correct"},{text:"₹45",type:"calculation_error"},{text:"₹150",type:"misinterpretation"}], explanation:"Round trip = 2 × 15 = ₹30.", solutionSteps:["2 × 15 = 30."], shortcut:"Round trip = × 2.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mw_q7", topicId:"math4_ch6_money_word_problems", text:"A pen costs ₹12. Buying 3, the discount is ₹6 off total. Final cost?", options:[{text:"₹30",type:"correct"},{text:"₹36",type:"calculation_error"},{text:"₹42",type:"calculation_error"},{text:"₹6",type:"misinterpretation"}], explanation:"3×12 = 36. − 6 discount = ₹30.", solutionSteps:["3 × 12 = 36.","36 − 6 = 30."], shortcut:"Total then subtract discount.", difficulty:"medium", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
  { questionId:"math4_ch6_mw_q8", topicId:"math4_ch6_money_word_problems", text:"A man earns ₹400/day. Earnings in 7 days?", options:[{text:"₹407",type:"misinterpretation"},{text:"₹2800",type:"correct"},{text:"₹4000",type:"calculation_error"},{text:"₹407",type:"calculation_error"}], explanation:"7 × 400 = ₹2800.", solutionSteps:["7 × 400 = 2800."], shortcut:"Days × per-day.", difficulty:"easy", subject:"Mathematics", grade:"4", chapter:"The Junk Seller" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 4 Math v2 questions (Ch5-6).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
