/**
 * Seed: CBSE Class 10 English — 30 practice questions
 * Topics: First Flight (prose/poems), Grammar (Tenses, Voice), Writing (Letter)
 * Safe to re-run — skips duplicates on { questionText, subject }
 *
 * Usage:
 *   cd ai-learning-backend/backend
 *   node config/seedEnglishQuestions.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const QUESTIONS = [
  // ── 1. First Flight — A Letter to God (5 questions) ─────────────────────────
  {
    topic: "First Flight — A Letter to God",
    subtopic: "Comprehension",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In 'A Letter to God', the story is set in a valley. What crop did Lencho grow?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Wheat and corn", type: "correct", logicTag: "" },
      { text: "Rice and sugarcane", type: "concept_error", logicTag: "wrong_crop_details" },
      { text: "Cotton and tobacco", type: "concept_error", logicTag: "unrelated_crops" },
      { text: "Barley and millet", type: "guessing", logicTag: "surface_guess" },
    ],
    solutionSteps: [
      "Lencho was a farmer who lived in a valley and grew crops of corn and wheat.",
      "He was eagerly awaiting rain for a good harvest.",
      "A sudden hailstorm destroyed his entire crop.",
    ],
    shortcut: "Lencho grew corn and wheat. Hailstorm destroyed everything. He wrote to God for 100 pesos.",
  },
  {
    topic: "First Flight — A Letter to God",
    subtopic: "Comprehension",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Why did Lencho call the post office employees 'a bunch of crooks'?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "They refused to deliver his letter to God", type: "concept_error", logicTag: "incorrect_reason" },
      { text: "He received only 70 pesos instead of the 100 pesos he had asked for", type: "correct", logicTag: "" },
      { text: "They opened and read his private letter", type: "partial_logic", logicTag: "partly_true_but_not_reason" },
      { text: "They sent him fake money", type: "concept_error", logicTag: "invented_detail" },
    ],
    solutionSteps: [
      "Lencho had asked God for 100 pesos. The post office employees collected money and sent 70 pesos.",
      "Lencho, being deeply religious, believed God would send exactly 100 pesos.",
      "He assumed the missing 30 pesos must have been stolen by the post office employees.",
    ],
    shortcut: "Asked 100, got 70 → Lencho blamed post office employees (crooks). Irony: they were generous, he was ungrateful.",
  },
  {
    topic: "First Flight — A Letter to God",
    subtopic: "Theme and Message",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the central theme of 'A Letter to God'?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "The destructive power of natural disasters", type: "concept_error", logicTag: "minor_theme_not_central" },
      { text: "Unshakeable faith in God and the irony of human ingratitude", type: "correct", logicTag: "" },
      { text: "The importance of writing letters", type: "concept_error", logicTag: "literal_surface_reading" },
      { text: "The corruption of government postal services", type: "concept_error", logicTag: "misread_moral" },
    ],
    solutionSteps: [
      "Lencho's absolute faith in God drives the entire story — he never doubts God will help.",
      "The irony is that humans (post office employees) show kindness but receive suspicion in return.",
      "The theme contrasts blind faith with practical human goodwill.",
    ],
    shortcut: "Theme = faith + irony. Lencho trusts God absolutely; ironically distrusts the kind humans who helped.",
  },
  {
    topic: "First Flight — A Letter to God",
    subtopic: "Character",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The postmaster decided to help Lencho because:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "He was ordered to do so by the government", type: "concept_error", logicTag: "authority_not_involved" },
      { text: "He did not want to shatter Lencho's faith in God", type: "correct", logicTag: "" },
      { text: "He wanted to test whether Lencho would be grateful", type: "concept_error", logicTag: "motive_invented" },
      { text: "He was a close friend of Lencho's family", type: "guessing", logicTag: "invented_relationship" },
    ],
    solutionSteps: [
      "The postmaster was deeply moved by Lencho's faith when he read the letter.",
      "He collected money from colleagues and contributed from his own salary.",
      "His motivation was to preserve Lencho's unshakeable faith in God.",
    ],
    shortcut: "Postmaster = goodwill, wanted to preserve faith. Outcome = irony (Lencho distrusts him).",
  },
  {
    topic: "First Flight — A Letter to God",
    subtopic: "Language and Style",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The story 'A Letter to God' is originally written in:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "English", type: "concept_error", logicTag: "assumed_original_language" },
      { text: "Spanish", type: "correct", logicTag: "" },
      { text: "Portuguese", type: "concept_error", logicTag: "related_language_guessed" },
      { text: "French", type: "guessing", logicTag: "random_european_language" },
    ],
    solutionSteps: [
      "The story was written by Mexican author G.L. Fuentes (Gregorio López y Fuentes) in Spanish.",
      "The English version in the textbook is a translation.",
      "The setting — a valley in Mexico — is consistent with a Spanish-language original.",
    ],
    shortcut: "Author = G.L. Fuentes (Mexican). Original language = Spanish. Story is a translation.",
  },

  // ── 2. First Flight — Nelson Mandela: Long Walk to Freedom (5 questions) ────
  {
    topic: "First Flight — Nelson Mandela: Long Walk to Freedom",
    subtopic: "Comprehension",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What did Nelson Mandela notice about the two national anthems at his inauguration?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Only the ANC anthem was sung as a mark of victory", type: "concept_error", logicTag: "partial_ceremony_misread" },
      { text: "Both the old anthem (Nkosi Sikelel' iAfrika) and the new national anthem were sung", type: "correct", logicTag: "" },
      { text: "The anthem was changed entirely to an English song", type: "concept_error", logicTag: "invented_detail" },
      { text: "There was no anthem because the ceremony was too short", type: "guessing", logicTag: "fabricated_claim" },
    ],
    solutionSteps: [
      "At the inauguration, two anthems were sung: the old anthem representing white South Africa, and the new ANC anthem.",
      "This symbolised reconciliation and the unity of the new rainbow nation.",
      "Mandela saw this as a sign that two nations were becoming one.",
    ],
    shortcut: "Two anthems = two nations becoming one. Symbol of reconciliation at inauguration.",
  },
  {
    topic: "First Flight — Nelson Mandela: Long Walk to Freedom",
    subtopic: "Theme",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "According to Mandela, what is the greatest wealth of South Africa?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Its gold and diamond mines", type: "concept_error", logicTag: "material_wealth_confused_with_human" },
      { text: "Its people", type: "correct", logicTag: "" },
      { text: "Its geographical diversity", type: "concept_error", logicTag: "landscape_confused" },
      { text: "Its military strength", type: "guessing", logicTag: "invented_detail" },
    ],
    solutionSteps: [
      "Mandela declares that South Africa's greatest wealth is its people — its human resources.",
      "He emphasises the courage and generosity of the South African people.",
      "This reflects his belief in the humanity and dignity of all people regardless of race.",
    ],
    shortcut: "Greatest wealth = its people (not gold/diamonds). Mandela values human dignity above material wealth.",
  },
  {
    topic: "First Flight — Nelson Mandela: Long Walk to Freedom",
    subtopic: "Character and Values",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Mandela says that the oppressor must be liberated just as the oppressed. What does he mean?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "The oppressor should be punished so that both sides can be free", type: "concept_error", logicTag: "revenge_logic_applied" },
      { text: "Prejudice and hatred cage the oppressor too — true freedom requires liberating both from hate", type: "correct", logicTag: "" },
      { text: "Only the oppressed need liberation; the oppressor is already free", type: "concept_error", logicTag: "literal_reading_only" },
      { text: "Both sides should leave South Africa", type: "concept_error", logicTag: "completely_wrong_interpretation" },
    ],
    solutionSteps: [
      "Mandela argues that the oppressor loses his humanity when he oppresses others.",
      "The oppressor is imprisoned by fear, prejudice, and the need to maintain control.",
      "True freedom can only exist when both oppressor and oppressed are freed from hatred.",
    ],
    shortcut: "Oppressor = also caged by prejudice and fear. True freedom = mutual liberation from hate.",
  },
  {
    topic: "First Flight — Nelson Mandela: Long Walk to Freedom",
    subtopic: "Autobiography",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "How long was Nelson Mandela imprisoned on Robben Island?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "10 years", type: "concept_error", logicTag: "underestimated" },
      { text: "27 years", type: "correct", logicTag: "" },
      { text: "35 years", type: "calculation_error", logicTag: "overestimated" },
      { text: "15 years", type: "concept_error", logicTag: "guessed_round_number" },
    ],
    solutionSteps: [
      "Mandela was imprisoned in 1964 and released in 1990 — a total of 27 years.",
      "Most of this time was spent on Robben Island.",
      "Despite imprisonment, his spirit and fight for freedom never broke.",
    ],
    shortcut: "Mandela imprisoned 1964–1990 = 27 years. Mostly on Robben Island.",
  },
  {
    topic: "First Flight — Nelson Mandela: Long Walk to Freedom",
    subtopic: "Theme",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What twin obligations does Mandela describe in the chapter?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Obligation to work hard and obligation to pay taxes", type: "concept_error", logicTag: "civic_duty_confused" },
      { text: "Obligation to family/community and obligation to one's people/nation", type: "correct", logicTag: "" },
      { text: "Obligation to God and obligation to the government", type: "concept_error", logicTag: "religious_civic_confused" },
      { text: "Obligation to self-improvement and obligation to earn wealth", type: "guessing", logicTag: "personal_goals_substituted" },
    ],
    solutionSteps: [
      "Mandela describes every man as having two obligations: to his family, parents, wife, and children; and to his people, his community, his country.",
      "In South Africa under apartheid, fulfilling the second obligation made him an outlaw.",
      "He chose country over personal safety — this defines his character.",
    ],
    shortcut: "Twin obligations: family duty + national duty. Apartheid made national duty illegal → he became an outlaw.",
  },

  // ── 3. First Flight — Two Stories About Flying (5 questions) ────────────────
  {
    topic: "First Flight — Two Stories About Flying",
    subtopic: "His First Flight — Comprehension",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In 'His First Flight', why was the young seagull afraid to fly?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "He had a broken wing", type: "concept_error", logicTag: "physical_injury_invented" },
      { text: "He was afraid that his wings would not support him over the vast expanse of sea", type: "correct", logicTag: "" },
      { text: "He had never seen other birds fly before", type: "concept_error", logicTag: "inexperience_confused_with_fear" },
      { text: "His parents forbade him from flying", type: "concept_error", logicTag: "parental_restriction_invented" },
    ],
    solutionSteps: [
      "The young seagull feared that the sea was too vast and his wings would not support him.",
      "His siblings had already flown but he stood frozen at the ledge, unable to take the leap.",
      "His mother used hunger (by dangling a piece of fish) to force him off the ledge.",
    ],
    shortcut: "Fear = wings won't support him over the sea. Hunger forced him to jump → he flew.",
  },
  {
    topic: "First Flight — Two Stories About Flying",
    subtopic: "His First Flight — Theme",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the central message of 'His First Flight'?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Young birds should obey their parents at all times", type: "concept_error", logicTag: "obedience_theme_misread" },
      { text: "Fear and self-doubt hold us back; courage and trust in oneself lead to success", type: "correct", logicTag: "" },
      { text: "Only hunger can motivate anyone to achieve great things", type: "concept_error", logicTag: "literal_reading_only" },
      { text: "Flying is a skill that must be taught formally", type: "concept_error", logicTag: "surface_interpretation" },
    ],
    solutionSteps: [
      "The seagull's fear was entirely mental — his wings were perfectly capable.",
      "Once he took the leap (forced by hunger), he discovered his natural ability.",
      "The message: self-doubt is the real obstacle; action reveals capability.",
    ],
    shortcut: "Theme = overcoming fear/self-doubt. The seagull had ability all along — fear was the only barrier.",
  },
  {
    topic: "First Flight — Two Stories About Flying",
    subtopic: "Black Aeroplane — Comprehension",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In 'The Black Aeroplane', the pilot was flying from:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "London to Paris", type: "concept_error", logicTag: "direction_reversed" },
      { text: "Paris to England (London)", type: "correct", logicTag: "" },
      { text: "New York to London", type: "concept_error", logicTag: "transatlantic_confused" },
      { text: "India to England", type: "guessing", logicTag: "irrelevant_route" },
    ],
    solutionSteps: [
      "The pilot was returning home to England from France (Paris).",
      "He was excited about having breakfast with his family in England.",
      "He encountered a massive storm over the mountains of France.",
    ],
    shortcut: "Paris → England. Storm over mountains. Mystery black aeroplane guided him through clouds.",
  },
  {
    topic: "First Flight — Two Stories About Flying",
    subtopic: "Black Aeroplane — Theme",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The mystery in 'The Black Aeroplane' is that:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "The pilot's radio and compass stopped working", type: "partial_logic", logicTag: "problem_not_mystery" },
      { text: "The black aeroplane that guided him had no record — neither control nor the pilot saw it", type: "correct", logicTag: "" },
      { text: "The pilot landed in the wrong country", type: "concept_error", logicTag: "invented_ending" },
      { text: "The storm suddenly disappeared without explanation", type: "concept_error", logicTag: "different_aspect_confused" },
    ],
    solutionSteps: [
      "The pilot was guided through a storm by an unknown black aeroplane.",
      "When he asked the control tower who had guided him, they said no other aircraft was flying that night.",
      "The mystery remains unsolved — was it real, imagined, or supernatural?",
    ],
    shortcut: "Mystery = the black aeroplane had no record, no pilot, no existence. Control tower saw nothing.",
  },
  {
    topic: "First Flight — Two Stories About Flying",
    subtopic: "His First Flight — Character",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "How did the young seagull's family react when he successfully flew and landed on the sea?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "They ignored him and flew away", type: "concept_error", logicTag: "indifferent_family_invented" },
      { text: "They screamed with joy, praising and swimming around him", type: "correct", logicTag: "" },
      { text: "They scolded him for taking so long to fly", type: "concept_error", logicTag: "negative_reaction_invented" },
      { text: "They were busy eating and did not notice", type: "guessing", logicTag: "distracted_family_invented" },
    ],
    solutionSteps: [
      "When the seagull landed on the sea, his whole family landed around him.",
      "They screamed with delight, praised him, and offered him pieces of fish.",
      "This celebration shows the family's love and relief after his achievement.",
    ],
    shortcut: "Family = joyful. They screamed with delight, offered fish, praised him warmly.",
  },

  // ── 4. Grammar — Tenses (5 questions) ───────────────────────────────────────
  {
    topic: "Grammar — Tenses",
    subtopic: "Simple Present",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Choose the correct tense: 'She ___ to school every day.'",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "goes", type: "correct", logicTag: "" },
      { text: "go", type: "concept_error", logicTag: "subject_verb_agreement_missed" },
      { text: "is going", type: "concept_error", logicTag: "present_continuous_instead_of_simple" },
      { text: "went", type: "concept_error", logicTag: "past_instead_of_present" },
    ],
    solutionSteps: [
      "The sentence describes a habitual action (every day) → use Simple Present tense.",
      "Subject 'She' is third person singular → verb gets '-s': goes.",
      "'Is going' would be used for an action happening right now, not a habit.",
    ],
    shortcut: "Habitual action = Simple Present. He/She/It → add -s/es. Every day, always, usually are clue words.",
  },
  {
    topic: "Grammar — Tenses",
    subtopic: "Present Perfect",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Identify the correct sentence using Present Perfect tense:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "She has went to the market.", type: "concept_error", logicTag: "wrong_past_participle" },
      { text: "She has gone to the market.", type: "correct", logicTag: "" },
      { text: "She is gone to the market.", type: "concept_error", logicTag: "is_instead_of_has" },
      { text: "She have gone to the market.", type: "concept_error", logicTag: "wrong_auxiliary_for_she" },
    ],
    solutionSteps: [
      "Present Perfect = has/have + past participle.",
      "Subject 'She' → has. Past participle of 'go' = 'gone' (not 'went').",
      "'Went' is simple past; 'gone' is past participle — these are different forms.",
    ],
    shortcut: "Present Perfect = has/have + V3 (past participle). She has GONE (not went).",
  },
  {
    topic: "Grammar — Tenses",
    subtopic: "Past Continuous",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Choose the correct form: 'When I arrived, they ___ dinner.'",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "had dinner", type: "concept_error", logicTag: "simple_past_not_continuous" },
      { text: "were having", type: "correct", logicTag: "" },
      { text: "had been having", type: "concept_error", logicTag: "past_perfect_continuous_overcomplicated" },
      { text: "have had", type: "concept_error", logicTag: "present_perfect_wrong_tense" },
    ],
    solutionSteps: [
      "The action 'having dinner' was in progress when I arrived → Past Continuous.",
      "Past Continuous = was/were + V-ing.",
      "They (plural) → were having.",
    ],
    shortcut: "Action in progress when another action interrupted = Past Continuous (was/were + V-ing).",
  },
  {
    topic: "Grammar — Tenses",
    subtopic: "Future Tense",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which sentence correctly expresses a future plan?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "I will going to visit Delhi next week.", type: "concept_error", logicTag: "double_future_marker" },
      { text: "I am going to visit Delhi next week.", type: "correct", logicTag: "" },
      { text: "I go to visit Delhi next week.", type: "concept_error", logicTag: "simple_present_for_future" },
      { text: "I was going to visit Delhi next week.", type: "concept_error", logicTag: "past_tense_for_future" },
    ],
    solutionSteps: [
      "'Going to + infinitive' expresses a definite future plan or intention.",
      "'Will' expresses spontaneous decisions or predictions — not plans made in advance.",
      "'I am going to visit' = a planned future action.",
    ],
    shortcut: "Future plan = am/is/are + going to + V1. Spontaneous/prediction = will + V1.",
  },
  {
    topic: "Grammar — Tenses",
    subtopic: "Tense Identification",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Identify the tense in: 'By the time she arrived, he had already left.'",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.72,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Simple Past in both clauses", type: "concept_error", logicTag: "tense_shift_ignored" },
      { text: "Simple Past (arrived) and Past Perfect (had left)", type: "correct", logicTag: "" },
      { text: "Past Continuous (was arriving) and Simple Past (left)", type: "concept_error", logicTag: "wrong_identification" },
      { text: "Past Perfect in both clauses", type: "concept_error", logicTag: "over-applied_past_perfect" },
    ],
    solutionSteps: [
      "'She arrived' = Simple Past (a completed past action).",
      "'He had already left' = Past Perfect (an action completed before another past action).",
      "Past Perfect marks the earlier of two past events: he left first, then she arrived.",
    ],
    shortcut: "Past Perfect (had + V3) shows the earlier of two past events. Use when one past action precedes another.",
  },

  // ── 5. Grammar — Voice (Active/Passive) (5 questions) ───────────────────────
  {
    topic: "Grammar — Voice (Active/Passive)",
    subtopic: "Passive Voice Transformation",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Change to passive voice: 'The teacher praised the student.'",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.25,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "The student is praised by the teacher.", type: "concept_error", logicTag: "present_tense_used" },
      { text: "The student was praised by the teacher.", type: "correct", logicTag: "" },
      { text: "The student has been praised by the teacher.", type: "concept_error", logicTag: "present_perfect_used" },
      { text: "The student praised the teacher.", type: "concept_error", logicTag: "subject_object_not_swapped" },
    ],
    solutionSteps: [
      "Active: The teacher (subject) praised (verb, Simple Past) the student (object).",
      "Passive: Object → Subject. Verb = was/were + past participle.",
      "Simple Past Active → was/were + V3 Passive: 'The student was praised by the teacher.'",
    ],
    shortcut: "Active to Passive: Object + was/were + V3 + by + Subject. Match tense carefully.",
  },
  {
    topic: "Grammar — Voice (Active/Passive)",
    subtopic: "Active Voice Transformation",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Change to active voice: 'The letter was written by Priya.'",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Priya writes the letter.", type: "concept_error", logicTag: "present_tense_wrong" },
      { text: "Priya wrote the letter.", type: "correct", logicTag: "" },
      { text: "Priya has written the letter.", type: "concept_error", logicTag: "present_perfect_wrong" },
      { text: "The letter writes Priya.", type: "concept_error", logicTag: "subject_object_confused" },
    ],
    solutionSteps: [
      "Passive: The letter (subject) was written (passive verb) by Priya (agent).",
      "Active: Agent → Subject. 'was written' (past passive) → 'wrote' (Simple Past active).",
      "Active: Priya wrote the letter.",
    ],
    shortcut: "Passive to Active: Agent becomes Subject, passive object becomes object. was+V3 → Simple Past.",
  },
  {
    topic: "Grammar — Voice (Active/Passive)",
    subtopic: "Passive Voice — Modal Verbs",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Change to passive: 'You must complete this task.'",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "This task was completed by you.", type: "concept_error", logicTag: "modal_dropped" },
      { text: "This task must be completed by you.", type: "correct", logicTag: "" },
      { text: "This task should be completed by you.", type: "concept_error", logicTag: "modal_changed" },
      { text: "This task must have been completed by you.", type: "concept_error", logicTag: "modal_perfect_over-applied" },
    ],
    solutionSteps: [
      "With modal verbs: Modal + be + past participle.",
      "'Must complete' → 'must be completed'.",
      "Object 'this task' becomes subject. Agent 'you' goes after 'by'.",
    ],
    shortcut: "Modal passive = Modal + be + V3. Must do → must be done. Can do → can be done.",
  },
  {
    topic: "Grammar — Voice (Active/Passive)",
    subtopic: "Identifying Voice",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is in passive voice?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Ram eats mangoes.", type: "concept_error", logicTag: "active_voice" },
      { text: "Mangoes are eaten by Ram.", type: "correct", logicTag: "" },
      { text: "Ram will eat mangoes.", type: "concept_error", logicTag: "future_active" },
      { text: "Ram is eating mangoes.", type: "concept_error", logicTag: "present_continuous_active" },
    ],
    solutionSteps: [
      "Passive voice: the subject receives the action instead of performing it.",
      "'Mangoes are eaten by Ram' — 'Mangoes' (object) is now the subject; action is performed on it.",
      "Structure: is/are/was/were + past participle = passive.",
    ],
    shortcut: "Passive = Subject + is/am/are/was/were + V3. The subject is acted upon, not acting.",
  },
  {
    topic: "Grammar — Voice (Active/Passive)",
    subtopic: "Passive Voice — Present Continuous",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Change to passive: 'The workers are building a new bridge.'",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "A new bridge is built by the workers.", type: "concept_error", logicTag: "continuous_aspect_dropped" },
      { text: "A new bridge is being built by the workers.", type: "correct", logicTag: "" },
      { text: "A new bridge was being built by the workers.", type: "concept_error", logicTag: "past_instead_of_present" },
      { text: "A new bridge has been built by the workers.", type: "concept_error", logicTag: "present_perfect_used" },
    ],
    solutionSteps: [
      "Active: Present Continuous = is/are + V-ing.",
      "Passive of Present Continuous = is/are + being + past participle.",
      "'are building' → 'is being built' (object 'a new bridge' is singular → 'is').",
    ],
    shortcut: "Present Continuous Passive = is/am/are + being + V3. 'Are building' → 'is being built'.",
  },

  // ── 6. Writing — Letter Writing (5 questions) ────────────────────────────────
  {
    topic: "Writing — Letter Writing",
    subtopic: "Formal Letter Format",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In a formal letter, which salutation is most appropriate when writing to the Editor of a newspaper?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "My dear friend,", type: "concept_error", logicTag: "informal_salutation" },
      { text: "Sir / Madam,", type: "correct", logicTag: "" },
      { text: "Hey Editor,", type: "concept_error", logicTag: "casual_informal" },
      { text: "To whom it may concern,", type: "concept_error", logicTag: "used_when_name_unknown_formal_ok_but_less_specific" },
    ],
    solutionSteps: [
      "Formal letters to editors use 'Sir' or 'Madam' as the salutation.",
      "'My dear friend' and 'Hey' are informal and inappropriate for official correspondence.",
      "'To whom it may concern' is acceptable but 'Sir/Madam' is standard for CBSE format.",
    ],
    shortcut: "Formal letter salutation = Sir/Madam. Informal = Dear [name]. Never use 'Hey' in formal writing.",
  },
  {
    topic: "Writing — Letter Writing",
    subtopic: "Formal Letter Format",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the correct order of components in a formal letter?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Subject → Salutation → Body → Sender's address → Date", type: "concept_error", logicTag: "completely_scrambled" },
      { text: "Sender's address → Date → Receiver's address → Subject → Salutation → Body → Complimentary close → Signature", type: "correct", logicTag: "" },
      { text: "Date → Sender's address → Subject → Body → Salutation → Signature", type: "concept_error", logicTag: "order_wrong" },
      { text: "Receiver's address → Date → Sender's address → Body → Signature", type: "concept_error", logicTag: "addresses_reversed" },
    ],
    solutionSteps: [
      "CBSE formal letter format: Sender's address → Date → Receiver's address → Subject → Salutation → Body → Complimentary close → Signature.",
      "Sender's address comes first (top left or right). Date follows the sender's address.",
      "Subject line summarises the purpose of the letter before the salutation.",
    ],
    shortcut: "SA → D → RA → Sub → Sal → Body → CC → Sign. (Sender, Date, Receiver, Subject, Salutation, Body, Close, Sign)",
  },
  {
    topic: "Writing — Letter Writing",
    subtopic: "Informal Letter",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In an informal letter to a friend, which complimentary close is appropriate?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Yours faithfully,", type: "concept_error", logicTag: "formal_close_used" },
      { text: "Yours sincerely,", type: "concept_error", logicTag: "semi_formal_close_used" },
      { text: "With love / Your friend,", type: "correct", logicTag: "" },
      { text: "Respectfully,", type: "concept_error", logicTag: "overly_formal_for_friend" },
    ],
    solutionSteps: [
      "Informal letters to friends use closings like 'With love', 'Your friend', 'Affectionately yours'.",
      "'Yours faithfully' is used in formal letters when the salutation is 'Sir/Madam'.",
      "'Yours sincerely' is used when the salutation names the person (Dear Mr. Sharma).",
    ],
    shortcut: "Faithfully = Sir/Madam (don't know name). Sincerely = Dear [Name]. With love = friend/family.",
  },
  {
    topic: "Writing — Letter Writing",
    subtopic: "Letter to Editor",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A letter to the editor of a newspaper is best described as:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "A personal diary entry shared with the public", type: "concept_error", logicTag: "diary_confused_with_letter" },
      { text: "A formal letter expressing views on a public issue, requesting publication", type: "correct", logicTag: "" },
      { text: "A private complaint letter between two individuals", type: "concept_error", logicTag: "private_nature_misunderstood" },
      { text: "A creative story submitted to the newspaper", type: "concept_error", logicTag: "fiction_confused" },
    ],
    solutionSteps: [
      "A letter to the editor addresses public issues — pollution, safety, civic problems — and requests publication.",
      "It is formal in tone and follows the format: address, date, salutation (Sir), subject, body, close.",
      "The purpose is to voice public concerns or commend/criticise published content.",
    ],
    shortcut: "Letter to editor = formal, public issue, requests publication. Not personal/private.",
  },
  {
    topic: "Writing — Letter Writing",
    subtopic: "Complaint Letter",
    subject: "English",
    grade: "10",
    examBoard: "CBSE",
    questionText: "When writing a complaint letter to a shopkeeper about a defective product, the tone should be:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: false,
    options: [
      { text: "Aggressive and threatening", type: "concept_error", logicTag: "rude_tone_not_appropriate" },
      { text: "Formal, polite, and assertive — clearly stating the problem and requesting remedy", type: "correct", logicTag: "" },
      { text: "Casual and humorous to keep it friendly", type: "concept_error", logicTag: "informal_tone_wrong" },
      { text: "Vague so as not to offend the shopkeeper", type: "concept_error", logicTag: "purpose_of_complaint_defeated" },
    ],
    solutionSteps: [
      "A complaint letter should be formal and polite — the goal is resolution, not confrontation.",
      "State: what was purchased, date, what defect was found, what remedy is expected (refund/replacement).",
      "A threatening or aggressive tone may escalate the situation and is inappropriate.",
    ],
    shortcut: "Complaint letter tone = polite + assertive. Include: product, date, defect, remedy requested.",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  let added = 0, skipped = 0;
  for (const q of QUESTIONS) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    added++;
  }
  console.log(`English questions: ${added} added, ${skipped} skipped`);
  await mongoose.disconnect();
}

seed().catch(console.error);
