/**
 * Seed: CBSE Class 10 English — First Flight Poems Questions (64 MCQs)
 * Topics: eng_ff_ch1_poem … eng_ff_ch8_poem  (8 questions each)
 * Safe to re-run — skips duplicates on { questionText, subject }
 * Usage: node config/seedEnglishQuestionsB.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const Q = [
  // ── eng_ff_ch1_poem — Dust of Snow + Fire and Ice ────────────────────────
  {
    topic: "eng_ff_ch1_poem", topicId: "eng_ff_ch1_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Dust of Snow', what did the crow shake down on the poet?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Dust of snow from a hemlock tree", type: "correct", logicTag: "" },
      { text: "Dry leaves from an oak tree", type: "concept_error", logicTag: "wrong_detail" },
      { text: "Rain drops from a pine tree", type: "concept_error", logicTag: "wrong_detail" },
      { text: "Blossoms from a cherry tree", type: "concept_error", logicTag: "wrong_detail" },
    ],
    solutionSteps: ["A crow sat on a hemlock tree.", "It shook down dust of snow on the poet.", "This simple act changed the poet's mood for the better."],
    shortcut: "Crow + hemlock tree + dust of snow = mood changer. Both crow and hemlock are traditionally considered inauspicious.",
  },
  {
    topic: "eng_ff_ch1_poem", topicId: "eng_ff_ch1_poem",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'Dust of Snow' by Robert Frost?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Small, unexpected moments in nature can transform one's mood and redeem the day", type: "correct", logicTag: "" },
      { text: "Nature is cruel and indifferent to human suffering", type: "concept_error", logicTag: "wrong_theme" },
      { text: "Crows are symbols of bad luck in all cultures", type: "concept_error", logicTag: "too_literal" },
      { text: "Winter makes people feel depressed and lonely", type: "concept_error", logicTag: "misreads_poem" },
    ],
    solutionSteps: ["The poet was in a bad mood ('rued') and felt the day was wasted.", "A crow's action — shaking snow — gave him a moment of joy.", "This tiny natural event changed his entire perspective."],
    shortcut: "Theme = nature's small gifts can redeem a bad day. Unexpected joy from unlikely sources (crow/hemlock).",
  },
  {
    topic: "eng_ff_ch1_poem", topicId: "eng_ff_ch1_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why does Frost choose a crow and a hemlock tree rather than a nightingale and a rose?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "To show that joy can come from even inauspicious or unconventional sources", type: "correct", logicTag: "" },
      { text: "Because crows and hemlocks are common in winter landscapes", type: "partial_logic", logicTag: "surface_reading" },
      { text: "To contrast the ugliness of nature with the beauty of the poet's soul", type: "concept_error", logicTag: "misreads_intent" },
      { text: "Because he disliked romantic imagery", type: "concept_error", logicTag: "biographical_speculation" },
    ],
    solutionSteps: ["Crow = symbol of ill omen in Western culture.", "Hemlock = poisonous plant, associated with death (Socrates).", "Using these 'dark' symbols to generate joy subverts expectations and strengthens the poem's message."],
    shortcut: "Subversion: joy from dark symbols (crow + hemlock). Frost says: beauty/joy can come from anywhere, even ominous things.",
  },
  {
    topic: "eng_ff_ch1_poem", topicId: "eng_ff_ch1_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Fire and Ice', what does 'fire' represent?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Desire and passion", type: "correct", logicTag: "" },
      { text: "War and violence", type: "concept_error", logicTag: "too_literal" },
      { text: "Anger and hatred", type: "partial_logic", logicTag: "secondary_meaning" },
      { text: "The sun's heat causing global warming", type: "concept_error", logicTag: "literal_misread" },
    ],
    solutionSteps: ["Frost uses fire as a metaphor for desire/passion.", "Unchecked desire can destroy just as fire destroys.", "Ice = hatred; both can bring about the end of the world (symbolically, human civilisation)."],
    shortcut: "Fire = desire/passion. Ice = hatred/indifference. Both can destroy the world. Frost sees both as equally dangerous.",
  },
  {
    topic: "eng_ff_ch1_poem", topicId: "eng_ff_ch1_poem",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the speaker's personal opinion in 'Fire and Ice' about which will cause the world's end?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He has experienced desire (fire) and thinks fire will suffice to end the world; ice (hatred) would also do the job", type: "correct", logicTag: "" },
      { text: "He believes ice (cold indifference) is definitely the more dangerous force", type: "concept_error", logicTag: "reversal" },
      { text: "He thinks neither fire nor ice can destroy the world — it is an exaggeration", type: "concept_error", logicTag: "misreads_poem" },
      { text: "He believes God will prevent the world's end", type: "concept_error", logicTag: "not_in_poem" },
    ],
    solutionSteps: ["'From what I've tasted of desire / I hold with those who favour fire.'", "He leans towards fire based on personal experience of desire.", "But he acknowledges ice (hatred) would also suffice for destruction."],
    shortcut: "Speaker votes fire (from personal experience of desire) but admits ice (hatred) is also enough to destroy the world.",
  },
  {
    topic: "eng_ff_ch1_poem", topicId: "eng_ff_ch1_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What poetic device is used in both 'Dust of Snow' and 'Fire and Ice' as a common technique?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Symbolism — nature objects represent abstract human emotions or forces", type: "correct", logicTag: "" },
      { text: "Onomatopoeia — sound words are used extensively", type: "concept_error", logicTag: "wrong_device" },
      { text: "Personification — animals and elements speak as humans", type: "concept_error", logicTag: "partial_yes_but_not_primary" },
      { text: "Repetition — key words are repeated in every stanza", type: "concept_error", logicTag: "wrong_device" },
    ],
    solutionSteps: ["Dust of Snow: crow = unconventional source of joy; snow = hope/renewal.", "Fire and Ice: fire = desire; ice = hatred.", "Both poems use natural images as symbols for abstract ideas."],
    shortcut: "Both Frost poems = symbolism as core device. Nature objects (snow, fire, ice, crow) = human emotions.",
  },
  {
    topic: "eng_ff_ch1_poem", topicId: "eng_ff_ch1_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does 'rued' mean in the line 'And saved some part of a day I had rued'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Regretted or felt sorry about", type: "correct", logicTag: "" },
      { text: "Enjoyed and looked forward to", type: "concept_error", logicTag: "antonym_error" },
      { text: "Misunderstood and been confused by", type: "concept_error", logicTag: "wrong_meaning" },
      { text: "Wasted by doing nothing useful", type: "partial_logic", logicTag: "effect_not_meaning" },
    ],
    solutionSteps: ["'Rued' means felt regret or sorrow about something.", "The poet was having a bad, regret-filled day.", "The snow changed that — saved a portion of the day from being entirely wasted."],
    shortcut: "'Rued' = regretted. Poet was having a bad, regretful day. Snow saved part of it.",
  },
  {
    topic: "eng_ff_ch1_poem", topicId: "eng_ff_ch1_poem",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How do 'Dust of Snow' and 'Fire and Ice' together reflect Frost's view of human nature?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Humans are vulnerable to negative emotions (desire, hatred) but also capable of finding redemption in small natural moments", type: "correct", logicTag: "" },
      { text: "Humans are fundamentally evil and will destroy the world", type: "concept_error", logicTag: "too_pessimistic" },
      { text: "Nature is indifferent to human emotions and the two are unconnected", type: "concept_error", logicTag: "contradicts_poems" },
      { text: "Humans can conquer nature through science and technology", type: "concept_error", logicTag: "not_in_poems" },
    ],
    solutionSteps: ["Fire and Ice: Frost acknowledges human destructive tendencies (desire, hatred).", "Dust of Snow: Frost shows nature can lift those same humans out of darkness.", "Together: humans are flawed but redeemable; nature is a healing force."],
    shortcut: "Together: humans = flawed (desire/hatred in F&I) + redeemable (snow lifts mood in DoS). Nature heals.",
  },

  // ── eng_ff_ch2_poem — A Tiger in the Zoo ─────────────────────────────────
  {
    topic: "eng_ff_ch2_poem", topicId: "eng_ff_ch2_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'A Tiger in the Zoo', where should the tiger be according to the poet's vision?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "In the jungle, hunting deer at the water's edge and terrorising villages", type: "correct", logicTag: "" },
      { text: "In a wildlife sanctuary with proper care", type: "concept_error", logicTag: "modern_view_not_poem" },
      { text: "In a circus performing for audiences", type: "concept_error", logicTag: "wrong_vision" },
      { text: "In a national park roaming freely among tourists", type: "concept_error", logicTag: "partial_correct_wrong_context" },
    ],
    solutionSteps: ["The poet imagines the tiger lurking in shadows, hunting deer, snarling at villages.", "This is where the tiger belongs — its natural habitat.", "The zoo is a stark contrast — confinement vs. natural freedom."],
    shortcut: "Tiger should be: jungle, hunting deer, lurking shadows, terrorising villages. Zoo = unnatural prison by contrast.",
  },
  {
    topic: "eng_ff_ch2_poem", topicId: "eng_ff_ch2_poem",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'A Tiger in the Zoo'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The cruelty of captivity and the suppressed rage of wild animals denied their natural freedom", type: "correct", logicTag: "" },
      { text: "The importance of zoos in conserving endangered species", type: "concept_error", logicTag: "misreads_poem" },
      { text: "The tiger's contentment with zoo life after initial adjustment", type: "concept_error", logicTag: "contradicts_poem" },
      { text: "The fear that tigers inspire in human beings", type: "concept_error", logicTag: "secondary_element" },
    ],
    solutionSteps: ["The tiger is caged, walking in 'few steps of his cage.'", "He ignores visitors and stares at stars — longing for freedom.", "His quiet fury ('locked in a concrete cell') suggests suppressed rage and helplessness."],
    shortcut: "Theme = captivity vs freedom. Tiger's quiet rage + staring at stars = suppressed longing. Zoo = cruel confinement.",
  },
  {
    topic: "eng_ff_ch2_poem", topicId: "eng_ff_ch2_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the tiger's act of staring at the stars at night symbolise?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "His longing for freedom, the wild, and the vastness that has been taken from him", type: "correct", logicTag: "" },
      { text: "His natural nocturnal behaviour of hunting by moonlight", type: "concept_error", logicTag: "literal_misread" },
      { text: "His boredom and inability to sleep in the zoo", type: "partial_logic", logicTag: "surface_reading" },
      { text: "His admiration for the beauty of the night sky", type: "concept_error", logicTag: "romantic_misread" },
    ],
    solutionSteps: ["Stars = vast, unreachable, free.", "The tiger staring at stars while locked in a cage contrasts confinement with infinite freedom.", "It symbolises his suppressed longing for the wild."],
    shortcut: "Stars = freedom/vastness. Locked tiger staring at stars = yearning for the wild. Contrast: cage vs. infinity.",
  },
  {
    topic: "eng_ff_ch2_poem", topicId: "eng_ff_ch2_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does 'velvet quiet rage' mean in the poem 'A Tiger in the Zoo'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A silent, hidden fury that is soft on the outside but intense within — controlled but palpable", type: "correct", logicTag: "" },
      { text: "The tiger is gentle and has no real anger left after years in captivity", type: "concept_error", logicTag: "misreads_oxymoron" },
      { text: "The tiger's fur looks soft like velvet when it is angry", type: "concept_error", logicTag: "literal_misread" },
      { text: "The tiger sleeps quietly, all rage subdued by zoo conditions", type: "concept_error", logicTag: "wrong_reading" },
    ],
    solutionSteps: ["'Velvet' = soft, silent. 'Rage' = intense anger. An oxymoron.", "The rage is not expressed loudly — it is suppressed, quiet, but deep.", "This tension between softness and fury is the tiger's condition in captivity."],
    shortcut: "'Velvet quiet rage' = oxymoron. Silent on surface, burning inside. Captivity suppresses but doesn't extinguish his fury.",
  },
  {
    topic: "eng_ff_ch2_poem", topicId: "eng_ff_ch2_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How does the tiger in the zoo react to the visitors and the patrolling guards?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He ignores them — he does not notice the visitors and hears the patrolling cars without flinching", type: "correct", logicTag: "" },
      { text: "He growls and shows his teeth to frighten them", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "He paces eagerly hoping they will feed him", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "He tries to escape when the guard passes by", type: "concept_error", logicTag: "wrong_reaction" },
    ],
    solutionSteps: ["The tiger ignores the visitors entirely.", "He hears the patrolling car but remains motionless.", "This indifference reflects his dignity and suppressed despair — he has given up."],
    shortcut: "Tiger ignores visitors + guards. His indifference = dignity + despair. Not aggressive — resigned to captivity.",
  },
  {
    topic: "eng_ff_ch2_poem", topicId: "eng_ff_ch2_poem",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What message does the poet Leslie Norris convey about wildlife conservation through this poem?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Zoos, however well-managed, are fundamentally cruel — wild animals belong in their natural habitats, not in cages for human entertainment", type: "correct", logicTag: "" },
      { text: "Zoos are necessary to protect tigers from poachers in the wild", type: "concept_error", logicTag: "contradicts_poem" },
      { text: "Tigers should be trained to live alongside humans peacefully", type: "concept_error", logicTag: "not_in_poem" },
      { text: "Human beings are the real animals because they cage others for amusement", type: "partial_logic", logicTag: "implied_not_stated" },
    ],
    solutionSteps: ["The poem never suggests zoos are good.", "Every image — cage, pacing, staring at stars — shows the animal's pain.", "The implicit message: captivity is cruelty; nature is where wild animals truly belong."],
    shortcut: "Poem's message: captivity = cruelty. Wild animals belong in wild. Zoos deny their identity and freedom.",
  },
  {
    topic: "eng_ff_ch2_poem", topicId: "eng_ff_ch2_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Identify the poetic device in 'He stalks in his vivid stripes'.",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Imagery — creates a vivid visual picture of the tiger's movement and appearance", type: "correct", logicTag: "" },
      { text: "Simile — compares the tiger to something else", type: "concept_error", logicTag: "no_like_as" },
      { text: "Metaphor — the stripes represent prison bars", type: "concept_error", logicTag: "interpretive_leap" },
      { text: "Alliteration — repetition of 's' sounds", type: "partial_logic", logicTag: "secondary_device" },
    ],
    solutionSteps: ["'Vivid stripes' creates a bright, visual image of the tiger.", "The word 'stalks' shows the powerful, deliberate movement.", "Primary device = imagery (visual)."],
    shortcut: "Primary device = imagery. Visual: vivid stripes + stalking = powerful image. Alliteration (s) is secondary.",
  },

  // ── eng_ff_ch3_poem — How to Tell Wild Animals + The Ball Poem ───────────
  {
    topic: "eng_ff_ch3_poem", topicId: "eng_ff_ch3_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'How to Tell Wild Animals', how does the poet suggest you can identify an Asian Lion?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "If a large tawny beast roars at you and eats you, it is an Asian Lion", type: "correct", logicTag: "" },
      { text: "If it has a mane and lives in Africa", type: "concept_error", logicTag: "wrong_clue" },
      { text: "If it purrs softly and has golden fur", type: "concept_error", logicTag: "wrong_clue" },
      { text: "If it charges but stops before reaching you", type: "concept_error", logicTag: "wrong_clue" },
    ],
    solutionSteps: ["The poet humorously says: if a large tawny beast roars terrifically and eats you, then it is an Asian Lion.", "The humour = the observer will not survive to make a note.", "This dark comedy is the poem's key device."],
    shortcut: "Asian Lion = roars terrifically + eats you. Humour: you won't survive to verify. Dark comedy throughout.",
  },
  {
    topic: "eng_ff_ch3_poem", topicId: "eng_ff_ch3_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the primary tone of 'How to Tell Wild Animals'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Humorous and ironic — the identification methods are absurd and involve the observer being killed or eaten", type: "correct", logicTag: "" },
      { text: "Educational and informative — it is a genuine guide to wildlife identification", type: "concept_error", logicTag: "misreads_tone" },
      { text: "Fearful and cautionary — warning children to avoid dangerous animals", type: "concept_error", logicTag: "misreads_tone" },
      { text: "Romantic and appreciative of nature's beauty", type: "concept_error", logicTag: "wrong_tone" },
    ],
    solutionSteps: ["Every 'method' of identification involves the observer being harmed.", "The humour is dark: being eaten, mauled, or strangled is the clue.", "It parodies a field guide, turning a serious format into comedy."],
    shortcut: "Tone = humorous/ironic. Parody of a wildlife guide. Identification = getting killed. Dark comedy.",
  },
  {
    topic: "eng_ff_ch3_poem", topicId: "eng_ff_ch3_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'How to Tell Wild Animals', how does the poet describe the Bengal Tiger?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "It has black stripes on yellow; if it attacks you and doesn't eat you immediately, it is a tiger who is playing with you", type: "correct", logicTag: "" },
      { text: "It has yellow stripes on black and hunts only at night", type: "concept_error", logicTag: "reversed" },
      { text: "It purrs like a cat but is much larger", type: "concept_error", logicTag: "wrong_detail" },
      { text: "It leaps and hugs — and if you survive the hug, it is a bear", type: "concept_error", logicTag: "mixed_up_animals" },
    ],
    solutionSteps: ["'If something black has yellow stripes... 'Tis the Bengal Tiger you've espied.'", "Poet reverses the usual 'yellow with black stripes' description humorously.", "The tiger plays with you ('kills you once or twice') — dark humour again."],
    shortcut: "Bengal Tiger: black with yellow stripes (reversed for humour). 'Plays' with you = mauls repeatedly. Comic.",
  },
  {
    topic: "eng_ff_ch3_poem", topicId: "eng_ff_ch3_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Ball Poem', what does the ball symbolise?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The joys and possessions of childhood that are inevitably lost as one grows up", type: "correct", logicTag: "" },
      { text: "The sport of cricket and the joy of playing games", type: "concept_error", logicTag: "too_literal" },
      { text: "The freedom of childhood against the restrictions of adult life", type: "partial_logic", logicTag: "related_but_not_primary" },
      { text: "The indifference of the universe to human suffering", type: "concept_error", logicTag: "overreach" },
    ],
    solutionSteps: ["The ball rolls into the water and is lost.", "The boy is learning, for the first time, about irretrievable loss.", "The ball represents innocent pleasures and possessions that cannot be recovered once gone."],
    shortcut: "Ball = childhood joys/possessions. Lost = first experience of irreversible loss. Ball can be replaced; innocence cannot.",
  },
  {
    topic: "eng_ff_ch3_poem", topicId: "eng_ff_ch3_poem",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the theme of 'The Ball Poem' by John Berryman?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Learning to cope with loss is an essential part of growing up", type: "correct", logicTag: "" },
      { text: "Adults should always comfort children when they lose things", type: "concept_error", logicTag: "misreads_poet_stance" },
      { text: "Material possessions are unimportant in the larger scheme of life", type: "partial_logic", logicTag: "secondary_message" },
      { text: "Children should be taught to be careful with their toys", type: "concept_error", logicTag: "literal_misread" },
    ],
    solutionSteps: ["The poet says 'I would not intrude on him' — the boy must learn grief alone.", "The loss teaches 'the epistemology of loss.'", "Growing up = accepting that some things are permanently lost; money cannot buy back everything."],
    shortcut: "Theme = learning to accept loss. Poet doesn't interfere — the boy must learn this himself. Crucial growing-up lesson.",
  },
  {
    topic: "eng_ff_ch3_poem", topicId: "eng_ff_ch3_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why does the poet say 'I would not intrude on him' in 'The Ball Poem'?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Because the experience of loss and coming to terms with it must be faced alone — it is a personal rite of passage", type: "correct", logicTag: "" },
      { text: "Because the poet is a stranger and it would be socially inappropriate", type: "concept_error", logicTag: "misses_deeper_meaning" },
      { text: "Because the boy is too young to understand adult consolation", type: "concept_error", logicTag: "partial_logic" },
      { text: "Because comforting the boy would teach him the wrong lesson about loss", type: "partial_logic", logicTag: "closer_but_incomplete" },
    ],
    solutionSteps: ["The poet understands the boy must face this loss himself.", "Intrusion would rob the boy of the formative experience of grief.", "'The epistemology of loss' — knowledge of loss — must be personally felt, not handed over."],
    shortcut: "'Not intrude' = let him grieve alone. Self-discovery of loss is essential. Can't learn it secondhand.",
  },
  {
    topic: "eng_ff_ch3_poem", topicId: "eng_ff_ch3_poem",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How are 'How to Tell Wild Animals' and 'The Ball Poem' different in tone and purpose?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "'How to Tell Wild Animals' is comic and playful; 'The Ball Poem' is serious and meditative on loss and growing up", type: "correct", logicTag: "" },
      { text: "Both are comic poems using animals to make children laugh", type: "concept_error", logicTag: "wrong_characterisation" },
      { text: "Both are serious explorations of nature and wildlife", type: "concept_error", logicTag: "wrong_for_both" },
      { text: "'How to Tell Wild Animals' is serious; 'The Ball Poem' is playful", type: "concept_error", logicTag: "reversed" },
    ],
    solutionSteps: ["'How to Tell Wild Animals' = humour, irony, dark comedy about animal identification.", "'The Ball Poem' = serious meditation on loss, grief, and the painful lessons of growing up.", "The contrast shows the range of poetry — from light comedy to deep philosophy."],
    shortcut: "Contrast: Wild Animals = comedy/parody. Ball Poem = serious/philosophical. Same chapter, opposite tones.",
  },

  // ── eng_ff_ch4_poem — Amanda! ─────────────────────────────────────────────
  {
    topic: "eng_ff_ch4_poem", topicId: "eng_ff_ch4_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Amanda!', what does Amanda imagine herself to be when she is being nagged about sitting straight?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A mermaid moving silently through the sea", type: "correct", logicTag: "" },
      { text: "A princess in a tower", type: "concept_error", logicTag: "different_stanza" },
      { text: "An orphan roaming the streets freely", type: "concept_error", logicTag: "different_stanza" },
      { text: "A bird flying above the clouds", type: "concept_error", logicTag: "wrong_image" },
    ],
    solutionSteps: ["While being told to sit straight and not hunch, Amanda imagines being a mermaid.", "She moves 'languidly' and alone in the sea — free from instructions.", "The contrast: scolding (reality) vs. serene sea (fantasy)."],
    shortcut: "Amanda's escape when told to sit straight = mermaid, moving alone in the sea. Languidly = slowly, freely.",
  },
  {
    topic: "eng_ff_ch4_poem", topicId: "eng_ff_ch4_poem",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'Amanda!' by Robin Klein?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Over-parenting stifles a child's spirit and imagination; children need space to be free", type: "correct", logicTag: "" },
      { text: "Children are naturally disobedient and must be disciplined strictly", type: "concept_error", logicTag: "contradicts_poem_sympathy" },
      { text: "Fantasy is a dangerous escape mechanism for lonely children", type: "concept_error", logicTag: "misreads_theme" },
      { text: "Mothers are always right when they correct their children", type: "concept_error", logicTag: "wrong_perspective" },
    ],
    solutionSteps: ["The poem alternates between the adult's instructions and Amanda's daydreams.", "The reader sympathises with Amanda, not the nagging adult.", "Theme: over-controlled children escape into fantasy; they need freedom, not constant correction."],
    shortcut: "Theme = over-parenting vs. child's spirit. Amanda's daydreams = her rebellion + longing for freedom.",
  },
  {
    topic: "eng_ff_ch4_poem", topicId: "eng_ff_ch4_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Amanda imagine as the 'golden silence' in 'Amanda!'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Being Rapunzel — alone in a high tower with no one to come up and disturb her", type: "correct", logicTag: "" },
      { text: "Being alone on a desert island where no one can find her", type: "concept_error", logicTag: "wrong_stanza" },
      { text: "Being an orphan with no parents to nag her", type: "concept_error", logicTag: "different_stanza" },
      { text: "Floating silently in the ocean without speaking", type: "concept_error", logicTag: "different_stanza" },
    ],
    solutionSteps: ["Amanda imagines being Rapunzel — but importantly, she never lets down her hair.", "No one can climb up; she has perfect, golden silence.", "The irony of Rapunzel: the original uses hair to let someone IN; Amanda's version = uses it to keep everyone OUT."],
    shortcut: "Golden silence = Rapunzel but NEVER lets down hair. Tower = isolation from nagging. Subverts fairy tale.",
  },
  {
    topic: "eng_ff_ch4_poem", topicId: "eng_ff_ch4_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "The speaker warns at the end: 'Don't sulk, Amanda!' What does this suggest?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Amanda's dreaminess is being misread as sulking, making the adult add yet another demand on top of the previous ones", type: "correct", logicTag: "" },
      { text: "Amanda has started crying and won't stop", type: "concept_error", logicTag: "wrong_reading" },
      { text: "Amanda has answered back rudely to the adult", type: "concept_error", logicTag: "not_stated" },
      { text: "The adult feels guilty about scolding Amanda and is apologising", type: "concept_error", logicTag: "wrong_reading" },
    ],
    solutionSteps: ["Amanda has simply gone quiet and dreamy — she's in her inner world.", "The adult sees this as sulking, adding one more complaint.", "This shows the adult's inability to understand Amanda's inner life; the cycle of nagging continues."],
    shortcut: "Sulking accusation = adult's misreading of Amanda's daydreaming. More control added. Vicious cycle of over-parenting.",
  },
  {
    topic: "eng_ff_ch4_poem", topicId: "eng_ff_ch4_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Amanda imagine when the speaker tells her not to eat chocolate?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She imagines nothing — this is where the adult says 'Don't sulk' at her silence", type: "correct", logicTag: "" },
      { text: "She imagines running away to buy chocolates secretly", type: "concept_error", logicTag: "invented" },
      { text: "She imagines an orphan who can eat whatever she wants", type: "concept_error", logicTag: "earlier_stanza" },
      { text: "She imagines a candy mountain where she can eat freely", type: "concept_error", logicTag: "invented" },
    ],
    solutionSteps: ["At the point 'Don't eat that chocolate', Amanda doesn't daydream — she just goes quiet.", "The adult then says 'Don't sulk' — misreading her silence.", "This stanza = acne warning + sulking accusation, no new fantasy."],
    shortcut: "Chocolate/acne stanza: no fantasy. Just silence → adult accuses of sulking. Builds irony to poem's end.",
  },
  {
    topic: "eng_ff_ch4_poem", topicId: "eng_ff_ch4_poem",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Who is the speaker in the poem 'Amanda!' and what does the poem subtly suggest about the speaker?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "The speaker is a parent or caregiver who, despite good intentions, is smothering Amanda's spirit with excessive instructions", type: "correct", logicTag: "" },
      { text: "The speaker is Amanda's teacher who is trying to discipline her properly", type: "concept_error", logicTag: "wrong_identity" },
      { text: "The speaker is Amanda's older sibling who is jealous of her", type: "concept_error", logicTag: "wrong_identity" },
      { text: "The speaker is a villain deliberately trying to suppress Amanda", type: "concept_error", logicTag: "oversimplified" },
    ],
    solutionSteps: ["The poem doesn't name the speaker.", "The instructions (posture, biting nails, finishing homework, cleaning room, eating chocolate) = typical parental concerns.", "The speaker is likely well-meaning but oblivious to the effect on Amanda's freedom."],
    shortcut: "Speaker = well-meaning parent. Not a villain — just over-controlling, unable to see Amanda's need for freedom.",
  },
  {
    topic: "eng_ff_ch4_poem", topicId: "eng_ff_ch4_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What literary technique is used in the alternating stanzas of 'Amanda!'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Contrast — alternating between the adult's voice (italics) and Amanda's fantasy (regular text) highlights the gulf between control and freedom", type: "correct", logicTag: "" },
      { text: "Flashback — the poem alternates between Amanda's past and present", type: "concept_error", logicTag: "wrong_device" },
      { text: "Dramatic monologue — only one character speaks throughout", type: "concept_error", logicTag: "wrong_structure" },
      { text: "Stream of consciousness — Amanda's thoughts flow without interruption", type: "concept_error", logicTag: "wrong_technique" },
    ],
    solutionSteps: ["The poem uses contrast between two voices.", "Instructions (in italics) = adult world, control.", "Daydreams (regular text) = Amanda's world, freedom.", "The structural contrast reinforces the thematic conflict."],
    shortcut: "Structure = contrast. Adult voice (italics) vs. Amanda's fantasy (regular). Form mirrors theme: control vs. freedom.",
  },

  // ── eng_ff_ch5_poem — The Trees ──────────────────────────────────────────
  {
    topic: "eng_ff_ch5_poem", topicId: "eng_ff_ch5_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Trees' by Adrienne Rich, where are the trees at the beginning of the poem?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Inside the house — they have been brought indoors", type: "correct", logicTag: "" },
      { text: "In a forest far from the city", type: "concept_error", logicTag: "wrong_location" },
      { text: "In a pot on the windowsill", type: "concept_error", logicTag: "wrong_scale" },
      { text: "Fallen on the ground after a storm", type: "concept_error", logicTag: "wrong_context" },
    ],
    solutionSteps: ["The trees are in the house — not in nature.", "They are moving towards the glass door to go outside.", "The poem describes their movement from inside (confinement) to outside (freedom)."],
    shortcut: "Trees start inside the house. Poem = trees moving outward. Confinement → freedom.",
  },
  {
    topic: "eng_ff_ch5_poem", topicId: "eng_ff_ch5_poem",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the symbolic meaning of the trees leaving the house in 'The Trees'?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Women breaking free from domestic confinement and reclaiming their natural identity and freedom", type: "correct", logicTag: "" },
      { text: "Environmental destruction — humans keep trees inside and there are no more forests outside", type: "concept_error", logicTag: "eco_misread" },
      { text: "Spiritual growth — the soul emerging from the body to find peace", type: "concept_error", logicTag: "spiritual_misread" },
      { text: "The importance of planting more trees for a better environment", type: "concept_error", logicTag: "literal_misread" },
    ],
    solutionSteps: ["Adrienne Rich is a feminist poet.", "Trees = women confined to domestic spaces ('inside the house').", "Their movement outside = women's liberation and reclaiming their natural place in the world.", "The house without trees = empty — suggesting confinement serves no one."],
    shortcut: "Feminist reading: trees = women. House = domestic confinement. Trees leaving = women's liberation. Rich's intent.",
  },
  {
    topic: "eng_ff_ch5_poem", topicId: "eng_ff_ch5_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does 'the glass is breaking' symbolise in 'The Trees'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The shattering of the barriers that confine the trees (women) as they break free", type: "correct", logicTag: "" },
      { text: "A literal glass window breaking in a storm", type: "concept_error", logicTag: "literal_misread" },
      { text: "The fragility of nature in the face of human construction", type: "concept_error", logicTag: "wrong_symbolism" },
      { text: "The poet's own heart breaking at the sight of deforestation", type: "concept_error", logicTag: "wrong_reading" },
    ],
    solutionSteps: ["The glass represents the transparent but real barriers — social norms, domestic roles.", "As trees push through the glass doors, they shatter these barriers.", "The breaking glass = moment of liberation."],
    shortcut: "'Glass breaking' = barriers shattering. Trees (women) push through — liberation is violent but necessary.",
  },
  {
    topic: "eng_ff_ch5_poem", topicId: "eng_ff_ch5_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does 'the moon is broken like a mirror' suggest in 'The Trees'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The world outside is also fragmented, turbulent, and not perfectly welcoming for the trees", type: "correct", logicTag: "" },
      { text: "It is a beautiful simile describing the full moon reflected in water", type: "concept_error", logicTag: "romantic_misread" },
      { text: "Bad luck is coming — broken mirrors symbolise misfortune", type: "concept_error", logicTag: "superstition_misread" },
      { text: "The trees have broken the moon by reaching into the sky", type: "concept_error", logicTag: "literal_misread" },
    ],
    solutionSteps: ["A broken mirror = shattered, fragmented reflection.", "The moon being like a broken mirror suggests the freedom found outside is also not perfect — fragmented.", "The trees have escaped but the outside world is not ideal either."],
    shortcut: "Broken mirror moon = outside world is fragmented too. Freedom is real but imperfect. No utopia outside.",
  },
  {
    topic: "eng_ff_ch5_poem", topicId: "eng_ff_ch5_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the poet doing while the trees are moving out in 'The Trees'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Writing letters while sitting inside, aware but not stopping the trees", type: "correct", logicTag: "" },
      { text: "Sleeping and unaware of the trees' movement", type: "concept_error", logicTag: "wrong_detail" },
      { text: "Trying to stop the trees from leaving by closing the door", type: "concept_error", logicTag: "wrong_action" },
      { text: "Planting new trees inside to replace the ones leaving", type: "concept_error", logicTag: "invented" },
    ],
    solutionSteps: ["The poet is sitting inside writing letters, smelling familiar smells.", "She is aware of the trees' departure but does not intervene.", "Her calm observation while they leave suggests she accepts and perhaps endorses their freedom."],
    shortcut: "Poet = writing letters inside, aware of trees leaving, not stopping them. Acceptance/endorsement of their freedom.",
  },
  {
    topic: "eng_ff_ch5_poem", topicId: "eng_ff_ch5_poem",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What makes 'The Trees' by Adrienne Rich a complex poem despite its simple surface?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "It operates on two levels simultaneously: a literal description of trees and a feminist metaphor for liberation", type: "correct", logicTag: "" },
      { text: "It uses very difficult vocabulary that requires a dictionary to understand", type: "concept_error", logicTag: "wrong_complexity_type" },
      { text: "Its complex rhyme scheme makes it hard to follow", type: "concept_error", logicTag: "no_strict_rhyme" },
      { text: "It tells a story backwards from the ending", type: "concept_error", logicTag: "wrong_structure" },
    ],
    solutionSteps: ["Surface: a simple, quiet scene of trees moving out of a house.", "Beneath: feminist commentary on women, domesticity, and liberation.", "The poem is effective because both readings work independently and together."],
    shortcut: "Two-level poem: literal (trees moving out) + feminist metaphor (women's liberation). Both readings are valid.",
  },

  // ── eng_ff_ch6_poem — Fog ────────────────────────────────────────────────
  {
    topic: "eng_ff_ch6_poem", topicId: "eng_ff_ch6_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "To what animal does Carl Sandburg compare the fog in 'Fog'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A cat", type: "correct", logicTag: "" },
      { text: "A wolf", type: "concept_error", logicTag: "wrong_animal" },
      { text: "A snake", type: "concept_error", logicTag: "wrong_animal" },
      { text: "A horse", type: "concept_error", logicTag: "wrong_animal" },
    ],
    solutionSteps: ["Sandburg compares fog to a cat in a six-line metaphor.", "'The fog comes on little cat feet' = silent, soft, stealthy movement.", "The cat sits, looks, and then moves on — like fog."],
    shortcut: "Fog = cat. Comes on 'little cat feet' — silent, soft, stealthy. Sits and moves on. Brevity = power.",
  },
  {
    topic: "eng_ff_ch6_poem", topicId: "eng_ff_ch6_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What poetic device is the entire poem 'Fog' built on?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Extended metaphor — fog is compared to a cat throughout the poem", type: "correct", logicTag: "" },
      { text: "Simile — fog is compared to a cat using 'like'", type: "concept_error", logicTag: "no_like_as" },
      { text: "Personification — the fog is given human qualities", type: "concept_error", logicTag: "it_is_compared_to_animal" },
      { text: "Alliteration — repeated sounds dominate", type: "concept_error", logicTag: "secondary_device" },
    ],
    solutionSteps: ["The fog IS the cat throughout (no 'like' or 'as') — this is metaphor.", "The metaphor extends across all six lines.", "Extended metaphor = one metaphor developed throughout a poem."],
    shortcut: "Device = extended metaphor. Fog IS cat (not 'like' cat). Six lines, one metaphor sustained throughout.",
  },
  {
    topic: "eng_ff_ch6_poem", topicId: "eng_ff_ch6_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why is 'Fog' considered an effective poem despite having only six lines?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "It captures the essential quality of fog — silent, brief, mysterious — with perfect economy of language", type: "correct", logicTag: "" },
      { text: "Short poems are always more powerful than long ones", type: "concept_error", logicTag: "generalisation" },
      { text: "It rhymes perfectly, making it easy to remember", type: "concept_error", logicTag: "no_rhyme_scheme" },
      { text: "It includes many facts about the science of fog formation", type: "concept_error", logicTag: "wrong_content" },
    ],
    solutionSteps: ["Fog is transient, silent, and mysterious.", "The poem captures these qualities in just six lines.", "'Economy of language' = saying more with fewer words. Brevity mirrors the fog's transience."],
    shortcut: "Fog's power = brevity mirrors fog's transience. Six lines, complete image. Economy of language = poetic mastery.",
  },
  {
    topic: "eng_ff_ch6_poem", topicId: "eng_ff_ch6_poem",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the image of fog 'sitting on silent haunches' suggest?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Fog pauses — it lingers temporarily and observes before moving on, just like a cat sitting still", type: "correct", logicTag: "" },
      { text: "Fog sinks low to the ground and becomes dense near the harbour", type: "concept_error", logicTag: "literal_weather" },
      { text: "The fog is resting and will not move for days", type: "concept_error", logicTag: "overextension" },
      { text: "Fog is dangerous and crouches like an animal ready to attack", type: "concept_error", logicTag: "misreads_tone" },
    ],
    solutionSteps: ["'Haunches' = squatting posture of a cat at rest.", "The fog pauses over the harbour and city — surveying, still.", "Then it moves on — fog doesn't stay forever. The stillness is temporary."],
    shortcut: "'Silent haunches' = cat crouching, still, observing. Fog pauses momentarily then departs. Transience.",
  },
  {
    topic: "eng_ff_ch6_poem", topicId: "eng_ff_ch6_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Over what two locations does the fog sit according to 'Fog'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "The harbour and the city", type: "correct", logicTag: "" },
      { text: "The sea and the shore", type: "concept_error", logicTag: "close_but_wrong" },
      { text: "The mountains and the valley", type: "concept_error", logicTag: "wrong_setting" },
      { text: "The river and the bridge", type: "concept_error", logicTag: "wrong_setting" },
    ],
    solutionSteps: ["'It sits looking over harbor and city on silent haunches.'", "Harbour and city are the two locations.", "This suggests an urban, port-city setting — likely Chicago (Sandburg's city)."],
    shortcut: "Fog sits over: harbour + city. Chicago setting (Sandburg's home). Urban, industrial, misty atmosphere.",
  },
  {
    topic: "eng_ff_ch6_poem", topicId: "eng_ff_ch6_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How does the structure of 'Fog' (no rhyme, free verse) contribute to its meaning?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Free verse mirrors the formless, unpredictable nature of fog itself", type: "correct", logicTag: "" },
      { text: "The lack of rhyme shows the poet was not very skilled", type: "concept_error", logicTag: "wrong_judgement" },
      { text: "Rhyme would have made the poem too cheerful for a dark subject", type: "concept_error", logicTag: "wrong_rationale" },
      { text: "The structure follows Japanese haiku traditions", type: "concept_error", logicTag: "wrong_tradition" },
    ],
    solutionSteps: ["Fog has no fixed shape or pattern — it drifts and changes.", "Free verse (no fixed rhyme/meter) also has no fixed pattern.", "Form matches content: the poem IS like fog in its movement."],
    shortcut: "Free verse = formless like fog. Structure mirrors subject. Form reinforces content — intentional, not accidental.",
  },

  // ── eng_ff_ch7_poem — The Tale of Custard the Dragon ─────────────────────
  {
    topic: "eng_ff_ch7_poem", topicId: "eng_ff_ch7_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Tale of Custard the Dragon', what was Custard's special characteristic?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He was a real dragon who breathed fire, but he was considered a coward by the others", type: "correct", logicTag: "" },
      { text: "He was a fake dragon made of paper and could not breathe fire", type: "concept_error", logicTag: "wrong_detail" },
      { text: "He was the bravest of all pets and defeated many dragons", type: "concept_error", logicTag: "misreads_poem_beginning" },
      { text: "He could fly but was afraid of heights", type: "concept_error", logicTag: "invented" },
    ],
    solutionSteps: ["Custard is described as a real dragon with sharp teeth and spikes.", "However, all the other pets — Belinda, ink the cat, Blink the mouse, Mustard the dog — mock him as a coward.", "He cried for a 'nice safe cage', which they found funny."],
    shortcut: "Custard = real dragon, but seen as coward. Others brave (Belinda laughed, dog/cat/mouse brave). Irony: he's the real fighter.",
  },
  {
    topic: "eng_ff_ch7_poem", topicId: "eng_ff_ch7_poem",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the irony in 'The Tale of Custard the Dragon'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The ones who boasted of bravery ran away when the pirate came; Custard (the 'coward') fought and defeated him", type: "correct", logicTag: "" },
      { text: "Custard was brave but was too humble to admit it", type: "concept_error", logicTag: "misses_irony" },
      { text: "The pirate was actually a friendly person in disguise", type: "concept_error", logicTag: "wrong_plot" },
      { text: "Belinda was actually the bravest but gave Custard the credit", type: "concept_error", logicTag: "wrong_plot" },
    ],
    solutionSteps: ["Ink, Blink, Mustard, and Belinda all claimed to be brave.", "When the pirate arrived, they all ran and hid.", "Custard, the supposed coward, attacked and ate the pirate.", "The brave ones are not truly brave; the 'coward' is the real hero."],
    shortcut: "Irony: braggers fled, 'coward' fought. Custard defeats pirate. True bravery ≠ boasting.",
  },
  {
    topic: "eng_ff_ch7_poem", topicId: "eng_ff_ch7_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the poem suggest about those who boast of bravery?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Boasting is empty — true courage is shown through action, not words", type: "correct", logicTag: "" },
      { text: "Boasting is necessary to maintain one's social status in a group", type: "concept_error", logicTag: "wrong_message" },
      { text: "Boasters are always the ones who fight hardest when threatened", type: "concept_error", logicTag: "contradicts_poem" },
      { text: "Animals are naturally braver than dragons", type: "concept_error", logicTag: "oversimplified" },
    ],
    solutionSteps: ["Mustard (dog) and others boasted of their bravery before the crisis.", "When the pirate arrived, they hid.", "Custard who never boasted was the one who acted. Actions > words."],
    shortcut: "Boasters = cowards in crisis. Custard = modest but acts. Poem's moral: true courage = action, not boasting.",
  },
  {
    topic: "eng_ff_ch7_poem", topicId: "eng_ff_ch7_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the tone of 'The Tale of Custard the Dragon' and how is it achieved?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Humorous and light-hearted — achieved through comic names, bouncy rhythm, exaggeration, and playful rhymes", type: "correct", logicTag: "" },
      { text: "Solemn and serious — the dragon's story is a tragedy", type: "concept_error", logicTag: "wrong_tone" },
      { text: "Dark and foreboding — the pirate's arrival creates terror", type: "concept_error", logicTag: "misreads_tone" },
      { text: "Satirical and bitter — it mocks all the characters equally", type: "partial_logic", logicTag: "satire_yes_but_not_bitter" },
    ],
    solutionSteps: ["Names like Ink, Blink, Mustard, Custard = playful/comic.", "The rhythm (anapestic) is bouncy and fast.", "Exaggeration (Custard's spikes/teeth described grandly; others brave but tiny) = comic effect.", "The overall tone is warm humour, not harsh satire."],
    shortcut: "Tone = humour. Comic names + bouncy rhythm + exaggeration. Light satire on braggarts, but warm overall.",
  },
  {
    topic: "eng_ff_ch7_poem", topicId: "eng_ff_ch7_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What happened to the pirate when Custard faced him?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Custard ate the pirate up, defeating him entirely", type: "correct", logicTag: "" },
      { text: "Custard scared the pirate away by breathing fire", type: "concept_error", logicTag: "wrong_method" },
      { text: "Custard captured the pirate and handed him to the police", type: "concept_error", logicTag: "invented" },
      { text: "The pirate surrendered when he saw the dragon's size", type: "concept_error", logicTag: "wrong_detail" },
    ],
    solutionSteps: ["Custard advanced on the pirate.", "He ate the pirate up — decisive, complete action.", "All others witnessed it after hiding during the attack."],
    shortcut: "Custard ate the pirate. Complete victory. Then others came back bragging again (irony continues).",
  },
  {
    topic: "eng_ff_ch7_poem", topicId: "eng_ff_ch7_poem",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "After Custard defeats the pirate, what do the other characters do — and what does this reveal?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "They resume their boasting, claiming they would have done the same — revealing that cowards are persistent in self-deception", type: "correct", logicTag: "" },
      { text: "They apologise to Custard and admit their cowardice", type: "concept_error", logicTag: "wrong_outcome" },
      { text: "They crown Custard as their king for his bravery", type: "concept_error", logicTag: "invented" },
      { text: "They all leave Belinda's house, ashamed of themselves", type: "concept_error", logicTag: "wrong_outcome" },
    ],
    solutionSteps: ["After the pirate is defeated, ink, Blink, and Mustard resume their claims of bravery.", "Custard modestly says the pirate was nasty.", "The others' continued boasting shows they cannot acknowledge reality.", "This extends the poem's satire: cowards are persistent self-deceivers."],
    shortcut: "After victory: others boast again ('we woulda done it'). Custard = modest. Satire extended: cowards never change.",
  },

  // ── eng_ff_ch8_poem — For Anne Gregory ──────────────────────────────────
  {
    topic: "eng_ff_ch8_poem", topicId: "eng_ff_ch8_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'For Anne Gregory', what does the young man complain about in the first stanza?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Men only love Anne for her beautiful yellow hair, not for her inner self", type: "correct", logicTag: "" },
      { text: "Anne is too intelligent and intimidates men", type: "concept_error", logicTag: "wrong_complaint" },
      { text: "Anne changes her hair colour too often", type: "concept_error", logicTag: "literal_misread" },
      { text: "Anne's family disapproves of any potential suitor", type: "concept_error", logicTag: "wrong_complaint" },
    ],
    solutionSteps: ["The young man says: no young man (including himself) could ever love Anne for herself alone.", "He specifies they love her 'great honey-coloured / Ramparts at your ear' — her hair.", "External beauty is the attraction, not her inner soul."],
    shortcut: "Man's complaint: men love Anne's yellow hair, not her soul. External beauty = the attraction, not inner self.",
  },
  {
    topic: "eng_ff_ch8_poem", topicId: "eng_ff_ch8_poem",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is Anne Gregory's response to the young man's claim in 'For Anne Gregory'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "She says she could dye her hair any colour — black, brown, or carrot — so he could love her for herself alone", type: "correct", logicTag: "" },
      { text: "She says she will never change her hair because it is her best feature", type: "concept_error", logicTag: "opposite_response" },
      { text: "She agrees that men only love beautiful women and resigns herself to it", type: "concept_error", logicTag: "wrong_response" },
      { text: "She argues that inner beauty is more important than outer beauty", type: "partial_logic", logicTag: "implied_but_not_said" },
    ],
    solutionSteps: ["Anne says she can change her hair to 'brown or black or carrot'.", "If her hair colour changes, the superficial attraction would go.", "Then he would have to love her for herself — this is her argument."],
    shortcut: "Anne: I'll dye my hair (brown/black/carrot). Remove the beauty he loves — then see if you love my soul.",
  },
  {
    topic: "eng_ff_ch8_poem", topicId: "eng_ff_ch8_poem",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Yeats say in the final stanza of 'For Anne Gregory'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Only God can love a person for their soul alone, not for their external beauty", type: "correct", logicTag: "" },
      { text: "Anne should accept that men love her for her hair because it is natural", type: "concept_error", logicTag: "wrong_conclusion" },
      { text: "The young man will one day learn to love Anne's soul", type: "concept_error", logicTag: "wrong_conclusion" },
      { text: "True love exists only in poetry and literature, not in real life", type: "concept_error", logicTag: "wrong_conclusion" },
    ],
    solutionSteps: ["An old religious man found a written text saying God loves us for our soul alone.", "Humans cannot help being attracted to external beauty.", "Only God is capable of purely spiritual love, not human beings."],
    shortcut: "Final stanza: only GOD loves soul alone. Humans are always swayed by external beauty. Yeats's conclusion.",
  },
  {
    topic: "eng_ff_ch8_poem", topicId: "eng_ff_ch8_poem",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the philosophical question at the centre of 'For Anne Gregory'?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Can human beings love someone purely for their soul, independent of external beauty?", type: "correct", logicTag: "" },
      { text: "Should women change their appearance to attract men?", type: "concept_error", logicTag: "misreads_question" },
      { text: "Is God's love superior to human love?", type: "partial_logic", logicTag: "conclusion_not_question" },
      { text: "Can beauty and intelligence coexist in a person?", type: "concept_error", logicTag: "not_the_poem's_question" },
    ],
    solutionSteps: ["The poem poses the question: can anyone love the inner self (soul) rather than the outer self (appearance)?", "Three characters answer: young man (no, I love your hair), Anne (I'll remove the hair), old man/God (only God can).", "The poem ends unresolved: human love = conditional, beauty-based."],
    shortcut: "Central question: can humans love soul alone? Answer: No — only God can. Human love = tied to external beauty.",
  },
  {
    topic: "eng_ff_ch8_poem", topicId: "eng_ff_ch8_poem",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does 'great honey-coloured / Ramparts at your ear' describe in 'For Anne Gregory'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Anne's beautiful golden/yellow hair falling beside her ears — described as fortress walls (ramparts)", type: "correct", logicTag: "" },
      { text: "Jewellery hanging near Anne's ears", type: "concept_error", logicTag: "literal_misread" },
      { text: "The high walls of Anne Gregory's family home", type: "concept_error", logicTag: "literal_misread" },
      { text: "Anne's broad shoulders described as protective battlements", type: "concept_error", logicTag: "wrong_body_part" },
    ],
    solutionSteps: ["'Honey-coloured' = golden/yellow.", "'Ramparts' = fortress walls — powerful, grand.", "Together: Anne's yellow hair is described as imposing, beautiful fortifications.", "The metaphor = her hair is both beautiful and powerful, a defence/fortress."],
    shortcut: "'Honey-coloured ramparts' = Anne's golden hair. Metaphor: hair = fortress walls. Beautiful AND powerful/grand.",
  },
  {
    topic: "eng_ff_ch8_poem", topicId: "eng_ff_ch8_poem",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How is 'For Anne Gregory' relevant to modern discussions of beauty standards?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "It raises the timeless issue of being judged by appearance rather than character, which remains central to feminist discourse", type: "correct", logicTag: "" },
      { text: "It proves that beauty standards were better in Yeats's time and have declined since", type: "concept_error", logicTag: "wrong_conclusion" },
      { text: "It argues that women should not dye their hair as it destroys their natural beauty", type: "concept_error", logicTag: "misreads_poem" },
      { text: "It shows that religious texts solve all modern social problems", type: "concept_error", logicTag: "wrong_reading" },
    ],
    solutionSteps: ["Yeats's poem (1930s) anticipates modern debates: being judged by appearance, not character.", "Anne's desire to be loved for herself alone = desire for recognition beyond physical appearance.", "This resonates with modern beauty standards, social media culture, and feminist arguments about objectification."],
    shortcut: "Modern relevance: judged by looks, not soul. Anne = wants recognition beyond appearance. Timeless feminist concern.",
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI, { serverSelectionTimeoutMS: 10_000 });
  console.log("MongoDB connected");

  let created = 0, skipped = 0;
  for (const q of Q) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    created++;
  }
  console.log(`\n✅ English QuestionsB (Poems): ${created} created, ${skipped} skipped (${Q.length} total)`);
  await mongoose.disconnect();
}

run().catch((err) => { console.error(err); process.exit(1); });
