/**
 * Seed: CBSE Class 10 English — Footprints Without Feet Questions (72 MCQs)
 * Topics: eng_fw_ch1 … eng_fw_ch9  (8 questions each)
 * Safe to re-run — skips duplicates on { questionText, subject }
 * Usage: node config/seedEnglishQuestionsC.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const Q = [
  // ── eng_fw_ch1 — A Triumph of Surgery ────────────────────────────────────
  {
    topic: "eng_fw_ch1", topicId: "eng_fw_ch1",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'A Triumph of Surgery', what was wrong with Tricki, Mrs Pumphrey's dog?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He was grossly overfed and had become hugely fat, lethargic, and unwell", type: "correct", logicTag: "" },
      { text: "He had broken his leg and needed a surgery to fix it", type: "concept_error", logicTag: "wrong_problem" },
      { text: "He had eaten something poisonous and needed emergency treatment", type: "concept_error", logicTag: "wrong_problem" },
      { text: "He had a skin disease from too much bathing", type: "concept_error", logicTag: "wrong_problem" },
    ],
    solutionSteps: ["Mrs Pumphrey overfed Tricki with cream cakes, chocolates, and malt.", "Tricki became 'hugely fat' like a bloated sausage.", "He was listless, vomiting, and unable to move."],
    shortcut: "Tricki's problem = overfed by Mrs Pumphrey. Too fat, listless. Vet Herriot's solution: hospital + diet + exercise.",
  },
  {
    topic: "eng_fw_ch1", topicId: "eng_fw_ch1",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What treatment did Dr Herriot give Tricki in 'A Triumph of Surgery'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "No medicine — just two weeks of no food, then little food, and plenty of exercise with other dogs", type: "correct", logicTag: "" },
      { text: "Surgery to remove excess fat from Tricki's body", type: "concept_error", logicTag: "wrong_treatment" },
      { text: "Special vitamin injections and a liquid diet", type: "concept_error", logicTag: "wrong_treatment" },
      { text: "A strict rest regime with no exercise for two weeks", type: "concept_error", logicTag: "wrong_treatment" },
    ],
    solutionSteps: ["Herriot gave Tricki no treatment or drugs.", "He kept Tricki with the other dogs: no food at first, then a little.", "Tricki played with other dogs, exercised, and recovered naturally."],
    shortcut: "No surgery! Treatment = starvation + exercise + company of other dogs. The 'surgery' = common sense care.",
  },
  {
    topic: "eng_fw_ch1", topicId: "eng_fw_ch1",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the irony in the title 'A Triumph of Surgery'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "No actual surgery was performed — the 'triumph' was just proper diet and exercise", type: "correct", logicTag: "" },
      { text: "The surgery was performed but failed, making it ironic to call it a triumph", type: "concept_error", logicTag: "wrong_plot" },
      { text: "The surgery was very simple but Mrs Pumphrey paid a huge bill for it", type: "concept_error", logicTag: "wrong_detail" },
      { text: "Tricki died despite the surgery, making the title bitterly ironic", type: "concept_error", logicTag: "wrong_ending" },
    ],
    solutionSteps: ["Mrs Pumphrey thinks her dog was saved by a medical miracle ('triumph of surgery').", "In reality, Herriot just withheld food and let Tricki play with other dogs.", "The 'triumph' = common sense; the title is sardonically ironic."],
    shortcut: "Irony: no surgery happened. 'Triumph' = diet + exercise. Mrs Pumphrey assumes medical miracle. Title is satirical.",
  },
  {
    topic: "eng_fw_ch1", topicId: "eng_fw_ch1",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Mrs Pumphrey's character in 'A Triumph of Surgery' represent?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Misplaced affection — excessive love expressed through overindulgence that actually harms the loved one", type: "correct", logicTag: "" },
      { text: "A cruel pet owner who neglects her dog's nutritional needs", type: "concept_error", logicTag: "wrong_characterisation" },
      { text: "The ideal caring dog owner who puts her pet's welfare first", type: "concept_error", logicTag: "contradicts_story" },
      { text: "The wealthy class's contempt for medical advice", type: "concept_error", logicTag: "misreads_theme" },
    ],
    solutionSteps: ["Mrs Pumphrey loves Tricki deeply but expresses it with food and luxury.", "She genuinely doesn't understand that her love is killing Tricki.", "Her character = a gentle satire on misguided love and over-indulgence."],
    shortcut: "Mrs Pumphrey = misguided love. Kills with kindness. Satire: love without wisdom can harm. Not villain, just unwise.",
  },
  {
    topic: "eng_fw_ch1", topicId: "eng_fw_ch1",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Mrs Pumphrey send eggs, wine, and brandy to the hospital for Tricki?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She thought Tricki needed extra nourishment and was worried about his weakness", type: "correct", logicTag: "" },
      { text: "The hospital staff requested these items as part of the treatment", type: "concept_error", logicTag: "wrong_reason" },
      { text: "She wanted to bribe the doctors for better treatment", type: "concept_error", logicTag: "wrong_inference" },
      { text: "It was a Christmas gift for the staff", type: "concept_error", logicTag: "wrong_reason" },
    ],
    solutionSteps: ["Mrs Pumphrey worried Tricki was too weak and needed building up.", "She sent two dozen eggs, wine, and brandy for his 'anemia'.", "Herriot and his staff enjoyed these themselves — humorous aside."],
    shortcut: "Mrs Pumphrey sent eggs/wine/brandy for 'weak' Tricki. Herriot's staff ate them. Comedy: misdirected luxury.",
  },
  {
    topic: "eng_fw_ch1", topicId: "eng_fw_ch1",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How does Herriot describe Tricki's condition when he first sees him at Mrs Pumphrey's house?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Like a sausage with legs — grossly overweight with a distended, swollen body", type: "correct", logicTag: "" },
      { text: "Thin and shivering, suggesting starvation", type: "concept_error", logicTag: "wrong_description" },
      { text: "Energetic but coughing, showing signs of a chest infection", type: "concept_error", logicTag: "wrong_description" },
      { text: "Restless and howling, clearly in pain from internal injuries", type: "concept_error", logicTag: "wrong_description" },
    ],
    solutionSteps: ["Herriot narrates: Tricki had become 'hugely fat, like a bloated sausage with legs sticking out.'", "The simile conveys both the humour and the seriousness of the condition.", "His eyes showed a glazed, dull look — no sparkle."],
    shortcut: "'Hugely fat, like a bloated sausage with legs' — Herriot's vivid description. Simile + humour + medical concern.",
  },
  {
    topic: "eng_fw_ch1", topicId: "eng_fw_ch1",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What lesson does 'A Triumph of Surgery' teach about true care and love?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "True care sometimes means withholding what the loved one wants and providing what they need", type: "correct", logicTag: "" },
      { text: "Animals should not be kept as pets because they are hard to care for", type: "concept_error", logicTag: "misreads_lesson" },
      { text: "Veterinarians are more capable of caring for animals than their owners", type: "partial_logic", logicTag: "secondary_point" },
      { text: "Wealthy people cannot be good parents or pet owners", type: "concept_error", logicTag: "oversimplified_class_reading" },
    ],
    solutionSteps: ["Mrs Pumphrey's love = give everything the pet wants.", "Herriot's love/care = give nothing, then gradually what is needed.", "Real care often means saying no; indulgence is not always love."],
    shortcut: "Lesson: true love = sometimes saying no. Herriot's 'less' saves Tricki. Mrs Pumphrey's 'more' was harming him.",
  },
  {
    topic: "eng_fw_ch1", topicId: "eng_fw_ch1",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What was Mrs Pumphrey's tearful farewell comment when Tricki was taken to hospital?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "She called it a 'triumph of surgery' and thanked Herriot profusely when Tricki recovered", type: "correct", logicTag: "" },
      { text: "She refused to let Tricki go and threatened to call the police", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "She cried and accused Herriot of being heartless", type: "concept_error", logicTag: "wrong_reaction" },
      { text: "She accepted the diagnosis calmly and paid the bill without emotion", type: "concept_error", logicTag: "wrong_reaction" },
    ],
    solutionSteps: ["When Tricki was being taken away, Mrs Pumphrey sobbed.", "She said it was 'a triumph of surgery' when he returned healthy.", "The phrase is her well-meaning but ironic conclusion — no surgery had been performed."],
    shortcut: "Mrs Pumphrey's phrase ('triumph of surgery') = title's source. She genuinely believes it. Herriot knows the truth.",
  },

  // ── eng_fw_ch2 — The Thief's Story ───────────────────────────────────────
  {
    topic: "eng_fw_ch2", topicId: "eng_fw_ch2",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Thief's Story', what was the narrator Hari Singh's occupation?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A young thief who befriended people to rob them", type: "correct", logicTag: "" },
      { text: "A writer who helped Anil with his stories", type: "concept_error", logicTag: "misreads_role" },
      { text: "A cook in a restaurant who stole from customers", type: "concept_error", logicTag: "partial_wrong" },
      { text: "A student who robbed his schoolmates", type: "concept_error", logicTag: "wrong_identity" },
    ],
    solutionSteps: ["Hari Singh introduced himself as a friend-maker who later stole.", "He changed his name to avoid being caught.", "His strategy: earn trust, then steal."],
    shortcut: "Hari Singh = young thief. Strategy: befriend someone, earn trust, then rob. Changed name to avoid identification.",
  },
  {
    topic: "eng_fw_ch2", topicId: "eng_fw_ch2",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Hari Singh return Anil's money in 'The Thief's Story'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Anil's trust and kindness made Hari feel guilty; he realised he would lose something more valuable than money — the chance to learn and become better", type: "correct", logicTag: "" },
      { text: "He was caught by the police and had no choice but to return it", type: "concept_error", logicTag: "wrong_reason" },
      { text: "The money was wet from rain and of no use", type: "partial_logic", logicTag: "only_trigger_not_reason" },
      { text: "Anil noticed the money was missing and confronted him", type: "concept_error", logicTag: "wrong_reason" },
    ],
    solutionSteps: ["Hari stole the money and went to the train station.", "He missed the train and stood in the rain, reflecting on his life.", "He realised Anil was teaching him to read and write — an opportunity for a better future.", "Staying with Anil = education + a future. Theft = only money but a dead end."],
    shortcut: "Hari returns money because: Anil teaches him to read/write. Future > money. Conscience + self-interest combined.",
  },
  {
    topic: "eng_fw_ch2", topicId: "eng_fw_ch2",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'The Thief's Story'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Trust and the transformative power of education and human goodness", type: "correct", logicTag: "" },
      { text: "Poverty as the root cause of all crime and dishonesty", type: "concept_error", logicTag: "secondary_factor" },
      { text: "The inefficiency of the police in catching thieves", type: "concept_error", logicTag: "not_in_story" },
      { text: "The danger of befriending strangers in cities", type: "concept_error", logicTag: "misreads_message" },
    ],
    solutionSteps: ["Anil's trust in Hari despite knowing he is untrustworthy is central.", "This trust + the gift of education ultimately reform Hari.", "Theme: goodness and education can transform even a thief."],
    shortcut: "Theme = transformative power of trust + education. Anil's goodness changes Hari more than punishment would.",
  },
  {
    topic: "eng_fw_ch2", topicId: "eng_fw_ch2",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How did Anil know that Hari had stolen from him?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The notes Hari returned were wet/damp from rain, revealing they had been taken out", type: "correct", logicTag: "" },
      { text: "A neighbour saw Hari leaving with money and told Anil", type: "concept_error", logicTag: "wrong_clue" },
      { text: "Anil counted the money and found some missing", type: "concept_error", logicTag: "different_method" },
      { text: "Hari confessed to him the following morning", type: "concept_error", logicTag: "wrong_ending" },
    ],
    solutionSteps: ["The returned notes were damp from being in the rain when Hari stood at the station.", "Anil noticed but smiled — suggesting he knew.", "He did not confront Hari directly, which shows his generous, forgiving nature."],
    shortcut: "Anil knew: damp notes = been outside in rain. He smiled but didn't confront Hari. Chose to forgive silently.",
  },
  {
    topic: "eng_fw_ch2", topicId: "eng_fw_ch2",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What did Anil teach Hari Singh in 'The Thief's Story'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "To read and write", type: "correct", logicTag: "" },
      { text: "To cook Indian meals", type: "concept_error", logicTag: "wrong_skill" },
      { text: "To drive and maintain a car", type: "concept_error", logicTag: "wrong_skill" },
      { text: "To write and sell stories", type: "concept_error", logicTag: "anil_is_writer_not_teaching_that" },
    ],
    solutionSteps: ["Anil taught Hari to read and write.", "He was also teaching him arithmetic.", "Hari reflected that literacy = a key to a better future; it made the decision to return easier."],
    shortcut: "Anil taught Hari: reading, writing, arithmetic. Literacy = Hari's real gain. Money was secondary.",
  },
  {
    topic: "eng_fw_ch2", topicId: "eng_fw_ch2",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Hari mean when he thinks stealing from an 'easy mark' is not 'really satisfying'?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "He has a thief's pride — stealing from a trusting, generous person feels hollow and is harder to justify to himself", type: "correct", logicTag: "" },
      { text: "He wants more money than Anil has and is dissatisfied with the amount", type: "concept_error", logicTag: "misreads_emotion" },
      { text: "He prefers robbing rich people rather than struggling writers", type: "concept_error", logicTag: "wrong_inference" },
      { text: "He is afraid of being caught and so prefers not to steal at all", type: "concept_error", logicTag: "misses_complexity" },
    ],
    solutionSteps: ["Hari recognises that Anil is trusting and good-natured.", "Stealing from such a person lacks the 'challenge' a thief might enjoy.", "More deeply, it creates guilt because Anil's goodness confronts his conscience."],
    shortcut: "Hari's reflection: robbing trusting/good people = unsatisfying. Their goodness makes theft feel worse, not better.",
  },
  {
    topic: "eng_fw_ch2", topicId: "eng_fw_ch2",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the story suggest about the relationship between education and moral transformation?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Education opens the door to a legitimate future, making crime seem less necessary and less appealing", type: "correct", logicTag: "" },
      { text: "Education alone cannot change a criminal; punishment is more effective", type: "concept_error", logicTag: "contradicts_story" },
      { text: "People who can read and write are more capable criminals", type: "concept_error", logicTag: "wrong_reading" },
      { text: "Moral change requires religious conversion, not education", type: "concept_error", logicTag: "not_in_story" },
    ],
    solutionSteps: ["Hari sees literacy as opening a better future ('the road that could lead to somewhere').", "This makes the stolen money seem less valuable.", "Education provides an alternative path — this is what tips the balance against theft."],
    shortcut: "Education = alternative future. With literacy, crime is less necessary. Ruskin Bond's message: teach, don't punish.",
  },

  // ── eng_fw_ch3 — The Midnight Visitor ────────────────────────────────────
  {
    topic: "eng_fw_ch3", topicId: "eng_fw_ch3",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Midnight Visitor', who was Ausable and what was surprising about him?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He was a secret agent, but he was fat, sloppy, and spoke with an American accent — not like a typical spy at all", type: "correct", logicTag: "" },
      { text: "He was a professor who secretly worked for the intelligence agency", type: "concept_error", logicTag: "wrong_characterisation" },
      { text: "He was a suave, well-dressed European spy in the James Bond mould", type: "concept_error", logicTag: "opposite_description" },
      { text: "He was a hotel waiter who turned out to be a spy", type: "concept_error", logicTag: "wrong_identity" },
    ],
    solutionSteps: ["Fowler, the writer accompanying Ausable, expected a romantic, dashing spy.", "Ausable was fat, sloppy, and spoke with a mixture of American and French accents.", "He had lived in Paris for 20 years but never lost his American twang."],
    shortcut: "Ausable = fat, sloppy, unromantic spy. Fowler is disappointed. Subverts spy fiction clichés deliberately.",
  },
  {
    topic: "eng_fw_ch3", topicId: "eng_fw_ch3",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How did Ausable deal with Max (the intruder) in 'The Midnight Visitor'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He invented a story about a non-existent balcony below the window; when there was a knock at the door, Max jumped out and fell to his death", type: "correct", logicTag: "" },
      { text: "He overpowered Max in a hand-to-hand fight despite being overweight", type: "concept_error", logicTag: "wrong_method" },
      { text: "He called the police and had Max arrested", type: "concept_error", logicTag: "wrong_method" },
      { text: "He persuaded Max to leave by telling him the report was worthless", type: "concept_error", logicTag: "wrong_method" },
    ],
    solutionSteps: ["Ausable claimed there was a balcony below the window and that it was used by multiple people to enter his room.", "When someone knocked (a waiter he'd ordered), Max panicked and stepped out the window thinking it was a second agent.", "There was no balcony — Max fell several floors."],
    shortcut: "Ausable's trick: invented a balcony below the window. Knock at door → Max panics → jumps out → no balcony → dies.",
  },
  {
    topic: "eng_fw_ch3", topicId: "eng_fw_ch3",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What quality of Ausable does the story 'The Midnight Visitor' celebrate?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "His ability to think quickly and use his wits under pressure rather than physical force", type: "correct", logicTag: "" },
      { text: "His physical strength and combat skills", type: "concept_error", logicTag: "opposite" },
      { text: "His knowledge of weapons and spy gadgets", type: "concept_error", logicTag: "not_in_story" },
      { text: "His ability to disguise himself in various costumes", type: "concept_error", logicTag: "not_in_story" },
    ],
    solutionSteps: ["Ausable doesn't fight; he talks.", "He uses a false story (non-existent balcony) to eliminate a threat.", "The story celebrates intelligence and quick thinking over physical prowess."],
    shortcut: "Ausable's strength = quick wit, not physical force. Intelligence > brawn. Subverts action-hero spy stereotype.",
  },
  {
    topic: "eng_fw_ch3", topicId: "eng_fw_ch3",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why was Fowler disappointed when he first met Ausable in 'The Midnight Visitor'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Fowler had expected a glamorous, exciting spy but found a fat, unimpressive man in a dull hotel room", type: "correct", logicTag: "" },
      { text: "Ausable was rude and refused to help Fowler with his writing", type: "concept_error", logicTag: "wrong_reason" },
      { text: "Ausable refused to take Fowler on the mission he had hoped for", type: "concept_error", logicTag: "wrong_reason" },
      { text: "The hotel was below the standard Fowler was used to", type: "concept_error", logicTag: "wrong_focus" },
    ],
    solutionSteps: ["Fowler was a writer who had romanticised spy work.", "He expected James Bond-style adventure.", "Finding Ausable fat, speaking oddly, and staying in a dull hotel was a letdown."],
    shortcut: "Fowler = disappointed. He expected glamorous spy. Got: fat man, bad accent, dull room. Reality vs. fiction.",
  },
  {
    topic: "eng_fw_ch3", topicId: "eng_fw_ch3",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Who knocked on the door of Ausable's hotel room during the confrontation with Max?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A waiter with the drinks Ausable had ordered earlier", type: "correct", logicTag: "" },
      { text: "Another spy working with Max", type: "concept_error", logicTag: "what_max_feared" },
      { text: "The hotel manager checking on guests", type: "concept_error", logicTag: "wrong_identity" },
      { text: "Fowler's assistant arriving with important information", type: "concept_error", logicTag: "wrong_identity" },
    ],
    solutionSteps: ["Ausable had ordered drinks before arriving at the room.", "The knock was the waiter delivering the order.", "Ausable used this ordinary event, combined with the fake balcony story, to make Max believe it was a second agent arriving."],
    shortcut: "Knock = waiter with drinks. Ordinary event. Ausable made Max think it was another agent. Max panicked and jumped.",
  },
  {
    topic: "eng_fw_ch3", topicId: "eng_fw_ch3",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the story 'The Midnight Visitor' suggest about appearances?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Appearances are deceptive — a person who looks unimpressive may be the most competent and clever", type: "correct", logicTag: "" },
      { text: "Good-looking people are always more trustworthy than ugly ones", type: "concept_error", logicTag: "contradicts_theme" },
      { text: "One should judge others based on their physical appearance before trusting them", type: "concept_error", logicTag: "wrong_lesson" },
      { text: "Appearances don't matter — what counts is wealth and status", type: "concept_error", logicTag: "wrong_lesson" },
    ],
    solutionSteps: ["Ausable looks incompetent but is brilliantly clever.", "Max is presumably more 'spy-like' in appearance but is outwitted easily.", "The story subverts the 'look of success' by making the unlikely hero win through brains."],
    shortcut: "Theme = don't judge by appearances. Ausable (unimpressive) > Max (presumably 'proper' spy). Brains beat looks.",
  },
  {
    topic: "eng_fw_ch3", topicId: "eng_fw_ch3",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the significance of the non-existent balcony in 'The Midnight Visitor'?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "It shows that a convincing lie told with confidence can be more powerful than any weapon", type: "correct", logicTag: "" },
      { text: "It shows that Ausable had a good knowledge of the hotel's layout", type: "concept_error", logicTag: "misses_depth" },
      { text: "It demonstrates that architects often make errors in building designs", type: "concept_error", logicTag: "literal_misread" },
      { text: "It shows that Max was stupid to believe anything Ausable said", type: "concept_error", logicTag: "too_simple" },
    ],
    solutionSteps: ["Ausable invented the balcony details with complete conviction.", "Max, under pressure, believed the story without questioning it.", "The balcony = the power of a confident, plausible deception at the right moment."],
    shortcut: "Non-existent balcony = confident deception as weapon. Ausable's words, not his fists, defeat Max. Wit = deadliest weapon.",
  },

  // ── eng_fw_ch4 — A Question of Trust ────────────────────────────────────
  {
    topic: "eng_fw_ch4", topicId: "eng_fw_ch4",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'A Question of Trust', who was Horace Danby and what was his secret?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A locksmith who appeared respectable but secretly committed one burglary a year to fund his love of rare books", type: "correct", logicTag: "" },
      { text: "A retired police officer who used his skills to solve burglaries", type: "concept_error", logicTag: "wrong_identity" },
      { text: "A wealthy collector who bought stolen goods from burglars", type: "concept_error", logicTag: "wrong_identity" },
      { text: "A librarian who stole money to buy books for a public library", type: "concept_error", logicTag: "wrong_identity" },
    ],
    solutionSteps: ["Horace Danby made safes and was considered honest and reliable.", "But every year he committed one safe-robbery to fund his real passion: buying rare books.", "He had never been caught — until the story's events."],
    shortcut: "Horace Danby = locksmith + annual burglar. Robbed once a year to buy rare books. Appeared respectable.",
  },
  {
    topic: "eng_fw_ch4", topicId: "eng_fw_ch4",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How was Horace Danby tricked in 'A Question of Trust'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A woman posed as the owner of the house and convinced him to open the safe without gloves, leaving fingerprints that got him arrested", type: "correct", logicTag: "" },
      { text: "The real owner returned home unexpectedly and caught him in the act", type: "concept_error", logicTag: "different_scenario" },
      { text: "His accomplice betrayed him to the police for a reward", type: "concept_error", logicTag: "wrong_plot" },
      { text: "A hidden camera recorded him breaking into the safe", type: "concept_error", logicTag: "anachronistic_wrong" },
    ],
    solutionSteps: ["A young woman appeared at the Shotover Grange while Horace was there.", "She claimed to be the owner and said she needed her jewels for a party.", "She convinced him to open the safe without gloves — she was another thief who had taken the jewels before the police arrived.", "Horace was arrested with fingerprints but no jewels — the woman had framed him."],
    shortcut: "Woman = thief posing as owner. Got Horace to open safe bare-handed (fingerprints). She took jewels, he got arrested.",
  },
  {
    topic: "eng_fw_ch4", topicId: "eng_fw_ch4",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central irony in 'A Question of Trust'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A thief was himself deceived and cheated by a more clever thief — the hunter became the hunted", type: "correct", logicTag: "" },
      { text: "An honest man was mistakenly accused of theft", type: "concept_error", logicTag: "wrong_reading" },
      { text: "The police outsmarted a criminal through careful investigation", type: "concept_error", logicTag: "wrong_plot" },
      { text: "A woman proved more intelligent than a man in the story", type: "partial_logic", logicTag: "secondary_irony" },
    ],
    solutionSteps: ["Horace Danby was a thief who trusted someone claiming to be the owner.", "That someone was also a thief who used his trust to frame him.", "The irony: thieves have no honour among themselves; Horace was robbed of his own con."],
    shortcut: "Irony: thief tricked by thief. Horace's own methods (charm, deception) used against him. No honour among thieves.",
  },
  {
    topic: "eng_fw_ch4", topicId: "eng_fw_ch4",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Horace remove his gloves when opening the safe in 'A Question of Trust'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The woman (posing as owner) convinced him that gloves would make the task harder; he was charmed into lowering his guard", type: "correct", logicTag: "" },
      { text: "He removed his gloves because the safe lock was very delicate and needed touch sensitivity", type: "concept_error", logicTag: "partial_truth_wrong_cause" },
      { text: "He had left his gloves at home and had no choice", type: "concept_error", logicTag: "wrong_reason" },
      { text: "He trusted the woman completely and didn't think he needed protection", type: "partial_logic", logicTag: "effect_not_cause" },
    ],
    solutionSteps: ["The woman flirted and charmed Horace.", "She asked him to remove his gloves under the guise of needing quick work.", "He complied — his guard dropped because of her charm and the false authority she projected."],
    shortcut: "Gloves removed: charmed/manipulated by woman's authority + flirtation. He trusted her = his fatal mistake.",
  },
  {
    topic: "eng_fw_ch4", topicId: "eng_fw_ch4",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What happened to Horace Danby after he was caught in 'A Question of Trust'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He was arrested and sent to prison; he now makes toys in jail and is no longer trusted by anyone", type: "correct", logicTag: "" },
      { text: "He escaped and continued his burglary career in another city", type: "concept_error", logicTag: "wrong_ending" },
      { text: "He was released due to lack of evidence", type: "concept_error", logicTag: "wrong_ending" },
      { text: "He turned informer and helped police catch the woman who tricked him", type: "concept_error", logicTag: "wrong_ending" },
    ],
    solutionSteps: ["Horace was caught with his fingerprints on the safe.", "No jewels were found on him — the woman had taken them.", "He was convicted and sentenced to two years in prison.", "He now makes toys, not safes, and has difficulty being believed."],
    shortcut: "Horace convicted: 2 years prison. Makes toys now. Can't be believed when he tells the truth about the woman.",
  },
  {
    topic: "eng_fw_ch4", topicId: "eng_fw_ch4",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does 'A Question of Trust' suggest about the consequences of dishonesty?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Dishonesty undermines one's ability to be believed even when telling the truth — losing trust is a lasting punishment", type: "correct", logicTag: "" },
      { text: "Dishonesty always leads to prison, which fully remedies the problem", type: "concept_error", logicTag: "simplistic" },
      { text: "Smart criminals can always find ways to avoid the consequences of dishonesty", type: "concept_error", logicTag: "wrong_moral" },
      { text: "Women are more dishonest than men, as shown by the female thief", type: "concept_error", logicTag: "gender_misread" },
    ],
    solutionSteps: ["Horace tells the truth about the woman who framed him — but no one believes him.", "His reputation as a thief means his honest account is dismissed.", "The story's sharpest punishment: a thief speaks truth and cannot be trusted even then."],
    shortcut: "Deepest punishment: Horace tells truth, no one believes him. Past dishonesty destroys future credibility. Lasting consequence.",
  },
  {
    topic: "eng_fw_ch4", topicId: "eng_fw_ch4",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What literary device does the title 'A Question of Trust' employ?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Irony — trust is central to the story, but everyone who trusts is betrayed", type: "correct", logicTag: "" },
      { text: "Alliteration — repetition of the 't' sound", type: "concept_error", logicTag: "not_primary_device" },
      { text: "Metaphor — trust is compared to a question mark", type: "concept_error", logicTag: "overreach" },
      { text: "Foreshadowing — the title warns readers about the betrayal to come", type: "partial_logic", logicTag: "secondary_function" },
    ],
    solutionSteps: ["The title is ironic: trust is supposed to be the foundation of relationships.", "In this story, trust is the weapon used by the female thief and the fatal flaw of Horace.", "Both the victim (house) and the criminal (Horace) fall because of misplaced trust."],
    shortcut: "Title's irony: trust = weapon. Horace trusted woman. She weaponised his trust. 'Question of trust' = who can you trust?",
  },

  // ── eng_fw_ch5 — Footprints Without Feet ────────────────────────────────
  {
    topic: "eng_fw_ch5", topicId: "eng_fw_ch5",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Footprints Without Feet', what scientific discovery had Griffin made?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He discovered a way to make the human body transparent (invisible)", type: "correct", logicTag: "" },
      { text: "He discovered a way to walk through solid walls", type: "concept_error", logicTag: "wrong_discovery" },
      { text: "He invented a potion to become extremely strong", type: "concept_error", logicTag: "wrong_discovery" },
      { text: "He found a formula for immortality", type: "concept_error", logicTag: "wrong_discovery" },
    ],
    solutionSteps: ["Griffin was a scientist who experimented on himself.", "He discovered that a human body could become invisible if the refractive index was changed to that of air.", "He swallowed certain drugs and became transparent."],
    shortcut: "Griffin's discovery: human body can become transparent/invisible by changing refractive index. He tested it on himself.",
  },
  {
    topic: "eng_fw_ch5", topicId: "eng_fw_ch5",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why were footprints appearing out of nowhere in the muddy London street in 'Footprints Without Feet'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "The invisible Griffin was walking barefoot through the mud, leaving visible footprints", type: "correct", logicTag: "" },
      { text: "A ghost was haunting the streets of London", type: "concept_error", logicTag: "wrong_explanation" },
      { text: "Children were playing a prank with special invisible shoes", type: "concept_error", logicTag: "wrong_explanation" },
      { text: "A machine was creating random impressions in the mud for scientific testing", type: "concept_error", logicTag: "wrong_explanation" },
    ],
    solutionSteps: ["Griffin was invisible but not weightless.", "When he walked on mud or snow, his body weight left impressions.", "In London's muddy streets, curious onlookers saw footprints appearing and disappearing."],
    shortcut: "Footprints = Griffin walking barefoot (invisible). Transparent but has mass. Mud/snow show his prints.",
  },
  {
    topic: "eng_fw_ch5", topicId: "eng_fw_ch5",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'Footprints Without Feet'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Scientific ability without moral responsibility leads to crime and harm", type: "correct", logicTag: "" },
      { text: "Invisibility is a superpower that would benefit humanity", type: "concept_error", logicTag: "wrong_reading" },
      { text: "Science should be kept secret to prevent misuse by criminals", type: "concept_error", logicTag: "misreads_lesson" },
      { text: "The British police were incompetent in dealing with scientific crimes", type: "concept_error", logicTag: "not_the_theme" },
    ],
    solutionSteps: ["Griffin had a brilliant scientific mind.", "He used his discovery for theft, arson, and lawless rampage.", "The story shows that science in the hands of an immoral person is dangerous."],
    shortcut: "Theme: scientific genius + moral bankruptcy = danger. Griffin's problem isn't intelligence; it's lack of ethics.",
  },
  {
    topic: "eng_fw_ch5", topicId: "eng_fw_ch5",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What crimes did Griffin commit using his invisibility in 'Footprints Without Feet'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Set fire to his landlord's house, stole from a London store, robbed a theatre owner, and stole from a vicar's home", type: "correct", logicTag: "" },
      { text: "He only stole food and clothing to survive as he had no money", type: "concept_error", logicTag: "minimises_crimes" },
      { text: "He murdered two people and escaped punishment", type: "concept_error", logicTag: "wrong_crimes" },
      { text: "He broke into a laboratory to steal scientific equipment", type: "concept_error", logicTag: "partial_wrong" },
    ],
    solutionSteps: ["1. Burned his landlord's house (evicted, took revenge).", "2. Broke into Drury Lane theatre, stole costume/bandages.", "3. Robbed London stores for food/money.", "4. Stole from a vicar and his wife in Iping.", "Pattern = escalating crimes with increasing violence."],
    shortcut: "Griffin's crimes: arson → costume theft → shop robbery → vicar robbery. Escalating from revenge to routine crime.",
  },
  {
    topic: "eng_fw_ch5", topicId: "eng_fw_ch5",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Griffin wrap bandages around his face and hands in Iping village?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "To become visible so he could rent a room and interact in the village without looking suspicious", type: "correct", logicTag: "" },
      { text: "Because he was injured from his arson fire and needed medical care", type: "concept_error", logicTag: "wrong_reason" },
      { text: "To disguise himself from police who were hunting him", type: "partial_logic", logicTag: "secondary_reason" },
      { text: "Because winter was cold and he needed warmth", type: "concept_error", logicTag: "wrong_reason" },
    ],
    solutionSteps: ["Griffin was invisible — he needed to cover his body to be 'seen'.", "He wore clothes, bandages, hat, and dark glasses.", "Without covering, people would see floating clothes and no body.", "In Iping, he rented a room at the Coach and Horses inn."],
    shortcut: "Bandages + clothes = makes invisible Griffin visible. Without coverings, people see nothing (or floating items).",
  },
  {
    topic: "eng_fw_ch5", topicId: "eng_fw_ch5",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Griffin's invisibility was meant to be a scientific breakthrough. Why did it become a curse instead?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Because Griffin had no moral framework to guide his use of the power — he used it selfishly and criminally rather than for human benefit", type: "correct", logicTag: "" },
      { text: "Because invisibility is physically painful and makes the person ill", type: "concept_error", logicTag: "not_stated" },
      { text: "Because other scientists discovered his formula and copied it to commit crimes", type: "concept_error", logicTag: "wrong_plot" },
      { text: "Because the British government wanted to use his discovery as a weapon", type: "concept_error", logicTag: "not_in_story" },
    ],
    solutionSteps: ["Griffin's discovery was scientifically remarkable.", "But he used it to: burn houses, steal, terrorise.", "The problem = the scientist, not the science. Power without ethics = destruction.", "This is H.G. Wells's broader message about unchecked scientific progress."],
    shortcut: "Invisibility + immoral scientist = disaster. Wells's message: science without ethics is dangerous. Griffin = brilliant but lawless.",
  },
  {
    topic: "eng_fw_ch5", topicId: "eng_fw_ch5",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How does H.G. Wells describe Griffin's character through his actions in the story?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "As a brilliant but reckless and lawless man who prioritises his own survival and desires over others' rights", type: "correct", logicTag: "" },
      { text: "As a misunderstood genius driven to crime by society's rejection", type: "concept_error", logicTag: "sympathetic_overread" },
      { text: "As a hero who uses his powers to fight injustice", type: "concept_error", logicTag: "wrong_reading" },
      { text: "As a tragic figure who never intended any harm", type: "concept_error", logicTag: "contradicts_text" },
    ],
    solutionSteps: ["Griffin set fire to his landlord's house without remorse.", "He robbed, threatened, and injured people.", "Wells presents him as an antagonist — his genius does not excuse his cruelty.", "He is described as 'lawless.'"],
    shortcut: "Griffin = brilliant + lawless. Wells doesn't sympathise. His genius ≠ excuse for cruelty and crime.",
  },

  // ── eng_fw_ch6 — The Making of a Scientist ──────────────────────────────
  {
    topic: "eng_fw_ch6", topicId: "eng_fw_ch6",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Making of a Scientist', what was Richard Ebright's first major scientific project?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "He tried to find the cause of a viral disease that was killing monarch butterflies", type: "correct", logicTag: "" },
      { text: "He built a working model of a rocket engine as a school science project", type: "concept_error", logicTag: "wrong_project" },
      { text: "He mapped the migration routes of monarch butterflies across North America", type: "concept_error", logicTag: "earlier_work_misattributed" },
      { text: "He discovered a new species of butterfly in the Amazon rainforest", type: "concept_error", logicTag: "wrong_project" },
    ],
    solutionSteps: ["Ebright had collected butterflies since childhood.", "He entered the county science fair with a project on the viral disease killing monarch butterflies.", "This led him to discover that the gold spots on monarch chrysalises produce a hormone."],
    shortcut: "Ebright's first big project: viral disease killing monarch butterflies. Led to hormone discovery from gold spots.",
  },
  {
    topic: "eng_fw_ch6", topicId: "eng_fw_ch6",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What major discovery did Richard Ebright make about the gold spots on monarch butterfly chrysalises?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The gold spots produce a hormone that is necessary for the butterfly's full development", type: "correct", logicTag: "" },
      { text: "The gold spots are used for camouflage from predators", type: "concept_error", logicTag: "wrong_function" },
      { text: "The gold spots are a sign of disease and disappear when the butterfly is healthy", type: "concept_error", logicTag: "wrong_function" },
      { text: "The gold spots contain minerals that give the butterfly its colour when it emerges", type: "concept_error", logicTag: "wrong_function" },
    ],
    solutionSteps: ["Ebright discovered that the 12 gold spots on a chrysalis produce a juvenile hormone.", "This hormone is needed to trigger a key stage in the butterfly's development.", "This was a significant scientific finding published in a journal."],
    shortcut: "Gold spots on chrysalis → produce a juvenile hormone → needed for butterfly's full development. Ebright's big discovery.",
  },
  {
    topic: "eng_fw_ch6", topicId: "eng_fw_ch6",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the story 'The Making of a Scientist' suggest about what makes a great scientist?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A combination of curiosity, hard work, competitive spirit, and a good mentor", type: "correct", logicTag: "" },
      { text: "Natural genius alone — Ebright was born a prodigy who didn't need effort", type: "concept_error", logicTag: "contradicts_story" },
      { text: "Access to expensive equipment and top-ranked laboratories", type: "concept_error", logicTag: "wrong_factor" },
      { text: "Coming from a privileged academic family with scientific heritage", type: "concept_error", logicTag: "not_stated" },
    ],
    solutionSteps: ["Ebright = curious from childhood (collecting butterflies, rocks, fossils, coins).", "He was competitive (won multiple science fairs).", "His mother and a scientist mentor encouraged him.", "Story emphasises character, not background, as the key to scientific achievement."],
    shortcut: "What makes a scientist: curiosity + hard work + competition + good mentor. Not just genius or privilege.",
  },
  {
    topic: "eng_fw_ch6", topicId: "eng_fw_ch6",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What role did Ebright's mother play in his scientific development?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She nurtured his curiosity by giving him telescopes, microscopes, and books, and took him on field trips", type: "correct", logicTag: "" },
      { text: "She enrolled him in a specialist science school that advanced his career", type: "concept_error", logicTag: "wrong_role" },
      { text: "She was a scientist herself and directly guided his experiments", type: "concept_error", logicTag: "wrong_role" },
      { text: "She had no role — Ebright was entirely self-motivated from childhood", type: "concept_error", logicTag: "contradicts_story" },
    ],
    solutionSteps: ["Ebright's father died young.", "His mother was his constant companion and supporter.", "She gave him a book on monarch butterflies, took him to scientific lectures, and provided equipment.", "Her encouragement was fundamental to his early development."],
    shortcut: "Mother's role = key encourager. Gave books, microscopes, telescopes. Took him to lectures. Solo parent, huge impact.",
  },
  {
    topic: "eng_fw_ch6", topicId: "eng_fw_ch6",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What was the later theoretical work Ebright did related to cell theory?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "He and his roommate proposed a new theory explaining how cells 'read' their DNA to develop properly", type: "correct", logicTag: "" },
      { text: "He discovered a new type of cell found only in butterfly wings", type: "concept_error", logicTag: "wrong_work" },
      { text: "He found the cure for a genetic disease in humans using butterfly hormone research", type: "concept_error", logicTag: "wrong_work" },
      { text: "He proposed that butterfly migration is controlled by a special type of brain cell", type: "concept_error", logicTag: "wrong_work" },
    ],
    solutionSteps: ["Ebright and his college roommate proposed a theory on how cells 'read' their genetic blueprint.", "This theory could explain how the DNA 'programme' is executed in a living organism.", "It was connected to his earlier hormone work."],
    shortcut: "Later work: theory on how cells read DNA. Connects to hormone work. Could explain cell development/differentiation.",
  },
  {
    topic: "eng_fw_ch6", topicId: "eng_fw_ch6",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What quality of Ebright's character is highlighted by his diverse interests (debate, public speaking, politics, photography)?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "He was a well-rounded achiever who applied the same competitive excellence to every area of life", type: "correct", logicTag: "" },
      { text: "He was distracted from science by too many hobbies", type: "concept_error", logicTag: "wrong_inference" },
      { text: "He was a typical overachiever with no genuine passion", type: "concept_error", logicTag: "wrong_reading" },
      { text: "He was interested in everything except science as a child", type: "concept_error", logicTag: "factually_wrong" },
    ],
    solutionSteps: ["Besides science, Ebright excelled in debate, canoeing, public speaking, and politics.", "He was a straight-A student and winner in multiple arenas.", "This shows that excellence in one area often comes with a broader excellence mentality."],
    shortcut: "Ebright = excellent in everything. Science + debate + politics + sports. Excellence mentality, not narrow specialist.",
  },
  {
    topic: "eng_fw_ch6", topicId: "eng_fw_ch6",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does the title 'The Making of a Scientist' suggest about how scientists develop?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Scientists are made through a gradual process of learning, mentoring, and experience — not born fully formed", type: "correct", logicTag: "" },
      { text: "Only people born with scientific talent can become scientists", type: "concept_error", logicTag: "contradicts_title" },
      { text: "Scientific training happens only in universities, not in childhood", type: "concept_error", logicTag: "contradicts_story" },
      { text: "The title refers to Ebright's work on making butterflies in a laboratory", type: "concept_error", logicTag: "literal_misread" },
    ],
    solutionSteps: ["'Making' implies a process, not an innate gift.", "The story shows step-by-step how Ebright developed: butterfly collection → science fairs → hormone research → cell theory.", "The title = development over time, not instant genius."],
    shortcut: "Title meaning: scientists are MADE (process), not born. Ebright's story = gradual steps from curious child to scientist.",
  },

  // ── eng_fw_ch7 — The Necklace ─────────────────────────────────────────────
  {
    topic: "eng_fw_ch7", topicId: "eng_fw_ch7",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Necklace', what was Matilda Loisel's main source of unhappiness?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She was a beautiful woman born into a poor family and could not stop dreaming of the luxury she felt she deserved", type: "correct", logicTag: "" },
      { text: "Her husband was cruel and refused to let her socialise", type: "concept_error", logicTag: "wrong_reason" },
      { text: "She had a chronic illness that prevented her from enjoying life", type: "concept_error", logicTag: "wrong_reason" },
      { text: "She was jealous of her friend Mme Forestier's beauty", type: "concept_error", logicTag: "wrong_reason" },
    ],
    solutionSteps: ["Matilda felt she was born for a life of luxury but had none.", "She dreamed of fine apartments, exquisite food, jewels, beautiful clothes.", "The gap between dream and reality caused constant unhappiness."],
    shortcut: "Matilda's problem = discontent. Believes she deserves luxury but lives modestly. Dreams ≠ reality = constant unhappiness.",
  },
  {
    topic: "eng_fw_ch7", topicId: "eng_fw_ch7",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What happened to the necklace Matilda borrowed in 'The Necklace'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "It was lost — she could not find it after the ball", type: "correct", logicTag: "" },
      { text: "It was stolen from her at the ball by a pickpocket", type: "concept_error", logicTag: "wrong_cause" },
      { text: "The clasp broke and the beads scattered on the dance floor", type: "concept_error", logicTag: "invented" },
      { text: "She accidentally dropped it into the Seine River", type: "concept_error", logicTag: "invented" },
    ],
    solutionSteps: ["After the ball, Matilda discovered the necklace was missing.", "She and her husband searched everywhere but couldn't find it.", "They decided to replace it — borrowing money to buy a diamond necklace for 36,000 francs."],
    shortcut: "Necklace lost after the ball. No explanation given — simply vanished. Replaced with real diamonds for 36,000 francs.",
  },
  {
    topic: "eng_fw_ch7", topicId: "eng_fw_ch7",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'The Necklace' by Guy de Maupassant?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The destructive nature of vanity, false pride, and the desire for a social status one cannot afford", type: "correct", logicTag: "" },
      { text: "The importance of honesty — Matilda should have told Mme Forestier the truth immediately", type: "partial_logic", logicTag: "secondary_moral" },
      { text: "The cruelty of French class society in the 19th century", type: "concept_error", logicTag: "background_not_theme" },
      { text: "Women are naturally vain and irresponsible with money", type: "concept_error", logicTag: "sexist_misread" },
    ],
    solutionSteps: ["Matilda's vanity led her to borrow jewels she didn't need.", "Losing the necklace led to ten years of poverty.", "The twist reveals the necklace was fake — her real life was destroyed for a fake aspiration.", "Theme = vanity and false pride lead to real suffering."],
    shortcut: "Theme = vanity destroys. Borrowed fake jewels → lost → 10 years suffering → necklace was fake. Irony + moral.",
  },
  {
    topic: "eng_fw_ch7", topicId: "eng_fw_ch7",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the dramatic irony at the end of 'The Necklace'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The original necklace was fake/paste — the Loisels spent ten years in poverty replacing a necklace worth only 500 francs with one worth 36,000 francs", type: "correct", logicTag: "" },
      { text: "Mme Forestier had already found the necklace and said nothing", type: "concept_error", logicTag: "wrong_plot" },
      { text: "The necklace was insured and could have been replaced for free", type: "concept_error", logicTag: "invented" },
      { text: "Matilda's husband had actually stolen the original necklace and hidden it", type: "concept_error", logicTag: "invented_plot" },
    ],
    solutionSteps: ["Matilda tells Mme Forestier the whole story at the end.", "Mme Forestier reveals: 'Oh, my poor Matilda! But mine was paste. It was worth at most five hundred francs!'", "Ten years of hardship to replace a worthless fake — this is devastating dramatic irony."],
    shortcut: "Twist: original necklace = fake (500 francs). They suffered 10 years replacing it with real diamonds (36,000 francs). Cruel irony.",
  },
  {
    topic: "eng_fw_ch7", topicId: "eng_fw_ch7",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How did Matilda Loisel change physically and mentally after ten years of poverty in 'The Necklace'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "She became rough, strong, and coarse — all the delicacy and beauty of her youth had vanished through hard work", type: "correct", logicTag: "" },
      { text: "She became wiser and found true happiness in simple things", type: "concept_error", logicTag: "wishful_reading" },
      { text: "She became more vain and bitter, never accepting her poverty", type: "concept_error", logicTag: "incorrect" },
      { text: "She improved her social standing through hard work and married a wealthier man", type: "concept_error", logicTag: "wrong_outcome" },
    ],
    solutionSteps: ["Matilda took on all the heavy housework to save money.", "She washed, cleaned, cooked, bargained, and scolded.", "Her beauty disappeared — she looked like a poor, coarse woman.", "The irony: the beauty she had prized was gone, along with everything else."],
    shortcut: "Matilda after 10 years: rough, old, coarse. Lost her beauty — the very thing she prized most. Full tragic irony.",
  },
  {
    topic: "eng_fw_ch7", topicId: "eng_fw_ch7",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Maupassant suggest through the ending of 'The Necklace' about the consequences of deception?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "A moment of vanity and a small deception (not confessing the loss) can spiral into a lifetime of suffering", type: "correct", logicTag: "" },
      { text: "Deception is justified when it protects someone's dignity", type: "concept_error", logicTag: "wrong_lesson" },
      { text: "Society is to blame for Matilda's suffering because it rewards wealth and beauty", type: "partial_logic", logicTag: "social_critique_not_primary" },
      { text: "Honesty always leads to a worse outcome than deception", type: "concept_error", logicTag: "contradicts_story" },
    ],
    solutionSteps: ["Matilda's deception: not telling Mme Forestier the truth → the snowball of debt.", "One honest conversation at the start would have revealed the necklace was fake (500 francs).", "Instead, false pride + avoidance of honesty → ten years of ruin.", "Maupassant: small self-deceptions have enormous consequences."],
    shortcut: "Maupassant's lesson: one honest conversation could have saved 10 years. Pride + deception = compounded catastrophe.",
  },
  {
    topic: "eng_fw_ch7", topicId: "eng_fw_ch7",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Matilda not simply tell Mme Forestier that the necklace was lost?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "She was too proud to admit the loss and feared social embarrassment and Mme Forestier's reaction", type: "correct", logicTag: "" },
      { text: "She planned to find the necklace before Mme Forestier noticed", type: "concept_error", logicTag: "partial_reason" },
      { text: "Mme Forestier had gone abroad and was unreachable", type: "concept_error", logicTag: "wrong_reason" },
      { text: "She could not afford the original necklace's price and wanted to avoid being shamed", type: "partial_logic", logicTag: "effect_not_primary_cause" },
    ],
    solutionSteps: ["Matilda's pride was her central flaw.", "Admitting the loss would mean admitting she had been careless with a friend's valuable jewel.", "Her vanity/pride prevented the one action that could have saved them."],
    shortcut: "Matilda didn't confess = pride. She could not bear the shame. Pride → silence → 10-year tragedy.",
  },

  // ── eng_fw_ch8 — Bholi ────────────────────────────────────────────────────
  {
    topic: "eng_fw_ch8", topicId: "eng_fw_ch8",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'Bholi', why was Bholi considered the least important child in the family?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She had fallen from a cot as an infant, was disfigured by smallpox, and her brain had been slightly damaged — she was considered dull and ugly", type: "correct", logicTag: "" },
      { text: "She was the youngest and parents typically favour older children", type: "concept_error", logicTag: "wrong_reason" },
      { text: "She was blind from birth and dependent on others", type: "concept_error", logicTag: "wrong_disability" },
      { text: "She was stubborn and always disobeyed, making parents ashamed of her", type: "concept_error", logicTag: "wrong_reason" },
    ],
    solutionSteps: ["Bholi (Sulekha) fell from a cot at age two — damaged her brain slightly.", "She later caught smallpox, leaving pockmarks on her face.", "She stuttered and was slow to learn.", "Parents saw her as a burden — dull and unmarriageable."],
    shortcut: "Bholi: fell as baby (brain damage) + smallpox (pockmarks) + stutter. Parents see her as burden, unmarriageable.",
  },
  {
    topic: "eng_fw_ch8", topicId: "eng_fw_ch8",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How did school transform Bholi in 'Bholi'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Her teacher showed her warmth and encouragement, building her confidence and removing her stutter; education gave her a voice and self-respect", type: "correct", logicTag: "" },
      { text: "School gave her medical treatment that cured her stutter and pockmarks", type: "concept_error", logicTag: "wrong_mechanism" },
      { text: "She won a prize at school that made her family respect her for the first time", type: "concept_error", logicTag: "invented" },
      { text: "She became popular and found many friends who accepted her appearance", type: "concept_error", logicTag: "not_stated" },
    ],
    solutionSteps: ["Bholi's teacher patted her back, gave her a picture book, and spoke to her kindly.", "This first act of encouragement opened Bholi up.", "Over years, she gained confidence, lost her stutter, and became articulate.", "Education = her real transformation."],
    shortcut: "Teacher's warmth = Bholi's transformation. Encouragement → confidence → education → strong voice. School = her salvation.",
  },
  {
    topic: "eng_fw_ch8", topicId: "eng_fw_ch8",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the central theme of 'Bholi'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Education empowers the marginalized and gives them the courage to stand up against social injustice", type: "correct", logicTag: "" },
      { text: "Physical beauty is more important than intelligence for social acceptance", type: "concept_error", logicTag: "contradicts_theme" },
      { text: "Parents should not arrange marriages without asking their children", type: "concept_error", logicTag: "secondary_point" },
      { text: "Greedy men will always exploit poor families at the time of marriage", type: "partial_logic", logicTag: "secondary_theme" },
    ],
    solutionSteps: ["Bholi was dismissed as useless because of her appearance and speech.", "Education transformed her into a confident, articulate person.", "Her education allowed her to refuse a greedy, disrespectful suitor publicly — a tremendous act of courage.", "Theme = education as empowerment and social liberation."],
    shortcut: "Theme = education as empowerment. Bholi goes from 'dumb cow' (family's words) to brave woman who refuses Bishamber.",
  },
  {
    topic: "eng_fw_ch8", topicId: "eng_fw_ch8",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Why did Bholi refuse to marry Bishamber Nath at the wedding ceremony?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "When Bishamber demanded a dowry (5,000 rupees) to accept her despite her pockmarks, she threw down the garland — she would not be bought", type: "correct", logicTag: "" },
      { text: "She loved someone else and could not go through with the marriage", type: "concept_error", logicTag: "wrong_reason" },
      { text: "She found out Bishamber had been married three times before", type: "concept_error", logicTag: "partial_wrong" },
      { text: "Her teacher arrived and convinced her to refuse at the last moment", type: "concept_error", logicTag: "wrong_agent" },
    ],
    solutionSteps: ["Bishamber Nath was old, lame, and had children from previous marriages.", "At the wedding, he demanded 5,000 rupees to accept Bholi with her pockmarks.", "Bholi's father began counting money — humiliated.", "Bholi spoke up: she threw down the garland and refused to marry a covetous, greedy man."],
    shortcut: "Bishamber demanded 5,000 rupees dowry for 'accepting' Bholi's pockmarks. Bholi refused: threw garland down. Self-respect won.",
  },
  {
    topic: "eng_fw_ch8", topicId: "eng_fw_ch8",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What did Bholi say she would do after refusing to marry Bishamber Nath?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "She would take care of her old parents and teach at the same school where her teacher had transformed her", type: "correct", logicTag: "" },
      { text: "She would leave the village and go to the city for work", type: "concept_error", logicTag: "wrong_plan" },
      { text: "She would join a women's rights organisation to fight dowry", type: "concept_error", logicTag: "invented" },
      { text: "She would pursue further studies and become a doctor", type: "concept_error", logicTag: "invented" },
    ],
    solutionSteps: ["After refusing Bishamber, Bholi said she would stay home and care for her aged parents.", "She also said she would teach at the same village school.", "Her plan shows independence and purpose — a complete reversal from her earlier helplessness."],
    shortcut: "Bholi's plan: care for parents + teach at village school. Independence + purpose. Full circle from helpless child to teacher.",
  },
  {
    topic: "eng_fw_ch8", topicId: "eng_fw_ch8",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "How does the character of Bholi challenge the social expectations of rural Indian women in the story?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "She refuses a socially arranged match, speaks publicly against a man, and chooses self-reliance — all radical acts for a rural woman of her time", type: "correct", logicTag: "" },
      { text: "She conforms to social expectations and accepts her family's decision quietly", type: "concept_error", logicTag: "contradicts_story" },
      { text: "She runs away from home, breaking with tradition entirely", type: "concept_error", logicTag: "wrong_action" },
      { text: "She challenges social norms by marrying a man of a different caste", type: "concept_error", logicTag: "not_in_story" },
    ],
    solutionSteps: ["Bholi publicly refuses a suitor — rare for rural women.", "She speaks clearly and firmly against her father's compliance.", "She chooses to remain single and work — not traditional for women of her village context.", "All of this is made possible by education."],
    shortcut: "Bholi breaks norms: refuses arranged match, speaks up publicly, chooses work over marriage. Education = radical transformation.",
  },

  // ── eng_fw_ch9 — The Book That Saved the Earth ───────────────────────────
  {
    topic: "eng_fw_ch9", topicId: "eng_fw_ch9",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "In 'The Book That Saved the Earth', who were the invaders who planned to conquer Earth?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Martians (inhabitants of Mars) led by Think-Tank", type: "correct", logicTag: "" },
      { text: "Robots from the planet Zorg", type: "concept_error", logicTag: "wrong_planet" },
      { text: "Earthlings from the future who had travelled back in time", type: "concept_error", logicTag: "wrong_invaders" },
      { text: "Venusians who wanted to colonise Earth", type: "concept_error", logicTag: "wrong_planet" },
    ],
    solutionSteps: ["The story is set in the 25th century.", "Think-Tank, the ruler of Mars, planned to invade Earth in the 20th century.", "His crew of Martians was sent to explore Earth first."],
    shortcut: "Invaders = Martians. Leader = Think-Tank. Setting = 25th century historian narrating 20th century events.",
  },
  {
    topic: "eng_fw_ch9", topicId: "eng_fw_ch9",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What object confused the Martians when they entered the library in 'The Book That Saved the Earth'?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Books — they had never seen books before and mistook them for sandwiches and then for communication devices", type: "correct", logicTag: "" },
      { text: "Computers — they could not understand human technology", type: "concept_error", logicTag: "wrong_object" },
      { text: "Telephones — they mistook them for weapons", type: "concept_error", logicTag: "wrong_object" },
      { text: "Televisions — they thought they were boxes of light", type: "concept_error", logicTag: "wrong_object" },
    ],
    solutionSteps: ["The Martians entered a public library.", "They found books on shelves and had no idea what they were.", "Think-Tank first thought they were sandwiches (for eating).", "Then he thought they were communication devices (for listening).", "Finally, he decided they were 'eye communication' devices for reading."],
    shortcut: "Martians puzzled by books: first thought edible (sandwiches), then audio, then visual. Humour = aliens reading nursery rhymes.",
  },
  {
    topic: "eng_fw_ch9", topicId: "eng_fw_ch9",
    subtopic: "Theme", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What book saved the Earth in the play 'The Book That Saved the Earth'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "A book of nursery rhymes — the Martians misread 'Mistress Mary' and other rhymes as military intelligence and fled in terror", type: "correct", logicTag: "" },
      { text: "A science textbook that gave the Martians terrible information about Earth's weapons", type: "concept_error", logicTag: "wrong_book" },
      { text: "A novel that predicted Earth would fight back and defeat Mars", type: "concept_error", logicTag: "wrong_book" },
      { text: "An encyclopaedia that proved Earth was too dangerous to invade", type: "concept_error", logicTag: "wrong_book" },
    ],
    solutionSteps: ["The Martians read a nursery rhyme book.", "They misinterpreted 'Mistress Mary, quite contrary, how does your garden grow?' as a military secret about weapons.", "'Little Miss Muffet sat on a tuffet' was read as a spy message.", "Think-Tank ordered retreat — Earth's 'intelligence' was too advanced for them."],
    shortcut: "Nursery rhyme book saved Earth. Martians misread children's rhymes as military secrets. Think-Tank ordered retreat in fear.",
  },
  {
    topic: "eng_fw_ch9", topicId: "eng_fw_ch9",
    subtopic: "Language", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the genre and tone of 'The Book That Saved the Earth'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Science fiction comedy (farce) — it uses space setting and alien characters to create absurd humour", type: "correct", logicTag: "" },
      { text: "Horror fiction — the Martian invasion is portrayed as a terrifying near-disaster", type: "concept_error", logicTag: "wrong_tone" },
      { text: "Historical drama — it accurately depicts 20th century events", type: "concept_error", logicTag: "wrong_genre" },
      { text: "Dystopian fiction — it warns about the dangers of alien life", type: "concept_error", logicTag: "wrong_genre" },
    ],
    solutionSteps: ["The setting is futuristic (25th century).", "Characters are aliens who misunderstand everything.", "The humour is absurd — aliens terrified by nursery rhymes.", "Genre = sci-fi comedy/farce."],
    shortcut: "Genre = sci-fi comedy/farce. Aliens terrified by nursery rhymes = peak absurdist humour. Not horror, not serious sci-fi.",
  },
  {
    topic: "eng_fw_ch9", topicId: "eng_fw_ch9",
    subtopic: "Analysis", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What does Think-Tank's character represent in 'The Book That Saved the Earth'?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "An arrogant leader who believes he knows everything but is completely wrong — a satire on pompous authority", type: "correct", logicTag: "" },
      { text: "A wise and careful leader who rightly decides not to invade Earth", type: "concept_error", logicTag: "wrong_characterisation" },
      { text: "A cowardly ruler who abandons his people at the first sign of danger", type: "partial_logic", logicTag: "secondary_trait" },
      { text: "An evil villain with a carefully planned strategy for domination", type: "concept_error", logicTag: "wrong_characterisation" },
    ],
    solutionSteps: ["Think-Tank has a huge head (signifying his arrogance about his 'great brain').", "He confidently misinterprets everything.", "His biggest blunder = ordering retreat from a children's book.", "He is a satire on arrogant, pompous leaders who refuse to admit they don't understand."],
    shortcut: "Think-Tank = satire on arrogant leaders. Big head (literal), big ego, wrong about everything. Pomposity = his downfall.",
  },
  {
    topic: "eng_fw_ch9", topicId: "eng_fw_ch9",
    subtopic: "Evaluation", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "What is the underlying message of 'The Book That Saved the Earth' about books?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 1, isAIGenerated: true,
    options: [
      { text: "Books are powerful — even a children's book can seem formidable to the ignorant, reminding us of the power of literacy and knowledge", type: "correct", logicTag: "" },
      { text: "Books are dangerous weapons that should be controlled by the government", type: "concept_error", logicTag: "misreads_message" },
      { text: "Only advanced scientific books have real value; children's books are trivial", type: "concept_error", logicTag: "contradicts_play" },
      { text: "The Martians were right to fear books as they contain secret human knowledge", type: "concept_error", logicTag: "literal_misread" },
    ],
    solutionSteps: ["A nursery rhyme book saved Earth — the most 'trivial' type of book.", "The play argues: all books have power.", "To the ignorant (Martians), even a simple book is incomprehensible and threatening.", "Message: literacy and books are humanity's greatest strength."],
    shortcut: "Message: books = power. Even a nursery rhyme book terrifies the ignorant. Humanity's strength = literacy/knowledge.",
  },
  {
    topic: "eng_fw_ch9", topicId: "eng_fw_ch9",
    subtopic: "Comprehension", subject: "English", grade: "10", examBoard: "CBSE",
    questionText: "Where is the play 'The Book That Saved the Earth' set and narrated from?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "The Great Museum of Mars in the 25th century — a historian narrates past events", type: "correct", logicTag: "" },
      { text: "A space station orbiting Earth in the year 3000", type: "concept_error", logicTag: "wrong_setting" },
      { text: "A library in London where aliens secretly landed", type: "concept_error", logicTag: "wrong_setting" },
      { text: "The United Nations headquarters in the year 2050", type: "concept_error", logicTag: "wrong_setting" },
    ],
    solutionSteps: ["The frame narrative is set in The Great Museum of Mars in the 25th century.", "A historian narrates 'the invasion that never was' — the events of the 20th century.", "This narrative frame makes it clear the invasion failed — we read events with hindsight."],
    shortcut: "Setting: Great Museum of Mars, 25th century. Historian narrates past (20th century) events. Frame narrative structure.",
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI, { serverSelectionTimeoutMS: 10_000 });
  console.log("MongoDB connected");

  let created = 0, skipped = 0;
  for (const q of Q) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    created++;
  }
  console.log(`\n✅ English QuestionsC (Footprints): ${created} created, ${skipped} skipped (${Q.length} total)`);
  await mongoose.disconnect();
}

run().catch((err) => { console.error(err); process.exit(1); });
