import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // ── Chapter 13: The Longest Step ── math2_ch13_measuring_length (8 Qs)
  {
    questionId: "math2_ch13_measuring_length_q1",
    topicId: "math2_ch13_measuring_length",
    text: "Why do we measure length?",
    options: [
      { text: "To know how heavy something is", type: "concept_error" },
      { text: "To know how long or short something is", type: "correct" },
      { text: "To know how full a container is", type: "concept_error" },
      { text: "To count objects", type: "concept_error" },
    ],
    explanation: "We measure length to find out how long, tall, or wide something is.",
    solutionSteps: ["Length tells distance from one end to another.", "Not weight, not volume, not counting."],
    shortcut: "Length = how long or short.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_measuring_length_q2",
    topicId: "math2_ch13_measuring_length",
    text: "Anu measures a pencil using her hand-span. This is called ____.",
    options: [
      { text: "Standard measurement", type: "concept_error" },
      { text: "Non-standard measurement", type: "correct" },
      { text: "Weight measurement", type: "concept_error" },
      { text: "Volume measurement", type: "concept_error" },
    ],
    explanation: "Using body parts like hand-span or footstep to measure is non-standard measurement because everyone's hand is a different size.",
    solutionSteps: ["Hand-span varies from person to person.", "Not a fixed unit → non-standard.", "Rulers/cm/m → standard."],
    shortcut: "Body part = non-standard unit.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_measuring_length_q3",
    topicId: "math2_ch13_measuring_length",
    text: "Two children measure the same desk in footsteps. Riya gets 5 steps; Sam gets 7 steps. Why are the answers different?",
    options: [
      { text: "They measured different desks", type: "concept_error" },
      { text: "Their feet are different sizes", type: "correct" },
      { text: "The desk changed size", type: "guessing" },
      { text: "Both are wrong", type: "concept_error" },
    ],
    explanation: "Non-standard units (footsteps) give different answers because people have different foot sizes. That's why standard units like cm and m are used.",
    solutionSteps: ["Same desk, different answers.", "Footstep varies by foot size.", "Bigger foot → fewer steps; smaller foot → more steps."],
    shortcut: "Non-standard unit → unreliable, varies by person.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_measuring_length_q4",
    topicId: "math2_ch13_measuring_length",
    text: "Which is the best tool to measure the length of a notebook?",
    options: [
      { text: "A weighing scale", type: "concept_error" },
      { text: "A measuring cup", type: "concept_error" },
      { text: "A ruler", type: "correct" },
      { text: "A thermometer", type: "concept_error" },
    ],
    explanation: "A ruler measures length. A weighing scale measures weight; a measuring cup measures volume; a thermometer measures temperature.",
    solutionSteps: ["We need to measure length.", "Ruler → measures length.", "Correct tool: ruler."],
    shortcut: "Length → ruler.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_measuring_length_q5",
    topicId: "math2_ch13_measuring_length",
    text: "A pencil is 3 paper clips long. A pen is 5 paper clips long. Which is longer?",
    options: [
      { text: "Pencil", type: "concept_error" },
      { text: "Both are same", type: "concept_error" },
      { text: "Pen", type: "correct" },
      { text: "Cannot say", type: "partial_logic" },
    ],
    explanation: "5 paper clips > 3 paper clips. The pen is longer because it measures more paper clips.",
    solutionSteps: ["Pencil = 3 paper clips.", "Pen = 5 paper clips.", "5 > 3 → pen is longer."],
    shortcut: "More units = longer object.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_measuring_length_q6",
    topicId: "math2_ch13_measuring_length",
    text: "A table is 8 hand-spans long. A bench is 6 hand-spans long. How much longer is the table?",
    options: [
      { text: "1 hand-span", type: "calculation_error" },
      { text: "2 hand-spans", type: "correct" },
      { text: "3 hand-spans", type: "calculation_error" },
      { text: "14 hand-spans", type: "concept_error" },
    ],
    explanation: "8 − 6 = 2. The table is 2 hand-spans longer than the bench.",
    solutionSteps: ["Table: 8 hand-spans.", "Bench: 6 hand-spans.", "Difference: 8 − 6 = 2."],
    shortcut: "Difference = bigger − smaller = 2.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_measuring_length_q7",
    topicId: "math2_ch13_measuring_length",
    text: "Meena's stride is 1 metre. She takes 5 strides. How far did she walk?",
    options: [
      { text: "4 metres", type: "calculation_error" },
      { text: "5 metres", type: "correct" },
      { text: "6 metres", type: "calculation_error" },
      { text: "50 metres", type: "concept_error" },
    ],
    explanation: "5 strides × 1 metre each = 5 metres.",
    solutionSteps: ["Each stride = 1 m.", "5 strides × 1 m = 5 m."],
    shortcut: "Strides × length per stride = total distance.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_measuring_length_q8",
    topicId: "math2_ch13_measuring_length",
    text: "Which statement about non-standard units is TRUE?",
    options: [
      { text: "They give the same result for everyone", type: "concept_error" },
      { text: "They are always more accurate than rulers", type: "concept_error" },
      { text: "They can give different results for different people", type: "correct" },
      { text: "They measure in centimetres", type: "concept_error" },
    ],
    explanation: "Non-standard units (handspans, footsteps) vary from person to person, so they give different results for the same object.",
    solutionSteps: ["Non-standard = not fixed size.", "Different people → different measurement.", "Standard units (cm, m) give same results."],
    shortcut: "Non-standard → different results per person.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },

  // ── math2_ch13_cm_and_m (8 Qs)
  {
    questionId: "math2_ch13_cm_and_m_q1",
    topicId: "math2_ch13_cm_and_m",
    text: "How many centimetres are in 1 metre?",
    options: [
      { text: "10", type: "concept_error" },
      { text: "100", type: "correct" },
      { text: "1000", type: "concept_error" },
      { text: "50", type: "guessing" },
    ],
    explanation: "1 metre = 100 centimetres. A metre stick has 100 equal centimetre divisions.",
    solutionSteps: ["1 m = 100 cm.", "Memorise: 100 cm in 1 m."],
    shortcut: "1 m = 100 cm.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_cm_and_m_q2",
    topicId: "math2_ch13_cm_and_m",
    text: "Which unit would you use to measure the length of a pencil?",
    options: [
      { text: "Metres", type: "concept_error" },
      { text: "Kilometres", type: "concept_error" },
      { text: "Centimetres", type: "correct" },
      { text: "Litres", type: "concept_error" },
    ],
    explanation: "Small objects like pencils are measured in centimetres. Metres are used for longer things like a room; kilometres for very long distances.",
    solutionSteps: ["Pencil is small.", "Use cm for small lengths.", "m for room length, km for distances."],
    shortcut: "Small object → cm.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_cm_and_m_q3",
    topicId: "math2_ch13_cm_and_m",
    text: "A classroom door is about 2 ____ tall.",
    options: [
      { text: "cm", type: "concept_error" },
      { text: "mm", type: "concept_error" },
      { text: "m", type: "correct" },
      { text: "km", type: "concept_error" },
    ],
    explanation: "A door is about 2 metres tall. 2 cm is tiny (width of a finger), and 2 km is extremely long.",
    solutionSteps: ["Door height ≈ 2 m.", "2 cm is too small.", "2 km is enormous."],
    shortcut: "Door-height objects → metres.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_cm_and_m_q4",
    topicId: "math2_ch13_cm_and_m",
    text: "2 metres = ____ centimetres.",
    options: [
      { text: "20", type: "concept_error" },
      { text: "200", type: "correct" },
      { text: "2000", type: "concept_error" },
      { text: "2", type: "concept_error" },
    ],
    explanation: "1 m = 100 cm, so 2 m = 200 cm.",
    solutionSteps: ["1 m = 100 cm.", "2 m = 2 × 100 = 200 cm."],
    shortcut: "Metres × 100 = centimetres.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_cm_and_m_q5",
    topicId: "math2_ch13_cm_and_m",
    text: "Which is longer — 150 cm or 1 m?",
    options: [
      { text: "1 m", type: "concept_error" },
      { text: "150 cm", type: "correct" },
      { text: "Both are equal", type: "concept_error" },
      { text: "Cannot compare", type: "guessing" },
    ],
    explanation: "1 m = 100 cm. 150 cm > 100 cm, so 150 cm is longer.",
    solutionSteps: ["1 m = 100 cm.", "150 cm vs 100 cm.", "150 > 100 → 150 cm is longer."],
    shortcut: "Convert to same unit, then compare.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_cm_and_m_q6",
    topicId: "math2_ch13_cm_and_m",
    text: "A rope is 3 m long. Riya cuts off 50 cm. How much rope is left in cm?",
    options: [
      { text: "200 cm", type: "calculation_error" },
      { text: "250 cm", type: "correct" },
      { text: "350 cm", type: "concept_error" },
      { text: "150 cm", type: "calculation_error" },
    ],
    explanation: "3 m = 300 cm. 300 − 50 = 250 cm of rope remains.",
    solutionSteps: ["3 m = 300 cm.", "Cut 50 cm.", "300 − 50 = 250 cm."],
    shortcut: "Convert m to cm first, then subtract.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_cm_and_m_q7",
    topicId: "math2_ch13_cm_and_m",
    text: "A shelf is 120 cm long. How many whole metres is that?",
    options: [
      { text: "12 m", type: "concept_error" },
      { text: "1 m", type: "correct" },
      { text: "2 m", type: "calculation_error" },
      { text: "1200 m", type: "concept_error" },
    ],
    explanation: "120 cm = 1 m 20 cm. There is 1 whole metre in 120 cm.",
    solutionSteps: ["100 cm = 1 m.", "120 cm = 1 m remainder 20 cm.", "1 whole metre."],
    shortcut: "Divide cm by 100 to get whole metres.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_cm_and_m_q8",
    topicId: "math2_ch13_cm_and_m",
    text: "Sam's height is 1 m 25 cm. In centimetres only, his height is ____.",
    options: [
      { text: "125 m", type: "concept_error" },
      { text: "25 cm", type: "partial_logic" },
      { text: "125 cm", type: "correct" },
      { text: "225 cm", type: "calculation_error" },
    ],
    explanation: "1 m = 100 cm. 1 m 25 cm = 100 + 25 = 125 cm.",
    solutionSteps: ["1 m = 100 cm.", "100 + 25 = 125 cm."],
    shortcut: "m × 100 + leftover cm = total cm.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },

  // ── math2_ch13_ruler_use (8 Qs)
  {
    questionId: "math2_ch13_ruler_use_q1",
    topicId: "math2_ch13_ruler_use",
    text: "Where should you place the start of the object when using a ruler?",
    options: [
      { text: "At the 5 cm mark", type: "concept_error" },
      { text: "At the 0 cm mark (the beginning)", type: "correct" },
      { text: "At any mark", type: "concept_error" },
      { text: "At the 10 cm mark", type: "concept_error" },
    ],
    explanation: "Always align the start of the object with the 0 mark on the ruler to get an accurate measurement.",
    solutionSteps: ["Place object's left end at 0.", "Read where the object's right end reaches.", "That number = length."],
    shortcut: "Start at 0, read the end.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_ruler_use_q2",
    topicId: "math2_ch13_ruler_use",
    text: "A pencil starts at 0 and ends at the 7 cm mark. How long is the pencil?",
    options: [
      { text: "0 cm", type: "concept_error" },
      { text: "6 cm", type: "calculation_error" },
      { text: "7 cm", type: "correct" },
      { text: "8 cm", type: "calculation_error" },
    ],
    explanation: "If it starts at 0 and ends at 7, the pencil is 7 cm long.",
    solutionSteps: ["Start: 0 cm.", "End: 7 cm.", "Length = 7 − 0 = 7 cm."],
    shortcut: "End mark − start mark = length.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_ruler_use_q3",
    topicId: "math2_ch13_ruler_use",
    text: "A stick starts at 2 cm and ends at 9 cm on the ruler. Its length is ____.",
    options: [
      { text: "9 cm", type: "concept_error" },
      { text: "11 cm", type: "concept_error" },
      { text: "7 cm", type: "correct" },
      { text: "2 cm", type: "concept_error" },
    ],
    explanation: "Length = end − start = 9 − 2 = 7 cm.",
    solutionSteps: ["Start: 2 cm.", "End: 9 cm.", "Length = 9 − 2 = 7 cm."],
    shortcut: "Always subtract: end − start.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_ruler_use_q4",
    topicId: "math2_ch13_ruler_use",
    text: "Tina places a leaf starting at 3 cm and it ends at 11 cm. How long is the leaf?",
    options: [
      { text: "11 cm", type: "concept_error" },
      { text: "3 cm", type: "concept_error" },
      { text: "8 cm", type: "correct" },
      { text: "14 cm", type: "concept_error" },
    ],
    explanation: "11 − 3 = 8 cm. The leaf is 8 cm long.",
    solutionSteps: ["End: 11 cm, Start: 3 cm.", "Length = 11 − 3 = 8 cm."],
    shortcut: "11 − 3 = 8 cm.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_ruler_use_q5",
    topicId: "math2_ch13_ruler_use",
    text: "Why is it wrong to start measuring from the 1 cm mark instead of 0?",
    options: [
      { text: "Because rulers only go to 10", type: "concept_error" },
      { text: "Because you miss 1 cm and get a smaller measurement", type: "correct" },
      { text: "Because it is harder to see", type: "guessing" },
      { text: "It does not matter where you start", type: "concept_error" },
    ],
    explanation: "Starting at 1 instead of 0 means you are not measuring the full length — you will get a reading that is 1 cm too small.",
    solutionSteps: ["Start at 1 → skip 1 cm.", "Result is 1 cm less than real length.", "Always start at 0."],
    shortcut: "Skip 0 → get wrong (smaller) measurement.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_ruler_use_q6",
    topicId: "math2_ch13_ruler_use",
    text: "A book is measured as 15 cm on a ruler. What does this tell us?",
    options: [
      { text: "The book weighs 15 grams", type: "concept_error" },
      { text: "The book holds 15 litres", type: "concept_error" },
      { text: "The book is 15 centimetres long", type: "correct" },
      { text: "There are 15 pages in the book", type: "concept_error" },
    ],
    explanation: "Measuring with a ruler gives the length in centimetres. 15 cm is the length of the book.",
    solutionSteps: ["Ruler → measures length.", "15 cm is the length.", "Not weight or volume."],
    shortcut: "Ruler reading = length in cm.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_ruler_use_q7",
    topicId: "math2_ch13_ruler_use",
    text: "Rohan measures a ribbon. It starts at 0 and ends between 12 cm and 13 cm, closer to 13. What is the best estimate?",
    options: [
      { text: "11 cm", type: "calculation_error" },
      { text: "12 cm", type: "partial_logic" },
      { text: "13 cm", type: "correct" },
      { text: "15 cm", type: "guessing" },
    ],
    explanation: "If the end is between 12 and 13 but closer to 13, the best estimate is 13 cm.",
    solutionSteps: ["Between 12 and 13.", "Closer to 13.", "Best estimate: 13 cm."],
    shortcut: "Round to nearest whole cm.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_ruler_use_q8",
    topicId: "math2_ch13_ruler_use",
    text: "Two sticks: Stick A = 9 cm, Stick B = 14 cm. How much longer is Stick B?",
    options: [
      { text: "4 cm", type: "calculation_error" },
      { text: "5 cm", type: "correct" },
      { text: "6 cm", type: "calculation_error" },
      { text: "23 cm", type: "concept_error" },
    ],
    explanation: "14 − 9 = 5 cm. Stick B is 5 cm longer than Stick A.",
    solutionSteps: ["Stick B: 14 cm.", "Stick A: 9 cm.", "14 − 9 = 5 cm longer."],
    shortcut: "Difference = 14 − 9 = 5.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },

  // ── math2_ch13_comparing_lengths (8 Qs)
  {
    questionId: "math2_ch13_comparing_lengths_q1",
    topicId: "math2_ch13_comparing_lengths",
    text: "A pencil is 12 cm. A pen is 15 cm. Which is shorter?",
    options: [
      { text: "Pen", type: "concept_error" },
      { text: "Pencil", type: "correct" },
      { text: "Both are equal", type: "concept_error" },
      { text: "Cannot tell", type: "guessing" },
    ],
    explanation: "12 cm < 15 cm. The pencil is shorter.",
    solutionSteps: ["Pencil: 12 cm, Pen: 15 cm.", "12 < 15 → pencil is shorter."],
    shortcut: "Smaller number = shorter object.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_comparing_lengths_q2",
    topicId: "math2_ch13_comparing_lengths",
    text: "A ribbon is 30 cm. A rope is 1 m. Which is longer?",
    options: [
      { text: "Ribbon", type: "concept_error" },
      { text: "Both equal", type: "concept_error" },
      { text: "Rope", type: "correct" },
      { text: "Cannot compare", type: "guessing" },
    ],
    explanation: "1 m = 100 cm. 100 cm > 30 cm, so the rope is longer.",
    solutionSteps: ["Convert: 1 m = 100 cm.", "30 cm vs 100 cm.", "100 > 30 → rope is longer."],
    shortcut: "Convert to same unit first.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_comparing_lengths_q3",
    topicId: "math2_ch13_comparing_lengths",
    text: "Arrange from shortest to longest: 8 cm, 15 cm, 3 cm, 10 cm.",
    options: [
      { text: "15, 10, 8, 3", type: "concept_error" },
      { text: "3, 8, 10, 15", type: "correct" },
      { text: "8, 3, 15, 10", type: "concept_error" },
      { text: "10, 8, 15, 3", type: "concept_error" },
    ],
    explanation: "Shortest to longest: 3 < 8 < 10 < 15.",
    solutionSteps: ["Smallest: 3 cm.", "Then 8 cm.", "Then 10 cm.", "Largest: 15 cm."],
    shortcut: "Order numbers smallest → largest.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_comparing_lengths_q4",
    topicId: "math2_ch13_comparing_lengths",
    text: "A tree is 5 m tall. A wall is 3 m tall. How much taller is the tree?",
    options: [
      { text: "1 m", type: "calculation_error" },
      { text: "2 m", type: "correct" },
      { text: "8 m", type: "concept_error" },
      { text: "3 m", type: "concept_error" },
    ],
    explanation: "5 − 3 = 2. The tree is 2 m taller than the wall.",
    solutionSteps: ["Tree: 5 m, Wall: 3 m.", "Difference: 5 − 3 = 2 m."],
    shortcut: "Taller by = bigger − smaller = 2 m.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_comparing_lengths_q5",
    topicId: "math2_ch13_comparing_lengths",
    text: "Riya has a ribbon 45 cm long. Anu has a ribbon 1 m long. How much longer is Anu's ribbon?",
    options: [
      { text: "55 cm", type: "correct" },
      { text: "45 cm", type: "concept_error" },
      { text: "145 cm", type: "concept_error" },
      { text: "65 cm", type: "calculation_error" },
    ],
    explanation: "1 m = 100 cm. 100 − 45 = 55 cm. Anu's ribbon is 55 cm longer.",
    solutionSteps: ["Anu: 100 cm, Riya: 45 cm.", "Difference: 100 − 45 = 55 cm."],
    shortcut: "Convert m to cm, then subtract.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_comparing_lengths_q6",
    topicId: "math2_ch13_comparing_lengths",
    text: "Which is the longest: 75 cm, 1 m, or 90 cm?",
    options: [
      { text: "75 cm", type: "concept_error" },
      { text: "90 cm", type: "concept_error" },
      { text: "1 m (= 100 cm)", type: "correct" },
      { text: "All equal", type: "concept_error" },
    ],
    explanation: "1 m = 100 cm. 100 > 90 > 75. So 1 m is the longest.",
    solutionSteps: ["Convert: 1 m = 100 cm.", "Compare: 75, 90, 100.", "100 is largest → 1 m wins."],
    shortcut: "1 m = 100 cm > 90 cm > 75 cm.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_comparing_lengths_q7",
    topicId: "math2_ch13_comparing_lengths",
    text: "Two ropes: Blue = 68 cm, Red = 82 cm. Together they are ____.",
    options: [
      { text: "14 cm", type: "concept_error" },
      { text: "140 cm", type: "calculation_error" },
      { text: "150 cm", type: "correct" },
      { text: "160 cm", type: "calculation_error" },
    ],
    explanation: "68 + 82 = 150 cm total length.",
    solutionSteps: ["68 + 82.", "8 + 2 = 10 → carry 1.", "6 + 8 + 1 = 15 → 150 cm."],
    shortcut: "68 + 82 = 150 cm.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },
  {
    questionId: "math2_ch13_comparing_lengths_q8",
    topicId: "math2_ch13_comparing_lengths",
    text: "Mohan is 1 m 10 cm tall. Priya is 95 cm tall. Who is taller and by how much?",
    options: [
      { text: "Priya by 5 cm", type: "concept_error" },
      { text: "Mohan by 5 cm", type: "concept_error" },
      { text: "Mohan by 15 cm", type: "correct" },
      { text: "Both are the same height", type: "concept_error" },
    ],
    explanation: "Mohan: 1 m 10 cm = 110 cm. Priya: 95 cm. 110 − 95 = 15 cm. Mohan is 15 cm taller.",
    solutionSteps: ["Mohan: 110 cm, Priya: 95 cm.", "Difference: 110 − 95 = 15 cm.", "Mohan is taller by 15 cm."],
    shortcut: "Convert to same unit, then subtract.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "The Longest Step",
  },

  // ── Chapter 14: Birds Come, Birds Go ── math2_ch14_data_collection (8 Qs)
  {
    questionId: "math2_ch14_data_collection_q1",
    topicId: "math2_ch14_data_collection",
    text: "What is data?",
    options: [
      { text: "A type of bird", type: "concept_error" },
      { text: "Information we collect to answer questions", type: "correct" },
      { text: "A drawing tool", type: "concept_error" },
      { text: "A kind of graph", type: "concept_error" },
    ],
    explanation: "Data is information collected about things or events. We collect data to find answers to questions.",
    solutionSteps: ["Data = collected information.", "Used to answer questions.", "Example: counting birds seen each day."],
    shortcut: "Data = information collected.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_data_collection_q2",
    topicId: "math2_ch14_data_collection",
    text: "Riya counts birds she sees each morning for 5 days. She is ____.",
    options: [
      { text: "Drawing pictures", type: "concept_error" },
      { text: "Collecting data", type: "correct" },
      { text: "Making a graph only", type: "concept_error" },
      { text: "Solving sums", type: "concept_error" },
    ],
    explanation: "Recording observations (bird counts) over time is collecting data.",
    solutionSteps: ["Riya is recording information (bird counts).", "Recording information = collecting data."],
    shortcut: "Recording observations = collecting data.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_data_collection_q3",
    topicId: "math2_ch14_data_collection",
    text: "A teacher records how many students are absent each day. After one week she has 5 numbers. These 5 numbers are ____.",
    options: [
      { text: "A story", type: "concept_error" },
      { text: "Data", type: "correct" },
      { text: "A picture", type: "concept_error" },
      { text: "A subtraction", type: "concept_error" },
    ],
    explanation: "The 5 recorded numbers (absences per day) form data — collected information about absences.",
    solutionSteps: ["Teacher recorded numbers daily.", "Recorded numbers = data."],
    shortcut: "Numbers recorded for a purpose = data.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_data_collection_q4",
    topicId: "math2_ch14_data_collection",
    text: "Monday: 3 birds, Tuesday: 5 birds, Wednesday: 2 birds. How many birds in total for these 3 days?",
    options: [
      { text: "8", type: "calculation_error" },
      { text: "9", type: "calculation_error" },
      { text: "10", type: "correct" },
      { text: "11", type: "calculation_error" },
    ],
    explanation: "3 + 5 + 2 = 10 birds in total.",
    solutionSteps: ["Mon: 3, Tue: 5, Wed: 2.", "3 + 5 = 8.", "8 + 2 = 10."],
    shortcut: "Add all observations: 3 + 5 + 2 = 10.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_data_collection_q5",
    topicId: "math2_ch14_data_collection",
    text: "Which day had the most birds? Mon: 3, Tue: 7, Wed: 5, Thu: 2.",
    options: [
      { text: "Monday", type: "concept_error" },
      { text: "Tuesday", type: "correct" },
      { text: "Wednesday", type: "concept_error" },
      { text: "Thursday", type: "concept_error" },
    ],
    explanation: "Tuesday had 7 birds, which is the highest count.",
    solutionSteps: ["Mon: 3, Tue: 7, Wed: 5, Thu: 2.", "Largest: 7 → Tuesday."],
    shortcut: "Find the biggest number in the data.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_data_collection_q6",
    topicId: "math2_ch14_data_collection",
    text: "In the data Mon: 3, Tue: 7, Wed: 5, Thu: 2 — which day had the fewest birds?",
    options: [
      { text: "Monday", type: "concept_error" },
      { text: "Tuesday", type: "concept_error" },
      { text: "Wednesday", type: "concept_error" },
      { text: "Thursday", type: "correct" },
    ],
    explanation: "Thursday had only 2 birds, the fewest in the data.",
    solutionSteps: ["Mon: 3, Tue: 7, Wed: 5, Thu: 2.", "Smallest: 2 → Thursday."],
    shortcut: "Fewest = smallest number.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_data_collection_q7",
    topicId: "math2_ch14_data_collection",
    text: "Why do we organise data after collecting it?",
    options: [
      { text: "To make it harder to read", type: "concept_error" },
      { text: "To make it easier to understand and compare", type: "correct" },
      { text: "To change the data", type: "concept_error" },
      { text: "Because it is fun", type: "guessing" },
    ],
    explanation: "Organising data (in tables, tally marks, graphs) makes it easier to read, compare, and draw conclusions from it.",
    solutionSteps: ["Raw data is hard to read.", "Organised data → easy to compare.", "We use tables, tallies, graphs."],
    shortcut: "Organised data → easier to understand.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_data_collection_q8",
    topicId: "math2_ch14_data_collection",
    text: "Riya's bird count for 5 days: 4, 2, 6, 3, 5. What is the total?",
    options: [
      { text: "18", type: "calculation_error" },
      { text: "19", type: "calculation_error" },
      { text: "20", type: "correct" },
      { text: "21", type: "calculation_error" },
    ],
    explanation: "4 + 2 + 6 + 3 + 5 = 20 birds in total.",
    solutionSteps: ["4 + 2 = 6.", "6 + 6 = 12.", "12 + 3 = 15.", "15 + 5 = 20."],
    shortcut: "Add all five: 4 + 2 + 6 + 3 + 5 = 20.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },

  // ── math2_ch14_tally_marks (8 Qs)
  {
    questionId: "math2_ch14_tally_marks_q1",
    topicId: "math2_ch14_tally_marks",
    text: "How many does this tally represent: ||||?",
    options: [
      { text: "3", type: "calculation_error" },
      { text: "4", type: "correct" },
      { text: "5", type: "calculation_error" },
      { text: "6", type: "calculation_error" },
    ],
    explanation: "Four vertical lines (||||) represent 4 in tally marks.",
    solutionSteps: ["Count each vertical line.", "| | | | = 4."],
    shortcut: "Count the sticks.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_tally_marks_q2",
    topicId: "math2_ch14_tally_marks",
    text: "A tally of 5 is written as ____.",
    options: [
      { text: "Five separate lines: |||||", type: "partial_logic" },
      { text: "Four lines with one crossing: ||||̶", type: "correct" },
      { text: "A circle", type: "concept_error" },
      { text: "The number 5", type: "concept_error" },
    ],
    explanation: "In tally marks, 5 is written as four vertical lines crossed by a diagonal line (||||̶). This groups counts in fives for easy reading.",
    solutionSteps: ["1–4 = single vertical lines.", "5 = four lines with a crossing diagonal.", "Groups of 5 are easier to count."],
    shortcut: "Tally 5 = four lines + one cross = ||||̶.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_tally_marks_q3",
    topicId: "math2_ch14_tally_marks",
    text: "A group of 5-tally (||||̶) plus 3 extra lines (|||) = how many in total?",
    options: [
      { text: "3", type: "concept_error" },
      { text: "5", type: "concept_error" },
      { text: "8", type: "correct" },
      { text: "53", type: "concept_error" },
    ],
    explanation: "||||̶ = 5, ||| = 3. Total = 5 + 3 = 8.",
    solutionSteps: ["First group: 5.", "Extra marks: 3.", "5 + 3 = 8."],
    shortcut: "Count each group of 5, then add extras.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_tally_marks_q4",
    topicId: "math2_ch14_tally_marks",
    text: "Anu sees 12 birds. How many tally groups of 5 will she have, with how many left over?",
    options: [
      { text: "1 group, 7 left over", type: "concept_error" },
      { text: "2 groups, 2 left over", type: "correct" },
      { text: "2 groups, 3 left over", type: "calculation_error" },
      { text: "3 groups, 0 left over", type: "calculation_error" },
    ],
    explanation: "12 ÷ 5 = 2 groups (10) with 2 left over. So ||||̶ ||||̶ || represents 12.",
    solutionSteps: ["12 = 5 + 5 + 2.", "Two complete groups of 5.", "Remainder: 2.", "Two groups, 2 left over."],
    shortcut: "Divide by 5 → groups and remainder.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_tally_marks_q5",
    topicId: "math2_ch14_tally_marks",
    text: "Why do we use tally marks instead of just writing numbers?",
    options: [
      { text: "Because numbers are wrong", type: "concept_error" },
      { text: "Because tally marks are easier to make one-by-one while counting", type: "correct" },
      { text: "Because tally marks take less space", type: "partial_logic" },
      { text: "Because tally marks are prettier", type: "guessing" },
    ],
    explanation: "Tally marks are ideal for counting in real time — you add one mark per event as it happens. Grouping in 5s makes them easy to count later.",
    solutionSteps: ["Count as you go → add one mark at a time.", "Groups of 5 easy to count.", "Faster than writing numbers during counting."],
    shortcut: "Tally = live counting tool.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_tally_marks_q6",
    topicId: "math2_ch14_tally_marks",
    text: "Three tally groups of 5 (||||̶ ||||̶ ||||̶) = ____.",
    options: [
      { text: "12", type: "calculation_error" },
      { text: "14", type: "calculation_error" },
      { text: "15", type: "correct" },
      { text: "53", type: "concept_error" },
    ],
    explanation: "Each group of 5. Three groups = 3 × 5 = 15.",
    solutionSteps: ["1 group = 5.", "3 groups = 3 × 5 = 15."],
    shortcut: "Groups × 5 = total.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_tally_marks_q7",
    topicId: "math2_ch14_tally_marks",
    text: "Raj records sparrows seen: Mon-4, Tue-5, Wed-3. Which day's tally has a crossed group?",
    options: [
      { text: "Monday (4 marks)", type: "concept_error" },
      { text: "Tuesday (5 marks)", type: "correct" },
      { text: "Wednesday (3 marks)", type: "concept_error" },
      { text: "None of them", type: "concept_error" },
    ],
    explanation: "The cross (diagonal) appears only when you reach 5. Tuesday (5 sparrows) uses the crossed tally group ||||̶.",
    solutionSteps: ["Mon: 4 → ||||", "Tue: 5 → ||||̶ (crossed)", "Wed: 3 → |||", "Tuesday has the cross."],
    shortcut: "5 = crossed group; less than 5 = no cross.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_tally_marks_q8",
    topicId: "math2_ch14_tally_marks",
    text: "A class voted for their favourite colour. Blue: ||||̶ |||, Red: ||||̶ |, Green: |||. How many voted for Blue?",
    options: [
      { text: "5", type: "concept_error" },
      { text: "7", type: "calculation_error" },
      { text: "8", type: "correct" },
      { text: "9", type: "calculation_error" },
    ],
    explanation: "Blue: ||||̶ ||| = 5 + 3 = 8.",
    solutionSteps: ["Blue: one crossed group = 5.", "Plus 3 extra marks.", "5 + 3 = 8."],
    shortcut: "||||̶ ||| = 5 + 3 = 8.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },

  // ── math2_ch14_bar_graphs (8 Qs)
  {
    questionId: "math2_ch14_bar_graphs_q1",
    topicId: "math2_ch14_bar_graphs",
    text: "A bar graph uses ____ to show data.",
    options: [
      { text: "Lines only", type: "concept_error" },
      { text: "Rectangular bars of different lengths", type: "correct" },
      { text: "Only numbers", type: "concept_error" },
      { text: "Circles", type: "concept_error" },
    ],
    explanation: "A bar graph uses rectangular bars. The length of each bar shows the value for that category.",
    solutionSteps: ["Bar graph → rectangular bars.", "Longer bar = larger value.", "Shorter bar = smaller value."],
    shortcut: "Bar = rectangle; length = value.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_bar_graphs_q2",
    topicId: "math2_ch14_bar_graphs",
    text: "In a bar graph about favourite fruits, the bar for Mango is the tallest. This means ____.",
    options: [
      { text: "Mango is the least favourite", type: "concept_error" },
      { text: "Mango is the most favourite", type: "correct" },
      { text: "Mango is the heaviest", type: "concept_error" },
      { text: "Mango costs the most", type: "concept_error" },
    ],
    explanation: "In a bar graph, the tallest (longest) bar represents the highest value — the most popular choice.",
    solutionSteps: ["Taller bar = higher count.", "Mango bar is tallest → most favourite."],
    shortcut: "Tallest bar = most popular.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_bar_graphs_q3",
    topicId: "math2_ch14_bar_graphs",
    text: "A bar graph shows: Sparrow=6, Parrot=4, Crow=8. Which bird was seen the fewest times?",
    options: [
      { text: "Sparrow", type: "concept_error" },
      { text: "Parrot", type: "correct" },
      { text: "Crow", type: "concept_error" },
      { text: "All equal", type: "concept_error" },
    ],
    explanation: "Parrot = 4 is the smallest value, meaning it was seen the fewest times.",
    solutionSteps: ["Sparrow: 6, Parrot: 4, Crow: 8.", "Smallest: 4 → Parrot."],
    shortcut: "Shortest bar = least count.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_bar_graphs_q4",
    topicId: "math2_ch14_bar_graphs",
    text: "Bar graph: Sparrow=6, Parrot=4, Crow=8. How many more crows than sparrows were seen?",
    options: [
      { text: "1", type: "calculation_error" },
      { text: "2", type: "correct" },
      { text: "4", type: "calculation_error" },
      { text: "14", type: "concept_error" },
    ],
    explanation: "8 − 6 = 2. Two more crows were seen than sparrows.",
    solutionSteps: ["Crow: 8, Sparrow: 6.", "8 − 6 = 2."],
    shortcut: "More = bigger − smaller = 2.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_bar_graphs_q5",
    topicId: "math2_ch14_bar_graphs",
    text: "Bar graph: Sparrow=6, Parrot=4, Crow=8. What is the total number of birds seen?",
    options: [
      { text: "14", type: "calculation_error" },
      { text: "16", type: "calculation_error" },
      { text: "18", type: "correct" },
      { text: "20", type: "calculation_error" },
    ],
    explanation: "6 + 4 + 8 = 18 birds in total.",
    solutionSteps: ["6 + 4 = 10.", "10 + 8 = 18."],
    shortcut: "Add all bar values: 6 + 4 + 8 = 18.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_bar_graphs_q6",
    topicId: "math2_ch14_bar_graphs",
    text: "Which axis in a bar graph usually shows the categories (names)?",
    options: [
      { text: "The top of the graph", type: "concept_error" },
      { text: "The horizontal axis (bottom)", type: "correct" },
      { text: "The vertical axis (side)", type: "concept_error" },
      { text: "The right side", type: "concept_error" },
    ],
    explanation: "In a vertical bar graph, the categories (names like Sparrow, Parrot, Crow) are shown along the horizontal axis at the bottom.",
    solutionSteps: ["Horizontal axis = bottom.", "Categories (names) go on the horizontal axis.", "Numbers (counts) go on the vertical axis."],
    shortcut: "Bottom = category names; side = numbers.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_bar_graphs_q7",
    topicId: "math2_ch14_bar_graphs",
    text: "A bar graph shows how many students like each subject. Maths bar reaches 10, Science 7, English 5. How many more students like Maths than English?",
    options: [
      { text: "3", type: "calculation_error" },
      { text: "5", type: "correct" },
      { text: "7", type: "calculation_error" },
      { text: "15", type: "concept_error" },
    ],
    explanation: "10 − 5 = 5. Five more students like Maths than English.",
    solutionSteps: ["Maths: 10, English: 5.", "10 − 5 = 5."],
    shortcut: "10 − 5 = 5 more.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_bar_graphs_q8",
    topicId: "math2_ch14_bar_graphs",
    text: "Which is the main advantage of a bar graph over a table of numbers?",
    options: [
      { text: "Bar graphs show more exact numbers", type: "concept_error" },
      { text: "Bar graphs are easier to compare values at a glance", type: "correct" },
      { text: "Bar graphs take less time to make", type: "concept_error" },
      { text: "Bar graphs are always more accurate", type: "concept_error" },
    ],
    explanation: "Bar graphs make comparison easy visually — you can see at a glance which bar is taller without calculating.",
    solutionSteps: ["Tables need careful reading.", "Bar graphs → visual comparison.", "Taller = more, shorter = less, instantly."],
    shortcut: "Graphs → easy visual comparison.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },

  // ── math2_ch14_pictographs (8 Qs)
  {
    questionId: "math2_ch14_pictographs_q1",
    topicId: "math2_ch14_pictographs",
    text: "A pictograph uses ____ to show data.",
    options: [
      { text: "Only numbers", type: "concept_error" },
      { text: "Small pictures or symbols to represent quantities", type: "correct" },
      { text: "Rectangular bars", type: "concept_error" },
      { text: "Lines connecting dots", type: "concept_error" },
    ],
    explanation: "A pictograph uses small pictures or symbols. Each picture represents a fixed number of items.",
    solutionSteps: ["Pictograph = pictures/symbols.", "Each symbol = fixed amount.", "Count symbols to find total."],
    shortcut: "Pictograph = pictures to show data.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_pictographs_q2",
    topicId: "math2_ch14_pictographs",
    text: "In a pictograph, each bird symbol = 2 birds. Riya has 3 symbols. How many birds did she see?",
    options: [
      { text: "3", type: "concept_error" },
      { text: "5", type: "calculation_error" },
      { text: "6", type: "correct" },
      { text: "8", type: "calculation_error" },
    ],
    explanation: "3 symbols × 2 birds each = 6 birds.",
    solutionSteps: ["Each symbol = 2 birds.", "3 symbols × 2 = 6."],
    shortcut: "Symbols × key value = total.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_pictographs_q3",
    topicId: "math2_ch14_pictographs",
    text: "In a pictograph, each apple symbol = 5 apples. A row has 4 symbols. How many apples does that row represent?",
    options: [
      { text: "4", type: "concept_error" },
      { text: "9", type: "calculation_error" },
      { text: "20", type: "correct" },
      { text: "45", type: "calculation_error" },
    ],
    explanation: "4 symbols × 5 apples each = 20 apples.",
    solutionSteps: ["Each symbol = 5 apples.", "4 × 5 = 20."],
    shortcut: "4 × 5 = 20.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_pictographs_q4",
    topicId: "math2_ch14_pictographs",
    text: "What does the 'key' in a pictograph tell you?",
    options: [
      { text: "The title of the graph", type: "partial_logic" },
      { text: "What each symbol stands for (how many each picture = )", type: "correct" },
      { text: "The date the data was collected", type: "concept_error" },
      { text: "The colours used", type: "concept_error" },
    ],
    explanation: "The key (or legend) tells you the value of each symbol in the pictograph — e.g., each bird = 2 birds.",
    solutionSteps: ["Key = symbol value.", "Example: 🐦 = 2 birds.", "Without key, cannot read pictograph."],
    shortcut: "Key = value of each symbol.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_pictographs_q5",
    topicId: "math2_ch14_pictographs",
    text: "Pictograph (each symbol = 3): Mon=2 symbols, Tue=4 symbols, Wed=1 symbol. Which day had the most?",
    options: [
      { text: "Monday", type: "concept_error" },
      { text: "Tuesday", type: "correct" },
      { text: "Wednesday", type: "concept_error" },
      { text: "All equal", type: "concept_error" },
    ],
    explanation: "More symbols = more items. Tue has 4 symbols (most), so Tuesday had the most.",
    solutionSteps: ["Mon: 2 sym = 6.", "Tue: 4 sym = 12.", "Wed: 1 sym = 3.", "Most: Tuesday (12)."],
    shortcut: "Most symbols = most items.",
    difficulty: "easy",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_pictographs_q6",
    topicId: "math2_ch14_pictographs",
    text: "Pictograph (each symbol = 3): Mon=2, Tue=4, Wed=1. Total for all 3 days = ____.",
    options: [
      { text: "7", type: "concept_error" },
      { text: "18", type: "calculation_error" },
      { text: "21", type: "correct" },
      { text: "24", type: "calculation_error" },
    ],
    explanation: "Total symbols: 2 + 4 + 1 = 7. Total items: 7 × 3 = 21.",
    solutionSteps: ["Total symbols: 2 + 4 + 1 = 7.", "7 × 3 = 21."],
    shortcut: "Total symbols × key = total.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_pictographs_q7",
    topicId: "math2_ch14_pictographs",
    text: "In a pictograph with key = 5, a row has 2 full symbols and half a symbol. How many does this row represent?",
    options: [
      { text: "10", type: "partial_logic" },
      { text: "12", type: "calculation_error" },
      { text: "12.5", type: "correct" },
      { text: "15", type: "calculation_error" },
    ],
    explanation: "2 full symbols = 10. Half symbol = 2.5. Total = 12.5. (In class 2 context, often written as 'between 10 and 15'.)",
    solutionSteps: ["2 symbols × 5 = 10.", "½ symbol × 5 = 2.5.", "Total = 12.5."],
    shortcut: "Half symbol = half the key value.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
  {
    questionId: "math2_ch14_pictographs_q8",
    topicId: "math2_ch14_pictographs",
    text: "A pictograph shows birds seen: Sparrow=3 symbols, Crow=5 symbols (key: each = 4). How many more crows than sparrows?",
    options: [
      { text: "2 birds", type: "concept_error" },
      { text: "4 birds", type: "calculation_error" },
      { text: "8 birds", type: "correct" },
      { text: "12 birds", type: "calculation_error" },
    ],
    explanation: "Sparrow: 3 × 4 = 12. Crow: 5 × 4 = 20. Difference: 20 − 12 = 8.",
    solutionSteps: ["Sparrow: 3 × 4 = 12.", "Crow: 5 × 4 = 20.", "20 − 12 = 8 more crows."],
    shortcut: "Difference in symbols × key = difference in count.",
    difficulty: "medium",
    subject: "Mathematics",
    grade: "2",
    chapter: "Birds Come, Birds Go",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded 64 Class 2 Math v2 questions (Chapters 13-14).`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
