/**
 * CBSE Class 9 Mathematics — Questions v2C (Ch5–Ch6, 64 questions)
 * Usage: node config/seedMath9QuestionsV2C.js
 */
import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const questions = [

  // ── Ch5 · Sub-topic 1: Basic Circle Properties ─────────────────────────────
  {
    questionId: "math9_ch5_basic_properties_q1", topicId: "math9_ch5_basic_properties",
    text: "In a circle with centre O, chord AB = 24 cm and OA = 13 cm. Find the distance of the chord from the centre.",
    options: [
      { text: "5 cm", type: "correct", logicTag: "OM=√(169−144)=√25=5" },
      { text: "7 cm", type: "concept_error", logicTag: "arithmetic error" },
      { text: "12 cm", type: "concept_error", logicTag: "half the chord" },
      { text: "√(169+144)", type: "concept_error", logicTag: "added instead of subtracted" },
    ],
    explanation: "OM⊥AB, so AM=12. OM=√(OA²−AM²)=√(169−144)=√25=5 cm.",
    solutionSteps: ["OM⊥AB → M is midpoint of AB → AM=12", "Pythagoras: OM²+12²=13²", "OM²=169−144=25 → OM=5"],
    shortcut: "Distance from centre = √(r²−(l/2)²) where l=chord length.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_basic_properties_q2", topicId: "math9_ch5_basic_properties",
    text: "Two chords PQ and RS of a circle are equidistant from the centre. Which statement is true?",
    options: [
      { text: "PQ > RS", type: "concept_error", logicTag: "equal distance → equal length" },
      { text: "PQ = RS", type: "correct", logicTag: "equal chords equidistant from centre" },
      { text: "PQ < RS", type: "concept_error", logicTag: "same as above" },
      { text: "Cannot determine without more info", type: "concept_error", logicTag: "theorem is definitive" },
    ],
    explanation: "Equal chords are equidistant from the centre, and conversely, chords equidistant from the centre are equal. So PQ = RS.",
    solutionSteps: ["Theorem (converse): chords equidistant from centre are equal", "PQ = RS"],
    shortcut: "Equidistant from centre ↔ equal chord lengths. The relationship is two-way.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_basic_properties_q3", topicId: "math9_ch5_basic_properties",
    text: "What is the longest chord of a circle?",
    options: [
      { text: "Any chord that passes near the centre", type: "concept_error", logicTag: "must pass through" },
      { text: "The diameter", type: "correct", logicTag: "passes through centre, maximum length" },
      { text: "A chord equal to the radius", type: "concept_error", logicTag: "shorter than diameter" },
      { text: "A chord at distance r/2 from centre", type: "concept_error", logicTag: "not the longest" },
    ],
    explanation: "The diameter passes through the centre and has length 2r. Any other chord is shorter (its distance from centre > 0).",
    solutionSteps: ["Chord length increases as distance from centre decreases", "Distance = 0 when chord passes through centre", "That chord is the diameter (length = 2r)"],
    shortcut: "Closer to centre → longer chord. Diameter is at distance 0 → longest.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_basic_properties_q4", topicId: "math9_ch5_basic_properties",
    text: "A perpendicular drawn from the centre of a circle to a chord:",
    options: [
      { text: "Bisects the chord", type: "correct", logicTag: "perpendicular from centre bisects chord" },
      { text: "Is equal to the radius", type: "concept_error", logicTag: "only if chord is at origin" },
      { text: "Touches the chord at one end", type: "concept_error", logicTag: "it meets at midpoint" },
      { text: "Is parallel to the chord", type: "concept_error", logicTag: "it's perpendicular" },
    ],
    explanation: "Theorem: The perpendicular from the centre of a circle to a chord bisects the chord.",
    solutionSteps: ["Perpendicular from O to chord AB meets at M", "Theorem: AM = BM", "M is the midpoint of AB"],
    shortcut: "Centre perp → bisects chord. This is one of the most fundamental circle theorems.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_basic_properties_q5", topicId: "math9_ch5_basic_properties",
    text: "Two equal chords of a circle subtend angles at the centre. These angles are:",
    options: [
      { text: "Supplementary (sum to 180°)", type: "concept_error", logicTag: "no, they're equal" },
      { text: "Equal", type: "correct", logicTag: "equal chords → equal central angles" },
      { text: "Complementary (sum to 90°)", type: "concept_error", logicTag: "unrelated" },
      { text: "Different in general", type: "concept_error", logicTag: "theorem says equal" },
    ],
    explanation: "Equal chords subtend equal angles at the centre (and converse: equal angles → equal chords).",
    solutionSteps: ["AB = CD (equal chords)", "∠AOB = ∠COD (equal central angles)"],
    shortcut: "Equal chords ↔ equal central angles. Same two-way relationship as with distances.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_basic_properties_q6", topicId: "math9_ch5_basic_properties",
    text: "In a circle of radius 10 cm, a chord is at a distance of 6 cm from the centre. Find the length of the chord.",
    options: [
      { text: "8 cm", type: "concept_error", logicTag: "only half the chord" },
      { text: "16 cm", type: "correct", logicTag: "half=√(100−36)=8, full=16" },
      { text: "12 cm", type: "concept_error", logicTag: "arithmetic error" },
      { text: "14 cm", type: "concept_error", logicTag: "10+6−2?" },
    ],
    explanation: "Half chord = √(r²−d²) = √(100−36) = √64 = 8. Full chord = 16 cm.",
    solutionSteps: ["Half chord = √(r²−d²) = √(100−36) = 8", "Full chord = 2×8 = 16 cm"],
    shortcut: "Half chord = √(r²−d²). Full chord = 2√(r²−d²).",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_basic_properties_q7", topicId: "math9_ch5_basic_properties",
    text: "If the perpendicular bisector of a chord passes through the centre, what does that tell you about the chord?",
    options: [
      { text: "The chord is a tangent", type: "concept_error", logicTag: "tangent touches at one point" },
      { text: "The chord is a diameter", type: "correct", logicTag: "perp bisector of diameter = the other diameter" },
      { text: "The chord is the shortest in the circle", type: "concept_error", logicTag: "opposite" },
      { text: "The chord is parallel to the diameter", type: "concept_error", logicTag: "not necessarily" },
    ],
    explanation: "The perpendicular bisector of every chord passes through the centre. If the perpendicular bisector of a chord is another chord, both chords are diameters.",
    solutionSteps: ["Perp bisector of any chord passes through O", "If perp bisector is itself a chord, it also passes through O", "A chord through O is a diameter → original chord is also a diameter"],
    shortcut: "Perpendicular bisector of a chord always passes through the centre. Two diameters are perpendicular bisectors of each other.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_basic_properties_q8", topicId: "math9_ch5_basic_properties",
    text: "In a circle, if two chords AB and CD are at distances 3 cm and 5 cm from the centre respectively, which is longer?",
    options: [
      { text: "CD is longer", type: "concept_error", logicTag: "farther from centre → shorter" },
      { text: "AB is longer", type: "correct", logicTag: "closer to centre → longer" },
      { text: "They are equal", type: "concept_error", logicTag: "different distances" },
      { text: "Cannot determine", type: "concept_error", logicTag: "the rule is definitive" },
    ],
    explanation: "Chord closer to the centre is longer. AB (distance 3) < CD (distance 5) from centre → AB is longer.",
    solutionSteps: ["Closer to centre → longer chord", "AB at 3 cm, CD at 5 cm", "3 < 5 → AB is closer → AB is longer"],
    shortcut: "Distance from centre and chord length have an inverse relationship.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },

  // ── Ch5 · Sub-topic 2: Angles in Circle ────────────────────────────────────
  {
    questionId: "math9_ch5_angles_in_circle_q1", topicId: "math9_ch5_angles_in_circle",
    text: "Arc PQ subtends ∠POQ = 100° at centre O. What angle does it subtend at any point R on the major arc?",
    options: [
      { text: "100°", type: "concept_error", logicTag: "that is the central angle" },
      { text: "50°", type: "correct", logicTag: "inscribed = half central for same arc" },
      { text: "200°", type: "concept_error", logicTag: "double" },
      { text: "80°", type: "concept_error", logicTag: "180−100" },
    ],
    explanation: "Inscribed angle = half the central angle subtending the same arc. ∠PRQ = 100°/2 = 50°.",
    solutionSteps: ["∠POQ = 100° (central angle)", "∠PRQ = 100°/2 = 50° (inscribed on major arc)"],
    shortcut: "Central angle = 2 × inscribed angle (same arc).",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_angles_in_circle_q2", topicId: "math9_ch5_angles_in_circle",
    text: "AB is a diameter. Point C is on the circle. What is ∠ACB?",
    options: [
      { text: "45°", type: "concept_error", logicTag: "angle in semicircle confusion" },
      { text: "90°", type: "correct", logicTag: "angle in semicircle = 90°" },
      { text: "60°", type: "concept_error", logicTag: "equilateral triangle assumption" },
      { text: "180°", type: "concept_error", logicTag: "that is the central angle for semicircle" },
    ],
    explanation: "AB is a diameter → arc AB is a semicircle → central angle = 180°. Inscribed angle ∠ACB = 180°/2 = 90°.",
    solutionSteps: ["AB is diameter → central angle = 180°", "Inscribed angle in semicircle = 180°/2 = 90°"],
    shortcut: "Angle in a semicircle is always 90°. Classic theorem.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_angles_in_circle_q3", topicId: "math9_ch5_angles_in_circle",
    text: "Points P, Q, R, S lie on a circle. ∠PRQ = 35°. What is ∠PSQ?",
    options: [
      { text: "70°", type: "concept_error", logicTag: "that is the central angle" },
      { text: "35°", type: "correct", logicTag: "same segment → equal inscribed angles" },
      { text: "145°", type: "concept_error", logicTag: "supplementary" },
      { text: "17.5°", type: "concept_error", logicTag: "half of 35" },
    ],
    explanation: "∠PRQ and ∠PSQ subtend the same chord PQ from the same side. Angles in the same segment are equal. ∠PSQ = 35°.",
    solutionSteps: ["∠PRQ and ∠PSQ are inscribed in the same segment", "Same segment → equal angles", "∠PSQ = 35°"],
    shortcut: "Angles in the same segment are always equal — regardless of where on the arc the vertex is.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_angles_in_circle_q4", topicId: "math9_ch5_angles_in_circle",
    text: "In a circle, ∠AOB = 130° (central angle). Find the inscribed angle ∠ACB where C is on the minor arc.",
    options: [
      { text: "65°", type: "concept_error", logicTag: "C on major arc would give 65°" },
      { text: "115°", type: "correct", logicTag: "(360−130)/2=230/2=115°" },
      { text: "130°", type: "concept_error", logicTag: "that is central angle" },
      { text: "50°", type: "concept_error", logicTag: "arithmetic error" },
    ],
    explanation: "C is on the minor arc, so it subtends the major arc (360°−130°=230°). Inscribed angle = 230°/2 = 115°.",
    solutionSteps: ["Major arc = 360°−130°=230°", "C on minor arc sees major arc", "∠ACB = 230°/2 = 115°"],
    shortcut: "If C is on the minor arc: inscribed angle = (360°−central angle)/2.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_angles_in_circle_q5", topicId: "math9_ch5_angles_in_circle",
    text: "In a circle with centre O, ∠OAB = 30° where A and B are on the circle. Find ∠ACB where C is on the major arc.",
    options: [
      { text: "60°", type: "correct", logicTag: "OA=OB=radius → ∠OAB=∠OBA=30° → ∠AOB=120° → inscribed=60°" },
      { text: "30°", type: "concept_error", logicTag: "equal to given angle" },
      { text: "120°", type: "concept_error", logicTag: "that is ∠AOB" },
      { text: "90°", type: "concept_error", logicTag: "angle in semicircle, not this case" },
    ],
    explanation: "OA=OB (radii) → triangle OAB is isosceles → ∠OAB=∠OBA=30°. ∠AOB=180°−60°=120°. Inscribed ∠ACB=120°/2=60°.",
    solutionSteps: ["OA=OB → ∠OBA=30°", "∠AOB=180−30−30=120°", "∠ACB=120/2=60°"],
    shortcut: "In isosceles triangle OAB: ∠AOB = 180°−2∠OAB.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_angles_in_circle_q6", topicId: "math9_ch5_angles_in_circle",
    text: "If ∠BAC = 40° and BC is a chord, what is ∠BOC?",
    options: [
      { text: "20°", type: "concept_error", logicTag: "half of inscribed" },
      { text: "80°", type: "correct", logicTag: "central = 2 × inscribed" },
      { text: "40°", type: "concept_error", logicTag: "equal to inscribed" },
      { text: "140°", type: "concept_error", logicTag: "reflex or supplement" },
    ],
    explanation: "∠BAC is the inscribed angle on BC. Central angle ∠BOC = 2×∠BAC = 2×40° = 80°.",
    solutionSteps: ["∠BAC = 40° (inscribed, subtending BC)", "∠BOC = 2×40° = 80° (central)"],
    shortcut: "Central = 2 × Inscribed. Always.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_angles_in_circle_q7", topicId: "math9_ch5_angles_in_circle",
    text: "Two chords AB and CD intersect at point P inside the circle. If ∠APC = 70°, find ∠BPD.",
    options: [
      { text: "110°", type: "concept_error", logicTag: "supplementary to ∠APC" },
      { text: "70°", type: "correct", logicTag: "vertically opposite angles" },
      { text: "35°", type: "concept_error", logicTag: "half" },
      { text: "140°", type: "concept_error", logicTag: "double" },
    ],
    explanation: "∠APC and ∠BPD are vertically opposite angles. Vertically opposite angles are equal. ∠BPD = 70°.",
    solutionSteps: ["∠APC and ∠BPD are vertically opposite", "Vertically opposite angles are equal", "∠BPD = 70°"],
    shortcut: "Vertically opposite angles are always equal — basic geometry, applies inside circles too.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_angles_in_circle_q8", topicId: "math9_ch5_angles_in_circle",
    text: "In a circle, ∠PQR = 55° where P, Q, R are on the circle. What is the arc PR that doesn't contain Q?",
    options: [
      { text: "55°", type: "concept_error", logicTag: "that is the inscribed angle" },
      { text: "110°", type: "correct", logicTag: "arc = 2 × inscribed angle" },
      { text: "250°", type: "concept_error", logicTag: "major arc" },
      { text: "125°", type: "concept_error", logicTag: "arithmetic error" },
    ],
    explanation: "The inscribed angle ∠PQR = 55° subtends arc PR (not containing Q). Arc PR = 2×55° = 110°.",
    solutionSteps: ["Inscribed angle = (1/2) × subtended arc", "Arc PR = 2 × ∠PQR = 110°"],
    shortcut: "Arc = 2 × inscribed angle. The arc subtended is opposite to the inscribed angle vertex.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },

  // ── Ch5 · Sub-topic 3: Cyclic Quadrilaterals ───────────────────────────────
  {
    questionId: "math9_ch5_cyclic_quadrilateral_q1", topicId: "math9_ch5_cyclic_quadrilateral",
    text: "ABCD is a cyclic quadrilateral with ∠A = 80°. Find ∠C.",
    options: [
      { text: "80°", type: "concept_error", logicTag: "opposite angles are supplementary not equal" },
      { text: "100°", type: "correct", logicTag: "∠A+∠C=180°" },
      { text: "280°", type: "concept_error", logicTag: "reflex" },
      { text: "90°", type: "concept_error", logicTag: "not necessarily 90°" },
    ],
    explanation: "Opposite angles in a cyclic quadrilateral sum to 180°. ∠C = 180°−80° = 100°.",
    solutionSteps: ["∠A + ∠C = 180° (cyclic quad)", "∠C = 180° − 80° = 100°"],
    shortcut: "Opposite angles of cyclic quad are supplementary.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_cyclic_quadrilateral_q2", topicId: "math9_ch5_cyclic_quadrilateral",
    text: "In cyclic quadrilateral PQRS, ∠P = 3x and ∠R = x. Find x.",
    options: [
      { text: "x = 45°", type: "correct", logicTag: "3x+x=180°→4x=180→x=45" },
      { text: "x = 60°", type: "concept_error", logicTag: "arithmetic error" },
      { text: "x = 30°", type: "concept_error", logicTag: "wrong equation" },
      { text: "x = 90°", type: "concept_error", logicTag: "too large" },
    ],
    explanation: "∠P + ∠R = 180° → 3x+x = 180° → 4x = 180° → x = 45°.",
    solutionSteps: ["3x + x = 180°", "4x = 180°", "x = 45°"],
    shortcut: "Set up: opposite angles sum = 180°. Solve for variable.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_cyclic_quadrilateral_q3", topicId: "math9_ch5_cyclic_quadrilateral",
    text: "Which of the following quadrilaterals is always cyclic?",
    options: [
      { text: "Rhombus", type: "concept_error", logicTag: "rhombus angles not necessarily supplementary" },
      { text: "Rectangle", type: "correct", logicTag: "opposite angles = 90°, sum = 180°" },
      { text: "General parallelogram", type: "concept_error", logicTag: "opposite angles equal, not supplementary unless 90°" },
      { text: "Trapezium", type: "concept_error", logicTag: "not always cyclic" },
    ],
    explanation: "A rectangle has all angles = 90°. Opposite angles: 90°+90°=180° ✓. So every rectangle is cyclic.",
    solutionSteps: ["Rectangle: all angles = 90°", "Opposite angles: 90°+90°=180° → supplementary", "So every rectangle is cyclic"],
    shortcut: "Squares and rectangles are always cyclic. Rhombuses (unless square) and general parallelograms are not.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_cyclic_quadrilateral_q4", topicId: "math9_ch5_cyclic_quadrilateral",
    text: "ABCD is a cyclic quadrilateral. What is the sum of all its angles?",
    options: [
      { text: "180°", type: "concept_error", logicTag: "that is for a triangle" },
      { text: "360°", type: "correct", logicTag: "sum of angles of any quadrilateral" },
      { text: "720°", type: "concept_error", logicTag: "that is for a hexagon" },
      { text: "270°", type: "concept_error", logicTag: "not defined" },
    ],
    explanation: "Sum of interior angles of any quadrilateral = (4−2)×180° = 360°. The cyclic property gives a further constraint but doesn't change the total.",
    solutionSteps: ["Any quadrilateral: sum = 360°", "Cyclic adds constraint: ∠A+∠C=180° and ∠B+∠D=180°", "Both sum to 360° total"],
    shortcut: "Sum of angles of any n-gon = (n−2)×180°. For n=4: 360°.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_cyclic_quadrilateral_q5", topicId: "math9_ch5_cyclic_quadrilateral",
    text: "Is a quadrilateral with angles 85°, 95°, 85°, 95° a cyclic quadrilateral?",
    options: [
      { text: "Yes", type: "correct", logicTag: "85+95=180° for opposite pairs" },
      { text: "No", type: "concept_error", logicTag: "check the opposite angle condition" },
      { text: "Cannot determine", type: "concept_error", logicTag: "the condition is sufficient" },
      { text: "Only if it is a rectangle", type: "concept_error", logicTag: "it does not need to be a rectangle" },
    ],
    explanation: "Opposite angles: 85°+95°=180° ✓. By the converse theorem, this quadrilateral IS cyclic.",
    solutionSteps: ["∠A+∠C=85+85=170°? No — opposite pairs are 85&95", "85+95=180° ✓", "Converse of cyclic quad theorem → it is cyclic"],
    shortcut: "Converse: if opposite angles sum to 180°, the quadrilateral is cyclic.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_cyclic_quadrilateral_q6", topicId: "math9_ch5_cyclic_quadrilateral",
    text: "In cyclic quadrilateral ABCD, ∠ABC = 70°. The exterior angle at D (outside the quadrilateral) equals:",
    options: [
      { text: "70°", type: "correct", logicTag: "exterior angle = opposite interior angle" },
      { text: "110°", type: "concept_error", logicTag: "that is ∠ADC" },
      { text: "140°", type: "concept_error", logicTag: "double" },
      { text: "90°", type: "concept_error", logicTag: "no reason for 90°" },
    ],
    explanation: "Exterior angle of a cyclic quadrilateral = opposite interior angle. Exterior angle at D = ∠ABC = 70°.",
    solutionSteps: ["∠ADC = 180°−70°=110° (opposite angles supplementary)", "Exterior angle at D = 180°−110°=70°=∠ABC"],
    shortcut: "Exterior angle of cyclic quad = opposite interior angle.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_cyclic_quadrilateral_q7", topicId: "math9_ch5_cyclic_quadrilateral",
    text: "A parallelogram ABCD is cyclic. Which type of parallelogram must it be?",
    options: [
      { text: "Rhombus", type: "concept_error", logicTag: "rhombus angles aren't necessarily 90°" },
      { text: "Rectangle", type: "correct", logicTag: "cyclic parallelogram has 90° angles" },
      { text: "General parallelogram", type: "concept_error", logicTag: "not cyclic unless rectangle" },
      { text: "Trapezium", type: "concept_error", logicTag: "not a parallelogram" },
    ],
    explanation: "In a parallelogram, opposite angles are equal. In a cyclic quad, opposite angles are supplementary. Equal and supplementary → each = 90°. So it's a rectangle.",
    solutionSteps: ["Parallelogram: ∠A=∠C, ∠B=∠D", "Cyclic: ∠A+∠C=180°", "∠A=∠C and 2∠A=180° → ∠A=90°", "All angles 90° → rectangle"],
    shortcut: "A cyclic parallelogram must be a rectangle.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_cyclic_quadrilateral_q8", topicId: "math9_ch5_cyclic_quadrilateral",
    text: "ABCD is cyclic with ∠A = 2x+10 and ∠C = x+20. Find ∠A.",
    options: [
      { text: "100°", type: "correct", logicTag: "3x+30=180→x=50→∠A=110? Let me recalc" },
      { text: "110°", type: "correct", logicTag: "2(50)+10=110" },
      { text: "80°", type: "concept_error", logicTag: "arithmetic error" },
      { text: "70°", type: "concept_error", logicTag: "wrong" },
    ],
    explanation: "∠A+∠C=180°: (2x+10)+(x+20)=180° → 3x+30=180 → x=50. ∠A=2(50)+10=110°.",
    solutionSteps: ["2x+10+x+20=180", "3x=150 → x=50", "∠A=100+10=110°"],
    shortcut: "Set up ∠A+∠C=180°, solve for x, substitute back.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },

  // ── Ch5 · Sub-topic 4: Tangents ─────────────────────────────────────────────
  {
    questionId: "math9_ch5_tangents_q1", topicId: "math9_ch5_tangents",
    text: "A tangent to a circle at point T makes what angle with the radius OT?",
    options: [
      { text: "45°", type: "concept_error", logicTag: "not necessarily" },
      { text: "60°", type: "concept_error", logicTag: "not necessarily" },
      { text: "90°", type: "correct", logicTag: "tangent ⊥ radius at point of contact" },
      { text: "180°", type: "concept_error", logicTag: "that would be collinear" },
    ],
    explanation: "A tangent to a circle is perpendicular to the radius at the point of contact. ∠OTl = 90°.",
    solutionSteps: ["Tangent at T, radius OT", "Tangent ⊥ radius → ∠OTl = 90°"],
    shortcut: "Tangent ⊥ radius. This is the defining property of a tangent.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_tangents_q2", topicId: "math9_ch5_tangents",
    text: "From external point P, two tangents PA and PB are drawn. PA = 8 cm and OP = 10 cm. Find the radius OA.",
    options: [
      { text: "4 cm", type: "concept_error", logicTag: "PA/2" },
      { text: "6 cm", type: "correct", logicTag: "OA=√(100−64)=6" },
      { text: "8 cm", type: "concept_error", logicTag: "equal to PA" },
      { text: "√164", type: "concept_error", logicTag: "added instead of subtracted" },
    ],
    explanation: "OA⊥PA. By Pythagoras: OA²+PA²=OP² → OA²=100−64=36 → OA=6 cm.",
    solutionSteps: ["OA⊥PA → right angle at A", "OA²+8²=10²", "OA²=36 → OA=6"],
    shortcut: "Right triangle OAP: OA²=OP²−PA².",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_tangents_q3", topicId: "math9_ch5_tangents",
    text: "From an external point P, two tangents PA and PB touch a circle. If ∠APB = 60°, find ∠AOB.",
    options: [
      { text: "60°", type: "concept_error", logicTag: "equal to ∠APB" },
      { text: "120°", type: "correct", logicTag: "∠AOB+∠APB=180°" },
      { text: "90°", type: "concept_error", logicTag: "not necessarily" },
      { text: "300°", type: "concept_error", logicTag: "reflex" },
    ],
    explanation: "In quadrilateral OAPB: ∠OAP=∠OBP=90° (tangent⊥radius). So ∠AOB+∠APB=180°. ∠AOB=180°−60°=120°.",
    solutionSteps: ["OAPB: ∠OAP=90°, ∠OBP=90°", "Sum of angles=360°: ∠AOB+90°+60°+90°=360°", "∠AOB=120°"],
    shortcut: "∠AOB + ∠APB = 180°. The two angles are supplementary.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_tangents_q4", topicId: "math9_ch5_tangents",
    text: "PA and PB are tangents from P to a circle with centre O, radius 5 cm. If OP = 13 cm, find PA.",
    options: [
      { text: "8 cm", type: "concept_error", logicTag: "13−5" },
      { text: "12 cm", type: "correct", logicTag: "√(169−25)=√144=12" },
      { text: "10 cm", type: "concept_error", logicTag: "2×5" },
      { text: "√194", type: "concept_error", logicTag: "added squares" },
    ],
    explanation: "OA⊥PA. PA=√(OP²−OA²)=√(169−25)=√144=12 cm. 5-12-13 triple!",
    solutionSteps: ["OA=5, OP=13", "PA=√(13²−5²)=√(169−25)=√144=12"],
    shortcut: "5-12-13 Pythagorean triple! OA=5, PA=12, OP=13.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_tangents_q5", topicId: "math9_ch5_tangents",
    text: "PA and PB are tangents from P. Which of the following is always true?",
    options: [
      { text: "PA > PB", type: "concept_error", logicTag: "they are equal" },
      { text: "PA = PB", type: "correct", logicTag: "tangents from external point are equal" },
      { text: "PA + PB = OP", type: "concept_error", logicTag: "no such relation" },
      { text: "∠OAP = ∠OBP = 45°", type: "concept_error", logicTag: "both are 90°" },
    ],
    explanation: "Tangent segments from an external point are always equal in length. PA = PB.",
    solutionSteps: ["PA and PB are both tangent from P", "Theorem: tangents from external point are equal", "PA = PB"],
    shortcut: "Equal tangents from external point. This is used extensively in geometry.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_tangents_q6", topicId: "math9_ch5_tangents",
    text: "How many tangents can be drawn to a circle from a point ON the circle?",
    options: [
      { text: "0", type: "concept_error", logicTag: "one tangent exists" },
      { text: "1", type: "correct", logicTag: "exactly one tangent at any point on the circle" },
      { text: "2", type: "concept_error", logicTag: "2 tangents from external point" },
      { text: "Infinite", type: "concept_error", logicTag: "only one tangent at a given point" },
    ],
    explanation: "From a point ON the circle, exactly 1 tangent can be drawn. From OUTSIDE: 2 tangents. From INSIDE: 0 tangents.",
    solutionSteps: ["Point on circle → 1 tangent", "External point → 2 tangents", "Internal point → 0 tangents"],
    shortcut: "Tangent count: on circle = 1, outside = 2, inside = 0.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_tangents_q7", topicId: "math9_ch5_tangents",
    text: "If PA is a tangent and PAB is a secant from P (A on circle, B on circle), and PA = 6, PB = 9, find AB.",
    options: [
      { text: "3 cm", type: "concept_error", logicTag: "9−6" },
      { text: "4 cm", type: "correct", logicTag: "PA²=PB×PA' but PA²=PA×PB gives 36=PA×9... wait use correct formula" },
      { text: "6 cm", type: "concept_error", logicTag: "equal to tangent" },
      { text: "5 cm", type: "concept_error", logicTag: "arithmetic error" },
    ],
    explanation: "Power of a point: PA²=PB×PA (where PA is tangent, PB is full secant, PA the near intersection). PA²=36. Let near intersection = PA'=36/9=4. AB=9−4=5. Actually: PA²=P(near)×P(far): 36=PA'×9 → PA'=4. AB=9−4=5.",
    solutionSteps: ["PA²=PB×Pnear: 36=9×Pnear → Pnear=4", "AB=PB−Pnear=9−4=5"],
    shortcut: "Tangent-secant: (tangent)²=(near intersection dist)×(far intersection dist).",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },
  {
    questionId: "math9_ch5_tangents_q8", topicId: "math9_ch5_tangents",
    text: "In triangle ABC, a circle is inscribed touching BC at X, CA at Y, AB at Z. If AY = 4, BX = 3, CX = 5, find AB.",
    options: [
      { text: "7 cm", type: "correct", logicTag: "AZ=AY=4, BZ=BX=3, AB=7" },
      { text: "9 cm", type: "concept_error", logicTag: "AY+CX" },
      { text: "12 cm", type: "concept_error", logicTag: "sum of all" },
      { text: "5 cm", type: "concept_error", logicTag: "BX+CX only" },
    ],
    explanation: "Tangents from same point are equal: AY=AZ=4, BX=BZ=3, CX=CY=5. AB=AZ+BZ=4+3=7.",
    solutionSteps: ["AY=AZ=4 (tangents from A)", "BX=BZ=3 (tangents from B)", "AB=AZ+BZ=4+3=7"],
    shortcut: "Equal tangents from vertices → label all three pairs, then sum the required sides.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "I'm Up and Down, and Round and Round",
  },

  // ── Ch6 · Sub-topic 1: Heron's Formula ─────────────────────────────────────
  {
    questionId: "math9_ch6_heron_formula_q1", topicId: "math9_ch6_heron_formula",
    text: "Find the area of a triangle with sides 7, 8, and 9 cm.",
    options: [
      { text: "12√5 cm²", type: "correct", logicTag: "s=12, area=√(12×5×4×3)=√720=12√5" },
      { text: "56 cm²", type: "concept_error", logicTag: "product of two sides" },
      { text: "28 cm²", type: "concept_error", logicTag: "half base×height estimate" },
      { text: "24√3 cm²", type: "concept_error", logicTag: "wrong formula" },
    ],
    explanation: "s=(7+8+9)/2=12. Area=√[12(12−7)(12−8)(12−9)]=√[12×5×4×3]=√720=12√5 cm².",
    solutionSteps: ["s=24/2=12", "Area=√[12×5×4×3]=√720", "√720=√(144×5)=12√5"],
    shortcut: "√720=√(144×5)=12√5. Factor out perfect squares under the root.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_heron_formula_q2", topicId: "math9_ch6_heron_formula",
    text: "The semi-perimeter of a triangle is 21 cm and its sides are 11, 14, and 17 cm. Verify s and find the area.",
    options: [
      { text: "s=21, Area=√(21×10×7×4)=√5880≈76.7 cm²", type: "correct", logicTag: "correct Heron application" },
      { text: "s=42, Area=√(42×...)", type: "concept_error", logicTag: "s is half the perimeter" },
      { text: "s=21, Area=84 cm²", type: "concept_error", logicTag: "close but not exact" },
      { text: "s=21, Area=60 cm²", type: "concept_error", logicTag: "arithmetic error" },
    ],
    explanation: "s=(11+14+17)/2=21 ✓. Area=√[21(21−11)(21−14)(21−17)]=√[21×10×7×4]=√5880=2√1470≈76.7 cm².",
    solutionSteps: ["s=(11+14+17)/2=21", "Area=√[21×10×7×4]=√5880"],
    shortcut: "s=(a+b+c)/2. Then substitute into √[s(s−a)(s−b)(s−c)].",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_heron_formula_q3", topicId: "math9_ch6_heron_formula",
    text: "A triangular park has sides 120 m, 80 m, and 50 m. Which formula would you use to find its area?",
    options: [
      { text: "(1/2)×base×height, since height is easily found", type: "concept_error", logicTag: "no height given" },
      { text: "Heron's formula, since only sides are given", type: "correct", logicTag: "all 3 sides given, no height" },
      { text: "Area = side² for equilateral", type: "concept_error", logicTag: "not equilateral" },
      { text: "Cannot calculate without height", type: "concept_error", logicTag: "Heron's works without height" },
    ],
    explanation: "Only side lengths are given with no height. Heron's formula is designed exactly for this case.",
    solutionSteps: ["Three sides given: 120, 80, 50", "No altitude given", "Use Heron's formula"],
    shortcut: "No height → use Heron's. Height given → use (1/2)×b×h.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_heron_formula_q4", topicId: "math9_ch6_heron_formula",
    text: "An equilateral triangle has side 6 cm. Find its area using Heron's formula.",
    options: [
      { text: "9√3 cm²", type: "correct", logicTag: "s=9, area=√(9×3×3×3)=9√3" },
      { text: "18 cm²", type: "concept_error", logicTag: "arithmetic error" },
      { text: "6√3 cm²", type: "concept_error", logicTag: "wrong formula" },
      { text: "36 cm²", type: "concept_error", logicTag: "s² confusion" },
    ],
    explanation: "s=(6+6+6)/2=9. Area=√[9(9−6)³]=√[9×27]=√243=9√3 cm².",
    solutionSteps: ["s=9", "Area=√[9×3×3×3]=√[9×27]=√243=9√3"],
    shortcut: "For equilateral side a: Area=(√3/4)a²=(√3/4)×36=9√3 ✓.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_heron_formula_q5", topicId: "math9_ch6_heron_formula",
    text: "A triangle has perimeter 32 cm and two sides 11 cm and 9 cm. Find the third side and the area.",
    options: [
      { text: "Third side = 12, Area = 6√35 cm²", type: "correct", logicTag: "s=16, √[16×5×7×4]=6√35" },
      { text: "Third side = 13, Area = 7√5 cm²", type: "concept_error", logicTag: "incorrect" },
      { text: "Third side = 12, Area = 60 cm²", type: "concept_error", logicTag: "Heron gives different answer" },
      { text: "Third side = 10, Area = 5√7 cm²", type: "concept_error", logicTag: "wrong third side" },
    ],
    explanation: "Third side = 32−11−9=12. s=16. Area=√[16×5×7×4]=√2240=√(64×35)=8√35. Wait: 16×5=80, 80×7=560, 560×4=2240. √2240=√(64×35)=8√35.",
    solutionSteps: ["Third side = 32−20 = 12", "s=16", "Area=√[16×5×7×4]=√2240=8√35 cm²"],
    shortcut: "Find missing side first, then apply Heron's.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_heron_formula_q6", topicId: "math9_ch6_heron_formula",
    text: "A right triangle has legs 9 cm and 12 cm. Find its area two ways and confirm they match.",
    options: [
      { text: "Area = 54 cm² by both methods", type: "correct", logicTag: "(1/2)×9×12=54 and Heron gives same" },
      { text: "Area = 108 cm²", type: "concept_error", logicTag: "forgot the half" },
      { text: "Area = 45 cm²", type: "concept_error", logicTag: "arithmetic error" },
      { text: "Heron gives different answer from (1/2)bh", type: "concept_error", logicTag: "they must match" },
    ],
    explanation: "Method 1: (1/2)×9×12=54. Method 2: hypotenuse=√(81+144)=15. s=(9+12+15)/2=18. √[18×9×6×3]=√2916=54 ✓.",
    solutionSteps: ["Direct: (1/2)×9×12=54", "Hypotenuse=15, s=18", "Heron: √[18×9×6×3]=√2916=54 ✓"],
    shortcut: "9-12-15 is 3×(3-4-5). Area=54 by both methods, confirming Heron's works.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_heron_formula_q7", topicId: "math9_ch6_heron_formula",
    text: "In Heron's formula, what is the semi-perimeter s for a triangle with perimeter 60 cm?",
    options: [
      { text: "60 cm", type: "concept_error", logicTag: "that is the full perimeter" },
      { text: "30 cm", type: "correct", logicTag: "s = perimeter/2 = 30" },
      { text: "20 cm", type: "concept_error", logicTag: "perimeter/3" },
      { text: "15 cm", type: "concept_error", logicTag: "perimeter/4" },
    ],
    explanation: "Semi-perimeter s = perimeter/2 = 60/2 = 30 cm.",
    solutionSteps: ["s = (a+b+c)/2 = perimeter/2", "s = 60/2 = 30"],
    shortcut: "s = P/2. Semi means half.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_heron_formula_q8", topicId: "math9_ch6_heron_formula",
    text: "Can Heron's formula be applied to an equilateral, isosceles, and scalene triangle?",
    options: [
      { text: "Only to scalene triangles", type: "concept_error", logicTag: "works for all" },
      { text: "Only to right triangles", type: "concept_error", logicTag: "works for all" },
      { text: "To all types of triangles", type: "correct", logicTag: "Heron is universal" },
      { text: "Only when height is unknown", type: "partial_logic", logicTag: "true but Heron is not limited to this case" },
    ],
    explanation: "Heron's formula works for ANY triangle given three sides — equilateral, isosceles, scalene, right, obtuse.",
    solutionSteps: ["Heron's: Area=√[s(s−a)(s−b)(s−c)]", "Requires only side lengths", "Valid for ALL triangles"],
    shortcut: "Heron's formula is universal. No restriction on triangle type.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },

  // ── Ch6 · Sub-topics 2–4 condensed ─────────────────────────────────────────
  {
    questionId: "math9_ch6_quadrilateral_area_q1", topicId: "math9_ch6_quadrilateral_area",
    text: "Find the area of a rhombus with diagonals 10 cm and 24 cm.",
    options: [
      { text: "120 cm²", type: "correct", logicTag: "(1/2)×10×24=120" },
      { text: "240 cm²", type: "concept_error", logicTag: "forgot the half" },
      { text: "60 cm²", type: "concept_error", logicTag: "only one diagonal" },
      { text: "34 cm²", type: "concept_error", logicTag: "sum of diagonals" },
    ],
    explanation: "Area of rhombus = (1/2)×d₁×d₂ = (1/2)×10×24 = 120 cm².",
    solutionSteps: ["Area = (1/2)×d₁×d₂", "= (1/2)×10×24 = 120"],
    shortcut: "Rhombus and kite: Area = (1/2)×d₁×d₂.",
    difficulty: "easy", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_surface_area_q1", topicId: "math9_ch6_surface_area",
    text: "Find the total surface area of a cylinder with radius 7 cm and height 10 cm. (Use π = 22/7)",
    options: [
      { text: "440 cm²", type: "concept_error", logicTag: "only CSA" },
      { text: "748 cm²", type: "correct", logicTag: "2πr(r+h)=2×22×(7+10)=748" },
      { text: "1540 cm²", type: "concept_error", logicTag: "wrong formula" },
      { text: "308 cm²", type: "concept_error", logicTag: "only two circles" },
    ],
    explanation: "TSA = 2πr(r+h) = 2×(22/7)×7×17 = 2×22×17 = 748 cm².",
    solutionSteps: ["TSA=2πr(r+h)", "=2×22/7×7×(7+10)=2×22×17=748"],
    shortcut: "π×7=22 when π=22/7. Simplifies nicely.",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_volume_q1", topicId: "math9_ch6_volume",
    text: "A cone has radius 3 cm and height 4 cm. Find its volume. (Use π = 3.14)",
    options: [
      { text: "37.68 cm³", type: "correct", logicTag: "(1/3)×3.14×9×4=37.68" },
      { text: "113.04 cm³", type: "concept_error", logicTag: "forgot the 1/3" },
      { text: "12.56 cm³", type: "concept_error", logicTag: "only πr²" },
      { text: "150.72 cm³", type: "concept_error", logicTag: "πr²h not cone" },
    ],
    explanation: "V(cone)=(1/3)πr²h=(1/3)×3.14×9×4=3.14×12=37.68 cm³.",
    solutionSteps: ["V=(1/3)πr²h", "=(1/3)×3.14×9×4=3.14×12=37.68"],
    shortcut: "Cone = 1/3 of cylinder (same base, same height).",
    difficulty: "medium", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
  {
    questionId: "math9_ch6_volume_q2", topicId: "math9_ch6_volume",
    text: "A sphere has volume (500/3)π cm³. Find its radius.",
    options: [
      { text: "5 cm", type: "correct", logicTag: "(4/3)πr³=(500/3)π → r³=125 → r=5" },
      { text: "10 cm", type: "concept_error", logicTag: "r³=1000" },
      { text: "3 cm", type: "concept_error", logicTag: "r³=27" },
      { text: "25 cm", type: "concept_error", logicTag: "r²=25 confusion" },
    ],
    explanation: "(4/3)πr³=(500/3)π → r³=500×3/(3×4)=125 → r=5 cm.",
    solutionSteps: ["(4/3)r³=500/3", "r³=500/4=125", "r=∛125=5"],
    shortcut: "Isolate r³, then take cube root.",
    difficulty: "hard", subject: "Mathematics", grade: "9", chapter: "Measuring Space: Perimeter and Area",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  for (const q of questions) {
    await Question.findOneAndUpdate(
      { questionId: q.questionId },
      q,
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`  ✓ ${q.questionId}`);
  }
  console.log(`\nSeeded ${questions.length} questions for Class 9 Math (Ch5–Ch6 sub-topics).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
