import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math3_ch3_addition_3digit — 8 Qs
  { questionId:"math3_ch3_a3_q1", topicId:"math3_ch3_addition_3digit", text:"234 + 153 = ?", options:[{text:"387",type:"correct"},{text:"387",type:"concept_error"},{text:"377",type:"calculation_error"},{text:"487",type:"calculation_error"}], explanation:"Ones: 4+3=7. Tens: 3+5=8. Hundreds: 2+1=3. → 387.", solutionSteps:["Ones: 4+3=7.","Tens: 3+5=8.","Hundreds: 2+1=3.","Sum = 387."], shortcut:"Add column by column from right.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_a3_q2", topicId:"math3_ch3_addition_3digit", text:"412 + 365 = ?", options:[{text:"777",type:"correct"},{text:"677",type:"calculation_error"},{text:"787",type:"calculation_error"},{text:"778",type:"calculation_error"}], explanation:"Ones: 2+5=7. Tens: 1+6=7. Hundreds: 4+3=7. → 777.", solutionSteps:["Ones: 2+5=7.","Tens: 1+6=7.","Hundreds: 4+3=7.","Sum = 777."], shortcut:"Right-to-left column addition.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_a3_q3", topicId:"math3_ch3_addition_3digit", text:"500 + 250 = ?", options:[{text:"750",type:"correct"},{text:"550",type:"calculation_error"},{text:"700",type:"calculation_error"},{text:"7500",type:"concept_error"}], explanation:"500 + 250 = 750.", solutionSteps:["500 + 250 = 750."], shortcut:"Add hundreds: 500+200=700. Then 50.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_a3_q4", topicId:"math3_ch3_addition_3digit", text:"123 + 456 = ?", options:[{text:"579",type:"correct"},{text:"589",type:"calculation_error"},{text:"679",type:"calculation_error"},{text:"567",type:"misinterpretation"}], explanation:"Ones: 3+6=9. Tens: 2+5=7. Hundreds: 1+4=5. → 579.", solutionSteps:["Ones: 3+6=9.","Tens: 2+5=7.","Hundreds: 1+4=5.","Sum = 579."], shortcut:"Right-to-left.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_a3_q5", topicId:"math3_ch3_addition_3digit", text:"325 + 100 = ?", options:[{text:"425",type:"correct"},{text:"3251",type:"concept_error"},{text:"335",type:"calculation_error"},{text:"525",type:"calculation_error"}], explanation:"Add 100 → just increase hundreds digit by 1: 325 → 425.", solutionSteps:["Add to hundreds: 3+1=4.","Tens and ones unchanged.","Result: 425."], shortcut:"+100: hundreds digit +1.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_a3_q6", topicId:"math3_ch3_addition_3digit", text:"205 + 304 = ?", options:[{text:"509",type:"correct"},{text:"519",type:"calculation_error"},{text:"609",type:"calculation_error"},{text:"500",type:"misinterpretation"}], explanation:"Ones: 5+4=9. Tens: 0+0=0. Hundreds: 2+3=5. → 509.", solutionSteps:["Ones: 5+4=9.","Tens: 0+0=0.","Hundreds: 2+3=5.","Sum = 509."], shortcut:"Zero tens stay zero.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_a3_q7", topicId:"math3_ch3_addition_3digit", text:"A school has 240 boys and 152 girls. Total students?", options:[{text:"392",type:"correct"},{text:"352",type:"calculation_error"},{text:"392",type:"concept_error"},{text:"282",type:"calculation_error"}], explanation:"240 + 152 = 392.", solutionSteps:["Ones: 0+2=2.","Tens: 4+5=9.","Hundreds: 2+1=3.","Sum = 392."], shortcut:"Total = boys + girls.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_a3_q8", topicId:"math3_ch3_addition_3digit", text:"600 + 199 = ?", options:[{text:"799",type:"correct"},{text:"800",type:"calculation_error"},{text:"6199",type:"concept_error"},{text:"709",type:"calculation_error"}], explanation:"600 + 199 = 799.", solutionSteps:["600 + 199 = 799.","(Or: 600 + 200 = 800, then −1 = 799.)"], shortcut:"Use friendly number: 200, then adjust by −1.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },

  // math3_ch3_subtraction_3digit — 8 Qs
  { questionId:"math3_ch3_s3_q1", topicId:"math3_ch3_subtraction_3digit", text:"768 − 234 = ?", options:[{text:"534",type:"correct"},{text:"434",type:"calculation_error"},{text:"574",type:"calculation_error"},{text:"354",type:"misinterpretation"}], explanation:"Ones: 8−4=4. Tens: 6−3=3. Hundreds: 7−2=5. → 534.", solutionSteps:["Ones: 8−4=4.","Tens: 6−3=3.","Hundreds: 7−2=5.","Diff = 534."], shortcut:"Subtract column by column from right.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_s3_q2", topicId:"math3_ch3_subtraction_3digit", text:"500 − 200 = ?", options:[{text:"300",type:"correct"},{text:"700",type:"misinterpretation"},{text:"3",type:"concept_error"},{text:"200",type:"calculation_error"}], explanation:"500 − 200 = 300.", solutionSteps:["Hundreds: 5−2=3.","Result = 300."], shortcut:"Subtract hundreds straight.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_s3_q3", topicId:"math3_ch3_subtraction_3digit", text:"999 − 1 = ?", options:[{text:"998",type:"correct"},{text:"999",type:"concept_error"},{text:"998",type:"calculation_error"},{text:"988",type:"calculation_error"}], explanation:"Just one less than 999 → 998.", solutionSteps:["Subtract 1 from ones: 9−1=8.","Other digits unchanged.","Result = 998."], shortcut:"Predecessor.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_s3_q4", topicId:"math3_ch3_subtraction_3digit", text:"879 − 543 = ?", options:[{text:"336",type:"correct"},{text:"336",type:"calculation_error"},{text:"346",type:"calculation_error"},{text:"436",type:"calculation_error"}], explanation:"Ones: 9−3=6. Tens: 7−4=3. Hundreds: 8−5=3. → 336.", solutionSteps:["Ones: 9−3=6.","Tens: 7−4=3.","Hundreds: 8−5=3.","Diff = 336."], shortcut:"Right-to-left.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_s3_q5", topicId:"math3_ch3_subtraction_3digit", text:"Rina had 658 stickers. She gave 234 to her friend. Stickers left?", options:[{text:"424",type:"correct"},{text:"892",type:"misinterpretation"},{text:"434",type:"calculation_error"},{text:"414",type:"calculation_error"}], explanation:"658 − 234: Ones 8−4=4. Tens 5−3=2. Hundreds 6−2=4. → 424.", solutionSteps:["Ones: 8−4=4.","Tens: 5−3=2.","Hundreds: 6−2=4.","Left = 424."], shortcut:"Started − gave = left.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_s3_q6", topicId:"math3_ch3_subtraction_3digit", text:"700 − 350 = ?", options:[{text:"350",type:"correct"},{text:"450",type:"calculation_error"},{text:"250",type:"calculation_error"},{text:"700",type:"concept_error"}], explanation:"700 − 350 = 350. (Half of 700.)", solutionSteps:["700 − 350 = 350."], shortcut:"Half of 700 is 350.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_s3_q7", topicId:"math3_ch3_subtraction_3digit", text:"What is 100 − 99?", options:[{text:"1",type:"correct"},{text:"0",type:"calculation_error"},{text:"10",type:"calculation_error"},{text:"99",type:"misinterpretation"}], explanation:"100 − 99 = 1.", solutionSteps:["99 + 1 = 100.","So 100 − 99 = 1."], shortcut:"Consecutive numbers differ by 1.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_s3_q8", topicId:"math3_ch3_subtraction_3digit", text:"In subtraction, the BIGGER number should be on…", options:[{text:"Top",type:"correct"},{text:"Bottom",type:"concept_error"},{text:"Either side",type:"misinterpretation"},{text:"Left",type:"guessing"}], explanation:"Always write the bigger number on top so you can subtract digit by digit.", solutionSteps:["Bigger on top → subtract row by row.","Smaller on top → negative result (not allowed here)."], shortcut:"Bigger on top.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },

  // math3_ch3_carrying — 8 Qs
  { questionId:"math3_ch3_ca_q1", topicId:"math3_ch3_carrying", text:"248 + 367 = ? (with carrying)", options:[{text:"615",type:"correct"},{text:"515",type:"calculation_error"},{text:"605",type:"calculation_error"},{text:"715",type:"calculation_error"}], explanation:"Ones: 8+7=15 → 5 carry 1. Tens: 4+6+1=11 → 1 carry 1. Hundreds: 2+3+1=6. → 615.", solutionSteps:["Ones: 8+7=15. Write 5, carry 1.","Tens: 4+6+1=11. Write 1, carry 1.","Hundreds: 2+3+1=6.","Sum = 615."], shortcut:"Carry when sum ≥ 10.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_ca_q2", topicId:"math3_ch3_carrying", text:"When do you carry in addition?", options:[{text:"When sum < 10",type:"concept_error"},{text:"When sum ≥ 10",type:"correct"},{text:"Always",type:"misinterpretation"},{text:"Never",type:"misinterpretation"}], explanation:"If a column's sum is 10 or more, carry 1 to the next column.", solutionSteps:["Sum ≥ 10 → carry.","Sum < 10 → no carry."], shortcut:"≥10 = carry 1.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_ca_q3", topicId:"math3_ch3_carrying", text:"159 + 26 = ?", options:[{text:"185",type:"correct"},{text:"175",type:"calculation_error"},{text:"285",type:"calculation_error"},{text:"195",type:"calculation_error"}], explanation:"Ones: 9+6=15 → 5 carry 1. Tens: 5+2+1=8. Hundreds: 1+0=1. → 185.", solutionSteps:["Ones: 9+6=15. Write 5, carry 1.","Tens: 5+2+1=8.","Hundreds: 1.","Sum = 185."], shortcut:"Carry from ones when ≥10.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_ca_q4", topicId:"math3_ch3_carrying", text:"99 + 11 = ?", options:[{text:"110",type:"correct"},{text:"100",type:"calculation_error"},{text:"111",type:"calculation_error"},{text:"99",type:"misinterpretation"}], explanation:"Ones: 9+1=10 → 0 carry 1. Tens: 9+1+1=11 → 1 carry 1. Hundreds: 0+0+1=1. → 110.", solutionSteps:["Ones: 9+1=10. Write 0, carry 1.","Tens: 9+1+1=11. Write 1, carry 1.","Hundreds: 0+0+1=1.","Sum = 110."], shortcut:"Double carry possible.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_ca_q5", topicId:"math3_ch3_carrying", text:"In 47 + 38, what is the carry from ones?", options:[{text:"0",type:"concept_error"},{text:"1",type:"correct"},{text:"2",type:"calculation_error"},{text:"15",type:"misinterpretation"}], explanation:"7+8=15 → write 5, carry 1.", solutionSteps:["Ones: 7+8=15.","15 has tens=1.","Carry = 1."], shortcut:"Carry = tens digit of column sum.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_ca_q6", topicId:"math3_ch3_carrying", text:"After carrying, you ADD the carry to which place?", options:[{text:"The same place",type:"concept_error"},{text:"The next column on the LEFT",type:"correct"},{text:"The next column on the RIGHT",type:"misinterpretation"},{text:"Top of the number",type:"guessing"}], explanation:"Carry moves to the NEXT LEFT column (higher place value).", solutionSteps:["Carry from ones → tens column.","Carry from tens → hundreds column."], shortcut:"Carries move LEFT.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_ca_q7", topicId:"math3_ch3_carrying", text:"88 + 12 = ?", options:[{text:"100",type:"correct"},{text:"99",type:"calculation_error"},{text:"110",type:"calculation_error"},{text:"90",type:"calculation_error"}], explanation:"Ones: 8+2=10 → 0 carry 1. Tens: 8+1+1=10 → 0 carry 1. Hundreds: 0+0+1=1. → 100.", solutionSteps:["Ones: 8+2=10.","Tens: 8+1+1=10.","Hundreds: 0+0+1=1.","Sum = 100."], shortcut:"Carry can cascade.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_ca_q8", topicId:"math3_ch3_carrying", text:"In 365 + 247, the tens column sums to…", options:[{text:"10",type:"concept_error"},{text:"11",type:"correct"},{text:"12",type:"calculation_error"},{text:"13",type:"calculation_error"}], explanation:"Ones: 5+7=12 → carry 1. Tens: 6+4+1=11.", solutionSteps:["Ones: 5+7=12. Carry 1.","Tens: 6+4=10. +1 carry = 11."], shortcut:"Don't forget incoming carry.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Give and Take" },

  // math3_ch3_borrowing — 8 Qs
  { questionId:"math3_ch3_bo_q1", topicId:"math3_ch3_borrowing", text:"43 − 17 = ? (with borrowing)", options:[{text:"26",type:"correct"},{text:"24",type:"calculation_error"},{text:"36",type:"calculation_error"},{text:"34",type:"calculation_error"}], explanation:"Ones: 3<7, borrow → 13−7=6. Tens: (4−1)=3, 3−1=2. → 26.", solutionSteps:["Ones: 3<7, borrow 1 ten → 13.","13−7=6.","Tens: (4−1=3)−1=2.","Diff = 26."], shortcut:"Borrow from next column on left.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_bo_q2", topicId:"math3_ch3_borrowing", text:"When do you borrow in subtraction?", options:[{text:"When top digit ≥ bottom",type:"concept_error"},{text:"When top digit < bottom",type:"correct"},{text:"Never",type:"misinterpretation"},{text:"Always",type:"misinterpretation"}], explanation:"Borrow only if the top digit is smaller than the bottom digit.", solutionSteps:["Top < bottom → borrow.","Top ≥ bottom → no borrow."], shortcut:"Smaller on top → borrow.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_bo_q3", topicId:"math3_ch3_borrowing", text:"523 − 168 = ?", options:[{text:"355",type:"correct"},{text:"445",type:"calculation_error"},{text:"345",type:"calculation_error"},{text:"365",type:"calculation_error"}], explanation:"Ones: 3<8, borrow → 13−8=5. Tens: (2−1=1)<6, borrow → 11−6=5. Hundreds: (5−1)−1=3. → 355.", solutionSteps:["Ones: 3<8. Borrow → 13−8=5.","Tens: (2−1=1)<6. Borrow → 11−6=5.","Hundreds: (5−1)−1=3.","Diff = 355."], shortcut:"Borrowing cascades.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_bo_q4", topicId:"math3_ch3_borrowing", text:"After borrowing 1 ten, the ones column gains how many?", options:[{text:"1",type:"concept_error"},{text:"10",type:"correct"},{text:"100",type:"misinterpretation"},{text:"5",type:"guessing"}], explanation:"1 ten = 10 ones. Borrowing converts a ten to 10 ones.", solutionSteps:["1 ten = 10 ones.","Ones column gains 10."], shortcut:"Borrow 1 ten = +10 ones.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_bo_q5", topicId:"math3_ch3_borrowing", text:"60 − 25 = ?", options:[{text:"35",type:"correct"},{text:"45",type:"calculation_error"},{text:"25",type:"misinterpretation"},{text:"55",type:"calculation_error"}], explanation:"Ones: 0<5, borrow → 10−5=5. Tens: (6−1)−2=3. → 35.", solutionSteps:["Ones: 0<5. Borrow.","10−5=5.","Tens: (6−1)−2 = 5−2 = 3.","Diff = 35."], shortcut:"Subtraction with zero in ones needs borrowing.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_bo_q6", topicId:"math3_ch3_borrowing", text:"700 − 256 = ?", options:[{text:"444",type:"correct"},{text:"544",type:"calculation_error"},{text:"434",type:"calculation_error"},{text:"464",type:"calculation_error"}], explanation:"Ones: 0<6, borrow from tens — but tens=0, so borrow from hundreds first. 7 hundreds → 6 hundreds + 10 tens; then 10 tens → 9 tens + 10 ones. Ones: 10−6=4. Tens: 9−5=4. Hundreds: 6−2=4. → 444.", solutionSteps:["Ones: 0<6. Tens=0 too, so cascade-borrow.","Hundreds: 7→6, tens: 0→10.","Tens: 10→9, ones: 0→10.","Ones: 10−6=4.","Tens: 9−5=4.","Hundreds: 6−2=4."], shortcut:"Cascade borrowing through zeros.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_bo_q7", topicId:"math3_ch3_borrowing", text:"Check by adding: if 523 − 168 = 355, then 355 + 168 = ?", options:[{text:"523",type:"correct"},{text:"533",type:"calculation_error"},{text:"513",type:"calculation_error"},{text:"500",type:"misinterpretation"}], explanation:"Answer + smaller = bigger. 355 + 168 = 523.", solutionSteps:["Verify: answer + subtractor should equal bigger.","355 + 168 = 523. ✓"], shortcut:"Subtraction check = reverse-add.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },
  { questionId:"math3_ch3_bo_q8", topicId:"math3_ch3_borrowing", text:"After borrowing 1 from the tens column, the tens digit becomes…", options:[{text:"Unchanged",type:"concept_error"},{text:"1 less",type:"correct"},{text:"1 more",type:"misinterpretation"},{text:"10 less",type:"calculation_error"}], explanation:"Borrowing 1 from a column reduces that column by 1.", solutionSteps:["Borrow gives 10 to right column.","Lender column loses 1."], shortcut:"Lender loses 1.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Give and Take" },

  // math3_ch4_units_cm_m — 8 Qs
  { questionId:"math3_ch4_uc_q1", topicId:"math3_ch4_units_cm_m", text:"1 m = ? cm", options:[{text:"10",type:"concept_error"},{text:"100",type:"correct"},{text:"1000",type:"misinterpretation"},{text:"1",type:"guessing"}], explanation:"1 metre = 100 centimetres.", solutionSteps:["By definition: 1 m = 100 cm."], shortcut:"1 m = 100 cm.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_uc_q2", topicId:"math3_ch4_units_cm_m", text:"Which unit should you use to measure the length of a pencil?", options:[{text:"km",type:"concept_error"},{text:"m",type:"misinterpretation"},{text:"cm",type:"correct"},{text:"kg",type:"concept_error"}], explanation:"A pencil is small, so cm is the right unit.", solutionSteps:["Pencil ≈ 15 cm.","cm is the small-object unit."], shortcut:"Small objects → cm.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_uc_q3", topicId:"math3_ch4_units_cm_m", text:"300 cm = ? m", options:[{text:"30 m",type:"calculation_error"},{text:"3 m",type:"correct"},{text:"0.3 m",type:"calculation_error"},{text:"3000 m",type:"misinterpretation"}], explanation:"300 ÷ 100 = 3 m.", solutionSteps:["cm → m: divide by 100.","300 ÷ 100 = 3 m."], shortcut:"Divide cm by 100 to get m.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_uc_q4", topicId:"math3_ch4_units_cm_m", text:"Which unit measures the distance between two cities?", options:[{text:"cm",type:"concept_error"},{text:"m",type:"partial_logic"},{text:"km",type:"correct"},{text:"kg",type:"misinterpretation"}], explanation:"Cities are far apart — kilometres (km) are used.", solutionSteps:["Long distances = km.","1 km = 1000 m."], shortcut:"Cities far → km.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_uc_q5", topicId:"math3_ch4_units_cm_m", text:"A child is 120 cm tall. In metres, that is…", options:[{text:"12 m",type:"calculation_error"},{text:"1.2 m",type:"correct"},{text:"120 m",type:"misinterpretation"},{text:"0.12 m",type:"calculation_error"}], explanation:"120 ÷ 100 = 1.2 m.", solutionSteps:["120 cm = 100 cm + 20 cm.","= 1 m + 20 cm = 1.2 m."], shortcut:"Divide cm by 100 for m.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_uc_q6", topicId:"math3_ch4_units_cm_m", text:"2 m = ? cm", options:[{text:"20",type:"calculation_error"},{text:"200",type:"correct"},{text:"2000",type:"misinterpretation"},{text:"2",type:"concept_error"}], explanation:"2 × 100 = 200 cm.", solutionSteps:["m → cm: multiply by 100.","2 × 100 = 200."], shortcut:"Multiply m by 100 for cm.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_uc_q7", topicId:"math3_ch4_units_cm_m", text:"Best unit for measuring a football field?", options:[{text:"cm",type:"concept_error"},{text:"m",type:"correct"},{text:"mm",type:"misinterpretation"},{text:"kg",type:"concept_error"}], explanation:"A football field is about 100 m — m is right.", solutionSteps:["Field is long but not huge.","m is the right unit."], shortcut:"Room/field length → m.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_uc_q8", topicId:"math3_ch4_units_cm_m", text:"450 cm = ? m ? cm", options:[{text:"45 m 0 cm",type:"calculation_error"},{text:"4 m 50 cm",type:"correct"},{text:"4 m 5 cm",type:"calculation_error"},{text:"4.5 m",type:"partial_logic"}], explanation:"450 cm = 400 cm + 50 cm = 4 m 50 cm.", solutionSteps:["450 ÷ 100 = 4 m (with remainder).","Remainder = 50 cm.","→ 4 m 50 cm."], shortcut:"Quotient = m; remainder = cm.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },

  // math3_ch4_measuring_length — 8 Qs
  { questionId:"math3_ch4_ml_q1", topicId:"math3_ch4_measuring_length", text:"To measure a pencil with a ruler, align which mark to one end?", options:[{text:"1 cm",type:"concept_error"},{text:"0 (zero)",type:"correct"},{text:"Any number",type:"misinterpretation"},{text:"The end of the ruler",type:"partial_logic"}], explanation:"Always align 0 with one end of the object.", solutionSteps:["Place 0 at one end.","Read at the other end."], shortcut:"Start at 0.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_ml_q2", topicId:"math3_ch4_measuring_length", text:"A pencil aligned at 0 ends at 14 on the ruler. Its length is…", options:[{text:"14 cm",type:"correct"},{text:"15 cm",type:"calculation_error"},{text:"13 cm",type:"calculation_error"},{text:"140 cm",type:"misinterpretation"}], explanation:"End − start = 14 − 0 = 14 cm.", solutionSteps:["End reading: 14.","Start reading: 0.","Length = 14 − 0 = 14 cm."], shortcut:"Length = end − start.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_ml_q3", topicId:"math3_ch4_measuring_length", text:"If a pencil starts at 2 cm and ends at 17 cm, its length is…", options:[{text:"19 cm",type:"calculation_error"},{text:"15 cm",type:"correct"},{text:"17 cm",type:"misinterpretation"},{text:"2 cm",type:"misinterpretation"}], explanation:"Length = end − start = 17 − 2 = 15 cm.", solutionSteps:["17 − 2 = 15.","Length = 15 cm."], shortcut:"Length = end reading − start reading.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_ml_q4", topicId:"math3_ch4_measuring_length", text:"Which is the standard tool to measure length in school?", options:[{text:"Spoon",type:"concept_error"},{text:"Ruler / Scale",type:"correct"},{text:"Weighing scale",type:"misinterpretation"},{text:"Stopwatch",type:"concept_error"}], explanation:"Ruler (or scale) is the standard length-measuring tool.", solutionSteps:["Ruler has cm markings.","It is for length."], shortcut:"Ruler = length tool.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_ml_q5", topicId:"math3_ch4_measuring_length", text:"A piece of string is 7 cm long. If you cut 3 cm, how much is left?", options:[{text:"3 cm",type:"misinterpretation"},{text:"4 cm",type:"correct"},{text:"10 cm",type:"calculation_error"},{text:"21 cm",type:"concept_error"}], explanation:"7 − 3 = 4 cm.", solutionSteps:["7 − 3 = 4.","String left = 4 cm."], shortcut:"Subtract the cut.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_ml_q6", topicId:"math3_ch4_measuring_length", text:"For a curved line, the best tool is…", options:[{text:"Ruler",type:"partial_logic"},{text:"String + ruler",type:"correct"},{text:"Compass",type:"misinterpretation"},{text:"Spoon",type:"concept_error"}], explanation:"Lay a string along the curve, then measure the straightened string with a ruler.", solutionSteps:["Follow curve with string.","Straighten string.","Measure with ruler."], shortcut:"Curved length: string then ruler.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_ml_q7", topicId:"math3_ch4_measuring_length", text:"If a book is measured as 22 cm by Ramu and 23 cm by Sita, what's the BEST single value?", options:[{text:"Pick Ramu's",type:"partial_logic"},{text:"Average them (22.5 cm)",type:"correct"},{text:"Add them (45 cm)",type:"misinterpretation"},{text:"Subtract (1 cm)",type:"concept_error"}], explanation:"Take the average of multiple measurements for a more accurate value.", solutionSteps:["Avg = (22 + 23) ÷ 2 = 22.5 cm."], shortcut:"Average multiple measurements.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_ml_q8", topicId:"math3_ch4_measuring_length", text:"A ruler's smallest divisions are usually…", options:[{text:"1 m",type:"concept_error"},{text:"1 cm",type:"partial_logic"},{text:"1 mm",type:"correct"},{text:"1 km",type:"guessing"}], explanation:"Most rulers show mm as the smallest divisions (10 mm = 1 cm).", solutionSteps:["Ruler markings: small lines = mm.","10 mm = 1 cm."], shortcut:"Ruler's tiniest = mm.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },

  // math3_ch4_comparing_lengths — 8 Qs
  { questionId:"math3_ch4_cl_q1", topicId:"math3_ch4_comparing_lengths", text:"Which is longer: 1 m or 80 cm?", options:[{text:"80 cm",type:"concept_error"},{text:"1 m",type:"correct"},{text:"Equal",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"1 m = 100 cm; 100 > 80 → 1 m is longer.", solutionSteps:["Convert 1 m = 100 cm.","100 > 80.","1 m is longer."], shortcut:"Convert to same unit before comparing.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_cl_q2", topicId:"math3_ch4_comparing_lengths", text:"Pencil A is 15 cm. Pencil B is 12 cm. Which is longer and by how much?", options:[{text:"A by 3 cm",type:"correct"},{text:"B by 3 cm",type:"misinterpretation"},{text:"A by 27 cm",type:"calculation_error"},{text:"Equal",type:"misinterpretation"}], explanation:"15 − 12 = 3. A is longer by 3 cm.", solutionSteps:["A > B (15 > 12).","Difference: 15 − 12 = 3 cm."], shortcut:"Longer − shorter = difference.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_cl_q3", topicId:"math3_ch4_comparing_lengths", text:"Which is the shortest: 50 cm, 1 m, 75 cm?", options:[{text:"1 m",type:"concept_error"},{text:"75 cm",type:"concept_error"},{text:"50 cm",type:"correct"},{text:"All equal",type:"misinterpretation"}], explanation:"Convert all: 1 m=100, 75, 50. Smallest = 50 cm.", solutionSteps:["1 m = 100 cm.","Compare 100, 75, 50.","Smallest = 50."], shortcut:"Convert and find smallest.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_cl_q4", topicId:"math3_ch4_comparing_lengths", text:"To compare 200 cm and 1 m 50 cm, both must be in…", options:[{text:"Different units",type:"concept_error"},{text:"Same unit",type:"correct"},{text:"Inches",type:"misinterpretation"},{text:"kg",type:"concept_error"}], explanation:"Always compare lengths in the same unit (e.g., cm).", solutionSteps:["Convert to same unit.","1 m 50 cm = 150 cm.","Compare 200 vs 150."], shortcut:"Same unit first, then compare.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_cl_q5", topicId:"math3_ch4_comparing_lengths", text:"Arrange in increasing order: 250 cm, 1 m, 75 cm", options:[{text:"75 cm, 1 m, 250 cm",type:"correct"},{text:"250 cm, 1 m, 75 cm",type:"concept_error"},{text:"1 m, 75 cm, 250 cm",type:"calculation_error"},{text:"75 cm, 250 cm, 1 m",type:"calculation_error"}], explanation:"In cm: 75, 100 (=1m), 250. Increasing → 75 cm, 1 m, 250 cm.", solutionSteps:["1 m = 100 cm.","Sort: 75 < 100 < 250.","Increasing: 75 cm, 1 m, 250 cm."], shortcut:"Convert all → sort.", difficulty:"hard", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_cl_q6", topicId:"math3_ch4_comparing_lengths", text:"How many cm shorter is 1 m than 1 m 25 cm?", options:[{text:"25 cm",type:"correct"},{text:"24 cm",type:"calculation_error"},{text:"75 cm",type:"calculation_error"},{text:"125 cm",type:"misinterpretation"}], explanation:"1 m 25 cm − 1 m = 25 cm.", solutionSteps:["1 m 25 cm − 1 m = 25 cm."], shortcut:"Subtract: bigger − smaller.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_cl_q7", topicId:"math3_ch4_comparing_lengths", text:"Riya's height is 1 m 30 cm. Ria's is 130 cm. They are…", options:[{text:"Equal",type:"correct"},{text:"Different",type:"concept_error"},{text:"Cannot tell",type:"misinterpretation"},{text:"Riya is taller",type:"calculation_error"}], explanation:"1 m 30 cm = 130 cm = Ria's height. Equal.", solutionSteps:["1 m 30 cm = 100 + 30 = 130 cm.","Both = 130 cm.","Equal."], shortcut:"Convert and check.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_cl_q8", topicId:"math3_ch4_comparing_lengths", text:"Compare: 99 cm ___ 1 m", options:[{text:">",type:"concept_error"},{text:"<",type:"correct"},{text:"=",type:"calculation_error"},{text:"Can't compare",type:"guessing"}], explanation:"1 m = 100 cm. 99 < 100.", solutionSteps:["1 m = 100 cm.","99 < 100.","99 cm < 1 m."], shortcut:"Convert before comparing.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },

  // math3_ch4_estimating — 8 Qs
  { questionId:"math3_ch4_es_q1", topicId:"math3_ch4_estimating", text:"What is estimation?", options:[{text:"Exact measurement",type:"concept_error"},{text:"A smart guess based on what you know",type:"correct"},{text:"Wrong answer",type:"misinterpretation"},{text:"Adding random numbers",type:"guessing"}], explanation:"Estimation is an educated guess using familiar references.", solutionSteps:["Not random.","Based on what you already know."], shortcut:"Estimation = smart guess.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_es_q2", topicId:"math3_ch4_estimating", text:"Approximately how long is your thumb (an average adult)?", options:[{text:"1 mm",type:"concept_error"},{text:"5 cm",type:"correct"},{text:"30 cm",type:"misinterpretation"},{text:"1 m",type:"misinterpretation"}], explanation:"An adult thumb is roughly 5 cm long.", solutionSteps:["Thumb ≈ 5 cm.","Useful reference."], shortcut:"Thumb ≈ 5 cm.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_es_q3", topicId:"math3_ch4_estimating", text:"Approximate length of one footstep?", options:[{text:"5 cm",type:"concept_error"},{text:"50 cm",type:"correct"},{text:"5 m",type:"misinterpretation"},{text:"50 m",type:"misinterpretation"}], explanation:"One foot step is about 50 cm.", solutionSteps:["Footstep ≈ 50 cm.","Useful reference."], shortcut:"Footstep ≈ 50 cm.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_es_q4", topicId:"math3_ch4_estimating", text:"Roughly how long is an arm-span (fingertip to fingertip)?", options:[{text:"10 cm",type:"concept_error"},{text:"1 m",type:"correct"},{text:"10 m",type:"misinterpretation"},{text:"1 cm",type:"calculation_error"}], explanation:"An adult's arm-span is approximately 1 m (same as height).", solutionSteps:["Arm-span ≈ height.","Adult ≈ 1.5 m, but kid arm-span ≈ 1 m."], shortcut:"Arm-span ≈ height.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_es_q5", topicId:"math3_ch4_estimating", text:"Estimate the length of a desk if you can walk along it in 4 footsteps.", options:[{text:"~200 cm = 2 m",type:"correct"},{text:"40 cm",type:"calculation_error"},{text:"4 m",type:"calculation_error"},{text:"2 cm",type:"concept_error"}], explanation:"4 × 50 cm = 200 cm = 2 m.", solutionSteps:["1 step ≈ 50 cm.","4 × 50 = 200 cm.","= 2 m."], shortcut:"Steps × 50 cm = total cm.", difficulty:"medium", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_es_q6", topicId:"math3_ch4_estimating", text:"Estimate the height of a door.", options:[{text:"20 cm",type:"concept_error"},{text:"2 m",type:"correct"},{text:"20 m",type:"misinterpretation"},{text:"2 cm",type:"misinterpretation"}], explanation:"A standard door is about 2 m tall.", solutionSteps:["Door height ≈ 2 m.","Tall enough for an adult to walk through."], shortcut:"Door ≈ 2 m.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_es_q7", topicId:"math3_ch4_estimating", text:"How tall is an adult human approximately?", options:[{text:"30 cm",type:"concept_error"},{text:"1.5 to 1.8 m",type:"correct"},{text:"15 m",type:"misinterpretation"},{text:"5 m",type:"calculation_error"}], explanation:"Most adults are between 1.5 m and 1.8 m tall.", solutionSteps:["Average adult: 150–180 cm.","= 1.5–1.8 m."], shortcut:"Adult ≈ 1.5–1.8 m.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
  { questionId:"math3_ch4_es_q8", topicId:"math3_ch4_estimating", text:"Why is estimation useful?", options:[{text:"It's always exact",type:"concept_error"},{text:"To quickly check approximate sizes",type:"correct"},{text:"Replaces all measurement",type:"misinterpretation"},{text:"It's just wrong",type:"guessing"}], explanation:"Estimation is faster than measuring and gives a near-correct value.", solutionSteps:["Faster than ruler.","Good for quick checks."], shortcut:"Estimation = quick approximate.", difficulty:"easy", subject:"Mathematics", grade:"3", chapter:"Long and Short" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
  }
  console.log(`Seeded ${questions.length} Class 3 Math v2 questions (Ch3-4).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
