/**
 * Seed: CBSE Class 10 Science — Chemistry (Chapters 1–4), 60 MCQ questions
 * Chapters: Chemical Reactions (15), Acids Bases Salts (18), Metals Non-metals (15), Carbon (12)
 * Safe to re-run — skips duplicates on { questionText, subject }
 *
 * Usage:
 *   cd ai-learning-backend/backend
 *   node config/seedScienceChemistryQuestions.js
 */

import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const QUESTIONS = [

  // ══════════════════════════════════════════════════════════════════════════════
  // CHAPTER 1: Chemical Reactions and Equations (15 questions — 5E 6M 4H)
  // ══════════════════════════════════════════════════════════════════════════════

  // ── Easy (5) ─────────────────────────────────────────────────────────────────
  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Signs of Chemical Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following observations indicates that a chemical reaction has taken place?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Water boiling to form steam", type: "concept_error", logicTag: "physical_change_confused_with_chemical" },
      { text: "Formation of a white precipitate when two colourless solutions are mixed", type: "correct", logicTag: "" },
      { text: "Ice melting at room temperature", type: "concept_error", logicTag: "state_change_is_physical" },
      { text: "Salt dissolving in water", type: "concept_error", logicTag: "dissolution_is_physical_not_chemical" },
    ],
    solutionSteps: [
      "Chemical reactions are identified by signs: gas evolution, precipitate formation, colour change, temperature change, or new smell.",
      "Boiling, melting, and dissolving are physical changes — the chemical composition does not change.",
      "Formation of a precipitate (insoluble solid from two soluble solutions) indicates a new substance has formed — a chemical reaction.",
    ],
    shortcut: "Signs of chemical reaction: GPCTE — Gas, Precipitate, Colour change, Temperature change, Emission of light/smell.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Balancing Chemical Equations",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the coefficient of H₂O when the equation H₂ + O₂ → H₂O is balanced?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "1", type: "concept_error", logicTag: "unbalanced_equation_used" },
      { text: "2", type: "correct", logicTag: "" },
      { text: "3", type: "calculation_error", logicTag: "incorrect_balancing_attempt" },
      { text: "4", type: "calculation_error", logicTag: "overcounted_oxygen" },
    ],
    solutionSteps: [
      "Start with O₂ (diatomic, contributes 2 O atoms). Place 2 in front of H₂O: H₂ + O₂ → 2H₂O.",
      "Now H: 2 on left, 4 on right. Put 2 in front of H₂: 2H₂ + O₂ → 2H₂O.",
      "Check: H = 4 each side ✓, O = 2 each side ✓. Coefficient of H₂O = 2.",
    ],
    shortcut: "Balanced equation: 2H₂ + O₂ → 2H₂O. The ratio is always 2:1:2.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Types of Chemical Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Quicklime reacts vigorously with water to produce slaked lime. Which type of reaction is this?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Decomposition reaction", type: "concept_error", logicTag: "one_reactant_needed_for_decomposition" },
      { text: "Combination reaction", type: "correct", logicTag: "" },
      { text: "Double displacement reaction", type: "concept_error", logicTag: "no_partner_swap_occurs" },
      { text: "Displacement reaction", type: "concept_error", logicTag: "no_element_displacing_another" },
    ],
    solutionSteps: [
      "CaO + H₂O → Ca(OH)₂ (slaked lime). Two reactants combine to form one product.",
      "Two substances → one product = combination reaction.",
      "This reaction also releases heat (exothermic) — the vigorous hissing is due to heat produced.",
    ],
    shortcut: "Combination = 2+ reactants → 1 product. CaO + H₂O → Ca(OH)₂ is the classic CBSE example.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "State Symbols",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In a chemical equation, which state symbol is used for a substance dissolved in water?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "(s)", type: "concept_error", logicTag: "solid_symbol_confused" },
      { text: "(aq)", type: "correct", logicTag: "" },
      { text: "(l)", type: "concept_error", logicTag: "liquid_pure_substance_not_solution" },
      { text: "(g)", type: "concept_error", logicTag: "gas_symbol_confused" },
    ],
    solutionSteps: [
      "(aq) stands for 'aqueous' — meaning dissolved in water.",
      "(l) is used for a pure liquid substance (e.g., H₂O(l) = liquid water itself).",
      "(aq) is used when a substance is in solution: e.g., NaCl(aq), HCl(aq), NaOH(aq).",
    ],
    shortcut: "State symbols: (s) solid, (l) pure liquid, (g) gas, (aq) dissolved in water (aqueous).",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Types of Chemical Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The reaction between sodium sulphate and barium chloride solutions produces a white precipitate of barium sulphate. This is an example of:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Combination reaction", type: "concept_error", logicTag: "two_products_not_one" },
      { text: "Double displacement reaction", type: "correct", logicTag: "" },
      { text: "Decomposition reaction", type: "concept_error", logicTag: "two_reactants_not_one" },
      { text: "Displacement reaction", type: "concept_error", logicTag: "single_displacement_needs_element_not_compound" },
    ],
    solutionSteps: [
      "Na₂SO₄(aq) + BaCl₂(aq) → BaSO₄(s)↓ + 2NaCl(aq)",
      "Both reactants are compounds; they exchange ions (SO₄²⁻ and Cl⁻ swap partners).",
      "Partner swap between two ionic compounds = double displacement reaction.",
    ],
    shortcut: "Double displacement = two compounds swap partners → often produces precipitate or water.",
  },

  // ── Medium (6) ───────────────────────────────────────────────────────────────
  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Balancing Chemical Equations",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is the correctly balanced equation for the reaction of iron with steam?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Fe + H₂O → FeO + H₂", type: "concept_error", logicTag: "wrong_oxide_of_iron_formed" },
      { text: "3Fe + 4H₂O → Fe₃O₄ + 4H₂", type: "correct", logicTag: "" },
      { text: "2Fe + 3H₂O → Fe₂O₃ + 3H₂", type: "concept_error", logicTag: "wrong_oxide_product" },
      { text: "Fe + 2H₂O → Fe(OH)₂ + H₂", type: "concept_error", logicTag: "hydroxide_not_formed_with_steam" },
    ],
    solutionSteps: [
      "Iron reacts with steam (not cold water) to form magnetite (Fe₃O₄) and hydrogen gas.",
      "3Fe(s) + 4H₂O(g) → Fe₃O₄(s) + 4H₂(g)",
      "Verify: Fe = 3 each side, H = 8 each side, O = 4 each side. ✓",
    ],
    shortcut: "Iron + steam → Fe₃O₄ (magnetite, Fe₃O₄ has both Fe²⁺ and Fe³⁺). Not Fe₂O₃ (rust) — that forms slowly with moist air.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Types of Chemical Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the thermite reaction: Fe₂O₃ + 2Al → Al₂O₃ + 2Fe, which metal acts as the reducing agent?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Iron (Fe)", type: "concept_error", logicTag: "iron_is_being_reduced_not_reducing" },
      { text: "Aluminium (Al)", type: "correct", logicTag: "" },
      { text: "Both Fe and Al are reducing agents", type: "concept_error", logicTag: "only_one_can_be_reduced_one_oxidised" },
      { text: "Oxygen acts as the reducing agent", type: "concept_error", logicTag: "oxygen_is_typically_oxidising_agent" },
    ],
    solutionSteps: [
      "In this reaction, Al is oxidised (gains oxygen → Al₂O₃), and Fe₂O₃ is reduced (loses oxygen → Fe).",
      "The reducing agent is the substance that gets OXIDISED (it reduces something else).",
      "Al gets oxidised → Al is the reducing agent. Fe₂O₃ gets reduced → it is the oxidising agent.",
    ],
    shortcut: "Reducing agent = gets oxidised. Oxidising agent = gets reduced. In thermite, Al reduces Fe₂O₃ → Al is the reducing agent.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Exothermic and Endothermic Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following is an endothermic reaction?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Combustion of natural gas (CH₄ + O₂ → CO₂ + H₂O)", type: "concept_error", logicTag: "combustion_is_exothermic" },
      { text: "Thermal decomposition of calcium carbonate (CaCO₃ → CaO + CO₂)", type: "correct", logicTag: "" },
      { text: "Neutralisation of HCl with NaOH", type: "concept_error", logicTag: "neutralisation_releases_heat" },
      { text: "Reaction of CaO with water", type: "concept_error", logicTag: "combination_with_water_is_exothermic" },
    ],
    solutionSteps: [
      "Endothermic reactions ABSORB heat energy from the surroundings (temperature of surroundings drops, or energy must be supplied).",
      "CaCO₃ requires continuous heating to decompose — energy is absorbed, not released.",
      "Combustion, neutralisation, and CaO + H₂O all release heat (exothermic).",
    ],
    shortcut: "Endothermic = energy IN (decomposition often needs heat input). Exothermic = energy OUT (combustion, neutralisation, most combination reactions).",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Oxidation and Reduction",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the reaction: MnO₂ + 4HCl → MnCl₂ + 2H₂O + Cl₂, which substance is oxidised?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "MnO₂", type: "concept_error", logicTag: "MnO2_is_reduced_gains_electrons" },
      { text: "HCl", type: "correct", logicTag: "" },
      { text: "H₂O", type: "concept_error", logicTag: "product_cannot_be_oxidised_in_same_step" },
      { text: "Cl₂", type: "concept_error", logicTag: "Cl2_is_a_product_of_oxidation_not_oxidised_itself" },
    ],
    solutionSteps: [
      "In HCl, chlorine is in the −1 oxidation state. In the product Cl₂, chlorine is 0.",
      "Cl going from −1 to 0 means it LOSES electrons → it is oxidised.",
      "MnO₂ (Mn is +4) → MnCl₂ (Mn is +2): Mn gains electrons → MnO₂ is reduced.",
    ],
    shortcut: "Check oxidation state change: Cl: −1 in HCl → 0 in Cl₂ = increase = OXIDISED. Mn: +4 in MnO₂ → +2 in MnCl₂ = decrease = REDUCED.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Corrosion and Rancidity",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Chips manufacturers flush bags of chips with nitrogen gas before sealing. The main purpose of this is to:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Kill bacteria in the chips", type: "concept_error", logicTag: "nitrogen_is_not_antibacterial" },
      { text: "Prevent oxidation of fats (rancidity)", type: "correct", logicTag: "" },
      { text: "Keep the chips warm", type: "guessing", logicTag: "nitrogen_does_not_generate_heat" },
      { text: "Maintain pressure inside the bag", type: "partial_logic", logicTag: "pressure_maintenance_is_secondary_effect_not_main_purpose" },
    ],
    solutionSteps: [
      "Rancidity is caused by oxidation of fats and oils in the chips when exposed to oxygen.",
      "Nitrogen (N₂) is an inert gas — it displaces oxygen from the bag, preventing oxidation.",
      "With no oxygen inside, the fats cannot be oxidised, so the chips remain fresh and non-rancid.",
    ],
    shortcut: "Anti-rancidity methods: nitrogen flushing (removes O₂), antioxidants (BHA/BHT slow oxidation), refrigeration (slows reaction), vacuum packing.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Photolytic Decomposition",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Silver chloride turns grey in sunlight because:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "It absorbs water from the atmosphere", type: "concept_error", logicTag: "hygroscopic_confused_with_photolytic" },
      { text: "It undergoes photolytic decomposition to form silver metal", type: "correct", logicTag: "" },
      { text: "It reacts with oxygen in sunlight to form silver oxide", type: "concept_error", logicTag: "oxidation_confused_with_photolysis" },
      { text: "The chloride ion evaporates on heating", type: "concept_error", logicTag: "ionic_compound_does_not_evaporate_this_way" },
    ],
    solutionSteps: [
      "2AgCl(s) →(sunlight) 2Ag(s) + Cl₂(g)",
      "Sunlight provides energy to break the Ag–Cl bond. Silver metal (grey) is deposited.",
      "This is a photolytic decomposition reaction — used as the basis of black-and-white photography.",
    ],
    shortcut: "AgCl/AgBr → grey in sunlight = photolytic decomposition (silver metal forms). Classic CBSE one-liner.",
  },

  // ── Hard (4) ─────────────────────────────────────────────────────────────────
  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Balancing Chemical Equations",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the balanced equation: aAl + bFe₃O₄ → cAl₂O₃ + dFe, the values of a, b, c, d are:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "a=2, b=1, c=1, d=3", type: "concept_error", logicTag: "Fe3O4_has_4_oxygens_not_3" },
      { text: "a=8, b=3, c=4, d=9", type: "correct", logicTag: "" },
      { text: "a=4, b=1, c=2, d=3", type: "calculation_error", logicTag: "iron_count_incorrect" },
      { text: "a=6, b=2, c=3, d=6", type: "calculation_error", logicTag: "oxygen_not_balanced" },
    ],
    solutionSteps: [
      "Al + Fe₃O₄ → Al₂O₃ + Fe. Fe₃O₄ has 4 O atoms; Al₂O₃ has 3 O atoms. LCM(4,3) = 12.",
      "Need 12 O on each side: 3 Fe₃O₄ (gives 12 O) and 4 Al₂O₃ (needs 12 O). So b=3, c=4.",
      "Al: 4 Al₂O₃ has 8 Al atoms → need 8 Al on left → a=8.",
      "Fe: 3 Fe₃O₄ has 9 Fe atoms → d=9. Final: 8Al + 3Fe₃O₄ → 4Al₂O₃ + 9Fe. ✓",
    ],
    shortcut: "Multi-element balancing: balance the most complex element (O here) first using LCM method, then cascade to others.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Oxidation and Reduction",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In electrolysis of water (2H₂O → 2H₂ + O₂), which half-reaction occurs at the anode?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "2H⁺ + 2e⁻ → H₂ (reduction)", type: "concept_error", logicTag: "cathode_reaction_placed_at_anode" },
      { text: "2H₂O → O₂ + 4H⁺ + 4e⁻ (oxidation)", type: "correct", logicTag: "" },
      { text: "O₂ + 4H⁺ + 4e⁻ → 2H₂O (reduction)", type: "concept_error", logicTag: "reverse_of_correct_anode_reaction" },
      { text: "H₂O → H₂ + ½O₂ (no charge transfer)", type: "concept_error", logicTag: "overall_equation_used_instead_of_half_reaction" },
    ],
    solutionSteps: [
      "Anode is the positive electrode — OXIDATION occurs at the anode (OA: Oxidation at Anode).",
      "At anode: water is oxidised — 2H₂O → O₂ + 4H⁺ + 4e⁻ (oxygen gas evolved).",
      "At cathode: 4H⁺ + 4e⁻ → 2H₂ (hydrogen gas evolved). Volume ratio H₂:O₂ = 2:1.",
    ],
    shortcut: "OA/RC — Oxidation at Anode, Reduction at Cathode. Anode (+) = O₂ released. Cathode (−) = H₂ released.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Types of Chemical Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Magnesium ribbon burns in nitrogen gas to form magnesium nitride (Mg₃N₂). The balanced equation is:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Mg + N₂ → MgN₂", type: "concept_error", logicTag: "formula_of_magnesium_nitride_wrong" },
      { text: "3Mg + N₂ → Mg₃N₂", type: "correct", logicTag: "" },
      { text: "2Mg + N₂ → Mg₂N₂", type: "concept_error", logicTag: "incorrect_empirical_formula_for_nitride" },
      { text: "6Mg + N₂ → 3Mg₂N₂", type: "partial_logic", logicTag: "correct_ratio_but_not_simplest_balanced_form" },
    ],
    solutionSteps: [
      "Magnesium has a 2+ charge (Mg²⁺). Nitrogen has a 3− charge (N³⁻).",
      "To balance charges: need 3 Mg²⁺ for 2 N³⁻ (total charge = 6+ and 6−). Formula: Mg₃N₂.",
      "Balanced equation: 3Mg(s) + N₂(g) → Mg₃N₂(s). This is a combination reaction.",
    ],
    shortcut: "Nitride = N³⁻. Mg = Mg²⁺. Cross-multiply charges: Mg₃N₂ is the correct formula.",
  },

  {
    topic: "Chemical Reactions and Equations",
    subtopic: "Corrosion",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "An iron nail is left in each of the following setups. In which setup will rusting occur FASTEST?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Nail in dry air", type: "concept_error", logicTag: "no_moisture_slows_rusting" },
      { text: "Nail in water with dissolved salt (NaCl solution)", type: "correct", logicTag: "" },
      { text: "Nail in boiled water sealed with oil", type: "concept_error", logicTag: "dissolved_oxygen_removed_and_sealed" },
      { text: "Nail in anhydrous CaCl₂ (desiccant)", type: "concept_error", logicTag: "desiccant_removes_all_moisture" },
    ],
    solutionSteps: [
      "Rusting requires both oxygen AND moisture. Neither alone is sufficient.",
      "Salt water (NaCl solution) accelerates rusting because: (a) dissolved O₂ present, (b) moisture present, (c) NaCl increases conductivity of electrolyte, accelerating the electrochemical corrosion process.",
      "Boiled water removes dissolved O₂; dry air has no moisture; CaCl₂ removes all moisture → none of these favour fast rusting.",
    ],
    shortcut: "Rusting = O₂ + H₂O. Salt water provides both AND increases ionic conductivity → fastest corrosion. This is why ships rust faster in seawater.",
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // CHAPTER 2: Acids, Bases and Salts (18 questions — 6E 8M 4H)
  // ══════════════════════════════════════════════════════════════════════════════

  // ── Easy (6) ─────────────────────────────────────────────────────────────────
  {
    topic: "Acids, Bases and Salts",
    subtopic: "Indicators",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What colour does phenolphthalein turn in a basic solution?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Yellow", type: "concept_error", logicTag: "methyl_orange_in_base_not_phenolphthalein" },
      { text: "Pink/magenta", type: "correct", logicTag: "" },
      { text: "Red", type: "concept_error", logicTag: "phenolphthalein_red_in_acid_is_incorrect_it_is_colourless" },
      { text: "Colourless", type: "concept_error", logicTag: "phenolphthalein_is_colourless_in_acid_not_base" },
    ],
    solutionSteps: [
      "Phenolphthalein: colourless in acid/neutral, pink/magenta in base.",
      "It changes to pink when OH⁻ ions are present (pH > 8.2).",
      "It is commonly used to detect the endpoint in acid-base titrations (when base just exceeds acid).",
    ],
    shortcut: "Phenolphthalein: Pink in Base, colourless in acid. 'Pink Basic, Nothing Acidic'.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "pH Scale",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Pure water at 25°C has a pH of:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "0", type: "concept_error", logicTag: "pH_0_is_strongly_acidic" },
      { text: "7", type: "correct", logicTag: "" },
      { text: "14", type: "concept_error", logicTag: "pH_14_is_strongly_basic" },
      { text: "5.6", type: "concept_error", logicTag: "5.6_is_normal_rainwater_not_pure_water" },
    ],
    solutionSteps: [
      "Pure water dissociates equally into H⁺ and OH⁻ ions at 25°C: [H⁺] = [OH⁻] = 10⁻⁷ mol/L.",
      "When H⁺ concentration = OH⁻ concentration, the solution is neutral → pH = 7.",
      "Note: Normal rainwater has pH 5.6 (slightly acidic due to dissolved CO₂).",
    ],
    shortcut: "pH 7 = neutral (pure water). Below 7 = acidic. Above 7 = basic.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Acids and Bases",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following acids is present in ant sting?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Acetic acid", type: "concept_error", logicTag: "acetic_acid_is_in_vinegar_not_ant_sting" },
      { text: "Methanoic acid (formic acid)", type: "correct", logicTag: "" },
      { text: "Citric acid", type: "concept_error", logicTag: "citric_acid_is_in_citrus_fruits" },
      { text: "Lactic acid", type: "concept_error", logicTag: "lactic_acid_is_in_curd_and_muscles" },
    ],
    solutionSteps: [
      "Ant sting and bee sting contain methanoic acid (formic acid, HCOOH).",
      "The burning sensation of an ant bite is due to formic acid injected under the skin.",
      "Remedy: applying baking soda (NaHCO₃, a mild base) neutralises the acid and relieves pain.",
    ],
    shortcut: "Natural acid sources: ant sting = formic acid (HCOOH). Vinegar = acetic acid. Lemon = citric acid. Curd = lactic acid. Stomach = HCl.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Neutralisation",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "When an acid reacts with a base, the products are always:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Salt and carbon dioxide", type: "concept_error", logicTag: "CO2_is_from_carbonate_reaction_not_neutralisation" },
      { text: "Salt and water", type: "correct", logicTag: "" },
      { text: "Salt and hydrogen gas", type: "concept_error", logicTag: "H2_is_from_metal_acid_reaction_not_neutralisation" },
      { text: "Metal oxide and water", type: "concept_error", logicTag: "reversed_reactants_and_products" },
    ],
    solutionSteps: [
      "Neutralisation: Acid + Base → Salt + Water.",
      "The H⁺ from the acid combines with OH⁻ from the base to form water: H⁺ + OH⁻ → H₂O.",
      "The remaining ions form the salt: Na⁺ + Cl⁻ → NaCl.",
    ],
    shortcut: "Neutralisation always gives SALT + WATER. The name of the salt depends on the acid (HCl→chloride, H₂SO₄→sulphate) and the base (NaOH→sodium, Ca(OH)₂→calcium).",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Important Salts",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Baking soda (NaHCO₃) is used in cooking because when heated it:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Releases SO₂ gas which makes the batter rise", type: "concept_error", logicTag: "SO2_is_from_decomposition_of_sulphur_compounds" },
      { text: "Releases CO₂ gas which makes the batter rise", type: "correct", logicTag: "" },
      { text: "Releases H₂ gas which makes the batter rise", type: "concept_error", logicTag: "H2_is_not_produced_by_NaHCO3_decomposition" },
      { text: "Absorbs moisture making the dough stiffer", type: "concept_error", logicTag: "opposite_effect_described" },
    ],
    solutionSteps: [
      "2NaHCO₃ →(heat) Na₂CO₃ + H₂O + CO₂↑",
      "The CO₂ gas released expands and forms bubbles in the batter, making it porous and fluffy.",
      "This is why cakes, breads, and dhokla use baking soda as a leavening agent.",
    ],
    shortcut: "NaHCO₃ + heat → Na₂CO₃ + H₂O + CO₂. CO₂ = leavening agent (makes dough rise).",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Chlor-alkali Process",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the chlor-alkali process, which gas is produced at the cathode?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Chlorine (Cl₂)", type: "concept_error", logicTag: "Cl2_is_produced_at_anode" },
      { text: "Hydrogen (H₂)", type: "correct", logicTag: "" },
      { text: "Oxygen (O₂)", type: "concept_error", logicTag: "O2_is_not_a_product_in_chlor-alkali" },
      { text: "Carbon dioxide (CO₂)", type: "concept_error", logicTag: "no_carbon_in_brine_electrolysis" },
    ],
    solutionSteps: [
      "Chlor-alkali: 2NaCl(aq) + 2H₂O(l) → Cl₂(g) + H₂(g) + 2NaOH(aq).",
      "At cathode (−): 2H⁺ + 2e⁻ → H₂ (reduction, hydrogen gas).",
      "At anode (+): 2Cl⁻ → Cl₂ + 2e⁻ (oxidation, chlorine gas).",
    ],
    shortcut: "Cathode = H₂ (negative electrode, reduction). Anode = Cl₂ (positive electrode, oxidation). NaOH forms in solution.",
  },

  // ── Medium (8) ───────────────────────────────────────────────────────────────
  {
    topic: "Acids, Bases and Salts",
    subtopic: "pH Scale",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A solution has a pH of 2. When diluted with water, the pH becomes 4. The H⁺ ion concentration has changed by a factor of:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Decreased by a factor of 2", type: "concept_error", logicTag: "linear_not_logarithmic_thinking" },
      { text: "Decreased by a factor of 100", type: "correct", logicTag: "" },
      { text: "Increased by a factor of 2", type: "concept_error", logicTag: "dilution_increases_pH_decreases_H_concentration" },
      { text: "Decreased by a factor of 10", type: "calculation_error", logicTag: "one_pH_unit_change_not_two" },
    ],
    solutionSteps: [
      "pH changes from 2 to 4 — a change of 2 units.",
      "Each pH unit represents a 10-fold change in H⁺ concentration.",
      "2 pH units = 10² = 100-fold change. Since pH increased, H⁺ concentration DECREASED by factor of 100.",
    ],
    shortcut: "ΔpH = 2 → H⁺ concentration changes by 10² = 100 times. pH increased → diluted → less acidic → H⁺ decreased.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Reactions of Acids",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the gas evolved when dilute sulphuric acid reacts with sodium carbonate?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Hydrogen (H₂)", type: "concept_error", logicTag: "H2_from_acid_plus_metal_not_carbonate" },
      { text: "Carbon dioxide (CO₂)", type: "correct", logicTag: "" },
      { text: "Sulphur dioxide (SO₂)", type: "concept_error", logicTag: "SO2_from_decomposition_of_sulphates_not_this_reaction" },
      { text: "Oxygen (O₂)", type: "concept_error", logicTag: "no_reaction_produces_O2_here" },
    ],
    solutionSteps: [
      "Na₂CO₃ + H₂SO₄ → Na₂SO₄ + H₂O + CO₂↑",
      "The CO₃²⁻ ion reacts with H⁺ ions: CO₃²⁻ + 2H⁺ → H₂O + CO₂.",
      "Test: CO₂ turns lime water (Ca(OH)₂ solution) milky → CaCO₃ precipitate forms.",
    ],
    shortcut: "Carbonate + acid → Salt + H₂O + CO₂. Always CO₂ (milky lime water test). Never H₂ (that's metal + acid).",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Hard Water",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Washing soda (Na₂CO₃) is used to soften hard water because it:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Dissolves the Mg²⁺ and Ca²⁺ ions by forming soluble salts", type: "concept_error", logicTag: "carbonate_salts_of_Ca_Mg_are_insoluble_not_soluble" },
      { text: "Precipitates Ca²⁺ and Mg²⁺ as insoluble carbonates, removing them from solution", type: "correct", logicTag: "" },
      { text: "Neutralises the hardness by making water acidic", type: "concept_error", logicTag: "Na2CO3_is_basic_not_acidic" },
      { text: "Replaces Ca²⁺ and Mg²⁺ with Na⁺ by ionic exchange", type: "partial_logic", logicTag: "ion_exchange_is_another_method_not_the_washing_soda_mechanism" },
    ],
    solutionSteps: [
      "Hard water contains dissolved Ca²⁺ and Mg²⁺ salts (sulphates, chlorides, bicarbonates).",
      "Na₂CO₃ provides CO₃²⁻ ions: Ca²⁺ + CO₃²⁻ → CaCO₃↓ (insoluble precipitate).",
      "Removing Ca²⁺ and Mg²⁺ by precipitation softens the water (reduces hardness).",
    ],
    shortcut: "Na₂CO₃ + hard water: CO₃²⁻ grabs Ca²⁺/Mg²⁺ → insoluble CaCO₃/MgCO₃ precipitates out → water softened.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Important Salts",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Plaster of Paris (CaSO₄·½H₂O) sets hard when mixed with water because:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "It undergoes decomposition to form CaO and SO₃", type: "concept_error", logicTag: "decomposition_requires_heat_not_water_addition" },
      { text: "It rehydrates to form gypsum (CaSO₄·2H₂O), a rigid crystalline solid", type: "correct", logicTag: "" },
      { text: "It reacts with CO₂ in air to form CaCO₃", type: "concept_error", logicTag: "CaCO3_formation_is_for_slaked_lime_not_POP" },
      { text: "Water evaporates quickly, leaving a compact dry layer", type: "concept_error", logicTag: "purely_physical_explanation_misses_chemical_change" },
    ],
    solutionSteps: [
      "CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O (gypsum)",
      "The half-hydrate absorbs water to become dihydrate (gypsum), which is a hard crystalline solid.",
      "This chemical change (not just drying) makes POP expand slightly and harden rapidly — useful for casts and moulds.",
    ],
    shortcut: "POP sets = absorbs water → gypsum (2H₂O). Remember: reverse of how POP was made (gypsum was heated to remove water).",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Reactions of Bases",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A student adds dilute HCl to a solution of NaOH until the solution turns neutral. Which ion is formed when H⁺ and OH⁻ combine?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.45,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Na⁺", type: "concept_error", logicTag: "Na_is_from_NaOH_not_from_H_OH_combination" },
      { text: "H₂O (water molecule, not an ion)", type: "correct", logicTag: "" },
      { text: "H₂O₂", type: "concept_error", logicTag: "hydrogen_peroxide_is_different_compound" },
      { text: "OH₂⁺", type: "concept_error", logicTag: "not_a_real_ionic_species_in_this_context" },
    ],
    solutionSteps: [
      "Neutralisation ionic equation: H⁺(aq) + OH⁻(aq) → H₂O(l)",
      "One proton (H⁺) combines with one hydroxide ion (OH⁻) to form one water molecule.",
      "Water is a molecule, not an ion. The Na⁺ and Cl⁻ ions remain in solution as NaCl (salt).",
    ],
    shortcut: "H⁺ + OH⁻ → H₂O. This is always the net ionic equation of any neutralisation.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "pH and Everyday Life",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Tooth enamel starts to dissolve when the pH of the mouth falls below 5.5. This is because enamel is mainly composed of calcium phosphate, which is:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "An acid that reacts with the basic bacteria", type: "concept_error", logicTag: "enamel_is_basic_not_acidic" },
      { text: "A basic substance that reacts with acid (H⁺ ions) and dissolves", type: "correct", logicTag: "" },
      { text: "A neutral salt that is soluble at all pH values", type: "concept_error", logicTag: "calcium_phosphate_is_insoluble_in_neutral_conditions" },
      { text: "An acidic substance that dissolves in basic conditions", type: "concept_error", logicTag: "opposite_of_correct_chemistry" },
    ],
    solutionSteps: [
      "Calcium phosphate Ca₃(PO₄)₂ is the main mineral in tooth enamel.",
      "Phosphate (PO₄³⁻) is a basic ion. When acids lower pH below 5.5, H⁺ ions react with PO₄³⁻ to form soluble hydrogen phosphate.",
      "This dissolves the enamel — hence tooth decay (dental caries). Toothpaste is mildly basic (pH ~8) to neutralise mouth acids.",
    ],
    shortcut: "Enamel = basic (Ca₃(PO₄)₂). Acids from bacteria (sugar fermentation) dissolve it. Prevention: toothpaste (base), less sugar, rinsing with water.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Bleaching Powder",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Bleaching powder is prepared by passing chlorine gas over:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Dry calcium carbonate (CaCO₃)", type: "concept_error", logicTag: "CaCO3_does_not_react_with_Cl2_this_way" },
      { text: "Dry slaked lime (Ca(OH)₂)", type: "correct", logicTag: "" },
      { text: "Quicklime (CaO)", type: "concept_error", logicTag: "quicklime_is_anhydrous_must_use_slaked_lime" },
      { text: "Calcium chloride (CaCl₂)", type: "concept_error", logicTag: "already_chlorinated_no_reaction" },
    ],
    solutionSteps: [
      "Ca(OH)₂ + Cl₂ → CaOCl₂ + H₂O",
      "Dry slaked lime (Ca(OH)₂) reacts with chlorine gas to form calcium oxychloride (CaOCl₂) — bleaching powder.",
      "It is kept dry because moisture causes the Cl₂ to be released (the bleaching action).",
    ],
    shortcut: "Bleaching powder = Ca(OH)₂ + Cl₂ → CaOCl₂. Formula CaOCl₂ = Ca(OCl)Cl = one Cl bonded to O, one directly to Ca.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "pH Scale",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The pH of gastric juice in the stomach is approximately 1.5. This is due to the presence of:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Dilute sulphuric acid (H₂SO₄)", type: "concept_error", logicTag: "H2SO4_is_not_naturally_secreted_in_stomach" },
      { text: "Dilute hydrochloric acid (HCl)", type: "correct", logicTag: "" },
      { text: "Citric acid", type: "concept_error", logicTag: "citric_acid_is_in_fruits_not_stomach" },
      { text: "Carbonic acid (H₂CO₃)", type: "concept_error", logicTag: "H2CO3_is_in_fizzy_drinks_not_stomach_acid" },
    ],
    solutionSteps: [
      "Parietal cells of the stomach secrete hydrochloric acid (HCl) into the gastric juice.",
      "HCl (pH 1.5–2) activates the enzyme pepsin and kills ingested bacteria.",
      "Excess HCl causes acidity/indigestion — treated with antacids (Mg(OH)₂, NaHCO₃) which neutralise the acid.",
    ],
    shortcut: "Stomach acid = HCl (not H₂SO₄ — that would permanently damage tissue). pH 1.5 = very acidic. Antacid = base to neutralise excess HCl.",
  },

  // ── Hard (4) ─────────────────────────────────────────────────────────────────
  {
    topic: "Acids, Bases and Salts",
    subtopic: "pH Scale",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Equal volumes of 0.1 M HCl and 0.1 M NaOH are mixed. The pH of the resulting solution is:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Less than 7 (acidic)", type: "concept_error", logicTag: "equal_moles_cancel_completely" },
      { text: "7 (neutral)", type: "correct", logicTag: "" },
      { text: "Greater than 7 (basic)", type: "concept_error", logicTag: "no_excess_base_present" },
      { text: "Depends on the temperature", type: "partial_logic", logicTag: "temperature_affects_Kw_but_neutral_pH_at_25C_is_still_7" },
    ],
    solutionSteps: [
      "Moles HCl = Moles NaOH (equal volume, equal molarity).",
      "HCl + NaOH → NaCl + H₂O. All acid is neutralised by all base.",
      "NaCl is a salt of strong acid + strong base → solution is neutral → pH = 7.",
    ],
    shortcut: "Equal moles of strong acid + strong base → complete neutralisation → pH 7. NaCl solution is always neutral.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Reactions of Acids",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "When zinc reacts with dilute H₂SO₄, the gas collected is tested with a burning splint held at the mouth of the test tube. The observation is:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "The gas burns with a blue flame continuously", type: "concept_error", logicTag: "blue_continuous_flame_is_methane_not_H2" },
      { text: "The gas burns with a 'pop' sound", type: "correct", logicTag: "" },
      { text: "The splint relights (glowing splint test)", type: "concept_error", logicTag: "relights_splint_tests_for_O2_not_H2" },
      { text: "The gas turns lime water milky", type: "concept_error", logicTag: "lime_water_test_is_for_CO2_not_H2" },
    ],
    solutionSteps: [
      "Zn + H₂SO₄ → ZnSO₄ + H₂↑",
      "Hydrogen gas (H₂) burns explosively — when ignited at the mouth of a test tube, it makes a 'pop' sound.",
      "This 'pop test' is the standard test for H₂. Do not confuse with O₂ (relights glowing splint) or CO₂ (lime water milky).",
    ],
    shortcut: "H₂ test = POP sound (burning splint). O₂ test = relights glowing splint. CO₂ test = lime water turns milky.",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Washing Soda and Baking Soda",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The chemical formula of washing soda is Na₂CO₃·10H₂O. When strongly heated, it forms Na₂CO₃. This change is an example of:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Decomposition followed by combination", type: "concept_error", logicTag: "only_dehydration_occurs_not_combination" },
      { text: "Loss of water of crystallisation (efflorescence)", type: "correct", logicTag: "" },
      { text: "Sublimation", type: "concept_error", logicTag: "sublimation_is_direct_solid_to_gas_transition" },
      { text: "Hydrolysis", type: "concept_error", logicTag: "hydrolysis_involves_water_addition_not_removal" },
    ],
    solutionSteps: [
      "Na₂CO₃·10H₂O →(heat) Na₂CO₃ + 10H₂O. The 10 water molecules are water of crystallisation.",
      "Efflorescence: loss of water of crystallisation on heating or exposure to dry air → compound loses its crystalline form.",
      "The reverse (Na₂CO₃ absorbing moisture from air) is called deliquescence.",
    ],
    shortcut: "Efflorescence = loses water of crystallisation (washing soda). Deliquescence = gains water from air (CaCl₂, NaOH pellets).",
  },

  {
    topic: "Acids, Bases and Salts",
    subtopic: "Olfactory Indicators",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Onion can be used as an olfactory indicator. In which medium does onion lose its characteristic smell?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Acidic medium", type: "concept_error", logicTag: "onion_retains_smell_in_acid" },
      { text: "Basic medium", type: "correct", logicTag: "" },
      { text: "Both acidic and basic medium", type: "concept_error", logicTag: "only_base_destroys_the_smell_compound" },
      { text: "Only neutral medium (pure water)", type: "concept_error", logicTag: "smell_is_present_in_neutral_medium" },
    ],
    solutionSteps: [
      "Olfactory indicators work by the presence/absence of smell rather than colour change.",
      "Onion has allicin and sulphur compounds responsible for its smell. These are destroyed by bases (OH⁻ ions).",
      "In acid: onion retains its pungent smell. In base: the smell-producing compounds are broken down → no smell.",
    ],
    shortcut: "Olfactory indicators: onion and vanilla LOSE smell in BASE. Clove oil loses smell in both acid and base (less useful). Turmeric turns red in base.",
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // CHAPTER 3: Metals and Non-metals (15 questions — 5E 6M 4H)
  // ══════════════════════════════════════════════════════════════════════════════

  // ── Easy (5) ─────────────────────────────────────────────────────────────────
  {
    topic: "Metals and Non-metals",
    subtopic: "Physical Properties",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following metals is a liquid at room temperature?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Copper", type: "concept_error", logicTag: "copper_is_solid_at_room_temp" },
      { text: "Mercury", type: "correct", logicTag: "" },
      { text: "Gold", type: "concept_error", logicTag: "gold_solid_melts_at_1064C" },
      { text: "Lead", type: "concept_error", logicTag: "lead_solid_melts_at_327C" },
    ],
    solutionSteps: [
      "Mercury (Hg) is the only metal that is a liquid at room temperature (melting point = −39°C).",
      "All other commonly encountered metals are solids at room temperature.",
      "Mercury is used in thermometers, barometers, and some electrical switches.",
    ],
    shortcut: "Mercury = only liquid metal at room temperature. Gallium is a solid but melts in your hand (~29°C).",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Physical Properties",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which non-metal is a good conductor of electricity?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Sulphur", type: "concept_error", logicTag: "sulphur_is_insulator" },
      { text: "Graphite", type: "correct", logicTag: "" },
      { text: "Phosphorus", type: "concept_error", logicTag: "phosphorus_is_poor_conductor" },
      { text: "Iodine", type: "concept_error", logicTag: "iodine_is_lustrous_but_not_a_conductor" },
    ],
    solutionSteps: [
      "Graphite is an allotrope of carbon (a non-metal). Each carbon forms 3 bonds in layers, leaving one delocalized electron per atom.",
      "These free electrons allow graphite to conduct electricity — unlike other non-metals.",
      "Graphite is used as electrodes in electrolytic cells and in dry-cell batteries (carbon rod).",
    ],
    shortcut: "Graphite = non-metal conductor (exception). Diamond = non-metal insulator (carbon with 4 bonds, no free electrons).",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Reactivity Series",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following metals can be stored under kerosene?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Gold", type: "concept_error", logicTag: "gold_is_least_reactive_needs_no_storage_precaution" },
      { text: "Sodium", type: "correct", logicTag: "" },
      { text: "Copper", type: "concept_error", logicTag: "copper_does_not_react_with_air_or_water_at_room_temp_rapidly" },
      { text: "Iron", type: "concept_error", logicTag: "iron_rusts_slowly_not_explosively" },
    ],
    solutionSteps: [
      "Sodium (Na) is extremely reactive — it reacts vigorously with water and catches fire in air.",
      "Kerosene is a non-polar liquid that does not react with Na and prevents contact with air and moisture.",
      "Potassium (K) is even more reactive — it is also stored in kerosene.",
    ],
    shortcut: "Na and K stored in kerosene (most reactive metals, react explosively with water/air). Phosphorus stored in water (catches fire in air).",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Ionic Compounds",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Ionic compounds generally have high melting points because:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "They are covalently bonded with strong sigma bonds", type: "concept_error", logicTag: "ionic_not_covalent" },
      { text: "Strong electrostatic forces of attraction between oppositely charged ions require large energy to overcome", type: "correct", logicTag: "" },
      { text: "They have very low molecular mass", type: "concept_error", logicTag: "low_mass_usually_lowers_melting_point" },
      { text: "They contain water of crystallisation which stabilises the lattice", type: "concept_error", logicTag: "anhydrous_ionic_compounds_also_have_high_MP" },
    ],
    solutionSteps: [
      "Ionic compounds form a crystal lattice — each ion is surrounded by many oppositely charged ions.",
      "The electrostatic (Coulombic) attraction between positive and negative ions is very strong.",
      "To melt the solid, all these strong attractions must be overcome → requires very high temperature (high melting point).",
    ],
    shortcut: "High MP of ionic compounds = strong electrostatic attraction in the lattice. More charge → higher MP (MgO has higher MP than NaCl because Mg²⁺/O²⁻ have higher charges than Na⁺/Cl⁻).",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Extraction of Metals",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Galvanising is the process of coating iron with:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Gold", type: "concept_error", logicTag: "coating_with_gold_is_gilding_not_galvanising" },
      { text: "Zinc", type: "correct", logicTag: "" },
      { text: "Tin", type: "concept_error", logicTag: "tin_plating_is_tinning_used_for_food_cans" },
      { text: "Silver", type: "concept_error", logicTag: "silver_coating_is_electroplating_not_galvanising" },
    ],
    solutionSteps: [
      "Galvanising = coating iron/steel with a thin layer of zinc (Zn) to prevent rusting.",
      "Zinc acts as a sacrificial anode — even if the zinc layer is scratched, Zn preferentially oxidises (being higher in reactivity series) and protects the iron beneath.",
      "Used for: galvanised iron sheets, corrugated roofing, buckets, nuts and bolts.",
    ],
    shortcut: "Galvanising = Zinc coating on iron. Zinc is sacrificial (higher reactivity) → protects iron from rusting.",
  },

  // ── Medium (6) ───────────────────────────────────────────────────────────────
  {
    topic: "Metals and Non-metals",
    subtopic: "Reactivity Series",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which of the following pairs of metals and solutions will result in a displacement reaction?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Copper metal in zinc sulphate solution", type: "concept_error", logicTag: "Cu_is_below_Zn_cannot_displace_it" },
      { text: "Silver metal in copper sulphate solution", type: "concept_error", logicTag: "Ag_is_below_Cu_cannot_displace_it" },
      { text: "Aluminium metal in iron(III) sulphate solution", type: "correct", logicTag: "" },
      { text: "Gold metal in silver nitrate solution", type: "concept_error", logicTag: "Au_is_below_Ag_cannot_displace_it" },
    ],
    solutionSteps: [
      "For displacement: the reacting metal must be ABOVE the metal in the salt solution in the reactivity series.",
      "Reactivity series: K>Na>Ca>Mg>Al>Zn>Fe>Pb>H>Cu>Hg>Ag>Au.",
      "Al is above Fe → Al CAN displace Fe from Fe₂(SO₄)₃ solution. 2Al + Fe₂(SO₄)₃ → Al₂(SO₄)₃ + 2Fe.",
    ],
    shortcut: "Displacement happens only when reacting metal is HIGHER in reactivity series than the metal in solution.",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Alloys",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Stainless steel is an alloy of iron. Which elements are added to iron to make stainless steel?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Copper and zinc", type: "concept_error", logicTag: "Cu_Zn_makes_brass_not_stainless_steel" },
      { text: "Chromium, nickel, and carbon", type: "correct", logicTag: "" },
      { text: "Aluminium and manganese only", type: "concept_error", logicTag: "Al_Mn_is_duralumin_not_stainless_steel" },
      { text: "Lead and tin", type: "concept_error", logicTag: "Pb_Sn_makes_solder_not_stainless_steel" },
    ],
    solutionSteps: [
      "Stainless steel: Fe + Cr (~18%) + Ni (~8%) + C (~0.2%).",
      "Chromium forms a passive Cr₂O₃ layer on the surface that prevents further oxidation (corrosion resistance).",
      "Nickel adds toughness and shine. Carbon hardens the steel.",
    ],
    shortcut: "Stainless steel = Fe + Cr + Ni + C. 'Iron Chrome Nicely Cleans' → doesn't rust. Brass = Cu+Zn. Bronze = Cu+Sn. Solder = Pb+Sn.",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Extraction of Metals",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the extraction of aluminium by electrolysis of molten Al₂O₃, why is cryolite (Na₃AlF₆) added?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.55,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "To increase the electrical conductivity of aluminium", type: "concept_error", logicTag: "cryolite_affects_electrolyte_not_Al_product" },
      { text: "To lower the melting point of Al₂O₃ and reduce energy cost", type: "correct", logicTag: "" },
      { text: "To act as an oxidising agent in the process", type: "concept_error", logicTag: "cryolite_is_not_an_oxidising_agent_here" },
      { text: "To prevent aluminium from reacting with the electrodes", type: "concept_error", logicTag: "electrode_material_not_cryolite_handles_that" },
    ],
    solutionSteps: [
      "Al₂O₃ has a very high melting point (~2072°C). Melting it would require enormous energy.",
      "Cryolite (Na₃AlF₆) dissolves Al₂O₃ and lowers the melting point to ~960°C, greatly reducing energy costs.",
      "The molten mixture is then electrolysed: Al³⁺ + 3e⁻ → Al at cathode; O²⁻ → O₂ at anode.",
    ],
    shortcut: "Cryolite: a flux that lowers Al₂O₃ melting point (2072°C → ~960°C). Energy cost drops hugely. Same principle as adding salt to ice.",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Ionic Bonding",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "An ionic compound conducts electricity when dissolved in water but not in solid state. The correct reason is:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Dissolving changes the ionic compound into a covalent compound", type: "concept_error", logicTag: "ionic_compounds_remain_ionic_in_solution" },
      { text: "In solution, ions are free to move and carry charge; in solid state they are fixed in lattice positions", type: "correct", logicTag: "" },
      { text: "Water itself conducts electricity and the ionic compound acts as a catalyst", type: "concept_error", logicTag: "pure_water_is_a_poor_conductor" },
      { text: "The lattice breaks down completely when dissolved, releasing electrons", type: "concept_error", logicTag: "ionic_compounds_release_ions_not_free_electrons" },
    ],
    solutionSteps: [
      "Electrical conduction requires mobile charged particles (ions or electrons).",
      "Solid ionic compound: ions are locked in fixed lattice positions → cannot move → no conduction.",
      "Dissolved/molten ionic compound: ions are free to drift towards oppositely charged electrodes → conduction occurs.",
    ],
    shortcut: "Conduction needs MOBILE charges. Solid lattice = fixed ions = no conduction. Dissolved/molten = free ions = conducts. Metals conduct via free electrons (not ions).",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Corrosion Prevention",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The green layer formed on the surface of copper vessels is due to the formation of:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Copper(II) oxide (CuO)", type: "concept_error", logicTag: "CuO_is_black_not_green" },
      { text: "Basic copper carbonate (CuCO₃·Cu(OH)₂)", type: "correct", logicTag: "" },
      { text: "Copper sulphate (CuSO₄)", type: "concept_error", logicTag: "CuSO4_is_blue_in_solution_not_green_patina" },
      { text: "Copper chloride (CuCl₂)", type: "concept_error", logicTag: "CuCl2_forms_in_specific_conditions_not_general_atmospheric" },
    ],
    solutionSteps: [
      "Copper slowly reacts with CO₂, H₂O, and O₂ in the atmosphere.",
      "Product: basic copper carbonate CuCO₃·Cu(OH)₂ — this is the green patina (verdigris).",
      "Same green colour on the Statue of Liberty (copper exterior). The patina protects copper from further corrosion.",
    ],
    shortcut: "Iron → red/brown rust (Fe₂O₃·xH₂O). Copper → green patina (CuCO₃·Cu(OH)₂). Silver → black tarnish (Ag₂S). Aluminium → protective white Al₂O₃ film.",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Reactivity Series",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Magnesium reacts vigorously with hot water but not with cold water. Which product is formed with hot water?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Magnesium oxide and hydrogen", type: "concept_error", logicTag: "MgO_from_steam_not_hot_water" },
      { text: "Magnesium hydroxide and hydrogen", type: "correct", logicTag: "" },
      { text: "Magnesium chloride and oxygen", type: "concept_error", logicTag: "no_chlorine_present_in_reaction" },
      { text: "Magnesium carbonate and steam", type: "concept_error", logicTag: "no_carbon_source_in_reaction" },
    ],
    solutionSteps: [
      "Mg + 2H₂O(hot) → Mg(OH)₂ + H₂↑",
      "Magnesium hydroxide (white precipitate) and hydrogen gas are formed.",
      "With steam: Mg + H₂O(g) → MgO + H₂↑ (magnesium oxide forms instead of hydroxide).",
    ],
    shortcut: "Mg + hot water → Mg(OH)₂ + H₂. Mg + steam → MgO + H₂. Na/K react with cold water: Na + H₂O → NaOH + ½H₂.",
  },

  // ── Hard (4) ─────────────────────────────────────────────────────────────────
  {
    topic: "Metals and Non-metals",
    subtopic: "Electrolytic Refining",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "During electrolytic refining of copper, the anode mud contains:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Pure copper deposited from solution", type: "concept_error", logicTag: "pure_copper_deposits_at_cathode_not_anode" },
      { text: "Noble metal impurities like gold and silver that do not dissolve", type: "correct", logicTag: "" },
      { text: "CuSO₄ electrolyte that crystallises out", type: "concept_error", logicTag: "electrolyte_stays_in_solution" },
      { text: "Copper(II) oxide formed by oxidation at the anode", type: "concept_error", logicTag: "Cu_dissolves_as_Cu2+_not_CuO_at_anode" },
    ],
    solutionSteps: [
      "At the anode (impure copper): Cu → Cu²⁺ + 2e⁻. Active metals (Zn, Fe, Ni) also dissolve.",
      "Noble metals (Au, Ag, Pt) are LESS reactive than Cu and do NOT dissolve electrochemically.",
      "These noble metal impurities remain as solid deposits below the anode = anode mud (valuable byproduct for recovering gold/silver).",
    ],
    shortcut: "Anode mud = noble metals (Au, Ag, Pt) that didn't dissolve. Valuable — gold and silver are recovered from anode mud commercially.",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Reactivity Series",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Why cannot sodium be extracted from sodium chloride by reduction with carbon?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Carbon reacts with chlorine to form carbon tetrachloride, not with sodium", type: "concept_error", logicTag: "side_reaction_irrelevant_to_main_argument" },
      { text: "Sodium is more reactive than carbon, so carbon cannot reduce Na⁺ ions", type: "correct", logicTag: "" },
      { text: "Carbon is too expensive to use for sodium extraction", type: "concept_error", logicTag: "economic_argument_not_the_chemical_reason" },
      { text: "NaCl does not react with carbon at any temperature", type: "concept_error", logicTag: "partially_true_but_wrong_fundamental_reason" },
    ],
    solutionSteps: [
      "Carbon can only reduce metal oxides/chlorides if carbon is MORE reactive than the metal.",
      "Reactivity series: Na is ABOVE carbon (Na > Mg > Al > C > Zn > Fe).",
      "Since Na is more reactive than C, Na would not be displaced by carbon. Electrolysis of molten NaCl is used instead.",
    ],
    shortcut: "Extraction rule: use carbon only for metals BELOW carbon in reactivity. Na, Mg, Al, Ca are above carbon → must use electrolysis.",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Physical Properties",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "When a copper wire is stretched, it does not break easily but forms a thin wire. When a piece of sulphur is struck with a hammer, it shatters. This difference is due to:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Copper being denser than sulphur", type: "concept_error", logicTag: "density_does_not_explain_ductility" },
      { text: "Copper being ductile (metallic bonding allows layers to slide) while sulphur is brittle (covalent/molecular solid)", type: "correct", logicTag: "" },
      { text: "Sulphur having a higher melting point than copper", type: "concept_error", logicTag: "sulphur_has_lower_mp_than_copper" },
      { text: "Copper having more valence electrons than sulphur", type: "partial_logic", logicTag: "number_of_valence_electrons_not_the_direct_explanation" },
    ],
    solutionSteps: [
      "Copper has metallic bonding: sea of electrons allows metal atom layers to slide past each other under stress → ductile.",
      "Sulphur is a non-metal with covalent bonding within S₈ rings and weak van der Waals forces between them → brittle, shatters under stress.",
      "Ductility is a property of metals due to metallic bonding. Brittleness is typical of non-metals and ionic compounds.",
    ],
    shortcut: "Metal ductility = metallic bonding (electron sea). Non-metal brittleness = covalent/van der Waals (no sea of electrons). 'Metals bend and stretch; non-metals break'.",
  },

  {
    topic: "Metals and Non-metals",
    subtopic: "Ionic Bonding",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the formation of aluminium oxide (Al₂O₃), what is the ratio of aluminium ions to oxide ions?",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "1:1", type: "concept_error", logicTag: "ignores_charge_balance" },
      { text: "2:3", type: "correct", logicTag: "" },
      { text: "3:2", type: "concept_error", logicTag: "inverted_ratio" },
      { text: "1:2", type: "concept_error", logicTag: "uses_wrong_charge_for_aluminium" },
    ],
    solutionSteps: [
      "Al forms Al³⁺ (loses 3 electrons). O forms O²⁻ (gains 2 electrons).",
      "For electrical neutrality: total positive charge = total negative charge.",
      "2 Al³⁺ gives 6+ charge. 3 O²⁻ gives 6− charge. 6+ = 6− → balanced. Formula: Al₂O₃. Ratio Al:O = 2:3.",
    ],
    shortcut: "Charge cross-multiply: Al³⁺ and O²⁻ → take 2 Al and 3 O → Al₂O₃. '2:3 is the ionic ratio for aluminium oxide'.",
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // CHAPTER 4: Carbon and its Compounds (12 questions — 4E 5M 3H)
  // ══════════════════════════════════════════════════════════════════════════════

  // ── Easy (4) ─────────────────────────────────────────────────────────────────
  {
    topic: "Carbon and its Compounds",
    subtopic: "Homologous Series",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The general formula of alkenes is:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "CₙH₂ₙ₊₂", type: "concept_error", logicTag: "alkane_formula_not_alkene" },
      { text: "CₙH₂ₙ", type: "correct", logicTag: "" },
      { text: "CₙH₂ₙ₋₂", type: "concept_error", logicTag: "alkyne_formula_not_alkene" },
      { text: "CₙHₙ", type: "concept_error", logicTag: "incorrect_formula_does_not_represent_any_homologous_series" },
    ],
    solutionSteps: [
      "Alkenes have one C=C double bond, which means 2 fewer H atoms than alkanes (CₙH₂ₙ₊₂ − 2 = CₙH₂ₙ).",
      "Example: ethene C₂H₄ (n=2, 2×2=4 ✓), propene C₃H₆ (n=3, 2×3=6 ✓).",
      "Alkanes: CₙH₂ₙ₊₂. Alkenes: CₙH₂ₙ. Alkynes: CₙH₂ₙ₋₂.",
    ],
    shortcut: "Formula pattern: +2 for alkanes, flat for alkenes, -2 for alkynes. Each double/triple bond removes 2 H atoms.",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "Functional Groups",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Which functional group is present in ethanol?",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "–COOH (carboxyl group)", type: "concept_error", logicTag: "carboxyl_is_in_acids_not_alcohols" },
      { text: "–OH (hydroxyl group)", type: "correct", logicTag: "" },
      { text: "–CHO (aldehyde group)", type: "concept_error", logicTag: "aldehyde_is_different_functional_group" },
      { text: "–NH₂ (amino group)", type: "concept_error", logicTag: "amino_group_is_in_amines_not_alcohols" },
    ],
    solutionSteps: [
      "Ethanol: CH₃CH₂OH or C₂H₅OH. The –OH group is the hydroxyl group.",
      "The –OH group is the functional group that classifies a compound as an alcohol.",
      "Different functional groups: –OH = alcohol, –COOH = carboxylic acid, –CHO = aldehyde, –CO– = ketone.",
    ],
    shortcut: "–OH = alcohol (ethanol). –COOH = acid (ethanoic acid). The suffix '-ol' in IUPAC names indicates –OH group.",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "Combustion",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "When ethanol burns completely in air, the products are:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Carbon and water", type: "concept_error", logicTag: "carbon_soot_is_from_incomplete_combustion" },
      { text: "Carbon dioxide and water", type: "correct", logicTag: "" },
      { text: "Carbon monoxide and hydrogen", type: "concept_error", logicTag: "incomplete_combustion_products" },
      { text: "Ethanoic acid and water", type: "concept_error", logicTag: "oxidation_not_combustion_product" },
    ],
    solutionSteps: [
      "Complete combustion of any carbon compound (with excess O₂): carbon compound + O₂ → CO₂ + H₂O.",
      "C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O (complete combustion).",
      "CO₂ and H₂O are always the products of COMPLETE combustion of hydrocarbons or alcohols.",
    ],
    shortcut: "Complete combustion: C→CO₂, H→H₂O, S→SO₂. Burns clean (blue flame). Incomplete: CO + soot (yellow/orange flame).",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "Covalent Bonding",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "The property of carbon by which it forms long chains with other carbon atoms is called:",
    questionType: "mcq",
    difficulty: "easy",
    difficultyScore: 0.2,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Tetravalency", type: "concept_error", logicTag: "tetravalency_is_ability_to_form_4_bonds_not_chain_forming" },
      { text: "Catenation", type: "correct", logicTag: "" },
      { text: "Isomerism", type: "concept_error", logicTag: "isomerism_is_same_formula_different_structure" },
      { text: "Hybridisation", type: "concept_error", logicTag: "hybridisation_is_mixing_of_atomic_orbitals" },
    ],
    solutionSteps: [
      "Catenation: the ability of carbon atoms to bond with each other to form long chains, branched chains, and rings.",
      "Carbon-carbon bonds are very stable — this is why millions of organic compounds exist.",
      "Tetravalency (4 bonds) combined with catenation makes carbon unique among all elements.",
    ],
    shortcut: "Catenation = chain forming (Latin: catena = chain). Unique to carbon. Tetravalency = 4 bonds. Both together = vast organic chemistry.",
  },

  // ── Medium (5) ───────────────────────────────────────────────────────────────
  {
    topic: "Carbon and its Compounds",
    subtopic: "Esterification",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the catalyst used in the esterification reaction between ethanol and ethanoic acid?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Dilute sodium hydroxide (NaOH)", type: "concept_error", logicTag: "NaOH_causes_saponification_not_esterification" },
      { text: "Concentrated sulphuric acid (H₂SO₄)", type: "correct", logicTag: "" },
      { text: "Platinum (Pt)", type: "concept_error", logicTag: "Pt_is_used_in_hydrogenation_not_esterification" },
      { text: "Nickel (Ni)", type: "concept_error", logicTag: "Ni_is_used_in_hydrogenation_of_alkenes" },
    ],
    solutionSteps: [
      "CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O (conc. H₂SO₄, gentle heat).",
      "Concentrated H₂SO₄ acts as a dehydrating agent (absorbs the water formed) and as an acid catalyst.",
      "The reaction is reversible — H₂SO₄ helps drive equilibrium towards ester formation.",
    ],
    shortcut: "Esterification catalyst: conc. H₂SO₄ (concentrated sulphuric acid). Also acts as dehydrating agent. Reverse reaction (ester + NaOH → soap + alcohol) is saponification.",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "Bromine Water Test",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "A student adds bromine water to an unknown organic compound. The orange colour of bromine water immediately decolourises. The compound is most likely:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Methane (CH₄)", type: "concept_error", logicTag: "methane_is_saturated_does_not_decolourise_bromine_water" },
      { text: "Ethene (CH₂=CH₂)", type: "correct", logicTag: "" },
      { text: "Ethane (CH₃–CH₃)", type: "concept_error", logicTag: "ethane_is_saturated_does_not_decolourise_bromine_water" },
      { text: "Propane (CH₃CH₂CH₃)", type: "concept_error", logicTag: "propane_is_saturated_alkane" },
    ],
    solutionSteps: [
      "Bromine water test: orange/brown Br₂ solution is decolourised by unsaturated compounds (alkenes, alkynes).",
      "CH₂=CH₂ + Br₂ → CH₂Br–CH₂Br (addition reaction, dibromoethane forms, colourless).",
      "Saturated compounds (alkanes like methane, ethane, propane) do NOT decolourise bromine water.",
    ],
    shortcut: "Bromine water decolourised = C=C present (unsaturated). No decolouration = saturated (no double/triple bond).",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "Soaps and Detergents",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Soap forms scum (white precipitate) in hard water but detergent does not. This is because:",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Soap has a shorter carbon chain than detergent", type: "concept_error", logicTag: "chain_length_is_not_the_factor" },
      { text: "Calcium and magnesium salts of soap are insoluble, while those of detergent are soluble", type: "correct", logicTag: "" },
      { text: "Detergent is acidic and neutralises the hardness of water", type: "concept_error", logicTag: "detergent_is_not_acidic" },
      { text: "Soap does not form micelles in hard water", type: "partial_logic", logicTag: "soap_loses_micelle_ability_because_scum_forms_not_an_independent_reason" },
    ],
    solutionSteps: [
      "Hard water contains Ca²⁺ and Mg²⁺ ions.",
      "Soap (RCOO⁻Na⁺) + Ca²⁺ → Ca(RCOO)₂ (insoluble scum — calcium stearate). Soap is wasted.",
      "Detergent (RSO₃⁻Na⁺) + Ca²⁺ → Ca(RSO₃)₂ (soluble in water). No scum, full cleaning action.",
    ],
    shortcut: "Soap vs detergent in hard water: Ca-soap = insoluble scum. Ca-detergent = soluble = no scum. This is why detergents are used in washing machines.",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "Ethanol and Ethanoic Acid",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Ethanoic acid is sometimes called 'glacial acetic acid' when pure. Why?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "It is extracted from glaciers and has a very low temperature", type: "concept_error", logicTag: "glacial_refers_to_ice-like_appearance_not_extraction_source" },
      { text: "Pure ethanoic acid freezes at 16.6°C, forming ice-like crystals in cold conditions", type: "correct", logicTag: "" },
      { text: "It has a very high boiling point similar to ice steam", type: "concept_error", logicTag: "boiling_point_and_glacial_terminology_not_related" },
      { text: "It is colourless like ice", type: "concept_error", logicTag: "colour_alone_does_not_explain_the_glacial_name" },
    ],
    solutionSteps: [
      "Pure ethanoic acid (100% concentration) has a melting point of 16.6°C.",
      "In cold weather (below 16.6°C), it solidifies into colourless ice-like crystals, resembling a glacier.",
      "Hence the term 'glacial acetic acid' for pure, concentrated ethanoic acid. Dilute solutions (like vinegar, 3–5%) remain liquid.",
    ],
    shortcut: "Glacial = pure (not dilute). Melts at 16.6°C → looks like ice in cold temperatures → 'glacial'. Vinegar is 3–5% CH₃COOH in water.",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "IUPAC Naming",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "What is the IUPAC name of the compound with the formula CH₃–CH₂–COOH?",
    questionType: "mcq",
    difficulty: "medium",
    difficultyScore: 0.5,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Ethanoic acid", type: "concept_error", logicTag: "ethanoic_acid_is_CH3COOH_only_2_carbons" },
      { text: "Propanoic acid", type: "correct", logicTag: "" },
      { text: "Propanol", type: "concept_error", logicTag: "propanol_has_OH_group_not_COOH" },
      { text: "Methanoic acid", type: "concept_error", logicTag: "methanoic_acid_is_HCOOH_only_1_carbon" },
    ],
    solutionSteps: [
      "Count carbons: CH₃ (1) – CH₂ (2) – COOH (3). Three carbons → 'prop' prefix.",
      "Functional group –COOH = carboxylic acid → suffix '-anoic acid'.",
      "IUPAC name: propanoic acid. Note: the COOH carbon is counted as part of the chain.",
    ],
    shortcut: "COOH acid names: 1C = methanoic, 2C = ethanoic (vinegar), 3C = propanoic, 4C = butanoic. Always count the C in COOH as part of the chain.",
  },

  // ── Hard (3) ─────────────────────────────────────────────────────────────────
  {
    topic: "Carbon and its Compounds",
    subtopic: "Addition and Substitution Reactions",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Vegetable oils are converted to vegetable ghee (vanaspati) by the process of:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Saponification using NaOH", type: "concept_error", logicTag: "saponification_makes_soap_not_ghee" },
      { text: "Catalytic hydrogenation using H₂ and Ni catalyst", type: "correct", logicTag: "" },
      { text: "Oxidation using acidified KMnO₄", type: "concept_error", logicTag: "oxidation_would_form_carboxylic_acids_not_solid_fat" },
      { text: "Esterification with ethanol", type: "concept_error", logicTag: "esterification_makes_esters_not_solid_fats" },
    ],
    solutionSteps: [
      "Vegetable oils contain unsaturated fatty acids (C=C double bonds) → liquid at room temperature.",
      "Catalytic hydrogenation: oil + H₂ →(Ni catalyst, heat) saturated fat (solid/semi-solid).",
      "C=C + H₂ → C–C (addition reaction). Converting unsaturated → saturated raises melting point → solid ghee/margarine.",
    ],
    shortcut: "Vegetable ghee = catalytic hydrogenation of oils. Ni catalyst, heat. C=C + H₂ → C–C (addition). Same reaction converts liquid oil to solid fat.",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "Covalent Bonding and Allotropes",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "Diamond is the hardest natural substance while graphite is very soft and slippery. Both are pure carbon. The reason for this difference is:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Diamond has higher carbon content than graphite", type: "concept_error", logicTag: "both_are_100_percent_carbon" },
      { text: "Diamond has a 3D network of C–C bonds (each C bonded to 4 others); graphite has 2D hexagonal layers that can slide over each other", type: "correct", logicTag: "" },
      { text: "Diamond has ionic bonds while graphite has covalent bonds", type: "concept_error", logicTag: "both_have_covalent_bonds_no_ionic_bonds" },
      { text: "Diamond is crystalline while graphite is amorphous", type: "concept_error", logicTag: "graphite_is_also_crystalline_just_different_structure" },
    ],
    solutionSteps: [
      "Diamond: each C bonded to 4 other C in a 3D tetrahedral network. No free electrons. Rigid → hardest substance.",
      "Graphite: each C bonded to 3 others in flat hexagonal layers. Layers held by weak van der Waals forces.",
      "Layers in graphite slide over each other easily under pressure → lubricant effect (used in pencils as 'lead').",
    ],
    shortcut: "Diamond (4 bonds, 3D) = hard, insulator. Graphite (3 bonds, 2D layers) = soft, conductor. 3D vs 2D bonding structure is the key difference.",
  },

  {
    topic: "Carbon and its Compounds",
    subtopic: "Soaps and Detergents",
    subject: "Science",
    grade: "10",
    examBoard: "CBSE",
    questionText: "In the cleansing action of soap, the micelle forms because the soap molecule has:",
    questionType: "mcq",
    difficulty: "hard",
    difficultyScore: 0.75,
    marks: 1,
    isAIGenerated: true,
    options: [
      { text: "Two hydrophilic ends and no hydrophobic part", type: "concept_error", logicTag: "soap_must_have_hydrophobic_tail_to_trap_grease" },
      { text: "A long hydrophobic hydrocarbon tail and a hydrophilic ionic head (–COO⁻Na⁺)", type: "correct", logicTag: "" },
      { text: "A polar covalent bond that attracts both water and oil equally", type: "concept_error", logicTag: "no_single_bond_type_attracts_both_simultaneously" },
      { text: "Two charged ends — one positive and one negative", type: "concept_error", logicTag: "soap_has_one_ionic_end_and_one_nonpolar_end_not_two_charged_ends" },
    ],
    solutionSteps: [
      "Soap molecule structure: long non-polar hydrocarbon chain (R–) + ionic head (–COO⁻Na⁺).",
      "Hydrophobic tail (R–): dissolves in grease/oil (like dissolves like). Hydrophilic head (–COO⁻): dissolves in water.",
      "In water, tails cluster inward trapping oil/grease; heads face outward towards water → forms micelle. Agitation removes micelle with trapped dirt.",
    ],
    shortcut: "Soap = one end loves water (–COO⁻Na⁺), one end loves grease (R–CH₂–CH₂–). Micelle = ball with grease inside, water-loving shell outside.",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI, { serverSelectionTimeoutMS: 10000 });
  let added = 0, skipped = 0;
  for (const q of QUESTIONS) {
    const exists = await Question.findOne({ questionText: q.questionText, subject: q.subject });
    if (exists) { skipped++; continue; }
    await Question.create(q);
    added++;
  }
  console.log(`Chemistry questions: ${added} added, ${skipped} skipped`);
  await mongoose.disconnect();
}

seed().catch(console.error);
