/**
 * CBSE Class 9 Mathematics — NcertTopicContent v2 (sub-topic expansion)
 * Replaces the single-topic-per-chapter model with 4 sub-topics per chapter (32 total).
 * Safe to re-run (upsert). Run AFTER seedMath9CleanupV1.js to remove old single-topic docs.
 * Usage: node config/seedMath9ContentV2.js
 */
import "dotenv/config";
import mongoose from "mongoose";
import { NcertTopicContent } from "../models/ncertTopicContentModel.js";

const topics = [

  // ── Chapter 1: Orienting Yourself — The Use of Coordinates ──────────────────
  {
    topicId: "math9_ch1_cartesian_plane",
    chapterNumber: 1, sectionNumber: "1.1",
    title: "The Cartesian Plane", subject: "Mathematics",
    intuition: "A Cartesian plane is simply two number lines crossing at right angles. Every point in the plane has a unique address — two numbers that tell you exactly where it sits, like GPS coordinates on a map.",
    process_explanation: "Draw a horizontal line (x-axis) and a vertical line (y-axis) crossing at the origin (0,0). The plane is split into four quadrants: Q1 (+,+), Q2 (−,+), Q3 (−,−), Q4 (+,−). Every point P is written as (x, y) where x is horizontal distance from origin and y is vertical distance.",
    worked_example: "Identify the quadrant for each point: A(3,5), B(−2,4), C(−1,−3), D(6,−2). A → Q1 (both positive). B → Q2 (x negative, y positive). C → Q3 (both negative). D → Q4 (x positive, y negative).",
    common_misconceptions: "Students often swap x and y when plotting — remember: x comes first, move horizontally THEN vertically. Also, the origin (0,0) is on no quadrant — it is the intersection point itself.",
    shortcuts_and_tricks: "Sign pattern trick: (+ ,+)→Q1, (−,+)→Q2, (−,−)→Q3, (+,−)→Q4. Visualise a clock: Q1 is top-right, go anticlockwise for Q2, Q3, Q4.",
    key_takeaway: "A point's address on the Cartesian plane is (x, y); the sign of each coordinate tells you which quadrant it lives in.",
  },
  {
    topicId: "math9_ch1_plotting_points",
    chapterNumber: 1, sectionNumber: "1.2",
    title: "Plotting Points in All Four Quadrants", subject: "Mathematics",
    intuition: "Plotting a point is like following treasure map directions: 'Go 3 steps right, then 4 steps up.' The x-value is your left-right move, the y-value is your up-down move.",
    process_explanation: "Step 1: Start at origin. Step 2: Move |x| units along the x-axis (right if x>0, left if x<0). Step 3: Move |y| units along the y-axis (up if y>0, down if y<0). Step 4: Mark and label the point.",
    worked_example: "Plot P(−3, 2): Start at origin → move 3 units LEFT (x=−3) → move 2 units UP (y=2) → mark P. Plot Q(4, −1): move 4 right → move 1 down → mark Q.",
    common_misconceptions: "Moving in the wrong direction is the most common error. Negative x means LEFT (not right), negative y means DOWN (not up). Always check the sign before moving.",
    shortcuts_and_tricks: "Draw dashed lines parallel to axes from your target x and y values — their intersection is exactly your point. This visual cross-hair method prevents direction errors.",
    key_takeaway: "Plot by moving horizontally first (x-direction), then vertically (y-direction) — always from the origin.",
  },
  {
    topicId: "math9_ch1_distance_formula",
    chapterNumber: 1, sectionNumber: "1.3",
    title: "Distance Between Two Points", subject: "Mathematics",
    intuition: "The distance formula is just the Pythagorean theorem applied to coordinates. The horizontal and vertical gaps between two points form the legs of a right triangle; the distance is the hypotenuse.",
    process_explanation: "For points A(x₁, y₁) and B(x₂, y₂): Distance AB = √[(x₂−x₁)² + (y₂−y₁)²]. Steps: 1. Find Δx = x₂−x₁. 2. Find Δy = y₂−y₁. 3. Square both. 4. Add. 5. Take the square root.",
    worked_example: "Find distance between A(1, 2) and B(4, 6). Δx = 4−1 = 3, Δy = 6−2 = 4. Distance = √(3² + 4²) = √(9+16) = √25 = 5 units.",
    common_misconceptions: "Squaring inside the root hides the sign — (x₂−x₁)² is always positive, so order of subtraction doesn't matter. But students often forget to square: writing √(3+4)=√7 instead of √(9+16)=5.",
    shortcuts_and_tricks: "Recognise 3-4-5 and 5-12-13 Pythagorean triples — if Δx and Δy match a triple, you can skip the root calculation. Also, if points share an x or y coordinate, it's a simple subtraction (horizontal/vertical line).",
    key_takeaway: "Distance = √(Δx² + Δy²) — a direct application of the Pythagorean theorem in the coordinate plane.",
  },
  {
    topicId: "math9_ch1_section_formula",
    chapterNumber: 1, sectionNumber: "1.4",
    title: "Midpoint and Section Formula", subject: "Mathematics",
    intuition: "The midpoint is simply the average of the two points' coordinates. The section formula generalises this: if a point divides a line segment in ratio m:n, it's a weighted average.",
    process_explanation: "Midpoint M of A(x₁,y₁) and B(x₂,y₂): M = ((x₁+x₂)/2, (y₁+y₂)/2). Section formula (internal division in ratio m:n): P = ((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n)).",
    worked_example: "Find midpoint of A(2,4) and B(8,10): M = ((2+8)/2, (4+10)/2) = (5, 7). Now find point dividing AB in 2:1: P = ((2×8+1×2)/(2+1), (2×10+1×4)/3) = (18/3, 24/3) = (6, 8).",
    common_misconceptions: "In the section formula, students mix up which point gets multiplied by m and which by n. Remember: m goes with the second point (x₂, y₂), n goes with the first (x₁, y₁).",
    shortcuts_and_tricks: "For midpoint: just average. For 1:1 ratio, section formula = midpoint. For 1:2 ratio, the point is one-third of the way from A to B.",
    key_takeaway: "Midpoint = coordinate average; section formula gives any division point using a weighted average with ratio m:n.",
  },

  // ── Chapter 2: Introduction to Linear Polynomials ───────────────────────────
  {
    topicId: "math9_ch2_poly_basics",
    chapterNumber: 2, sectionNumber: "2.1",
    title: "Polynomials — Definitions and Degree", subject: "Mathematics",
    intuition: "A polynomial is an expression with variables raised to whole-number powers — like building with blocks where each block is a term. The degree is the highest power, which controls the overall shape and behaviour.",
    process_explanation: "A polynomial in x: p(x) = aₙxⁿ + aₙ₋₁xⁿ⁻¹ + … + a₁x + a₀. Key terms: degree = n (highest power), leading coefficient = aₙ, constant term = a₀. Types: monomial (1 term), binomial (2), trinomial (3).",
    worked_example: "Classify: (a) 3x² − 5x + 2: degree 2, trinomial, leading coeff 3. (b) 7x⁴: degree 4, monomial. (c) x³ − 1: degree 3, binomial. (d) 5: degree 0, monomial (constant polynomial).",
    common_misconceptions: "A negative exponent (like x⁻²) or fractional exponent (like x^(1/2)) makes it NOT a polynomial. Also, the degree of 0 (zero polynomial) is undefined, not 0.",
    shortcuts_and_tricks: "Find degree by looking at the term with the highest power — ignore coefficients. For a polynomial like 2x³ + 5x − 3x⁴, degree is 4 (from −3x⁴), not 3.",
    key_takeaway: "A polynomial uses only non-negative integer powers of variables; its degree is the highest power present.",
  },
  {
    topicId: "math9_ch2_zeroes",
    chapterNumber: 2, sectionNumber: "2.2",
    title: "Zeroes of a Polynomial", subject: "Mathematics",
    intuition: "A zero of a polynomial p(x) is a value of x that makes p(x) equal zero — the x-coordinate where the graph crosses or touches the x-axis. Finding zeroes is like finding the polynomial's 'quiet moments.'",
    process_explanation: "To find zero of p(x): set p(x) = 0 and solve for x. For linear p(x) = ax + b: zero = −b/a. For quadratic ax²+bx+c: use factoring or quadratic formula. Verify: substitute back and confirm p(zero) = 0.",
    worked_example: "Find zero of p(x) = 2x − 6: Set 2x − 6 = 0 → x = 3. Verify: p(3) = 2(3) − 6 = 0. ✓. Find zeroes of p(x) = x² − 5x + 6: factor → (x−2)(x−3) = 0 → x = 2 or x = 3.",
    common_misconceptions: "A zero of p(x) is NOT the same as p(0). p(0) is the y-intercept (value when x=0). A zero is an x-value where p(x)=0. The number of zeroes ≤ degree of polynomial.",
    shortcuts_and_tricks: "For linear polynomials (degree 1): exactly 1 zero, always at x = −(constant term)/(coefficient of x). A constant non-zero polynomial has NO zeroes.",
    key_takeaway: "Zeroes of p(x) are the x-values where p(x) = 0; a degree-n polynomial has at most n zeroes.",
  },
  {
    topicId: "math9_ch2_remainder_theorem",
    chapterNumber: 2, sectionNumber: "2.3",
    title: "Remainder Theorem", subject: "Mathematics",
    intuition: "When you divide a polynomial p(x) by (x−a), the remainder is simply p(a). Instead of doing long division, just plug in the value a — a massive shortcut for finding remainders.",
    process_explanation: "Remainder Theorem: If p(x) is divided by (x−a), the remainder r = p(a). Steps: 1. Identify a (from divisor x−a, so a is the zero of the divisor). 2. Substitute x=a into p(x). 3. Calculate — that result is the remainder.",
    worked_example: "Find remainder when p(x) = x³ − 3x² + 4x − 1 is divided by (x−2). By RT: remainder = p(2) = 8 − 12 + 8 − 1 = 3. Verify by long division if needed.",
    common_misconceptions: "For divisor (x+a), the substitution value is x=−a, NOT +a. (x+3) means the divisor is (x−(−3)), so substitute x=−3. Students frequently plug in +3 instead.",
    shortcuts_and_tricks: "Divisor (2x−1): rewrite as 2(x−1/2), so substitute x=1/2. Divisor (ax−b): substitute x=b/a.",
    key_takeaway: "Remainder when p(x) ÷ (x−a) = p(a). Just substitute — no long division needed.",
  },
  {
    topicId: "math9_ch2_factor_theorem",
    chapterNumber: 2, sectionNumber: "2.4",
    title: "Factor Theorem and Factorisation", subject: "Mathematics",
    intuition: "The Factor Theorem is a special case of the Remainder Theorem: if the remainder is zero, then (x−a) is a factor. It's like saying: if a room is perfectly cleaned (remainder=0), then the cleaning rule (x−a) divides the mess (polynomial) completely.",
    process_explanation: "Factor Theorem: (x−a) is a factor of p(x) ⟺ p(a) = 0. To factorise: 1. Find a value 'a' where p(a)=0. 2. Divide p(x) by (x−a) using synthetic/long division. 3. Factorise the quotient further if possible.",
    worked_example: "Factorise p(x) = x³ − 4x² + x + 6. Test x=2: p(2)=8−16+2+6=0 ✓. So (x−2) is a factor. Divide: x³−4x²+x+6 ÷ (x−2) = x²−2x−3 = (x−3)(x+1). Full factorisation: (x−2)(x−3)(x+1).",
    common_misconceptions: "Students try random values without a strategy. Use the rational root theorem: possible rational zeroes of p(x)=aₙxⁿ+…+a₀ are ±(factors of a₀)/(factors of aₙ). For monic polynomials, try ±(factors of constant term).",
    shortcuts_and_tricks: "For cubic with small coefficients, try x=1,−1,2,−2,3,−3 first — they cover most CBSE exam cases. If p(1)=0, then (x−1) is always a factor (sum of coefficients = 0).",
    key_takeaway: "Factor Theorem: (x−a) is a factor ⟺ p(a)=0. Find one zero to peel off one factor, then factorise the quotient.",
  },

  // ── Chapter 3: The World of Numbers ────────────────────────────────────────
  {
    topicId: "math9_ch3_number_systems",
    chapterNumber: 3, sectionNumber: "3.1",
    title: "Real Number System — Rational and Irrational Numbers", subject: "Mathematics",
    intuition: "All numbers on the number line are real numbers. They split into two families: rationals (can be expressed as p/q) and irrationals (cannot). Together they fill the entire number line without gaps.",
    process_explanation: "Rational numbers: p/q where p,q are integers and q≠0. Their decimal form either terminates (1/4=0.25) or repeats (1/3=0.333…). Irrational numbers: non-terminating, non-repeating decimals (√2, π, e). Real numbers = Rationals ∪ Irrationals.",
    worked_example: "Classify: (a) 7/3 — rational (terminates? no; repeats? yes → 2.333…). (b) √5 — irrational (√5 ≈ 2.2360679… non-terminating, non-repeating). (c) 0.121221222… — irrational (pattern but not repeating block). (d) 0.7̄ = 7/9 — rational.",
    common_misconceptions: "√4 = 2 is rational, NOT irrational. Not all square roots are irrational — only those of non-perfect squares. Also, π is irrational; 22/7 is just a rational approximation of π.",
    shortcuts_and_tricks: "To check if √n is irrational: if n is a perfect square (1,4,9,16,25…), it's rational. Otherwise, irrational. A number that repeats in a BLOCK is rational (e.g. 0.142857142857… = 1/7).",
    key_takeaway: "Rationals have terminating or repeating decimals; irrationals have non-terminating, non-repeating decimals. Together they make up all real numbers.",
  },
  {
    topicId: "math9_ch3_irrational_representation",
    chapterNumber: 3, sectionNumber: "3.2",
    title: "Representing Irrationals on the Number Line", subject: "Mathematics",
    intuition: "Even though irrationals can't be written as simple fractions, they have exact positions on the number line. We can locate √2 using geometry — the diagonal of a unit square — and transfer it to the line with a compass.",
    process_explanation: "To plot √n on the number line: 1. Draw OA=n units on the number line from origin O. 2. From A, draw AB=1 unit perpendicular. 3. Find midpoint M of OB. 4. Draw semicircle with center M, radius MO=MB. 5. The semicircle intersects the perpendicular at C where OC=√n. 6. Transfer OC to the number line.",
    worked_example: "Locate √2 on number line: Draw OA=1 unit, AB=1 unit perpendicular to OA. OB = √(1²+1²) = √2 by Pythagoras. Draw arc of radius OB centred at O — it cuts the number line at √2.",
    common_misconceptions: "Students think this is approximation — it's an exact construction. The arc transferring OB to the number line places the point at exactly √2, not an approximation.",
    shortcuts_and_tricks: "For √(n+1): notice that the hypotenuse of a right triangle with legs √n and 1 has length √(n+1). So you can build a spiral of right triangles to plot √2, √3, √4, √5… step by step.",
    key_takeaway: "Irrational numbers occupy exact positions on the number line, located using geometric constructions based on the Pythagorean theorem.",
  },
  {
    topicId: "math9_ch3_surds_rationalisation",
    chapterNumber: 3, sectionNumber: "3.3",
    title: "Surds and Rationalisation", subject: "Mathematics",
    intuition: "A surd is an irrational root that can't be simplified to a rational number (like √3, ∛5). Rationalisation clears the surd from a denominator by multiplying by the right conjugate — like removing a splinter to make a fraction clean.",
    process_explanation: "To rationalise: If denominator is √a, multiply numerator and denominator by √a. If denominator is (a+√b), multiply by conjugate (a−√b), using (a+b)(a−b)=a²−b². Laws of surds: √a×√b=√(ab), √a/√b=√(a/b), (√a)²=a.",
    worked_example: "Rationalise 3/√5: Multiply by √5/√5 → 3√5/5. Rationalise 2/(3+√2): Multiply by (3−√2)/(3−√2) → 2(3−√2)/(9−2) = 2(3−√2)/7 = (6−2√2)/7.",
    common_misconceptions: "√(a+b) ≠ √a + √b. This is one of the most common errors in algebra. Also, after rationalising, students forget to simplify the resulting fraction.",
    shortcuts_and_tricks: "The conjugate of (a+√b) is (a−√b) and vice versa. Their product is always a²−b (rational). This trick works only for square roots — cube root rationalisation needs a³+b³ identity.",
    key_takeaway: "Surds are exact irrational roots; rationalisation removes surds from denominators by multiplying by the conjugate.",
  },
  {
    topicId: "math9_ch3_laws_of_exponents",
    chapterNumber: 3, sectionNumber: "3.4",
    title: "Laws of Exponents for Real Numbers", subject: "Mathematics",
    intuition: "Exponent laws are shortcuts for multiplying or dividing powers. Instead of writing out all the repeated multiplications, these rules let you manipulate powers algebraically — even when the base or exponent is irrational.",
    process_explanation: "Key laws: (1) aᵐ×aⁿ = aᵐ⁺ⁿ, (2) aᵐ÷aⁿ = aᵐ⁻ⁿ, (3) (aᵐ)ⁿ = aᵐⁿ, (4) (ab)ⁿ = aⁿbⁿ, (5) (a/b)ⁿ = aⁿ/bⁿ, (6) a⁰ = 1 (a≠0), (7) a⁻ⁿ = 1/aⁿ, (8) a^(p/q) = (aᵖ)^(1/q) = q-th root of aᵖ.",
    worked_example: "Simplify: (a) 2³×2⁴ = 2⁷ = 128. (b) (3²)³ = 3⁶ = 729. (c) 8^(1/3) = ∛8 = 2. (d) (16)^(3/4) = (2⁴)^(3/4) = 2³ = 8. (e) 5² × 5⁻³ = 5⁻¹ = 1/5.",
    common_misconceptions: "aᵐ + aⁿ ≠ aᵐ⁺ⁿ — exponent rules only apply to multiplication, not addition. Also, (a+b)ⁿ ≠ aⁿ+bⁿ. Zero exponent: a⁰=1 for any a≠0, but 0⁰ is indeterminate.",
    shortcuts_and_tricks: "Convert bases to prime form before applying laws. 16 = 2⁴, 27 = 3³, 125 = 5³. This makes simplification straightforward. For a^(p/q), compute the root first (q-th root of a), then raise to power p to avoid large numbers.",
    key_takeaway: "Exponent laws work for all real bases; a^(p/q) means the q-th root of aᵖ — combine with prime factorisation for clean simplification.",
  },

  // ── Chapter 4: Exploring Algebraic Identities ───────────────────────────────
  {
    topicId: "math9_ch4_standard_identities",
    chapterNumber: 4, sectionNumber: "4.1",
    title: "Standard Algebraic Identities", subject: "Mathematics",
    intuition: "Algebraic identities are equations true for all values of the variables — like universal rules. Knowing them lets you expand or factorise expressions instantly without multiplying term by term.",
    process_explanation: "Core identities: (1) (a+b)²=a²+2ab+b², (2) (a−b)²=a²−2ab+b², (3) (a+b)(a−b)=a²−b², (4) (x+a)(x+b)=x²+(a+b)x+ab, (5) (a+b+c)²=a²+b²+c²+2ab+2bc+2ca, (6) (a+b)³=a³+3a²b+3ab²+b³, (7) (a−b)³=a³−3a²b+3ab²−b³.",
    worked_example: "Evaluate 103² using (a+b)²: (100+3)² = 10000+600+9 = 10609. Evaluate 97×103 using (a−b)(a+b): (100−3)(100+3) = 100²−3² = 10000−9 = 9991.",
    common_misconceptions: "(a+b)² ≠ a²+b². The middle term 2ab is always forgotten. Also (a+b)³ has 4 terms, not 2. The coefficient pattern is 1,3,3,1 (Pascal's triangle row).",
    shortcuts_and_tricks: "For numbers near a round number: 98² = (100−2)² = 10000−400+4 = 9604. Numbers whose sum is easy: 37×63 = (50−13)(50+13) = 2500−169 = 2331.",
    key_takeaway: "Algebraic identities are shortcuts: (a+b)²=a²+2ab+b² and (a+b)(a−b)=a²−b² are the most used in CBSE Class 9.",
  },
  {
    topicId: "math9_ch4_expansion",
    chapterNumber: 4, sectionNumber: "4.2",
    title: "Expansion Using Identities", subject: "Mathematics",
    intuition: "Expansion is opening brackets — turning a compact factored form into a sum of terms. Identities make this mechanical: match the pattern, apply the formula, get the expanded form in one step.",
    process_explanation: "Steps: 1. Identify which identity applies (look for squares, cubes, products of conjugates). 2. Label a, b, c from the expression. 3. Substitute into the identity's RHS. 4. Simplify each term.",
    worked_example: "Expand (2x+3y)²: use (a+b)²=a²+2ab+b² with a=2x, b=3y. = (2x)²+2(2x)(3y)+(3y)² = 4x²+12xy+9y². Expand (x+2)(x−2)(x²+4): = (x²−4)(x²+4) = x⁴−16.",
    common_misconceptions: "Squaring a binomial: (2x+3)² ≠ 4x²+9. The 2ab term must include coefficients: 2×(2x)×3 = 12x. Students forget to square the coefficients of the terms.",
    shortcuts_and_tricks: "Recognise (a+b)(a−b) = a²−b² before expanding — it reduces work significantly. If you see x⁴−y⁴, it factors as (x²+y²)(x+y)(x−y).",
    key_takeaway: "Choose the matching identity, substitute correctly including coefficients, and expand in one clean step — don't FOIL term by term if an identity applies.",
  },
  {
    topicId: "math9_ch4_factorisation_identities",
    chapterNumber: 4, sectionNumber: "4.3",
    title: "Factorisation Using Identities", subject: "Mathematics",
    intuition: "Factorisation is the reverse of expansion — converting a sum of terms back into a product. Identities work both ways: if an expression matches the RHS pattern, you can rewrite it as the LHS.",
    process_explanation: "Steps: 1. Check if expression matches an identity pattern on the RHS. 2. Extract a and b. 3. Write the factored form (LHS). Key reverse identities: a²−b²=(a+b)(a−b); a²+2ab+b²=(a+b)²; a³+b³=(a+b)(a²−ab+b²); a³−b³=(a−b)(a²+ab+b²).",
    worked_example: "Factorise: (a) 9x²−25: = (3x)²−5² = (3x+5)(3x−5). (b) x²+6x+9: = x²+2(x)(3)+3² = (x+3)². (c) 8x³+27: = (2x)³+3³ = (2x+3)(4x²−6x+9).",
    common_misconceptions: "a²+b² does NOT factorise using real numbers. Only a²−b² (difference) = (a+b)(a−b). Sum of squares cannot be factored over reals.",
    shortcuts_and_tricks: "For a³+b³ identity, the second bracket is always 'square minus product plus square': (a²−ab+b²). For a³−b³: (a²+ab+b²). The sign in the first bracket determines the middle sign in the second.",
    key_takeaway: "Factorisation reverses expansion — match the pattern to the identity RHS, read off a and b, and write the factored LHS.",
  },
  {
    topicId: "math9_ch4_applications",
    chapterNumber: 4, sectionNumber: "4.4",
    title: "Applications and Problem Solving with Identities", subject: "Mathematics",
    intuition: "Algebraic identities are power tools for computation — they let you evaluate large numbers, simplify complex expressions, and prove algebraic results without brute-force multiplication.",
    process_explanation: "Applications: (1) Numerical calculations: rewrite numbers as (a±b) and apply identity. (2) Proving identities: expand both sides or transform one side to match the other. (3) Finding values: use a²+b² = (a+b)² − 2ab to find sum of squares from sum and product.",
    worked_example: "If x + y = 5 and xy = 6, find x² + y². Using (x+y)² = x²+2xy+y²: 25 = x²+12+y² → x²+y² = 13. Find x³+y³: (x+y)³ = x³+3xy(x+y)+y³ → 125 = x³+18(5)+y³ → x³+y³ = 125−90 = 35.",
    common_misconceptions: "Students confuse which identity to use. When asked for x²+y² from x+y and xy, use (x+y)²−2xy. When asked for x³+y³, use (x+y)³−3xy(x+y).",
    shortcuts_and_tricks: "Key derived results: x²+y²=(x+y)²−2xy; x³+y³=(x+y)³−3xy(x+y); x²−y²=(x+y)(x−y). These are the most tested identity applications in CBSE examinations.",
    key_takeaway: "Identity applications convert hard computations into substitution problems — given sum and product of variables, any symmetric expression can be found.",
  },

  // ── Chapter 5: Circles ──────────────────────────────────────────────────────
  {
    topicId: "math9_ch5_basic_properties",
    chapterNumber: 5, sectionNumber: "5.1",
    title: "Basic Properties of Circles and Chord Theorems", subject: "Mathematics",
    intuition: "A circle is perfectly symmetric — every chord has a perpendicular bisector that passes through the centre. Equal chords are equidistant from the centre, like spokes of equal length balanced around a hub.",
    process_explanation: "Key theorems: (T1) The perpendicular from the centre to a chord bisects it. (T2) Equal chords are equidistant from the centre. (T3) A line through the centre perpendicular to a chord bisects the chord AND the arc. Converse: a line bisecting a chord perpendicularly passes through the centre.",
    worked_example: "In circle with centre O (radius 10 cm), chord AB = 16 cm. Find distance of chord from centre. OM⊥AB, so AM = 8 cm. By Pythagoras: OM² + 8² = 10² → OM² = 100−64 = 36 → OM = 6 cm.",
    common_misconceptions: "Students think the perpendicular from the centre just touches the chord — it actually passes through the midpoint. Also, longer chords are CLOSER to the centre (not farther); diameter is the longest chord and passes through the centre (distance 0).",
    shortcuts_and_tricks: "For a chord of length 2l in a circle of radius r, the distance from centre = √(r²−l²). This comes directly from the right triangle formed by radius, half-chord, and perpendicular distance.",
    key_takeaway: "The perpendicular from the centre bisects any chord; equal chords are equidistant from the centre.",
  },
  {
    topicId: "math9_ch5_angles_in_circle",
    chapterNumber: 5, sectionNumber: "5.2",
    title: "Angles Subtended by Chords and Arcs", subject: "Mathematics",
    intuition: "The central angle is always double the inscribed angle subtending the same arc — like a zoom in/out. This single rule unlocks dozens of circle angle problems.",
    process_explanation: "Theorems: (T1) Angle subtended by an arc at the centre = 2 × angle at any point on the remaining arc. (T2) Angles in the same segment are equal. (T3) Angle in a semicircle = 90°. (T4) Equal chords subtend equal angles at the centre.",
    worked_example: "Arc PQ subtends ∠POQ = 80° at centre O. Find ∠PRQ where R is on the major arc. By T1: ∠PRQ = 80°/2 = 40°. If R is on minor arc: ∠PRQ = (360°−80°)/2 = 140°.",
    common_misconceptions: "The 'double angle' theorem requires the angle at the centre and inscribed angle to subtend the SAME arc. Students sometimes use the wrong arc. Also, the theorem only applies when both angles subtend the same chord from the same side.",
    shortcuts_and_tricks: "Inscribed angle = (1/2) × central angle for the same arc. Angle in semicircle = 90° (central angle = 180°, so inscribed = 90°). Angles in the same segment are ALWAYS equal regardless of where on the arc the vertex lies.",
    key_takeaway: "Central angle = 2 × inscribed angle; angles in the same segment are equal; angle in semicircle = 90°.",
  },
  {
    topicId: "math9_ch5_cyclic_quadrilateral",
    chapterNumber: 5, sectionNumber: "5.3",
    title: "Cyclic Quadrilaterals", subject: "Mathematics",
    intuition: "A cyclic quadrilateral has all four vertices on a circle. Its opposite angles always add up to 180° — they're supplementary. This is a powerful constraint for solving angle problems.",
    process_explanation: "Theorem: Opposite angles of a cyclic quadrilateral sum to 180° (∠A + ∠C = 180°, ∠B + ∠D = 180°). Converse: If opposite angles of a quadrilateral sum to 180°, it is cyclic. Exterior angle of a cyclic quad = opposite interior angle.",
    worked_example: "ABCD is cyclic with ∠A = 75° and ∠B = 110°. Find ∠C and ∠D. ∠C = 180°−75° = 105° (opposite to A). ∠D = 180°−110° = 70° (opposite to B). Check: 75+105+110+70 = 360°. ✓",
    common_misconceptions: "Not every quadrilateral inscribed in a circle has perpendicular diagonals — that's for rhombuses/squares. The only guaranteed property is opposite angles summing to 180°.",
    shortcuts_and_tricks: "If one angle of a cyclic quad is 90°, the opposite angle is also 90°, and the diagonal is a diameter. This is a very common CBSE question setup.",
    key_takeaway: "Opposite angles of a cyclic quadrilateral are supplementary (sum to 180°).",
  },
  {
    topicId: "math9_ch5_tangents",
    chapterNumber: 5, sectionNumber: "5.4",
    title: "Tangents to a Circle", subject: "Mathematics",
    intuition: "A tangent touches a circle at exactly one point and is always perpendicular to the radius at that point. It's like a road running alongside a circular track — touching at one point and going straight.",
    process_explanation: "Key facts: (1) Tangent ⊥ radius at point of tangency. (2) From an external point, two tangent segments to the circle are equal in length. (3) The angle between a tangent and a chord = angle in the alternate segment (Tangent-Chord angle = Inscribed angle in alternate segment).",
    worked_example: "From external point P, two tangents PA and PB touch a circle with centre O. PA = 6 cm, OP = 10 cm. Find radius OA. Since OA⊥PA: OA² + 6² = 10² → OA² = 64 → OA = 8 cm. Also PA = PB = 6 cm (tangents from external point are equal).",
    common_misconceptions: "Tangents from an external point are equal in LENGTH, not equal as angles. Students confuse this with the equal angles theorem. Also, only ONE tangent can be drawn at any single point on a circle (not two).",
    shortcuts_and_tricks: "Triangle OPA is always a right triangle (with right angle at A). Use Pythagoras directly: OP² = OA² + PA². The quadrilateral OAPB (two tangents from P) always has ∠AOB + ∠APB = 180°.",
    key_takeaway: "A tangent is perpendicular to the radius at the point of contact; tangents from an external point are equal in length.",
  },

  // ── Chapter 6: Measuring Space — Perimeter and Area ─────────────────────────
  {
    topicId: "math9_ch6_heron_formula",
    chapterNumber: 6, sectionNumber: "6.1",
    title: "Heron's Formula for Triangle Area", subject: "Mathematics",
    intuition: "Heron's formula lets you find a triangle's area knowing only its three side lengths — no height needed. It's perfect when the altitude is hard to calculate.",
    process_explanation: "For triangle with sides a, b, c: (1) Find semi-perimeter: s = (a+b+c)/2. (2) Area = √[s(s−a)(s−b)(s−c)]. The formula works for ALL triangles — scalene, isosceles, equilateral.",
    worked_example: "Triangle with sides 13, 14, 15 cm. s = (13+14+15)/2 = 21. Area = √[21(21−13)(21−14)(21−15)] = √[21×8×7×6] = √7056 = 84 cm².",
    common_misconceptions: "Students sometimes compute s − a with a as the wrong side, mixing up which side is which. Label sides consistently as a, b, c and compute all three differences before substituting.",
    shortcuts_and_tricks: "For equilateral triangle with side a: Area = (√3/4)a² (derived from Heron's). For right triangle with legs p, q: Area = pq/2 (simpler than Heron's — use the right-angle shortcut when available).",
    key_takeaway: "Heron's formula: Area = √[s(s−a)(s−b)(s−c)] where s = semi-perimeter. Use when no height is given.",
  },
  {
    topicId: "math9_ch6_quadrilateral_area",
    chapterNumber: 6, sectionNumber: "6.2",
    title: "Area of Quadrilaterals and Composite Figures", subject: "Mathematics",
    intuition: "Any polygon's area can be found by dividing it into triangles. For quadrilaterals, split along a diagonal — you get two triangles whose areas add up to the total area.",
    process_explanation: "Quadrilateral ABCD with diagonal d₁: Area = (1/2)×d₁×(h₁+h₂) where h₁, h₂ are perpendicular distances from opposite vertices to the diagonal. Special cases: Parallelogram = base×height; Trapezium = (1/2)(a+b)×h; Rhombus = (1/2)d₁d₂.",
    worked_example: "Rhombus with diagonals 10 cm and 24 cm. Area = (1/2)×10×24 = 120 cm². Trapezium with parallel sides 8 cm and 12 cm, height 5 cm. Area = (1/2)(8+12)×5 = 50 cm².",
    common_misconceptions: "For a rhombus, Area = base×height (not ½×d₁d₂ — wait, both are correct!) Both formulas are valid for rhombus. For parallelogram, height must be perpendicular to base — the slant side is NOT the height.",
    shortcuts_and_tricks: "For any quadrilateral with diagonals d₁ and d₂ intersecting at right angles (rhombus, kite): Area = (1/2)d₁d₂. This is the fastest formula for kites and rhombuses.",
    key_takeaway: "Divide complex shapes into triangles; use diagonal formula for quadrilaterals; know special formulas for parallelogram, trapezium, and rhombus.",
  },
  {
    topicId: "math9_ch6_surface_area",
    chapterNumber: 6, sectionNumber: "6.3",
    title: "Surface Area of 3D Shapes", subject: "Mathematics",
    intuition: "Surface area is how much wrapping paper you'd need to cover a 3D shape completely. It's the total area of all faces — think of unfolding the shape flat and measuring all pieces.",
    process_explanation: "Key formulae: Cube (side a): TSA=6a², LSA=4a². Cuboid (l,b,h): TSA=2(lb+bh+hl), LSA=2(l+b)h. Cylinder (r,h): TSA=2πr(r+h), CSA=2πrh. Cone (r,l,h): TSA=πr(r+l), CSA=πrl where l=slant height=√(r²+h²). Sphere (r): TSA=4πr². Hemisphere: TSA=3πr², CSA=2πr².",
    worked_example: "Cylinder r=7 cm, h=10 cm. CSA = 2π×7×10 = 440 cm². TSA = 2π×7×(7+10) = 2π×7×17 = 748 cm². (Using π=22/7: CSA=2×22×10=440 cm², TSA=2×22×17=748 cm².)",
    common_misconceptions: "Students use TSA when only lateral/curved surface is needed (e.g., open containers). CSA excludes the base(s); TSA includes all surfaces. For a cone, slant height l ≠ height h — always compute l=√(r²+h²) first.",
    shortcuts_and_tricks: "Cone's slant height: l=√(r²+h²) — Pythagorean theorem on cross-section. For hemisphere placed on a flat surface, the flat circle base area = πr² is added, giving TSA = 3πr².",
    key_takeaway: "Surface area = sum of areas of all faces. Learn the 6 standard formulas; always distinguish CSA (curved/lateral) from TSA (total).",
  },
  {
    topicId: "math9_ch6_volume",
    chapterNumber: 6, sectionNumber: "6.4",
    title: "Volume of 3D Shapes", subject: "Mathematics",
    intuition: "Volume measures how much space a 3D shape occupies — like how much water it can hold. The key insight: prisms and cylinders = base area × height; pyramids and cones = (1/3) of the prism.",
    process_explanation: "Key formulae: Cube: V=a³. Cuboid: V=lbh. Cylinder: V=πr²h. Cone: V=(1/3)πr²h. Sphere: V=(4/3)πr³. Hemisphere: V=(2/3)πr³. Rule: Volume of cone = 1/3 × volume of cylinder with same base and height.",
    worked_example: "Sphere r=6 cm: V=(4/3)π×216=288π≈904.8 cm³. Cone r=3, h=4: l=5, V=(1/3)π×9×4=12π≈37.7 cm³. Ratio sphere:cone (same r,h=2r): (4/3)πr³ : (1/3)πr²(2r) = (4/3):(2/3) = 2:1.",
    common_misconceptions: "Cone volume has the (1/3) factor that students frequently forget. Also, volume uses the perpendicular height h, not the slant height l.",
    shortcuts_and_tricks: "Cylinder : Cone : Sphere (same radius, cylinder height = diameter) = 3 : 1 : 2. This classic ratio appears in CBSE problems. Memorise it to solve comparison questions instantly.",
    key_takeaway: "V(cylinder) = πr²h; V(cone) = (1/3)πr²h; V(sphere) = (4/3)πr³. Cone is always 1/3 of the cylinder with same base and height.",
  },

  // ── Chapter 7: The Mathematics of Maybe — Probability ──────────────────────
  {
    topicId: "math9_ch7_probability_basics",
    chapterNumber: 7, sectionNumber: "7.1",
    title: "Basic Probability Concepts and Terminology", subject: "Mathematics",
    intuition: "Probability measures the likelihood of an event on a scale from 0 (impossible) to 1 (certain). It's the mathematical language for describing chance — from coin tosses to weather forecasts.",
    process_explanation: "Key terms: Experiment = repeatable process with well-defined outcomes. Sample space S = set of all possible outcomes. Event E = subset of S. P(E) = n(E)/n(S) where n = number of outcomes. 0 ≤ P(E) ≤ 1. P(certain event) = 1. P(impossible event) = 0. P(E') = 1 − P(E).",
    worked_example: "A die is rolled. S={1,2,3,4,5,6}, n(S)=6. P(even) = n({2,4,6})/6 = 3/6 = 1/2. P(prime) = n({2,3,5})/6 = 3/6 = 1/2. P(>6) = 0/6 = 0. P(≤6) = 6/6 = 1.",
    common_misconceptions: "Probability cannot be greater than 1 or less than 0. If you get P = 7/3 for example, you've made an error. Also, 'equally likely' is assumed for standard problems but doesn't hold for biased coins/dice.",
    shortcuts_and_tricks: "Complementary probability: P(at least one) = 1 − P(none). P(E') = 1 − P(E). This is often faster than counting all favourable outcomes directly.",
    key_takeaway: "P(E) = favourable outcomes / total outcomes; probability ranges from 0 to 1; P(E) + P(E') = 1.",
  },
  {
    topicId: "math9_ch7_experimental_theoretical",
    chapterNumber: 7, sectionNumber: "7.2",
    title: "Experimental vs Theoretical Probability", subject: "Mathematics",
    intuition: "Experimental probability is what actually happens when you run trials (empirical). Theoretical probability is what should happen based on perfect symmetry (classical). As the number of trials increases, experimental approaches theoretical.",
    process_explanation: "Experimental: P(E) = number of times E occurred / total number of trials. Theoretical: P(E) = n(E)/n(S) assuming equally likely outcomes. Law of Large Numbers: as trials → ∞, experimental P → theoretical P.",
    worked_example: "A coin is tossed 200 times; heads appears 108 times. Experimental P(H) = 108/200 = 0.54. Theoretical P(H) = 1/2 = 0.5. The experimental value deviates slightly but both are approximately equal, showing the coin is approximately fair.",
    common_misconceptions: "After 5 heads in a row, P(next = tail) is still 1/2. Past outcomes don't affect future independent events — this is the Gambler's Fallacy. Experimental probability is not 'wrong' if it differs from theoretical — it's just based on observed data.",
    shortcuts_and_tricks: "Experimental probability is always a ratio of actual observations. If asked 'how many times would you expect E in n trials?', multiply n × P(theoretical E) for the expected frequency.",
    key_takeaway: "Experimental probability uses actual data; theoretical probability uses mathematical reasoning. More trials make them converge.",
  },
  {
    topicId: "math9_ch7_sample_space_events",
    chapterNumber: 7, sectionNumber: "7.3",
    title: "Sample Space and Types of Events", subject: "Mathematics",
    intuition: "Listing the sample space is the first step in any probability calculation. Complex events (two dice, drawing cards) have large sample spaces — organising them systematically prevents missing outcomes.",
    process_explanation: "Methods to list sample space: (1) Tree diagram — branches at each stage. (2) Table — rows for one experiment, columns for another. (3) Ordered pairs — (outcome1, outcome2). Types of events: Simple (single outcome), Compound (multiple outcomes), Complementary, Mutually exclusive (can't both occur).",
    worked_example: "Two dice thrown. n(S) = 6×6 = 36. Find P(sum=7): favourable = {(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)} = 6 outcomes. P(sum=7) = 6/36 = 1/6. Find P(both same): {(1,1),(2,2),(3,3),(4,4),(5,5),(6,6)} = 6. P = 6/36 = 1/6.",
    common_misconceptions: "When rolling two dice, n(S) = 36, not 11. There are 11 possible sums (2 to 12) but not 11 equally likely outcomes. Students often confuse the number of distinct sum values with the sample space size.",
    shortcuts_and_tricks: "For 2 dice, sum probability table: P(sum=7) is highest (6/36). For 52-card deck: P(ace) = 4/52 = 1/13; P(red) = 26/52 = 1/2; P(face card) = 12/52 = 3/13.",
    key_takeaway: "Always list the complete sample space first. For two experiments, n(S) = n(S₁) × n(S₂). Use tables or tree diagrams to stay organised.",
  },
  {
    topicId: "math9_ch7_probability_rules",
    chapterNumber: 7, sectionNumber: "7.4",
    title: "Probability Rules and Applications", subject: "Mathematics",
    intuition: "A few simple rules — addition for 'or', multiplication for independent 'and', complement for 'not' — unlock the ability to solve complex probability problems by breaking them into manageable pieces.",
    process_explanation: "Rules: (1) P(A or B) = P(A) + P(B) − P(A and B). (2) If A, B mutually exclusive: P(A or B) = P(A) + P(B). (3) P(not A) = 1 − P(A). (4) Independent events: P(A and B) = P(A) × P(B). Applications: cards, dice, balls from bags, selections.",
    worked_example: "Bag has 5 red, 3 blue balls. P(red) = 5/8. P(not red) = 3/8. If drawing 2 balls with replacement: P(both red) = 5/8 × 5/8 = 25/64. P(at least one red) = 1 − P(none red) = 1 − (3/8)² = 1 − 9/64 = 55/64.",
    common_misconceptions: "Independence vs mutual exclusivity: independent events CAN both occur; mutually exclusive events CANNOT both occur. Two fair coins are independent — result of one doesn't affect the other.",
    shortcuts_and_tricks: "'At least one' problems: always use P(at least one E) = 1 − P(no E). This is almost always faster than summing P(exactly 1) + P(exactly 2) + …",
    key_takeaway: "P(A or B) = P(A)+P(B)−P(A and B); for independent events P(A and B)=P(A)×P(B); use complements for 'at least one' problems.",
  },

  // ── Chapter 8: Sequences and Progressions ──────────────────────────────────
  {
    topicId: "math9_ch8_sequences_intro",
    chapterNumber: 8, sectionNumber: "8.1",
    title: "Introduction to Sequences and Patterns", subject: "Mathematics",
    intuition: "A sequence is an ordered list of numbers following a rule. Recognising the pattern is the key — once you know the rule, you can predict any term without listing them all.",
    process_explanation: "A sequence is a function from natural numbers to real numbers: a₁, a₂, a₃, …, aₙ, … The nth term formula (general term) aₙ allows finding any term directly. Types: Finite (ends) vs Infinite (continues). Pattern identification: find the operation connecting consecutive terms.",
    worked_example: "Sequence: 3, 7, 11, 15, … Differences: 7−3=4, 11−7=4, 15−11=4. Constant difference → arithmetic. General term: aₙ = 3 + (n−1)×4 = 4n−1. Verify: a₁=3 ✓, a₅=19 ✓. Sequence: 2, 6, 18, 54… Ratios: 6/2=3, 18/6=3. Constant ratio → geometric.",
    common_misconceptions: "A sequence is NOT just any list — it must follow a rule. Also, the first term is a₁ (when n=1), not a₀. In the formula aₙ = 4n−1, substituting n=0 gives −1, which is NOT part of the sequence.",
    shortcuts_and_tricks: "For constant differences → arithmetic. For constant ratios → geometric. For squares: aₙ = n². For triangular numbers: aₙ = n(n+1)/2. Most CBSE sequences are arithmetic.",
    key_takeaway: "Identify the rule (constant difference → AP, constant ratio → GP); the general term formula aₙ gives any term directly.",
  },
  {
    topicId: "math9_ch8_ap_basics",
    chapterNumber: 8, sectionNumber: "8.2",
    title: "Arithmetic Progressions — Basics", subject: "Mathematics",
    intuition: "An AP is any sequence where you add the same number each time. Salary increments, distance covered at constant speed, steps of a staircase — real life is full of APs.",
    process_explanation: "AP definition: aₙ − aₙ₋₁ = d (constant common difference) for all n. Standard form: a, a+d, a+2d, …. Three quantities fully define an AP: first term a, common difference d, number of terms n. d can be positive (increasing), negative (decreasing), or zero (constant).",
    worked_example: "Is 3, 6, 9, 12 an AP? Differences: 6−3=3, 9−6=3, 12−9=3. Yes, d=3. Is 1, 1, 2, 3, 5 (Fibonacci) an AP? Differences: 0, 1, 1, 2 — not constant. Not an AP. Write first 5 terms of AP with a=5, d=−3: 5, 2, −1, −4, −7.",
    common_misconceptions: "A constant sequence (like 7,7,7,7) is an AP with d=0. Students sometimes reject it. Also, d is the FIXED difference between consecutive terms — not between any two terms.",
    shortcuts_and_tricks: "Three consecutive terms of an AP: take them as (a−d), a, (a+d). Their sum = 3a (d cancels). Four consecutive terms: (a−3d),(a−d),(a+d),(a+3d). These setups simplify most 'find the AP' problems.",
    key_takeaway: "An AP has a constant common difference d between consecutive terms; defined by first term a and common difference d.",
  },
  {
    topicId: "math9_ch8_nth_term",
    chapterNumber: 8, sectionNumber: "8.3",
    title: "nth Term of an Arithmetic Progression", subject: "Mathematics",
    intuition: "The nth term formula is a shortcut to find any term without listing all the ones before it. It's like a GPS address for any position in the sequence.",
    process_explanation: "nth term: aₙ = a + (n−1)d. Derivation: a₁=a, a₂=a+d, a₃=a+2d, …, aₙ=a+(n−1)d. To find n for a given term: solve aₙ = a+(n−1)d for n. Key: n must be a positive integer; if n is not a natural number, the value is not a term of the AP.",
    worked_example: "AP: 5, 8, 11, 14… a=5, d=3. Find 20th term: a₂₀ = 5+(20−1)×3 = 5+57 = 62. Is 100 a term? 100 = 5+(n−1)×3 → 95 = 3(n−1) → n−1 = 31.67 — not an integer, so 100 is NOT a term.",
    common_misconceptions: "The formula has (n−1)d, not nd. A very common error is writing aₙ = a + nd. Check: for n=1, formula gives a+0×d = a ✓. With nd, you'd get a+d for n=1, which is a₂.",
    shortcuts_and_tricks: "If last term (lₙ) is given, find n: n = (l−a)/d + 1. The middle term of a finite AP with n terms is a + ((n−1)/2)×d = the average of first and last term.",
    key_takeaway: "aₙ = a + (n−1)d is the nth term formula. Always use (n−1), not n. Verify with n=1 to catch errors.",
  },
  {
    topicId: "math9_ch8_sum_of_ap",
    chapterNumber: 8, sectionNumber: "8.4",
    title: "Sum of n Terms of an Arithmetic Progression", subject: "Mathematics",
    intuition: "To add up all terms of an AP, pair the first with the last, second with second-last — each pair gives the same sum. Gauss used this trick as a child to sum 1 to 100 instantly.",
    process_explanation: "Sₙ = n/2 × (2a + (n−1)d) or equivalently Sₙ = n/2 × (a + l) where l = last term. Derivation: write sum forwards and backwards, add them — each pair sums to (2a+(n−1)d), and there are n pairs, so total = n×(a+l)/2. Key: nth term aₙ = Sₙ − Sₙ₋₁.",
    worked_example: "Sum of first 20 terms of AP 3, 7, 11… a=3, d=4, n=20. S₂₀ = 20/2 × (2×3 + 19×4) = 10 × (6+76) = 10×82 = 820. Alternative: l = a₂₀ = 3+19×4 = 79. S₂₀ = 20/2 × (3+79) = 10×82 = 820. ✓",
    common_misconceptions: "Sₙ formula gives the sum of the FIRST n terms — not any n consecutive terms. Also, if the last term l is given but n is unknown, find n first using the nth term formula, then apply Sₙ.",
    shortcuts_and_tricks: "Sum 1+2+3+…+n = n(n+1)/2 (AP with a=1, d=1). Sum of odd numbers 1+3+5+…+(2n−1) = n². Sum of even numbers 2+4+6+…+2n = n(n+1). Memorise these three — they appear frequently.",
    key_takeaway: "Sₙ = n/2 × (2a+(n−1)d) = n/2 × (first + last term). Use complementary: aₙ = Sₙ − Sₙ₋₁.",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  for (const t of topics) {
    await NcertTopicContent.findOneAndUpdate(
      { topicId: t.topicId },
      t,
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`  ✓ ${t.topicId}`);
  }
  console.log(`\nSeeded ${topics.length} NcertTopicContent docs for CBSE Class 9 Mathematics (v2 sub-topics).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
