import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const BOARD = "AP_SSC", GRADE = "9";

const questions = [
  // ─────────────────────────────────────────────────────────
  // TOPIC 1: ap_ssc_math9_ch2_polynomials_basics  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch2_polybas_a01",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The degree of the polynomial 3x⁴ − 2x² + 7 is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "2", type: "concept_error", logicTag: "highest_seen_wrong" },
      { text: "4", type: "correct",       logicTag: "highest_power" },
      { text: "7", type: "concept_error", logicTag: "constant_term" },
      { text: "3", type: "concept_error", logicTag: "leading_coefficient" },
    ],
    solutionSteps: [
      "Degree = highest power of the variable.",
      "Powers present: 4, 2, 0. Highest = 4.",
    ],
    shortcut: "Degree = largest exponent of the variable.",
    bloomLevel: "remember", conceptTested: "Degree of a polynomial",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a02",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Which of the following is NOT a polynomial?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "x² + 2x + 1",  type: "concept_error", logicTag: "quadratic_polynomial" },
      { text: "5",             type: "concept_error", logicTag: "constant_polynomial" },
      { text: "x + 1/x",      type: "correct",       logicTag: "negative_exponent" },
      { text: "√3 · x",       type: "concept_error", logicTag: "irrational_coefficient_ok" },
    ],
    solutionSteps: [
      "1/x = x⁻¹ — negative exponent of variable.",
      "Polynomials require non-negative integer exponents.",
      "x + 1/x is not a polynomial.",
    ],
    shortcut: "Look for negative exponents or fractional exponents in variables → not a polynomial.",
    bloomLevel: "understand", conceptTested: "Definition of a polynomial",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a03",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "A polynomial of degree 1 is called a:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Constant polynomial",  type: "concept_error", logicTag: "degree_0" },
      { text: "Linear polynomial",    type: "correct",       logicTag: "degree_1" },
      { text: "Quadratic polynomial", type: "concept_error", logicTag: "degree_2" },
      { text: "Cubic polynomial",     type: "concept_error", logicTag: "degree_3" },
    ],
    solutionSteps: [
      "Degree 0 → constant, Degree 1 → linear, Degree 2 → quadratic, Degree 3 → cubic.",
    ],
    shortcut: "1-linear, 2-quadratic, 3-cubic.",
    bloomLevel: "remember", conceptTested: "Classification of polynomials by degree",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a04",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The coefficient of x² in 5x³ − 3x² + 2x − 7 is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "5",   type: "concept_error", logicTag: "leading_coefficient" },
      { text: "−3",  type: "correct",       logicTag: "x_squared_coefficient" },
      { text: "2",   type: "concept_error", logicTag: "x_coefficient" },
      { text: "3",   type: "concept_error", logicTag: "sign_dropped" },
    ],
    solutionSteps: [
      "The term with x² is −3x².",
      "Coefficient of x² = −3.",
    ],
    shortcut: "Read off the number multiplying the required power of x (include sign).",
    bloomLevel: "remember", conceptTested: "Coefficient of a term",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a05",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "p(x) = x³ − 3x² + 2x − 5. What is p(1)?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "−4",  type: "concept_error", logicTag: "arithmetic_error" },
      { text: "−5",  type: "correct",       logicTag: "1minus3plus2minus5" },
      { text: "0",   type: "concept_error", logicTag: "forgot_constant" },
      { text: "5",   type: "concept_error", logicTag: "sign_error" },
    ],
    solutionSteps: [
      "p(1) = 1³ − 3(1)² + 2(1) − 5 = 1 − 3 + 2 − 5 = −5.",
    ],
    shortcut: "Substitute x = 1; every xⁿ → 1, so just sum the coefficients with signs.",
    bloomLevel: "apply", conceptTested: "Evaluating a polynomial at a value",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a06",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Which is a binomial of degree 3?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "x³",            type: "concept_error", logicTag: "monomial" },
      { text: "x³ + x² + x",  type: "concept_error", logicTag: "trinomial" },
      { text: "x³ + 4",        type: "correct",       logicTag: "two_terms_degree_3" },
      { text: "x² + 4",        type: "concept_error", logicTag: "degree_2" },
    ],
    solutionSteps: [
      "Binomial = exactly 2 terms. Degree 3 means highest power is x³.",
      "x³ + 4 has 2 terms and degree 3. ✓",
    ],
    shortcut: "Monomial=1 term, binomial=2, trinomial=3.",
    bloomLevel: "apply", conceptTested: "Classifying polynomials by terms and degree",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a07",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If p(x) = 2x + 5, what is p(−2)?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "9",   type: "concept_error", logicTag: "2_times_2_plus_5" },
      { text: "1",   type: "correct",       logicTag: "neg_4_plus_5" },
      { text: "−1",  type: "concept_error", logicTag: "sign_error" },
      { text: "5",   type: "concept_error", logicTag: "ignored_x_term" },
    ],
    solutionSteps: [
      "p(−2) = 2(−2) + 5 = −4 + 5 = 1.",
    ],
    shortcut: "Substitute x = −2 carefully, especially with negative signs.",
    bloomLevel: "apply", conceptTested: "Evaluating polynomial at negative value",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a08",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The sum of the coefficients of p(x) = 3x³ − 2x + 4 is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "5",   type: "correct",       logicTag: "p(1)_sum_of_coefficients" },
      { text: "9",   type: "concept_error", logicTag: "ignored_signs" },
      { text: "7",   type: "concept_error", logicTag: "wrong_arithmetic" },
      { text: "3",   type: "concept_error", logicTag: "only_leading" },
    ],
    solutionSteps: [
      "Sum of coefficients = p(1) = 3(1) − 2(1) + 4 = 3 − 2 + 4 = 5.",
    ],
    shortcut: "Sum of all coefficients = p(1).",
    bloomLevel: "understand", conceptTested: "Sum of coefficients = p(1)",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a09",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The degree of the zero polynomial is:",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "0",           type: "concept_error", logicTag: "constant_confusion" },
      { text: "1",           type: "concept_error", logicTag: "linear_confusion" },
      { text: "Undefined",   type: "correct",       logicTag: "zero_polynomial_special" },
      { text: "−∞",          type: "concept_error", logicTag: "convention_variation" },
    ],
    solutionSteps: [
      "The zero polynomial p(x) = 0 has no terms.",
      "Its degree is not defined (conventionally left undefined or sometimes −∞).",
      "Do NOT confuse with p(x) = 0 (constant polynomial of degree 0 ← this is WRONG; constant 0 is the zero polynomial).",
    ],
    shortcut: "Degree of the zero polynomial = undefined.",
    bloomLevel: "evaluate", conceptTested: "Degree of the zero polynomial",
  },
  {
    questionId: "ap_ssc9_ch2_polybas_a10",
    topicId: "ap_ssc_math9_ch2_polynomials_basics",
    topic: "Polynomials", subtopic: "Polynomial Basics",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If p(x) = xⁿ + 1 and p(−1) = 0, which value of n is possible?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "2",  type: "concept_error", logicTag: "even_power" },
      { text: "4",  type: "concept_error", logicTag: "even_power" },
      { text: "3",  type: "correct",       logicTag: "odd_power_minus1_gives_minus1" },
      { text: "6",  type: "concept_error", logicTag: "even_power" },
    ],
    solutionSteps: [
      "p(−1) = (−1)ⁿ + 1 = 0 → (−1)ⁿ = −1.",
      "(−1)ⁿ = −1 only when n is odd.",
      "Among the options, n = 3 is odd. ✓",
    ],
    shortcut: "(−1)^even = 1, (−1)^odd = −1.",
    bloomLevel: "analyse", conceptTested: "Evaluating polynomial at −1 using parity of exponent",
  },

  // ─────────────────────────────────────────────────────────
  // TOPIC 2: ap_ssc_math9_ch2_zeroes_of_polynomial  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch2_zeroes_a01",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "A zero of the polynomial p(x) = x − 5 is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "−5",  type: "concept_error", logicTag: "sign_error" },
      { text: "5",   type: "correct",       logicTag: "x_minus_5_zero" },
      { text: "0",   type: "concept_error", logicTag: "confused_with_y_intercept" },
      { text: "1",   type: "concept_error", logicTag: "wrong_value" },
    ],
    solutionSteps: [
      "Set p(x) = 0: x − 5 = 0 → x = 5.",
    ],
    shortcut: "Zero of ax + b is x = −b/a.",
    bloomLevel: "apply", conceptTested: "Finding zero of linear polynomial",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a02",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "How many zeroes can a quadratic polynomial have?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Exactly 2",            type: "concept_error", logicTag: "always_two_wrong" },
      { text: "At most 2",            type: "correct",       logicTag: "degree_2_at_most" },
      { text: "Exactly 1",            type: "concept_error", logicTag: "wrong" },
      { text: "Infinitely many",      type: "concept_error", logicTag: "impossible_for_polynomial" },
    ],
    solutionSteps: [
      "A polynomial of degree n has at most n real zeroes.",
      "Quadratic (degree 2) → at most 2 zeroes.",
      "It can have 0, 1, or 2 real zeroes depending on the discriminant.",
    ],
    shortcut: "Degree n → at most n zeroes.",
    bloomLevel: "understand", conceptTested: "Number of zeroes of a polynomial",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a03",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The zeroes of p(x) = x² − 4 are:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "4 and −4",   type: "concept_error", logicTag: "forgot_square_root" },
      { text: "2 and −2",   type: "correct",       logicTag: "x_squared_equals_4" },
      { text: "2 and 2",    type: "concept_error", logicTag: "missed_negative" },
      { text: "0 and 4",    type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "x² − 4 = 0 → x² = 4 → x = ±2.",
    ],
    shortcut: "Difference of squares: x² − a² = (x−a)(x+a) → zeroes ±a.",
    bloomLevel: "apply", conceptTested: "Zeroes of difference of squares",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a04",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If α and β are zeroes of x² − 5x + 6, what is α + β?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "−5",  type: "concept_error", logicTag: "wrong_sign" },
      { text: "6",   type: "concept_error", logicTag: "product_not_sum" },
      { text: "5",   type: "correct",       logicTag: "vieta_sum" },
      { text: "−6",  type: "concept_error", logicTag: "completely_wrong" },
    ],
    solutionSteps: [
      "For ax² + bx + c, sum of zeroes = −b/a.",
      "Here a=1, b=−5 → sum = −(−5)/1 = 5.",
    ],
    shortcut: "α + β = −b/a (Vieta's formula).",
    bloomLevel: "apply", conceptTested: "Sum of zeroes of quadratic (Vieta's)",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a05",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If α and β are zeroes of x² − 5x + 6, what is αβ?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "5",   type: "concept_error", logicTag: "sum_not_product" },
      { text: "−6",  type: "concept_error", logicTag: "wrong_sign" },
      { text: "6",   type: "correct",       logicTag: "vieta_product" },
      { text: "−5",  type: "concept_error", logicTag: "completely_wrong" },
    ],
    solutionSteps: [
      "Product of zeroes = c/a.",
      "c = 6, a = 1 → αβ = 6.",
    ],
    shortcut: "αβ = c/a (Vieta's product formula).",
    bloomLevel: "apply", conceptTested: "Product of zeroes of quadratic (Vieta's)",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a06",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The zero of a constant polynomial c ≠ 0 is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "0",             type: "concept_error", logicTag: "confused_with_zero_polynomial" },
      { text: "c",             type: "concept_error", logicTag: "confused_value_with_zero" },
      { text: "No zero",       type: "correct",       logicTag: "constant_never_zero" },
      { text: "Every real number", type: "concept_error", logicTag: "confused_with_zero_poly" },
    ],
    solutionSteps: [
      "A constant polynomial p(x) = c (c ≠ 0) is never equal to 0 for any x.",
      "It has no zeroes.",
    ],
    shortcut: "Non-zero constant polynomial → no zeroes. Zero polynomial → every number is a zero.",
    bloomLevel: "understand", conceptTested: "Zeroes of constant polynomial",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a07",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The number of zeroes that the polynomial f(x) = (x − 1)(x + 2)(x − 3) has is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "1",  type: "concept_error", logicTag: "counted_one" },
      { text: "2",  type: "concept_error", logicTag: "counted_two" },
      { text: "3",  type: "correct",       logicTag: "three_linear_factors" },
      { text: "6",  type: "concept_error", logicTag: "product_of_roots" },
    ],
    solutionSteps: [
      "Each linear factor gives one zero: x=1, x=−2, x=3.",
      "Three distinct zeroes.",
    ],
    shortcut: "Count distinct linear factors → that's the number of zeroes.",
    bloomLevel: "apply", conceptTested: "Zeroes from factored form",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a08",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If 2 is a zero of p(x) = x³ − kx + 6, then k =",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "5",   type: "concept_error", logicTag: "wrong" },
      { text: "7",   type: "correct",       logicTag: "substitute_x=2" },
      { text: "−5",  type: "concept_error", logicTag: "sign_error" },
      { text: "2",   type: "concept_error", logicTag: "confuses_root_with_k" },
    ],
    solutionSteps: [
      "p(2) = 0: 2³ − k(2) + 6 = 0",
      "8 − 2k + 6 = 0 → 14 = 2k → k = 7.",
    ],
    shortcut: "Substitute the given zero and solve for the unknown coefficient.",
    bloomLevel: "apply", conceptTested: "Finding unknown coefficient using a known zero",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a09",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Form a quadratic polynomial whose zeroes are 3 and −4.",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "x² + x − 12",   type: "correct",       logicTag: "vieta_reverse" },
      { text: "x² − x − 12",   type: "concept_error", logicTag: "wrong_b_sign" },
      { text: "x² + x + 12",   type: "concept_error", logicTag: "wrong_constant_sign" },
      { text: "x² − 12",       type: "concept_error", logicTag: "missing_linear_term" },
    ],
    solutionSteps: [
      "Sum = 3 + (−4) = −1; Product = 3 × (−4) = −12.",
      "Polynomial: x² − (sum)x + product = x² − (−1)x + (−12) = x² + x − 12.",
    ],
    shortcut: "p(x) = x² − (α+β)x + αβ.",
    bloomLevel: "apply", conceptTested: "Forming quadratic from zeroes",
  },
  {
    questionId: "ap_ssc9_ch2_zeroes_a10",
    topicId: "ap_ssc_math9_ch2_zeroes_of_polynomial",
    topic: "Polynomials", subtopic: "Zeroes of a Polynomial",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If α + β = 4 and αβ = −5, the quadratic polynomial is:",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "x² + 4x − 5",   type: "concept_error", logicTag: "wrong_sum_sign" },
      { text: "x² − 4x − 5",   type: "correct",       logicTag: "vieta_formula" },
      { text: "x² − 4x + 5",   type: "concept_error", logicTag: "wrong_product_sign" },
      { text: "x² + 4x + 5",   type: "concept_error", logicTag: "both_signs_wrong" },
    ],
    solutionSteps: [
      "Quadratic = x² − (α+β)x + αβ = x² − 4x + (−5) = x² − 4x − 5.",
    ],
    shortcut: "p(x) = x² − (sum)x + (product).",
    bloomLevel: "apply", conceptTested: "Constructing quadratic from Vieta relations",
  },

  // ─────────────────────────────────────────────────────────
  // TOPIC 3: ap_ssc_math9_ch2_remainder_theorem  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch2_remainder_a01",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "By the Remainder Theorem, when p(x) is divided by (x − a), the remainder is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "p(0)",   type: "concept_error", logicTag: "wrong_substitution" },
      { text: "p(a)",   type: "correct",       logicTag: "remainder_theorem" },
      { text: "p(−a)",  type: "concept_error", logicTag: "wrong_sign" },
      { text: "0",      type: "concept_error", logicTag: "only_if_factor" },
    ],
    solutionSteps: [
      "Remainder Theorem: if p(x) ÷ (x−a), remainder = p(a).",
    ],
    shortcut: "Divide by (x−a) → substitute x=a to get remainder.",
    bloomLevel: "remember", conceptTested: "Statement of Remainder Theorem",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a02",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Find the remainder when p(x) = x³ − 2x² + 5 is divided by (x − 1).",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "5",   type: "concept_error", logicTag: "only_constant" },
      { text: "4",   type: "correct",       logicTag: "p(1)" },
      { text: "3",   type: "concept_error", logicTag: "arithmetic_error" },
      { text: "2",   type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "p(1) = 1³ − 2(1²) + 5 = 1 − 2 + 5 = 4.",
    ],
    shortcut: "Remainder when divided by (x−1) = p(1).",
    bloomLevel: "apply", conceptTested: "Applying Remainder Theorem at x=1",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a03",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The remainder when x³ + 3x² + 3x + 1 is divided by (x + 1) is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "8",    type: "concept_error", logicTag: "p(1)_wrong" },
      { text: "1",    type: "concept_error", logicTag: "wrong" },
      { text: "0",    type: "correct",       logicTag: "p(-1)=0" },
      { text: "−8",   type: "concept_error", logicTag: "wrong_sign" },
    ],
    solutionSteps: [
      "(x+1) → substitute x = −1.",
      "p(−1) = (−1)³ + 3(−1)² + 3(−1) + 1 = −1 + 3 − 3 + 1 = 0.",
    ],
    shortcut: "Divide by (x+1) → remainder = p(−1).",
    bloomLevel: "apply", conceptTested: "Remainder Theorem with (x+a) divisor",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a04",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If p(x) = 2x³ − x + k and remainder when divided by (x − 1) is 3, then k =",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "2",   type: "correct",       logicTag: "p(1)=3" },
      { text: "−2",  type: "concept_error", logicTag: "sign_error" },
      { text: "4",   type: "concept_error", logicTag: "wrong" },
      { text: "1",   type: "concept_error", logicTag: "off_by_one" },
    ],
    solutionSteps: [
      "p(1) = 2(1) − 1 + k = 3 → 1 + k = 3 → k = 2.",
    ],
    shortcut: "Set p(divisor root) = given remainder and solve for unknown.",
    bloomLevel: "apply", conceptTested: "Finding unknown constant using Remainder Theorem",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a05",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "When x⁴ − 1 is divided by (x − 1), the remainder is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "1",   type: "concept_error", logicTag: "wrong" },
      { text: "−1",  type: "concept_error", logicTag: "wrong" },
      { text: "0",   type: "correct",       logicTag: "p(1)=1-1=0" },
      { text: "2",   type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "p(1) = 1⁴ − 1 = 0.",
      "Remainder = 0 → (x−1) is a factor.",
    ],
    shortcut: "When remainder = 0, the divisor is a factor.",
    bloomLevel: "apply", conceptTested: "Remainder Theorem and factor connection",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a06",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The remainder when p(x) = x² + x + 1 is divided by (x − 2) is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "3",   type: "concept_error", logicTag: "p(1)" },
      { text: "5",   type: "concept_error", logicTag: "wrong" },
      { text: "7",   type: "correct",       logicTag: "p(2)=4+2+1" },
      { text: "9",   type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "p(2) = 4 + 2 + 1 = 7.",
    ],
    shortcut: "Divisor (x−2) → evaluate at x = 2.",
    bloomLevel: "apply", conceptTested: "Applying Remainder Theorem at x=2",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a07",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "When p(x) = x³ − ax² + 6x − a is divided by (x − a), the remainder is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "6a",          type: "concept_error", logicTag: "partial_terms" },
      { text: "5a",          type: "correct",       logicTag: "p(a)_computed" },
      { text: "a³ + 5a",     type: "concept_error", logicTag: "wrong" },
      { text: "0",           type: "concept_error", logicTag: "factor_assumption" },
    ],
    solutionSteps: [
      "p(a) = a³ − a·a² + 6a − a = a³ − a³ + 6a − a = 5a.",
    ],
    shortcut: "Carefully expand p(a) term by term, simplify.",
    bloomLevel: "analyse", conceptTested: "Remainder with symbolic divisor",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a08",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The remainder when 3x³ + 5x² − 3x + 2 is divided by (x + 2) is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "0",    type: "concept_error", logicTag: "factor_assumption" },
      { text: "−12",  type: "correct",       logicTag: "p(-2)" },
      { text: "12",   type: "concept_error", logicTag: "sign_error" },
      { text: "−4",   type: "concept_error", logicTag: "partial_evaluation" },
    ],
    solutionSteps: [
      "(x+2) → x = −2.",
      "p(−2) = 3(−8) + 5(4) − 3(−2) + 2 = −24 + 20 + 6 + 2 = 4.",
    ],
    shortcut: "Be careful with signs when substituting negative values.",
    bloomLevel: "apply", conceptTested: "Remainder Theorem with negative root",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a09",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If (x − 2) and (x − 3) both divide p(x) evenly, which MUST also divide p(x)?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "(x − 6)",     type: "concept_error", logicTag: "product_of_roots" },
      { text: "(x − 1)",     type: "concept_error", logicTag: "wrong" },
      { text: "(x−2)(x−3)",  type: "correct",       logicTag: "product_of_factors" },
      { text: "(x + 1)",     type: "concept_error", logicTag: "sum_of_roots" },
    ],
    solutionSteps: [
      "If (x−2) | p(x) and (x−3) | p(x), and gcd(x−2, x−3) = 1,",
      "then (x−2)(x−3) | p(x).",
    ],
    shortcut: "If two coprime factors each divide p(x), their product also divides p(x).",
    bloomLevel: "analyse", conceptTested: "Divisibility by product of coprime factors",
  },
  {
    questionId: "ap_ssc9_ch2_remainder_a10",
    topicId: "ap_ssc_math9_ch2_remainder_theorem",
    topic: "Polynomials", subtopic: "Remainder Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If p(x) gives remainder 3 when divided by (x−1) and remainder 5 when divided by (x−2), what is the remainder when divided by (x−1)(x−2)?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "2x + 1",  type: "correct",       logicTag: "linear_remainder_form" },
      { text: "2x − 1",  type: "concept_error", logicTag: "sign_error" },
      { text: "3x + 5",  type: "concept_error", logicTag: "just_stated_remainders" },
      { text: "8",       type: "concept_error", logicTag: "sum_of_remainders" },
    ],
    solutionSteps: [
      "Remainder when dividing by degree-2 polynomial is linear: r(x) = ax + b.",
      "r(1) = a + b = 3 and r(2) = 2a + b = 5.",
      "Subtract: a = 2; b = 1.",
      "r(x) = 2x + 1.",
    ],
    shortcut: "Remainder ÷ degree-n = degree (n−1) polynomial; use given conditions to solve for coefficients.",
    bloomLevel: "evaluate", conceptTested: "Chinese Remainder Theorem for polynomials (intro)",
  },

  // ─────────────────────────────────────────────────────────
  // TOPIC 4: ap_ssc_math9_ch2_factor_theorem  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch2_factor_a01",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "(x − a) is a factor of p(x) if and only if:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "p(a) = 1",   type: "concept_error", logicTag: "wrong_value" },
      { text: "p(a) = a",   type: "concept_error", logicTag: "confused" },
      { text: "p(a) = 0",   type: "correct",       logicTag: "factor_theorem" },
      { text: "p(0) = a",   type: "concept_error", logicTag: "wrong_substitution" },
    ],
    solutionSteps: [
      "Factor Theorem: (x−a) is a factor of p(x) ↔ p(a) = 0.",
    ],
    shortcut: "Factor Theorem = Remainder Theorem with remainder = 0.",
    bloomLevel: "remember", conceptTested: "Statement of Factor Theorem",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a02",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Is (x − 2) a factor of x³ − 6x² + 11x − 6?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "No, because p(2) ≠ 0",   type: "concept_error", logicTag: "wrong_computation" },
      { text: "Yes, because p(2) = 0",  type: "correct",       logicTag: "factor_theorem_check" },
      { text: "Cannot determine",        type: "concept_error", logicTag: "unsure" },
      { text: "Yes, because degree = 3", type: "concept_error", logicTag: "wrong_reasoning" },
    ],
    solutionSteps: [
      "p(2) = 8 − 24 + 22 − 6 = 0.",
      "Since p(2) = 0, (x−2) is a factor.",
    ],
    shortcut: "Test p(root); if 0 → factor.",
    bloomLevel: "apply", conceptTested: "Checking factor using Factor Theorem",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a03",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If (x + 1) is a factor of p(x) = x³ + 2x² + k, then k =",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "2",    type: "concept_error", logicTag: "wrong" },
      { text: "−1",   type: "correct",       logicTag: "p(-1)=0" },
      { text: "1",    type: "concept_error", logicTag: "off_by_sign" },
      { text: "−3",   type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "(x+1) is a factor → p(−1) = 0.",
      "(−1)³ + 2(−1)² + k = −1 + 2 + k = 1 + k = 0 → k = −1.",
    ],
    shortcut: "Substitute root of factor, set = 0, solve.",
    bloomLevel: "apply", conceptTested: "Finding constant using Factor Theorem",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a04",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Factorize x² − 5x + 6 using the Factor Theorem.",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "(x−1)(x−6)",  type: "concept_error", logicTag: "wrong_factors" },
      { text: "(x−2)(x−3)",  type: "correct",       logicTag: "roots_2_and_3" },
      { text: "(x+2)(x+3)",  type: "concept_error", logicTag: "wrong_signs" },
      { text: "(x−1)(x−5)",  type: "concept_error", logicTag: "wrong_factors" },
    ],
    solutionSteps: [
      "Potential roots: ±1, ±2, ±3, ±6.",
      "p(2) = 4−10+6 = 0 ✓, p(3) = 9−15+6 = 0 ✓.",
      "x² − 5x + 6 = (x−2)(x−3).",
    ],
    shortcut: "Find rational roots, confirm with Factor Theorem, then write factors.",
    bloomLevel: "apply", conceptTested: "Factorising quadratic using Factor Theorem",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a05",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Factorize x³ − 6x² + 11x − 6.",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "(x−1)(x−2)(x−3)", type: "correct",       logicTag: "three_roots" },
      { text: "(x+1)(x+2)(x+3)", type: "concept_error", logicTag: "wrong_signs" },
      { text: "(x−1)(x−2)(x+3)", type: "concept_error", logicTag: "one_wrong_sign" },
      { text: "(x−2)(x²−4x+3)",  type: "concept_error", logicTag: "partially_factored" },
    ],
    solutionSteps: [
      "p(1)=0, p(2)=0, p(3)=0 — all three are roots.",
      "x³ − 6x² + 11x − 6 = (x−1)(x−2)(x−3).",
    ],
    shortcut: "Test rational roots systematically, then divide out factors.",
    bloomLevel: "apply", conceptTested: "Factorising cubic using Factor Theorem",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a06",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If both (x−2) and (x+3) are factors of p(x) = x² + ax + b, then a + b =",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "−5",  type: "concept_error", logicTag: "wrong" },
      { text: "1",   type: "concept_error", logicTag: "wrong" },
      { text: "−7",  type: "correct",       logicTag: "vieta_sum" },
      { text: "5",   type: "concept_error", logicTag: "wrong_sign" },
    ],
    solutionSteps: [
      "Roots are 2 and −3.",
      "Sum = 2 + (−3) = −1 = −a → a = 1.",
      "Product = 2 × (−3) = −6 = b → b = −6.",
      "a + b = 1 + (−6) = −5.",
      "Wait — recheck: p(x) = x² + ax + b. sum of roots = −a, product = b.",
      "−a = −1 → a = 1. b = −6. a + b = 1 − 6 = −5.",
    ],
    shortcut: "Use Vieta's: sum = −a, product = b for monic quadratic x² + ax + b.",
    bloomLevel: "analyse", conceptTested: "Finding coefficients from known roots",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a07",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Which is a factor of x³ + 1?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "(x − 1)",  type: "concept_error", logicTag: "p(1)=2_not_0" },
      { text: "(x + 1)",  type: "correct",       logicTag: "p(-1)=0" },
      { text: "(x + 2)",  type: "concept_error", logicTag: "p(-2)=-7" },
      { text: "(x − 2)",  type: "concept_error", logicTag: "p(2)=9" },
    ],
    solutionSteps: [
      "p(−1) = (−1)³ + 1 = −1 + 1 = 0 → (x+1) is a factor.",
      "In fact x³ + 1 = (x+1)(x² − x + 1).",
    ],
    shortcut: "For sum of cubes a³ + b³ = (a+b)(a²−ab+b²), factor (x+1) comes from x+1.",
    bloomLevel: "apply", conceptTested: "Factor theorem on sum of cubes",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a08",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If (2x − 1) is a factor of p(x) = 2x² − 7x + 3, the other factor is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "(x + 3)",   type: "concept_error", logicTag: "wrong_sign" },
      { text: "(x − 3)",   type: "correct",       logicTag: "polynomial_division" },
      { text: "(2x − 3)",  type: "concept_error", logicTag: "wrong_factor" },
      { text: "(x − 1)",   type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "2x² − 7x + 3 = (2x − 1)(x − 3) — check by expansion: 2x²−6x−x+3 = 2x²−7x+3. ✓",
    ],
    shortcut: "Divide p(x) by the known factor using polynomial long division or synthetic division.",
    bloomLevel: "apply", conceptTested: "Finding remaining factor by division",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a09",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "The value of k for which (x − 1) is a factor of 4x³ + 3x² − 4x + k is:",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "−3",  type: "correct",       logicTag: "p(1)=0" },
      { text: "3",   type: "concept_error", logicTag: "wrong_sign" },
      { text: "−7",  type: "concept_error", logicTag: "wrong" },
      { text: "7",   type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "p(1) = 4 + 3 − 4 + k = 3 + k = 0 → k = −3.",
    ],
    shortcut: "Factor Theorem: p(root) = 0 → solve for k.",
    bloomLevel: "apply", conceptTested: "Finding k for a given factor",
  },
  {
    questionId: "ap_ssc9_ch2_factor_a10",
    topicId: "ap_ssc_math9_ch2_factor_theorem",
    topic: "Polynomials", subtopic: "Factor Theorem",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Factorize 2x³ + x² − 5x + 2 completely.",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "(2x − 1)(x − 1)(x + 2)", type: "concept_error", logicTag: "wrong_factors" },
      { text: "(x − 1)(2x − 1)(x + 2)", type: "correct",       logicTag: "three_correct_factors" },
      { text: "(2x + 1)(x − 1)(x − 2)", type: "concept_error", logicTag: "wrong_signs" },
      { text: "(x + 1)(2x − 1)(x − 2)", type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "Test rational roots ±1, ±2, ±1/2.",
      "p(1) = 2+1−5+2 = 0 → (x−1) is factor.",
      "Divide: 2x³+x²−5x+2 ÷ (x−1) = 2x²+3x−2.",
      "Factor 2x²+3x−2 = (2x−1)(x+2).",
      "Complete: (x−1)(2x−1)(x+2).",
    ],
    shortcut: "Find one rational root first; divide; factor the remaining quadratic.",
    bloomLevel: "analyse", conceptTested: "Complete factorisation of cubic polynomial",
  },

  // ─────────────────────────────────────────────────────────
  // TOPIC 5: ap_ssc_math9_ch2_algebraic_identities  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch2_identity_a01",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "(a + b)² equals:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "a² + b²",        type: "concept_error", logicTag: "forgot_middle_term" },
      { text: "a² + 2ab + b²",  type: "correct",       logicTag: "square_of_sum" },
      { text: "a² − 2ab + b²",  type: "concept_error", logicTag: "sign_error" },
      { text: "2a + 2b",        type: "concept_error", logicTag: "linear_confusion" },
    ],
    solutionSteps: [
      "(a+b)² = a² + 2ab + b². Standard identity.",
    ],
    shortcut: "Square = first² + 2·(first)(last) + last².",
    bloomLevel: "remember", conceptTested: "Identity: (a+b)²",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a02",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "(a + b)(a − b) equals:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "a² + b²",   type: "concept_error", logicTag: "sign_wrong" },
      { text: "a² − b²",   type: "correct",       logicTag: "difference_of_squares" },
      { text: "2a",        type: "concept_error", logicTag: "wrong" },
      { text: "(a−b)²",    type: "concept_error", logicTag: "confused_identity" },
    ],
    solutionSteps: [
      "(a+b)(a−b) = a² − b². Difference of squares.",
    ],
    shortcut: "Conjugate product always gives difference of squares.",
    bloomLevel: "remember", conceptTested: "Identity: (a+b)(a−b)",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a03",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Using (a + b)², find (102)².",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "10040",  type: "concept_error", logicTag: "off_by_one" },
      { text: "10404",  type: "correct",       logicTag: "100plus2_squared" },
      { text: "10204",  type: "concept_error", logicTag: "forgot_cross_term_factor" },
      { text: "10200",  type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "102 = 100 + 2.",
      "(100+2)² = 10000 + 400 + 4 = 10404.",
    ],
    shortcut: "Near-round-number: use (100 ± n)² = 10000 ± 200n + n².",
    bloomLevel: "apply", conceptTested: "Applying (a+b)² to numerical computation",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a04",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "a³ + b³ equals:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "(a+b)(a²+ab+b²)",  type: "concept_error", logicTag: "wrong_middle_sign" },
      { text: "(a+b)³",           type: "concept_error", logicTag: "completely_wrong" },
      { text: "(a+b)(a²−ab+b²)",  type: "correct",       logicTag: "sum_of_cubes" },
      { text: "(a−b)(a²+ab+b²)",  type: "concept_error", logicTag: "difference_of_cubes" },
    ],
    solutionSteps: [
      "Sum of cubes: a³ + b³ = (a+b)(a²−ab+b²).",
      "Difference of cubes: a³ − b³ = (a−b)(a²+ab+b²).",
    ],
    shortcut: "Same sign | Opposite | Always Positive → SOAP for sum of cubes.",
    bloomLevel: "remember", conceptTested: "Identity: sum of cubes",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a05",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If x + 1/x = 3, what is x² + 1/x²?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "9",   type: "concept_error", logicTag: "squared_directly" },
      { text: "7",   type: "correct",       logicTag: "sq_minus_2" },
      { text: "11",  type: "concept_error", logicTag: "added_2" },
      { text: "6",   type: "concept_error", logicTag: "just_doubled" },
    ],
    solutionSteps: [
      "(x + 1/x)² = x² + 2 + 1/x².",
      "9 = x² + 2 + 1/x² → x² + 1/x² = 7.",
    ],
    shortcut: "x² + 1/x² = (x + 1/x)² − 2.",
    bloomLevel: "apply", conceptTested: "Using (a+b)² to find a²+b² from a+b",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a06",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Evaluate 99 × 101 using an algebraic identity.",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "9800",  type: "concept_error", logicTag: "wrong" },
      { text: "9999",  type: "correct",       logicTag: "difference_of_squares" },
      { text: "10000", type: "concept_error", logicTag: "forgot_subtract_1" },
      { text: "9801",  type: "concept_error", logicTag: "99_squared" },
    ],
    solutionSteps: [
      "99 × 101 = (100−1)(100+1) = 100² − 1² = 10000 − 1 = 9999.",
    ],
    shortcut: "(n−1)(n+1) = n² − 1. Quick mental math trick.",
    bloomLevel: "apply", conceptTested: "Difference of squares for mental multiplication",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a07",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "(a + b + c)² = a² + b² + c² + ______",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "ab + bc + ca",     type: "concept_error", logicTag: "missing_factor_2" },
      { text: "2(ab + bc + ca)",  type: "correct",       logicTag: "three_variable_square" },
      { text: "2ab + 2bc",        type: "concept_error", logicTag: "missing_ca_term" },
      { text: "4(ab + bc + ca)",  type: "concept_error", logicTag: "wrong_factor" },
    ],
    solutionSteps: [
      "(a+b+c)² = a²+b²+c²+2ab+2bc+2ca = a²+b²+c² + 2(ab+bc+ca).",
    ],
    shortcut: "Expand by treating (a+b+c) as one sum; each pair appears twice.",
    bloomLevel: "apply", conceptTested: "Identity: (a+b+c)²",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a08",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If a + b + c = 0, then a³ + b³ + c³ equals:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "0",       type: "concept_error", logicTag: "confused_with_sum" },
      { text: "3abc",    type: "correct",       logicTag: "identity_when_sum_zero" },
      { text: "abc",     type: "concept_error", logicTag: "wrong_coefficient" },
      { text: "3(a+b+c)", type: "concept_error", logicTag: "completely_wrong" },
    ],
    solutionSteps: [
      "Identity: a³+b³+c³ − 3abc = (a+b+c)(a²+b²+c²−ab−bc−ca).",
      "If a+b+c = 0, RHS = 0 → a³+b³+c³ = 3abc.",
    ],
    shortcut: "Whenever a+b+c = 0, use a³+b³+c³ = 3abc.",
    bloomLevel: "apply", conceptTested: "Identity: a³+b³+c³ when a+b+c=0",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a09",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "Factorize 8x³ + 27 using the sum of cubes identity.",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "(2x+3)(4x²+6x+9)",   type: "correct",       logicTag: "a=2x_b=3" },
      { text: "(2x+3)(4x²−6x+9)",   type: "concept_error", logicTag: "wrong_middle_sign" },
      { text: "(2x−3)(4x²+6x+9)",   type: "concept_error", logicTag: "wrong_sign" },
      { text: "(8x+27)(x²−x+1)",    type: "concept_error", logicTag: "wrong_factorisation" },
    ],
    solutionSteps: [
      "8x³ = (2x)³, 27 = 3³.",
      "a³+b³ = (a+b)(a²−ab+b²) with a=2x, b=3.",
      "= (2x+3)((2x)²−(2x)(3)+3²) = (2x+3)(4x²−6x+9).",
      "Wait — middle term: a²−ab+b² = 4x²−6x+9.",
      "Answer: (2x+3)(4x²−6x+9).",
    ],
    shortcut: "a³+b³ = (a+b)(a²−ab+b²). Identify a and b first.",
    bloomLevel: "apply", conceptTested: "Factorising sum of cubes",
  },
  {
    questionId: "ap_ssc9_ch2_identity_a10",
    topicId: "ap_ssc_math9_ch2_algebraic_identities",
    topic: "Polynomials", subtopic: "Algebraic Identities",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 2,
    questionText: "If x − y = 5 and xy = 6, what is x³ − y³?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "95",   type: "concept_error", logicTag: "wrong" },
      { text: "155",  type: "correct",       logicTag: "difference_of_cubes_identity" },
      { text: "125",  type: "concept_error", logicTag: "5_cubed" },
      { text: "143",  type: "concept_error", logicTag: "wrong" },
    ],
    solutionSteps: [
      "x³−y³ = (x−y)(x²+xy+y²).",
      "Need x²+y² = (x−y)² + 2xy = 25 + 12 = 37.",
      "x²+xy+y² = 37 + 6 = 43.",
      "x³−y³ = 5 × 43 = 215.",
      "Recheck: (x−y)³ = x³−3x²y+3xy²−y³. Let me use identity directly:",
      "x³−y³ = (x−y)[(x−y)²+3xy] = 5[25+18] = 5×43 = 215.",
    ],
    shortcut: "x³−y³ = (x−y)[(x−y)²+3xy] — avoids finding x²+y² separately.",
    bloomLevel: "analyse", conceptTested: "Applying difference of cubes identity",
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  let upserted = 0, skipped = 0;
  for (const q of questions) {
    try {
      await Question.findOneAndUpdate(
        { questionId: q.questionId },
        { $set: q },
        { upsert: true, new: true }
      );
      console.log(`  ✓ ${q.questionId}`);
      upserted++;
    } catch (err) {
      if (err.code === 11000) { console.log(`  — skip ${q.questionId}`); skipped++; }
      else throw err;
    }
  }
  console.log(`\nDone. Upserted: ${upserted}  Skipped: ${skipped}`);
  await mongoose.disconnect();
  process.exit(0);
}
run().catch(err => { console.error(err); process.exit(1); });
