import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";
dotenv.config();

const questions = [
  // math2_ch1_long_vs_round — 8 questions
  { questionId:"math2_ch1_lvr_q1", topicId:"math2_ch1_long_vs_round", text:"Which of these objects is round?", options:[{text:"Pencil",type:"concept_error"},{text:"Ruler",type:"concept_error"},{text:"Ball",type:"correct"},{text:"Book",type:"misinterpretation"}], explanation:"A ball is round — it curves all the way around.", solutionSteps:["Round objects curve continuously","A ball has one curved surface — it is round"], shortcut:"Round objects can roll in any direction.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_lvr_q2", topicId:"math2_ch1_long_vs_round", text:"Which object is long and thin?", options:[{text:"Orange",type:"concept_error"},{text:"Marble",type:"concept_error"},{text:"Pencil",type:"correct"},{text:"Coin",type:"misinterpretation"}], explanation:"A pencil is long and thin.", solutionSteps:["Long objects are much longer than they are wide","A pencil fits this description"], shortcut:"Long = much taller or wider than thick.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_lvr_q3", topicId:"math2_ch1_long_vs_round", text:"A ball and a box are on a slope. What happens?", options:[{text:"Both roll",type:"concept_error"},{text:"Both stay still",type:"concept_error"},{text:"Ball rolls, box stays",type:"correct"},{text:"Box rolls, ball stays",type:"misinterpretation"}], explanation:"A ball has a curved surface so it rolls. A box has flat surfaces so it slides or stays.", solutionSteps:["Curved surface → rolls","Flat surface → stays or slides"], shortcut:"Curved = rolls. Flat = slides.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_lvr_q4", topicId:"math2_ch1_long_vs_round", text:"Which is the correct description of a banana?", options:[{text:"Round",type:"concept_error"},{text:"Long and curved",type:"correct"},{text:"Flat",type:"misinterpretation"},{text:"Square",type:"guessing"}], explanation:"A banana is long and curved, not perfectly round like a ball.", solutionSteps:["Banana extends in length → long","Banana bends → curved"], shortcut:"'Curved' describes the bend; 'long' describes the length.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_lvr_q5", topicId:"math2_ch1_long_vs_round", text:"Sita has a coin and a pencil. Which is long?", options:[{text:"Coin",type:"concept_error"},{text:"Pencil",type:"correct"},{text:"Both",type:"misinterpretation"},{text:"Neither",type:"guessing"}], explanation:"A pencil is long. A coin is flat and round.", solutionSteps:["Pencil: much longer than wide → long","Coin: thin and circular → not long"], shortcut:"If it's much taller/wider than thick = long.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_lvr_q6", topicId:"math2_ch1_long_vs_round", text:"Which word describes a globe (Earth model)?", options:[{text:"Long",type:"concept_error"},{text:"Flat",type:"misinterpretation"},{text:"Round",type:"correct"},{text:"Square",type:"guessing"}], explanation:"A globe is a sphere — it is round, curving all the way around.", solutionSteps:["Globe = sphere → curved all around → round"], shortcut:"Sphere = round.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_lvr_q7", topicId:"math2_ch1_long_vs_round", text:"A broomstick and a ball: what are their shapes?", options:[{text:"Both round",type:"concept_error"},{text:"Both long",type:"concept_error"},{text:"Broomstick long, ball round",type:"correct"},{text:"Broomstick round, ball long",type:"misinterpretation"}], explanation:"A broomstick is long and thin. A ball is round.", solutionSteps:["Broomstick → long","Ball → round"], shortcut:"Compare to familiar objects: stick = long, ball = round.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_lvr_q8", topicId:"math2_ch1_long_vs_round", text:"Which of these is NOT round?", options:[{text:"Ball",type:"misinterpretation"},{text:"Marble",type:"misinterpretation"},{text:"Globe",type:"misinterpretation"},{text:"Pencil",type:"correct"}], explanation:"A pencil is long, not round. Ball, marble, and globe are all round (sphere-shaped).", solutionSteps:["Check each: ball=round, marble=round, globe=round, pencil=long"], shortcut:"Pencil cannot roll in all directions — it is not round.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },

  // math2_ch1_rolling_sliding — 8 questions
  { questionId:"math2_ch1_rs_q1", topicId:"math2_ch1_rolling_sliding", text:"Which shape rolls the easiest?", options:[{text:"Cube",type:"concept_error"},{text:"Cuboid",type:"concept_error"},{text:"Sphere",type:"correct"},{text:"Cone",type:"partial_logic"}], explanation:"A sphere (ball) rolls in any direction because its entire surface is curved.", solutionSteps:["Sphere = curved all around → rolls in any direction"], shortcut:"Sphere rolls in all directions; cone rolls in circles.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_rs_q2", topicId:"math2_ch1_rolling_sliding", text:"A wooden block is pushed on a table. What does it do?", options:[{text:"Rolls",type:"concept_error"},{text:"Slides",type:"correct"},{text:"Both rolls and slides",type:"partial_logic"},{text:"Neither",type:"guessing"}], explanation:"A cube/block has flat surfaces — it slides, not rolls.", solutionSteps:["Flat surface → slides","No curved surface → cannot roll"], shortcut:"Flat = slides.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_rs_q3", topicId:"math2_ch1_rolling_sliding", text:"A tin can (cylinder) is placed on its curved side and pushed. What happens?", options:[{text:"It rolls in a straight line",type:"correct"},{text:"It rolls in circles",type:"concept_error"},{text:"It slides",type:"misinterpretation"},{text:"Nothing",type:"guessing"}], explanation:"A cylinder rolls in a straight line along its curved surface.", solutionSteps:["Cylinder: curved side → rolls","Rolls straight because the diameter is constant"], shortcut:"Cylinder → straight roll.", difficulty:"medium", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_rs_q4", topicId:"math2_ch1_rolling_sliding", text:"A cone placed on its curved side rolls in which shape?", options:[{text:"Straight line",type:"concept_error"},{text:"Circle",type:"correct"},{text:"Zigzag",type:"misinterpretation"},{text:"Does not roll",type:"guessing"}], explanation:"A cone rolls in a circle because one end is pointed and the other is wider.", solutionSteps:["Cone: pointed tip one end, wider circle other end → rolls in a circle"], shortcut:"Cone rolls in a circle (its path curves).", difficulty:"medium", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_rs_q5", topicId:"math2_ch1_rolling_sliding", text:"Which shape both rolls AND slides?", options:[{text:"Cube",type:"concept_error"},{text:"Sphere",type:"concept_error"},{text:"Cylinder",type:"correct"},{text:"Cuboid",type:"misinterpretation"}], explanation:"A cylinder has two flat faces (can slide) and one curved surface (can roll).", solutionSteps:["Cylinder: flat circles → can slide (stand on end)","Curved surface → can roll"], shortcut:"Flat face = can slide; curved surface = can roll. Cylinder has both.", difficulty:"medium", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_rs_q6", topicId:"math2_ch1_rolling_sliding", text:"Which objects roll? (Choose the best answer)", options:[{text:"Dice and book",type:"concept_error"},{text:"Ball and orange",type:"correct"},{text:"Box and tin",type:"concept_error"},{text:"Ruler and pen",type:"misinterpretation"}], explanation:"Ball and orange are both spherical and will roll because of their curved surfaces.", solutionSteps:["Ball = sphere → rolls","Orange ≈ sphere → rolls"], shortcut:"Spherical/round objects roll.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_rs_q7", topicId:"math2_ch1_rolling_sliding", text:"Why does a book not roll?", options:[{text:"Because it is heavy",type:"concept_error"},{text:"Because it has only flat surfaces",type:"correct"},{text:"Because it is made of paper",type:"misinterpretation"},{text:"Because it is long",type:"guessing"}], explanation:"A book has only flat surfaces, which slide but don't roll.", solutionSteps:["Flat surface only → no rolling possible → slides"], shortcut:"No curved surface = cannot roll.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_rs_q8", topicId:"math2_ch1_rolling_sliding", text:"Riya pushes a ball and Sana pushes a box. Who's object rolls away?", options:[{text:"Sana's box",type:"concept_error"},{text:"Riya's ball",type:"correct"},{text:"Both",type:"misinterpretation"},{text:"Neither",type:"guessing"}], explanation:"Riya's ball rolls; Sana's box slides.", solutionSteps:["Ball = curved → rolls","Box = flat → slides"], shortcut:"Curved = rolls away; flat = slides away.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },

  // math2_ch1_flat_vs_curved — 8 questions
  { questionId:"math2_ch1_fvc_q1", topicId:"math2_ch1_flat_vs_curved", text:"How many flat faces does a cube have?", options:[{text:"2",type:"concept_error"},{text:"4",type:"calculation_error"},{text:"6",type:"correct"},{text:"8",type:"misinterpretation"}], explanation:"A cube has 6 flat square faces.", solutionSteps:["Cube: top, bottom, front, back, left, right = 6 flat faces"], shortcut:"Cube = 6 flat square faces.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_fvc_q2", topicId:"math2_ch1_flat_vs_curved", text:"How many curved surfaces does a sphere have?", options:[{text:"0",type:"concept_error"},{text:"1",type:"correct"},{text:"2",type:"calculation_error"},{text:"6",type:"guessing"}], explanation:"A sphere has exactly 1 curved surface — the entire outer surface.", solutionSteps:["Sphere: no flat faces, 1 continuous curved surface"], shortcut:"Sphere = 1 curved surface, 0 flat.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_fvc_q3", topicId:"math2_ch1_flat_vs_curved", text:"A cylinder has __ flat faces and __ curved surface(s).", options:[{text:"0 flat, 1 curved",type:"concept_error"},{text:"2 flat, 1 curved",type:"correct"},{text:"2 flat, 2 curved",type:"calculation_error"},{text:"6 flat, 0 curved",type:"misinterpretation"}], explanation:"A cylinder has 2 flat circular faces (top and bottom) and 1 curved surface.", solutionSteps:["Cylinder: 2 circles (top/bottom) = 2 flat faces","Curved rectangular-wrap = 1 curved surface"], shortcut:"Cylinder = 2 flat + 1 curved.", difficulty:"medium", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_fvc_q4", topicId:"math2_ch1_flat_vs_curved", text:"Which shape has NO flat faces at all?", options:[{text:"Cube",type:"concept_error"},{text:"Cylinder",type:"concept_error"},{text:"Sphere",type:"correct"},{text:"Cone",type:"partial_logic"}], explanation:"A sphere has only 1 curved surface and zero flat faces.", solutionSteps:["Sphere: all curved, no flat face"], shortcut:"Sphere = 0 flat, 1 curved.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_fvc_q5", topicId:"math2_ch1_flat_vs_curved", text:"A cone has __ flat face(s) and __ curved surface(s).", options:[{text:"0 flat, 2 curved",type:"concept_error"},{text:"1 flat, 1 curved",type:"correct"},{text:"2 flat, 1 curved",type:"calculation_error"},{text:"1 flat, 0 curved",type:"misinterpretation"}], explanation:"A cone has 1 flat circular base and 1 curved surface (the pointed side).", solutionSteps:["Cone: bottom circle = 1 flat face","Pointed side = 1 curved surface"], shortcut:"Cone = 1 flat + 1 curved.", difficulty:"medium", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_fvc_q6", topicId:"math2_ch1_flat_vs_curved", text:"If you press a cube into clay, what shape is the footprint?", options:[{text:"Circle",type:"concept_error"},{text:"Triangle",type:"misinterpretation"},{text:"Square",type:"correct"},{text:"Hexagon",type:"guessing"}], explanation:"A cube's face is a square, so its footprint in clay is a square.", solutionSteps:["Cube face = square → footprint = square"], shortcut:"Footprint = shape of the face that touches the clay.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_fvc_q7", topicId:"math2_ch1_flat_vs_curved", text:"A cuboid (box) has __ flat faces.", options:[{text:"4",type:"calculation_error"},{text:"5",type:"calculation_error"},{text:"6",type:"correct"},{text:"8",type:"misinterpretation"}], explanation:"A cuboid has 6 rectangular flat faces.", solutionSteps:["Top, bottom, front, back, left, right = 6 faces"], shortcut:"Like a cube: 6 faces, but rectangles not squares.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_fvc_q8", topicId:"math2_ch1_flat_vs_curved", text:"Which shape has BOTH flat and curved surfaces?", options:[{text:"Sphere",type:"concept_error"},{text:"Cube",type:"concept_error"},{text:"Cylinder",type:"correct"},{text:"Both sphere and cube",type:"misinterpretation"}], explanation:"A cylinder has 2 flat circular faces AND 1 curved surface.", solutionSteps:["Flat: top and bottom circles","Curved: the rounded side"], shortcut:"Cylinder: flat circles on ends, curved in middle.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },

  // math2_ch1_3d_shapes — 8 questions
  { questionId:"math2_ch1_3ds_q1", topicId:"math2_ch1_3d_shapes", text:"What is the real-world example of a sphere?", options:[{text:"Book",type:"concept_error"},{text:"Ball",type:"correct"},{text:"Tin can",type:"misinterpretation"},{text:"Ice cream cone",type:"concept_error"}], explanation:"A ball is a sphere — curved all around with no flat faces.", solutionSteps:["Ball: round, curves all around → sphere"], shortcut:"Ball = sphere.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_3ds_q2", topicId:"math2_ch1_3d_shapes", text:"A dice is an example of which 3D shape?", options:[{text:"Sphere",type:"concept_error"},{text:"Cylinder",type:"misinterpretation"},{text:"Cube",type:"correct"},{text:"Cone",type:"guessing"}], explanation:"A dice has 6 equal square faces — it is a cube.", solutionSteps:["Dice: 6 square faces, all equal → cube"], shortcut:"Dice = cube (6 equal square faces).", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_3ds_q3", topicId:"math2_ch1_3d_shapes", text:"Which 3D shape looks like an ice cream cone?", options:[{text:"Cube",type:"concept_error"},{text:"Cylinder",type:"misinterpretation"},{text:"Sphere",type:"concept_error"},{text:"Cone",type:"correct"}], explanation:"An ice cream cone has a circular base and a pointed top — it is a cone shape.", solutionSteps:["Circular base + pointed top = cone"], shortcut:"Ice cream cone shape = cone.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_3ds_q4", topicId:"math2_ch1_3d_shapes", text:"A drum (dholak) is shaped like which 3D object?", options:[{text:"Sphere",type:"concept_error"},{text:"Cylinder",type:"correct"},{text:"Cube",type:"misinterpretation"},{text:"Cone",type:"guessing"}], explanation:"A drum has two circular ends and a curved side — it is a cylinder.", solutionSteps:["Drum: circular ends + curved body → cylinder"], shortcut:"Cylindrical objects: tin can, drum, bottle.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_3ds_q5", topicId:"math2_ch1_3d_shapes", text:"A cereal box is shaped like a ___.", options:[{text:"Cube",type:"partial_logic"},{text:"Cuboid",type:"correct"},{text:"Cylinder",type:"concept_error"},{text:"Sphere",type:"guessing"}], explanation:"A cereal box has 6 rectangular faces — it is a cuboid.", solutionSteps:["Box: rectangle faces, not all equal → cuboid"], shortcut:"Box shape = cuboid (rectangle faces).", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_3ds_q6", topicId:"math2_ch1_3d_shapes", text:"How many corners (vertices) does a cube have?", options:[{text:"4",type:"concept_error"},{text:"6",type:"concept_error"},{text:"8",type:"correct"},{text:"12",type:"misinterpretation"}], explanation:"A cube has 8 corners (vertices) — one at each corner of the 3D box.", solutionSteps:["Cube: 4 corners on top face + 4 corners on bottom face = 8"], shortcut:"Cube: 6 faces, 12 edges, 8 vertices.", difficulty:"medium", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_3ds_q7", topicId:"math2_ch1_3d_shapes", text:"Which shape has NO corners at all?", options:[{text:"Cube",type:"concept_error"},{text:"Cuboid",type:"concept_error"},{text:"Cone",type:"partial_logic"},{text:"Sphere",type:"correct"}], explanation:"A sphere has no corners (vertices) and no edges — just a smooth curved surface.", solutionSteps:["Sphere: 1 curved surface, 0 flat faces, 0 corners"], shortcut:"Sphere = no corners, no edges.", difficulty:"easy", subject:"Math", grade:2, chapter:1 },
  { questionId:"math2_ch1_3ds_q8", topicId:"math2_ch1_3d_shapes", text:"Riya says 'A square is a 3D shape'. Is she correct?", options:[{text:"Yes, all shapes are 3D",type:"concept_error"},{text:"No, a square is a 2D shape; a cube is the 3D version",type:"correct"},{text:"Yes, because it has corners",type:"misinterpretation"},{text:"No, squares don't exist",type:"guessing"}], explanation:"A square is flat (2D). The 3D version with 6 equal square faces is a cube.", solutionSteps:["2D: flat on paper → square","3D: solid you can hold → cube"], shortcut:"Square = 2D. Cube = 3D square.", difficulty:"medium", subject:"Math", grade:2, chapter:1 },

  // math2_ch2_counting_by_2s — 8 questions
  { questionId:"math2_ch2_cb2_q1", topicId:"math2_ch2_counting_by_2s", text:"Count by 2s: 2, 4, 6, __, 10. What is missing?", options:[{text:"7",type:"concept_error"},{text:"9",type:"misinterpretation"},{text:"8",type:"correct"},{text:"6",type:"partial_logic"}], explanation:"Counting by 2s: 2, 4, 6, 8, 10. Missing = 8.", solutionSteps:["Each step +2","6+2=8"], shortcut:"Even number sequence: +2 each time.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb2_q2", topicId:"math2_ch2_counting_by_2s", text:"How many shoes do 4 children have? (Each child has 2 shoes.)", options:[{text:"4",type:"concept_error"},{text:"6",type:"calculation_error"},{text:"8",type:"correct"},{text:"10",type:"calculation_error"}], explanation:"4 children × 2 shoes each = count by 2s four times: 2, 4, 6, 8.", solutionSteps:["Count by 2s: 2, 4, 6, 8","4 pairs = 8 shoes"], shortcut:"Groups of 2 → skip-count by 2.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb2_q3", topicId:"math2_ch2_counting_by_2s", text:"Which number comes next: 12, 14, 16, __?", options:[{text:"17",type:"concept_error"},{text:"18",type:"correct"},{text:"20",type:"calculation_error"},{text:"15",type:"misinterpretation"}], explanation:"Counting by 2s: 16+2=18.", solutionSteps:["+2 each step","16+2=18"], shortcut:"Always even, always +2.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb2_q4", topicId:"math2_ch2_counting_by_2s", text:"Is 14 in the count-by-2s sequence?", options:[{text:"No, 14 is odd",type:"concept_error"},{text:"Yes, 14 is even",type:"correct"},{text:"No, 14 is too big",type:"misinterpretation"},{text:"Cannot tell",type:"guessing"}], explanation:"14 ends in 4 (even), so it IS in the count-by-2s sequence.", solutionSteps:["Count-by-2s gives even numbers","14 ends in 4 → even → yes"], shortcut:"Last digit 0/2/4/6/8 → in count-by-2s.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb2_q5", topicId:"math2_ch2_counting_by_2s", text:"What is the 6th number when counting by 2s starting from 2?", options:[{text:"10",type:"calculation_error"},{text:"12",type:"correct"},{text:"14",type:"calculation_error"},{text:"8",type:"calculation_error"}], explanation:"2, 4, 6, 8, 10, 12 — the 6th number is 12.", solutionSteps:["List: 2(1), 4(2), 6(3), 8(4), 10(5), 12(6)","6th term = 12"], shortcut:"6th even number = 2×6=12.", difficulty:"medium", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb2_q6", topicId:"math2_ch2_counting_by_2s", text:"Count by 2s backwards from 10: 10, 8, __, 4, 2.", options:[{text:"5",type:"concept_error"},{text:"7",type:"concept_error"},{text:"6",type:"correct"},{text:"9",type:"misinterpretation"}], explanation:"Counting backwards by 2s: 10, 8, 6, 4, 2.", solutionSteps:["8−2=6"], shortcut:"Backwards by 2: subtract 2 each step.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb2_q7", topicId:"math2_ch2_counting_by_2s", text:"How many legs do 5 birds have? (Each bird has 2 legs.)", options:[{text:"7",type:"concept_error"},{text:"10",type:"correct"},{text:"8",type:"calculation_error"},{text:"12",type:"calculation_error"}], explanation:"5 × 2 = count by 2s five times: 2, 4, 6, 8, 10.", solutionSteps:["5 birds × 2 legs = 10 legs"], shortcut:"Skip count by 2 five times.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb2_q8", topicId:"math2_ch2_counting_by_2s", text:"Which number does NOT belong: 4, 6, 7, 8, 10?", options:[{text:"4",type:"misinterpretation"},{text:"6",type:"misinterpretation"},{text:"7",type:"correct"},{text:"10",type:"misinterpretation"}], explanation:"7 is odd — it does not appear in the count-by-2s sequence.", solutionSteps:["Count-by-2s: even numbers only","7 is odd → does not belong"], shortcut:"Odd numbers never appear when counting by 2s from 2.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },

  // math2_ch2_counting_by_5s — 8 questions
  { questionId:"math2_ch2_cb5_q1", topicId:"math2_ch2_counting_by_5s", text:"Count by 5s: 5, 10, __, 20, 25. What is missing?", options:[{text:"12",type:"concept_error"},{text:"16",type:"calculation_error"},{text:"15",type:"correct"},{text:"18",type:"misinterpretation"}], explanation:"Counting by 5s: 5, 10, 15, 20, 25. Missing = 15.", solutionSteps:["Each step +5","10+5=15"], shortcut:"Multiples of 5 end in 0 or 5.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb5_q2", topicId:"math2_ch2_counting_by_5s", text:"3 packets each have 5 biscuits. How many biscuits in all?", options:[{text:"8",type:"concept_error"},{text:"10",type:"calculation_error"},{text:"15",type:"correct"},{text:"20",type:"calculation_error"}], explanation:"3 × 5 = count by 5s three times: 5, 10, 15.", solutionSteps:["Count by 5s: 5, 10, 15","3 packets → 15 biscuits"], shortcut:"Groups of 5 → skip-count by 5.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb5_q3", topicId:"math2_ch2_counting_by_5s", text:"Which number is in the count-by-5s pattern?", options:[{text:"13",type:"concept_error"},{text:"22",type:"concept_error"},{text:"35",type:"correct"},{text:"38",type:"misinterpretation"}], explanation:"35 ends in 5, so it is a multiple of 5 and appears in the count-by-5s pattern.", solutionSteps:["Multiples of 5 end in 0 or 5","35 ends in 5 → belongs"], shortcut:"Ends in 0 or 5 → multiple of 5.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb5_q4", topicId:"math2_ch2_counting_by_5s", text:"What comes after 45 when counting by 5s?", options:[{text:"46",type:"concept_error"},{text:"48",type:"misinterpretation"},{text:"50",type:"correct"},{text:"55",type:"calculation_error"}], explanation:"45+5=50.", solutionSteps:["45+5=50"], shortcut:"+5 each step.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb5_q5", topicId:"math2_ch2_counting_by_5s", text:"How many fingers do 4 children have? (Each child has 5 fingers on one hand.)", options:[{text:"9",type:"concept_error"},{text:"15",type:"calculation_error"},{text:"20",type:"correct"},{text:"25",type:"calculation_error"}], explanation:"4 children × 5 fingers = count by 5s four times: 5, 10, 15, 20.", solutionSteps:["5, 10, 15, 20 — 4th step = 20"], shortcut:"4 groups of 5 = 20.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb5_q6", topicId:"math2_ch2_counting_by_5s", text:"Which number is NOT a multiple of 5?", options:[{text:"10",type:"misinterpretation"},{text:"25",type:"misinterpretation"},{text:"18",type:"correct"},{text:"40",type:"misinterpretation"}], explanation:"18 does not end in 0 or 5, so it is not a multiple of 5.", solutionSteps:["10✓ 25✓ 18✗ 40✓","18 ends in 8 → not multiple of 5"], shortcut:"Last digit not 0 or 5 → NOT multiple of 5.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb5_q7", topicId:"math2_ch2_counting_by_5s", text:"Count by 5s starting at 0: 0, 5, 10, 15, 20, __", options:[{text:"22",type:"concept_error"},{text:"24",type:"calculation_error"},{text:"25",type:"correct"},{text:"30",type:"calculation_error"}], explanation:"20+5=25.", solutionSteps:["20+5=25"], shortcut:"+5 each step regardless of starting point.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb5_q8", topicId:"math2_ch2_counting_by_5s", text:"What is the 8th number in the count-by-5s sequence starting from 5?", options:[{text:"35",type:"calculation_error"},{text:"40",type:"correct"},{text:"45",type:"calculation_error"},{text:"50",type:"calculation_error"}], explanation:"5×8=40. The 8th multiple of 5 is 40.", solutionSteps:["5, 10, 15, 20, 25, 30, 35, 40","8th term = 40"], shortcut:"nth term = n×5.", difficulty:"medium", subject:"Math", grade:2, chapter:2 },

  // math2_ch2_counting_by_10s — 8 questions
  { questionId:"math2_ch2_cb10_q1", topicId:"math2_ch2_counting_by_10s", text:"Count by 10s: 10, 20, __, 40, 50. What is missing?", options:[{text:"25",type:"concept_error"},{text:"35",type:"misinterpretation"},{text:"30",type:"correct"},{text:"45",type:"calculation_error"}], explanation:"Counting by 10s: 10, 20, 30, 40, 50. Missing = 30.", solutionSteps:["20+10=30"], shortcut:"+10 each step; ones digit stays 0.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb10_q2", topicId:"math2_ch2_counting_by_10s", text:"You have 7 packets each with 10 toffees. How many toffees in all?", options:[{text:"17",type:"concept_error"},{text:"60",type:"calculation_error"},{text:"70",type:"correct"},{text:"80",type:"calculation_error"}], explanation:"7 × 10 = 70. Count by 10s seven times: 10, 20, 30, 40, 50, 60, 70.", solutionSteps:["Count by 10 seven times → 70"], shortcut:"groups×10 = answer.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb10_q3", topicId:"math2_ch2_counting_by_10s", text:"What comes next: 60, 70, 80, __?", options:[{text:"85",type:"concept_error"},{text:"88",type:"calculation_error"},{text:"90",type:"correct"},{text:"100",type:"calculation_error"}], explanation:"80+10=90.", solutionSteps:["80+10=90"], shortcut:"+10 → tens digit increases by 1.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb10_q4", topicId:"math2_ch2_counting_by_10s", text:"Which number is a multiple of 10?", options:[{text:"35",type:"concept_error"},{text:"42",type:"misinterpretation"},{text:"50",type:"correct"},{text:"57",type:"guessing"}], explanation:"50 ends in 0, so it is a multiple of 10.", solutionSteps:["Multiples of 10 end in 0","50 ends in 0 → multiple of 10"], shortcut:"Multiples of 10 always end in 0.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb10_q5", topicId:"math2_ch2_counting_by_10s", text:"Count back by 10s: 90, 80, __, 60, 50.", options:[{text:"65",type:"concept_error"},{text:"75",type:"misinterpretation"},{text:"70",type:"correct"},{text:"85",type:"calculation_error"}], explanation:"80−10=70.", solutionSteps:["80−10=70"], shortcut:"Backwards by 10: subtract 10.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb10_q6", topicId:"math2_ch2_counting_by_10s", text:"There are 4 bundles of 10 sticks. How many sticks?", options:[{text:"14",type:"concept_error"},{text:"30",type:"calculation_error"},{text:"40",type:"correct"},{text:"44",type:"misinterpretation"}], explanation:"4 × 10 = 40.", solutionSteps:["4 bundles × 10 sticks each = 40 sticks"], shortcut:"Bundles of 10: count by 10 as many times as bundles.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb10_q7", topicId:"math2_ch2_counting_by_10s", text:"Which is the 5th number when counting by 10s from 10?", options:[{text:"40",type:"calculation_error"},{text:"50",type:"correct"},{text:"55",type:"misinterpretation"},{text:"60",type:"calculation_error"}], explanation:"10×5=50. The 5th multiple of 10 is 50.", solutionSteps:["10, 20, 30, 40, 50 — 5th term = 50"], shortcut:"nth term = n×10.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_cb10_q8", topicId:"math2_ch2_counting_by_10s", text:"What is 30 + 10 + 10?", options:[{text:"40",type:"calculation_error"},{text:"50",type:"correct"},{text:"60",type:"calculation_error"},{text:"310",type:"concept_error"}], explanation:"30+10=40, 40+10=50.", solutionSteps:["30+10=40","40+10=50"], shortcut:"Add 10 twice = add 20.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },

  // math2_ch2_odd_and_even — 8 questions
  { questionId:"math2_ch2_oae_q1", topicId:"math2_ch2_odd_and_even", text:"Is 14 an odd or even number?", options:[{text:"Odd",type:"concept_error"},{text:"Even",type:"correct"},{text:"Both",type:"misinterpretation"},{text:"Neither",type:"guessing"}], explanation:"14 ends in 4 (an even digit), so 14 is even.", solutionSteps:["14 ends in 4","0/2/4/6/8 → even"], shortcut:"Check last digit only.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_oae_q2", topicId:"math2_ch2_odd_and_even", text:"Is 7 odd or even?", options:[{text:"Even",type:"concept_error"},{text:"Odd",type:"correct"},{text:"Both",type:"misinterpretation"},{text:"Neither",type:"guessing"}], explanation:"7 ends in 7 (an odd digit), so 7 is odd.", solutionSteps:["7 ends in 7","1/3/5/7/9 → odd"], shortcut:"Odd last digit = odd number.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_oae_q3", topicId:"math2_ch2_odd_and_even", text:"You have 9 marbles. Can you put them in pairs with none left over?", options:[{text:"Yes",type:"concept_error"},{text:"No",type:"correct"},{text:"Only if we add one",type:"partial_logic"},{text:"Depends on colour",type:"guessing"}], explanation:"9 is odd — 4 pairs with 1 left over. Cannot pair perfectly.", solutionSteps:["9 ÷ 2 = 4 remainder 1 → one left over → odd"], shortcut:"Odd numbers cannot pair perfectly — one is always left.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_oae_q4", topicId:"math2_ch2_odd_and_even", text:"Which of these is an even number?", options:[{text:"13",type:"concept_error"},{text:"17",type:"concept_error"},{text:"20",type:"correct"},{text:"25",type:"misinterpretation"}], explanation:"20 ends in 0 (even). 13, 17, 25 end in odd digits.", solutionSteps:["20 ends in 0 → even","Others end in odd digits"], shortcut:"20 ends in 0 → even.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_oae_q5", topicId:"math2_ch2_odd_and_even", text:"Is 0 even or odd?", options:[{text:"Odd",type:"concept_error"},{text:"Even",type:"correct"},{text:"Neither",type:"misinterpretation"},{text:"Cannot say",type:"guessing"}], explanation:"0 is even — it can be paired zero times with none left over.", solutionSteps:["0 ÷ 2 = 0 with remainder 0 → even"], shortcut:"0 is always even.", difficulty:"medium", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_oae_q6", topicId:"math2_ch2_odd_and_even", text:"Which is the odd number in: 12, 15, 18, 20?", options:[{text:"12",type:"misinterpretation"},{text:"15",type:"correct"},{text:"18",type:"misinterpretation"},{text:"20",type:"misinterpretation"}], explanation:"15 ends in 5 (odd). 12, 18, 20 end in even digits.", solutionSteps:["12→even, 15→odd, 18→even, 20→even"], shortcut:"15 ends in 5 → odd.", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_oae_q7", topicId:"math2_ch2_odd_and_even", text:"Even number + Even number = ?", options:[{text:"Always odd",type:"concept_error"},{text:"Always even",type:"correct"},{text:"Can be either",type:"misinterpretation"},{text:"Always zero",type:"guessing"}], explanation:"Even + Even = Even. Example: 4+6=10 (even).", solutionSteps:["4+6=10 (even)","6+8=14 (even)"], shortcut:"Even + Even = Even. (Odd + Odd = Even too.)", difficulty:"medium", subject:"Math", grade:2, chapter:2 },
  { questionId:"math2_ch2_oae_q8", topicId:"math2_ch2_odd_and_even", text:"How many even numbers are there between 1 and 10?", options:[{text:"4",type:"calculation_error"},{text:"5",type:"correct"},{text:"6",type:"calculation_error"},{text:"3",type:"guessing"}], explanation:"Even numbers between 1 and 10: 2, 4, 6, 8, 10 → 5 numbers.", solutionSteps:["2, 4, 6, 8, 10 — count = 5"], shortcut:"Between 1–10: exactly 5 even numbers (2,4,6,8,10).", difficulty:"easy", subject:"Math", grade:2, chapter:2 },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  let inserted = 0;
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
    console.log(`  ✓ ${q.questionId}`);
    inserted++;
  }
  console.log(`\nSeeded ${inserted} Class 2 Math v2 questions (Ch1–Ch2).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
