/**
 * Seed — System Design DEPTH batch 8 (SD_DEPTH_STANDARD.md).
 *
 *   sysd_m18_t1  Vector Database / Semantic Search   (module sysd_m18)
 *   sysd_m18_t2  RAG Pipeline (LLM Knowledge Base)   (module sysd_m18)
 *   sysd_m18_t3  LLM Inference Serving Platform       (module sysd_m18)
 *   sysd_m18_t4  ML Model Registry & Deployment       (module sysd_m18)
 *   sysd_m22_t2  Load Balancer                        (module sysd_m22)
 *   sysd_m22_t1  DNS Service                          (module sysd_m22)
 *
 * Idempotent upsert by id; recomputes totals. Verify:
 *   node config/auditSysdDepth.mjs --require sysd_m18_t1,sysd_m18_t2,sysd_m18_t3,sysd_m18_t4,sysd_m22_t2,sysd_m22_t1
 * Usage: node config/seedSysdDepthBatch8.js  ·  npm run seed:sysd-depth-8
 */
import "dotenv/config";
import mongoose from "mongoose";
import { ProModule, ProTopic, ProExercise } from "../models/proModels.js";
import { recomputeTrackTotals } from "./proTrackTotals.mjs";

const TRACK_KEY = "pro_sysd";

const FONT = "system-ui,-apple-system,Segoe UI,Roboto,sans-serif";
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
function box(x, y, w, h, label, sub, fill = "#eff6ff") {
  const cy = sub ? y + h / 2 - 3 : y + h / 2 + 5;
  let s = `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="${fill}" stroke="#94a3b8" stroke-width="1.5"/>`;
  s += `<text x="${x + w / 2}" y="${cy}" text-anchor="middle" font-family="${FONT}" font-size="14" font-weight="600" fill="#0f172a">${esc(label)}</text>`;
  if (sub) s += `<text x="${x + w / 2}" y="${y + h / 2 + 14}" text-anchor="middle" font-family="${FONT}" font-size="11" fill="#475569">${esc(sub)}</text>`;
  return s;
}
function arrow(x1, y1, x2, y2, label, dashed) {
  const dash = dashed ? ` stroke-dasharray="5 4"` : "";
  let s = `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#94a3b8" stroke-width="2"${dash} marker-end="url(#ah)"/>`;
  if (label) s += `<text x="${(x1 + x2) / 2}" y="${(y1 + y2) / 2 - 6}" text-anchor="middle" font-family="${FONT}" font-size="10.5" fill="#64748b">${esc(label)}</text>`;
  return s;
}
function note(x, y, text, anchor = "middle") {
  return `<text x="${x}" y="${y}" text-anchor="${anchor}" font-family="${FONT}" font-size="11" fill="#64748b">${esc(text)}</text>`;
}
function svg(w, h, inner) {
  return `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" width="100%" style="max-width:${w}px;height:auto">` +
    `<defs><marker id="ah" markerWidth="9" markerHeight="9" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#94a3b8"/></marker></defs>` +
    `<rect x="0" y="0" width="${w}" height="${h}" fill="#ffffff"/>${inner}</svg>`;
}

const DIAG = {
  vdb: svg(820, 250,
    box(20, 30, 110, 50, "Documents", "") +
    box(160, 30, 110, 50, "Embed", "model", "#f0fdf4") +
    box(320, 90, 170, 60, "ANN index", "HNSW / IVF", "#fce7f3") +
    box(20, 165, 110, 50, "Query", "") +
    box(160, 165, 110, 50, "Embed", "model", "#f0fdf4") +
    box(540, 90, 150, 60, "Top-k neighbors", "+ metadata filter", "#ede9fe") +
    arrow(130, 55, 160, 55) + arrow(270, 55, 360, 90, "vectors") +
    arrow(130, 190, 160, 190) + arrow(270, 190, 360, 150, "query vector") +
    arrow(490, 120, 540, 120, "ANN search") +
    note(410, 240, "Embeddings indexed for approximate nearest-neighbor; query by similarity")),
  rag: svg(820, 270,
    box(20, 25, 100, 46, "Docs", "") +
    box(150, 25, 90, 46, "Chunk", "", "#f0fdf4") +
    box(270, 25, 90, 46, "Embed", "", "#f0fdf4") +
    box(390, 25, 130, 46, "Vector store", "", "#fce7f3") +
    box(20, 150, 110, 50, "Question", "") +
    box(160, 150, 90, 50, "Embed", "", "#f0fdf4") +
    box(290, 150, 130, 50, "Retrieve top-k", "context", "#ede9fe") +
    box(460, 150, 110, 50, "LLM", "+ context", "#fef9c3") +
    box(620, 150, 140, 50, "Answer", "+ citations") +
    arrow(120, 48, 150, 48) + arrow(240, 48, 270, 48) + arrow(360, 48, 390, 48) +
    arrow(130, 175, 160, 175) + arrow(250, 175, 290, 175) + arrow(420, 175, 460, 175) + arrow(570, 175, 620, 175) +
    arrow(455, 71, 360, 150, "search", true) +
    note(410, 255, "Index chunks; retrieve relevant context; ground the LLM -> cited answer")),
  llm: svg(820, 240,
    box(20, 95, 100, 56, "Requests", "prompts") +
    box(160, 95, 110, 56, "Queue", "", "#fef9c3") +
    box(310, 95, 140, 56, "Batcher", "continuous", "#f0fdf4") +
    box(490, 30, 150, 52, "GPU model", "+ KV cache", "#fce7f3") +
    box(490, 150, 150, 52, "Autoscale GPUs", "", "#ede9fe") +
    box(680, 95, 110, 56, "Stream tokens", "") +
    arrow(120, 123, 160, 123) + arrow(270, 123, 310, 123) +
    arrow(450, 110, 490, 60, "batched") + arrow(450, 140, 490, 176, "scale") +
    arrow(640, 60, 680, 110, "tokens") +
    note(410, 230, "Batch requests to keep scarce GPUs busy; KV-cache; stream tokens; autoscale")),
  mlreg: svg(820, 250,
    box(20, 95, 100, 56, "Train", "") +
    box(160, 95, 160, 56, "Model registry", "versions+metrics+lineage", "#fce7f3") +
    box(360, 30, 110, 46, "Staging", "", "#fef9c3") +
    box(360, 100, 110, 46, "Prod", "serve", "#f0fdf4") +
    box(360, 170, 130, 46, "Monitor drift", "", "#ede9fe") +
    box(540, 100, 130, 56, "Rollback", "prior version", "#eff6ff") +
    arrow(120, 123, 160, 123, "register") +
    arrow(320, 110, 360, 55, "promote") + arrow(470, 53, 360, 105, "approve") +
    arrow(360, 146, 360, 170, "watch") + arrow(490, 175, 540, 140, "drift -> roll back / retrain", true) +
    arrow(470, 123, 540, 125) +
    note(410, 240, "Version + lineage -> staged promotion + canary -> serve; monitor drift -> rollback")),
  lb: svg(820, 250,
    box(20, 100, 100, 56, "Clients", "") +
    box(170, 100, 150, 56, "Load balancer", "L4/L7 + health", "#f0fdf4") +
    box(390, 25, 120, 44, "Backend 1", "", "#fce7f3") +
    box(390, 92, 120, 44, "Backend 2", "", "#fce7f3") +
    box(390, 159, 120, 44, "Backend 3", "", "#fce7f3") +
    box(560, 100, 140, 56, "Standby LB", "VIP failover", "#ede9fe") +
    arrow(120, 128, 170, 128) +
    arrow(320, 115, 390, 47, "least-conn") + arrow(320, 128, 390, 114) + arrow(320, 141, 390, 181) +
    arrow(320, 150, 560, 130, "HA pair", true) +
    note(410, 240, "Distribute by algorithm to healthy backends; make the LB itself HA (VIP failover)")),
  dns: svg(820, 250,
    box(20, 100, 100, 56, "Client", "") +
    box(160, 100, 110, 56, "Resolver", "+ cache", "#f0fdf4") +
    box(330, 25, 110, 44, "Root", "", "#fce7f3") +
    box(330, 92, 110, 44, "TLD", ".com", "#fce7f3") +
    box(330, 159, 130, 44, "Authoritative", "your zone", "#fce7f3") +
    box(540, 100, 140, 56, "Record + TTL", "A/AAAA/CNAME", "#ede9fe") +
    arrow(120, 128, 160, 128, "query") +
    arrow(270, 115, 330, 47, "root") + arrow(270, 128, 330, 114, "TLD") + arrow(270, 141, 330, 181, "auth") +
    arrow(460, 181, 540, 130, "record") +
    note(410, 240, "Hierarchical resolution; heavy TTL caching at every level; anycast for nearby servers")),
};

const TT = (moduleId, id, num, name, slug, tags, hookQ, hookI, blocks, rel, gaps, diff, svgStr, vaType) => ({
  trackKey: TRACK_KEY, moduleId, topicId: id, topicNumber: num, name, slug,
  metadata: { estimated_minutes: 50, difficulty: 4, prerequisites: [], tags },
  hook: { question: hookQ, insight: hookI },
  teaching: { blocks, visual_aid: { type: vaType, svg: svgStr, alt_text: `${name} architecture diagram.` } },
  interviewRelevance: rel, commonGaps: { gaps },
  prerequisites: [], estimatedMinutes: 50, difficulty: diff, xpReward: 80, visualizer: null,
});
const C = (section, heading, body) => ({ kind: "concept", section, heading, body });
const K = (section, heading, body) => ({ kind: "code", section, heading, body });
const G = (id, w, r, d) => ({ gap_id: id, what_students_get_wrong: w, remediation: r, detection_pattern: d });

const TOPICS = [
  // ───────────────────── VECTOR DATABASE / SEMANTIC SEARCH ──────────────────
  TT("sysd_m18", "sysd_m18_t1", 1, "Design a Vector Database / Semantic Search", "design-vector-db",
    ["case-study", "vector-db", "embeddings", "ann"],
    "You have millions of items represented as high-dimensional embedding vectors, and a query is also a vector — you want the items whose meaning is closest to it (semantic search), in milliseconds. Comparing the query to every vector is far too slow. How do you find nearest neighbors at scale?",
    "Store embeddings and build an APPROXIMATE NEAREST NEIGHBOR (ANN) index — exact kNN over millions of high-dimensional vectors is too slow, so you trade a little recall for huge speed using structures like HNSW (a navigable small-world graph) or IVF (inverted-file clustering). A query embedding is searched against the index for the top-k closest by a distance metric (cosine/dot), optionally combined with metadata filters. ANN indexing + the recall/latency trade + scaling are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: store high-dimensional embedding vectors (with ids + metadata); given a query vector, return the k most SIMILAR vectors (nearest neighbors) by a distance metric; support inserts/updates/deletes; and ideally combine similarity search with METADATA filtering (e.g. 'similar docs where category=finance'). Non-functional: low-latency queries (single-digit to tens of ms) over millions-to-billions of vectors, high RECALL (the approximate results should closely match the true nearest neighbors), high throughput, and scalability. Clarify scope: this powers semantic search, recommendations, and RAG (embeddings from an ML model encode meaning, so nearby vectors = semantically similar items). The defining problem is that EXACT nearest-neighbor search (compare the query to every vector) is O(n·d) — far too slow at millions of high-dimensional vectors — so you must use an APPROXIMATE index that finds very-likely-nearest neighbors in sublinear time, accepting a small recall loss for orders-of-magnitude speedup. The core design is that ANN index, plus how to scale and filter it."),
      K("estimation", "Capacity estimation (with numbers)",
        "Assume 100M vectors, 768 dims, float32 (4 B):\n  raw size = 100M * 768 * 4 B ~= 300 GB  -> too big for one node's RAM -> shard\n  + the ANN index (graph/cluster structure) adds overhead on top\nExact search: 100M * 768 mults per query = ~77B ops/query -> way too slow\n  ANN (HNSW): visits ~ hundreds-thousands of vectors/query -> ms latency\nQuantization (e.g. PQ) can compress vectors ~4-32x to fit memory.\nTakeaway: vectors are memory-heavy (shard + quantize); exact search is infeasible\n-> ANN index turns it into a fast graph/cluster traversal with tunable recall."),
      C("hld", "High-level design",
        "On INGEST, items are passed through an embedding model (often outside the DB) to produce vectors, which are stored and inserted into an ANN INDEX (e.g. HNSW or IVF) along with their metadata; the index is sharded across nodes when the data exceeds one machine's memory. On QUERY, the query vector is searched against the ANN index to retrieve the top-k nearest neighbors by the chosen distance metric (cosine similarity or dot product), and metadata FILTERS can constrain results; in a sharded deployment the query scatters to shards and the top-ks are merged (gather), much like a search engine. Trace a query: query text -> embed -> vector -> ANN search the index -> top-k candidate vectors (+ exact-distance re-rank) -> apply metadata filter -> return ids. The expensive work (finding neighbors among millions) is made fast by the index structure; embedding generation and re-ranking bracket it. The vector DB's job is fast, scalable ANN over the indexed embeddings."),
      K("api", "API design",
        "upsert(id, vector[768], metadata{...})        // insert/update a vector\ndelete(id)\nquery(vector[768], k=10, filter={category:'finance'}, metric='cosine')\n  -> [ { id, score, metadata } ]   // top-k nearest, optionally filtered\nbatch upsert for bulk ingestion; sharded query = scatter-gather + merge top-k"),
      K("data_model", "Data model",
        "vectors:  id -> { embedding: float[d], metadata{...} }\nANN index: HNSW (multi-layer proximity graph) OR IVF (clusters/posting lists)\n  + optional product quantization (PQ) to compress vectors\nmetric:    cosine / dot-product / euclidean (how 'closeness' is measured)\nsharding:  by vector (each shard holds a subset) -> scatter-gather queries\nfilter:    metadata index combined with ANN (pre/post-filtering)"),
      C("deep_dive", "Deep dive: ANN indexing (HNSW & IVF)",
        "The heart of a vector DB is the APPROXIMATE-nearest-neighbor index, because exact search doesn't scale. HNSW (Hierarchical Navigable Small World) builds a multi-layer GRAPH where each vector links to nearby vectors; a search starts at an entry point in the top (sparse) layer and greedily hops toward the query, descending layers to refine — finding very-close neighbors by visiting only a few hundred nodes instead of all of them (excellent recall/latency, but memory-heavy and slower to update). IVF (Inverted File) CLUSTERS the vectors (k-means) into buckets; a query is compared only to the few nearest clusters' vectors (not all) — less memory, faster build, slightly lower recall, tunable by how many clusters you probe. Both expose the central RECALL vs LATENCY/MEMORY knob: searching more (more graph hops / more clusters probed) raises recall but costs latency; the index is APPROXIMATE on purpose. PRODUCT QUANTIZATION compresses vectors (lossy) to cut memory dramatically at a small recall cost. Choosing and tuning the ANN index for the recall/latency/memory target is the core engineering."),
      C("deep_dive", "Deep dive: scaling, distance metrics & filtering",
        "Three practical concerns round it out. SCALING: vectors are large and indices are memory-resident, so beyond one node you SHARD by vector across machines and run queries as SCATTER-GATHER (each shard returns its local top-k, merged globally) — same tail-latency dynamics as a search engine, mitigated by replication. DISTANCE METRIC: similarity is defined by the metric — COSINE (angle, common for normalized text embeddings), DOT PRODUCT, or EUCLIDEAN — and it must match how the embeddings were trained; the index is built for a specific metric. FILTERING: real queries combine similarity with metadata constraints ('similar AND category=X'), which is subtle — PRE-filtering (restrict candidates then ANN) can hurt the index's graph traversal, while POST-filtering (ANN then drop non-matching) may return too few after filtering; vector DBs implement hybrid strategies. UPDATES: ANN graphs (HNSW) are costly to mutate, so high-churn data needs incremental index maintenance or periodic rebuilds. These — sharded scatter-gather, the right metric, and filtered ANN — are what make a vector DB usable in production beyond a toy index."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "MEMORY is the dominant cost: vectors + index are large and held in RAM for speed — mitigate with sharding and QUANTIZATION (compress vectors, trade a little recall). RECALL vs LATENCY is the fundamental knob: more thorough search (more hops/clusters probed) = higher recall but slower; you tune to the target. UPDATES to graph-based indexes (HNSW) are expensive — high write churn needs incremental maintenance or rebuilds. FILTERED search is tricky (pre vs post filtering trade coverage vs correctness). Scatter-gather adds tail latency at scale. Trade-offs: HNSW (best recall/latency, memory-heavy, slow updates) vs IVF (less memory, faster build, lower recall) vs flat/exact (perfect recall, too slow at scale); approximate (fast, slight recall loss) vs exact (precise, infeasible large); quantized (cheap memory, recall cost) vs full-precision; pre-filter vs post-filter. Closing signal: an ANN index (HNSW/IVF) with the right distance metric, sharded scatter-gather + replication for scale, quantization for memory, and metadata filtering — tuned on the recall/latency/memory triangle."),
      C("deep_dive", "Deep dive: quantization, updates & operations",
        "Operationally a vector DB balances memory, freshness, and recall. Quantization: PRODUCT QUANTIZATION (and scalar quantization) compress each vector into a compact code, shrinking the in-memory footprint 4-32x so far more vectors fit per node — at a modest recall cost, often recovered by re-ranking the top candidates with full-precision vectors (a two-stage: cheap quantized ANN -> exact re-rank of top-N). Updates/freshness: HNSW graphs degrade and are costly to mutate, so deletes are often tombstoned and the index periodically rebuilt/compacted (LSM-like 'fresh segment + background merge'), while IVF can re-cluster periodically — high-churn workloads must plan for this. Sharding & replication: shard by vector for capacity, replicate shards for query throughput and availability; queries scatter-gather. Hybrid search: combine vector similarity with keyword/BM25 (lexical) search and fuse scores — pure semantic search misses exact-term matches, so hybrid is common. Embedding consistency: all vectors (and queries) must come from the SAME embedding model/version; re-embedding the corpus is required if the model changes. Observability: query latency p99, recall (vs a ground-truth sample), memory per shard, and index-build/merge lag are the SLOs. The spine holds: ANN index + quantization + sharded scatter-gather + periodic rebuilds + (often) hybrid search, tuned on recall/latency/memory."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'Why not exact nearest-neighbor?' O(n·d) per query is too slow at millions of high-dim vectors — use an approximate index (HNSW/IVF). 'HNSW vs IVF?' graph (best recall/latency, memory-heavy, slow updates) vs clustering (cheaper, faster build, lower recall). 'Memory too big?' shard + quantize (product quantization), re-rank top candidates at full precision. 'Combine with filters?' hybrid pre/post filtering of metadata with ANN. 'Updates?' tombstone + periodic rebuild (graphs are costly to mutate). 'Which distance metric?' match the embedding model (cosine/dot/euclidean). 'Scale past one node?' shard by vector, scatter-gather, replicate. 'Pure semantic misses exact terms?' hybrid vector + lexical (BM25) search. 'Embedding model changes?' re-embed the corpus. Each returns to the spine: an ANN index over embeddings, tuned on recall/latency/memory, sharded + quantized, with filtering and (often) hybrid retrieval."),
    ],
    "A vector DB tests approximate nearest-neighbor search (HNSW graph / IVF clustering) instead of infeasible exact kNN, the recall/latency/memory trade-off, sharded scatter-gather + quantization for scale, and metadata-filtered + hybrid retrieval. The signal is choosing ANN over brute force, naming the recall/latency knob, and handling memory via sharding/quantization.",
    [
      G("exact_search", "Comparing the query to every vector (exact kNN) at scale.", "Use an ANN index (HNSW/IVF) for sublinear approximate search.", "Linear scan / brute-force distance to all vectors."),
      G("ignore_memory", "Ignoring that vectors + index are huge and memory-resident.", "Shard by vector and quantize (PQ); re-rank top candidates at full precision.", "No sharding/quantization for 100M+ high-dim vectors."),
      G("recall_latency", "Not acknowledging the recall vs latency/memory trade.", "Tune search effort (hops/clusters probed) to the recall target; it's approximate by design.", "Treats ANN results as exact / no recall consideration."),
    ],
    0.6, DIAG.vdb, "Vector database architecture"),

  // ─────────────────────────────── RAG PIPELINE ────────────────────────────
  TT("sysd_m18", "sysd_m18_t2", 2, "Design a RAG Pipeline (LLM Knowledge Base)", "design-rag-pipeline",
    ["case-study", "rag", "llm", "retrieval"],
    "You want an LLM to answer questions about YOUR private/up-to-date data (docs, wiki, tickets) — accurately and with sources — even though the model was never trained on it and tends to hallucinate. How do you ground an LLM in your own knowledge?",
    "RETRIEVAL-AUGMENTED GENERATION: at ingest, CHUNK your documents, EMBED the chunks, and store them in a vector DB. At query time, EMBED the question, RETRIEVE the most relevant chunks (semantic search), and STUFF them into the LLM's prompt as context, so the model answers GROUNDED in your retrieved data (with citations) instead of hallucinating from memory. Retrieval quality (chunking + embeddings) and grounding the generation are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: answer natural-language questions over a private/proprietary knowledge base using an LLM; ground answers in retrieved source material and provide CITATIONS; ingest and keep the knowledge base reasonably fresh. Non-functional: answer RELEVANCE/accuracy (the point is to reduce hallucination and use current/private data the base model lacks), acceptable latency (retrieval + generation), freshness (new/changed docs become answerable), and scalability. Clarify scope: RAG vs fine-tuning — RAG injects knowledge at QUERY time via retrieval (cheap to update, citable, no retraining) whereas fine-tuning bakes it into weights (costly, hard to update, no citations); RAG is the standard for evolving/factual knowledge. The defining problem: an LLM only 'knows' its training data and will confidently HALLUCINATE about your private or recent information, so instead of relying on its parametric memory you RETRIEVE the relevant facts from your own data and put them in the prompt as context — making the model reason over provided, verifiable text. The quality of the whole system is dominated by RETRIEVAL: if you fetch the wrong context, the LLM answers wrong (garbage in, garbage out)."),
      K("estimation", "Capacity estimation (with numbers)",
        "Knowledge base: 1M documents, avg chunked into ~5 chunks -> ~5M chunks/vectors\n  -> a vector DB of ~5M embeddings (see the vector-DB design for sizing)\nIngest: embed 5M chunks once (batch) + re-embed changed docs incrementally.\nQuery: 1 embed call + 1 vector search (top-k, e.g. 5) + 1 LLM call (the slow part:\n  hundreds of ms to seconds, dominated by generation).\nContext budget: top-k chunks must FIT the LLM context window (token limit).\nTakeaway: ingestion is a batch embedding job; query latency/cost is dominated by\nthe LLM call; retrieval quality (chunking + top-k) drives answer quality."),
      C("hld", "High-level design",
        "Two pipelines. INGESTION (offline/continuous): documents are split into CHUNKS (passages sized to be self-contained and to fit context budgets), each chunk is EMBEDDED into a vector, and the vectors (with source metadata) are stored in a VECTOR DB. QUERY (online): the user's question is EMBEDDED, the vector DB is searched for the top-k most relevant chunks (semantic RETRIEVAL), those chunks are inserted into a PROMPT template as CONTEXT ('answer using the following sources: ...'), and the LLM GENERATES an answer grounded in them, returning the answer plus CITATIONS to the source chunks. Optionally a re-ranking step refines retrieved chunks, and hybrid (keyword + vector) retrieval improves recall. Trace a question: 'What's our refund policy?' -> embed -> retrieve top-5 policy chunks -> build prompt with those chunks -> LLM answers citing them. The base LLM is unchanged; knowledge enters via retrieval at query time, so updating the knowledge base is just re-indexing documents — no retraining."),
      K("api", "API design",
        "ingest(doc) -> chunk(doc) -> [embed(chunk) -> vectorDB.upsert] // build the KB\nask(question) -> {\n  qv = embed(question)\n  chunks = vectorDB.query(qv, k=5, filter)        // retrieve relevant context\n  prompt = template(question, chunks)             // augment\n  answer = LLM.generate(prompt)                    // grounded generation\n  return { answer, citations: chunks.sources }\n}"),
      K("data_model", "Data model",
        "documents: doc_id -> source, version, updated_at\nchunks:    chunk_id -> { text, doc_id, position, embedding[d], metadata }\nvector index: ANN over chunk embeddings (the vector-DB design)\nprompt template: instruction + {retrieved context} + {question} + 'cite sources'\n(freshness) re-embed + re-index chunks when a document changes"),
      C("deep_dive", "Deep dive: ingestion, chunking & embeddings",
        "Retrieval quality is set at ingestion, and CHUNKING is the most underrated lever. You split documents into chunks because (a) you retrieve and inject PASSAGES, not whole documents (which wouldn't fit the context window and would dilute relevance), and (b) embeddings represent a bounded piece of text well. Chunk SIZE matters: too large and a chunk mixes multiple topics (noisy retrieval, wasted context); too small and it loses the context needed to be meaningful — so you tune size and use OVERLAP between chunks so a concept split across a boundary isn't lost. Smart chunking respects structure (by section/paragraph, not blind fixed length). Each chunk is then EMBEDDED with a model (the SAME model used for queries, or retrieval fails) into a vector, and stored in the vector DB with metadata (source, title) for citations and filtering. Getting chunking + embedding right is what makes retrieval surface the RIGHT passages — and since the LLM can only ground on what's retrieved, this stage largely determines answer quality. Re-embedding on document changes keeps the base fresh."),
      C("deep_dive", "Deep dive: retrieval, augmentation & grounding",
        "At query time the pipeline RETRIEVES then GENERATES. Retrieval: embed the question and vector-search for the top-k most semantically relevant chunks (often improved by HYBRID search — combining vector similarity with keyword/BM25 so exact terms aren't missed — and a RE-RANKER that reorders candidates by relevance to the question). Augmentation: insert the retrieved chunks into the prompt as CONTEXT with an instruction to answer USING those sources and to cite them — this is the 'augmented' in RAG. GROUNDING: because the LLM now reasons over provided, factual text rather than its fuzzy memory, hallucination drops sharply and answers can cite exactly which source supports each claim (verifiability). Constraints to respect: the CONTEXT WINDOW (token limit) caps how many chunks you can include, so retrieval must be precise (fetch few, relevant chunks, not many) — and you instruct the model to say 'I don't know' if the context doesn't contain the answer (so it doesn't fall back to hallucinating). Retrieve-relevant-context + augment-the-prompt + grounded-cited-generation is the loop that turns a generic LLM into an accurate answerer over your data."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "RETRIEVAL QUALITY dominates everything — if you fetch irrelevant chunks, the LLM answers wrong no matter how good it is (garbage in, garbage out); improve with better chunking, hybrid search, and re-ranking. CHUNKING is a balance (too big = noisy/over-budget, too small = context-less). CONTEXT WINDOW limits how much retrieved text fits, so you can't just stuff everything — precision over recall in what you inject. FRESHNESS requires re-embedding/re-indexing changed docs (and handling deletes). HALLUCINATION isn't fully eliminated — the model can still ignore or misread context, so instruct it to cite and to abstain, and evaluate. Cost/latency is dominated by the LLM call. Trade-offs: RAG (cheap to update, citable, no retraining) vs fine-tuning (knowledge in weights, costly/static, no citations) — often complementary; more retrieved chunks (more recall, more tokens/cost, more noise) vs fewer (precise, may miss); semantic-only vs hybrid retrieval; bigger context window (more context, more cost/latency) vs tighter. Closing signal: chunk + embed + index your docs; at query time retrieve relevant context (hybrid + re-rank), augment the prompt, and generate a grounded, cited answer — quality gated by retrieval."),
      C("deep_dive", "Deep dive: freshness, evaluation & operations",
        "Operationally RAG must stay fresh, accurate, and measurable. Freshness: when source documents change, re-chunk, re-embed, and upsert the affected vectors (and delete removed ones), so the knowledge base reflects current data without retraining the model — a big advantage over fine-tuning. Evaluation: answer quality is hard to measure, so build an EVAL set (questions + expected answers/sources) and track retrieval metrics (did we fetch the right chunk?) and generation metrics (faithfulness to context, correctness) — LLM-as-judge or human review; without evaluation you can't tell if a chunking/retrieval change helped. Guardrails: instruct the model to answer ONLY from context and to say it doesn't know otherwise, and validate citations point to real retrieved chunks (to catch fabricated sources). Hybrid retrieval + re-ranking lifts recall/precision. Caching: cache embeddings and even (question -> answer) for repeated queries to cut LLM cost/latency. Security/access: enforce that retrieval only returns chunks the user is allowed to see (tenant/ACL filtering in the vector search) — a RAG leak is a data leak. Observability: retrieval relevance, answer faithfulness, latency, token cost, and KB freshness lag are the SLOs. The spine holds: chunk+embed+index -> retrieve (hybrid+re-rank, access-filtered) -> augment -> grounded cited generation, kept fresh and continuously evaluated."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'Why RAG not fine-tuning?' RAG injects knowledge at query time (cheap to update, citable, current) vs baking into weights (costly, static, no citations) — often complementary. 'What most affects quality?' RETRIEVAL — chunking, embeddings, hybrid search, re-ranking (garbage in -> garbage out). 'Chunk size?' big enough to be self-contained, small enough to be focused/fit context; use overlap + structure-aware splitting. 'Reduce hallucination?' ground on retrieved context, instruct to cite + abstain, validate citations. 'Freshness?' re-embed/re-index changed docs (no retraining). 'Context window limits?' retrieve few, precise chunks; re-rank. 'Pure semantic misses keywords?' hybrid (vector + BM25). 'Evaluate it?' an eval set + retrieval/faithfulness metrics. 'Access control?' filter retrieval by the user's permissions (a RAG leak is a data leak). Each returns to the spine: chunk+embed+index -> retrieve relevant context -> augment the prompt -> grounded, cited generation, gated by retrieval quality."),
    ],
    "A RAG pipeline tests grounding an LLM in private/current data via retrieval: chunk + embed + index documents, then at query time retrieve the most relevant chunks (hybrid + re-rank) and inject them as prompt context for a grounded, cited answer — vs fine-tuning. The signal is that retrieval quality (chunking/embeddings) dominates, grounding reduces hallucination, and updates are just re-indexing (no retraining).",
    [
      G("retrieval_afterthought", "Treating the LLM as the system and retrieval as trivial.", "Retrieval quality (chunking, embeddings, hybrid, re-rank) dominates answer quality — design it first.", "Focuses on the prompt/model, hand-waves retrieval."),
      G("finetune_for_knowledge", "Fine-tuning to add changing/factual knowledge.", "Use RAG (retrieve at query time) for evolving/citable knowledge; fine-tune for style/format.", "Proposes retraining the model whenever data changes."),
      G("no_grounding", "Letting the LLM answer from memory (hallucination).", "Inject retrieved context, instruct to cite + abstain if absent; validate citations.", "No retrieved context in the prompt / no citations."),
    ],
    0.6, DIAG.rag, "RAG pipeline architecture"),

  // ───────────────────── LLM INFERENCE SERVING PLATFORM ────────────────────
  TT("sysd_m18", "sysd_m18_t3", 3, "Design an LLM Inference Serving Platform", "design-llm-inference",
    ["case-study", "llm", "gpu", "batching"],
    "You must serve a large language model to many users at once — generating tokens with low latency and high throughput — on GPUs that are scarce, expensive, and have limited memory. Running one request at a time wastes the GPU; running too many runs out of memory. How do you serve LLM inference efficiently?",
    "Maximize expensive-GPU utilization with BATCHING — combine many requests so the GPU processes them together — using CONTINUOUS (in-flight) batching that adds/removes requests every step rather than waiting for a fixed batch. Manage the KV-CACHE (per-request attention state that grows with tokens) carefully since it dominates GPU memory; STREAM tokens to users; shard huge models across GPUs (tensor/pipeline parallelism); and AUTOSCALE GPU workers off a queue. GPU-throughput batching + memory/cost management are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: accept prompt + parameters and generate a text completion, ideally STREAMING tokens as they're produced; support many concurrent users and multiple models. Non-functional: low LATENCY (time-to-first-token and inter-token latency matter for UX), high THROUGHPUT (tokens/sec across all users), efficient GPU UTILIZATION (GPUs are scarce and very expensive, so idle GPU time is wasted money), and cost-efficiency at scale. Clarify scope: serving (inference) of an already-trained LLM, not training. The defining reality is the GPU: LLM inference is GPU-bound, GPUs are expensive and memory-limited, and they are THROUGHPUT devices — processing one request at a time barely uses the hardware, while the autoregressive nature of generation (produce one token, feed it back, repeat) makes each request a sequence of dependent steps. So the central tension is keeping the GPU saturated (high throughput, good $/token) WITHOUT exhausting its limited memory or hurting individual-request latency too much — which is what batching and KV-cache management are all about."),
      K("estimation", "Capacity estimation (with numbers)",
        "A large model's weights may be tens-hundreds of GB -> needs one or several GPUs\n  (sharded across GPUs if it doesn't fit one) just to LOAD.\nKV-cache: per request, grows with sequence length; can be GBs for long contexts\n  -> KV-cache memory, not weights, often caps how many requests batch together.\nThroughput: batching many requests can yield ~10x the tokens/sec of one-at-a-time.\nCost: GPUs are the dominant cost -> utilization directly drives $/token.\nTakeaway: weights + KV-cache fill GPU memory (limiting batch size); batching\nmaximizes throughput/utilization; autoscale GPUs to demand; quantize to fit/speed."),
      C("hld", "High-level design",
        "The model is LOADED onto GPU(s) by inference WORKERS (sharded across GPUs via tensor/pipeline PARALLELISM if it's too big for one). Incoming generation requests go into a QUEUE; a BATCHER/scheduler groups requests to run together on the GPU, and crucially uses CONTINUOUS (in-flight) batching — it doesn't wait to assemble a fixed batch, but adds new requests and evicts finished ones at each generation STEP, so the GPU stays busy and a short request isn't stuck behind a long one. Each request keeps a KV-CACHE (the attention key/value state for its tokens so far) on the GPU, reused across steps to avoid recomputation — and this cache is the main consumer of GPU memory, so it's managed carefully (e.g. paged). Generated tokens are STREAMED back to the client as produced (low time-to-first-token feel). A router/load-balancer spreads requests across worker replicas, and the worker pool AUTOSCALES on queue depth/load. Trace a request: prompt -> queue -> joined into the running batch -> GPU generates tokens step by step (using its KV-cache) -> tokens streamed out -> request leaves the batch when done. Batching + KV-cache + streaming + autoscaled GPU workers is the shape."),
      K("api", "API design",
        "POST /v1/generate { model, prompt, max_tokens, temperature, stream: true }\n  -> streamed tokens (SSE/websocket): { token } ... { done, usage }\nInternal: request -> queue -> continuous-batching scheduler -> GPU worker\n  worker keeps a per-request KV-cache; emits tokens each step\nrouting: load-balance across worker replicas; autoscale on queue depth"),
      K("data_model", "Data model / state",
        "model weights: loaded in GPU memory (sharded across GPUs if large)\nrequest queue: pending generation requests (+ params)\nrunning batch: set of in-flight requests sharing each GPU step (continuous batching)\nKV-cache:      per-request attention state (grows per token) -> dominates GPU memory\nautoscaler:    GPU worker replicas scaled on load/queue depth"),
      C("deep_dive", "Deep dive: batching for GPU throughput",
        "GPUs are massively parallel THROUGHPUT devices, so the key to efficiency is processing many requests together. NAIVE/static batching waits to collect N requests, runs them as a fixed batch, and waits for ALL to finish before starting the next — but LLM generations have very different lengths, so short requests wait idle for the longest one, wasting GPU and adding latency. CONTINUOUS (in-flight / iteration-level) BATCHING fixes this: the scheduler operates at the per-token STEP level, adding newly-arrived requests into the running batch and removing finished ones EVERY step, so the GPU is always working on a full batch of active requests and no request blocks others — dramatically improving both throughput and latency (this is what vLLM/TGI-style servers do). Batching works because generating the next token for many requests at once uses the GPU's parallelism far better than one at a time (often ~10x throughput). The trade-off: bigger batches raise throughput and GPU utilization (lower $/token) but can increase individual-request latency, and batch size is CAPPED by memory (the KV-cache) — so the scheduler balances throughput vs latency under the memory limit. Continuous batching is the single most important LLM-serving technique."),
      C("deep_dive", "Deep dive: KV-cache, memory, parallelism & cost",
        "Memory and cost are the other half. KV-CACHE: during autoregressive generation, each request caches the attention keys/values for all its tokens so each new token doesn't recompute the whole sequence — a big speedup, but the cache GROWS with sequence length and number of concurrent requests, and it (alongside the weights) is what fills GPU memory and thus LIMITS how many requests can batch. Efficient KV-cache management (e.g. PAGED attention — allocate cache in pages to avoid fragmentation and fit more requests) directly increases achievable batch size and throughput. MODEL PARALLELISM: a model too large for one GPU is sharded across several via TENSOR parallelism (split each layer across GPUs) and/or PIPELINE parallelism (different layers on different GPUs) — necessary just to load big models, at the cost of inter-GPU communication. QUANTIZATION (serve weights in lower precision, e.g. int8/int4) shrinks memory and speeds inference with small quality loss, letting models fit fewer/cheaper GPUs. COST: since GPUs dominate cost, you maximize utilization (batching), autoscale workers to demand (scale to zero for idle models), and may use spot/cheaper GPUs for non-latency-critical work. The KV-cache (memory limit), parallelism (fit big models), and quantization (cheaper/faster) together determine how much you can serve per GPU dollar."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "GPU MEMORY is the binding constraint — weights + KV-cache cap batch size and concurrency; manage the KV-cache (paged attention) and quantize to fit more. THROUGHPUT vs LATENCY is the core tension: bigger batches = higher throughput/utilization (better $/token) but higher per-request latency — continuous batching eases it but you still tune. COST: GPUs are expensive and scarce, so idle GPUs waste money — maximize utilization and autoscale (including scale-to-zero for cold models), accepting cold-start load time when a model must be loaded. Long contexts blow up KV-cache memory, shrinking batch size. Model loading is slow (tens of GB) — keep hot models warm. Trade-offs: continuous batching (high throughput + good latency, complex scheduler) vs one-at-a-time (simple, wasteful); large batch (throughput, latency) vs small (latency, lower utilization); quantization (cheaper/faster, slight quality loss) vs full precision; many small GPUs vs few large (model-parallel) for big models; dedicated (low latency) vs shared/multi-tenant (efficient, fairness needed). Closing signal: continuous batching to saturate GPUs, KV-cache/paged-attention + quantization for memory, model parallelism for big models, token streaming, and autoscaled GPU workers — all to maximize tokens per GPU dollar."),
      C("deep_dive", "Deep dive: scaling, multi-tenancy & operations",
        "Operationally an LLM serving platform is about squeezing the most out of GPUs reliably. Autoscaling: scale GPU worker replicas on queue depth/utilization; because GPUs are costly, scale DOWN aggressively (even to zero for rarely-used models, accepting cold-load latency on the next request) and keep popular models warm. Multi-model/multi-tenant: serve several models on a pool, route requests to workers that have the right model loaded; for many small fine-tuned variants, techniques like serving multiple LoRA adapters on one base model save memory. Fairness: under shared load, prevent one tenant's huge/long requests from starving others (per-tenant limits, fair scheduling), and cap max tokens. Latency optimizations: time-to-first-token matters, so prioritize prompt processing (prefill) and stream; speculative decoding can speed generation. Routing/HA: a load balancer fronts worker replicas; health-check and drain GPUs for upgrades. Caching: cache results for identical prompts and reuse shared prompt prefixes' KV-cache. Cost controls: quantization, batching, spot GPUs, and right-sizing models to the task. Observability: GPU utilization, tokens/sec, time-to-first-token, KV-cache occupancy, queue depth, and $/token are the SLOs. The spine holds: continuous-batched, KV-cache-managed, autoscaled (often quantized, model-parallel) GPU serving with streaming and fair multi-tenancy."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'Why batch?' GPUs are throughput devices — batching many requests gives ~10x tokens/sec vs one-at-a-time; use CONTINUOUS batching so short requests don't wait on long ones. 'What limits batch size?' GPU memory — the KV-cache (grows with tokens/concurrency) + weights; use paged attention + quantization to fit more. 'Model too big for one GPU?' tensor/pipeline parallelism across GPUs. 'Cut cost?' maximize utilization (batching), autoscale (scale to zero for idle models), quantize, spot GPUs. 'Latency?' continuous batching + streaming (time-to-first-token), speculative decoding. 'Long contexts?' blow up KV-cache -> fewer concurrent requests. 'Many fine-tunes?' multi-LoRA on a shared base. 'Fairness under load?' per-tenant limits + fair scheduling. Each returns to the spine: continuous batching to saturate GPUs, KV-cache/quantization for memory, parallelism for big models, streaming + autoscaling — maximizing tokens per GPU dollar."),
    ],
    "An LLM inference platform tests maximizing scarce-GPU utilization: CONTINUOUS (in-flight) batching to saturate throughput, KV-cache management (the memory limiter; paged attention) + quantization, model parallelism for big models, token streaming, and autoscaling — to optimize tokens per GPU dollar. The signal is batching for GPU throughput and KV-cache/memory as the constraint, not treating it like a stateless web service.",
    [
      G("one_at_a_time", "Serving requests one at a time / static batching that waits on the longest.", "Use continuous (in-flight) batching to keep the GPU saturated and not block short requests.", "Per-request inference with no/naive batching; idle GPU."),
      G("ignore_kvcache", "Ignoring GPU memory / the KV-cache as the limiter.", "Manage the KV-cache (paged attention) + quantize; it caps batch size/concurrency.", "No mention of KV-cache/memory limiting concurrency."),
      G("treat_stateless", "Treating it like a cheap stateless web service / ignoring GPU cost.", "Optimize utilization (batching), autoscale GPUs, quantize, model-parallel for big models.", "No GPU-utilization/cost or model-loading consideration."),
    ],
    0.7, DIAG.llm, "LLM inference serving architecture"),

  // ──────────────────── ML MODEL REGISTRY & DEPLOYMENT ─────────────────────
  TT("sysd_m18", "sysd_m18_t4", 4, "Design an ML Model Registry & Deployment (MLOps)", "design-ml-model-registry",
    ["case-study", "mlops", "model-registry", "deployment"],
    "Data scientists train many model versions; you must track which version is in production, reproduce how it was built, deploy new versions safely, roll back instantly if one misbehaves, and notice when a live model silently degrades. How do you operationalize ML models like you operationalize code?",
    "A MODEL REGISTRY is the versioned source of truth for models — storing each version's artifact plus its METADATA and LINEAGE (training data, code, metrics) for reproducibility — and a deployment PIPELINE promotes a version through stages (staging -> production) with approvals, canary/shadow rollout, and instant ROLLBACK to a prior registered version. Live models are MONITORED for data/concept DRIFT, triggering retraining. Versioning + lineage + safe staged deployment + drift monitoring are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: register and VERSION trained models with their metadata; track which version is deployed where (staging/prod); deploy a model to serving; promote/roll back versions; and monitor deployed models. Non-functional: REPRODUCIBILITY (you can recreate/understand how any model version was produced — data, code, params), SAFE deployment (a new model can't silently break things), instant ROLLBACK, auditability, and the ability to detect DEGRADATION over time. Clarify scope: the MLOps lifecycle around models (not training itself). The defining idea is treating models like first-class, versioned, governed artifacts — code has CI/CD, versioning, and rollback, and models need the same PLUS extra concerns unique to ML: a model is a function of its TRAINING DATA and code (so reproducibility requires capturing both — LINEAGE), its quality is statistical (so you compare versions by METRICS, not just 'it compiles'), and it DEGRADES in production as the world changes (DRIFT) even though the code is unchanged — so monitoring and retraining are part of the loop. The registry + deployment pipeline + drift monitoring operationalize this."),
      K("estimation", "Capacity estimation (with numbers)",
        "Models/versions are modest in count (hundreds of models, many versions each) but\n  artifacts are LARGE (model files can be MBs-GBs) -> stored in object storage,\n  the registry holds metadata + pointers, not the bytes inline.\nDeployment events are infrequent (per release) -> not a throughput problem.\nMonitoring runs continuously over prediction logs (volume tracks serving traffic).\nTakeaway: small metadata DB + large artifacts in object storage; the value is\nGOVERNANCE (versioning, lineage, safe rollout, drift), not raw scale."),
      C("hld", "High-level design",
        "After training, a model is REGISTERED into the MODEL REGISTRY: the artifact (weights/serialized model) is stored (object storage) and a registry entry records the VERSION plus METADATA — the training dataset version, code/commit, hyperparameters, and evaluation METRICS — establishing LINEAGE. A deployment PIPELINE promotes a version through STAGES (e.g. dev -> staging -> production), often gated by automated checks and human approval; deployment to the serving layer loads the chosen version, frequently via CANARY or SHADOW rollout (route a little/mirror traffic to the new model and compare) before full cutover. The registry always knows the current prod version and prior versions, so ROLLBACK is just re-pointing serving at a previous registered version. A MONITORING component watches the live model's inputs/outputs for DRIFT and performance degradation and can trigger alerts/retraining (closing the loop back to training and registration). Trace it: train -> register v5 (artifact + data/code/metrics) -> promote to staging -> canary in prod -> full prod; later drift detected -> roll back to v4 / retrain -> v6. Registry (source of truth) + staged safe deployment + monitoring is the shape."),
      K("api", "API design",
        "register(model_name, version, artifact_uri, { dataset, code_commit, params, metrics })\npromote(model_name, version, stage)        // dev -> staging -> production (approval)\ndeploy(model_name, stage)                  // serving loads that version (canary/shadow)\nget_current(model_name, stage) -> version  // what's serving now\nrollback(model_name, stage) -> prior version\nmonitor: log predictions -> detect drift -> alert/trigger retrain"),
      K("data_model", "Data model",
        "models:   model_name -> versions[]\nversion:  { version, artifact_uri, stage(dev|staging|prod|archived),\n            dataset_version, code_commit, hyperparams, eval_metrics, created_by, ts }\nlineage:  links a model version to the exact data + code that produced it\ndeployments: (model, stage) -> current version (+ history for rollback)\nmonitoring: prediction logs + drift metrics per deployed model"),
      C("deep_dive", "Deep dive: versioning, lineage & reproducibility",
        "The registry's foundational job is making models VERSIONED and REPRODUCIBLE. Unlike code, a model is determined by its TRAINING DATA + code + hyperparameters, so simply versioning the model file isn't enough — you must capture LINEAGE: which dataset version, which code commit, and which params produced THIS model version. With that, you can answer 'how was the prod model built?', reproduce it, debug a regression, and satisfy audit/compliance — without it, a model is an opaque artifact nobody can recreate or trust. The registry stores each version's artifact (in object storage) plus this metadata and its EVALUATION METRICS, so versions are comparable by quality (accuracy/precision on a holdout set), not just by name — promotion decisions are metric-driven. The registry becomes the single SOURCE OF TRUTH for 'what models exist, how each was made, how good each is, and which is deployed where'. This versioning + lineage + metrics is what turns ad-hoc model files scattered in notebooks into a governed, reproducible, comparable catalog — the prerequisite for everything else (safe deployment, rollback, audit)."),
      C("deep_dive", "Deep dive: deployment, rollout & drift monitoring",
        "Operationalizing models safely mirrors code CI/CD plus ML-specific monitoring. STAGED PROMOTION: a version moves dev -> staging -> production through gates (automated metric checks + human approval), so an unvalidated model can't reach users. SAFE ROLLOUT: rather than a hard switch, use CANARY (send a small % of traffic to the new model, watch its metrics) or SHADOW/dark launch (mirror real traffic to the new model WITHOUT serving its outputs, comparing predictions to the live model offline) or A/B testing — catching a bad model before it affects everyone; if metrics regress, abort. ROLLBACK: because every version is in the registry, reverting prod to a prior known-good version is instant (re-point serving), the ML analog of a code rollback. DRIFT MONITORING is the uniquely-ML part: a model's accuracy SILENTLY DEGRADES as production data diverges from training data (DATA drift) or the relationship being predicted changes (CONCEPT drift) — the code didn't change, but the world did. So you monitor input distributions and prediction quality (where ground truth is available) and ALERT/trigger RETRAINING when drift exceeds thresholds, closing the loop. Staged + canary/shadow deploy, instant rollback, and drift-triggered retraining are what keep deployed models trustworthy."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "REPRODUCIBILITY fails without captured lineage (data + code + params) — the #1 governance gap; enforce it at registration. DRIFT is the silent killer — a model degrades with no code change, so monitoring + retraining is mandatory, but getting ground-truth labels to measure quality can be delayed/expensive (sometimes you only have input-distribution drift as a proxy). SAFE ROLLOUT vs speed: canary/shadow catch bad models but add deployment latency/complexity; skipping them risks shipping a regression to all users. Large artifacts live in object storage (registry holds pointers). Trade-offs: canary/shadow/A-B (safe, slower, more infra) vs direct deploy (fast, risky); automated metric gates (objective) vs human approval (judgment, slower); frequent retraining (fresh, costly, risk of training-pipeline bugs) vs infrequent (stale, drift); shadow (no user impact, no real outcome feedback) vs canary (real impact, real metrics on a few). Closing signal: a versioned registry with lineage/metrics as source of truth, staged promotion + canary/shadow rollout + instant rollback, and drift monitoring that triggers retraining — code-grade CI/CD plus ML-specific drift handling."),
      C("deep_dive", "Deep dive: pipelines, governance & operations",
        "Operationally MLOps wires the registry into automated pipelines and governance. CI/CD for models: a pipeline trains, evaluates against a holdout + the current prod model, registers the version with lineage/metrics, and (if it passes gates) promotes it — automating the path from training to safe deployment. Feature consistency: the features used at serving must match training (else training/serving SKEW silently breaks accuracy) — a feature store helps keep them consistent. Approvals & audit: promotions to prod require approval and are logged (who deployed what, when, why) for governance/compliance — important in regulated domains. Retraining triggers: scheduled, or drift/performance-triggered; a new model re-enters the same register -> evaluate -> canary -> promote loop. Rollback drills: ensure reverting to a prior version is fast and tested. Multi-environment: the same registry serves dev/staging/prod with stage tags. Artifact management: store large model files in object storage with the registry referencing them, plus the runtime/dependencies (container) for reproducible serving. Observability: per-model prediction quality, drift metrics, latency, and deployment success/rollback rate are the SLOs. The spine holds: automated train->register(lineage+metrics)->stage->canary->prod pipelines with drift-triggered retraining and instant rollback, governed and audited."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'Why version models with lineage?' a model = data + code + params; capturing lineage gives reproducibility, debugging, and audit — a model file alone is opaque. 'Compare versions?' by evaluation metrics on a holdout (promotion is metric-driven). 'Deploy safely?' staged promotion + canary or shadow rollout (compare before full cutover) + approvals. 'Rollback?' re-point serving to a prior registered version (instant). 'Model degrades with no code change?' data/concept DRIFT — monitor input distributions + prediction quality, alert/retrain. 'Training/serving skew?' keep features consistent (feature store). 'Retraining cadence?' scheduled or drift-triggered, back through register->canary->promote. 'Big artifacts?' object storage + registry pointers + container for runtime. Each returns to the spine: a versioned, lineage-tracked registry + staged/canary deployment + instant rollback + drift monitoring — code-grade CI/CD plus ML drift handling."),
    ],
    "An ML model registry / MLOps tests treating models as versioned, reproducible artifacts (lineage: data+code+params, comparable by metrics) with code-grade deployment (staged promotion, canary/shadow, instant rollback) PLUS the ML-specific need to monitor data/concept DRIFT and retrain. The signal is lineage for reproducibility, safe staged rollout/rollback, and drift monitoring — not just 'save the model file'.",
    [
      G("no_lineage", "Versioning only the model file, without data/code lineage.", "Capture lineage (dataset version, code commit, params, metrics) for reproducibility.", "Stores model artifacts with no record of how they were built."),
      G("unsafe_deploy", "Hard-swapping a new model into prod with no canary/rollback.", "Stage + canary/shadow rollout with metric gates, and instant rollback to a prior version.", "New model goes straight to 100% prod; no rollback path."),
      G("no_drift", "Assuming a deployed model stays accurate (no monitoring).", "Monitor data/concept drift + prediction quality; alert and retrain on degradation.", "No post-deployment monitoring; model silently degrades."),
    ],
    0.6, DIAG.mlreg, "ML model registry & deployment architecture"),

  // ───────────────────────────── LOAD BALANCER ─────────────────────────────
  TT("sysd_m22", "sysd_m22_t2", 2, "Design a Load Balancer", "design-load-balancer-internals",
    ["case-study", "load-balancer", "health-check", "ha"],
    "Traffic must be spread evenly across a pool of backend servers, dead servers must be skipped automatically, and the thing doing the spreading must itself never become the single point of failure. How does a load balancer distribute traffic, and how do you make the balancer itself highly available?",
    "A LOAD BALANCER distributes incoming requests across healthy backends using an ALGORITHM (round-robin, least-connections, hashing), removing failed servers via HEALTH CHECKS. It operates at L4 (transport — fast, by IP/port) or L7 (application — smart, by HTTP path/header). Crucially, the LB itself is a SPOF, so it's made highly available (active-passive with a floating VIP, or scaled out behind anycast/DNS). Distribution algorithms + L4/L7 + health checks + making the LB itself HA are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: accept client traffic and forward it across a POOL of backend servers; balance load EVENLY (by some algorithm); HEALTH-CHECK backends and stop sending traffic to unhealthy ones; support adding/removing backends (scaling). Non-functional: low added LATENCY (it's on every request), high THROUGHPUT, high AVAILABILITY (the LB must not be a single point of failure — if it dies, the whole service is unreachable), and even distribution (no hot backend). Clarify scope: L4 vs L7 load balancing (very different capabilities), and the deployment (hardware/software/cloud). The two defining problems are (1) HOW to distribute — picking an algorithm and operating level (L4/L7) that spreads load well and routes correctly while skipping dead servers via health checks — and (2) the meta-problem that the LB, by sitting in front of everything, becomes the SINGLE POINT OF FAILURE itself, so a huge part of the design is making the LOAD BALANCER highly available so it can't take the whole system down. Both matter; the second is the one candidates forget."),
      K("estimation", "Capacity estimation (with numbers)",
        "The LB handles ALL traffic: if the service does 100k req/sec, so does the LB.\n  L4 (packet/connection forwarding) is very cheap -> one LB handles huge throughput\n  L7 (parse HTTP, route by content, terminate TLS) costs more CPU per request\nConnections: track active connections (for least-connections / stickiness).\nHealth checks: probe each backend every few seconds.\nTakeaway: L4 is fast/dumb and scales hugely; L7 is smarter but heavier; either way\nthe LB sees all traffic, so it must be HA + horizontally scalable, not one box."),
      C("hld", "High-level design",
        "Clients send traffic to the load balancer (a stable endpoint/VIP). The LB maintains a POOL of backend servers and, for each request/connection, selects a backend using an ALGORITHM (e.g. round-robin or least-connections) and forwards it. It continuously HEALTH-CHECKS backends (active probes to a health endpoint, or passive failure detection) and removes unhealthy ones from rotation so traffic only goes to live servers; new backends are added to the pool as they come up (often via service discovery). It operates at L4 (forwarding packets/connections by IP+port — fast, protocol-agnostic) or L7 (terminating the connection, parsing HTTP, routing by path/host/header, and able to do TLS termination, sticky sessions, content-based routing). Critically, the LB itself is deployed in HIGH AVAILABILITY — typically an ACTIVE-PASSIVE pair sharing a floating Virtual IP that fails over to the standby if the active dies, or multiple active LBs scaled out behind anycast/DNS — so a single LB failure doesn't break the service. Trace a request: client -> VIP (active LB) -> pick a healthy backend by least-connections -> forward -> response; if a backend is unhealthy it's skipped; if the LB dies, the VIP fails over to the standby. Distribution + health checks + LB-level HA is the shape."),
      K("api", "Configuration / behavior",
        "config (not a per-request API):\n  backends: [ server1, server2, server3 ]\n  algorithm: round_robin | least_connections | ip_hash (sticky) | weighted\n  health_check: GET /healthz every 3s, mark down after N fails\n  level: L4 (TCP/UDP by ip:port) | L7 (HTTP, route by path/host, TLS terminate)\nHA: active-passive pair + floating VIP (failover) OR N active LBs via anycast/DNS\nconnection draining: stop new conns to a backend, let existing finish (graceful)"),
      K("data_model", "Data model / state",
        "backend pool: [ { addr, weight, health: up|down, active_connections } ]\nalgorithm state: round-robin pointer / least-conn counts / hash ring (sticky)\nhealth: per-backend check results (consecutive failures -> mark down)\nLB HA: VIP ownership (active vs standby) + heartbeat between LB instances\n(L7) TLS certs, routing rules (path/host -> backend pool)"),
      C("deep_dive", "Deep dive: L4 vs L7 & distribution algorithms",
        "Two design axes. LEVEL — L4 (transport) load balancing forwards packets/connections based only on IP and port; it doesn't look inside the traffic, so it's extremely FAST and protocol-agnostic but 'dumb' (can't route by URL or do HTTP-aware things). L7 (application) load balancing terminates the connection and understands HTTP, so it can route by PATH/host/header (content-based routing), terminate TLS, do sticky sessions, rewrite requests, and cache — far smarter, at higher CPU cost per request (it's essentially what an API gateway/reverse proxy does). ALGORITHMS — how to pick a backend: ROUND ROBIN (rotate through backends — simple, even when requests are uniform); LEAST CONNECTIONS (send to the backend with the fewest active connections — better when request durations vary); WEIGHTED (bias toward more powerful servers); IP/CONSISTENT HASH (map a client/key to a consistent backend — for session STICKINESS or cache locality). The choice depends on whether requests are uniform, whether sessions need stickiness, and backend heterogeneity. L4-vs-L7 (speed vs smarts) and the distribution algorithm (even spread vs stickiness vs weighting) are the core knobs."),
      C("deep_dive", "Deep dive: health checks & making the LB itself HA",
        "Two reliability concerns. HEALTH CHECKS keep traffic off dead backends: the LB ACTIVELY probes each backend (e.g. GET /healthz every few seconds) and marks it DOWN after N consecutive failures (removing it from rotation), and back UP when it recovers — plus PASSIVE detection (treat connection errors/timeouts as failures). Tuning matters: too aggressive flaps healthy backends out on a blip; too lazy keeps routing to dead ones (failed requests) — so thresholds balance freshness vs stability, and CONNECTION DRAINING lets in-flight requests finish when a backend is removed gracefully. The bigger issue is that the LB ITSELF IS A SPOF — everything flows through it, so its failure = total outage. Make the LB HIGHLY AVAILABLE: the classic pattern is an ACTIVE-PASSIVE pair sharing a floating VIRTUAL IP (VIP) with a heartbeat between them — if the active LB dies, the standby takes over the VIP (failover) in seconds; alternatively run MULTIPLE ACTIVE LBs and distribute across them via ANYCAST (same IP announced from several, routed to the nearest/healthy) or DNS (multiple LB IPs) — which also scales throughput. So you never rely on one LB. Health-checking backends AND making the balancer itself redundant are both required for a truly available system."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "The LB as SPOF is the headline — solved by HA (active-passive VIP failover or multiple active LBs via anycast/DNS); a single LB is unacceptable. The LB as a THROUGHPUT bottleneck — L4 scales hugely (cheap), L7 is heavier (parsing/TLS) so it may need scaling out. Health-check tuning trades flapping vs routing-to-dead. Sticky sessions (needed for stateful backends) reduce balancing evenness and complicate scaling — prefer stateless backends so any LB algorithm works. Uneven load if the algorithm mismatches the workload (round-robin with very uneven request costs -> use least-connections). Trade-offs: L4 (fast, dumb, protocol-agnostic) vs L7 (smart content routing/TLS/stickiness, heavier); round-robin (simple, uniform) vs least-connections (varied durations) vs hash (stickiness/locality); active-passive (simple HA, idle standby) vs active-active (scales + HA, more complex); stateless backends (easy balancing) vs sticky (needed for session state, uneven). Closing signal: distribute via an appropriate L4/L7 + algorithm to health-checked backends, and make the LB itself HA (VIP failover or anycast) so it's not a SPOF."),
      C("deep_dive", "Deep dive: scaling, stickiness & operations",
        "Operationally a load balancer must scale, route correctly, and self-heal. Scaling backends: integrate with autoscaling/service discovery so backends are added/removed from the pool automatically as they scale or fail; connection draining ensures graceful removal. Scaling the LB: for very high traffic, run multiple LBs (active-active) behind anycast or DNS round-robin (often a fast L4 tier in front of smarter L7 LBs — a layered design); cloud LBs do this transparently. Stickiness: if backends hold session state, use IP-hash/cookie-based affinity so a client returns to the same backend — but this hurts even distribution and breaks when that backend dies, so the better answer is usually stateless backends (state in a shared store) enabling free balancing. Global load balancing: DNS/anycast routes users to the nearest regional LB (geo load balancing), which then balances locally. TLS: L7 LBs terminate TLS centrally (offloading backends). Failover testing: regularly verify VIP failover and that health checks correctly eject bad nodes. Observability: per-backend request/error rates and latency, health status, LB CPU/throughput, and failover events are the SLOs. The spine holds: health-checked distribution (L4/L7 + algorithm), autoscaling-integrated backend pools, stickiness only when needed, and a highly-available (failover/anycast) LB tier."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'L4 vs L7?' L4 forwards by ip:port (fast, dumb); L7 understands HTTP (route by path/header, TLS terminate, stickiness) at higher cost. 'Which algorithm?' round-robin (uniform), least-connections (varied durations), weighted (heterogeneous backends), hash (stickiness/locality). 'How are dead servers handled?' active health checks (+ passive) mark them down and drain connections. 'Isn't the LB a SPOF?' yes — make it HA: active-passive with a floating VIP failover, or multiple active LBs via anycast/DNS. 'Sticky sessions?' IP-hash/cookie affinity, but prefer stateless backends (state in a shared store) for even balancing. 'Scale the LB?' active-active behind anycast/DNS, often L4-in-front-of-L7 layering. 'Global traffic?' DNS/anycast to the nearest regional LB. Each returns to the spine: distribute to health-checked backends by an appropriate L4/L7 + algorithm, integrate autoscaling, and make the LB itself highly available."),
    ],
    "A load balancer tests distribution (L4 vs L7; round-robin/least-connections/hash) to health-checked backends AND — the part candidates miss — making the LB itself highly available (active-passive VIP failover or active-active anycast/DNS) so it's not a SPOF. The signal is the right level+algorithm + health checks, plus redundancy for the balancer itself; prefer stateless backends over sticky sessions.",
    [
      G("lb_spof", "Designing a single load balancer (it becomes the SPOF).", "Make the LB HA: active-passive with a floating VIP failover, or active-active via anycast/DNS.", "One LB in front of everything; no HA for the LB itself."),
      G("no_health", "Distributing to backends with no health checking.", "Active (+ passive) health checks to eject dead backends; connection draining.", "Sends traffic to all backends regardless of health."),
      G("l4_l7_confusion", "Not distinguishing L4 vs L7 / picking a wrong algorithm.", "Choose L4 (fast) vs L7 (content routing/TLS/stickiness) and an algorithm fitting the workload.", "No mention of L4/L7 or why a given algorithm."),
    ],
    0.5, DIAG.lb, "Load balancer architecture"),

  // ─────────────────────────────── DNS SERVICE ─────────────────────────────
  TT("sysd_m22", "sysd_m22_t1", 1, "Design a DNS Service", "design-dns-service",
    ["case-study", "dns", "caching", "anycast"],
    "Every connection on the internet starts by turning a name like api.example.com into an IP address — billions of times per second, globally, with sub-millisecond expectations, and if it goes down, you effectively vanish from the internet. How do you build name resolution that's that fast, that scalable, and that available?",
    "DNS is a hierarchical, heavily-CACHED lookup system: a resolver walks root -> TLD -> AUTHORITATIVE nameserver to get a record, and CACHING with TTLs at every level means the vast majority of queries are answered from cache (not the authoritative servers) — which is what makes it scale. ANYCAST places authoritative servers near users globally (latency + DDoS resilience), and DNS can do geo/latency-based ROUTING (return different IPs by location). Hierarchy + caching/TTL + availability/anycast are the substance.",
    [
      C("requirements", "Requirements",
        "Functional: resolve a domain NAME to records (A/AAAA = IP, CNAME = alias, MX, etc.); let domain owners manage their zone records; and optionally route based on the client's location/health (DNS-based load balancing). Non-functional: extremely low LATENCY (resolution is on the critical path of every connection — milliseconds), massive SCALE (billions of queries/sec globally), and very high AVAILABILITY (DNS down = your services are unreachable even if they're up — it's foundational), plus reasonable propagation of changes. Clarify scope: authoritative DNS (serving YOUR domain's records) vs recursive resolvers (looking up on behalf of clients) — both matter. The defining realities: DNS is a GLOBAL, hierarchical, read-dominated system whose scale is achieved almost entirely through CACHING (most queries never reach the authoritative servers), where AVAILABILITY is paramount (it's the entry point to everything), and where the propagation of changes is governed by cache TTLs (so updates aren't instant). The design is fundamentally about a cacheable hierarchy served close to users."),
      K("estimation", "Capacity estimation (with numbers)",
        "Query volume is enormous (every new connection): billions/sec globally.\n  BUT caching means authoritative servers see a tiny fraction:\n  with TTL=300s, a popular record is fetched from authoritative ~once per cache\n  per 5 min, not per request -> caching is a massive multiplier.\nRecords are small and read-mostly (writes = occasional zone edits).\nAnycast: the same IP served from many global locations -> nearby + DDoS-resilient.\nTakeaway: caching + TTL absorb almost all load; authoritative servers handle the\nsmall cache-miss residue; latency/availability come from anycast + redundancy."),
      C("hld", "High-level design",
        "DNS is a hierarchy. A client asks a RECURSIVE RESOLVER (e.g. its ISP's or 8.8.8.8) to resolve a name; the resolver, if not cached, walks the hierarchy: ask a ROOT server (which points to the TLD server for .com), ask the TLD server (which points to the AUTHORITATIVE nameserver for example.com), ask the AUTHORITATIVE server (which returns the actual record). Every level CACHES results with a TTL, so subsequent queries for the same name are answered from the resolver's (or OS/browser's) cache without walking the hierarchy again — which is why authoritative servers see only a small fraction of total queries. Authoritative servers are made highly available and globally close via ANYCAST (the same IP announced from many locations; routing sends the query to the nearest), and they can return DIFFERENT records by client location/health (geo/latency-based routing, DNS load balancing). Trace a lookup: client -> resolver (cache miss) -> root -> TLD (.com) -> authoritative (example.com) -> A record -> cached at TTL -> returned; next time -> served from cache. Hierarchy + pervasive caching + anycast availability is the shape."),
      K("api", "API / protocol",
        "query(name, type) -> records   // e.g. query('api.example.com', 'A') -> [IPs] + TTL\n  resolution: resolver -> root -> TLD -> authoritative (each cached by TTL)\nrecord types: A/AAAA (IP), CNAME (alias), MX (mail), NS (nameserver), TXT, ...\nzone management (authoritative): create/update records with a TTL\nsmart routing: return different A records by geo/latency/health (DNS LB)"),
      K("data_model", "Data model",
        "zone:    domain -> set of records [ { name, type, value, TTL } ]\n  e.g. api.example.com  A  93.184.216.34  TTL=300\ncaches:  resolver/OS/browser cache: name -> records, expires_at (= now + TTL)\nhierarchy: root -> TLD (.com) -> authoritative NS (example.com)\nanycast: authoritative servers share IPs announced from many global sites\n(geo) policy: name -> different value by client region/health"),
      C("deep_dive", "Deep dive: the hierarchy & caching (TTL)",
        "Two intertwined ideas make DNS work at internet scale. The HIERARCHY distributes authority and avoids any single global database: the root servers know where each TLD's servers are, TLD servers (.com, .org) know where each domain's authoritative servers are, and authoritative servers hold the actual records — so resolving a new name walks root -> TLD -> authoritative, and no one server must know everything. But walking the full hierarchy for every query would overwhelm the upper levels, so CACHING is the load-bearing mechanism: every record carries a TTL, and resolvers (and the OS and browser) cache the answer for that TTL, serving all repeat queries from cache without contacting the hierarchy again. Because popular names are queried constantly, the cache hit rate is enormous and authoritative servers see only a trickle — caching is what turns billions of queries into a manageable load. The TTL is the key knob: a LONG TTL means better caching (less load, faster) but slower PROPAGATION of changes (old IPs cached for up to the TTL after you change a record); a SHORT TTL propagates changes fast but increases query load and latency. So 'DNS changes take time to propagate' is exactly this TTL caching at work. Hierarchy (distributed authority) + caching/TTL (scale + the propagation trade-off) are the core."),
      C("deep_dive", "Deep dive: availability, anycast & smart routing",
        "DNS must be exceptionally available and is also a routing tool. AVAILABILITY: because DNS is the entry point to everything (if name resolution fails, your services are unreachable even when healthy), authoritative DNS is run with heavy redundancy — multiple authoritative nameservers, often across providers, with no single point of failure. ANYCAST is the key technique: the same authoritative IP address is announced from MANY locations worldwide, and internet routing (BGP) delivers each query to the NEAREST instance — this gives low latency (a server is always close), massive aggregate capacity, and DDoS RESILIENCE (attack traffic is absorbed across all the anycast sites rather than hitting one). SMART ROUTING: because DNS decides which IP a client gets, it doubles as a global load-balancing/traffic-steering layer — return DIFFERENT records based on the client's geographic location (geo-routing: send users to the nearest datacenter), latency, or backend HEALTH (failover: stop returning a dead region's IP) — this is GeoDNS / DNS-based load balancing, used for global traffic management and disaster failover (with the caveat that TTL caching slows how fast a failover takes effect). Anycast for availability/latency/DDoS + DNS as a smart global router are what make DNS both robust and a powerful traffic-control tool."),
      C("bottlenecks", "Bottlenecks & trade-offs",
        "AVAILABILITY is paramount — DNS is foundational, so redundancy (multiple nameservers/providers, anycast) is non-negotiable; an outage takes you off the internet. PROPAGATION DELAY is inherent to caching — a record change isn't seen until cached TTLs expire, so changes (and DNS-based failover) are not instant; pre-lower TTLs before a planned change. DDoS: DNS is a prime attack target (and amplification vector) — anycast absorbs/spreads attacks. CONSISTENCY: caching means different clients may briefly see different (old vs new) records during a change — eventual consistency by design. The TTL is the central trade. Trade-offs: long TTL (better caching/scale/latency, slow propagation) vs short TTL (fast changes/failover, more load + latency); anycast (latency + DDoS resilience + capacity, complex routing) vs unicast; aggressive geo-routing/DNS-LB (smart global steering, but TTL-limited responsiveness) vs simple static records; many providers (resilience) vs one (simpler). Closing signal: a cached hierarchy (root->TLD->authoritative) where TTL caching provides scale (and the propagation trade-off), made available + low-latency + DDoS-resilient via anycast and redundant nameservers, doubling as a geo/health-aware global router."),
      C("deep_dive", "Deep dive: change propagation, security & operations",
        "Operationally DNS balances cacheability, correctness, and security. Change management: because TTLs gate propagation, operators LOWER the TTL well before a planned record change (so caches expire quickly around the cutover) then raise it back — essential for fast, predictable failovers/migrations; emergency changes are still bounded by whatever TTL clients last cached. Redundancy: run multiple authoritative nameservers (ideally across providers/networks) so no single failure or provider outage breaks resolution; anycast each. Security: DNS is spoofable, so DNSSEC signs records so resolvers can verify authenticity (preventing cache poisoning), and rate-limiting/anycast mitigate DDoS and amplification abuse. Health-checked failover: GeoDNS/traffic management integrates backend health so a dead region's IP stops being returned (a global failover layer, TTL-limited in speed). Negative caching: cache NXDOMAIN (no such name) too, to avoid hammering authoritative servers for bad names. Monitoring: query volume, cache hit rates, resolution latency by region, authoritative server health, and propagation are the SLOs. Note many teams USE managed DNS (Route 53/Cloudflare) rather than build it — know the model regardless. Observability: per-region latency, authoritative QPS (cache-miss residue), availability, and DNSSEC validation are tracked. The spine holds: a redundant, anycast, DNSSEC-secured cached hierarchy with TTL-managed propagation and health-aware geo-routing."),
      C("deep_dive", "Common follow-ups & how it evolves",
        "Expect: 'How does DNS scale to billions of queries?' pervasive CACHING with TTLs at resolver/OS/browser — authoritative servers see only the cache-miss residue. 'Why do DNS changes take time?' cached records live until their TTL expires (propagation delay) — lower TTL before a planned change. 'Make it low-latency + available globally?' ANYCAST (same IP from many sites, routed to nearest) + redundant nameservers across providers. 'DDoS?' anycast spreads/absorbs it; rate-limit; DNSSEC stops spoofing/cache poisoning. 'Route users to the nearest datacenter / failover?' GeoDNS / DNS-based load balancing returns different IPs by location/health (TTL-limited speed). 'Resolution path?' resolver -> root -> TLD -> authoritative, each cached. 'Negative results?' cache NXDOMAIN. 'Build vs buy?' often managed DNS, but the model is the same. Each returns to the spine: a cached hierarchy (TTL = scale + propagation trade-off), made available/low-latency/DDoS-resilient by anycast + redundancy, doubling as a geo/health-aware global router."),
    ],
    "A DNS service tests a hierarchical, heavily-cached resolution system (root->TLD->authoritative) where TTL CACHING provides the scale (and the propagation trade-off), made highly available and low-latency via ANYCAST + redundant nameservers (and DDoS-resilient), doubling as a geo/health-aware global router. The signal is caching/TTL as the scaling mechanism, anycast for availability, and TTL as the propagation knob.",
    [
      G("no_caching", "Designing DNS without caching/TTL as the scaling mechanism.", "Cache records by TTL at every level — authoritative servers should see only cache misses.", "Every query walks to authoritative servers; no caching story."),
      G("dns_not_ha", "Treating DNS as ordinary and not specially available.", "Run redundant authoritative nameservers + anycast; DNS down = total outage.", "Single nameserver / no anycast or redundancy for foundational DNS."),
      G("ignore_ttl_propagation", "Expecting record changes (or failover) to take effect instantly.", "Account for TTL-bound propagation; lower TTL before planned changes.", "Assumes a record change is seen immediately everywhere."),
    ],
    0.6, DIAG.dns, "DNS service architecture"),
];

// ── 3 exercises per topic ────────────────────────────────────────────────────
const xpFor = (l) => (l === "warmup" ? 5 : l === "easy" ? 10 : l === "medium" ? 15 : 20);
const diffFor = (l) => (l === "warmup" ? 0.1 : l === "easy" ? 0.2 : l === "medium" ? 0.4 : 0.6);
function pm(moduleId, o) {
  return { trackKey: TRACK_KEY, moduleId, topicId: o.topicId, exerciseId: o.exerciseId,
    position: o.position, level: o.level, type: "pattern_match", title: o.title, scenario: o.scenario,
    instructions: "Pick the best answer.", starterCode: "", expectedSolution: o.correct,
    blanks: [{ options: o.options }], testCases: [{ type: "pattern_match", correct: o.correct, explanation: o.explanation }],
    hints: [], xpReward: xpFor(o.level), difficulty: diffFor(o.level) };
}

const EXERCISES = [
  // Vector DB
  pm("sysd_m18", { topicId: "sysd_m18_t1", exerciseId: "sysd_m18_t1_pm_d1", position: 11, level: "hard",
    title: "Why not exact search?", scenario: "Finding nearest neighbors among 100M high-dim vectors per query — what do vector DBs use?",
    options: ["An approximate nearest-neighbor index (HNSW/IVF)", "A full linear scan computing all distances", "A B-tree on one dimension", "A hash map"],
    correct: "An approximate nearest-neighbor index (HNSW/IVF)",
    explanation: "Exact kNN is O(n·d) — too slow at scale; ANN indexes (HNSW graph / IVF clustering) find very-likely-nearest neighbors in sublinear time, trading a little recall." }),
  pm("sysd_m18", { topicId: "sysd_m18_t1", exerciseId: "sysd_m18_t1_pm_d2", position: 12, level: "medium",
    title: "The core trade-off", scenario: "What's the fundamental knob when tuning an ANN index?",
    options: ["Recall vs latency/memory", "Consistency vs availability", "Read vs write", "Latency vs durability"],
    correct: "Recall vs latency/memory",
    explanation: "Searching more (more graph hops / clusters probed, full precision) raises recall but costs latency/memory; ANN is approximate by design." }),
  pm("sysd_m18", { topicId: "sysd_m18_t1", exerciseId: "sysd_m18_t1_pm_d3", position: 13, level: "medium",
    title: "Fitting huge vector sets", scenario: "Vectors + index exceed one node's RAM. What helps fit/scale them?",
    options: ["Shard by vector + quantization (compress vectors), re-rank at full precision", "Store them on disk and scan", "Reduce to 1 dimension", "Use a relational table"],
    correct: "Shard by vector + quantization (compress vectors), re-rank at full precision",
    explanation: "Shard across nodes (scatter-gather) and quantize to cut memory; re-rank the top candidates with full-precision vectors to recover recall." }),
  // RAG
  pm("sysd_m18", { topicId: "sysd_m18_t2", exerciseId: "sysd_m18_t2_pm_d1", position: 11, level: "medium",
    title: "Grounding an LLM in your data", scenario: "How do you get an LLM to answer accurately about your private, current docs?",
    options: ["Retrieve relevant chunks and inject them into the prompt as context (RAG)", "Hope the model already knows", "Fine-tune on every change", "Increase temperature"],
    correct: "Retrieve relevant chunks and inject them into the prompt as context (RAG)",
    explanation: "RAG embeds + indexes your docs, retrieves the relevant chunks for a question, and puts them in the prompt so the LLM answers grounded (cited), not from memory." }),
  pm("sysd_m18", { topicId: "sysd_m18_t2", exerciseId: "sysd_m18_t2_pm_d2", position: 12, level: "hard",
    title: "What dominates answer quality?", scenario: "RAG answers are wrong even with a great LLM. Most likely cause?",
    options: ["Poor retrieval (bad chunking/embeddings) — garbage context in, garbage out", "The model is too small", "Temperature too low", "Not enough GPUs"],
    correct: "Poor retrieval (bad chunking/embeddings) — garbage context in, garbage out",
    explanation: "The LLM can only ground on what's retrieved; if retrieval surfaces the wrong chunks, the answer is wrong — retrieval quality (chunking, embeddings, hybrid, re-rank) dominates." }),
  pm("sysd_m18", { topicId: "sysd_m18_t2", exerciseId: "sysd_m18_t2_pm_d3", position: 13, level: "medium",
    title: "RAG vs fine-tuning", scenario: "Your knowledge base changes weekly and answers must cite sources. RAG or fine-tuning?",
    options: ["RAG — update by re-indexing, citable, no retraining", "Fine-tune weekly", "Neither", "Fine-tune once and never update"],
    correct: "RAG — update by re-indexing, citable, no retraining",
    explanation: "RAG injects knowledge at query time, so updates are just re-indexing and answers can cite retrieved sources; fine-tuning bakes static knowledge into weights (costly, no citations)." }),
  // LLM serving
  pm("sysd_m18", { topicId: "sysd_m18_t3", exerciseId: "sysd_m18_t3_pm_d1", position: 11, level: "hard",
    title: "Using the GPU efficiently", scenario: "Serving one LLM request at a time barely uses the GPU. What maximizes throughput?",
    options: ["Continuous (in-flight) batching of many requests", "A faster CPU", "Bigger disks", "One request per GPU always"],
    correct: "Continuous (in-flight) batching of many requests",
    explanation: "GPUs are throughput devices; continuous batching adds/removes requests every token step so the GPU stays saturated and short requests don't wait on long ones (~10x throughput)." }),
  pm("sysd_m18", { topicId: "sysd_m18_t3", exerciseId: "sysd_m18_t3_pm_d2", position: 12, level: "hard",
    title: "What limits batch size?", scenario: "What primarily caps how many requests you can batch on a GPU?",
    options: ["GPU memory — the KV-cache (grows with tokens) plus weights", "CPU cores", "Network bandwidth", "Disk IOPS"],
    correct: "GPU memory — the KV-cache (grows with tokens) plus weights",
    explanation: "Weights + the per-request KV-cache (grows with sequence length/concurrency) fill GPU memory and cap concurrency; paged attention + quantization help fit more." }),
  pm("sysd_m18", { topicId: "sysd_m18_t3", exerciseId: "sysd_m18_t3_pm_d3", position: 13, level: "medium",
    title: "A model too big for one GPU", scenario: "The model's weights don't fit in a single GPU. What do you do?",
    options: ["Shard it across GPUs (tensor/pipeline parallelism)", "Run it on CPU", "Truncate the model", "Use one request at a time"],
    correct: "Shard it across GPUs (tensor/pipeline parallelism)",
    explanation: "Model parallelism splits layers across GPUs (tensor) and/or stages across GPUs (pipeline) so a large model can load and run, at the cost of inter-GPU communication." }),
  // ML model registry
  pm("sysd_m18", { topicId: "sysd_m18_t4", exerciseId: "sysd_m18_t4_pm_d1", position: 11, level: "medium",
    title: "Reproducible models", scenario: "Why version models WITH lineage (data + code + params), not just the file?",
    options: ["A model = its training data + code; lineage gives reproducibility/audit/debugging", "To save disk space", "It runs faster", "No reason"],
    correct: "A model = its training data + code; lineage gives reproducibility/audit/debugging",
    explanation: "Unlike code, a model depends on its training data and params; capturing lineage lets you reproduce, debug, audit, and compare versions — a bare model file is opaque." }),
  pm("sysd_m18", { topicId: "sysd_m18_t4", exerciseId: "sysd_m18_t4_pm_d2", position: 12, level: "hard",
    title: "Deploying a new model safely", scenario: "How do you avoid a new model silently harming users on deploy?",
    options: ["Staged promotion + canary/shadow rollout with metric gates + instant rollback", "Deploy straight to 100% prod", "Skip evaluation", "Never update the model"],
    correct: "Staged promotion + canary/shadow rollout with metric gates + instant rollback",
    explanation: "Promote through stages, canary (small % traffic) or shadow (mirror traffic, compare offline) before full cutover, and roll back instantly to a prior registered version if metrics regress." }),
  pm("sysd_m18", { topicId: "sysd_m18_t4", exerciseId: "sysd_m18_t4_pm_d3", position: 13, level: "medium",
    title: "A model degrades with no code change", scenario: "Accuracy drops in production though nothing was deployed. What's happening and what do you do?",
    options: ["Data/concept drift — monitor inputs+quality and retrain", "The code rotted", "The GPU is slow", "Nothing can be done"],
    correct: "Data/concept drift — monitor inputs+quality and retrain",
    explanation: "Production data diverges from training data (drift), silently degrading the model; monitor input distributions + prediction quality and trigger retraining." }),
  // Load balancer
  pm("sysd_m22", { topicId: "sysd_m22_t2", exerciseId: "sysd_m22_t2_pm_d1", position: 11, level: "hard",
    title: "The LB is a SPOF", scenario: "Everything flows through the load balancer. How do you stop it being a single point of failure?",
    options: ["Make it HA: active-passive with a floating VIP failover, or active-active via anycast/DNS", "Buy a bigger LB", "Add more backends", "Cache on the client"],
    correct: "Make it HA: active-passive with a floating VIP failover, or active-active via anycast/DNS",
    explanation: "A single LB takes down the whole service if it dies; run an HA pair sharing a VIP (failover) or multiple active LBs behind anycast/DNS." }),
  pm("sysd_m22", { topicId: "sysd_m22_t2", exerciseId: "sysd_m22_t2_pm_d2", position: 12, level: "medium",
    title: "L4 vs L7", scenario: "You need to route by URL path and terminate TLS. Which load balancing level?",
    options: ["L7 (application) — understands HTTP", "L4 (transport) — only ip:port", "Neither", "Both are identical"],
    correct: "L7 (application) — understands HTTP",
    explanation: "L7 terminates the connection and parses HTTP, enabling path/header routing, TLS termination, and stickiness; L4 only forwards by ip:port (faster but content-blind)." }),
  pm("sysd_m22", { topicId: "sysd_m22_t2", exerciseId: "sysd_m22_t2_pm_d3", position: 13, level: "medium",
    title: "Skipping dead servers", scenario: "How does the LB avoid sending traffic to a crashed backend?",
    options: ["Health checks mark it down and remove it from rotation", "It keeps sending and hopes", "Round-robin ignores health", "The client retries forever"],
    correct: "Health checks mark it down and remove it from rotation",
    explanation: "Active (+ passive) health checks detect failures and remove the backend from the pool (with connection draining), so traffic only goes to healthy servers." }),
  // DNS
  pm("sysd_m22", { topicId: "sysd_m22_t1", exerciseId: "sysd_m22_t1_pm_d1", position: 11, level: "medium",
    title: "How DNS scales", scenario: "DNS handles billions of queries/sec. What mechanism makes that possible?",
    options: ["Pervasive caching with TTLs at every level", "One huge database", "Querying authoritative servers every time", "Sharding by user"],
    correct: "Pervasive caching with TTLs at every level",
    explanation: "Resolvers/OS/browsers cache records for their TTL, so most queries are served from cache and authoritative servers see only the small cache-miss residue." }),
  pm("sysd_m22", { topicId: "sysd_m22_t1", exerciseId: "sysd_m22_t1_pm_d2", position: 12, level: "hard",
    title: "Latency, availability, DDoS", scenario: "How do you make authoritative DNS low-latency globally and resilient to DDoS?",
    options: ["Anycast — announce the same IP from many sites; routing hits the nearest", "One big server in one region", "Disable caching", "Use TCP only"],
    correct: "Anycast — announce the same IP from many sites; routing hits the nearest",
    explanation: "Anycast puts servers near users (low latency), adds aggregate capacity, and spreads/absorbs DDoS across all sites; combined with redundant nameservers for availability." }),
  pm("sysd_m22", { topicId: "sysd_m22_t1", exerciseId: "sysd_m22_t1_pm_d3", position: 13, level: "medium",
    title: "Why changes take time", scenario: "You changed a DNS record but old clients still hit the old IP. Why?",
    options: ["Cached records live until their TTL expires (propagation delay)", "DNS is broken", "Records never change", "The client is hacked"],
    correct: "Cached records live until their TTL expires (propagation delay)",
    explanation: "TTL caching means a changed record isn't seen until cached copies expire; lower the TTL before a planned change so it propagates faster (also limits failover speed)." }),
];

// ── upsert + recompute ──────────────────────────────────────────────────────
async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  const moduleIds = [...new Set(TOPICS.map((t) => t.moduleId))];
  for (const mid of moduleIds) {
    const m = await ProModule.findOne({ trackKey: TRACK_KEY, moduleId: mid }).lean();
    if (!m) throw new Error(`Module ${mid} not found — run the base SD seeds first.`);
  }
  let tUp = 0, eUp = 0;
  for (const t of TOPICS) { await ProTopic.updateOne({ trackKey: TRACK_KEY, topicId: t.topicId }, { $set: t }, { upsert: true }); tUp++; }
  for (const e of EXERCISES) { await ProExercise.updateOne({ trackKey: TRACK_KEY, exerciseId: e.exerciseId }, { $set: e }, { upsert: true }); eUp++; }
  const totals = await recomputeTrackTotals(TRACK_KEY);
  console.log(`✓ Depth batch 8 seeded: ${tUp} topics deepened, ${eUp} exercises upserted.`);
  console.log(`  track totals now: ${JSON.stringify(totals)}`);
  await mongoose.disconnect();
}
run().catch((err) => { console.error(err); process.exit(1); });
