import "dotenv/config";
import mongoose from "mongoose";
import { Question } from "../models/index.js";

const BOARD = "AP_SSC", GRADE = "9";

const questions = [
  // ─────────────────────────────────────────────────────────
  // TOPIC 1: ap_ssc_math9_ch1_irrational_numbers  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch1_irrational_a01",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Which of the following is an irrational number?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "√9",   type: "concept_error", logicTag: "perfect_square_root" },
      { text: "√2",   type: "correct",       logicTag: "non_perfect_square_root" },
      { text: "22/7", type: "concept_error", logicTag: "rational_pi_approx" },
      { text: "0.25", type: "concept_error", logicTag: "terminating_decimal" },
    ],
    solutionSteps: [
      "√9 = 3, a whole number → rational.",
      "22/7 is a fraction p/q with integers → rational.",
      "0.25 = 1/4 → rational terminating decimal.",
      "√2 cannot be written as p/q for any integers p, q → irrational.",
    ],
    shortcut: "Check if the radicand is a perfect square. If not → irrational.",
    bloomLevel: "understand", conceptTested: "Identifying irrational numbers",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a02",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Which of the following is NOT an irrational number?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "π",       type: "concept_error", logicTag: "famous_irrational" },
      { text: "√3",      type: "concept_error", logicTag: "non_perfect_square" },
      { text: "√16",     type: "correct",       logicTag: "perfect_square_equals_4" },
      { text: "√5",      type: "concept_error", logicTag: "non_perfect_square" },
    ],
    solutionSteps: [
      "π ≈ 3.14159… is non-terminating non-repeating → irrational.",
      "√3 ≈ 1.732… is non-terminating non-repeating → irrational.",
      "√5 ≈ 2.236… is non-terminating non-repeating → irrational.",
      "√16 = 4, a whole number → rational, NOT irrational.",
    ],
    shortcut: "√n is rational only when n is a perfect square.",
    bloomLevel: "understand", conceptTested: "Distinguishing rational from irrational",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a03",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Every irrational number is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "A natural number",        type: "concept_error", logicTag: "subset_confusion" },
      { text: "A real number",           type: "correct",       logicTag: "real_number_includes_irrationals" },
      { text: "A rational number",       type: "concept_error", logicTag: "definition_confusion" },
      { text: "A whole number",          type: "concept_error", logicTag: "subset_confusion" },
    ],
    solutionSteps: [
      "Irrational numbers cannot be expressed as p/q → not rational.",
      "They are certainly not natural or whole numbers.",
      "Real numbers = Rational ∪ Irrational. Every irrational is a real number.",
    ],
    shortcut: "ℝ = ℚ ∪ Irrationals — irrationals live inside ℝ.",
    bloomLevel: "remember", conceptTested: "Classification of real numbers",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a04",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Between any two rational numbers there exists:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "No irrational number",               type: "concept_error", logicTag: "density_wrong" },
      { text: "Exactly one irrational number",      type: "concept_error", logicTag: "density_wrong" },
      { text: "Infinitely many irrational numbers", type: "correct",       logicTag: "density_of_irrationals" },
      { text: "Only rational numbers",              type: "concept_error", logicTag: "density_wrong" },
    ],
    solutionSteps: [
      "The real line is densely packed — between any two rationals there are infinitely many irrationals.",
      "Example: between 1 and 2 lie √2, √3, π - 1, … (all irrational).",
    ],
    shortcut: "Density property: both rationals and irrationals are dense in ℝ.",
    bloomLevel: "understand", conceptTested: "Density of irrational numbers",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a05",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "The product of two irrational numbers is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Always irrational",     type: "concept_error", logicTag: "overgeneralisation" },
      { text: "Always rational",       type: "concept_error", logicTag: "overgeneralisation" },
      { text: "Sometimes rational",    type: "correct",       logicTag: "closure_not_guaranteed" },
      { text: "Always a whole number", type: "concept_error", logicTag: "completely_wrong" },
    ],
    solutionSteps: [
      "√2 × √2 = 2 (rational) — product of two irrationals is rational here.",
      "√2 × √3 = √6 (irrational) — product of two irrationals is irrational here.",
      "So the product can be either; answer: sometimes rational.",
    ],
    shortcut: "Irrationals are NOT closed under multiplication.",
    bloomLevel: "analyse", conceptTested: "Closure property for irrationals",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a06",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "If p is a prime, then √p is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Always rational",   type: "concept_error", logicTag: "incorrect_property" },
      { text: "Always irrational", type: "correct",       logicTag: "prime_root_irrational" },
      { text: "Sometimes rational", type: "concept_error", logicTag: "overgeneralisation" },
      { text: "Always a natural number", type: "concept_error", logicTag: "incorrect" },
    ],
    solutionSteps: [
      "A prime p has no perfect-square factor.",
      "By the irrationality proof (similar to √2), √p cannot equal p/q.",
      "For every prime p, √p is irrational.",
    ],
    shortcut: "√(prime) is always irrational.",
    bloomLevel: "apply", conceptTested: "Irrationality of square roots of primes",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a07",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "The sum of a rational number and an irrational number is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Always rational",   type: "concept_error", logicTag: "wrong_closure" },
      { text: "Always irrational", type: "correct",       logicTag: "rational_plus_irrational" },
      { text: "Sometimes rational", type: "concept_error", logicTag: "overgeneralisation" },
      { text: "Always zero",        type: "concept_error", logicTag: "completely_wrong" },
    ],
    solutionSteps: [
      "Let r be rational, x be irrational. Suppose r + x = s (rational).",
      "Then x = s − r = difference of two rationals = rational — contradiction.",
      "So r + x must be irrational.",
    ],
    shortcut: "Rational + Irrational = Irrational (always).",
    bloomLevel: "analyse", conceptTested: "Sum of rational and irrational",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a08",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Which of the following represents an irrational number on the number line?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "√4",  type: "concept_error", logicTag: "perfect_square" },
      { text: "√5",  type: "correct",       logicTag: "irrational_plotted_geometrically" },
      { text: "√9",  type: "concept_error", logicTag: "perfect_square" },
      { text: "√1",  type: "concept_error", logicTag: "equals_one" },
    ],
    solutionSteps: [
      "√4 = 2, √9 = 3, √1 = 1 — all rationals.",
      "√5 ≈ 2.236… — non-terminating, non-repeating → irrational.",
      "√5 is located on the number line using a right triangle with legs 2 and 1.",
    ],
    shortcut: "Use the Pythagorean theorem to plot irrational square roots geometrically.",
    bloomLevel: "apply", conceptTested: "Geometric representation of irrational numbers",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a09",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "In the proof that √2 is irrational, which assumption leads to a contradiction?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "√2 is a whole number",                    type: "concept_error", logicTag: "wrong_assumption" },
      { text: "√2 = p/q where p, q have no common factor", type: "correct",    logicTag: "contradiction_proof" },
      { text: "√2 × √2 = 2",                            type: "concept_error", logicTag: "not_an_assumption" },
      { text: "2 is a prime number",                     type: "concept_error", logicTag: "used_in_proof_not_assumption" },
    ],
    solutionSteps: [
      "Assume √2 = p/q where gcd(p, q) = 1 (in lowest terms).",
      "Then 2 = p²/q² → p² = 2q² → 2 | p² → 2 | p.",
      "Write p = 2m → 4m² = 2q² → q² = 2m² → 2 | q.",
      "So 2 | p and 2 | q, contradicting gcd(p,q)=1.",
      "Contradiction → √2 is irrational.",
    ],
    shortcut: "Contradiction proof: assume rational in lowest terms, show denominator and numerator both even.",
    bloomLevel: "evaluate", conceptTested: "Proof by contradiction for irrationality of √2",
  },
  {
    questionId: "ap_ssc9_ch1_irrational_a10",
    topicId: "ap_ssc_math9_ch1_irrational_numbers",
    topic: "Number Systems", subtopic: "Irrational Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Which pair both contains irrational numbers?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "√4 and √9",     type: "concept_error", logicTag: "both_perfect_squares" },
      { text: "√2 and 22/7",   type: "concept_error", logicTag: "22_7_is_rational" },
      { text: "√7 and π",      type: "correct",       logicTag: "both_irrational" },
      { text: "0 and √25",     type: "concept_error", logicTag: "both_rational" },
    ],
    solutionSteps: [
      "√4 = 2 (rational), √9 = 3 (rational) — neither is irrational.",
      "22/7 is a rational fraction, not π.",
      "√25 = 5 (rational).",
      "√7 ≈ 2.6457… and π ≈ 3.14159… — both are irrational.",
    ],
    shortcut: "22/7 is a common trap — it is rational; π is irrational.",
    bloomLevel: "analyse", conceptTested: "Identifying irrational numbers in pairs",
  },

  // ─────────────────────────────────────────────────────────
  // TOPIC 2: ap_ssc_math9_ch1_decimal_expansions  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch1_decimal_a01",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "The decimal expansion of 1/3 is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "0.3",        type: "concept_error", logicTag: "terminating_wrong" },
      { text: "0.33",       type: "concept_error", logicTag: "partial_expansion" },
      { text: "0.3̄ (0.333…)", type: "correct",   logicTag: "non_terminating_repeating" },
      { text: "0.34",       type: "concept_error", logicTag: "rounding_error" },
    ],
    solutionSteps: [
      "1 ÷ 3 = 0.3333… — the digit 3 repeats endlessly.",
      "Notation: 0.3̄ means the 3 repeats forever.",
      "This is non-terminating repeating → rational.",
    ],
    shortcut: "Fractions 1/3, 1/6, 1/7, 1/9 give repeating decimals.",
    bloomLevel: "remember", conceptTested: "Decimal expansion of 1/3",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a02",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Which decimal is terminating?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "1/3",  type: "concept_error", logicTag: "repeating" },
      { text: "1/7",  type: "concept_error", logicTag: "repeating_block_6" },
      { text: "3/8",  type: "correct",       logicTag: "denominator_2a_5b" },
      { text: "2/11", type: "concept_error", logicTag: "repeating_block_2" },
    ],
    solutionSteps: [
      "A fraction p/q (lowest terms) terminates ↔ q has only factors 2 and/or 5.",
      "8 = 2³ → only factor 2 → 3/8 terminates.",
      "3/8 = 0.375 ✓",
    ],
    shortcut: "Denominator = 2ᵃ × 5ᵇ ⟹ terminating decimal.",
    bloomLevel: "apply", conceptTested: "Condition for terminating decimal",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a03",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "A non-terminating repeating decimal represents a:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "Irrational number",        type: "concept_error", logicTag: "definition_mix" },
      { text: "Rational number",          type: "correct",       logicTag: "repeating_implies_rational" },
      { text: "Natural number",           type: "concept_error", logicTag: "subset_confusion" },
      { text: "Cannot be determined",     type: "concept_error", logicTag: "unsure" },
    ],
    solutionSteps: [
      "Non-terminating NON-repeating → irrational.",
      "Non-terminating REPEATING → rational (can convert to fraction).",
      "E.g. 0.3̄ = 1/3.",
    ],
    shortcut: "Key distinction: repeating (rational) vs. non-repeating (irrational).",
    bloomLevel: "remember", conceptTested: "Classification by decimal type",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a04",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "0.ī (0.111…) as a fraction is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "1/10",  type: "concept_error", logicTag: "place_value_error" },
      { text: "1/9",   type: "correct",       logicTag: "geometric_series" },
      { text: "1/11",  type: "concept_error", logicTag: "off_by_one" },
      { text: "1/3",   type: "concept_error", logicTag: "similar_pattern_wrong" },
    ],
    solutionSteps: [
      "Let x = 0.1111…",
      "10x = 1.1111…",
      "10x − x = 1 → 9x = 1 → x = 1/9.",
    ],
    shortcut: "0.n̄ = n/9 for any single digit n.",
    bloomLevel: "apply", conceptTested: "Converting repeating decimal to fraction",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a05",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "The decimal expansion of √2 is:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "1.414 (terminating)",          type: "concept_error", logicTag: "approximation_mistaken" },
      { text: "1.414141… (repeating)",        type: "concept_error", logicTag: "wrong_type" },
      { text: "1.41421356… (non-terminating, non-repeating)", type: "correct", logicTag: "irrational_decimal" },
      { text: "1.5 (terminating)",            type: "concept_error", logicTag: "wrong_value" },
    ],
    solutionSteps: [
      "√2 is irrational → its decimal expansion is non-terminating and non-repeating.",
      "√2 = 1.41421356237…",
    ],
    shortcut: "Irrational ↔ non-terminating, non-repeating decimal.",
    bloomLevel: "understand", conceptTested: "Decimal nature of irrational numbers",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a06",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Which fraction has a terminating decimal expansion?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "7/12",  type: "concept_error", logicTag: "has_factor_3" },
      { text: "5/6",   type: "concept_error", logicTag: "has_factor_3" },
      { text: "9/40",  type: "correct",       logicTag: "40=2cubed_times_5" },
      { text: "4/15",  type: "concept_error", logicTag: "has_factor_3" },
    ],
    solutionSteps: [
      "12 = 4×3 (has factor 3) → 7/12 repeating.",
      "6 = 2×3 (has factor 3) → 5/6 repeating.",
      "15 = 3×5 (has factor 3) → 4/15 repeating.",
      "40 = 2³ × 5 (only 2 and 5) → 9/40 terminates = 0.225.",
    ],
    shortcut: "Factor the denominator — if primes other than 2, 5 appear → repeating.",
    bloomLevel: "apply", conceptTested: "Identifying terminating fractions",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a07",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Convert 0.36̄ (0.3666…) to a fraction.",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "11/30", type: "correct",       logicTag: "multiply_by_10_and_100" },
      { text: "36/99", type: "concept_error", logicTag: "wrong_multiplier" },
      { text: "3/10",  type: "concept_error", logicTag: "ignored_repeating" },
      { text: "4/11",  type: "concept_error", logicTag: "wrong_method" },
    ],
    solutionSteps: [
      "x = 0.3666…",
      "10x = 3.666…",
      "100x = 36.66…",
      "100x − 10x = 36.66… − 3.66… = 33",
      "90x = 33 → x = 33/90 = 11/30.",
    ],
    shortcut: "Multiply by 10^(non-repeating digits) and 10^(total digits before period), then subtract.",
    bloomLevel: "apply", conceptTested: "Converting mixed repeating decimal to fraction",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a08",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "How many rational numbers exist between 1/4 and 1/2?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "Zero",         type: "concept_error", logicTag: "density_ignored" },
      { text: "One",          type: "concept_error", logicTag: "density_ignored" },
      { text: "Finitely many", type: "concept_error", logicTag: "density_wrong" },
      { text: "Infinitely many", type: "correct",    logicTag: "density_of_rationals" },
    ],
    solutionSteps: [
      "1/4 = 0.25, 1/2 = 0.50.",
      "Rationals are dense: between any two distinct rationals lie infinitely many rationals.",
      "E.g. 1/3, 3/8, 2/5, 5/12, … are all between 1/4 and 1/2.",
    ],
    shortcut: "Density: infinitely many rationals between any two rationals.",
    bloomLevel: "understand", conceptTested: "Density of rational numbers",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a09",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Which of the following decimal expansions is non-terminating non-repeating?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "0.1212̄ (0.121212…)",        type: "concept_error", logicTag: "repeating_block_12" },
      { text: "0.1010010001…",               type: "correct",       logicTag: "pattern_grows_no_repeat" },
      { text: "0.125 (terminating)",          type: "concept_error", logicTag: "terminating" },
      { text: "0.285714̄ (0.285714285714…)", type: "concept_error", logicTag: "1_div_7_repeating" },
    ],
    solutionSteps: [
      "0.121212… repeats the block '12' → rational.",
      "0.285714285714… repeats '285714' (= 2/7) → rational.",
      "0.125 terminates → rational.",
      "0.1010010001… adds one extra 0 each time — the pattern keeps growing, no fixed repeating block → non-terminating non-repeating → irrational.",
    ],
    shortcut: "Constructed decimals that grow without repeating are always irrational.",
    bloomLevel: "analyse", conceptTested: "Identifying non-terminating non-repeating decimals",
  },
  {
    questionId: "ap_ssc9_ch1_decimal_a10",
    topicId: "ap_ssc_math9_ch1_decimal_expansions",
    topic: "Number Systems", subtopic: "Decimal Expansions",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "If 1/7 = 0.142857̄, what is 3/7?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "0.428571̄",  type: "correct",       logicTag: "cyclic_permutation" },
      { text: "0.333333̄",  type: "concept_error", logicTag: "confused_with_1/3" },
      { text: "0.4285̄",    type: "concept_error", logicTag: "wrong_period" },
      { text: "0.285714̄",  type: "concept_error", logicTag: "2/7_not_3/7" },
    ],
    solutionSteps: [
      "3/7 = 3 × (1/7) = 3 × 0.142857142857…",
      "= 0.428571428571… = 0.428571̄",
      "This is a cyclic permutation of the digits 142857.",
    ],
    shortcut: "Multiples of 1/7 cycle through the same 6 digits (142857) starting at different places.",
    bloomLevel: "apply", conceptTested: "Cyclic nature of 1/7 decimal expansion",
  },

  // ─────────────────────────────────────────────────────────
  // TOPIC 3: ap_ssc_math9_ch1_operations_on_reals  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch1_opsreals_a01",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "√3 + √3 is equal to:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "√6",   type: "concept_error", logicTag: "wrong_addition_rule" },
      { text: "2√3",  type: "correct",       logicTag: "like_surd_addition" },
      { text: "3",    type: "concept_error", logicTag: "product_rule_used" },
      { text: "√9",   type: "concept_error", logicTag: "wrong_simplification" },
    ],
    solutionSteps: [
      "√3 + √3 = 1·√3 + 1·√3 = 2√3 (same as 3+3 = 2×3 in ordinary arithmetic).",
      "2√3 ≈ 3.464.",
    ],
    shortcut: "Like surds add/subtract by combining coefficients: a√n ± b√n = (a±b)√n.",
    bloomLevel: "apply", conceptTested: "Addition of like surds",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a02",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "√6 × √6 is equal to:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "36",  type: "concept_error", logicTag: "6_times_6_error" },
      { text: "√12", type: "concept_error", logicTag: "wrong_product" },
      { text: "6",   type: "correct",       logicTag: "surd_self_product" },
      { text: "12",  type: "concept_error", logicTag: "double_counted" },
    ],
    solutionSteps: [
      "√6 × √6 = (√6)² = 6.",
      "In general: √a × √a = a for a ≥ 0.",
    ],
    shortcut: "√a × √a = a.",
    bloomLevel: "remember", conceptTested: "Product of a surd with itself",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a03",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Rationalize the denominator of 1/√2.",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "√2",        type: "concept_error", logicTag: "forgot_denominator" },
      { text: "√2 / 2",    type: "correct",       logicTag: "multiply_by_sqrt2" },
      { text: "1 / 2",     type: "concept_error", logicTag: "wrong_simplification" },
      { text: "2 / √2",    type: "concept_error", logicTag: "inverted" },
    ],
    solutionSteps: [
      "Multiply numerator and denominator by √2:",
      "1/√2 × √2/√2 = √2/2.",
    ],
    shortcut: "To rationalize 1/√a, multiply by √a/√a → answer: √a/a.",
    bloomLevel: "apply", conceptTested: "Rationalizing the denominator",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a04",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "√12 simplified is:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "3√2",  type: "concept_error", logicTag: "wrong_factorisation" },
      { text: "2√3",  type: "correct",       logicTag: "12=4x3_sqrt4=2" },
      { text: "4√3",  type: "concept_error", logicTag: "extra_factor" },
      { text: "6",    type: "concept_error", logicTag: "completely_wrong" },
    ],
    solutionSteps: [
      "12 = 4 × 3 = 2² × 3.",
      "√12 = √(4×3) = √4 × √3 = 2√3.",
    ],
    shortcut: "Factor out the largest perfect square: √12 = √(4·3) = 2√3.",
    bloomLevel: "apply", conceptTested: "Simplifying surds",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a05",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Rationalize: 1/(3 + √2).",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "(3 − √2)/7",    type: "correct",       logicTag: "conjugate_3squared_minus_2" },
      { text: "(3 + √2)/7",    type: "concept_error", logicTag: "forgot_conjugate_sign" },
      { text: "(3 − √2)/11",   type: "concept_error", logicTag: "wrong_denominator" },
      { text: "1/(3 − √2)",    type: "concept_error", logicTag: "only_flipped_sign" },
    ],
    solutionSteps: [
      "Conjugate of (3+√2) is (3−√2).",
      "Multiply: 1/(3+√2) × (3−√2)/(3−√2) = (3−√2)/(9−2) = (3−√2)/7.",
    ],
    shortcut: "Use conjugate (a+√b)(a−√b) = a²−b to clear surd from denominator.",
    bloomLevel: "apply", conceptTested: "Rationalizing using conjugates",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a06",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "√2 × √8 equals:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "√10",  type: "concept_error", logicTag: "added_instead" },
      { text: "√16",  type: "concept_error", logicTag: "stopped_before_simplifying" },
      { text: "4",    type: "correct",       logicTag: "sqrt16=4" },
      { text: "2√4",  type: "concept_error", logicTag: "partially_simplified" },
    ],
    solutionSteps: [
      "√2 × √8 = √(2×8) = √16 = 4.",
      "Product rule: √a × √b = √(ab) for a, b ≥ 0.",
    ],
    shortcut: "√a × √b = √(ab); then simplify the result.",
    bloomLevel: "apply", conceptTested: "Product rule for square roots",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a07",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Which of the following is equal to (√5 + √3)(√5 − √3)?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "8",       type: "concept_error", logicTag: "added_instead_of_subtracted" },
      { text: "2",       type: "correct",       logicTag: "difference_of_squares" },
      { text: "√2",      type: "concept_error", logicTag: "wrong_simplification" },
      { text: "2√15",    type: "concept_error", logicTag: "wrong_expansion" },
    ],
    solutionSteps: [
      "(√5 + √3)(√5 − √3) = (√5)² − (√3)² = 5 − 3 = 2.",
      "Identity: (a+b)(a−b) = a² − b².",
    ],
    shortcut: "(√a + √b)(√a − √b) = a − b.",
    bloomLevel: "apply", conceptTested: "Difference of squares with surds",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a08",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "2√3 + 3√3 − √3 equals:",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "4√3",   type: "correct",       logicTag: "like_surd_combine" },
      { text: "6√3",   type: "concept_error", logicTag: "added_but_didnt_subtract" },
      { text: "4√9",   type: "concept_error", logicTag: "radicand_wrong" },
      { text: "√12",   type: "concept_error", logicTag: "mixed_operation" },
    ],
    solutionSteps: [
      "All terms have √3 as the surd — combine coefficients.",
      "2 + 3 − 1 = 4.",
      "Answer: 4√3.",
    ],
    shortcut: "Treat √3 like a variable: 2x + 3x − x = 4x, so 4√3.",
    bloomLevel: "apply", conceptTested: "Adding and subtracting like surds",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a09",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Simplify: (3 + √7)(3 − √7).",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "16",   type: "concept_error", logicTag: "9_plus_7_error" },
      { text: "9",    type: "concept_error", logicTag: "ignored_surd" },
      { text: "2",    type: "correct",       logicTag: "9_minus_7=2" },
      { text: "6√7",  type: "concept_error", logicTag: "FOIL_error" },
    ],
    solutionSteps: [
      "(3+√7)(3−√7) = 3² − (√7)² = 9 − 7 = 2.",
    ],
    shortcut: "(a+√b)(a−√b) = a² − b.",
    bloomLevel: "apply", conceptTested: "Applying difference of squares identity",
  },
  {
    questionId: "ap_ssc9_ch1_opsreals_a10",
    topicId: "ap_ssc_math9_ch1_operations_on_reals",
    topic: "Number Systems", subtopic: "Operations on Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Rationalize and simplify: 6/(2√3 − √6).",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "√6(2√3 + √6)/6",      type: "concept_error", logicTag: "wrong_denominator" },
      { text: "2√3 + √6",            type: "correct",       logicTag: "denominator_simplifies_to_6" },
      { text: "6/(2√3 + √6)",        type: "concept_error", logicTag: "forgot_to_simplify" },
      { text: "2(2√3 + √6)",         type: "concept_error", logicTag: "wrong_final_fraction" },
    ],
    solutionSteps: [
      "Multiply by conjugate (2√3 + √6)/(2√3 + √6).",
      "Denominator: (2√3)² − (√6)² = 12 − 6 = 6.",
      "Numerator: 6(2√3 + √6) = 12√3 + 6√6.",
      "Result: (12√3 + 6√6)/6 = 2√3 + √6.",
    ],
    shortcut: "Always compute the denominator product first using (a−b)(a+b) = a²−b².",
    bloomLevel: "analyse", conceptTested: "Rationalizing complex surd denominators",
  },

  // ─────────────────────────────────────────────────────────
  // TOPIC 4: ap_ssc_math9_ch1_laws_of_exponents  (10 MCQs)
  // ─────────────────────────────────────────────────────────
  {
    questionId: "ap_ssc9_ch1_exponents_a01",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "What is 2³ × 2⁴?",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "2⁷",   type: "correct",       logicTag: "add_exponents_same_base" },
      { text: "2¹²",  type: "concept_error", logicTag: "multiplied_exponents" },
      { text: "4⁷",   type: "concept_error", logicTag: "base_added" },
      { text: "2¹",   type: "concept_error", logicTag: "subtracted_exponents" },
    ],
    solutionSteps: [
      "Same base: aᵐ × aⁿ = aᵐ⁺ⁿ.",
      "2³ × 2⁴ = 2^(3+4) = 2⁷ = 128.",
    ],
    shortcut: "Multiply powers → add exponents (same base).",
    bloomLevel: "remember", conceptTested: "Product rule of exponents",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a02",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "5⁶ ÷ 5² equals:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "5⁸",   type: "concept_error", logicTag: "added_instead_of_subtracted" },
      { text: "5³",   type: "concept_error", logicTag: "off_by_one" },
      { text: "5⁴",   type: "correct",       logicTag: "subtract_exponents" },
      { text: "1⁴",   type: "concept_error", logicTag: "base_divided" },
    ],
    solutionSteps: [
      "aᵐ ÷ aⁿ = aᵐ⁻ⁿ (same base, m > n).",
      "5⁶ ÷ 5² = 5^(6−2) = 5⁴ = 625.",
    ],
    shortcut: "Divide powers → subtract exponents (same base).",
    bloomLevel: "remember", conceptTested: "Quotient rule of exponents",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a03",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "(3²)³ equals:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "3⁵",  type: "concept_error", logicTag: "added_exponents" },
      { text: "3⁶",  type: "correct",       logicTag: "power_of_power" },
      { text: "9³",  type: "concept_error", logicTag: "partially_simplified" },
      { text: "3⁹",  type: "concept_error", logicTag: "3_cubed" },
    ],
    solutionSteps: [
      "(aᵐ)ⁿ = aᵐⁿ.",
      "(3²)³ = 3^(2×3) = 3⁶ = 729.",
    ],
    shortcut: "Power of a power → multiply exponents.",
    bloomLevel: "remember", conceptTested: "Power of a power rule",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a04",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "8^(1/3) equals:",
    questionType: "mcq", difficulty: "easy", difficultyScore: 0.2, marks: 1, isAIGenerated: true,
    options: [
      { text: "8",    type: "concept_error", logicTag: "ignored_exponent" },
      { text: "2",    type: "correct",       logicTag: "cube_root_of_8" },
      { text: "4",    type: "concept_error", logicTag: "square_root_of_8" },
      { text: "24",   type: "concept_error", logicTag: "multiplied" },
    ],
    solutionSteps: [
      "a^(1/n) = nth root of a.",
      "8^(1/3) = ∛8 = 2, because 2³ = 8.",
    ],
    shortcut: "a^(1/n) = ⁿ√a.",
    bloomLevel: "apply", conceptTested: "Fractional exponents as roots",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a05",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Simplify: (2³ × 3²) / (2² × 3).",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "6",   type: "correct",       logicTag: "2power1_times_3power1" },
      { text: "12",  type: "concept_error", logicTag: "off_by_2" },
      { text: "18",  type: "concept_error", logicTag: "wrong_subtraction" },
      { text: "3",   type: "concept_error", logicTag: "missed_factor" },
    ],
    solutionSteps: [
      "Separate bases: (2³/2²) × (3²/3¹) = 2¹ × 3¹ = 2 × 3 = 6.",
    ],
    shortcut: "Separate each base and apply quotient rule independently.",
    bloomLevel: "apply", conceptTested: "Simplifying expressions with multiple bases",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a06",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "What is the value of (27)^(2/3)?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "3",   type: "concept_error", logicTag: "only_applied_1/3" },
      { text: "9",   type: "correct",       logicTag: "cube_root_then_square" },
      { text: "18",  type: "concept_error", logicTag: "wrong_computation" },
      { text: "6",   type: "concept_error", logicTag: "2_times_3" },
    ],
    solutionSteps: [
      "a^(m/n) = (ⁿ√a)ᵐ.",
      "27^(2/3) = (∛27)² = 3² = 9.",
    ],
    shortcut: "a^(m/n): first take nth root, then raise to power m.",
    bloomLevel: "apply", conceptTested: "Evaluating a^(m/n)",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a07",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "If 2ˣ = 32, what is x?",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "4",   type: "concept_error", logicTag: "2_to_4=16" },
      { text: "5",   type: "correct",       logicTag: "2_to_5=32" },
      { text: "6",   type: "concept_error", logicTag: "2_to_6=64" },
      { text: "16",  type: "concept_error", logicTag: "confused_base_and_exponent" },
    ],
    solutionSteps: [
      "32 = 2⁵.",
      "So 2ˣ = 2⁵ → x = 5.",
    ],
    shortcut: "Express both sides as powers of the same base, then equate exponents.",
    bloomLevel: "apply", conceptTested: "Solving exponential equations",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a08",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "Simplify: 3^(1/2) × 3^(1/2).",
    questionType: "mcq", difficulty: "medium", difficultyScore: 0.5, marks: 1, isAIGenerated: true,
    options: [
      { text: "9",      type: "concept_error", logicTag: "squared_base" },
      { text: "3",      type: "correct",       logicTag: "half_plus_half_equals_1" },
      { text: "3^(1/4)", type: "concept_error", logicTag: "multiplied_exponents" },
      { text: "√3",     type: "concept_error", logicTag: "left_unchanged" },
    ],
    solutionSteps: [
      "3^(1/2) × 3^(1/2) = 3^(1/2 + 1/2) = 3¹ = 3.",
    ],
    shortcut: "√a × √a = a (equivalent to aᵐ × aⁿ = aᵐ⁺ⁿ with m=n=1/2).",
    bloomLevel: "apply", conceptTested: "Fractional exponent product rule",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a09",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "What is (16)^(−1/4)?",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "2",     type: "concept_error", logicTag: "positive_exponent" },
      { text: "1/2",   type: "correct",       logicTag: "negative_fractional_exponent" },
      { text: "−2",    type: "concept_error", logicTag: "negative_base_confusion" },
      { text: "1/4",   type: "concept_error", logicTag: "exponent_itself" },
    ],
    solutionSteps: [
      "a^(−m) = 1/aᵐ.",
      "16^(−1/4) = 1/16^(1/4) = 1/(⁴√16) = 1/2.",
    ],
    shortcut: "Negative exponent → reciprocal. Fractional exponent → root.",
    bloomLevel: "apply", conceptTested: "Negative fractional exponents",
  },
  {
    questionId: "ap_ssc9_ch1_exponents_a10",
    topicId: "ap_ssc_math9_ch1_laws_of_exponents",
    topic: "Number Systems", subtopic: "Laws of Exponents for Real Numbers",
    subject: "Mathematics", grade: GRADE, examBoard: BOARD, chapterNumber: 1,
    questionText: "If 5^(2x−1) = 125, the value of x is:",
    questionType: "mcq", difficulty: "hard", difficultyScore: 0.8, marks: 2, isAIGenerated: true,
    options: [
      { text: "1",   type: "concept_error", logicTag: "wrong_equation" },
      { text: "2",   type: "correct",       logicTag: "5_cubed=125_then_solve" },
      { text: "3",   type: "concept_error", logicTag: "solved_for_5x_not_2x_minus_1" },
      { text: "4",   type: "concept_error", logicTag: "off_by_one" },
    ],
    solutionSteps: [
      "125 = 5³.",
      "So 5^(2x−1) = 5³ → 2x − 1 = 3 → 2x = 4 → x = 2.",
    ],
    shortcut: "Convert RHS to same base, equate exponents, solve linearly.",
    bloomLevel: "analyse", conceptTested: "Solving exponential equations with linear exponents",
  },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  let upserted = 0, skipped = 0;
  for (const q of questions) {
    try {
      await Question.findOneAndUpdate(
        { questionId: q.questionId },
        { $set: q },
        { upsert: true, new: true }
      );
      console.log(`  ✓ ${q.questionId}`);
      upserted++;
    } catch (err) {
      if (err.code === 11000) { console.log(`  — skip ${q.questionId}`); skipped++; }
      else throw err;
    }
  }
  console.log(`\nDone. Upserted: ${upserted}  Skipped: ${skipped}`);
  await mongoose.disconnect();
  process.exit(0);
}
run().catch(err => { console.error(err); process.exit(1); });
