import mongoose from "mongoose";
import dotenv from "dotenv";
import { NcertTopicContent } from "../models/ncertTopicContentModel.js";
dotenv.config();

const topics = [
  // ── Chapter 1: Where to Look From ──────────────────────────────────────
  {
    topicId: "math3_ch1_top_view", chapterNumber: 1, sectionNumber: "1.1",
    title: "Top View of Objects", subject: "Mathematics",
    intuition: "Looking straight down on an object gives a 'top view' — like a bird looking at the ground.",
    process_explanation: "Stand directly above the object. What you see is the top view. A glass becomes a circle; a book becomes a rectangle.",
    worked_example: "A cup viewed from above looks like a circle. A matchbox viewed from above looks like a rectangle.",
    common_misconceptions: "Students draw the side they're most familiar with. Top view is what you'd see ONLY from directly above.",
    shortcuts_and_tricks: "Hold the object below your eye and look straight down. That's the top view.",
    key_takeaway: "Top view shows the outline of an object as seen from directly above it.",
  },
  {
    topicId: "math3_ch1_front_view", chapterNumber: 1, sectionNumber: "1.2",
    title: "Front View of Objects", subject: "Mathematics",
    intuition: "When you face an object head-on, what you see is the front view.",
    process_explanation: "Stand in front of the object at eye level. The shape you see is the front view.",
    worked_example: "A tea cup from the front looks like a U-shape (with handle). A house from the front shows a square wall and triangle roof.",
    common_misconceptions: "Students confuse the front with the top. Front = looking straight at it. Top = looking down on it.",
    shortcuts_and_tricks: "Imagine taking a photo standing in front — that photo is the front view.",
    key_takeaway: "Front view shows the object as you face it directly.",
  },
  {
    topicId: "math3_ch1_side_view", chapterNumber: 1, sectionNumber: "1.3",
    title: "Side View of Objects", subject: "Mathematics",
    intuition: "Moving 90° to the right or left of an object shows its side view — its profile.",
    process_explanation: "Move to the left or right of the object, then look at it. What you see is the side view.",
    worked_example: "A car from the side shows wheels, doors, and a body outline. A cylinder from the side looks like a rectangle.",
    common_misconceptions: "Left and right side views are often mirror images of each other — not always identical.",
    shortcuts_and_tricks: "Top, front, and side views together describe a 3D shape completely.",
    key_takeaway: "The side view shows the object's profile from the left or right.",
  },
  {
    topicId: "math3_ch1_mirror_images", chapterNumber: 1, sectionNumber: "1.4",
    title: "Mirror Images", subject: "Mathematics",
    intuition: "A mirror reflects an object so left and right swap. The size and shape stay the same.",
    process_explanation: "Stand in front of a mirror. Your right hand appears on the left side of the image. The mirror flips horizontally.",
    worked_example: "If you write 'd' on paper and look at it in a mirror, you see 'b'. Letters with vertical symmetry (A, H, M, T) look the same in a mirror.",
    common_misconceptions: "Students think mirrors flip up-and-down too — they only flip left-right.",
    shortcuts_and_tricks: "Symmetric letters: A, H, I, M, O, T, U, V, W, X, Y all look the same in a vertical mirror.",
    key_takeaway: "A mirror image flips left and right but keeps size and orientation of the shape.",
  },

  // ── Chapter 2: Fun with Numbers ────────────────────────────────────────
  {
    topicId: "math3_ch2_three_digit_numbers", chapterNumber: 2, sectionNumber: "2.1",
    title: "Three-Digit Numbers", subject: "Mathematics",
    intuition: "Numbers from 100 to 999 are 3-digit numbers. They are bigger than 2-digit numbers because they have a hundreds place.",
    process_explanation: "A 3-digit number has hundreds, tens, and ones. 100 = smallest 3-digit. 999 = largest 3-digit. After 999 comes 1000.",
    worked_example: "256 is a 3-digit number. 99 is 2-digit (not 3-digit). 1000 has 4 digits — beyond 3-digit range.",
    common_misconceptions: "Students think 099 is a 3-digit number. Leading zeros don't count — 099 = 99 (2-digit).",
    shortcuts_and_tricks: "Range of 3-digit numbers: 100 to 999 (900 numbers in total).",
    key_takeaway: "3-digit numbers range from 100 to 999 and have hundreds, tens, and ones places.",
  },
  {
    topicId: "math3_ch2_place_value", chapterNumber: 2, sectionNumber: "2.2",
    title: "Place Value (Hundreds, Tens, Ones)", subject: "Mathematics",
    intuition: "Each digit's position decides its value. The same digit means different things in different places.",
    process_explanation: "In 457: 4 is in the hundreds place (worth 400), 5 in the tens (worth 50), 7 in the ones (worth 7).",
    worked_example: "Number 836 → 8 hundreds + 3 tens + 6 ones = 800 + 30 + 6 = 836.",
    common_misconceptions: "Students see '4' in 457 and think it's just 4. Position matters: in 457, the 4 actually means 400.",
    shortcuts_and_tricks: "Place value chart: H | T | O. Put each digit in its column to see the value clearly.",
    key_takeaway: "A digit's value depends on its place: hundreds, tens, or ones.",
  },
  {
    topicId: "math3_ch2_comparing_numbers", chapterNumber: 2, sectionNumber: "2.3",
    title: "Comparing 3-Digit Numbers", subject: "Mathematics",
    intuition: "To compare two numbers, look at the leftmost digit first. The one with more hundreds is bigger.",
    process_explanation: "Compare hundreds first. If equal, compare tens. If still equal, compare ones.",
    worked_example: "Compare 457 and 482: hundreds equal (4=4) → compare tens (5<8) → 482 > 457. Compare 600 and 599: hundreds (6>5) → 600 > 599.",
    common_misconceptions: "Students compare from right to left. Always start with the LEFTMOST (largest place) digit.",
    shortcuts_and_tricks: "Same digit count? Read like words — leftmost difference wins. Different digit counts? More digits = bigger number.",
    key_takeaway: "Compare 3-digit numbers from the leftmost digit (hundreds) onward.",
  },
  {
    topicId: "math3_ch2_expanded_form", chapterNumber: 2, sectionNumber: "2.4",
    title: "Expanded Form of Numbers", subject: "Mathematics",
    intuition: "Expanded form breaks a number into the value of each digit, showing exactly what each digit represents.",
    process_explanation: "Multiply each digit by its place value, then write them as a sum: hundreds + tens + ones.",
    worked_example: "457 = 400 + 50 + 7. 836 = 800 + 30 + 6. 503 = 500 + 0 + 3 = 500 + 3.",
    common_misconceptions: "Students write 457 as 4 + 5 + 7. Wrong — each digit must be multiplied by its place value first.",
    shortcuts_and_tricks: "Place a zero for each empty place: 500 + 3 (skip the tens) is fine because the tens digit is 0.",
    key_takeaway: "Expanded form shows the value of each digit as a sum: hundreds + tens + ones.",
  },

  // ── Chapter 3: Give and Take ───────────────────────────────────────────
  {
    topicId: "math3_ch3_addition_3digit", chapterNumber: 3, sectionNumber: "3.1",
    title: "Addition of 3-Digit Numbers", subject: "Mathematics",
    intuition: "Adding 3-digit numbers works the same way as 2-digit: line up the places, add column by column starting from ones.",
    process_explanation: "Write numbers one below the other so that ones align with ones, tens with tens, hundreds with hundreds. Add right to left.",
    worked_example: "234 + 153: ones 4+3=7. Tens 3+5=8. Hundreds 2+1=3. Sum = 387.",
    common_misconceptions: "Students align numbers from the left instead of the right. Always align from the RIGHT (ones place).",
    shortcuts_and_tricks: "Use a place value chart or graph paper to keep columns straight.",
    key_takeaway: "Add 3-digit numbers column by column, starting from the ones place.",
  },
  {
    topicId: "math3_ch3_subtraction_3digit", chapterNumber: 3, sectionNumber: "3.2",
    title: "Subtraction of 3-Digit Numbers", subject: "Mathematics",
    intuition: "Subtraction takes away. Line up the numbers and subtract column by column, ones first.",
    process_explanation: "Write the bigger number on top. Subtract right to left. Ones, then tens, then hundreds.",
    worked_example: "768 − 234: ones 8−4=4. Tens 6−3=3. Hundreds 7−2=5. Difference = 534.",
    common_misconceptions: "Subtracting the smaller from the larger digit even when it's on top. Always do top minus bottom; borrow if needed.",
    shortcuts_and_tricks: "Check by adding: answer + smaller number = bigger number.",
    key_takeaway: "Subtract 3-digit numbers column by column, top minus bottom, starting from ones.",
  },
  {
    topicId: "math3_ch3_carrying", chapterNumber: 3, sectionNumber: "3.3",
    title: "Carrying in Addition", subject: "Mathematics",
    intuition: "When a column's sum is 10 or more, the 'extra' tens carry over to the next column on the left.",
    process_explanation: "If ones add to 10 or more, write the ones digit and carry the tens digit to the tens column. Repeat for each column.",
    worked_example: "248 + 367: ones 8+7=15 → write 5, carry 1. Tens 4+6+1=11 → write 1, carry 1. Hundreds 2+3+1=6. Sum = 615.",
    common_misconceptions: "Forgetting to add the carried 1 to the next column.",
    shortcuts_and_tricks: "Always write the carry above the next column so you don't forget.",
    key_takeaway: "When a column sums to 10 or more, write the ones and carry the tens to the next column.",
  },
  {
    topicId: "math3_ch3_borrowing", chapterNumber: 3, sectionNumber: "3.4",
    title: "Borrowing in Subtraction", subject: "Mathematics",
    intuition: "If the top digit is smaller than the bottom, borrow 10 from the next column on the left.",
    process_explanation: "Borrow 1 from the tens column (it becomes 10 ones added to the ones place). The tens column loses 1.",
    worked_example: "523 − 168: ones 3<8 → borrow, 13−8=5. Tens (now 1)<6 → borrow, 11−6=5. Hundreds (now 4)−1=3. Answer: 355.",
    common_misconceptions: "Forgetting to reduce the tens column after borrowing.",
    shortcuts_and_tricks: "Cross out the borrowed-from digit and write the new (reduced) value above it.",
    key_takeaway: "Borrowing converts 1 ten into 10 ones so you can subtract.",
  },

  // ── Chapter 4: Long and Short ──────────────────────────────────────────
  {
    topicId: "math3_ch4_units_cm_m", chapterNumber: 4, sectionNumber: "4.1",
    title: "Units of Length (cm and m)", subject: "Mathematics",
    intuition: "Centimetres (cm) measure small things; metres (m) measure bigger things. 1 m = 100 cm.",
    process_explanation: "Use cm for pencils, books, and small objects. Use m for room dimensions, height of people, and longer distances.",
    worked_example: "A pencil = 15 cm. A child's height = 120 cm or 1 m 20 cm. A football field = 100 m.",
    common_misconceptions: "Students mix up cm and m. 1 m = 100 cm, NOT 10 cm.",
    shortcuts_and_tricks: "Convert m to cm: multiply by 100. Convert cm to m: divide by 100.",
    key_takeaway: "Use cm for small things and m for large things. 1 m = 100 cm.",
  },
  {
    topicId: "math3_ch4_measuring_length", chapterNumber: 4, sectionNumber: "4.2",
    title: "Measuring with a Ruler", subject: "Mathematics",
    intuition: "A ruler has marks every centimetre. Place the zero at one end of the object and read the number at the other end.",
    process_explanation: "Align the 0 of the ruler at the start of the object. Read the cm number where the object ends.",
    worked_example: "A pencil starts at 0 and ends at 14 on the ruler → length = 14 cm.",
    common_misconceptions: "Starting from 1 instead of 0. Always align 0 with the start of the object.",
    shortcuts_and_tricks: "If you can't start from 0, subtract: end reading − start reading = length.",
    key_takeaway: "To measure length, align 0 with one end and read the value at the other end.",
  },
  {
    topicId: "math3_ch4_comparing_lengths", chapterNumber: 4, sectionNumber: "4.3",
    title: "Comparing Lengths", subject: "Mathematics",
    intuition: "Bigger number = longer object (when both are in the same unit). Always convert to the same unit first.",
    process_explanation: "Measure both objects in the same unit (cm or m), then compare the numbers.",
    worked_example: "Pencil A = 15 cm, Pencil B = 12 cm → A is longer by 3 cm. Compare 1 m and 80 cm → convert 1 m to 100 cm → 100 > 80.",
    common_misconceptions: "Comparing 1 m to 80 cm without converting; thinking 80 > 1 because 80 > 1.",
    shortcuts_and_tricks: "Always convert to the smaller unit (cm) to avoid confusion.",
    key_takeaway: "To compare lengths, measure in the same unit and compare the numbers.",
  },
  {
    topicId: "math3_ch4_estimating", chapterNumber: 4, sectionNumber: "4.4",
    title: "Estimating Length", subject: "Mathematics",
    intuition: "Estimation is a smart guess based on what you know. It's faster than measuring exactly.",
    process_explanation: "Use familiar objects as a reference: thumb ≈ 1 cm, foot ≈ 25 cm, step ≈ 50 cm. Compare to estimate.",
    worked_example: "Estimate the length of a desk: 4 footsteps ≈ 4 × 50 = 200 cm = 2 m.",
    common_misconceptions: "Students think estimation is just guessing. It's a guess based on a known reference.",
    shortcuts_and_tricks: "Memorise common reference lengths: finger nail ≈ 1 cm, hand-span ≈ 20 cm, arm-span ≈ 1 m.",
    key_takeaway: "Estimate length using known references like your hand, foot, or steps.",
  },

  // ── Chapter 5: Shapes and Designs ──────────────────────────────────────
  {
    topicId: "math3_ch5_2d_shapes", chapterNumber: 5, sectionNumber: "5.1",
    title: "2D Shapes", subject: "Mathematics",
    intuition: "2D shapes are flat — they have length and width but no depth. Examples: square, rectangle, triangle, circle.",
    process_explanation: "Count sides and corners to identify a shape: triangle (3), quadrilateral (4), pentagon (5), hexagon (6), circle (0).",
    worked_example: "A square has 4 equal sides and 4 corners. A rectangle has 4 sides (opposite pairs equal). A circle has no sides or corners.",
    common_misconceptions: "Students think every 4-sided shape is a square. Squares have ALL sides equal; rectangles only have opposite pairs equal.",
    shortcuts_and_tricks: "Sides + corners are always the same number for any polygon (closed shape with straight sides).",
    key_takeaway: "2D shapes are flat. Identify them by counting sides and corners.",
  },
  {
    topicId: "math3_ch5_3d_shapes", chapterNumber: 5, sectionNumber: "5.2",
    title: "3D Shapes", subject: "Mathematics",
    intuition: "3D shapes are solid — they have length, width, AND height. Examples: cube, cuboid, sphere, cylinder, cone.",
    process_explanation: "3D shapes have faces (flat surfaces), edges (where faces meet), and vertices (corners).",
    worked_example: "Cube: 6 faces, 12 edges, 8 vertices. Sphere: 1 curved surface, 0 edges, 0 vertices.",
    common_misconceptions: "Confusing square (2D) with cube (3D), or circle (2D) with sphere (3D).",
    shortcuts_and_tricks: "2D = flat (paper). 3D = solid (object you can hold).",
    key_takeaway: "3D shapes have faces, edges, and vertices, and exist in space — they're not flat.",
  },
  {
    topicId: "math3_ch5_tiling", chapterNumber: 5, sectionNumber: "5.3",
    title: "Tiling and Tessellation", subject: "Mathematics",
    intuition: "Tiling covers a surface with shapes that fit together without gaps or overlaps — like floor tiles.",
    process_explanation: "Squares, rectangles, triangles, and hexagons all tile perfectly. Circles can't tile (gaps remain).",
    worked_example: "Floor tiles are usually squares or rectangles. Honeycomb cells tile with hexagons. Triangles tile if arranged correctly.",
    common_misconceptions: "Students think any shape can tile. Pentagons (regular) and circles cannot tile without gaps.",
    shortcuts_and_tricks: "Test: if you can repeat a shape across a surface without gaps, it tiles.",
    key_takeaway: "Tiling means covering a surface with shapes that fit together — no gaps, no overlaps.",
  },
  {
    topicId: "math3_ch5_symmetry", chapterNumber: 5, sectionNumber: "5.4",
    title: "Line of Symmetry", subject: "Mathematics",
    intuition: "A shape is symmetric if you can fold it along a line and both halves match exactly.",
    process_explanation: "Find the line where folding produces matching halves. Some shapes have 1 line, others have many.",
    worked_example: "Square: 4 lines of symmetry. Rectangle: 2. Circle: infinitely many. Letter 'A': 1 (vertical). Letter 'F': 0.",
    common_misconceptions: "Students think every shape has at least one line of symmetry. F, G, P, R, S have NONE.",
    shortcuts_and_tricks: "Try folding the shape mentally. If halves match, you found a line of symmetry.",
    key_takeaway: "A line of symmetry divides a shape so both halves are mirror images.",
  },

  // ── Chapter 6: Fun with Give and Take ──────────────────────────────────
  {
    topicId: "math3_ch6_word_problems_add", chapterNumber: 6, sectionNumber: "6.1",
    title: "Word Problems — Addition", subject: "Mathematics",
    intuition: "Word problems hide math in everyday situations. Words like 'total', 'altogether', 'in all' usually mean addition.",
    process_explanation: "Read the problem twice. Identify the numbers. Spot the keyword. Decide if it's addition. Write the equation. Solve.",
    worked_example: "Rita has 234 stamps. Her brother gives her 156 more. Total stamps = 234 + 156 = 390.",
    common_misconceptions: "Students just add all numbers without reading carefully. Sometimes a number is irrelevant.",
    shortcuts_and_tricks: "Keywords for addition: total, sum, altogether, in all, both, combined, plus.",
    key_takeaway: "Addition word problems use keywords like total, sum, altogether, and in all.",
  },
  {
    topicId: "math3_ch6_word_problems_sub", chapterNumber: 6, sectionNumber: "6.2",
    title: "Word Problems — Subtraction", subject: "Mathematics",
    intuition: "Subtraction comes up when we lose, give away, or compare two numbers.",
    process_explanation: "Spot the keyword. Identify the bigger number and the smaller one. Subtract smaller from bigger.",
    worked_example: "Ramu had 458 marbles. He gave 173 to his sister. Marbles left = 458 − 173 = 285.",
    common_misconceptions: "Students subtract bigger from smaller and get negative answers (not allowed at this level). Always bigger − smaller.",
    shortcuts_and_tricks: "Keywords for subtraction: difference, how many more, how many less, remaining, left over.",
    key_takeaway: "Subtraction word problems use keywords like difference, left, remaining, and how many more.",
  },
  {
    topicId: "math3_ch6_mental_math", chapterNumber: 6, sectionNumber: "6.3",
    title: "Mental Math Strategies", subject: "Mathematics",
    intuition: "Some additions/subtractions are easy to do in your head. Round, split, or use friendly numbers.",
    process_explanation: "Round to the nearest 10 or 100, then adjust. Or break numbers into parts that are easier to add/subtract.",
    worked_example: "298 + 156: think 300 + 156 = 456, then subtract 2 → 454. Or 100 − 47: think 100 − 50 = 50, then add 3 → 53.",
    common_misconceptions: "Students rely on paper for every calculation. Mental math is faster for small numbers.",
    shortcuts_and_tricks: "Friendly numbers: round to multiples of 10 or 100, do the easy operation, adjust at the end.",
    key_takeaway: "Mental math saves time. Round, split, or use friendly numbers to calculate in your head.",
  },
  {
    topicId: "math3_ch6_estimation", chapterNumber: 6, sectionNumber: "6.4",
    title: "Estimation of Sums and Differences", subject: "Mathematics",
    intuition: "Estimation gives a quick approximate answer before doing the exact calculation. Useful for checking errors.",
    process_explanation: "Round each number to the nearest 10 or 100, then add or subtract the rounded values.",
    worked_example: "Estimate 298 + 411: round to 300 + 400 = 700. Actual answer (709) is very close.",
    common_misconceptions: "Estimation isn't a 'wrong' answer — it's a quick approximation.",
    shortcuts_and_tricks: "Round to the nearest 10 for numbers under 100. Round to the nearest 100 for bigger numbers.",
    key_takeaway: "Estimation rounds numbers first, then computes a quick approximate answer.",
  },

  // ── Chapter 7: Time Goes On ────────────────────────────────────────────
  {
    topicId: "math3_ch7_reading_clock", chapterNumber: 7, sectionNumber: "7.1",
    title: "Reading a Clock", subject: "Mathematics",
    intuition: "A clock has two hands: short = hour, long = minute. Reading the time = reading both hands.",
    process_explanation: "Hour hand shows the hour. Minute hand shows minutes past the hour. The minute hand moves 6° per minute.",
    worked_example: "Short hand on 3, long hand on 6 → time = 3:30 (3 hours, 30 minutes).",
    common_misconceptions: "Students confuse hour and minute hand. Hour hand is shorter; minute hand is longer.",
    shortcuts_and_tricks: "Long for minute, short for hour. Multiply the minute-hand number by 5 to get minutes.",
    key_takeaway: "Read the hour hand first (short), then the minute hand (long).",
  },
  {
    topicId: "math3_ch7_am_pm", chapterNumber: 7, sectionNumber: "7.2",
    title: "AM and PM", subject: "Mathematics",
    intuition: "Each day has 24 hours. AM = morning (midnight to noon). PM = afternoon and evening (noon to midnight).",
    process_explanation: "AM: 12 midnight to 12 noon. PM: 12 noon to 12 midnight. Each is 12 hours long.",
    worked_example: "School starts at 8 AM (morning). Dinner is at 8 PM (evening). Sunrise: AM. Sunset: PM.",
    common_misconceptions: "Students think 12 AM is noon. 12 AM = midnight (start of day). 12 PM = noon.",
    shortcuts_and_tricks: "AM = Ante Meridiem (before noon). PM = Post Meridiem (after noon).",
    key_takeaway: "AM is morning; PM is afternoon/evening. Each spans 12 hours.",
  },
  {
    topicId: "math3_ch7_calendar", chapterNumber: 7, sectionNumber: "7.3",
    title: "Calendar — Days, Months, Year", subject: "Mathematics",
    intuition: "A year has 12 months. A month has about 30 days. A week has 7 days. A day has 24 hours.",
    process_explanation: "Months: Jan (31), Feb (28/29), Mar (31), Apr (30), May (31), Jun (30), Jul (31), Aug (31), Sep (30), Oct (31), Nov (30), Dec (31). Leap year = Feb has 29 days, comes every 4 years.",
    worked_example: "Year has 12 months = 365 days (366 in leap year). Week has 7 days. 1 day = 24 hours.",
    common_misconceptions: "All months have 30 days — WRONG. Use knuckle trick: knuckles = 31 days, gaps = 30 days (except Feb).",
    shortcuts_and_tricks: "Knuckle trick: count months on knuckles. Knuckle = long month (31 days). Gap = short month (30 days, except Feb).",
    key_takeaway: "12 months/year, ~30 days/month, 7 days/week, 24 hours/day.",
  },
  {
    topicId: "math3_ch7_duration", chapterNumber: 7, sectionNumber: "7.4",
    title: "Calculating Duration", subject: "Mathematics",
    intuition: "Duration = end time − start time. It tells how long an event lasted.",
    process_explanation: "Subtract start time from end time. If end is the next day, add 24 hours first.",
    worked_example: "Movie starts at 4 PM, ends at 6 PM → duration = 6 − 4 = 2 hours. School: 8 AM to 2 PM → 2 PM = 14:00 → 14 − 8 = 6 hours.",
    common_misconceptions: "Students just subtract numbers without checking AM/PM.",
    shortcuts_and_tricks: "Convert both times to 24-hour format, then subtract.",
    key_takeaway: "Duration = end time − start time. Always check AM/PM.",
  },

  // ── Chapter 8: Who is Heavier? ─────────────────────────────────────────
  {
    topicId: "math3_ch8_heavier_lighter", chapterNumber: 8, sectionNumber: "8.1",
    title: "Heavier and Lighter", subject: "Mathematics",
    intuition: "Heavier objects need more force to lift. Lighter objects are easier to lift.",
    process_explanation: "Compare two objects by lifting them or using a balance. The one that pulls down more is heavier.",
    worked_example: "Iron ball vs paper ball of same size → iron is heavier. A book vs a pencil → book is heavier.",
    common_misconceptions: "Bigger size = heavier. Not always! A pillow (big) is lighter than a brick (small).",
    shortcuts_and_tricks: "Use a balance scale: the side that goes down is heavier.",
    key_takeaway: "Heavier objects pull down more on a balance scale.",
  },
  {
    topicId: "math3_ch8_grams_kilograms", chapterNumber: 8, sectionNumber: "8.2",
    title: "Grams and Kilograms", subject: "Mathematics",
    intuition: "Gram (g) is small (like a paperclip). Kilogram (kg) is big (like a textbook). 1 kg = 1000 g.",
    process_explanation: "Use g for light things (food packets, paper). Use kg for heavy things (rice bags, body weight).",
    worked_example: "A coin = 5 g. A bag of sugar = 1 kg = 1000 g. A child = 25 kg.",
    common_misconceptions: "Students think 1 kg = 100 g. Correct: 1 kg = 1000 g.",
    shortcuts_and_tricks: "Convert kg to g: multiply by 1000. Convert g to kg: divide by 1000.",
    key_takeaway: "1 kg = 1000 g. Use g for light objects, kg for heavy ones.",
  },
  {
    topicId: "math3_ch8_balance_scale", chapterNumber: 8, sectionNumber: "8.3",
    title: "Using a Balance Scale", subject: "Mathematics",
    intuition: "A balance compares two weights. If equal, both sides are level. If unequal, the heavier side goes down.",
    process_explanation: "Place objects on both sides. Observe which side dips. To weigh, add standard weights until balanced.",
    worked_example: "If a fruit balances with three 100 g weights, its weight = 300 g.",
    common_misconceptions: "Students think the heavier side goes up. Heavier ALWAYS goes down (gravity).",
    shortcuts_and_tricks: "Add standard weights one by one until the scale levels. Then total the weights.",
    key_takeaway: "On a balance scale, the heavier side goes down. Use standard weights to find exact mass.",
  },
  {
    topicId: "math3_ch8_weight_word", chapterNumber: 8, sectionNumber: "8.4",
    title: "Word Problems on Weight", subject: "Mathematics",
    intuition: "Real-life questions about weight often involve adding, subtracting, or comparing weights.",
    process_explanation: "Read carefully. Identify weights and the operation needed. Solve and label the answer with units.",
    worked_example: "A bag of rice weighs 5 kg. A bag of dal weighs 2 kg. Total weight = 5 + 2 = 7 kg.",
    common_misconceptions: "Forgetting to convert units. Adding 500 g + 1 kg as 501 is wrong — convert 1 kg = 1000 g first.",
    shortcuts_and_tricks: "Always convert all values to the same unit (preferably grams) before doing math.",
    key_takeaway: "In weight word problems, convert to the same unit, then add, subtract, or compare.",
  },

  // ── Chapter 9: How Many Times? ─────────────────────────────────────────
  {
    topicId: "math3_ch9_repeated_addition", chapterNumber: 9, sectionNumber: "9.1",
    title: "Multiplication as Repeated Addition", subject: "Mathematics",
    intuition: "Multiplication is a shortcut for adding the same number many times. 3 × 4 means 'three fours' = 4 + 4 + 4.",
    process_explanation: "First number = how many groups. Second number = items per group. Multiplying gives the total.",
    worked_example: "5 × 3 = 3 + 3 + 3 + 3 + 3 = 15. Or 5 groups of 3 = 15.",
    common_misconceptions: "Students see 5 × 3 and add 5 + 3 = 8. Multiplication is NOT addition of the two numbers — it's repeated addition.",
    shortcuts_and_tricks: "A × B means 'A groups of B' or 'add B to itself A times'.",
    key_takeaway: "Multiplication is repeated addition of equal groups.",
  },
  {
    topicId: "math3_ch9_times_tables", chapterNumber: 9, sectionNumber: "9.2",
    title: "Times Tables (2 to 10)", subject: "Mathematics",
    intuition: "Times tables are short patterns that help you multiply quickly without adding each time.",
    process_explanation: "Memorise tables of 2, 3, 4, 5, 6, 7, 8, 9, 10. Each table shows multiples of a number from 1 to 10.",
    worked_example: "Table of 5: 5, 10, 15, 20, 25, 30, 35, 40, 45, 50. 5 × 7 = 35.",
    common_misconceptions: "Students think tables are just memorisation. They are patterns — table of 2 = even numbers; table of 5 ends in 0 or 5.",
    shortcuts_and_tricks: "Table of 9: digits of each answer add up to 9 (9, 18, 27, 36 — 1+8=9, 2+7=9, 3+6=9).",
    key_takeaway: "Times tables (2 to 10) make multiplication fast. Look for patterns to learn them easily.",
  },
  {
    topicId: "math3_ch9_multiplication_word", chapterNumber: 9, sectionNumber: "9.3",
    title: "Multiplication Word Problems", subject: "Mathematics",
    intuition: "Word problems involving 'each', 'every', 'per' usually mean multiplication.",
    process_explanation: "Identify: number of groups × items per group = total. Write the equation, then solve.",
    worked_example: "Each box has 6 chocolates. There are 4 boxes. Total = 4 × 6 = 24 chocolates.",
    common_misconceptions: "Confusing per-group count and number of groups. Both must be identified clearly.",
    shortcuts_and_tricks: "Keywords for multiplication: each, every, per, twice, double, triple, times.",
    key_takeaway: "Multiplication word problems use keywords like each, every, per, and times.",
  },
  {
    topicId: "math3_ch9_arrays", chapterNumber: 9, sectionNumber: "9.4",
    title: "Arrays and Equal Groups", subject: "Mathematics",
    intuition: "An array arranges objects in rows and columns — like soldiers in a parade. It's a visual way to see multiplication.",
    process_explanation: "Rows × columns = total objects. Count one row, then multiply by the number of rows.",
    worked_example: "A 3×4 array: 3 rows of 4 = 12. Or 4 columns of 3 = 12. Same answer.",
    common_misconceptions: "Students count one object at a time instead of using the array's structure.",
    shortcuts_and_tricks: "3 × 4 = 4 × 3 = 12. The order doesn't change the total (commutative property).",
    key_takeaway: "Arrays show multiplication as rows × columns. Total = rows × columns.",
  },

  // ── Chapter 10: Play with Patterns ─────────────────────────────────────
  {
    topicId: "math3_ch10_number_patterns", chapterNumber: 10, sectionNumber: "10.1",
    title: "Number Patterns", subject: "Mathematics",
    intuition: "Numbers in a sequence often follow a rule. Find the rule, and you can predict the next number.",
    process_explanation: "Look at the difference between consecutive numbers. If constant, the rule is 'add that number' each time.",
    worked_example: "2, 4, 6, 8, ___ → +2 each time → 10. 5, 10, 15, 20, ___ → +5 each time → 25.",
    common_misconceptions: "Students guess randomly. Always check the difference between consecutive numbers first.",
    shortcuts_and_tricks: "Differences not constant? Try multiplying or skipping rules.",
    key_takeaway: "To find a number pattern, look at the rule connecting consecutive numbers.",
  },
  {
    topicId: "math3_ch10_shape_patterns", chapterNumber: 10, sectionNumber: "10.2",
    title: "Shape Patterns", subject: "Mathematics",
    intuition: "Shapes can repeat in a sequence. Find the repeating unit to predict what comes next.",
    process_explanation: "Identify the repeating block of shapes. Continue the block in the same order.",
    worked_example: "□ △ □ △ □ ___ → repeating unit is □ △ → next is △. ⭐ ⭐ ◯ ⭐ ⭐ ◯ → next is ⭐.",
    common_misconceptions: "Students only look at the most recent shape. Always identify the full repeating unit.",
    shortcuts_and_tricks: "Find the smallest repeating block — that's your pattern unit.",
    key_takeaway: "Shape patterns repeat a unit. Find the unit to predict the next shape.",
  },
  {
    topicId: "math3_ch10_growing_patterns", chapterNumber: 10, sectionNumber: "10.3",
    title: "Growing Patterns", subject: "Mathematics",
    intuition: "Growing patterns add (or take away) more each step. The change increases or decreases steadily.",
    process_explanation: "Compute the difference between consecutive terms. If it grows by a fixed amount each step, it's a growing pattern.",
    worked_example: "1, 3, 6, 10, ___ → differences are +2, +3, +4 → next add 5 → 15. (Triangular numbers!)",
    common_misconceptions: "Students apply a constant rule like +2 to all growing patterns. The rule must match.",
    shortcuts_and_tricks: "Write differences below each pair. If differences themselves form a pattern, it's growing.",
    key_takeaway: "Growing patterns increase (or decrease) by a changing amount each step.",
  },
  {
    topicId: "math3_ch10_pattern_rules", chapterNumber: 10, sectionNumber: "10.4",
    title: "Finding the Pattern Rule", subject: "Mathematics",
    intuition: "Every pattern has a rule. To find it, look at how each term changes from the one before.",
    process_explanation: "Step 1: list the terms. Step 2: find the difference. Step 3: state the rule (e.g., 'add 3' or 'multiply by 2').",
    worked_example: "2, 6, 18, 54, ___ → rule: multiply by 3 → next is 162. 100, 90, 80, 70 → rule: subtract 10 → next is 60.",
    common_misconceptions: "Some patterns use multiplication, not addition. Always test both rules.",
    shortcuts_and_tricks: "If consecutive numbers ÷ each other give the same answer, the rule is multiplication.",
    key_takeaway: "A pattern rule explains how each term comes from the previous one.",
  },

  // ── Chapter 11: Jugs and Mugs ──────────────────────────────────────────
  {
    topicId: "math3_ch11_ml_litres", chapterNumber: 11, sectionNumber: "11.1",
    title: "Millilitres and Litres", subject: "Mathematics",
    intuition: "Millilitre (ml) is small (like a spoonful). Litre (l) is big (like a water bottle). 1 l = 1000 ml.",
    process_explanation: "Use ml for medicine, spoonfuls, and drops. Use l for water bottles, milk packets, and buckets.",
    worked_example: "A teaspoon = 5 ml. A water bottle = 1 l = 1000 ml. A bucket = 10 l.",
    common_misconceptions: "Students think 1 l = 100 ml. Correct: 1 l = 1000 ml.",
    shortcuts_and_tricks: "Convert l to ml: multiply by 1000. Convert ml to l: divide by 1000.",
    key_takeaway: "1 l = 1000 ml. Use ml for small amounts, l for big amounts.",
  },
  {
    topicId: "math3_ch11_measuring_capacity", chapterNumber: 11, sectionNumber: "11.2",
    title: "Measuring Capacity", subject: "Mathematics",
    intuition: "Capacity is how much liquid a container can hold. We measure it with marked containers like measuring cups.",
    process_explanation: "Pour liquid into a marked container. Read the level on the scale.",
    worked_example: "A measuring jug shows 500 ml when filled to that mark. To measure 750 ml, fill to the 750 ml line.",
    common_misconceptions: "Students confuse capacity (how much fits) with weight (how heavy it is).",
    shortcuts_and_tricks: "Look at the surface of the liquid at eye level for accurate reading.",
    key_takeaway: "Capacity is how much liquid a container holds. Measure with marked containers.",
  },
  {
    topicId: "math3_ch11_comparing_capacity", chapterNumber: 11, sectionNumber: "11.3",
    title: "Comparing Capacities", subject: "Mathematics",
    intuition: "Bigger number in the same unit = more capacity. Always use the same unit before comparing.",
    process_explanation: "Convert all values to ml (or all to l). Then compare numbers directly.",
    worked_example: "Compare 1 l and 600 ml: convert 1 l = 1000 ml → 1000 > 600 → 1 l is bigger.",
    common_misconceptions: "Comparing 1 l vs 600 ml as 1 < 600 — forgetting unit conversion.",
    shortcuts_and_tricks: "Convert to the smaller unit (ml) when comparing l and ml.",
    key_takeaway: "Compare capacities in the same unit. Convert before comparing.",
  },
  {
    topicId: "math3_ch11_capacity_word", chapterNumber: 11, sectionNumber: "11.4",
    title: "Word Problems on Capacity", subject: "Mathematics",
    intuition: "Capacity problems often involve filling, emptying, or comparing containers.",
    process_explanation: "Identify the operation (add/subtract). Convert units if needed. Solve with the correct unit in the answer.",
    worked_example: "A jug has 750 ml of milk. We add 250 ml more. Total = 750 + 250 = 1000 ml = 1 l.",
    common_misconceptions: "Forgetting to attach units to the answer.",
    shortcuts_and_tricks: "Convert everything to ml first; convert the final answer back to l if needed.",
    key_takeaway: "Capacity word problems use add/subtract. Always include units in the answer.",
  },

  // ── Chapter 12: Can We Share? ──────────────────────────────────────────
  {
    topicId: "math3_ch12_sharing_equally", chapterNumber: 12, sectionNumber: "12.1",
    title: "Sharing Equally — Division Intro", subject: "Mathematics",
    intuition: "Division splits a total into equal parts. 12 ÷ 3 means 'share 12 among 3 equally'.",
    process_explanation: "Total ÷ number of groups = items per group. Distribute one at a time until all are shared.",
    worked_example: "12 sweets shared among 3 children → 12 ÷ 3 = 4 sweets each.",
    common_misconceptions: "Students confuse 12 ÷ 3 with 3 ÷ 12. The big number is shared, not the small one.",
    shortcuts_and_tricks: "Use objects to act out: deal one to each person until all are distributed.",
    key_takeaway: "Division shares a total into equal groups: total ÷ groups = per group.",
  },
  {
    topicId: "math3_ch12_division_facts", chapterNumber: 12, sectionNumber: "12.2",
    title: "Division by 2, 5, and 10", subject: "Mathematics",
    intuition: "Some divisions are easy because their times tables are simple. Knowing 5 × 4 = 20 means 20 ÷ 5 = 4.",
    process_explanation: "Use the times table backwards. If A × B = C, then C ÷ A = B and C ÷ B = A.",
    worked_example: "20 ÷ 2 = 10. 50 ÷ 5 = 10. 100 ÷ 10 = 10.",
    common_misconceptions: "Students try to divide without knowing the matching times table.",
    shortcuts_and_tricks: "Memorise tables of 2, 5, 10 first — these give the easiest divisions.",
    key_takeaway: "Division by 2, 5, and 10 uses the corresponding times tables in reverse.",
  },
  {
    topicId: "math3_ch12_remainders", chapterNumber: 12, sectionNumber: "12.3",
    title: "Division with Remainders", subject: "Mathematics",
    intuition: "Sometimes division doesn't divide evenly. The leftover is called the remainder.",
    process_explanation: "Find the largest multiple of the divisor that fits. Subtract to find the remainder.",
    worked_example: "14 ÷ 3 → 3 × 4 = 12, remainder = 14 − 12 = 2. So 14 ÷ 3 = 4 remainder 2.",
    common_misconceptions: "Forgetting to compute the remainder, or stating it as the wrong number.",
    shortcuts_and_tricks: "Quotient × divisor + remainder = dividend. Use this to check your answer.",
    key_takeaway: "When division isn't exact, the leftover is the remainder.",
  },
  {
    topicId: "math3_ch12_division_word", chapterNumber: 12, sectionNumber: "12.4",
    title: "Division Word Problems", subject: "Mathematics",
    intuition: "Division word problems involve sharing, distributing, or grouping equally.",
    process_explanation: "Read the problem. Identify total and number of groups. Divide to get per-group count.",
    worked_example: "24 students sit in 4 rows equally. Students per row = 24 ÷ 4 = 6.",
    common_misconceptions: "Confusing total and groups. Total is always the bigger number you're splitting.",
    shortcuts_and_tricks: "Keywords for division: share, distribute, split, equally, each, per group.",
    key_takeaway: "Division word problems split a total into equal groups.",
  },

  // ── Chapter 13: Smart Charts! ──────────────────────────────────────────
  {
    topicId: "math3_ch13_pictographs", chapterNumber: 13, sectionNumber: "13.1",
    title: "Pictographs", subject: "Mathematics",
    intuition: "A pictograph uses pictures or symbols to show data. Each symbol stands for a number.",
    process_explanation: "Read the key: each symbol = X items. Count symbols per row, multiply by X.",
    worked_example: "Key: each ★ = 5 apples. A row has 4 stars → 4 × 5 = 20 apples.",
    common_misconceptions: "Students count symbols and forget the key. Always multiply by what each symbol stands for.",
    shortcuts_and_tricks: "Find the key first. Then count and multiply.",
    key_takeaway: "Pictographs use symbols. Multiply symbols × key value to find the count.",
  },
  {
    topicId: "math3_ch13_bar_graphs", chapterNumber: 13, sectionNumber: "13.2",
    title: "Bar Graphs", subject: "Mathematics",
    intuition: "A bar graph uses bars of different heights to show data visually. Taller bar = bigger value.",
    process_explanation: "Read the y-axis scale. For each category, read the bar's top to find its value.",
    worked_example: "Bar graph of pets: Dog=10, Cat=8, Fish=5. Tallest bar (dog) means most pets.",
    common_misconceptions: "Misreading the scale. If scale is in 2s, each gridline = 2 items.",
    shortcuts_and_tricks: "Use a ruler to align the top of the bar with the y-axis scale.",
    key_takeaway: "Bar graph: taller bar = bigger value. Read the y-axis for the count.",
  },
  {
    topicId: "math3_ch13_reading_charts", chapterNumber: 13, sectionNumber: "13.3",
    title: "Reading and Interpreting Charts", subject: "Mathematics",
    intuition: "Charts let us answer questions about data quickly: most, least, total, difference.",
    process_explanation: "Find the relevant bar/row. Read its value. Compare or compute as the question asks.",
    worked_example: "From bar graph: most students like cricket (15). Least like hockey (5). Difference = 15 − 5 = 10.",
    common_misconceptions: "Students read the wrong bar. Always check labels carefully.",
    shortcuts_and_tricks: "Read labels first. Then trace the bar to the y-axis.",
    key_takeaway: "Reading charts: identify the bar, read its value, then answer the question.",
  },
  {
    topicId: "math3_ch13_data_collection", chapterNumber: 13, sectionNumber: "13.4",
    title: "Collecting and Organising Data", subject: "Mathematics",
    intuition: "Before making a chart, we must collect data — usually by asking, observing, or recording.",
    process_explanation: "Step 1: decide what to find out. Step 2: ask/observe. Step 3: tally results. Step 4: organise in a table.",
    worked_example: "Survey: favourite sport. Ask 20 students. Tally: cricket=10, football=6, hockey=4. Now make a chart.",
    common_misconceptions: "Skipping the tally step and trying to remember all responses.",
    shortcuts_and_tricks: "Tally marks: |, ||, |||, ||||, then cross-bar for 5: ||||̸.",
    key_takeaway: "Data collection = ask + tally + organise. Then chart it.",
  },

  // ── Chapter 14: Rupees and Paise ───────────────────────────────────────
  {
    topicId: "math3_ch14_rupees_paise", chapterNumber: 14, sectionNumber: "14.1",
    title: "Rupees and Paise", subject: "Mathematics",
    intuition: "Indian money has rupees (₹) and paise (p). 1 rupee = 100 paise.",
    process_explanation: "Coins: 1, 2, 5, 10 rupees. Notes: 10, 20, 50, 100, 200, 500, 2000 rupees. Paise are rarely used now but still 100 paise = 1 rupee.",
    worked_example: "₹25 = 25 rupees. ₹25.50 = 25 rupees and 50 paise. 200 paise = ₹2.",
    common_misconceptions: "Students think 1 ₹ = 10 paise. Correct: 1 ₹ = 100 paise.",
    shortcuts_and_tricks: "Convert paise to rupees: divide by 100. Convert rupees to paise: multiply by 100.",
    key_takeaway: "1 rupee = 100 paise. Money in India is in rupees and paise.",
  },
  {
    topicId: "math3_ch14_money_conversion", chapterNumber: 14, sectionNumber: "14.2",
    title: "Converting Rupees and Paise", subject: "Mathematics",
    intuition: "To compare or add money in different units, convert everything to one unit first.",
    process_explanation: "Convert paise to rupees by dividing by 100. Convert rupees to paise by multiplying by 100.",
    worked_example: "350 paise = ₹3.50. ₹4 = 400 paise. ₹2.75 = 275 paise.",
    common_misconceptions: "Multiplying paise by 10 instead of dividing by 100.",
    shortcuts_and_tricks: "If working with both, convert everything to paise (whole numbers) — easier.",
    key_takeaway: "Convert money to the same unit before adding or comparing.",
  },
  {
    topicId: "math3_ch14_money_addition", chapterNumber: 14, sectionNumber: "14.3",
    title: "Adding and Subtracting Money", subject: "Mathematics",
    intuition: "Money math works the same as number math. Add or subtract rupees and paise like regular numbers.",
    process_explanation: "Line up the decimals (or convert to paise). Add or subtract column by column.",
    worked_example: "₹25.50 + ₹14.25 = ₹39.75. ₹100 − ₹37.50 = ₹62.50.",
    common_misconceptions: "Misaligning the decimal point — leads to wrong answers.",
    shortcuts_and_tricks: "Always line up the decimal points (or convert all to paise to skip decimals).",
    key_takeaway: "Add/subtract money by aligning decimal points or converting to a single unit.",
  },
  {
    topicId: "math3_ch14_money_problems", chapterNumber: 14, sectionNumber: "14.4",
    title: "Word Problems on Money", subject: "Mathematics",
    intuition: "Money word problems involve buying, change, and totals. Read carefully to choose the right operation.",
    process_explanation: "Identify amounts. Decide: add (total), subtract (change), multiply (multiple items same price).",
    worked_example: "A pen costs ₹15. Riya buys 3 pens. Total = 3 × ₹15 = ₹45. She pays ₹50 → change = ₹50 − ₹45 = ₹5.",
    common_misconceptions: "Forgetting to subtract for change. 'How much change?' means subtract.",
    shortcuts_and_tricks: "Keywords: 'change' = subtract. 'Total' = add. 'Each' = multiply.",
    key_takeaway: "Money word problems use add (total), subtract (change), multiply (multiple same items).",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log(`Seeding ${topics.length} Class 3 Math v2 sub-topics...`);
  for (const t of topics) {
    await NcertTopicContent.findOneAndUpdate({ topicId: t.topicId }, t, { upsert: true, new: true });
  }
  console.log(`Seeded ${topics.length} Class 3 Math v2 sub-topics.`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
