/**
 * seedMath1QuestionsV2C.js
 * Class 1 Mathematics v2 — Chapters 5–6 (64 questions)
 * Numbers 10-20 and Time sub-topics
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import { Question } from "../models/index.js";

dotenv.config();

const questions = [

  // ── Ch5 S1: The Number Ten (math1_ch5_number_ten) ────────────────────────────
  { questionId:"math1_ch5_number_ten_q1", topicId:"math1_ch5_number_ten", text:"How many fingers do you have on BOTH hands?", options:[{text:"5",type:"concept_error",logicTag:"one hand only"},{text:"8",type:"concept_error",logicTag:"wrong"},{text:"10",type:"correct",logicTag:"both hands = 10"},{text:"12",type:"concept_error",logicTag:"too many"}], explanation:"5 fingers on each hand. 5 + 5 = 10.", solutionSteps:["Left hand: 5 fingers","Right hand: 5 fingers","5 + 5 = 10"], shortcut:"Both hands together = 10.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_number_ten_q2", topicId:"math1_ch5_number_ten", text:"10 is made of how many tens and how many ones?", options:[{text:"0 tens and 10 ones",type:"concept_error",logicTag:"no tens recognised"},{text:"2 tens and 0 ones",type:"concept_error",logicTag:"that's 20"},{text:"1 ten and 0 ones",type:"correct",logicTag:"10 = 1 ten"},{text:"1 ten and 1 one",type:"concept_error",logicTag:"that's 11"}], explanation:"10 = 1 group of ten, zero ones.", solutionSteps:["Bundle 10 objects","1 bundle = 1 ten","0 extras = 0 ones"], shortcut:"10 = 1 ten + 0 ones.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_number_ten_q3", topicId:"math1_ch5_number_ten", text:"A full ten-frame has how many dots?", options:[{text:"5",type:"concept_error",logicTag:"half frame"},{text:"8",type:"concept_error",logicTag:"not full"},{text:"10",type:"correct",logicTag:"full ten-frame = 10"},{text:"12",type:"concept_error",logicTag:"too many for one frame"}], explanation:"A ten-frame has 2 rows of 5 boxes = 10 boxes. When full, it shows 10.", solutionSteps:["Ten-frame: 5 + 5 = 10","Full = 10 dots"], shortcut:"Full ten-frame = 10.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_number_ten_q4", topicId:"math1_ch5_number_ten", text:"Which numeral means ten?", options:[{text:"1",type:"concept_error",logicTag:"that's one"},{text:"01",type:"concept_error",logicTag:"digits reversed"},{text:"100",type:"concept_error",logicTag:"hundred"},{text:"10",type:"correct",logicTag:"ten written as 10"}], explanation:"Ten is written as 10 — a '1' in the tens place and a '0' in the ones place.", solutionSteps:["Ten = 10","1 in tens place, 0 in ones place"], shortcut:"10: the 1 is on the LEFT (tens), 0 is on the RIGHT (ones).", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_number_ten_q5", topicId:"math1_ch5_number_ten", text:"What comes right after 9?", options:[{text:"8",type:"concept_error",logicTag:"before 9"},{text:"11",type:"concept_error",logicTag:"skipped 10"},{text:"10",type:"correct",logicTag:"after 9 = 10"},{text:"19",type:"concept_error",logicTag:"wrong"}], explanation:"After 9 is 10 — our first two-digit number.", solutionSteps:["…8, 9, 10…","After 9 = 10"], shortcut:"9 → 10: the next number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_number_ten_q6", topicId:"math1_ch5_number_ten", text:"10 = 5 + ___", options:[{text:"4",type:"calculation_error",logicTag:"gives 9"},{text:"6",type:"calculation_error",logicTag:"gives 11"},{text:"5",type:"correct",logicTag:"5+5=10"},{text:"10",type:"concept_error",logicTag:"gives 20"}], explanation:"5 + 5 = 10. Both halves of the ten-frame.", solutionSteps:["5 + ? = 10","10 − 5 = 5"], shortcut:"10 = 5 + 5.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_number_ten_q7", topicId:"math1_ch5_number_ten", text:"How many legs does a crab have? (Hint: crabs have 10 legs.)", options:[{text:"6",type:"concept_error",logicTag:"insect legs"},{text:"8",type:"concept_error",logicTag:"spider legs"},{text:"10",type:"correct",logicTag:"crab = 10 legs"},{text:"4",type:"concept_error",logicTag:"dog legs"}], explanation:"Crabs have 10 legs — a great way to remember the number 10.", solutionSteps:["Crab has 10 legs","10 = ten"], shortcut:"Crab: 10 legs = 10.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_number_ten_q8", topicId:"math1_ch5_number_ten", text:"Is 10 a one-digit or two-digit number?", options:[{text:"One-digit",type:"concept_error",logicTag:"one digit = 1-9"},{text:"Three-digit",type:"concept_error",logicTag:"three digits = 100+"},{text:"Two-digit",type:"correct",logicTag:"10 has two digits: 1 and 0"},{text:"It has no digits",type:"concept_error",logicTag:"wrong"}], explanation:"10 has two digits: 1 and 0. It is the first two-digit number.", solutionSteps:["Count digits in 10: '1' and '0'","Two digits → two-digit number"], shortcut:"10 = first two-digit number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },

  // ── Ch5 S2: Numbers 11 to 15 (math1_ch5_numbers_11_to_15) ────────────────────
  { questionId:"math1_ch5_numbers_11_to_15_q1", topicId:"math1_ch5_numbers_11_to_15", text:"13 = 1 ten and ___ ones.", options:[{text:"1",type:"concept_error",logicTag:"that's 11"},{text:"0",type:"concept_error",logicTag:"that's 10"},{text:"3",type:"correct",logicTag:"13 = 1 ten + 3 ones"},{text:"4",type:"concept_error",logicTag:"that's 14"}], explanation:"13 = 1 ten + 3 ones.", solutionSteps:["13 − 10 = 3","So 1 ten + 3 ones"], shortcut:"Ones digit of 13 is 3.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_11_to_15_q2", topicId:"math1_ch5_numbers_11_to_15", text:"What is the word name for 12?", options:[{text:"Twelvety",type:"concept_error",logicTag:"not a real word"},{text:"Twelve",type:"correct",logicTag:"correct"},{text:"Twenty",type:"concept_error",logicTag:"that's 20"},{text:"Eleventeen",type:"concept_error",logicTag:"not a real word"}], explanation:"12 = twelve. An irregular word that must be memorised.", solutionSteps:["12 → twelve","Memorise: eleven (11), twelve (12)"], shortcut:"Twelve = 12. Memorise it!", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_11_to_15_q3", topicId:"math1_ch5_numbers_11_to_15", text:"Which number is 1 ten + 5 ones?", options:[{text:"51",type:"concept_error",logicTag:"reversed digits"},{text:"14",type:"concept_error",logicTag:"one off"},{text:"15",type:"correct",logicTag:"1 ten + 5 ones = 15"},{text:"10",type:"concept_error",logicTag:"no ones"}], explanation:"1 ten + 5 ones = 15 (fifteen).", solutionSteps:["1 ten = 10","+ 5 ones = 15"], shortcut:"10 + 5 = 15.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_11_to_15_q4", topicId:"math1_ch5_numbers_11_to_15", text:"What is the number name for 14?", options:[{text:"Forteen",type:"concept_error",logicTag:"misspelling"},{text:"Fourteen",type:"correct",logicTag:"correct"},{text:"Forty",type:"concept_error",logicTag:"that's 40"},{text:"Fortteen",type:"concept_error",logicTag:"misspelling"}], explanation:"14 = fourteen (four + teen).", solutionSteps:["four + teen = fourteen","14 = fourteen"], shortcut:"Four-TEEN = 14.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_11_to_15_q5", topicId:"math1_ch5_numbers_11_to_15", text:"Order: 13, 11, 15, 12, 14 — smallest first.", options:[{text:"15,14,13,12,11",type:"concept_error",logicTag:"descending"},{text:"11,12,13,14,15",type:"correct",logicTag:"ascending"},{text:"13,11,12,14,15",type:"concept_error",logicTag:"not ordered"},{text:"11,13,12,14,15",type:"concept_error",logicTag:"not correctly ordered"}], explanation:"Ascending: 11, 12, 13, 14, 15.", solutionSteps:["Smallest = 11","Then 12,13,14,15"], shortcut:"Count up: 11,12,13,14,15.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_11_to_15_q6", topicId:"math1_ch5_numbers_11_to_15", text:"What number comes after 11?", options:[{text:"10",type:"concept_error",logicTag:"before 11"},{text:"13",type:"concept_error",logicTag:"skips 12"},{text:"12",type:"correct",logicTag:"after 11 = 12"},{text:"20",type:"concept_error",logicTag:"too far"}], explanation:"After 11 is 12.", solutionSteps:["…11, 12, 13…","After 11 = 12"], shortcut:"11 → 12.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_11_to_15_q7", topicId:"math1_ch5_numbers_11_to_15", text:"Eleven is written as ___.", options:[{text:"10",type:"concept_error",logicTag:"that's ten"},{text:"21",type:"concept_error",logicTag:"wrong"},{text:"11",type:"correct",logicTag:"eleven = 11"},{text:"12",type:"concept_error",logicTag:"that's twelve"}], explanation:"Eleven = 11. Irregular name; memorise it.", solutionSteps:["Eleven = 11","Memorise this pair"], shortcut:"Eleven = 11.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_11_to_15_q8", topicId:"math1_ch5_numbers_11_to_15", text:"A ten-frame is full (10) and 4 extra dots are added. What number is shown?", options:[{text:"10",type:"concept_error",logicTag:"forgot the 4"},{text:"14",type:"correct",logicTag:"10+4=14"},{text:"40",type:"concept_error",logicTag:"tens and ones swapped"},{text:"13",type:"calculation_error",logicTag:"one short"}], explanation:"10 + 4 = 14 (fourteen).", solutionSteps:["Full ten-frame = 10","Add 4 more = 14"], shortcut:"10 + extra ones = teen number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },

  // ── Ch5 S3: Numbers 16 to 20 (math1_ch5_numbers_16_to_20) ────────────────────
  { questionId:"math1_ch5_numbers_16_to_20_q1", topicId:"math1_ch5_numbers_16_to_20", text:"18 = 1 ten and ___ ones.", options:[{text:"8",type:"correct",logicTag:"18 = 10 + 8"},{text:"1",type:"concept_error",logicTag:"that's 11"},{text:"10",type:"concept_error",logicTag:"that's 20"},{text:"6",type:"concept_error",logicTag:"that's 16"}], explanation:"18 = 1 ten + 8 ones.", solutionSteps:["18 − 10 = 8","So 1 ten + 8 ones"], shortcut:"Ones digit of 18 = 8.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_16_to_20_q2", topicId:"math1_ch5_numbers_16_to_20", text:"What is the word name for 20?", options:[{text:"Twelvety",type:"concept_error",logicTag:"not real"},{text:"Nineteen",type:"concept_error",logicTag:"that's 19"},{text:"Twenty",type:"correct",logicTag:"20 = twenty"},{text:"Two",type:"concept_error",logicTag:"that's 2"}], explanation:"20 = twenty (2 tens).", solutionSteps:["20 = two tens = twenty"], shortcut:"Twenty = 20.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_16_to_20_q3", topicId:"math1_ch5_numbers_16_to_20", text:"Which number is 1 ten + 9 ones?", options:[{text:"19",type:"correct",logicTag:"19 = 10 + 9"},{text:"91",type:"concept_error",logicTag:"reversed"},{text:"18",type:"concept_error",logicTag:"one less"},{text:"20",type:"concept_error",logicTag:"one more"}], explanation:"1 ten + 9 ones = 19 (nineteen).", solutionSteps:["10 + 9 = 19"], shortcut:"10 + ones = teen.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_16_to_20_q4", topicId:"math1_ch5_numbers_16_to_20", text:"20 = ___ tens.", options:[{text:"0",type:"concept_error",logicTag:"no tens"},{text:"1",type:"concept_error",logicTag:"that's 10"},{text:"2",type:"correct",logicTag:"20 = 2 tens"},{text:"20",type:"concept_error",logicTag:"that's all ones"}], explanation:"20 = 2 tens + 0 ones.", solutionSteps:["20 ÷ 10 = 2 tens","0 ones remaining"], shortcut:"20 = 2 tens.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_16_to_20_q5", topicId:"math1_ch5_numbers_16_to_20", text:"What number comes BEFORE 20?", options:[{text:"21",type:"concept_error",logicTag:"after 20"},{text:"18",type:"concept_error",logicTag:"two before"},{text:"19",type:"correct",logicTag:"one before 20"},{text:"10",type:"concept_error",logicTag:"too far before"}], explanation:"Before 20 is 19.", solutionSteps:["…18, 19, 20…","Before 20 = 19"], shortcut:"19 comes before 20.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_16_to_20_q6", topicId:"math1_ch5_numbers_16_to_20", text:"Sixteen = ?", options:[{text:"60",type:"concept_error",logicTag:"sixty"},{text:"17",type:"concept_error",logicTag:"seventeen"},{text:"16",type:"correct",logicTag:"sixteen = 16"},{text:"6",type:"concept_error",logicTag:"just the ones"}], explanation:"Sixteen = 16 (1 ten + 6 ones).", solutionSteps:["Sixteen = 16","six-TEEN: 6 ones, 1 ten"], shortcut:"six-TEEN = 16.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_16_to_20_q7", topicId:"math1_ch5_numbers_16_to_20", text:"Order: 20, 16, 18, 17, 19 — largest first.", options:[{text:"16,17,18,19,20",type:"concept_error",logicTag:"smallest first"},{text:"20,19,18,17,16",type:"correct",logicTag:"descending"},{text:"20,18,16,17,19",type:"concept_error",logicTag:"not ordered"},{text:"19,20,18,16,17",type:"concept_error",logicTag:"not ordered"}], explanation:"Largest first (descending): 20, 19, 18, 17, 16.", solutionSteps:["Largest = 20","Then 19,18,17,16"], shortcut:"Count down: 20,19,18,17,16.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_numbers_16_to_20_q8", topicId:"math1_ch5_numbers_16_to_20", text:"Fill in: 16, 17, ___, 19, 20.", options:[{text:"16",type:"concept_error",logicTag:"already there"},{text:"21",type:"concept_error",logicTag:"too far"},{text:"18",type:"correct",logicTag:"between 17 and 19"},{text:"15",type:"concept_error",logicTag:"before 16"}], explanation:"16, 17, 18, 19, 20 — missing number is 18.", solutionSteps:["Between 17 and 19 = 18"], shortcut:"Count on from 17: 18.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },

  // ── Ch5 S4: Ordering Numbers to 20 (math1_ch5_ordering_to_20) ────────────────
  { questionId:"math1_ch5_ordering_to_20_q1", topicId:"math1_ch5_ordering_to_20", text:"Which is greater: 14 or 17?", options:[{text:"14",type:"concept_error",logicTag:"smaller"},{text:"They are equal",type:"concept_error",logicTag:"not equal"},{text:"17",type:"correct",logicTag:"17 > 14"},{text:"Cannot tell",type:"guessing",logicTag:"can tell by comparing"}], explanation:"17 > 14 (17 is further right on the number line).", solutionSteps:["Both have 1 ten","Ones: 7 > 4","So 17 > 14"], shortcut:"Same tens: compare ones. 7 > 4.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_ordering_to_20_q2", topicId:"math1_ch5_ordering_to_20", text:"Order 7, 19, 13, 2, 15 from smallest to largest.", options:[{text:"19,15,13,7,2",type:"concept_error",logicTag:"descending"},{text:"2,7,13,15,19",type:"correct",logicTag:"ascending"},{text:"2,13,7,15,19",type:"concept_error",logicTag:"not in order"},{text:"7,2,13,15,19",type:"concept_error",logicTag:"not in order"}], explanation:"Ascending: 2, 7, 13, 15, 19.", solutionSteps:["Smallest: 2","Then 7,13,15,19"], shortcut:"Ascending = smallest to largest.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_ordering_to_20_q3", topicId:"math1_ch5_ordering_to_20", text:"What is the largest number from 1 to 20?", options:[{text:"19",type:"concept_error",logicTag:"one before"},{text:"10",type:"concept_error",logicTag:"in the middle"},{text:"20",type:"correct",logicTag:"largest in range"},{text:"9",type:"concept_error",logicTag:"single digit"}], explanation:"20 is the largest number from 1 to 20.", solutionSteps:["1 to 20: 20 is the last","20 is largest"], shortcut:"Last number in range = largest.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_ordering_to_20_q4", topicId:"math1_ch5_ordering_to_20", text:"Is 11 > 9?", options:[{text:"No, 9 is bigger",type:"concept_error",logicTag:"incorrect"},{text:"They are equal",type:"concept_error",logicTag:"not equal"},{text:"Yes, 11 > 9",type:"correct",logicTag:"two digits > one digit"},{text:"Cannot compare",type:"guessing",logicTag:"can compare"}], explanation:"11 > 9 because 11 is a two-digit number (has tens) while 9 is single-digit.", solutionSteps:["11 has 1 ten","9 has 0 tens","More tens = bigger: 11 > 9"], shortcut:"Two-digit numbers are always bigger than one-digit numbers.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_ordering_to_20_q5", topicId:"math1_ch5_ordering_to_20", text:"Which number is BETWEEN 16 and 20?", options:[{text:"15",type:"concept_error",logicTag:"before 16"},{text:"21",type:"concept_error",logicTag:"after 20"},{text:"18",type:"correct",logicTag:"16 < 18 < 20"},{text:"20",type:"concept_error",logicTag:"endpoint not between"}], explanation:"18 is between 16 and 20 (17, 18, 19 are all valid — 18 is the best unique answer here).", solutionSteps:["Between 16 and 20: 17,18,19","18 is clearly between"], shortcut:"Between = in the gap.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_ordering_to_20_q6", topicId:"math1_ch5_ordering_to_20", text:"Fill in: ___, 12, 13, 14, 15.", options:[{text:"13",type:"concept_error",logicTag:"already there"},{text:"10",type:"concept_error",logicTag:"two before 12"},{text:"11",type:"correct",logicTag:"one before 12"},{text:"16",type:"concept_error",logicTag:"after 15"}], explanation:"One before 12 is 11.", solutionSteps:["…11, 12, 13…","Before 12 = 11"], shortcut:"Count back 1 from 12.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_ordering_to_20_q7", topicId:"math1_ch5_ordering_to_20", text:"The number line goes 1, 2, 3… to 20. Where is 10?", options:[{text:"At the start",type:"concept_error",logicTag:"start = 1"},{text:"At the end",type:"concept_error",logicTag:"end = 20"},{text:"In the middle",type:"correct",logicTag:"10 is the midpoint of 1-20"},{text:"Cannot tell",type:"guessing",logicTag:"can tell"}], explanation:"10 is in the middle of 1 to 20 (10 numbers before, 10 numbers after).", solutionSteps:["1 to 20 = 20 numbers","10 is the halfway point"], shortcut:"10 = midpoint of 1–20.", difficulty:"medium", subject:"Mathematics", grade:"1", chapter:"5" },
  { questionId:"math1_ch5_ordering_to_20_q8", topicId:"math1_ch5_ordering_to_20", text:"16 ___ 13 (which symbol fits: >, <, or =?)", options:[{text:"<",type:"concept_error",logicTag:"16 is more than 13"},{text:"=",type:"concept_error",logicTag:"not equal"},{text:">",type:"correct",logicTag:"16 > 13"},{text:"None",type:"guessing",logicTag:"a symbol fits"}], explanation:"16 > 13 (16 is greater than 13).", solutionSteps:["Both two-digit","Ones: 6 > 3 (same tens)","16 > 13"], shortcut:"Open mouth of > faces 16 (the bigger).", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"5" },

  // ── Ch6 S1: Days of the Week (math1_ch6_days_of_week) ────────────────────────
  { questionId:"math1_ch6_days_of_week_q1", topicId:"math1_ch6_days_of_week", text:"How many days are in one week?", options:[{text:"5",type:"concept_error",logicTag:"school days only"},{text:"6",type:"concept_error",logicTag:"one short"},{text:"7",type:"correct",logicTag:"7 days in a week"},{text:"8",type:"concept_error",logicTag:"one too many"}], explanation:"There are 7 days in a week: Sun, Mon, Tue, Wed, Thu, Fri, Sat.", solutionSteps:["Count: Sun,Mon,Tue,Wed,Thu,Fri,Sat","Total = 7"], shortcut:"A week = 7 days. Always.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_days_of_week_q2", topicId:"math1_ch6_days_of_week", text:"Which day comes AFTER Wednesday?", options:[{text:"Tuesday",type:"concept_error",logicTag:"before Wednesday"},{text:"Friday",type:"concept_error",logicTag:"two after"},{text:"Thursday",type:"correct",logicTag:"one after Wednesday"},{text:"Monday",type:"concept_error",logicTag:"earlier in week"}], explanation:"After Wednesday is Thursday.", solutionSteps:["Sun,Mon,Tue,WED,THU,Fri,Sat","After Wednesday = Thursday"], shortcut:"Wed → Thu.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_days_of_week_q3", topicId:"math1_ch6_days_of_week", text:"Which day comes BEFORE Friday?", options:[{text:"Saturday",type:"concept_error",logicTag:"after Friday"},{text:"Sunday",type:"concept_error",logicTag:"start of week"},{text:"Thursday",type:"correct",logicTag:"one before Friday"},{text:"Wednesday",type:"concept_error",logicTag:"two before"}], explanation:"Before Friday is Thursday.", solutionSteps:["…Thu, Fri, Sat…","Before Friday = Thursday"], shortcut:"Thu comes before Fri.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_days_of_week_q4", topicId:"math1_ch6_days_of_week", text:"Today is Monday. What day is tomorrow?", options:[{text:"Sunday",type:"concept_error",logicTag:"before Monday"},{text:"Wednesday",type:"concept_error",logicTag:"skips one"},{text:"Tuesday",type:"correct",logicTag:"after Monday"},{text:"Saturday",type:"concept_error",logicTag:"far away"}], explanation:"After Monday is Tuesday.", solutionSteps:["Mon → Tue","Tomorrow = Tuesday"], shortcut:"Mon → Tue.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_days_of_week_q5", topicId:"math1_ch6_days_of_week", text:"Today is Saturday. What day was YESTERDAY?", options:[{text:"Sunday",type:"concept_error",logicTag:"after Saturday"},{text:"Friday",type:"correct",logicTag:"one before Saturday"},{text:"Thursday",type:"concept_error",logicTag:"two before"},{text:"Monday",type:"concept_error",logicTag:"far away"}], explanation:"Before Saturday is Friday.", solutionSteps:["…Fri, Sat…","Yesterday = Friday"], shortcut:"Before Saturday = Friday.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_days_of_week_q6", topicId:"math1_ch6_days_of_week", text:"Which is the FIRST day of the week (as shown on most Indian calendars)?", options:[{text:"Monday",type:"concept_error",logicTag:"starts many Western calendars"},{text:"Tuesday",type:"concept_error",logicTag:"wrong"},{text:"Sunday",type:"correct",logicTag:"traditional Indian calendar starts Sunday"},{text:"Saturday",type:"concept_error",logicTag:"near the end"}], explanation:"Most Indian calendars start the week with Sunday.", solutionSteps:["Sunday = first day","…then Monday, Tuesday…"], shortcut:"Sunday starts the week on Indian calendars.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_days_of_week_q7", topicId:"math1_ch6_days_of_week", text:"Which day comes between Tuesday and Thursday?", options:[{text:"Monday",type:"concept_error",logicTag:"before Tuesday"},{text:"Friday",type:"concept_error",logicTag:"after Thursday"},{text:"Wednesday",type:"correct",logicTag:"between Tue and Thu"},{text:"Sunday",type:"concept_error",logicTag:"wrong"}], explanation:"Tue, Wed, Thu — Wednesday is between Tuesday and Thursday.", solutionSteps:["Sequence: Tue, Wed, Thu","Between = Wednesday"], shortcut:"Wed is in the middle of the week.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_days_of_week_q8", topicId:"math1_ch6_days_of_week", text:"After Saturday, the week starts again with ___.", options:[{text:"Monday",type:"concept_error",logicTag:"starts many Western weeks"},{text:"Friday",type:"concept_error",logicTag:"not the start"},{text:"Sunday",type:"correct",logicTag:"cycle restarts at Sunday"},{text:"Tuesday",type:"concept_error",logicTag:"wrong"}], explanation:"The week is a cycle. After Saturday, Sunday begins the new week.", solutionSteps:["…Fri, Sat → Sun,Mon…","After Saturday = Sunday (new week)"], shortcut:"Sat → Sun (cycle repeats).", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },

  // ── Ch6 S2: Parts of the Day (math1_ch6_parts_of_day) ────────────────────────
  { questionId:"math1_ch6_parts_of_day_q1", topicId:"math1_ch6_parts_of_day", text:"You eat breakfast. When is this?", options:[{text:"Night",type:"concept_error",logicTag:"sleep time"},{text:"Afternoon",type:"concept_error",logicTag:"lunch time"},{text:"Morning",type:"correct",logicTag:"breakfast = morning"},{text:"Evening",type:"concept_error",logicTag:"too late for breakfast"}], explanation:"Breakfast is eaten in the morning after waking up.", solutionSteps:["Morning = wake up, school, breakfast"], shortcut:"Breakfast = morning.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_parts_of_day_q2", topicId:"math1_ch6_parts_of_day", text:"The sun is setting. What part of the day is it?", options:[{text:"Morning",type:"concept_error",logicTag:"sun rises in morning"},{text:"Afternoon",type:"concept_error",logicTag:"sun is high"},{text:"Evening",type:"correct",logicTag:"sun sets in evening"},{text:"Night",type:"concept_error",logicTag:"after sun sets, dark"}], explanation:"The sun sets in the evening — the sky turns orange/red.", solutionSteps:["Sunset = evening"], shortcut:"Sunset = evening.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_parts_of_day_q3", topicId:"math1_ch6_parts_of_day", text:"It is dark outside and you are sleeping. What part of the day is it?", options:[{text:"Morning",type:"concept_error",logicTag:"morning is light"},{text:"Afternoon",type:"concept_error",logicTag:"afternoon is light"},{text:"Evening",type:"concept_error",logicTag:"evening is not fully dark yet"},{text:"Night",type:"correct",logicTag:"dark and sleeping = night"}], explanation:"Night is when it is dark and we sleep.", solutionSteps:["Dark + sleeping = night"], shortcut:"Dark + sleep = night.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_parts_of_day_q4", topicId:"math1_ch6_parts_of_day", text:"You eat lunch. What part of the day is this?", options:[{text:"Morning",type:"concept_error",logicTag:"breakfast time"},{text:"Afternoon",type:"correct",logicTag:"lunch = afternoon"},{text:"Night",type:"concept_error",logicTag:"dinner time"},{text:"Evening",type:"concept_error",logicTag:"too late for lunch"}], explanation:"Lunch is eaten in the afternoon.", solutionSteps:["Afternoon = lunch, midday"], shortcut:"Lunch = afternoon.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_parts_of_day_q5", topicId:"math1_ch6_parts_of_day", text:"Order these parts of the day from FIRST to LAST: Night, Afternoon, Morning, Evening.", options:[{text:"Night,Morning,Afternoon,Evening",type:"concept_error",logicTag:"wrong order"},{text:"Morning,Afternoon,Evening,Night",type:"correct",logicTag:"correct daily order"},{text:"Afternoon,Morning,Evening,Night",type:"concept_error",logicTag:"wrong"},{text:"Evening,Afternoon,Morning,Night",type:"concept_error",logicTag:"wrong"}], explanation:"A day goes: Morning → Afternoon → Evening → Night.", solutionSteps:["Morning (sunrise) first","Then Afternoon (noon)","Then Evening (sunset)","Then Night (dark)"], shortcut:"M-A-E-N: Morning, Afternoon, Evening, Night.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_parts_of_day_q6", topicId:"math1_ch6_parts_of_day", text:"You go to school. When is this?", options:[{text:"Night",type:"concept_error",logicTag:"sleeping time"},{text:"Evening",type:"concept_error",logicTag:"too late"},{text:"Morning",type:"correct",logicTag:"school starts in morning"},{text:"Afternoon",type:"concept_error",logicTag:"already in school"}], explanation:"School typically starts in the morning.", solutionSteps:["Morning = go to school"], shortcut:"Morning = school time.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_parts_of_day_q7", topicId:"math1_ch6_parts_of_day", text:"What do you look at to know if it is morning or evening?", options:[{text:"The clock alone",type:"partial_logic",logicTag:"clock helps but sun is easier"},{text:"The position and colour of the sky/sun",type:"correct",logicTag:"sky tells the part of day"},{text:"The colour of the walls",type:"concept_error",logicTag:"irrelevant"},{text:"The food on the table",type:"partial_logic",logicTag:"indirect clue only"}], explanation:"The sun's position (rising or setting) and sky colour tell us the part of the day.", solutionSteps:["Rising sun = morning","High sun = afternoon","Orange/setting = evening","Dark = night"], shortcut:"Watch the sky and sun.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_parts_of_day_q8", topicId:"math1_ch6_parts_of_day", text:"How many parts does a day have (morning, afternoon, evening, night)?", options:[{text:"2",type:"concept_error",logicTag:"too few"},{text:"5",type:"concept_error",logicTag:"too many"},{text:"4",type:"correct",logicTag:"4 main parts"},{text:"3",type:"concept_error",logicTag:"one missing"}], explanation:"A day has 4 main parts: morning, afternoon, evening, and night.", solutionSteps:["1. Morning  2. Afternoon","3. Evening  4. Night","Total = 4"], shortcut:"4 parts: M, A, E, N.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },

  // ── Ch6 S3: Reading the Clock (math1_ch6_reading_clock) ──────────────────────
  { questionId:"math1_ch6_reading_clock_q1", topicId:"math1_ch6_reading_clock", text:"The short hand is at 3 and the long hand is at 12. What time is it?", options:[{text:"12 o'clock",type:"concept_error",logicTag:"confused which hand"},{text:"3 o'clock",type:"correct",logicTag:"short hand at 3 + long at 12"},{text:"6 o'clock",type:"concept_error",logicTag:"wrong number"},{text:"9 o'clock",type:"concept_error",logicTag:"wrong number"}], explanation:"Short hand at 3, long hand at 12 → 3 o'clock.", solutionSteps:["Short hand = hour hand","Points to 3","Long hand at 12 = o'clock","Answer: 3 o'clock"], shortcut:"Short hand number + long at 12 = __ o'clock.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_reading_clock_q2", topicId:"math1_ch6_reading_clock", text:"Which hand on the clock tells us the HOUR?", options:[{text:"The long hand",type:"concept_error",logicTag:"long = minutes"},{text:"The second hand",type:"concept_error",logicTag:"seconds not taught yet"},{text:"The short hand",type:"correct",logicTag:"short = hours"},{text:"Both hands",type:"concept_error",logicTag:"each has a role"}], explanation:"The short (hour) hand tells us the hour.", solutionSteps:["Short hand = hour hand","Long hand = minute hand"], shortcut:"Short = hours (H is short).", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_reading_clock_q3", topicId:"math1_ch6_reading_clock", text:"When the long hand points to 12, what kind of time is it?", options:[{text:"Half past",type:"concept_error",logicTag:"half past = long at 6"},{text:"Quarter to",type:"concept_error",logicTag:"not this"},{text:"O'clock",type:"correct",logicTag:"long at 12 = o'clock"},{text:"Unknown",type:"guessing",logicTag:"known"}], explanation:"Long hand at 12 always means o'clock.", solutionSteps:["Long at 12 → o'clock","Check short hand for the hour"], shortcut:"Long at 12 = o'clock.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_reading_clock_q4", topicId:"math1_ch6_reading_clock", text:"The short hand is at 7 and the long hand is at 12. What time is it?", options:[{text:"12 o'clock",type:"concept_error",logicTag:"confused hands"},{text:"7 o'clock",type:"correct",logicTag:"short at 7, long at 12"},{text:"6 o'clock",type:"concept_error",logicTag:"wrong"},{text:"1 o'clock",type:"concept_error",logicTag:"wrong"}], explanation:"Short hand at 7, long hand at 12 → 7 o'clock.", solutionSteps:["Short at 7, long at 12","→ 7 o'clock"], shortcut:"Short hand number = hour.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_reading_clock_q5", topicId:"math1_ch6_reading_clock", text:"At 5 o'clock, where does the long hand point?", options:[{text:"5",type:"concept_error",logicTag:"long hand doesn't point to hour"},{text:"6",type:"concept_error",logicTag:"that's half past"},{text:"12",type:"correct",logicTag:"long at 12 = o'clock always"},{text:"3",type:"concept_error",logicTag:"wrong"}], explanation:"At ANY o'clock time, the long (minute) hand always points to 12.", solutionSteps:["O'clock → long hand at 12","Always, for all o'clock times"], shortcut:"O'clock: long at 12. Always.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_reading_clock_q6", topicId:"math1_ch6_reading_clock", text:"Which hand is SHORTER on a clock?", options:[{text:"The minute hand",type:"concept_error",logicTag:"minute = long"},{text:"Both are the same",type:"concept_error",logicTag:"they are different"},{text:"The hour hand",type:"correct",logicTag:"hour hand is short"},{text:"There is only one hand",type:"concept_error",logicTag:"there are two"}], explanation:"The hour hand is shorter; the minute hand is longer.", solutionSteps:["Hour hand = SHORT","Minute hand = LONG"], shortcut:"HOUR = SHORT. Think: 'h' in 'hour' is short.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_reading_clock_q7", topicId:"math1_ch6_reading_clock", text:"It is 9 o'clock. Which number is the short hand pointing to?", options:[{text:"12",type:"concept_error",logicTag:"that's the long hand"},{text:"6",type:"concept_error",logicTag:"wrong"},{text:"9",type:"correct",logicTag:"9 o'clock → short at 9"},{text:"3",type:"concept_error",logicTag:"wrong"}], explanation:"At 9 o'clock, the short hand points to 9.", solutionSteps:["9 o'clock","Short hand → 9"], shortcut:"Short hand = hour number.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_reading_clock_q8", topicId:"math1_ch6_reading_clock", text:"A clock shows short hand at 12 and long hand at 12. What time is it?", options:[{text:"12 o'clock",type:"correct",logicTag:"both at 12 = 12 o'clock"},{text:"6 o'clock",type:"concept_error",logicTag:"wrong"},{text:"1 o'clock",type:"concept_error",logicTag:"wrong"},{text:"Cannot be a real time",type:"concept_error",logicTag:"it is midnight or noon"}], explanation:"Short at 12, long at 12 → 12 o'clock (noon or midnight).", solutionSteps:["Short at 12 = 12th hour","Long at 12 = o'clock","→ 12 o'clock"], shortcut:"Both at 12 = 12 o'clock.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },

  // ── Ch6 S4: Sequencing Events in Time (math1_ch6_sequencing_events) ──────────
  { questionId:"math1_ch6_sequencing_events_q1", topicId:"math1_ch6_sequencing_events", text:"Getting ready for school: wake up → brush teeth → eat breakfast → go to school. Which happens FIRST?", options:[{text:"Eat breakfast",type:"concept_error",logicTag:"third step"},{text:"Go to school",type:"concept_error",logicTag:"last step"},{text:"Brush teeth",type:"concept_error",logicTag:"second step"},{text:"Wake up",type:"correct",logicTag:"first step"}], explanation:"'First' means the very first thing — waking up comes before all else.", solutionSteps:["First = wake up","Then brush teeth","Then eat","Then school"], shortcut:"First = earliest action.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_sequencing_events_q2", topicId:"math1_ch6_sequencing_events", text:"Planting a seed: plant seed → water it → wait → flower blooms. What happens LAST?", options:[{text:"Plant seed",type:"concept_error",logicTag:"first"},{text:"Water it",type:"concept_error",logicTag:"second"},{text:"Wait",type:"concept_error",logicTag:"third"},{text:"Flower blooms",type:"correct",logicTag:"last"}], explanation:"The flower blooms at the end — after all other steps.", solutionSteps:["Last = flower blooms","It's the final result"], shortcut:"Last = final outcome.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_sequencing_events_q3", topicId:"math1_ch6_sequencing_events", text:"Which word describes what comes right before the LAST step?", options:[{text:"First",type:"concept_error",logicTag:"start"},{text:"Last",type:"concept_error",logicTag:"end"},{text:"Before",type:"partial_logic",logicTag:"okay but vague"},{text:"Then / Next",type:"correct",logicTag:"step before last"}], explanation:"'Then' or 'next' describes the step that comes right before the last one.", solutionSteps:["First → Next/Then → Last","'Then' = second-to-last or middle step"], shortcut:"First → Next → Then → Last.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_sequencing_events_q4", topicId:"math1_ch6_sequencing_events", text:"'Before school' means the event happens ___ school.", options:[{text:"During",type:"concept_error",logicTag:"at the same time"},{text:"After",type:"concept_error",logicTag:"opposite"},{text:"Earlier than",type:"correct",logicTag:"before = earlier"},{text:"Inside",type:"concept_error",logicTag:"not a time word"}], explanation:"'Before' means earlier than — it happens first, then school comes after.", solutionSteps:["Before = happens first","Before school = earlier than school"], shortcut:"Before = earlier than.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_sequencing_events_q5", topicId:"math1_ch6_sequencing_events", text:"Making tea: boil water → add tea → pour in cup → drink. What is the SECOND step?", options:[{text:"Boil water",type:"concept_error",logicTag:"first step"},{text:"Add tea",type:"correct",logicTag:"second step"},{text:"Pour in cup",type:"concept_error",logicTag:"third step"},{text:"Drink",type:"concept_error",logicTag:"last step"}], explanation:"Boil water (first), add tea (second), pour in cup (third), drink (last).", solutionSteps:["1. Boil water","2. Add tea ← SECOND","3. Pour","4. Drink"], shortcut:"Count to the second step.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_sequencing_events_q6", topicId:"math1_ch6_sequencing_events", text:"'After dinner' means the event happens ___ dinner.", options:[{text:"Before",type:"concept_error",logicTag:"opposite"},{text:"During",type:"concept_error",logicTag:"at the same time"},{text:"Later than / following",type:"correct",logicTag:"after = later"},{text:"Without",type:"concept_error",logicTag:"not time-related"}], explanation:"'After' means later than — the event happens following dinner.", solutionSteps:["After = later than","After dinner = when dinner is done"], shortcut:"After = later than.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_sequencing_events_q7", topicId:"math1_ch6_sequencing_events", text:"Reading a book: open book → read page 1 → read page 2 → close book. How many steps are there?", options:[{text:"3",type:"concept_error",logicTag:"one short"},{text:"5",type:"concept_error",logicTag:"one too many"},{text:"2",type:"concept_error",logicTag:"too few"},{text:"4",type:"correct",logicTag:"four steps listed"}], explanation:"Four steps: open, read p1, read p2, close.", solutionSteps:["1. Open 2. Read p1 3. Read p2 4. Close","Total = 4 steps"], shortcut:"Count each arrow → step.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
  { questionId:"math1_ch6_sequencing_events_q8", topicId:"math1_ch6_sequencing_events", text:"Which sequence word means the VERY LAST thing?", options:[{text:"First",type:"concept_error",logicTag:"start"},{text:"Next",type:"concept_error",logicTag:"middle"},{text:"Last / Finally",type:"correct",logicTag:"end"},{text:"Before",type:"concept_error",logicTag:"earlier"}], explanation:"'Last' or 'finally' indicates the final step in a sequence.", solutionSteps:["First = start","Next/Then = middle","Last/Finally = end"], shortcut:"Finally = last step.", difficulty:"easy", subject:"Mathematics", grade:"1", chapter:"6" },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("MongoDB connected");
  for (const q of questions) {
    await Question.findOneAndUpdate({ questionId: q.questionId }, q, { upsert: true, new: true });
    console.log(`  ✓ ${q.questionId}`);
  }
  console.log(`\nSeeded ${questions.length} questions for Class 1 Math v2 (Ch5–Ch6).`);
  await mongoose.disconnect();
}

seed().catch((err) => { console.error(err); process.exit(1); });
